### ISSUE TITLE
configure can't find gss_acquire_cred on Solaris

### ISSUE THREAD

**Issue by vlmarek** [rsyslog/rsyslog#1009]
Hi,

configure:16118: checking for gss_acquire_cred in -lgssapi_krb5
configure:16143: /usr/gcc/4.8/bin/gcc -o conftest -m64 -O3 -std=c99 -m64  
conftest.c -lgssapi_krb5  -ljson-c  >&5
ld: fatal: library -lgssapi_krb5: not found

The problem is that on Solaris this functionality is in libgss and not libgssapi_krb5

I am attaching patch to correct it.

Thank you
__ 
  Vlad

[patch.zip](https://github.com/rsyslog/rsyslog/files/249039/patch.zip)

**Comment by vlmarek** [comment]
Please note that the patch applies to rsyslog 8.15, hopefully it's useful to latest revision too.

Cheers
__
  Vlad

**Comment by rgerhards** [comment]
thx, created PR https://github.com/rsyslog/rsyslog/pull/1015 for it.
