### ISSUE TITLE
several dynstats_* tests fail

### ISSUE THREAD

**Issue by rgerhards** [rsyslog/rsyslog#1011]
This used to work until roughly a week ago. Beginning then, it failed on very slow machines.

I have seen similar problems with other tests. I suspect that the root cause were some package  updates, proabably in valgrind. At least this is where I traced the other issues back to and could solve them by better shutdown procedures inside diag.sh (waiting for pid to actually terminate vs. previously waiting for pidfile to disappear). However, these tests have different failure scenarios, but currently only on the very slow Fedora 23, 32bit box. Here is a sample:

http://build.rsyslog.com:8010/builders/rsyslog%20fedora23x32%20rsyslog/builds/226/steps/shell_3/logs/stdio

On all other platforms, it seems to work now. I admit I really don't know if this is a testbench issue or a real one. After all, the test was changed to do explicit sync. @janmejay What do you think?

**Comment by janmejay** [comment]
Interesting. Will dig this.

On Fri, May 6, 2016 at 1:56 PM, Rainer Gerhards <notifications@github.com>
wrote:

> This used to work until roughly a week ago. Beginning then, it failed on
> very slow machines.
>
> I have seen similar problems with other tests. I suspect that the root
> cause were some package updates, proabably in valgrind. At least this is
> where I traced the other issues back to and could solve them by better
> shutdown procedures inside diag.sh (waiting for pid to actually terminate
> vs. previously waiting for pidfile to disappear). However, these tests have
> different failure scenarios, but currently only on the very slow Fedora 23,
> 32bit box. Here is a sample:
>
>
> http://build.rsyslog.com:8010/builders/rsyslog%20fedora23x32%20rsyslog/builds/226/steps/shell_3/logs/stdio
>
> On all other platforms, it seems to work now. I admit I really don't know
> if this is a testbench issue or a real one. After all, the test was changed
> to do explicit sync. @janmejay <https://github.com/janmejay> What do you
> think?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/rsyslog/rsyslog/issues/1011>
>



-- 
Regards,
Janmejay
http://codehunk.wordpress.com

**Comment by janmejay** [comment]
Does it consistently fail on fedora 32bit box? I want to add some
diagnostics info (hence the question).

On Fri, May 6, 2016 at 5:17 PM, singh.janmejay <singh.janmejay@gmail.com>
wrote:

> Interesting. Will dig this.
>
> On Fri, May 6, 2016 at 1:56 PM, Rainer Gerhards <notifications@github.com>
> wrote:
>
>> This used to work until roughly a week ago. Beginning then, it failed on
>> very slow machines.
>>
>> I have seen similar problems with other tests. I suspect that the root
>> cause were some package updates, proabably in valgrind. At least this is
>> where I traced the other issues back to and could solve them by better
>> shutdown procedures inside diag.sh (waiting for pid to actually terminate
>> vs. previously waiting for pidfile to disappear). However, these tests have
>> different failure scenarios, but currently only on the very slow Fedora 23,
>> 32bit box. Here is a sample:
>>
>>
>> http://build.rsyslog.com:8010/builders/rsyslog%20fedora23x32%20rsyslog/builds/226/steps/shell_3/logs/stdio
>>
>> On all other platforms, it seems to work now. I admit I really don't know
>> if this is a testbench issue or a real one. After all, the test was changed
>> to do explicit sync. @janmejay <https://github.com/janmejay> What do you
>> think?
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/rsyslog/rsyslog/issues/1011>
>>
>
>
>
> --
> Regards,
> Janmejay
> http://codehunk.wordpress.com
>



-- 
Regards,
Janmejay
http://codehunk.wordpress.com

**Comment by rgerhards** [comment]
2016-05-06 13:58 GMT+02:00 Janmejay Singh <notifications@github.com>:

> Does it consistently fail on fedora 32bit box? I want to add some
> diagnostics info (hence the question).
>

I'd say at least 90%. You can base your branch on master, I checked that
the issue is with master before I created this tracker.

Thanks! Rainer

**Comment by janmejay** [comment]
Yes Im on master.

On Fri, May 6, 2016 at 5:29 PM, Rainer Gerhards <notifications@github.com>
wrote:

> 2016-05-06 13:58 GMT+02:00 Janmejay Singh <notifications@github.com>:
>
> > Does it consistently fail on fedora 32bit box? I want to add some
> > diagnostics info (hence the question).
> >
>
> I'd say at least 90%. You can base your branch on master, I checked that
> the issue is with master before I created this tracker.
>
> Thanks! Rainer
>
> >
> > On Fri, May 6, 2016 at 5:17 PM, singh.janmejay <singh.janmejay@gmail.com
> >
> > wrote:
> >
> >
> > > Interesting. Will dig this.
> > >
> > > On Fri, May 6, 2016 at 1:56 PM, Rainer Gerhards <
> > notifications@github.com>
> > > wrote:
> > >
> > >> This used to work until roughly a week ago. Beginning then, it failed
> on
> > >> very slow machines.
> > >>
> > >> I have seen similar problems with other tests. I suspect that the root
> > >> cause were some package updates, proabably in valgrind. At least this
> is
> > >> where I traced the other issues back to and could solve them by better
> > >> shutdown procedures inside diag.sh (waiting for pid to actually
> > terminate
> > >> vs. previously waiting for pidfile to disappear). However, these tests
> > have
> > >> different failure scenarios, but currently only on the very slow
> Fedora
> > 23,
> > >> 32bit box. Here is a sample:
> > >>
> > >>
> > >>
> >
> http://build.rsyslog.com:8010/builders/rsyslog%20fedora23x32%20rsyslog/builds/226/steps/shell_3/logs/stdio
> > >>
> > >> On all other platforms, it seems to work now. I admit I really don't
> > know
> > >> if this is a testbench issue or a real one. After all, the test was
> > changed
> > >> to do explicit sync. @janmejay <https://github.com/janmejay> What do
> > you
> > >> think?
> > >>
> > >> —
> > >> You are receiving this because you were mentioned.
> > >> Reply to this email directly or view it on GitHub
> > >> <https://github.com/rsyslog/rsyslog/issues/1011>
> > >>
> > >
> > >
> > >
> > > --
> > > Regards,
> > > Janmejay
> > > http://codehunk.wordpress.com
> > >
> >
> >
> >
> > --
> > Regards,
> > Janmejay
> > http://codehunk.wordpress.com
> >
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly or view it on GitHub
> > <https://github.com/rsyslog/rsyslog/issues/1011#issuecomment-217421449>
>
> >
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/rsyslog/rsyslog/issues/1011#issuecomment-217421629>
>



-- 
Regards,
Janmejay
http://codehunk.wordpress.com
