### ISSUE TITLE
rsyslog 8.18 "could not activate relp listner" error with imrelp input

### ISSUE THREAD

**Issue by phr0gz** [rsyslog/rsyslog#1016]
Hello, I've one issue when I'm trying to run imrelp with mutual authentication. 
Error message:
"rsyslogd: imrelp: could not activate relp listner, code 10046 [v8.18.0 try http://www.rsyslog.com/e/2291 ]"

 If I use omrelp, I don't have any error...

OS: CentOS 6.7
Installed packages:
libfastjson-0.99.2-1
liblogging-1.0.5-1
rsyslog-8.18.0-1
rsyslog-relp-8.18.0-1
libgt-0.3.11-1
librelp-1.2.10-1
rsyslog-gnutls-8.18.0-1
GnuTLS-2.8.5
libgcrypt-1.4.5-11

Debug Log:
http://pastebin.com/3Q6bKNNz

**Comment by davidelang** [comment]
config file please.

David Lang

**Comment by phr0gz** [comment]
The config file '/etc/conf.d/test.conf':
http://pastebin.com/gGU41XsH

The '/etc/rsyslog.conf' is the default config:
http://pastebin.com/yrwJYGTC

Thx

**Comment by davidelang** [comment]
It's not clear to me why it is failing.

does DNS work for test.lab?

have you tried it without the TLS config?

**Comment by phr0gz** [comment]
The quoted imtcp (with Mutual TLS) quoted in the conf work very well.

And if I change the imrelp part by:
```
input(
  type="imrelp"
  name="imtcp_secure"
  port="10514"
  ruleset="remote_relp_secure_10514"
  tls="on"
  #tls.dhbits="2048"
  #tls.caCert="/etc/ssl/mycerts/syslog-ca-cert.crt"
  #tls.myCert="/etc/ssl/mycerts/syslog-rsyslog-cert.crt"
  #tls.myPrivKey="/etc/ssl/mycerts/syslog-rsyslog-key.key"
  #tls.authMode="name"
  #tls.permittedPeer="*.test.lab"
)
```
It is working

**Comment by rgerhards** [comment]
The platform has a top old gnutls. This is the error code:

define RELP_RET_ERR_NO_TLS_AUTH RELPERR_BASE + 46 /**< platform does not
provide TLS auth support */

We need to enhance our error reporting.

Hth
Rainer

Sent from phone, thus brief.
Am 09.05.2016 21:07 schrieb "phr0gz" <notifications@github.com>:

**Comment by phr0gz** [comment]
ok, thx.
