### ISSUE TITLE
CentOS7 RELP Mutual TLS Handshake failed

### ISSUE THREAD

**Issue by phr0gz** [rsyslog/rsyslog#1045]
Hello, I've one issue when I'm trying to use RELP over tls with mutual authentication.

If I try with gnutls-cli and gnutls-server, the handshake is successful.
###### Error message

`TLS handshake failed [gnutls error -21: Could not negotiate a supported cipher suite.`
###### System

OS: CentOS 7
###### Installed packages

libfastjson-0.99.2-1.el7.x86_64.rpm
libgt-0.3.11-1.el7.x86_64.rpm
liblogging-1.0.5-1.el7.x86_64.rpm
librelp-1.2.10-1.el7.x86_64.rpm
rsyslog-8.18.0-1.el7.x86_64.rpm
rsyslog-gnutls-8.18.0-1.el7.x86_64.rpm
rsyslog-relp-8.18.0-1.el7.x86_64.rpm
GnuTLS-3.3.8-14
###### Diagram

rsyslogE ---Mutual TLS---> rsyslogI ---Mutual TLS---> Logstash
###### Config and log

rsyslogE:
log: http://pastebin.com/xih2H6C0
conf: http://pastebin.com/wRQUQh18

rsyslogI:
log: http://pastebin.com/FrGwAjJ0
conf: http://pastebin.com/arz3GhR2
###### Other tests

from rsyslogE with **gnutls-cli** ---> rsyslogI with **gnutls-serv** ===> Handshake: **OK**
from rsyslogE with **gnutls-cli** ---> rsyslogI with **rsyslog**               ===> Handshake: **OK**
from rsyslogE with **rsyslog** ---> rsyslogI with **gnutls-serv**    ===> Handshake: **NOK**
###### Command used for gnutls-cli and gnutls-serv

Client:
`gnutls-cli -d 10 -r -p 10514 rsyslogi.test.lab --x509cafile /etc/ssl/mycerts/syslog-ca-cert.crt --x509keyfile /etc/ssl/mycerts/syslog-client-key.key --x509certfile /etc/ssl/mycerts/syslog-client-cert.crt --priority "SECURE128:-AES-128-CBC:-CAMELLIA-128-CBC:-VERS-SSL3.0:-VERS-TLS1.0"`

Server:
`gnutls-serv -d 10 -r -p 10514 --x509cafile /etc/ssl/mycerts/syslog-ca-cert.crt --x509keyfile /etc/ssl/mycerts/syslog-rsyslog-key.key --x509certfile /etc/ssl/mycerts/syslog-rsyslog-cert.crt --priority "SECURE128:-AES-128-CBC:-CAMELLIA-128-CBC:-VERS-SSL3.0:-VERS-TLS1.0"`

**Comment by alorbach** [comment]
Files have been removed. Does this problem still exist?

**Comment by phr0gz** [comment]
thx, I'll try and give you a feedback next week.

**Comment by phr0gz** [comment]
Same problem:
debugged with:
Server:
gnutls-serv -d 10 -r -p 10514 --x509cafile /etc/ssl/mycerts/syslog-ca-cert.crt --x509keyfile /etc/ssl/mycerts/syslog-rsyslog-key.key --x509certfile /etc/ssl/mycerts/syslog-rsyslog-cert.crt --priority "SECURE128:-AES-128-CBC:-CAMELLIA-128-CBC:-VERS-SSL3.0:-VERS-TLS1.0"

Client: rSyslog with librelp-1.2.11-1.el7.x86_64, (I just made an update of the rpm)

I've tried with (see additinal line bellow) and without forcing the ciphers: 
tls.prioritystring="SECURE128:-AES-128-CBC:-CAMELLIA-128-CBC:-VERS-SSL3.0:-VERS-TLS1.0"

rSyslog debug:
without forcing ciphers: http://pastebin.com/xPBhdvdD
with tls.prioritystring: http://pastebin.com/j6gdiwFv

**Comment by phr0gz** [comment]
And with:

Client: rSyslog with librelp-1.2.12-1.el7.x86_64, (I just made an update with the rpm)

I've just tried with,
tls.prioritystring="SECURE128:-AES-128-CBC:-CAMELLIA-128-CBC:-VERS-SSL3.0:-VERS-TLS1.0"


rSyslog debug:
with tls.prioritystring: http://pastebin.com/2fUhsN53

**Comment by phr0gz** [comment]
I just tested and it is working now on v8.31 with librelp-1.2.14-1.
