### ISSUE TITLE
Missing docs

### ISSUE THREAD

**Issue by szepeviktor** [rsyslog/rsyslog#1049]
Good afternoon!

/doc and http://www.rsyslog.com/doc is missing as well.
Please advise.

**Comment by szepeviktor** [comment]
Found /doc https://github.com/rsyslog/rsyslog-doc
Will rsyslog.com be updated?

**Comment by rgerhards** [comment]
The /doc link should work, we will look into fixing it (it's supposed to be a redirect).

**Comment by rgerhards** [comment]
This seems to have been a temporary glitch caused by a server change. If it still persists, please check again later today. I have tried from multiple locations (Europe and US) and it now works again well.

**Comment by szepeviktor** [comment]
Thanks.
