### ISSUE TITLE
Debian 7 Jessie Suppport

### ISSUE THREAD

**Issue by joeyisking** [rsyslog/rsyslog#1053]
Does rsyslog work with newer versions of Debian, Documentation here: http://www.rsyslog.com/debian-repository/ suggests it only working for wheezy

Jessie uses an older version of rsyslog (8.4) and I'm looking to upgrade it to at least 8.5 so I can use wildcards with imfile

**Comment by rgerhards** [comment]
The link is in regard to which packages are build by the rsyslog project. rsyslog works on all versions, at most you need to build it from source.
