### ISSUE TITLE
Infinite loop when rsyslog allows for including an already include config file

### ISSUE THREAD

**Issue by portante** [rsyslog/rsyslog#1058]
From FreeNode's #rsyslog channel, June 5th, 02:04 UTC:

```
TrevorH: I've just been assisting someone with an rsyslog problem where it was eating all available ram and being killed by the OOM killer. It turns out he was an idiot and had copied /etc/rsyslog.conf into /etc/rsyslog.d and his rsyslog.conf had an $includeconfig /etc/rsyslog.d/*.conf
TrevorH: so the copy of rsyslog.conf in the include dir had another includeconfig for itself...
TrevorH: I suspect that allowing an include that includes the file that's doing the include is not a wide idea
TrevorH: wise even
```

**Comment by davidelang** [comment]
On Sat, 4 Jun 2016, Peter Portante wrote:

> From FreeNode's #rsyslog channel, June 5th, 02:04 UTC:
>
> ```
> TrevorH: I've just been assisting someone with an rsyslog problem where it was eating all available ram and being killed by the OOM killer. It turns out he was an idiot and had copied /etc/rsyslog.conf into /etc/rsyslog.d and his rsyslog.conf had an $includeconfig /etc/rsyslog.d/*.conf
> TrevorH: so the copy of rsyslog.conf in the include dir had another includeconfig for itself...
> TrevorH: I suspect that allowing an include that includes the file that's doing the include is not a wide idea
> TrevorH: wise even
> ```

Allowing it in the config file spec is a good idea. It's not always a good idea 
to use the feature, but in some cases it can be extremely valuable.

Personally, I generally try to avoid using includes at all, but sometimes they 
can greatly simplify the management of your systems.

David Lang

**Comment by TrevorPH** [comment]
The problem is not the include itself, it's the loop that occurs if you include the same directory containing the file with the $IncludeConfig in it. I agree that being able to include all files in a directory is a good idea and it's one that's popular with distros. So in a standard config where /etc/rsyslog.conf has $IncludeConfig /etc/rsyslog.d/*.conf, doing

echo '$IncludeConfig /etc/rsyslog.d/*.conf' > /etc/rsyslog.d/breakme.conf

and restarting rsyslog is enough to cause an OOM error and prevent rsyslog from starting.

Yes, I agree it's idiotic and shouldn't be done but it still shouldn't stop rsyslog from starting and nor should it loop eating all available memory.

**Comment by davidelang** [comment]
On Sun, 5 Jun 2016, TrevorPH wrote:

> The problem is not the include itself, it's the loop that occurs if you include the same directory containing the file with the $IncludeConfig in it. I agree that being able to include all files in a directory is a good idea and it's one that's popular with distros. So in a standard config where /etc/rsyslog.conf has $IncludeConfig /etc/rsyslog.d/*.conf, doing
>
> echo '$IncludeConfig /etc/rsyslog.d/*.conf' > /etc/rsyslog.d/breakme.conf
>
> and restarting rsyslog is enough to cause an OOM error and prevent rsyslog from starting.
>
> Yes, I agree it's idiotic and shouldn't be done but it still shouldn't stop rsyslog from starting and nor should it loop eating all available memory.

Well, I would expect it to use all the available memory, just like if you gave 
rsyslog a config file larger than your ram (whichis what you are doing)

now, it would be nice to add loop detection to the include, but I dont' know how 
hard it would be. detecting that you are including the file that has the include 
in it is relatively easy, but detecting an include chain that's several files 
deep is much more work.

David Lang

**Comment by rgerhards** [comment]
I had a quick look, and it is fairly easy to detect.
