### ISSUE TITLE
imklog: add ruleset support

### ISSUE THREAD

**Issue by trefalgar** [rsyslog/rsyslog#106]
module(load="imuxsock" ruleset="kernel") -- generates error, unknown option ruleset
input(type="imuxsock" ruleset="kernel") -- generates error about no socket, and unknown option ruleset
input(type="imklog" ruleset="kernel") -- generates error that imklog doesn't support "input"

It appears the only method for processing these modules is via the default ruleset.

**Comment by otisg** [comment]
One more +1 for this.

**Comment by donaldguy** [comment]
This bit me as well

**Comment by sapiophile** [comment]
I would like to have it too.

**Comment by atombender** [comment]
+1.

**Comment by huangyg11** [comment]
+1

**Comment by rgerhards** [comment]
splitting imuxsock off to its own issue: https://github.com/rsyslog/rsyslog/issues/765

**Comment by darue-keller** [comment]
FYI the Documentation clearly lists **ruleset** as an option for **input(type=imuxsock**

Of course I'm only using 8.12.0 (thanks ubuntu 15.10!)

**Comment by rgerhards** [comment]
This tracker is for imklog; in the correct one #765 you see that it is implemented in 8.17.0.

**Comment by rgerhards** [comment]
imuxsock was already implemented, imklog via #4356, so this is finally closed.
