### ISSUE TITLE
rsyslog 8.18 imtcp PermittedPeer wildcard regression

### ISSUE THREAD

**Issue by JFC2** [rsyslog/rsyslog#1063]
We have upgraded from rsyslog 8.10 to 8.18 a few days ago.
We have noticed a regression at runtime with our configuration of imtcp module.
We setup TLS with permitted peers using wildcard to ease the configuration (many permitted hosts).
The configuration working with 8.10 is as below :

```
    module( load="imtcp"
        # Set the maximum number of sessions supported
        MaxSessions="500"
        # TLS protected operation
        StreamDriver.Mode="1"
        # Certificate validation and subject name authentication
        StreamDriver.AuthMode="x509/name"
        # Set permitted peers
        PermittedPeer=["*.domain.com"]
)
```

Unfortunately, this is no more working with rsyslog 8.18.
We found the following message in debug log of rsyslog :

> "error: peer name not authorized -  not permitted to talk to it"

We have bypassed the problem by providing the full list of permitted peers FQDN, like this :

```
        ...
        PermittedPeer=["host1.domain.com","host2.domain.com","host3.domain.com"]
        ...
```

But for us, this is not a viable solution.
Is it really an issue or a deliberate change in the behavior or rsyslog ?
I didn't find any information in release note, monitorware KB or rsyslog github about that.
Would it be possible to get back to the previous behavior with wildcard ?

**Comment by alorbach** [comment]
Should be fixed by now. Wildcards for permittedpeers are checked in tls drivers.
