### ISSUE TITLE
logger to rsyslogd via tcp fail

### ISSUE THREAD

**Issue by haoren3696** [rsyslog/rsyslog#1065]
Hi, I have met the same problem with https://github.com/rsyslog/rsyslog/issues/823, but i see no result of this closed issue, where can i get some clue?

**Comment by haoren3696** [comment]
I have found the reason!

testing way:
success:echo “<190>Jun 14 16:39:48 root: hello world”|nc 9.43.1.15 514
fail:logger --tcp --server 9.43.1.15  --port 514 --priority local7.info hello world

the rsyslog drop the message sent from logger because logger util append \0 to the message while nc append \n to the message.

tcps_sess.c
                ```
if((   ((c == '\n') && !pThis->pSrv->bDisableLFDelim)
                   || ((pThis->pSrv->addtlFrameDelim != TCPSRV_NO_ADDTL_DELIMITER) && (c == pThis->pSrv->addtlFrameDelim))
                   ) && pThis->eFraming == TCP_FRAMING_OCTET_STUFFING) { /* record delimiter? */
                        defaultDoSubmitMessage(pThis, stTime, ttGenTime, pMultiSub);
                        pThis->inputState = eAtStrtFram;
```

rsyslog only accept message end with \n in tcp way.

here is the same problem met in util-linux:
https://github.com/karelzak/util-linux/issues/225

update the logger util and the problem solved, but I think maybe rsyslog can do something to adapt old logger.:)

**Comment by davidelang** [comment]
On Tue, 14 Jun 2016, Xie Zhipeng wrote:

> rsyslog only accept message end with \n in tcp way.
>
> here is the same problem met in util-linux:
> https://github.com/karelzak/util-linux/issues/225
>
> update the logger util and the problem solved, but I think maybe rsyslog can do something to adapt old logger.:)

Well, if people won't upgrade logger to a new version to solve the problem, what 
makes you think that they will upgrade rsyslog? :-)

Although I agree that rsyslog should take the closing of a connection as the end 
of a message, even if there wasn't a \n just before it.

David Lang

**Comment by rgerhards** [comment]
Sent from phone, thus brief.
Am 14.06.2016 19:19 schrieb "davidelang" <notifications@github.com>:
>
> On Tue, 14 Jun 2016, Xie Zhipeng wrote:
>
> > rsyslog only accept message end with \n in tcp way.
> >
> > here is the same problem met in util-linux:
> > https://github.com/karelzak/util-linux/issues/225
> >
> > update the logger util and the problem solved, but I think maybe
rsyslog can do something to adapt old logger.:)
>
> Well, if people won't upgrade logger to a new version to solve the
problem, what
> makes you think that they will upgrade rsyslog? :-)
>
> Although I agree that rsyslog should take the closing of a connection as
the end
> of a message, even if there wasn't a \n just before it.

That was a bug that is fixed now (at least so I remember)

Rainer

**Comment by haoren3696** [comment]
> That was a bug that is fixed now (at least so I remember)

Could you give me a commit id?

**Comment by davidelang** [comment]
> Could you give me a commit id?

not likely without a bunch of digging. just too many releases between then and 
now.

David Lang
