### ISSUE TITLE
Centos 6.4 upgraded rsyslogd 8.19.0 audit.log alert "denied  { read } "

### ISSUE THREAD

**Issue by laiyongmao** [rsyslog/rsyslog#1067]
HI:
   I upgraded the rsyslog to the audit.log and then started to make a mistake.My host information is as follow:
```
[root@es01 etc]# uname -a
Linux es01 2.6.32-358.el6.x86_64 #1 SMP Fri Feb 22 00:31:26 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux
[root@es01 etc]# rsyslogd -v
rsyslogd 8.19.0, compiled with:
        PLATFORM:                               x86_64-redhat-linux-gnu
        PLATFORM (lsb_release -d):
        FEATURE_REGEXP:                         Yes
        GSSAPI Kerberos 5 support:              No
        FEATURE_DEBUG (debug build, slow code): No
        32bit Atomic operations supported:      Yes
        64bit Atomic operations supported:      Yes
        memory allocator:                       system default
        Runtime Instrumentation (slow code):    No
        uuid support:                           Yes
        Number of Bits in RainerScript integers: 64
[root@es01 etc]# getenforce
Enforcing
[root@es01 etc]# vi /etc/rsyslog.conf
     26 global(workDirectory="/var/spool/rsyslog/spool")
     27 module(load="imfile" )
     28 ruleset(name="infiles") {
     29         action(type="omfwd"
     30         target="192.168.1.167"
     31         protocol="udp" port="514" )
     32 }
     33 input(type="imfile"
     34         File="/var/log/audit/audit.*"
     35         Tag="audit    "
     36         Severity="error"
     37         Facility="local0"
     38         Ruleset="infiles")
```
And my host is not allowed to modify SELinux,I have modified the rsyslog tag,follow:
```
[root@es01 etc]# ls -Z|grep rsyslog
-rw-r--r--. root  root  system_u:object_r:syslog_conf_t:s0 rsyslog.conf
drwxr-xr-x. root  root  system_u:object_r:etc_t:s0       rsyslog.d
```
Then,there's infomations in  /var/log/audit/audit.log:
```
type=AVC msg=audit(1466129319.255:276355751): avc:  denied  { read } for  pid=20441 comm="in:imfile" path="inotify" dev=inotifyfs ino=1 scontext=unconfined_u:system_r:syslogd_t:s0 tcontext=system_u:object_r:inotifyfs_t:s0 tclass=dir
type=SYSCALL msg=audit(1466129319.255:276355751): arch=c000003e syscall=0 success=no exit=-13 a0=4 a1=7fcb13ffc930 a2=2000 a3=0 items=0 ppid=1 pid=20441 auid=0 uid=0 gid=0
euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=754 comm="in:imfile" exe="/sbin/rsyslogd" subj=unconfined_u:system_r:syslogd_t:s0 key=(null)
type=AVC msg=audit(1466129319.255:276355752): avc:  denied  { read } for  pid=20441 comm="in:imfile" path="inotify" dev=inotifyfs ino=1 scontext=unconfined_u:system_r:syslogd_t:s0 tcontext=system_u:object_r:inotifyfs_t:s0 tclass=dir
```

I want to know what I need to do to solve this problem,thanks.

**Comment by davidelang** [comment]
On Thu, 16 Jun 2016, laiyongmao wrote:

> HI:
>   I upgraded the rsyslog to the audit.log and then started to make a mistake.My host information is as follow:
> ```
> [root@es01 etc]# uname -a
> Linux es01 2.6.32-358.el6.x86_64 #1 SMP Fri Feb 22 00:31:26 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux
> [root@es01 etc]# rsyslogd -v
> rsyslogd 8.19.0, compiled with:
>        PLATFORM:                               x86_64-redhat-linux-gnu
>        PLATFORM (lsb_release -d):
>        FEATURE_REGEXP:                         Yes
>        GSSAPI Kerberos 5 support:              No
>        FEATURE_DEBUG (debug build, slow code): No
>        32bit Atomic operations supported:      Yes
>        64bit Atomic operations supported:      Yes
>        memory allocator:                       system default
>        Runtime Instrumentation (slow code):    No
>        uuid support:                           Yes
>        Number of Bits in RainerScript integers: 64
> [root@es01 etc]# getenforce
> Enforcing
> [root@es01 etc]# vi /etc/rsyslog.conf
>     26 global(workDirectory="/var/spool/rsyslog/spool")
>     27 module(load="imfile" )
>     28 ruleset(name="infiles") {
>     29         action(type="omfwd"
>     30         target="192.168.1.167"
>     31         protocol="udp" port="514" )
>     32 }
>     33 input(type="imfile"
>     34         File="/var/log/audit/audit.*"
>     35         Tag="audit    "
>     36         Severity="error"
>     37         Facility="local0"
>     38         Ruleset="infiles")
> ```
> And my host is not allowed to modify SELinux,I have modified the rsyslog tag,follow:
> ```
> [root@es01 etc]# ls -Z|grep rsyslog
> -rw-r--r--. root  root  system_u:object_r:syslog_conf_t:s0 rsyslog.conf
> drwxr-xr-x. root  root  system_u:object_r:etc_t:s0       rsyslog.d
> ```
> Then,there's infomations in  /var/log/audit/audit.log:
> ```
> type=AVC msg=audit(1466129319.255:276355751): avc:  denied  { read } for  pid=20441 comm="in:imfile" path="inotify" dev=inotifyfs ino=1 scontext=unconfined_u:system_r:syslogd_t:s0 tcontext=system_u:object_r:inotifyfs_t:s0 tclass=dir
> type=SYSCALL msg=audit(1466129319.255:276355751): arch=c000003e syscall=0 success=no exit=-13 a0=4 a1=7fcb13ffc930 a2=2000 a3=0 items=0 ppid=1 pid=20441 auid=0 uid=0 gid=0
> euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=754 comm="in:imfile" exe="/sbin/rsyslogd" subj=unconfined_u:system_r:syslogd_t:s0 key=(null)
> type=AVC msg=audit(1466129319.255:276355752): avc:  denied  { read } for  pid=20441 comm="in:imfile" path="inotify" dev=inotifyfs ino=1 scontext=unconfined_u:system_r:syslogd_t:s0 tcontext=system_u:object_r:inotifyfs_t:s0 tclass=dir
> ```
>
> I want to know what I need to do to solve this problem,thanks.

Well, if SELinux is denying access to read the directory and you aren't allowed 
to modify the SELinux permissions on that directory, I don't know what could be 
done.

David Lang

**Comment by rgerhards** [comment]
This is an admin-question, not for the devs. I suggest to try the rsyslog mailing list.

**Comment by laiyongmao** [comment]
thanks,i will try.
