### ISSUE TITLE
Need CA file when both sender and receiver skip authentication 

### ISSUE THREAD

**Issue by haoren3696** [rsyslog/rsyslog#1068]
runtime/nsd_gtls.c

```
    /* sets the trusted cas file */
    cafile = glbl.GetDfltNetstrmDrvrCAF();
    if(cafile == NULL) {
        errmsg.LogError(0, RS_RET_CA_CERT_MISSING, "error: ca certificate is not set, cannot "
                "continue");
        ABORT_FINALIZE(RS_RET_CA_CERT_MISSING);
    }
```

Although it is a NOT RECOMMENDED case in RFC5425,
https://tools.ietf.org/html/rfc5425#page-10

 it seems that we have no need to configure the CA file when using TLS module in this case.

**Comment by alorbach** [comment]
Support for anon ciphers could be added and then we could remove the need to have CA, Cert and Key being configured. 

But thats an enhancement.

**Comment by rgerhards** [comment]
implemented via https://github.com/rsyslog/rsyslog/pull/3430
