### ISSUE TITLE
RPM EL 7 Repository for stable 8 release broken

### ISSUE THREAD

**Issue by schlitzered** [rsyslog/rsyslog#1088]
http://rpms.adiscon.com/v8-stable/epel-7/x86_64/RPMS/ currently provides a libfastjson-0.99.3-1.el7.x86_64 package, that delivers libfastjson.so.4, but rsyslog requires  libfastjson.so.3 which is provided by libfastjson-0.99.2-1.el7.x86_64

this breaks yum update:

```
yum update -y
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
Resolving Dependencies
--> Running transaction check
---> Package libfastjson.x86_64 0:0.99.2-1.el7 will be updated
--> Processing Dependency: libfastjson.so.3()(64bit) for package: rsyslog-8.19.0-1.el7.x86_64
---> Package libfastjson.x86_64 0:0.99.3-1.el7 will be an update
--> Finished Dependency Resolution
Error: Package: rsyslog-8.19.0-1.el7.x86_64 (@EL7_Rsyslog8)
           Requires: libfastjson.so.3()(64bit)
           Removing: libfastjson-0.99.2-1.el7.x86_64 (@EL7_Rsyslog8)
               libfastjson.so.3()(64bit)
           Updated By: libfastjson-0.99.3-1.el7.x86_64 (EL7_Rsyslog8)
              ~libfastjson.so.4()(64bit)
           Available: libfastjson-0.99.0-1.el7.x86_64 (EL7_Rsyslog8)
               libfastjson.so.3()(64bit)
           Available: libfastjson-0.99.1-1.el7.x86_64 (EL7_Rsyslog8)
               libfastjson.so.3()(64bit)
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
```

pleas ether remove libfastjson-0.99.3-1.el7.x86_64 or make rsyslog use libfastjson.so.4 instead of libfastjson.so.3

i would also suggest, that your adjust you packaging, so that two major versions of libraries can be installed side by side.

for example call the packages like this:
libfastjson3-0.99.2-1.el7.x86_64
libfastjson4-0.99.3-1.el7.x86_64
or something like this...

Regards

**Comment by rgerhards** [comment]
Thanks for the info. I have just talked to our packaging guys. For now, we will remove the newer versions and revalute the package build process.

**Comment by rgerhards** [comment]
They have been removed.
