### ISSUE TITLE
Provide Ubuntu 16.04 PPA rsyslog packages

### ISSUE THREAD

**Issue by jeanpaulgalea** [rsyslog/rsyslog#1089]
Hello,

Would it be possible to provide rsyslog packages for Ubuntu 16.04 (xenial) through your Ubuntu PPA?

https://launchpad.net/~adiscon/+archive/ubuntu/v8-stable?field.series_filter=xenial
https://launchpad.net/~adiscon/+archive/ubuntu/v8-stable?field.series_filter=trusty

Not all packages which are built on trusty are built on xenial - you can see the diff from the links above.

Thank you.

**Comment by rgerhards** [comment]
This should have been reported against the rsyslog-ubuntu-pkg project. Anyhow, it has been done some time ago :-)

**Comment by jeanpaulgalea** [comment]
Sorry, I'll keep that in mind next time. Thanks for providing packages!
