### ISSUE TITLE
Send syslogs throw namespace

### ISSUE THREAD

**Issue by arch1tect0r** [rsyslog/rsyslog#1103]
I want to send syslogs to a server, the route for which is available in a Linux namespace (netns).
Is there any config option in rsyslog, to specify namespaces ? 

Thanks!

**Comment by rgerhards** [comment]
This question is better asked on the mailing list, but I would say "no".

**Comment by davidelang** [comment]
Namespaces would be managed outside of rsyslog. If rsyslog is running inside a 
namespace, it will get the routes for that namespace. If it's not running inside 
that namespace, Rsyslog has no way to change the namespace it's running in.

Run a separate copy of rsyslog in the namespace.

David Lang
