### ISSUE TITLE
rsyslog stop working when imjournal.state is empty

### ISSUE THREAD

**Issue by haoren3696** [rsyslog/rsyslog#1104]
Hi, I met a problem after I reboot my system. Rsyslog does not log any logs after the reboot while the systemd-journald is working normally. It seems imjournal stop reading logs from journal files. Even when I restart rsyslog, It still can not work.
Here is the log:

```
Jul 28 14:51:28 localhost rsyslogd: [origin software="rsyslogd" swVersion="7.4.7" x-pid="41570" x-info="http://www.rsyslog.com"] exiting on signal 15.
Jul 28 14:51:28 localhost rsyslogd: [origin software="rsyslogd" swVersion="7.4.7" x-pid="41705" x-info="http://www.rsyslog.com"] start
Jul 28 14:51:28 localhost rsyslogd-2027: imjournal: fscanf on state file `/var/lib/rsyslog/imjournal.state' failed
 [try http://www.rsyslog.com/e/2027 ]
```

the imjournal.state is empty

```
[root@localhost ~]# ll /var/lib/rsyslog/imjournal.state 
-rw-r--r--. 1 root root 0 Jul 28 14:48 /var/lib/rsyslog/imjournal.state
```

It seems that the cursor did not write to imjournal.state successfully （Maybe there was no enough time for system to flush cache to disk）during the system powering down, 

for now, I change the state file path to /run/log/imjournal.state to avoid the problem, because in my system journal files store in /run which is a tmpfs. After reboot, journal files lost and rsyslog has no need to read outdated cursor in state file.

However, if I choose to store journal in /var, the problem still exist. Does anyone known howto fix the problem in this situation?

**Comment by radosroka** [comment]
I would say that,  this PR #1317 resolves your problem.

**Comment by rgerhards** [comment]
fixed in 8.24.0

**Comment by avlaanderen** [comment]
My system wasn't logging to /var/log/messages anymore with "imjournal: fscanf on state file `/var/lib/rsyslog/imjournal.state' failed"

Tried changing properties for the file /var/lib/rsyslog/imjournal.state to 777 - no success
Then moved it to /var/lib/rsyslog/imjournal.state.old and restarted service rcsyslog.
Back on track

**Comment by jgerhards** [comment]
This is a really old issue - what version of rsyslog are you currently using? If it is a newer one, please consider opening a new issue.

**Comment by davidelang** [comment]
On Thu, 11 Oct 2018, avlaanderen wrote:

> Running CentOS 7.4, so very recent :)

The version of rsyslog shipped with CentOSRedhat is typically pretty old, The 
current version of rsyslog is 8.38, what version of rsyslog are you running?

David Lang
