### ISSUE TITLE
changelog on the website does not mention 8.19 or 8.20

### ISSUE THREAD

**Issue by JonZeolla** [rsyslog/rsyslog#1106]
I was looking at the changelog today and can't find the information regarding 8.19 and 8.20.  Specifically, I am looking at http://www.rsyslog.com/changelog/ - I am aware that the changelog [here](https://github.com/rsyslog/rsyslog/blob/master/ChangeLog) has been updated.

**Comment by rgerhards** [comment]
The web site no longer duplicates the ChangeLog.

**Comment by rgerhards** [comment]
I have redirected the old web content to the real ChangeLog. Thx.
