### ISSUE TITLE
Sometimes rsyslog will automatically stop

### ISSUE THREAD

**Issue by zhou-mfk** [rsyslog/rsyslog#1107]
Hi
I have a problem about imfile module.
my rsyslog configure as follows:
# cat my.conf

ruleset(name="tomcatlog") {
    if not ($msg contains "DEBUG") then {
        action(type="omfwd"
            Protocol="udp"
            Target="10.201.64.145"
            Template="IpTemplate"
            Port="1519"
        )
    }
    stop
}
input(type="imfile"
    File="/opt/app/server/apache-tomcat-21080/logs/catalina.out"
    Tag="web_log"
    PersistStateInterval="1000"
    reopenOnTruncate="on"
    addMetadata="on"  
    startmsg.regex="[A-Fa-f0-9]{8}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{12}(.*)[0-9]{4}(-[0-9]{2}){2}"
    Ruleset="tomcatlog"
)
# 

/opt/app/server/apache-tomcat-21080/logs/catalina.out 
The Tomcat log file is increasing very fast.

sometimes rsyslog will automatically stop .
 log file:/var/log/message  no Error log
# dmesg

rsyslogd[26699] trap divide error ip:7f1acbcae7ea sp:7ffeff299820 error:0 in rsyslogd[7f1acbc78000+95000]
in:imfile[26725] trap divide error ip:7f494e3b67ea sp:7f494b50f480 error:0 in rsyslogd[7f494e380000+95000]
# 

Please help me analyze what is the reason.
Thanks!

**Comment by mostolog** [comment]
Hi.

Could you run syslog with debug flag and paste the result here **enclosed with markdown syntax** \`\`\` \`\`\`? (rsyslogd -dn)
Could you compile with --enable-debug set on configure, execute it using gdb and paste result also?
```
gdb /usr/sbin/rsyslogd
...
(gdb) run -n
...
(gdb) thread apply all bt full
...
```

Thanks

**Comment by davidelang** [comment]
Also, what version are you running, versions 8.19 and earlier were using the json-c library which we know had serious threading problems that caused corruption and segfaults.
