### ISSUE TITLE
Problem: Persistent when using memory queue.

### ISSUE THREAD

**Issue by danieldingzju** [rsyslog/rsyslog#1114]
I'v read the introduction related with rsyslog, and it said that rsyslog can persist the data in memory when server was unfortunately shutdown. Then I tried to read the source code and wanted to found how it works, finally I found the code below:
![image](https://cloud.githubusercontent.com/assets/1768553/17476636/981626b6-5d93-11e6-80f1-bcd7d5e7316c.png)

I just cannot understand how the local variable **pThis** object related to the parameter **ppThis** ???

@rgerhards

**Comment by mostolog** [comment]
@rgerhards As a code curiosity, I would also like to know how these objects are related.

**Comment by rgerhards** [comment]
check the ```OBJCONSTRUCT_CHECK_SUCCESS_AND_CLEANUP``` macro.

**Comment by mostolog** [comment]
Although I understand what the macro does (appending that bunch of code to each function _tail_), I don't get why it does it that way. Wouldn't it be simpler to use *pthis as function argument and return &this? (Probably this is more a ML conversation, though)

**Comment by rgerhards** [comment]
could be for the mailing list. All functions return either void (if it is extremely unlikely that the'll ever fail) or a status code. So you cannot return pThis, this is already used for the status code.
