### ISSUE TITLE
various compiler warnings (with GCC 6)

### ISSUE THREAD

**Issue by mbiebl** [rsyslog/rsyslog#1115]
This is not a targetted issue. With GCC 6 I get a couple of compiler warnings which might be worth looking into. Attached as build.txt

[build.txt](https://github.com/rsyslog/rsyslog/files/414801/build.txt)

**Comment by mostolog** [comment]
Today's build just raised a warning about _asprintf_, being discussed on mail list.

@radu-gheorghe  @rgerhards If you are working with a local copy, please consider using regex to **find and replace all places where an if without curly braces are being used** as a good practice. https://blog.codecentric.de/en/2014/02/curly-braces/

Please, close!

**Comment by rgerhards** [comment]
This should be solved for a while, closing.
