### ISSUE TITLE
rsyslog logs violate RFC5424

### ISSUE THREAD

**Issue by fruetschi** [rsyslog/rsyslog#1120]
Here is an example of a logline of rsyslog 8.20.0 when it starts up.

<46>1 2016-08-18T10:35:20.662120+00:00 MYHOSTNAME rsyslogd - - - [origin software="rsyslogd" swVersion="8.20.0" x-pid="21741" x-info="http://www.rsyslog.com"] start message:[origin software="rsyslogd" swVersion="8.20.0" x-pid="21741" x-info="http://www.rsyslog.com"] start

According to RFC5424 the message should look like this

      SYSLOG-MSG      = HEADER SP STRUCTURED-DATA [SP MSG]

      HEADER          = PRI VERSION SP TIMESTAMP SP HOSTNAME
                        SP APP-NAME SP PROCID SP MSGID

PRI, VERSION, TIMESTAMP, HOSTNAME, APP-NAME are given, PROCID and MSGID is NIL and then there is a third "-" which sets STRUCTURED-DATA to NIL but there is structured data given in the message. Therefore it is shifted to MSG and not correctly interpreted by subsequent systems receiving this logline.

**Comment by rgerhards** [comment]
Well, while **this specific message** looks like structured data, it actually is **not**. It is part of the MSG content, albeit mimiced like a draft version of RFC5424 (note for example the x-pid field which would be a structured data violation). So actually everything is correct.
