### ISSUE TITLE
crash on shutdown with nested rulesets

### ISSUE THREAD

**Issue by janmejay** [rsyslog/rsyslog#1122]
Here is what happens:
- We terminate all rulesets, we do it in a certain order (this is order of cnfDoObj is called, which is config parsing order)
- Its possible to have a scenario similar to this: 
  ```
  ruleset(name="foo") {
  set $.x = re_extract($hostname, '^(._)-[0-9]+$', 0, 1, '_none*');
  ...
  }

  ruleset(name="bar" queue.size="10000" queue.type="LinkedList" queue.workerthreads="2" 
  queue.discardmark="9900") {
  ...
  call foo
  ...
  }
  ```
- Now, termination leads to foo being destroyed before bar, which means statements in foo-ruleset are destroyed, rainerscript functions (funcdata etc) are all destroyed etc.
- Because bar is still not destroyed and we come to it next, if it has some messages in its queue, it tries to process them, which leads to the crash when it calls into foo.

Various solutions are possible:
- Simplest is to check for termination(glbl.GetGlobalInputTermState() etc) before calling into another ruleset (but this is the most naive too, because then ruleset-queue timeouts etc won't work as expected)
- We can re-look at shutdown sequence, where we turn off inputs first and then wait for a single value of timeout (global timeout config) before we destroy rulesets and actions. Once inputs are turned-off, the longer we leave it running, the more messages it will drain out (assuming actions not suspended for some reason). We don't destroy anything in this duration, so messages can go around queue to queue without any problem, except new messages will not enter the system. Along with this, we report per-queue level what number of messages were still present when we actually started destruction. When destruction starts, we use term-state check at every ruleset call and action invocation boundary and discard any messages trying to cross the boundary.  This is not a problem because user has choice to configure quiesce-period for inputs. This does away with queue level drain-timeouts.
- We keep queue-level timeouts for termination but topo-sort by out ruleset inter-dependency. We destroy rulesets in dependent-before-dependency order. (This is the most backward compatibility friendly way by far, I guess?).

Thoughts?

**Comment by janmejay** [comment]
I will fix it, but can't work on it immediately (it'll take me 2 - 3 weeks to get to this). 

I hope that is OK, because the easy workaround is to never define a dependency before dependent.

**Comment by janmejay** [comment]
Also, 3rd seems like the best option to me.

**Comment by rgerhards** [comment]
Topo-Sort does not reliably work, as we may have circular dependencies (which are terminated by ```if``` constructs).

**Comment by rgerhards** [comment]
After some thinking I come to the conclusion that the proper path is to split the queue shutdown sequence. In a first step, all worker threads shall be terminated and the queue set to enqOnly. While some are terminated, it is still possible that the others enqueue messages into the queue (which are then just placed into the queue, not processed). After this happens, a ```call``` can no longer be issued (as there are no more workers). So then we can destruct the rulesets in any order.

We need to check that inputs are terminated prior to this sequence, but I think this already is the case (and required). Still should validate that.
