### ISSUE TITLE
Backslash (\) character is not properly escaped

### ISSUE THREAD

**Issue by lliknart** [rsyslog/rsyslog#1126]
It seems that the "\" character is not properly escaped when option.json="on" is used.

version used: rsyslogd 8.18.0

Configuration file:
```
template(name="template_test" type="list" option.json="on") {
        constant(value="{")
        constant(value="\"@timestamp\":\"")       property(name="timereported" dateFormat="rfc3339")
        constant(value="\",\"@src_event\":\"")    property(name="hostname")
        constant(value="\",\"@severity\":\"")     property(name="syslogseverity-text")
        constant(value="\",\"@facility\":\"")     property(name="syslogfacility-text")
        constant(value="\",\"@program\":\"")      property(name="programname")
        constant(value="\",\"message\":\"")       property(name="msg")
        constant(value="\"}")
}
```

**Message received:**
`<164>Aug 22 2016 09:30:52: %ASA: Deny udp src Internet:1.2.3.4/100(LOCAL\user) dst WAN:5.5.5.5/100 by access-group "access-group"
`

**After handling:**
```
{"@timestamp":"2016-08-22T09:30:52+02:00",
"@src_event":"src-asa.domain.lan",
"@severity":"warning",
"@facility":"local4",
"@program":"%ASA",
"message":" Deny udp src Internet:1.2.3.4/100(LOCAL\user) dst WAN:5.5.5.5/100 by access-group \"access-group\"
"}
```

The above message generates a "_jsonparsefailure" raised by logstash.
Let me know if there is a way to escape the "\" by increasing the template.

Thank you

**Comment by mostolog** [comment]
Hi.

I don't understand where's the problem here. Perhaps I'm confused, but IMHO this seems correct.

Could you give more details?

@rgerhards Can you add "requiredInfo/waitingOnResponse" tags?

**Comment by clement-casse** [comment]
Hello, 

I do indeed see a JSON parse failure regarding the use of backslashes within strings.

According to the JSON **string** specification, the only two characters which have a special meaning are `"` and  `\`. 
The following image comes from http://www.json.org
![string](http://www.json.org/string.gif)
I am pretty sure that the `_jsonparsefailure` mentioned below comes from the `\` in `...(LOCAL\user)...` in the `"message"` field. 
Encoding this original log in the JSON format would have resulted in `Deny udp src Internet:1.2.3.4/100(LOCAL\\user) dst WAN:5.5.5.5/100 by access-group \"access-group\"`. As the message is, it tries to parse `\user)` as an hexadecimal notation of a character. 

An acceptable workaround to format logs as JSON would be to move the json encoding at the property level instead to keep it at the template level: 
```
template(name="template_test" type="list") {
	constant(value="{")
	constant(value="\"@timestamp\":\"")      property(name="timereported" dateFormat="rfc3339" format="jsonr")
	constant(value="\",\"@src_event\":\"")  property(name="hostname" format="jsonr")
	constant(value="\",\"@severity\":\"")    property(name="syslogseverity-text" format="jsonr")
	constant(value="\",\"@facility\":\"")      property(name="syslogfacility-text" format="jsonr")
	constant(value="\",\"@program\":\"")  property(name="app-name" format="jsonr")
	constant(value="\",\"message\":\"")      property(name="msg" format="jsonr")
	constant(value="\"}")
}
```

**Comment by mostolog** [comment]
You are right! I just mislooked at it. Indeed, \user should be escaped to "\\user".
Just checked 
https://github.com/rsyslog/rsyslog/blob/master/template.c#L470
and
https://github.com/rsyslog/rsyslog/blob/master/template.c#L488

but can't PR now.
I'll try to change and test tomorrow ;)

Thanks

**Comment by rgerhards** [comment]
fixed via #1216 (#1216 was missing "closes #1126" in commit comment)

**Comment by mostolog** [comment]
@rgerhards hmm....according to https://github.com/rsyslog/rsyslog/issues/1126#issuecomment-255098089, shouldn't it escape ALL these characters?
```
\"
\\
\/
\b
\f
\n
\r
\t
\u four-hex-digits
```

**Comment by rgerhards** [comment]
Solidus is not strictly required and often whished not to be escaped. Other control characters should indeed be escaped, but on the other hand they should not be present. However, if someone turns off control character escaping, they may actually be present. So a safe bet would be to escape them.

As a side-note, it may be best to use libfastjson to do this work; however, this is probably slower than the current method... 

In any case, I think we need a new issue tracker for this request, because the scope of the issue changes AND a fix has already been applied.
