### ISSUE TITLE
Update required dependencies to build on Ubuntu 14.04

### ISSUE THREAD

**Issue by mostolog** [rsyslog/rsyslog#1128]
Hi.

[README.md](https://github.com/rsyslog/rsyslog/blob/master/README.md) references a bunch of dependencies needed to build rsyslog, but they seem quite outdated.

I just compiled rsyslog **with omhiredis support** on **Ubuntu 14.04**, and needed to do:

> apt-get update && apt-get install -y software-properties-common

> add-apt-repository -y ppa:adiscon/v8-stable

> apt-get update && apt-get install -y build-essential pkg-config libestr-dev libfastjson-dev zlib1g-dev uuid-dev libgcrypt20-dev liblogging-stdlog-dev libhiredis-dev

Hope it helps others.

**Comment by rgerhards** [comment]
closed via #1203
