### ISSUE TITLE
Rsyslog stops sending data to remote server after log rotation

### ISSUE THREAD

**Issue by hdep** [rsyslog/rsyslog#1131]
I have some issue with rsyslog and imfile module. During file rotation rsyslog stop sending logs to central syslog server. 
Here is my logrotate file :
{
    missingok
    daily
    rotate 10
    olddir /var/log/tomcat/
    compress
    copytruncate
    sharedscripts
 }

Here is part of my rsyslog configuration : 

input(type="imfile" File="/var/log/tomcat/*" Tag="log4j")

Any idea on what happen ?

**Comment by mhyllander** [comment]
I saw the same behavior this week. I am also doing log rotation using copytruncate on this particular log file. It seems that rsyslog did not detect that the file had shrunk, I could see in the imfile state file in /var/spool/rsyslog that rsyslog was still reading the correct file, but the offset was bigger than the size of the file after rotation. When I restarted rsyslog it detected the size change and started reading from the beginning.

**Comment by hdep** [comment]
Yes this is exactly this issue.

I modified my logrotate like this : 

/var/log/tomcat/log4j*
{
    missingok
    daily
    rotate 10
    olddir /var/log/tomcat/z_old
    compress
    copytruncate
    sharedscripts
        postrotate
                invoke-rc.d rsyslog force-reload > /dev/null
        endscript
}


But I'm not sure this is working.

**Comment by rgerhards** [comment]
If you truncate the file, you need to add reopenOnTruncate="on" in the imfile input. This is experimental, as we saw some strange message duplication due to file system races in the past.

**Comment by rgerhards** [comment]
doc ist here: http://www.rsyslog.com/doc/master/configuration/modules/imfile.html

**Comment by akaFalsh** [comment]
When enabling reopenOnTruncate on log4j files application receives thread block errors.

**Comment by akaFalsh** [comment]
When enabling reopenOnTruncate I receive this error on java side:
```
Blocked on java.io.PrintStream@13d509b7, owned by [70] pool-13-thread-1
 -java.base@9/java.io.PrintStream.write(PrintStream.java:478)
 -java.base@9/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:233)
 -java.base@9/sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:303)
 -java.base@9/sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:281)
 -java.base@9/sun.nio.cs.StreamEncoder.write(StreamEncoder.java:125)
  - locked java.io.OutputStreamWriter@62696953
 -java.base@9/sun.nio.cs.StreamEncoder.write(StreamEncoder.java:135)
 -java.base@9/java.io.OutputStreamWriter.write(OutputStreamWriter.java:229)
 -java.base@9/java.io.Writer.write(Writer.java:162)
 -app//org.apache.log4j.helpers.QuietWriter.write(QuietWriter.java:48)
 -app//org.apache.log4j.WriterAppender.subAppend(WriterAppender.java:310)
 -app//org.apache.log4j.WriterAppender.append(WriterAppender.java:162)
 -app//org.apache.log4j.AppenderSkeleton.doAppend(AppenderSkeleton.java:251)
  - locked org.apache.log4j.ConsoleAppender@21cb2d8
 -app//org.apache.log4j.helpers.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:66)
 -app//org.apache.log4j.Category.callAppenders(Category.java:206)
  - locked org.apache.log4j.spi.RootLogger@bfcb43a
 -app//org.apache.log4j.Category.forcedLog(Category.java:391)
 -app//org.apache.log4j.Category.info(Category.java:666)
```
