### ISSUE TITLE
rsyslog crashes when omhiredis module enabled without network connectivity.

### ISSUE THREAD

**Issue by manu844** [rsyslog/rsyslog#1140]
We are using omhiredis module in rsyslog and omhiredis relies on hiredis to connect to redis. Everytime when the redis server is not reachable due to network issue rsyslog crashes. On looking further into the issue, the crash occurs while calling redisConnectWithTimeout and it doesn't return any error when network is unreachable.

Below is the snippet. Is there anything wrong in the way the function is handled ?

	server = (pWrkrData->pData->server == NULL) ? "127.0.0.1" : 
			(char*) pWrkrData->pData->server;
	DBGPRINTF("omhiredis: trying connect to '%s' at port %d\n", server, 
			pWrkrData->pData->port);

	struct timeval timeout = { 1, 500000 }; /* 1.5 seconds */
	pWrkrData->conn = redisConnectWithTimeout(server, pWrkrData->pData->port,
			timeout);

	if (pWrkrData->conn->err) {
		if(!bSilent)
			errmsg.LogError(0, RS_RET_SUSPENDED,
				"can not initialize redis handle");
		ABORT_FINALIZE(RS_RET_SUSPENDED);
	}

**Comment by manu844** [comment]
@brianknox Any idea why is this happening ?

**Comment by manu844** [comment]
Below is the stack trace when rsyslog crashes.

*** glibc detected *** /usr/sbin/rsyslogd: free(): invalid pointer: 0x00007f2eb20cfef8 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x75bb6)[0x7f2eb1dbcbb6]
/lib/x86_64-linux-gnu/libc.so.6(cfree+0x6c)[0x7f2eb1dc195c]
/usr/lib/rsyslog/omhiredis.so(+0x10da)[0x7f2eb06d60da]
/usr/sbin/rsyslogd[0x441c0e]
/usr/sbin/rsyslogd(actionCommitAllDirect+0x9a)[0x44280a]
/usr/sbin/rsyslogd[0x43b274]
/usr/sbin/rsyslogd[0x44abcc]
/usr/sbin/rsyslogd[0x437871]
/usr/sbin/rsyslogd(wtiWorker+0xd6)[0x433b86]
/usr/sbin/rsyslogd[0x432cc0]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x6b50)[0x7f2eb2afab50]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x6d)[0x7f2eb1e24fbd]

**Comment by radu-gheorghe** [comment]
Can you try building rsyslog from this fork here: https://github.com/rsyslog/rsyslog/pull/1109 and see if it works for you? It seems like that's a fix for this issue

**Comment by manu844** [comment]
@radu-gheorghe Thanks, that patch works for us.

**Comment by mostolog** [comment]
@rgerhards Could you close this one?
