### ISSUE TITLE
Obscene memory usage for imjournal module

### ISSUE THREAD

**Issue by otheus** [rsyslog/rsyslog#1141]
I closed ticket https://github.com/rsyslog/rsyslog/issues/1127 when I discovered the memory hog was, in fact, 100% completely due to the `imjournal` module.

With imjournal module enabled:

```
# ps -o vsz,rss,size -C rsyslogd
   VSZ   RSS  SIZE
572644 148664 156212
```

Without imjournal module:

```
# ps -o vsz,rss,size -C rsyslogd
   VSZ   RSS  SIZE
108248  3700 82444
```

Configuration:

```
$ModLoad imuxsock 
$ModLoad imjournal # or disabled per above
$OmitLocalLogging on
*.emerg :omusrmsg:*
```

Version: `rsyslog-7.4.7-12.el7.x86_64`
RedHat 7 but also seen on 6.

**Comment by rgerhards** [comment]
seems to be related to journal lib (discussion outcome)
