### ISSUE TITLE
Wrong Timestamp

### ISSUE THREAD

**Issue by Quentish** [rsyslog/rsyslog#1145]
Hello.

I've  syslog running and sending logs via UDP but the timestamp send is wrong by 1day. The system's date is correct and inside the log's file everything is correct. The result of timereported or timegenerated are one day in the past. 
> 
root@kali:~# date
mercredi 14 septembre 2016, 10:05:41 (UTC+0200)
root@kali:~# tail -n 3  /var/log/syslog
2016-09-14T10:05:55.029571+02:00 kali rsyslogd: -- MARK --

timestamp send : 1473754620 => 13/09/2016   10:17:00

property(name="timereported" dateformat="unixtimestamp")

Why does it have one day off ?

**Comment by rgerhards** [comment]
Rsyslog version?

Sent from phone, thus brief.

Am 14.09.2016 10:20 schrieb "Quentish" <notifications@github.com>:

**Comment by Quentish** [comment]
> root@kali:~# rsyslogd -v
rsyslogd 8.16.0, compiled with:
	PLATFORM:				x86_64-pc-linux-gnu
	PLATFORM (lsb_release -d):		
	FEATURE_REGEXP:				Yes
	GSSAPI Kerberos 5 support:		Yes
	FEATURE_DEBUG (debug build, slow code):	No
	32bit Atomic operations supported:	Yes
	64bit Atomic operations supported:	Yes
	memory allocator:			system default
	Runtime Instrumentation (slow code):	No
	uuid support:				Yes
	Number of Bits in RainerScript integers: 64

**Comment by rgerhards** [comment]
too old, fixed in 8.17; https://github.com/rsyslog/rsyslog/blob/master/ChangeLog#L352
