### ISSUE TITLE
Use unsigned int when reporting actual rcvbuf sizes in debug mode

### ISSUE THREAD

**Issue by zytek** [rsyslog/rsyslog#1146]
rsyslog 8.21.0

Problem:

```
(ubuntu) ~ $ sudo rsyslogd  -n
rsyslogd: cannot set os socket rcvbuf size 1215752192 for socket 6, value now is -931731456: No such file or directory [v8.21.0]
rsyslogd: cannot set os socket rcvbuf size 1215752192 for socket 8, value now is -931731456 [v8.21.0]
```

Expected output: 
-931731456 treated as unsigned int should render 3363235840 (~3.3 GB) if I did my math good.

Steps to reproduce:

Set uberhigh rcvbuf size in UDP input module that won't be permitted by kernel.
You must do it on a system that will permit you setting it to >2GB so hat `int` will overflow.  I did it on Ubuntu 12.04 with kernel 3.13 and 7.2 GB of RAM (used 1100MB).

`input(type="imudp" port="514" rcvbufSize="10G")`

Run rsyslog in debug mode and notice overflown value.

The bug is somewhere here https://github.com/rsyslog/rsyslog/blob/master/runtime/net.c#L1343

**Comment by rgerhards** [comment]
We need to carefully check the socket API:

http://man7.org/linux/man-pages/man7/socket.7.html

It says that the parameter for SO_RECVBUF must be int. So IMHO we cannot simply change it to unsigned, as done e.g. in #1217 (I am not posting it there as I am not sure if the PR again gets deleted). On the other hand, the bug report indicates that int is insufficient, so there seems to be a mismatch between theory (man 7 socket) and practice... We need to find what is right, and **then** can apply a proper patch based on that knowledge.

**Comment by davidelang** [comment]
is it actually reasonable to set the receive buffer size to something over 2G
would we possibly be better off just adding a test to prohibit values that are too large.

2G is a LOT of messages.

**Comment by rgerhards** [comment]
in any case, it's not supported by the OS API as said above. So I agree the right thing to do is probably to not permit more than 2G in the first place.

**Comment by zytek** [comment]
Whatever protects from displaying incorrect value is reasonable IMHO.
