### ISSUE TITLE
imrelp does not support address binding

### ISSUE THREAD

**Issue by dch** [rsyslog/rsyslog#1151]
`imtcp` supports a very nice address parameter to allow binding e.g. to localhost, and allowing a firewall or vpn to avoid having rsyslog being connected directly to the internet. It would be great if `imrelp` could do this too.

**Comment by mostolog** [comment]
Definitively, it could be an interesting feature to be able to listen only on certain interfaces.
@rgerhards @radu-gheorghe Do you think this might be a "trivial" change? With your assistance, I could try to do it...

**Comment by radu-gheorghe** [comment]
Thanks for the offer, @mostolog! I could try reviewing your patch but I'm faaaar from being an expert (with regards to this part of the code and with C programming in general). If you're up for a PR, maybe you can also include a couple of tests (default config vs binding to an interface) - that should be a good-enough guarantee, IMO (especially since it's a new feature), and then I can have a look and surely Rainer or someone else will also check before merging.

**Comment by mostolog** [comment]
Having an eye on https://github.com/rsyslog/librelp/blob/master/src/librelp.h I still have to look for documentation on:

- relpSrvAddPermittedPeer
- relpCltSetClientIP
- relpCltAddPermittedPeer

Already "added" address parameter to imrelp (copying what's on imtcp), but still missing how to:
> configureTCPListen(pOurTcpsrv, inst->pszBindPort, inst->bSuppOctetFram, inst->pszBindAddr);

I'll have an eye later (I have to prepare a report, which deadline was yesterday).

Regards

**Comment by radu-gheorghe** [comment]
In librelp I see this function: https://github.com/rsyslog/librelp/blob/master/src/relpsrv.c#L166 but I can't find the equivalent one for interface/address. I suppose it needs to be added? Either way, I think it needs to be used in imrelp, like the one for ports: https://github.com/rsyslog/rsyslog/blob/master/plugins/imrelp/imrelp.c#L339

It looks like imtcp uses a different approach.

**Comment by mostolog** [comment]
I just had a look (instead of working on my report...¬¬) and suspect Relp is based on a TCP instance, hence it may be should configured there.

https://github.com/rsyslog/librelp/blob/master/src/relpsrv.c#L359

**Comment by mostolog** [comment]
After a few more tries I haven't been able to find a place to _easily_ define IP address binding. We will have to wait for _The One_ to give us a hand.

**Comment by mostolog** [comment]
Didn't notice it's a duplicate of #894.
Please, close.

**Comment by dch** [comment]
duplicate see @mostolog 's comment.
