### ISSUE TITLE
Warning/Error messages without timestamp marks

### ISSUE THREAD

**Issue by mostolog** [rsyslog/rsyslog#1153]
Hi

I'm getting several warnings/errors on a test environment:
> rsyslogd: can not initialize redis handle [v8.21.0 try http://www.rsyslog.com/e/2007 ]

Seems https://github.com/rsyslog/rsyslog/blob/90101db284f6a53d3e22ad8c9c27a01c95632d4c/contrib/omhiredis/omhiredis.c#L152 it's due to network connectivity issues, queues full...or whatever someone else could know, but I don't.

Is there any way this log/output to get _timestamp_ marks to know when/why this happened?
Are _timestamps_ enabled by default on rsyslog messages? **Are rsyslog log messages compliying somehow with syslog format**? Is this just a omhiredis issue?

Regards

**Comment by rgerhards** [comment]
Where does this message occur? If in the regular syslog stream it has a proper timestamp (depending on the template).  If it is just spit out to stdout as part of an interactive run, it does not. So make sure styslog.* Is recorded.

Re redis, @taotetek may be able to help (I have no idea of redis).

**Comment by mostolog** [comment]
I'm running **rsyslogd -n**, so probably what you said.
Shouldn't interactive/stdout messages also contain timestamps?

**Comment by rgerhards** [comment]
2016-09-26 15:56 GMT+02:00 mostolog <notifications@github.com>:

> I'm running *rsyslogd -n*, so probably what you said.
> Shouldn't interactive/stdout messages also contain timestamps?
>

I can't look at the code at the moment. But it's just an interactive
debugging vehicle, so I don't think that we output timestamps. This is not
meant for real logging. Use in rsyslog.conf

syslog.* /var/log/rsyslogd.log

or similar.

HTH
Rainer

**Comment by mostolog** [comment]
Although timestamps wont hurt anyone, I understand stdout it's not debugging-oriented, hence we don't need them. Please, consider it for a future release if you think worths it.
