### ISSUE TITLE
Rsyslog Missing MySQL Table Silent Error

### ISSUE THREAD

**Issue by riddler75** [rsyslog/rsyslog#1158]
I have a pretty basic rsyslog configuration file that parses an incoming log file, extracts specific fields, builds a query and writes to a local MySQL database. The table names can change dynamically, although the underlying structure of the table is constant. For that reason, I have another configuration file that watches the messages file for an error message saying a table doesn't exist (e.g. db error (1146): Table xxx doesn't exist) and subsequently fires a Perl script to create the table and the logs are written to the new table flawlessly. This is all happening under rsyslog version rsyslog-mysql-8.19.0-1.

I recently upgraded to rsyslog-8.21.0-1 at which time the above functionality stops working because rsyslog is not throwing any errors to the messages file when it attempts to write to a MySQL table that doesn't exist. This causes incoming log files to be dropped and not properly logged in the local MySQL database. If I downgrade to rsyslog-mysql-8.19.0-1 the same configuration works as intended and the missing tables are dynamically created. 

I believe the underlying issue is the error message is not making it to the messages file - either it is being dropped or it's going to some other log file, of which I've yet to find. Thank you!

**Comment by rgerhards** [comment]
I guess this hits you:

https://github.com/rsyslog/rsyslog/blob/master/ChangeLog#L13

follow advise there and please report back.

**Comment by riddler75** [comment]
Adding the global(processInternalMessages="on") in my rsyslog.conf file has restored rsyslog to the messages file, confirmed via rsyslog restart. The actual table error is infrequent but I'm hopeful I'll see it should it crop up again. Thank you kindly!
