### ISSUE TITLE
EscapecontrolCharactersOnReceive setting affects $rawmsg

### ISSUE THREAD

**Issue by otheus** [rsyslog/rsyslog#1159]
The property "rawmsg" is described as "the message as it was received on the socket". This is blatantly false. The EscapecontrolCharactersOnReceive when on (by default) transforms non-ascii characters such as TAB but not NL into hex string thingys.  In the Parser code, it can be seen where GetParserEscapeControlCharactersOnReceive is used to prefix code which modifies the string _before_ it is saved as "raw message". 

Since we cannot unroll history, I suggest the documentation be amended as to what "rawmsg" actually means. 

Further, I suggest an additional control to the EscapeControlCharactersOnReceive to allow a subset (such as matching the isspace() C character class) to pass through.

UPDATE: I guess the docs could use some updating w.r.t. to this message massaging. I learned EscapeControlCharacterTab exists and solves my particular problem. The general issue persists.

**Comment by mostolog** [comment]
@rgerhards may I update -doc or this behaviour should be fixed to avoid escaping on rawmsg*?

**Comment by rgerhards** [comment]
The behaviour is correct, the doc is slightly wrong.

**Comment by mostolog** [comment]
Please, close
