### ISSUE TITLE
Extending of ksi signature fails

### ISSUE THREAD

**Issue by Sotuke** [rsyslog/rsyslog#1160]
Prequisite:
1. rsyslog.conf file configured to use: 
- sig.provider="ksi",
- sig.block.sizeLimit="5" 
- sig.keepTreeHashes="off" 
- sig.keepRecordHashes="off"
- rsyslog is working
  Steps to reproduce:
- Use an older ksi signature (generated before 15th of current month) or generate enough log entries for a log block to be signed and wait for 15th.
- Send the extend request with rsgtutil in following format: "rsgtutil -e <path/to/logFile/> -P <publications find URL> -E <extender URL> -d

Expected result: Response indicating that the extending was successful
Actual result: Snippet from the log: KSI Extend Signature: [256]Invalid argument.

Attached rsgtutil log, log file and the log file signature

[Archive.zip](https://github.com/rsyslog/rsyslog/files/500708/Archive.zip)

**Comment by andreassisask** [comment]
This is most likely because you did not provide the Extender parameters - service URL, login ID and key which are required for extending. However, a better error message would be expected in that case anyway.

**Comment by rgerhards** [comment]
I am closing this, as the 2016 KSI subsystem has been replaced by a new one (rewritten from scratch to the new APIs). Please report a new issue if the problem persists with 8.31 and above. Thanks.
