### ISSUE TITLE
imfile plugin does not initialize iMaxFileSize which causes divide-by-zero exception

### ISSUE THREAD

**Issue by hubo1016** [rsyslog/rsyslog#1162]
It should also be the root cause of #1066 

imfile never set strm_t.iMaxFileSize field and leave it to 0. When uses multiline mode e.g. setting startmsg.regex, this causes a divide-by-zero exception in the following statements in strm

``` C
static rsRetVal
strmNextFile(strm_t *pThis)
{
    DEFiRet;

    ASSERT(pThis != NULL);
    ASSERT(pThis->iMaxFiles != 0);
    ASSERT(pThis->fd != -1);

    CHKiRet(strmCloseFile(pThis));

    /* we do modulo operation to ensure we obey the iMaxFile property. This will always
     * result in a file number lower than iMaxFile, so it if wraps, the name is back to
     * 0, which results in the first file being overwritten. Not desired for queues, so
     * make sure their iMaxFiles is large enough. But it is well-desired for other
     * use cases, e.g. a circular output log file. -- rgerhards, 2008-01-10
     */
    pThis->iCurrFNum = (pThis->iCurrFNum + 1) % pThis->iMaxFiles;

finalize_it:
    RETiRet;
}
```

This line of statement

``` C
pThis->iCurrFNum = (pThis->iCurrFNum + 1) % pThis->iMaxFiles;
```

causes the program to crash.

There are a few ways to fix this problem:
1. Set the iMaxFiles field in imfile module, but the same problem may appear again in other modules
2. Initialize iMaxFiles field to a reasonable non-zero value in strmConstruc to prevent it from crashing. Modules are free to initialize the field to preferred value after construction.
3. Add a judge in strmNextFile for iMaxFiles = 0. But the number may overflow after a very long time (though not quite possible)

Used configuration file:

```
module(load="imfile")
module(load="omkafka")

$WorkDirectory /data
$MainMsgQueueType LinkedList
$MainMsgQueueFileName local5.info
$MainMsgQueueHighWatermark 2400000
$MainMsgQueueLowWatermark 100000
$MainMsgQueueMaxDiskSpace 100g
$MainMsgQueueSize 4000000
$MainMsgQueueSaveOnShutdown on
$MainMsgQueueDiscardSeverity 8
$MainMsgQueueDiscardMark 4000000
$MainMsgQueueTimeoutEnqueue 3000
$MainMsgQueueDequeueBatchSize 1000
$MaxMessageSize 5000k

string="hostname:%hostname% tag:%syslogtag% msg:%msg%\n")
template(name="nginxAccessTemplate" type="string" string="%hostname% %syslogtag% %msg%\n")
ruleset(name="kafka") {
  action (
    queue.workerthreads="1"
    type="omkafka"
    topic="test-kafka"
    broker=["10.1.1.2:9092","10.1.1.3:9092"]
    template="nginxAccessTemplate"
    partitions.auto="on"
    errorfile="/data/logstash/omkafka/log_kafka_failures.log"
  )
  stop
}
input(
    type="imfile"
    PersistStateInterval="1"
    Tag="test"
    File="/data/access1.log"
    startmsg.regex="^\\["
    Facility="local5"
    Severity="info"
    Ruleset="kafka"
)
```

The software version is the latest 8.21.0, system: CentOS 6.5

I'll submit a pr using the second way to fix the problem.

**Comment by hubo1016** [comment]
pr #1163

**Comment by rgerhards** [comment]
could you compile rsyslog with debugging enabled (so that the assertions are active) and provide the backtrace of the resulting abort? That would be phantastic.

**Comment by hubo1016** [comment]
I'll try if I have time, but may not be very soon... I think it is quite easy to reproduce because as long as you set PersistStateInterval="1" startmsg.regex="<somereg>", the program crashes with even a few lines of log.

**Comment by rgerhards** [comment]
Thanks. I gave it a try, but did not get to a crash. Will see if I can add some more instrumentation later on. A concrete example (or backtrace) would of course be much better.

**Comment by mostolog** [comment]
@rgerhards I could try to reproduce it, as I have several multiline files being processed.
What would be a proper value for _PersistStateInterval_? (perhaps 1 is **too** low)

**Comment by rgerhards** [comment]
@mostolog that would be great! *PersistStateInterval* it really depends on what is your target. As for now, I think it is primarily repo, 1 is probably a good value as it creates most stress.

**Comment by mostolog** [comment]
I'll let you know if I observe any issues in the following days. We are probably moving that to testing environment, so I expect more traffic.

**Comment by rgerhards** [comment]
If you get it to crash, I would be primarily interested in seeing a backtrace of the crash location. I hope that with that I may be able to build a testbench test. What I do not understand is why the function in question is called at all (it's not supposed to be under these circumstances), so knowing the callers would be immensly useful (I think... ;-)).

**Comment by mostolog** [comment]
I'm definitely getting errors processing 339 files (123 of them have _startmsg.regex_) using **PersistStateInterval="1"**

Sample:
```
input(type="imfile" file="/logs/one.log" tag="weblogic/gesper1-1" addMetadata="on" ruleset="mytag" PersistStateInterval="1")
input(type="imfile" file="/logs/two.log" tag="mynewtag" addMetadata="on" ruleset="json" startmsg.regex="^[[:digit:]]{2} [[:alpha:]]{3} [[:digit:]]{4}" PersistStateInterval="1")
```

A few seconds after launching rsyslog I'm getting:
> rsyslogd: problem on disk queue 'action 0 queue[DA]': queue files contain 1 messages fewer than specified in .qi file -- we lost those messages. That's all we know. [v8.22.0 try http://www.rsyslog.com/e/0 ]

Be right back, I'm following http://www.rsyslog.com/doc/v8-stable/troubleshooting/debug.html :wink:

**Comment by rgerhards** [comment]
So can you get back to a state where the problem occurs?

**Comment by rgerhards** [comment]
Oh... And is it possible to do this without hundreds of file monitors? That makes it extremely hard to see what fails (well, of course better than no repro ;-)).

**Comment by mostolog** [comment]
Once it has crashed, it seems it cannot start again, but I still have to get a backtrace.
And yes, I will try to reproduce it with less than 300 files. 😉

**Comment by hubo1016** [comment]
Thanks @mostolog , I should really have done this, but I just had no time...
Did you use the latest code to compile the rsyslog? I remember that asserts are inserted, so if the program hits the criteria, there should be some assert reports.

**Comment by mostolog** [comment]
As referenced above, I achieved to get a crash which could be related to this issue, but I haven't been able to easily reproduce the "disk queue issues" appearing as: 
```
rsyslogd: problem on disk queue 'action 0 queue[DA]': queue files contain 1 messages fewer than specified in .qi file -- we lost those messages. That's all we know. [v8.22.0 try http://www.rsyslog.com/e/0 ]
```

**Comment by rgerhards** [comment]
The exact case seems to be reproduced in https://github.com/rsyslog/rsyslog/issues/1239
