### ISSUE TITLE
Having newline characters in syslog messages over TCP

### ISSUE THREAD

**Issue by suezzelur** [rsyslog/rsyslog#1165]
Is '\n' assumed to be the end of a syslog message when sent over TCP? The debug format of rsyslog shows everything after '\n' to be part of another message. Is there a way to consider \n to be part of the original message?

**Comment by radu-gheorghe** [comment]
Yes, that's the "traditional" protocol. You can use octet-count delimitation by setting TCP_Framing in omfwd: http://www.rsyslog.com/doc/v8-stable/configuration/modules/omfwd.html

Though not all daemons will support receiving octet-delimited messages. rsyslog certainly can, though.
