### ISSUE TITLE
omelasticsearch can exceed http.max_content_length when bulking messages

### ISSUE THREAD

**Issue by barakshechter** [rsyslog/rsyslog#1170]
omelasticsearch is configurable in bulk mode by number of messages, however, ElasticSearch limits requests based on content-length (default is 100Mb). This can result in batch submission that exceeds the configured limit on the elasticsearch cluster. 

The output module would ideally be configurable to have a maxbytes it can send in bulk mode and when that size is reached, flush any batch buffers it has been accumulating.

**Comment by rgerhards** [comment]
is there any way to obtain this limit from ES?

**Comment by barakshechter** [comment]
It is possible to obtain it, however the extra convenience of not having to provide an explicit setting is probably not worth tightly coupling rsyslog configuration to an ElasticSearch settings retrieval API. I would imagine most users do not change the ES default of 100Mb.
