### ISSUE TITLE
omelasticsearch does not support HA addressing of elasticsearch cluster

### ISSUE THREAD

**Issue by barakshechter** [rsyslog/rsyslog#1171]
ElasticSearch is highly available, where any node of the cluster is subject to failure at any given time. However, the ElasticSearch output module only accepts a single server url for the cluster. This requires ensuring dynamic resolution of the cluster servers, (for example, by using a reverse proxy). 

It would be nice to be able to specify the server url as a comma separated list, one of which is selected in round robin fashion when POSTing messages to ElasticSearch.

**Comment by rgerhards** [comment]
I like the idea, but an array should be used rather than a comma-delimited list, because this is how multiple objects are usually done in rsyslog.conf. An example is omkafka: https://github.com/rsyslog/rsyslog/blob/master/plugins/omkafka/omkafka.c#L147

**Comment by barakshechter** [comment]
I agree the array parameter is better in that it is more explicit in how the module expects to be configured. The only reason for suggesting the commas was for backwards compatibility of the plugin configuration. If this is not a concern, then I am happy to do it as an array.

**Comment by rgerhards** [comment]
Array does not break backwards compatibility...

Sent from phone, thus brief.

Am 05.10.2016 18:53 schrieb "barakshechter" <notifications@github.com>:

**Comment by barakshechter** [comment]
Just looked at the grammar definition. Sounds great. I'll use the array handler here
