### ISSUE TITLE
hang at system startup (regression starting 8.21.0)

### ISSUE THREAD

**Issue by rgerhards** [rsyslog/rsyslog#1188]
When we log internal messages to syslog (the default starting with 8.21), early error messages can result in rsyslogd hanging, as well as everything else that wants to log hanging.

This is the result of deadlock: rsyslog triesto write to the log socket, which blocks but can't be unblocked as rsyslog processing would need to advance to do so. Interestingly, this only happens occasionally (even though the startup sequence is deterministic at this point), so it is hard to diagnose. Also, not all platforms seem to be affected. Platforms with systemd journal will never run into a deadlock (as journal in this case reads the system log socket).

The root cause is that for internal messages we maintain a queue for such early messages and emit them only after full startup. Similar code is missing when writing to the log socket. The full code needs to be restructured so that this condition is obeyed under all conditions.

A temporary workaround is to use
```
global(ProcessInternalMessages="on")
```
at the top of rsyslog.conf.

**Comment by himadrisingh001** [comment]
We have been also observing similar issue where few of the servers hang due to rsyslog issue. It also made the unresponsive to ssh. If we have salt running on these nodes, restarting rsyslog helps to revive the node back alive.
