### ISSUE TITLE
rsyslog 8 config 

### ISSUE THREAD

**Issue by zhangmingju** [rsyslog/rsyslog#1189]
this is my config

$WorkDirectory /var/spool/rsyslog
module(load="imfile")
input(type="imfile"
      File="/home/yesqin/alphaLog/moon/log/production.log"
      Tag="test@yesqin.com"
      Severity="info"
      Facility="local7"
      PersistStateInterval="2000"
    )
template(name="yesqin" type="string"
         string="@#@ %timereported:::date-rfc3339% %app-name% #@# %msg%\n")
module(load="omfwd" Template="yesqin")
action(type="omfwd" Target="103.21.117.62" Port="5140")

i want to send log to remote server,
but,template without effictive,how i do?

**Comment by mostolog** [comment]
You shouldn't open an issue for this, but ask on http://lists.adiscon.net/mailman/listinfo/rsyslog
