### ISSUE TITLE
omkafka - support partition selection based on message key

### ISSUE THREAD

**Issue by tedwardia** [rsyslog/rsyslog#1199]
Many kafka deployments determine what specific partition to produce to based on a hash of the message key:

https://cwiki.apache.org/confluence/display/KAFKA/FAQ#FAQ-Whyisdatanotevenlydistributedamongpartitionswhenapartitioningkeyisnotspecified?

You can use partitions.useFixed to accomplish something similar, but being able to do this in the normal kafka way would be much more convenient :) The latest version of librdkafka appears to support this by default:

https://github.com/edenhill/librdkafka/releases/tag/0.9.1
https://github.com/edenhill/librdkafka/pull/548

That version of librdkafka still supports 0.8.x kafka brokers, though the following might need to be kept in mind (maybe mention setting broker.version.fallback in confParam in the omkafka docs?):

https://github.com/edenhill/librdkafka/wiki/Broker-version-compatibility

**Comment by mrauter** [comment]
anybody work on this?

**Comment by rgerhards** [comment]
I am not aware of anybody.

**Comment by alorbach** [comment]
is this still needed with the current deveolpment state?
