### ISSUE TITLE
segfault when using omrelp rebindinterval option

### ISSUE THREAD

**Issue by alexjfisher** [rsyslog/rsyslog#120]
I'm looking to use rebindinterval to help with loadbalancing to multiple RELP receivers (haproxy/logstash).

But... It (version 8.4.0 built against librelp 1.2.7) segfaults after rebindinterval number of messages.

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffeffff700 (LWP 8708)]
0x00007ffff73cd5c4 in relpCltHintBurstEnd (pThis=0x7fffe4002520)
    at relpclt.c:355
355             relpTcpHintBurstEnd(pThis->pSess->pTcp);

**Comment by Smana** [comment]
Hi @alexjfisher , i got the same issue. Did you find a way to solve it ?

**Comment by alexjfisher** [comment]
eek sorry, was quite a long time ago and I've since left the company I was working for.

**Comment by Smana** [comment]
Ok then i can give some inputs if needed to solve this bug.

**Comment by mostolog** [comment]
rebindinterval seems undocumented, isn't it?

As we have plans for LB, I would like to know what's current state of art.
We have also considered using docker swarm mode, but this is an interesting feature.

**Comment by davidelang** [comment]
rebindinterval is documented for omfwd, but not for omrelp 

http://www.rsyslog.com/doc/v8-stable/configuration/modules/omfwd.html

It's purpose is quite simple, giving a load balancer the chance to operate (no load balancer can safely move a connection from one machine to another without full understanding of the protocols involve)

With TCP and UDP, there is no feedback to rsyslog, so rebindinterval is trivial to implement. For RELP it gets a bit more complicated (if there are some messages that haven't been acked yet, do you wait for them to get acked or 'retransmit' them on the new connection, I haven't looked into the code to see what we currently try to do)

We haven't heard from anyone else that it's not working with relp, but we haven't had anyone speak up and say it is working either.

**Comment by mostolog** [comment]
> do you wait for them to get acked

Probably, this could be a global config setting.
IMHO, I'll vote for _timeoutRelpAck_ and check if write was done or error happened

> or 'retransmit' them on the new connection

After _timeoutRelpAck_, retransmit


Could someone prioritize this issue? I could do some testing, but seems there are higher priority issues to look at.

**Comment by rgerhards** [comment]
There seem to be two errors introduced to omrelp when the rebind interval was added. The second one is that if it would not segfault, only one message per connection would be sent for each rebind interval.

**Comment by rgerhards** [comment]
@kortemik while I cannot craft a testbench test, could you give the patch I posted a try?

**Comment by rgerhards** [comment]
@kortemik I did a quick manual test, and it looks like this indeed fixes the problem. Confirmation would still be good. I used current master (8.30.0) as base, but it should apply to all versions.
