### ISSUE TITLE
Dynamic key value for omhiredis

### ISSUE THREAD

**Issue by mostolog** [rsyslog/rsyslog#1201]
Enable dynamic key usage based on template, like omkafka does:

http://stackoverflow.com/questions/33560544/rsyslog-write-programname-as-kafka-topic/33604660#33604660

**Comment by rgerhards** [comment]
Would you be willing to add this information to the rsyslog-doc project?

**Comment by mostolog** [comment]
Hi Rainer.

You mean update omkafka doc to mention stackoverflow's example or to update omhiredis doc when this feature is available?

Anyway, I don't have any problem updating anything as you may need. I have been looking at how omkafka works, and I think something like "dynakey" could be added to omhiredis in order to insert into dynamic lists/channels.

**Comment by rgerhards** [comment]
mhhh.. from what I understood, the stackoverflow posting is the solution on how to do these kinds of things. A "dynakey" parameter would do exactly the same, wouldn't it?

**Comment by mostolog** [comment]
stackoverflow's answer (untested by me) it's a solution to support dynamic topic names in kafka.

This issue is intended to copy this behaviour to redis, to be able to use dynamic key values.

yes, a "dynakey" parameter would work the same way

**Comment by rgerhards** [comment]
ah, ok I didn't notice when skimming over the bug. So let's do nothing until sombody comes along and is interested in implementing this :-)

**Comment by mostolog** [comment]
@bobthemighty @taotetek @manu844 Do you think this is an interesting feature? Any of you could add it to his agenda? I don't feel very confident on being able to implement this...

**Comment by bobthemighty** [comment]
@mostolog I think I'm willing to give it a go. I'll see if I can find some time in the next few days. 

I've been wanting to play with rsyslog some more anyway.

**Comment by taotetek** [comment]
@bobthemighty @mostolog @rgerhards so - I have not messed with the code that allows you to use a template to define a variable to pass into a module like this before. I have a lot of interest in  this however, as I'd like to use the exact same technique for defining dynamic topics for my omczmq output plugin.

If I recall, I took a stab at this once and got a bit lost in all the macros, as there's not much documentation around this.

@rgerhards - do you have some pointers as to what is required to do this?

**Comment by bobthemighty** [comment]
@mostolog I started implementing `dynakey` this morning but, before I start debugging the inevitable segfaults and explosions, are you aware of the `template` mode of omhiredis?

That allows you to execute arbitrary raw redis commands - the template you provide for your message would then yield a string like `LPUSH {keyname} {message}`.

That's less user-friendly than the dynakey option, but certainly more general. I'm unsure whether I should continue with the change or not, since it's essentially a subset of existing behaviour.

Any thoughts from @rgerhards ?

**Comment by rgerhards** [comment]
@bobthemighty Unfortunately, I have very litlle knowlege on redis, so I don't feel qualified to give a suggestion. @taotetek what do you think?

**Comment by rgerhards** [comment]
well... as a general comment, I think a dedicated option would probably be better understood (and used) by most users, but I really don't feel well to suggest something here...

**Comment by mostolog** [comment]
@bobthemighty Although I read it, I wasn't aware of that. 

Let me confirm if I understood properly:
```
#This template defines the command sent to redis
template(name="redis" type="list") {
	constant(value="LPUSH ")
	property(name="programname")
	constant(value=" \" and here comes the message...")
	property(name="hostname")
	...
}
#Action using mode=template (template is not _format_, but _command_)
action(type=”omhiredis” name=”redis” server=”server” serverport=”6379” mode=”template” template=”redis”) 
```

Will this work as a workaround to LPUSH into _dynamic_ key?

**Comment by bobthemighty** [comment]
@mostolog From a cursory reading of the code, that absolutely should work.

If we were able to make a breaking change, I think the `template` mode would be better named `raw`.

**Comment by mostolog** [comment]
Stated in http://www.rsyslog.com/doc/master/configuration/modules/omhiredis.html:
> Note this mode has problems with strings with spaces in them - full message won’t work correctly

That's sounds scary...lets try:
```
template(name="redis" type="string" string="LPUSH %syslogtag% {\"time_received\":\"%timereported:::date-rfc3339%\",\"host_received\":\"$myhostname\",\"host_forwarded\":\"%hostname%\",\"tag\":\"%syslogtag%\",%msg:3%\n")
```
Result:
> "{\"\n"

:cry:

**Comment by bobthemighty** [comment]
@mostolog https://github.com/rsyslog/rsyslog/pull/1218

Is this what you want? I need to do some bug fixing, and clean up build warnings and things,  so consider this Very Much Work In Progress.

**Comment by mostolog** [comment]
@bobthemighty #1218 seems much better than I thought.
I could help with testing, and documentation. In fact I have 1600 high-rate files awaiting to be processsed...
Thanks a lot for your work!

**Comment by bobthemighty** [comment]
Dynakey it is then :) full speed ahead!
