### ISSUE TITLE
External module written with omprog and queue.type="Direct" does not write any logs nor gives an error

### ISSUE THREAD

**Issue by Dark-Passenger** [rsyslog/rsyslog#1205]
as stated in heading. Used omprog successfully to call the skeleton python script. Now the problem is that it doesnt seems to be working with queue.type = "Direct" and even without.

**Comment by Dark-Passenger** [comment]
simply put I am looking at instant message passing to module rather than waiting for a batch

**Comment by Dark-Passenger** [comment]
@rgerhards any help on implementing queue parameters ? I just need to understand how this flow works, and maybe improve my performance.

**Comment by rgerhards** [comment]
There should not be any need to do anything in regard to queues etc, this is all handled by the rsyslog core. Messages are always delivered as soon as they are ready, larger batches only if they are instantly available.

Can you post your script so that we can begin to look at what's going on?

**Comment by Dark-Passenger** [comment]
I am doing this with the skeleton plugin.py file itself.

I even wrote a c++ program for the same flow.

the setup I have a process sample that writes to syslog (local1.info) a sample string.
I have added the following to rsyslog.conf

if ($programname == "sample")
      then
          {
              action(type="omprog" binary="/opt/plugin.py")
           }

this is suppose to write it to a file. What i see is 20 logs written to the file while 200 logs have been logged and written to the syslog.

**Comment by rgerhards** [comment]
can you run rsyslog in debug mode and post the debug log (best via a gist, pastebin or similar service!).

**Comment by Dark-Passenger** [comment]
https://gist.github.com/Dark-Passenger/3454cc23aefab757998737a610b212f2

**Comment by Dark-Passenger** [comment]
rsyslog logs when a sample process was writing logs every 1 second. Total logs visible on /var/log/messages = 53, logs written to file = 9

**Comment by Dark-Passenger** [comment]
@rgerhards any comments ?

**Comment by rgerhards** [comment]
don't hurry so much, I've also some paid work to do ;-)

**Comment by rgerhards** [comment]
... but it looks like I need to create a testbench test case, and that takes a little while (especially as it is not top priority).

**Comment by Dark-Passenger** [comment]
@rgerhards I actually have a company usecase that this would solve(read certain messages from syslog and transmit to a custom server)

I just need your opinion on what would be the best way to solve this ?

an internal module would have been ideal I suppose but the compilation process seems too tedious.

and this is the external module....

**Comment by Dark-Passenger** [comment]
@rgerhards okay my bad. seems it was my setup that was at fault. now all good. but it seems to be dumping to the script at every 43 messages. Any way I can speed this up or slow it down ?

**Comment by Dark-Passenger** [comment]
oh my god... I am so sorry. It was all me.

**Comment by Dark-Passenger** [comment]
1 small thing :D is the plugin suppose to terminate on eof ?

**Comment by rgerhards** [comment]
yes, EOF indicates that the plugin must terminate.

side-note: if this is urgent and if it is for a company use case, you should consider http://www.rsyslog.com/professional-services/
