### ISSUE TITLE
LOGSIG11 missing in the beginning of KSI log signature file

### ISSUE THREAD

**Issue by andreassisask** [rsyslog/rsyslog#1206]
When logging with KSI is not working properly for whatever reason, an empty <logsig>.ksisig file is created (which by itself is not an issue). However, later it looks like this file is re-used, but it is not checked whether it already contains the magic LOGSIG11 in the beginning of the file. This leads to a log signature file which has correct content but is missing the LOGSIG11 magic in the beginning.

**Comment by rgerhards** [comment]
Would it be possible to create a testbench test case for this problem (based on the existing tests)? That would be a great aid in fixing the issue.
