### ISSUE TITLE
libmongo-client is obsolete

### ISSUE THREAD

**Issue by radosroka** [rsyslog/rsyslog#1208]
Hi,

Module OMMONGODB is still using libmongo-client which is an obsolete library.
Using an obsolete library without any support is kind of risky. Any plans for the future?

Using official mongo-db-client which is still well maintained, could be an option.
https://github.com/mongodb/mongo-c-driver

**Comment by rgerhards** [comment]
We used libmongo-client because the official API at that time was neither stable nor fully functional, and I think not even working reliably. Do you know if this has changed and is now mature?

**Comment by radosroka** [comment]
Stability looks good https://abi-laboratory.pro/tracker/timeline/mongo-c-driver/

What do you think?

**Comment by radosroka** [comment]
I think this was resolved in v8.31.0.
