### ISSUE TITLE
Config check omission on omfile templates

### ISSUE THREAD

**Issue by skreien** [rsyslog/rsyslog#1225]
When parsing the config it does not check to see if the templates specified in the config exist or not, at least when it's an omfwd template.  Did not try any other places templates can be specified.  If the omfwd template doesn't exist there are no warnings given and I assume it then falls back to the default template, but a non-fatal warning should be given if the template doesn't exist.  In my case a remote was being forwarded data that it didn't expect, and later on when a template with the same name was created the new template broke some forwarders entirely.

**Comment by rgerhards** [comment]
We should first create a testbench test to verify this indeed is a bug. That can than also be used to make sure it will be fixed.

**Comment by PascalWithopf** [comment]
I created a test but there is an error given.
When using an action of type omfwd and the template specified doesn't exist the following error is given:
rsyslogd:  Could not find template 0 'omfwd' - action disabled [v8.29.0.master try http://www.rsyslog.com/e/3003 ]

**Comment by rgerhards** [comment]
@skreien I assume that this was fixed as a side-effect in the mean time. I close the bug tracker for now. If the problem exists with current version, let me know and I'll re-open.
