### ISSUE TITLE
Regression: rsyslog no longer forwarding logs over UDP Multicast

### ISSUE THREAD

**Issue by heanssgen-troy** [rsyslog/rsyslog#1229]
As of rsyslog 8.16.0-1ubuntu3 (Shipped in Ubuntu 16.04) we have noticed that the message forwarder is no longer correctly sending messages to a remote server over Multicast.

This is a regression from the version of rsyslog shipped in Ubuntu 14.04 (7.4.4-1ubuntu2.3) where this functionality worked. It is possible that this is a problem related to the way journalctl handles log forwarding to traditional syslog via socket, though I have been unable to reproduce the same problem when using 7.4.4.1 backported to xenial.

We have ensured that /etc/systemd/journald.conf has ForwardToSyslog set to yes and that the socket in /run/systemd/journal is being created.

The rule in question is a simple forwarding expression. We are using the following rule on both systems:

`*.* @239.0.0.222:2514`

When sending multicast traffic manually through the mcsender tool (part of the smcroute package) the traffic sends successfully.

Here is a packet capture of mcsender at work: http://imgur.com/a/ztouM. There are no packets sent by rsyslog in the following 3 scenarios:

1: 'logger' is invoked on the terminal
2: A system message is sent to either kmesg or dmesg
3: An entry is written manually into /var/log/syslog

A ptrace shows that there are no permission denied errors, and I have double checked that the syslog file is owned by root:adm (default in Ubuntu).

**Comment by davidelang** [comment]
can you start rsyslog in debug mode and show us what happens when it tries to process the first log message?

rsyslog has no explicit support for multicast. I've used it with multicast MAC to great success, but my understanding is that using IP layer multicast (the @239.* addresses) requires explicit support.

Does Ubuntu have an out-of-tree patch to support this in their 7.4.4-1 version?

**Comment by rgerhards** [comment]
no answer, no repo
