### ISSUE TITLE
omkafka making a topic it can't publish to

### ISSUE THREAD

**Issue by jdblack** [rsyslog/rsyslog#1230]
Hello,

omkafka in rsyslog 8.2.2 seems to be creating topis that it can't publish to by default to Kafka 0.10.1. Worse, it appears that setting topic parameters is also broken, making it impossible to make a working omkafka stack.   We were able to figure out that the problem is that the topic is not usable unless segment.bytes for the topic is configured.
# 

module(load="imuxsock") # provides support for local system logging (e.g. via logger command)
module(load="imklog")   # provides kernel logging support (previously done by rklogd)
module(load="omkafka")
module(load="imudp") # needs to be done just once
input(type="imudp" port="514")
module(load="imtcp") # needs to be done just once
input(type="imtcp" port="514")
template(name="forwardFormat" type="string"
         string="%PRI% %TIMESTAMP:::date-rfc3339% %HOSTNAME% %syslogtag:1:32%%msg:::sp-if-no-1st-sp%%msg%" )
template(name="tokafka" type="list") {
    property(name="pri")
    constant(value=" ")
    property(name="timestamp" dateFormat="rfc3339")
    constant(value=" ")
    property(name="hostname")
    constant(value=" ")
    property(name="programname")
    constant(value=" ")
    property(name="procid")
    constant(value=" ")
    property(name="msgid")
    constant(value=" ")
    property(name="msg")
    constant(value="\n")
}

main_queue(
  queue.workerthreads="1"      # threads to work on the queue
  queue.dequeueBatchSize="100" # max number of messages to process at once
  queue.size="10000"           # max queue size
)

action(
  broker=["KAFKASERVER:9092"]
  type="omkafka"
  topic="logs"
  template="tokafka"
  partitions.auto="on"
  topicConfParam="segment.bytes=100000"
# )

rsyslogd: error in kafka topic conf parameter 'segment.bytes=100000': No such configuration property: "segment.bytes" [v8.22.0 try http://www.rsyslog.com/e/1000 ]

I also tied topicConfParam = ["segment.bytes=100000"], which reports the same error.

**Comment by alorbach** [comment]
librdkafka was properly to old. Please try with next release v8.28
