### ISSUE TITLE
omfile can't write template type mode is subtree

### ISSUE THREAD

**Issue by weisst** [rsyslog/rsyslog#1238]
hi all
my rsyslogd -v
rsyslogd 8.22.0, compiled with:
	PLATFORM:				x86_64-redhat-linux-gnu
	PLATFORM (lsb_release -d):
	FEATURE_REGEXP:				Yes
	GSSAPI Kerberos 5 support:		No
	FEATURE_DEBUG (debug build, slow code):	No
	32bit Atomic operations supported:	Yes
	64bit Atomic operations supported:	Yes
	memory allocator:			system default
	Runtime Instrumentation (slow code):	No
	uuid support:				Yes
	Number of Bits in RainerScript integers: 64

my template example:
template(name="csv" type="list") {
        property(name="$!usr!rcvdat" format="csv")
        constant(value=",")
        property(name="$!usr!rcvdfrom" format="csv")
        constant(value=",")
        property(name="$!usr!user" format="csv")
        constant(value=",")
        property(name="$!usr!type" format="csv")
        constant(value="\n")
}
template(name="cee" type="subtree" subtree="$!usr")

ruleset(name="output") {
        action(type="omfile" file="/var/sec/logfile.cee" template="cee")
        action(type="omfile" file="/var/sec/logfile.csv" template="csv")
}
i'm find logfile.csv file have data,but logfile.cee no data, see the debug log ,find this log

3369.622757395:main Q:Reg/w0  : omfile: write to stream, pData->pStrm 0x7ff4e8020900, lenBuf 0, strt data { "type": "logon", "rcvdfrom": "Centos", "rcvdat": "Oct 20 20:36:24", "user": "roots" }
but logfile.cee file no data,can help me?thx

3369.622682028:main Q:Reg/w0  : END batch execution phase, entering to commit phase [processed 1 of 1 messages]
3369.622689574:main Q:Reg/w0  : actionCommitAllDirect: action 0, state 0, nbr to commit 0 isTransactional 0
3369.622696548:main Q:Reg/w0  : actionCommitAllDirect: action 1, state 0, nbr to commit 0 isTransactional 0
3369.622703462:main Q:Reg/w0  : actionCommitAllDirect: action 2, state 1, nbr to commit 0 isTransactional 1
3369.622709860:main Q:Reg/w0  : doTransaction: have commitTransaction IF, using that, pWrkrInfo 0x7ff504991190
3369.622716876:main Q:Reg/w0  : entering actionCallCommitTransaction(), state: itx, actionNbr 2, nMsgs 1
3369.622740973:main Q:Reg/w0  : file stream logfile.cee params: flush interval 0, async write 0
3369.622757395:main Q:Reg/w0  : omfile: write to stream, pData->pStrm 0x7ff4e8020900, lenBuf 0, strt data { "type": "logon", "rcvdfrom": "Centos", "rcvdat": "Oct 20 20:36:24", "user": "roots" }
3369.622769043:main Q:Reg/w0  : strm 0x7ff4e8020900: strmFlushinternal: file -1(logfile.cee) flush, buflen 0 (no need to flush)
3369.622776725:main Q:Reg/w0  : Action 2 transitioned to state: rdy

**Comment by davidelang** [comment]
the debug output you show indicates that rsyslog is writing the data to the file, but you are saying that you aren't seeing it in the file.

Is it possible that the data just hasn't been flushed out to disk when you check? try sending rsyslog a hill -HUP to force it to close all it's outputs and flush all data to disk and then see if you still have no data in the file.

**Comment by dud225** [comment]
I confirm this issue.

@davidelang please look again at the end of the log message
```
strmFlushinternal: file -1(logfile.cee) flush, buflen 0 (no need to flush)
Action 2 transitioned to state: rdy
```

whereas when using a classicla string template 
```
strm 0x7fa418008310: strmFlushinternal: file 23(/tmp/test_out) flush, buflen 600
strm 0x7fa418008310: file 23(/tmp/test_out) doWriteInternal: bFlush 1
strmPhysWrite, stream 0x7fa418008310, len 600
strm 0x7fa418008310: file 23 write wrote 600 bytes
Action 1 transitioned to state: rdy
```

so there is probably something wrong here when using a subtree template.

@weisst please reopen this issue

**Comment by davidelang** [comment]
rsyslog does not force a flush to disk for every message. It does a flush when it gets a HUP or exits. beyond that it lets the OS buffer what it wants.

if you send it a HUP does the data get flushed to disk?

the template used is not going to change the flushing behavior.

**Comment by rgerhards** [comment]
Actually, rsyslog shiuld flush after each batch it processed. But there was
a bug some time ago that prevents this.

Rainer

Sent from phone, thus brief.

Am 23.06.2017 04:28 schrieb "David Lang" <notifications@github.com>:

**Comment by saurabhnanda** [comment]
I seem to be hitting the exact same bug. I have used `mmnormalize` to parse a log message and want to output the entire JSON to a log file:

```
template(
        name="parsed_json"
        type="subtree"
        subtree="$!abc"
)         

ruleset(name="dbrules" queue.type="LinkedList" queue.filename="dbq"){
        action(type="mmnormalize" rulebase="/etc/rsyslog.d/ssh.rb" userawmsg="off" path="$!abc")
        if $parsesuccess == "OK" then {
                action(type="omfile" dirCreateMode="0755" fileCreateMode="0644" file="/var/log/parsed.log" template="parsed_json")
        } else {
                action(type="omfile" dirCreateMode="0755" fileCreateMode="0644" file="/var/log/unparsed.log")
        }
}       
```

but here's what I see in the debug log:

```
4707.042319837:dbrules:Reg/w0 : omfile.c: omfile: write to stream, pData->pStrm 0x7efedc004310, lenBuf 0, strt data { "clientport": "43186"
, "clientip": "94.130.105.191" }
4707.042330026:dbrules:Reg/w0 : strm 0x7efedc004310: stream.c: strmFlushinternal: file -1(parsed.log) flush, buflen 0 (no need to flush)
```

... and there is no data in `/var/log/parsed.log`

I've tried sending a SIGHUP to rsyslogd, but that didn't help.

**Comment by davidelang** [comment]
Please create a log with the template RSYSLOG_DebugFormat at this point in your 
ruleset so we can see exactly what the variables are at that point in 
processing.

David Lang

**Comment by saurabhnanda** [comment]
> Please create a log with the template RSYSLOG_DebugFormat at this point in your ruleset so we can see exactly what the variables are at that point in processing.

Here's the output of `RSYSLOG_DebugFormat`:

```
Debug line with all properties:
FROMHOST: 'throwaway-ipsec', fromhost-ip: '127.0.0.1', HOSTNAME: 'throwaway-ipsec', PRI: 38,
syslogtag 'sshd[9688]:', programname: 'sshd', APP-NAME: 'sshd', PROCID: '9688', MSGID: '-',
TIMESTAMP: 'Mar 25 03:11:37', STRUCTURED-DATA: '-',
msg: ' Failed password for root from 112.85.42.88 port 10365 ssh2'
escaped msg: ' Failed password for root from 112.85.42.88 port 10365 ssh2'
inputname: imuxsock rawmsg: '<38>Mar 25 03:11:37 sshd[9688]: Failed password for root from 112.85.42.88 port 10365 ssh2'
$!:{ "abc": { "clientport": "10365", "clientip": "112.85.42.88", "user": "root" } }
$.:
$/:
```

Here's how this debug log was generated:

```
action(type="mmnormalize" rulebase="/etc/rsyslog.d/ssh.rb" userawmsg="off" path="$!abc")
action(type="omfile" dirCreateMode="0755" fileCreateMode="0644" file="/tmp/debug.log" template="RSYSLOG_DebugFormat")
```

PS: From the docs at https://www.rsyslog.com/doc/v8-stable/configuration/templates.html , it isn't very clear whether `RSYSLOG_DebugFormat` is something that is pre-defined or is recommended to be manually defined as given in the docs.
