### ISSUE TITLE
AIX port 

### ISSUE THREAD

**Issue by pduveau** [rsyslog/rsyslog#1264]
We work on rsyslog's AIX port, we got three issues on code 
- the "struct msg" is reserved by AIX so we suggest to rename it in "struct rmsg"
- the typedef "msg_t" is also reserved so we suggest to rename it in "rmsg_t"
- the "struct var" has the same issue the new name should be "struct rvar" and optionally a new "typedef struct rvar rvar_t"

Do you agree with that ? If so we will create a branch to publish this patch.

**Comment by davidelang** [comment]
On Wed, 16 Nov 2016, Philippe Duveau wrote:

> We work on rsyslog's AIX port, we got three issues on code
> - the "struct msg" is reserved by AIX so we suggest to rename it in "struct rmsg"
> - the typedef "msg_t" is also reserved so we suggest to rename it in "rmsg_t"
> - the "struct var" has the same issue the new name should be "struct rvar" and optionally a new "typedef struct rvar rvar_t"

Sounds good.

David Lang

**Comment by rgerhards** [comment]
Please coordinate with @purnimam1, who has done the exact some thing in this PR: https://github.com/rsyslog/rsyslog/pull/1247

That PR also contains the answers to your question, it has already been discussed in that context.

**Comment by pduveau** [comment]
Hi rainer,
Sorry for this duplicate issue. I'll participate on previous #1247 issue if necessary and close this one.

**Comment by rgerhards** [comment]
No problem with the dup. I am more than happy that aix finally gets to
speed. I appreciate your help with that. Unfortunately I myself do not even
have access to a test environment.

Sent from phone, thus brief.

Am 16.11.2016 18:34 schrieb "Philippe Duveau" <notifications@github.com>:
