### ISSUE TITLE
Enhancement Request: add option to disable flow control in imptcp module

### ISSUE THREAD

**Issue by Amorik** [rsyslog/rsyslog#1266]
In the imtcp module there is an option to disable Flow Control. Flow control is used to throttle the sender if the receiver queue is near-full preserving some space for input that can not be throttled. There is no such equivalent option in imptcp. I would request that the FlowControl option also be added to the imptcp module.

**Comment by PascalWithopf** [comment]
@Amorik 
I added the option to imptcp.
Could you test if it works as expected

**Comment by Amorik** [comment]
@PascalWithopf 
Sorry it took me a while to get to this. I ran some basic tests between two Rsyslog servers using tcpflood (tcpflood -> server1 -> server2). As far as i can tell it works as expected. When turned on queuing occurs only for the sending server. When off queuing takes place on the receiving end until full. 

Note that in my test the sending server had much higher queue and processing settings than the receiving server.

Thanks

~Regards
