### ISSUE TITLE
tests/empty-hostname.sh fails: expected hostname "localhost" not found in logs

### ISSUE THREAD

**Issue by mbiebl** [rsyslog/rsyslog#1268]
Bug-Debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=844914

I'm getting a test-suite failure

```
======================================================================
------------------------------------------------------------
Test: ./empty-hostname.sh
------------------------------------------------------------
rsyslogd started with pid  7403
imdiag[13500]: mainqueue empty
expected hostname "localhost" not found in logs, rsyslog.out.log is:
2016-11-20T14:10:26.205937+01:00 foo rsyslogd: [origin software="rsyslogd" swVersion="8.23.0" x-pid="7403" x-info="http://www.rsyslog.com"] start
2016-11-20T14:10:28.238432+01:00 foo rsyslogd: [origin software="rsyslogd" swVersion="8.23.0" x-pid="7403" x-info="http://www.rsyslog.com"] exiting on signal 15.
FAIL empty-hostname.sh (exit status: 1)
```

To reproduce the issue setup a /etc/hosts like this
```
127.0.0.1	foo localhost
```

If one uses
```
127.0.0.1 localhost
127.0.1.1 foo
```
the test succeeds. So I asume it makes certain (incorrect) assumptions about how /etc/hosts is setup

**Comment by rgerhards** [comment]
I have added some doc to the test. The assumptions on the hostname are valid, the probable root cause is that the preload library is not loaded for some reason.

**Comment by mbiebl** [comment]
I added some printf debug statements to runtime/net.c

Looking at getLocalHostname(), we do get an empty hostname from
gethostname() (from the overriden library) and at
https://github.com/rsyslog/rsyslog/blob/master/runtime/net.c#L1157

hnbuf is set to localhost (as expected).

At https://github.com/rsyslog/rsyslog/blob/master/runtime/net.c#L1164
dot is NULL so it calls gethostbyname() and iterates over the aliases.
This is where things go wrong. If I have an entry like this
```
127.0.0.1 foo localhost
```
fqdn is set to foo and this is what's returned from getLocalHostname.

**Comment by mbiebl** [comment]
On a related note: if gethostname() returns a non-emtpy string, why do we not use that name but set it to localhost at
https://github.com/rsyslog/rsyslog/blob/master/runtime/net.c#L1151

**Comment by rgerhards** [comment]
Thanks, I was obviously too focussed on the gethostname() call. Using ```localhost``` as a default obviously also brings some confusion. I think we should rename it to ```localhost-empty-hostname```, which would be an indicator of the real problem. I'll change the code accordingly and create a PR.

**Comment by rgerhards** [comment]
Note: I have also reconfigured the debian buildbot slave to showcase that problem. So hostname-related issues are hopefully sooner detected in the future.
