### ISSUE TITLE
create a pmnormalize that uses liblognorm to populate standard properties

### ISSUE THREAD

**Issue by davidelang** [rsyslog/rsyslog#1278]
create a parser module that uses liblognorm (like mmnormalize does) to parse the incoming message.

The idea is to create an easy way to specify handling of messages that are not in standard syslog formats. A common example of this is logs that are sent as json without any headers

After the message is parsed, look for things in the parsed output that match the standard properties and copy them to the standard properties (and optionally remove them from the variables)

As per the rgc-3164 parser, there are some standard things to do
  set fromhost, fromhost-ip, timereceived
  if a pri is not set, a default needs to be set
  pri should be broken up into the normal facility/severity
  if timestamp and hostname are not set, they should be set to timereceived and fromhost

NICE TO HAVES

like mmnormalize, be able to specify the root of the resulting tree (default $!)

config options to be able to set the mapping to the standard properties, for example:
  timestamp="$!@timestamp" #logstash
  msg="$rawmsg"
  msg="$!msg"
  msg="$!Message" #nxlog

**Comment by chenryn** [comment]
+1

2016-11-25 0:24 GMT+08:00 davidelang <notifications@github.com>:

**Comment by rgerhards** [comment]
implemented via https://github.com/rsyslog/rsyslog/pull/1465, in v8.29
