### ISSUE TITLE
Rsyslog not completing Initialization on IBM AIX

### ISSUE THREAD

**Issue by vigorousblessings** [rsyslog/rsyslog#1285]
Hello Everyone, 

We use IBM AIX 7.1 in my environment. I downloaded RSYSLOG from the AIX IBM Expansion pack (Rsyslog v8.4.2) and installed it successfully but having issues getting it to run successfully. For some reasons I cannot get it to pass 'in child, finalizing initialization' stage as shown in the debug log. 

Please find attached files.

[_Rsyslog.conf.txt](https://github.com/rsyslog/rsyslog/files/617112/_Rsyslog.conf.txt)
[DebugLog.txt](https://github.com/rsyslog/rsyslog/files/617113/DebugLog.txt)

**Comment by rgerhards** [comment]
This should be solved in 8.24.0, as we now merged the IBM port to AIX. If it isn't with that version, please let us know.
