### ISSUE TITLE
imjournal bug, logging stops if time goes backwards

### ISSUE THREAD

**Issue by davidelang** [rsyslog/rsyslog#1290]
linking to redhat bug
https://bugzilla.redhat.com/show_bug.cgi?id=1088021

when reading logs with imjournal, if the time goes backwards (ntp adjustment, user fixing the time, etc), logging stops until the journal rotates files so that imjournal is no longer reading a file that has the time go backwards.

I suspect that this is the result of the work-around that was introduced to fix imjournal corruption that caused pointers to go backwards in the file, which caused a endless loop (something checks the timestamps to detect the loop instead of the file position is my guess). I don't know if this is a bug in imjournal or in the systemd libraries.

**Comment by rgerhards** [comment]
Systemd, we just call the"get next" API. I remember that bug, it also
happens with journalctl.

Rainer
Sent from phone, thus brief.

Am 28.11.2016 17:38 schrieb "davidelang" <notifications@github.com>:
