### ISSUE TITLE
Bad proccess name

### ISSUE THREAD

**Issue by radosroka** [rsyslog/rsyslog#1292]
Hi, when I start|stop|restart rsyslog via systemctl, I see in messages line like this:

liblogging-stdlog: [origin software="rsyslogd" swVersion="8.23.0" x-pid="9698" x-info="http://www.rsyslog.com"] start

liblogging-stdlog is there intentionally ? or it really should be rsyslogd?

**Comment by radosroka** [comment]
I think that there is something wrong with this commit fdd9de9626de052b026053d81ce8084b5b654653.
In function "logmsgInternal_doWrite", MsgTAG is somehow ignored.

**Comment by rgerhards** [comment]
sorry for not yet having time to look into this. As you probably guess, that's not intentional.

**Comment by rgerhards** [comment]
fixed in 8.25
