### ISSUE TITLE
WorkDirectory set to non-existing directory creates imfile-state on /

### ISSUE THREAD

**Issue by mostolog** [rsyslog/rsyslog#1296]
Using 8.23 with this config seems to be enough to replicate this.

```
global(
	workDirectory="/home/user/this_doesnt_exists"
)
input(type="imfile" file="/logs/apps/app1.log" tag="group1/app1" addMetadata="on" readTimeout="5" PersistStateInterval="1")
```

Log shows:
> rsyslogd: $WorkDirectory: /home/user/this_doesnt_exists can not be accessed, probably does not exist - directive ignored [v8.23.0 try http://www.rsyslog.com/e/2181 ]

So perhaps this is intended behavior and it's only a doc issue. Just let me know.

**Comment by rgerhards** [comment]
We need to check if this problem still persists. IIRC it was solved.

**Comment by rgerhards** [comment]
Testing brings up that if we enforce this, it may affect existing installations. Maybe we should just go with a warning. Need to think a bit about this. See also https://github.com/rsyslog/rsyslog/issues/2558, which I think really makes sense.

**Comment by davidelang** [comment]
loud warning, otherwise we break 'working' configs.

yes it's a surprise to find them in /, but it's better than not working at all.

David Lang

**Comment by rgerhards** [comment]
@davidelang thx for the confirmation, that's exactly what concerned me.
