### ISSUE TITLE
Broken flushOnTXEnd option in omfile

### ISSUE THREAD

**Issue by tomassykora** [rsyslog/rsyslog#1297]
When flushOnTXEnd option of omfile is off, disk writes should be done when the buffer is full. Now the behaviour in rsyslog is different and this is not true. The disk writes are now done after each transaction. It was probably broken with this commit  6de01034a. According to the current code, when asyncWriting is off, Flush function is called in both cases when flushOnTXEnd is on or off. I'm not sure if this is wanted behaviour.

**Comment by tomassykora** [comment]
The else part of the mentioned commit should be executed only if flushOnTXEnd is off, otherwise the disk writes should be done in runtime/stream.c via strmWrite() function when the buffer if full. Am I right or do I missing something here?

**Comment by tomassykora** [comment]
Any updates on this? Is this at least considered as a bug? @rgerhards

**Comment by jvymazal** [comment]
Ok, investigated original bug when with flushOnTXEnd switch OFF omfile would flush buffer in middle of message, opened pull request #1353 to handle this while preserving buffering function, opinions on this? @rgerhards

**Comment by davidelang** [comment]
I agree that commit looks odd, the description of what it's trying to do doesn't make sense, that's "works as designed"

I agree that this looks like it's doing far too many flushes.

**Comment by rgerhards** [comment]
I have now had a deeper look into the issue.

Let's have a clear look of what was actually changed: From

```
	if(pData->bFlushOnTXEnd && pData->pStrm != NULL) {
		/* if we have an async writer, it controls the flush via
		 * a timeout. However, without it, we actually need to flush,
		 * else incomplete records are written.
		 */
		if(!pData->bUseAsyncWriter)
			CHKiRet(strm.Flush(pData->pStrm));
	}
```
which means flush the file if no async writer is used and flush on tx end is set; do **never** do this if the async writer is used
to
```
	if(pData->bUseAsyncWriter) {
		if(pData->bFlushOnTXEnd && pData->pStrm != NULL) {
			CHKiRet(strm.Flush(pData->pStrm));
		}
	} else {
		if(pData->pStrm != NULL) {
			CHKiRet(strm.Flush(pData->pStrm));
		}
	}
```
Which means flush the file even if async writer is used plus *flush always if not*.

Unfortunately, I can find neither email messages nor issue trackers of why this patch was applied. But I now think that the intent was to make flush work in async writer case and the *flush always if not* part was a regression. At least that would make sense to me, as someone might validly have complained that with async writing, incomplete lines were written even if configured to not do this.

Any comments?

**Comment by jvymazal** [comment]
I did not look in much depth into the async code so not sure where to put some extra flushing, but would definitely vote for reverting at least the `else` branch of commit because if we specially set via `bFlushOnTXEnd` off that we do **not** want to data flushed each transaction it makes sense not to do it.

**Comment by davidelang** [comment]
I agree it looks like a regression

David Lang
