### ISSUE TITLE
'call' should support parameters

### ISSUE THREAD

**Issue by darthmdh** [rsyslog/rsyslog#1318]
set $.dispatch = lookup("hostmap", $hostname);
    call $.dispatch

Results in:

    rsyslogd: error during parsing file /etc/rsyslog.conf, on or before line 16: invalid character '$' in 'call' statement- is there an invalid escape sequence somewhere?

Ideally, **call** would be able to use the lookup table to dispatch rulesets.  In the mean time, you can work around this by using an **if** block to match each value and then hardcode the **call** to it.  Implementing this feature would prevent the maintenance nightmare that is this workaround.

**Comment by davidelang** [comment]
one problem with this approach is that you have to figure out what to do if $.dispatch doesn't exist.

Also, since your flow can now depend on input from untrusted sources, it opens up potential for odd/bad things to happen if the contents of the variable you use in the call are not expected.

We just discussed a very similar topic on the mailing list, and I was going to open an issue on that anyway.

The discussion concluded that we probably would add the ability to call based on a variable.

**Comment by darthmdh** [comment]
I'm not sure what you mean by "untrusted sources" as the lookup table is a json file created by the admin, its as equally untrusted as the rest of the rsyslog config.  When the lookup doesn't exist, rsyslog returns the value of the nomatch parameter.

In my use case, one of the things I'm doing is splitting log files by device type, so the JSON looks like this:

```json
{ "version": 1, "nomatch": "unknown_logtype", "type":"string", "table":[
   {"index":"firewall", "value":"asa" },
   {"index":"ips01", "value":"sourcefire" },
]
}
```
and the config logic goes like this:

```rsyslog
if $.dispatch == "asa" then {
   call asa
} else if $.dispatch == "sourcefire" then {
  call sourcefire
} else if $.dispatch == "unknown_logtype" then {
  call unknown_logtype
}
# ... bored already

template(name="filelog" type="string" string="/var/log/%$.dispatch%/%HOSTNAME%/syslog")
ruleset(name="asa") {
   if $msg contains "something I want logged" then {
      action(type="omfile" dynafile="filelog")
   }
  stop
}
ruleset(name="unknown_logtype") {
  action(type="omfile" file="/var/log/rsyslog/unknown_devicetype.log")
  stop
}
```

I just thought it'd be useful to replace that ugly if .. else if .. for a hundred device types with "call $.dispatch"

I appreciate people can shoot themselves in the foot, with great power comes great responsibility :)

**Comment by davidelang** [comment]
On Thu, 8 Dec 2016, Matthew Hawkins wrote:

> I'm not sure what you mean by "untrusted sources" as the lookup table is a 
> json file created by the admin, its as equally untrusted as the rest of the 
> rsyslog config.  When the lookup doesn't exist, rsyslog returns the value of 
> the nomatch parameter.

see #1319 for my writeup on the options.

If we add the ability to do call $.var, someone is going to do call $hostname or 
similar (anything with an untested variable) and that could cause 'interesting' 
results.

That said, there are ways to make it safe, and Rainer said that it probably is a 
fairly small change (most of the needed infrastructure is already in place), so 
we will probably get the capability before we get the function table type that I 
wrote up, which is an even more streamlined approach, and allows things to be 
changed on the fly as a nice bonus.

David Lang

**Comment by darthmdh** [comment]
Sounds excellent, I agree having both 5 and 6 is the sensible way forward.

I'm closing this off in favour of #1319 given I'm not on the mailing list and you people will sort it out.

**Comment by davidelang** [comment]
I think we want to keep both open as this one will probably be implemented first.

**Comment by rgerhards** [comment]
Note that we cannot name this "call", as this would invalidate existing configs. So this needs to be something along the lines of ```call_indirect```.

**Comment by davidelang** [comment]
On Sat, 10 Dec 2016, Rainer Gerhards wrote:

> Note that we cannot name this "call", as this would invalidate existing configs. So this needs to be something along the lines of ```call_indirect```.

would it? I was thinking that all existing configs would remain valid, this 
would just make some things that are currently invalid, valid.

David Lang

**Comment by rgerhards** [comment]
> would it? I was thinking that all existing configs would remain valid, this
> would just make some things that are currently invalid, valid.

Unfortunately not. We currently use ```call rulesetname```. To support dynamic expressions, I must change the rulesetname part to be an expression. If I do this, you need to use ```call "rulesetname"``` to call a constant name. Doing anything else would involve very dirty tricks, which could not be crafted into a clean grammar.
