### ISSUE TITLE
Is this behaviour a bug ?

### ISSUE THREAD

**Issue by aizikil** [rsyslog/rsyslog#1327]
I try to set up rsyslog and I think I don't understand something or this is a bug. I use debian 8 and I've got standart rsyslog.conf file, except that I uncommented these two lines -
$ModLoad imtcp
$InputTCPServerRun 514

Next I added a few lines to config file to store remote logs -

```
ruleset(name="remote"){

        if (:msg, regex, "Django.*") then {
        action (type="omfile" file="/var/log/lab/django.log")
        }

        else if (:msg, regex "np82\snamed.*") then {
        action (type="omfile" file="/var/log/lab/np82_dns.log")
        }

        else {
        action(type="omfile" file="/var/log/lab/remote_general.log")
        }
}

input (type="imtcp" port="514" ruleset="remote")
```

When I execute rsyslogd -N1 I receive this output - 

```

rsyslogd: version 8.23.0, config validation run (level 1), master config /etc/rsyslog.conf
rsyslogd: error during parsing file /etc/rsyslog.conf, on or before line 108: invalid character ':' in expression - is there an invalid escape sequence somewhere? [v8.23.0 try http://www.rsyslog.com/e/2207 ]
```
Line 108 is first line with if statement, also I installed version 8.23.0 from backports because I thought it would resolve this problem.
I want to note that I am quite knew to syslog in general, so I've reading rsyslog docs for almost all day, and my configuration attempt is based on RainerScript. So, what is wrong ?

**Comment by aizikil** [comment]
Just in case here goes full config file -
```
#  /etc/rsyslog.conf	Configuration file for rsyslog.
#
#			For more information see
#			/usr/share/doc/rsyslog-doc/html/rsyslog_conf.html


#################
#### MODULES ####
#################

$ModLoad imuxsock # provides support for local system logging
$ModLoad imklog   # provides kernel logging support
#$ModLoad immark  # provides --MARK-- message capability

# provides UDP syslog reception
#$ModLoad imudp
#$UDPServerRun 514

# provides TCP syslog reception
$ModLoad imtcp
$InputTCPServerRun 514


###########################
#### GLOBAL DIRECTIVES ####
###########################

#
# Use traditional timestamp format.
# To enable high precision timestamps, comment out the following line.
#
$ActionFileDefaultTemplate RSYSLOG_TraditionalFileFormat

#
# Set the default permissions for all log files.
#
$FileOwner root
$FileGroup adm
$FileCreateMode 0640
$DirCreateMode 0755
$Umask 0022

#
# Where to place spool and state files
#
$WorkDirectory /var/spool/rsyslog

#
# Include all config files in /etc/rsyslog.d/
#
#$IncludeConfig /etc/rsyslog.d/*.conf


###############
#### RULES ####
###############

#
# First some standard log files.  Log by facility.
#
auth,authpriv.*			/var/log/auth.log
*.*;auth,authpriv.none		-/var/log/syslog
#cron.*				/var/log/cron.log
daemon.*			-/var/log/daemon.log
kern.*				-/var/log/kern.log
lpr.*				-/var/log/lpr.log
mail.*				-/var/log/mail.log
user.*				-/var/log/user.log

#
# Logging for the mail system.  Split it up so that
# it is easy to write scripts to parse these files.
#
mail.info			-/var/log/mail.info
mail.warn			-/var/log/mail.warn
mail.err			/var/log/mail.err

#
# Logging for INN news system.
#
news.crit			/var/log/news/news.crit
news.err			/var/log/news/news.err
news.notice			-/var/log/news/news.notice

#
# Some "catch-all" log files.
#
*.=debug;\
	auth,authpriv.none;\
	news.none;mail.none	-/var/log/debug
*.=info;*.=notice;*.=warn;\
	auth,authpriv.none;\
	cron,daemon.none;\
	mail,news.none		-/var/log/messages

#
# Emergencies are sent to everybody logged in.
#
*.emerg				:omusrmsg:*



#######################################
######### REMOTE LOGS PROCESSING ######

ruleset(name="remote"){

	if (:msg, regex, "Django.*" then { 
	action (type="omfile" file="/var/log/lab/django.log")
	}
	
	else if (:msg, regex, "np82\snamed.*") then {
	action (type="omfile" file="/var/log/lab/np82_dns.log")
	}
	
	else {
	action(type="omfile" file="/var/log/lab/remote_general.log")
	}	
}

input (type="imtcp" port="514" ruleset="remote")
```

**Comment by aizikil** [comment]
If I do something like this - 

```

ruleset(name="remote"){



#action (type="omfile" file="/var/log/lab/remote_general.log")
#
#
#
#
#}




        if ($msg regex "Django.*") then {
        action (type="omfile" file="/var/log/lab/django.log")
        }
#
#       else if ($msg regex "np82\snamed.*") then {
#       action (type="omfile" file="/var/log/lab/np82_dns.log")
#       }
#
        else {
        action(type="omfile" file="/var/log/lab/remote_general.log")
        }
}

input (type="imtcp" port="514" ruleset="remote")
```

It will complain on regex string - 
```
rsyslogd: version 8.23.0, config validation run (level 1), master config /etc/rsyslog.conf
rsyslogd: error during parsing file /etc/rsyslog.conf, on or before line 120: syntax error on token 'regex' [v8.23.0 try http://www.rsyslog.com/e/2207 ]
rsyslogd: CONFIG ERROR: could not interpret master config file '/etc/rsyslog.conf'. [v8.23.0 try http://www.rsyslog.com/e/2207 ]
```
but if I change regex to contains it would work -  

```
ruleset(name="remote"){

#action (type="omfile" file="/var/log/lab/remote_general.log")
#
#
#
#
#}




        if ($msg contains "Django[17612]:*") then {
        action (type="omfile" file="/var/log/lab/django")
        }
#
#       else if ($msg regex "np82\snamed.*") then {
#       action (type="omfile" file="/var/log/lab/np82_dns.log")
#       }
#
        else {
        action(type="omfile" file="/var/log/lab/remote_general.log")
        }
}

input (type="imtcp" port="514" ruleset="remote")
```

I don't get it (

**Comment by davidelang** [comment]
On Tue, 13 Dec 2016, aizikil wrote:

>        if (:msg, regex, "Django.*") then {

This is not valid syntax

you can do

:msg, regex, "Django.*", {
   action
}

or you can do

if $msg contains "Django" then {
   action
}

but you can't mix the two types of tests.

David Lang

**Comment by aizikil** [comment]
@davidelang  Thank you for your help !!!
I rebuilt my configuration and rsyslogd -N1 doesn't complain on conf issues, but it doesn't work out. So all the messages goes to remote_general.log ((( Did i forget something ?



```
ruleset(name="remote"){



:msg, regex, "ntshrk.*" {
action (type="omfile" file="/var/log/lab/ntsharks") }


action (type="omfile" file="/var/log/lab/remote_general.log")

}

input (type="imtcp" port="514" ruleset="remote")
```

**Comment by davidelang** [comment]
what did you intend to have happen?

your ruleset says that all los should be written to the remote_general.log file 
and that some logs should also be written to the ntsharks file

David Lang

**Comment by aizikil** [comment]
@davidelang once again thank for not leaving me alone ! 
All logs are written to the remote_general.log file, but logs that match regex aren't written to ntsharks file, but they should as you sad, so I suppose this is a bug, isnt it ? 

In general i'm trying to achieve that some logs that match regex are written to different files and all other logs that do not match regex are written to remote_general.log file.

Thank you.

**Comment by davidelang** [comment]
The first question I have is do you really require a regex? a regex is very 
expensive and from your examples, is actually not the right tool for the job.

rsyslog as the startswith and contains functions. If you are looking for 
messages that contain a string (all your examples so far match this), you should 
use it, not regex. If you know the string should always be at the start of 
something, you should use startswith as it's both faster and more reliable

if you really need to use a regex, look at the functions here:

http://www.rsyslog.com/doc/v8-stable/rainerscript/index.html

I think you need to use re_match.

David Lang

**Comment by aizikil** [comment]
Yep, because I have a few netsharks and they give me this kind of a string -

`Dec 14 22:59:01 ntshrk110 `
`Dec 14 22:59:02 ntshrk120 `

So if use contains functions, I will need to create a rule for every shark, because documentation says that contains function match exact string and of course creating tons of rules is inconvenient.

So I've tested your proposal -

```
ruleset(name="remote"){



if re_match($msg,"ntshark.*") then { action (type="omfile" file="/var/log/lab/ntsharks") }


action (type="omfile" file="/var/log/lab/remote_general.log")

}


input (type="imtcp" port="514" ruleset="remote")
```
and nothing changed, all remote logs are written to remote_general.log file and re_match do nothing.

Maybe I should enable some module ?

**Comment by rgerhards** [comment]
Use $rawmsg instead of $msg.

Rainer

Sent from phone, thus brief.

Am 14.12.2016 21:09 schrieb "aizikil" <notifications@github.com>:

**Comment by davidelang** [comment]
On Wed, 14 Dec 2016, aizikil wrote:

> Yep, because I have a few netsharks and they give me this kind of a string -
>
> `Dec 14 22:59:01 ntshrk110 `
> `Dec 14 22:59:02 ntshrk120 `

that's not the message, that's the header

try

if $hostname startswith "ntshrk" then

> So if use contains functions, I will need to create a rule for every shark, 
> because documentation says that contains function match exact string and of 
> course creating tons of rules is inconvenient.

no.

if $msg contains "ntshrk"

is almost exactly the same thing as looking for a regex match of "ntshrk.*", the 
only difference is that the regex requires that ntshrk not be at the very end of 
the message

write the logs out with the template RSYSLOG_DebugFormat and look at the 
results, that will show you what's in each variable and you will understand why 
your search for that string in $msg didn't work.

David Lang

> So I've tested your proposal -
>
> ```
> ruleset(name="remote"){
>
>
>
> if re_match($msg,"ntshark.*") then { action (type="omfile" file="/var/log/lab/ntsharks") }



>
> action (type="omfile" file="/var/log/lab/remote_general.log")
>
> }
>
>
> input (type="imtcp" port="514" ruleset="remote")
> ```
> and nothing changed, all remote logs are written to remote_general.log file and re_match do nothing.
>
> Maybe I should enable some module ?
>
>
>
>
>

**Comment by aizikil** [comment]
@rgerhards  Thank you ! I've tried and it works !!!


>  So if use contains functions, I will need to create a rule for every shark,
>  because documentation says that contains function match exact string and of
>  course creating tons of rules is inconvenient.
> no.

This information I read from the documentation - 

```
contains
    Checks if the string provided in value is contained in the property. There must be an exact match, wildcards are not supported.
```
For me, exact match is, for example if we search ntshrk, the string that match should be " ntshrk " please note a space at the start of the string and at the end. Anyway, I understood your explanation, thank you !

> write the logs out with the template RSYSLOG_DebugFormat and look at the results, that will show you what's in each variable and you will understand why your search for that string in $msg didn't work.

@davidelang Thank you for this tip it's really awesome !!!!

So let's try to use it !

```

ruleset(name="remote"){


if $hostname startswith "ntshark" then { action (type="omfile" file="/var/log/lab/ntsharks") }


action (type="omfile" file="/var/log/lab/remote" template="RSYSLOG_DebugFormat")

}


input (type="imtcp" port="514" ruleset="remote")
```
This one works !. Here goes log dump -

```
Debug line with all properties:
FROMHOST: '***.***.**', fromhost-ip: '192.168.50.110', HOSTNAME: 'ntshrk110', PRI: 78,
syslogtag 'CROND[29288]:', programname: 'CROND', APP-NAME: 'CROND', PROCID: '29288', MSGID: '-',
TIMESTAMP: 'Dec 15 14:39:01', STRUCTURED-DATA: '-',
msg: ' (root) CMD (/usr/sbin/check-ntp.pl >/dev/null 2>&1)'
escaped msg: ' (root) CMD (/usr/sbin/check-ntp.pl >/dev/null 2>&1)'
inputname: imtcp rawmsg: '<78>Dec 15 14:39:01 ntshrk110 CROND[29288]: (root) CMD (/usr/sbin/check-ntp.pl >/dev/null 2>&1)'
$!:
$.:
$/:
```

Guys thank you very much indeed !!! I really appreciate your help !!!
