### ISSUE TITLE
GSSAPI not encrypting

### ISSUE THREAD

**Issue by eng3** [rsyslog/rsyslog#1329]
Each Host has host principal in keytab and has active ticket

Client: 
$ModLoad omgssapi
...
\*.\* :omgssapi:server

Server:
$ModLoad imgssapi
$InputGSSServerRun 514
...

log data can clearly be read going over network using tcpdump

Also, ticket cache file cannot be read unless selinux is disabled

**Comment by bodik** [comment]
have you tried to explicitly set gssmode ? 
$gssmode encryption.

i believe that by default gssapi uses only integrity setting by default

https://github.com/bodik/rsyslog2/blob/master/puppet/rsyslog/templates/etc/rsyslog.d/meta-remote-omgssapi.conf.erb#L4
