### ISSUE TITLE
Missing documentation for recover_qi.pl script

### ISSUE THREAD

**Issue by jvymazal** [rsyslog/rsyslog#1339]
The tools/recover_qi.pl script is not documented anywhere, can be tested on any RPM-based distro by running "$ rpm -qal 'rsyslog*' | xargs grep -i recover.qi 2>/dev/null" which does not yield any useful information

It is possible to add t least a brief mention of purpose and usage please?

**Comment by rgerhards** [comment]
Would you be willing to contribute this to https://github.com/rsyslog/rsyslog-doc?

**Comment by jvymazal** [comment]
Ok, did some try to understand what it does and drop at least few lines to queues concept (enclosed) 
[queues.rst.patch.txt](https://github.com/rsyslog/rsyslog/files/670749/queues.rst.patch.txt)
