### ISSUE TITLE
rsyslog-kafka package not available for ubuntu 16.04

### ISSUE THREAD

**Issue by eli-jordan** [rsyslog/rsyslog#1341]
I raised this issue over on the ubuntu packing repo without a response https://github.com/rsyslog/rsyslog-pkg-ubuntu/issues/53

**Comment by rgerhards** [comment]
I guess the problem is that there are no contributors for rsyslog-pkg-ubuntu. I'll see if I can find someone who does this.

**Comment by lozair31** [comment]
we want use this output but it seems to be difficult to maintain it manually if 'upstream" packages doesn't provide it.

do you think Kafka module could be included in future release ?

**Comment by rgerhards** [comment]
@friedl do you think you can add it? There don't seem to be too many dependencies, so this should not be too hard (I hope)

**Comment by friedl** [comment]
Added omkafka to xenial, yakkety and zesty.
