### ISSUE TITLE
Assert Failure in imtcp.c

### ISSUE THREAD

**Issue by lilgreenwein** [rsyslog/rsyslog#1343]
[debug_log.txt](https://github.com/rsyslog/rsyslog/files/667106/debug_log.txt)
I’m working setting up a syslog pipeline with rsyslog at the front, and I’m running in to an issue with rsyslogd core dumping when I try to start it. Debug log shows everything loading fine, then this:

```
4473.240773513:imtcp.c        : nspoll.c:147 ISOBJ assert failure: invalid object type, expected 'netstrms' actual 'nspoll', cookie: BADEFEE
rsyslogd: nspoll.c:147: SetDrvrName: Assertion `0' failed.
```

Then it core dumps.  Attached is a full debug log (hostnames and dirs scrubbed)

Basic setup is this - rsyslog listens on UDP, plain TCP, TLS and RELP ports, parses the syslogtag and outputs to a Kafka topic of the same name via omkafka. UDP, TCP and RELP work as intended, and the issue occurs on both 8.22 and 8.23.  In my opinion it’s likely a configuration issue

My configuration is setup in a straight forward include structure, my main rsyslog.conf file looks like:

```
$IncludeConfig /<app_dir>/managed_by_ansible/rsyslog/etc/rsyslog.d/globals/*.conf
$IncludeConfig /<app_dir>/managed_by_ansible/rsyslog/etc/rsyslog.d/modules/*.conf
$IncludeConfig /<app_dir>/managed_by_ansible/rsyslog/etc/rsyslog.d/templates/*.conf
$IncludeConfig /<app_dir>/managed_by_ansible/rsyslog/etc/rsyslog.d/inputs/*.conf
$IncludeConfig /<app_dir>/managed_by_ansible/rsyslog/etc/rsyslog.d/rules/*.conf
$IncludeConfig /<app_dir>/managed_by_ansible/rsyslog/etc/rsyslog.d/*.conf
```

I have a number of small conf files from there:

```
./rsyslog.conf
./rsyslog.d
./rsyslog.d/globals
./rsyslog.d/globals/01_common.conf
./rsyslog.d/globals/02_main_queue.conf
./rsyslog.d/inputs
./rsyslog.d/inputs/01_udp.conf
./rsyslog.d/inputs/02_tcp.conf
./rsyslog.d/inputs/03_tls.conf
./rsyslog.d/inputs/04_relp.conf
./rsyslog.d/modules
./rsyslog.d/modules/01_imudp.conf
./rsyslog.d/modules/02_imtcp.conf
./rsyslog.d/modules/03_imtls.conf
./rsyslog.d/modules/04_imrelp.conf
./rsyslog.d/modules/05_imfile.conf
./rsyslog.d/modules/09_impstats.conf
./rsyslog.d/modules/20_omkafka.conf
./rsyslog.d/rules
./rsyslog.d/rules/00_rsyslogd_internal.conf
./rsyslog.d/rules/01_udp2kafka.conf
./rsyslog.d/rules/02_tcp2kafka.conf
./rsyslog.d/rules/03_tls2kafka.conf
./rsyslog.d/rules/04_relp2kafka.conf
./rsyslog.d/rules/50_sawmill_stats.conf
./rsyslog.d/templates
./rsyslog.d/templates/kakfa_json.conf
./rsyslog.d/templates/local_files.conf
```

The dump occurs during the loading of the TLS portion (imtcp), here’s the conf files for the TLS config (scrubbed):

03_tls.conf:

```
input(
   type    = "imtcp"
   port    = "10448"
   ruleset = "tls_10448"
)
```

03_imtls.conf:

```
module(
   load                  = "imtcp"
   maxSessions           = "300"
   StreamDriver.Name     = "gtls"
   StreamDriver.Mode     = "1"
   StreamDriver.AuthMode = "x509/name"
   PermittedPeer         = [ "*.apple.com", “*.----.apple.com", “*.----.apple.com" ]
)
```

03_tls2kafka.conf:

```
ruleset(name = "tls_10448") {
   if $syslogtag startswith "sawmill_test_topic_tls" then {
       action(
           name                  = "tls10448_sawmill_test_topic_tls_to_kafka"
           type                  = "omkafka"
           # Queue configuration - in-memory up to 976.5625M, then to disk up to 1024M
           queue.spoolDirectory  = “/<app_dir>/managed_by_ansible/rsyslog/var/spool"
           queue.type            = "LinkedList"
           queue.size            = "1000000"
           queue.filename        = "tls10448_sawmill_test_topic_tls_to_kafka"
           queue.maxdiskspace    = "1024M"
           queue.saveonshutdown  = "off"
           queue.highwatermark   = "900000"
           queue.lowwatermark    = "400000"
           queue.discardseverity = "5"
           # Kafka configuration
           template              = "KAFKA_JsonLineTemplate"
           broker                = [ “broker1:9092", “broker2:9092", “broker3:9092", “broker4:9092", “broker5:9092" ]
           confParam             = ["queue.buffering.max.messages=10000"]
           topic                 = "sawmill_test_topic_tls"
           partitions.auto       = "on"
       )
       stop
   }
}
```

**Comment by lilgreenwein** [comment]
[debug_log.txt](https://github.com/rsyslog/rsyslog/files/667108/debug_log.txt)

**Comment by mostolog** [comment]
It's me or:

    PermittedPeer         = [ "*.apple.com", “*.----.apple.com", “*.----.apple.com" ]

quotes aren't correct? **“ instead of "**

**Comment by davidelang** [comment]
any chance that this is the same issue as #1332 ?

**Comment by lilgreenwein** [comment]
It doesn't seem the same as #1332 - that segfault occurs with default rsyslog.conf.  This issue goes away when TLS config is taken out of the picture

**Comment by lilgreenwein** [comment]
It is worth mentioning that in my environment rsyslogd is NOT being run as root

**Comment by davidelang** [comment]
I had missed that it went away with the TLS config.

What version of gnutls is on that system? we've had trouble in the past when 
they made incompatible changes with new versions.

David Lang

**Comment by lilgreenwein** [comment]
gnutls version 3.3.8:

```
gnutls-dane-3.3.8-14.el7_2.x86_64
gnutls-utils-3.3.8-14.el7_2.x86_64
gnutls-3.3.8-14.el7_2.x86_64
```

I don't have (and can't get) root access to test.  However the certificates I'm using are all under this app context and permissions are open for the app account.  Here's my global() config:

```
global(
    workDirectory                       = "/<app_dir>/managed_by_ansible/rsyslog"
    preserveFQDN                        = "on"
    action.reportSuspension             = "on"
    action.reportSuspensionContinuation = "on"
    defaultNetstreamDriver              = "gtls"
    defaultNetstreamDriverCAFile        = "/<app_dir>/managed_by_ansible/rsyslog/apple_certs/apple_server_cert_root_ca_cert.pem"
    defaultNetstreamDriverKeyFile       = "/<app_dir>/managed_by_ansible/rsyslog/apple_certs/SAWMILL_UAT_key.pem"
    defaultNetstreamDriverCertFile      = "/<app_dir>/managed_by_ansible/rsyslog/apple_certs/SAWMILL_UAT_cert.pem"
    senders.keepTrack                   = "on"
    senders.timeoutAfter                = "86400"
    senders.reportGoneAway              = "on"
    senders.reportNew                   = "on"
)
```

Any alternative to gnutls?  OpenSSL?

**Comment by davidelang** [comment]
On Wed, 21 Dec 2016, Andrew Griffin wrote:

> Any alternative to gnutls?  OpenSSL?

no, an app needs to be written differently for gnutls vs openssl vs ...

David Lang

**Comment by rgerhards** [comment]
This sounds like a first class bug. The reason is that the assertion
ensures proper operation in rsyslog. It is only available in debug builds,
as it slows down this. So it may be interesting to see if a release build
"works".

Rainer

Sent from phone, thus brief.

Am 21.12.2016 21:28 schrieb "davidelang" <notifications@github.com>:

**Comment by lilgreenwein** [comment]
Recompiled without --enable-debug and it works

**Comment by lilgreenwein** [comment]
This is a satisfactory workaround for me, but should we leave this issue open to track a fix for debug builds?

**Comment by rgerhards** [comment]
Yes, please let it open. This indicates most probably a real problem (or
invalid debug code ;-)).

Sent from phone, thus brief.

Am 21.12.2016 22:21 schrieb "Andrew Griffin" <notifications@github.com>:

**Comment by rgerhards** [comment]
I checked the code, it is indeed just a problem with the debugging
instrumentation.

Rainer

Sent from phone, thus brief.

Am 21.12.2016 22:24 schrieb "Rainer Gerhards" <rgerhards@hq.adiscon.com>:
