### ISSUE TITLE
clarify date format property in documentation

### ISSUE THREAD

**Issue by vit1251** [rsyslog/rsyslog#1350]
I found unclarify describe date format in actual v8 documentation.
Could you describe more detail about what kind of dateformat type is exist (i.e. only alias like rfc3999 exists).
Could I setup my specific date format like "%Y-%m-%d %h:%m:%S %o"? How to do that and where this information could I found in documentation?

**Comment by davidelang** [comment]
On Sat, 31 Dec 2016, Vitold S wrote:

> I found unclarify describe date format in actual v8 documentation.
> Could you describe more detail about what kind of dateformat type is exist (i.e. only alias like rfc3999 exists).
> Could I setup my specific date format like "%Y-%m-%d %h:%m:%S %o"? How to do that and where this information could I found in documentation?

to set dates in output templates, you use the property replacer to format the 
date, possibly extracting specific columns

http://www.rsyslog.com/doc/v8-stable/configuration/property_replacer.html

David Lang

**Comment by jebl01** [comment]
The docs are still very unclear when it comes to *list templates*.

`property(name="timereported" dateformat="?????")`

**Comment by rgerhards** [comment]
@jebl01 as some quick help, from the doc @davidelang mentioned excerpt below. This probably needs to be replicated to the template section. But maybe it already helps.

```
date-utc
convert data to UTC prior to outputing it (available since 8.18.0)
date-mysql
format as mysql date
date-rfc3164
format as RFC 3164 date
date-rfc3164-buggyday
similar to date-rfc3164, but emulates a common coding error: RFC 3164 demands that a space is written for single-digit days. With this option, a zero is written instead. This format seems to be used by syslog-ng and the date-rfc3164-buggyday option can be used in migration scenarios where otherwise lots of scripts would need to be adjusted. It is recommended not to use this option when forwarding to remote hosts - they may treat the date as invalid (especially when parsing strictly according to RFC 3164).

This feature was introduced in rsyslog 4.6.2 and v4 versions above and 5.5.3 and all versions above.

date-rfc3339
format as RFC 3339 date
date-unixtimestamp
Format as a unix timestamp (seconds since epoch)
date-year
just the year part (4-digit) of a timestamp
date-month
just the month part (2-digit) of a timestamp
date-day
just the day part (2-digit) of a timestamp
date-hour
just the hour part (2-digit, 24-hour clock) of a timestamp
date-minute
just the minute part (2-digit) of a timestamp
date-second
just the second part (2-digit) of a timestamp
date-subseconds
just the subseconds of a timestamp (always 0 for a low precision timestamp)
date-tzoffshour
just the timezone offset hour part (2-digit) of a timestamp
date-tzoffsmin
just the timezone offset minute part (2-digit) of a timestamp. Note that this is usually 0, but there are some time zones that have offsets which are not hourly-granular. If so, this is the minute offset.
date-tzoffsdirection
just the timezone offset direction part of a timestamp. This specifies if the offsets needs to be added (“+”) or subtracted (“-“) to the timestamp in order to get UTC.
date-ordinal
returns the ordinal for the given day, e.g. it is 2 for January, 2nd
date-week
returns the week number
date-wday
just the weekday number of the timstamp. This is a single digit, with 0=Sunday, 1=Monday, …, 6=Saturday.
date-wdayname
just the abbreviated english name of the weekday (e.g. “Mon”, “Sat”) of the timestamp.
```

**Comment by jebl01** [comment]
>This probably needs to be replicated to the template section.

Yes please!

>But maybe it already helps.

Nope... :-)

**Comment by rgerhards** [comment]
> But maybe it already helps.
> 
> Nope... :-)

sorry, I am stuck in my own thinking. Could you elaborate a bit of what you would like to see -- I would just have copied that text over ;-) @deoren do you see what I miss?

**Comment by jebl01** [comment]
The absolute dream would be if it was possible to do something like this:

`property(name="timereported" dateformat="yyyy-MM-dd'T'HH:mm:ss.SSSXXX")`

If not, how can I combine the different `date-*` properties to accomplish the same?

**Comment by rgerhards** [comment]
> The absolute dream would be if it was possible to do something like this:
> 
> property(name="timereported" dateformat="yyyy-MM-dd'T'HH:mm:ss.SSSXXX")

That's actually not a doc issue but rather a feature request -- maybe it's worth creating one (but the 8.33 timeframe is already extremely full, so I doubt it'll happen within the next couple of weeks). Maybe there even already is one, I am not sure...

You can achieve this by doing a couple of property references:
```
property(name="timereported" dateformat="date-year")
constant(value="-")
property(name="timereported" dateformat="date-month")
constant(value="-")
property(name="timereported" dateformat="date-day")
constant(value="'T'")
...
```
This could be a bit streamlined by using date-rfc3339 and substrings, but ATM I do not have time to try it out exactly myself and I do not like to give an example that is too far from working...

**Comment by davidelang** [comment]
That is the long term goal, but we are not there yet. It's a real pain to do it 
today, but possible (you would have to keep repeating the timereported property 
with different formats)

but check that the format you want isn't one of the supported ones.

**Comment by rgerhards** [comment]
> but check that the format you want isn't one of the supported ones.

It's close to rfc3339, but the single quotes around the ```T``` (```'T'```) make it different...

**Comment by jebl01** [comment]
`yyyy-MM-dd'T'HH:mm:ss.SSSXXX` was just an example to crank in as much as possible in the formatting example :-)
My desired format is more like `yyMMdd HH:mm:ss.SSS` (+ converted to UTC)...

But thanks anyway, the "repeating the timereported property" technique will have to do for now :-)

**Comment by rgerhards** [comment]
@PascalWithopf could you add a bit to the doc?
