### ISSUE TITLE
mmrm1stspace copies the entire message back one character, is that necessary?

### ISSUE THREAD

**Issue by portante** [rsyslog/rsyslog#1358]
Just reviewing the `mmrm1stspace` code a bit, and I noticed that it appears to copy the entire message to remove the one space.

Would it be possible to avoid that by just changing the message structure to increment the message offset in the raw message to avoid the memory copies?

**Comment by rgerhards** [comment]
Unfortunately not, as the raw message shall also be corrected. I think (but have not verified due to the first reason) that the offset just points after PRI, not at any of the other fields.
