### ISSUE TITLE
imjournal programname name parsing problem when long programname

### ISSUE THREAD

**Issue by hese10** [rsyslog/rsyslog#1361]
It seems that rsyslog (imjournal plugin?) has bug that it does not get programname property at all in some case, but just empty string.
This was seen when outputting%programname% into file as separate field. The output format in this case was :
`template(name="FileFormat2" type="string" string="%timereported:::date-rfc3164%.%timereported:::date-subseconds% %syslogseverity-text% %HOSTNAME:F,46:1:uppercase% %programname% %syslogtag:R,ERE,1,FIELD:^(.*):--end%:%msg:::sp-if-no-1st-sp%%msg:::drop-cc%\n")
`
programname is correct in bash case, but empty in that long one "/opt/testi/SS_TstBash/bin/bash"
```
Jan 12 20:00:05.170717 info TMN-0 -bash -bash[2206]: HISTORY: PID=2206 UID=0 /opt/testi/SS_TstBash/bin/bash
Jan 12 20:00:07.071914 info TMN-0  /opt/testi/SS_TstBash/bin/bash[13629]: HISTORY: PID=13629 UID=0 pwd
```

so is there some limit in rsyslog for programname, and when over it, there comes empty programname?

**Comment by davidelang** [comment]
On Thu, 12 Jan 2017, hese10 wrote:

> It seems that rsyslog has bug that it does not get programname property at all, but just empty string.
> This was seen when outputting%programname% into file as separate field. The output format in this case was :
> `template(name="FileFormat2" type="string" string="%timereported:::date-rfc3164%.%timereported:::date-subseconds% %syslogseverity-text% %HOSTNAME:F,46:1:uppercase% %programname% %syslogtag:R,ERE,1,FIELD:^(.*):--end%:%msg:::sp-if-no-1st-sp%%msg:::drop-cc%\n")
> `
> programname is correct in bash case, but empty in that long one "/opt/testi/SS_TstBash/bin/bash"
> ```
> Jan 12 20:00:05.170717 info TMN-0 -bash -bash[2206]: HISTORY: PID=2206 UID=0 /opt/testi/SS_TstBash/bin/bash
> Jan 12 20:00:07.071914 info TMN-0  /opt/testi/SS_TstBash/bin/bash[13629]: HISTORY: PID=13629 UID=0 pwd
> ```
>
> so is there some limit in rsyslog for programname, and when over it, there comes empty programname?

Yes, the RFC3184 parser has lots of heuristics to try and guess what to do when 
it receives a malformed message. IIRC, the RFC limits programnames to 32 
characters.

But with the sample logs you show, I would expect that the hostname would be 
'info' and the programname would be 'TMN-0'

although the invalid timestamp may be making it so that the entire log message 
is unparsable.

Please write the logs out with the format RSYSLOG_DebugFormat to see exactly 
what ends up in what variable.

David Lang

**Comment by hese10** [comment]
here is the output for that problem log:
```
Debug line with all properties:
FROMHOST: 'TMN-0', fromhost-ip: '127.0.0.1', HOSTNAME: 'TMN-0', PRI: 14,
syslogtag '/opt/testi/SS_TstBash/bin/bash[23135]:', programname: '', APP-NAME: '', PROCID: '23135', MSGID: '-',
TIMESTAMP: 'Jan 12 20:39:34', STRUCTURED-DATA: '-',
msg: 'HISTORY: PID=23135 UID=0 exit'
escaped msg: 'HISTORY: PID=23135 UID=0 exit'
inputname: imjournal rawmsg: 'HISTORY: PID=23135 UID=0 exit'
$!:{ "PRIORITY": "6", "_UID": "0", "_GID": "0", "_BOOT_ID": "90e28d1fa3bb49149a11a905c940cac3", "_MACHINE_ID": "ef4c3cde36214893a0fa49d71f9b7b6b", "_HOSTNAME": "TMN-0", "_TRANSPORT": "syslog", "SYSLOG_FACILITY": "1", "SYSLOG_IDENTIFIER": "\/opt\/testi\/SS_TstBash\/bin\/bash", "SYSLOG_PID": "23135", "_PID": "23135", "MESSAGE": "HISTORY: PID=23135 UID=0 exit", "_SOURCE_REALTIME_TIMESTAMP": "1484246374811182" }
$.:
$/:

```

**Comment by davidelang** [comment]
On Thu, 12 Jan 2017, hese10 wrote:

> here is the output for that problem log:
> ```
> Debug line with all properties:
> FROMHOST: 'TMN-0', fromhost-ip: '127.0.0.1', HOSTNAME: 'TMN-0', PRI: 14,
> syslogtag '/opt/testi/SS_TstBash/bin/bash[23135]:', programname: '', APP-NAME: '', PROCID: '23135', MSGID: '-',
> TIMESTAMP: 'Jan 12 20:39:34', STRUCTURED-DATA: '-',
> msg: 'HISTORY: PID=23135 UID=0 exit'
> escaped msg: 'HISTORY: PID=23135 UID=0 exit'
> inputname: imjournal rawmsg: 'HISTORY: PID=23135 UID=0 exit'
> $!:{ "PRIORITY": "6", "_UID": "0", "_GID": "0", "_BOOT_ID": "90e28d1fa3bb49149a11a905c940cac3", "_MACHINE_ID": "ef4c3cde36214893a0fa49d71f9b7b6b", "_HOSTNAME": "TMN-0", "_TRANSPORT": "syslog", "SYSLOG_FACILITY": "1", "SYSLOG_IDENTIFIER": "\/opt\/testi\/SS_TstBash\/bin\/bash", "SYSLOG_PID": "23135", "_PID": "23135", "MESSAGE": "HISTORY: PID=23135 UID=0 exit", "_SOURCE_REALTIME_TIMESTAMP": "1484246374811182" }
> $.:
> $/:
>
> ```

Ok, this is arriving via imjournal, so the RFC3164 parser is not involved.

It looks like the journal is not passing a programname to rsyslog, the most it's 
passing is the syslog_identifier, which is getting put into syslogtag.

Rainer will need to comment on why this isn't getting into programname/ap-name 
(or someone will need to dig into imjournal)

David Lang

**Comment by rgerhards** [comment]
More comments later but is there a reason you use rfc5424 programname instead of syslogtag?

**Comment by davidelang** [comment]
On Fri, 13 Jan 2017, Rainer Gerhards wrote:

> More comments later but is there a reason you use rfc5424 programname instead of syslogtag?

I would want to be able to use programname instead of syslogtag exactly because 
syslogtag includes the pid, so I would have to use startswith instead of == in 
lookups (or do other manipulations to eliminate the pid portion of the 
syslogtag)

David Lang

**Comment by rgerhards** [comment]
I reviewed the code and I must admit that I mistook programname with app-name. Programname is nota RFC5424 construct but rather a BSD one. The source code comment says it all:

````
 * Programname
 * is a BSD concept, it is the tag without any instance-specific information.
 * Precisely, the programname is terminated by either (whichever occurs first):
 * - end of tag
 * - nonprintable character
 * - ':'
 * - '['
 * - '/'
 * The above definition has been taken from the FreeBSD syslogd sources.
````

That said, I think it still makes sense to include an option that permits slashes inside the programname.

**Comment by rgerhards** [comment]
Just to avoid unnecessary discussion: this is the link the the FreeBSD code in question: https://github.com/freebsd/freebsd/blob/master/usr.sbin/syslogd/syslogd.c#L1068

**Comment by rgerhards** [comment]
solved via doc improvement and new global option as can be seen above.
