### ISSUE TITLE
set/unset statement do not check variable name validity

### ISSUE THREAD

**Issue by rgerhards** [rsyslog/rsyslog#1377]
only JSON-based variables can be use with set and unset. Unfortunately, this restriction is not checked. If an invalid variable is given (e.g. ```$invalid```), this is not detected upon config processing on startup. During execution phase, this can lead to a segfault, a memory leak (see https://github.com/rsyslog/rsyslog/issues/1376) or other types of problems.

**Comment by kkaarreell** [comment]
Out of curiosity, is "$.foo!" a valid statement?

**Comment by davidelang** [comment]
On Thu, 15 Jun 2017, Karel Srot wrote:

> Out of curiosity, is "$.foo!" a valid statement?

good question, $.foo is a valid variable name, $.foo!bar is a valid variable 
name, $.foo! probably will not work (it hasn't been defined as valid or invalid, 
but I'll bet that it doesn't work, and I can't think of a reason to try and make 
it work)
