### ISSUE TITLE
imfile module readTimeout do not time out

### ISSUE THREAD

**Issue by levi-lq** [rsyslog/rsyslog#1379]
My config is:
module(load="imfile" timeoutGranularity="10")
input(type="imfile" file="/data/log/slow_mysql.log" tag="mysql_slow" ruleset="mysql_slow_rs" readTimeout="15" startmsg.regex="^# Time")

But the last log still held, the readTimeout does not work,Can anyone help me?
Thanks!

**Comment by rgerhards** [comment]
which rsyslog version?

**Comment by fttyX** [comment]
Same problem. 8.25.0

Steps to reproduce:
1. imfile sections as in original message above. Messages delivery are working fine.
2. restart rsyslog service (centos 7 here).
3. readTimeout stops working.

Fix that works for me: stop rsyslog, delete imfile state file for my source logfile and start again.

Any idea what can be wrong?
