### ISSUE TITLE
rsyslogd-2007: action 'action 0' suspended, next retry is Wed Jan 25 13:08:55 2017 [v8.16.0 try http://www.rsyslog.com/e/2007 ]

### ISSUE THREAD

**Issue by voyalab** [rsyslog/rsyslog#1383]
**OS : CentOS 5.11 (Final)
Rsyslog version :  v8.16.0
Log Size :  > 7 GB**

I am using Rsyslog to send logs to Logstash from TCP ports. It is working fine for few log files. But when I moved to production I am getting error rsyslogd-2007.

My rsyslog.conf

```

# rsyslog configuration file
# note that most of this config file uses old-style format,
# because it is well-known AND quite suitable for simple cases
# like we have with the default config. For more advanced 
# things, RainerScript configuration is suggested.

# For more information see /usr/share/doc/rsyslog-*/rsyslog_conf.html
# If you experience problems, see http://www.rsyslog.com/doc/troubleshoot.html

#### MODULES ####

module(load="imfile" PollingInterval="10")
#module(load="imuxsock") # provides support for local system logging (e.g. via logger command)
#module(load="imklog")   # provides kernel logging support (previously done by rklogd)
#module(load"immark")  # provides --MARK-- message capability

# Provides UDP syslog reception
# for parameters see http://www.rsyslog.com/doc/imudp.html
#module(load="imudp") # needs to be done just once
#input(type="imudp" port="514")

# Provides TCP syslog reception
# for parameters see http://www.rsyslog.com/doc/imtcp.html
#module(load="imtcp") # needs to be done just once
#input(type="imtcp" port="514")


#### GLOBAL DIRECTIVES ####

# Use default timestamp format
#$template FileFormat,"%TIMESTAMP:::date-rfc3339% %HOSTNAME% %syslogtag%%msg:::sp-if-no-1st-sp%%msg:::drop-last-lf%\n"
#$template ForwardFormat,"%msg:::sp-if-no-1st-sp%%msg%"
#$ActionFileDefaultTemplate ForwardFormat


# File syncing capability is disabled by default. This feature is usually not required,
# not useful and an extreme performance hit
#$ActionFileEnableSync on

# Include all config files in /etc/rsyslog.d/
$IncludeConfig /etc/rsyslog.d/*.conf


#### RULES ####

# Log all kernel messages to the console.
# Logging much else clutters up the screen.
#kern.*                                                 /dev/console

# Log anything (except mail) of level info or higher.
# Don't log private authentication messages!
*.info;mail.none;authpriv.none;cron.none                /var/log/messages

# The authpriv file has restricted access.
authpriv.*                                              /var/log/secure

# Log all the mail messages in one place.
mail.*                                                  /var/log/maillog


# Log cron stuff
cron.*                                                  /var/log/cron

# Everybody gets emergency messages
*.emerg                                                 :omusrmsg:*

# Save news errors of level crit and higher in a special file.
uucp,news.crit                                          /var/log/spooler

# Save boot messages also to boot.log
local7.*                                                /var/log/boot.log


# ### begin forwarding rule ###
# The statement between the begin ... end define a SINGLE forwarding
# rule. They belong together, do NOT split them. If you create multiple
# forwarding rules, duplicate the whole block!
# Remote Logging (we use TCP for reliable delivery)
#
# An on-disk queue is created for this action. If the remote host is
# down, messages are spooled to disk and sent when it is up again.
$WorkDirectory /var/lib/rsyslog # where to place spool files
$ActionQueueFileName fwdRule1 # unique name prefix for spool files
$ActionQueueMaxDiskSpace 4g   # 1gb space limit (use as much as possible)
$ActionQueueSaveOnShutdown on # save messages to disk on shutdown
$ActionQueueType LinkedList   # run asynchronously
$ActionResumeRetryCount -1    # infinite retries if host is down

# Use standard RFC5424 log format for local logs
#$ActionFileDefaultTemplate RSYSLOG_SyslogProtocol23Format
# remote host is: name/ip:port, e.g. 192.168.0.1:514, port optional
#*.* @@remote-host:514
# ### end of the forwarding rule ###

```

And my logging configuration file, 
```
main_queue(
  queue.workerThreads="4"
  queue.dequeueBatchSize="1000"
  queue.highWatermark="3000000"    # max no. of events to hold in memory
  queue.lowWatermark="200000"     # use memory queue again, when it's back to this level
  queue.spoolDirectory="/var/lib/rsyslog"  # where to write on disk
  queue.fileName="stats_ruleset"
  queue.maxDiskSpace="5g"        # it will stop at this much disk space
  queue.size="5000000"           # or this many messages
  queue.saveOnShutdown="on"      # save memory queue contents to disk when rsyslog is exiting
)
template(name="ForwardFormatQueries" type="list") {
    property(name="msg" spifno1stsp="on" )
    property(name="msg")
}
input(type="imfile"
      File="/var/log/searchservice-liveA2/queries.log.*"
      Tag="queries-log"
      startmsg.regex="^([0-9][0-9][0-9][0-9])-([0-9][0-9])-([0-9][0-9])[[:space:]]([0-9][0-9]):([0-9][0-9]):([0-9][0-9]),([0-9]|[0-9][0-9]|[0-9][0-9][0-9]|[0-9][0-9][0-9][0-9])"
)
if $programname == 'queries-log' then {
   action(
        type="omfwd"
        Target="###-###-###-###"
        Port="5002"
        Protocol="tcp"
        Template="ForwardFormatQueries"
    )
    stop
}

```
Am I missing something, What will be the possible solution for that?

**Comment by davidelang** [comment]
On Thu, 26 Jan 2017, Jakir Patel wrote:

> **OS : CentOS 5.11 (Final)
> Rsyslog version :  v8.16.0
> Log Size :  > 7 GB**
>
> I am using Rsyslog to send logs to Logstash from TCP ports. It is working fine for few log files. But when I moved to production I am getting error rsyslogd-2007.
>
> My rsyslog.conf
>
> ```
>
> # rsyslog configuration file
> # note that most of this config file uses old-style format,
> # because it is well-known AND quite suitable for simple cases
> # like we have with the default config. For more advanced
> # things, RainerScript configuration is suggested.
>
> # For more information see /usr/share/doc/rsyslog-*/rsyslog_conf.html
> # If you experience problems, see http://www.rsyslog.com/doc/troubleshoot.html
>
> #### MODULES ####
>
> module(load="imfile" PollingInterval="10")
> #module(load="imuxsock") # provides support for local system logging (e.g. via logger command)
> #module(load="imklog")   # provides kernel logging support (previously done by rklogd)
> #module(load"immark")  # provides --MARK-- message capability
>
> # Provides UDP syslog reception
> # for parameters see http://www.rsyslog.com/doc/imudp.html
> #module(load="imudp") # needs to be done just once
> #input(type="imudp" port="514")
>
> # Provides TCP syslog reception
> # for parameters see http://www.rsyslog.com/doc/imtcp.html
> #module(load="imtcp") # needs to be done just once
> #input(type="imtcp" port="514")
>
>
> #### GLOBAL DIRECTIVES ####
>
> # Use default timestamp format
> #$template FileFormat,"%TIMESTAMP:::date-rfc3339% %HOSTNAME% %syslogtag%%msg:::sp-if-no-1st-sp%%msg:::drop-last-lf%\n"
> #$template ForwardFormat,"%msg:::sp-if-no-1st-sp%%msg%"
> #$ActionFileDefaultTemplate ForwardFormat
>
>
> # File syncing capability is disabled by default. This feature is usually not required,
> # not useful and an extreme performance hit
> #$ActionFileEnableSync on
>
> # Include all config files in /etc/rsyslog.d/
> $IncludeConfig /etc/rsyslog.d/*.conf
>
>
> #### RULES ####
>
> # Log all kernel messages to the console.
> # Logging much else clutters up the screen.
> #kern.*                                                 /dev/console
>
> # Log anything (except mail) of level info or higher.
> # Don't log private authentication messages!
> *.info;mail.none;authpriv.none;cron.none                /var/log/messages
>
> # The authpriv file has restricted access.
> authpriv.*                                              /var/log/secure
>
> # Log all the mail messages in one place.
> mail.*                                                  /var/log/maillog
>
>
> # Log cron stuff
> cron.*                                                  /var/log/cron
>
> # Everybody gets emergency messages
> *.emerg                                                 :omusrmsg:*
>
> # Save news errors of level crit and higher in a special file.
> uucp,news.crit                                          /var/log/spooler
>
> # Save boot messages also to boot.log
> local7.*                                                /var/log/boot.log
>
>
> # ### begin forwarding rule ###
> # The statement between the begin ... end define a SINGLE forwarding
> # rule. They belong together, do NOT split them. If you create multiple
> # forwarding rules, duplicate the whole block!
> # Remote Logging (we use TCP for reliable delivery)
> #
> # An on-disk queue is created for this action. If the remote host is
> # down, messages are spooled to disk and sent when it is up again.
> $WorkDirectory /var/lib/rsyslog # where to place spool files


> $ActionQueueFileName fwdRule1 # unique name prefix for spool files
> $ActionQueueMaxDiskSpace 4g   # 1gb space limit (use as much as possible)
> $ActionQueueSaveOnShutdown on # save messages to disk on shutdown
> $ActionQueueType LinkedList   # run asynchronously
> $ActionResumeRetryCount -1    # infinite retries if host is down

These only affect the next action, and only if the next action is a legacy 
format action.


> # Use standard RFC5424 log format for local logs
> #$ActionFileDefaultTemplate RSYSLOG_SyslogProtocol23Format
> # remote host is: name/ip:port, e.g. 192.168.0.1:514, port optional
> #*.* @@remote-host:514
> # ### end of the forwarding rule ###
>
> ```
>
> And my logging configuration file,
> ```
> main_queue(
>  queue.workerThreads="4"
>  queue.dequeueBatchSize="1000"
>  queue.highWatermark="3000000"    # max no. of events to hold in memory
>  queue.lowWatermark="200000"     # use memory queue again, when it's back to this level
>  queue.spoolDirectory="/var/lib/rsyslog"  # where to write on disk
>  queue.fileName="stats_ruleset"
>  queue.maxDiskSpace="5g"        # it will stop at this much disk space
>  queue.size="5000000"           # or this many messages
>  queue.saveOnShutdown="on"      # save memory queue contents to disk when rsyslog is exiting
> )
> template(name="ForwardFormatQueries" type="list") {
>    property(name="msg" spifno1stsp="on" )
>    property(name="msg")
> }
> input(type="imfile"
>      File="/var/log/searchservice-liveA2/queries.log.*"
>      Tag="queries-log"
>      startmsg.regex="^([0-9][0-9][0-9][0-9])-([0-9][0-9])-([0-9][0-9])[[:space:]]([0-9][0-9]):([0-9][0-9]):([0-9][0-9]),([0-9]|[0-9][0-9]|[0-9][0-9][0-9]|[0-9][0-9][0-9][0-9])"
> )
> if $programname == 'queries-log' then {
>   action(
>        type="omfwd"
>        Target="###-###-###-###"
>        Port="5002"
>        Protocol="tcp"
>        Template="ForwardFormatQueries"

This does not have retrycount set to -1 and does not have any queue.

>    )
>    stop
> }
>
> ```
> Am I missing something, What will be the possible solution for that?

So there are a couple things happening here

first, you do not have retries and queueing setup the way you think you do.

As a result, when the destination logstash server can't keep up, rsyslog is 
failing to deliver the log message, and suspending output to that action for a 
while.

you want to set the retries and queueing as part of the action.

But then you are going to be running into the problem that logstash can't keep 
up with you. If you are using logstash to put logs into Elasticsearch, I 
recommend that you try omelasticsearch and deliver them directly.

David Lang

**Comment by voyalab** [comment]
Thank you, David, for Reply. I am using Logstash for parsing some custom logs. I have written a parser with grok filter that's why I need logstash. What if I add retry count? What problems I 'll face on logstash side?

**Comment by voyalab** [comment]
As you said omelasticsearch , how to I parse custom logs to it ? is it `mnormalize`?

**Comment by davidelang** [comment]
On Thu, 26 Jan 2017, Jakir Patel wrote:

> Thank you, David, for Reply. I am using Logstash for parsing some custom logs. 
> I have written a parser with grok filter that's why I need logstash.

rsyslog has mmnormalize and mmgrok (mmnormalize is MUCH faster than mmgrok)

> What if I 
> add retry count? What problems I 'll face on logstash side?

simple throughput, rsyslog is several orders of magnatude faster than logstash.

David Lang

**Comment by voyalab** [comment]
Thank you, David for your Reply. I will look into it.
