### ISSUE TITLE
"WARNING: rsyslogd is running in compatibility mode" despite adding -c5 option

### ISSUE THREAD

**Issue by khba** [rsyslog/rsyslog#1384]
Hello, 
I am configuring rsyslog on Centos 6.8 and I keep getting this warning while debugging rsyslog: 

rsyslogd: WARNING: rsyslogd is running in compatibility mode. Automatically generated config directives may interfer with your rsyslog.conf settings. We suggest upgrading your config and adding -c5 as the first rsyslogd option.
rsyslogd: Warning: backward compatibility layer added to following directive to rsyslog.conf: ModLoad immark
rsyslogd: Warning: backward compatibility layer added to following directive to rsyslog.conf: MarkMessagePeriod 1200
rsyslogd: Warning: backward compatibility layer added to following directive to rsyslog.conf: ModLoad imuxsock
rsyslogd: End of config validation run. Bye.

So I add the -c5 option in /etc.sysconfig/rsyslog as asked like this : 
SYSLOGD_OPTIONS="-c5"
#or this SYSLOGD_OPTIONS="-c 5"

But I keep getting the same warning.
I only solution I found on google is to stop the service manually and restart manually like:

/sbin/rsyslogd -c5 -f /etc/rsyslog.conf 

But it doesn't change anything and I keep getting the warning :(

Anyone know what's this about?!

**Comment by davidelang** [comment]
wiht current versions this should not be needed any longer, what version are you 
running.

David Lang

**Comment by khba** [comment]
I am running  version 5.8.10. Our servers are still in centos6.8  and the rsyslog version 5.8.10 seems to be the last version provided on the repositories since when I do "yum update rsyslog"  it says there is nothing to update. 
I am happy with the functionalities of the 5.8.10 though and everything is working fine, apart those warnings I wouldn't  want to ignore. What should I do to have the 5.8.10 work without those warnings or do I have to update to rsyslog last version? If so is there a safe way to do this on centos 6.8?

**Comment by rgerhards** [comment]
I guess this is primarily a question for the centos folks. It looks like the -c5 option is not passed to rsyslog, and thus this warning. There is nothing we can do against that.
