### ISSUE TITLE
check that queue same file name is given only for one queue

### ISSUE THREAD

**Issue by rgerhards** [rsyslog/rsyslog#1385]
If the same name is specified for multiple queues, the queue files will become corrupted. Currently this is not checked, and a check should be added for obvious reasons. This should err-out during config parsing.

**Comment by davidelang** [comment]
we need a similar check for actions with the same name. It doesn't corrupt 
things if they have the same name, but it does mess up the stats.

**Comment by rgerhards** [comment]
Right - could you add an issue?

Sent from phone, thus brief.

Am 02.02.2017 10:44 vorm. schrieb "davidelang" <notifications@github.com>:
