### ISSUE TITLE
Feature Request: Support libtls or libressl / openssl

### ISSUE THREAD

**Issue by raphaelcohn** [rsyslog/rsyslog#1390]
This is probably a lot of work... but at the moment, we're unable to use rsyslog (a logging solution I really like) on our new builds because of it's use of gnutls. This isn't because gnutls is bad, or anything like it, but we have to audit our dependencies. Our other dependencies rely on the legacy openssl interfaces or it's modern, simpler replacement libtls (via libressl). Supporting and auditing two critical TLS libraries is just too much, especially with the number of CVEs TLS libraries are generating these days.

Would there be any appetite to make a change to support these? Perhaps by adopting libcurl's approach of an independent layer? I know the best way to get support is to write it and submit a PR, but much as I'd like to (:-) I don't have the time available (:-(.

(BTW, nxlog still uses SSLv3 for anyone considering an alternative. So be warned)!

**Comment by rgerhards** [comment]
Quite late, but: we already have an abstraction layer. Still quite a bit of work.

**Comment by raphaelcohn** [comment]
Ta!

**Comment by PascalWithopf** [comment]
I have analysed existing drivers and are now developing core functionalities.

This is a list of areas that need to be looked at. This will be updated as I progress with the development:
- multithreading
- allowed SSL/TLS versions

**Comment by GrayTShirt** [comment]
for CA chains I imagine many folks including myself will be interesting in using Lets Encrypt, or also including myself a self signed CA-Chain with an intermediate CA.

This link might be a useful reference: https://jamielinux.com/docs/openssl-certificate-authority/

**Comment by raphaelcohn** [comment]
Supporting Lets Encrypt would be extremely useful. For myself, it's become my go-to for most projects and I see a lot of small and medium scale businesses using it. Self-signed certificates are useful, as are custom CAs - typically for organisation-wide / deployment environment scenarios (in the latter, a common pattern is to use a CA per-environment, preventing cross-environment foul ups to some extent).

**Comment by GrayTShirt** [comment]
I know this is getting off topic but here are some more custom CA resources: 

https://www.vaultproject.io/docs/secrets/pki/index.html
https://jameshunt.us/writings/roll-your-own-x509-ca.html

**Comment by rgerhards** [comment]
@raphaelcohn 
> Supporting Lets Encrypt would be extremely useful. For myself, it's become my go-to for most projects and I see a lot of small and medium scale businesses using it. Self-signed certificates are useful, as are custom CAs - typically for organisation-wide / deployment environment scenarios (in the latter, a common pattern is to use a CA per-environment, preventing cross-environment foul ups to some extent).

Did you try Lets Encrypt with the current TLS implementation? IMHO it should work. Unfortunately, I have no time to test it out myself. If you could test, and it does not work, please open a new issue and we can see what we can do against it. Thx!

**Comment by rgerhards** [comment]
@raphaelcohn just a side-question: do you know the state (or official home page) of libssl (the new API project)? I did a quick search and it somehow doe not look too alive...

**Comment by raphaelcohn** [comment]
AHH... I meant the libressl subproject libtls. Might have got mixed up. I
have found myself substituting SSL for tls for years... Sorry.

**Comment by davidelang** [comment]
On Thu, 21 Dec 2017, Rainer Gerhards wrote:

> @raphaelcohn
>> Supporting Lets Encrypt would be extremely useful. For myself, it's become my go-to for most projects and I see a lot of small and medium scale businesses using it. Self-signed certificates are useful, as are custom CAs - typically for organisation-wide / deployment environment scenarios (in the latter, a common pattern is to use a CA per-environment, preventing cross-environment foul ups to some extent).
>
> Did you try Lets Encrypt with the current TLS implementation? IMHO it should work. Unfortunately, I have no time to test it out myself. If you could test, and it does not work, please open a new issue and we can see what we can do against it. Thx!

and if it does work, could you writeup a how-to guide to be added to the docs?

**Comment by Dinesh-Ramakrishnan** [comment]
@rgerhards @PascalWithopf : Thank you very much for the supporting openssl on rsyslog.  
1) Is there any timeline planned for this activity? Is it possible for you to share the current progress (if possible, doc,  code).  I would like to contribute (coding or testing)
2) Will there be any restriction on the openssl version that can be used with Rsyslog.

**Comment by rgerhards** [comment]
@Dinesh-Ramakrishnan thanks for your kind words and interest in this project! Unfortunately it is currently a bit stalled due to other things going on. If you would like to contribute, that would be much appreciated.

@PascalWithopf can you please point to your development branch and maybe provide some info of what was already achieved. Thanks a lot!

**Comment by PascalWithopf** [comment]
@rgerhards @Dinesh-Ramakrishnan  I'm sorry, I'm working on something else at the moment so I don't have much time for this.
This is the branch with the current changes:
https://github.com/PascalWithopf/rsyslog/tree/openssl
It fails at the handshake and there is no multi threading at the moment.

**Comment by Dinesh-Ramakrishnan** [comment]
@PascalWithopf , Thank you very much for sharing.  Will look into it and update my progress/findings.

**Comment by rgerhards** [comment]
In blunt words: but ready for merge ;-)

**Comment by Dinesh-Ramakrishnan** [comment]
@PascalWithopf, Thank you for sharing the repo.  I have built the rsyslog with your changes and hit with the TLS Handshake failure,  Currently I am debugging the same.  Meanwhile is it possible for you to provide me some hints/overview about this driver? I prefer to have a small chat.

**Comment by alorbach** [comment]
Hi @Dinesh-Ramakrishnan, are you planning on contributing to the code in near future? 
If not I will be taking over the code state from Pascal and continue on the OpenSSL implementation.

**Comment by Dinesh-Ramakrishnan** [comment]
Hi @alorbach ,  I have made a small progress by fixing the TLS handshake issue.  Now we are able to establish the connection and transfer the messages securely.  But there are lot more of TODOs and Multithread Support to be addressed.  It would be helpful you could continue further on this.  Please keep me updated on the progress ( may be sharing the commits) so that we can collaborate and complete this feature sooner. 

You can find the latest code in the link below.

https://github.com/Dinesh-Ramakrishnan/rsyslog/commit/2e276663915afea009e4adc4d1b35dc09a87aed3

**Comment by alorbach** [comment]
Hi @Dinesh-Ramakrishnan, I started already working on the OpenSSL support. 
However I had to start from scratch as the previous implementation try doesn't blend into the rsyslog network framework drivers properly. You can see my progress on my personal fork: 
https://github.com/alorbach/rsyslog-1/tree/openssl2

**Comment by Dinesh-Ramakrishnan** [comment]
Hi @alorbach,  Thank you very much for the information.  Could you please share the list of pending items and the targeted milestone?

**Comment by raphaelcohn** [comment]
@alorbach @rgerhards @Dinesh-Ramakrishnan  Thank you very much!
