### ISSUE TITLE
rsyslog with disk queue enabled shuffle logs then restore network connection

### ISSUE THREAD

**Issue by zystem** [rsyslog/rsyslog#1400]
How to reproduce
Sender
```
module(load="imfile" mode="inotify")
input(type="imfile"
      File="/var/log/1.log"
      Tag="FILE_test:")

module(load="omrelp")
:syslogtag, startswith, "FILE" action(type="omrelp" target="192.168.1.101" port="2514"
      action.resumeRetryCount="-1"
      queue.type="Disk"
      queue.filename="queue.logremote"
      queue.discardmark="1000000"
      queue.size="1000001"
      queue.maxfilesize="10m"
      queue.maxdiskspace="4g"
      queue.saveonshutdown="on")
```

receiver
```
module(load="imrelp")
input(type="imrelp" port="2514")

$template DYNtest,"/var/log/%HOSTNAME%/1.log"

#crop leading space
$template MSG,"%msg:2:999999999%\n"
:syslogtag, isequal, FILE_test:            ?DYNtest;MSG
```

Stop rsyslog on receiver

On sender run
```
for i in {1..100000}; do echo $i >> /var/log/1.log; done
```

Start rsyslog on receiver

/var/log/1.log and /var/log/%HOSTNAME%/1.log are not the same.
numbers in /var/log/%HOSTNAME%/1.log are shuffled

**Comment by rgerhards** [comment]
you mean the  message sequence is different? If so, that is expected behaviour. If you need the sequence to stay the same, you need to use a pure disk queue.

**Comment by selivan** [comment]
@rgerhards : `queue.type="Disk"` - isn't that a pure disk queue?

**Comment by rgerhards** [comment]
@selivan  jupp, sorry overlooked this (it's a very unpopular choice). So it looks like the outage causes the reordering (if that is the issue). In any case, message reordering is fine. See http://www.gerhards.net/download/LinuxKongress2010rsyslog.pdf section 7 for an in-depth explanation.
