### ISSUE TITLE
Rate limiting not logging process name

### ISSUE THREAD

**Issue by jvymazal** [rsyslog/rsyslog#1406]
This would generally help to quickly understand which process is sending more logs than the rsyslog default limit. And user does not need to go to the terminal to grep that process. 
Also assume we are analysing previous logs. Since they were collected pid could change or process could be terminated so it would not help to see pid but if name is logged it can help.

**Comment by davidelang** [comment]
how would you record this? the rate limiting makes rsyslog stop processing logs 
for a while, so you either already have the data in the logs that are processed, 
or rsyslog doesn't have the data to do the reporting you are asking for.

David Lang

**Comment by rgerhards** [comment]
merged via pr in 8.26.0
