### ISSUE TITLE
Feature request: Support pipeline parameter in omelasticsearch

### ISSUE THREAD

**Issue by BrentDouglas** [rsyslog/rsyslog#1411]
Elasticsearch 5.2 supports referencing a 'pipeline' in the query string which allows processing the message before it is inserted into the index. (https://www.elastic.co/guide/en/elasticsearch/reference/current/ingest.html)

For what looks like simple functionality to add I can see it being very useful. An example would be to translate multiline documents back from their on-the-wire representation into a readable format, which afaict is not supported within rsyslog itself.

I would be willing to add this if you think it is a reasonable proposal.

**Comment by davidelang** [comment]
This sounds like very good functionality to have, if you can create a PR for it, 
please do.

David Lang

**Comment by BrentDouglas** [comment]
It might actually be better to add a more generic parameter like `queryString` some something. I just noticed I can actually already get the behaviour I'm looking for by using `timeout="60&pipeline=the-pipeline"`

**Comment by mostolog** [comment]
What about something like omkafka confParam and topicConfParam? http://www.rsyslog.com/doc/master/configuration/modules/omkafka.html

**Comment by wdauchy** [comment]
@BrentDouglas any progress on that matter?

**Comment by rgerhards** [comment]
implemented via #1862

**Comment by BrentDouglas** [comment]
Sorry for not replying to the earlier notification, I must have missed it. Once I realised I could stick everything into the timeout parameter I didn't look into it much further.
