### ISSUE TITLE
Add chdir to chroot call

### ISSUE THREAD

**Issue by jvymazal** [rsyslog/rsyslog#1419]
Rsyslog has (with the `T` cmd-line option) option to perform `chroot` immediately after starting. It is generally recommend practice to do a `chdir` call ASAP after `chroot`. This prevents easy escape outside of chroot'ed environment. Could this call be added?

**Comment by rgerhards** [comment]
Just so that this is said here again for anyone coming in from Google: -T is a **testing aid** not a security aid. For security needs, you **should not** rely on it. more inside the PR.

**Comment by rgerhards** [comment]
done in 8.26 via separate pr
