### ISSUE TITLE
Dynamic key value for omkafka

### ISSUE THREAD

**Issue by aalkilani** [rsyslog/rsyslog#1421]
Allow dynamic keys using templates, similar to dynaTopic, make available a dynaKey configuration that allows the key to be created via a template. At the very least, have the key take in a variable. As it currently stands the key is simply static for all messages produced.

While similar to dynatopic, I don't see this will need a cache and the limitations that brings in how the dynatopic implementation is done. The topic requiring a cache makes sense, but the key should be handled similar to how the message is.. i.e., not a static string, rather simply part of the datum emitted.

Implementing this is also one step towards resolving #1199

While there are many use cases for this I'm sure, the simplest use case would be appending information RSyslog gets to a Key instead of manipulating the message received as it's being forwarded to Kafka. For example, I could keep the message intact while adding programname, timestamp and hostname to the key for auditing and measuring performance as messages travel through systems.

**Comment by davidelang** [comment]
exposing my ignorance of the kafka protocol, is there a place where it would 
make sense to offer the option of having a template that could be defined to let 
you vary all sorts of things?

what would the rules be about what can and can't be varied between different 
messages sent over the same connection (and even more specifically, sent as a 
single batch)?

David Lang

**Comment by aalkilani** [comment]
For data producers, outside of configuration parameters, Kafka exposes 2 essential things
 - The topic to produce to
 - The datum (ProducerRecord) to produce which is further split into Key and Message

So both the key and message are simply parts of the data being produced and are expected to be something the user chooses on a message by message basis.

Typically, the topic is a little less dynamic and the current implementation works beautifully, in my opinion, to address any dynamic topic routing required which I will add has been great.

**Comment by mostolog** [comment]
Excuse my ignorance, but wouldn't this solve your issue?

```
template(name="topic" type="string" string="whateveryouwant")
...
action(
		name="kafka"
		action.resumeRetryCount="-1"
		action.reportsuspension="on"
		#action.reportSuspensionContinuation="on"
		type="omkafka"
		broker=["kafka:9092"]
		dynatopic="on"
		topic="topic"
		partitions.auto="on"
		dynatopic.cachesize="300"
		template="json"
		errorFile="/logs/rsyslog-kafka.json"
	)
```

**Comment by rgerhards** [comment]
@alorbach isn't that done?

**Comment by alorbach** [comment]
This has not been done yet. 
dynaTopic works different then a dynamic key would work. 
We could use template format to set a dynamic key like we are doing it for the timestamp.

**Comment by duylong** [comment]
I go back this feature because I did not find the solution in the documentation. 

The idea is to keep a single topic and deliver the messages to one partition. This method is used to keep messages order in a multi-partition configuration with a single topic.

A exemple: key="%HOSTNAME%_%PROGNAME%"

**Comment by aalkilani** [comment]
It's been a while since I've looked at this ask but it keeps coming up as something we need.
I may have misguided the implementation a bit by trying to explain this in relation to dynaTopic. The intent is very different however and I believe @alorbach has a handle on the ask now. With the risk of being repetitive, the ask is this:

A message in Kafka consists of 2 parts. The Key and the Value. As it currently stands, OMKafka only considers populating the Value of Kafka message and allows for providing a static string to represent the key that is used with every single message. i.e., unlike the message being dynamic based on incoming data, the key is either set to NULL or a static string by using the `key="some static string"` property.

The value part of the produced messaged can be configured based on a template. Specifically, I can have an output that looks like this

```   
template(name="my_value_template" type="list") {
  property(name="timestamp" dateFormat="rfc3339")
  constant(value=",")
  property(name="$!programname")
  constant(value=",")
  property(name="hostname")
  constant(value=",")
  property(name="$myhostname")
  constant(value=",")
  property(name="msg" position.from="2")
}

 action (
      name="kafka"
      type="omkafka"
      partitions.auto="on"
      template="my_value_template"
    )
```

This allows me to configure the **_value-part_** of every message. There is no means to configure the **_key-part_**

Preferably, something like this
```   
template(name="my_value_template" type="list") {
  property(name="timestamp" dateFormat="rfc3339")
  constant(value=",")
  property(name="$!programname")
  constant(value=",")
  property(name="hostname")
  constant(value=",")
  property(name="$myhostname")
  constant(value=",")
  property(name="msg" position.from="2")
}

template(name="my_key_template" type="list") {
  property(name="msg" position.from="10") # just an example for using a template that produces a value based on some part of the incoming message. This has no real significance
}
 action (
      name="kafka"
      type="omkafka"
      partitions.auto="on"
      template="my_value_template"
      keyTemplate="my_key_template"
    )
```

In this scenario, OKafka would set the Kafka Producer Message's Key value to the result of the template defined by "keyTemplate" for each and every record that passes through. This is similar to how this works for the value field of a Kafka producer message.

**Comment by alorbach** [comment]
I will set this to enhancment. It sounds like a reasonable feature which can be added.

**Comment by rgerhards** [comment]
loos like #3350 implemented this.
