### ISSUE TITLE
Template not same in two different rulesets

### ISSUE THREAD

**Issue by tejas3190** [rsyslog/rsyslog#1435]
What causes the template output to be different, when the same template is used in two different rulesets having separate input sources.
Case 1: Calling ruleset using call {ruleset}, here template output is as expected  
Case 2: Calling ruleset through input() with type "imfile", here template output is not as expected 
Below is a sample configuration to reproduce this scenario -

#Configuration Start from here

module(load="imfile")
set $.foo = "FOO";
#foo(can be from env variable)
$template MyFile_Template,"%.foo%-LOGS\n"

ruleset(name = "system_log_ruleset" queue.type = "LinkedList" queue.saveonshutdown = "on"){
    **#Here the file content are as expected "FOO-LOGS"** 
    action(template="MyFile_Template" type="omfile" File="/var/log/sample_xx.log")
}

ruleset(name = "comp_log_ruleset"  queue.type = "LinkedList" queue.saveonshutdown = "on"){
    **#Problem is here, the file content is  just "-LOGS"** 
    action(template="MyFile_Template" type="omfile" File="/var/log/sample_yy.log")

}
input(type="imfile" File="/var/log/{some_log_file}" Tag="comp1_log:" Facility="local6" Severity="info" ruleset="comp_log_ruleset")

#system-logs only 
auth.info call system_log_ruleset
authpriv.info call system_log_ruleset
cron.warn call system_log_ruleset
daemon.warn call system_log_ruleset
kern.warn call system_log_ruleset
user.warn call system_log_ruleset
syslog.warn call system_log_ruleset

**Comment by davidelang** [comment]
it sounds like $.foo is not defined when you are processing the second ruleset.

**Comment by tejas3190** [comment]
Is anything wrong in the above configuration ?

**Comment by davidelang** [comment]
Yes, there is nothing that set $.foo  in the ruleset that you have tied to the input.

When you define a ruleset as part of an input, the only actions that are applied are ones that are inside that ruleset.

**Comment by tejas3190** [comment]
Thanks @davidelang, so does that mean defining $.foo within the tied ruleset will result in expected output (in this case "FOO-LOGS") from the defined template. I was in a thought that templates are static. Sorry but I am new to rsyslogs, my questions may be stupid.

**Comment by rgerhards** [comment]
template are static, but the set statement is not.

**Comment by rgerhards** [comment]
Probably the misunderstanding is that when you define a ruleset in an input, the default ruleset is NOT executed (by intention). So the set statement is never executed.

**Comment by tejas3190** [comment]
That clears a lot of stuff for me @rgerhards, thank you guys, great work. 👍 :-)

**Comment by davidelang** [comment]
templates are defined once, but they are evaluated when they are used. That way 
they can use variables that come from the message or are otherwise calculated.

If you define $.foo in the ruleset, you will get what you expect.

Any time you don't get what you expect, write a log out with the template 
RSYSLOG_DebugFormat and it will show you all the variables. This will let you 
see what's not defined the way you expect it to be.

**Comment by tejas3190** [comment]
That's very informative & details explanation @davidelang, thanks, I haven't used RSYSLOG_DebugFormat till now but good to know.
