### ISSUE TITLE
 Environment variable in rsyslog, getenv() return's empty string. 

### ISSUE THREAD

**Issue by tejas3190** [rsyslog/rsyslog#1438]
What am I doing wrong here:
- Trying to get environment variable "FOO"
- But seems **getenv("FOO")** return blank or empty.
- Have exported the env variable  as **export FOO="BAR"**
- Then restarting rsyslog - **service rsyslog restart**  

With the following config I am able to get only **"-LOGS"** in log file, but was expecting **"BAR-LOGS"**. Can you please explain what's wrong here, I am working on ubuntu 14.4. 
Here is the rsyslog config

`
set $.my_var = getenv("FOO")
template Check_ENV, "%.my_var%-LOGS\n"

#rule to log above template to file
ruleset(name = "env_ruleset" queue.type = "LinkedList" queue.saveonshutdown = "on"){ 
         action(template="Check_ENV" type="omfile" File="/var/log/check_env.log") 
}

local7.* call env_ruleset
`

**Comment by rgerhards** [comment]
where did you export the variable? Was it the right script location?

**Comment by tejas3190** [comment]
Hi @rgerhards, I have exported the variable in the same shell from I am also restarting rsyslog, this is the sequence I followed -
1. export FOO="BAR", resulting the env variable FOO set to BAR
2. service rsyslog restart

**Comment by rgerhards** [comment]
ok, this shell has nothing to do with the shell rsyslog runs in. You need to set the var in the operating system startup script, whereever this needs to be done for your OS.

**Comment by fengxiaochuang** [comment]
```shell
vim /etc/sysconfig/rsyslog
```
add some  param is fine
