### ISSUE TITLE
What is the difference between main_queue and the queue with an ruleset tied to an input 

### ISSUE THREAD

**Issue by tejas3190** [rsyslog/rsyslog#1440]

**Comment by davidelang** [comment]
pretty much nothing.

a queue on a ruleset tied to an input replaces the main queue for that input

the default size of the main queue is higher than other queues, that's about it.

David Lang

**Comment by tejas3190** [comment]
Thanks @davidelang, so if an input bounded ruleset does not have a queue defined does it default to main queue config ?
What is the recommended way to use imfile module to read several log files, should there be a need to define a queue for the rulesets

**Comment by davidelang** [comment]
It boils down to what actions you are going to take on the logs that you get.

If you are going to be doing the same thing (or close to the same thing) with 
all the logs, then they should share a ruleset (which can be the default ruleset 
if you are doing the same things with things arriving via /dev/log)

If you are doing different things with different logs, then they should have 
different rulesets.

For example, on my systems, I have the default ruleset process things from 
/dev/log and send them over the network to the nearest relay system.

All systems have this same default ruleset

Then on the relay systems, I have a ruleset that is tied to both TCP and UDP 
listeners, and it receives the messages from the network cleans them up, and 
sends them on.

There is no mixing of these two processing paths, so having them as completly 
separate paths with rulesets tied to the inputs and queues on those rulesets 
makes sense


A queue on a ruleset tied to one or more inputs can be thought of as if you were 
running a separate instance of rsyslog to process those logs.


In your case, you are reading logs from files, what are you doing with them? are 
you doing the same thing to other logs? or are the log paths really separate?



If you have an input that has a ruleset defined, but no queue on that ruleset, 
the logs do go to the main queue.

David Lang

**Comment by tejas3190** [comment]
In my system i am reading the log files sending the logs to kafka brokers on separate topics. There are multiple log files which are input() and tied with each having their separate rulesets.

**Comment by PascalWithopf** [comment]
If every log file has different types of logs then I would use a ruleset for every input.
But if they are all sending logs which need to be filtered anyway it would probably be easier to do it in one ruleset.
