### ISSUE TITLE
imfile module readTimeout does not time out (8.25.0)

### ISSUE THREAD

**Issue by fttyX** [rsyslog/rsyslog#1445]
Same problem as in [this](https://github.com/rsyslog/rsyslog/issues/1379) closed issue.

rsyslog 8.25.0

Steps to reproduce:
1. Originally, we have rsyslog with imfile section. Messages delivery is working fine.
2. Restart rsyslog service (centos 7 here, so systemctl restart rsyslog).
3. readTimeout stops working (means, if we send a new message to the log, it isn't processed, until we send another one. and we get just 1st message on the output, 2nd is still inside, until we send a 3rd message and so on).
4. Fix that works for me: stop rsyslog, delete imfile state file for my source logfile and start again.

A bug or any idea what can be wrong?

My imfile section:
```
input(
    type="imfile"
    File="/var/log/elasticsearch/elastic*.log"
    Tag="aaa_elastic"
    Severity="notice"
    Facility="local6"
    readTimeout="2"
    startmsg.regex="^.[[:digit:]]{4}-[[:digit:]]{2}-[[:digit:]]{2}"
    escapeLF="off")
```

Same problems without wildcard.
Works fine without startmsg.regex, but that makes multilined logs processed wrong.

**Comment by execextreme** [comment]
Wanted to say that I am having this same issue on 8.26.0

My configuration is similar to the one posted above, so I'm not going to post it.

**Comment by jhenry82** [comment]
Confirming the same behavior in 8.26.0.

**Comment by jhenry82** [comment]
Actually, I need to revise that statement. How are you folks loading the imfile module? With "$ModLoad imfile" or "module(load="imfile")" ?

I found that once I switched to the module() style syntax, readTimeout works as expected. It seems that ModLoad creates a version of imfile that does not support all new features, like readTimeout and inotify mode.

**Comment by fttyX** [comment]
I'm using module(load="imfile") syntax.

**Comment by jhenry82** [comment]
Ok. Weird, it's working for me now that I made that change.

**Comment by tedg** [comment]
Also using module(load="imfile") syntax

**Comment by alorbach** [comment]
Can somebody post a full debug log where it happens?

**Comment by rgerhards** [comment]
I have just re-confirmed that the testbench has timeout-related tests and they always pass. So this must be somehow induced by the environment. In other words, we currently have no idea of how to reproduce and really need a debug log to proceed any further.

**Comment by rgerhards** [comment]
Tentatively assigning milestone in the hope that we get more information. If not, I'll (re)move milestone again.

**Comment by rgerhards** [comment]
FYI: I got a debug log via private mail and it looks very promising.
