### ISSUE TITLE
rsyslog(5.8) not logging messages

### ISSUE THREAD

**Issue by nbommu1** [rsyslog/rsyslog#1454]
Hi,

we are having an issue with rsyslog, intermittently it stop logging to /var/log/messages , this is causing server slowness and ssh login is taking longer than expected, if I restart rsyslog, things are coming back to normal.

running instance in ec2 
Instance type r4.2xlarge
rsyslog version: rsyslog-5.8.10-9.26

when I run 'starce logger "test"', I have noticed that strace is waiting at /dev/log for couple of seconds and exit with 0 but no log message in the log.

connect(3, {sa_family=AF_LOCAL, sun_path="/dev/log"}, 110) = 0
sendto(3, "<13>Mar  7 12:54:13 <user>: test"..., 45, MSG_NOSIGNAL, NULL, 0) = 45

can someone help us out on this?

thanks
Niranjan

**Comment by davidelang** [comment]
On Tue, 7 Mar 2017, Niranjan Bommu wrote:

> Hi,
>
> we are having an issue with rsyslog, intermittently it stop logging to /var/log/messages , this is causing server slowness and ssh login is taking longer than expected, if I restart rsyslog, things are coming back to normal.
>
> running instance in ec2
> Instance type r4.2xlarge
> rsyslog version: rsyslog-5.8.10-9.26
>
> when I run 'starce logger "test"', I have noticed that strace is waiting at /dev/log for couple of seconds and exit with 0 but no log message in the log.
>
> connect(3, {sa_family=AF_LOCAL, sun_path="/dev/log"}, 110) = 0
> sendto(3, "<13>Mar  7 12:54:13 <user>: test"..., 45, MSG_NOSIGNAL, NULL, 0) = 45
>
> can someone help us out on this?

5.8 is ancient (current is 8.25 or so), so the community isn't going to do a lot 
of debugging on 5.8

do you have rsyslog delivering logs to anything else? if it has problems 
delivering logs to the network, that would pause writing local logs as well.

If your system is having disk I/O issues it could cause this problem (common on 
virtual systems or systems with network based disks)

beyond that, we would need to see your config before making any better guesses 
as to where the problem could be.

David Lang

**Comment by nbommu1** [comment]
thanks for you reply, here is rsyslog.conf, when I noticed this slowness I checked central log server communication, nothing I found in there.

$ModLoad imuxsock # provides support for local system logging (e.g. via logger command)
$ModLoad imklog   # provides kernel logging support (previously done by rklogd)
$MaxMessageSize 20k # apps sends huge stack trace to loggly
$SystemLogRateLimitInterval 5 # sending log rate interval
$SystemLogRateLimitBurst 500 # 500 messages from a single PID are received within a 5 second interval



$ActionFileDefaultTemplate RSYSLOG_TraditionalFileFormat



$IncludeConfig /etc/rsyslog.d/*.conf


*.info;mail.none;authpriv.none;cron.none                /var/log/messages
authpriv.*                                              /var/log/secure
mail.*                                                  -/var/log/maillog
cron.*                                                  /var/log/cron
local7.*                                               /var/log/boot.log
*.* @central-logserver01:514

**Comment by davidelang** [comment]
On Wed, 8 Mar 2017, Niranjan Bommu wrote:

> thanks for you reply, here is rsyslog.conf, when I noticed this slowness I checked central log server communication, nothing I found in there.
>
> $ModLoad imuxsock # provides support for local system logging (e.g. via logger command)
> $ModLoad imklog   # provides kernel logging support (previously done by rklogd)
> $MaxMessageSize 20k # apps sends huge stack trace to loggly
> $SystemLogRateLimitInterval 5 # sending log rate interval
> $SystemLogRateLimitBurst 500 # 500 messages from a single PID are received within a 5 second interval

This limit of 500 messages every 5 seconds could be the reason that it stops 
processing messages. Unless ther is something in the included files, I don't see 
anything else here that would pause message processing.

David Lang

>
>
> $ActionFileDefaultTemplate RSYSLOG_TraditionalFileFormat
>
>
>
> $IncludeConfig /etc/rsyslog.d/*.conf
>
>
> *.info;mail.none;authpriv.none;cron.none                /var/log/messages
> authpriv.*                                              /var/log/secure
> mail.*                                                  -/var/log/maillog
> cron.*                                                  /var/log/cron
> local7.*                                               /var/log/boot.log
> *.* @central-logserver01:514
>
>
>
