### ISSUE TITLE
What parameters are needed to be set to make sure that only N lines are read when using imfile.

### ISSUE THREAD

**Issue by tejas3190** [rsyslog/rsyslog#1456]
Rsyslog version rsyslogd 8.25.0, compiled with: PLATFORM: x86_64-pc-linux-gnu PLATFORM (lsb_release -d): FEATURE_REGEXP: Yes GSSAPI Kerberos 5 support: No FEATURE_DEBUG (debug build, slow code): No 32bit Atomic operations supported: Yes 64bit Atomic operations supported: Yes memory allocator: system default Runtime Instrumentation (slow code): No uuid support: Yes Number of Bits in RainerScript integers: 64

See http://www.rsyslog.com for more information.

Options: 1) MaxLinesAtOnce 2) readTimeout 3) MaxSubmitAtOnce does not seem to work, can anybody clarify about this options in more details, that will be very helpful

**Comment by davidelang** [comment]
On Wed, 8 Mar 2017, tejas3190 wrote:

> Rsyslog version rsyslogd 8.25.0, compiled with: PLATFORM: x86_64-pc-linux-gnu PLATFORM (lsb_release -d): FEATURE_REGEXP: Yes GSSAPI Kerberos 5 support: No FEATURE_DEBUG (debug build, slow code): No 32bit Atomic operations supported: Yes 64bit Atomic operations supported: Yes memory allocator: system default Runtime Instrumentation (slow code): No uuid support: Yes Number of Bits in RainerScript integers: 64
>
> See http://www.rsyslog.com for more information.
>
> Options: 1) MaxLinesAtOnce 2) readTimeout 3) MaxSubmitAtOnce does not seem to work, can anybody clarify about this options in more details, that will be very helpful

what is happening and what are you expecting to happen?

Maxlinesatones and maxsubmitatonce are not things that you would be able to 
easily see the effects of. they are things that you would only use when trying 
to tweak rsyslog for very high performance systems.

David Lang

**Comment by tejas3190** [comment]
ok, I was expecting to have a control over the log file by explicitly setting the max number of lines it should read on every poll interval, is there any parameter we can use for such use case? Thanks

**Comment by davidelang** [comment]
On Wed, 8 Mar 2017, tejas3190 wrote:

> ok, I was expecting to have a control over the log file by explicitly setting 
> the max number of lines it should read on every poll interval, is there any 
> parameter we can use for such use case? Thanks

No, when it detects new messages to be read, it will not stop until it reads all 
new messages. The parameters mentioned above control how many messages it will 
read before it does anything else, but once it has checked the other files (and 
processed some messages from each), it will do another batch from the first 
file, repeating until it is up to the end of the file for all of them. Then it 
will go to sleep until the next poll interval hits.

David Lang
