### ISSUE TITLE
action.execOnlyWhenPreviousIsSuspended is never triggered with chained actions

### ISSUE THREAD

**Issue by Ralnoc** [rsyslog/rsyslog#146]
With a central logging server I have a configuration that is setup so that incoming packets attempt to send to one server, but should that server fail and the action get 'Suspended' it should try the next server on the list and if that one fails the next.

Unfortunately what seems to actually happen is that the first action is suspended and the following actions never trigger. This happens regardless to what the retry count is set to or what the debatch queue size is set to.

This is manifesting on both CentOS 5 and CentOS 6 systems using the RPMs from the Adiscon Repo.

```
*.*      action(name="flume_collector.server2"
                type="omfwd"
                Target="server2"
                Port="41414"
                Protocol="tcp"
                queue.type="Fixedarray"
                queue.size="5000"
                queue.dequeuebatchsize="1"
                queue.workerthreads="16"
                template="flume-collector-Template")
&        action(name="flume_collector.server3"
                type="omfwd"
                Target="server3"
                Port="41414"
                Protocol="tcp"
                queue.type="Fixedarray"
                queue.size="5000"
                queue.dequeuebatchsize="1"
                queue.workerthreads="16"
                action.execOnlyWhenPreviousIsSuspended="on"
                template="flume-collector-Template")
&        action(name="flume_collector.server1"
                type="omfwd"
                Target="server1"
                Port="41414"
                Protocol="tcp"
                queue.type="Fixedarray"
                queue.size="5000"
                queue.dequeuebatchsize="1"
                queue.workerthreads="16"
                action.execOnlyWhenPreviousIsSuspended="on"
                template="flume-collector-Template")

```

**Comment by needleshaped** [comment]
Seems to be duplicate of https://github.com/rsyslog/rsyslog/issues/375

**Comment by Ralnoc** [comment]
Is it truly a duplicate when this was opened first? :) However it does look like they may be the same issue. I no longer am involved with the infrastructure this was being experienced on, though. Lets assume they are the same issue and I'll close this.
