### ISSUE TITLE
memory corruption during configuration parsing

### ISSUE THREAD

**Issue by bwdoll** [rsyslog/rsyslog#1474]
We are running rsyslog-8.24.0-2.el7.x86_64 on RedHat Enterprise Linux 7.3.  We stumbled across a configuration for rsyslog which results in a libc error on a corrupted doubly-linked list followed by process abort. The trace can be found here: http://pastebin.com/g2bC0gwb. The error appears to go away if some parts of the configuration are edited. In particular, if the "StreamDriverPermittedPeers" parameter string is any length other than 23 characters, or if the imfile configuration is removed. We re-tested with 8.25.0 and observed the same issue. I have attached anonymized configuration as "config-v8.zip". The configuration utilizes imfile, imtcp, imuxsock, omfile, and omfwd. The TCP connections are secured using the gtls netstream driver. The error can be triggered in normal invocation or with "-N 1" config validation run.

[config-v8.zip](https://github.com/rsyslog/rsyslog/files/856669/config-v8.zip)

As a separate but possibly related issue, we also noticed a memory corruption very similar to https://github.com/rsyslog/rsyslog/issues/194 on a related configuration of rsyslog-7.4.7-7.el7_0.x86_64 on RedHat Enterprise Linux 7.1. In this case the process reports the memory corruption during malloc and appears to hang. This error can also be triggered in normal invocation or "-N 1" config validation. I have attached the anonymized configuration as "config-v7.zip". This error also goes away if the StreamDriverPermittedPeers string is any length other than 23 or if the imfile configuration is removed.

[config-v7.zip](https://github.com/rsyslog/rsyslog/files/856679/config-v7.zip)

Please let me know if any additional information is needed.

**Comment by bwdoll** [comment]
After reviewing other issues in more detail this appears to be a possible duplicate of https://github.com/rsyslog/rsyslog/issues/1408.

**Comment by rgerhards** [comment]
Please update to rsyslog current (8.27.0) and report if the problem persists.

**Comment by bwdoll** [comment]
This is still an issue as of rsyslog 8.28.0, tested with the el7 version in the adiscon repository.

**Comment by bwdoll** [comment]
By inspection of the code it seems #1408 remains unresolved. The offending line is now https://github.com/rsyslog/rsyslog/blob/master/tools/omfwd.c#L1170. In the case where the inner while loop reaches the end of the string, p will be left pointing to the null terminator. I'm unclear why *(p+1) is set to null. Even though it is restored a few lines later, the corruption appears to trigger this bug depending on the length of the string - presumably dependent on alignment of whatever may or may not reside at the next byte.  I rebuilt rsyslog having removed "*(p+1) = '\0';" and the later "*(p+1) = save;" lines and it did not experience the issue. However, because I do not understand the original reason these lines were included I was hesitant to submit a patch or pull request.

**Comment by rgerhards** [comment]
@bwdoll I also do not see why the save is needed. I guess that had a reason in the dark ages of that code (it has not been touched for at least 5 years now). I'll submit a PR with you as author.

**Comment by rgerhards** [comment]
> I'll submit a PR with you as author.

ah... I can't neither have your name nor email address. So I'll give credits in the commit message.
