### ISSUE TITLE
rsyslog fails to build on macOS

### ISSUE THREAD

**Issue by fxcoudert** [rsyslog/rsyslog#1485]
Build for macOS using Homebrew fails with the following compilation error: https://github.com/Homebrew/homebrew-core/pull/8771

```
srutils.c:459:2: error: must use 'struct' tag to refer to type 'tm'
        tm.tv_sec = tv.tv_sec;
        ^
        struct 
srutils.c:459:4: error: expected identifier or '('
        tm.tv_sec = tv.tv_sec;
          ^
srutils.c:460:2: error: must use 'struct' tag to refer to type 'tm'
        tm.tv_nsec = tv.tv_usec * 1000;
        ^
        struct 
srutils.c:460:4: error: expected identifier or '('
        tm.tv_nsec = tv.tv_usec * 1000;
          ^
srutils.c:463:22: error: use of undeclared identifier 'tm'
        return ((long long) tm.tv_sec) * 1000 + (tm.tv_nsec / 1000000);
                            ^
srutils.c:463:43: error: use of undeclared identifier 'tm'
        return ((long long) tm.tv_sec) * 1000 + (tm.tv_nsec / 1000000);
                                                 ^
```

**Comment by rgerhards** [comment]
macOS is not a supported platform for rsyslog. We do not have anyone with know-how of it in the team. If you can provide a buildbot slave that is properly configured to build rsyslog, I would be willing to try to get it to work and ensure that in the future it will not be broken.

**Comment by fxcoudert** [comment]
Version 7.4.5 builds fine, so probably not much is needed. The bug above in `srutils.c` is not macOS-specific and would affect any platform with `_POSIX_TIMERS <= 0`. A fix should be:

```
--- srUtils.c.old	2017-03-29 13:41:57.000000000 +0200
+++ srUtils.c	2017-03-29 13:42:03.000000000 +0200
@@ -446,9 +446,8 @@ timeoutComp(struct timespec *pt, long iT
 long long
 currentTimeMills(void)
 {
-#	if _POSIX_TIMERS > 0
 	struct timespec tm;
-#   else
+#	if _POSIX_TIMERS <= 0
 	struct timeval tv;
 #	endif
 
```

**Comment by rgerhards** [comment]
Thanks, I'll gladly accept that patch. But my point is broader: we do not have any environment where we test rsyslog against macOS and so running it there is fragile. If you have interest in that platform, it would be a great thing if you could help us getting going with a CI provider plus some help when problems do occur. I guess once CI would be setup, little work would actually be involved.

**Comment by rgerhards** [comment]
I should note that we have done so with other folks as well. For example, I currently work with the openCSW guys on support for Solaris.
