### ISSUE TITLE
imptcp: add optional connection tracking messages

### ISSUE THREAD

**Issue by rgerhards** [rsyslog/rsyslog#1488]
For network debugging and special use cases, imptcp should support to generate messages

* when a new client connects a session
* when a client session is disconnected

This MUST be controlled by input() parameters:
* report.connectionopen
* report.connectionclose

and these parameters must default to false, as most users do not need nor want these messages as part of normal operations.

**Comment by PascalWithopf** [comment]
parameter notifyonconnectionclose did already exist so parameter names are:

notifyonconnectionclose
notifyonconnectionopen
