### ISSUE TITLE
imfile with wildcard processes files in wrong order

### ISSUE THREAD

**Issue by peick** [rsyslog/rsyslog#1489]
When using `imfile` with wildcards the log files are processed in the wrong order.

### How to reproduce

```
echo first >> /var/log/sample.log
logrotate /etc/logrotate.d/sample
echo second >> /var/log/sample.log
logrotate /etc/logrotate.d/sample
echo third >> /var/log/sample.log
```

#### Content of omfile output in /var/log/sample-rsyslog-transported.log

```
2017-03-31T12:45:46.019822+02:00 vagrant sample: third
2017-03-31T12:45:46.020095+02:00 vagrant sample: second
2017-03-31T12:45:46.020152+02:00 vagrant sample: first
```

#### Expected output of  /var/log/sample-rsyslog-transported.log

```
2017-03-31T12:45:46.019822+02:00 vagrant sample: first
2017-03-31T12:45:46.020095+02:00 vagrant sample: second
2017-03-31T12:45:46.020152+02:00 vagrant sample: third
```

#### (partial) rsyslog configuration

```
module(load="imfile" mode="inotify")
module(load="builtin:omfile")

input(
  type="imfile"
  stateFile="sample-state"
  File="/var/log/sample.log*"
  Tag="sample:"
  ruleset="sample-out"
  Facility="local0"
)

ruleset(name="sample-out") {
  action(
    type="omfile"
    File="/var/log/sample-rsyslog-transported.log"
  )
  stop
}
```

#### logrotate configuration

```
/var/log/sample.log {
    rotate 5
    create 640 daemon daemon
    size 1
    missingok
}
```

#### version used
```
$ rsyslogd -v
rsyslogd 8.25.0, compiled with:
        PLATFORM:                               x86_64-unknown-linux-gnu
        PLATFORM (lsb_release -d):
        FEATURE_REGEXP:                         Yes
        GSSAPI Kerberos 5 support:              No
        FEATURE_DEBUG (debug build, slow code): Yes
        32bit Atomic operations supported:      Yes
        64bit Atomic operations supported:      Yes
        memory allocator:                       jemalloc
        Runtime Instrumentation (slow code):    No
        uuid support:                           Yes
        Number of Bits in RainerScript integers: 64
```

**Comment by alorbach** [comment]
What happens if you add more than 3 loglines to the test? Do they all appear it wrong order?

**Comment by rgerhards** [comment]
I think it must also be said that the operation is race all the way up from the OS to inside rsyslog. It all depends on async operations which are not guaranteed to happen in a specific order. So I don't think this is a bug...

**Comment by davidelang** [comment]
I think there are a couple things here

1. if we are reading an existing file and it's rotated (via mv so it's the same 
inode), I think it's fair to expect us to finish the existing file before 
starting on the replacement.

If files are rotated faster than we can process the old files and we fall 
behind, all bets are off, we could end up skipping a file entirely

2. If we startup and are given a directory with a bunch of files in it, I think 
it's reasonable to expect us to grab data from them in sortorder (at least up to 
the max number of lines we are configured to grab before moving on to the next 
file)

**Comment by rgerhards** [comment]
> 1. if we are reading an existing file and it's rotated (via mv so it's the same
> inode), I think it's fair to expect us to finish the existing file before
> starting on the replacement.
> 
> If files are rotated faster than we can process the old files and we fall
> behind, all bets are off, we could end up skipping a file entirely
> 

this is already done. Note that it would be a config error to include the names of the files after rotation in the wildcard. That would be treated as a new file and consequently the data be duplicated.

> 2. If we startup and are given a directory with a bunch of files in it, I think
> it's reasonable to expect us to grab data from them in sortorder (at least up to
> the max number of lines we are configured to grab before moving on to the next
> file)

@alorbach do you remember how it was done in this case. I think this is what happens on startup.

**Comment by alorbach** [comment]
I believe there is no sort order when reading files from a directry because it would consume unecessary performance when the directory has many files.

**Comment by davidelang** [comment]
I wouldn't expect us to sort the directory entries, but I would expect us to 
sort the imfile wildcard matches (which should be a lot fewer, and in any case 
things would be slow if there are a lot of them)

**Comment by rgerhards** [comment]
milestone assignment might be a bit optimistic

**Comment by rgerhards** [comment]
We could add an option to force ```glob()``` to sort the entries. As @alorbach said, that causes extra overhead (IMHO unnecessarily), but if someone would like to ensure sorted processing of files, than this is probably the way to go. Due to the inherent asynchronozity of the whole operations involved in tracking files we can anyhow never guarantee a specific order (depends on operation mode and OS timing if and when we see changes).
