### ISSUE TITLE
main_queue directives RainerScript syntax

### ISSUE THREAD

**Issue by jvymazal** [rsyslog/rsyslog#1491]
While researching (undocumented) new syntax for main queue options, I found out that config validator ignores whether config directives in main_queue() block are actually valid. For example putting 
`main_queue(totalNonsense="whatever")`
into config file produces no error whatsoever.

**Comment by jvymazal** [comment]
Are those directives supposed to work @rgerhards ? Thanks for info.

**Comment by rgerhards** [comment]
they are
