### ISSUE TITLE
imfile: GLOB_BRACE unavailable on Solaris and linux with musl libc

### ISSUE THREAD

**Issue by doughdemon** [rsyslog/rsyslog#1494]
The imfile plugin uses the GNU extension GLOB_BRACE to glob(), which is unavailable at least on Solaris and linux systems using the musl c library. So currently compilation will fail on theses systems when the plugin is enabled.

One way to fix might be to define GLOB_BRACE as 0 if not yet defined. containsGlobWildcard might also need to take into account whether GLOB_BRACE is defined or not.

**Comment by alorbach** [comment]
We have a few solaris machines (Solaris 10/11 sparc/x64) in our buildbot sytsme integrated which are also compiling imfile. I don't see any error compiling imfile there. 

Perhaps you can post some compile logs showing the compile error's.

**Comment by doughdemon** [comment]
> We have a few solaris machines (Solaris 10/11 sparc/x64) in our
> buildbot sytsme integrated which are also compiling imfile. I don't
> see any error compiling imfile there. 

Yes, you are right, Solaris is unaffected since while it does not have
GLOB_BRACE, it does not compile the relevant code in imfile.c, which is
guarded by HAVE_INOTIFY_INIT.

Still, musl has inotify_init but no GLOB_BRACE. Defining GLOB_BRACE
when not defined in some HAVE_INOTIFY_INIT block is probably the best
thing to do.

Alpine linux carries a (dirty) patch for the compilation error:

https://git.alpinelinux.org/cgit/aports/tree/main/rsyslog/musl-fix.patch?id=9c38c131fb20cd4172c9e46699f07ae8797a4caf

(The other issues address by the patch seem to be fixed.)

**Comment by rgerhards** [comment]
fixed in https://github.com/rsyslog/rsyslog/issues/1494
