### ISSUE TITLE
Build pmnull module in ubuntu packages

### ISSUE THREAD

**Issue by selivan** [rsyslog/rsyslog#1498]
I made this PR to `rsyslog-pkg-ubuntu` repo: https://github.com/rsyslog/rsyslog-pkg-ubuntu/pull/55, but seems nobody is watching PRs or issues in that repository :( Sorry for writing this to inappropriate issue tracker, but this one seems to be alive.

Useful module for file reading and forwarding over network.

**Comment by rgerhards** [comment]
@friedl can you please have a look at this?

**Comment by friedl** [comment]
The PR was incomplete, but I have added the module. New packages are currently building.

**Comment by selivan** [comment]
@friedl thank you :) I didn't modify `debian/control` because I thought such a small but useful module should be installed with main package. But separate package is fine too.

**Comment by rgerhards** [comment]
@selivan just out of curiosity: what is your use case for the module (might be worth adding to the doc, thus I ask)?

**Comment by selivan** [comment]
@rgerhards 
I am using rsyslog to forward logs over network. Some applications write logs directly to syslog, some write log files and rsyslog reads them. On receiving server side for logs that were read from files I use template like this: `template(name="OnlyMsg" type="string" string="%msg:::drop-last-lf%\n")`. I don't want to write additional information like timestamp - it's useless because it indicates time message was read by rsyslog, not time it was actually created.

Now if one of this logs resemble syslog format, timestamp part will be lost. It didn't happen yet, but it is a fragile part of configuration I want to get rid of.

Btw, I did rather thorough article on my rsyslog setup - https://selivan.github.io/2017/02/07/rsyslog-log-forward-save-filename-handle-multi-line-failover.html - saving filenames while forwarding logs and other useful stuff. Could you please include it in http://wiki.rsyslog.com/index.php/Configuration_Samples on rsyslog wiki? That wiki is closed for unregistered users and there is not way to register :(

**Comment by selivan** [comment]
As I mentioned before, `debian/rules` file for rsyslog already has entry `debian/tmp/usr/lib/rsyslog/pm*.so`, so additional steps for parser modules are not required: they all are installed with main rsyslog package. Moreover, when both rsyslog and rsyslog-pmnull packages have file `/usr/lib/rsyslog/pmnull.so`, they produce conflict on installation:
```
Unpacking rsyslog-pmnull (8.26.0-0adiscon2trusty1) ...
dpkg: error processing archive /var/cache/apt/archives/rsyslog-pmnull_8.26.0-0adiscon2trusty1_amd64.deb (--unpack):
 trying to overwrite '/usr/lib/rsyslog/pmnull.so', which is also in package rsyslog 8.26.0-0adiscon2trusty1
```
Package rsyslog-pmnull should be removed from `debian/control`, because pmnull module is already installed with main rsyslog package.

**Comment by mgraff** [comment]
Sorry to interfere in this issue, but could you please also add this module to the epel-7 repository ?
I would like to use it but it is not packaged yet.
Thanks !

**Comment by jay7x** [comment]
Could you please build `pmnull` module for epel-* repos? I'd like to use it to improve custom software logs import performance (using `imfile` module) on RHEL 6.6.

**Comment by rgerhards** [comment]
@jay7x While it makes sense to package that module, I would like to point out that it does not offer any performance benefits (or at least very very very small if any).

**Comment by jay7x** [comment]
Ah, good to know! Thank you @rgerhards! Actually my idea was based on documentation (http://www.rsyslog.com/doc/v8-stable/configuration/modules/pmnull.html) which states "It is used as a performance improvment since there are no CPU cycles wasted on parsing the message". May be it's good idea to update docs then.

**Comment by rgerhards** [comment]
@friedl can you packe this for rhel as well? 

@jay7x I've just updated the doc, thanks.

**Comment by selivan** [comment]
@rgerhards I'd like to mention again, that pnull module, like all parser modules, is automatically built with `rsyslog` package. So `rsyslog-pmnull` package, that also includes this module, conflicts with main `rsyslog` package. See https://github.com/rsyslog/rsyslog/issues/1498#issuecomment-294495790.

**Comment by rgerhards** [comment]
ah, ok, I am not into packaging ... so @friedl needs to cleanup that (and probably remove the extra package). right?
