### ISSUE TITLE
Solaris File Event Notification - Feature request

### ISSUE THREAD

**Issue by janorn** [rsyslog/rsyslog#150]
Would it be possible to support Solaris FEN in imfile. Solaris doesn't have inotify but FEN should most probably work for monitoring which files have changed.

Some URLS for reading and sample code:
https://blogs.oracle.com/praks/entry/file_events_notification
http://solarisrants.wordpress.com/2013/07/24/solaris-file-event-notification/

**Comment by rgerhards** [comment]
see also #1954 - sorry I opened the duplicate

**Comment by rgerhards** [comment]
implemented via #2227
