### ISSUE TITLE
i can not use "apt install rsyslog-kafka"

### ISSUE THREAD

**Issue by zorelu** [rsyslog/rsyslog#1505]
I want to use Rsyslog log to Kafka ,but the error code just like `root@debian:~# apt install rsyslog-kafka
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 rsyslog-kafka : Depends: rsyslog (= 8.23.0-2~bpo8+1) but 8.4.2-1+deb8u2 is to be installed
E: Unable to correct problems, you have held broken packages.
`
so please help

**Comment by rgerhards** [comment]
This should go to the https://github.com/rsyslog/rsyslog-pkg-ubuntu package, but maybe @friedl can look at it.

**Comment by friedl** [comment]
@zorelu on which Ubuntu version is this?

**Comment by zorelu** [comment]
i use debian8 and ubuntu 16.04 for this.so i must use gcc to make Source Code pkg?

**Comment by rgerhards** [comment]
We are currently overhauling the kafka subsystem inside rsyslog. This also affects packaging. Onc we are done, this will be fixed as well.
