### ISSUE TITLE
impstats using int-sized counters to store long-sized getrusage() results

### ISSUE THREAD

**Issue by jay7x** [rsyslog/rsyslog#1517]
I've found following today in my `impstats` output:
`2017-04-17T04:05:35.324399+00:00 { "name": "resource-usage", "origin": "impstats", "utime": 54692206578, "stime": 29162949066, "maxrss": 1511876, "minflt": 31139090, "majflt": 1, "inblock": 192, "oublock": 428207376, "nvcsw": -1679221256, "nivcsw": 27747771 }`

Look at field `nvcsw`. It have integer overflow as far as I understand.

According to man page `getrusage()` syscall return results as `struct rusage` which contain long-sized counters:
```
struct rusage {
    struct timeval ru_utime; /* user CPU time used */
    struct timeval ru_stime; /* system CPU time used */
    long   ru_maxrss;        /* maximum resident set size */
    long   ru_ixrss;         /* integral shared memory size */
    long   ru_idrss;         /* integral unshared data size */
    long   ru_isrss;         /* integral unshared stack size */
    long   ru_minflt;        /* page reclaims (soft page faults) */
    long   ru_majflt;        /* page faults (hard page faults) */
    long   ru_nswap;         /* swaps */
    long   ru_inblock;       /* block input operations */
    long   ru_oublock;       /* block output operations */
    long   ru_msgsnd;        /* IPC messages sent */
    long   ru_msgrcv;        /* IPC messages received */
    long   ru_nsignals;      /* signals received */
    long   ru_nvcsw;         /* voluntary context switches */
    long   ru_nivcsw;        /* involuntary context switches */
};
```
But rsyslog store those values into int-sized fields:
```
/* resource use stats counters */
static intctr_t st_ru_utime;
static intctr_t st_ru_stime;
static int st_ru_maxrss;
static int st_ru_minflt;
static int st_ru_majflt;
static int st_ru_inblock;
static int st_ru_oublock;
static int st_ru_nvcsw;
static int st_ru_nivcsw;
```
Counters definitions:
https://github.com/rsyslog/rsyslog/blob/master/plugins/impstats/impstats.c#L119
Function `generateStatsMsgs`:
https://github.com/rsyslog/rsyslog/blob/master/plugins/impstats/impstats.c#L259

As far as I see in `statsobj.[hc]` it's not so obvious to add 64-bit counters to rsyslog. But I can try after some guidance.

I'm using CentOS 7 64-bit and rsyslog-8.26.0-1.el7.x86_64 from v8-stable repo (http://www.rsyslog.com/rhelcentos-rpms/)

**Comment by jay7x** [comment]
Found this in impstats log today:
```2017-06-07T02:55:14.847918+00:00 { "name": "resource-usage", "origin": "impstats", "utime": 338210709405, "stime": 149650779876, "maxrss": 362028, "minflt": 42671351, "majflt": 34, "inblock": 277824, "oublock": -1742565520, "nvcsw": -163404101, "nivcsw": 2470568 }```

`oublock` got overflow too.

**Comment by rgerhards** [comment]
Thanks for opening this issue. Unfortunately, I was hyper-busy with many other things for quite some month and not all issues were properly followed up. I am currently triaging everything.

That said, I think this has been fixed in the meantime (by you? ;-)). Need to check. If you know, tell me.

**Comment by jay7x** [comment]
Unfortunately no. I had quick look but found no easy way to change counter type size :(

**Comment by rgerhards** [comment]
ok, thanks for the effort. I'll see if I can look in the next dev cycle after it. But there is already quite a lot of more important stuff, so I may need to shuffle it forward to next milestone.

**Comment by jay7x** [comment]
This one is not critical at all! We have fix on prometheus side :)

**Comment by rgerhards** [comment]
just out of curiosity: which platform is it that has long with 64 bits? usually long equals int and long long is int64_t

**Comment by rgerhards** [comment]
mmmhhh... ```intctr_t``` is 64 bits and is unsigned. Looks like the problem is when the string is extracted...

**Comment by rgerhards** [comment]
could be an issue with libjastjson: https://github.com/rsyslog/rsyslog/blob/master/runtime/statsobj.c#L309

**Comment by rgerhards** [comment]
mhhh.. libfastjson handles this correctly (assuming we have no value larger 2^63). It uses ```int64_t``` for storage and does the correct conversion via ```sprintbuf(pb, "%" PRId64, jso->o.c_int64);```.

**Comment by rgerhards** [comment]
damn... it's so obvious ;-) the counter definitions are wrong. Of course, they must not be ```int``` but ``ìntctr_t```. I was soo focussed on the 32 vs 64 bits that I didn't notice. All the time since I saw this the first time... ;-)

**Comment by rgerhards** [comment]
I stand corrected, it was 32 vs 64 bit (unswisly choosen names being the root cause) -- commit comment has the full story, please see there.
