### ISSUE TITLE
enhanced tls settings

### ISSUE THREAD

**Issue by akriegisch** [rsyslog/rsyslog#153]
please allow more tls settings:
- enable/disable protocols (ie. no SSLv3 by default)
- cipher selection (aka cipher string)
- the server should select the ciphers
- ephemeral ciphers (allow to specify the curve to be used and/or the dh params)
- add support for crl verification (in simple case with a configurable file)

nice to have would be:
- crl verification based on the crl location announced by the ca itself
- ocsp verification based on the information contained in the ca itself (or just allow the user to specify the ocsp server)

**Comment by JPvRiel** [comment]
In addition to enhanced setting options, it may well be nice to cleanup how TLS options are configured. For example, with imrelp, TLS options can be specified per input, with tls.<option> but with the older TCP TLS input module, imtcp its cumbersome to connect it with a netstreamdriver which has to be set in the 'tls' mode (streamdriver.mode="1") and using rainerscript config, this seems stuck as a global setting. It would be nice to see the imtcp and omfwd action updated to support variable TLS configurations and match the tls.<option> convention used in with omrelp/imrelp.

**Comment by rgerhards** [comment]
@PascalWithopf didn't you implement this via priority string?

**Comment by PascalWithopf** [comment]
Yes, this was implemented via the priority string parameter.

**Comment by rgerhards** [comment]
It's at least contained in 8.31.
