### ISSUE TITLE
Rsyslog 8.26.0 stops reading line when meeting ^@ (C based end of string)

### ISSUE THREAD

**Issue by SuperFunks** [rsyslog/rsyslog#1530]
Hi guys,

I have these ANSI files i need to parse - and an entry looks like this:
![image](https://cloud.githubusercontent.com/assets/20201219/25482479/57db1b6e-2b52-11e7-8a86-ac96ab44135c.png)

In an editor like NANO - the NUL is represented like this: ^@ (like shown below)

WMSESSION                         6e9a48b0-d02e-132c-9ac1-ffffffffc298    ^@                                       6e9a48b0-d02e-132c-9ac1-ffffffffc298

The issue here is that for some reason rsyslog also stops reading the line when it hits this ^@ char - so all my output coming from rsyslog is simply capped there.
All actions and outputs seem ok - but the payload is capped all the way through.

I have tried making IMFile understand to start the event AFTER the ^@ - but all regex attempts have failed because the IMFile never sees passed the ^@ (nul/end-of-string) char.

I would love this to be fixed :)

Best regards,

Funks

**Comment by SuperFunks** [comment]
Any workaround suggestions are welcome as well.

**Comment by PascalWithopf** [comment]
I tried to reproduce this, but everything works with me.
Which version of rsyslog are you using? Try to use the newest.
Could you give more detail on how your configuration looks like.

**Comment by rgerhards** [comment]
no repo
