### ISSUE TITLE
Rsyslog 7.4.7 stops writting all the logs when one of the plugin stops reading data from it's queue. 

### ISSUE THREAD

**Issue by krohan91** [rsyslog/rsyslog#1541]
Hi,

I have written a rsyslog plugin which gets live logs from rsyslog and on request will provide it to a consumer application. 
The issue I am facing is, when my plugin waits for n minutes before getting a request from consumer application , it will block all the logging (other plugins which simply writes into files). 

The one thing worked where I simply dropped the logs after reading in, 

> while(std::getline(std::cin, strInput))

But this is not the optimized way of doing it.

As per below link,
http://www.rsyslog.com/doc/v8-stable/whitepapers/queues_analogy.html

It looks like when a plugin stops reading data from its own queue, it affects the main queue as well.
But if this is the case then, a single plugin can block all the rsyslog logging.

Is there a way to handle this case ? or this is the way it works.
As I thought, the main queue should automatically drop logs for a plugin if it is not reading or some other way at least it should not affect the other plugins.
Am I missing any extra configuration parameters which needs to be added while writing a plugin ?

Please find below my code snippets,

conf file
if ($programname == 'kernel') then {
    action(type="omprog"
            binary="/usr/local/quickheal/bin/rsyslog_kernel"
            template="RSYSLOG_JsonFormat")
}

Plugin >
              // application_status is getting updated by other event
              if(application_status == 1){
                            while(std::getline(std::cin, strInput))
                                                                 {
                                                                      Json::Value const jsonInput = jsonParse(strInput);
    
                                                                      // Send jsonInput to the consumer app
                                                                 }
                                                      }                       
                   
 Thanks,
Krohan

**Comment by davidelang** [comment]
On Wed, 3 May 2017, krohan91 wrote:

> Hi,
>
> I have written a rsyslog plugin which gets live logs from rsyslog and on request will provide it to a consumer application.
> The issue I am facing is, when my plugin waits for n minutes before getting a request from consumer application , it will block all the logging (other plugins which simply writes into files).
>
> The one thing worked where I simply dropped the logs after reading in,
>
>> while(std::getline(std::cin, strInput))
>
> But this is not the optimized way of doing it.
>
> As per below link,
> http://www.rsyslog.com/doc/v8-stable/whitepapers/queues_analogy.html
>
> It looks like when a plugin stops reading data from its own queue, it affects the main queue as well.
> But if this is the case then, a single plugin can block all the rsyslog logging.
> Is there a way to handle this case ? or this is the way it works.

Yes, this is the case. When an action queue fills up, the main queue starts 
filling up.

You need to make the action queue large enough to not fill up (which can include 
the disk assisted type that spills out to disk), or you need to configure the 
queue to start throwing logs away in the action queue when it gets too full.


> As I thought, the main queue should automatically drop logs for a plugin if it is not reading or some other way at least it should not affect the other plugins.

No, Rsyslog should never automatically throw away logs. It should only throw 
away logs when it is instructed to by the configuration. Yes, having all the 
queues fill up can be bad, but that can be the right thing to do, and it's a lot 
easier to configure rsyslog to throw away logs that it would otherwise keep than 
to figure out how to have it not throw away logs when that's the normal way of 
operating.

> Am I missing any extra configuration parameters which needs to be added while writing a plugin ?

It's not a good idea to have plugins that block for long periods in normal 
operation, for just the reasons you are running into.

But the fixes are all in the queue configuration as I noted above.

David Lang

**Comment by krohan91** [comment]
Thank you David..

So what will you suggest instead of plugin which will fit into my case.
I have a simple requirement, On request need live logs for requested modules. 

-Krohan

**Comment by davidelang** [comment]
I'm not sure what you mean by 'live logs'

If your plugin can't keep up with the peak traffic, you need large enough action queues to buffer the logs until it can keep up.

If your plugin can't keep up with the average logs (or even the average logs at your peak time), you need to have some way of not having it look at all the logs. This can be filtering the logs before they are sent to your plugin, or it can be configuring the queues to throw away low severity logs when the queue gets too full.

Or you need to make your plugin faster (or possibly have multiple copies of it running from different threads)
