### ISSUE TITLE
rsyslog 8.4.2 stops logging locally and remotely when no route to specified server.

### ISSUE THREAD

**Issue by an0nEmoose** [rsyslog/rsyslog#1543]
If a user configures rsyslog to send to a remote server that there is no network route to reach, rsyslog will stop logging locally as well when using this syntax in rsyslog.conf. this should not prevent rsyslog from doing anything at all. The syntax is as such:
`
if (
    ($syslogseverity-text == 'info') and
    ($programname == 'placeholder.program' or $programname == 'place_holder.program')
)
then @@place.holder.server:65001;Default
& stop
`

This is supported syntax and should not prevent rsyslog from logging locally. The code below works even with an unreachable server, it doesn't send the remote logs because the server is unreachable yet it still logs locally as it should. However, the above code will prevent rsyslog from logging remotely as well as locally. Since it is supported syntax, it should not prevent rsyslog from logging locally. It should provide an error.
`
*.* @@place.holder.server:65001;Default
`

following supported syntax documented here:
http://www.rsyslog.com/doc/v8-stable/configuration/properties.html
http://www.rsyslog.com/doc/v8-stable/configuration/filters.html
http://www.rsyslog.com/filter-optimization-with-arrays/

the bug is that, using supported syntax, this should not stop rsyslog from doing anything and currently, as of 8.4.2 it prevents it from performing any actions at all: logging locally or remotely.

**Comment by davidelang** [comment]
you are telling rsyslog to deliver the logs to a remote server using reliable 
transportation. When it can't do so, it waits until it can and can't finish 
processing the log message

you would need to create an action queue for the remote transmission (and deal 
with making sure that it doesn't fill up) to allow local logging to continue 
when the remote system is unreachable.

David Lang

**Comment by an0nEmoose** [comment]
@davidelang  Thank you for the quick response! That was very helpful and informative.
