### ISSUE TITLE
[omelasticsearch] Use GET instead of HEAD for health check

### ISSUE THREAD

**Issue by Nayar** [rsyslog/rsyslog#1546]
Hi, 

According to my HAProxy graphs, I'm getting lots of 404 HTTP status on my elasticsearch. It turns out rsyslog's module omelestaic does lots of `HEAD` on `/_cat/health`

![spectacle j24314](https://cloud.githubusercontent.com/assets/454815/25839303/280ad7ee-34a8-11e7-93cf-db5386d55f0d.png)

![spectacle m24314](https://cloud.githubusercontent.com/assets/454815/25839315/378ddd74-34a8-11e7-930c-96a9ffc02a78.png)

A manual curl on the elasticsearch give me this
```
nayar@sys-asus-nayarj:~$ curl -u xxx:xxx http://es1:9200/_cat/health -X HEAD -v
Warning: Setting custom HTTP method to HEAD with -X/--request may not work the 
Warning: way you want. Consider using -I/--head instead.
*   Trying 100.64.111.41...
* Connected to es1 (100.64.111.41) port 9200 (#0)
* Server auth using Basic with user 'xxx'
> HEAD /_cat/health HTTP/1.1
> Host: es1:9200
> Authorization: Basic xxxxxxxx
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 404 Not Found
< Warning: 299 Elasticsearch-5.3.0-3adb13b "[HEAD /{index}/{type}] is deprecated! Use [HEAD /{index}/_mapping/{type}] instead." "Tue, 09 May 2017 07:12:20 GMT"
< content-type: text/plain; charset=UTF-8
< content-length: 0
< Connection: close
< 
* Closing connection 0
```

ES Version: 5.3.0
RSYSLOG: 8.24.0

**Comment by jgerhards** [comment]
i have tried to fix this now, but since i don't have access to an adequate testing environment i can't test it. Could you give it a try and report back?

**Comment by wdauchy** [comment]
@jgerhards this would break support for ES2 clusters, you need to introduce a version check or parameter

**Comment by wdauchy** [comment]
@jgerhards I had a closer look and I don't know where you found out about "_cat/_mapping/health". "{index}/_mapping/{type}" is used for checking a specific index.

"_cat/health" still exists and is still the reference https://www.elastic.co/guide/en/elasticsearch/reference/master/cat-health.html

tested on a local ES5.4.3 version

The issue here is about switching from HEAD to GET request

**Comment by wdauchy** [comment]
I have proposed a patch which fixes the issue; tested on my local machine. see pull request #1697

**Comment by rgerhards** [comment]
fixed via https://github.com/rsyslog/rsyslog/pull/1697
