### ISSUE TITLE
ompgsql issue

### ISSUE THREAD

**Issue by xavierromero** [rsyslog/rsyslog#155]
Hello,

I've been running rsyslog for 2 or 3 years with no issues. Few weeks ago I've updated to 8.4.2, and I just noticed that since then, the ompgsql output is not working anymore.

Database is up and running and there been no config change at all. I've read some posts about "action 17" and xconsole, but it has nothing to do thought,...

Log is showing these messages:
Nov 18 16:17:54 nex-logserver rsyslogd0: action 'action 25' resumed (module 'ompgsql') [try http://www.rsyslog.com/e/0 ]
Nov 18 16:17:54 nex-logserver rsyslogd0: action 'action 25' resumed (module 'ompgsql') [try http://www.rsyslog.com/e/0 ]
Nov 18 16:17:54 nex-logserver rsyslogd0: action 'action 25' resumed (module 'ompgsql') [try http://www.rsyslog.com/e/0 ]
Nov 18 16:17:54 nex-logserver rsyslogd0: action 'action 25' resumed (module 'ompgsql') [try http://www.rsyslog.com/e/0 ]
Nov 18 16:17:54 nex-logserver rsyslogd0: action 'action 25' resumed (module 'ompgsql') [try http://www.rsyslog.com/e/0 ]
Nov 18 16:17:54 nex-logserver rsyslogd0: action 'action 25' resumed (module 'ompgsql') [try http://www.rsyslog.com/e/0 ]
Nov 18 16:17:54 nex-logserver rsyslogd0: action 'action 25' resumed (module 'ompgsql') [try http://www.rsyslog.com/e/0 ]
Nov 18 16:17:54 nex-logserver rsyslogd0: action 'action 25' resumed (module 'ompgsql') [try http://www.rsyslog.com/e/0 ]
Nov 18 16:17:54 nex-logserver rsyslogd0: action 'action 25' resumed (module 'ompgsql') [try http://www.rsyslog.com/e/0 ]
Nov 18 16:17:54 nex-logserver rsyslogd0: action 'action 25' resumed (module 'ompgsql') [try http://www.rsyslog.com/e/0 ]
Nov 18 16:17:54 nex-logserver rsyslogd-2007: action 'action 25' suspended, next retry is Tue Nov 18 16:18:24 2014 [try http://www.rsyslog.com/e/2007 ]

My config file is as follows (only significant parts):
...
$ModLoad ompgsql
...
$template INSERT,"insert into systemevents (Message, Facility, FromHost, Priority, DeviceReportedTime, ReceivedAt, InfoUnitID, SysLogTag, processid, remoteip) values ('%msg%', %syslogfacility%, '%fromhost%', %syslogpriority%, \
  '%timereported:::date-rfc3339%', '%timegenerated:::date-rfc3339%', %iut%, '%syslogtag:R,ERE,1,FIELD:([A-Za-z0-9]+)(\[[0-9]+\])?:--end%', '%syslogtag:R,ERE,2,BLANK:(.+)\[([0-9]+)\]:--end%', '%fromhost-ip%')",SQL
...
if $syslogseverity >= 6 then ~
*.* :ompgsql:127.0.0.1,rsyslog,rsyslog_writer,mypassword;INSERT

From command line, I can connect to the postgres database with the parameters supplied (host, user, pass, db).
That configuration was working right for the last years until I've upgraded rsyslog (my previous version was 6 if I'm right). I can provide any additional information required.

Additionnal info:

rsyslog-8.4.2.ad1-1.el6.x86_64
rsyslog-elasticsearch-8.4.2.ad1-1.el6.x86_64
rsyslog-pgsql-8.4.2.ad1-1.el6.x86_64

postgresql-libs-8.4.20-1.el6_5.x86_64
postgresql-8.4.20-1.el6_5.x86_64
postgresql-server-8.4.20-1.el6_5.x86_64

Linux nex-logserver 2.6.32-504.el6.centos.plus.x86_64 #1 SMP Mon Oct 20 03:07:34 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

CentOS release 6.6 (Final)

Best regards,
Xavier Romero.

**Comment by rgerhards** [comment]
While not adressing this bug specifically, I would strongly think that it is fixed at least in 8.10, which will be released tomorrow. So I close the bug for now. Please re-open if it is not fixed.
