### ISSUE TITLE
High memory usage in inotify mode for imfile startmsg regex

### ISSUE THREAD

**Issue by jhenry82** [rsyslog/rsyslog#1552]
rsyslog 8.26
CentOS 6.9

I've been (unintentionally) running my servers in polling mode for several years with "$ModLoad imfile". I recently tried switching over to module(load="imfile") and immediately noticed rsyslog bouncing between 90 and 150MB (edit: MB, not GB!) of RAM (RSS, not virtual) whereas previously it was about 7MB.

I narrowed it down to a couple large files containing multiline messages. If I stop tailing them, memory usage is the same between polling and inotify. If I include them, it jumps by 10-20x. It's also consistently reproducible by switching the mode= setting on imfile and restarting.

I did note this line in the imfile documentation: "read modes other than “0” currently seem to have issues in inotify mode". Is the huge RAM spike one of these issues?

Here's a pretty minimal config that reproduces the issue for me. The main_queue settings do seem significant, too:
```
module(load="imfile")

global(
  preserveFQDN="on"
  workDirectory="/var/log/rsyslog_spool"
  umask="0000"
)

main_queue(
  queue.type="LinkedList"
  queue.size="100000"
)

input(
  type="imfile"
  File="/var/log/multiline.log"
  Tag="multiline.log_app:"
  Severity="error"
  startmsg.regex="^[0-9]{4}-[0-9]{2}-[0-9]{2}[ \t]"
  Facility="local7"
)
```

**Comment by davidelang** [comment]
the various readmode options are somewhat depriciated now, startmsg.regex should 
be able to replace them with little or no overhead (at some point this needs to 
be tested, and if so, the readmode options need to be ripped out of the code and 
be turned into wrappers that set the appropriate startmsg.regex)

your example uses startmsg.regex, does it have the problem, or is the problem 
only if you use readmode?

**Comment by rgerhards** [comment]
I would assume that the extra memory is for file buffers. In inotify mode, we can keep the files open, which saves us performance. I think in polling this is not the case (but need to check to be 100% sure).

**Comment by rgerhards** [comment]
side-note: since the introduction of journal, we no longer really care about low-end systems. So I don't consider 100MB a problem for a real server. That doesn't mean we shouldn't look into what is causing this ;-)

**Comment by jhenry82** [comment]
@davidelang I am not using readmode at all. The exact config I posted above is sufficient to reproduce the issue for me.

@rgerhards agreed that in 2017 100MB of RAM isn't a huge deal. It just jumped out at me because usually rsyslog runs in an amazingly small footprint, no matter what it is parsing. Adding "startmsg" to an input caused the memory usage to immediately jump by an order of magnitude and that seemed at least worth investigating whether it's working as intended or not.

For what it's worth, valgrind doesn't immediately complain about leaking dozens of MB.

**Comment by rgerhards** [comment]
@jhenry82 yup, I'd also like to dig into it. Can you send me a copy of one of the problematic files?

**Comment by jhenry82** [comment]
I'll have to ask our dev team if that is acceptable. I'm pretty sure it contains confidential company information. Might be possible for me to sanitize.

**Comment by rgerhards** [comment]
I am primarily interested in the structure. It probably is sufficient if I can see the structure of the longest multi-line message, even if all line content is replaced by the same char -- as long as imfile is able to detect it properly. I'd like to use that in lab...

**Comment by jay7x** [comment]
JFYI, I've hit into similar issue when our developers silently ignored convention on log files format. Rsyslog imfile tried to collect all messages into single line (because `startmsg.regex` doesn't match anymore) and failed. I've found 4Gb state file finally in /var/lib/rsyslog. So I've added `readTimeout` option to limit further issues.

**Comment by rgerhards** [comment]
Ah, this makes things much clearer. I think we need to make sure that imfile also abides the max message size limit when reading lines (and discards everything that is over the max size). That way, we also do not need to store the extra data.

@PascalWithopf A warning in this case would make sense. But it should be possible to disable it via config param.

**Comment by davidelang** [comment]
throw away everything after the max length or make it the next message?

There are reasons to do either.

Historically, excess data from network messages that was > maxmessagesize became 
the next message.

**Comment by rgerhards** [comment]
> Historically, excess data from network messages that was > maxmessagesize became
> the next message.

Yeah, we could optionally do this here as well. But that mode really, really has most often caused problems, and in most cases the rest of the message has been lost in any case. Because of the missing header, it was usually not sorted to where the initial part went to.

I would opt to first simply discard the excess message, but I wouldn't object if you (and others) say we should have the option to split it. For imfile, this makes a whole more sense, I admit, as we do not loose header information.

**Comment by jay7x** [comment]
I'm not sure topic starter have exactly my issue. So better to check his configs anyway. But for my case I'd like to have following behaviour. When collected message is over size limit then throw rest of line away and assume we have next message from next line. May be emit message and increase some counter is good idea as well.

**Comment by rgerhards** [comment]
+1 on the impstats counter! That's a great idea in general. @PascalWithopf please also consider this.

**Comment by davidelang** [comment]
given that 'throw away the rest of the line' may end up being the rest of the 
file (if startmsg.regex doesn't match, or if there is a problem with readmode), 
I think it should be configurable to either throw it away or make it the next 
message.

We should always preserve data if we can, unless the admin tells us to throw it 
away. Data that's thrown away can't be recovered.

**Comment by PascalWithopf** [comment]
With this pull request messages are truncated if they are too long and the following part is processed as a new message.
With the parameter discardTruncatedMsg it is possible to discard the rest of the message instead of processing it.
An error message is given upon truncation, which can be turned off with a second parameter msgDiscardingError.
