### ISSUE TITLE
omelasticsearch: replace cjson with libfastjson

### ISSUE THREAD

**Issue by rgerhards** [rsyslog/rsyslog#1572]
cjson was originally used, but we should unify on libfastjson. This means the module needs to be reviewed and changed accordingly.

**Comment by wdauchy** [comment]
@PascalWithopf do you need any help on this? I started something on my side as well

**Comment by wdauchy** [comment]
oh there is already a pull request for that https://github.com/rsyslog/rsyslog/pull/1601
thanks

**Comment by rgerhards** [comment]
fixed via #1601
