### ISSUE TITLE
segfault after configuration error

### ISSUE THREAD

**Issue by robfr** [rsyslog/rsyslog#1573]
Hello, I have experienced a strange segfault (reproducable on one server only) after leaving a syntax error in my config file. It appears to cause a problem when the rsyslog internal logging system tries to log a message about my config syntax error.

I've attached a gdb session, the debug log and a minimal config that reproduces the problem on my platform. However, like I said, I can't reproduce it elsewhere (even on another Centos 6.5) so it is hard to say where the problem lies.

versions :
os : Centos 6.5 (Linux ---- 2.6.32-431.20.3.el6.x86_64 #1 SMP Thu Jun 19 21:14:45 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
rsyslog : rsyslog-8.27.0-1.el6.x86_64.rpm

reproduce :
```
$ rsyslogd -dn -f test.conf -i /tmp/test.pid
....
-> $$ = nterm s_act ()
Stack now 0 1 6 30 60 99
Entering state 26
Reducing stack by rule 37 (line 192):
   $1 = nterm s_act ()
-> $$ = nterm actlst ()
Stack now 0 1 6 30 60 99
Entering state 25
Reading a token: Next token is token '&' ()
Shifting token '&' ()
Entering state 54
Reading a token: Next token is token '}' ()
0233.712116500:main thread    : Called LogMsg, msg: error during parsing file test.conf, on or before line 9: syntax error on token '}'
Segmentation fault
```

backtrace:
```
#0  AddRef (pThis=0x0) at prop.c:136
#1  0x00007f3d9305b8cd in MsgSetRcvFrom (pThis=0x7f3d9420e0f0, new=0x0) at msg.c:2711
#2  0x00007f3d930383cb in logmsgInternalSubmit (iErr=-2207, pri=43,
    msg=0x7fff65afdc50 "error during parsing file test.conf, on or before line 9: syntax error on token '}' [v8.27.0 try http://www.rsyslog.com/e/2207 ]", flags=0) at rsyslogd.c:875
#3  logmsgInternal (iErr=-2207, pri=43,
    msg=0x7fff65afdc50 "error during parsing file test.conf, on or before line 9: syntax error on token '}' [v8.27.0 try http://www.rsyslog.com/e/2207 ]", flags=0) at rsyslogd.c:924
#4  0x00007f3d93067927 in doLogMsg (iErrno=<value optimized out>, iErrCode=-2207, severity=3,
    msg=0x7fff65afe8b0 "error during parsing file test.conf, on or before line 9: syntax error on token '}'") at errmsg.c:102
#5  0x00007f3d93067c8a in LogError (iErrno=0, iErrCode=-2207, fmt=<value optimized out>) at errmsg.c:134
#6  0x00007f3d930583a6 in parser_errmsg (fmt=<value optimized out>) at rsconf.c:416
#7  0x00007f3d930587ff in yyerror (s=<value optimized out>) at rsconf.c:427
#8  0x00007f3d93045fa0 in yyparse () at grammar.c:2026
#9  0x00007f3d93059925 in load (cnf=0x7f3d932c0948, confFile=0x7fff65b018e4 "test.conf") at rsconf.c:1321
#10 0x00007f3d93039c57 in initAll (argc=<value optimized out>, argv=<value optimized out>) at rsyslogd.c:1407
#11 0x00007f3d9303a23b in main (argc=6, argv=<value optimized out>) at rsyslogd.c:1896
```

[gdb.txt](https://github.com/rsyslog/rsyslog/files/1014442/gdb.txt)
[test_conf.txt](https://github.com/rsyslog/rsyslog/files/1014443/test_conf.txt)
[debug.txt](https://github.com/rsyslog/rsyslog/files/1014441/debug.txt)
[rpms.txt](https://github.com/rsyslog/rsyslog/files/1014466/rpms.txt)

**Comment by jcshort** [comment]
write(2</dev/pts/1>, "Reading a token: ", 17Reading a token: ) = 17
write(2</dev/pts/1>, "Next token is ", 14Next token is ) = 14
write(2</dev/pts/1>, "token LEGACY_ACTION (", 21token LEGACY_ACTION () = 21
write(2</dev/pts/1>, ")", 1))            = 1
write(2</dev/pts/1>, "\n", 1
)           = 1
write(2</dev/pts/1>, "Shifting ", 9Shifting )    = 9
write(2</dev/pts/1>, "token LEGACY_ACTION (", 21token LEGACY_ACTION () = 21
write(2</dev/pts/1>, ")", 1))            = 1
write(2</dev/pts/1>, "\n", 1
)           = 1
write(2</dev/pts/1>, "Entering state 14\n", 18Entering state 14
) = 18
write(2</dev/pts/1>, "Reducing stack by rule 40 (line "..., 38Reducing stack by rule 40 (line 196):
) = 38
write(2</dev/pts/1>, "   $1 = ", 8   $1 = )     = 8
write(2</dev/pts/1>, "token LEGACY_ACTION (", 21token LEGACY_ACTION () = 21
write(2</dev/pts/1>, ")", 1))            = 1
write(2</dev/pts/1>, "\n", 1
)           = 1
clock_gettime(CLOCK_REALTIME, {1495490297, 793889927}) = 0
write(1</dev/pts/1>, "0297.793889927:main thread    : "..., 800297.793889927:main thread    : tried selector action for builtin:omfile: -2001
) = 80
clock_gettime(CLOCK_REALTIME, {1495490297, 793974593}) = 0
write(1</dev/pts/1>, "0297.793974593:main thread    : "..., 800297.793974593:main thread    : tried selector action for builtin:ompipe: -2001
) = 80
clock_gettime(CLOCK_REALTIME, {1495490297, 794059316}) = 0
write(1</dev/pts/1>, "0297.794059316:main thread    : "..., 790297.794059316:main thread    : tried selector action for builtin-shell: -2001
) = 79
clock_gettime(CLOCK_REALTIME, {1495490297, 794145089}) = 0
write(1</dev/pts/1>, "0297.794145089:main thread    : "..., 400297.794145089:main thread    : discard
) = 40
clock_gettime(CLOCK_REALTIME, {1495490297, 794230069}) = 0
write(1</dev/pts/1>, "0297.794230069:main thread    : "..., 1290297.794230069:main thread    : Called LogMsg, msg: warning: ~ action is deprecated, consider using the 'stop' statement instead
) = 129
gettimeofday({1495490297, 794316}, NULL) = 0
open("/etc/localtime", O_RDONLY|O_CLOEXEC) = 3
fstat(3</usr/share/zoneinfo/Zulu>, {st_mode=S_IFREG|0644, st_size=118, ...}) = 0
fstat(3</usr/share/zoneinfo/Zulu>, {st_mode=S_IFREG|0644, st_size=118, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f6b2d81a000
read(3</usr/share/zoneinfo/Zulu>, "TZif2\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\1\0\0\0\1\0\0\0\0"..., 4096) = 118
lseek(3</usr/share/zoneinfo/Zulu>, -62, SEEK_CUR) = 56
read(3</usr/share/zoneinfo/Zulu>, "TZif2\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\1\0\0\0\1\0\0\0\0"..., 4096) = 62
close(3</usr/share/zoneinfo/Zulu>)      = 0
munmap(0x7f6b2d81a000, 4096)            = 0
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x10} ---
+++ killed by SIGSEGV +++
Segmentation fault
```

[gdb-trusty.txt](https://github.com/rsyslog/rsyslog/files/1020318/gdb-trusty.txt)

**Comment by ptarpan** [comment]
hey @jcshort did you find a solution for this? I'm seeing the same issue on other Amazon AMI's.

**Comment by jcshort** [comment]
We've rolled back to 8.26 for the time being

**Comment by ptarpan** [comment]
Could you outline the steps taken to downgrade?

**Comment by rgerhards** [comment]
Isn't the straight work-around to fix the config?

Am 25.05.2017 07:39 schrieb "ptarpan" <notifications@github.com>:

Could you outline the steps taken to downgrade?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/rsyslog/rsyslog/issues/1573#issuecomment-303927639>,
or mute
the thread

**Comment by jcshort** [comment]
@ptarpan we had a copy laying about in our in-house mirrors, i believe PPAs still remove old versions so they're not readily available publicly.

@rgerhards funny story about debugging this - it only manifested during a Packer AMI build job, then the segfaults stopped after about an hour of uptime in debug mode.  Haven't had a chance to eliminate variables yet, e.g. cloud-init, kernel versions.

**Comment by tejas3190** [comment]
Facing the same issue in Ubuntu 14, rsyslog version 8.27 as mentioned by @jcshort. Here is the core dump along with debug logs.  
`Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/sbin/rsyslogd -dn -f /etc/rsyslog.conf -i /var/run/rsyslog.pid'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000000000450b10 in ?? ()
(gdb) info thread
  Id   Target Id         Frame 
* 1    Thread 0x7faf65340780 (LWP 17750) 0x0000000000450b10 in ?? ()
(gdb) thread apply all bt full

Thread 1 (Thread 0x7faf65340780 (LWP 17750)):
#0  0x0000000000450b10 in ?? ()
No symbol table info available.
#1  0x0000000000433395 in MsgSetRcvFrom ()
No symbol table info available.
#2  0x000000000040f0cb in logmsgInternal ()
No symbol table info available.
#3  0x000000000043c049 in ?? ()
No symbol table info available.
#4  0x000000000043c262 in LogMsg ()
No symbol table info available.
#5  0x0000000000418424 in ?? ()
No symbol table info available.
#6  0x000000000042b62a in cflineDoAction ()
No symbol table info available.
#7  0x0000000000423682 in cnfstmtNewLegaAct ()
No symbol table info available.
#8  0x000000000041b442 in yyparse ()
No symbol table info available.
#9  0x000000000042d791 in ?? ()
No symbol table info available.
#10 0x000000000040fb5a in ?? ()
No symbol table info available.
#11 0x000000000040ddd8 in main ()
No symbol table info available.`



[rsyslog_debug_logs.pdf](https://github.com/rsyslog/rsyslog/files/1130588/rsyslog_debug_logs.pdf)

**Comment by abh23** [comment]
Any resolution yet?

**Comment by rgerhards** [comment]
What is the problem in simply correcting the config error? I admit I do not
understand this problem...

Sent from phone, thus brief.

Am 17.07.2017 08:32 schrieb "Amit Bhardwaj" <notifications@github.com>:

**Comment by tejas3190** [comment]
Hi @rgerhards ,

I am observing the problem is not just with the config, it's also failing when module imfile is loaded & not being used. Getting segfault in this case.
Here is the debug logs:

[rsyslog_debug.txt](https://github.com/rsyslog/rsyslog/files/1152088/rsyslog_debug.txt)

**Comment by rgerhards** [comment]
@tehas3190 thanks for the clarification and the debug log. I'll definitely have a look. Just because I am really curious on this point: what is the reason that you do load the module even though you do not need it?

**Comment by rgerhards** [comment]
@tejas3190 I just crafted a test where imfile is loaded but not used, but it does not abort. So I guess there is some relation to other things in your config that trigger the problem.

Could you run rsyslog under valgrind control and submit the resulting logs?

**Comment by rgerhards** [comment]
I also reviewed the posted stack traces once again. Might it be possible that the hostname is not set on these system? Still, this should be handled by the runtime, and there is also a CI test checking for this, but the stack traces point to this reason. So it looks like I really need someone to run valgrind on a failing instance to get any further ... or maybe build a potential "shot-in-the-dark" kind of patch, which may not work at all and is based on wild guesses...

**Comment by rgerhards** [comment]
FYI: I have run the existing test through valgrind and it passes that as well without any issues. Out of clues again..., so waiting for responses.

**Comment by tejas3190** [comment]
Can you provide me the steps for running rsyslog under valgrind ? Thanks alot.

**Comment by rgerhards** [comment]
@tejas3190 will do ... but got a different idea. Let me investigate this briefly, maybe it is promising. Will post more info soon.

**Comment by rgerhards** [comment]
I think I found the root cause. The debug log you posted tells
```2993.845244238:main thread    : getaddrinfo: Name or service not know```
where the local hostname should be set. This is most probably not correctly handled. I have no idea of how I could craft such a test, so it would be appreciated if the proposed patch could be tested by someone who actually experiences the issues. I guess I'll be able to craft a patch today.

**Comment by rgerhards** [comment]
I can now reproduce it by changing (damaging) code so that the triggering condition is enforced. Works for 8.27 and 8.29. Of course, that's not the same as confirmation this actually is the cause **you** are seeing. I may just artificially generate an error...

**Comment by rgerhards** [comment]
I fixed what I think is the root cause with this commit:

https://github.com/rsyslog/rsyslog/pull/1673/commits/7d372e4f5e762115b19e43995945c259cc7227ec

It would be great if somebody could apply the fix and try it out. Note that the testbench also contains a new test for the case, but is is based on the assumption that I was right on the root cause - which was never validated.

**Comment by dmourati** [comment]
I ran into a similar problem with configuration from a v5 rsyslog running on a v8 binary on an AWS host with a wonky hostname. Result was segfault. Fixing the config resolved the segfault. Having the old config and running rsyslog-8.29.0-2.el7.x86_64.rpm also fixed the problem.
