### ISSUE TITLE
[Feature request] Introduce action parameter dynaName

### ISSUE THREAD

**Issue by timtofan** [rsyslog/rsyslog#1574]
As of now we have action parameter **name** which is a string.
Is it possible to implement a **dynaName** parameter to specify a template name instead?

Say you have a single omfile action which writes to 10 different files by using **dynaFile** param.
Then impstats will report writes to all 10 files under a single name.

So in order to have more fine-grained stats for monitoring/troubleshooting/etc you need to change that to 10 actions where each would have a different name. Having a **dynaName** parameter would allow having same fine-grained stats with just a single action.

**Comment by rgerhards** [comment]
That's pretty complicated and the number of stats will grow dramatically. Some of the settings will also not be useful in this context (like dynafile cache counters). I think in essence it will be primarily number of messages delivered. Does that really make sense?

@davidelang do you have an opinion on this?

To set expectations straight: I myself find that idea interesting, but have much more often requested things to do, so I won't implement it in the foreseeable future. But with good reasoning, someone else might step in.

**Comment by davidelang** [comment]
If you need this sort of detail, it's trivial to setup dyn_stats to gather it. 
This is exactly the sort of thing that they were designed for.

We should leave the action stats as they are, breaking them up will lead to 
problems in analyzing program flow and bottlenecks.
