### ISSUE TITLE
configure check for (om)kafka looks wrong

### ISSUE THREAD

**Issue by mbiebl** [rsyslog/rsyslog#1578]
omkafka has the following pkg-config check:
```
PKG_CHECK_MODULES([LIBRDKAFKA], [librdkafka],, [
```
I don't find a librdkafka.pc anywhere in the librdkafka package though, only rdkafka.pc (not the missing "lib" prefix).
The check for imkafka looks correct in that regard, it uses
```
PKG_CHECK_MODULES(LIBRDKAFKA, rdkafka >= 0.9.1)
```
(fwiw, you have inconsistent quoting here).

/CC @alorbach

**Comment by alorbach** [comment]
I believe this has already being fixed by this commit : 
https://github.com/rsyslog/rsyslog/commit/41bfe274e6ab0320d6bdba9e88f0136ad82562e4

**Comment by mbiebl** [comment]
Indeed. Sorry for not checking git master (was looking at 8.27.0)
