### ISSUE TITLE
imfile: Unhandled inotify event -- `IN_MOVED_TO`

### ISSUE THREAD

**Issue by zacharyzhao** [rsyslog/rsyslog#1588]
In our case, we use `logrotate` to rotate log file. It moves `foo.log` to `foo.log.1`, then to `foo.log.2`, etc. At last , `logrotate` cleans `foo.log.9` and moves the empty file to `foo.log` (we just keep 9 log dump files), and this action causes a mistake: rsyslog does not handle inotify's `IN_MOVED_TO` event, so  `foo.log` will never be monitored.

In order to solve this problem, we update `logrotate`'s configuration to avoid moving file back. It works, but I hope rsyslog can do right thing with files which were moved to directory.

My PR: #1587

**Comment by davidelang** [comment]
logrotate takes an old file that rsyslog has fully processed, deletes the 
contents, and moves it to where the new logs should be (all using the same 
inode)???

what logrotate config is this, and why are you doing something so odd?

when you replace foo.log with foo.log.9 you are going to loose the unread 
content of foo.log.

That said, if we don't handle the results of using mv to put a new file in the 
place to be read, that is a problem.

k

**Comment by zacharyzhao** [comment]
I don't know how our client configure their logrotate exactly or why they were doing so, I just noticed that  logrotate did a moving operation as creation after it moves a log file to another, because the new `foo.log`'s inode is the same as `foo.log.9` just now.

**Comment by rgerhards** [comment]
closed via #1587
