### ISSUE TITLE
lmsig_ksi-ls12 does not build on some platforms

### ISSUE THREAD

**Issue by rgerhards** [rsyslog/rsyslog#1594]
detected on Centos7, but may also be a problem on others

**Comment by daniel-lucio** [comment]
Error: Package: rsyslog-8.27.0-3.el7.x86_64 (rsyslog_v8)
           Requires: libksi.so.7()(64bit)

A workaround for the REPO would be to take out the -3 release

**Comment by rgerhards** [comment]
fixed via https://github.com/rsyslog/rsyslog/pull/1603
