### ISSUE TITLE
ksi-ls12 regeression: libksi requirement added to all binaries

### ISSUE THREAD

**Issue by rgerhards** [rsyslog/rsyslog#1600]
The AC_CHECK_LIB macro used adds libksi & dependencies to LIBS variable, which results in all binaries getting this as requirements. That in turn causes packaging problems. Using AC_CHECK_LIBS seems to be unnecessary in any case, because there is a PKG_CHECK_MODULES check which makes a version check. Probably, the macro can just be removed (looks the like). @allanpark any concerns?

**Comment by allanpark** [comment]
It is actually a tiny bit more complicated than that/ Found a fix for this. I shall create a PR for this.
