### ISSUE TITLE
Add null-byte terminator for TCP

### ISSUE THREAD

**Issue by ralberto** [rsyslog/rsyslog#1602]
In order to send messages using TCP/GELF to Graylog it's  necessary to support null-byte as message delimiter.

**Comment by jgerhards** [comment]
since i don't have access to a graylog testing machine, it would be great if you could test the patch and provide feedback.

**Comment by ralberto** [comment]
Hi @jgerhards,

Adding the parameter TCP_FramingDelimiter="0", results in an error during configuration validation. 

`
rsyslogd: error during parsing file /etc/rsyslog.conf, on or before line 47: parameter 'TCP_FramingDelimiter' not known -- typo in config file? [v8.28.0.master ...
`

**Comment by PascalWithopf** [comment]
@ralberto 
When I'm reading it correct the parameter name is "tcp_framedelimiter" and you are using "tcp_framingdelimiter"

**Comment by ralberto** [comment]
Yep... sorry, copy & paste from the wrong place :)

I've added a GELF TCP Input on graylog and configured rsyslog to send messages through that input, and it's working as expected.  

One thing I've noticed is that  messages sent using curl, the new line character (\n) is displayed correctly, i.e., the line breaks. However, using rsyslog the message is displayed in a single line with \n in the middle of the message. Here's an example:

`echo -e '{"version": "1.1","host":"example.org", "short_message":"Short message","full_message":"Backtrace here\n\nmore stuff"}\0' | nc -w 1 127.0.0.1 6555`

This message is displayed:

     Backtrace here

     more stuff
The same message sent using rsyslog is displayed in the same line, i.e.

    Backtrace here\n\nmore stuff

Any idea why is this happening? :-/

**Comment by PascalWithopf** [comment]
You should open a new issue with the question and your whole configuration.

For example:
If you are using imfile as the input to rsyslog then the default behaviour is that multi line messages are added to one line and line feeds are escaped, because most tools do not expect these and they would cause trouble.
For imfile there is an option escapeLF which you could turn off and then it wouldn't escape them.

**Comment by ralberto** [comment]
I'm using imfile and disabling the escapeLF did the trick! Thank you @PascalWithopf.  

@jgerhards, the patch is working.
