### ISSUE TITLE
rsyslog not sending data to logstash

### ISSUE THREAD

**Issue by sLuvpreet33** [rsyslog/rsyslog#1606]
I have followed this [Digital Ocean tutorial][1] to send logs to logstash via rsyslog.

But I am not getting logs in logstash. I am sending logs to a centralized rsyslog-server, and then to logstash. This rsyslog-server and logstash are on the same machine.

This is the /etc/rsyslog.d/50-default.conf file on rsyslog-client :-
   
    *.*                         @xx.xx.xx.xx:514
I have added this line at the top, rest is the same

This is the /etc/rsyslog.conf file on rsyslog-server,
 
    # provides UDP syslog reception
    module(load="imudp")
    input(type="imudp" port="514")

    # provides TCP syslog reception
    module(load="imtcp")
    input(type="imtcp" port="514")
 
I have enabled these modules, rest is same as default. Below is the file, /etc/rsyslog.d/01-json-template.conf

     template(name="json-template" type="list") {
    constant(value="{")
      constant(value="\"@timestamp\":\"")     property(name="timereported" dateFormat="rfc3339")
      constant(value="\",\"@version\":\"1")
      constant(value="\",\"message\":\"")     property(name="msg" format="json")
      constant(value="\",\"sysloghost\":\"")  property(name="hostname")
      constant(value="\",\"severity\":\"")    property(name="syslogseverity-text")
      constant(value="\",\"facility\":\"")    property(name="syslogfacility-text")
      constant(value="\",\"programname\":\"") property(name="programname")
      constant(value="\",\"procid\":\"")      property(name="procid")
    constant(value="\"}\n")
    }

And the last is my output file config which sends data to logstash, it is also on the rsyslog-server machine, 

    *.*                         @127.0.0.1:5044;json-template

This below is my logstash configuration, 

    input {
    udp {
        host => "127.0.0.1"
        port => "5044"
        codec => "json"
        type => "rsyslog"
    }
    }

    output {
      elasticsearch {
        hosts => [ "localhost:9200" ]
        user => xxxxxxxx
        password => xxxxxxx
        index => "%{type}_index"
    }
    }

Still, with all this configuration, I dont see my rsyslog_index in elasticsearch. All the ports are up and running, there is no firewall issue also.

What and where is the problem ?

  [1]: https://www.digitalocean.com/community/tutorials/how-to-centralize-logs-with-rsyslog-logstash-and-elasticsearch-on-ubuntu-14-04#step-3-%E2%80%94-configuring-the-centralized-server-to-receive-data

**Comment by sLuvpreet33** [comment]
I have tested this on my local machine, and it works fine on my local machine. Just not working on my servers.

**Comment by davidelang** [comment]
so what is different between your local machine and your servers? Are there 
firewall or SELinux differences?

what shows up on logstash? does it see any data? is the connection between 
rsyslog and logstash established and passing traffic (tcpdump and netstat -an 
are tools that can help here)

**Comment by sLuvpreet33** [comment]
The logstash does not see any data. The firewall issues are most probably not there.

Is my rsyslog config ok ?

Are these actions logged ? If logs are being made of it, then I can check what is going wrong.

**Comment by davidelang** [comment]
does the netstat show a connection being established?

If so, does tcpdump show any data flowing?

David Lang

**Comment by sLuvpreet33** [comment]
Okay, this problem was solved.

But there are other questions I want to ask.

1 - For sending logs from application to rsyslog, I  should use UDP, and for sending logs from rsyslog directly to elasticsearch, I should use TCP for making use of queues. Is it correct ?

2 - What is the maximum limit upto which rsyslog can send data to elasticsearch ? Like how many logs it can send in 1 second ?  Can I put a maximum limit manually on the number of logs sent per second ?

**Comment by sLuvpreet33** [comment]
Also, is debugging option not available now OR is it deprecated ?

       $DebugFile /var/log/rsyslog-debug.log
       $DebugLevel 

You did not mention it.

**Comment by davidelang** [comment]
On Thu, 8 Jun 2017, Luvpreet Singh wrote:

> But there are other questions I want to ask.
>
> 1 - For sending logs from application to rsyslog, I  should use UDP, and for sending logs from rsyslog directly to elasticsearch, I should use TCP for making use of queues. Is it correct ?

elasticsearch will use TCP (that's the only protocol it supports), you can use 
many different protocols to delier messages to rsyslog. If you are on the same 
system, you should write logs to /dev/log. There are pros and cons to using TCP 
vs UDP and there are other procols that youc an use if it's appropriate.

> 2 - What is the maximum limit upto which rsyslog can send data to elasticsearch ? Like how many logs it can send in 1 second ?  Can I put a maximum limit manually on the number of logs sent per second ?

last I tested, much faster than elasticsearch can process them :-)

**Comment by davidelang** [comment]
On Fri, 9 Jun 2017, Luvpreet Singh wrote:

> Also, is debugging option not available now OR is it deprecated ?
>
>       $DebugFile /var/log/rsyslog-debug.log
>       $DebugLevel
>
> You did not mention it.

your problems were not complex enough to need doing this sort of thing, the 
debug log can be VERY verbose.

**Comment by sLuvpreet33** [comment]
> last I tested, much faster than elasticsearch can process them :-)
That can cause a problem if elasticsearch cannot process them properly, can we limit the rate of sending logs per second ?

**Comment by davidelang** [comment]
On Fri, 9 Jun 2017, Luvpreet Singh wrote:

>> last I tested, much faster than elasticsearch can process them :-)
> That can cause a problem if elasticsearch cannot process them properly, can we 
limit the rate of sending logs per second ?

no, there is not currently a way to slow rsyslog down, but if ES can't process 
the log rsyslog is sending, it will not ack the data, so rsyslog will slow down 
automatically.

**Comment by sLuvpreet33** [comment]
Cool !

What do you suggest I should use to send application(like nginx, postgresql) logs to rsyslog, unix-socket, udp OR tcp ?

**Comment by davidelang** [comment]
unix socket is always the least overhead. If the program has an option to send 
logs to syslog, that almost always defaults to writing to the local unix socket 
on the machine.

**Comment by sLuvpreet33** [comment]
@davidelang I am having trouble getting the omelasticsearch module in my machine.

Can you please provide some help ?

**Comment by sLuvpreet33** [comment]
I downloaded the tarball, and then ,

    luvpreet@DHARI-Inspiron-3542:~/Desktop/rsyslog-8.27.0$ sudo ./configure --enable-om
    --enable-omamqp1              --enable-omjournal            --enable-omrelp-default-port  --enable omuxsock
    --enable-omczmq               --enable-omkafka              --enable-omruleset            --enable-omzmq3
    --enable-omhdfs               --enable-ommongodb            --enable-omstdout             
    --enable-omhiredis            --enable-omprog               --enable-omtcl                
    --enable-omhttpfs             --enable-omrabbitmq           --enable-omudpspoof

**Comment by davidelang** [comment]
so you aren't using the pre-built packages?

Why not?

**Comment by sLuvpreet33** [comment]
Hey @davidelang ,  sorry for above comments, it was `--enable-elasticsearch` and not, `--enable-omelasticsearch`.

But now, I have another question.
I have not declared any queues in my config file. 

below is the conf file I have made for sending to elasticsearch.

    action(type="omelasticsearch"
       server="127.0.0.1"
       serverport="9200"
       searchIndex="direct-from-rsyslog"
       bulkmode="on"
       action.resumeretrycount="-1"
    )

It was succesful. After that I stopped elasticsearch. What I think that when elasticsearch is stopped, then all the logs are lost. If we want to make a reliable system, then we should use queues. But I have not used any.

But something is happening I don't understand.
Below is the RAM usage of rsyslog, after I stopped elastcisearch, it goes on increasing. 
![screenshot from 2017-06-12 14-54-38](https://user-images.githubusercontent.com/23127804/27027958-e3087edc-4f80-11e7-8a47-77184bc2e439.png)


And after that, when I turned elasticsearch back on, I see that no logs are lost. Even when elastic was down, the logs of that time have reached here.
![screenshot from 2017-06-12 14-56-24](https://user-images.githubusercontent.com/23127804/27028010-16068838-4f81-11e7-89d9-a48997c84751.png)


Can you explain this behaviour as to how my logs were able to reach elasticsearch when it was down.
If this behaviour is available by default, then why do we need queues ?

**Comment by davidelang** [comment]
rsyslog has a single main queue by default, so the logs were queued there.

**Comment by sLuvpreet33** [comment]
Oh I see !

Is there any need for a new action queue if I am doing only one action i.e, sending logs to elasticsearch only ? OR this primary key will be sufficient ?

**Comment by davidelang** [comment]
you put in an action queue if you want to decouple that one action from the 
processing of the rest of the system.

If you just use the main queue, all logging stops when you can't deliver logs to 
ES, if you put a queue just on that action, only that action stops (unless that 
queue fills up)

**Comment by sLuvpreet33** [comment]
Can we write to some file once the queue is full 
1- main ? 
2 -action ?

**Comment by davidelang** [comment]
On Mon, 12 Jun 2017, Luvpreet Singh wrote:

> Can we write to some file once the queue is full
> 1- main ?
> 2 -action ?

that's what a disk assisted queue is.

**Comment by sLuvpreet33** [comment]
Can we secure rsyslog by username password ?

Or http://www.rsyslog.com/doc/v8-stable/tutorials/tls_cert_summary.html  is the only option ?

**Comment by rgerhards** [comment]
This is going way of topic. I suggest the rsyslog mailing list for how to discussions, otherwise please open dedicated issues. Thanks!
