### ISSUE TITLE
rsyslogd log retention to send to remote server 

### ISSUE THREAD

**Issue by rp-happiestbaby** [rsyslog/rsyslog#1607]
Hi,
I have server which is receiving logs from servers (syslog-ng).
And all other servers sending logs with rsyslogd.

If my syslog-ng server will be terminated When and how much data it will send to log server when syslog-ng will be avalabe
(I want to know how many days rsyslogd will keep logs and how much data, what is threshold to store logs for rsyslogd before my syslog-ng will be up and will accept connections)

**Comment by davidelang** [comment]
This all depends on the queue settings on your sending system. By default 
rsyslog keeps the messages in a 10K memory queue. You can set the queue to be 
larger, set it to spill to disk when it gets to full, set it to save to disk on 
a clean shutdown, and many other items.

how this translates into time depends on how fast your system generates 
messages.

**Comment by rp-happiestbaby** [comment]
Thank you @davidelang 
One more think after server reboot all queue will be deleted right ? 
And how do i set queue to be on disk and make it larger ?


Thanks in advance !

**Comment by davidelang** [comment]
when you reboot, anything in RAM is lost.

read up on queues and ask other questions (asking on the mailing list is better 
than as a github issue)

http://www.rsyslog.com/doc/v8-stable/concepts/queues.html
http://www.rsyslog.com/doc/v8-stable/rainerscript/queue_parameters.html
