### ISSUE TITLE
property $programname not available inside ruleset

### ISSUE THREAD

**Issue by kortemik** [rsyslog/rsyslog#1608]
We are using rulesets as:

input(type="imtcp" port="10514" address="10.128.99.153" ruleset="exampleset")

ruleset(name="exampleset") {
call omfileset
}

ruleset(name="omfileset") {
    if $programname != "" then {
        action(type="omfile" ...)
    } else {
        action(type="omfile" ...)
    }
}

debug shows that programname is not set while doing the if-else. Therefore else is always called.

Note: for dynafile template used in action omfile %PROGRAMNAME% is available.

**Comment by davidelang** [comment]
On Thu, 8 Jun 2017, Mikko Kortelainen wrote:

> We are using rulesets as:
>
> input(type="imtcp" port="10514" address="10.128.99.153" ruleset="exampleset")
>
> ruleset(name="exampleset") {
> call omfileset
> }
>
> ruleset(name="omfileset") {
>    if $programname != "" then {
>        action(type="omfile" ...)
>    } else {
>        action(type="omfile" ...)
>    }
> }
>
> debug shows that programname is not set while doing the if-else. Therefore else is always called.
>
> Note: for dynafile template used in action omfile %PROGRAMNAME% is available.

Please log with the template RSYSLOG_DebugFormat just before the if statement 
(or before the call to omfileset if you think that's causing the problem. 
All properties should be defined not matter what ruleset is used.

**Comment by rgerhards** [comment]
@kortemik could you do as David suggested? I, too, think this is caused by parsing and/or original message...

**Comment by rgerhards** [comment]
@kortemik i assume this is solved. If not, please let me know and I will re-open.
