### ISSUE TITLE
mmanon plugin doesn't support IPv6

### ISSUE THREAD

**Issue by mejo-** [rsyslog/rsyslog#1614]
Hello,

I just discovered that the `mmamon` IP address anonymization plugin for rsyslog doesn't support IPv6. I found a blog post by Rainer Gerhards from 2013 where he mentions that "[IPv6 support is planned](http://blog.gerhards.net/2013/04/log-anonymization-with-rsyslog.html)".

@rgerhards: Do you still work on that? Do you have a preliminary version available for testing?

Im asking as IPv6 is (slowly) becoming reality ;)

**Comment by xshadow** [comment]
I'm also looking for a solution with mmanon with IPv6, would be happy to test.

**Comment by xshadow** [comment]
@rgerhards  Could you provide the current state of the code? Else I would think about to setup a bug bounty.

**Comment by davidelang** [comment]
setup your bug bounty, the todo list is so long that getting anything anywhere 
on it done elsewhere will leave time for other things.
k

**Comment by mejo-** [comment]
The bug bounty is set up: https://www.bountysource.com/issues/46205295-mmanon-plugin-doesn-t-support-ipv6

**Comment by jgerhards** [comment]
How would you like to anonymize the address? are there any parameters you think are neccessary, i.e. how may bits are to be anonymized?

**Comment by mejo-** [comment]
I would expect all bits to be anonymized, e.g. by replacing it with `0:0:0:0:0:0:0:0`. Just like the mmanon plugin does for IPv4 right now.

**Comment by jgerhards** [comment]
In that case i'll try to implement an ipv6 anonymizer similar to the ipv4 one. After i'm done with that, i might put in some more work.

**Comment by mejo-** [comment]
@jgerhards: that would be awesome. You will do privacy-aware admins and their users a big favour. Log anonymization is an important step for data minimization.

**Comment by mejo-** [comment]
@jgerhards: that would be awesome. You will do privacy-aware admins and their users a big favour. Log anonymization is an important step for data minimization.

**Comment by davidelang** [comment]
If you are wanting to replace all of something (IP address or anything else), 
keep in mind that you can parse things with mmnormalize, and get back the rule 
that is matched as one of the variables

Since that rule includes the variable names in place of the data that is parsed 
to that name, this is the 'perfect' anonomization for any data type. You can 
then just remove the variables you don't want to have show up, and you have a 
json object that contains the template and the variable contents you are willing 
to share.

**Comment by jgerhards** [comment]
quick update: I have found some bugs in the ipv4 anonymizer that I'll fix before getting back to work on the ipv6 one.

**Comment by mejo-** [comment]
Thanks at @jgerhards for working on it.

**Comment by jgerhards** [comment]
I have now started a [meta issue tracker](https://github.com/rsyslog/rsyslog/issues/1723) for the ipv4 bugs (and rewrite) as well as ipv6 function.

However, **please don't close this issue** since it will still be in use for the initial ipv6 anonymization feature request.

**Comment by jgerhards** [comment]
update on mmanon rewrite: http://jan.gerhards.net/2017/08/rewriting-mmanon-update.html

**Comment by xshadow** [comment]
Sounds pretty awesome! Thanks

**Comment by jgerhards** [comment]
I have now completed implementing IPv6 support for mmanon. It now just needs to be merged. You can find out more here: http://jan.gerhards.net/2017/09/mmanon-rewrite-finished-for-time-being.html

**Comment by t2d** [comment]
Can we maybe stall the payout of the bounty? I don't have the capacity to extensively test a self-compiled version at the moment. There has been no release or build and I can't check, that it works as expected. But also, I don't want reject the bounty claim.

**Comment by rgerhards** [comment]
Just FYI: there are daily build packages at least for Ubuntu.

**Comment by rgerhards** [comment]
I should have provided the link... ;-) http://www.rsyslog.com/downloads/download-daily-build/

**Comment by t2d** [comment]
Thanks, but I need to test on Debian stable.

**Comment by t2d** [comment]
The latest version for Ubuntu zesty seems to be outdated and not installable
```
➜  ~ apt-cache madison rsyslog
   rsyslog | 8.26.0~20170322151113-0adiscon1zesty | http://ppa.launchpad.net/adiscon/v8-devel/ubuntu zesty/main amd64 Packages
   rsyslog | 8.16.0-1ubuntu5 | http://de.archive.ubuntu.com/ubuntu zesty/main amd64 Packages
➜  ~ sudo apt install rsyslog
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 rsyslog : Depends: liblogging-stdlog1 but it is not installable
E: Unable to correct problems, you have held broken packages.
```

**Comment by rgerhards** [comment]
> The latest version for Ubuntu zesty seems to be outdated and not installable

I would appreciate if you could open a bug report at https://github.com/rsyslog/rsyslog-pkg-ubuntu as this does not directly relate to the rsyslog project (and the packagers look here only very occasionally).

**Comment by rgerhards** [comment]
@mbiebl do you have any idea when rsyslog 8.30 (release target mid october) will make it into debian stable?

**Comment by mejo-** [comment]
@rgerhards: probably rsyslog 8.30 will never make it into Debian Stretch (current stable). But once rsyslog 8.30 is in Debian Unstable (which usually happens quite fast thanks to the awesome work of @mbiebl), backporting it to stretch-backports should be an easy task.

**Comment by mbiebl** [comment]
Atm a stretch backport is rather straightforward so I'm happy to provide one if there is user demand (assuming 8.30.0 doesn't radically change any build dependencies).
@mejo- if you want to see such a 8.30.0 backport, please file a corresponding bug against the Debian package, so I don't forget. Thanks!

**Comment by jgerhards** [comment]
FYI: http://jan.gerhards.net/2017/10/slfa-release.html
might be interesting in regards to anonymization already existing log files.

**Comment by t2d** [comment]
Are you aware of [loganon](https://github.com/sys4/loganon)? It seems like a bit of a similar project.

**Comment by jgerhards** [comment]
I've briefly looked at it and decided to start slfa, because it has a much broader focus. For example, one goal is to be able to train analyzers or liblognorm with psodomized output.

Of course, slfa is still in its infancy, but there are already some differences i'd like to point out:

- slfa is capable of pseudonymizing IP addresses, which might be useful when analyzing log files
- since loganon is written in python, slfa might be faster (no benchmark yet)
- in loganon, a regex can only be replaced by a static string, but not randomized, which is possible with slfa

I also plan on implementing more options and parsers to slfa.

**Comment by jgerhards** [comment]
@t2d have you tested it yet?

**Comment by mejo-** [comment]
Hey. Thanks to @mbiebl rsyslog 8.30 is in Debian stretch-backports now. I just gave it a try and it works like a charm for me with the following settings:

```
module(load="mmanon")
action(type="mmanon" mode="zero" ipv4.bits="32" ipv6.bits="128")
```

Thanks a lot @jgerhards for implementing it!
