### ISSUE TITLE
crash on start/hup on centos6 with imfile

### ISSUE THREAD

**Issue by evgkrsk** [rsyslog/rsyslog#1615]
Shortly after updates (to rsyslog-8.27* from official repo) of our Centos6 systems we catch following issue:

```
[root@hosting]~# service rsyslog status
rsyslogd dead but pid file exists
[root@hosting]~# service rsyslog restart 
Shutting down system logger:                               [FAILED]
Starting system logger:                                    [  OK  ]
[root@hosting]~# Ohhhh jeeee: Assertion `pool_is_locked' failed (random-csprng.c:1075:add_randomness)

[root@hosting]~# service rsyslog status 
rsyslogd dead but pid file exists
[root@hosting]~# rpm -q --changelog rsyslog |head -n 5
* Fri May 19 2017 Florian Riedl
- Fixed liblognorm dependency

* Tue May 16 2017 Florian Riedl
- Updated RPM's for Rsyslog 8.27.0

[root@hosting]~# ls -lht /var/lib/rsyslog 
total 16K
-rw------- 1 root root 255 Jun 14 03:37 imfile-state:-usr-local-mgr5-var-ispmgrnode.log
-rw------- 1 root root 251 Jun 14 03:37 imfile-state:-usr-local-mgr5-var-ispmgr.log
-rw------- 1 root root 257 Jun 14 03:37 imfile-state:-var-lib-mysql-hosting.optibit.ru.err
-rw------- 1 root root 238 Jun 14 03:37 imfile-state:-var-log-mysqld.log
[root@hosting]~# rm -f /var/lib/rsyslog/*.log
[root@hosting]~# service rsyslog restart
Shutting down system logger:                               [FAILED]
Starting system logger:                                    [  OK  ]
[root@hosting]~# service rsyslog status 
rsyslogd (pid  311083) is running...
[root@hosting]~# 
```

but next day after that restart, rsyslog crashed again with same syndroms (HUP from logrotate, I think).

**Comment by alorbach** [comment]
Can you try rsyslog 8.28 ?

**Comment by evgkrsk** [comment]
Version 8.28.0-1.el6 is affected as well.

**Comment by evgkrsk** [comment]
BTW, i have many machines where imfile just "hangs" and stop forwarding strings from high-volume logs until rsyslog's restart. Some time later, forwarding stops again :-(

**Comment by devicenull** [comment]
I'm seeing this on rsyslog-8.28.0-1.el6.x86_64 as well.  This appears to be related to gnutls (it only started when we enabled TLS)

**Comment by Overbryd** [comment]
Same version here, running a tls setup with gnutls.
Any information or straces I can provide to help debug the issue?

devicenull <notifications@github.com> schrieb am Mi. 12. Juli 2017 um 20:02:

**Comment by jaredledvina** [comment]
Tossing my +1 on this as well. We're on `CentOS release 6.9 (Final)` and with both rsyslog 8.28 and 8.27 we're seeing the exact same error. I've downgraded to 8.26 and so far the issues hasn't resurfaced. The specific packages we're running are:
```
rsyslog-8.26.0-1.el6.x86_64 rsyslog-gnutls-8.26.0-1.el6.x86_64 rsyslog-elasticsearch-8.26.0-1.el6.x86_64 rsyslog-mmnormalize-8.26.0-1.el6.x86_64
```

Happy to provide any other info if it'll help debug this issue!

**Comment by wbrian-onlineed** [comment]
I can't fix the bug, but i got things to work by clearing the spool:
`sudo rm /var/spool/rsyslog/*`

**Comment by davidelang** [comment]
corrupt queue files can cause a lot of problems, see the discussion on modifying 
systemd config to give rsyslog time to shutdown properly.

**Comment by qha** [comment]
We also see this message ("Ohhhh jeeee: Assertion `pool_is_locked' failed (random-csprng.c:1075:add_randomness)") as the last line in our rsyslog debug log after most Rsyslog crashes on one host.

Module imfile not loaded, no forwarding configured (all messages written to disk or discarded) and /sbin/init from upstart-0:0.6.5-16.el6.x86_64 but we have configured imtcp with gtls stream driver.

CentOS release 6.9 (Final)

# yum info rsyslog
Loaded plugins: fastestmirror, security
Loading mirror speeds from cached hostfile
Installed Packages
Name        : rsyslog
Arch        : x86_64
Version     : 8.29.0
Release     : 1.el6
Size        : 2.3 M
Repo        : installed
From repo   : rsyslog_v8
Summary     : Enhanced system logging and kernel message trapping daemon
URL         : http://www.rsyslog.com/
License     : (GPLv3+ and ASL 2.0)
Description : Rsyslog is an enhanced, multi-threaded syslog daemon. It supports
            : MySQL, syslog/TCP, RFC 3195, permitted sender lists, filtering on
            : any message part, and fine grain output format control. It is
            : compatible with stock sysklogd and can be used as a drop-in
            : replacement. Rsyslog is simple to set up, with advanced features
            : suitable for enterprise-class, encryption-protected syslog relay
            : chains.

**Comment by mowgli** [comment]
Let me add my metoo.

I even updated to 8.29.0-1.el6 and the error persists on two of my machines.

and even worse, the removal of /var/spool/rsyslog/* (what had worked in the past) does not work with this two machines.

I am somewhat out of an idea.

**Comment by Overbryd** [comment]
Switching all our systems to ‚syslog-ng‘ (has an equivalent feature set
with similar performance characteristics) solved the problem for us.
Tls transport support works even better with syslog-ng.


Let me add my metoo.

**Comment by mowgli** [comment]
It also help to switch off tls. This is also needed as we have a mixed centos6 and centos7 setup and the gnutls versions in them are not able to speak with each other.

That proves that the problem lies in the gnutls stuff.

It is a suboptimal solution, however, in this setup I can live with it for some time.

**Comment by tweeks024** [comment]
rsyslogd 8.31.0 is also effective, does anyone know what version this was introduced in?  I know it was working in 8.22.0

**Comment by rgerhards** [comment]
this seems to be an issue with the gnutls version shipped in CentOS6 -- @PascalWithopf is currently working on an openssl implementation, which will hopefully solve this issue as well.

**Comment by tweeks024** [comment]
Thanks, I rolled rsyslog and rsyslog-gnutls back for 8.22.0 and its working properly until the fix is out

**Comment by wbrian-onlineed** [comment]
For what its worth, I'm still having this problem but have isolated it somewhat. 

I am running the problem system as an AWS EC2 instance. I configure the system on a 1GB RAM system, save as a disk image, and relaunch on a 4GB production system. Rsyslog works fine on the small box launched from the exact same image, can be rebooted, and service can be started/stopped normally. However when the image is launched on the large machine, rsyslog goes into it's normal hissy fit and refuses to start up, erroring with "Ohhhh jeeee: Assertion `pool_is_locked' failed (random-csprng.c:1078:add_randomness)". Deleting state files no longer works.

Additional info: 

rsyslogd 8.29.0, compiled with:
        PLATFORM:                               x86_64-redhat-linux-gnu
        PLATFORM (lsb_release -d):
        FEATURE_REGEXP:                         Yes
        GSSAPI Kerberos 5 support:              No
        FEATURE_DEBUG (debug build, slow code): No
        32bit Atomic operations supported:      Yes
        64bit Atomic operations supported:      Yes
        memory allocator:                       system default
        Runtime Instrumentation (slow code):    No
        uuid support:                           Yes
        Number of Bits in RainerScript integers: 64

**Comment by rgerhards** [comment]
Just to provide info that probably was missing: CentOS 6's version of gnuTLS does not properly work in some multithreaded cases (obviously). However, there is also an openssl TLS driver available (I think since 8.37). A major reason for writing it was to be able to support TLS on CentOS 6 again. So this driver should be used instead of gnutls. Another big plus is that openssl gives us much better error message, e.g. on certificate problems. The openssl driver will become the preferred one, on all distros.

**Comment by gleventhal** [comment]
How do you configure the openssl driver to be used by rsyslog instead of the gnutls?  Can you provide an example please?

**Comment by rgerhards** [comment]
well, it's exactly the same except that instead of the `gtls` driver you select `ossl`.

**Comment by gleventhal** [comment]
@rgerhards Perfect, thanks!

**Comment by simonsunx** [comment]
@gleventhal @rgerhards Could you share ossl driver config?

I caught same issue (pool_is_locked) in CentOS 6.8 with rsyslog 8.1904.0. My experiments with ossl config failed.

May be tail of rsyslog -dn will be helpful:
```
2737.322422116:main Q:Reg/w0  : rainerscript.c: 7F 2737.322423839:action-0-builtin:omfwd queue:Reg/w0: ../action.c: processBatchMain: i 0, COMM state set
2737.322425880:action-0-builtin:omfwd queue[DA]:Reg/w0: omfwd.c: omfwd: add 132 bytes to send buffer (curr offs 416)

2737.322429722:main Q:Reg/w0  : rainerscript.c: 7F 2737.322431611:action-0-builtin:omfwd queue:Reg/w0: ../action.c: actionCommit[action-0-builtin:omfwd]: enter, 1 msgs
2737.322433687:action-0-builtin:omfwd queue[DA]:Reg/w0: omfwd.c: omfwd: add 127 bytes to send buffer (curr offs 548)

2737.322452834:main Q:Reg/w0  : rainerscript.c: 7F 2737.322460874:action-0-builtin:omfwd queue:Reg/w0: ../action.c: actionCommit[action-0-builtin:omfwd]: processing...
2737.322462670:action-0-builtin:omfwd queue[DA]:Reg/w0: omfwd.c: omfwd: add 132 bytes to send buffer (curr offs 675)

2737.322468081:main Q:Reg/w0  : rainerscript.c:  X 2737.322469756:action-0-builtin:omfwd queue:Reg/w0: ../action.c: actionTryCommit[action-0-builtin:omfwd] enter
2737.322471658:action-0-builtin:omfwd queue[DA]:Reg/w0: omfwd.c: omfwd: add 127 bytes to send buffer (curr offs 807)

2737.322475969:main Q:Reg/w0  : rainerscript.c:  X 2737.322478070:action-0-builtin:omfwd queue:Reg/w0: ../action.c: doTransaction: have commitTransaction IF, using that, pWrkrInfo 0x7f13848ec720
2737.322479695:action-0-builtin:omfwd queue[DA]:Reg/w0: omfwd.c: omfwd: add 106 bytes to send buffer (curr offs 934)

2737.322483817:main Q:Reg/w0  : rainerscript.c: 7F 2737.322485943:action-0-builtin:omfwd queue:Reg/w0: ../action.c: entering actionCallCommitTransaction[action-0-builtin:omfwd], state: itx, nMsgs 1
2737.322947360:action-0-builtin:omfwd queue:Reg/w0: ../action.c: checking external state file
2737.322489146:action-0-builtin:omfwd queue[DA]:Reg/w0: nsd_gtls.c: CheckConnection for 0x7f137c01a260
2737.322952513:action-0-builtin:omfwd queue:Reg/w0: ../action.c: done checking external state file, iRet=0
2737.322956786:action-0-builtin:omfwd queue:Reg/w0: omfwd.c: omfwd: OS does not support network namespaces
2737.322963000:action-0-builtin:omfwd queue:Reg/w0: omfwd.c: omfwd: doTryResume rsyslog.myawesomedomain.ru iRet 0
2737.322967013:action-0-builtin:omfwd queue:Reg/w0: omfwd.c:  rsyslog.myawesomedomain.ru:10514/tcp
2737.322971615:action-0-builtin:omfwd queue:Reg/w0: omfwd.c: omfwd: add 132 bytes to send buffer (curr offs 0)
2737.322976240:action-0-builtin:omfwd queue:Reg/w0: nsd_gtls.c: CheckConnection for 0x7f1364004ea0

2737.322491358:main Q:Reg/w0  : rainerscript.c: 7F 
2737.322992287:main Q:Reg/w0  : rainerscript.c: 7F 7F 7F 7F 7F 7F 7F Ohhhh jeeee: 7F Assertion `pool_is_locked' failed (random-csprng.c:1075:add_randomness)
7F 7F 7F 7F 7F 
2737.323044157:main Q:Reg/w0  : ruleset.c: PRIFILT condition result is 1
```

**Comment by qha** [comment]
@simonsunx I think this is what i have configured to receive logs with Openssl:

    global(defaultnetstreamdrivercafile="/path/to/ca-cert.pem"
           defaultnetstreamdrivercertfile="/path/to/receiver-node-cert.pem"
           defaultnetstreamdriverkeyfile="/path/to/receiver-node.key.pem")
    module(load="imtcp"
           streamdriver.name="ossl"
           streamdriver.mode="1"
           streamdriver.authmode="x509/certvalid"
           notifyonconnectionclose="on")
    input(type="imtcp"
          address="receiver-node.example.net"
          port="6514"
          name="signedsources")
