### ISSUE TITLE
add rainerscript function is_timestamp()

### ISSUE THREAD

**Issue by rgerhards** [rsyslog/rsyslog#1624]
It would be useful to add a function

```is_timestamp(property, format)```

where property is any (string) property and format is a set of known formats (e.g. rfc3339, unix timestamp, ...). The function shall return 1 if this is a timestamp in specified format and 0 if it is invalid. This could also be used in conjunction with conversion functions (common core functionality).

see also https://github.com/rsyslog/rsyslog/issues/971

**Comment by mrworkman** [comment]
@mrworkman

**Comment by rgerhards** [comment]
@mrworkman any plans to implement this one here? ;-) I wonder if I should shuffle the release goal, thus the question.

**Comment by mrworkman** [comment]
Yes, but probably not by the 24th. I wish the days were longer!

**Comment by rgerhards** [comment]
> I wish the days were longer!

haha, we are in the same camp. I'll move the release goal to 8.32 - we can always move it back. But so it doesn't pollute the list of "this could be done" the next couple of days ;-)

**Comment by jgerhards** [comment]
I have just seen this issue on the tracker and I have noticed I have already worked on an isDate function, though it does not work. You can find it here: https://github.com/rsyslog/rsyslog/commit/52bbf957e7bc9f56d9be2d7a94b1143979f35a09
Would you like to work together on date related functions? However, i will probably be short on time next week.

**Comment by mrworkman** [comment]
I'm ok working on them together, though I had a different approach in mind for this function. I'm open to sharing thoughts, etc...

**Comment by jgerhards** [comment]
great. I personally have not worked much on open source yet and would appreciate your advice. What is the direction you wanted to take?

**Comment by mrworkman** [comment]
@jgerhards, sorry for the delay, guess I didn't have much time this week either :) 

I think, from reading your code, you're trying to parse numerically formatted dates only. No time parsing. Rainer already has some functions internally for parsing standard syslog date/time strings that can be used (see the recently added `parse_time()` function which uses them). I was going to start by using those, with future iterations supporting strptime-like options.

**Comment by mrworkman** [comment]
Hoping to work on this this weekend, but my wife wants me to do Christmassy stuff, so we'll see ;)

**Comment by mrworkman** [comment]
Suggest going with `is_time()` rather than `is_timestamp()` for consistency with `parse_time()` and `format_time()`.

**Comment by rgerhards** [comment]
implemented via #450
