### ISSUE TITLE
some logs can not be created for some ip addresses 

### ISSUE THREAD

**Issue by hoyeunglee** [rsyslog/rsyslog#1627]
rsyslog server has two ethernet cards, and two ip address,  one of ip address is for same vlan 53 , other hosts from the same vlan 53 can create log file in /var/log/remote but some window host from vlan 53 send udp syslog , these syslog can not create log file in the linux

i add ip address and hostname in /etc/hosts ,and restart rsyslog service and run all combinations of facilities with level using a testing program can see all messages received with tcpdump, but still no log files created

**Comment by rgerhards** [comment]
Please post your full config.

**Comment by hoyeunglee** [comment]
=~=~=~=~=~=~=~=~=~=~=~= PuTTY log 2017.03.24 08:56:41 =~=~=~=~=~=~=~=~=~=~=~=
lscd /etc/rsyslog.d/
]0;noc@xcpalx03:/etc/rsyslog.d[root@xcpalx03 rsyslog.d]# ls
40-from-remote.conf  local-enable-tcp.conf
]0;noc@xcpalx03:/etc/rsyslog.d[root@xcpalx03 rsyslog.d]# cat 40-from-remote.conf 
#  Default rules for remote server logs

# log every host in its own directory
$template RemoteHost,"/var/log/remote/%HOSTNAME%.log"

#if $hostname != 'xcpalx03new1' then {
#if $hostname != 'xcpalx04' then {
if $hostname != 'xcpalx03' then {
        *.* ?RemoteHost
        stop
}
]0;noc@xcpalx03:/etc/rsyslog.d[root@xcpalx03 rsyslog.d]# cat local-s[Kenable-tcp.conf 
# enable UDP syslog reception

#$ModLoad imudp
#$UDPServerRun 514

# enable TCP syslog reception
#$ModLoad imtcp
#$InputTCPServerRun 514
]0;noc@xcpalx03:/etc/rsyslog.d[root@xcpalx03 rsyslog.d]# cd /etc/
]0;noc@xcpalx03:/etc[root@xcpalx03 etc]# cat syslog.con[K[K[K[K[K[K[K[K[K[Krsyslog.conf
# rsyslog v5 configuration file

# For more information see /usr/share/doc/rsyslog-*/rsyslog_conf.html
# If you experience problems, see http://www.rsyslog.com/doc/troubleshoot.html

#### MODULES ####

$ModLoad imuxsock # provides support for local system logging (e.g. via logger command)
$ModLoad imklog   # provides kernel logging support (previously done by rklogd)
#$ModLoad immark  # provides --MARK-- message capability

# Provides UDP syslog reception
$ModLoad imudp
$UDPServerRun 514

# Provides TCP syslog reception
#$ModLoad imtcp
#$InputTCPServerRun 514


#### GLOBAL DIRECTIVES ####

# Use default timestamp format
$ActionFileDefaultTemplate RSYSLOG_TraditionalFileFormat

# File syncing capability is disabled by default. This feature is usually not required,
# not useful and an extreme performance hit
#$ActionFileEnableSync on

# Include all config files in /etc/rsyslog.d/
$IncludeConfig /etc/rsyslog.d/*.conf


#### RULES ####

# Log all kernel messages to the console.
# Logging much else clutters up the screen.
#kern.*                                                 /dev/console

# Log anything (except mail) of level info or higher.
# Don't log private authentication messages!
*.info;mail.none;authpriv.none;cron.none                /var/log/messages

# The authpriv file has restricted access.
authpriv.*                                              /var/log/secure

# Log all the mail messages in one place.
mail.*                                                  -/var/log/maillog

# collect juniper switch syslog
cron.info                                                /var/log/remote/cisco.log

# Log cron stuff
cron.*                                                  /var/log/cron

# Everybody gets emergency messages
*.emerg                                                 /var/log/messages

# Save news errors of level crit and higher in a special file.
uucp,news.crit                                          /var/log/spooler

# Save boot messages also to boot.log
#local7.*                                                /var/log/boot.log
#*.*                                                /var/log/remote/cisco.log
local7.*                                                /var/log/remote/cisco.log
#local7.*                                                /var/log/cisco.log


# add one line for test
syslog.*						/var/log/remote/wlan.log
syslog.warning						/var/log/remote/wlan.log


# ### begin forwarding rule ###
# The statement between the begin ... end define a SINGLE forwarding
# rule. They belong together, do NOT split them. If you create multiple
# forwarding rules, duplicate the whole block!
# Remote Logging (we use TCP for reliable delivery)
#
# An on-disk queue is created for this action. If the remote host is
# down, messages are spooled to disk and sent when it is up again.
#$WorkDirectory /var/lib/rsyslog # where to place spool files
#$ActionQueueFileName fwdRule1 # unique name prefix for spool files
#$ActionQueueMaxDiskSpace 1g   # 1gb space limit (use as much as possible)
#$ActionQueueSaveOnShutdown on # save messages to disk on shutdown
#$ActionQueueType LinkedList   # run asynchronously
#$ActionResumeRetryCount -1    # infinite retries if host is down
# remote host is: name/ip:port, e.g. 192.168.0.1:514, port optional
#*.* @@remote-host:514
# ### end of the forwarding rule ###
]0;noc@xcpalx03:/etc[root@xcpalx03 etc]# exit
exit
-bash-4.1$ exit
logout

**Comment by hoyeunglee** [comment]
https://drive.google.com/file/d/0Bxs_ao6uuBDUOWNpRkppNFlibk0/view?usp=sharing

i had recorded a detailed screen capture.
if you watched, then i can remove this link

**Comment by rgerhards** [comment]
looking at the config, I do not see remote reception activated. So I actually wonder why some hosts log... Did you mistakenly post the wrong config?

**Comment by hoyeunglee** [comment]
No, no one change this config, I will capture a video to show this config same as I post

**Comment by hoyeunglee** [comment]
Other window hosts can also create logs but I am curious why some window host do not have logs

**Comment by hoyeunglee** [comment]
https://drive.google.com/file/d/0Bxs_ao6uuBDUMG0xYklkQU1EY2c/view?usp=sharing

Here is the new video with detailed screen capture, 

initially i think it is out of limit of inodes, but my supervisor told me that it is not related with the limit
i captured the config and file size of directory and done the test again

**Comment by hoyeunglee** [comment]
is here the correct place to ask this and is here all linux distributions using rsyslog over the world?

**Comment by davidelang** [comment]
well, we don't know what all linux distributions are, so we can't say that they 
all use rsyslog. The big ones all do (if they have any syslog implementation)

what is your question?

**Comment by hoyeunglee** [comment]
some logs from window can not be created log in rsyslog server in centos, i find other window hosts can create log successfully from the same vlan , i think that is a rare case, then find that not only one, a number of window hosts can not create log even if testing by sending udp syslog message manually

**Comment by davidelang** [comment]
depending on how old the centos version is, you may be tripping over a total 
path length limit or something like this.

what doesn't make sense is that you seem to be saying that some files are 
created properly, but others are not, on the same machine.

**Comment by hoyeunglee** [comment]
it is strange but it really happen
we are using

[root@xcpalx03 noc]# rsyslogd -version
rsyslogd 8.17.0, compiled with:
        PLATFORM:                               x86_64-redhat-linux-gnu
        PLATFORM (lsb_release -d):
        FEATURE_REGEXP:                         Yes
        GSSAPI Kerberos 5 support:              No
        FEATURE_DEBUG (debug build, slow code): No
        32bit Atomic operations supported:      Yes
        64bit Atomic operations supported:      Yes
        memory allocator:                       system default
        Runtime Instrumentation (slow code):    No
        uuid support:                           Yes
        Number of Bits in RainerScript integers: 64

See http://www.rsyslog.com for more information.
[root@xcpalx03 noc]#

**Comment by rgerhards** [comment]
@davidelang can you please check the posted config. As far as I see, it
does not even enable remote reception, which means we do not really know
what is going on here. Finding the real config then would be the first
thing to do imho.

Or am I overlooking the statements?

Sent from phone, thus brief.

Am 25.06.2017 16:34 schrieb "David Lang" <notifications@github.com>:

**Comment by davidelang** [comment]
in the main config, UDP reception is enabled.

**Comment by hoyeunglee** [comment]
do you mind provide email to me so that i can send a webex to you then you can come to see the real situation?

**Comment by hoyeunglee** [comment]
real config is as i posted before and  post again here

# rsyslog v5 configuration file

# For more information see /usr/share/doc/rsyslog-*/rsyslog_conf.html
# If you experience problems, see http://www.rsyslog.com/doc/troubleshoot.html

#### MODULES ####

$ModLoad imuxsock # provides support for local system logging (e.g. via logger command)
$ModLoad imklog   # provides kernel logging support (previously done by rklogd)
#$ModLoad immark  # provides --MARK-- message capability

# Provides UDP syslog reception
$ModLoad imudp
$UDPServerRun 514

# Provides TCP syslog reception
#$ModLoad imtcp
#$InputTCPServerRun 514


#### GLOBAL DIRECTIVES ####

# Use default timestamp format
$ActionFileDefaultTemplate RSYSLOG_TraditionalFileFormat

# File syncing capability is disabled by default. This feature is usually not required,
# not useful and an extreme performance hit
#$ActionFileEnableSync on

# Include all config files in /etc/rsyslog.d/
$IncludeConfig /etc/rsyslog.d/*.conf


#### RULES ####

# Log all kernel messages to the console.
# Logging much else clutters up the screen.
#kern.*                                                 /dev/console

# Log anything (except mail) of level info or higher.
# Don't log private authentication messages!
*.info;mail.none;authpriv.none;cron.none                /var/log/messages

# The authpriv file has restricted access.
authpriv.*                                              /var/log/secure

# Log all the mail messages in one place.
mail.*                                                  -/var/log/maillog

# collect juniper switch syslog
cron.info                                                /var/log/remote/cisco.log

# Log cron stuff
cron.*                                                  /var/log/cron

# Everybody gets emergency messages
*.emerg                                                 /var/log/messages

# Save news errors of level crit and higher in a special file.
uucp,news.crit                                          /var/log/spooler

# Save boot messages also to boot.log
#local7.*                                                /var/log/boot.log
#*.*                                                /var/log/remote/cisco.log
local7.*                                                /var/log/remote/cisco.log
#local7.*                                                /var/log/cisco.log


# add one line for test
syslog.*                                                /var/log/remote/wlan.log
syslog.warning                                          /var/log/remote/wlan.log


# ### begin forwarding rule ###
# The statement between the begin ... end define a SINGLE forwarding
# rule. They belong together, do NOT split them. If you create multiple
# forwarding rules, duplicate the whole block!
# Remote Logging (we use TCP for reliable delivery)
#
# An on-disk queue is created for this action. If the remote host is
# down, messages are spooled to disk and sent when it is up again.
#$WorkDirectory /var/lib/rsyslog # where to place spool files
#$ActionQueueFileName fwdRule1 # unique name prefix for spool files
#$ActionQueueMaxDiskSpace 1g   # 1gb space limit (use as much as possible)
#$ActionQueueSaveOnShutdown on # save messages to disk on shutdown
#$ActionQueueType LinkedList   # run asynchronously
#$ActionResumeRetryCount -1    # infinite retries if host is down
# remote host is: name/ip:port, e.g. 192.168.0.1:514, port optional
#*.* @@remote-host:514
# ### end of the forwarding rule ###

**Comment by hoyeunglee** [comment]
due to this issue, we are preparing to change to use splunk to collect log from window

**Comment by davidelang** [comment]
do you have any samples of raw logs (what is sent over the wire)?

This can be doen by capturing the logs via tcpdump or by creating a template 
something like "%rawmsg%\n"

if you are going to change your entire logging infrastructure because of a 
problem writing long filenames, I think you are overreacting.

we are still trying to fully understand the situations that cause the problems.

Is the problem that logs from some hosts work and some don't? or is the problem 
that sometimes logs from one host work and sometimes logs from that same host 
don't work?

What are you using to send the logs from the windows machines?

David Lang

**Comment by davidelang** [comment]
In my first post on this issue, I think I was mixing this up with another issue.

Here your template is just using %hostname%, and I was thinking this was the issue that had very long names in the dynafile template.

how many machines are you receiving logs from? If it's more than a handful, you probably need to switch to the action() format and set your dynafilecachesize to a larger value than the default (something larger than the number of hosts you are receiving logs from)

As to switching to Splunk to receive logs from the windows machines. Splunk's syslog receiver is rather poor, so it's unlikely to solve any complex problem.

**Comment by rgerhards** [comment]
@hoyeunglee If this is so mission critical to you that you consider switching to a costly solution like splunk, you could also consider purchasing enterprise support for rsyslog: http://www.rsyslog.com/professional-services/enterprise-support/

With enterprise support, you get direct access to a paid technician which will work with you in-depth on the cases - in contrast to us giving help as time permits... I am personally always a bit disappointed if I try to help someone for free and than that someone comes up with the idea that this is considered enterprise-class support in order to help them make money...

**Comment by hoyeunglee** [comment]
https://drive.google.com/file/d/0Bxs_ao6uuBDUTkpKQUI3eDhmWGs/view?usp=sharing
i googled rsyslog function and edit it for send udp syslog message form window to linux
and then i edit it as a simple testing program

tell me if you downloaded this code, then i can delete this link.

i have to ask supervisor whether buy this service.
since he is negotiating splunk service

**Comment by davidelang** [comment]
I don't need the code (I'm not going to read the code to see what it's doing), 
but I was wondering if it was something that was well known. In this case it 
doesn't seem to be.

so we are back to needing to see exactly what is sent over the wire before we 
can say what we would expect to see happen in this case.

As I said before, you can either gather the data via tcpdump, or by logging with 
the %rawmsg% property (if you use the built-in template RSYSLOG_DebugFormat it 
will have everything needed)

The usual problem in cases like this is that the logs are not what you think 
they are, but we need to see them to know what's happening.

David Lang

**Comment by hoyeunglee** [comment]
actually the code is correct, since other successful window host send syslog to linux is also using this code, 
as you watched the video link, the tcp dump show that linux received this udp syslog message successfully

i just send a string
"message"
with
syslog(content2, level=int(sys.argv[6]), facility=int(sys.argv[5]), host=sys.argv[1], port=514)

in function
def syslog(message, level=LEVEL['err'], facility=FACILITY['syslog'],host='localhost', port=514):

sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
data = '<%d>%s' % (level + facility*8, message)
sock.sendto(data, (host, port))

the data is the format it sent

**Comment by davidelang** [comment]
I am not going to wade through a video to see a little text. I'm not getting 
paid to support anyone (or to do anything with rsyslog for that matter). Please 
provide an example of what is sent from a system that works and what is sent 
from one that doesn't work.

one thing about debugging problems, it doesn't matter what you think you are 
sending, what matters is what is actually going out over the wire. If everything 
was what was expected/intended then everything would work. The fact that it's 
not working means that something isn't happening as expected.

We don't know where the problem is, so it makes sense to start at the beginning 
and see what's being received. It's especially useful to be able to compare what 
works with what doesn't work.

I've had cases where the problem ended up being routing tables on the system, so 
the message was never getting to rsyslog in the first place.

**Comment by hoyeunglee** [comment]
i understand now, and solved.
i find that the message is in message.log

the message has to contain the ip address ,after put an ip address in the udp message
it can create a log now

thanks, please closed this case

**Comment by davidelang** [comment]
so was the problem that the message didn't have a hostname in it?

Or that it had a name instead of an IP and you were looking for the IP?

Or something else?

**Comment by hoyeunglee** [comment]
no hostname in the message,

i am curious that if there are two different ip address in message , how do it classify?
will it create two files named two different ip address

and it must put the name of message at the first column of the message

**Comment by davidelang** [comment]
It doesn't look for "an IP address in the message"

a proper format is

<pri>timestamp hostname syslogtag message

whatever is after the timestamp will be used as the hostname, unless it is 
something that is identified as having no possibility of being a hostname 
(contains characters not allowed in a hostname)

if that is an IP address, then the HOSTNAME variable will be an IP, if it's a 
name, it will be a name. If the sender leaves it out, the syslogtag or the first 
word of the message will be used as a the HOSTNAME
k

**Comment by hoyeunglee** [comment]
i get it. thank you very much.
