### ISSUE TITLE
hostname in syslog changed from hostname to 'localhost'

### ISSUE THREAD

**Issue by kochtopf** [rsyslog/rsyslog#1631]
I did came up from rsyslog:armhf (8.24.0-1 to 8.27.0-3 Debian testing) and after reboot the system name changed from the content of /etc/hostname) to localhost in all syslog messages (did broke all msg forward rules).  A quick fix: put in you /etc/hostname into /etc/hosts. This is just a quick note for anybody else running into this 'undesirable feature'. This also is platform specific on all Raspberry Pi's but not on Intel i386's.

**Comment by rgerhards** [comment]
@mbiebl this sounds like a packaging issue - or do you think this has something to do with the rsyslog project itself?

**Comment by mbiebl** [comment]
@rgerhards not sure how this could be a packaging issue. Can you elaborate?

How exactly does rsyslog determine the hostname? I assume it doesn't parse /etc/hostname directly but uses libc's gethostname?
@kochtopf did you upgrade other packages besides rsyslog? If you downgrade rsyslog again and remove your hostname from /etc/hosts, is the problem reproducible still

Fwiw, it sounds like a misconfiguration if the hostname is not resolvable.

**Comment by mbiebl** [comment]
@kochtopf please share your /etc/hostname and /etc/hosts which exhibit the problem.

**Comment by kochtopf** [comment]
root@pi2:/etc # cat hostname
pi2
root@pi2:/etc # cat hosts
127.0.0.1	localhost
192.168.0.10	pi2	#rsyslog (8.27.0-3) fix - else cat syslog gets 'localhost' as the hostname after reboot

I did not upgrade anything besides rsyslog. I'll will test the downgrade and report asap.

**Comment by rgerhards** [comment]
I did some more digging, the problem could be related to https://github.com/rsyslog/rsyslog/pull/1521

Git master branch has the fix; also, tomorrow will have the 8.28 release. Maybe it's worth waiting and re-trying.

**Comment by rgerhards** [comment]
@mbiebl yes, it's basically a call to gethostname(), but with some extra conditions (as said in #1521)

**Comment by kochtopf** [comment]
...some more tests. Downgraded to 8.24 restored the old hosts file and rebooted. All norman. dist-upgraded to 8.27 and rebooted. The problem reappeared again. Instead of 

Jun 26 08:42:42 pi2 systemd[1]: Stopping LSB: Autogenerate and use a swap file...
Jun 26 08:43:05 [localhost] kernel: [    0.000000] Booting Linux on physical CPU 0xf00

pi2 replaced by [localhost].

Observation: A simple service rsyslog restart will bring change [localhost] -> pi2 again.

**Comment by kochtopf** [comment]
Can't reproduce this with after upgrading to v8.28. Consider this fixed.
