### ISSUE TITLE
./configure  on aix6.1 Cannot find or read export file: strippedsymbols.exp

### ISSUE THREAD

**Issue by LauYongfu** [rsyslog/rsyslog#1632]
configure:4128: checking whether the C compiler works
configure:4150: xlc_r -D_AIX -D_THREAD_SAFE -D_BSD43 -D_AIX -qcpluscmt -brtl -bexpall -bE:strippedsymbols.exp  conftest.c -lbsd -lsrc >&5
ld: 0706-004 Cannot find or read export file: strippedsymbols.exp
	ld:accessx(): No such file or directory
configure:4154: $? = 255
configure:4192: result: no

When i try to run ./configure ,will report the above error,
How should I do?

**Comment by rgerhards** [comment]
We unfortunately have no AIX know how at all, but would appreciate if you let us know your findings. In order to have at least a chance to get an answer to your question, I highly recommend posting on the rsyslog mailing list. There may be folks which have an idea.
