### ISSUE TITLE
Possible loss of log messages when syslog-ng.persist file has cursor "in the future".

### ISSUE THREAD

**Issue by faithlesstomas** [rsyslog/rsyslog#1635]
**Description**
When syslog-ng checks cursor position from syslog-ng.persist file it does not check if saved cursor is "in the future" with respect to the system (i.e. time in the cursor is in the future with the respect to the system time). This causes logging glitch when syslog-ng is started (syslog-ng waits for the "time to come" to continue logging) when there is no systemd journal entries with the given "future time" or later. This is because sd_journald_seek_cursors() seeks to the next closest entry (in terms of time) if no entry matches.

**Possible fix**
Use sd_journal_test_cursor() to test the validity of the cursor.

**Side note**
This issue won't occur normally unless someone or something mess up with system time and systemd journal. Consider following example, how one can reproduce this bug:

1. Stop syslog-ng and systemd-journald services
2. cleanup/remove journal logs
3. set the time in some past with respect to given time
4. reboot machine

**Comment by faithlesstomas** [comment]
sorry, mistake, wrong project

**Comment by davidelang** [comment]
we had a similar problem.

Another case where this same problem can happen is when time goes backwards (the 
system boots, then sometime later the network comes up and NTP warps the time 
back to be correct)

**Comment by faithlesstomas** [comment]
Yes, I saw comment in your code.
But thanks, anyway :)
