### ISSUE TITLE
Install Rsyslog with omkafka module on CentOS 5 32 bit

### ISSUE THREAD

**Issue by wess1984** [rsyslog/rsyslog#1640]
Hi Everybody,

How to install **Rsyslog** with **omkafka** module on **CentOS 5 32 bit** ?

**Comment by alorbach** [comment]
I believe that we do not have omkafka packages for CentOS 5, only for 6 and 7. 
It is most likely to difficult to get librdkafka compiled on this old plattform.

**Comment by rgerhards** [comment]
Yes, that is the problem. It is too hard to build the dependencies. So if someone is interested in doing that on CentOS 5, he must build from source - what probably is quite an endeavor. In case someone get's it right, a pointer on what is needed would be appreciated.

**Comment by wess1984** [comment]
Hi guys,
Finally I have successfully built the rsyslog-kafka rpm packages for CentOS 5 32 & 64 bit. 
I have worked with rsyslog 8.16.0 and enabled the omkafka module. 
The biggest problem, i have found, is in the dependency of librdkafka library with the 32-bit architecture. I have worked with the librdkakfa0.9.5 and everything was ok :)
I can share the rpm packages with u if you want to test them !!

**Comment by rgerhards** [comment]
@wess1984 Unfortunately, building for 8.16.0 does not help, because it is heavily outdated. Most importantly, the omkafka present in that version has severe limitations and problems compared to the current (8.28.0) one.

**Comment by rgerhards** [comment]
I forgot to add: if you can provide a way to build current librdkafka, we can see if we get the current version going on CentOS 5. Right now, this is the blocker.

**Comment by ravi45722** [comment]
Am also searching for those omkafka rpm (0.9 kafka).   @wess1984 Can you please share those links for me??

**Comment by techwizardg** [comment]
@wess1984 i am also in need of the same for Rhel 5.4 and could you provide me links on how you built omkafka plugin for the same.It would be helpful.

**Comment by dpatino82** [comment]
@wess1984 I'm also searching it for CentOS 5.2 (32bits). Could you, please, share those links?? Thanks a lot!

**Comment by devcrops-official** [comment]
@wess1984 I'm also searching it for CentOS 5.2 (64bits). Could you, please, share those links?
