### ISSUE TITLE
Bug: CentOS package: logrotate setting

### ISSUE THREAD

**Issue by schlitzered** [rsyslog/rsyslog#1641]
at least the CentOS 7 package (rsyslog-8.27.0-2.el7.x86_64) delivers a logrotate setting with the file
"/etc/logrotate.d/syslog", with the content:
```
/var/log/cron
/var/log/maillog
/var/log/messages
/var/log/secure
/var/log/spooler
{
    sharedscripts
    postrotate
        /bin/kill -HUP `cat /var/run/syslogd.pid 2> /dev/null` 2> /dev/null || true
    endscript
}
```

but kill -HUP will not work, because the pidfile is '/var/run/rsyslogd.pid' not 'cat /var/run/syslogd.pid'

could you please fix this?

**Comment by wdauchy** [comment]
you probably should report this to centos directly (https://bugs.centos.org ?), we do not manage such script here

**Comment by schlitzered** [comment]
no, it belongs to the rpm package provided by http://rpms.adiscon.com/v8-stable/epel-7/x86_64/

rpm -qf /etc/logrotate.d/syslog
rsyslog-8.28.0-1.el7.x86_64

**Comment by wdauchy** [comment]
ok sorry, that's looks like something to report in https://github.com/rsyslog/rsyslog-pkg-rhel-centos

I however looked at the code, and it seems coherent with the use of syslod.pid file for rhel >=6 https://github.com/rsyslog/rsyslog-pkg-rhel-centos/blob/master/rpmbuild/SPECS/v7-stable.spec#L7

something to dig into, but I believe we can close the issue in this repo
