### ISSUE TITLE
Change and use Json type in Mutliline Log

### ISSUE THREAD

**Issue by bosungs2y** [rsyslog/rsyslog#1645]
hello :)
I am currently receiving logs in multiline (/var/log/modsec_audit.log)
I want to combine them and send them to the remote server in json format
How do I set it up?

# Information
- CentOS7
- rsyslogd 8.25.0

# rsyslog.conf
module(load="imfile")
module(load="imuxsock") # provides support for local system logging (e.g. via logger command)
module(load="imklog")   # provides kernel logging support (previously done by rklogd)

$ActionFileDefaultTemplate RSYSLOG_TraditionalFileFormat
$IncludeConfig /etc/rsyslog.d/*.conf
$UDPServerRun 8888

input(type="imfile"
     File="/var/log/modsec_audit.log"
     Tag="mod-bbo:"
     Severity="info"
     startmsg.regex=".+"
     readTimeout="2"
     escapeLF="off"
     Facility="local6")

if $syslogtag == "mod-bbo:" then {
    action(type="omfwd"
        Target="10.10.10.200"
        Port="8888"
        Protocol="udp")
        stop
}
.....

# /var/log/modsec_audit.log (MultiLine Log)

```
---6eF8aaQl---A--
[06/Jul/2017:14:16:42 +0900] 14927518021.000000 172.26.137.64 57229 10.10.10.1 443
---6eF8aaQl---B--
GET /index.html HTTP/2.0
host: server.com
cache-control: max-age=0
upgrade-insecure-requests: 1
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36
accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
accept-encoding: gzip, deflate, sdch, br
accept-language: ko-KR,ko;q=0.8,en-US;q=0.6,en;q=0.4
 
---6eF8aaQl---C--
 
---6eF8aaQl---E--
<!DOCTYPE HTML>
<html>
<head>
  <title>hello </title>
</head>
</html>
 
 
---6eF8aaQl---F--
Server: nginx/1.11.13
Date: Fri, 21 Apr 2017 05:16:42 GMT
Content-Length: 1077
Content-Type: text/html
Last-Modified: Fri, 21 Apr 2017 05:14:14 GMT
Connection: close
ETag: "58f99526-435"
Accept-Ranges: bytes
 
---6eF8aaQl---J--
 
---6eF8aaQl---Z--

```

# Want Format to the remote server
`{"transaction":{"time":"21/Apr/2017:18:58:50 +0900","transaction_id":"Bc0clcZcAchcPcAcAcAdAcAA","remote_address":"172.26.137.64","remote_port":57229,
"local_address":"10.10.10.1","local_port":443},"request":{"request_line":"GET /index.html HTTP/2.0","headers":{"host":"server.com","cache-control":
"max-age=0","upgrade-insecure-requests":"1","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133
Safari/537.36","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8","accept-encoding":"gzip, deflate, sdch, br","accept-language":
"ko-KR,ko;q=0.8,en-US;q=0.6,en;q=0.4"}},"response":{"protocol":"HTTP/1.1","status":200,"headers":{"ETag":"\"58f99526-435\"","Content-Type":"text/html","Content-Length":
"2639","Last-Modified":"Fri, 21 Apr 2017 07:33:31 GMT","Connection":"close"},"body":"<html><body>  <title>hello </title> </body></html>\n"},"audit_data":{}}
`
# remote server log :(
```06/Jul/2017:14:16:42 +0900
Jul  6 18:17:25 bs-nginx3 mod-bbo: [06/Jul/2017:14:16:42 +0900] 149933264545.190558 172.26.137.64 57229 10.10.10.1 443
Jul  6 18:17:25 bs-nginx3 mod-bbo: ---UgNEA5aY---B--
Jul  6 18:17:25 bs-nginx3 mod-bbo: GET /index.html HTTP/1.1
Jul  6 18:17:25 bs-nginx3 mod-bbo: Host: server.com
Jul  6 18:17:25 bs-nginx3 mod-bbo: User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133
Safari/537.36
Jul  6 18:17:25 bs-nginx3 transaction: Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Jul  6 18:17:25 bs-nginx3 mod-bbo: ---UgNEA5aY---C--
Jul  6 18:17:25 bs-nginx3 mod-bbo: ---UgNEA5aY---E--
Jul  6 18:17:25 bs-nginx3 mod-bbo: <!DOCTYPE html>
Jul  6 18:17:25 bs-nginx3 mod-bbo: <html><body><h1>It works!</h1></body></html>
```

**Comment by davidelang** [comment]
once you have read in a multiline log you can put it into a json message with no 
problem, just define a template to use when you forward the message.

You can use mmnormalize to parse the message apart into different variables.

Please look over the documentation and then ask further questions on the rsyslog 
mailing list.
