### ISSUE TITLE
have_to_generate_man_pages= is not properly set for git builds

### ISSUE THREAD

**Issue by mbiebl** [rsyslog/rsyslog#1651]
Looking at https://github.com/rsyslog/rsyslog/blob/master/configure.ac#L2011
```
        have_to_generate_man_pages=git_src_have_to_generate_man_pages
```
I'm pretty sure you want  have_to_generate_man_pages to be set to the *value*, ie. ```$git_src_have_to_generate_man_pages```.

**Comment by rgerhards** [comment]
@Whissi could you have a look at this? would be much appreciated.

**Comment by Whissi** [comment]
Yes, @mbiebl is right. See the linked PR.
