### ISSUE TITLE
core: messages might get garbled

### ISSUE THREAD

**Issue by rgerhards** [rsyslog/rsyslog#1658]
The MsgDup() function will return a garbled message object under these conditions. The message was originally created with message length equal to CONF_RAWMSG_BUFSIZE. This makes rsyslog store the message in dynamically allocated buffer space. Then, the parser removed a known-bad LF at the end of the messages. This reduces the message size by one. Then, MsgDup is executed. It checks the message size and finds that it is below CONF_RAWMSG_BUFSIZE, which make it copy the msg object internal buffer instead of the dynamically allocated one. That buffer was not written to in the first place, so unitialized data is copied. Note that no segfault can happen, as the copied location was properly allocated, just not used in this processing flow.

In the end result, the new message object contains garbage data. Whenever the new object is used (e.g. in a async ruleset or action) that garbage will be used. Whenever the old object is accessed, correct data will be used. Both types of access can happen inside the same processing flow, which makes the problem appear to be random.

**Comment by davidelang** [comment]
There are other things that can reduce the message size (mmrm1stspace, some of 
the parser modules that fixup bad logs like the aix parser)

**Comment by rgerhards** [comment]
@davidelang yes,that's right. Under the conditions described above, this will also trigger the problem.

**Comment by jay7x** [comment]
Ah, JFYI, I've seen some garbage when trying to manipulate by JSON message properties. I.e. after parsing by mmjsonparse/mmnormalize. Unsetting some properties may cause garbage in {{$!all-json}}. Not sure is it related or not though.

**Comment by davidelang** [comment]
what version are you using? we had some serious corruption issues before 8.16 
that didn't get fully hammered out until a few versions later IIRC.

**Comment by rgerhards** [comment]
@jay7x This bug here requires modification of the rawmsg property, which is not done by json manipulation. So we can rule this out as cause of what you say.
