### ISSUE TITLE
Ubuntu PPA is missing v8.28.0

### ISSUE THREAD

**Issue by deoren** [rsyslog/rsyslog#1660]
Currently only 8.27.0 is available from the `v8-stable` PPA (https://launchpad.net/~adiscon/+archive/ubuntu/v8-stable).

P.S.

Thank you for providing this PPA. I appreciate being able to use newer versions of the software than what the base distro provides.

**Comment by rgerhards** [comment]
note that this is an issue for the packaging project and likely to attract more action there

**Comment by deoren** [comment]
@rgerhards Sorry, I completely missed that you have various sub-projects. Are you able to move issues or should I close this one and recreate there?

**Comment by rgerhards** [comment]
I am not aware of a way to move. If you know one, I am all ears (missing
this for a while...).

Rainer

2017-07-12 13:49 GMT+02:00 Deoren Moor <notifications@github.com>:

**Comment by deoren** [comment]
@rgerhards I turned to Google and it does not appear that github supports this feature. Oh well. I'll recreate this issue in the other repo and link here.

Sorry for the trouble.

**Comment by deoren** [comment]
Created here: https://github.com/rsyslog/rsyslog-pkg-ubuntu/issues/60
