### ISSUE TITLE
impstats: add counter for number of open files

### ISSUE THREAD

**Issue by rgerhards** [rsyslog/rsyslog#1661]
For troubleshooting, health monitoring and capacity planning purposes it is useful to know the number of open file handles (files, sockets, ...) for the running instance of rsyslog. Impstats looks like the perfect place to provide this.

As far as current thinking is, we will query ```proc/{pid}/fd``` and count open files. This is linux-specific, so the counter will initially not be available on other platforms.

**Comment by jhenry82** [comment]
Thanks for implementing this! I did a deep dive on our rsyslog performance issues a while back and only noticed via strace (constant open/close of files on a box receiving logs from thousands of servers) that something was very wrong. Raising the Linux open file limit and dynaFileCacheSize fixed things up.

Having these stats would have made it even more apparent.

**Comment by davidelang** [comment]
On Thu, 27 Jul 2017, Jon Henry wrote:
> 
> Thanks for implementing this! I did a deep dive on our rsyslog performance issues a while back and only noticed via strace (constant open/close of files on a box receiving logs from thousands of servers) that something was very wrong. Raising the Linux open file limit and dynaFileCacheSize fixed things up.

dynafilecachesize < # of files being written to will absolutly kill performance 
(at least four orders of magnatude, and I wouldn't be surprised to see it go 
past 6)

> Having these stats would have made it even more apparent.

there is a stat in the pstats output that shows how many dynamic files were 
closed in a reporting window, if it's more than the number of files you expect 
to be writing, increase dynafilecachsize.

If the OS limits prevent you from using that many, you need to fix the OS 
limits.
