### ISSUE TITLE
omelasticsearch "errorfile" and "bulkId" memory leak

### ISSUE THREAD

**Issue by GUI** [rsyslog/rsyslog#1668]
After upgrading from 8.27.0 to 8.28.0, we started to see rsyslogd's memory use to grow indefinitely. The more messages rsyslogd processes, the more it's memory grew. I've tracked the issue down to our usage of omelasticsearch, but I think there might be 2 separate issues going on:

- When omelasticsearch's `bulkId` setting is used, rsyslogd 8.28.0 considers successful responses from Elasticsearch to be errors. I guess this setting isn't documented, but we had been using it in 8.27.0 and previous versions successfully.
- If omelasticsearch's `errorfile` is defined, then the errors generated seem to trigger a memory leak in rsyslogd. It seems like rsyslogd's memory growth corresponds to the amount of error data logged in the error file. I'm not sure if this is a new problem in 8.28.0, or whether we just hit it since the `bulkId` issue caused a lot more error data to be generated.

So it seems like the memory leak issue might really just be specific to `errorfile`, but using `bulkId` is now logging all responses as errors in 8.28.0 (despite the indexing actually being successful).

The `bulkId` issue seems to stem from this check for the `create` attribute on the response: https://github.com/rsyslog/rsyslog/blob/v8.28.0/plugins/omelasticsearch/omelasticsearch.c#L746 When the `bulkId` option is used to explicitly set the `_id` of the document being sent to elasticsearch, then Elasticsearch uses the `"index"` bulk mechanism, instead of `"create"` (see https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-bulk.html). This in turn means the response will not be nested under the `create` attribute, but instead it's nested under an `index` attribute.

I put together this little repo with some scripts to demonstrate the memory leak with the different combinations of settings and versions: https://github.com/GUI/rsyslog-omelasticsearch-leak

**Comment by wdauchy** [comment]
I proposed a possible fix in #1699

**Comment by ajrpayne** [comment]
Not using omelasticsearch's bulkId setting, but rsyslogd 8.28.0 seems to be considering successful responses from Elasticsearch as errors. No memory leak though for me. downgraded to 8.27.0 to fix the issue.

**Comment by rgerhards** [comment]
fixed via https://github.com/rsyslog/rsyslog/pull/1699
