### ISSUE TITLE
v8.27.0 - Imfile - Path with wildcard in directories path don't work

### ISSUE THREAD

**Issue by jcardon-altima** [rsyslog/rsyslog#1672]
Following my post on the mailing list (see http://rsyslog-users.1305293.n2.nabble.com/v8-27-0-Imfile-Path-with-wildcard-in-directories-path-don-t-work-td7592589.html), I post this issue here.

I'm try to use imfile module with a path containing wildcard in directories. When rsyslog start, I've got this message in rsyslog.log :
> Jul 13 18:00:58 ALT190-P rsyslogd: rsyslogd's groupid changed to 108
> Jul 13 18:00:58 ALT190-P rsyslogd: rsyslogd's userid changed to 104
> Jul 13 18:00:58 ALT190-P rsyslogd:  [origin software="rsyslogd" swVersion="8.27.0" x-pid="25840" x-info="http://www.rsyslog.com"<http://www.rsyslog.com>] start
> Jul 13 18:00:58 ALT190-P rsyslogd: imfile: error with inotify API, ignoring file '/data/www/xxxx/*/shared/var/log/exception.log': No such file or directory  [v8.27.0]
> 
As you can see, I'm using rsyslog v8.27.0 on ubuntu from PPA adiscon (last available at this time).
> root@ALT190-P:~# rsyslogd -v
> rsyslogd 8.27.0, compiled with:
>     PLATFORM:                x86_64-pc-linux-gnu
>     PLATFORM (lsb_release -d):
>     FEATURE_REGEXP:                Yes
>     GSSAPI Kerberos 5 support:        No
>     FEATURE_DEBUG (debug build, slow code):    No
>     32bit Atomic operations supported:    Yes
>     64bit Atomic operations supported:    Yes
>     memory allocator:            system default
>     Runtime Instrumentation (slow code):    No
>     uuid support:                Yes
>     Number of Bits in RainerScript integers: 64
> See http://www.rsyslog.com for more information.

Part of my config, this work just fine :
> input(type="imfile" File="/data/www/xxxx/applogs/*.*.log"
>        Tag="exception:" Severity="info" Facility="local7" freshStartTail="on" reopenOnTruncate="on"
>        startmsg.regex="^[[:digit:]]{4}-[[:digit:]]{2}-[[:digit:]]{2}T[[:digit:]]{2}:[[:digit:]]{2}:[[:digit:]]{2}"
>        readTimeout="3" addMetadata="on" ruleset="logs_type_parser")
> 
> input(type="imfile" File="/data/www/xxxx/logs/yyy*.xxxx-preprod.com.access.log"
>        Tag="http.access:" Severity="info" Facility="local7" freshStartTail="on"
>        addMetadata="on" ruleset="logs_instance_parser")

This dont' work :
> input(type="imfile" File="/data/www/xxxx/*/shared/var/log/exception.log"
>        Tag="exception:" Severity="info" Facility="local7" freshStartTail="on" reopenOnTruncate="on"
>        startmsg.regex="^[[:digit:]]{4}-[[:digit:]]{2}-[[:digit:]]{2}T[[:digit:]]{2}:[[:digit:]]{2}:[[:digit:]]{2}"
>        readTimeout="3" addMetadata="on" ruleset="logs_instance_parser")

I have just one level under "*" between "/data/www/xxx" and "shared/var...".

Directories and files are created before rsyslog start. Imfile doesn't detect any changes in watched files.

A full startup debug log is attached in file [rsyslog-start-debug.txt](https://github.com/rsyslog/rsyslog/files/1152205/rsyslog-start-debug.txt).

**Comment by zhong9257** [comment]
@alorbach HI.Thank you.
After you fixed this wildcard bug.
1. Dose mutlilevelwildcard can work? The path like this file=/app/*/ctg*.log.
2. Dost it can discovery the new file after rsyslog start?
3. Can your code commit to the v8.29?

**Comment by alorbach** [comment]
1. Yes nothing changed on wildcard detetction. 
2. Yes the initial watches should be created properly now.
3. Already done, Pull request will be merged after Rainers approval.

**Comment by rgerhards** [comment]
On 2: I would expect that this does not work. At least it's against the
spec. It has huge performance implications, among others.

Rainer

Sent from phone, thus brief.

Am 26.07.2017 8:20 vorm. schrieb "alorbach" <notifications@github.com>:

**Comment by zhong9257** [comment]
Thank you Rainer . Thank you alorbach.
I see.
