### ISSUE TITLE
V8.27 imfile cant't discovry new files when using directory wildcards

### ISSUE THREAD

**Issue by zhong9257** [rsyslog/rsyslog#1687]
use imfile. the path = /app/\*/\*/\*.log.
during rsyslog running, new log file generate in the directory "/app/\*/\*".and the rsyslog cant't konw this things,it not to gather the content of the new log file.
After restart rsyslog,imfile can gather the content of new log file.

Can imfile discover the new log file during rsyslog running

**Comment by alorbach** [comment]
This properly the same bug as here: 
https://github.com/rsyslog/rsyslog/issues/1672

I have a fix ready which is currently running through the testbench.
