### ISSUE TITLE
Ommysql don't export from CEF to MySQL

### ISSUE THREAD

**Issue by gubzh** [rsyslog/rsyslog#1691]
Hi, 
As described in https://stackoverflow.com/questions/45274192/export-from-cef-to-mysql-rules-rsyslog-conf

I need to collect CEF logs and write them to MySQL database using rsyslog. In the rsyslog.conf registered the following rules:

module(load="ommysql")
module(load="imtcp")
module(load="imudp")
module(load="mmfields")
template(name="ceflogs" type="string" option.sql="on" string="insert into idslogs (DeviceVendor, DeviceProduct, DeviceVersion, SignatureID, Name, Severity, Extensions_cat, Extensions_dmac, Extensions_cnt, Extensions_cs2Label, Extensions_cs2, Extensions_cs3Label, Extensions_cs3, Extensions_cs1Label, Extensions_cs1, Extensions_dst, Extensions_spt, Extensions_dpt, Extensions_proto, Extensions_deviceExternalId, Extensions_smac, Extensions_rt, Extensions_src) values ('%$!cef!DeviceVendor%', '%$!cef!DeviceProduct%', '%$!cef!DeviceVersion%', '%$!cef!SignatureID%', '%$!cef!Name%', %$!cef!Severity%, %$!cef!Extensions!cat%, '%$!cef!Extensions!dmac%', %$!cef!Extensions!cnt%, '%$!cef!Extensions!cs2Label%', '%$!cef!Extensions!cs2%', '%$!cef!Extensions!cs3Label%', '%$!cef!Extensions!cs3%', '%$!cef!Extensions!cs1Label%', %$!cef!Extensions!cs1%, '%$!cef!Extensions!dst%', %$!cef!Extensions!spt%, %$!cef!Extensions!dpt%, '%$!cef!Extensions!proto%', %$!cef!Extensions!deviceExternalId%, '%$!cef!Extensions!smac%', %$!cef!Extensions!rt:::date-mysql%, '%$!cef!Extensions!src%')")
ruleset(name="remote") {
action(type="mmfields")
action(type="ommysql" server="localhost" db="dbname" uid="root" pwd="password")
}
input(type="imtcp" port="514" ruleset="remote")
input(type="imudp" port="514" ruleset="remote")

"nc -l -u 514" shows incoming logs in CEF format, but logs are not written to MySQL database. What needs to be changed in rsyslog.conf.

**Comment by davidelang** [comment]
write some logs out in RSYSLOG_DebugFormat, check to see that the variables you 
are using in your config match what is being parsed.

David Lang

**Comment by gubzh** [comment]
Added rule *.* /var/log/debugfmt;RSYSLOG_DebugFormat to rsyslog.conf and restart rsyslog, but logs are not written.

**Comment by Amorik** [comment]
Where did you place the rule in the config?
Make sure its in the ruleset that is being called for your relative input statement.
Place one before the mmfields action and another one after. That way you can see what is (or is not) happening between each step.

**Comment by davidelang** [comment]
what is your full config?

**Comment by gubzh** [comment]
If you put `*.* /var/log/debugfmt;RSYSLOG_DebugFormat` before or after `action(type="mmfields")` then logs are written in `debugfmt`, but when `*.* /var/log/debugfmt;RSYSLOG_DebugFormat` is put after `action(type="ommysql" server="localhost" db="dbname" uid="root" pwd="password")` in `debugfmt` nothing is written down.

This is full rsyslog.conf:

# rsyslog configuration file
# note that most of this config file uses old-style format,
# because it is well-known AND quite suitable for simple cases
# like we have with the default config. For more advanced
# things, RainerScript configuration is suggested.

# For more information see /usr/share/doc/rsyslog-*/rsyslog_conf.html
# If you experience problems, see http://www.rsyslog.com/doc/troubleshoot.html

#### MODULES ####

# Load the MySQL Module
module(load="ommysql")

# Provides TCP syslog reception
module(load="imtcp")

# Provides UDP syslog reception
module(load="imudp")

# Load the Mmfields Module
module(load="mmfields")

template(name="ceflogs" type="string" string="insert into idslogs (`DeviceVendor`, `DeviceProduct`, `DeviceVersion`, `SignatureID`, `Name`, `Severity`, `Extensions_cat`, `Extensions_dmac`, `Extensions_cnt`, `Extensions_cs2Label`, `Extensions_cs2`, `Extensions_cs3Label`, `Extensions_cs3`, `Extensions_cs1Label`, `Extensions_cs1`, `Extensions_dst`, `Extensions_spt`, `Extensions_dpt`, `Extensions_proto`, `Extensions_deviceExternalId`, `Extensions_smac`, `Extensions_rt`, `Extensions_src`) values ('%$!cef!DeviceVendor%', '%$!cef!DeviceProduct%', '%$!cef!DeviceVersion%', '%$!cef!SignatureID%', '%$!cef!Name%', %$!cef!Severity%, %$!cef!Extensions!cat%, '%$!cef!Extensions!dmac%', %$!cef!Extensions!cnt%, '%$!cef!Extensions!cs2Label%', '%$!cef!Extensions!cs2%', '%$!cef!Extensions!cs3Label%', '%$!cef!Extensions!cs3%', '%$!cef!Extensions!cs1Label%', '%$!cef!Extensions!cs1%', '%$!cef!Extensions!dst%', %$!cef!Extensions!spt%, %$!cef!Extensions!dpt%, '%$!cef!Extensions!proto%', %$!cef!Extensions!deviceExternalId%, '%$!cef!Extensions!smac%', %$!cef!Extensions!rt:::date-mysql%, '%$!cef!Extensions!src%')")

ruleset(name="remote") {

# *.* /var/log/debugfmt;RSYSLOG_DebugFormat

action(type="mmfields")

# *.* /var/log/debugfmt;RSYSLOG_DebugFormat

action(type="ommysql" server="localhost" serverport="3306" db="dbname" uid="username" pwd="password")

# *.* /var/log/debugfmt;RSYSLOG_DebugFormat

}

input(type="imtcp" port="514" ruleset="remote")
input(type="imudp" port="514" ruleset="remote")

#### GLOBAL DIRECTIVES ####

# Use default timestamp format
$ActionFileDefaultTemplate RSYSLOG_TraditionalFileFormat

# File syncing capability is disabled by default. This feature is usually not required,
# not useful and an extreme performance hit
# $ActionFileEnableSync on

# Include all config files in /etc/rsyslog.d/
$IncludeConfig /etc/rsyslog.d/*.conf


#### RULES ####

# Log all kernel messages to the console.
# Logging much else clutters up the screen.
# kern.*                                                 /dev/console

# Log anything (except mail) of level info or higher.
# Don't log private authentication messages!
*.info;mail.none;authpriv.none;cron.none                /var/log/messages

# The authpriv file has restricted access.
authpriv.*                                              /var/log/secure

# Log all the mail messages in one place.
mail.*                                                  /var/log/maillog

# Log cron stuff
cron.*                                                  /var/log/cron

# Everybody gets emergency messages
*.emerg                                                 :omusrmsg:*

# Save news errors of level crit and higher in a special file.
uucp,news.crit                                          /var/log/spooler

# Save boot messages also to boot.log
local7.*                                                /var/log/boot.log


# ### begin forwarding rule ###
# The statement between the begin ... end define a SINGLE forwarding
# rule. They belong together, do NOT split them. If you create multiple
# forwarding rules, duplicate the whole block!
# Remote Logging (we use TCP for reliable delivery)
# An on-disk queue is created for this action. If the remote host is
# down, messages are spooled to disk and sent when it is up again.

# $WorkDirectory /home/logs/rsyslogs # where to place spool files

#$ActionQueueFileName fwdRule1 # unique name prefix for spool files
#$ActionQueueMaxDiskSpace 1g   # 1gb space limit (use as much as possible)

$ActionQueueSaveOnShutdown on # save messages to disk on shutdown
$ActionQueueType LinkedList   # run asynchronously
$ActionResumeRetryCount -1    # infinite retries if host is down

# remote host is: name/ip:port, e.g. 192.168.0.1:514, port optional
# CPG - if you need to forward to other systems as well, just add additional config lines:

# ### end of the forwarding rule ###

**Comment by davidelang** [comment]
On Tue, 25 Jul 2017, gubzh wrote:

> If you put `*.* /var/log/debugfmt;RSYSLOG_DebugFormat` before or after 
> `action(type="mmfields")` then logs are written in `debugfmt`, but when `*.* 
> /var/log/debugfmt;RSYSLOG_DebugFormat` is put after `action(type="ommysql" 
> server="localhost" db="dbname" uid="root" pwd="password")` in `debugfmt` 
> nothing is written down.

so that tells me that rsyslog is unable to connec to the mysql server to deliver 
the log messages

>
> This is full rsyslog.conf:
>
> # rsyslog configuration file
> # note that most of this config file uses old-style format,
> # because it is well-known AND quite suitable for simple cases
> # like we have with the default config. For more advanced
> # things, RainerScript configuration is suggested.
>
> # For more information see /usr/share/doc/rsyslog-*/rsyslog_conf.html
> # If you experience problems, see http://www.rsyslog.com/doc/troubleshoot.html
>
> #### MODULES ####
>
> # Load the MySQL Module
> module(load="ommysql")
>
> # Provides TCP syslog reception
> module(load="imtcp")
>
> # Provides UDP syslog reception
> module(load="imudp")
>
> # Load the Mmfields Module
> module(load="mmfields")
>
> template(name="ceflogs" type="string" string="insert into idslogs (`DeviceVendor`, `DeviceProduct`, `DeviceVersion`, `SignatureID`, `Name`, `Severity`, `Extensions_cat`, `Extensions_dmac`, `Extensions_cnt`, `Extensions_cs2Label`, `Extensions_cs2`, `Extensions_cs3Label`, `Extensions_cs3`, `Extensions_cs1Label`, `Extensions_cs1`, `Extensions_dst`, `Extensions_spt`, `Extensions_dpt`, `Extensions_proto`, `Extensions_deviceExternalId`, `Extensions_smac`, `Extensions_rt`, `Extensions_src`) values ('%$!cef!DeviceVendor%', '%$!cef!DeviceProduct%', '%$!cef!DeviceVersion%', '%$!cef!SignatureID%', '%$!cef!Name%', %$!cef!Severity%, %$!cef!Extensions!cat%, '%$!cef!Extensions!dmac%', %$!cef!Extensions!cnt%, '%$!cef!Extensions!cs2Label%', '%$!cef!Extensions!cs2%', '%$!cef!Extensions!cs3Label%', '%$!cef!Extensions!cs3%', '%$!cef!Extensions!cs1Label%', '%$!cef!Extensions!cs1%', '%$!cef!Extensions!dst%', %$!cef!Extensions!spt%, %$!cef!Extensions!dpt%, '%$!cef!Extensions!proto%', %$!cef!Exte!
 nsions!deviceExternalId%, '%$!cef!Extensions!smac%', %$!cef!Extensions!rt:::date-mysql%, '%$!cef!Extensions!src%')")
>
> ruleset(name="remote") {
>
> # *.* /var/log/debugfmt;RSYSLOG_DebugFormat
>
> action(type="mmfields")
>
> # *.* /var/log/debugfmt;RSYSLOG_DebugFormat
>
> action(type="ommysql" server="localhost" serverport="3306" db="dbname" uid="username" pwd="password")
>
> # *.* /var/log/debugfmt;RSYSLOG_DebugFormat
>
> }
>
> input(type="imtcp" port="514" ruleset="remote")
> input(type="imudp" port="514" ruleset="remote")
>
> #### GLOBAL DIRECTIVES ####
>
> # Use default timestamp format
> $ActionFileDefaultTemplate RSYSLOG_TraditionalFileFormat
>
> # File syncing capability is disabled by default. This feature is usually not required,
> # not useful and an extreme performance hit
> # $ActionFileEnableSync on
>
> # Include all config files in /etc/rsyslog.d/
> $IncludeConfig /etc/rsyslog.d/*.conf
>
>
> #### RULES ####
>
> # Log all kernel messages to the console.
> # Logging much else clutters up the screen.
> # kern.*                                                 /dev/console
>
> # Log anything (except mail) of level info or higher.
> # Don't log private authentication messages!
> *.info;mail.none;authpriv.none;cron.none                /var/log/messages
>
> # The authpriv file has restricted access.
> authpriv.*                                              /var/log/secure
>
> # Log all the mail messages in one place.
> mail.*                                                  /var/log/maillog
>
> # Log cron stuff
> cron.*                                                  /var/log/cron
>
> # Everybody gets emergency messages
> *.emerg                                                 :omusrmsg:*
>
> # Save news errors of level crit and higher in a special file.
> uucp,news.crit                                          /var/log/spooler
>
> # Save boot messages also to boot.log
> local7.*                                                /var/log/boot.log
>
>
> # ### begin forwarding rule ###
> # The statement between the begin ... end define a SINGLE forwarding
> # rule. They belong together, do NOT split them. If you create multiple
> # forwarding rules, duplicate the whole block!
> # Remote Logging (we use TCP for reliable delivery)
> # An on-disk queue is created for this action. If the remote host is
> # down, messages are spooled to disk and sent when it is up again.
>
> # $WorkDirectory /home/logs/rsyslogs # where to place spool files
>
> #$ActionQueueFileName fwdRule1 # unique name prefix for spool files
> #$ActionQueueMaxDiskSpace 1g   # 1gb space limit (use as much as possible)
>
> $ActionQueueSaveOnShutdown on # save messages to disk on shutdown
> $ActionQueueType LinkedList   # run asynchronously
> $ActionResumeRetryCount -1    # infinite retries if host is down
>
> # remote host is: name/ip:port, e.g. 192.168.0.1:514, port optional
> # CPG - if you need to forward to other systems as well, just add additional config lines:
>
> # ### end of the forwarding rule ###
>
>

**Comment by gubzh** [comment]
In the `action(type="ommysql" server="localhost" db="dbname" uid="root" pwd="password")` server, db, uid, pwd are entered correctly.
When database is opened with command `mysql -u root -p dbname`, after the password is entered, the database is opened and SQL commands are executed.

**Comment by davidelang** [comment]
what does mysql log when rsyslog attempts to connect and insert a log? crank the 
logging level up to where it logs the insert string to make sure everything is 
what you expect.

does it show rsyslog connecting as expected?, does it show an attempt to insert 
the log? does it show an error on that insert?

**Comment by gubzh** [comment]
This is message from mysqld.log

> Connect	root@localhost on dbname
Query	set autocommit=0
Query	insert into table (`DeviceVendor`, `DeviceProduct`, `DeviceVersion`, `SignatureID`, `Name`, `Severity`, `Extensions_cat`, `Extensions_dmac`, `Extensions_cnt`, `Extensions_cs2Label`, `Extensions_cs2`, `Extensions_cs3Label`, `Extensions_cs3`, `Extensions_cs1Label`, `Extensions_cs1`, `Extensions_dst`, `Extensions_spt`, `Extensions_dpt`, `Extensions_proto`, `Extensions_deviceExternalId`, `Extensions_smac`, `Extensions_rt`, `Extensions_src`) values ('', '', '', '', '', , , '', , '', '', '', '', '', '', '', , , '', , '', , '')
Quit

**Comment by gubzh** [comment]
Blank values are written to the database. mmfields don't parsing added values from CEF logs. `%$!cef!DeviceVendor%` and other values don't working.
How can I fix this?

**Comment by davidelang** [comment]
so this tells methat the variables do not contain the values you expect them to.

log with the template RSYSLOG_DebugFormat and see what variables you actually 
have.

**Comment by gubzh** [comment]
This is log in RSYSLOG_DebugFormat:

`$!:{ "cef": { "DeviceVendor": "Vendor", "DeviceProduct": "Product", "DeviceVersion": "Verison", "SignatureID": "ID", "Name": "Event name", "Severity": "2", "Extensions": { "at": "1", "cn1": "1111", "cn1Label": "EventID", "cnt": "1", "cs1": "cs1 name", "cs1Label": "cs1Label name", "cs2": "cs2-info", "cs2Label": "cs2Label name", "cs3": "cs3 info", "cs3Label": "cs3Label name", "deviceExternalId": "ID", "dmac": "11:11:11:11:11:aa", "dpt": "111", "dst": "10.0.0.1", "proto": "PR name", "rt": "Jul 30 201`

This is log from mysql.log:

`190 Query	commit
190 Query	START TRANSACTION
190 Query	insert into idslogs (DeviceVendor, DeviceProduct, DeviceVersion, SignatureID, Name, Severity, Extensions_cat, Extensions_dmac, Extensions_cnt, Extensions_cs2Label, Extensions_cs2, Extensions_cs3Label, Extensions_cs3, Extensions_cs1Label, Extensions_cs1, Extensions_dst, Extensions_spt, Extensions_dpt, Extensions_proto, Extensions_deviceExternalId, Extensions_smac, Extensions_rt, Extensions_src) values ('', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '')`

This is rule from rsyslog.conf:

`template(name="cef" type="string" option.sql="on"
string="insert into idslogs (DeviceVendor, DeviceProduct, DeviceVersion, SignatureID, Name, Severity, Extensions_cat, Extensions_dmac, Extensions_cnt, Extensions_cs2Label, Extensions_cs2, Extensions_cs3Label, Extensions_cs3, Extensions_cs1Label, Extensions_cs1, Extensions_dst, Extensions_spt, Extensions_dpt, Extensions_proto, Extensions_deviceExternalId, Extensions_smac, Extensions_rt, Extensions_src) values ('%$!cef!DeviceVendor%', '%$!cef!DeviceProduct%', '%$!cef!DeviceVersion%', '%$!cef!SignatureID%', '%$!cef!Name%', '%$!cef!Severity%', '%$!cef!Extensions!cat%', '%$!cef!Extensions!dmac%', '%$!cef!Extensions!cnt%', '%$!cef!Extensions!cs2Label%', '%$!cef!Extensions!cs2%', '%$!cef!Extensions!cs3Label%', '%$!cef!Extensions!cs3%', '%$!cef!Extensions!cs1Label%', '%$!cef!Extensions!cs1%', '%$!cef!Extensions!dst%', '%$!cef!Extensions!spt%', '%$!cef!Extensions!dpt%', '%$!cef!Extensions!proto%', '%$!cef!Extensions!deviceExternalId%', '%$!cef!Extensions!smac%', '%$!cef!Extensions!rt:::date-mysql%', '%$!cef!Extensions!src%')")`

Why don't write in MySQL database?

What the variable format is needed in rsyslog.conf?
($!cef!DeviceVendor and other)

P.S.

If you put '%$!cef' then in MySQL database is written down 

`"DeviceVendor": "Vendor", "DeviceProduct": "Product", "DeviceVersion": "Verison", "SignatureID": "ID", "Name": "Event name", "Severity": "2", "Extensions": { "at": "1", "cn1": "1111", "cn1Label": "EventID", "cnt": "1", "cs1": "cs1 name", "cs1Label": "cs1Label name", "cs2": "cs2-info", "cs2Label": "cs2Label name", "cs3": "cs3 info", "cs3Label": "cs3Label name", "deviceExternalId": "ID", "dmac": "11:11:11:11:11:aa", "dpt": "111", "dst": "10.0.0.1", "proto": "PR name", "rt": "Jul 30 2017 01:01:01.001 MSK", "smac": "aa:aa:aa:aa:aa:ba", "spt": "222", "src": "10.0.0.2"`

**Comment by davidelang** [comment]
On Sun, 30 Jul 2017, gubzh wrote:

> This is log in RSYSLOG_DebugFormat:
>
> `$!:{ "cef": { "DeviceVendor": "Vendor", "DeviceProduct": "Product", "DeviceVersion": "Verison", "SignatureID": "ID", "Name": "Event name", "Severity": "2", "Extensions": { "at": "1", "cn1": "1111", "cn1Label": "EventID", "cnt": "1", "cs1": "cs1 name", "cs1Label": "cs1Label name", "cs2": "cs2-info", "cs2Label": "cs2Label name", "cs3": "cs3 info", "cs3Label": "cs3Label name", "deviceExternalId": "ID", "dmac": "11:11:11:11:11:aa", "dpt": "111", "dst": "10.0.0.1", "proto": "PR name", "rt": "Jul 30 201`

at least some versions of rsyslog have problems with variables with mixed case, 
I think there is a config option around this now

> What the variable format is needed in rsyslog.conf?
> ($!cef!DeviceVendor and other)

yes, this would be the correct way to access these variables.

>
> P.S.
>
> If you put '%$!cef' then in MySQL database is written down
>
> `"DeviceVendor": "Vendor", "DeviceProduct": "Product", "DeviceVersion": 
> "Verison", "SignatureID": "ID", "Name": "Event name", "Severity": "2", 
> "Extensions": { "at": "1", "cn1": "1111", "cn1Label": "EventID", "cnt": "1", 
> "cs1": "cs1 name", "cs1Label": "cs1Label name", "cs2": "cs2-info", "cs2Label": 
> "cs2Label name", "cs3": "cs3 info", "cs3Label": "cs3Label name", 
> "deviceExternalId": "ID", "dmac": "11:11:11:11:11:aa", "dpt": "111", "dst": 
> "10.0.0.1", "proto": "PR name", "rt": "Jul 30 2017 01:01:01.001 MSK", "smac": 
> "aa:aa:aa:aa:aa:ba", "spt": "222", "src": "10.0.0.2"`

I think ths confirms the upper case variable name problem.

David Lang

**Comment by gubzh** [comment]
Thank you for the information, but what can I do to correct the error?

**Comment by davidelang** [comment]
well, I'm hoping that someone who knows the answer offhand is going to speak up 
(Rainer is in Germany, so he should be getting going petty soon :-)

I don't remember how things were resolved, I would have to dig through past 
issues, documentation, and code looking for something about case sensitive 
variable names (or some search like that)

**Comment by gubzh** [comment]
How to change template modules "mmnormalize" to rsyslog.conf so that instead of `DeviceVersion, DeviceVendor, DeviceProduct` there would be `deviceversion, devicevendor, deviceproduct`?

**Comment by davidelang** [comment]
what is your mmnormalize config? Depending on how you do things there, it's either trivial or impossible.

looking at the documentation, I find on the page: http://www.rsyslog.com/doc/v8-stable/configuration/templates.html
the option
option.casesensitive - treat property name references as case sensitive. The default is “off”, where all property name references are first converted to lowercase during template definition. With this option turned “on”, property names are looked up as defined in the template. Use this option if you have JSON ($!*), local (!.*), or global ($!\\*) properties which container uppercase letters. The normal Rsyslog properties are case-insensitive, so this option is not needed for properly referencing those properties.

try redefining your template for oommysql to use this.

**Comment by rgerhards** [comment]
2017-07-31 8:09 GMT+02:00 David Lang <notifications@github.com>:

> well, I'm hoping that someone who knows the answer offhand is going to
> speak up
> (Rainer is in Germany, so he should be getting going petty soon :-)
>
>
Sorry,  I have been out for a couple of days, only now "back to action".

Go to

http://www.rsyslog.com/doc/v8-stable/configuration/templates.html

and search for "casesensitive".

The case sensitivity is indeed a bad issue; we should try to find a
solution that does not break existing configs (that's the hard part...).

Rainer

**Comment by gubzh** [comment]
Excuse me, please tell me where add `option.casesensitive="off"` in my rsyslog.conf.

**Comment by davidelang** [comment]
On Tue, 1 Aug 2017, Rainer Gerhards wrote:

> The case sensitivity is indeed a bad issue; we should try to find a
> solution that does not break existing configs (that's the hard part...).

I was thinking about that, and I want to propose the following:

case sensitive match of variable names, but if no such name is found, do a case 
insensitive match

thoughts?

David Lang

**Comment by davidelang** [comment]
On Tue, 1 Aug 2017, gubzh wrote:

> Excuse me, please tell me where add `option.casesensitive="off"` in my rsyslog.conf.

It would be part of the template definition, you would have to use the new style 
template definition, not the old style, and add the option as an additional 
parameter.

by the way, you want casesensitive="on", off is the default.

David Lang

**Comment by gubzh** [comment]
What should be template module "mmnormolize" for CEF logs?

**Comment by rgerhards** [comment]
I have crafted a test that checks with case-sensitive JSON content. The current rsyslog comparation logic does **not** properly cover this, at least I am getting the same invalid result. Will check what is going on.

**Comment by rgerhards** [comment]
mmmhhh... my fault. I used ```option.casesensitive="off"``` in my test, but it should be on, of course... Then it works. Will try some more...

**Comment by rgerhards** [comment]
Well, I now used the exact same data given here. It works. I used this stripped-down template definition:
```
template(name="outfmt" type="string" string="%$!cef!DeviceVendor%|%msg%\n" option.casesensitive="on")
```
I guess just the option was not properly applied.

**Comment by gubzh** [comment]
If added this rule
> template(name="cef" type="string" option.sql="on" string="insert into idslogs (DeviceVendor) values ('%$!cef!DeviceVendor%|%msg%')" option.casesensitive="on")
 in rsyslog.conf, then in mysqld.log logs are not recorded.

**Comment by rgerhards** [comment]
Please provide complete debug log.  Details: http://www.rsyslog.com/doc/v8-stable/troubleshooting/debug.html#enabling-debug-via-rsyslog-conf

**Comment by rgerhards** [comment]
Or maybe the column is too small and mysql barks for that reason? %msg% is pretty large...

**Comment by gubzh** [comment]
if added rule
`
template(name="cef" type="string" option.sql="on" string="insert into idslogs (DeviceVendor) values ('%$!cef!DeviceVendor%|%msg%')" option.casesensitive="off")`

in rsyslog.conf then

in debagfmt added logs:

`$!:{ "cef": { "DeviceVendor": "IT", "DeviceProduct": "Softname", "DeviceVersion": "1.2.3-456789", "SignatureID": "123:4:5", "Name": "SCAN", "Severity": "3", "Extensions": { "at": "1", "cn1": "12345678", "cn1Label": "ID", "cnt": "1", "cs1": "proto", "cs1Label": "Class", "cs2": "proc", "cs2Label": "Group", "cs3": "", "cs3Label": "CID", "deviceExternalId": "1233456789", "dmac": "00:11:22:33:44:55", "dpt": "0", "dst": "1.1.1.1", "proto": "IP", "rt": "Oct 05 2017 09:31:27.957 MSK", "smac": "22:22:22:22:22:22", "spt": "0", "src": "2.2.2.2" } } }`

and added in mysqld.log this logs:


```
761 Query	START TRANSACTION
		  761 Query	insert into idslogs (DeviceVendor) values ('| CEF:0|IT|Softname|1.2.3-456789|123:4:5|SCAN|3|cat=1 cn1=12345678 cn1Label=ID cnt=1 cs1=proto cs1Label=Class cs2=proc cs2Label=Group cs3= cs3Label=CID deviceExternalId=1233456789 dmac=00:11:22:33:44:55 dpt=0 dst=1.1.1.1 proto=IP rt=Oct 05 2017 09:31:27.957 MSK smac=22:22:22:22:22:22 spt=0 src=2.2.2.2')
		  761 Query	commit
```

and if added rule

`template(name="cef" type="string" option.sql="on" string="insert into idslogs (DeviceVendor) values ('%$!cef!DeviceVendor%|%msg%')" option.casesensitive="on")`

in rsyslog.conf then

in debagfmt added logs:

`$!:{ "cef": { "DeviceVendor": "IT", "DeviceProduct": "Softname", "DeviceVersion": "1.2.3-456789", "SignatureID": "123:4:5", "Name": "SCAN", "Severity": "3", "Extensions": { "at": "1", "cn1": "12345678", "cn1Label": "ID", "cnt": "1", "cs1": "proto", "cs1Label": "Class", "cs2": "proc", "cs2Label": "Group", "cs3": "", "cs3Label": "CID", "deviceExternalId": "1233456789", "dmac": "00:11:22:33:44:55", "dpt": "0", "dst": "1.1.1.1", "proto": "IP", "rt": "Oct 05 2017 09:31:27.957 MSK", "smac": "22:22:22:22:22:22", "spt": "0", "src": "2.2.2.2" } } }`

and don't added logs in mysqld.log.

**Comment by rgerhards** [comment]
I need a debug log to diagnose this. See my last reply.

**Comment by gubzh** [comment]
This is debug log[
[rsyslog-debug.log](https://github.com/rsyslog/rsyslog/files/1359121/rsyslog-debug.log)
](url)

**Comment by rgerhards** [comment]
I can see several error messages in the debug log. You should really check rsyslog error output...

8706.723803141:main thread    : errmsg.c: Called LogMsg, msg: template 'cef' has multiple incompatible options of sql, stdsql or json specified
8706.723941318:main thread    : glbl.c: rsyslog/glbl: using '127.0.0.1' as localhost IP
8706.724575651:main thread    : errmsg.c: Called LogMsg, msg: error during parsing file /etc/rsyslog.conf, on or before line 24: error processing template objec
8706.729670400:main thread    : errmsg.c: Called LogMsg, msg:  Could not find template 0 'cef' - action disabled
8706.729717069:main thread    : errmsg.c: Called LogMsg, msg: error during parsing file /etc/rsyslog.conf, on or before line 26: errors occured in file '/etc/rsyslog.conf' around line 2

**Comment by rgerhards** [comment]
nevertheless, the first error message points to a bug (but it would have been much easier if you posted the error messages right from the beginning - both for you and me ;-)).

**Comment by gubzh** [comment]
Sorry, this is must be correctly logs:
[rsyslog-debug.log](https://github.com/rsyslog/rsyslog/files/1359440/rsyslog-debug.log)

**Comment by rgerhards** [comment]
What problem do you want to show with the last log? Mysql is not used nor is a file mysqld.log inside the config...

**Comment by gubzh** [comment]
In rule 
`template(name="cef" type="string" option.sql="on" string="insert into idslogs (DeviceVendor) values ('%$!cef!DeviceVendor%|%msg%')" option.casesensitive="on")`
don`t working 2 option option.sql="on" and option.casesensitive="on" simultaneously.

**Comment by rgerhards** [comment]
Yes, that's what I said...

**Comment by rgerhards** [comment]
Just in case you did not follow this ticket, this is the link to the related patch: https://github.com/rsyslog/rsyslog/issues/1811

**Comment by gubzh** [comment]
how can I fix it?

**Comment by gubzh** [comment]
Thanks for the help. In version 8.30 the problem is solved.
