### ISSUE TITLE
Provide C module/plugin interface via an installable header file

### ISSUE THREAD

**Issue by dkopecek** [rsyslog/rsyslog#1692]
Hello,
 I'm curious whether it is possible to have an externally build rsyslog module, provided as a separate package? 
From a quick look at the source of some of the modules it seems to me that there is some kind of versioned interface used by the modules. Would it be possible to provide this interface via an installable header file which would enable developing loadable modules out of the rsyslog source tree?

**Comment by richm** [comment]
@portante

**Comment by radosroka** [comment]
What do you think about it @rgerhards ? is it possible?

**Comment by rgerhards** [comment]
it's for sure possible, but its probably a lot refactoring to be done. Among others, I guess, the convenience rsyslog runtime lib would probably need to be turned into a full blown-lib to make it linkable. Also, while the interface is versioned, there currently is no backwards compatibility support.

**Comment by rgerhards** [comment]
anyone still interested in implementing this? If not, I'd close the tracker...
