### ISSUE TITLE
how to decide mapping  for elasticsearch

### ISSUE THREAD

**Issue by luvpreetsingh** [rsyslog/rsyslog#1696]
I am using rsyslog version 8.27.0 on ubuntu 14.04 for pushing logs to elasticsearch(I intend to use it on 16.04 in near future).

Here is the liblognorm rulebase for matching the logs,

    version=2

    #below are the rules for nginx log matching 
    rule=infotrack: %remote_addr:word% %ident:word% %auth:word% [%@timestamp:char-to:]%] "%method:word% %request:word% HTTP/%httpversion:float% "%status:number% %bytes_sent:number% %requesttime:float% "%referrer:char-to:"%" "%agent:char-to:"%"%blob:rest%

So, I have added here that `httpversion`, `status`, `requesttime`, `bytes_sent` are not strings, but they are numbers. 

This is for matching the logs, and my logs are separated into different fields. 

I want my these fields, `httpversion`, `status`, `requesttime`, `bytes_sent` as numbers and floats(as they have been matched).

But, in my elasticsearch, I see that all the fields are stored as **text**.

Here is the mapping, 

    luvpreet@ubuntu-server-14.04:~$ curl -XGET 'localhost:9200/nginx-logs-alpha-parsed/_mapping?pretty'
    {
      "nginx-logs-alpha-parsed" : {
        "mappings" : {
          "nginx" : {
            "properties" : {
              "@timestamp" : {
                "type" : "date"
              },
              "agent" : {
                "type" : "text",
                "fields" : {
                  "keyword" : {
                    "type" : "keyword",
                    "ignore_above" : 256
                  }
                 }
              },
              "auth" : {
                "type" : "text",
                "fields" : {
                  "keyword" : {
                    "type" : "keyword",
                    "ignore_above" : 256
                  }
                }
              },
              "blob" : {
                "type" : "text",
                "fields" : {
                  "keyword" : {
                    "type" : "keyword",
                    "ignore_above" : 256
                  }
                }
              },
              "bytes_sent" : {
                "type" : "text",
                "fields" : {
                  "keyword" : {
                    "type" : "keyword",
                    "ignore_above" : 256
                  }
            }
          },
          "event" : {
            "properties" : {
              "tags" : {
                "type" : "text",
                "fields" : {
                  "keyword" : {
                    "type" : "keyword",
                    "ignore_above" : 256
                  }
                }
              }
            }
          },
          "httpversion" : {
            "type" : "text",
            "fields" : {
              "keyword" : {
                "type" : "keyword",
                "ignore_above" : 256
              }
            }
          },
          "ident" : {
            "type" : "text",
            "fields" : {
              "keyword" : {
                "type" : "keyword",
                "ignore_above" : 256
              }
            }
          },
          "method" : {
            "type" : "text",
            "fields" : {
              "keyword" : {
                "type" : "keyword",
                "ignore_above" : 256
              }
            }
          },
          "referrer" : {
            "type" : "text",
            "fields" : {
              "keyword" : {
                "type" : "keyword",
                "ignore_above" : 256
              }
            }
          },
          "remote_addr" : {
            "type" : "text",
            "fields" : {
              "keyword" : {
                "type" : "keyword",
                "ignore_above" : 256
              }
            }
          },
          "request" : {
            "type" : "text",
            "fields" : {
              "keyword" : {
                "type" : "keyword",
                "ignore_above" : 256
              }
            }
          },
          "requesttime" : {
            "type" : "text",
            "fields" : {
              "keyword" : {
                "type" : "keyword",
                "ignore_above" : 256
              }
            }
          },
          "status" : {
            "type" : "text",
            "fields" : {
              "keyword" : {
                "type" : "keyword",
                "ignore_above" : 256
              }
            }
          }
        }
      }
     }
    }
    }

This is not the way I intended it to stored.  

Is there any way I can create a mapping for the index through rsyslog 
OR 
I have to create a mapping in elasticsearch before pushing the logs there ?

**Comment by wdauchy** [comment]
The best way is to create a mapping in ES before pushing logs (ES templates)

**Comment by luvpreetsingh** [comment]
I think you should update the docs about this thing.

One more question,

How does elastic get to know the `@timestamp` as **date field** ? Why is not @timestamp stored as text type ? Does rsyslog sends it as a date field ?

**Comment by wdauchy** [comment]
Could you point out what is wrong in the documentation http://www.rsyslog.com/doc/v8-stable/configuration/modules/omelasticsearch.html ? it's not up to rsyslog doc to explain it is better to define your mapping on ES side first.

@timestamp represents the time when the event was generated. Again, the important thing here is to define on ES the type of your field (type timestamp preferably)

**Comment by luvpreetsingh** [comment]
There is nothing wrong with the docs. 

I am just suggesting that you should write there that mappings should be created first in the elasticsearch.

**Comment by davidelang** [comment]
I don't believe we currntly have a way to do this, we used to have the interpret 
parser in liblognorm that I think would have done what you want, but that didn't 
get re-written into the v2 engine.

Rsyslog treats everything as stings (actually sequences of bytes, we don't even 
care if they are valid in any particular charset rules)
