### ISSUE TITLE
rsyslog stops writing logs until restarted

### ISSUE THREAD

**Issue by jhenry82** [rsyslog/rsyslog#1701]
Apologies in advance for what is going to start out as a vague bug report. I'm very interested in next steps I can provide to help flesh this out, as it is making rsyslog unusable for us.

rsyslog: 8.26
librelp: 1.2.13
CentOS 6.9 x86_64

We have 2 servers that receive logs from about 1000 remote hosts via RELP. The volume is large but not insane, maybe in the dozens of gigabytes per hour range. After a seemingly random amount of time (days to weeks), one of these servers will simply stop writing logs until rsyslog is restarted. Messages continue to be received by RELP and written to disk-assisted queues. But the omfile action that writes them to their final destination seems just infinitely blocked. No errors of any kind are logged by rsyslog when this happens. I do have impstats configured to write to ElasticSearch periodically, and these stats continue to update while the issue is happening.

I monitor open file descriptors and we're only using about 25% of the configured limit, so it shouldn't be that. There's nothing remarkable happening on the box when this happens. System metrics look normal other than memory usage spiking, which seems due to messages starting to pile up in the main queue.

Here is the full config on the affected servers. Is there something obviously boneheaded about the actions or main queue?

rsyslog.conf
```
#################
#### MODULES ####
#################

module(load="imuxsock")  # provides support for local system logging
module(load="imklog")    # provides kernel logging support (previously done by rklogd)
module(load="immark")    # provides --MARK-- message capability
module(load="imfile")    # provides support for tailing local files
module(load="omrelp")    # provides support for RELP protocol

###########################
#### GLOBAL DIRECTIVES ####
###########################

global(
	preserveFQDN="on"
	workDirectory="/var/log/rsyslog_spool"
	umask="0000"
	action.reportSuspensionContinuation="on"
	janitor.interval="1"
)

# Use default timestamp format, but allow app names (syslogtag) longer than 32 characters
# This prevents weird truncated filenames on the log servers, and in Logstash
template(name="LongTagForwardFormat" type="string"
	string="<%PRI%>%TIMESTAMP% %HOSTNAME% %syslogtag%%msg:::sp-if-no-1st-sp%%msg%"
)

# Set the default permissions for all log files.
module(
	load="builtin:omfile"
	dirCreateMode="0755"
	fileCreateMode="0644"
	fileOwner="root"
	fileGroup="root"
	dirOwner="root"
	dirGroup="root"
)

##########################
#### STATS MONITORING ####
##########################
module(load="mmnormalize")
module(load="omelasticsearch")
module(
	load="impstats"
	interval="60"
	resetCounters="on"
	format="json-elasticsearch"
	ruleset="stats"
)

# Template to generate the JSON doc of all stats, which will be submitted to ElasticSearch
template(name="rsyslog_stats" type="list") {
	constant(value="{")
	constant(value="\"@timestamp\":\"")
	property(name="timereported" dateFormat="rfc3339")
	constant(value="\",\"host\":\"")
	property(name="hostname")
	constant(value="\",")
	property(name="$!all-json" position.from="2")
}

# Template for naming and sharding the elasticsearch index per-day
# rsyslog-YYYY.MM.DD
template(
	name="rsyslog-index-name"
	type="string"
	string="rsyslog-%timereported:::date-year%.%timereported:::date-month%.%timereported:::date-day%"
)

# Doing all of the stats logging in a ruleset effectively namespaces it,
# so it's not processed by any other rules later on
ruleset(
	name="stats"
	queue.type="LinkedList"
	queue.saveonshutdown="on"
	queue.filename="impstats.queue"
	queue.lowwatermark="100"
	queue.highwatermark="1000"
	queue.maxdiskspace="1g"
) {
	# Transform the logs to JSON
	action(
		name="parse_rsyslog_stats"
		type="mmnormalize"
		ruleBase="/etc/rsyslog.d/rsyslog-json.rulebase"
	)

	# Emit the JSON logs to ElasticSearch for storage
	action(
		name="push_rsyslog_stats"
		type="omelasticsearch"
		server="REDACTED"
		serverport="80"
		template="rsyslog_stats"
		bulkmode="on"
		dynSearchIndex="on"
		errorfile="/var/log/rsyslog-es-err.log"
		searchIndex="rsyslog-index-name"
		action.resumeRetryCount="-1"
		action.resumeInterval="60"
	)
}

##########################

# Include all config files in /etc/rsyslog.d/
$IncludeConfig /etc/rsyslog.d/*.conf
```

01server.conf
```
module(load="imrelp")
module(load="imtcp")
module(load="imudp")

# Main queue config
# Adding a (high) threshold to start spooling to disk. This is an attempt
# to mitigate issues we've seen where rsyslog suddenly consumes all memory
# and just dies.
main_queue(
    queue.size="5000000"
    queue.workerthreadminimummessages="100"
    queue.type="LinkedList"
    queue.workerthreads="10"
    queue.dequeuebatchsize="16384"
    queue.filename="main.queue"
    queue.highwatermark="2500000"
    queue.lowwatermark="1000000"
    queue.discardMark="5000000"
    queue.saveonshutdown="on"
    queue.maxdiskspace="100g"
)

# We wanted a way to replay logs that were not successfully replicated to rsyslog for whatever reason
# This config section defines a custom listener on TCP 51414. When messages come in to this port, log them using the
# timereported property, which is the time they were ORIGINALLY logged, not when they came into this server.
# Then drop them, so they aren't double-counted in "today's" directory as well
input(type="imtcp" port="51414" name="logreplay")
template(name="ReplayOldLogs" type="string"
    string="/data/system-logs/%timereported:::date-year%/%timereported:::date-month%/%timereported:::date-day%/%hostname%/%programname:::lowercase%-%timereported:::date-year%%timereported:::date-month%%timereported:::date-day%-%timereported:::date-hour%.log"
)

if $inputname == "logreplay" then {
    action(
        name="logreplay"
        type="omfile"
        dynaFile="ReplayOldLogs"
        template="RSYSLOG_TraditionalFileFormat"
        flushOnTXEnd="off"
        ioBufferSize="128k"
        dynaFileCacheSize="100"
        asyncWriting="on"
        closeTimeout="5"
    )
    stop
}

# Define network inputs. RELP is the primary one we use.
input(
    type="imrelp"
    port="20514"
    name="imrelp"
    keepalive="on"
)

input(
    type="imtcp"
    port="514"
    name="imtcp"
)

input(
    type="imudp"
    port="514"
    name="imudp"
)

# This allows per-host logging
template(
    name="DirPerHost"
    type="string"
    string="/data/system-logs/%$YEAR%/%$MONTH%/%$DAY%/%hostname%/%programname:::lowercase%-%$YEAR%%$MONTH%%$DAY%-%$hour%.log"
)

action(
    name="dirperhost"
    type="omfile"
    dynaFile="DirPerHost"
    template="RSYSLOG_TraditionalFileFormat"
    flushOnTXEnd="off"
    ioBufferSize="128k"
    dynaFileCacheSize="10000"
    asyncWriting="on"
    closeTimeout="5"
)
```
rsyslog-json.rulebase
```
version=2
rule=:%data:json%
```

**Comment by davidelang** [comment]
setting the workerthreads=10 seems like it could potentially be a problem (too many workers and you run into grief because it makes the batch sizes processed too small, among other things.

I would also disable asyncwriting from dirperhost, when you aren't doing compression, asyncwriting is almost always slower than writing directly to disk (it also results in LOTS of threads being created, which can cause memory issues, lock contention, and other problems)

what does the pstats data show? does it show actions as syspended or failed? does it show the actions continuing to process logs?

**Comment by jhenry82** [comment]
Thanks, I will look into those settings.

I never see a suspend or failure logged in pstats (these would be the "failed" and "suspended" fields, right?). All actions except the one pushing stats to ElasticSearch go dormant. imrelp continues to be busy, though. It's like at some point omfile failed or blocked and never tried again.

**Comment by jhenry82** [comment]
@davidelang , when I turned off async writing, it had a surprising side effect. Some of our logs that are pretty low volume (like 1 message a minute or less) end up never being flushed to disk until you restart rsyslog, or the closeTimeout is reached. Even if I set `flushOnTXEnd="on"`.

In a dynafile omfile action, is the IO buffer per-file or global? I'm guessing what's happening is that the IO buffer on these low volume logs never fills, and so data is never written. But I'd also expect `flushOnTXEnd="on"` to mitigate that. But that's not happening. Is the "transaction end" defined as either the IO buffer filling or the closeTimeout firing, then?

Is there something else I can do to make these lower-volume logs flush closer to real time? Dramatically lower the size of the IO buffer? We also have logs that get hundreds of thousands of lines an hour, which makes the tuning tough. I don't care if there's a few second delay, but having them buffered for hours is problematic.

**Comment by davidelang** [comment]
On Wed, 2 Aug 2017, Jon Henry wrote:

> @davidelang , when I turned off async writing, it had a surprising side 
> effect. Some of our logs that are pretty low volume (like 1 message a minute 
> or less) end up never being flushed to disk until you restart rsyslog, or the 
> closeTimeout is reached. Even if I set `flushOnTXEnd="on"`.

they should also be written out on a HUP

> In a dynafile omfile action, is the IO buffer per-file or global?

per file

> I'm guessing what's happening is that the IO buffer on these low volume logs 
> never fills, and so data is never written. But I'd also expect 
> `flushOnTXEnd="on"` to mitigate that. But that's not happening. Is the 
> "transaction end" defined as either the IO buffer filling or the closeTimeout 
> firing, then?
>
> Is there something else I can do to make these lower-volume logs flush closer 
> to real time? Dramatically lower the size of the IO buffer? We also have logs 
> that get hundreds of thousands of lines an hour, which makes the tuning tough. 
> I don't care if there's a few second delay, but having them buffered for hours 
> is problematic.

on my systems, I HUP frequently for log rotation purposes, and that makes sure 
the data is written out 'fast enough'

I think Rainer is going to have to comment on all of this.

**Comment by rgerhards** [comment]
> In a dynafile omfile action, is the IO buffer per-file or global? I'm guessing what's happening is that the IO buffer on these low volume logs never fills, and so data is never written. But I'd also expect flushOnTXEnd="on" to mitigate that. But that's not happening. Is the "transaction end" defined as either the IO buffer filling or the closeTimeout firing, then?

I remember that there was a bug in some versions that caused such behavior. When a batch is completed, it should be written. I think, however, that 8.26 should address the issue. Anyhow, it might be a good idea to upgrade to 8.28.0 to make sure all patches are in place. Please report if the problem persists after doing so. We then need to debug into it.

**Comment by jhenry82** [comment]
I am going to upgrade to 8.29 as soon as RPM's are published to the official repo.

It's much too early to declare victory, since this issue would recur anywhere from 1 hour to 3-4 weeks after the last instance. But since disabling async writes and reducing the main queue workers to 1, it has not happened again. If I get a consecutive 6 weeks of uptime, I will come back and close this out.

If eliminating concurrency ends up resolving the issue, that would seem to indicate a bad deadlock bug lurking in the codebase?

**Comment by jhenry82** [comment]
Also, thanks for the SIGHUP tip. That is super helpful. I will add a cron to signal rsyslog periodically, but that's not directly related to this bug.
