### ISSUE TITLE
TLS enabled TCP input and output

### ISSUE THREAD

**Issue by ayashjorden** [rsyslog/rsyslog#1702]
Hello,
I'm looking for a way to configure a log relay which provides:
1. TCP input with TLS enabled
2. TCP output to a TLS enabled endpoint.

I've tried setting `$DefaultNetstreamDriverCAFile` config element multiple times, but it seems that only the last entry takes place and above entries are ignored.

This issue is somewhat similar but different to #1688 

# Example config
```
#### Modules ####
module(load="omstdout")

module(load="imtcp"
streamdriver.mode="1"
streamdriver.authmode="x509/name"
PermittedPeer="*.rsyslog.local")

# make gtls driver the default
$DefaultNetstreamDriver gtls

# certificate files
$DefaultNetstreamDriverCAFile /ssl/MyRootCA.pem
$DefaultNetstreamDriverCertFile /ssl/rsyslog.pem
$DefaultNetstreamDriverKeyFile /ssl/rsyslog.key

#### LISTENERS ####
input(type="imtcp" port="514")

#### OUTPUTS ####
*.* :omstdout:

template <TEMPLATE_NAME>,<TEMPLATE_CONTENT>
*.* @@tls.enabled.endpoint.com:PORT;TEMPLATE_NAME
```

Thank you,
Jorden

**Comment by ayashjorden** [comment]
Hello again,
I've refactored my config to RainerScript:
```
#### Global #####
global(
    # My CA pem file that signes rsyslog machine and MyOtherClient machine
    # This file contains a concatenation of my CA pem and *.tls.enabled.endpoint.com pem
    defaultNetstreamDriverCAFile="/ssl/ca.pem" 
    defaultNetstreamDriverKeyFile="/ssl/rsyslog.key"
    defaultNetstreamDriverCertFile="/ssl/rsyslog.pem"
    debug.gnutls="3"
)
#### Modules ####
module(load="omstdout")
module(load="imtcp"
    streamdriver.name="gtls"
    streamdriver.mode="1"
    streamdriver.authmode="x509/name"
    PermittedPeer=["*.rsyslog.local","*.tls.enabled.endpoint.com"]
)

#### LISTENERS ####
input(type="imtcp" port="514" name="tls-input")

#### OUTPUTS ####
*.* :omstdout:
    
template(name="TEMPLATE_NAME"
    type="string"
    string="TEMPLATE_FORMAT"
)
*.* action(type="omfwd"
    Protocol="tcp"
    Target="listener.tls.enabled.endpoint.com"
    Port="5001"
    StreamDriver="gtls"
    StreamDriverMode="1"
    StreamDriverAuthMode="x509/name"
    StreamDriverPermittedPeers="*.tls.enabled.endpoint.com"
    template="TEMPLATE_NAME"
)
```

This still doesn't work, it accepts messages from MyOtherClient machine, prints them to stdout **but wont relay them to `*.tls.enabled.endpoint.com` endpoint.**

**Comment by ayashjorden** [comment]
@rgerhards, can you point me to the correct person?

**Comment by davidelang** [comment]
posting on the mailing list would be more likely to get people to notice and 
help, there are very few people who watch the github issues or the forum

I will say that your first attempt made the mistake of mixing legacy and new 
style configs, you can't do that, you need to do one or the other.

I haven't used TLS enough to be familiar with the ins and outs of 
troubleshooting it, but there have got to be tools that are part of the gnutls 
package that will help you do this (which would at least check what the library 
is returning when you attempt to connect to this destination with the files 
you've created)

**Comment by ayashjorden** [comment]
Hi, @davidelang,
I've mailed the community a couple of days ago, apparently this issue gets no traction. 

Can you comment or ping someone who can?

Thank you,
Jorden

**Comment by rgerhards** [comment]
@PascalWithopf did you solve this? Or is it solved otherwise?

**Comment by rgerhards** [comment]
re-assigning timestamp as I wait on @PascalWithopf
