### ISSUE TITLE
rsyslog error with opened for non-append write, but already contains 11266750 bytes 

### ISSUE THREAD

**Issue by Cloud-Leung** [rsyslog/rsyslog#1704]
this is error logs : 

Aug  3 11:04:38 worker-01 rsyslogd: queue 'strm 0x7f68708efcd0', file '/var/log/result_file.00000197' opened for non-append write, but already contains 11266750 bytes  [v8.27.0 try http://www.rsyslog.com/e/0 ]

what's wrong with this ?

**Comment by davidelang** [comment]
This came up in another context, I think it means that rsyslog did not get a 
chance to shutdown cleanly and write the proper .qi file for that queue, and 
starting up, rsyslog notices that there is a file there that has data in it that 
it's not expecting.

Rainer should comment on this to confirm what I'm thinking here.

David Lang

**Comment by deoren** [comment]
For what it is worth, I am seeing this as well with v8.28.0. In my case I'm using Ubuntu 16.04 and the package from the official PPA. One thing I'm doing differently is intentionally holding back rsyslog from starting up until the network is available. This is to work around the issue I reported on #1656.

The contents of the `/etc/systemd/system/rsyslog.service.d/10-wait-on-network.conf` file:

<pre>
[Unit]
After=network.target
Wants=nework.target
</pre>

I'm not sure if that is part of my problem (which I only noticed just recently as the number of clients for the central rsyslog instance increased), but figured it was worth sharing since it might be relevant.

**Comment by rgerhards** [comment]
Yup, that indicates a queue corruption. Due to Shutdown... Or whatever
else...

Most probably, that's an old file from a previous abort.

Rainer

Sent from phone, thus brief.

Am 04.08.2017 22:36 schrieb "David Lang" <notifications@github.com>:

**Comment by jay7x** [comment]
As I understand this problem (see it frequently) it happens because of following reason. 

1. {{systemctl stop rsyslog}} tries to kill rsyslog with SIGTERM, wait 60s (by default).
1. During this time rsyslog is trying to save in-memory queue to disk. So it creates some files.
1. Systemd kill rsyslog with SIGKILL because of timeout.
1. rsyslog is trying to allocate file which must not exists (as rsyslog expect). But it's already there because state was not saved (because of SIGKILL).

This is how I see. I haven't read the sources, just guessing. So may be wrong.

**Comment by rgerhards** [comment]
@jay7x That's exactly what I seen in those cases. Actually very little we can do from the rsyslog side to solve that issue...

**Comment by deoren** [comment]
@rgerhards pardon my ignorance (and a slight tangent), but is it possible to introduce a flag to enable logging of improper shutdown? It might help correlating this specific error message with cases where rsyslog is forcefully closed.

**Comment by rgerhards** [comment]
> @rgerhards pardon my ignorance (and a slight tangent), but is it possible to introduce a flag to enable logging of improper shutdown? It might help correlating this specific error message with cases where rsyslog is forcefully closed.

well... yes and no. We cannot do it during shutdown, because of the kill -9. But we could write a file that we delete on startup, so missing file on startup would indicate that the shutdown had problems. How does that sound?

**Comment by deoren** [comment]
> @rgerhards:
> well... yes and no. We cannot do it during shutdown, because of the kill -9. But we could write a file that we delete on startup, so missing file on startup would indicate that the shutdown had problems. How does that sound?

That sounds great to me and would achieve the same purpose, especially if rsyslog could check for the presence of that file and log a warning. Do you want me to spin off a separate request for that to keep this ticket focused just on the original issue?

**Comment by rgerhards** [comment]
2017-08-15 16:06 GMT+02:00 Deoren Moor <notifications@github.com>:

> @rgerhards <https://github.com/rgerhards>:
> well... yes and no. We cannot do it during shutdown, because of the kill
> -9. But we could write a file that we delete on startup, so missing file on
> startup would indicate that the shutdown had problems. How does that sound?
>
> That sounds great to me and would achieve the same purpose, especially if
> rsyslog could check for the presence of that file and log a warning. Do you
> want me to spin off a separate request for that to keep this ticket focused
> just on the original issue?
>
>
yupp, would be great!

Rainer

**Comment by deoren** [comment]
@rgerhards Created #1721. Thanks for offering to implement that. 

Assuming that the root issue is that rsyslog is just taking a while to cleanly shutdown, perhaps a usable workaround for systemd-based systems is to increase the wait time before letting systemd kill the rsyslog daemon.

I'm going to use this approach on my end to see if the problem reoccurs.

1. `nano /etc/systemd/system/rsyslog.service.d/20-increase-rsyslog-wait-time.conf`
1. Insert the following, substituting `300` with whatever is the desired wait time in seconds
<pre>
[Service]
TimeoutSec=300
</pre>
or
<pre>
[Service]
TimeoutStopSec=300
</pre>

Assuming that only the latter is used, this is my results from an Ubuntu 16.04 system using v8.29.0 from the official Ubuntu PPA:

`systemctl show rsyslog | grep -E '^Timeout'`

<pre>
TimeoutStartUSec=1min 30s
TimeoutStopUSec=5min
</pre>

References:

- [stackexchange - How to change systemd service timeout value?](https://unix.stackexchange.com/questions/227017/how-to-change-systemd-service-timeout-value)
- [systemd.service man page](https://www.freedesktop.org/software/systemd/man/systemd.service.html)
- [various timing parameters have an incorrect USec suffix](https://bugzilla.redhat.com/show_bug.cgi?id=1018335)

**Comment by davidelang** [comment]
Yes, increasing the wait time on shutdown to allow it to write everything is the 
correct answer.

Make sure that you don't have other dependencies that will trip you up (writing 
to a network drive and having those get shutdown while rsyslog is still trying 
to flush the queues)

**Comment by deoren** [comment]
@davidelang Good tips. In my case I'm writing the logs locally, but good to have here as a future reference for the next person that lands here from a search engine.

**Comment by deoren** [comment]
> Does issuing a `reboot` command result in systemd ignoring the `TimeoutStopSec` value?

I created a [question on stackexchange.com](https://unix.stackexchange.com/questions/386766/does-systemd-have-a-different-timeout-setting-when-rebooting-vs-normal-restart-o) to see if others know the answer. I'll post any relevant responses back here for others that come across this open ticket in the future.

**Comment by jay7x** [comment]
I have related question. What if one will set `queue.timeoutshutdown` to non-zero value? Will rsyslogd abort on write in the same way? Is it good idea to have `queue.timeoutshutdown` set to few seconds less than systemd' `TimeoutStopSec`?

**Comment by deoren** [comment]
>> Does issuing a `reboot` command result in systemd ignoring the `TimeoutStopSec` value?

> I created a [question on stackexchange.com](https://unix.stackexchange.com/questions/386766/does-systemd-have-a-different-timeout-setting-when-rebooting-vs-normal-restart-o) to see if others know the answer. I'll post any relevant responses back here for others that come across this open ticket in the future.

Some follow-up notes from that stackexchange thread that may be relevant:

* It is probably a good idea to enable persistent storage of systemd journal logs. Doing so should allow systemd to log any timeout warnings/errors related to the rsyslog daemon when rebooting that can be used to correlate corrupt disk queue errors with systemd forcefully terminating the daemon.
* systemd does not use a different timeout setting when rebooting the system vs normal retart of a service.

Direct quote from @sourcejedi on that thread:

> Looking at the service files on Debian 9, note that `syslog.socket` (supplied by systemd) has `DefaultDependencies=no`, but also  `Before=shutdown.target` and `Conflicts=shutdown.target`.  The latter line is commented `Don't allow logging until the very end`.  If you didn't have those last two [AND](https://unix.stackexchange.com/a/382239/29483) rsyslog.service had `DefaultDependencies=no`, the syslog daemon could be re-activated immediately, and get killed by `systemd-shutdown.service` (`systemd-shutdown`) instead.  `systemd-shutdown` uses the built-in default timeout between SIGTERM and SIGKILL, which I think is 90 seconds.

**Comment by deoren** [comment]
> @jay7x I have related question. What if one will set `queue.timeoutshutdown` to non-zero value? Will rsyslogd abort on write in the same way? Is it good idea to have `queue.timeoutshutdown` set to few seconds less than systemd' `TimeoutStopSec`

I found the documentation for the [`queue.timeoutshutdown` parameter](http://www.rsyslog.com/doc/v8-stable/rainerscript/queue_parameters.html), but I didn't get much out of it:

> `queue.timeoutshutdown` number number is timeout in ms (1000ms is 1sec!), **default 0 (indefinite)**

Does that mean that rsyslog will wait indefinitely for the queue to empty (send, save to disk) before stopping or something else?

**Comment by deoren** [comment]
I encountered this problem again with one of our receivers yesterday. This is with these settings present (as indicated previously):

<pre>
[Unit]

After=network.target

[Service]

TimeoutStopSec=240
</pre>

Here are the relevant messages from `/var/log/rsyslog.log`:

<pre>
2017-08-28T17:41:45.446804-05:00 sawmill2 rsyslogd: action 'ForwardToSawmill1' resumed (module 'omrelp') [v8.29.0 try http://www.rsyslog.com/e/2359 ]
2017-08-28T17:41:45.447521-05:00 sawmill2 rsyslogd: action 'ForwardToSawmill1' resumed (module 'omrelp') [v8.29.0 try http://www.rsyslog.com/e/2359 ]
2017-08-28T17:45:01.658850-05:00 sawmill2 rsyslogd: imfile: no files configured to be monitored - no input will be gathered [v8.29.0 try http://www.rsyslog.com/e/2212 ]
2017-08-28T17:45:01.659243-05:00 sawmill2 rsyslogd: rsyslogd's groupid changed to 103
2017-08-28T17:45:01.659426-05:00 sawmill2 rsyslogd: rsyslogd's userid changed to 101
2017-08-28T17:45:01.659632-05:00 sawmill2 rsyslogd: queue 'strm 0x20117c0', file '/var/spool/rsyslog/q_ForwardToSawmill1.00000001' opened for non-append write, but already contains 23140 bytes  [v8.29.0 try http://www.rsyslog.com/e/0 ]
2017-08-28T17:45:01.659812-05:00 sawmill2 rsyslogd:  [origin software="rsyslogd" swVersion="8.29.0" x-pid="877" x-info="http://www.rsyslog.com"] start
2017-08-28T17:45:01.712112-05:00 sawmill2 kernel: [   10.916973] systemd-journald[243]: Received request to flush runtime journal from PID 1
</pre>

The relevant bits from the systemd journal:

<pre>
Aug 28 17:32:08 sawmill2 rsyslogd[37879]: -- MARK --
Aug 28 17:41:45 sawmill2 rsyslogd[37879]: action 'ForwardToSawmill1' resumed (module 'omrelp') [v8.29.0 try http://www.rsyslog.com/e/2359 ]
Aug 28 17:41:45 sawmill2 rsyslogd[37879]: action 'ForwardToSawmill1' resumed (module 'omrelp') [v8.29.0 try http://www.rsyslog.com/e/2359 ]
Aug 28 17:44:38 sawmill2 rsyslogd[37879]:  [origin software="rsyslogd" swVersion="8.29.0" x-pid="37879" x-info="http://www.rsyslog.com"] exiting on signal 15.
Aug 28 17:44:38 sawmill2 systemd[1]: Stopping System Logging Service...
Aug 28 17:44:39 sawmill2 systemd[1]: Stopped System Logging Service.
-- Reboot --
Aug 28 17:45:01 sawmill2 systemd[1]: Starting System Logging Service...
Aug 28 17:45:01 sawmill2 rsyslogd[877]: imfile: no files configured to be monitored - no input will be gathered [v8.29.0 try http://www.rsyslog.com/e/2212 ]
Aug 28 17:45:01 sawmill2 rsyslogd[877]: rsyslogd's groupid changed to 103
Aug 28 17:45:01 sawmill2 rsyslogd[877]: rsyslogd's userid changed to 101
Aug 28 17:45:01 sawmill2 rsyslogd[877]: queue 'strm 0x20117c0', file '/var/spool/rsyslog/q_ForwardToSawmill1.00000001' opened for non-append write, but already contains 23140 bytes  [v8.29.
Aug 28 17:45:01 sawmill2 rsyslogd[877]:  [origin software="rsyslogd" swVersion="8.29.0" x-pid="877" x-info="http://www.rsyslog.com"] start
Aug 28 17:45:01 sawmill2 systemd[1]: Started System Logging Service.
</pre>

In our configuration, we have sawmill1 (our central rsyslog server) forwarding copies of messages on to sawmill2 and another node dedicated for testing in addition to a test graylog instance. Both sawmill2 and sawmill3 forward locally generated messages on to sawmill1 in an effort to have a complete "picture" of the log activity. Other than the messages forwarded into the graylog instance (where we use TCP forwarding), all nodes use RELP for forwarding/receiving messages and are running the latest official Ubuntu PPA-provided rsyslog v8.29.0.

**Comment by rgerhards** [comment]
I just noticed that the error message was unfortunately wrong (the predicate check was incorrect), See https://github.com/rsyslog/rsyslog/pull/1759

However, all said related to shutdown is still true and worth looking at it.

**Comment by rgerhards** [comment]
closed via https://github.com/rsyslog/rsyslog/pull/1759
