### ISSUE TITLE
rsyslog fails to write pid in pidfile

### ISSUE THREAD

**Issue by mrproper** [rsyslog/rsyslog#171]
After this fix: https://github.com/rsyslog/rsyslog/issues/169

The current ppa for ubuntu v8-stable 8.6.0.r1-0adiscon
When using drop privs it fails to write the actual pid into the pidfile

It successfully creates the pidfile but does not write the pid to the file:
$ sudo rm /var/run/rsyslogd.pid
$ sudo service rsyslog start
$ ps aux | grep rsyslog
syslog     862  2.0  0.1 147220  2548 ?        Ssl  23:24   0:00 rsyslogd
$ ls -lah /var/run/rsyslogd.pid
-rw-r--r-- 1 root root 0 Dec  3 23:24 /var/run/rsyslogd.pid

upstart can still determin its running:
$ sudo service rsyslog status
rsyslog start/running, process 862

**Comment by rgerhards** [comment]
The problem with removing on shutdown is that rsyslog no longer has permissons to do that. The alternative is to switch the pid file to a less stringent access control, but I doubt that is a really cool idea. Also, we could have a process with elevated privileges hang around all until rsyslog terminates, but this doesn't see so well either. So I don't see anything how we could improve that together with privilege drop.

**Comment by rgerhards** [comment]
closing as no good idea came in (and I also didn't get one).
