### ISSUE TITLE
imfile with multiple, consecutive, wildcards does not pick up new files in folders that don't already exist

### ISSUE THREAD

**Issue by dansteen** [rsyslog/rsyslog#1716]
Hi!

First of all, I wanted to thank you guys for the great work you do on rsyslog.  It's an amazing work, and only gets better with each release!

I did run into a quick problem.  I noticed that for imfile, if a path has multiple wildcards consecutively, new files will not be picked up in folders that don't already exist.   A concrete example will probably make this more clear:

given the following imfile stanza:
```
input( type="imfile" File="/var/log/*/*/application.log" Severity="info" Tag="nomad" addMetadata="on" ReadMode="0" PersistStateInterval="10000" ruleset="application.log")
```
if `/var/log/bob` does not exist when rsyslog is started, then `/var/log/bob/dave/application.log` will not be picked up when it is eventually created.

However, in the following case:
```
input( type="imfile" File="/var/log/*/sam/*/application.log" Severity="info" Tag="nomad" addMetadata="on" ReadMode="0" PersistStateInterval="10000" ruleset="application.log")
```
a file named `/var/log/bob/sam/dave/application.log` will be picked up regardless of whether `/var/log/bob` exists when rsyslog starts up.

A quick workaround I have found that works is to just put two consecutive slashes next to each other.   so instead of this `/var/log/*/*/application.log`,  do this: `/var/log/*//*/application.log`, and things will work.

Thanks!

**Comment by mostolog** [comment]
Have you tried /var/log/**/application.log ?

**Comment by josiahp** [comment]
I'm encountering this same issue (currently on 8.25.0 after trying 8.30.0). My early tests seemed to indicate that 8.25.0 did not have this issue, but it indeed seems to. 

@mostolog 's suggestion does not seem to alleviate the issue, and @dansteen 's workaround is not working in my case either. A restart of rsyslog causes all new files to be picked up immediately.

A new file in a directory that was already being watched seems to be picked up whereas a new file in a directory that previously was not being watched seems not to work. By "previously not being watched" I mean that no files were previously being updated, but that it was included in the wildcard specified in the imfile directive.

**Comment by mostolog** [comment]
After asking on lists, seems ** is unsupported.
Perhaps a sigHUP would do the trick.

Anyhow, due to our needs, we aren't longer using glob wilcards for multiple directories.

**Comment by rgerhards** [comment]
@alorbach we seem to have overlooked this one. I guess it might be relevant to your current imfile-related work.

**Comment by alorbach** [comment]
Looks indeed like a potential bug. Going to look into this later.

**Comment by rgerhards** [comment]
please change label to "bug" if you can confirm it. I need to document the workflow on that part, it's not yet 100% finalized.

**Comment by alorbach** [comment]
I confirm that this is a bug. 
If a directory exists before rsyslog is started that matches wildcard, it is not detected on startup. Only if the directory is created while rsyslog is running.

**Comment by rgerhards** [comment]
fixed by refactored imfile, but forgotten to close this issue.
