### ISSUE TITLE
[Improvement] It's impossible to guess by error message from which input large message was received

### ISSUE THREAD

**Issue by jay7x** [rsyslog/rsyslog#1718]
I've found those messages today in log:
```
rsyslogd[12306]: error: message received is at least 1429 byte larger than max msg size; message will be split starting at: " <149>2017-08-15T08:56:36.779453"  [v8.27.0]
rsyslogd[12306]: error: message received is at least 837 byte larger than max msg size; message will be split starting at: " <150>2017-08-15T08:56:43.599000"  [v8.27.0]
```

I have multiple inputs configured on this instance of rsyslog. So I'm unable to guess on which input rsyslog got those large messages. Is it possible to add input name to error message?

**Comment by PascalWithopf** [comment]
These messages probably come from imptcp.
I will change the message to include the module name.

**Comment by rgerhards** [comment]
well, it's already done ;-)

* https://github.com/rsyslog/rsyslog/pull/1678
* https://github.com/rsyslog/rsyslog/pull/1677

Part of 8.29.0.

**Comment by rgerhards** [comment]
sorry, my bad. I misread the request.

@PascalWithopf please go ahead, makes a lot of sense

**Comment by jay7x** [comment]
Hi @PascalWithopf! I've checked your MR. There is a bit more. I know those messages come from imptcp module. But I have 6 imptcp inputs on those machine. They have different names (name="xxx"). This is the name I'd like to see in error message to know which input to debug.

**Comment by PascalWithopf** [comment]
@jay7x I changed the message so it includes now at the beginning first the module name and then the parameter name.
