### ISSUE TITLE
RFE: Create a file at startup that could be used to detect improper shutdown

### ISSUE THREAD

**Issue by deoren** [rsyslog/rsyslog#1721]
If rsyslog finds this file at startup it could emit a warning that could help identify problematic situations such as corrupt disk queues (as noted on #1704).

**Comment by rgerhards** [comment]
@portante @mbiebl @Whissi I'd appreciate your feedback on this issue

**Comment by mbiebl** [comment]
I'm not sure if such a state-file would be super helpful. In most configurations, it's not an issue if rsyslog is forecfully killed. And if you have disk queue like in #1704 you can already detect inconsistencies and report them back to the user. Maybe a better solution is to simply improve the error message in #1704 ?

**Comment by rgerhards** [comment]
> Maybe a better solution is to simply improve the error message in #1704

Thanks, this sounds like an obvious and good suggestion ;-)

**Comment by deoren** [comment]
Improving the message is good, I completely agree with that point. However I think having rsyslog report improper shutdowns is useful for troubleshooting in general, not just regarding corrupt queue files.

**Comment by rgerhards** [comment]
I think we could improve a bit on this idea. Maybe that file should not just be a flag but provide very minimal but highly essential information on the startup and shutdown. So it could help nail down the exact cause of a problem if it occurs.

**Comment by rgerhards** [comment]
That's probably especially useful inside (docker) containers where it could provide us a means to get some state information in "unusual situations".
