### ISSUE TITLE
Logging issue with rsyslog 8.28

### ISSUE THREAD

**Issue by jay7x** [rsyslog/rsyslog#1735]
Hello! This is kind of JFYI-issue because we hit issue in production and downgraded from 8.28 to 8.27 for now (which works fine for us). So I have no debug logs nor in-depth details. But let me describe issue for future investigations anyway.

So we have php processes which are writing log messages (php `socket_sendto()`) into custom unix datagram socket (`imuxsock`) which is bound to dedicated ruleset. Messages in this ruleset are parsed by `mmnomalize` module. Then they are written to local log (`omfile`). Then they are sent to Kafka (`omkafka` with dynatopic).

Rsyslog is listening for system log messages forwarded by `journald` on `/run/systemd/journal/syslog` too. Messages are filtered by facility/programname and written to appropriate log files.

Once per 1-3 days few our nodes are just starting to fail on log socket write. When investigating I've found we have 8.28 on those nodes while other nodes have 8.27. According to `impstats` there was no messages hit into appropriate ruleset nor into action queues inside of that ruleset. Few system logs contains no messages during this time window as well (`/var/log/cron` e.g.). Some of them contains though (like `/var/log/messages`).

Rsyslog restart fixes this issue temporarily (for another 1-3 days). Unfortunately there was no time to investigate further because this is our production. So we have downgraded to 8.27 which works fine for us as I told before.

This remind me times of pre-8.26 when there was deadlock in rsyslog core. I can't provide any proofs so let's just keep this case in our mind for next time.
I can provide relevant config files though if needed (no special magic there though).

**Comment by rgerhards** [comment]
Hi, du you know if the issue persists with 8.31?

**Comment by jay7x** [comment]
Actually had no chance to check yet. There was change freeze. I'll try to setup testlab for latest rsyslog version in next month.
