### ISSUE TITLE
Unable to deliver log message > 128k when using RELP (rsyslog 8.27)

### ISSUE THREAD

**Issue by jay7x** [rsyslog/rsyslog#1741]
I've tried to increase rsyslog max message size from 128k to 256k this Friday and got broken RELP delivery. Checked librelp sources today. It seems librelp >= 1.2.14 have API call to set max message size but I can't find rsyslog is using it. So it seems rsyslog is unable to deliver messages larger than 128k using RELP. Am I right? Or is there any way RELP client and server have negotiate this during connection w/o explicit relpSrvSetMaxDataSize()/relpSessSetMaxDataSize() call?

```
#ifndef RELP_DFLT_MAX_DATA_SIZE
#	define RELP_DFLT_MAX_DATA_SIZE 128 * 1024 /* 128K should be sufficient for everything... */
#endif
```

**Comment by jay7x** [comment]
Actually I haven't found any relpSrvSetMaxDataSize()/relpSessSetMaxDataSize() in `omrelp` as well. `imrelp` can be configured via `maxdatasize` option. But I see no way to send message longer than RELP_DFLT_MAX_DATA_SIZE from `omrelp`. I'd propose to use something like `relpSrvSetMaxDataSize(glbl.GetMaxLine())` in `omrelp`.

**Comment by mostolog** [comment]
Good finding.

Due to Java stack traces we were forced to increase maxMessageSize to 128k in order to handle multiline properly.
I would add, however, that this lengthy messages should be avoided, as it is really TOO MUCH for a single line.

Have you found any alternatives?

**Comment by jay7x** [comment]
Our case is worse. We're receiving '|'-separated messages from API via imuxsock (128kb limit is applied here). Then I'm using mmnormalize to convert them to JSON. This cause message size growth. So when I'm trying to deliver such message to relay it appears truncated (so JSON is broken). That's why I've tried to increase max message size on relays.

**Comment by davidelang** [comment]
I seem to remember that there is a code limit involved around the 128k message size

something along the lines that you could go up to 128k with just config changes, but to go past 128k message size required a code change.

@rgerhards does this ring a bell with you?

**Comment by rgerhards** [comment]
It might really just require an API call... Anyone up to testing a patch if I craft it?

**Comment by rgerhards** [comment]
I did a **very quick** check, it might be that the relp client is currently not configurable inside librelp. That doesn't sound like it makes too much sense... I'll do further checking.

@deoren could you test a patch if it becomes available? Someone else?

**Comment by deoren** [comment]
@rgerhards Thanks for directing me here. I'll be happy to test whether it resolves the problem I noted on #1782. Are you able to easily generate test packages or would this just be manually applying a patch on top of the latest code in master and then building from source?

**Comment by deoren** [comment]
> @rgerhards I did a very quick check, it might be that the relp client is currently not configurable inside librelp. That doesn't sound like it makes too much sense... I'll do further checking.
>
> @deoren could you test a patch if it becomes available? Someone else?

Sure. 

Are you able to easily generate test packages or would this just be manually applying a patch on top of the latest code in master and then building from source?

**Comment by deoren** [comment]
@rgerhards In case my last comments indicated otherwise, I'm ready to build from source and test once you have code ready for testing.

**Comment by rgerhards** [comment]
sorry, I didn't make it into 8.31 due to the large number of things going now. Now trying for next release!

**Comment by rgerhards** [comment]
fixed in https://github.com/rsyslog/rsyslog/pull/2656
requires librelp 1.2.16
