### ISSUE TITLE
Is there a configuration parameter to control worker threads using only one TCP connection?

### ISSUE THREAD

**Issue by jipengzhu** [rsyslog/rsyslog#1742]
I found that rsyslog would establish two TCP connections to send data for load balancing in one worker thread , so the log messages recieved by tornado tcp server is out-of-order.

I want to keep the order of receiving logs in order to parse multiple lines of logs, such as XML, JSON, and Traceback error.

My english is poor, I hope you can understand what I mean.

**Comment by davidelang** [comment]
what is your config? did you set worker threads to a value larger than 1? do you 
have multiple places in your config that can deliver the messages? both of these 
can cause multiple connections to be opened.

There are many things that can cause messages to be processed out of order, 
eliminating all of them will cripple performance.

**Comment by jipengzhu** [comment]
Thanks for your reply.

the situation is here
1. The config file is only one and  [The default value of $ActionQueueWorkerThreads  is 1](http://www.rsyslog.com/doc/v8-stable/configuration/action/index.html)
2. [I set $ActionQueueWorkerThreads to be 1 and $ActionQueueWorkerThreadMinumumMessages to be 1000000](http://www.rsyslog.com/doc/v8-stable/concepts/queues.html)
3. I try to use $ActionQueueDequeueBatchSize, KeepAlive, RebindInterval, but doesn't take effect

config file is here
```
# Config Start
module(load="imfile" mode="inotify")
$WorkDirectory /var/spool/rsyslog

$MainMsgQueueDequeueBatchSize 30
$MainMsgQueueDequeueSlowdown 300
$ActionQueueWorkerThreads 1
$ActionQueueWorkerThreadMinumumMessages 1000000
$ActionQueueDequeueBatchSize 1

input(type="imfile"
      File="/home/dig/zhujipeng/res/seq.log"
      Tag="ls_d2dd5cded3104c048e0c1c1fdf1a47aa_test_seq"
      Severity="info"
      PersistStateInterval="20000"
      reopenOnTruncate="on"
      )

# $InputFilePollInterval 3

template (name="HaiZhiFormat__home_dig_zhujipeng_res_seq.log" type="string" string="<%pri%>%protocol-version% %timestamp:::date-rfc3339% %HOSTNAME% %app-name% %procid% %msgid% [ls_d2dd5cded3104c048e0c1c1fdf1a47aa@32473 tag=\"test_seq\"] %msg%\n")

# Send message to HaiZhi and discard it
if $programname == 'ls_d2dd5cded3104c048e0c1c1fdf1a47aa_test_seq' then action(type="omfwd" protocol="tcp" target="bd-003" port="5540" template="HaiZhiFormat__home_dig_zhujipeng_res_seq.log" KeepAlive="on" RebindInterval="-1")
if $programname == 'ls_d2dd5cded3104c048e0c1c1fdf1a47aa_test_seq' then ~
```

**Comment by jay7x** [comment]
I'd say it may happens because default number of threads for imptcp is 2. Actually I'm just guessing on top of documentation: http://www.rsyslog.com/doc/v8-stable/configuration/modules/imptcp.html

> Threads <number>
> Number of helper worker threads to process incoming messages. These threads are utilized to pull data off the network. On a busy system, additional helper threads (but not more than there are CPUs/Cores) can help improving performance. The default value is two, which means there is a default thread count of three (the main input thread plus two helpers). No more than 16 threads can be set (if tried to, rsyslog always resorts to 16).

So you may try to set `threads` value to 1 and check:
```module(load="imptcp" threads="1")```

**Comment by jay7x** [comment]
Sorry I've misread original issue and give totally unrelated answer.

**Comment by rgerhards** [comment]
Sorry for the late reply. Is this still of interest for you?

**Comment by jipengzhu** [comment]
yes 

this [article](http://blog.gerhards.net/2013/06/rsyslog-performance-main-and-action.html) tells me that  If multiple workers are concurrently active, messages will obviously be reordered, as the order now, among others, depends on thread scheduling order.

the [rsyslog document](http://www.rsyslog.com/doc/v8-stable/configuration/global/index.html) tells me that the default value of MainMsgQueueWorkerThreads is 1

<img width="733" alt="wx20171209-195647 2x" src="https://user-images.githubusercontent.com/29984300/33814365-afff9462-de64-11e7-9ad4-c6afd214112b.png">

but the [code](https://github.com/rsyslog/rsyslog/blob/master/runtime/rsconf.c) tells us that the default value of MainMsgQueueWorkerThreads is 2 (???)

<img width="651" alt="wx20171211-111924 2x" src="https://user-images.githubusercontent.com/29984300/33814447-2eacfa70-de65-11e7-8368-2c08283d9d74.png">

so we set MainMsgQueueWorkerThreads and ActionQueueWorkerThreads to 1 to make it resolved.

**Comment by rgerhards** [comment]
thanks again for alerting us. Doc fix is underway.
