### ISSUE TITLE
File read limit based on configuration

### ISSUE THREAD

**Issue by dpkkumar01** [rsyslog/rsyslog#1763]
Hi,
I am using rsyslog to read and transfer my CDR file. My application will write 500 record lines per second. 
I would like to read 100 records per second and push to Kafka from rsyslog. Is there any configuration at rsyslog for this?

Below is my flow,
Rsyslog---->Kafka---->Logstash---->Elasticsearch

Please let me know your valuable input on the same.

**Comment by jay7x** [comment]
AFAIK there is no rate-limit on {{imfile}}. But you can use following options on {{omkafka}} action as simple workaround:
action.execOnlyEveryNthTime="5"
action.execOnlyEveryNthTimeout="1" 
You may want to check http://www.rsyslog.com/doc/v8-stable/configuration/actions.html#general-action-parameters for details.

**Comment by dpkkumar01** [comment]
Thanks for your prompt response.

Actually i am collecting the data from multiple servers which is impacting my network bandwidth.

I want to restrict the outgoing data with respect to message or bandwidth.

Please suggest, If any other option  available for this.

**Comment by rgerhards** [comment]
@jay7x gave the workaround. Other than that, there is no specific rate limiting.

**Comment by rgerhards** [comment]
This looks like oversized queues.

**Comment by rgerhards** [comment]
pls do not post to old and closed issues - I suggest opening a new one if there is actually need
