### ISSUE TITLE
compare two varibles error

### ISSUE THREAD

**Issue by zhxiaom5** [rsyslog/rsyslog#1775]
the rsyslog config below
```
   action(type="mmjsonparse" )
   if $!request_byte == $!send_byte then {
       set $!finish_status1 = "finish";
   }
```
the request_bte and send_byte varible is json fileld.I can  debug the request_byte  and request_byte  they exit and equal.but in rsyslog they seems nevel equal,why?

**Comment by zhxiaom5** [comment]
my colleague test below works
   if (($!request_byte+0) == ($!send_byte+0)) then {
       set $!finish_status1 = "finish";
   }
so,maybe  type convert problem ?

**Comment by rgerhards** [comment]
thx for reporting and sorry for late action.

We should craft a test for this first. Anybody with the same problem let us know so that we can adjust the priority accordingly.

**Comment by rgerhards** [comment]
can you provide me one log message where this problem is seen? I would like to include that into a test. Also, I need to lognorm rulebase.
