### ISSUE TITLE
tcpflood test tool and gnutls

### ISSUE THREAD

**Issue by laerus** [rsyslog/rsyslog#1776]
I am trying to make tcpflood  to send messages to a rsyslog server with TCP and TLS, but i'm getting
`unexpected GnuTLS error -15 in nsdsel_gtls.c:178: An unexpected TLS packet was received.`
on the server.

Forwarding from the same machine with rsyslog and TCP over TLS with the same certificates 
passed to tcpflood works as expected. Also works with a simple python script with a socket connection wrapped with TLS.

tried with tcpflood both from current master and debian-stretch sources.

command:
`./tcpflood -t 10.0.3.16 -p 10514 -z thekey -Z thecert`

system:
```
rsyslogd 8.24.0, compiled with:
	PLATFORM:				x86_64-pc-linux-gnu
	PLATFORM (lsb_release -d):		
	FEATURE_REGEXP:				Yes
	GSSAPI Kerberos 5 support:		Yes
	FEATURE_DEBUG (debug build, slow code):	No
	32bit Atomic operations supported:	Yes
	64bit Atomic operations supported:	Yes
	memory allocator:			system default
	Runtime Instrumentation (slow code):	No
	uuid support:				Yes
	Number of Bits in RainerScript integers: 64
```

```
Linux logging-server 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u3 (2017-08-06) x86_64 GNU/Linux
```

note: tcpflood with UDP works as expected

**Comment by rgerhards** [comment]
Would you be willing to build and try out a test version of tcpflood if we create it?

**Comment by laerus** [comment]
yes @rgerhards !

**Comment by PascalWithopf** [comment]
@laerus the current version of tcpflood is enough.
Could you activate the parameter ```-L 10``` for tcpflood and provide us with the debug log. Then we will be able to see gnutls specific debug output.

**Comment by laerus** [comment]
hey @PascalWithopf `tcpflood` doesn't seem to know anything about the error on the server,
tested again with a new rsyslog server setup, again all other cases seem to work fine.

client:
```
root@flooder:~# ./tcpflood -t 10.0.3.16 -p 20514 -z flooder.key -Z flooder.crt -L 9
00001 open connections
starting run 1
Sending 1 messages.
00000001 messages sent
runtime: 0.000
00001 close connections
End of tcpflood Run
```

server:
```
logging-server liblogging-stdlog[106]: gnutls returned error on handshake: An unexpected TLS packet was received.  [v8.24.0 try http://www.rsyslog.com/e/2083 ]
```

**Comment by PascalWithopf** [comment]
@laerus I just noticed you are missing the parameter ```-Ttls```.
This parameter tells tcpflood to use tcp+tls, otherwise it only creates a tcp connection.
I confirmed that I'm getting error ```gnutls returned error on handshake: An unexpected TLS packet was received``` when I leave that parameter out.

**Comment by laerus** [comment]
@PascalWithopf that was it, i was following an older documentation, thank you for looking into this!

**Comment by rgerhards** [comment]
Can you point me to the doc so that we can update it? TIA

Sent from phone, thus brief.

Am 24.11.2017 16:17 schrieb "Kon Tsaki" <notifications@github.com>:

**Comment by laerus** [comment]
http://www.rsyslog.com/how-to-use-tcpflood/

**Comment by rgerhards** [comment]
@laerus Thx a lot, I'll see that we update it!
