### ISSUE TITLE
It seems imrelp is limited to single CPU core

### ISSUE THREAD

**Issue by jay7x** [rsyslog/rsyslog#1777]
As far as I see from current rsyslog 8.27 behaviour `imrelp` is always running on single thread. So it is limited to single CPU core. Am I right? Is it possible to run different `imrelp` inputs on different threads?

**Comment by rgerhards** [comment]
It's actually right, librelp is the limiting factor here. It would need to be enhanced. A solution would be to run multiple **instances** of **rsyslog** - sorry I have no better answer yet. I'll close the issue, but feel free to post to it. I can re-open if desired. Right now, I just don't see what rsyslog could do against it.

**Comment by jay7x** [comment]
Thank you for answer anyway! It'd be great to have imrelp thread per input or ruleset at least. I'll switch to imptcp for now on most loaded channels.

**Comment by jay7x** [comment]
Just found this in `top -H` output today (rsyslog 8.27):
```
25358 root      20   0 8779804 290948   4444 S 19.3  0.4   5:00.34 in:imrelp
25411 root      20   0 8779804 290948   4444 S  2.3  0.4   0:40.03 in:imrelp
25415 root      20   0 8779804 290948   4444 S  2.3  0.4   0:39.91 in:imrelp
25412 root      20   0 8779804 290948   4444 S  2.0  0.4   0:26.69 in:imrelp
25413 root      20   0 8779804 290948   4444 S  2.0  0.4   0:26.74 in:imrelp
25414 root      20   0 8779804 290948   4444 S  2.0  0.4   0:26.72 in:imrelp
```
Does it mean `imrelp` run some threads inside? Or is it some kind of (cosmetic) bug?
