### ISSUE TITLE
Can't fill rsyslog queue more than 70% of configured size

### ISSUE THREAD

**Issue by jay7x** [rsyslog/rsyslog#1778]
I have ruleset in rsyslog 8.27 with queue configured like below:
```
  queue.type="fixedArray"
  queue.size="250000"
  queue.dequeueBatchSize="8192"
  queue.workerThreads="4"
  queue.workerThreadMinimumMessages="50000"
  queue.spoolDirectory="/data/logs/rsyslog"
  queue.fileName="transit"
  queue.maxFileSize="16m"
  queue.maxDiskSpace="50G"
  queue.highWaterMark="200000"
  queue.lowWaterMark="150000"
  queue.checkpointInterval="25000"
  queue.saveOnShutdown="on"
```

But I've never seen more 175005 messages in this ruleset queue. I've changed queue size to 100000 and never seen more 70000 messages there. If I'll configure action queue instead it will works as expected. So no 70% limit for action queue configured by default. I guess it may be `queue.fulldelaymark` configured like this by default (haven't checked actual code yet though).

Side effect of this is DA-queue never get any message because `queue.highWaterMark` was configured more than 70% of in-memory queue size.

Could anyone please shed some light to this?

**Comment by rgerhards** [comment]
I assume that the messages arrive via some input that can throttle, e.g. TCP or files. In this case, rsyslog does not blindly build up the queue but rather make the sender throttle. This is controlled by the queue.lightdelaymark setting. I think the default is 70%. In that case, what you see is expected behaviour. Starting a DA queue is very expensive, so it is way better to throttle the sender then doing that.

**Comment by jay7x** [comment]
Great to know about `lightdelaymark` option meaning (it's empty here: http://www.rsyslog.com/doc/v8-stable/rainerscript/queue_parameters.html).

Is it possible to set `*mark` values to percentage in rsyslog config (like `queue.lightdelaymark="80%"`)?

**Comment by jay7x** [comment]
According to source code I see no way to disable `queue.lightDelayMark` easily. 
If I'll set it to `-1` it will be overriden to 70% of Q size by this code:
```
  if(pThis->iLightDlyMrk == -1 || pThis->iLightDlyMrk > pThis->iMaxQueueSize) {
    pThis->iLightDlyMrk = (pThis->iMaxQueueSize / 100) * 70;
    if(pThis->iLightDlyMrk == 0) {
      pThis->iLightDlyMrk =
        (pThis->iMaxQueueSize == 1) ? 1 : pThis->iMaxQueueSize - 1;
    }
  }
```
 If I'll set it to `0` it will pass check above but will hit into this condition (Q size >= 0):
```
    if(pThis->iQueueSize >= pThis->iLightDlyMrk) {
      DBGOPRINT((obj_t*) pThis, "doEnqSingleObject: LightDelay mark reached for light "
                "delayable message - blocking a bit.\n");
```

**Comment by mostolog** [comment]
We have found a related issue. Already asked on list but didn’t open an issue yet.

Seems there might be a bug when using DA queues, as rsyslog overrides lightDelay and fullDelay with some defults (50%/70% and 97? I can’t remember now), no matter what configuration we set.

Sadly this information (delay) is not printed by impstats, and seems to be only visible on debug.

**Comment by jay7x** [comment]
Actual problem I still see there is no way to disable `queue.lightDelayMark` when you have DA queue configured. Because there is no max messages count in this case. DA queue is about disk space not about message count. Only way is to give some unreal high amount here which looks ugly.

**Comment by rgerhards** [comment]
ah, I see. Doc issue again ;-) There **is** max message count. It is the same as with non-DA. Only the in-memory part of the queue is affected by it.

**Comment by jay7x** [comment]
Ah! So if I configure `queue.lightDelayMark` to be more than `queue.size` this kind of 'throttling' will be disabled, right?

**Comment by rgerhards** [comment]
I am not sure if you can configure it to be larger, but you can configure it equal in any case. And, yes, that would work.

**Comment by rgerhards** [comment]
Let me add: if it does not work, please report. Because that would definitely be a bug!

**Comment by jay7x** [comment]
Got it! Thank you very much for explanation. It's better to make it clearer in documentation though :)

**Comment by jay7x** [comment]
Well, tonight I've realised `lightDelayMark` affects DA queue too. So I've configured it to very big number to prevent inputs throttling.

There was ruleset with following settings:
```
  queue.type="fixedArray"
  queue.size="800000"
  queue.lightDelayMark="800000"
  queue.highWaterMark="750000"
  queue.lowWaterMark="650000"
  queue.workerThreads="8"
  queue.workerThreadMinimumMessages="80000"
  queue.dequeueBatchSize="20000"
  queue.checkpointInterval="25000"
  queue.spoolDirectory="/data/logs/rsyslog"
  queue.fileName="transit_nginx"
  queue.maxFileSize="16m"
  queue.maxDiskSpace="50G"
  queue.saveOnShutdown="on"
  queue.timeoutEnqueue="1"
```

We had inter-DC link maintenance so there was no connection to next relay. I've seen 0 messages in DA Q and full in-memory Q. So I've increased `lightDelayMark` to 800001. DA queue started to fill. But not more than 800000 messages. So I've increased `lightDelayMark` to 800000001 to workaround this. Then DA queue started to work as expected.

P.S. Still rsyslog 8.27

**Comment by rgerhards** [comment]
Going over this again, I think we can classify this issue as "doc-only" problem. @jay7x do you agree? If not, would would you like to see changed in functionality/config params?

**Comment by jay7x** [comment]
I'd like to have easy way to disable this behaviour w/o estimating how much messages my DA queue may contain. Can we use `lightDelayMark="0"` for this? As I understand this require small change in code (check my previous comment: https://github.com/rsyslog/rsyslog/issues/1778#issuecomment-330455390). May be I've missed something when looking on code though.

**Comment by rgerhards** [comment]
make sense, but I unfortunately was not able to do it in 8.32.
