### ISSUE TITLE
Metadata is not sent to remote server;

### ISSUE THREAD

**Issue by mvdpoel** [rsyslog/rsyslog#1780]
Hi,

I'm have a central log server which receives all logs.

On a client i forward the message using:
```
input(type="imfile"
      File="/var/log/s-service/*.log"
      Tag="s-service"
      Facility="local0"
      addMetadata="on"
)

if $programname == 's-service' then {
    action(
        type="omfwd"
        Target="0.0.0.0" (hidden ip)
        Port="514"
        Protocol="udp"
    )
    stop
}
```
on log server i filter them:

```
#$template TmplS, "/var/log/s-service/%$!metadata!filename%"
$template TmplS, "/var/log/s-service/s-combined.log"

if $programname == 's-service' then ?TmplS;RSYSLOG_DebugFormat
```

The commented line does not work, and when i use debugFormat i get an empty $!

I just want the log files to be mapped 1:1 to the central server, they all have unique filenames.

Any help would be greatly appreciated!

**Comment by rgerhards** [comment]
I think this was also discussed and resolved on the mailing list, so I close the issue. If the question is still open, let me know and I'll re-open.

**Comment by riturajb** [comment]
Please point to where in the mailing list this has been discussed. Facing same issue.

**Comment by davidelang** [comment]
what version are you running? you probably just need to update to the current version and test it.
