### ISSUE TITLE
rsyslogd crash __strlen_sse2 () at ../sysdeps/x86_64/strlen.S:31 on Centos 7

### ISSUE THREAD

**Issue by GioMac** [rsyslog/rsyslog#1793]
Program received signal SIGSEGV, Segmentation fault.
__strlen_sse2 () at ../sysdeps/x86_64/strlen.S:31
31		movdqu	(%rdi), %xmm1

can always reproduce on:
rsyslog-8.29.0-2.el7.x86_64 (from rsyslog repo)
rsyslog-8.24.0-12.el7.x86_64 (from centos repo)
rsyslog-8.24.0-12.el7.x86_64 (locally rebuilt from centos repo)

All RPM installation verified - md5sum OK
all packages updated, includes some non-Centos RPM's, no custom installs, only packages - no broken deps

CPU is haswell, tsx disabled due to intel bug (virtualized env)

abrt logs with core dump attached

[abrt.tar.gz](https://github.com/rsyslog/rsyslog/files/1332174/abrt.tar.gz)

**Comment by GioMac** [comment]
reason identified: postgresql module configuration became invalid - rsyslogd couldn't login to the server, but didn't throw any related warnings or errors.

**Comment by rgerhards** [comment]
was this via ompgsql or omlibdbi?

**Comment by GioMac** [comment]
ompgsql

reason: server was not available at the moment and subsystem refused connection as it supposed to do (TCP RST), bad thing is that id didn't throw any messages for that

**Comment by rgerhards** [comment]
thx a lot, will see that I check the ompgsql code.

**Comment by rgerhards** [comment]
ompgsql has been rewritten in the mean time: https://github.com/rsyslog/rsyslog/pull/2172

I assume that this also solves the issue here, and so I close it. Please give the new module a try. If the problem re-occurs, please open a new issue as the code in question is probably different. Thx!
