### ISSUE TITLE
rsyslogd:  Child XXX has terminated, reaped by main-loop.

### ISSUE THREAD

**Issue by ssapalski** [rsyslog/rsyslog#1794]
I see in the log many errors of the following kind:
`rsyslogd:  Child XXX has terminated, reaped by main-loop. [v8.29.0 try http://www.rsyslog.com/e/0 ]`

I've created a hopefully minimal rsyslog.conf which still produces this problem. My configuration is as follows:

**rsyslog.conf**
```
$ModLoad imuxsock
$ModLoad imklog

$SystemLogSocketFlowControl on
$AddUnixListenSocket /dev/log

$umask 0027

$FileOwner root
$FileGroup root

$template format,"%timestamp:::date-rfc3339% %fromhost% [%syslogseverity-text%]     %syslogtag% %msg%\n"

$outchannel messages,/var/log/messages,16384,/sbin/logrotate messages
*.* :omfile:$messages;format
```

**/sbin/logrotate**
```
#!/bin/bash

echo $$ >> /tmp/logrotate_pids

TOKEEP=4
FILENAME=$1

cd /var/log
[[ ! -e $FILENAME ]] && exit 0

DESTFILE=${FILENAME}.1.gz
for ((i=$((TOKEEP - 1)); i > 0; --i)); do
    [[ -e $FILENAME.$i.gz ]] && mv "$FILENAME"."$i".gz "$FILENAME"."$((i+1))".gz
done

MSG=$(grep "reaped by main-loop" "$FILENAME")
if [ $? -eq 0 ]; then
    echo "$MSG" > /tmp/logrotate_reaped
fi

gzip -c "$FILENAME" > "$DESTFILE"
echo "" > $FILENAME
```

**trigger**
```
#!/bin/bash

rm -f /tmp/logrotate_pids
rm -f /tmp/logrotate_reaped

i=0
while [ 0 ]
do
    logger "test message, test message, test message, test message ($i)"
    [[ -e /tmp/logrotate_reaped ]] && break
    i=$((i+1))
done
```

**rsyslog version**
```
rsyslogd 8.29.0, compiled with:
    PLATFORM:                           mips64-octeon2-linux-gnu
    PLATFORM (lsb_release -d):
    FEATURE_REGEXP:                             Yes
    GSSAPI Kerberos 5 support:          No
    FEATURE_DEBUG (debug build, slow code):     No
    32bit Atomic operations supported:  No
    64bit Atomic operations supported:  No
    memory allocator:                   system default
    Runtime Instrumentation (slow code):        No
    uuid support:                               Yes
    Number of Bits in RainerScript integers: 64
```

**How to reproduce?**
1. Copy **logrotate** to /sbin/logrotate and make it executable
2. Copy **trigger** to wherever and make it executable
3. Restart rsyslog with my **rsyslog.conf**
4. Execute script **trigger**

The script 'trigger' will stop after the issue was reproduced. This script fills the log with messages to trigger the logrotate script by rsyslog. The logrotate script writes it's own PID continuously into /tmp/logrotate_pids and creates the file /tmp/logrotate_reaped if during log rotation the error "reaped by main-loop" was found in the log. The presence of /tmp/logrotate_reaped stops the trigger script.

The process which gets reaped is the logrotate process as it is visible via the recorded PID's in /tmp/logrotate_pids. Well, maybe that's a configuration issue and I have to setup log rotation differently or is that a bug in rsyslog?

**Comment by ssapalski** [comment]
@rgerhards 
@davidelang 

Can you please help with this issue or is there more information needed?
Did you have time to reproduce this issue and state if this is a configuration problem on my side or a bug in rsyslog?

**Comment by ssapalski** [comment]
@janmejay 

I see that you are the original author of the introduced error message, this was merged to rsyslog with pull request #1155 and the specific commit introducing this change was 12081b688b21d8f0e9208f78ae5a1420acc87108

What was your intention of this error message? To my understanding it shall report if a process which should get reaped by omprog, was reaped by the main-loop?

In my case I'm not using omprog and the logrotate process which I start must be reaped by the main-loop to avoid having zombies hanging around. This is my current understanding, so this error message might be misleading in some cases.

What is your view?

**Comment by janmejay** [comment]
The intention was to let user know that a process died. It is helpful because it attracts user's attention to a potential problem. Process death is an important event that doesn't occur frequently during steady processing. When it does, it often indicates a problem. Sometimes people write scripts that do not use non-zero exit code, but exit is still an unexpected circumstance and this message can help identify that situation. 

It doesn't have much to do with omprog really. Because main-loop reaps any children that are reapable, it may have come from many different kind of situations (dead omprog child is just one of the potential sources), the message in conjunction with module-level message of the child disappearing makes diagnosis easy.

**Comment by ssapalski** [comment]
Thanks for your prompt comment.
In my case I do not see a potential problem but it is still being reported as problem, log level => error.

From my configuration you can see that I rotate the log after it's file size exceeded 16384 bytes. If this event happens, rsyslog will spawn a shell script which does the log rotation. This script of course will terminate as soon as log rotation is finished and thus will be reaped by the main-loop.

Do you see anything which is wrong in my setup and how I could avoid seeing this error messages in the log for the logrotate process?

**Comment by janmejay** [comment]
You may want to add a filter:
`
if msg contains "reaped by main-loop" then stop
`
which will drop this message (specifically), the filter can be made more specific with regex, if necessary.

Or you may want to replace stop with another file, so all these restart messages go to /var/log/child-process-restart.log.

Alternatively, you can use logrotate daemon, which can rotate the log file and issue HUP to rsyslog, which will make it re-open log-file handles (this will not involve a child process at all, hence no child-reaped noise).

**Comment by ssapalski** [comment]
This sounds like a workaround to me but not a proper solution.

Just dropping this message hides situations where it would be useful to see if a child terminated but wasn't expected. In my case it is expected that the child terminates and isn't a problem.

Redirecting these messages isn't a proper solution as well from my point of view for the already above stated reason. There might be children where it can be considered an error if they terminate and others not.

Using cron is no solution for me, I need to control log rotation in dependence of the file size to trigger log rotation as soon as it is needed and not on dependence of a timed trigger.

I think rsyslog lacks proper child management where it can be decided for all child processes spawned by rsyslog if termination is expected and not worth a log message (or maybe a message with log level => info/debug) or if termination is unexpected and needs to be logged as an error.

**Comment by rgerhards** [comment]
We should change the message to informational, because that's what it is. I
can do so this week.

Note: this is not an error condition but a cleanup for things exactly of
what you do.

Rainer

Sent from phone, thus brief.

Am 09.10.2017 12:32 schrieb "Samuel Sapalski" <notifications@github.com>:

**Comment by ssapalski** [comment]
Many thanks, I will wait for the fix.

**Comment by davidelang** [comment]
the problem is that rsyslog doesn't really know when this is a big problem as 
opposed to expected operation, it all depends on what you are doing at the time.

reducing it from an error to a lower severity is a good move.

**Comment by gjmilne** [comment]
It seems reasonable to log a message when the (rotation) script exits with a non-zero exit code. However, when exiting with an exit code of zero (i.e. success) I do not think it should log anything. After all, no error has occurred and the system is behaving as you would expect, so why log anything?

**Comment by leoheck** [comment]
I agree, how to avoid this?
``` 
Nov 13 14:45:23 homebase liblogging-stdlog[17854]: Child 18371 has terminated, reaped by main-loop. [v8.24.0 try http://www.rsyslog.com/e/0 ]
Nov 13 14:45:28 homebase liblogging-stdlog[17854]: Child 18556 has terminated, reaped by main-loop. [v8.24.0 try http://www.rsyslog.com/e/0 ]
Nov 13 14:45:33 homebase liblogging-stdlog[17854]: Child 18599 has terminated, reaped by main-loop. [v8.24.0 try http://www.rsyslog.com/e/0 ]
Nov 13 14:45:38 homebase liblogging-stdlog[17854]: Child 18614 has terminated, reaped by main-loop. [v8.24.0 try http://www.rsyslog.com/e/0 ]
Nov 13 14:45:43 homebase liblogging-stdlog[17854]: Child 18630 has terminated, reaped by main-loop. [v8.24.0 try http://www.rsyslog.com/e/0 ]
Nov 13 14:45:48 homebase liblogging-stdlog[17854]: Child 18645 has terminated, reaped by main-loop. [v8.24.0 try http://www.rsyslog.com/e/0 ]
Nov 13 14:45:52 homebase liblogging-stdlog[17854]: Child 18660 has terminated, reaped by main-loop. [v8.24.0 try http://www.rsyslog.com/e/0 ]
Nov 13 14:45:58 homebase liblogging-stdlog[17854]: Child 18675 has terminated, reaped by main-loop. [v8.24.0 try http://www.rsyslog.com/e/0 ]
Nov 13 14:46:03 homebase liblogging-stdlog[17854]: Child 18690 has terminated, reaped by main-loop. [v8.24.0 try http://www.rsyslog.com/e/0 ]
Nov 13 14:46:08 homebase liblogging-stdlog[17854]: Child 18761 has terminated, reaped by main-loop. [v8.24.0 try http://www.rsyslog.com/e/0 ]
Nov 13 14:46:13 homebase liblogging-stdlog[17854]: Child 18776 has terminated, reaped by main-loop. [v8.24.0 try http://www.rsyslog.com/e/0 ]
Nov 13 14:46:18 homebase liblogging-stdlog[17854]: Child 18791 has terminated, reaped by main-loop. [v8.24.0 try http://www.rsyslog.com/e/0 ]
Nov 13 14:46:23 homebase liblogging-stdlog[17854]: Child 18806 has terminated, reaped by main-loop. [v8.24.0 try http://www.rsyslog.com/e/0 ]
Nov 13 14:46:28 homebase liblogging-stdlog[17854]: Child 18825 has terminated, reaped by main-loop. [v8.24.0 try http://www.rsyslog.com/e/0 ]
Nov 13 14:46:33 homebase liblogging-stdlog[17854]: Child 18840 has terminated, reaped by main-loop. [v8.24.0 try http://www.rsyslog.com/e/0 ]
Nov 13 14:46:38 homebase liblogging-stdlog[17854]: Child 18855 has terminated, reaped by main-loop. [v8.24.0 try http://www.rsyslog.com/e/0 ]
Nov 13 14:46:43 homebase liblogging-stdlog[17854]: Child 18870 has terminated, reaped by main-loop. [v8.24.0 try http://www.rsyslog.com/e/0 ]
Nov 13 14:46:47 homebase liblogging-stdlog[17854]: Child 18885 has terminated, reaped by main-loop. [v8.24.0 try http://www.rsyslog.com/e/0 ]
Nov 13 14:46:53 homebase liblogging-stdlog[17854]: Child 18900 has terminated, reaped by main-loop. [v8.24.0 try http://www.rsyslog.com/e/0 ]
Nov 13 14:46:58 homebase liblogging-stdlog[17854]: Child 18915 has terminated, reaped by main-loop. [v8.24.0 try http://www.rsyslog.com/e/0 ]
Nov 13 14:47:03 homebase liblogging-stdlog[17854]: Child 18930 has terminated, reaped by main-loop. [v8.24.0 try http://www.rsyslog.com/e/0 ]
Nov 13 14:47:08 homebase liblogging-stdlog[17854]: Child 18979 has terminated, reaped by main-loop. [v8.24.0 try http://www.rsyslog.com/e/0 ]
```

**Comment by gjmilne** [comment]
We need to remember that this message is not very that useful. It tells us the id of a process. It does not help us determine which of our (many?) rotation scripts is exiting. If we knew the name of the script/command we might be better able to diagnose/fix a problem. Also, a script that exits normally (i.e. exit code zero) is working as expected so why log normal operation.

In my case, we rotate log files every 600,000 bytes. It's an embedded system. We find it annoying that we get one of these messages at the top of newest log file after the rotation script finishes. It isn't helpful to us, nor our users. We end up with around 50 of these log files in our rotation pool and every one of them, except for the very first, has one of these reaping messages as its first line.
