### ISSUE TITLE
rsyslog stops writing logs after rotation

### ISSUE THREAD

**Issue by ralberto** [rsyslog/rsyslog#1795]
I'm configuring rsyslog to read log messages from /run/systemd/journal/syslog socket and write then to a file. With that in mind, I've configured systemd-journald to forward messages to syslog and configured the service with a syslog identifier, i.e.:

/etc/systemd/system/&lt;service identifier>.service.d/logging.conf
<pre>
    SyslogIdentifier= &lt;service identifier>
    SyslogFacility=local0
</pre>
After that, I've configured rsyslog to write messages from that &lt;service identifier> into the specified file, i.e:

/etc/rsyslog.conf
<pre>
...
$addUnixListenSocket /run/systemd/journal/syslog

if $programname == '&lt;service identifier>'  then {
        /var/log/service identifier/<service identifier>.log
        stop
}
..
</pre>

Things work a expected nicely, however after log rotation rsyslog stops writing. Here's the relevant log rotation configuration:
<pre>
{
  …
  postrotate
        /bin/kill -HUP `cat /var/run/syslogd.pid 2> /dev/null` 2> /dev/null || true  #No logs after rotation
  endscript
}
</pre>

Doing a full rsyslog restart solves the problem. (i.e.     /bin/systemctl restart rsyslog 2> /dev/null || true)

Does rsyslog requires a full restart in this scenario or it's a bug? What are the drawbacks of doing a full restart? Will I lose messages considering that I'm using a Disk-Assisted Memory Queue?

Thanks.

**Comment by davidelang** [comment]
you don't want to do a full restart because that can take enough time that you 
loose messages

you show us the postrotate block, what is the rest of the log rotation config?

also, double check that the .pid file you are using is the one that rsyslog is 
creating in your config.
