### ISSUE TITLE
details of impstats module fields made in elasticsearch

### ISSUE THREAD

**Issue by luvpreetsingh** [rsyslog/rsyslog#1796]
I am using this Impstats module to monitor the Rsyslog queues.

I have read the docs, http://www.rsyslog.com/doc/v8-stable/configuration/modules/impstats.html 

and this article on it, http://www.rsyslog.com/how-to-use-impstats/

That explains pretty much the working of this module.

But I am seeing more stuff than documented.

I am storing the stats in Elasticsearch database.

Here are all the fields which are created, 

![screenshot from 2017-09-27 13-17-58](https://user-images.githubusercontent.com/23127804/30901904-243ab8e8-a387-11e7-83de-d92ae25d0bd5.png)

As you can see all the fields being made, can you explain what those mean? 

I know the meaning of 
  
    discarded.nf, discarded.full, submitted, enqueued, processed, origin, name, maxqsize.

Please explain, 
  
    called.recvmmsg
    called.recvmsg
    failed.checkConn
    failed.es
    failed.http
    majflt
    maxrss
    minflt
    nivcsw
    nvcsw
    outblock
    stime
    utime
    ratelimit.discarded
    ratelimit.numratelimiters

these fields.

**Comment by davidelang** [comment]
they are all various stats about the system. fields can be created by any module 
that's loaded, so different things will show to different people

below are my educated guesses

> Please explain,
>
>    called.recvmmsg

thevnumber of times that recvmmsg was called (the ability to fetch multiple UDP 
messages in a single function call, relatively new)

>    called.recvmsg

the number of times recvmsg was called (single message version of the above)

>    failed.checkConn

the number of times a check of the connection failed??

>    failed.es

count of failed messages sent to ES

>    failed.http

count of failed http calls(possibly calls to ES??)

>    majflt
>    maxrss
>    minflt
>    nivcsw
>    nvcsw
>    outblock
>    stime
>    utime

I thinkthese are all performance stats, I would just google these with linux and 
see if that produces a good explination

>    ratelimit.discarded

the number of times that a message was thrown away as the result of a 
ratelimit

>    ratelimit.numratelimiters

the number of ratelimits that are being tracked.

**Comment by jay7x** [comment]
There is some info on site: http://www.rsyslog.com/tag/counter/

**Comment by rgerhards** [comment]
For everyone reaching this via google, I would like to point out that the impstats doc http://www.rsyslog.com/doc/v8-stable/configuration/modules/impstats.html contains the link to the individual stats counters. These are separate pages because of the volume of information. I don't give a direct link here as that link can change, whereas the doc link remains stable.
