### ISSUE TITLE
HTTP output module

### ISSUE THREAD

**Issue by imilo** [rsyslog/rsyslog#1797]
Unfortunately I can't find a general HTTP output module for Rsyslog. Do you have plans to implement it?

Use case - nowadays more and more custom (micro)services appear, often with a HTTP handler - it would be much easier to send data directly with a built-in module and acknowledging successful receiving from server with some response code like **200**.

Probably I could use **omfwd** with a template which includes some basic HTTP headers, but then there is no chance to know about success on a higher level.

**Comment by davidelang** [comment]
> Unfortunately I can't find a general HTTP output module for Rsyslog. Do you have plans to implement it?

not that I know of, but contributions are welcome :-)

I think the problem is the hidden complexity that would show up once you tried 
to make such a module work with a bunch of services.

you also are going to need persistant connections or something like that or you 
will cripple your performance with all the reconnects.

In a high performance environment, it's going to be ugly enough sending the 
messages one at a time.

**Comment by imilo** [comment]
Thanks for explaining. What about **omelasticsearch**? I see it uses `curl_easy_perform` from the imported library - isn't it almost the same thing?

**Comment by rgerhards** [comment]
Can you specify what exactly the module should do and which parameters it
should support? Without that, I think it is too vague to discuss what is
similar and what not.

Rainer

Am 01.10.2017 15:02 schrieb "imilo" <notifications@github.com>:

**Comment by imilo** [comment]
For example:
```
action(
    type="omhttp"
    ssl="false"
    server="example.com"
    serverport="8080"
    uri="/rsyslog"
    template="httpTemplate"
)
```
.. this sends an event in a POST request to the `http://example.com:8080/rsyslog` -> checks a success; if OK -> sends next event.

But these are just thoughts. I don't know whether **omelasticsearch** holds the connection open, whether it checks a response, etc. If you really say that HTTP output would be very inefficient, and **omelasticsearch** is created somehow in a different way, then OK.

**Comment by rgerhards** [comment]
Do you have any specific need or is this just a general idea?

**Comment by imilo** [comment]
I need to process JSON logs with a custom service, rsyslog easily could take file reading and sending tasks. HTTP handler is the easiest to implement on a server-side, TCP output is not reliable

**Comment by rgerhards** [comment]
ah, OK. Would you be willing to create  a new module omhttp? This could simply be done by
a) copying omelasticsearch
b) removing everything you do not need
c) doing some adjustments for the post
Once I have this PR, I could direct you on how to integrate it into the build system

**Comment by imilo** [comment]
Not a **C** expert, sorry

**Comment by rgerhards** [comment]
ok, then we need to see some interest in the community to have this feature -- the TODO list is very long. Alternatively, if this is for a business case you could talk to your company if they want to fund development.

Sorry I have no better answer, but as I said, the TODO list is very long and we need to focus on the most important issues.

**Comment by rgerhards** [comment]
Does this maybe help? https://github.com/rsyslog/rsyslog/issues/1977

**Comment by richm** [comment]
@ctramnitz 

> My main goal is to execute this against AWS API Gateway.

Would that allow you to send log records to S3 and/or CloudWatch?
