### ISSUE TITLE
invalid omkafka confParam value causes infinite actionDoRetry loop

### ISSUE THREAD

**Issue by JPvRiel** [rsyslog/rsyslog#1806]
If an invalid value is provided to `confParam`, such as `"security.protocol=lies"` (invalid), then rsyslog actions run in an infinite loop retrying.

A misconfiguration shouldn't cause rsyslog (or the underlying libdrkafka library) to consume memory.

Debug output that shows an infinite actionDoRetry loop when an invalid config parameter is supplied:

```
5544.078420976:main thread    : modules.c: module builtin:omfwd of type 1 being loaded (keepType=0).
...
5019.877144013:main Q:Reg/w0  : omkafka.c: omkafka: setting custom configuration parameter: security.protocol:lies
5019.877145291:main Q:Reg/w0  : omkafka.c: omkafka: tryResume returned -1000
5019.877146260:main Q:Reg/w0  : ../action.c: actionDoRetry: action 1 action->tryResume returned -1000
5019.877147200:main Q:Reg/w0  : ../action.c: actionDoRetry: action 1 enter loop, iRetries=0, ResumeInRow 1
5019.877151053:main Q:Reg/w0  : omkafka.c: omkafka: setting custom configuration parameter: batch.num.messages:1
5019.877152639:main Q:Reg/w0  : omkafka.c: omkafka: setting custom configuration parameter: queue.buffering.max.ms:100
5019.877154070:main Q:Reg/w0  : omkafka.c: omkafka: setting custom configuration parameter: security.protocol:lies
5019.877155367:main Q:Reg/w0  : omkafka.c: omkafka: tryResume returned -1000
...
```

The above output ends abruptly and rsyslog exits with code 137 (128 + 9) due to SIGKILL because it either runs into a memory limit or is selected by the out of memory manager on Linux.

Context/config snippets

```
...
ruleset(name="output") {
  call fwd_kafka
}
...
module(load="omkafka")
ruleset(name="fwd_kafka")
{
  action(
    type="omkafka"
    broker=["test_kafka:9093"]
    confParam=["batch.num.messages=1", "queue.buffering.max.ms=100", "security.protocol=lies", "ssl.ca.location=/usr/local/etc/pki/test/test_ca.cert.pem", "ssl.key.location=/usr/local/etc/pki/test/test_syslog_server.key.pem", "ssl.certificate.location=/usr/local/etc/pki/test/test_syslog_server.cert.pem"]
    topic="test_syslog"
    dynatopic="off"
    partitions.auto="on"
    resubmitOnFailure="on"
    keepFailedMessages="on"
    failedMsgFile="/var/lib/rsyslog/kafka_failed.msg"
  )
}
```
I've attempted for clone the rsyslog project, but getting going with valgrind and the build dependencies is a bit beyond my time at the moment.

https://github.com/rsyslog/rsyslog/issues/1792#issuecomment-334195397 is where I first commented on this in relation to https://github.com/rsyslog/rsyslog/issues/1792.  `"security.protocol=ssl"` (valid) now works fine.

OS: CentOS 7. 
Version: 8.29.

Tested in a docker container with rsyslog-kafka and adisconbuild-librdkafka1 installed via http://rpms.adiscon.com/v8-stable/rsyslog.repo

**Comment by rgerhards** [comment]
I would suggest that when librdkafka errs out on a config parameter, the action disables itself. While in theory this could be healing, in practice this seems highly unlikely. This is done simply by returning RS_RET_DISABLE_ACTION (see omsnmp).

As an alternative, the retry period should probably prolonged (no core support exists for that, so it needs to be handled by the module via sleep() or such). Or we find the actual memleak (and report it to librdkafka, if it is there).

For simplicity, I would suggest to disable the action.
