### ISSUE TITLE
imkafka: Add reconnect /retry logic

### ISSUE THREAD

**Issue by alorbach** [rsyslog/rsyslog#1813]
Check code for connection retry logic. Currently it seems like imkafka input does not retry to connect to kafka server if unavailable.

**Comment by rgerhards** [comment]
@alorbach is this still open?

**Comment by alorbach** [comment]
As an enhancement yes it's still open.

**Comment by alorbach** [comment]
Problem could not be produced anymore. 
Closing issue for now.
