### ISSUE TITLE
omfile - create file path hierarchy splitting hostname

### ISSUE THREAD

**Issue by ltagliamonte** [rsyslog/rsyslog#1815]
Hi All,
I'm reading logline from Kafka using imkafka and I'm able to save them on file.
An example of the save logline is:
```
Oct  2 22:44:00  my-domain-staging3-worker-i-0a646fbe35 serverID:i-0a646fbe35 msg....
```
As showed the sent server hostname looks like <myDomain>-<environment>-<serverType>-<serverID>.
Where environment can be: stg,stg2.. etc.; serverType: api,worker.. etc and server ID is a unique ID.

I'm trying to configure a receiver rsyslog server that is automatically able to split the hostname and write the log file in a hierarchy structure:

<environment >/
-----------------< serverType >/
----------------------------------<serverID>/
---------------------------------------------- logFile

I read a couple of blog/docs and the only thing I was able to find is a multi-config setup like:

if ($fromhost contains ’something′ ) then {}
if ($fromhost contains ’someting′) then {}

Since my environment is dynamic and <serverTypes>  and <environment> get created/destroyed I was looking for a way to split the hostname on the fly and implement the hierarchy structure illustrated before.

Because I'm reading from Kafka do I need to use mmnormalize to extract the fields and use them?
Is there any easier way to do this? Can somebody point me to a doc/example?

**Comment by davidelang** [comment]
mmnormalize can parse anything

you can then use dynafile to use a template to create a filename. I just replied 
on the mailing list, please close this issue and we can discuss it there.
