### ISSUE TITLE
RepeatedMsgReduction does not work for kernel messages?

### ISSUE THREAD

**Issue by mgrimes123** [rsyslog/rsyslog#1821]
I've got a few systems that periodically get hammered by mpt2sas log_info messages.  These may well indicate a problem to resolve, but the spamming of the log does not help.   I have the global RepeatedMsgReduction enabled in my rsyslog.conf.   I've confirmed the multiple message function is enabled via a manual repeated logger call.

If imklog does not support the global RepeatedMsgReduction setting, could support for it be added?

Tested on CentOS 7.4.

**Comment by rgerhards** [comment]
Well, the message needs to be identical to catch that old-style repeated message detection.

**Comment by mgrimes123** [comment]
Yes, forcing the same message from a script gets trapped by the reduction handler.

Below is a sample output from the kernel:
<4> 2017 Oct  3 18:03:49.241708 MCG-HangTest kernel: mpt2sas_cm0: log_info(0x31120b10): originator(PL), code(0x12), sub_code(0x0b10)
<4> 2017 Oct  3 18:03:49.241708 MCG-HangTest kernel: mpt2sas_cm0: log_info(0x31120b10): originator(PL), code(0x12), sub_code(0x0b10)
<4> 2017 Oct  3 18:03:49.241709 MCG-HangTest kernel: mpt2sas_cm0: log_info(0x31120b10): originator(PL), code(0x12), sub_code(0x0b10)
<4> 2017 Oct  3 18:03:49.241709 MCG-HangTest kernel: mpt2sas_cm0: log_info(0x31120b10): originator(PL), code(0x12), sub_code(0x0b10)
<4> 2017 Oct  3 18:03:49.241710 MCG-HangTest kernel: mpt2sas_cm0: log_info(0x31120b10): originator(PL), code(0x12), sub_code(0x0b10)
<4> 2017 Oct  3 18:03:49.241710 MCG-HangTest kernel: mpt2sas_cm0: log_info(0x31120b10): originator(PL), code(0x12), sub_code(0x0b10)
<4> 2017 Oct  3 18:03:49.241711 MCG-HangTest kernel: mpt2sas_cm0: log_info(0x31120b10): originator(PL), code(0x12), sub_code(0x0b10)
<4> 2017 Oct  3 18:03:49.241711 MCG-HangTest kernel: mpt2sas_cm0: log_info(0x31120b10): originator(PL), code(0x12), sub_code(0x0b10)
<4> 2017 Oct  3 18:03:49.241716 MCG-HangTest kernel: mpt2sas_cm0: log_info(0x31120b10): originator(PL), code(0x12), sub_code(0x0b10)
<4> 2017 Oct  3 18:03:49.241716 MCG-HangTest kernel: mpt2sas_cm0: log_info(0x31120b10): originator(PL), code(0x12), sub_code(0x0b10)
<4> 2017 Oct  3 18:03:49.241717 MCG-HangTest kernel: mpt2sas_cm0: log_info(0x31120b10): originator(PL), code(0x12), sub_code(0x0b10)
<4> 2017 Oct  3 18:03:49.241717 MCG-HangTest kernel: mpt2sas_cm0: log_info(0x31120b10): originator(PL), code(0x12), sub_code(0x0b10)
<4> 2017 Oct  3 18:03:49.241727 MCG-HangTest kernel: mpt2sas_cm0: log_info(0x31120b10): originator(PL), code(0x12), sub_code(0x0b10)
<4> 2017 Oct  3 18:03:49.241727 MCG-HangTest kernel: mpt2sas_cm0: log_info(0x31120b10): originator(PL), code(0x12), sub_code(0x0b10)

Here is the template I use (let me know if you would like to see the entire conf file):
template(name="MCGFormat" type="list") {
    constant(value="<")
    property(name="syslogseverity")
    constant(value=">")
    constant(value=" ")
    property(name="timestamp" dateformat="rfc3339" position.from="1" position.to="4")
    constant(value=" ")
    property(name="timestamp" dateformat="rfc3164" position.from="1" position.to="15")
    property(name="timestamp" dateformat="rfc3339" position.from="20" position.to="26")
    constant(value=" ")
    property(name="hostname")
    constant(value=" ")
    property(name="syslogtag" position.from="1" position.to="32")
    constant(value=" ")
    property(name="msg")
    constant(value="\n")
}

**Comment by davidelang** [comment]
show sample messages from the kernel that you think should be combined.
k

**Comment by mgrimes123** [comment]
rgerhards said 'old-style repeated message reduction'.  Is there a 'new style' I should be using?

**Comment by davidelang** [comment]
No, the message reduction is a legacy thing from when logs were small and people 
looked through them on one server. under those conditions, "last message 
repeated X times" has some meaning.

in modern networks, you have the logs from many machines combined into one feed, 
and it's so many thousands of lines that having a person look at it raw makes no 
sense.

As a result, matching up "last line repeated X times" with whatever line was 
actually repeated is hard to impossible. It's far better to log the logs as-is 
and have the log server detect the duplicates.

David Lang

**Comment by mgrimes123** [comment]
Thanks for your opinion, but I'm trying to understand why the feature does not appear work for kernel messages.

**Comment by rgerhards** [comment]
which module do you use to read the kernel messages?

**Comment by mgrimes123** [comment]
imklog

**Comment by mgrimes123** [comment]
I see a comment in imklog.c which states:

> note: we do NOT use rate-limiting, as the kernel itself does the rate-limiting

The kernel rate-limiting is voluntary in that printk_ratelimited must be used instead of the more common printk.  Also, rate-limiting is not the same as repeated message reduction.  I'm not yet certain if the imklog comment associates rate-limiting to the message reduction.

**Comment by mgrimes123** [comment]
Looking at the source to imklog.c, it might be related to not having isCompatibleWithFeature for RepeatedMsgReduction.

**Comment by rgerhards** [comment]
Sorry for being unable to follow up until now. Do you still have interest in this feature? If so, did you see a reason why imklog does not want the feature? If not, could you craft a PR to enable it?

**Comment by rgerhards** [comment]
no interest any longer
