### ISSUE TITLE
update postgres to new config syntax.

### ISSUE THREAD

**Issue by GrayTShirt** [rsyslog/rsyslog#1824]
I'm interesting in updating the configuration syntax of the postgres output module, (refactoring the entire module for the new API?)

In terms of backwards compatibility what's expected?

**Comment by GrayTShirt** [comment]
ah, I see there is a similar issue #818

**Comment by rgerhards** [comment]
Hi Dan,

That would be really great!

Backwards compatibility is easy: old good should continue to work without
need to change anything.

Usually this means the legacy statements need to be preserved and be
functionality be added only via new style parameters.

If you have questions, let me know.

Rainer

Sent from phone, thus brief.

Am 09.10.2017 16:29 schrieb "Dan Molik" <notifications@github.com>:

**Comment by GrayTShirt** [comment]
Is there an example of a module that preserves the legacy syntax parameters while supporting the new style parameters?

**Comment by rgerhards** [comment]
All of them do, except some very new ones which do not have legacy statement. Ommysql might be a natural choice. I've also just done a change to the new transactional interface, so this might also be good to look at.

**Comment by GrayTShirt** [comment]
hmmm, I got a chance to look at the code, how do you feel about a new module instead, I get a hunch that it will be less maintenance moving forward, and considering that new configuration will need to be written user-side, a few letters difference isn't a big deal.

**Comment by davidelang** [comment]
There are a lot of modules with features that only exist in the new syntax. If 
you look through the various documentation pages, most features added during the 
8.x timeframe are going to be new syntax only.

you just don't change the legacy config section and only add things to the v6+ 
config.

David Lang

**Comment by davidelang** [comment]
what's the difference? if the new module is enough different, it could be 
accepted. But if it's just a parameter or two, they should be combined.

**Comment by rgerhards** [comment]
> I got a chance to look at the code, how do you feel about a new module instead

I am not sure I really understand: do you mean just because of the config? If so, that would not be a good reason to create a new module.  There really is no maintenance problem. You need to write (copy&paste) the old-style support code once and it will never be touched again. At least in practice with all other modules no noteworthy changes ever happened.

On contrast, if you duplicate the actual code (everything that does not deal with the config), you constantly would need to update two versions of almost the same code, what is a maintenance nightmare.

**Comment by GrayTShirt** [comment]
That's a fair point. That's the answer I was looking for, in terms of maintenance...On Oct 10, 2017 3:19 AM, Rainer Gerhards <notifications@github.com> wrote:
I got a chance to look at the code, how do you feel about a new module instead

I am not sure I really understand: do you mean just because of the config? If so, that would not be a good reason to create a new module.  There really is no maintenance problem. You need to write (copy&paste) the old-style support code once and it will never be touched again. At least in practice with all other modules no noteworthy changes ever happened.
On contrast, if you duplicate the actual code (everything that does not deal with the config), you constantly would need to update two versions of almost the same code, what is a maintenance nightmare.

**Comment by rgerhards** [comment]
closed via https://github.com/rsyslog/rsyslog/pull/2172
