### ISSUE TITLE
omfile: handling of writes to read-only file

### ISSUE THREAD

**Issue by rgerhards** [rsyslog/rsyslog#1832]
The omfile-read-only.sh test assume that when omfile tries to write to a read-only file omfile should treat that condition as potentially recoverable and thus put omfile into suspension. The question is if that is really a good idea. IMHO this is more like a DATAFAIL error, which should lead to message discarding rather than trying to resume. Especially as omfile will most probably go into discarding as well "a bit" later when the number of retries is exhausted and the action actually suspended.

Even worse: if writing to dynafile, omfile treats the condition not as an error but as an OK state, that way discarding the message from the module. This makes kind of sense, as a single bad file should not stall the whole action.

Note: with the 8.30 improvements the rsyslog core engine itself can handle that situation and so no module-specific logic should be necessary.

**Comment by mostolog** [comment]
my 0.2:

If omfile is not able to write (temporary or permanently) it should use queues as any other output modules does, and behave the same way as any other module does.

**Comment by rgerhards** [comment]
The core detects when a problem is permanent and does NOT queue in such cases, as that effectively disables the action (a permanent failure by definition is never temporary).

**Comment by mostolog** [comment]
ie: It would be permanent until I noticed queues are getting full, realize the problem and issue a chmod.

**Comment by rgerhards** [comment]
Not really. If you use the regular omfile settings (not setting it to eternal retry), rsyslog would starting to discard messages after 10 retries and from then on never write to the file. But, yes, if you would set it to eternal retry the queues would fill up.

But I would suggest to check rsyslog error messages - that way you see the problem even before the queue begins to fill ;-)

**Comment by davidelang** [comment]
On Tue, 10 Oct 2017, Rainer Gerhards wrote:

> But I would suggest to check rsyslog error messages - that way you see the problem even before the queue begins to fill ;-)

dynafiles means that you need to watch for such errors continually.

I agree that trying to write to a read-only file should be considered a 
temporary error that triggers retries/queueing (yes, the default configs will 
quickly transition to a more severe error state, but those are only the 
defaults, let them take effect as the admin may have changed the values to 
something else)

**Comment by deoren** [comment]
> @rgerhards: But I would suggest to check rsyslog error messages - that way you see the problem even before the queue begins to fill ;-)

I'm currently experiencing issues with an omrelp queue filling without an error message. Instead, I've found lots of `action NAME_OF_QUEUE_HERE resumed (module 'omrelp')` messages from the sending rsyslog instance.

Since I have yet to determine the exact cause, I've created a Nagios check that monitors the queue 'size' attribute for non-zero values and reports the issue. Thus far, I don't know what the root issue is.

All of that to say that I echo what others have said: omfile having an issue writing to a file should be treated as a problem similar any other output module retrying "later" would be the right thing to do here (perhaps a NFS volume mount is restored after as temporary network blip?).

**Comment by davidelang** [comment]
On Sun, 15 Oct 2017, Deoren Moor wrote:

>> @rgerhards: But I would suggest to check rsyslog error messages - that way you see the problem even before the queue begins to fill ;-)
>
> I'm currently experiencing issues with an omrelp queue filling without an 
> error message. Instead, I've found lots of `action NAME_OF_QUEUE_HERE resumed 
> (module 'omrelp')` messages from the sending rsyslog instance.

you have to explicitly turn on 'suspended' messages, and if you don't have them 
going to a different queue than your other messages, they will be blocked behind 
whatever is blocking your messages.

**Comment by rgerhards** [comment]
What @deoren sees in regard to the missing messages probably is fixed in this bug patch: https://github.com/rsyslog/rsyslog/pull/1834

Based on the feedback here, I'll change omfile so that it returns suspended state instead of error state in the case described.

Note to all: the rsyslog engine has logic that sorts out unfixable errors induced by data. This logic is present for quite some while, but we discovered that it was disabled in a couple of the latest versions. The patch above fixes that.
