### ISSUE TITLE
imfile resends all line in log file

### ISSUE THREAD

**Issue by trileybus** [rsyslog/rsyslog#1833]
version 8.29
here is the part of the rsyslog.conf
module(load="imfile" PollingInterval="10")

input(type="imfile"
      File="/etc/rsyslog.d/file.log"
      Tag="file_test"
      Severity="error"
      Facility="local0")

here is the state file
imfile-state:-etc-rsyslog.d-file.log

<Obj:1:strm:1:
+iCurrFNum:2:1:1:
+pszFName:1:23:/etc/rsyslog.d/file.log:
+iMaxFiles:2:1:0:
+bDeleteOnClose:2:1:0:
+sType:2:1:2:
+tOperationsMode:2:1:1:
+tOpenMode:2:3:384:
+iCurrOffs:2:2:29:
+inode:2:8:20447473:
+bPrevWasNL:2:1:0:
>End
.
when new string appended CurrOffs changes no problem.I am trying to send to a remote server.But whenever the log file is edited , the file is sent from the beginning , not from the offset

**Comment by rgerhards** [comment]
That means the editor creates a new file (new inode). rsyslog detects that it is a new file, and thus begins to process it from beginning.
