### ISSUE TITLE
Broken `imgssapi`

### ISSUE THREAD

**Issue by scibi** [rsyslog/rsyslog#1838]
Commit 5c5a7a3ed509dfb39b451c806646ab67782f6eda (PR #1750, issue #1749) broke imgssapi.

https://github.com/rsyslog/rsyslog/blob/6d064cd5071fb0c985259e871b22ca6f0cfec699/plugins/imgssapi/imgssapi.c#L310

```
In file included from imgssapi.c:47:0:
imgssapi.c: In function 'doRcvData':
imgssapi.c:310:11: error: too few arguments to function 'netstrm.Rcv'
   CHKiRet(netstrm.Rcv(pSess->pStrm, (uchar*) buf, piLenRcvd) != RS_RET_OK);
           ^
```

**Comment by Whissi** [comment]
Confirmed.
