### ISSUE TITLE
tls error with latest version

### ISSUE THREAD

**Issue by cristi1979** [rsyslog/rsyslog#184]
This is an error that we see on all machines upgraded to 8.6.0 (el6 and el7):

unexpected GnuTLS error -53 in nsd_gtls.c:1572: Error in the push function

Also, no forwarding works anymore.

If we revert to 8.4.2, everything is ok.

Please let me know if you need the configuration files

**Comment by binarymist** [comment]
I'm getting same error but on 1571. I also get "GnuTLS error: Error in the push function." from stderr. Any ideas on how to get more logging on this issue to trouble-shoot?

I'm on:
libcurl3-gnutls:amd64          7.38.0-4             amd64                easy-to-use client-side URL transfer library (GnuTLS flavour)
libgnutls-deb0-28:amd64        3.3.8-5              amd64                GNU TLS library - main runtime library
libgnutls-openssl27:amd64      3.3.8-5              amd64                GNU TLS library - OpenSSL wrapper
libgnutls26:amd64              2.12.20-8+deb7u2     amd64                GNU TLS library - runtime library
rsyslog-gnutls                 8.4.2-1              amd64                TLS protocol support for rsyslog

Cheers.

**Comment by stephanbuys** [comment]
I'm seeing something similar, from time to time (every couple of days), I get a fatal TLS error and have to restart the rsyslog daemon before it starts sending again. This is on 8.9.0.

I'm happy to get stuck into debugging this if someone can give guidance as to what tracing I can enable to assist.

**Comment by blaind** [comment]
Same here, though version is ubuntu 12.04's rsyslog 5.8.6. Rsyslog got stuck after that message

**Comment by rgerhards** [comment]
Can you add  ```global(debug.gnutls="on") ``` to rsyslog.conf and then run rsyslog in debug mode so that it creates a debug log. Instructions on the debug log here: http://www.rsyslog.com/doc/debug.html

When done, please post the result.

**Comment by virtualjmills** [comment]
Old, but important. This directive (late rsyslog 8.x code) now uses a quoted-integer from zero (0) to ten (10), with most useful output emitted at level "3" or higher. The "on" value simply throws a configuration file parser error.  :-)

Example rsyslog.conf line:
global(debug.gnutls="3")
