### ISSUE TITLE
Unhandled GNUTLS_E_AGAIN from gnutls_handshake

### ISSUE THREAD

**Issue by n2N8Z** [rsyslog/rsyslog#1840]
Was getting error:
Oct 12 05:10:02 ip-10-120-20-20 rsyslogd: unexpected GnuTLS error -28 in nsd_gtls.c:1785: Resource temporarily unavailable, try again.  [v8.29.0 try http://www.rsyslog.com/e/2078 ]

nsd_gtls.c:1785 is CHKgnutls(gnutls_handshake(pThis->sess));
which doesn't handle the non-fatal GNUTLS_E_AGAIN return.

Attached is a little patch that has resolved the issue for me.
[rsyslog-8.29.0-gnutls_handshake-retry.patch.txt](https://github.com/rsyslog/rsyslog/files/1378890/rsyslog-8.29.0-gnutls_handshake-retry.patch.txt)

**Comment by rgerhards** [comment]
We need to check if the blocking behaviour proposed in the patch is acceptable - or if we need a different approach.

**Comment by rgerhards** [comment]
shuffling this over to 8.33 because with that version we will have openssl support as backup if something really goes wrong and we do not detect it ;-)
