### ISSUE TITLE
FR: Add `noop` operation to fill empty condition blocks (or allow to have empty blocks)

### ISSUE THREAD

**Issue by jay7x** [rsyslog/rsyslog#1843]
I'm using complex template in puppet to create rsyslog ruleset config. Sometimes it's really tricky to prevent empty condition blocks like below to appears:
```
if ($.foo == "bar") then {
} else {
  action(...)
}
```
Such empty block cause parser error in rsyslog. So I'd say `noop` operation may be really helpful there. Another way here is to allow empty blocks (`{}`).

**Comment by rgerhards** [comment]
This already exists: ```continue```. See http://www.rsyslog.com/doc/master/rainerscript/control_structures.html
