### ISSUE TITLE
Dependancy on for apt package libfastjson4 needs version specifier

### ISSUE THREAD

**Issue by TD-4242** [rsyslog/rsyslog#1853]
in Changelog:
`libfastjson 0.99.7 is now mandatory`

in apt package
`Depends: libc6 (>= 2.17), libestr0 (>= 0.1.10-0adiscon1trusty1), libfastjson4, libgcrypt11 (>= 1.4.5), libuuid1 (>= 2.16), zlib1g (>= 1:1.1.4), sysv-rc (>= 2.88dsf-24) | file-rc (>= 0.8.16), lsb-base (>= 3.2-14), adduser, ucf, liblogging-stdlog1`

should have ... `libfastjson4 (>= 0.99.7)` ...

This allowed the rsyslog package to update without forcing an update to libfastjson4.

**Comment by alexhexabeam** [comment]
This seems to also affect the rpm packages, not just the debs.

```
$ rpm -qpR rsyslog-8.30.0-2.el7.x86_64.rpm
warning: rsyslog-8.30.0-2.el7.x86_64.rpm: Header V3 RSA/SHA1 Signature, key ID e00b8985: NOKEY
/bin/bash
/bin/sh
/bin/sh
/bin/sh
/bin/sh
/sbin/chkconfig
/sbin/chkconfig
/sbin/service
/sbin/service
bash >= 2.0
config(rsyslog) = 8.30.0-2.el7
coreutils
libc.so.6()(64bit)
libc.so.6(GLIBC_2.12)(64bit)
libc.so.6(GLIBC_2.14)(64bit)
libc.so.6(GLIBC_2.15)(64bit)
libc.so.6(GLIBC_2.17)(64bit)
libc.so.6(GLIBC_2.2.5)(64bit)
libc.so.6(GLIBC_2.3)(64bit)
libc.so.6(GLIBC_2.3.2)(64bit)
libc.so.6(GLIBC_2.3.4)(64bit)
libc.so.6(GLIBC_2.4)(64bit)
libc.so.6(GLIBC_2.7)(64bit)
libc.so.6(GLIBC_2.8)(64bit)
libc.so.6(GLIBC_2.9)(64bit)
libdl.so.2()(64bit)
libdl.so.2(GLIBC_2.2.5)(64bit)
libestr.so.0()(64bit)
libfastjson.so.4()(64bit)
libgcc_s.so.1()(64bit)
libgcc_s.so.1(GCC_3.0)(64bit)
libgcc_s.so.1(GCC_3.3.1)(64bit)
libgcrypt.so.11()(64bit)
libgcrypt.so.11(GCRYPT_1.2)(64bit)
libgpg-error.so.0()(64bit)
libpthread.so.0()(64bit)
libpthread.so.0(GLIBC_2.12)(64bit)
libpthread.so.0(GLIBC_2.2.5)(64bit)
libpthread.so.0(GLIBC_2.3.2)(64bit)
librt.so.1()(64bit)
librt.so.1(GLIBC_2.2.5)(64bit)
librt.so.1(GLIBC_2.3.4)(64bit)
libsystemd-id128.so.0()(64bit)
libsystemd-journal.so.0()(64bit)
libsystemd-journal.so.0(LIBSYSTEMD_JOURNAL_183)(64bit)
libsystemd-journal.so.0(LIBSYSTEMD_JOURNAL_201)(64bit)
libsystemd-journal.so.0(LIBSYSTEMD_JOURNAL_38)(64bit)
libuuid.so.1()(64bit)
libuuid.so.1(UUID_1.0)(64bit)
libz.so.1()(64bit)
logrotate >= 3.5.2
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(FileDigests) <= 4.6.0-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rtld(GNU_HASH)
rpmlib(PayloadIsXz) <= 5.2-1```

Specifically:
`libfastjson.so.4()(64bit)`

We've had failed upgrades to 8.30 due to it not also updating libfastjson. The package installs, but rsyslog fails to run.

**Comment by maltris** [comment]
Just to confirm this:

On Ubuntu 16.04 with libfastjson4 0.99.5-0adiscon1xenial1 I experienced:
```
rsyslogd: symbol lookup error: rsyslogd: undefined symbol: fjson_global_do_case_sensitive_comparison
```

After upgrading libfastjson4 to 0.99.7-0adiscon1xenial1 it seems to be working fine. Version 0.99.7-0adiscon1xenial1 is already in the Ubuntu-Repo as of now:
```
apt-cache policy libfastjson4
libfastjson4:
  Installed: 0.99.7-0adiscon1xenial1
  Candidate: 0.99.7-0adiscon1xenial1
  Version table:
 *** 0.99.7-0adiscon1xenial1 500
        500 http://ppa.launchpad.net/adiscon/v8-stable/ubuntu xenial/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by rgerhards** [comment]
@friedl this went to the main repo, not the packaging project. Please let me know when this is fixed, so that I can close it.

**Comment by EdwardStudy** [comment]
Same as the error in automation pipeline. The OS version is 14.04.

**Comment by friedl** [comment]
Ubuntu packages have been updated to require the current libfastjson version. This should solve the issue. Install tests showed a proper update for both libfastjson and rsyslog.

**Comment by alexhexabeam** [comment]
Looks like you also fixed the RPM package, but you didn't bump the version number!!! This means that anyone caching these packages will not be updated.

Please bump the version so that caches aren't broken! Releasing a different package with the same name greatly decreases trust in your software and your organization.

rsyslog-8.30.0-**2**.el7.x86_64.rpm should have been rsyslog-8.30.0-**3**.el7.x86_64.rpm

**Comment by friedl** [comment]
The 8.30.0-2 RPM released on wednesday is only different because of the fixed signature from the 8.30.0-2 released on tuesday. The actual rsyslog files didn't change at all. 

Should the RPM version number be bumped in such a case as well?

**Comment by alexhexabeam** [comment]
@friedl Yes! The `-2` or `-3` in that number is the version of the RPM, not of the software inside. In this case, the rsyslog version is `8.30.0`, but the rpm version was `2.el7`. Any change which would cause the RPM to be a different file should have a version bump.

**Comment by rgerhards** [comment]
just FYI: this should have gone to the packaging project (still thanks for the notification!). Here, the packagers do not usually watch out. I now close it (as @friedl cannot do this here and this seems to be solved in all regards).
