### ISSUE TITLE
rsyslog rpm not signed

### ISSUE THREAD

**Issue by c-nichols** [rsyslog/rsyslog#1854]
Hi there,

It appears that the most recent release, 8.30.0-2.el6 (uploaded today), in the v8-stable epel-6 yum repository is not signed with the appropriate GPG key.

When I run `yum install rsyslog` I get the following error:

`Package rsyslog-8.30.0-2.el6.x86_64.rpm is not signed`

Similar error is reported for rsyslog-gnutls package.

**Comment by rgerhards** [comment]
seems to have been solved by @friedl 

Note that this issue should have gone to the packaging project here on github.
