### ISSUE TITLE
Spooling with omfwd stops handling logs

### ISSUE THREAD

**Issue by andrewthad** [rsyslog/rsyslog#1865]
This may be related to https://github.com/rsyslog/rsyslog/issues/1701. The high level description is that I'm using `omfwd` and `imudp` to take incoming UDP traffic and feed it downstream over a TCP connection. Occasionally, the downstream service will restart, closing the TCP connection in a non-graceful way. If I don't have spooling enabled, everything works fine. If I have spooling turned on, then after the downstream service restarts, rsyslog stops sending logs. We can see with `tcpdump` that the traffic stops entirely after a few seconds.

My example configuration is provided below. It's worth noting that, in this example, we are forwarding to two downstream locations. However, even when we do this against a single location, we have the same problem.

Operating System: Ubuntu 16.04
Rsyslog Version: 8.30 [from official repo](http://www.rsyslog.com/ubuntu-repository/)

Spooling Directories (`rsyslog-allsight` and `rsyslog-FortiSIEM`):

    noc@NS-NPM-COLLECTOR:/var/spool$ tree -p -u -g .
    .
    ├── [drwxr-xr-x root     root    ]  cron
    │   ├── [drwxrwx--T daemon   daemon  ]  atjobs [error opening dir]
    │   ├── [drwxrwx--T daemon   daemon  ]  atspool [error opening dir]
    │   └── [drwx-wx--T root     crontab ]  crontabs [error opening dir]
    ├── [lrwxrwxrwx root     root    ]  mail -> ../mail
    ├── [drwx------ syslog   adm     ]  rsyslog [error opening dir]
    ├── [drwxr-xr-x syslog   syslog  ]  rsyslog-allsight
    │   ├── [-rw------- syslog   syslog  ]  myapp-spool.00000001
    │   └── [-rw------- syslog   syslog  ]  myapp-spool.qi
    └── [drwxr-xr-x syslog   syslog  ]  rsyslog-FortiSIEM

Configuration file:

```
noc@NS-NPM-COLLECTOR:/var/spool$ cat /etc/rsyslog.conf 

module(load="imuxsock") # provides support for local system logging
module(load="imklog")   # provides kernel logging support

module(load="imudp")
input(type="imudp" port="514")

$ActionFileDefaultTemplate RSYSLOG_TraditionalFileFormat
$RepeatedMsgReduction on

$FileOwner syslog
$FileGroup adm
$FileCreateMode 0640
$DirCreateMode 0755
$Umask 0022
$PrivDropToUser syslog
$PrivDropToGroup syslog

template(name="withip" type="list") {
   constant(value="<")
   property(name="pri")
   constant(value="> ")
   constant(value="10.100.105.253")
   constant(value=" $$$ ")
   property(name="fromhost-ip")
   constant(value=" $$$ ")
   property(name="rawmsg-after-pri")
   constant(value="\n")
}
template(name="nochange" type="list") {
   property(name="rawmsg")
}

*.* -/var/log/syslog

action (
type="omfwd" target="192.168.254.15" port="10514" protocol="tcp"
queue.size="50000"
queue.type="FixedArray"
queue.spoolDirectory="/var/spool/rsyslog-allsight"
queue.filename="myapp-spool"
queue.lowwatermark="48000"
queue.highwatermark="49000"
queue.discardmark="49999"
queue.maxfilesize="1g"
queue.saveonshutdown="on"
queue.dequeuebatchsize="100"
queue.fulldelaymark="47000"
action.ResumeInterval="1"
action.ResumeRetryCount="-1"
action.reportSuspension="on"
action.reportSuspensionContinuation="on"
template="withip"
)

*.* -/var/log/syslog

action (
type="omfwd" target="10.50.5.42" port="514" protocol="udp"
queue.size="50000"
queue.type="FixedArray"
queue.spoolDirectory="/var/spool/rsyslog-FortiSIEM"
queue.filename="myapp-spool"
queue.lowwatermark="48000"
queue.highwatermark="49000"
queue.discardmark="49999"
queue.maxfilesize="1g"
queue.saveonshutdown="on"
queue.dequeuebatchsize="100"
queue.fulldelaymark="47000"
action.ResumeInterval="1"
action.ResumeRetryCount="-1"
action.reportSuspension="on"
action.reportSuspensionContinuation="on"
template="nochange"
)
```

Let me know if there is any additional information I can provide.

**Comment by andrewthad** [comment]
Ahhh! Found this in the logs:

    queue "action 1 queue": queue.fullDelayMark is set below high water mark. This will result in DA mode  NOT being activated for full delayable messages

Fixed `queue.fullDelayMark` and it works. Closing.

**Comment by deoren** [comment]
@andrewthad Is there any text surrounding that message which indicates it is a warning or error condition? Just curious. That sounds like a good place to use such a prefix to make it easier to grep/search in the debug log for problems.

That also sounds like a useful message to have logged by rsyslog in non-debug operation.

@rgerhards do you agree? I can create a new RFE ticket for that if so.

**Comment by tmahany419** [comment]
Here are the logs leading up to it:

```
Oct 19 12:13:18 mww-allsight systemd[1]: Stopped System Logging Service.
Oct 19 12:13:18 mww-allsight systemd[1]: Starting System Logging Service...
Oct 19 12:13:19 mww-allsight systemd[1]: Started System Logging Service.
Oct 19 12:13:19 mww-allsight rsyslogd-2040: fatal error on disk queue 'action 1 queue[DA]', emergency switch to direct mode [v8.16.0 try http://www.rsyslog.com/e/2040 ]
Oct 19 12:13:19 mww-allsight rsyslogd: [origin software="rsyslogd" swVersion="8.16.0" x-pid="21842" x-info="http://www.rsyslog.com"] start
Oct 19 12:13:19 mww-allsight rsyslogd: rsyslogd's groupid changed to 108
Oct 19 12:13:19 mww-allsight rsyslogd: rsyslogd's userid changed to 104
Oct 19 12:13:19 mww-allsight rsyslogd-2358: queue "action 1 queue": queue.fullDelayMark is set below high water mark. This will result in DA mode  NOT being activated for full delayable messages [v8.16.0 try http://www.rsyslog.com/e/2358 ]
Oct 19 12:13:19 mww-allsight rsyslogd-2358: queue "action 3 queue": queue.fullDelayMark is set below high water mark. This will result in DA mode  NOT being activated for full delayable messages [v8.16.0 try http://www.rsyslog.com/e/2358 ]

```

**Comment by rgerhards** [comment]
Sent from phone, thus brief.

Am 19.10.2017 20:06 schrieb "Deoren Moor" <notifications@github.com>:

@andrewthad <https://github.com/andrewthad> Is there any text surrounding
that message which indicates it is a warning or error condition? Just
curious. That sounds like a good place to use such a prefix to make it
easier to grep/search in the debug log for problems.

That also sounds like a useful message to have logged by rsyslog in
non-debug operation.

@rgerhards <https://github.com/rgerhards> do you agree? I can create a new
RFE ticket for that if so.


Definitely, that should be logged as error.

Rainer

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/rsyslog/rsyslog/issues/1865#issuecomment-337990004>,
or mute
the thread

**Comment by davidelang** [comment]
unfortunantly this log output doesn't include the severity level (it's sent as 
part of the message, but this format doesn't include it)
