### ISSUE TITLE
libfastjson4-0.99.7 rpm package breaks installation of rsyslog < 8.20.0

### ISSUE THREAD

**Issue by timp87** [rsyslog/rsyslog#1873]
Hello! I'm creating this bug report about RPM packages here because I couldn't find a separate bug tracker for http://rpms.adiscon.com

The latest libfastjson4-0.99.7 rpm package obsoletes any earlier versions of libfastjson package:

```
# diff -u libfastjson4-0.99.5-1.spec  libfastjson4-0.99.7-2.spec 
--- libfastjson4-0.99.5-1.spec  2017-05-03 14:37:32.000000000 +0000
+++ libfastjson4-0.99.7-2.spec  2017-10-18 07:53:04.000000000 +0000
@@ -3,8 +3,10 @@
 %global debug_package %{nil} 
 
 Name:          libfastjson4
-Version:       0.99.5
-Release:       1%{?dist}
+Version:       0.99.7
+Release:       2%{?dist}
+Provides:      libfastjson4 = %{version}-%{release}
+Obsoletes:     libfastjson <= 0.99.6 
 Summary:       A JSON implementation in C
 Group:         Development/Libraries
 License:       MIT
@@ -96,6 +98,12 @@
 #%doc doc/html/*
 
 %changelog
+* Wed May 03 2017 Florian Riedl <friedl@adiscon.com> - 0.99.7-2
+- Rebuild
+
+* Wed May 03 2017 Florian Riedl <friedl@adiscon.com> - 0.99.7-1
+- New RPM for libfastjson4 0.99.7
+
 * Wed May 03 2017 Florian Riedl <friedl@adiscon.com> - 0.99.5-1
 - New RPM for libfastjson4 0.99.5
``` 

This statement
_Obsoletes:     libfastjson <= 0.99.6_
breaks installation of any rsyslog version earlier than 8.20.0:
```
[root@centos7 ~]# # rpm -qa | grep rsyslog
<no output, i. e. not installed>
[root@centos7 ~]# yum install rsyslog-8.19.0
Loaded plugins: fastestmirror, versionlock
Loading mirror speeds from cached hostfile
Resolving Dependencies
--> Running transaction check
---> Package rsyslog.x86_64 0:8.19.0-1.el7 will be installed
--> Processing Dependency: libfastjson.so.3()(64bit) for package: rsyslog-8.19.0-1.el7.x86_64
Package libfastjson is obsoleted by libfastjson4, but obsoleting package does not provide for requirements
--> Finished Dependency Resolution
Error: Package: rsyslog-8.19.0-1.el7.x86_64 (tools)
           Requires: libfastjson.so.3()(64bit)
           Available: libfastjson-0.99.0-1.el7.x86_64 (tools)
               libfastjson.so.3()(64bit)
           Available: libfastjson-0.99.1-1.el7.x86_64 (tools)
               libfastjson.so.3()(64bit)
           Available: libfastjson-0.99.2-1.el7.x86_64 (tools)
               libfastjson.so.3()(64bit)
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
```

It obviously will not work since libfastjson shared object has different version.
I. e.  rsyslog < 8.20 wants libfastjson.so.3, but it's obsoleted by libfastjson.so.4.

**Comment by rgerhards** [comment]
@friedl I guess this is fixed, right?

If so, I'll close the issue.

Note that there are dedicated projects for packaging, thus this issue here was not seen by the right folks.

**Comment by timp87** [comment]
As far as I can see there were no new packages for libfastjson4 in http://rpms.adiscon.com repo since I've created this issue.

**Comment by timp87** [comment]
WA:
```
yum install --setopt=obsoletes=0 rsyslog-8.19.0
```

**Comment by rgerhards** [comment]
@friedl can you please have a look?

@timp87 just FYI: the packaging project resides here: https://github.com/rsyslog/rsyslog-pkg-rhel-centos

**Comment by rgerhards** [comment]
@friedl is this solved?

**Comment by friedl** [comment]
There was no change here, because we require the "obsoletes" instruction to override distribution default packages of libfastjson and there is no other way to do it as far as we know.

**Comment by rgerhards** [comment]
So this can be closed?

**Comment by friedl** [comment]
In my opinion, yes. If nobody else points out a different method at least, we should stick to the current one.

**Comment by janiboy505** [comment]
configure: error: Package requirements (libfastjson >= 0.99.8) were not met:

Package 'libfastjson', required by 'virtual:world', not found

How can I fix this?
