### ISSUE TITLE
Enhance "queue.fullDelayMark is set below high water mark" message to explicitly indicate it is an error condition

### ISSUE THREAD

**Issue by deoren** [rsyslog/rsyslog#1876]
From #1865 :

```
Oct 19 12:13:19 mww-allsight rsyslogd-2358: queue "action 1 queue": queue.fullDelayMark is set below high water mark. This will result in DA mode  NOT being activated for full delayable messages [v8.16.0 try http://www.rsyslog.com/e/2358 ]
Oct 19 12:13:19 mww-allsight rsyslogd-2358: queue "action 3 queue": queue.fullDelayMark is set below high water mark. This will result in DA mode  NOT being activated for full delayable messages [v8.16.0 try http://www.rsyslog.com/e/2358 ]
```

Request:

Modify the message to explicitly indicate it is an error condition that requires user interaction to fix.

**Comment by jgerhards** [comment]
I have enhanced the warning message. However, it is not an error since this configuration might be intended, for example when using UDP and TCP as input for the same queue and only wanting UDP to use the high watermark config.

**Comment by deoren** [comment]
@jgerhards Thanks! I suspect that @andrewthad and @tmahany419 will find that useful.

**Comment by andrewthad** [comment]
Thanks! Yes, we will find this useful.
