### ISSUE TITLE
The Centos7 can't install  rsyslog-mongodb

### ISSUE THREAD

**Issue by zorelu** [rsyslog/rsyslog#1893]
when I use `yum install rsyslog-mongodb` the error code like this
 `Error: Package: rsyslog-mmnormalize-8.30.0-3.el7.x86_64 (rsyslog-v8-stable)
           Requires: 30
Error: Package: rsyslog-mmaudit-8.24.0-12.el7.x86_64 (@base)
           Requires: rsyslog = 8.24.0-12.el7
Error: Package: libfastjson-devel-0.99.4-2.el7.x86_64 (@base)
           Requires: libfastjson(x86-64) = 0.99.4-2.el7
           Removing: libfastjson-0.99.4-2.el7.x86_64 (@base)
               libfastjson(x86-64) = 0.99.4-2.el7
           Obsoleted By: libfastjson4-0.99.7-2.el7.x86_64 (rsyslog-v8-stable)
              ~libfastjson4(x86-64) = 0.99.7-2.el7
           Available: libfastjson-0.99.0-1.el7.x86_64 (rsyslog-v8-stable)
               libfastjson(x86-64) = 0.99.0-1.el7
           Available: libfastjson-0.99.1-1.el7.x86_64 (rsyslog-v8-stable)
               libfastjson(x86-64) = 0.99.1-1.el7
           Available: libfastjson-0.99.2-1.el7.x86_64 (rsyslog-v8-stable)
               libfastjson(x86-64) = 0.99.2-1.el7
Error: Package: rsyslog-mmnormalize-8.30.0-3.el7.x86_64 (rsyslog-v8-stable)
           Requires: 000
Error: Package: rsyslog-mmsnmptrapd-8.24.0-12.el7.x86_64 (@base)
           Requires: rsyslog = 8.24.0-12.el7
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
`
and i use the yum repo like 
`[rsyslog-v8-stable]
name=Adiscon Rsyslog v8-stable for CentOS-$releasever-$basearch
baseurl=http://rpms.adiscon.com/v8-stable/epel-$releasever/$basearch
enabled=1
gpgcheck=0
protect=1
`
And then i try use the rsyslog-8.30.0.tar.gz pkg to install mogodb modules 
but when i use ./configure the error code 
`configure: error: Package requirements (libfastjson >= 0.99.7) were not met:

Requested 'libfastjson >= 0.99.7' but version of libfastjson is 0.99.4

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables LIBFASTJSON_CFLAGS
and LIBFASTJSON_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
`
I  try to use yum install libfastjson*   but no use
so I want to use rsyslog with mongdb in   centos7 , can you get me some help?

**Comment by rgerhards** [comment]
@friedl can you have a look?

**Comment by rgerhards** [comment]
@friedl is this done?

**Comment by friedl** [comment]
This should be fixed by installing `libfastjson4` instead of `libfastjson`. Also, there was no mongodb build since 8.30.0 as we had trouble with dependencies I believe.
