### ISSUE TITLE
RELP+TLS Documentation: obsolete section?

### ISSUE THREAD

**Issue by pataquets** [rsyslog/rsyslog#1894]
After reading:
http://www.rsyslog.com/tls-secured-syslog-via-relp/
http://www.rsyslog.com/using-tls-with-relp/

The docs have a warning in the limitations section: http://www.rsyslog.com/doc/v8-stable/tutorials/tls.html#limitations

Does this warning still stands or is it obsolete?
I might need to do it in the future, thus confirming or negating it. How do I submit docs improvements? Usual fork & PR workflow?
TIA.

**Comment by deoren** [comment]
Hi @pataquets,

Sorry for the lack of a response on this. The devs are under a heavy load and it is taking a bit to circle around to all of the open issues.

> @pataquets: How do I submit docs improvements? Usual fork & PR workflow?

Yes, please call out if you need help with that.

> @pataquets: Does this warning still stands or is it obsolete?

Based on what I read here, it is obsolete:

- http://www.rsyslog.com/doc/v8-stable/configuration/modules/omrelp.html
- http://www.rsyslog.com/doc/v8-stable/configuration/modules/imrelp.html

For what it is worth, there is work underway to add OpenSSL support to rsyslog. I believe that will be in place of GnuTLS, but I've not been following those efforts closely.

**Comment by rgerhards** [comment]
> For what it is worth, there is work underway to add OpenSSL support to rsyslog. I believe that will be in place of GnuTLS, but I've not been following those efforts closely.

It'll be an additional driver, so GnuTLS will still be available. One reason for adding the addtional driver is that we always have issue with Certificates under GnuTLS and also the error reporting from it is really bad, which forces us to report bad errors. We hope to get this straight with openssl (and yes, we use openssl so that it will be available on older platforms as well).

**Comment by deoren** [comment]
@rgerhards thanks for the correction.

**Comment by deoren** [comment]
@pataquets Related issue: #1738

**Comment by pataquets** [comment]
@rgerhards @deoren: Thanks everyone!
I suppose that until the milestone is achieved, the docs on the website URL will still have the warning. Does this issue also applies to 7.x? (I have servers using it, too)

**Comment by rgerhards** [comment]
I have to admit that I do not remember if we had TLS with RELP in 7.x, but the ChangeLog suggests it was added in 7.6.1.

**Comment by deoren** [comment]
> @pataquets: I suppose that until the milestone is achieved, the docs on the website URL will still have the warning. 

I believe that is correct. Look at the master branch documentation in the meantime.

http://www.rsyslog.com/doc/master/
