### ISSUE TITLE
imjournal: disables it self on some errors

### ISSUE THREAD

**Issue by rgerhards** [rsyslog/rsyslog#1895]
If ```sd_journal_next()``` inside the main loop fails, imjournal exits with an error code, actually disabling all logging from the journal. This was probably never intended. We should look into a way to make imjournal recover and continue to read the journal.

**Comment by rgerhards** [comment]
same issue with failure of ```pollJournal()``` and ```readjournal()```

**Comment by radosroka** [comment]
I'm just guessing that problem is with statefile. In https://github.com/rsyslog/rsyslog/issues/1867 statefile was somehow corrupted. And I have the same problem without existed statefile.

**Comment by radosroka** [comment]
And this is working on 8.29.0.

**Comment by rgerhards** [comment]
> And this is working on 8.29.0.

well, not sure what actually triggered the problem that was now reported, but the problematic code is present in 8.29.0 as well. I would even guess it's in there since its beginning, but haven't yet checked that.

**Comment by radosroka** [comment]
This seems like right fix for that.

```
  1 diff -up ./plugins/imjournal/imjournal.c.fix ./plugins/imjournal/imjournal.c
  2 --- ./plugins/imjournal/imjournal.c.fix 2017-10-24 16:44:00.750681977 +0200
  3 +++ ./plugins/imjournal/imjournal.c     2017-10-24 16:44:46.715455331 +0200
  4 @@ -118,10 +118,10 @@ static sd_journal *j;
  5  static rsRetVal persistJournalState(void);
  6  static rsRetVal loadJournalState(void);
  7 
  8 -static rsRetVal openJournal(sd_journal* jj) {
  9 +static rsRetVal openJournal(sd_journal** jj) {
 10         DEFiRet;
 11 
 12 -       if (sd_journal_open(&jj, SD_JOURNAL_LOCAL_ONLY) < 0)
 13 +       if (sd_journal_open(jj, SD_JOURNAL_LOCAL_ONLY) < 0)
 14                 iRet = RS_RET_IO_ERROR;
 15         RETiRet;
 16  }
 17 @@ -516,7 +516,7 @@ pollJournal(void)
 18                 closeJournal(j);
 19                 cs.stateFile = tmp;
 20 
 21 -               iRet = openJournal(j);
 22 +               iRet = openJournal(&j);
 23                 if (iRet != RS_RET_OK) {
 24                         char errStr[256];
 25                         rs_strerror_r(errno, errStr, sizeof(errStr));
 26 @@ -773,7 +773,7 @@ ENDfreeCnf
 27  /* open journal */
 28  BEGINwillRun
 29  CODESTARTwillRun
 30 -       iRet = openJournal(j);
 31 +       iRet = openJournal(&j);
 32  ENDwillRun
 33 
 34  /* close journal */
~                                      
```

**Comment by radosroka** [comment]
Messages are OK e.g. sd_journal_next should never return negative value.

**Comment by rgerhards** [comment]
I researched the same commit just now: https://github.com/rsyslog/rsyslog/commit/92ac8016e4cd6a2d7a791233b613c8c74746d08b#diff-b1ea6478b8060f07cd30ecde78bfdc49

Still we need to change the main loop and do recovery in unexpected cases. Note that I have a PR with many changes of imjournal open -- https://github.com/rsyslog/rsyslog/pull/1872

**Comment by radosroka** [comment]
I think that rsyslog should be aborter after such situation. Journal structure wasn't basically allocated.

**Comment by rgerhards** [comment]
We cannot abort rsyslog as whole just because one of the input modules has a problem. IMHO the module should try to recover. At least according to the man page (https://www.freedesktop.org/software/systemd/man/sd_journal_next.html)  ```sd_journal_next()``` can fail - so we should not outrule that. In an extreme case like here, of course, this will not help. But I guess we usually can assume that the code works. So does it really hurt to try to re-open the journal in such cases?

... which brings me to another point that IMHO is even more important: we finally need at least a basic CI test for imjournal. A problem like this would have easily been detected by the testbench. A key to make the test useful is that we can run it without special privileges. Suggestions are welcome. I'll add another tracker for that soon, as I am now heading out of office.

**Comment by rgerhards** [comment]
@radosroka side-note: do you have an explanation why no compiler ever complained about the bug that you provided a fix for? I would have expected we get a type error.

**Comment by rgerhards** [comment]
see also https://github.com/rsyslog/rsyslog/issues/164

**Comment by rgerhards** [comment]
@radosroka I turned your patch into PR #1898 (in a sligtly different twist). Hope to have all merged soon (including test). Then going back to refactoring the main loop.

**Comment by radosroka** [comment]
@rgerhards I think that for compiler POV is everything OK even types. Compiler is not able to predict anything in such cases especially with pointers. But valgrind can be helpful.

Perhaps getting rid of global variables would be better approach.

**Comment by rgerhards** [comment]
I had actually hoped that clang static analyzer would have caught it, but it doesn't. And compiler could detect set-but-never read, at least we have such warnings sometimes. But doesn't matter.

valgrind requires a dynamic test - now that I have a base test we can probably extend on that. :-)

Yup, the global might be worth reconsidering! But I think it is most important to do it consistently, thus I have changed that in my commit according to current state.
