### ISSUE TITLE
imudp: error msg for every listener that cannot be started

### ISSUE THREAD

**Issue by PascalWithopf** [rsyslog/rsyslog#1899]
When imtcp fails to create a listener it puts out an error msg for every listener.
"Could not create tcp listener, ignoring port (port) bind-address (ip-address)."

When imudp fails it would be great if it would put out a similar message containing the port and address of the specific listener that failed.

**Comment by rgerhards** [comment]
Please clarify which error message is meant (as UDP does not have connections). Best with link to code line in question. Thx.
