### ISSUE TITLE
ommysql: inserting response to query in column

### ISSUE THREAD

**Issue by gubzh** [rsyslog/rsyslog#1900]
In the rsyslog.conf registered the following rules:

    template(name="cef" type="string" option.sql="on" string="insert into table (Extensions_src_country) values ('http://ip-api.com/json/1.1.1.1?fields=country')")

How add in column Extensions_src_country value response to a request - Australia?

**Comment by rgerhards** [comment]
You currently cannot do http request from the scripting language. However, such a feature is under consideration.

**Comment by gubzh** [comment]
I added a query to sys_exec in rsyslog.conf:

> template(name="cef" type="string" option.sql="on" string="insert into table (Extensions_src_country) values sys_exec('/usr/bin/php5 /opt/rsyslog/test.php')")

and created a php file /opt/rsyslog/test.php:

`<?php 
	$ip='%$!cef!Extensions!src%';
	$url = 'http://ip-api.com/json/'.$ip.'?fields=country';
	$content = file_get_contents($url);
	$json = json_decode($content, true);
	print $json['country'];
?>`

After this, the Extensions_src_country column permanently records 32512.
But I need that there would be an answer to the request http://ip-api.com/json/'.$ip.'?fields=country.
(Country to which the IP address belongs)

**Comment by rgerhards** [comment]
> But I need that there would be an answer to the request http://ip-api.com/json/'.$ip.'?fields=country.
> (Country to which the IP address belongs)

Are you aware you can also do this via mmdblookup plugin?

**Comment by rgerhards** [comment]
rsyslog script now has a ```http_request()``` function. You can use that in rsyslog.conf if the database engine does not work for you. Closing this now. If the problem persists, provide additional information and I'll re-open.
