### ISSUE TITLE
Package rsyslog-mmnormalize-8.30.0-3 for EL7 requires broken dependencies

### ISSUE THREAD

**Issue by mgraff** [rsyslog/rsyslog#1905]
Hello,

The last RPM build of the mmnormalize module (8.30.0-3) requires bad dependencies :

```
$ repoquery --requires rsyslog-mmnormalize-8.30.0-3.el7
000
30
libc.so.6(GLIBC_2.2.5)(64bit)
libfastjson.so.4()(64bit)
liblognorm.so.5()(64bit)
liblognorm5 >= 
rsyslog = 8.30.0-3.el7
rtld(GNU_HASH)
```

The `000` and `30` dependencies are wrong.
Could you please correct these dependencies as they break package installation.

Thanks

**Comment by rgerhards** [comment]
@friedl pls have a look, issue went to rsyslog issue tracker instead of packaging one

**Comment by mgraff** [comment]
Sorry I missed out the dedicated issue tracker

**Comment by friedl** [comment]
Uploading the fixed RPMs right now.

**Comment by mgraff** [comment]
I cannot find the fixed RPMs...
The RPM `rsyslog-mmnormalize-8.30.0-2.el7.x86_64.rpm` was modified (date changed) but this version was not concerned by the dependency issue.
However, the package `rsyslog-mmnormalize-8.30.0-3.el7.x86_64.rpm` is still broken.

**Comment by friedl** [comment]
This was fixed: https://github.com/rsyslog/rsyslog-pkg-rhel-centos/commit/71bf897803854b52e74539bdb2252885934a786e

**Comment by mgraff** [comment]
Thanks for the fix
