### ISSUE TITLE
omzmq3 does not work with rsyslog8.6 

### ISSUE THREAD

**Issue by deltay** [rsyslog/rsyslog#192]
I have followed http://www.rsyslog.com/quick-guide-to-omzmq3/
and have no luck to get it work.
I build  rsyslog from source (I built  libzmq libczmq and installed pyzmq ).
I setup 2 actions in rsyslogd.conf,  one is omzmq3 and the others is omfile.
I started pyzmq 's example  topics_sub.py  and get nothing ( topics_sub.py and topics_pub.py works)
I can get syslog from omfile, but nothing from omzmq3（topics_sub.py from pyzmq)

According to debug log, no error occured and the action is excuted .

**Comment by rgerhards** [comment]
This is a contributed and deprecated module. The 0mq stuff is maintained by @taotetek . He has written a new module omczmq, you should use that one. Closing issue for now, please re-open if omczmq doesn't work for you.
