### ISSUE TITLE
testbench: add Elasticsearch testing capability w/o root access

### ISSUE THREAD

**Issue by rgerhards** [rsyslog/rsyslog#1934]
We should try to add ES tests that download specific ES versions and can start/stop them without root access - no longer depend on OS provided packages.

**Comment by rgerhards** [comment]
tenatively assigned released goal

**Comment by alorbach** [comment]
https://github.com/alorbach/rsyslog-1/commit/87dafc7fbc3670f90ab997b720d1fc1db9077fce
does that. 

Should I convert all other tests?

**Comment by rgerhards** [comment]
implemented via #2071
