### ISSUE TITLE
Support client cert and client key in omelasticsearch module

### ISSUE THREAD

**Issue by radosroka** [rsyslog/rsyslog#1935]
Since omelasticsearch already uses libcurl, and libcurl already supports
client cert and client key, it should be relatively straightforward to
add these additional parameters.

**Comment by richm** [comment]
https://github.com/rsyslog/rsyslog/pull/2519

**Comment by jvymazal** [comment]
@radosroka shouldn't this be closed already? (resolved by #2519 )

**Comment by rgerhards** [comment]
looks like the "closes" was missing inside the PR.
