### ISSUE TITLE
RainerScript: previous action is suspended

### ISSUE THREAD

**Issue by WaeCo** [rsyslog/rsyslog#1939]
Hello,

I want to do something like:
```
module(load="omruleset")
# ...
$ActionExecOnlyWhenPreviousIsSuspended on
$ActionOmrulesetRulesetName failover
```
Doc states that `omruleset` is depreciated, also it does only support legacy format.
Is there a way to use rainerscripts `call ruleset` statement in a similar manner?
I have not found any property that let me check the suspension state, is there one?

**Edit**: If this currently does not work. Maybe one could expose the state as a local variable. E.g. `$!PreviousActionIsSuspended`?

**Comment by WaeCo** [comment]
Following patch is simple and works.
But considering performance is probably not the best way to do it. Any suggestions regarding this?
Also this should be configurable and optional.
I will submit a proper PR if there is any chance that such a functionality will be merged.

```diff
diff --git a/action.c b/action.c
index 4e467ee8b..2d829d852 100644
--- a/action.c
+++ b/action.c
@@ -1615,6 +1615,7 @@ doSubmitToActionQ(action_t * const pAction, wti_t * const pWti, smsg_t *pMsg)
        }
        pWti->execState.bPrevWasSuspended
                = (iRet == RS_RET_SUSPENDED || iRet == RS_RET_ACTION_FAILED);
+       msgAddJSON(pMsg, (uchar*)"!PreviousActionIsSuspended", json_object_new_boolean(pWti->execState.bPrevWasSuspended), 0, 0);

        if (iRet == RS_RET_ACTION_FAILED)       /* Increment failed counter */
                STATSCOUNTER_INC(pAction->ctrFail, pAction->mutCtrFail);
```

Usage in config:
```
action(...)
if $!PreviousActionIsSuspended then {
 # ... e.g. call failover
}
```

**Comment by rgerhards** [comment]
We should double-check how the action engine keeps this state. Best if we can reuse some of that.

**Comment by rgerhards** [comment]
details on upcoming solution proposal in #1978
