### ISSUE TITLE
omelasticsearch: 401 on _cat/health with http basic auth

### ISSUE THREAD

**Issue by waster** [rsyslog/rsyslog#1949]
We are using Rsyslog + Omelasticsearch 8.30.0-0adiscon2trusty1 with external http basic authorization based on nginx. It seems that uid and password configuration parameters are not used to check a connection health of Elasticsearch server and these messages in http logs are appearing:
```
X.X.X.X - - [01/Nov/2017:09:12:56 +0300] "GET /_cat/health HTTP/1.1" 401 188 "-" "-"
X.X.X.X - - [01/Nov/2017:09:12:57 +0300] "GET /_cat/health HTTP/1.1" 401 188 "-" "-"
X.X.X.X - - [01/Nov/2017:09:12:58 +0300] "GET /_cat/health HTTP/1.1" 401 188 "-" "-"
```
At the same time bulk mode is on and works well.

Best regards, Andrey.

**Comment by bayaro** [comment]
it is connected with #1906 
`checkCon` does not use a full request setup

**Comment by rgerhards** [comment]
> it is connected with #1906

Do you have a clear connection of why this causes the segfault? If so, I would *really* like to hear the details. If not, I suggest we treat this issue here as separate, #1906 is about a potential segfault.

**Comment by bayaro** [comment]
I have marked it as connected with 1906, because of in both `checkConn` is a one of points.
I will add details about segfault at 1906
