### ISSUE TITLE
omelasticsearch: incorrect handling of CURLOPT_WRITEFUNCTION

### ISSUE THREAD

**Issue by rgerhards** [rsyslog/rsyslog#1962]
Spliting this off #1906 as it probably is a different issue - but may be the root cause of the remaining issue in #1906.

@bayaro said in https://github.com/rsyslog/rsyslog/issues/1906#issuecomment-341548095 (additional information in that issue tracker as well):

Both function `checkConn` and `curlPost` use one structure `pWrkrData` that is being given to the curl.

The curl uses callback `curlResult` in which `pWrkrData->reply` reallocated for every response.

`checkConn` is calling periodically and do not clear/free `pWrkrData->reply`. (It is reallocated always inside `curlResult`).

BUT `curlPost` starts with
```
pWrkrData->reply = NULL;
pWrkrData->replyLen = 0;
```

so every `checkConn` call that occurs before a `curlPost` call (not from inside curlPost)  add a memory leak.

There are should be not an assignment of NULL but  reallocation to 0. (Of course freeing of `->reply` also should be removed, and added on the exit of the program)

BTW I think `checkConn` inside the `curlPost` is overwhelming request to ES.
It will be less resource usable if after a curl request inside  `curlPost` the curl response will be checked similar to `checkConn` instead of calling `checkConn` before `setPostURL`.
So `checkConn` will be used only for checking if ES is available.

**Comment by rgerhards** [comment]
there actually seems to be some additional issues. At least the user pointer provided to the callback is not always set correctly -- maybe it's even random. Investigating...

**Comment by rgerhards** [comment]
OK, the problems were introduced roughly a year ago: https://github.com/rsyslog/rsyslog/commit/96b5fce0acd57e8ae39f053b9e20cb0c28911b80

We can probably now also work from that commit to check the intent.

**Comment by rgerhards** [comment]
The root problem that we got this regression is that there is no testbench test for elasticsearch under valgrind. It would have detected the problem.

**Comment by bayaro** [comment]
`curlPost` `free(pWrkrData->reply);` into `finalize_it:`

I could not find definitely where `tryResume` is called but i think it is called somewhere if it is coded. And `tryResume` is just a wrapper for `checkConn`. Voila.

yes. my sentence should be changed as:
if `checkConn` is called before/between `curlPost` calls the pWrkrData->reply is undefined.

**Comment by rgerhards** [comment]
The health check URL uses an invalid pointer. Among others, this can also cause a slowly growing memory leak.

**Comment by rgerhards** [comment]
```checkConn``` needs to be called inside ```curlPost``` to support ES HA feature - but only if more than one server is configured.
