### ISSUE TITLE
journald support is not packaged for el7

### ISSUE THREAD

**Issue by cristi1979** [rsyslog/rsyslog#197]
There is no support for journald in the packages provided for el7.

I can try to provide a patch for the spec file. Tell me if it should be included as default or in a separate package.

**Comment by rgerhards** [comment]
This is actually an item for the packaging project: https://github.com/rsyslog/rsyslog-pkg-rhel-centos

I think it is best to do it as two separate package (one each for input and output).

I close this tracker here, feel free to simply submit a PR to the packaging project.
