### ISSUE TITLE
Rsyslog stops pushing log to tcp endpoint after sometime

### ISSUE THREAD

**Issue by shivkumarmallesappa** [rsyslog/rsyslog#1974]
Apologies in advance.
Following is my configuration , which I am using to push mysql-error logs to my tcp endpoint.
```
module(load="imfile" PollingInterval="10") #needs to be done just once

#File 1
input(type="imfile"
  mode="polling"
  File="/var/log/mysql/error.log"
  Tag="mysql-error"
  Severity="error"
  PollingInterval="10"
  PersistStateInterval="20000"
 startmsg.regex="^[[:digit:]]{4}-[[:digit:]]{2}-[[:digit:]]{2}"
)

$PrivDropToUser mysql
$WorkDirectory /var/spool/rsyslog
$InputRunFileMonitor

#Add a tag for MySQL events
$template MySQLError,"%msg%\n"

if $programname == 'mysql-error' then @@xx.xx.xx.xx:12345;MySQLError
if $programname == 'mysql-error' then ~
~ 
```

It works perfectly fine when I start the rsyslog service, but after sometime if any of the log is written to mysql error.log then rsyslog is not pushing the new events to my tcp endpoint.
What I am doing wrong here ?

Thanks.

**Comment by rgerhards** [comment]
sorry for the late reply. I am wrangling with the many open issues and this one I unfortunately overlooked. If the issue still persists, would it be possible that you create a debug log?

**Comment by rgerhards** [comment]
seems to be resolved. If not, please let me know and I will re-open.
