### ISSUE TITLE
RainerScript function: http_request(url)

### ISSUE THREAD

**Issue by rgerhards** [rsyslog/rsyslog#1977]
Add a function to do a http request (via libcurl) and provide the response back as a string. This is useful for many applications, among other for querying Amazon AWS config data.

A mock-up of AWS state document has been placed here: http://www.rsyslog.com/files/testbench/aws-sim.php This can be used for testbench tests.

**Comment by davidelang** [comment]
doing this for every log message that's processed would be insanely slow. If 
this is included, it needs to have a LOT of warnings about being protected by 
something that prevents it from being executed every message.

**Comment by rgerhards** [comment]
Ack, but there are many legit uses for it.

**Comment by davidelang** [comment]
On Mon, 6 Nov 2017, Rainer Gerhards wrote:

> Ack, but there are many legit uses for it.

I agree, but I'm not sure if it's valid to have it as a function.

We've talked a few times about external things affecting the config on the fly 
(adding or removing inputs for example to work with containers)

This sounds like a case where what you really want is the ability for an 
external 'thing' to set a global variable and update it periodically. Having 
something in the ruleset do this seems to be in the "I have a hammer, this looks 
like a nail" category :-)

David Lang

**Comment by rgerhards** [comment]
I don't think so. Adding a module is not as flexible. We have had other
requests for similar functionality these days. Of course it's powerfull and
can be abused but there are other things inside rsyslog that can so also.

If you insist in it, I can disable it by default and require a global
directive to opt-in.

Rainer

Sent from phone, thus brief.

Am 06.11.2017 22:58 schrieb "David Lang" <notifications@github.com>:
