### ISSUE TITLE
RainerScript: add capability to parse JSON string

### ISSUE THREAD

**Issue by rgerhards** [rsyslog/rsyslog#1979]
It is useful to be able to parse arbitrary JSON strings without the need of an external message modification module. For example, together with #1977 this can be used to parse out specific fields from Amazon AWS configuration info. There are also other ample uses for such functionality.

**Comment by rgerhards** [comment]
proposed interface:
```
int json_parse(json_string, var_root);
```
returns 0 if success, something else on failure.
Supports the ```script_error()``` interface.

**Comment by davidelang** [comment]
On Sun, 10 Dec 2017, Rainer Gerhards wrote:

> proposed interface:
> ```
> int json_parse(json_string, var_root);
> ```
> returns 0 if success, something else on failure.
> Supports the ```script_error()``` interface.

Why this instead of a mmnormalize call with a inline format?

Yes, it's shorter, but is it enough faster to matter? (to make up for the 
long-term maintinance? or is it so trivial that long-term maintinance is 
non-existant?)

**Comment by rgerhards** [comment]
It's a bit faster, but it is more about the usability. It's far more intuitive for a very common use case. Maintainance-wise it's not a real problem, it's around 10 lines of code.

**Comment by davidelang** [comment]
Ok, I try to double check such things to keep too much from building up.

and while I don't subscribe to the Python "there should only be one way to do 
something" I don't like adding too many different ways. :-)

**Comment by rgerhards** [comment]
I am with you in the same camp and appreciate you keeping an eye on those things. It's better if you have to reason, so nothing accidently slips in.
