### ISSUE TITLE
pmnormalize: potential memory leak

### ISSUE THREAD

**Issue by rgerhards** [rsyslog/rsyslog#2007]
While working on something else: it could be that there is a leak in pmnormalize if in ```parse2```entry point the path leading to error message "error %d during ln_normalize" is taken. This should be tested (testbench test crafted) and, if actually a bug, be fixed.

**Comment by rgerhards** [comment]
@PascalWithopf did we try to reproduce this via a test?

**Comment by PascalWithopf** [comment]
@rgerhards I don't remember, I will try to reproduce this to be sure.

**Comment by rgerhards** [comment]
If you do, pls add the info to the issue tracker.

**Comment by rgerhards** [comment]
confirmed by new testbench test
