### ISSUE TITLE
Omelasticsearch with es 6.x

### ISSUE THREAD

**Issue by Ekouyoja** [rsyslog/rsyslog#2070]
Hi,

Recently, I have try to use omelasticsearch plugin with the new elasticsearch version (6) and it appear that it doesn't work.
I have this reply from elasticsearch : 
        "reply":        {
                "error":        "Content-Type header [text/json; charset=utf-8] is not supported",
                "status":       406
        }
Am I wrong to say that an update on omelasticsearch is needed for es 6.x ?

**Comment by rgerhards** [comment]
Which version of rsyslog is this?

I tried to run a very basic testbench test against ES 6.0 (downloaded right now), and it did not show any errors. But I am not an ES expert. @hakman Do you know of any incompatibility?

**Comment by Ekouyoja** [comment]
This is the version 8.24.0 on RHEL 7

**Comment by rgerhards** [comment]
> This is the version 8.24.0 on RHEL 7

maybe it is missing some bugfixes. We've done a bit of work recently on omelasticsearch. You could go with 8.30, but it probably is better to wait until next Tuesday, when 8.31 comes out -- it has a couple of more changes to omelasticsearch.

**Comment by Ekouyoja** [comment]
I have update my rsyslog and plugins from your repository to 8.30 (non available from redhat channels for the moment) and it works. Thanks for your help.
Have nice day :)
