### ISSUE TITLE
File Path with Spaces

### ISSUE THREAD

**Issue by drice000** [rsyslog/rsyslog#2073]
Anytime I add a config that has a file path with space the configuration check fails. I remove the config and the issue is fixed. Doesn't matter if I use escape, or put quotes around etc. It see the string ending.

i.e. /var/lib/application support/logs/application logging.log

It thinks the file name is /var/lib/application

I may be missing something but in case I'm not wanted to post it.

**Comment by rgerhards** [comment]
Please provide at least the relevant config lines and the error message.
