### ISSUE TITLE
Rsyslog was abnormally killed process, restart a large number of duplicate log printing.

### ISSUE THREAD

**Issue by baotouwang** [rsyslog/rsyslog#2074]
rsyslog normal circumstances will not repeat the print log, kill rsyslog process by abnormal termination, rsyslog start will repeat the print log. Through the test found that duplicate log content can see a few days ago log information, the number of logs up to millions.

**Comment by rgerhards** [comment]
Thanks for reporting the issue. I unfortunately have to admit I do not fully understand. Also can you tell me your rsyslog version?
