### ISSUE TITLE
impstats as json missing quote

### ISSUE THREAD

**Issue by khornberg** [rsyslog/rsyslog#208]
I turned on impstats yesterday and started sending data to elasticsearch. While looking at the message in Kibana, I noticed that it seems that there is a missing quote in the json. After looking through the issues I didn't see this specific issue but I could already be reported.

The quote seems to be the missing around `origin"` and should be `"origin"`.

Log viewed in Kibana:
```
{""name":"imudp(w0)",origin":"imudp","called.recvmmsg":1520502,"called.recvmsg":0,"msgs.received":1255610}
```

Log written to file:
```
Wed Jan 14 13:04:35 2015: {""name":"imudp(w0)",origin":"imudp","called.recvmmsg":1520502,"called.recvmsg":0,"msgs.received":1255610}
```

I'm using rsyslog 8.6.0 and loading the module with:
```
module(load="impstats"
       interval="300"
       severity="7"
       format="json"
       log.syslog="on"
       log.file="/data/rsyslog/stats.log"
       Ruleset="stats")
```
 and using the [default](http://www.rsyslog.com/output-to-elasticsearch-in-logstash-format-kibana-friendly/) suggested templates to get syslog to elasticsearch.

**Comment by rgerhards** [comment]
This is fixed in v8.7.0.
