### ISSUE TITLE
imstats not logging to file when using upstart

### ISSUE THREAD

**Issue by mrproper** [rsyslog/rsyslog#210]
rsyslog 8.7.0-0adiscon1trust tested on both ubuntu 12.04 and 14.04
I've also changed apparmor to complain for rsyslogd with no change in results
using the config:
...
module(
    load="impstats"
    interval="500"
    severity="6"
    log.file="/var/log/rsyslog-stats.log"
    log.syslog="off"
)
# Set the default permissions for all log files.
$Umask 0022
$FileOwner syslog
$FileGroup adm
$FileCreateMode 0640
$DirCreateMode 0755
$PrivDropToUser syslog
$PrivDropToGroup syslog
...

# Running rsyslog with rsyslogd in complain mode
$ sudo service rsyslog stop
$ aa-complain usr.sbin.rsyslogd
$ sudo rm /var/log/rsyslog-stats.log
$ sudo service rsyslog start
$ ls -lah /var/log/rsyslog-stats.log
ls: cannot access /var/log/rsyslog-stats.log: No such file or directory

# Running rsyslog in the foreground
$ sudo service rsyslog stop
$ sudo rsyslogd -dn
....
^C
$ ls -lah /var/log/rsyslog-stats.log
-rw------- 1 syslog syslog 2.2K Jan 15 02:38 /var/log/rsyslog-stats.log

Im happy to provide more info if needed

sudo rm /var/log/rsyslog-stats.log

**Comment by rgerhards** [comment]
It looks like the "syslog" user does not have permission to write to that file. Do you capture rsyslog error messages (syslog.* , most people unfortunately throw them away)? If you don't think it's a permission problem, please post a debug log. Instructions here: http://www.rsyslog.com/doc/debug.html

**Comment by rgerhards** [comment]
looks like this was indeed the permission problem --> closing
