### ISSUE TITLE
imzmq3/omzmq3: include deprecation notice

### ISSUE THREAD

**Issue by rgerhards** [rsyslog/rsyslog#2100]
according to @brianknox these modules are outdated: 

https://twitter.com/taotetek/status/931860786959540224

They are replaced by imczmq/omczmq and are no longer maintained. We should put a deprecation notice into them that is emitted upon module load. In the somewhat longer term, we should completely remove them.

@mbiebl @Whissi would be great to get your feedback

**Comment by mbiebl** [comment]
2017-11-24 8:51 GMT+01:00 Rainer Gerhards <notifications@github.com>:

> according to @brianknox <https://github.com/brianknox> these modules are
> outdated:
>
> https://twitter.com/taotetek/status/931860786959540224
>
> They are replaced by imczmq/omczmq and are no longer maintained. We should
> put a deprecation notice into them that is emitted upon module load. In the
> somewhat longer term, we should completely remove them.
>
> @mbiebl <https://github.com/mbiebl> @Whissi <https://github.com/whissi>
> would be great to get your feedback
>

In Debian I've never built the imzmq3/omzmq3 modules (only imczmq/omczmq).
So Debian/Ubuntu is not affected by this change.

Thanks for checking with us though.

Regards,
Michael




-- 
Why is it that all of the instruments seeking intelligent life in the
universe are pointed away from Earth?
