### ISSUE TITLE
Travis: autoconf-archive too old

### ISSUE THREAD

**Issue by rgerhards** [rsyslog/rsyslog#2102]
The packages of autoconf-archive are too old to support AX_COMPILER_FLAGS. I tried to solve this in the past, but never found a working solution. It would be great if someone could let me know how to install a recent version (PR would even be better ;-)).

@Whissi could you help?

**Comment by Whissi** [comment]
Let me see if we can just manually install a newer package. If not, I'll backport current version to Travis' Ubuntu version.

**Comment by rgerhards** [comment]
FYI: I got a solution from @Whissi - thx! PR will be upcoming in the near future.

**Comment by rgerhards** [comment]
Basic plumbing is in place after merging PR #2112. We need to fully enable the new autoconf-archive. See https://github.com/rsyslog/rsyslog/pull/2112/commits/42fd7c7b7818547e3ff58b92bf568f8166a50473 for more details.

**Comment by rgerhards** [comment]
this is now fully in place and working (done a couple of days ago)
