### ISSUE TITLE
error during config processing: omfile: creating parent directories for file  'File exists' failed

### ISSUE THREAD

**Issue by nipakoo** [rsyslog/rsyslog#2107]
We are bumping into the race in makeFileParentDirs quite heavily. Got two rsyslogd threads repeatedly competing for creating parent directories on an NFS mount (service failing and restarting). Journal flooding with following messages until the rsyslog service is manually restarted:

Nov 24 23:16:05 xx-0 rsyslogd[1518]: error during config processing: omfile: creating parent directories for file  'File exists' failed: /var/log/node/xxxxx [v8.30.0 try http://www.rsyslog.com/e/2207 ]
Nov 24 23:16:05 xx-0 rsyslogd[1518]: error during config processing: omfile: creating parent directories for file  'File exists' failed: /var/log/node/yyyyy/auth.log [v8.30.0 try http://www.rsyslog.com/e/2207 ]

On our deployment, this is currently reproduced ~50% of the time.

**Comment by rgerhards** [comment]
Thanks for the report. I am currently preparing next Tuesdays release, so I can unfortunately not look directly into it. Will try during next week.

My first impression is that actually a mutex lock is missing during file path creation.

**Comment by nipakoo** [comment]
Yeah, there is a comment dating back to 2010 that acknowledges this. Seems the lock was not implemented because it will not fix race with other processes. Anyway, should be fixed as the most likely race should be within our process space.

**Comment by rgerhards** [comment]
fixed via #2109
