### ISSUE TITLE
ommongodb: does not build with gcc-7

### ISSUE THREAD

**Issue by rgerhards** [rsyslog/rsyslog#2108]
We are seeing build issues under gcc-7: http://build.rsyslog.com:8010/builders/rsyslog%20ubuntu16%20rsyslog/builds/447/steps/shell_7/logs/stdio

This looks like it is induced by [libbson](https://github.com/mongodb/libbson) (do we need to file a bug there?).

I have temporarily disabled the gcc-7 check for mongodb on the Ubuntu16 build slave, because otherwise CI would be broken. Note: this check was added yesterday afternoon in an effort to improve code quality. So the problem is not new, just newly detected.

@HugoSoszynski is this the problem you talked about in https://github.com/rsyslog/rsyslog/issues/2098? If so, do you happen to know a work-around?

**Comment by HugoSoszynski** [comment]
This flag was added by default in gcc 7.1.X. It shows up when *defined* preprocessor word is used outside of a *#if* statement.
It looks like some other projects like webkit had some issue with this flag too and always for version check macros.

This issue does not seems to be related to those mentioned in #2098.

I was not able to reproduce the error even with the flag on my system so could you tell me the version of libbson on the buildbot please ?
I will look for more informations directly at the libbson repository.

For now, I think that **-Wno-expansion-to-defined** should be a good work-around but as I was not able to reproduce the error I can't confirm it works.

**Comment by rgerhards** [comment]
> For now, I think that -Wno-expansion-to-defined should be a good work-around but as I was not able to reproduce the error I can't confirm it works.

Thanks! I would assume it works. We just need to add it as pragma as we cannot totally control what options the user activates.

**Comment by rgerhards** [comment]
this has been solved in the interim, guess I missed the PR closes tag ;-) thx again @HugoSoszynski
