### ISSUE TITLE
Rsyslog imfile not working with wildcards in background mode

### ISSUE THREAD

**Issue by hackeracc** [rsyslog/rsyslog#2118]
I have rsyslog setup to read messages from a file and send out the messages to a remote rsyslog server. I am using imfile to read the files. I am also using wildcards to specify the input files. 
When I start the rsyslog as a foreground process (using : sudo rsyslogd -n), I am able to see the watch being registered for the files matching the regex and I am receiving the messages at the server side.
But when I start rsyslog as a background process (using : sudo service rsyslog start), there are no watches registered (I checked using lsof), I am not receiving anything at server side.
My client configuration looks as follows:

module(load="imfile" mode="inotify")

input(type="imfile"
      File="/root/srv.*"
      Tag="test:"
        Ruleset="sendLogs"
        addMetadata="on")

ruleset(name="sendLogs") {
        action(type="omfwd" Target=<ip> Port="514" Protocol="tcp")
}

I am unable to understand why rsyslog is behaving differently in foreground and background mode. Any help would be appreciated.
Any suggestions on how I can debug this further ?

**Comment by rgerhards** [comment]
I think that the issue is rooted in access permissions/SELinux/AppArmor. The forground an background most probably have different security properties. Please check and let us know the result.

**Comment by rgerhards** [comment]
@hackeracc did that solve the issue for you?

**Comment by hackeracc** [comment]
Yes @rgerhards 
That did the trick. It was an issue with SELinux. Thanks for the help.

**Comment by kevin8100** [comment]
Hello

I ') dancing thé samedi issue with wildcard Anderson selinux.

I hace configured SElinux fcontext for wildcard.

When using imfile for reading  specific file it does  work properly.
But when I configure imfile for  reading the whole directory it does not.  I still got SELinux on parent folders...

Did you use omrelp or omfwd or rsyslog protocol to send logs to server?
Can you please give more details about your selinux config?

Thanks
