### ISSUE TITLE
testbench: daqueue-dirty-shutdown.sh sometimes aborts with segfault

### ISSUE THREAD

**Issue by rgerhards** [rsyslog/rsyslog#2122]
...unfortunately the current test harness does not provide any more information. This may be a bug in the testbench or in actual code.

**Comment by mbiebl** [comment]
Looks like this happened for the recent 8.89.0 upload to Debian on armel
https://buildd.debian.org/status/fetch.php?pkg=rsyslog&arch=armel&ver=8.39.0-1&stamp=1540991734&raw=0

**Comment by rgerhards** [comment]
PR #3502 analysis reveals that this is actually a test bug (not rsyslog bug).
