### ISSUE TITLE
rscript_parse_time.sh: test failure: Failed own self-test(s)!

### ISSUE THREAD

**Issue by Whissi** [rsyslog/rsyslog#2124]
```
  File "./rscript_parse_time_get-ts.py", line 52
    print "Error: %s. Expected %4d, got %4d!" % (expr, val, result)
                                            ^
SyntaxError: invalid syntax
Failed own self-test(s)!
FAIL rscript_parse_time.sh (exit status: 1)
```

**Comment by rgerhards** [comment]
@mrworkman do you have a chance to look at this? I could still do a merge tomorow immediately before release.

@Whissi do you agree we can otherwise disable the test until 8.32? I don't think actual code is affected.

**Comment by mrworkman** [comment]
Looks I was silly and made an assumption (that Python 2.x would be the default system Python everywhere.) I'll have a PR in a couple of minutes.

**Comment by mrworkman** [comment]
Just waiting on Travis (on my end).

**Comment by Whissi** [comment]
Oh, for some reason I totally missed that the test suite was using Python. :)

I pulled from your repository and can confirm that your PR will fix this problem. Thanks!

**Comment by mrworkman** [comment]
> I pulled from your repository and can confirm that your PR will fix this problem. Thanks!
Glad I could help ;)

**Comment by rgerhards** [comment]
> Oh, for some reason I totally missed that the test suite was using Python. :)

It's not very commonly used, but I think in one or two other places as well. As long as something is common, we do not place restrictions on its use. Of course a limited subset is easier to keep working, but IMHO it is better to have tests in than to make contributors go away because it is too hard.

**Comment by Whissi** [comment]
As package maintainer you have to do some additional work if the package you are building is calling Python, that's all. But it is totally fine that *rsyslog* is using Python. It was just me who didn't notice that before ;)
