### ISSUE TITLE
imfile - reading in /var/log/apt/term.log results in segfault

### ISSUE THREAD

**Issue by deoren** [rsyslog/rsyslog#2127]
- Distro: Ubuntu 14.04, Ubuntu 16.04
- Rsyslog: 8.30.0 (ppa:adiscon/v8-stable), 381da21e3de6 (ppa:adiscon/v8-devel)
- Conf: https://github.com/deoren/rsyslog-examples/blob/44767f57347a3969d6973c6a6b94ab0baa53c3c6/rsyslog-i2127.conf
- Debug log: [rsyslog-valgrind-debug-i2127.zip](https://github.com/rsyslog/rsyslog/files/1507575/rsyslog-valgrind-debug-i2127.zip)

While working to setup a small conf fragment to read in the contents of `/var/log/apt/history.log` and `/var/log/apt/term.log` I first encountered issues with imfile failing to read all of the content when using `readMode="1"`. I then re-read the docs and saw that when using inotify input mode, that '0' provides the most reliable results.

I changed `readMode` to '0' for both inputs and restarted rsyslog after first running `rsyslogd -N6` to confirm I didn't introduce any syntax errors.

For some of our Ubuntu boxes no issues were noted, but on a few, rsyslog segfaulted after only a few moments. It appears that using anything other than `readMode="1"` for the `/var/log/apt/term.log` file is what triggers the segfault.

I'm working now to collect a debug log. When I post it, I'll also include copies of both log files within `/var/log/apt` for reference.

**Comment by deoren** [comment]
`root@ubuntu-virtual-machine:~# dmesg | tail -n 5`
```
[ 1168.182763] rs:main Q:Reg[29960]: segfault at 0 ip 00007f5ca665c3e5 sp 00007f5ca4822980 error 4 in libestr.so.0.0.0[7f5ca665b000+3000]
[ 1169.782078] rs:main Q:Reg[29972]: segfault at 0 ip 00007fe2a63e63e5 sp 00007fe29fffe980 error 4 in libestr.so.0.0.0[7fe2a63e5000+3000]
[ 1170.283805] rs:main Q:Reg[29986]: segfault at 0 ip 00007f0a22f443e5 sp 00007f0a2110a980 error 4 in libestr.so.0.0.0[7f0a22f43000+3000]
[ 1170.797558] rs:main Q:Reg[29995]: segfault at 0 ip 00007fc4ded1a3e5 sp 00007fc4dcee0980 error 4 in libestr.so.0.0.0[7fc4ded19000+3000]
[ 1171.291796] rs:main Q:Reg[30003]: segfault at 0 ip 00007f9e0174a3e5 sp 00007f9dff910980 error 4 in libestr.so.0.0.0[7f9e01749000+3000]
```

**Comment by deoren** [comment]
Here are some log files generated without running valgrind and starting rsyslog normally.

[rsyslog-logs-i2127.zip](https://github.com/rsyslog/rsyslog/files/1507566/rsyslog-logs-i2127.zip)

**Comment by deoren** [comment]
Here is a another set of logs, one a standard full debug (enabled within conf) and the output of `valgrind rsyslogd -dn > /var/log/rsyslog-valgrind-debug.log 2>&1`

[rsyslog-valgrind-debug-i2127.zip](https://github.com/rsyslog/rsyslog/files/1507575/rsyslog-valgrind-debug-i2127.zip)

**Comment by deoren** [comment]
After some additional testing, it appears that I can toggle segfaults by removing the `ltrim()` call from this line:

```
set $.msg = ltrim($msg);
```

A longer example of how I was trying to use the `ltrim()` function can be found in [this conf file](https://github.com/deoren/rsyslog-examples/blob/475daafbb8d69e4c1bb07160feb559392a8e2680/rsyslog-i545.conf#L95) that I posted to rsyslog/rsyslog#545:

**Comment by rgerhards** [comment]
@jgerhards it looks like there is an issue in ltrim. Can you have a look?

**Comment by rgerhards** [comment]
@deoren sorry, I think we cannot make that in tomorrow's release - problem?

**Comment by deoren** [comment]
@rgerhards I understand. I wouldn't want to rush a quick fix into a release for the next day either. 

@jgerhards @alorbach Please let me know if you need any additional info to help reproduce this.

**Comment by deoren** [comment]
Built from source (88d52eae3ba7eb74b3aef659c43ade04331bab9a) using these steps:

1. rsyslog_conf_url="https://raw.githubusercontent.com/deoren/rsyslog-examples/master/github_issues/rsyslog-i2127.conf"
2. rsyslog_conf_file=$(basename ${rsyslog_conf_url})
3. service rsyslog stop
4. sudo apt-get update
5. sudo apt-get -y install libtool autoconf automake valgrind git-core build-essential pkg-config libestr-dev zlib1g-dev uuid-dev libgcrypt20-dev liblogging-stdlog-dev libhiredis-dev uuid-dev libgcrypt11-dev liblogging-stdlog-dev flex bison libdbi-dev libmysqlclient-dev postgresql-client libpq-dev libnet-dev librdkafka-dev libgrok-dev libgrok1 libgrok-dev libpcre3-dev libtokyocabinet-dev libglib2.0-dev libmongo-client-dev python-docutils valgrind
6. cd /tmp
7. rm -rf libfastjson libestr rsyslog
8. git clone https://github.com/rsyslog/libfastjson
9. cd libfastjson/
10. sh autogen.sh CFLAGS="-g"
11. make
12. sudo make install
13. cd /tmp
14. git clone https://github.com/rsyslog/libestr
15. cd libestr/
16. sh autogen.sh CFLAGS="-g"
17. make
18. sudo make install
19. cd /tmp
20. git clone https://github.com/rsyslog/rsyslog
21. cd rsyslog
22. sh autogen.sh CFLAGS="-g" --disable-generate-man-pages
23. make
24. sudo make install
25. wget ${rsyslog_conf_url} -O /tmp/${rsyslog_conf_file}
26. valgrind rsyslogd -dn -f /tmp/${rsyslog_conf_file}

Listing them explicitly in case I've done something wrong.

Tail end of the output:

```
0867.065373711:main thread    : rsyslogd.c: ----RSYSLOGD INITIALIZED
0867.066126351:76be700: debug.c: thread created, tid 24593, name 'in:imuxsock'
0867.066826317:76be700: ../threads.c: set thread name to 'in:imuxsock'
0867.088263732:imuxsock.c     : imuxsock.c: --------imuxsock calling select, active file descriptors (max 5): 
0867.088410736:7abf700: debug.c: thread created, tid 24594, name 'in:imfile'
0867.088540790:7abf700: ../threads.c: set thread name to 'in:imfile'
0867.088988455:imfile.c       : imfile.c: imfile: working in inotify mode
0867.090627026:imfile.c       : imfile.c: imfile: dirsAdd added dir 0 to dirs table: '/var/log/apt'
0867.098530117:imfile.c       : imfile.c: imfile: inotify fd 7
0867.100369064:imfile.c       : imfile.c: imfile: enter into wdmap[0]: wd 1, dir 0, lstn DIRECTORY:/var/log/apt
0867.110319906:imfile.c       : imfile.c: imfile: in_setupDirWatch: watch 1 added for dir /var/log/apt(Idx=0)
0867.112763729:imfile.c       : imfile.c: imfile: adding file '/var/log/apt/term.log' to configured table
0867.112869339:imuxsock.c     : imuxsock.c: 5 
0867.118948773:imfile.c       : imfile.c: imfile: associated file [/var/log/apt/term.log] to directory 0[/var/log/apt], Active = 0
0867.121983873:imfile.c       : ratelimit.c: ratelimit:imfile[/var/log/apt/term.log]:new ratelimiter:bReduceRepeatMsgs 0
0867.123428622:imuxsock.c     : imuxsock.c: Message from UNIX socket: #5, size 63
0867.135269702:imfile.c       : imfile.c: imfile: enter into wdmap[1]: wd 2, dir -1, lstn FILE:/var/log/apt/term.log
0867.135583407:imfile.c       : imfile.c: imfile: watch 2 added for file /var/log/apt/term.log
0867.135889376:imfile.c       : imfile.c: imfile: associated file [/var/log/apt/term.log] to directory 0[/var/log/apt], Active = 1
0867.136755401:imfile.c       : imfile.c: imfile: getStateFileName for '/var/log/apt/term.log'
0867.141756243:imfile.c       : imfile.c: imfile: trying to open state for '/var/log/apt/term.log', state file 'imfile-state:-var-log-apt-term.log'
0867.145488607:imfile.c       : stream.c: file stream /var/spool/rsyslog/imfile-state:-var-log-apt-term.log params: flush interval 0, async write 0
0867.184948493:imfile.c       : stream.c: file '/var/spool/rsyslog/imfile-state:-var-log-apt-term.log' opened as #8 with mode 384
0867.186060132:imuxsock.c     : main Q: queue.c: qqueueAdd: entry added, size now log 1, phys 1 entries
0867.193163142:imfile.c       : strm 0x6198210: stream.c: opened file '/var/spool/rsyslog/imfile-state:-var-log-apt-term.log' for READ as 8
0867.194060669:imfile.c       : strm 0x6198210: stream.c: file 8 read 236 bytes
0867.232745197:imfile.c       : stream.c: file stream /var/log/apt/term.log params: flush interval 0, async write 0
0867.236122544:82c0700: debug.c: thread created, tid 24595, name 'rs:main Q:Reg'
0867.236472203:imuxsock.c     : wtp.c: main Q:Reg: started with state 0, num workers now 1
0867.239888056:main Q:Reg/w0  : wti.c: wti 0x616f500: worker starting
==24592== Thread 3 in:imfile:
==24592== Invalid read of size 1
==24592==    at 0x5CE3CC0: vfprintf (vfprintf.c:1632)
==24592==    by 0x5D0BA48: vsnprintf (vsnprintf.c:114)
==24592==    by 0x457D62: r_dbgprintf (debug.c:1028)
==24592==    by 0x70B6F6A: ??? (in /usr/lib/rsyslog/imfile.so)
==24592==    by 0x70B771C: ??? (in /usr/lib/rsyslog/imfile.so)
==24592==    by 0x70B7C87: ??? (in /usr/lib/rsyslog/imfile.so)
==24592==    by 0x70B9242: ??? (in /usr/lib/rsyslog/imfile.so)
==24592==    by 0x70B93AD: ??? (in /usr/lib/rsyslog/imfile.so)
==24592==    by 0x488A0C: thrdStarter (threads.c:220)
==24592==    by 0x505B6B9: start_thread (pthread_create.c:333)
==24592==    by 0x5D9C3DC: clone (clone.S:109)
==24592==  Address 0x100000002 is not stack'd, malloc'd or (recently) free'd
==24592== 
==24592== 
==24592== Process terminating with default action of signal 11 (SIGSEGV)
==24592==  Access not within mapped region at address 0x100000002
==24592==    at 0x5CE3CC0: vfprintf (vfprintf.c:1632)
==24592==    by 0x5D0BA48: vsnprintf (vsnprintf.c:114)
==24592==    by 0x457D62: r_dbgprintf (debug.c:1028)
==24592==    by 0x70B6F6A: ??? (in /usr/lib/rsyslog/imfile.so)
==24592==    by 0x70B771C: ??? (in /usr/lib/rsyslog/imfile.so)
==24592==    by 0x70B7C87: ??? (in /usr/lib/rsyslog/imfile.so)
==24592==    by 0x70B9242: ??? (in /usr/lib/rsyslog/imfile.so)
==24592==    by 0x70B93AD: ??? (in /usr/lib/rsyslog/imfile.so)
==24592==    by 0x488A0C: thrdStarter (threads.c:220)
==24592==    by 0x505B6B9: start_thread (pthread_create.c:333)
==24592==    by 0x5D9C3DC: clone (clone.S:109)
==24592==  If you believe this happened as a result of a stack
==24592==  overflow in your program's main thread (unlikely but
==24592==  possible), you can try to increase the size of the
==24592==  main thread stack using the --main-stacksize= flag.
==24592==  The main thread stack size used in this run was 8388608.
==24592== 
==24592== HEAP SUMMARY:
==24592==     in use at exit: 1,077,619 bytes in 1,453 blocks
==24592==   total heap usage: 2,052 allocs, 599 frees, 1,163,801 bytes allocated
==24592== 
==24592== LEAK SUMMARY:
==24592==    definitely lost: 0 bytes in 0 blocks
==24592==    indirectly lost: 0 bytes in 0 blocks
==24592==      possibly lost: 864 bytes in 3 blocks
==24592==    still reachable: 1,076,755 bytes in 1,450 blocks
==24592==         suppressed: 0 bytes in 0 blocks
==24592== Rerun with --leak-check=full to see details of leaked memory
==24592== 
==24592== For counts of detected and suppressed errors, rerun with: -v
==24592== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
==24592== could not unlink /tmp/vgdb-pipe-from-vgdb-to-24592-by-root-on-???
==24592== could not unlink /tmp/vgdb-pipe-to-vgdb-from-24592-by-root-on-???
==24592== could not unlink /tmp/vgdb-pipe-shared-mem-vgdb-24592-by-root-on-???
```

Log files: [rsyslog-valgrind-logs-88d52ea.zip](https://github.com/rsyslog/rsyslog/files/1507792/rsyslog-valgrind-logs-88d52ea.zip)

**Comment by deoren** [comment]
Thanks! Just tested the latest nightly and (as you already know based on your results) the problem appears to be resolved.
