### ISSUE TITLE
Error message when using RepeatedMsgReduction with multithreaded imudp input

### ISSUE THREAD

**Issue by andrewthad** [rsyslog/rsyslog#2132]
We recently ran into an issue where multithreaded imudp input would crash. I came across a [solution from the mailing list](http://lists.adiscon.net/pipermail/rsyslog/2015-August/040965.html). Like most people, we had no reason to have RepeatedMsgReduction on, so the solution works fine for us. It would be nice if, instead of attempting to run when these incompatible settings are used, rsyslog would fail earlier with a message explaining that the two are incompatible.

cc @tmahany419

**Comment by deoren** [comment]
Related to #441?

**Comment by andrewthad** [comment]
Very related. I guess the difference is that that issue is looking for an actual fix, while I would be content with just a better error message. It doesn’t really matter to me whether or not I’m able to use repeated message reduction.

**Comment by rgerhards** [comment]
Thanks for the bug report. I was tied up with quite a bit of other important things, but will now try to look at this ASAP. I think I have an idea of what it may be...

**Comment by rgerhards** [comment]
@andrewthad could you give the fix a try? Would be best if we can confirm in practice...

**Comment by andrewthad** [comment]
I’ll make some time to try it out this week. Thanks.

**Comment by rgerhards** [comment]
Thx!

Note: the issue will be auto-closed when I merge the PR. Please still report back. If the issue persists, I'll re-open!
