### ISSUE TITLE
Multiple brokers with omkafka and security.protocol=ssl

### ISSUE THREAD

**Issue by harperlangston** [rsyslog/rsyslog#2138]
Reviewing prior issues, I was able to set the proper ca.location and keys with ssl security.  But, I cannot figure out if there is a way to have multiple brokers with security.protocol=ssl.

Is it possible to pass multiple ca locations, or is the only way to do this presently is with one broker per action?

**Comment by rgerhards** [comment]
forgive my ignorance, but you want to set these via the ```confParam=[]``` configuration attribute?

**Comment by harperlangston** [comment]
Yes - I was trying to set the ssl.ca.location in confParam (to pass to librdkafka) to use TLS security.  It works for a single broker, but for more than one broker with security fails unless there is some other way to set the CA locations.

I think one way to do it may be to have multiple actions per ruleset with one action for each broker, all on the same topic.  But, I didn't know if there was something more elegant.

**Comment by rgerhards** [comment]
OK - actually, we simply pass these parameters through to the kafka client (https://github.com/edenhill/librdkafka to be precise) and it acts on them. I do not know if that is supported by the kafka client for a single instance. Maybe you can check it out there.

From rsyslog PoV, different actions open different kafka handles, so they can have different settings.

Does that help at least a little bit?

**Comment by harperlangston** [comment]
Thanks  - it is helpful.  It looks like they treat the TLS security a little differently for the omkakfka module as a client than they do for native Kafka.  I will check with them if this is something they have in the pipeline for consistency.

It seems if there is a single root CA, we can get away with how it is now.  Thanks again!
