### ISSUE TITLE
rsyslogd 7.x (and probably 8.x) will fail to log if $WorkDirectory does not exist

### ISSUE THREAD

**Issue by und1sk0** [rsyslog/rsyslog#215]
rsyslogd starts without error regardless if WorkDirectory exists, quietly and happily does nothing if it doesn't.

if WorkDirectory doesn't exist, daemon should either (1) complain and fail or (2) create the WorkDirectory if possible and (2a) complain and fail if not.

**Comment by rgerhards** [comment]
The currently supported versions of rsyslog log a message in this case.

**Comment by rgerhards** [comment]
I re-read the title. Do you mean no logging happens if the directory does not exist? This sounds extremely strange. Can you see if you can reproduce this with the current 8.7.0 release? Thx.

**Comment by und1sk0** [comment]
Yes, give me a day or two to valid this on several different versions of rsyslog (include the current stable).

This behavior is observed on SmartOS 1.8 systems within the Joyent SmartDataCenter.
