### ISSUE TITLE
RFE: Add ability to optionally include specific files via direct reference (e.g., not via wildcard)

### ISSUE THREAD

**Issue by deoren** [rsyslog/rsyslog#2151]
## Current functionality

1. `$IncludeConfig /etc/rsyslog.d/*.conf`
1. `$IncludeConfig /path/to/file/that/must/exist/or/rsyslog/will/complain/rsyslog-forward-to-test-receiver.conf`

The first allows for conditional loading if files are found by wildcard match, or not if they're not matched (e.g., file.conf.disabled).

## New functionality (concept)

- `$IncludeOptionalConfig /etc/rsyslog-forward-to-test-receiver.conf`

It could be combined with the existing functionality like this:

```
$IncludeOptionalConfig /etc/rsyslog-forward-to-test-receiver.conf
$IncludeConfig /etc/rsyslog-forward-to-prod-receiver.conf
```

If the test conf is found, then forwarding to the test node would be enabled, otherwise only forwarding to the prod node. 

I know similar functionality could be enabled via environment variables or some other conditional check, but the ability to use a directive like `$IncludeOptionalConfig` would open up the potential for conditional loading of modules, inputs and other items not (AFAIK) currently possible with the existing configuration support.

**Comment by rgerhards** [comment]
When we implement this, we should probably provide a new-style counterpart to $includeConfig and control the optionality via a parameter.
