### ISSUE TITLE
Unable to install rsyslog-8.17 in Suse Linux Enterprise server 11

### ISSUE THREAD

**Issue by dpkkumar01** [rsyslog/rsyslog#2162]
I am trying to install rsyslog-8.17 in Suse linux-11 (64 bit).  I am getting the below error in command line while checking the version.

 # rsyslogd -v
rsyslogd: /lib64/libpthread.so.0: version `GLIBC_2.12' not found (required by rsyslogd)

lrwxrwxrwx 1 root root 20 Dec  4 10:50 /lib64/libpthread.so.0 -> libpthread-2.11.3.so

I have GLIBC 2.11 in my machine and my gcc version is 4.3.4.

Can some one help me to overcome this installation issue.

**Comment by halfer** [comment]
What command did you use to install Rsyslog?

At a guess, if it need glibc, then it would need `libglib2.0-0` or `libglib2.0-dev`. You could try installing one or both of those manually, though your repository manager should have resolved these dependencies for you.

**Comment by rgerhards** [comment]
no response
