### ISSUE TITLE
rsyslogd: imfile: error with inotify API, ignoring file '/xxx.log': No space left on device  [v8.28.0]

### ISSUE THREAD

**Issue by zhs077** [rsyslog/rsyslog#2166]
my disk space is enough, receiver disk space is enough;
how?

**Comment by rgerhards** [comment]
thx for the report. Which OS is this on?

@alorbach can you please consider this in your current imfile work

**Comment by alorbach** [comment]
This error can happen when there is free diskspace but no more free INODES available. 
Please run: df -i

It will show you how many inodes are in use and free.

**Comment by rgerhards** [comment]
@zhs077 I assume @alorbach answered your question. If the problem still persists, please report back. I'll then re-open the issue.

**Comment by bmy4415** [comment]
Hi, I'm getting similar error with this.
```

**Comment by rgerhards** [comment]
The version you are using is very old and no longer supported by the community. It is also very probable that the issues stems back to a long-solved issues. As such, please update to the currently supported version and retry. Report back if the problem persists.

The rsyslog project provides packages for current versions: https://www.rsyslog.com/downloads/download-other/

If you insist on using an outdated version, you can also contact your distro or consider [rsyslog professional services](https://www.rsyslog.com/professional-services/enterprise-support/).

Please also note that you are reporting to an old and solved issue. If you have problems with the new version, I strongly recommend to open a new issue instead.
