### ISSUE TITLE
has timestamp format changed in 8.31

### ISSUE THREAD

**Issue by staylor-au** [rsyslog/rsyslog#2169]
Upgraded from 8.24 to 8.31 and it appears that the timestamp format has changed .. or perhaps additional config is needed ?

8.24 messages format output is:
Dec  5 20:35:50 host.name.com blahblah rest of message

8.31 output now:
2017-12-06T17:53:09.400531+11:00 host.name.com blahblah rest of message

message template format:
template(name="rfc3164mode" type="string"
         string="<%PRI%>%TIMESTAMP:::date-rfc3339% %FROMHOST% %syslogtag:1:32%%msg:::sp-if-no-1st-sp%%msg%"
        )

Thanks

**Comment by rgerhards** [comment]
It looks like the template you mention was never applied, because neither format matches.

Which Distro are you on? Where did you install rsyslog from?

**Comment by staylor-au** [comment]
solved. the syslog.conf had an incorrect configuration. No problem now. Thanks

**Comment by rgerhards** [comment]
thanks for letting us know, appreciated!
