### ISSUE TITLE
rsyslog hostname resolved localhost when set /etc/hosts to  `127.0.0.1 localhost xxxx`

### ISSUE THREAD

**Issue by stanxing** [rsyslog/rsyslog#2200]
Bug Report:
version: rsyslog 8.16.0
system: ubuntu 16.04

Reproduce steps:
1.root@stanxing:~# hostname
stanxing
2. vim /etc/hosts:
127.0.0.1 localhost stanxing
3. systemctl restart rsyslog.service
4. logging some syslog ('docker rm -f' can make some kernerl log) 

Expected result:
-  the hostname should be stanxing.

Actual result:
- Dec 12 16:30:12 localhost kernel: [2438526.858400] aufs au_opts_verify:1597:dockerd[29143]: dirperm1 breaks the protection by the permission bits on the lower branch

Supplement
1. when I modify /etc/hosts as following:
  127.0.0.1 localhost 
  127.0.0.1 stanxing
 The log as expected and hostname is correct
2. when I remove ' 127.0.0.1 stanxing'
 The log as expected and hostname is correct

I don't know why this is so and is it a  bug?

**Comment by rgerhards** [comment]
Thanks for the bug report. This was fixed roughly a year ago in commit faca48813a84ae9b50d996b158030e5ef5f8468f. Please upgrade to at least 8.23.0 (8.31.0 is current). If you can't please file a bug with your distro and quote this bug tracker, so the package maintainer knows what to backport. Thanks!

**Comment by rgerhards** [comment]
Mhhh.. I may have mis-read the description. Anyways, let me know if the issue persists with 8.31.0, I'll then re-open the bug tracker.

**Comment by davidelang** [comment]
when you ask /etc/hosts for a hostname for a given IP address, it returns the 
first name on the line

if you were to change it to

127.0.0.1 stanxing localhost

it should do what you are wanting
