### ISSUE TITLE
rsyslog stop collect log after log file is rotated by logrotate in inotify mode

### ISSUE THREAD

**Issue by jipengzhu** [rsyslog/rsyslog#2202]
i write a script to test it

#  Condition
### log script
```
[root@log-shipper rsyslog-check]# cat gen_log.sh
if [ $# -ne 1 ]; then
	echo "require only one param which is output file path"
	exit 1
fi

file_path=$1
file_count=9
file_size=$((3 * 1024))

auto_rotate=0

while true
do
	for i in {1..10000}
	do
		echo "test message ${i}" >> ${file_path}
		sleep 0.5

		if [ $(wc -c ${file_path} | awk '{print $1}') -gt ${file_size} -a ${auto_rotate} -gt 0 ]; then
			echo "start rotate"

			j=${file_count}
			while [ ${j} -gt 0 ]
			do
				old_path="${file_path}.${j}"
				if [ -e "${old_path}" ]; then
					new_path="${file_path}.$((${j} + 1))"
					echo "mv ${old_path} ${new_path}"
					mv "${old_path}" "${new_path}"
				fi

				j=$((j - 1))
			done

			echo "mv ${file_path} ${file_path}.1"
			mv "${file_path}" "${file_path}.1"

			out_path="${file_path}.$((${file_count} + 1))"
			if [ -e "${out_path}" ]; then
				echo "rm ${out_path}"
				rm -f "${out_path}"
			fi

			echo "end rotate"
		fi
	done
done
```

auto_rotate enviroment  is to decide rotating log file by script or logrotate

### start script 
```
sh gen_log.sh /tmp/test.log
```

### logrotate config
```
[root@log-shipper rsyslog-check]# cat /etc/logrotate.d/test_rsyslog
/tmp/test.log {
rotate 9
size 3k
nodateext
}
```

### logrotate script
```
[root@log-shipper rsyslog-check]# cat cron_log.sh
while true
do
logrotate /etc/logrotate.conf
sleep 5
done
```

### start script
```
sh cron_log.sh
``` 

### rsyslog config
use inotify mode and reopenOnTruncate param

```
[root@log-shipper rsyslog-check]# grep inotify /etc/rsyslog.conf
module(load="imfile" mode="inotify")

[root@log-shipper rsyslog-check]# cat /etc/rsyslog.d/HaiZhi-_test.conf
# Config Start
$WorkDirectory /var/spool/rsyslog

$MainMsgQueueWorkerThreads 1
$ActionQueueWorkerThreads 1
$MainMsgQueueDequeueBatchSize 30
$MainMsgQueueDequeueSlowdown 1000
$MaxMessageSize 64k

input(type="imfile"
      File="/tmp/test.log"
      Tag="test_token_test"
      Severity="info"
      PersistStateInterval="20000"
      reopenOnTruncate="on"
      )

template (name="HaiZhiFormat_test_token_test" type="string" string="<%pri%>%protocol-version% %timestamp:::date-rfc3339% %HOSTNAME% %app-name% %procid% %msgid% %$!metadata!filename% [test_token@32733 tag=\"bqd_log\"] %msg%\n")

# Send message to HaiZhi and discard it
if $programname == 'test_token_test' then action(type="omfwd" protocol="tcp" target="192.168.128.152" port="5140" template="HaiZhiFormat_test_token_test")
if $programname == 'test_token_test' then ~
```

### rsyslog version
```
[root@log-shipper rsyslog-check]# rsyslogd -v | head -n 2
rsyslogd 8.16.0, compiled with:
	PLATFORM:				x86_64-redhat-linux-gnu
```
### start rsyslog
```
[root@log-shipper rsyslog-check]# cat start_rsyslog.sh
rm -f /var/log/rsyslog

RSYSLOG_DEBUGLOG="/var/log/rsyslog" RSYSLOG_DEBUG="Debug" rsyslogd -d -n -i /var/run/test_rsyslog.pid &>/dev/null
```

# Question
## Problem
when i use logrotate to rotate log file ,  rsyslog stop collect log after log file is rotated by logrotate in inotify mode, the inode has changed and the size is small than the old

i find some debug info 
```
6514.821980548:imfile.c       : file was CREATED: logrotate_temp.WMG3fJ
6514.822002314:imfile.c       : imfile: handle dir event for /tmp
6514.822011457:imfile.c       : imfile: fileTableSearch file 'logrotate_temp.WMG3fJ' - '(null)', found:-1
6514.822026694:imfile.c       : imfile: file 'logrotate_temp.WMG3fJ' not active in dir '/tmp'
6514.822064143:imfile.c       : imfile: fileTableSearch file 'logrotate_temp.WMG3fJ' - 'test.log', found:-1
6514.822067706:imfile.c       : imfile: file 'logrotate_temp.WMG3fJ' not associated with dir '/tmp'
6514.822072047:imfile.c       : watch IN_MOVED_FROM
6514.822075037:imfile.c       : imfile: fileTableSearchNoWildcard file 'logrotate_temp.WMG3fJ' - '(null)', found:-1
6514.822077727:imfile.c       : imfile: IN_MOVED_FROM Event (ftIdx=-1, name=logrotate_temp.WMG3fJ)
6514.822080130:imfile.c       : watch IN_DELETE
6514.822082622:imfile.c       : imfile: handle dir event for /tmp
6514.822085244:imfile.c       : imfile: fileTableSearch file 'test.log.10' - '(null)', found:-1
6514.822087871:imfile.c       : imfile: deleted file 'test.log.10' not active in dir '/tmp'
6587.879501116:main thread    : janitorRun() called
```
rsyslog detect a new file named with `logrotate_temp.WMG3fJ`, not my file named with `test.log`

## OK 
when i use my script to rotate log file, rsyslog is ok

when i use polling mode, rsyslog is ok

## Help
i am unfamiliar with  logrotate, so is anyone tell me why it is

**Comment by rgerhards** [comment]
> rsyslogd 8.16.0,

You need to get to a more recent rsyslog version. Current is 8.31. I close the tracker for now, please let us know if the problem persists after upgrade. I'll then re-open. Thanks!

**Comment by jipengzhu** [comment]
@rgerhards 

1. the log is written to a file under a directory which contains date info 
2. so we make a soft link with it  and change the link every day with crontab
3. and we use rsyslog to collect the soft link file with inotify mode 

the rsyslog will stop to collect log in the next day 

in my understood, the inotify mode can't detect the change of the directory linked by a soft link in the  next day

is it right ?

**Comment by rgerhards** [comment]
> in my understood, the inotify mode can't detect the change of the directory linked by a soft link in the next day

IIRC that was the case. I think there is an issue open for that. Note that we will refactor imfile most probably in the 8.33 (next release) timeframe.

**Comment by rgerhards** [comment]
https://github.com/rsyslog/rsyslog/projects/4 is the refactoring project with issue links.

**Comment by davidelang** [comment]
On Fri, 5 Jan 2018, 朱继鹏 wrote:

> @rgerhards
>
> 1. the log is written to a file under a directory which contains date info
> 2. so we make a soft link with it  and change the link every day with crontab
> 3. and we use rsyslog to collect the soft link file with inotify mode
>
> the rsyslog will stop to collect log in the next day
>
> in my understood, the inotify mode can't detect the change of the directory linked by a soft link in the  next day

As I understand things, inotify will not detect that the target of a softlink 
has changed, it's only looking for changes in the files/directories that are 
specified, not other directories/files that are pointed to via a soft link.

**Comment by jipengzhu** [comment]
> As I understand things, inotify will not detect that the target of a softlink
has changed, it's only looking for changes in the files/directories that are
specified, not other directories/files that are pointed to via a soft link.


so is there a way to solve it ? 

will you  provide a mechanism to detect the the target of a symlink has changed ?

for example, assign a signal to do it

this is a common situation，restarting is not an elegant solution

**Comment by davidelang** [comment]
just from a theoretical point of view, you would have to find all the symlinks, 
and then setup inotify on all the targets of the symlinks.

you would need to track that that target was tied to that symlink so that if the 
symlink changes, you stop tracking the target file.

and if the symlink is pointing to a symlink, you need to do the whole thing 
again.

detecting that files that are the destinations of symlinks have changes has 
always been problematic (and relativly expensive) as far as I know.

**Comment by rgerhards** [comment]
First thing to get this into the imfile work is to create an on-the-spot github issue for this. This closesed and fuzzy one here does not help put the feature request into the spotlight ;-)

That said, I can envison it is done. Of course, it costs some performance but there is a price for everything .. and people willing to pay it.
