### ISSUE TITLE
omstdout.so module is not being installed in CentOS 6

### ISSUE THREAD

**Issue by mashayev** [rsyslog/rsyslog#2203]
Hey,

When installing `CentOS 6`, the `omstdout.so` module is not being installed as part of `rsyslog` installation. In `CentOS 7` it's being installed by default.

Any reason why?

How can I add this module to `CentOS 6`?

**Comment by rgerhards** [comment]
I guess it accidently slipped into CentOS7. It's a testbench tool. Do you really have a use for it?

**Comment by mashayev** [comment]
@rgerhards I do have a use case for it in Docker environment.
I found another way to achieve it.

Thanks.

**Comment by rgerhards** [comment]
Could you elaborate on the use case? We always try to understand what might be needed...

**Comment by cfann61CW** [comment]
@rgerhards  I was trying to use omstdout to get centralized logging working quickly on Google's Kubernetes engine.  Default logging mechanism takes all stdout/stderr from docker containers.  I was struggling to find a way for my proxy (haproxy) to log to stdout

**Comment by rgerhards** [comment]
Thx for the explanation, this makes sense!

**Comment by rgerhards** [comment]
@friedl can you please create packages for these.

**Comment by rgerhards** [comment]
Note: I need to review the code if it is really production grade.

**Comment by friedl** [comment]
I have re-built the rsyslog RPM for EL6. It is now version 8.32.0-2.

In this one, I enable omstdout. It should be available now.

**Comment by rgerhards** [comment]
@friedl I think we should package it as a separate package. It is of use only and only if used in a container environment.

**Comment by friedl** [comment]
EL6 RPMs updated accordingly.

omstdout is now available by installing rsyslog-omstdout.

**Comment by rgerhards** [comment]
excellent! Can you do the same for CentOS 7?

**Comment by rgerhards** [comment]
... and Ubuntu btw ;-) ... when they will ever get Launchpad working again...

**Comment by friedl** [comment]
In CentOS 7 it is already distributed through the base package, that's how they did it in the base repo, too.

Ubuntu is on the list for whenever Launchpad works again ;)

**Comment by friedl** [comment]
The builds for rsyslog 8.32.0 on Ubuntu are currently in the queue and should be finished later today. The next daily build will have the omstdout module as well.

All builds can use omstdout by additionaly installing
`rsyslog-omstdout
`

The only exception is the build for EL7, which has omstdout delivered with the core rsyslog RPM.

**Comment by rgerhards** [comment]
Excelent, thx
