### ISSUE TITLE
Make all valgrind tests have a -vg.sh suffix

### ISSUE THREAD

**Issue by mbiebl** [rsyslog/rsyslog#2212]
If valgrind is available, the test suite runs an additional set of tests. Almost all of those tests have a -vg.sh suffix. This makes it rather simple to spot which tests are related to valgrind. 
Notable exceptions are

internal-errmsg-memleak.sh
unused_lookup_table.sh
imfile-basic-vgthread.sh

I'm not sure if that is deliberate and there is a good reason for this. If not, please consider renaming those 3 tests for consistencies sake

**Comment by rgerhards** [comment]
> internal-errmsg-memleak.sh
> unused_lookup_table.sh

probably overlooked -- thanks!

> imfile-basic-vgthread.sh

actually ```-vgthread``` is the first in a series of valgrind (vg) test that use the helgrind (thread) debugger. Sorry for not mentioning this.

I guess it would make sense to add the convention to CONTRIBUTING and maybe a README file? :-)
