### ISSUE TITLE
imfile module：read the message from the end of the file

### ISSUE THREAD

**Issue by lishengjia** [rsyslog/rsyslog#2220]
How config imfile module read the message from the end of the file?

**Comment by rgerhards** [comment]
I am sorry, I do not understand the question. Can you try to re-phrase?

**Comment by lishengjia** [comment]
For example, the command(start_position) for file input plugin for logstash. The default behavior(start_position => end) treats files like live streams and thus starts at the end.


https://www.elastic.co/guide/en/logstash/current/plugins-inputs-file.html#plugins-inputs-file-start_position

**Comment by rgerhards** [comment]
Thanks, now I understand.  Use parameter ```freshStartTail```.
doc: http://www.rsyslog.com/doc/v8-stable/configuration/modules/imfile.html

**Comment by lishengjia** [comment]
@rgerhards  Thanks very much. Does the old version(v5 or v7 ) have a support configuration?

**Comment by rgerhards** [comment]
@lishengjia no, it was introduced in 8.18 in April 2016.

**Comment by lishengjia** [comment]
@rgerhards  ok.Thanks!
