### ISSUE TITLE
script: add new function to_hex()

### ISSUE THREAD

**Issue by rgerhards** [rsyslog/rsyslog#2224]
This should convert the provided integer value to a hexadecimal string representation.

**Comment by jay7x** [comment]
Can we have some hashing functions as well? It's frequently used to distribute flow evenly between multiple rulesets/receivers. For now it's hard to do using RainerScript only w/o external modules.

**Comment by rgerhards** [comment]
Please open a new issue for it  :-)

**Comment by davidelang** [comment]
another useful function to distribute traffic would be a random() function. In 
addition, it could be used to be able to do things like "log 1% of traffic" on a 
high volume server

**Comment by rgerhards** [comment]
@davidelang actually, ```random()``` exists, I think for quite a while. Maybe doc is missing (could not check right now).
