### ISSUE TITLE
omfile with DynaFile parameter truncates file path to 200 bytes

### ISSUE THREAD

**Issue by Dieken** [rsyslog/rsyslog#2228]
tools/omfile.c uses macro MAXFNAME which is 200 defined in runtime/syslogd-types.h,  I'm not sure which line truncates my /very/long/file/path.

Probably these lines in tools/omfile.c, prepareFile():
```
 609     /* the copies below are clumpsy, but there is no way around given the
 610      * anomalies in dirname() and basename() [they MODIFY the provided buffer...]
 611      */
 612     uchar szNameBuf[MAXFNAME+1];
 613     uchar szDirName[MAXFNAME+1];
 614     uchar szBaseName[MAXFNAME+1];
 615     ustrncpy(szNameBuf, newFileName, MAXFNAME);
 616     szNameBuf[MAXFNAME] = '\0';
 617     ustrncpy(szDirName, (uchar*)dirname((char*)szNameBuf), MAXFNAME);
 618     szDirName[MAXFNAME] = '\0';
 619     ustrncpy(szNameBuf, newFileName, MAXFNAME);
 620     szNameBuf[MAXFNAME] = '\0';
 621     ustrncpy(szBaseName, (uchar*)basename((char*)szNameBuf), MAXFNAME);
 622     szBaseName[MAXFNAME] = '\0';
```

**Comment by Dieken** [comment]
I have a DynaFile template "/very/long/path-YYYY-mm-dd-HH", this bug breaks my hourly log rotation,  the file size of truncated file path "/very/long/path-YYYY" keeps increasing :-(

**Comment by rgerhards** [comment]
Thanks for the report. This seems not to be intentional. Nevertheless the question: what is your platform?

**Comment by Dieken** [comment]
@rgerhards  I'm using Ubuntu 14.04 and Ubuntu 16.06,  thanks for your quick response!

**Comment by davidelang** [comment]
I've seen OS limits in that range (250 or so characters IIRc), so this may 
actually be an OS limitation you are running into instead of a rsyslog one

doing a little googling, the max file name length in linux is 255 characters, 
and max path size is 4096 characters, but there is some ability to change these.

On other operating systems, the limits are going to be different.

**Comment by Dieken** [comment]
@davidelang Yes, different OSes have different limits, and people can change the limit(but I doubt anybody will change).

On Linux there is function to check the limits: http://man7.org/linux/man-pages/man3/pathconf.3.html, but I think it’s unnecessary to limit, if it’s too long the OS will fail the file operation.

Anyway, a hardcoded 200 characters path limit is not good.

**Comment by rgerhards** [comment]
> Anyway, a hardcoded 200 characters path limit is not good.

@davidelang for above reason, it's definitely a bug. I first thought it was a regeression where something from limits.h is not picked up properly, but it's actually a bit more complex (to review). A quick fix is to change the hardcoded value to 4k (linux), but I investigate if there is a better way to do it (probably not as it looks).

**Comment by rgerhards** [comment]
I kind of give up and do the "4k quick fix" -- everything else does not seem worth the effort. Saying so after code review.
