### ISSUE TITLE
imfile wildcard directory can't discover new files

### ISSUE THREAD

**Issue by Dieken** [rsyslog/rsyslog#2230]
I'm running Rsyslogd as Kubernetes DaemonSet to collect console log and file log,  I construct a directory layout with a cron job:

```
## console log
# can't directly symlink to log file due to #2229
/archive/NAMESPACE/DEPLOYMENT/POD/CONTAINER -> /var/lib/docker/containers/CONTAINER/

## file log
/archive/NAMESPACE/DEPLOYMENT/POD/logs -> /var/lib/kubelet/pods/POD_ID/volumes/kubernetes.io~empty-dir/
```

I tried wildcard directory `/archive/*/*/*/*/*/*.log` to collect file log, for example:
```
/archive/test/svcA/svcA-6d648bff95-22hgd/logs/log-vol/error.log
```

But when I create "new.log" in an existed matched directory "/archive/test/svcA/svcA-6d648bff95-22hgd/logs/log-vol/",  imfile in inotify mode can't automatically pick it.  Restarting Rsyslog works.

And newly created directory matching the wildcard directory also can't be automatically picked by Rsyslog.

I bypassed this issue to have a cron job to generate Rsyslog configuration files with wildcard file name "/archive/xxx/xxx/xxx/xxx/xxx/*.log", this works fine.

platform: Ubuntu 14.04 & 16.04 with ppa:adicson/v8-stable.

**Comment by rgerhards** [comment]
@alorbach it looks like we have some issues with files not being picked up in inotify mode. IIRC there have been other issues raised in the past weeks. Could you have a look? Maybe we can craft a dedicated testbench test? I *think* the issue came up not only with containers.

**Comment by davidelang** [comment]
I don't think we support lots of wildcards in the path (or did that get changed)

for a long time we didn't support any wildcards in the path, only in the 
filename, but since you are running a current rsyslog, you are running a new 
enough version to have that support. But I don't remember if it allowed multiple 
layers of wildcards.

**Comment by alorbach** [comment]
I can create a testcase for this scenario. perhaps there is a limit of wildcards that the GLOB api can handle here. The debug logfile will tell.

**Comment by alorbach** [comment]
Could not reproduce this issue yet. 
Maybe related to this bug as here https://github.com/rsyslog/rsyslog/issues/1716 ? 

When /archive/ does not exist on startup of rsyslog, it willl fail to detect /archive/test/ and all other subdirectories.

**Comment by khogeland** [comment]
Experiencing what appears to be the same issue.

File pattern is `/usr/spark/work/app-*/*/std*`. `/usr/spark/work` exists on startup as an empty directory. Files in that directory are not picked up when created, but are correctly found when restarting rsyslog.

**Comment by khogeland** [comment]
It doesn't appear to be consistent: I have 4 directories in `/usr/spark/work/app-foo/`, and all files from one of those directories were picked up.
