### ISSUE TITLE
[FEAUTURE REQUEST] use some hash for imstate-file file name

### ISSUE THREAD

**Issue by Dieken** [rsyslog/rsyslog#2231]
Currently imfile modue uses "imstate-file:-full-path-name" as state file name,  truncation happens for very long path name (seems max length of path name can be 4096 bytes).

It's better to use something like "imstate-file:SHA256" for the state file name,  imfile can double check the hash by calculating it from file path in the state file.

**Comment by rgerhards** [comment]
thanks. That is a good suggestion, but we must think a bit about backwards compatibility. To me personally, it's not an easy decision, but I tend towards your suggestion.

**Comment by rgerhards** [comment]
@kortemik @janmejay @davidelang @alorbach @taotetek @deoren ... and whoever I forgot -- what do you think? It also does not make immediately clear which state file this is for. On the other hand, it removes all potential error cases (path length, char escaping).

I set the milestone to 8.33, so we should decide in that time frame.

**Comment by deoren** [comment]
@rgerhards Is there a limit on the name parameter for imfile that would keep it from approaching the path name length restriction? Perhaps combine that value with the hash to build state files?

**Comment by davidelang** [comment]
since filenames can only be 255 bytes long, and paths can be 4096 bytes long, 
this is a problem.

But I don't like loosing the easy ability to see what file the statefile is for.

To preserve backwards compatibility, I would only use a hash if the full path 
name results in a filename that's 'too long'. That way all existing files 
continue to work and we only use the hash when we can't use the filename (and I 
would append the tail of the path name after the hash to try and have as much 
chance as possible of being able to identify what file it's for)

**Comment by Dieken** [comment]
@rgerhards  the imstate-file is created by imfile module: http://www.rsyslog.com/doc/v8-stable/configuration/modules/imfile.html#state-files

@deoren,  I did find imfile module truncated file name "/var/spool/rsyslog/imstate-file:-a-very-long-path", I don't know whether imfile has a smaller filename length limit than default OS limit 255.

@davidelang  Usually people won't check /var/spool/rsyslog often, Rsyslog should just work, but if necessary, we can easily grep the path name from the imstate-files.

@rgerhards @davidelang About the backward-compatibility, I like more this logic:
```
open-imstate-file(a-very-long-path) {
     a-possibly-truncated-file-name = "imstate-file:a-very-long-path-truncated-to-242"; # length of "imstate-file:" is 13.
     if (existed("/var/spool/rsyslog/a-possibly-truncated-file-name")) {
         read-whole-imstate-file();
     }
     open("/var/spool/rsyslog/imstate-file:SHA256(a-very-long-path)");
     write(state);
     if (success) unlink("/var/spool/a-possible-truncated-file-name")
}
```

So `/var/spool/rsyslog/imstate-file:*` won't mix two kinds of naming convention if all old imstate-files will be written again or the user has a cron job to delete too old imstate-files.

**Comment by kortemik** [comment]
We used to have md5sum based statefile names calculated from the imfile
path when we were using rsyslog version 5. But when wildcards came into the
picture we dropped the feature. We didn't encounter drawbacks at that time
but of course our use case was limited.

**Comment by alorbach** [comment]
I think it's actually a good Idea. You can migrate old statefiles automatically. SHA256 could be used or a simple 32/64Bit Checksum. I would go for something fast and simple. You can't see then which file the statefile belongs anymore, but you can track it by looking into the debug logfile if needed.

**Comment by kortemik** [comment]
One can figure out where the statefile belongs also with grep -R
'^+pszFName' /var/lib/rsyslog so i don't see that much of a problem!

**Comment by rgerhards** [comment]
OK, looks like there is consensus to move towards hashes. So let's do that :-)

**Comment by rgerhards** [comment]
I looked into implementing hashes, but as it looks libc does not provide any of the standard hashing functions. I looked for md5 and sha1 and the man pages referred to openssl. I do not like the idea of introducing a dependency on a crypto lib just for imfile. Does anybody know a solution? After all, md5sum seems to be present on any system, so... 

@andreasstieger @Whissi @mbiebl I would appreciate your thoughts as package maintainers on this topic. Would be great if you had a minute.

**Comment by rgerhards** [comment]
On backward compatibility: the refactoring introduced several non-backward compatible changes to the state file. While I really hate this, I think we should actually just document this and try not to hide it. Reason:

* we need to keep quite some old code and complexity to maintain once-at-startup compatibility with old state files
* it is uncertain how long we need to carry that bunch of code around as it will most probably take years for distros to pick up the new version (especially enterprise ones)
* as a result the complexity reduction from refactoring is mitigated

IMHO it is one of the rare occasions where the need to retain a one-time backward compatiblity on upgrade is not worth the cost it bears. Comments?

**Comment by rgerhards** [comment]
further researching my own question in https://github.com/rsyslog/rsyslog/issues/2231#issuecomment-376802013, I'll probably get away for the imfile use case with a simple has function we use in hash tables:
```
```
I think the number of collisions is really low enough that, taken together with the inode number, it should really be sufficient to identify a file. I'll probably take that route for now. Let me know if you disagree.

**Comment by mbiebl** [comment]
@rgerhards systemd uses siphash
https://en.wikipedia.org/wiki/SipHash
https://github.com/systemd/systemd/blob/master/src/basic/siphash24.c

Maybe something to take inspiration from?

**Comment by rgerhards** [comment]
@mbiebl thx for the pointer, that looks useful.

Reference implemenation is at https://github.com/veorq/SipHash

I just wonder if for our use case it has advantages over the very simple function Aaron Wiebe provided (my last posting). But granted, it's not a lot of code either, so probably no issue dragging it in.

**Comment by Whissi** [comment]
Or maybe use Blake2, already implemented in coreutils.

**Comment by kortemik** [comment]
https://github.com/curl/curl/blob/master/lib/md5.c#L174
<https://opensource.apple.com/source/Security/Security-28/AppleCSP/MiscCSPAlgs/MD5.c>

We at least need a way to convert from old format to new format, although
it can be a one time pass for the configured work-directory: to simplify
the new code, i would use the approach that we provide a conversion script
and refuse to start if working directory is not converted or empty.

**Comment by rgerhards** [comment]
> We at least need a way to convert from old format to new format, although
> it can be a one time pass for the configured work-directory: to simplify
> the new code, i would use the approach that we provide a conversion script
> and refuse to start if working directory is not converted or empty.

OK, then let's keep the old code - everything else is far more work and risk. Maybe I add a configure option so that this support can be disabled if a distro does not want it.

**Comment by davidelang** [comment]
if someone is trying to upgrade and has some state files in place, what should 
they do?
k

**Comment by rgerhards** [comment]
@davidelang yeah, @kortemik already made that point. That's why I am currently shuffling back the old code, so if the new file is not present, I fall back and do a check of the old one. In a sense I have just noticed that even means overall less work, as some refactoring and cleanup I had on my mind can now not happen ;-) I thought about redoing the imfile/stream integration, but that doesn't play well with the idea of old style state files - would have been the majority of the saving.

**Comment by Dieken** [comment]
And about the hash algorithms,  I feel a hash longer than 4 bytes and 8 bytes is safer,  blake2 mentioned by @Whissi  is a good candidate, it can generate variable length hash,  but it does introduce an extra dependency https://github.com/BLAKE2/libb2.

**Comment by rgerhards** [comment]
> Sorry I didn't follow the discussion in time, could you double think about the smooth migration solution mentioned in #2231 (comment) ?

The old code is used for old files (as a fallback), so this should be covered.
