### ISSUE TITLE
omfile: add option for dynfile actions to block

### ISSUE THREAD

**Issue by kortemik** [rsyslog/rsyslog#2236]
Currently omfile actions using dynfile do not block. Please add option to make them block. 

This will prevent data loss in case files can not be appended/created.

**Comment by rgerhards** [comment]
@kortemik I have just added a module-global option. I don't think it would make sense to change this on an action-by-action basis. If you disagree, please let me know.

**Comment by kortemik** [comment]
Module option is more than enough for us! Many thanks.
