### ISSUE TITLE
imfile: FEN Mode, expose error on stat failure of configured files? 

### ISSUE THREAD

**Issue by alorbach** [rsyslog/rsyslog#2249]
When static configured files do not exist on startup, they are checked in each processing loop in do_fen if they exist. On failure an error is printed into the debug log. 

```
		/* Get File Stats */
		if (!(revents & FILE_EXCEPTION) && stat(fobjp->fo_name, &statFile) == -1) {
			DBGPRINTF("fen_processEventFile: Failed to stat file: %s - errno %d\n",
				fobjp->fo_name, errno);
			ABORT_FINALIZE(RS_RET_FILE_NO_STAT);
		}

```

Question is should we LogError instead? it would generated an error each time the configured file is checked but does not exist.

**Comment by rgerhards** [comment]
@alorbach  can you please add a bit of context so that others can make a decision.  Thx

**Comment by alorbach** [comment]
Updated description

**Comment by rgerhards** [comment]
Question: did this also apply to the inotify case?

**Comment by alorbach** [comment]
I need to review the code in order to tell more.

**Comment by alorbach** [comment]
So one problem is that FEN API doesn't provide us a file name once a DIR update is processed. Or I am too stupid to find a property for the filename when something changes in a directory? I have searched the documentation up and down ;). 

So we check for all configured files when a change happens to the parent directory. 
If we would output a LogError here, it would be generated each time if a file is modified in the parent directory. This could become very busy. 

It would be easier to decide if there was a global LogError limit by module. For example max 10 errors in 60 minutes per module for example. In this case we could use LogError much more often without having to care about spamming ;).

**Comment by rgerhards** [comment]
@kortemik do you have an opinion on this issue?

**Comment by rgerhards** [comment]
> It would be easier to decide if there was a global LogError limit by module. For example max 10 errors in 60 minutes per module for example. In this case we could use LogError much more often without having to care about spamming ;).

well, there kind of is ;-) The internal message rate limiter trims messages. But it does not work on a per-module basis.

**Comment by kortemik** [comment]
I see the point, notify event's can come with quite high frequency and therefore log flood of misconfigured entires is very much a likely problem. But how often the DIR events get fired? Only when file is moved,removed,created and such?

http://www.sptci.com/docs/cpp/fen.html

**Comment by rgerhards** [comment]
First thing I see is this:
```
==28533== Process terminating with default action of signal 6 (SIGABRT)
==28533==    at 0x5CC6428: raise (raise.c:54)
==28533==    by 0x5CC8029: abort (abort.c:89)
==28533==    by 0x40EA23: rsyslogdDoDie (rsyslogd.c:1677)
==28533==    by 0x506538F: ??? (in /lib/x86_64-linux-gnu/libpthread-2.23.so)
==28533==    by 0x506135F: pthread_cond_wait@@GLIBC_2.3.2 (pthread_cond_wait.S:183
```
The SIGABRT is quite a bit bizarre. 

Next thing is a big leak:
```
==28533== 47,869,208 bytes in 193,021 blocks are still reachable in loss record 2,022 of 2,023
==28533==    at 0x4C2FB55: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==28533==    by 0x7EA4CD3: rd_kafka_op_new0 (in /usr/lib/rsyslog/imkafka.so)
==28533==    by 0x7EA8071: rd_kafka_op_new_fetch_msg (in /usr/lib/rsyslog/imkafka.so)
==28533==    by 0x7EE5060: rd_kafka_msgset_reader_msg_v2 (in /usr/lib/rsyslog/imkafka.so)
==28533==    by 0x7EE65D7: rd_kafka_msgset_reader_msgs_v2 (in /usr/lib/rsyslog/imkafka.so)
==28533==    by 0x7EE678D: rd_kafka_msgset_reader_decompress (in /usr/lib/rsyslog/imkafka.so)
==28533==    by 0x7EE9D92: rd_kafka_msgset_reader_v2 (in /usr/lib/rsyslog/imkafka.so)
==28533==    by 0x7EE252F: rd_kafka_msgset_reader_run (in /usr/lib/rsyslog/imkafka.so)
==28533==    by 0x7EEB9BC: rd_kafka_msgset_parse (in /usr/lib/rsyslog/imkafka.so)
==28533==    by 0x7E81D28: rd_kafka_fetch_reply_handle (in /usr/lib/rsyslog/imkafka.so)
==28533==    by 0x7E83BCD: rd_kafka_broker_fetch_reply (in /usr/lib/rsyslog/imkafka.so)
==28533==    by 0x7E9F5D2: rd_kafka_buf_callback (in /usr/lib/rsyslog/imkafka.so)
==28533== 
==28533== 3,559,317,285 bytes in 9,889 blocks are still reachable in loss record 2,023 of 2,023
==28533==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==28533==    by 0x7EF41BD: rd_kafka_lz4_decompress (in /usr/lib/rsyslog/imkafka.so)
==28533==    by 0x7EE6815: rd_kafka_msgset_reader_decompress (in /usr/lib/rsyslog/imkafka.so)
==28533==    by 0x7EE9D92: rd_kafka_msgset_reader_v2 (in /usr/lib/rsyslog/imkafka.so)
==28533==    by 0x7EE252F: rd_kafka_msgset_reader_run (in /usr/lib/rsyslog/imkafka.so)
==28533==    by 0x7EEB9BC: rd_kafka_msgset_parse (in /usr/lib/rsyslog/imkafka.so)
==28533==    by 0x7E81D28: rd_kafka_fetch_reply_handle (in /usr/lib/rsyslog/imkafka.so)
==28533==    by 0x7E83BCD: rd_kafka_broker_fetch_reply (in /usr/lib/rsyslog/imkafka.so)
==28533==    by 0x7E9F5D2: rd_kafka_buf_callback (in /usr/lib/rsyslog/imkafka.so)
==28533==    by 0x7E85F54: rd_kafka_recv (in /usr/lib/rsyslog/imkafka.so)
==28533==    by 0x7E9D1C7: rd_kafka_transport_io_event (in /usr/lib/rsyslog/imkafka.so)
==28533==    by 0x7E8C257: rd_kafka_broker_serve (in /usr/lib/rsyslog/imkafka.so
```
Now let me have a deeper look,

**Comment by rgerhards** [comment]
How about this: let's log as a user message and wait if someone complains? If nobody complains, we could conclude it is acceptable...

**Comment by alorbach** [comment]
Whenever a file is modifed in a monitored directory. And we always need to monitor the parent directory.

**Comment by kortemik** [comment]
I would assume that the need to monitor the parent directory has masks like FILE_CREATE or FILE_DELETE not everything and from those parent directory events the invidual file monitors would be constructed/deconstructed when needed. So misconfiguration on a file name or path would only fire not so frequently.

**Comment by alorbach** [comment]
Unfortunately there are no such masks. The FEN api is very limited. 
That's why we had to workaround the problem in order to detect dynamically that a configured file is created.

**Comment by kortemik** [comment]
I wont bet my head over it but I'd assume
http://fxr.watson.org/fxr/ident?v=OPENSOLARIS;im=10;i=FILE_MODIFIED this
gets fired if a directory handle is changed i.e. file is created or
deleted. I didn't read the full implementation in detail though.

**Comment by alorbach** [comment]
It does tell you something changed in the directory. But it doesn't tells you what changed. Unless I really missed something. But I read the API description over and over again.

**Comment by rgerhards** [comment]
@alorbach what does the message "failed to stat" actually mean? My understanding is "file not found". Is this correct?

**Comment by rgerhards** [comment]
Proposed PR #2267 - please let me know if anyone objects or has better wording.

**Comment by alorbach** [comment]
Fully correct yes
