### ISSUE TITLE
rainerscript.c: potentially invalid index operation

### ISSUE THREAD

**Issue by rgerhards** [rsyslog/rsyslog#2255]
@mrworkman reports in str2num where ```neg = -1```:

i gets set to -1, and then is used in the while loop below - reading outside the bounds of the array. The result is that it cannot parse negative numbers.

I'm pretty sure this should be 1, not -1.

**Comment by rgerhards** [comment]
It's a bit crazy -- I agree it's a bug, but I can't create a testbench test that fails right now...

**Comment by mrworkman** [comment]
It was failing in my `is_time()` test where I pass a negative number (as a string) into the function: `is_time("-88", "date-unix")`

**Comment by rgerhards** [comment]
ok, let me check... I used arithmetic ops, probably they have a different path...

**Comment by rgerhards** [comment]
I just messed up as it looks ;-)
