### ISSUE TITLE
don't execute multi rules

### ISSUE THREAD

**Issue by arp220** [rsyslog/rsyslog#2257]
hi all. 
i add four rule in rsyslog.conf file. but don't execute all rules !! execute only last rule !! . please look my rules.
```
template(name="tp1" type="string" string="%msg:::sp-if-no-1st-sp%\n")
ruleset(name="rule1"){
        action(type="omfile" Template="tp1" file="/var/log/mylog1")
}
input(type="imudp" port="514" Ruleset="rule1")
#---------------------------------------------------------------------------------------
template(name="tp2" type="string" string="%FROMHOST-IP%\n")
ruleset(name="rule2"){
        action(type="omfile" Template="tp2" file="/var/log/mylog2")
}
input(type="imudp" port="514" Ruleset="rule2")
#-----------------------------------------------------------------------------------------
template(name="tp3" type="string" string="%TIMESTAMP%\n")
ruleset(name="rule3"){
        action(type="omfile" Template="tp3" file="/var/log/mylog3")
}
input(type="imudp" port="514" Ruleset="rule3")
#------------------------------------------------------------------------------------------
template(name="tp4" type="string" string="%syslogtag% %HOSTNAME%\n")
ruleset(name="rule4"){
        action(type="omfile" Template="tp4" file="/var/log/mylog4")
}
input(type="imudp" port="514" ruleset="rul4")
``` 
why execute only last rule ? please guide me. thanks.

**Comment by rgerhards** [comment]
can you re-format so that the config is readable ;-)

**Comment by rgerhards** [comment]
wait, I see, I can fix that...

**Comment by rgerhards** [comment]
you cannot bind multiple listeners to the same port number. What do you want to do?

**Comment by arp220** [comment]
i want use in laboratory. do for each rule should open a port on the server ?!!

**Comment by arp220** [comment]
i want configure rsyslog for a centralized Linux log server.

**Comment by rgerhards** [comment]
you need to be more specific on what you want, else I cannot give good advise.

**Comment by deoren** [comment]
@arp220 One input per port and one ruleset per input. A workaround for the latter is to have that ruleset call other rulesets.

See this page for more info: http://www.rsyslog.com/doc/v8-stable/concepts/multi_ruleset.html

**Comment by davidelang** [comment]
On Mon, 18 Dec 2017, arp220 wrote:

> hi all.
> i add four rule in rsyslog.conf file. but don't execute all rules !! execute only last rule !! . please look my rules.
>
> `template(name="tp1" type="string" string="%msg:::sp-if-no-1st-sp%\n")
> ruleset(name="rule1"){
>        action(type="omfile" Template="tp1" file="/var/log/mylog1")
> }
> input(type="imudp" port="514" Ruleset="rule1")
> #---------------------------------------------------------------------------------------
> template(name="tp2" type="string" string="%FROMHOST-IP%\n")
> ruleset(name="rule2"){
>        action(type="omfile" Template="tp2" file="/var/log/mylog2")
> }
> input(type="imudp" port="514" Ruleset="rule2")
> #-----------------------------------------------------------------------------------------
> template(name="tp3" type="string" string="%TIMESTAMP%\n")
> ruleset(name="rule3"){
>        action(type="omfile" Template="tp3" file="/var/log/mylog3")
> }
> input(type="imudp" port="514" Ruleset="rule3")
> #------------------------------------------------------------------------------------------
> template(name="tp4" type="string" string="%syslogtag% %HOSTNAME%\n")
> ruleset(name="rule4"){
>        action(type="omfile" Template="tp4" file="/var/log/mylog4")
> }
> input(type="imudp" port="514" ruleset="rul4")
> `
> why execute only last rule ? please guide me. thanks.

In this case you have defined four listeners, all trying to grab control of the 
same port. Only one can successfully grab that port, the other three will fail 
(port already in use or similar error)

you need to explain more about what you are trying to do. Why are you trying to 
setup four separate listeners on the same port rather than either putting them 
on four different ports or having one listener with four rules in the ruleset.

**Comment by arp220** [comment]
It's simple and clear. I want to have some template. how can i defined multi rules ? my code is true ? only i should change port listeners? and Finally, is this correct then for each rule open a port on the server ?

**Comment by deoren** [comment]
@arp220 the general idea is to define a port per purpose, then attach a ruleset to each port as needed.

For example, perhaps you have 514/UDP for classic UDP syslog messages, then 514/tcp for clients that support sending by TCP and then you have 2514 for clients that support RELP.

With that scenario you have three ports:

- 514 UDP for standard syslog
- 514 TCP for standard syslog
- 2514 TCP for standard syslog over RELP

You can choose to create and attach the same ruleset to all three or you can create and attach a different ruleset to each, it is up to you. You can also opt to not attach a ruleset to any and the default ruleset will apply.

For the 2514 port, in our setup we are sending JSON data within a standard syslog message, so we have a dedicated ruleset for that port which handles those messages differently than messages coming in on the other two ports.

Also, in case it wasn't clear, a ruleset is a way of collecting multiple rules together, usually for a specific purpose. You then attach the ruleset to an input (equivalent to a port when dealing with network inputs) or call the ruleset at the spot you want to apply the rules (like you would a function in a programming language).

Does that help?

**Comment by arp220** [comment]
i change rules : 
`
template(name="tp1" type="string" string="%msg:::sp-if-no-1st-sp%\n")
template(name="tp2" type="string" string="%FROMHOST-IP%\n")
template(name="tp3" type="string" string="%TIMESTAMP% %msg% \n")
template(name="tp4" type="string" string="%syslogtag% %HOSTNAME%\n")

ruleset(name="rul1"){
if $syslogtag contains 'rsyslog' then {
        action(type="omfile" Template="tp1" file="/var/log/mylog1")
        stop
        }

  if $syslogtag == "sshd" then {           

         action(type="omfile" Template="tp2" file="/var/log/mylog2")          
        stop
        }

  if $fromhost-ip == "192.168.26.17" then {

         action(type="omfile" Template="tp3" file="/var/log/mylog3")
         stop

        }
  if $programname contains 'bind' then {

         action(type="omfile" Template="tp4" file="/var/log/mylog4")
         stop
        }
}
input(type="imudp" port="514" Ruleset="rul1")

`
and worked. one question ! why condition $programname and $syslogtag not work ?

**Comment by arp220** [comment]
thanks guys. my problem has been resolved
```
template(name="tp1" type="string" string="%msg%\n")

template(name="tp2"
  type="list") {
    constant(value="{")
      constant(value="\"@timestamp\":\"")     property(name="timereported" dateFormat="$
      constant(value="\",\"host\":\"")        property(name="hostname")
      constant(value="\",\"severity\":\"")    property(name="syslogseverity-text")
      constant(value="\",\"facility\":\"")    property(name="syslogfacility-text")
      constant(value="\",\"tag\":\"")   property(name="syslogtag" format="json")
      constant(value="\",\"message\":\"")    property(name="msg" format="json")
    constant(value="\"}")
}

template(name="tp3" type="string" string="{\"hostname\":\"%msg:F,32:7:%\", \"ip\":\"%fr$


ruleset(name="rule1"){
        if $msg contains 'Apache' then {
                action(type="omfile" file="/var/log/memessages" Template="tp1")

        }
        if $msg contains 'sshd' then {
                action(type="omfile" file="/var/log/memessages" Template="tp1")

        }
        if $programname contains 'httpd' then {
                action(type="omfile" file="/var/log/meprogramname" Template="tp1")

        }
        if $msg contains 'EIR' then {
                action(type="omfile" file="/var/log/EIR" Template="tp3")
        }

}
input (type="imudp" port="514" ruleset="rule1")
```
