### ISSUE TITLE
Version 8.7.0 fails to build on illumos.

### ISSUE THREAD

**Issue by andy-js** [rsyslog/rsyslog#226]
This patch fixes the problem for me:

<pre>
diff --git a/configure.ac b/configure.ac
index 71e7cad..a7f9dd1 100644
--- a/configure.ac
+++ b/configure.ac
@@ -70,8 +70,7 @@ case "${host}" in
     os_type="solaris"
     AC_DEFINE([OS_SOLARIS], [1], [Indicator for a Solaris OS])
     AC_DEFINE([_POSIX_PTHREAD_SEMANTICS], [1], [Use POSIX pthread semantics])
-    AC_DEFINE([_XOPEN_SOURCE], [1], [Use X/Open CAE Specification])
-    AC_DEFINE([_XOPEN_SOURCE_EXTENDED], [1], [Use X/Open CAE Specification])
+    AC_DEFINE([_XOPEN_SOURCE], [600], [Use X/Open CAE Specification])
     SOL_LIBS="-lsocket -lnsl"
     # Solaris libuuid does not ship with a pkgconfig file so override the appropriate
     # variables (but only if they have not been set by the user).
diff --git a/runtime/nsd_ptcp.c b/runtime/nsd_ptcp.c
index 80515b6..bc84b82 100644
--- a/runtime/nsd_ptcp.c
+++ b/runtime/nsd_ptcp.c
@@ -652,7 +652,7 @@ EnableKeepAlive(nsd_t *pNsd)
                ABORT_FINALIZE(RS_RET_ERR);
        }
 
-#      if defined(TCP_KEEPCNT)
+#      if defined(SOL_TCP) && defined(TCP_KEEPCNT)
        if(pThis->iKeepAliveProbes > 0) {
                optval = pThis->iKeepAliveProbes;
                optlen = sizeof(optval);
@@ -667,7 +667,7 @@ EnableKeepAlive(nsd_t *pNsd)
                errmsg.LogError(ret, NO_ERRCODE, "imptcp cannot set keepalive probes - ignored");
        }
 
-#      if defined(TCP_KEEPCNT)
+#      if defined(SOL_TCP) && defined(TCP_KEEPCNT)
        if(pThis->iKeepAliveTime > 0) {
                optval = pThis->iKeepAliveTime;
                optlen = sizeof(optval);
@@ -682,7 +682,7 @@ EnableKeepAlive(nsd_t *pNsd)
                errmsg.LogError(ret, NO_ERRCODE, "imptcp cannot set keepalive time - ignored");
        }
 
-#      if defined(TCP_KEEPCNT)
+#      if defined(SOL_TCP) && defined(TCP_KEEPCNT)
        if(pThis->iKeepAliveIntvl > 0) {
                optval = pThis->iKeepAliveIntvl;
                optlen = sizeof(optval);

</pre>

**Comment by rgerhards** [comment]
Thx. If you get me your mail and email address, I can add proper credits in git commit log (which happens automatically if you do a pull request, just so that you know). Also, it would be great you could help me setup an illuminos machine, then I would be able to run tests there continuously.

**Comment by rgerhards** [comment]
Mhh... I guess the patch is not against rsyslog's baseline:

- we don't have any _XOPEN_SOURCE defined, which is deleted above
- SOL_TCP is also not presents ... and it looks like it is being added

please check, I guess this is a diff between two of your internal versions.

**Comment by andy-js** [comment]
I'm building against the code pointed to by the 8.7.0 tag which does indeed include references to SOL_TCP: https://github.com/rsyslog/rsyslog/blob/v8.7.0/runtime/nsd_ptcp.c#L659

The XOPEN_SOURCE stuff isn't defined anywhere though.  Maybe I added that, but I don't remember doing so.

**Comment by rgerhards** [comment]
my bad with the SOL_TCP, I was so focussed that it is something you added as a compatibility layer. So I'll see that I merge manually.

**Comment by andy-js** [comment]
NP.  My name and email should be visible in my profile.

**Comment by andy-js** [comment]
So I can confirm that I did add the XOPEN_SOURCE stuff.  I think you should include the updated lines though as without it the code won't build.
