### ISSUE TITLE
imfile: misses files very quickly created after directory creation

### ISSUE THREAD

**Issue by alorbach** [rsyslog/rsyslog#2271]
Review test failures when timing changes in imfile-wildcards-dirs2.sh. 
In some cases inotify or fen API misses a file during the test when sleetime  is changed or removed.

**Comment by rgerhards** [comment]
test ```imfile-wildcards-dirs.sh``` seems to have similar issues

**Comment by rgerhards** [comment]
actually, ```imfile-wildcard-dirs.sh```seems to fail more frequently. I did some test runs, and it looks like a real bug, not a testbench issue. I currently think that files already existing in a directory when the directory notification is processed are not properly detected and handled.

**Comment by rgerhards** [comment]
actually, this commit describes the problem, we just need a different soltution that actualyl fixes the problem inside code: https://github.com/rsyslog/rsyslog/commit/faca9c8ced118c2aa47f2c38c3f8c680be01ddca

**Comment by rgerhards** [comment]
I disable the test that fails due to this bug so that the CI system can work normally again. This needs to be re-enabled once this bug here is fixed.
