### ISSUE TITLE
Imkafka - reduce logging

### ISSUE THREAD

**Issue by ltagliamonte** [rsyslog/rsyslog#2289]
Didn't find anything in the documentation, so posting here.
I'm getting the syslog file full of "debug" messages from imkafka:

```Dec 22 01:16:08 server-i-0e3ef62b3f07c25f3 rsyslogd: imkafka: Consumer reached end of topic "logging" [21]message queue offset 42945376  [v8.32.0.1dba684c9fe8 try http://www.rsyslog.com/e/2422 ]```

@rgerhards Is it possible to move this message to debug or fine level?
Thanks.

**Comment by rgerhards** [comment]
consider this solved: https://github.com/rsyslog/rsyslog/pull/2286/commits/fa8b34162fee5d92b6231e0e800c42f080470786

merge will happen either today or very soon - I need to get another bugfix in master before the testbench succeeds. See PR https://github.com/rsyslog/rsyslog/pull/2286
