### ISSUE TITLE
rscript_http_request.sh test should use a local HTTP endpoint

### ISSUE THREAD

**Issue by Whissi** [rsyslog/rsyslog#2339]
We should try to avoid external network access in test suite: This will fail for most users because for security reason most build environments are restricting external network access.

Best solution: Ship a local HTTP endpoint with the test suite (i.e. Python based?) to allow tests against an own instance spawned by the test suite running on localhost.

Intermediate solution:
Because the feature depends on cURL, try to fetch the external resource first via cURL. If this is failing, skip the test. I.e. something like https://github.com/rsyslog/rsyslog/blob/master/tests/faketime_common.sh:
```Bash
rsyslog_testbench_test_network_access() {
    local missing_requirements=
    if ! hash curl 2>/dev/null ; then
        missing_requirements="'curl' is missing in PATH; Make sure you have cURL installed! Skipping test ..."
    fi

    if [ -n "${missing_requirements}" ]; then
        echo ${missing_requirements}
        exit 77
    fi

    local http_endpoint="http://www.rsyslog.com/testbench/echo-get.php"
    if ! curl --fail --max-time 30 "${http_endpoint}" 1>/dev/null 2>&1; then
        echo "HTTP endpont '${http_endpoint}' isn't reachable. Skipping test ..."
        exit 77
    else
        echo "HTTP endpoint '${http_endoint}' is reachable! Starting test ..."
    fi
}
```

**Comment by rgerhards** [comment]
thx. For now, I'll just add the check. Later we may add a local http endpoint.
