### ISSUE TITLE
imfile: refactor data structures

### ISSUE THREAD

**Issue by rgerhards** [rsyslog/rsyslog#2359]
Recent issues and related code review have show that imfile has grown over the years to a state where the data structures used to keep track of ongoing activity do no longer properly match what needs to be done. This results in complex code, hard to find bugs and high maintenance effort.

This means it is time to refactor the data structures and along that probably a lot of the processing code. This should result in a notable simplification.

As part of this activity, code for poll, inotify and FEN mode should be unified as much as possible.

**Comment by davidelang** [comment]
As you are doing this sort of change to imfile, can you add an option to apply a 
parser to the line being read from the file?

Specifically, I'm looking situations like where someone is reading in a syslog 
file that already has timestamp, hostname, syslogtag in it and we want to use 
those values. Being able to specify the RFC3164 parser be run against this would 
be a very nice option.

In other cases, you would want to be able to specify a custom parser, similar to 
how we can now use a mmnormalize parser on inbound network connections.

The output of the parser would replace (or make unneccessary) the config options 
to specify these values.

**Comment by rgerhards** [comment]
I think it would make sense to add an extra issue tracker for this, so it is easier to work on.
