### ISSUE TITLE
spurious xOS_LINUX in configure.ac

### ISSUE THREAD

**Issue by mbiebl** [rsyslog/rsyslog#2386]
Looking through configure.ac, I see
```
AM_CONDITIONAL(xOS_LINUX, test x$os_type == xlinux)
AM_CONDITIONAL(OS_LINUX, test x$os_type == xlinux)
```
xOS_LINUX isn't used anywhere and it feels kinda odd, defining two conditionals for the same os_type.

**Comment by rgerhards** [comment]
Thx, that indeed looks wrong!

**Comment by rgerhards** [comment]
... and it is wrong. I guess a left-over from some experiment.
