### ISSUE TITLE
jsonmesg property in template causes omfile assert to trigger

### ISSUE THREAD

**Issue by kortemik** [rsyslog/rsyslog#2396]
### Expected behavior
json output should be written to file indicated by omfile
### Actual behavior
rsyslogd: stringbuf.c:406: cstrGetSzStrNoNULL: Assertion `pThis->isFinalized' failed.
Aborted (core dumped)
### Steps to reproduce the behavior
configure rsyslog with following configuration
```
$LocalHostName test.host.example
$PreserveFQDN on
main_queue(queue.type="Direct")
global(
    workDirectory="/opt/Fail-Safe/rsyslog/var"
    maxMessageSize="128k"
)
$MainMsgQueueType Direct
module(load="imrelp")
input(type="imrelp" port="601" MaxDataSize="128k")
template(name="testformat" type="list"){
    property(name="jsonmesg")
    constant(value="\n")
}
action(type="omfile" file="/var/log/debug.log" template="testformat")
```
flood it with
```
./tcpflood -t 192.168.10.101 -p 601 -m 1 -T relp-plain -M '<134>1 2018-01-12T13:39:28+01:00 testhost-1 good - - - [2018-01-12T13:39:28+01:00] Example payload. ID 1515760768.688376851'
```
### Environment
- rsyslog version: [e.g. 8.31.0 -- see rsyslogd -v]
```
rsyslogd 8.32.0, compiled with:
        PLATFORM:                               x86_64-pc-linux-gnu
        PLATFORM (lsb_release -d):
        FEATURE_REGEXP:                         Yes
        GSSAPI Kerberos 5 support:              No
        FEATURE_DEBUG (debug build, slow code): Yes
        32bit Atomic operations supported:      Yes
        64bit Atomic operations supported:      Yes
        memory allocator:                       system default
        Runtime Instrumentation (slow code):    No
        uuid support:                           Yes
        systemd support:                        No
        Number of Bits in RainerScript integers: 64

See http://www.rsyslog.com for more information.
```
- platform: [e.g. Ubuntu 16.04]
```
# cat /etc/redhat-release 
Fedora release 27 (Twenty Seven)
# uname -a
Linux 59ca53eb2397 3.10.0-514.el7.x86_64 #1 SMP Tue Nov 22 16:42:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```
- for configuration questions/issues, include rsyslog.conf:
included above
*Note: rsyslog documentation is available here*:
  [pre-release](http://www.rsyslog.com/doc/master/),
  [current stable release](http://www.rsyslog.com/doc/v8-stable/)

**Comment by rgerhards** [comment]
thx for the great bug report. I can confirm that I can reproduce in lab.

The problem seems actually be rooted in imrelp, as the same config via imtcp does not trigger the problem.

**Comment by rgerhards** [comment]
no, seems to be the rfc5424 parser

**Comment by rgerhards** [comment]
@kortemik commit abe327b08a32b00e4981d529c297d95089b65f72 contains the patch. Just FYI if you want to rebuild. Thx again for the report!
