### ISSUE TITLE
Question: Will patches continue to be applied to release builds post-release?

### ISSUE THREAD

**Issue by deoren** [rsyslog/rsyslog#2418]
### Expected behavior

1. Official release is made
1. Updates to the DEB or RPM files used to create the package process are applied as needed to resolve any deployment issues with the package itself
1. Work continues on next release milestone
1. Once the new milestone is closed a new stable release is made from that milestone

### Actual behavior

1. Official release is made
1. Updates to the DEB or RPM files used to create the package process are applied as needed to resolve any deployment issues with the package itself
1. Work continues on next release milestone
1. New changes are applied to prior stable release and new package is released containing current stable version + cherry-picked bug fixes scheduled for next milestone
1. Once the new milestone is closed a new stable release is made from that milestone

##### CentOS

`yum changelog 3 rsyslog`

```
Loaded plugins: changelog, fastestmirror, security

Listing 3 changelogs

==================== Installed Packages ====================
rsyslog-8.32.0-4.el6.x86_64              installed
* Wed Jan 17 06:00:00 2018 Florian Riedl - 8.32.2-4
- Added patches for json processing in rainerscript
  and jsonmesg
  fixes: https://github.com/rsyslog/rsyslog/issues/2391
  fixes: https://github.com/rsyslog/rsyslog/issues/2396

* Wed Jan 10 06:00:00 2018 Florian Riedl - 8.32.2-3
- put omstdout.so in its own sub-package
  rsyslog-omstdout

* Wed Jan 10 06:00:00 2018 Florian Riedl - 8.32.2-2
- Included omstdout.so in EL6 build per request
  https://github.com/rsyslog/rsyslog/issues/2203

changelog stats. 1 pkg, 1 source pkg, 3 changelogs
```

##### Ubuntu

```
--- Changes for rsyslog (rsyslog rsyslog-mmjsonparse rsyslog-relp) ---
rsyslog (8.32.0-0adiscon3trusty1) trusty; urgency=medium

  * Added patch for external cmd parser
    ref: https://github.com/rsyslog/rsyslog/pull/2410

 -- Florian Riedl <adiscon-pkg-maintainers@adiscon.com>  Fri, 19 Jan 2018 12:00:46 +0000
```

### Thoughts

This isn't a problem, it was just unexpected. Will this be the norm going forward? Any chance that the changes would be released as 8.32.1, 8.32.2, 8.32.3, etc?

I understand that the versioning scheme has changed from prior days:

- http://www.rsyslog.com/rsyslogs-new-release-cycle-and-versioning-scheme/
- https://www.slideshare.net/rainergerhards1/rsyslog-version-naming-v860

but if the changes included in the updated Adiscon packages are significant enough to warrant a re-release of those packages, perhaps they're significant enough to warrant a source fixlevel release (X.Y.fixlevel)?

Just a thought.

**Comment by rgerhards** [comment]
It's actually an experiment. We need to look at the fine details. We have

* the rsyslog *upsteam* project
* that packaging projects 

You talk about Adiscon's packaging project, but there are others like Debian, RHEL, Suse. The projects release policy covers the source releases. When we changed to the 6-weekly cycle, there was understanding that every 6 weeks will be good fast enough so that we do not need to hurry except for real emergencies. One reason was that the distros (packaging projects) can pick up patches if they desire it is worth it.

Now packaging project hat on: we found it useful to fix some non-catastrophic albeit bad enough backs by backporting patches. It wasn't a lot of effort, and is useful to the community. Even more, all distros for which we build packages do not provide current packages, so there actually is nobody else who uses rsyslog current. So the patches reach a large number of the user base, except those that build themselves.

Now rsyslog source project maintainer hat on: if I need to keep another stable release branch and do frequent releases in addition to the 6-week cycle, I'll definitely get a sharp drop in productivity. I will not release them as .1, .2 etc except for extremely good reasons.

Conclusion: If the updated packages cause confusion, we will go back to not provide any updates except the links to the source patches that we publish inside the issue trackers. We did not do this before, and it wasn't a big deal.

**Comment by rgerhards** [comment]
I need to add: the packaging project always did interim releases, e.g. to catch up on new libraries. Libfastjson 0.99.8 was a recent case, I think. In those cases, rsyslog also gets repackaged, and that is the right thing to do. We need to continue this, even if we stop providing patches to the binary.

**Comment by rgerhards** [comment]
A "little bit" of history:

* http://lists.adiscon.net/pipermail/rsyslog/2014-October/038786.html
* http://lists.adiscon.net/pipermail/rsyslog/2015-December/041747.html

**Comment by deoren** [comment]
@rgerhards It's not a problem for me, and while I mainly wanted to get a better understanding of the process, I did want to offer my thoughts re fixlevel releases (if nothing else a release tag in the GitHub repo). 

The Dovecot team uses a similar process with their Enterprise Edition releases. They will often include fixes scheduled for the next milestone in interim bugfix releases for EE users before the next stable release is available, so rsyslog is far from the only project to use this approach.

**Comment by rgerhards** [comment]
sorry for the tons of stuff, but I really think it is time spent well going through the mailing list posts -- they'll provide a lot of insight of why things are as they are.

Another question is if we go back to providing on LTS release -- we dropped this, as in the past nobody really used it and it was **a lot** of work to do. Work, we now can spend on new stuff and CI.

I honestly believe this split of source vs. packaging project makes sense, especially if the packaging project keeps things moving smoothly.

**Comment by rgerhards** [comment]
side-note: it may obviously make sense to document the policy... not sure where I have to admit (I would say it's not real doc, as it is cross-project).

**Comment by deoren** [comment]
> @rgerhards: sorry for the tons of stuff

Not a problem at all, thanks for the info. Always feel free to toss as much detail as you wish my way. :)

> @rgerhards: Another question is if we go back to providing on LTS release -- we dropped this, as in the past nobody really used it and it was a lot of work to do. Work, we now can spend on new stuff and CI.

To be clear, I wasn't recommending going back to a LTS release model, I was instead recommending the introduction of fixlevel releases between two regularly scheduled versions (e.g., fixes intended for release between 8.32.0 and 8.33.0), irregardless of the frequency of those scheduled releases. I'd say that six weeks is probably a good balance between new features and bug fixes and only with sufficient staffing could you increase the frequency and still maintain stability within those releases.

> @rgerhards: I honestly believe this split of source vs. packaging project makes sense, especially if the packaging project keeps things moving smoothly.

If going with fixlevel releases in the source project increases the workload and cuts into dev time, then omitting them and including pre-release changes in the Adiscon-provided packages is a reasonable approach. Those packages are offered (as you've pointed out before) as a courtesy for your user base, so using them implies an acceptable of the release policy for those packages.

Since you mentioned that this is an experimental policy, it's probably worth documenting the change in policy for those packages in the doc project, *perhaps* in the changelog for the source project (not sure about that one), the website in the news section and on the mailing list. 

I doubt that many would have an issue with the change in policy, but making the change in packaging as clear as possible would be a good idea.

Re including mention of this in the doc project, I think it's worth including there as the history of the release policy is interesting material for anyone new to the project and that are interested in becoming a regular contributor. If nothing else it wouldn't add much to the "weight" of the content.

**Comment by deoren** [comment]
> @rgerhards: side-note: it may obviously make sense to document the policy... not sure where I have to admit (I would say it's not real doc, as it is cross-project).

You responded before I finished my last post; I suppose I should quit writing walls of text. ;)

Including it in the doc project could work: we could create a section centered around how versioning of the project is handled, the release process, etc. I think covering back-ported fixes from the next milestone for "upstream" or "official" packages would be a good fit there. 

On a side-note, I keep referring to "upstream" or "official" packages as an attempt to clarify the source (vs Ubuntu, CentOS, etc). Is there another term that you'd like to see used to refer to the packages available from rpms.adiscon.com or the Ubuntu PPA?

**Comment by rgerhards** [comment]
> On a side-note, I keep referring to "upstream" or "official" packages as an attempt to clarify the source (vs Ubuntu, CentOS, etc). Is there another term that you'd like to see used to refer to the packages available from rpms.adiscon.com or the Ubuntu PPA?

Sorry, no real good idea here. Maybe "source" and "packaging" project makes sense. As I said, it's a fine line, and maybe one only I see. I think both of these projects should have the ability to use their own release policies (just like Debian or RHEL do) even though there is overlap between the folks.

Side-note: our initial testing with Suse OBS seems to go very well. If all continues to run sufficiently smooth, we'll be able to provide packages for many more distributions. Have a look at Florian's work area: https://build.opensuse.org/project/show/home:friedl-ad:branches:home:rgerhards as well as the potential coverage of OBS: http://openbuildservice.org/
