### ISSUE TITLE
http://www.rsyslog.com/e/2420 is a 404

### ISSUE THREAD

**Issue by otisg** [rsyslog/rsyslog#242]
Got this in the log (latest 8.7.0 version, installed today)
Feb  2 23:12:54 logsene-reports rsyslogd-2420: imfile: warning: it looks like to-be-monitored file "/mnt/opt/jetty/logs/*.stderrout.log" contains wildcards. This usually does not work well with specifying a state file. [try http://www.rsyslog.com/e/2420 ]

But http://www.rsyslog.com/e/2420 is a 404

**Comment by teifler** [comment]
This message tells the user that a state file is specified for an imfile input which uses wildcards. This is usually an extremely bad idea, as the state file becomes corrupted if multiple files match the wildcard. The option primarily exist for exotic use cases and it is strongly recommended not to specify state file names in this setup.

For more details check the documentation at http://www.rsyslog.com/doc/v8-stable/configuration/modules/imfile.html

**Comment by teifler** [comment]
fixed
