### ISSUE TITLE
Problem with my relp config

### ISSUE THREAD

**Issue by Ekouyoja** [rsyslog/rsyslog#2427]
Hi,

I have a gnutls handshake error between my server and my client but i don't know where i do an error.
I have an server config that work and one that doesn't work. For me it's the same thing.

Here is my client config that doesn't change.
action(type="omrelp" target="rsyslog-test.mydomain.fr" port="1514" tls="on" tls.cacert="/etc/openssl/certificates/server-rsyslog.crt" tls.authMode="name")

Here is the server config that work
$DefaultNetstreamDriver gtls
$DefaultNetstreamDriverCAFile /etc/openssl/certificates/ca-rsyslog.crt
$DefaultNetstreamDriverCertFile /etc/openssl/certificates/server-rsyslog.crt
$DefaultNetstreamDriverKeyFile /etc/openssl/certificates/server-rsyslog.key

input(type="imrelp" port="1514" ruleset="clients" tls="on")

Here is the server config that doesn't work
$DefaultNetstreamDriver gtls
input(type="imrelp" port="1514" ruleset="clients" tls="on"
tls.caCert="/etc/openssl/certificates/ca-rsyslog.crt"
tls.myCert="/etc/openssl/certificates/server-rsyslog.crt"
tls.myPrivKey="/etc/openssl/certificates/server-rsyslog.key")

I have the last rsyslog version : 8.32.0-3

**Comment by jay7x** [comment]
`DefaultNetstreamDriver*` have nothing common with RELP. Please re-read documentation: http://www.rsyslog.com/doc/master/configuration/modules/imrelp.html

All certs/keys must be configured in `imrelp` action.
Here is good article in rsyslog blog about it: http://www.rsyslog.com/using-tls-with-relp/
