### ISSUE TITLE
rsyslog 8.7 crashes with omrelp output

### ISSUE THREAD

**Issue by sapiophile** [rsyslog/rsyslog#245]
The message when crashing is:
 service rsyslog start
Starting system logger:                                    [  OK  ]
[root@hostname rsyslog.d]# rsyslogd: ath.c:193: _gcry_ath_mutex_lock: Assertion `*lock == ((ath_mutex_t) 0)' failed.

Systems on both sides are CentOS 6.6 with latest updates. rpms are installed from http://rpms.adiscon.com/v8-stable/epel-6/x86_64/RPMS/
rsyslog-8.7.0-1.el6.x86_64
rsyslog-gnutls-8.7.0-1.el6.x86_64
rsyslog-relp-8.7.0-1.el6.x86_64
rsyslog-debuginfo-8.7.0-1.el6.x86_64

'rsyslogd -d' outputs a lot, last messages on terminal are different:
sometimes imfile messages:
6709.107277037:imfile.c       : main Q: qqueueAdd: entry added, size now log 2375, phys 2376 entries
6709.107287441:imfile.c       : main Q: qqueueAdd: entry added, size now log 2376, phys 2377 entries
6709.107297790:imfile.c       : main Q: qqueueAdd: entry added, size now log 2377, phys 2378 entries
sometimes omrelp messages:
6710.898027801:main Q:Reg/w0  : librelp: TLS send returned 212
6710.898032892:main Q:Reg/w0  : Warning: exceeding window size, max 128, curr 128
6710.898035605:main Q:Reg/w0  : ADD sess 0x7f6d74002650 unacked 128, sessState 5
6710.898037995:main Q:Reg/w0  : sendbuf added to unacked list
6710.898041030:main Q:Reg/w0  : omrelp: shutdownImmediate ptr now is 0x7f6d85e9b048
6710.898043525:main Q:Reg/w0  : entering actionCalldoAction(), state: itx, actionNbr 0
6710.898045871:main Q:Reg/w0  :  x.x.x.x:514/RELP

rsyslog configuration to forward messages to server is:
action (type="omrelp"
  target="x.x.x.x"
  port="514"
  tls="on"
  action.resumeRetryCount="-1"
)

**Comment by sapiophile** [comment]
Interesting is that if I comment out one tag line from imfile configuration section, this error goes away.

input(type="imfile"
  file="/home/git/gitlab/log/unicorn.stderr.log"
  tag="unicorn"
  severity="error"
  ruleset="remote_default"
)
input(type="imfile"
  file="/home/git/gitlab/log/unicorn.stdout.log"
  tag="unicorn"
  severity="info"
  ruleset="remote_default"
)
input(type="imfile"
  file="/home/git/gitlab/log/sidekiq.log"
  tag="sidekiq"
  severity="info"
  ruleset="remote_default"
)
input(type="imfile"
  file="/home/git/gitlab/log/production.log"
  #tag="thisissometag"
  severity="info"
  ruleset="remote_default"
)
input(type="imfile"
  file="/home/git/gitlab/log/githost.log"
  tag="githost"
  ruleset="remote_default"
)
It does not matter what to write into that tag,  ath.c:193: _gcry_ath_mutex_lock: Assertion `*lock == ((ath_mutex_t) 0)' failed. is shown and rsyslogd crashes.

**Comment by sapiophile** [comment]
From the same server, another imfile section where defining tag crashes rsyslog.
input(type="imfile"
  file="/var/www/gitolite-home/.gitolite/logs/gitolite-*.log"
#  tag="gitolite"
  ruleset="remote_default"
)

**Comment by rgerhards** [comment]
fixed at least in 8.16.0

**Comment by darkrwe** [comment]
not fixed in v8.17
