### ISSUE TITLE
Message is empty when an action is defined with a list style template that refers to other template, where the action is within a ruleset 

### ISSUE THREAD

**Issue by getrdone93** [rsyslog/rsyslog#2456]
I have the following config:

```module(load="imptcp")

input(type="imptcp"
        port="10514"
        ruleset="testRuleset")

$template t_standard,"%msg%\n"

set $.t-stand = exec_template("t_standard");

template(name="combo" type="list") {
        constant(value="{")
        property(name="$.t-stand" format="jsonf" outname="log_line")
        constant(value="}\n")
}

ruleset(name="testRuleset") {
        action(type="omfile"
                file="/opt/testRsyslog/writeFile"
                template="combo")
}
```

### Expected behavior
(after sending data to the `10514` socket over netcat)
```
{"log_line":"<data sent over netcat>"}
```

### Actual behavior
(the message is empty)
```
{"log_line":""}
```

When I change the ruleset's template to `t_standard`
```
ruleset(name="testRuleset") {
        action(type="omfile"
                file="/opt/testRsyslog/writeFile"
                template="t_standard")
}
```
the message is no longer empty. Also, I removed the input's ruleset and used this instead:

```
*.* action(type="omfile"
                file="/opt/testRsyslog/writeFile"
                template="combo")
```
And the message is not empty. I need the configuration to work the first way I provided (the first code block). Is there something wrong with the first code block? Or is this a bug?
### Environment
rsyslogd -v output
```
rsyslogd 8.32.0, compiled with:
	PLATFORM:				x86_64-redhat-linux-gnu
	PLATFORM (lsb_release -d):		
	FEATURE_REGEXP:				Yes
	GSSAPI Kerberos 5 support:		Yes
	FEATURE_DEBUG (debug build, slow code):	No
	32bit Atomic operations supported:	Yes
	64bit Atomic operations supported:	Yes
	memory allocator:			system default
	Runtime Instrumentation (slow code):	No
	uuid support:				Yes
	systemd support:			Yes
	Number of Bits in RainerScript integers: 64

See http://www.rsyslog.com for more information.
```
- platform: CentOS Linux 7 (Core)

**Comment by rgerhards** [comment]
The set is not executed within the rule set! Move it to in there.

**Comment by getrdone93** [comment]
Okay that works, thank you. However, my templates, inputs, rulesets, and actions are all in there own files and I include each of those files from the main `rsyslog.conf` with the `$IncludeConfig` directive. Should this functionality still work then? Can my ruleset file have `set $.var-name = exec_template("t_standard")` where t_standard is in a separate file?

**Comment by getrdone93** [comment]
Okay I got it @rgerhards. Thank you for the quick responses! I appreciate it.

**Comment by rgerhards** [comment]
glad it helped! If you are all set for now, please close the ticket. you can always open a new one for the next question :-)

**Comment by davidelang** [comment]
Yes, all the include files get combined into the config before anything is 
evaluated.
