### ISSUE TITLE
Idea: Update "new issue" template to use HTML comments

### ISSUE THREAD

**Issue by deoren** [rsyslog/rsyslog#2463]
Take a look at what the Microsoft/vscode project is doing:

https://github.com/Microsoft/vscode/issues/new

```
<!-- Do you have a question? Please ask it on https://stackoverflow.com/questions/tagged/vscode. -->

<!-- Use Help > Report Issue to prefill these. -->
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

<!-- Launch with `code --disable-extensions` to check. -->
Does this issue occur when all extensions are disabled?: Yes/No
```

Feel free to close if you don't see anything here that you could use. 

I thought the `--disabled-extensions` suggestion was interesting; while that specific option is only relevant to the Visual Studio Code editor, I thought that a loose analogy for this project would be suggesting that the output of `rsyslogd -N2` be included in the report.

**Comment by rgerhards** [comment]
Mhhh.. I think that's fewer info than we right now request. -N2 may make sense though...

**Comment by deoren** [comment]
> @rgerhards: Mhhh.. I think that's fewer info than we right now request.

No, no, I didn't meant adopt it directly or even replace with relevant rsyslog text, but just as an inspiration for tweaking the existing template here.

I wasn't aware that HTML comments were allowed in the form and hidden from view once the posting went live. Figured I'd share in case it gave you any ideas.

**Comment by rgerhards** [comment]
> I wasn't aware that HTML comments were allowed in the form and hidden from view once the posting went live. Figured I'd share in case it gave you any ideas.

Ah, I now see what you mean. I thought this was just regularly rendered and needed to be deleted like usual. That's indeed pretty nice!
