### ISSUE TITLE
omprog + disk-assisted queue does not honor workerThreads/forceSingleInstance

### ISSUE THREAD

**Issue by bspencer168** [rsyslog/rsyslog#2468]
### Expected behavior
A single external process always being spawned

### Actual behavior
Multiple processes spawned - one for new messages and one for messages being drained from the DA queue. 

### Steps to reproduce the behavior
rsyslog configuration
```
module(load="omprog")

if ($syslogfacility-text == 'local0') then
{
  action(
    type="omprog"
    name="slowwrite"
    binary="/root/slowwrite.sh"
    forceSingleInstance="on"
    queue.type="fixedArray"
    queue.size="101"
    queue.filename="slowwrite"
    queue.workerThreads="1"
  )
}
```

omprog script:
```
#!/bin/sh

pid=$$
while read line
do
        rec=`date`
        sleep 3
        write=`date`
        echo "$pid|$rec|$write|$line" >> /tmp/slowwrite.dat
done
```

Execution:
`while true; do logger -p local0.info testing;done`

Watch the PID in the /tmp/slowwrite.dat in combination with ps and/or the work directory where the DA files are (/usr/lib/rsyslog on RHEL7)

### Environment
- rsyslog version: [e.g. 8.31.0 -- see rsyslogd -v]
8.24.0
- platform: [e.g. Ubuntu 16.04]
Redhat Enterprise Linux 7.4

- for configuration questions/issues, include rsyslog.conf:
Included above in the setup.

**Comment by rgerhards** [comment]
That's actually a documentation issue. A disk assisted queue is actually two queues - an in-memory queue and a disk queue. The doc says that. However, the doc does not tell that this means things like the single instance are on a per-queue level by design. So Having two instances, one for each queue, is expected behavior.

If you want to avoid that, you need to use either a pure disk or a pure in-memory queue. There may be work-arounds involving rulesets queues if having DA **and** a truely single instance is absolutely mandatory.

**Comment by bspencer168** [comment]
Thank you for confirming and providing the option of a pure disk queue (traffic seems to be too spiky to be RAM only and still need to deal with saving the queue to disk at shutdown). Did you want this issue to remain open from the documentation standpoint? otherwise I will close it as my concern/need is addressed.

**Comment by davidelang** [comment]
be aware that a disk-only queue is going to have a huge performance impact, test 
it to make sure you have enough performance to handle your traffic with a 
disk-only queue

**Comment by bspencer168** [comment]
The data needs to flow through the script to correlate lines to create an event, extracts data, and writes out the results to a file (like SEC except specialized and performs better because of that). Would disk-only queues have a larger i/o impact or be slower than having rsyslog write directly to a file and using tail or something to stream the data to the script (which then writes out the extracted data)?

**Comment by rgerhards** [comment]
> Would disk-only queues have a larger i/o impact or be slower than having rsyslog write directly to a file and using tail or something to stream the data to the script (which then writes out the extracted data)?

definitely - it's writing metadata and then re-reading it. 

Please also keep the tracker open, we'll at least add doc.

**Comment by jsiwrk** [comment]
Not yet, see #2813. Will close both issues together when solved (and documented).

**Comment by jsiwrk** [comment]
Considering it a bug for the reasons explained in #2813 (it should work with forceSingleInstance enabled).
