### ISSUE TITLE
Unexpected logs in /var/log/messages

### ISSUE THREAD

**Issue by G3ph4z** [rsyslog/rsyslog#2476]
### Expected behavior
Just casual functions.

### Actual behavior
Rsyslog writes asterisk's log to /var/log/messages after disabled it.

### Environment
- rsyslog version: rsyslogd 8.24.0
- platform: CentOS Linux release 7.2.1511 (Core) 
- for configuration questions/issues, include rsyslog.conf:
`# rsyslog configuration file:
http://paste.denes.cloud/view/cfe095f2

We used it for send logs to another server, but we turned off that, but after it still writes logs to /var/log/messages. On another server (v: rsyslogd 7.4.7) with same config working fine.  In asterisk's logger turned off that too.

I reinstalled to old version (7.4.7) and still not working.

(English is not my mother tongue; please excuse any errors on my part.)

**Comment by deoren** [comment]
Hi @G3ph4z, 

If I understand the report, asterisk is writing log messages to syslog and rsyslog is picking them up and saving them to `/var/log/messages` (the default "catch-all" log file). 

Are you saying that you're trying to prevent asterisk from logging to rsyslog or that you're trying to have log messages for asterisk go to a dedicated file and then stop duplicate log messages from also being saved to `/var/log/messages`?

**Comment by G3ph4z** [comment]
Hi @deoren ,

Yes, you have right. I trying to prevent log duplication.  The asterisk config is correct. We have same configs on other server, and everything working fine.

**Comment by deoren** [comment]
Take a look in the `/etc/rsyslog.d/` folder on the other systems and I suspect you'll find a configuration fragment that routes the asterisk messages into a dedicated file and then uses either the `~` character (deprecated) or the `stop` action to prevent further logging of duplicate messages.

**Comment by G3ph4z** [comment]
Same files on both servers.
```
-rw-r--r-- 1 root root 325 2016 dec   12 ignore-systemd-session-slice.conf
-rw-r--r-- 1 root root  49 okt   20 05.07 listen.conf
```

**Comment by deoren** [comment]
@G3ph4z: Rsyslog writes asterisk's log to /var/log/messages after disabled it.

According to your original post you've taken steps to disable message duplication. I looked at your provided conf file and I don't see anything there that prevents messages from going to `/var/log/messages` via this entry:

```
*.info;mail.none;authpriv.none;cron.none                /var/log/messages
```

I suggested that there was a conf file in `/etc/rsyslog.d/` that was handling that for you as I don't see anything in your provided conf file that is handling that task.

For the systems which are preventing duplicates from going to `/var/log/messages`, which log file are you sending those messages to? Can you share where in your configuration that you've defined this?

**Comment by G3ph4z** [comment]
Asterisk `logger.conf:`
```
[general]
;rotatestrategy=timestamp
[logfiles]
console => notice,error,warning
messages => notice,warning,error
full => notice,warning,error,debug,verbose,dtmf,fax
warning => warning
error => error
;syslog.local0 => warning,error

```
`ignore-systemd-session-slice.conf`:
```
if $programname == "systemd" and ($msg contains "New Session" or$msg contains "Starting Session" or $msg contains "Started Session" or $msg contains "Created slice" or $msg contains "Starting user-") then stop
if $programname == "systemd-logind" and ($msg contains "New session" or $msg contains "Removed session") then stop

```
`listen.conf`:
`$SystemLogSocketName /run/systemd/journal/syslog`

**Comment by deoren** [comment]
```
[general]
;rotatestrategy=timestamp
[logfiles]
console => notice,error,warning
messages => notice,warning,error
full => notice,warning,error,debug,verbose,dtmf,fax
warning => warning
error => error
;syslog.local0 => warning,error
```

I don't know anything about configuring asterisk, but it unless the default setting is to write to a log file, this configuration is not sending log messages to the syslog socket.

**EDIT**

Looking over Asterisk's [Logging Configuration page](https://wiki.asterisk.org/wiki/display/AST/Logging+Configuration) I get the impression that the above configuration actually *disables* sending log messages to syslog.

Assuming that asterisk logs with its program name set to 'asterisk', this should capture messages from asterisk and route them to a specific dedicated file:

```
if ($programname == 'asterisk') then {

    # Write asterisk messages to a dedicated file
    # NOTE: Make sure that rsyslog has permission to
    #       create files in the '/var/log' directory and
    #       also make sure to rotate the log file to
    #       prevent the '/var/log' volume from filling up
    action(
        name="asterisk-messages"
        type="omfile"
        file="/var/log/asterisk.log")

    # Do not log asterisk messages to other files
    stop
}
```

You'll have to make sure that rsyslog has permission to create files in that directory and you will also likely need to craft a logrotate conf file to handle rotating that log file (make sure to send a HUP signal to rsyslog).

Example:

```
# /etc/logrotate.d/asterisk

/var/log/asterisk.log
{
	rotate 7
	daily
	missingok
	notifempty
	delaycompress
	compress
	postrotate
		/etc/init.d/rsyslog rotate > /dev/null
	endscript
}
```

**Comment by G3ph4z** [comment]
Okey, BUT why I have to set this in rSyslog, if the Asterisk logging (to file) is working fine?

**Comment by deoren** [comment]
> @G3ph4z: Okey, BUT why I have to set this in rSyslog, if the Asterisk logging (to file) is working fine?

Based on your original post, my assumption was that you wanted to route messages from asterisk to rsyslog and then on to a local file. I further interpreted your remarks as indicating that you were getting duplicate results, messages in one file (which I don't believe you specified) and then messages also in `/var/log/messages`.

I made this remark where I asked for more information:

> @deoren: For the systems which are preventing duplicates from going to /var/log/messages, which log file are you sending those messages to? Can you share where in your configuration that you've defined this?

You followed up with your notes in https://github.com/rsyslog/rsyslog/issues/2476#issuecomment-365545282 which indicated the configuration for asterisk. I took this post as providing details for the systems where you were getting the desired results.

In my last response, I provided an untested configuration fragment that would allow you to handle messages coming into rsyslog from asterisk and route them to a file and prevent duplication later in `/var/log/messages`. I believe I failed to take into account that systemd may be playing a part here: Asterisk may be logging to stdout which systemd would ingest and then pass to rsyslogd via rsyslog's imjournal module. While the Asterisk configuration you provided doesn't seem to indicate logging to a local file, the configuration used elsewhere may do that in addition to logging to stdout (which rsyslog would pick up from the systemd journal and then write to `/var/log/messages`).

Do you have any desire to intentionally place messages from asterisk into rsyslog (for remote forwarding, filtering, etc) or are you just looking to log from asterisk to a local file on the specific server where asterisk runs? If not, I would guess that disabling console logging would stop the messages from also coming into rsyslog.

**Comment by G3ph4z** [comment]
@deoren You have right, the disabling console logging is solved the problem, but on the #2 server still enabled, and working fine and not forwarding the asterisk's log to messages. We used rSyslog for sending log to remote log server but we changed our mind, so we have to revert.

**Comment by deoren** [comment]
@G3ph4z So both servers run the same version of CentOS, same version of Asterisk, etc? Could you paste the result of running this command (search/replace any private info) for both server 1 and server 2?

`grep -v ';' /path/to/logger.conf`

Replace the '/path/to' part of the path with wherever your installation of Asterisk keeps the `logger.conf` file.

**Comment by G3ph4z** [comment]
srv1:
```
[root@srv1 ~]# grep -v ';' /etc/asterisk/logger.conf 
[general]
[logfiles]
console => notice,error,warning
messages => notice,warning,error
full => notice,warning,error,debug,verbose,dtmf,fax
warning => warning
error => error
```

srv2:
```
[root@srv2 ~]# grep -v ';' /etc/asterisk/logger.conf 
[general]
[logfiles]
console => notice,warning,error
messages => notice,warning,error
full => notice,warning,error,debug,verbose,dtmf,fax
warning => warning
error => error
```

**Comment by deoren** [comment]
@G3ph4z Do those `logger.conf` files reflect the configuration before or after disabling console logging?

**Comment by G3ph4z** [comment]
@deoren Before disabling. My co-workers use console logging, so I cant disable for long time.

**Comment by G3ph4z** [comment]
So for first:
I'm sorry to make you confused.

Asterisk is logging to `/var/log/asterisk/{full, warning, error}`

Your script is solved the problem, so I am very grateful. (and sorry for missed ur solution before)
Yea, maybe something wrong with `systemd ` forgot, so I did not think so.
Probably somebody edited one of config w/o documentation. I will debug that.

Thank you again, and have a nice weekend!

**Comment by deoren** [comment]
> @G3ph4z: I'm sorry to make you confused.

I suspect my quick reviews of the ticket prior to responding is as much to blame, so no worries. Thanks for your patience.

> @G3ph4z: Asterisk is logging to /var/log/asterisk/{full, warning, error}

Thanks for noting that.

> @G3ph4z: Your script is solved the problem, so I am very grateful. (and sorry for missed ur solution before)

Not a problem. The first posting is useful if you want the messages to come into rsyslog and have it handle routing/filtering/forwarding the messages, but the last example is useful if you'd rather Asterisk and systemd handle logging and would like rsyslog to ignore the messages.

> @G3ph4z: Thank you again, and have a nice weekend!

You're welcome, and thanks for confirming this is working for you now. I'll go ahead and close this ticket.

**Comment by Packcy20** [comment]
Hello, I have the same issue - asterisk logs are being duplicated to /var/log/messages
@G3ph4z : where did you insert @deoren  script
I have the following configs.
#### RULES ####

# Log all kernel messages to the console.
# Logging much else clutters up the screen.
#kern.*                                                 /dev/console

# Log anything (except mail) of level info or higher.
# Don't log private authentication messages!

*.info;mail.none;authpriv.none;cron.none                /var/log/messages

# The authpriv file has restricted access.
authpriv.*                                              /var/log/secure

# Log all the mail messages in one place.
mail.*                                                  -/var/log/maillog


# Log cron stuff
cron.*                                                  /var/log/cron

# Everybody gets emergency messages
#*.emerg                                                 *

Thank you for your support

**Comment by G3ph4z** [comment]
@Packcy20 
Before `#### GLOBAL DIRECTIVES ####`

```
#### MODULES ####

# The imjournal module bellow is now used as a message source instead of imuxsock.
$ModLoad imuxsock # provides support for local system logging (e.g. via logger command)
$ModLoad imjournal # provides access to the systemd journal
#$ModLoad imklog # reads kernel messages (the same are read from journald)
#$ModLoad immark  # provides --MARK-- message capability

# Provides UDP syslog reception
#$ModLoad imudp
#$UDPServerRun 514

# Provides TCP syslog reception
#$ModLoad imtcp
#$InputTCPServerRun 514

if ($programname == 'asterisk') then {
        stop
}

#### GLOBAL DIRECTIVES ####

```

**Comment by Packcy20** [comment]
@G3ph4z  Thanks a lot for your support. 
In my case I put the script at the end after #### GLOBAL DIRECTIVES #### and it worked.
