### ISSUE TITLE
structured-data is '-', how can i get it?

### ISSUE THREAD

**Issue by super-l** [rsyslog/rsyslog#2478]
**The following is the client configuration：test.conf**

$ModLoad imfile
$InputFilePollInterval 3
$WorkDirectory /var/lib/rsyslog

$InputFileName /var/log/httpd/access_log
$InputFileTag apache_access
$InputFileStateFile stat_apache_access
$InputFileSeverity info
$InputFilePersistStateInterval 20000
$RepeatedMsgReduction off
$InputRunFileMonitor

$template MYFormat_APPNAME,"<%pri%>%protocol-version% %timestamp:::date-rfc3339% %HOSTNAME% %app-name% %procid% %msgid% [e4d5377e89bc4ddfbe5caa097f1b94a2@32473 tag=\"TAG\"] %msg%\n"

if $programname == 'apache_access' then @@198.13.38.255:514;MYFormat_APPNAME
if $programname == 'apache_access' then ~

**The following are the server information**

{ "msg": "24:19.484263+08:00 superl-centos apache_access - - [e4d5377e89bc4ddfbe5caa097f1b94a2@32473 tag=\"TAG\"] 192.168.192.1 - - [13\/Feb\/2018:13:24:10 +0800] \"-\" 408 - \"-\" \"-\"", "rawmsg": "<134>0 2018-02-13T13:24:19.484263+08:00 superl-centos apache_access - - [e4d5377e89bc4ddfbe5caa097f1b94a2@32473 tag=\"TAG\"] 192.168.192.1 - - [13\/Feb\/2018:13:24:10 +0800] \"-\" 408 - \"-\" \"-\"", "timereported": "2018-02-14T00:07:03.013357+08:00", "hostname": "0", "syslogtag": "2018-02-13T13:", "inputname": "imtcp", "fromhost": "48.1.61.117.broad.js.dynamic.163data.com.cn", "fromhost-ip": "117.61.1.48", "pri": "134", "syslogfacility": "16", "syslogseverity": "6", "timegenerated": "2018-02-14T00:07:03.013357+08:00", "programname": "2018-02-13T13", "protocol-version": "0", **"structured-data": "-"**, "app-name": "2018-02-13T13", "procid": "-", "msgid": "-", "uuid": null, "$!": null }

This  problem that has been bothering me for several days. Please help. Thank you.

**Comment by rgerhards** [comment]
Can you more precisely tell what your question is?

**Comment by super-l** [comment]
thanks,I have solved this problem today。
The main problem is that the rsyslog server can't get struct-data.  I used the new template below, succeeded.

**old template **
$template MYFormat_APPNAME,"<%pri%>%protocol-version% %timestamp:::date-rfc3339% %HOSTNAME% %app-name% %procid% %msgid% [e4d5377e89bc4ddfbe5caa097f1b94a2@32473 tag="TAG"] %msg%\n"

**new template**
$template MYFormat_APPNAME,"<%pri%>1 %timestamp:::date-rfc3339% %HOSTNAME% %app-name% %procid% %msgid% [e4d5377e89bc4ddfbe5caa097f1b94a2@32473 tag="TAG"] %msg%\n"
