### ISSUE TITLE
new style equivalent of $outchannel is missing

### ISSUE THREAD

**Issue by rgerhards** [rsyslog/rsyslog#2479]
It's simply not yet implemented. It is an infrequently used feature that was simply overlooked to port.

I think we should take the idea of $outchannel but use a different set of parameters for omfile causing the same effect. That would also provide more features as it would/should(?) work on dynafiles as well.

Until this is solved, old style can be used.

**Comment by rgerhards** [comment]
Milestone tenatively assigned, we need to weight priorities in the already-filled 8.34 timeframe. Will probably move to 8.35.

**Comment by lmoellendorf** [comment]
> I’m surprised this is an infrequently used feature. Is there some other way to prevent log files from filling up the disk?

I think most use [logrotate](https://github.com/logrotate/logrotate).

**Comment by lmoellendorf** [comment]
See https://github.com/rsyslog/rsyslog/issues/2852#issuecomment-2124910334.

**Comment by rgerhards** [comment]
It's now part of omfile.
