### ISSUE TITLE
in debug mode: wtpShutdownAll assertion fails on stop, in some cases corrupting omfile contents

### ISSUE THREAD

**Issue by StrongestNumber9** [rsyslog/rsyslog#2480]
### Expected behavior
Stops gracefully

### Actual behavior
\# kill $(cat /opt/Fail-Safe/rsyslog/var/rsyslogd.pid)
```
rsyslogd: wtp.c:241: wtpShutdownAll: Assertion `pThis != ((void *)0)' failed.
Aborted (core dumped)
```
When used with full configuration (not included), this message sometimes leaks to omfile but it doesn't have 100% success rate. I provided smallest configuration that crashes reliably.

### Steps to reproduce the behavior
>rsyslog-small.conf

```
$AbortOnUncleanConfig on
$LocalHostName wtpshutdownall
$PreserveFQDN on

global(
    workDirectory="/opt/Fail-Safe/rsyslog/var"
)
module(load="mmjsonparse")
module(
        load="impstats"
        interval="300"
        resetCounters="on"
        format="cee"
        ruleset="metrics-impstat"
        log.syslog="on"
)
ruleset(
        name="metrics-impstat"
        queue.type="Direct"
){
    action(type="omfile" file="/opt/Fail-Safe/stats.log")
}
```
>\# /opt/Fail-Safe/rsyslog/rsyslog/sbin/rsyslogd -f /opt/Fail-Safe/rsyslog/etc/rsyslog-small.conf -i /opt/Fail-Safe/rsyslog/var/rsyslogd.pid -n
### Environment
```
# /opt/Fail-Safe/rsyslog/rsyslog/sbin/rsyslogd -v
rsyslogd 8.32.0, compiled with:
        PLATFORM:                               x86_64-unknown-linux-gnu
        PLATFORM (lsb_release -d):
        FEATURE_REGEXP:                         Yes
        GSSAPI Kerberos 5 support:              No
        FEATURE_DEBUG (debug build, slow code): Yes
        32bit Atomic operations supported:      Yes
        64bit Atomic operations supported:      Yes
        memory allocator:                       system default
        Runtime Instrumentation (slow code):    No
        uuid support:                           Yes
        systemd support:                        No
        Number of Bits in RainerScript integers: 64

```
```
# cat /etc/centos-release
CentOS Linux release 7.4.1708 (Core)
```
```
# uname -a
Linux wtpshutdownall 3.10.0-514.el7.x86_64 #1 SMP Tue Nov 22 16:42:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by StrongestNumber9** [comment]
Pinging @kortemik 

We have container ready where this can be reliably reproduced, and can provide access to it and gdb/valgrind/strace etc outputs if needed.

**Comment by rgerhards** [comment]
While the assertion should not occur, I wonder if you run the debug code inside the production environment? If so, that is not recommended. Just FYI.

**Comment by rgerhards** [comment]
> this message sometimes leaks to omfile but it doesn't have 100% success rate

that's (kind of) normal: debug builds are not designed to run detached (production) and so stdout is closed but assert still emits the message to there.

**Comment by rgerhards** [comment]
@PascalWithopf can you please try to add a testbench test for this

**Comment by PascalWithopf** [comment]
I added a test and was able to reproduce it.
