### ISSUE TITLE
shutdown.enable.ctl-c parameter name invalid - no "-" in param name permitted

### ISSUE THREAD

**Issue by olfway** [rsyslog/rsyslog#2482]
### Expected behavior
rsyslogd should start and die on ctrl+c

### Actual behavior
rsyslog could not interpret master config file

### Steps to reproduce the behavior
```
# /usr/sbin/rsyslogd -N 1 -f /tmp/rsyslog.conf
rsyslogd: version 8.33.0.master, config validation run (level 1), master config /tmp/rsyslog.conf
rsyslogd: error during parsing file /tmp/rsyslog.conf, on or before line 1: invalid character '-' in object definition - is there an invalid escape sequence somewhere? [v8.33.0.master try http://www.rsyslog.com/e/2207 ]
rsyslogd: error during parsing file /tmp/rsyslog.conf, on or before line 1: syntax error on token 'c' [v8.33.0.master try http://www.rsyslog.com/e/2207 ]
rsyslogd: CONFIG ERROR: could not interpret master config file '/tmp/rsyslog.conf'. [v8.33.0.master try http://www.rsyslog.com/e/2207 ]
```

### Environment
- rsyslog version: v8.30.0-1127-g4893d0a01
- platform: Ubuntu 17.10
- for configuration questions/issues, include rsyslog.conf:
```
global(shutdown.enable.ctl-c="on")
```

**Comment by rgerhards** [comment]
this is a feature of the upcomign 8.33 release (Feb, 20th 2018).

**Comment by olfway** [comment]
I was tried on today's master branch from git
Your changes already there and it seems config parser doesn't allow "-" in parameter name

**Comment by rgerhards** [comment]
> I was tried on today's master branch from git

Oh, I just looked at the version, which was given as 8.30. Looking more closer, the version looks strange. Any specific reason you changed it from the default of 8.33.0.master?

**Comment by rgerhards** [comment]
> Your changes already there and it seems config parser doesn't allow "-" in parameter name

oh, and you are right: that's probably the issue. Thx for mentioning it.

**Comment by olfway** [comment]
Sorry for the wrong version, actually rsyslogd -v says "8.33.0.master"

I take "v8.30.0-1127-g4893d0a01" from "git describe" output and didn't noticied that it's 30 instead of 33

**Comment by rgerhards** [comment]
ahhh - thx! I guess git describe gets confused by the stable tags present on master as well. I should have looked closer, sry for that. In any case, it's right in time, I am closing 8.33 dev right now. Patch is underway. :-)

**Comment by olfway** [comment]
I'm trying to rebuild http://rpms.adiscon.com/v8-stable/epel-7/x86_64/RPMS/rsyslog-8.33.0-1.el7.centos.src.rpm and unfortunately, it still has `shutdown.enable.ctl-c` somehow
