### ISSUE TITLE
[omkafka] Temporary 'Local: Host resolution failure' is fatal ?

### ISSUE THREAD

**Issue by mNantern** [rsyslog/rsyslog#2489]
### Expected behavior
Sometimes we have the following error in our logs:

```
Feb  5 13:01:12 localhost rsyslogd[655]: omkafka: kafka error message: -193,'Local: Host resolution failure','kaf.qa.local:9092/bootstrap: Failed to resolve 'kaf.qa.local:9092': Name or service not known' [v8.29.0 try http://www.rsyslog.com/e/2422 ]
```
After that no message are send to Kafka anymore even if the host resolution is now working:

```
ping kaf.qa.local
PING kaf.qa.local (192.168.6.166) 56(84) bytes of data.
64 bytes from kaf.qa.local (192.168.6.166): icmp_seq=1 ttl=64 time=0.223 ms
^C
--- kaf.qa.local ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.223/0.223/0.223/0.000 ms
```

I think that retrying when facing a host resolution error (RD_KAFKA_RESP_ERR__RESOLVE in librdkafka) is reasonable.

### Actual behavior

No message send to kafka after that error

### Steps to reproduce the behavior

I don't know how to simulate a temporary hostname resolution

### Environment
- rsyslog version: rsyslogd 8.29.0
- platform: CentOS Linux release 7.4.1708 (Core) 
- for configuration questions/issues, include rsyslog.conf:

```
#################
#### MODULES ####
#################

$ModLoad imuxsock # provides support for local system logging
$ModLoad imjournal # provides access to the systemd journal
#$ModLoad imklog   # provides kernel logging support (previously done by rklogd)
#$ModLoad immark  # provides --MARK-- message capability

###########################
#### GLOBAL DIRECTIVES ####
###########################
#
# Set max message size for sending and receiving
#
$MaxMessageSize 64k

#
# Set rate limit for messages received.
# 
$SystemLogRateLimitInterval 1
$SystemLogRateLimitBurst 100

#
# Set the default permissions for all log files.
#
$FileOwner root
$FileGroup root
$FileCreateMode 0600
$DirOwner root
$DirGroup root
$DirCreateMode 0750
$PrivDropToUser root
$PrivDropToGroup root
$WorkDirectory /VAR/rsyslog
$Umask 0000

# Turn off message reception via local log socket;
# local messages are retrieved through imjournal now.
$OmitLocalLogging on

# Settings for imjournal (If supported)
$imjournalStateFile imjournal.state
$imjournalIgnorePreviousMessages off
$imjournalRatelimitInterval 600
$imjournalRatelimitBurst 20000

#
# Include all config files in /etc/rsyslog.d/
#
$IncludeConfig /etc/rsyslog.d/*.conf

#
# Emergencies are sent to everybody logged in.
#
*.emerg	:omusrmsg:*
```

Thank you !

**Comment by aturetta** [comment]
Hi mNantern, I'm getting the same error message with 8.37.0
For some reason the output module is adding /bootstrap to the hostname

Did you manage to make it work?

**Comment by aturetta** [comment]
I've been able to get it working only because kafka is in the same machine, I omitted the 'broker' parameter and it connects just fine to localhost:9092

I think the config parser is mangling something, will get a look at it soon

**Comment by aturetta** [comment]
turns out I'm just being dumb....

kafka was up but not running due to problems with zookeeper, once fixed everything works ok

To be honest, the wording of the error message is at least misleading.

**Comment by alorbach** [comment]
Thanks for the update - closing.
