### ISSUE TITLE
imklog: cannot open kernel log (/proc/kmsg): No such file or directory

### ISSUE THREAD

**Issue by steowens** [rsyslog/rsyslog#2491]
### Expected behavior
rsyslog starts and does not emit the error with text to syslog:
   rsyslogd: imklog: cannot open kernel log (/proc/kmsg): No such file or directory.

### Actual behavior
rsyslog starts and emits the error with text to syslog:
   rsyslogd: imklog: cannot open kernel log (/proc/kmsg): No such file or directory.

### Steps to reproduce the behavior
On Windows 10 enable Windows Linux Subsystem WSL.
Start a bash console, by entering bash in the run bar and then selecting bash.

Enter the following commands:
sudo -i
apt-get update
apt-get install rsyslog
service rsyslog start
tail -f /var/log/syslog

### Environment
- rsyslog version:  8.16.0
- platform: Linux LAPTOP-OT0BG026 4.4.0-43-Microsoft #1-Microsoft Wed Dec 31 14:42:53 PST 2014 x86_64 x86_64 x86_64 GNU/Linux
- for configuration questions/issues, include rsyslog.conf:

*Note: rsyslog documentation is available here*:
  [pre-release](http://www.rsyslog.com/doc/master/),
  [current stable release](http://www.rsyslog.com/doc/v8-stable/)

**Comment by rgerhards** [comment]
It looks like the Windows Subsystem does not provide a kernel log, or maybe you do not have permissions to read it.

Can you do a ```sudo cat /proc/kmsg``` and report what happens?
