### ISSUE TITLE
rsyslog-kafka module missing for Ubuntu precise 

### ISSUE THREAD

**Issue by ltagliamonte** [rsyslog/rsyslog#2495]
Hi there,
I'm updating rsyslog on a series of precise ubuntu servers, and the module rsyslog-kafka isn't built for this distro:
```
apt-cache policy rsyslog-kafka
N: Unable to locate package rsyslog-kafka
```
I'm using the stable repo:
```
deb http://ppa.launchpad.net/adiscon/v8-stable/ubuntu precise main
deb-src http://ppa.launchpad.net/adiscon/v8-stable/ubuntu precise main
```

 @rgerhards can we please fix this?

**Comment by ltagliamonte** [comment]
@rgerhards any update on this issue?

**Comment by rgerhards** [comment]
@friedl can you comment on this (@ltagliamonte I only occasionally work on the packaging).

**Comment by friedl** [comment]
@ltagliamonte To build packages on precise, we are missing a dependency to build librdkafka. Thus, we cannot build the package for librdkafka and thus cannot build rsyslog-kafka. 

At least that was the case when I last tried to build the package (some time last year), but I assume it hasn't changed.

**Comment by ltagliamonte** [comment]
Thank you, @friedl.
Closing the issue.
