### ISSUE TITLE
imrelp: protocol failure with low MaxMessageSize 

### ISSUE THREAD

**Issue by alorbach** [rsyslog/rsyslog#2496]
### Expected behavior
normal transfer messages using imrelp & omrelp. 

### Actual behavior
If messages above the MaxDataSize limit are processed, the protocol talk is aborted and the session teared down. Sample debug: 

`1514.038734619:imrelp.c       : imrelp.c: relp session 7 iRet 10010, tearing it down
1514.038752485:imrelp.c       : imrelp.c: librelp: delete sock 7 from epoll set
1514.038761589:imrelp.c       : imrelp.c: hint-frame to send: '0 serverclose 0
So logs being sent, then tearing down in the middle of a log
1514.038777357:imrelp.c       : imrelp.c: relpTcpSend: sock 7, lenbuf 16, send returned 16 [errno 0]
1514.038788710:imrelp.c       : imrelp.c: in destructor: sendbuf 0x7f011c002d00
1514.038816764:imrelp.c       : imrelp.c: librelp: doing epoll_wait
1514.386872108:imrelp.c       : imrelp.c: librelp: done epoll_wait, nEvents:1
`

### Steps to reproduce the behavior
Global maxMessageSize or imrelp's MaxDataSize set to a low value (2KB or less). 

### Environment
- rsyslog version: 8.28 or higher 
- platform: ALL

**Comment by alorbach** [comment]
This is most likely related to this issue 
https://github.com/rsyslog/rsyslog/issues/1741

**Comment by deoren** [comment]
@alorbach See also https://github.com/rsyslog/rsyslog/issues/1782#issuecomment-352041870

**Comment by rgerhards** [comment]
fixed in #2656
requires librelp 1.2.16
