### ISSUE TITLE
Sometimes rsyslog delays system reboot

### ISSUE THREAD

**Issue by jussilei** [rsyslog/rsyslog#2500]
### Actual behavior

Sometimes rsyslog delays system reboot

There are some cases where the rsyslog does not terminate when SIGTERM is sent to it which causes delays in the system reboot

One case seems to be if the TERM signal is sent to the rsyslog before it goes to the mainloop. There is the wait_timeout, which is a long
wait before the bFinished flag is checked.

Second case is when the rsyslog stucks in the pthread_cond_wait forever because all other threads of the process 
have already exited. 

### Stacktrace of the situation

 [Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
0x00007ffff79ab883 in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x6c5798) at ../sysdeps/unix/sysv/linux/futex-internal.h:88

Thread 1 (Thread 0x7ffff7fde2c0 (LWP 2545)):
#0  0x00007ffff79ab883 in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x6c5798) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
#1  __pthread_cond_wait_common (abstime=0x0, mutex=0x6c5748, cond=0x6c5770) at pthread_cond_wait.c:502
#2  __pthread_cond_wait (cond=0x6c5770, mutex=0x6c5748) at pthread_cond_wait.c:655
#3  0x000000000044ae9b in wtpAdviseMaxWorkers ()
#4  0x000000000044f86f in qqueueDestruct ()
#5  0x000000000045947a in actionDestruct ()
#6  0x0000000000424159 in ?? ()
#7  0x0000000000424039 in cnfstmtDestructLst ()
#8  0x0000000000424109 in ?? ()
#9  0x0000000000424039 in cnfstmtDestructLst ()
#10 0x0000000000452282 in rulesetDestruct ()
#11 0x00000000004522c3 in rulesetDestructForLinkedList ()
#12 0x0000000000439e78 in ?? ()
#13 0x0000000000439ee8 in llDestroy ()
#14 0x00000000004524a6 in ?? ()
#15 0x000000000040df9d in main ()

### Environment
- rsyslog version: 8.30-0

*Note: rsyslog documentation is available here*:
  [pre-release](http://www.rsyslog.com/doc/master/),
  [current stable release](http://www.rsyslog.com/doc/v8-stable/)

**Comment by davidelang** [comment]
rsyslog has a number of things that it can be set to do after a sigterm and 
before it shuts down (including potentially writing a lot of data to disk)

You may have found some cases where rsyslog doesn't exit ever exit, or delays 
for reasons don't know about.

What you you tell us about ways to duplicate the problem?

Can you duplicate the problem on the current 8.33 release (8.30 is fairly 
recent, but it would help if you could check on the most current)

David Lang
