### ISSUE TITLE
[omfile] Occasional lack of flush with FlushOnTXEnd and dynfile

### ISSUE THREAD

**Issue by pclouds** [rsyslog/rsyslog#2502]
I've found this bug on rsyslogd-8.4 but I think the bug remains on latest version too. The short description is, when dynamic file name is used sometimes some file may not get flushed even if FlushOnTXEnd is set (and AsyncWriting is not).

I think the problem is in omfile.c, commitTransaction, when you do `strm.Flush(pData->pStrm)`. at the end. When `pData->bDynamicName` is true and we receive more than one message, the messages may end up in different files (e.g. file name is constructed based on syslogtag). pData->pStrm has to be switched accordingly. But we still only flush on the last pStrm. Streams of messages other than the last one may never be flushed at commit transaction time.

Perhaps we can flush when we switch from one file to another? It seems to work for me but I don't know if it results in on-disk incomplete messages or anything.

**Comment by davidelang** [comment]
something that may be related. When I write to a compressed dynfile, and 
repeatedly HUP rsyslog, A fair percentage of the time the compressed file will 
end up corrupted

**Comment by rgerhards** [comment]
Thanks for the bug report, I guess you have described the actual root cause. Nevertheless, could you give the current 8.33.0 a try, just to be sure? Keep in mind that when your description is right, you need to either upgrade or do a manual build in any case...

**Comment by pclouds** [comment]
I've just tried master and the problem is still there.

I set up two rsyslogd servers, the "sender" one has imfile configured to forward messages from 3 files to the receiver via udp. The receiver server simply stores messages on disk using dynfile. Then I do "for i in source-files/*; do echo one >>$i; done" (source-files is where those three watched files are) to trigger this. "ls" on the receiver side confirms that only two out of three receives data until I send SIGHUP.

**Comment by uday3110** [comment]
Running into the same issue. The buffer is randomly flushed when more data is sent. However I cannot get the buffer to flush even with HUP signal as described in you doc. I am using `8.16.0-1` for client/server. Here is my config for server
```
if $syslogfacility-text == 'local0' and $syslogseverity-text == 'info' then {
  action(type="omfile" template="MESSAGE" dynaFile="BPA-DYNAFILE" flushOnTXEnd="on")
  stop
}
```

**Comment by rgerhards** [comment]
@pclouds sorry it took me so long to finally fix this in the official version. Your analysis was right. Many thanks! Should be present in master branch soon.
