### ISSUE TITLE
why not resend logs when the imfile-state file is deleted?

### ISSUE THREAD

**Issue by bosiam** [rsyslog/rsyslog#2503]
### Expected behavior
read log file  from first line and resend logs to remote host
### Steps to reproduce the behavior
rm -rf /var/lib/rsyslog/imfile-state\:******.log_2018-02-26
service rsyslog restart
### Environment
- rsyslog version:  8.29.0
- platform: CentOS release 6.6 (Final)
- for configuration questions/issues, include rsyslog.conf:
ruleset(name="remote1") {
   action(type="mmexternal" binary="/etc/rsyslog.d/json_fmt.py" interface.input="fulljson")
   action(type="omfwd" Protocol="tcp" Target="x.x.x.x" Port="514")
}
input(type="imfile"
    File="/*****/log.log*"
    Facility="user"
    Severity="error"
    Tag="xxxxxxx"
    PersistStateInterval="1"
    reopenOnTruncate="on"
    Ruleset="remote1")

**Comment by rgerhards** [comment]
the state file persists between rsyslog restarts. If you keep it running, it will not reprocess the file. The question really is: why do you want to have duplicate data?

**Comment by bosiam** [comment]
@rgerhards  But i delete the state file before rsyslog restart is not work as also.
I just want reprocess the logs file after i  Modified the mmexternal script.

**Comment by rgerhards** [comment]
TBH this sounds totally illogical to me, because if rsyslog is not active AND there is no state file, we have no way to pick up an old position. Can you create a debug log of such a startup?

**Comment by diepes** [comment]
I also had rsyslogd fail/stop sending logs.   
Had to delete /var/spool/ryslog/imfile-state:xxxx file refering to the log file and restart rsyslogd

**Comment by basilabbas** [comment]
You have to do the following one shot:

    systemctl stop rsyslog; rm /var/spool/rsyslog/the_state_file_you_want_to_delete; systemctl start rsyslog
