### ISSUE TITLE
Template option.jsonf and constant format="jsonf" not working

### ISSUE THREAD

**Issue by unflag** [rsyslog/rsyslog#2504]
### Expected behavior
Proper json generation as explained in docs - https://www.rsyslog.com/doc/v8-stable/configuration/templates.html

### Actual behavior
rsyslog can't parse config file containing these options:

`rsyslogd[22311]: error during parsing file /etc/rsyslog.conf, on or before line 52: parameter 'format' not known -- typo in config file? [v8.33.0 try http://www.rsys>`
`rsyslogd[22311]: error during parsing file /etc/rsyslog.conf, on or before line 52: parameter 'option.jsonf' not known -- typo in config file? [v8.33.0 try http://ww>`

### Steps to reproduce the behavior
Add template to rsyslog.conf and restart daemon:

```
template(name="tmplJson" type="list" option.jsonf="on") {
    property(outname="hostname" name="hostname" format="jsonf")
    property(outname="tag" name="programname" format="jsonf")
    property(outname="message" name="msg" format="jsonf")
    constant(outname="@version" value="1" format="jsonf")
    }
```

config file:
[rsyslog.txt](https://github.com/rsyslog/rsyslog/files/1767149/rsyslog.txt)

### Environment
- rsyslog version: rsyslogd 8.33.0 installed from adiscon repo
- platforms: CentOS 7.3

**Comment by rgerhards** [comment]
This has almost for sure to do with the fact that we got a mixup in the 8.33.0 release process (see #2493). I am currently working on this. I hope we can re-release as 8.33.1 early next week. This will also fix your issue.

**Comment by unflag** [comment]
Thank you, I will test update as soon as it will be released.

**Comment by deoren** [comment]
> @unflag: Thank you, I will test update as soon as it will be released.

FYI: In case you haven't seen it yet, 8.33.1 has been released.

**Comment by unflag** [comment]
Works great, thanks.

**Comment by rgerhards** [comment]
Thx for the confirmation, much appreciated. If you have any additional suggestions, just let us know!
