### ISSUE TITLE
Rsyslog coredump in omfile

### ISSUE THREAD

**Issue by dopuskh3** [rsyslog/rsyslog#251]
Hi

We have some issues on our rsyslog (8.6.0) daemons.

After a bit of inversigation we found that we are crashing in the omfile.c module here:

780	
781	finalize_it:
782		pCache[pData->iCurrElt]->nInactive = 0;
783		RETiRet;
784	}

Looks like we are trying to acccess non-existent cached data. pData value is optimized (build with -O3) and that prevent us from digging deeper into the core file analisys.

Here is the OMFile related configuration: 

$OMFileFlushOnTXEnd off
$OMFileIOBufferSize 131072k
$OMFileAsyncWriting on
$OMFileFlushInterval 30

Please let me know I you have test case I can try to provide additional feedback

F.

**Comment by rgerhards** [comment]
would it be possible that you run rsyslog under valgrind and report any issues it may see? Note that it can happen that the issue does not appear under valgrind control, but it is always worth giving it a try first.

**Comment by dopuskh3** [comment]
We have a very few crashes in our environment (about one per week). I will try to play with the OMFileIOBufferSize and OMFileFlushInterval parameters to see if it has an impact on crash frequency. If I manage to reproduce the crash I will run rsyslog with valgrind.

**Comment by rgerhards** [comment]
Do you have an update for me?

**Comment by alorbach** [comment]
Does the problem still exist in the current version?

**Comment by ab4lfour** [comment]
It's probably the issue where if dynafile creation fails (or something else fails in prepareDynFile()...), rsyslogd would segfault on the pCache entry for the current element, because pData->iCurrElt is likely still -1:

https://github.com/rsyslog/rsyslog/commit/008f0097b610742595034cdab381749dbc00f93f

fixed in 8.12.0
