### ISSUE TITLE
$MaxMessageSize Setting does not take effect? rsyslog 8.3*

### ISSUE THREAD

**Issue by xiagujinqiao** [rsyslog/rsyslog#2525]
Hi
### Expected behavior
If the log line size  less than $MaxMessageSize, it is sent successfully.
### Actual behavior
log line size less than $MaxMessageSize, but send fail, I think is a bug.
rsyslog errorfile output: { "errcode": 10, "errmsg": "Broker: Message size too large", ...}

### Environment
- rsyslog version:
rsyslogd 8.33.1, compiled with:
	PLATFORM:				x86_64-redhat-linux-gnu
	PLATFORM (lsb_release -d):
	FEATURE_REGEXP:				Yes
	GSSAPI Kerberos 5 support:		No
	FEATURE_DEBUG (debug build, slow code):	No
	32bit Atomic operations supported:	Yes
	64bit Atomic operations supported:	Yes
	memory allocator:			system default
	Runtime Instrumentation (slow code):	No
	uuid support:				Yes
	systemd support:			No
	Number of Bits in RainerScript integers: 64
- platform: 
CentOS release 6.5 (Final)
- for configuration questions/issues, include rsyslog.conf:

- egrep -v  "^$|^#" /etc/rsyslog.conf
$ModLoad imuxsock # provides support for local system logging (e.g. via logger command)
$ModLoad imklog   # provides kernel logging support (previously done by rklogd)
$ModLoad imfile
$ModLoad omkafka
$ModLoad mmsequence
$ActionFileDefaultTemplate RSYSLOG_TraditionalFileFormat
$IncludeConfig /etc/rsyslog.d/*.conf
*.info;mail.none;authpriv.none;cron.none;local5.none;local1.none                /var/log/messages
authpriv.*                                              /var/log/secure
mail.*                                                  -/var/log/maillog
cron.*                                                  /var/log/cron
*.emerg  :omusrmsg:*
uucp,news.crit                                          /var/log/spooler
local7.*                                                /var/log/boot.log

- egrep -v  "^$|^#" /etc/rsyslog.d/achievement-achievement.conf
$MaxMessageSize 32k
$WorkDirectory /data/rsyslogstate
$MainMsgQueueType LinkedList
$MainMsgQueueFileName local5.info
$MainMsgQueueHighWatermark 240000
$MainMsgQueueLowWatermark 100000
$MainMsgQueueMaxDiskSpace 10g
$MainMsgQueueSize 40000
$MainMsgQueueSaveOnShutdown on
$MainMsgQueueDiscardSeverity 1
$MainMsgQueueDiscardMark 32000
$MainMsgQueueTimeoutEnqueue 3000
template(name="achievement" type="string" string="%hostname% %syslogtag% %rawmsg%\n")
ruleset(name="achievement") {
  if $syslogtag == 'achievement-achievement.log' then {
  action (
    queue.workerthreads="1"
    type="omkafka"
    topic="achievement"
    broker=["kafka01:9092","kafka02:9092","kafka03:9092","kafka04:9092","kafka05:9092"]
    template="achievement"
    partitions.auto="on"
    confParam=["compression.codec=snappy","batch.num.messages=100","queue.buffering.max.messages=100","message.send.max.retries=1","topic.metadata.refresh.interval.ms=60000","socket.keepalive.enable=true"]
    errorfile="/data/rsyslogstate/log_kafka_failures.log"
  )
}
}
input(type="imfile" freshStartTail="off" Tag="achievement-achievement.log" File="/data/logs/achievement/achievement.log" Facility="local5" Severity="info" reopenOnTruncate="on" Ruleset="achievement")

- kafka conf
egrep -v '^$|^#' /data/kafka2/config/server.properties
broker.id=1
host.name=kafka01
log.dirs=/data/kafka2/kafka-logs
zookeeper.connect=zk01:2181,zk02:2181,zk03:2181
listeners=PLAINTEXT://:9092
port=9092
message.max.bytes=32768
socket.send.buffer.bytes=1048576
socket.receive.buffer.bytes=1048576
socket.request.max.bytes=104857600
num.partitions=3
num.recovery.threads.per.data.dir=1
log.retention.hours=168
log.segment.bytes=1073741824
log.flush.interval.messages=10000
log.flush.interval.ms=60000
log.retention.check.interval.ms=300000
zookeeper.connection.timeout.ms=6000
auto.create.topics.enable=false
delete.topic.enable=true
num.network.threads=32
num.io.threads=64
num.replica.fetchers=8
auto.leader.rebalance.enable=true
queued.max.requests=5000
replica.fetch.max.bytes=10240000
controller.socket.timeout.ms=30000
controlled.shutdown.enable=true

- rsyslog errorfile messages
cat /data/rsyslogstate/log_kafka_failures.log
{ "errcode": 10, "errmsg": "Broker: Message size too large", "data": "ploanbonus_php_1 achievement-achievement.log NOTICE: 18-03-09 09:57:14 100.105.8.137 [URI:\/achievement\/callback\/loan-trigger] errno[0] log_id[646955895aa1e9fa49da146c426702] 用户[572497606239176479] 成就[3] 执行计算公式[{totalBorrowAmount} >= 1000000] 解析结果[165410.00 >= 1000000] mdc_uri[\/achiement\/call\/loan-trigger] mdc_traceId[6469558951e9fa49da146c32426702] mdc_clientIP[100.10.70.55] mdc_inBG[0] ai_tags[T_BORROW_LENDOUT_FINISH_TAG] ai_topic[T_LENDOUT_FINISH_TOPIC] ai_body[{\"type\":1,\"payor\":\"6234709366611870\",\"productUser\":\"5724976239176479\",\"productID\":\"83834063234862130001\",\"productSource\":0,\"rate\":\"24.00\",\"payee\":\"5724606239176479\",\"orderID\":null,\"transID\":\"8383533907631106\",\"laundryUuid\":\"8383523404318721\",\"amount\":\"230.00\",\"principal\":\"230.00\",\"payResult\":1,\"lendType\":1,\"loanFlag\":null}] ai_msgid[646A0F0500002A9F000001C39B69D7] ai_orderId[T_BORROW_LENDOUT_FINISH_TAG_8383534404318721] mdc_startTime[1520560634727] TIMER_TOTAL[12ms] \n" }
{ "errcode": 10, "errmsg": "Broker: Message size too large", "data": "ploanbonus_php_1 achievement-achievement.log NOTICE: 18-03-09 09:57:14 100.105.8.137 [URI:\/achievement\/call\/loan-trigger] errno[0] log_id[646955895aa1e9fa49146c32426702] output[{\"flag\":\"success\"}] mdc_uri[\/achievement\/call\/loan-trigger] mdc_traceId[6469558aa1e9fa49da146c32426702] mdc_clientIP[100.10.7.55] mdc_inBG[0] ai_tags[T_BORROW_LENDOUT_FINISH_TAG] ai_topic[T_LENDOUT_FINISH_TOPIC] ai_body[{\"type\":1,\"payor\":\"6234722096611870\",\"productUser\":\"572497606176479\",\"productID\":\"83834063214862130001\",\"productSource\":0,\"rate\":\"24.00\",\"payee\":\"572406276479\",\"orderID\":null,\"transID\":\"838353407631106\",\"laundryUuid\":\"838353423404318721\",\"amount\":\"230.00\",\"principal\":\"230.00\",\"payResult\":1,\"lendType\":1,\"loanFlag\":null}] ai_msgid[646A0F050009F00000129B69D7] ai_orderId[T_BORROW_LENDOUT_FINISH_TAG_83834234043721] mdc_startTime[1520560634727] TIMER_TOTAL[12ms] \n" }
{ "errcode": 10, "errmsg": "Broker: Message size too large", "data": "ploanbonus_php_1 achievement-achievement.log DEBUG: 18-03-09 09:57:15 100.10.8.144 [\/data\/application\/ploanframework\/apis\/models\/Request.php:155] errno[0] log_id[tcui07pqercoktumiugad5uhl7] [ApiContext] msg[achievement_call_debt_result] url[http:\/\/100.10.22.21\/debt\/friend-service\/inner-host-extend] retry[1] http_code[200] cost[0.020208] name_lookup_time[0.001293] connect_time[0.001587] pre_transfer_time[0.001589] start_transfer_time[0.020187] redirect_time[0] \n" }

thanks

**Comment by xiagujinqiao** [comment]
Single log is less than 32k, $MaxMessageSize 32k at the top of all conf

**Comment by deoren** [comment]
@xiagujinqiao I don't know this for sure, but I suspect your problem may be due to your mixing the [`obsolete legacy`](http://www.rsyslog.com/doc/v8-stable/configuration/conf_formats.html) configuration format with the [`advanced`](http://www.rsyslog.com/doc/v8-stable/configuration/conf_formats.html) configuration format.

If I recall correctly, you have to use the matching parameter/directive for a format to set the maximum message size value.

Since you are using the [`advanced`](http://www.rsyslog.com/doc/v8-stable/configuration/conf_formats.html) configuration format for your `omkafka` action (output), I believe you will need to get the max message size via the `global()` configuration object.

Example (with `...` indicating other options within the `global()` object now shown here):

```
global (
...
    maxMessageSize="32k"
...
)
```

On a (loosely) related note, there appears to be a bug with RELP (possibly just `imrelp`) where it does not honor the `global(maxMessageSize)` parameter. You instead have to also set the `MaxDataSize` parameter to whatever you opted to set `global(maxMessageSize)` to in order to prevent `imrelp` from falling back to the built-in default of 8k (which is far too small for some log messages that we're passing).

See rsyslog/rsyslog#1782 for details regarding that issue.

I don't see a separate parameter to configure the max message size for `omkafka`, so it may not be affected in the same way as `imrelp`. In that case, I would try setting `maxMessageSize` via the `global()` configuration object to resolve your issue.

**Comment by xiagujinqiao** [comment]
@deoren thanks,so I will change my conf?
change from old to it:
global (
  maxMessageSize="32k"
  workDirectory="/data/rsyslogstate"
)
template(name="achievement" type="string" string="%hostname% %syslogtag% %rawmsg%\n")
  ruleset(name="achievement"
  queue.type="LinkedList"
  queue.saveonshutdown="on"
  queue.filename="local5.info"
  queue.size="400000"
  queue.maxdiskspace="10g"
  queue.discardseverity="4"
  queue.workerthreads="1"
  queue.timeoutenqueue="3000"
) {
  if $syslogtag == 'achievement-achievement.log' then {
  action (
    type="omkafka"
    topic="achievement"
    broker=["IP1:9092","IP2:9092","IP3:9092","IP4:9092","IP5:9092"]
    template="achievement"
    partitions.auto="on"
    confParam=["compression.codec=snappy","batch.num.messages=100","queue.buffering.max.messages=100","message.send.max.retries=1","topic.metadata.refresh.interval.ms=60000","socket.keepalive.enable=true"]
    errorfile="/data/rsyslogstate/log_kafka_failures.log"
  )
}
}
input(type="imfile" freshStartTail="off" Tag="achievement-achievement.log" File="/data/logs/achievement/achievement.log" Facility="local5" Severity="info" reopenOnTruncate="on" Ruleset="achievement")

I will continue to observe.

**Comment by xiagujinqiao** [comment]
sry. if batch.num.messages single message.bytes  > message.max.bytes,kafka will output :Broker: Message size too large.
so i think not related to mixing the obsolete legacy configuration format with the advanced configuration format.
-
According to the kafka docs the message.max.bytes property operates on message batches, not individual batches, so you must either increase this value on the broker, or limit the batch size on the producer (by setting message.max.bytes on the producer accordingly or batch.num.messages=1).
Do note that you will need to include batching overhead (say topicLen + 100 bytes or so).

**Comment by xiagujinqiao** [comment]
close issue
