### ISSUE TITLE
Empty log messages.

### ISSUE THREAD

**Issue by bentleg** [rsyslog/rsyslog#2542]
I receiveing logs via syslog from firewall but in log messages have not any informations. E.g.
```
Mar 14 09:25:26 uahqsrv-cpm01 CheckPoint[25801] 
Mar 14 09:25:26 uahqsrv-cpm01 CheckPoint[25801] 
Mar 14 09:25:26 uahqsrv-cpm01 CheckPoint[25801] 
Mar 14 09:25:26 uahqsrv-cpm01 CheckPoint[25801] 
```

But when logs from firewall sending in Splunk with same settings, i receve next logs:
```
03 14 2018 11:31:55 192.168.11.111 <LOC0:INFO> 1 - uahqsrv-cpm01 CheckPoint 7459 - [action:"Drop"; flags:"400644"; ifdir:"inbound"; ifname:"bond3.13"; logid:"0"; loguid:"{0x0,0x0,0x0,0x0}"; origin:"10.10.13.21"; originsicname:"CN=INET-GW-01,O=uahqsrv-cpm01.uahqsrv----------outzone:"External"; product:"VPN-1 & FireWall-1"; proto:"17"; s_port:"63421"; security_inzone:"Interface_inside"; service:"53"; service_id:"UDP_All_SourcePort"; src:"192.168.70.3"; ]
03 14 2018 11:31:55 192.168.11.111 <LOC0:INFO> 1 - uahqsrv-cpm01 CheckPoint 7459 - [action:"Drop"; flags:"400644"; ifdir:"inbound"; ifname:"bond3.13"; logid:"0"; loguid:"{0x0,0x0,0x0,0x0}"; origin:"10.10.13.21"; originsic------------outzone:"External"; product:"VPN-1 & FireWall-1"; proto:"17"; s_port:"63541"; security_inzone:"Interface_inside"; service:"53"; service_id:"UDP_All_SourcePort"; src:"192.168.70.3"; ]
```
So why message in syslog is empty?
### Environment
- rsyslog version: 8.24
- PLATFORM: x86_64-redhat-linux-gnu

In config i have only one rule:
$template FILENAME,"/var/log/rsyslog/%$year%%$month%%$day%/%fromhost-ip%/syslog.log"
*.* ?FILENAME

From another sources i receiving logs with full information.

**Comment by rgerhards** [comment]
This looks like malformed RFC5424 format.

**Comment by bentleg** [comment]
But another log collectors receiving full messages. And this logs from chekpoint firewall, so i doubt what it have wrong format.
Are there any another ideas?

**Comment by davidelang** [comment]
It looks as if these logs actually have a blank message section, they put all 
their info in the structured data section of the message.

log with the template RSYSLOG_DebugFormat and let's see what the logs look like 
over the wire, but I think you will need to decode the structured data and then 
use a template that puts that data into the message.

David Lang
