### ISSUE TITLE
Feature Request - imjournal statistics gathering.

### ISSUE THREAD

**Issue by monobaila** [rsyslog/rsyslog#2549]
I'm currently a very happy user running 8.24.0 on CentOS7. I've been playing around with the impstats module with a view to setting up some monitoring of my rsyslog pipeline. So far it's offered some great insight to the internals which I'll be able to create alerts from (failed counters and discarded counters in particular).

One thing I'd like to be able to track is the number of messages submitted via imjournal, the majority of my inputs come from here so it's a really good metric to baseline, it could be useful for identifying runaway loggers spamming the pipeline. 

It doesn't look like statistics gathering is setup for imjournal - I'd love to see this in a future release. From my naive reading of the code in tcpsrv.c that does the same thing it doesn't look like a massive amount of changes but my C is no where near good enough to make an attempt!

Once I've made some more progress with my monitoring project I'll happily make a contribution to the documentation with things I've learnt which might be useful for others.

**Comment by rgerhards** [comment]
Thanks for your kind words and the suggestion. This looks like a valuable addition. Tentatively assigning 8.34 release goal, but I am not sure we can make it as it closes soon.
