### ISSUE TITLE
How to convert Unix timestamp to specified date format e.g yyyy-MM-dd-hh

### ISSUE THREAD

**Issue by yfliuyanyan** [rsyslog/rsyslog#2560]
### Expected behavior
I want to convert a Unix timestamp to a formatted date. For example: 
1521450441123  -> 2018-03-19 17:7:21
how to implement it?

Thanks!

### Environment
- rsyslog version: [e.g. 8.31.0 -- see rsyslogd -v]
- platform: [e.g. Ubuntu 16.04]
- for configuration questions/issues, include rsyslog.conf:

*Note: rsyslog documentation is available here*:
  [pre-release](http://www.rsyslog.com/doc/master/),
  [current stable release](http://www.rsyslog.com/doc/v8-stable/)

**Comment by yfliuyanyan** [comment]
I'm looking forward for your answer.

**Comment by rgerhards** [comment]
As nobody else has taken this so far, let me give at least some pointers. This is basically rfc3339 format. You can use the property replacer to extract the first part and the final part.

We also plan to add better support for arbitrary formats as well.

**Comment by rgerhards** [comment]
@PascalWithopf can you post a template sample? 
@deoren I think we should some specific cases to  the doc, but unsure where...

**Comment by davidelang** [comment]
didn't we just add a parse_time()/format_time() pair of functions? (or did we 
only talk about what they needed to be)

David Lang

**Comment by deoren** [comment]
> @davidelang: didn't we just add a parse_time()/format_time() pair of functions? (or did we only talk about what they needed to be)

Looks like `format_time` was added in #1814 (8.30.0 milestone), and `parse_time` added in #1925 (8.31.0 milestone).

- http://www.rsyslog.com/doc/master/rainerscript/functions.html#parse-time-timestamp
- http://www.rsyslog.com/doc/master/rainerscript/functions.html#format-time-unix-timestamp-format-str

**Comment by deoren** [comment]
> @rgerhards: @deoren I think we should some specific cases to the doc, but unsure where...

It would probably be good to take a look at the new page created as part of the work being done by @PascalWithopf on rsyslog/rsyslog-doc#637. If that initial pass works out then examples could be provided there.

A follow-up step would be to find where to drop references to those examples in the docs. Templates perhaps, or perhaps the properties section where `$hour` and other system properties are discussed (http://www.rsyslog.com/doc/v8-stable/configuration/properties.html#time-related-system-properties).

**Comment by PascalWithopf** [comment]
@rgerhards It is possible to do it in two ways.
First in the template when using the timestamp property just specify the date format like this:
```
%timestamp:::date-rfc3164%
```
Or like @davidelang and @deoren said use the format_time() function:
```
format_time(1521450441123, "date-rfc3164")
```

**Comment by rgerhards** [comment]
@PascalWithopf note that the OP did want a very specific format - I am not sure if format_time() can provide this at the moment. Would be good to check.

We should add and address a doc issue tracker based on https://github.com/rsyslog/rsyslog/issues/2560#issuecomment-376750348

**Comment by PascalWithopf** [comment]
@rgerhards yes both is also possible with rfc-3339.

**Comment by rgerhards** [comment]
> @rgerhards yes both is also possible with rfc-3339.

ahhh... I may have mixed up this with some other issue. @yfliuyanyan does that solve your issue?

**Comment by yfliuyanyan** [comment]
I read the doc for format_time, the first param is required to be second. But my timestamp is millisecond.
Could you give me an example? Thanks!

**Comment by yfliuyanyan** [comment]
And another question, how can I use the formatted time variable in template?

**Comment by davidelang** [comment]
The current version doesn't handle fractional seconds, you can convert the ms 
based timestamp to a second based one.

to use the result in a template, you do something like

set !.converted_timestamp = format_time();

then you can use $!.converted_timestamp or in a template like you would any 
other variable.

**Comment by mrworkman** [comment]
If only the jerk who added `format_time` hadn't disappeared for 5 months.. who was that guy?

> the first param is required to be second. But my timestamp is millisecond.
I think rainerscript supports basic arithmetic, doesn't it? Divide your timestamp by 1000 before sending to `format_time` ?

**Comment by davidelang** [comment]
nothing stops anyone else from adding features to that function. It's far less 
work to add another feature to an existing function (especially when we have a 
plan to do so) than to justify adding a new function to start with ;-)

If you want more, submit code (or sponsor someone else to submit code if you 
don't have the skills or time to do it right)

**Comment by yfliuyanyan** [comment]
**my conf as follows:**
module(load="builtin:omfile")
module(load="imkafka")
module(load="mmjsonparse")

set $.formatedTime=format_time($!time, "date-rfc3339"); # declare local variable
set $.xx = "quux";

template(name="var_test" type="list") {
    constant(value="time=")
    property(name="$!time")
    constant(value="-formatedTime=")
    property(name="$.formatedTime") # test local variable formatedTime
    constant(value="-xx=")
    property(name="$.xx")  # test local variable xx
    constant(value="\n")
}

ruleset(name="sink-to-local") {
    action(type="mmjsonparse" cookie="" useRawMsg="on")
    action(type="omfile"
           template="var_test"
           file="/tmp/output.log"
          )
}

input(
        type="imkafka"
        ruleset="sink-to-local"
        topic="mylog"
        broker=["127.0.0.1:9091"]
)

**output from /tmp/output.log:**
time=1525254054000-formatedTime=-xx=

There is no value for my local variable formatedTime and even xx. Where am I wrong?

**Comment by rgerhards** [comment]
The
```
set $.formatedTime=format_time($!time, "date-rfc3339"); # declare local variable
set $.xx = "quux";
```
is not part of your ruleset, so it is not executed. Move it down into the ruleset.

**Comment by yfliuyanyan** [comment]
Wow, it works! @rgerhards Thank you so much!

**Comment by sinontaylor** [comment]
yes this is excellent! Is there a list of additional functions like format_time() providing different functionality? Could not find in the search on rsyslog.com or in the property replacer page (where I thought they might be). Cheers, Simon

**Comment by davidelang** [comment]
sorry for the late reply, right now format_time() is very limited, the idea is 
to make it far more flexible in the future, but it hasn't bubbled up the top of 
anyone's todo list (contributions welcome :-) )

**Comment by sinontaylor** [comment]
Thanks. I actually meant other functions but found them here https://www.rsyslog.com/doc/v8-stable/rainerscript/functions/idx_built-in_functions.html. Cheers, Simon
