### ISSUE TITLE
LinkedList Queue not Encrypted

### ISSUE THREAD

**Issue by valsoray17** [rsyslog/rsyslog#2575]
Changing the queue.type from "disk" to "LinkedList" the file is *not* encrypted after shutdown, but rather, it is in clear text. Here is the rule config I used:

`*.*     action(type="omfwd" protocol="tcp" queue.type="linkedlist" queue.filename="fwdExternal1" queue.maxdiskspace="1g" queue.cry.provider="gcry" queue.cry.key="testtesttesttest" queue.saveonshutdown="on" action.resumeRetryCount="-1" target="unaccessible-server" port="6514")`

Changing it to "disk" results in the encrypted file after shutdown.

### Environment
- rsyslog version: 8.32.0
- platform: Fedora 27

**Comment by valsoray17** [comment]
I've seen the same issue was mentioned on one of the forums in 2015, but there was no solution. Is there any other steps I can perform to confirm or disprove that this is a bug?

Thank you

**Comment by davidelang** [comment]
On Tue, 3 Apr 2018, Yaroslav Sapozhnyk wrote:

> Is there any other steps I can perform to confirm or disprove that this is a 
> bug?

generate a queue file and show that the contents of the file are not encrypted 
if it's a disk-assisted queue vs a disk-only queue.

**Comment by valsoray17** [comment]
### For disk-assisted queue
Action configuration:
`*.* action(type="omfwd" protocol="tcp" queue.type="linkedlist" queue.filename="fwdExternal1" queue.maxdiskspace="1g" queue.cry.provider="gcry" queue.cry.key="testtesttesttest" queue.saveonshutdown="on" action.resumeRetryCount="-1" target="unaccessible-server" port="6514")`

The contents of the file:
> .
<Obj:1:msg:1:
+iProtocolVersion:2:1:0:
+iSeverity:2:1:5:
+iFacility:2:1:1:
+msgFlags:2:1:0:
+ttGenTime:2:10:1522790646:
+tRcvdAt:3:33:2:2018:4:3:17:24:6:523357:6:-:4:0:
+tTIMESTAMP:3:33:2:2018:4:3:17:24:6:523357:6:-:4:0:
+pszTAG:1:14:testuser[7284]::
+pszRawMsg:1:9:Test12345:
+pszHOSTNAME:1:9:localhost:
+pszInputName:1:9:imjournal:
+pszRcvFrom:1:9:localhost:
+pszRcvFromIP:1:9:127.0.0.1:
+json:1:885:{ "PRIORITY": "5", "_BOOT_ID": "95845ac6c09c458cb5191fd58f2d0528", "_MACHINE_ID": "5ecadda819ff4027b9aaa9046f364676", "_HOSTNAME": "localhost.localdomain", "_UID": "0", "_GID": "0", "_CAP_EFFECTIVE": "3fffffffff", "_TRANSPORT": "syslog", "SYSLOG_FACILITY": "1", "_COMM": "logger", "_EXE": "\/usr\/bin\/logger", "_SYSTEMD_USER_SLICE": "-.slice", "_SELINUX_CONTEXT": "unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023", "_AUDIT_LOGINUID": "1000", "_AUDIT_SESSION": "2", "_SYSTEMD_OWNER_UID": "1000", "_SYSTEMD_SLICE": "user-1000.slice", "_SYSTEMD_CGROUP": "\/user.slice\/user-1000.slice\/session-2.scope", "_SYSTEMD_SESSION": "2", "_SYSTEMD_UNIT": "session-2.scope", "_SYSTEMD_INVOCATION_ID": "9a03b3b1a2f94f20a06a9e5094470d26", "SYSLOG_IDENTIFIER": "esapyar", "MESSAGE": "Test12345", "_PID": "7284", "_CMDLINE": "logger Test12345", "_SOURCE_REALTIME_TIMESTAMP": "1522790646523335" }:
+pCSAPPNAME:1:7:testuser:
+offMSG:2:1:0:
\>End

### For disk-only queue
Action configuration
`*.*     action(type="omfwd"
queue.type="disk" queue.fileName="enc"
queue.cry.provider="gcry" queue.cry.key="testtesttesttest"
target="unaccessible-serve"
port="6514")`

The file contents in this case contain some gibberish like:

> <90>Å}Ü4·Ä÷^C^BéÚº è><91>Û¯L^ROJò<9d>Ä/aVÙ;^Y<9d>­ µÀý<8a><85>Û^V¯Å^[_^_ö° æÿ^Pí^Zµ^P¬Iªg]ý<87>ßî^M<91>(<8b>ª"¬ðüì³o\<9c>D^Zý½^L·^Zî¤*[ëÚ?

**Comment by rgerhards** [comment]
implementing tests myself
