### ISSUE TITLE
mmjsonparse with invalid container name causes assertion failure

### ISSUE THREAD

**Issue by StrongestNumber9** [rsyslog/rsyslog#2584]
### Expected behavior
Refuse to start. Error message on -N9.

### Actual behavior
(Wait until impstats runs)

4791.351477132:impstats.c     : ../action.c: action[metrics-impstats-mmjsonparse] transitioned to state: itx
4791.351482631:impstats.c     : ../action.c: entering actionCalldoAction(), state: itx, actionNbr 0
4791.351490472:impstats.c     : mmjsonparse.c: mmjsonparse: toParse: ' { "name": "global", "origin": "dynstats", "values": { "foo.ops_overflow": 0, "foo.new_metric_add": 0, "foo.no_metric": 0, "foo.metrics_purged": 0, "foo.ops_ignored": 0, "foo.purge_triggered": 0, "bar.ops_overflow": 0, "bar.new_metric_add": 0, "bar.no_metric": 0, "bar.metrics_purged": 0, "bar.ops_ignored": 0, "bar.purge_triggered": 0 } }'
rsyslogd: msg.c:3054: getJSONRootAndMutexByVarChar: Assertion `c == '!' || c == '.' || c == '/'' failed.
Aborted (core dumped)

### Steps to reproduce the behavior
```sh
module(
    load="impstats"
    interval="300"
    resetCounters="on"
    format="cee"
    ruleset="fooruleset"
    log.syslog="on"
)
```
```sh
action(
    name="fooname"
    type="mmjsonparse"
    container="foobar"
)
```

### Environment
rsyslogd 8.32.0, compiled with:
        PLATFORM:                               x86_64-unknown-linux-gnu
        PLATFORM (lsb_release -d):
        FEATURE_REGEXP:                         Yes
        GSSAPI Kerberos 5 support:              No
        FEATURE_DEBUG (debug build, slow code): Yes
        32bit Atomic operations supported:      Yes
        64bit Atomic operations supported:      Yes
        memory allocator:                       system default
        Runtime Instrumentation (slow code):    No
        uuid support:                           Yes
        systemd support:                        No
        Number of Bits in RainerScript integers: 64

See http://www.rsyslog.com for more information.

CentOS Linux release 7.4.1708 (Core)

Linux foo 3.10.0-514.el7.x86_64 #1 SMP Tue Nov 22 16:42:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

*Note: rsyslog documentation is available here*:
  [pre-release](http://www.rsyslog.com/doc/master/),
  [current stable release](http://www.rsyslog.com/doc/v8-stable/)

**Comment by rgerhards** [comment]
bug confirmed via #2644

**Comment by rgerhards** [comment]
It's a debug only issue as far as the segfault is concerned. In non-debug mode, an error message is emitted and rsyslog continues to run (except of course for the wrongly configured mmjsonparse).
