### ISSUE TITLE
rsyslog accepts messages to ruleset but does not process them intermittently 

### ISSUE THREAD

**Issue by bspencer168** [rsyslog/rsyslog#2585]
### Expected behavior
Messages come into the ruleset and flow down through the conditioned action statements

### Actual behavior
This is unfortunately a reoccurring intermittent issue which has been happening roughly once a week for the last 3-4 weeks though it does not appear to be time based. While this is a new environment which has been set up and has gone through various configuration times up to and after these issues started we have been unable to determine a specific time/trigger partly because of the delay in when the issue is actually triggered.

rsyslog accepts messages via UDP & TCP and processes them for a period of time and then appears to continue to accept messages the messages from UDP sources into the DA queue but they stay there. TCP sources continue to stay connected but I see very little from them. restarting rsyslog restores normal functionality. It's noted that the TCP 514 connections to the server have a sizable Recv-Q. 

The issue is currently happening but that unfortunately is only for a limited time as /var/lib/rsyslog will eventually fill.

Attached:

[rsyslog.zip](https://github.com/rsyslog/rsyslog/files/1845400/rsyslog.zip) - contains the files
    rsyslog.stats - the imstats data from before & during the issue
    configs.tar.gz - the configuration files - remote-audit.conf is the one which contains the remoteaudit ruleset

[rsyslog-debug-1M.zip](https://github.com/rsyslog/rsyslog/files/1845407/rsyslog-debug-1M.zip) - rsyslog debug data for a short time

[ps.txt](https://github.com/rsyslog/rsyslog/files/1845438/ps.txt) - ps output of the rsyslog threads (ps -L -o lwp,pid,ppid,state,start,rss,vsz,cmd,comm:50 -p 2259)

### Steps to reproduce the behavior
Unknown.

### Environment
- rsyslog version: 8.24.0 (RHEL7 delivered)
- platform: Redhat Enterprise Linux 7
- for configuration questions/issues, include rsyslog.conf:

**Comment by rgerhards** [comment]
8.24 is pretty old. There have been many bug fixes to the queue subsystem around 8.30. So I would strongly suggest to update to current rsyslog (8.33.1 at the time of this writing). I guess it will solve your issue.

I have to admit that I as a developer will also not look at 8.24, as I know many bugs have been fixed, so this is wasted time from my PoV. Sorry to be that blunt, but I guess it's best to set expectations straight. I'll keep the issue open in case others want to jump in.

**Comment by davidelang** [comment]
check to make sure you don't have an output that is blocked and/or an action 
queue filling up.

That's the typical problem that generates these sorts of reports.

**Comment by bspencer168** [comment]
The output is local disk and while a separate filesystem than the queue files, the queue files end up being written without issues. The ruleset only has a queue and not the individual actions. 

Rainer's point taken and I prefer the honesty over beating around the bush. This is a point which will be used when asking RedHat to rebaseline the the version on RHEL7. We are purposefully trying to stick with their provided version from a support perspective which bit us this time.

Closing this issue.

**Comment by davidelang** [comment]
On Wed, 28 Mar 2018, bspencer168 wrote:

> The output is local disk and while a separate filesystem than the queue files, 
> the queue files end up being written without issues. The ruleset only has a 
> queue and not the individual actions.

are any of the individual actions blocked?

> Rainer's point taken and I prefer the honesty over beating around the bush. 
> This is a point which will be used when asking RedHat to rebaseline the the 
> version on RHEL7. We are purposefully trying to stick with their provided 
> version from a support perspective which bit us this time.

who gives you better support, RedHat or us :-)

If RedHat is giving you better support, stick with the version they give you and 
that they support.

If we give you better support, move to the current version so that we can 
support you.

David Lang

**Comment by rgerhards** [comment]
I wouldn't mind if Red Hat is forced to update their packages to something more recent... ;-)

**Comment by bspencer168** [comment]
While the server in question is a syslog concentrator for us, it is also just syslog. Each deviation from RedHat means we need to monitor more releases and update when released as we have requirements to run the most recent vendor provided version. We are able to point to RedHat for that as our vendor with no additional overhead of maintaining each individual component of the OS. Sometimes utilizing a 3rd or 4th party for support & updates does make sense from our standpoint.

I figured a client requesting an updated version from RedHat would be a good thing and maybe get them to update the version. There has been a lot of changes around the 8.31 & 8.33 versions it seems.  RedHat just updated to 8.24 in RHEL 7.4 (7.5 is in beta now) so i don't know how willing they will be. They do back port/fix some bugs in the various versions too but in this case, I can't point to the specific issue/upstream fix. If interested in what they fix/backport, search for rsyslog in https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html-single/7.3_release_notes/ & https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html-single/7.4_release_notes/

**Comment by rgerhards** [comment]
Just for your information: this statement is simply plain wrong:
```
Previously, when the logrotate utility with copytruncate option was rotating a log file, the imfile module might not have read all of the log messages from the file being rotated. As a consequence, these log messages were lost. The imfile module has been extended to handle this situation. As a consquence, messages are no longer lost when logrotate copytruncate is used on log files.
```
(7.4 changelog)

copytruncate is never a good choice and will guarantee that on a busy system you loose logs. It is flagged as "experiemental" inside our doc. You may want to file a bug report with RH.
