### ISSUE TITLE
omhiredis packages

### ISSUE THREAD

**Issue by vdmitrief** [rsyslog/rsyslog#2605]
Hi,
I have about a hundred servers mostly CentOs and Ubuntu on each of them is installed rsyslog of different versions.
I need support for the omhiredis.so output module on these servers.
How can I automate the process of updating and compiling rsyslog with the support of the omhiredis module?
Can I compile some standard rsyslog for Centos and Ubuntu, and then from these packages to install on all servers? How can I do it ?
Is there any version in the repository compiled with support omhiredis or should I compile procedure on each of the servers?

**Comment by rgerhards** [comment]
@friedl: what blocks us from building these?

**Comment by vdmitrief** [comment]
too long and a lot of human resources are required for this procedure

**Comment by friedl** [comment]
Hm ... actually on Ubuntu there is a rsyslog-redis package for most of the current releases. 

For CentOS, this wasn't a requirement yet, but I can enable it and see if it builds.

**Comment by rgerhards** [comment]
If somebody knows how to solve dependency issues for CentOS, pls let us know. Right now, I close the tracker, but will re-open when we get new information.
