### ISSUE TITLE
RELP loosing messages [when not configured to retry]

### ISSUE THREAD

**Issue by ikostoski** [rsyslog/rsyslog#2610]
Rsyslog looses messages with RELP when 'receiver' is shutdown temporarily. I believe intended usage of RELP protocol would be preventing loss of messages in this scenario, i.e. not an edge-case but expected routine situation, central log server which is temporary shutdown for i.e. maintenance.

Please see 'Steps to reproduce' below.

Looking trough the sources, it seems that there is problem how rsyslog transactions and librelp sessions interact. The omrelp module forwards the messages to librelp and considers them 'commited' as far as rsyslogd is concerned. In case something happens either to 'sender' or 'receiver' these messages in librelp buffer are in no-mans-land and won't get queued if connection problem is detected at later point, or even after connection problem is detected. The amount of messages in no-mans-land is limited by the internal session queue of librelp. They get dropped somewhere when connection is reestablished

This is different from what other 'transnational' modules do (i.e. omelasticsearch), which wait for response from remote server/service before reporting back to the core whether transaction was commited or not.

I do not know if it is feasible to change omrelp module to wait until queue size inside librelp is empty (which will require exposing such API function via the 'Client' librelp interface) and what else will such blocking call block ?
Or if connection is already detected as broken, whether to rollback the transactions until connection is re-established and possibly to 'de-queue' un-acked messages from librelp and preprend them back into rsyslog queue ?

### Expected behavior
Messages are queued and delivered after 'receiver' becomes available again. 

### Actual behavior
Some amount of messages (probably limited by librelp internal queue) is lost

### Steps to reproduce the behavior
Freshly installed CentOS 7.4 minimal VMs, called 's1' and 's2', latest updates (2018-04-03), latest v8-stable rsyslod (via v8-stable repo), SELinux disabled, firewalld disabled.

Sender config (i.e. s1:`/etc/rsyslog.d/relp-sender.conf`):
```
module(load="omrelp")
if prifilt("user.info") then {
  action(
    type="omrelp"
    target="s2"
    port="2514"
  )
}
```

Receiver config (i.e. s2:`/etc/rsyslog.d/relp-listen.conf`):
```
module(load="imrelp")
input(
  type="imrelp"
  port="2514"
)
if ($fromhost-ip != "127.0.0.1") then {
  action(type="omfile" file="/var/log/relp.log")
  stop
}
```
Steps:
```bash
#(on sender 's1')
logger "Message 1"
logger "Message 2"
#(stop rsyslogd on receiver 's2')
logger "Message 3"
...
logger "Message 5"
#(start rsyslogd on receiver 's2')
logger "Message 6"
logger "Message 7"
```
Result on receiver s2, file `/var/log/relp.log`
```
Apr  3 15:04:56 s1 root[1346]: Message 1
Apr  3 15:05:17 s1 root[1347]: Message 2
Apr  3 15:06:25 s1 root[1352]: Message 7
```

### Environment
- rsyslog version: 8.31.1+
- platform: CentOS-7-x86_64-Minimal-1708

**Comment by rgerhards** [comment]
you need to tell the relp action that it should retry (parameter ```action.resumeRetryCount```). If not, rsyslog defaults apply, which means messages are discarded after one failure. So it is not the RELP protocol that loses messages here, but the rsyslog core who does this intentional.

action param doc: http://www.rsyslog.com/doc/v8-stable/configuration/actions.html

**Comment by ikostoski** [comment]
I missed that parameter in the documentation. Now it works as expected.

With retry set and disk queue enabled, in the my worst test case, when sender is restarted while receiver is down, only single message is lost. Which, I believe, is quite acceptable compared to risk of that happening.

Thank You.

**Comment by rgerhards** [comment]
> With retry set and disk queue enabled, in the my worst test case, when sender is restarted while receiver is down, only single message is lost. Which, I believe, is quite acceptable compared to risk of that happening.

This is a know issue which can be cured, but I had no time so far to do this and also no sponsors (which seem to indicate that it indeed is not a big issue).

Both librelp and rsyslog would need to be modified so that rsyslog can pull the librelp-internal "not acked list" of messages and persist it to disk state (and vice versa on restart). The loss can actually be a full relp window size of messages if things go really bad. Just FYI.

**Comment by atc0005** [comment]
> I had no time so far to do this and also no sponsors

Just curious, but do you have an official bug/feature bounty for specific feature enhancements or is additional functionality provided by standard contracts with adiscon.com?

**Comment by davidelang** [comment]
On Wed, 4 Apr 2018, Adam Chalkley wrote:

>> I had no time so far to do this and also no sponsors
>
> Just curious, but do you have an official bug/feature bounty for specific 
> feature enhancements or is additional functionality provided by standard 
> contracts with adiscon.com?

sponsored development is usually done via standard Professional Services 
contracts with adiscon.

David Lang
