### ISSUE TITLE
wrong configure switch for atomic ops

### ISSUE THREAD

**Issue by mbiebl** [rsyslog/rsyslog#2612]
configure.ac in 8.34.0 contains
```
AC_ARG_ENABLE(regexp,
        [AS_HELP_STRING([--enable-atomic-operations],[Enable atomic operation support @<:@default=yes@:>@])],
```

I'm pretty sure the ```regexp``` is a C&P mistake

**Comment by rgerhards** [comment]
Thanks for reporting. It indeed is a C&P mistake, and a fix is underway in https://github.com/rsyslog/rsyslog/pull/2604. I just didn't manage to include it in 8.34. Will merge that now.
