### ISSUE TITLE
replace all select() calls with poll()

### ISSUE THREAD

**Issue by rgerhards** [rsyslog/rsyslog#2615]
This is far easier and portable than epoll, but relieves us of the problematic issues with select.

**Comment by rgerhards** [comment]
couple of select() remain:
* those solely used for waiting (just timeout param non-NULL)
* gss-misc and imgssapi - this is contributed functionality we cannot even test
* one select on initial fork of rsyslog - no problem here, not fd can be >= 1024

So the following remain to do:
- [ ] imudp
- [ ] imuxsock

We may consider to change some other places just for sake of removing the API at all from the code, That might be useful for automated checks, but is not yet a priority.

**Comment by towolf** [comment]
This entirely fixed our problems with rsyslog and we can now hold inbound TCP connections from 2500 hosts. Thank you, @rgerhards!

**Comment by rgerhards** [comment]
Thx for confirming, much appreciated!
