### ISSUE TITLE
ksi-ls12: rpm for version 8.34 are not available

### ISSUE THREAD

**Issue by joschi99** [rsyslog/rsyslog#2621]
We have installed rsyslog on CentOS 6.9 thourgh rpm repo (http://rpms.adiscon.com/v8-stable) and the package rsyslog-ksi-ls12 is not more available.

```
yum update
Loaded plugins: refresh-packagekit, security
Setting up Update Process
Resolving Dependencies
--> Running transaction check
---> Package rsyslog.x86_64 0:8.33.0-1.el6 will be updated
--> Processing Dependency: rsyslog = 8.33.0-1.el6 for package: rsyslog-ksi-ls12-8.33.0-1.el6.x86_64
---> Package rsyslog.x86_64 0:8.34.0-1.el6 will be an update
---> Package rsyslog-elasticsearch.x86_64 0:8.33.0-1.el6 will be updated
---> Package rsyslog-elasticsearch.x86_64 0:8.34.0-1.el6 will be an update
---> Package rsyslog-mmjsonparse.x86_64 0:8.33.0-1.el6 will be updated
---> Package rsyslog-mmjsonparse.x86_64 0:8.34.0-1.el6 will be an update
---> Package rsyslog-mmnormalize.x86_64 0:8.33.0-1.el6 will be updated
---> Package rsyslog-mmnormalize.x86_64 0:8.34.0-1.el6 will be an update
---> Package rsyslog-mysql.x86_64 0:8.33.0-1.el6 will be updated
---> Package rsyslog-mysql.x86_64 0:8.34.0-1.el6 will be an update
--> Finished Dependency Resolution
Error: Package: rsyslog-ksi-ls12-8.33.0-1.el6.x86_64 (@rsyslog_v8)
```

**Comment by rgerhards** [comment]
sorry, we currently cannot build this module due to https://github.com/rsyslog/rsyslog/issues/2517

**Comment by rgerhards** [comment]
@friedl as #2517 is settled now, we could possibly create the KSI packages again via a patch, based on this commit: https://github.com/rsyslog/rsyslog/pull/2631/commits/b56fd2bd2d972cc3de553408f16e6203e904c863

Alternatively, we could wait for the next release, which gives us a better baseline.

@joschi99 what's your thought on this?

**Comment by joschi99** [comment]
@rgerhards,
I think that maybe is better to release the fix with next release.

**Comment by friedl** [comment]
@allanpark What is your opinion on this? Should we push a new RPM version with the fix?

@joschi99 That would at least be the easiest way.

**Comment by rgerhards** [comment]
packages created as part of the 8.35.0 release process
