### ISSUE TITLE
 rsyslogd: command 'InputTCPServerStreamDriverAuthMode' is currently not permitted 

### ISSUE THREAD

**Issue by naveen230** [rsyslog/rsyslog#2626]
Hello all,
When I do syslog restart I get this error,

Starting system logger: rsyslogd: command 'InputTCPServerStreamDriverAuthMode' is currently not permitted - did you already set it via a RainerScript command (v6+ config)? [v8.33.1 try http://www.rsyslog.com/e/2222 ]
rsyslogd: command 'InputTCPServerStreamDriverPermittedPeer' is currently not permitted - did you already set it via a RainerScript command (v6+ config)? [v8.33.1 try http://www.rsyslog.com/e/2222 ]
rsyslogd: command 'InputTCPServerStreamDriverMode' is currently not permitted - did you already set it via a RainerScript command (v6+ config)? [v8.33.1 try http://www.rsyslog.com/e/2222 ]

here are the modules I use,
#### MODULES ####
$MaxMessageSize 500k
module(load="imuxsock") # provides support for local system logging (e.g. via logger command)
module(load="imklog")   # provides kernel logging support (previously done by rklogd)
module(load="ommail") # provides email support
module(load="omkafka") #load kafka module

Any help will be appreciated!

**Comment by davidelang** [comment]
please post your full config

**Comment by naveen230** [comment]
# rsyslog configuration file
# note that most of this config file uses old-style format,
# because it is well-known AND quite suitable for simple cases
# like we have with the default config. For more advanced
# things, RainerScript configuration is suggested.

# For more information see /usr/share/doc/rsyslog-*/rsyslog_conf.html
# If you experience problems, see http://www.rsyslog.com/doc/troubleshoot.html

#### MODULES ####
$MaxMessageSize 500k
module(load="imuxsock") # provides support for local system logging (e.g. via logger command)
module(load="imklog")   # provides kernel logging support (previously done by rklogd)
#module(load"immark")  # provides --MARK-- message capability
module(load="ommail") # provides email support
"rsyslog.conf" 117L, 4253C
# Provides TCP syslog reception
# for parameters see http://www.rsyslog.com/doc/imtcp.html
module(load="imtcp") # needs to be done just once
input(type="imtcp" port="8069")

#### GLOBAL DIRECTIVES ####

# Use default timestamp format
$ActionFileDefaultTemplate RSYSLOG_TraditionalFileFormat

# File syncing capability is disabled by default. This feature is usually not required,
# not useful and an extreme performance hit
#$ActionFileEnableSync on

# Include all config files in /etc/rsyslog.d/
$IncludeConfig /etc/rsyslog.d/*.conf

# Set the default permissions for all log files.
#
$FileOwner root
$FileGroup adm
$FileCreateMode 0644
$DirCreateMode 0755
$Umask 0022

#### SYSLOG ENCRYPTION ####

#$ModLoad imuxsock # local messages
#$ModLoad imtcp # TCP listener

# make gtls driver the default
$DefaultNetstreamDriver gtls






#Certificates
$DefaultNetstreamDriverCAFile /etc/ssl/certs/ca-cert.pem
$DefaultNetstreamDriverCertFile /etc/ssl/certs/server-cert.pem
$DefaultNetstreamDriverKeyFile /etc/ssl/certs/server-key.pem

$InputTCPServerStreamDriverAuthMode x509/name
$InputTCPServerStreamDriverPermittedPeer *domainname
$InputTCPServerStreamDriverMode 1 # run driver in TLS-only mode
$InputTCPServerRun 10514 # start up listener at port 10514


#### RULES ####

# Log all kernel messages to the console.
# Logging much else clutters up the screen.
#kern.*                                                 /dev/console

# Log anything (except mail) of level info or higher.
# Don't log private authentication messages!
*.info;mail.none;authpriv.none;cron.none                /var/log/messages

# The authpriv file has restricted access.
authpriv.*                                              /var/log/secure

# Log all the mail messages in one place.
mail.*                                                  /var/log/maillog


# Log cron stuff
cron.*                                                  /var/log/cron

# Everybody gets emergency messages
*.emerg                                                 :omusrmsg:*

# Save news errors of level crit and higher in a special file.
uucp,news.crit                                          /var/log/spooler

# Save boot messages also to boot.log
local7.*                                                /var/log/boot.log
# ### begin forwarding rule ###
# The statement between the begin ... end define a SINGLE forwarding
# rule. They belong together, do NOT split them. If you create multiple
# forwarding rules, duplicate the whole block!
# Remote Logging (we use TCP for reliable delivery)
#
# An on-disk queue is created for this action. If the remote host is
# down, messages are spooled to disk and sent when it is up again.
#$WorkDirectory /var/lib/rsyslog # where to place spool files
#$ActionQueueFileName fwdRule1 # unique name prefix for spool files
#$ActionQueueMaxDiskSpace 1g   # 1gb space limit (use as much as possible)
#$ActionQueueSaveOnShutdown on # save messages to disk on shutdown
#$ActionQueueType LinkedList   # run asynchronously
#$ActionResumeRetryCount -1    # infinite retries if host is down
# remote host is: name/ip:port, e.g. 192.168.0.1:514, port optional
#*.* @@remote-host:514
# ### end of the forwarding rule ###

**Comment by davidelang** [comment]
please switch to the new format (module() and input()) and put the encryption 
parameters there.

It's far clearer what is going on with the new syntax, and mixing the syntax 
(using module(load="imtcp") and input(type="imtcp") as well as the obsolete 
multi-line style) can have unexpected problems.

If this is a config that has been working in the past and is now broken with a 
new version, that's a clear bug we need to fix. But if this is a new config, 
please use the new syntax.

**Comment by rgerhards** [comment]
the error is actually totally correct and up to the point: as the input() statement for imtcp has been used, the obsolete legacy statements can no longer be used. side-note: If the input() were done in legacy as well, you would get no error message, but things would not work either as they would be in the wrong sequence -- avoiding these hard to find issues is exactly the reason why the old format has been obsoleted.

**Comment by naveen230** [comment]
I used what I found in the rsyslog documentation(in the example),
https://www.rsyslog.com/doc/v8-stable/configuration/modules/imtcp.html

Won't I be able to add parameters for $InputTCPServerRun and where is the new syntax documented?

**Comment by davidelang** [comment]
On Fri, 6 Apr 2018, Rainer Gerhards wrote:

> the error is actually totally correct and up to the point: as the input() 
> statement for imtcp has been used, the obsolete legacy statements can no 
> longer be used. side-note: If the input() were done in legacy as well, you 
> would get no error message, but things would not work either as they would be 
> in the wrong sequence -- avoiding these hard to find issues is exactly the 
> reason why the old format has been obsoleted.

It's messier than that, he has an input() for port 514 early on, and then is 
trying to use the old-style syntax for a different port (IIRC 1514) later

As you say, this is why this sort of multi-line config is deemed obsolete now 
and strongly discouraged

**Comment by davidelang** [comment]
On Fri, 6 Apr 2018, naveen230 wrote:

> I used what I found in the rsyslog documentation(in the example),
> https://www.rsyslog.com/doc/v8-stable/configuration/modules/imtcp.html

that page has been updated since you last looked at it, it no longer describes 
the obsolete config syntax, only the new syntax

> Won't I be able to add parameters for $InputTCPServerRun and where is the new syntax documented?

you don't use $InputTCPServerRun, you use input() instead. Your config uses the 
input() syntax early in the config, and that's why the older style syntax is 
flagged as an error.

David Lang

**Comment by naveen230** [comment]
Will this syntax work?

input(type="imtcp" port="8069" StreamDriver="gtls" StreamDriverMode="1")

Because it didn't work for me!

**Comment by paul-at-k** [comment]
The documentation here: https://www.rsyslog.com/doc/v8-stable/tutorials/tls.html is not updated. I am finding it very difficult to get from the configuration in this document to your recommended configuration using the new syntax.

**Comment by paul-at-k** [comment]
So it should look something like the following - this is fairly close to the tutorial that is out of date. However note this is still not working for me YMMV.

global(
      DefaultNetstreamDriverCAFile="/path/to/ca-cert.pem" 
      DefaultNetstreamDriverCertFile="/path/to/server-cert.pem" 
      DefaultNetstreamDriverKeyFile="/path/to/server-key.pem" 
)
module(
     load="imtcp" 
     StreamDriver.Name="gtls" 
     StreamDriver.Mode="1"
     StreamDriver.Mode="anon"
 )
 input(type='imtcp' port='514)

**Comment by akarollil** [comment]
This does work for me with rsyslog v8.32 on Ubuntu 18.04:

```
# make gtls driver the default
$DefaultNetstreamDriver gtls

# certificate files
$DefaultNetstreamDriverCAFile /path/to/ca-cert.pem
$DefaultNetstreamDriverCertFile /path/to/server-cert.pem
$DefaultNetstreamDriverKeyFile /path/to/server-key.pem

# provides TCP syslog reception with encryption
module(load="imtcp" StreamDriver.Name="gtls" StreamDriver.Mode="1" StreamDriver.AuthMode="anon")
input(type="imtcp" port="514" )

```

But yes, it would be great if https://www.rsyslog.com/doc/v8-stable/tutorials/tls.html were updated because most people would be adding on to the default rsyslog configuration which uses module() rather than the legacy options for the same. @rgerhards, is updating the tutorial something you are planning? I could create a PR to update https://github.com/rsyslog/rsyslog-doc/blob/master/source/tutorials/tls_cert_server.rst?
