### ISSUE TITLE
fmhttp should not be enabled if --disable-libcurl is used

### ISSUE THREAD

**Issue by mbiebl** [rsyslog/rsyslog#2628]
Version: 8.34.0

The new fmhttp function module requires libcurl. So if ```--disable-libcurl``` has been passed to configure, the fmhttp function module should not be built.
If both ```--disable-libcurl``` and ```--enable-fmhttp``` are passed to ```./configure``` and error should be displayed that fmhttp requires libcurl.

**Comment by mbiebl** [comment]
I wanted to add a remark, that mmkubernetes has the same problem. I uses libcurl but apparently it adds a check for libcurl itself
```
if test "x$enable_mmkubernetes" = "xyes"; then
        PKG_CHECK_MODULES([CURL], [libcurl])
fi
```
So this is inconsistent.
Either we drop the ```--enable-libcurl``` configure switch, and every module which requires curl checks for it itself, or we make all modules, which use libcurl (mmkubernetes, omhttpfs, fmhttp) respect ```--disable-libcurl```

**Comment by rgerhards** [comment]
The ```--enable-libcurl``` switch was actually added to be able to disable libcurl functionality inside the rsyslog core, see https://github.com/rsyslog/rsyslog/commit/46f4f43b8f911d11d9076bc9b2870d5eb339f71a As this is no longer the case, it needs to be removed. This also means the modules need to check themselves.
