### ISSUE TITLE
rsyslog write log into the wrong file

### ISSUE THREAD

**Issue by Cloud-Leung** [rsyslog/rsyslog#2636]
### Expected behavior
rsyslog can write log into /var/log/message
### Actual behavior
but it write into /var/log/messages-20180402
### Environment
- rsyslog version: [8.26.1 -- see rsyslogd -v]
- platform: [x86_64-redhat-linux-gnu]
- for configuration questions/issues, include rsyslog.conf:
rsyslog.conf
------------------------------------------------------------------------
![2](https://user-images.githubusercontent.com/16982375/38599611-c1ce63ce-3d93-11e8-974c-49ef1d1f1baa.png)
![3](https://user-images.githubusercontent.com/16982375/38599612-c2264ee0-3d93-11e8-9154-cac136afe6df.png)
![4](https://user-images.githubusercontent.com/16982375/38599613-c2755652-3d93-11e8-8e29-437046874e36.png)

------------------------------------------------------------------------
![1](https://user-images.githubusercontent.com/16982375/38599377-e7b71d0c-3d92-11e8-8a1c-55de20715e4d.png)
look this ,you can see that ,now time is Wed Apr 11 14:16:51 CST 2018.
today log was writed into /var/log/messages-20180402.
this file's update time is Apr 11 13:34, but it shouldn't be, it shoud write into /var/log/message.

**Comment by rgerhards** [comment]
It would be good if you could post the config in text form - I cannot search inside the images ;-) From looking over it, all looks well. I guess there is some include file that changes behavior. Be sure to show all include files (in text form!).

**Comment by davidelang** [comment]
what is in your /etc/rsyslog.d directory?

8.26 is getting fairly old (current is 8.34, so about a year old), can you 
reproduce the problem with  current version?

**Comment by Cloud-Leung** [comment]
@rgerhards i'm sorry about that , this is the config file text .

# rsyslog configuration file
# note that most of this config file uses old-style format,
# because it is well-known AND quite suitable for simple cases
# like we have with the default config. For more advanced 
# things, RainerScript configuration is suggested.

# For more information see /usr/share/doc/rsyslog-*/rsyslog_conf.html
# If you experience problems, see http://www.rsyslog.com/doc/troubleshoot.html

#### MODULES ####

module(load="imuxsock") # provides support for local system logging (e.g. via logger command)
module(load="imklog")   # provides kernel logging support (previously done by rklogd)
#module(load"immark")  # provides --MARK-- message capability

# Provides UDP syslog reception
# for parameters see http://www.rsyslog.com/doc/imudp.html
#module(load="imudp") # needs to be done just once
#input(type="imudp" port="514")

# Provides TCP syslog reception
# for parameters see http://www.rsyslog.com/doc/imtcp.html
#module(load="imtcp") # needs to be done just once
#input(type="imtcp" port="514")


#### GLOBAL DIRECTIVES ####

# Use default timestamp format
$ActionFileDefaultTemplate RSYSLOG_TraditionalFileFormat

# File syncing capability is disabled by default. This feature is usually not required,
# not useful and an extreme performance hit
#$ActionFileEnableSync on

# Include all config files in /etc/rsyslog.d/
$IncludeConfig /etc/rsyslog.d/*.conf


#### RULES ####

# Log all kernel messages to the console.
# Logging much else clutters up the screen.
#kern.*                                                 /dev/console

# Log anything (except mail) of level info or higher.
# Don't log private authentication messages!
*.info;mail.none;authpriv.none;cron.none                /var/log/messages

# The authpriv file has restricted access.
authpriv.*                                              /var/log/secure

# Log all the mail messages in one place.
mail.*                                                  /var/log/maillog


# Log cron stuff
cron.*                                                  /var/log/cron

# Everybody gets emergency messages
*.emerg                                                 :omusrmsg:*

# Save news errors of level crit and higher in a special file.
uucp,news.crit                                          /var/log/spooler

# Save boot messages also to boot.log
local7.*                                                /var/log/boot.log


# ### begin forwarding rule ###
# The statement between the begin ... end define a SINGLE forwarding
# rule. They belong together, do NOT split them. If you create multiple
# forwarding rules, duplicate the whole block!
# Remote Logging (we use TCP for reliable delivery)
#
# An on-disk queue is created for this action. If the remote host is
# down, messages are spooled to disk and sent when it is up again.
#$WorkDirectory /var/lib/rsyslog # where to place spool files
#$ActionQueueFileName fwdRule1 # unique name prefix for spool files
#$ActionQueueMaxDiskSpace 1g   # 1gb space limit (use as much as possible)
#$ActionQueueSaveOnShutdown on # save messages to disk on shutdown
#$ActionQueueType LinkedList   # run asynchronously
#$ActionResumeRetryCount -1    # infinite retries if host is down
# remote host is: name/ip:port, e.g. 192.168.0.1:514, port optional
#*.* @@remote-host:514
# ### end of the forwarding rule ###

**Comment by Cloud-Leung** [comment]
@davidelang em, I updated rsyslog to 8.34 on a machine just now. but i need to observe one or two days to see if it is normal.
in rsyslog.d have two config file ,graylog-rsyslog.conf and listen.conf.
In order to avoid the format, I added a point at the beginning of the every line.
------------------------------------------------------------------------------------------
graylog-rsyslog.conf
.module(load="imfile"  mode="inotify")
.# load required modules
.module(load="imtcp")
.module(load="omkafka")
.input(type="imfile"
.      freshStartTail="on" 
.      File="/var/log/messages"
.      Tag="syslog,messages,text" ruleset="writeRemoteData")
.
.input(type="imtcp"
.      port="10514"
.      ruleset="writeRemoteData")
.template(name="tenant_json" type="list") {
.    constant(value="{") constant(value="\"version\":\"1\"") constant(value=",")
.    constant(value="\"logType\":\"vendor\"") constant(value=",")
.    constant(value="\"timestamp\":")            property(name="timegenerated" dateformat="unixtimestamp") constant(value=",")
.    constant(value="\"vendorIdentifier\":\"")   property(name="$!provider_id" format="json") constant(value="\",")
.    constant(value="\"container\":\"")		property(name="$!container" format="json" ) constant(value="\",")
.    constant(value="\"image\":\"")		property(name="$!image" format="json" ) constant(value="\",")
.    constant(value="\"source\":\"")             property(name="$myhostname" format="json" ) constant(value="\",")
.    constant(value="\"fromIp\":\"")             constant(value="10.43.66.137")  constant(value="\",")
.    constant(value="\"severity\":\"")           property(name="syslogseverity-text" format="json") constant(value="\",")
.    constant(value="\"facility\":\"")           property(name="syslogfacility-text" format="json") constant(value="\",")
.    constant(value="\"programName\":\"")        property(name="programname" format="json") constant(value="\",")
.    constant(value="\"procId\":\"")             property(name="procid" format="json") constant(value="\",")
.    constant(value="\"message\":")              property(name="msg" position.from="2") constant(value="}") constant(value="\n")
.}
.template(name="tenant_text" type="list") {
.    constant(value="{") constant(value="\"version\":\"1\"") constant(value=",")
.    constant(value="\"logType\":\"vendor\"") constant(value=",")
.    constant(value="\"timestamp\":")            property(name="timegenerated" dateformat="unixtimestamp") constant(value=",")
.    constant(value="\"vendorIdentifier\":\"")   property(name="$!provider_id" format="json") constant(value="\",")
.    constant(value="\"container\":\"")		property(name="$!container" format="json" ) constant(value="\",")
.    constant(value="\"image\":\"")		property(name="$!image" format="json" ) constant(value="\",")
.    constant(value="\"source\":\"")             property(name="$myhostname" format="json" ) constant(value="\",")
.    constant(value="\"fromIp\":\"")             constant(value="10.43.66.137")  constant(value="\",")   
.    constant(value="\"severity\":\"")           property(name="syslogseverity-text" format="json") constant(value="\",")
.    constant(value="\"facility\":\"")           property(name="syslogfacility-text" format="json") constant(value="\",")
.    constant(value="\"programName\":\"")        property(name="programname" format="json") constant(value="\",")
.    constant(value="\"procId\":\"")             property(name="procid" format="json") constant(value="\",")
.    constant(value="\"message\":\"")            property(name="msg" position.from="2" format="json") constant(value="\"}") constant(value="\n")
.}
.template(name="platform_json" type="list") {
.    constant(value="{") constant(value="\"version\":\"1\"") constant(value=",")
.    constant(value="\"logType\":\"platform\"") constant(value=",")
.    constant(value="\"timestamp\":")            property(name="timegenerated" dateformat="unixtimestamp") constant(value=",")
.    constant(value="\"container\":\"")          property(name="$.provider_container" format="json") constant(value="\",")
.    constant(value="\"image\":\"")		property(name="$!image" format="json" ) constant(value="\",")
.    constant(value="\"source\":\"")             property(name="$myhostname" format="json" ) constant(value="\",")
.    constant(value="\"fromIp\":\"")             constant(value="10.43.66.137")  constant(value="\",")
.    constant(value="\"severity\":\"")           property(name="syslogseverity-text" format="json") constant(value="\",")
.    constant(value="\"facility\":\"")           property(name="syslogfacility-text" format="json") constant(value="\",")
.    constant(value="\"programName\":\"")        property(name="programname" format="json") constant(value="\",")
.    constant(value="\"procId\":\"")             property(name="procid" format="json") constant(value="\",")
.    constant(value="\"message\":")              property(name="msg" position.from="2") constant(value="}") constant(value="\n")
.}
.template(name="platform_text" type="list") {
.    constant(value="{") constant(value="\"version\":\"1\"") constant(value=",")
.    constant(value="\"logType\":\"platform\"") constant(value=",")
.    constant(value="\"timestamp\":")            property(name="timegenerated" dateformat="unixtimestamp") constant(value=",")
.    constant(value="\"container\":\"")          property(name="$.provider_container" format="json") constant(value="\",")
.    constant(value="\"image\":\"")		property(name="$!image" format="json" ) constant(value="\",")
.    constant(value="\"source\":\"")           	property(name="$myhostname" format="json" ) constant(value="\",")
.    constant(value="\"fromIp\":\"")             constant(value="10.43.66.137")  constant(value="\",")
.    constant(value="\"severity\":\"")           property(name="syslogseverity-text" format="json") constant(value="\",")
.    constant(value="\"facility\":\"")           property(name="syslogfacility-text" format="json") constant(value="\",")
.    constant(value="\"programName\":\"")        property(name="programname" format="json") constant(value="\",")
.    constant(value="\"procId\":\"")             property(name="procid" format="json") constant(value="\",")
.    constant(value="\"message\":\"")            property(name="msg" position.from="1" format="json") constant(value="\"}") constant(value="\n")
.}
.
.template (name="DynFile" type="string" string="/usr/local/data/rsyslog/%$now%/%$.program_name%-%$now%-%$hour%.log")
.
.ruleset(name="writeRemoteData" 
.				queue.type="disk"
.                                queue.spoolDirectory="/var/log"
.                                queue.filename="result_file"
.                                queue.size="200000"
.                                queue.saveonshutdown="on"
.				) {
.	
.	set $.program_name  = field(replace($syslogtag, 'docker/' , '') , '[' , 1) ; 
.	set $.provider_container = field($.program_name, ',', 1);
.	if ($syslogfacility-text == "local7") then {
.		set $!provider_id = field($.provider_container, '.', 1);
.		set $!container = field($.provider_container, '.', 2);
.	}
.	set $!image = field($.program_name, ',', 2);
.	set $!format = tolower(field($.program_name, ',', 3));
.	if($!format == 'json') then {
.		if($syslogfacility-text == "local7") then {
.        		#action(type="omfile" template="tenant_json" dirCreateMode="0700" FileCreateMode="0644" dynaFile="DynFile" )
.
.			action(type="omkafka"
.				template="tenant_json"
.				confParam=["compression.codec=snappy", "queue.buffering.max.messages=400000", "log.connection.close=false"]
.				topic="logs-tenant_json"
.				broker=["10.43.66.161:9092","10.43.66.162:9092","10.43.66.163:9092"]
.				partitions.auto="on"
.				queue.type="linkedlist"
.                                queue.size="200000"
.                                queue.saveonshutdown="on"
.			)
.		}else{
.                        #action(type="omfile" template="platform_json" dirCreateMode="0700" FileCreateMode="0644" dynaFile="DynFile" )
.
.			action(type="omkafka"
.				template="platform_json"
.				confParam=["compression.codec=snappy", "queue.buffering.max.messages=400000", "log.connection.close=false"]
.				topic="logs-platform_json"
.				broker=["10.43.66.161:9092","10.43.66.162:9092","10.43.66.163:9092"]
.				partitions.auto="on"
.				queue.type="linkedlist"
.                                queue.size="200000"
.                                queue.saveonshutdown="on"
.			)
.		}
.	}else{
.		if($syslogfacility-text == "local7") then {
.                        #action(type="omfile" template="tenant_text" dirCreateMode="0700" FileCreateMode="0644" dynaFile="DynFile" )
.
.			action(type="omkafka"
.				template="tenant_text"
.				confParam=["compression.codec=snappy", "queue.buffering.max.messages=400000", "log.connection.close=false"]
.				topic="logs-tenant_text"
.				broker=["10.43.66.161:9092","10.43.66.162:9092","10.43.66.163:9092"]
.				partitions.auto="on"
.				queue.type="linkedlist"
.                                queue.size="200000"
.                                queue.saveonshutdown="on"
.			)
.		}else{
.                        #action(type="omfile" template="platform_text" dirCreateMode="0700" FileCreateMode="0644" dynaFile="DynFile" )
.
.			action(type="omkafka"
.				template="platform_text"
.				confParam=["compression.codec=snappy", "queue.buffering.max.messages=400000", "log.connection.close=false"]
.				topic="logs-platform_text"
.				broker=["10.43.66.161:9092","10.43.66.162:9092","10.43.66.163:9092"]
.				partitions.auto="on"
.				queue.type="linkedlist"
.                                queue.size="200000"
.                                queue.saveonshutdown="on"
.			)
.		}
.	}
.}
---------------------------------------------------------
#listen.conf
$SystemLogSocketName /run/systemd/journal/syslog

**Comment by Cloud-Leung** [comment]
@davidelang 
I updated rsyslog to 8.34 on a machine just now. but I need to observe one or two days to see if it is right.
/etc/rsyslog.d directory has two config file ,graylog-rsyslog.conf and listen.conf.

In order to avoid the format, I added a point at the beginning of the every line.

graylog-rsyslog.conf 
-----------------------------------------------------
.module(load="imfile"  mode="inotify")
.# load required modules
.module(load="imtcp")
.module(load="omkafka")
.input(type="imfile"
.      freshStartTail="on" 
.      File="/var/log/messages"
.      Tag="syslog,messages,text" ruleset="writeRemoteData")
.
.input(type="imtcp"
.      port="10514"
.      ruleset="writeRemoteData")
.template(name="tenant_json" type="list") {
.    constant(value="{") constant(value="\"version\":\"1\"") constant(value=",")
.    constant(value="\"logType\":\"vendor\"") constant(value=",")
.    constant(value="\"timestamp\":")            property(name="timegenerated" dateformat="unixtimestamp") constant(value=",")
.    constant(value="\"vendorIdentifier\":\"")   property(name="$!provider_id" format="json") constant(value="\",")
.    constant(value="\"container\":\"")		property(name="$!container" format="json" ) constant(value="\",")
.    constant(value="\"image\":\"")		property(name="$!image" format="json" ) constant(value="\",")
.    constant(value="\"source\":\"")             property(name="$myhostname" format="json" ) constant(value="\",")
.    constant(value="\"fromIp\":\"")             constant(value="10.43.66.137")  constant(value="\",")
.    constant(value="\"severity\":\"")           property(name="syslogseverity-text" format="json") constant(value="\",")
.    constant(value="\"facility\":\"")           property(name="syslogfacility-text" format="json") constant(value="\",")
.    constant(value="\"programName\":\"")        property(name="programname" format="json") constant(value="\",")
.    constant(value="\"procId\":\"")             property(name="procid" format="json") constant(value="\",")
.    constant(value="\"message\":")              property(name="msg" position.from="2") constant(value="}") constant(value="\n")
.}
.template(name="tenant_text" type="list") {
.    constant(value="{") constant(value="\"version\":\"1\"") constant(value=",")
.    constant(value="\"logType\":\"vendor\"") constant(value=",")
.    constant(value="\"timestamp\":")            property(name="timegenerated" dateformat="unixtimestamp") constant(value=",")
.    constant(value="\"vendorIdentifier\":\"")   property(name="$!provider_id" format="json") constant(value="\",")
.    constant(value="\"container\":\"")		property(name="$!container" format="json" ) constant(value="\",")
.    constant(value="\"image\":\"")		property(name="$!image" format="json" ) constant(value="\",")
.    constant(value="\"source\":\"")             property(name="$myhostname" format="json" ) constant(value="\",")
.    constant(value="\"fromIp\":\"")             constant(value="10.43.66.137")  constant(value="\",")   
.    constant(value="\"severity\":\"")           property(name="syslogseverity-text" format="json") constant(value="\",")
.    constant(value="\"facility\":\"")           property(name="syslogfacility-text" format="json") constant(value="\",")
.    constant(value="\"programName\":\"")        property(name="programname" format="json") constant(value="\",")
.    constant(value="\"procId\":\"")             property(name="procid" format="json") constant(value="\",")
.    constant(value="\"message\":\"")            property(name="msg" position.from="2" format="json") constant(value="\"}") constant(value="\n")
.}
.template(name="platform_json" type="list") {
.    constant(value="{") constant(value="\"version\":\"1\"") constant(value=",")
.    constant(value="\"logType\":\"platform\"") constant(value=",")
.    constant(value="\"timestamp\":")            property(name="timegenerated" dateformat="unixtimestamp") constant(value=",")
.    constant(value="\"container\":\"")          property(name="$.provider_container" format="json") constant(value="\",")
.    constant(value="\"image\":\"")		property(name="$!image" format="json" ) constant(value="\",")
.    constant(value="\"source\":\"")             property(name="$myhostname" format="json" ) constant(value="\",")
.    constant(value="\"fromIp\":\"")             constant(value="10.43.66.137")  constant(value="\",")
.    constant(value="\"severity\":\"")           property(name="syslogseverity-text" format="json") constant(value="\",")
.    constant(value="\"facility\":\"")           property(name="syslogfacility-text" format="json") constant(value="\",")
.    constant(value="\"programName\":\"")        property(name="programname" format="json") constant(value="\",")
.    constant(value="\"procId\":\"")             property(name="procid" format="json") constant(value="\",")
.    constant(value="\"message\":")              property(name="msg" position.from="2") constant(value="}") constant(value="\n")
.}
.template(name="platform_text" type="list") {
.    constant(value="{") constant(value="\"version\":\"1\"") constant(value=",")
.    constant(value="\"logType\":\"platform\"") constant(value=",")
.    constant(value="\"timestamp\":")            property(name="timegenerated" dateformat="unixtimestamp") constant(value=",")
.    constant(value="\"container\":\"")          property(name="$.provider_container" format="json") constant(value="\",")
.    constant(value="\"image\":\"")		property(name="$!image" format="json" ) constant(value="\",")
.    constant(value="\"source\":\"")           	property(name="$myhostname" format="json" ) constant(value="\",")
.    constant(value="\"fromIp\":\"")             constant(value="10.43.66.137")  constant(value="\",")
.    constant(value="\"severity\":\"")           property(name="syslogseverity-text" format="json") constant(value="\",")
.    constant(value="\"facility\":\"")           property(name="syslogfacility-text" format="json") constant(value="\",")
.    constant(value="\"programName\":\"")        property(name="programname" format="json") constant(value="\",")
.    constant(value="\"procId\":\"")             property(name="procid" format="json") constant(value="\",")
.    constant(value="\"message\":\"")            property(name="msg" position.from="1" format="json") constant(value="\"}") constant(value="\n")
.}
.
.template (name="DynFile" type="string" string="/usr/local/data/rsyslog/%$now%/%$.program_name%-%$now%-%$hour%.log")
.
.ruleset(name="writeRemoteData" 
.				queue.type="disk"
.                                queue.spoolDirectory="/var/log"
.                                queue.filename="result_file"
.                                queue.size="200000"
.                                queue.saveonshutdown="on"
.				) {
.	
.	set $.program_name  = field(replace($syslogtag, 'docker/' , '') , '[' , 1) ; 
.	set $.provider_container = field($.program_name, ',', 1);
.	if ($syslogfacility-text == "local7") then {
.		set $!provider_id = field($.provider_container, '.', 1);
.		set $!container = field($.provider_container, '.', 2);
.	}
.	set $!image = field($.program_name, ',', 2);
.	set $!format = tolower(field($.program_name, ',', 3));
.	if($!format == 'json') then {
.		if($syslogfacility-text == "local7") then {
.        		#action(type="omfile" template="tenant_json" dirCreateMode="0700" FileCreateMode="0644" dynaFile="DynFile" )
.
.			action(type="omkafka"
.				template="tenant_json"
.				confParam=["compression.codec=snappy", "queue.buffering.max.messages=400000", "log.connection.close=false"]
.				topic="logs-tenant_json"
.				broker=["10.43.66.161:9092","10.43.66.162:9092","10.43.66.163:9092"]
.				partitions.auto="on"
.				queue.type="linkedlist"
.                                queue.size="200000"
.                                queue.saveonshutdown="on"
.			)
.		}else{
.                        #action(type="omfile" template="platform_json" dirCreateMode="0700" FileCreateMode="0644" dynaFile="DynFile" )
.
.			action(type="omkafka"
.				template="platform_json"
.				confParam=["compression.codec=snappy", "queue.buffering.max.messages=400000", "log.connection.close=false"]
.				topic="logs-platform_json"
.				broker=["10.43.66.161:9092","10.43.66.162:9092","10.43.66.163:9092"]
.				partitions.auto="on"
.				queue.type="linkedlist"
.                                queue.size="200000"
.                                queue.saveonshutdown="on"
.			)
.		}
.	}else{
.		if($syslogfacility-text == "local7") then {
.                        #action(type="omfile" template="tenant_text" dirCreateMode="0700" FileCreateMode="0644" dynaFile="DynFile" )
.
.			action(type="omkafka"
.				template="tenant_text"
.				confParam=["compression.codec=snappy", "queue.buffering.max.messages=400000", "log.connection.close=false"]
.				topic="logs-tenant_text"
.				broker=["10.43.66.161:9092","10.43.66.162:9092","10.43.66.163:9092"]
.				partitions.auto="on"
.				queue.type="linkedlist"
.                                queue.size="200000"
.                                queue.saveonshutdown="on"
.			)
.		}else{
.                        #action(type="omfile" template="platform_text" dirCreateMode="0700" FileCreateMode="0644" dynaFile="DynFile" )
.
.			action(type="omkafka"
.				template="platform_text"
.				confParam=["compression.codec=snappy", "queue.buffering.max.messages=400000", "log.connection.close=false"]
.				topic="logs-platform_text"
.				broker=["10.43.66.161:9092","10.43.66.162:9092","10.43.66.163:9092"]
.				partitions.auto="on"
.				queue.type="linkedlist"
.                                queue.size="200000"
.                                queue.saveonshutdown="on"
.			)
.		}
.	}
.}

listen.conf 
-----------------------------------------------------
$SystemLogSocketName /run/systemd/journal/syslog

**Comment by rgerhards** [comment]
@Cloud-Leung 
> @rgerhards i'm sorry about that , this is the config file text ,
> In order to avoid the format, I added a point at the beginning of the every line.

I have edited your post. You can use three backticks to flag text that shall be displayed literally. Press the edit button on your post, then you see what I have done (I can't show it here as it would be interpreted as commands ;-)).

Doc is here: https://guides.github.com/features/mastering-markdown/

Note that the text immediately followed by a line of dashes (or similar chars) creates a heading. I have also corrected that.

**Comment by rgerhards** [comment]
Looking at the includes, this looks really strange. I admit I doubt that this is the correct config. Maybe it was diverted to another file via ```-f``` rsyslogd command line option? But let's see if the new version brings a change. If not, we need an actual debug log from startup.

**Comment by Cloud-Leung** [comment]
@rgerhards 

the includes config graylog-rsyslog.conf has two input.

one is receive log from tcp port 10514, another is read log from /var/log/messages file.
The log will be assembled and sent to kafka, Graylog will receives the log from kafka and saves it in elasticsearch . This process is currently tested correctly.
This part of the operation will theoretically only read the messages file and does nothing else.

The current log is not lost，it just keeps printing to the same file. Even though the file name has been automatically modified by the system plus a time suffix and a new log file is created, the log is always printed in the old file.But in fact he should print it to a new file.

em, I observed rsyslog version 8.34.0, maybe my version is too old, or maybe there is something wrong with my configuration file.

**Comment by Cloud-Leung** [comment]
@rgerhards @davidelang 
first thank you help me and i found the reason and already solve the problem.
the reason is my system earliest syslog version is 7.4.7，
i want to use omkafka module then i update it to 8.26.1.
well 7.4.7 save the pid to /var/run/syslogd.pid but 8.26.1 save it to /var/run/rsyslogd.pid, it's diferent.
The logrotate rotation log uses this configuration file /etc/logrotate.d/syslog，
this commond "/bin/kill -HUP `cat /var/run/syslogd.pid 2> /dev/null` 2> /dev/null || true"
it will use the pid file ,but when i install rsyslog, i havn't update this, 
when i use 8.26.1 this commond should be  "/bin/kill -HUP `cat /var/run/rsyslogd.pid 2> /dev/null` 2> /dev/null || true". 
Should rsyslog automatically change the file when it is installed?

By the way, I found version 8.34 don't have this pid file , where is it ?
