### ISSUE TITLE
rsyslog stucks with 100% CPU

### ISSUE THREAD

**Issue by surco1971** [rsyslog/rsyslog#2637]
### Expected behavior
We have a centralized logging infrastructure within a public cloud from Huawei (OTC) where at the endpoint a rsyslog process listening on Port 10514 receiving log entries from around 400 clients and writing the results in separate files for every client. There are around 1000 log entries per minute.

### Actual behavior
The rsyslog process stucks with one CPU 100% after a certain time - between 3 hours and 10 days. First the rsyslog was running in a docker container, but the same happens when it is installed directly on a ubuntu 14.04. It happned as well with older version (8.28, 8.32)

top -bH -d 5 -n 49 -p 35604
top - 07:54:33 up 37 days, 26 min,  1 user,  load average: 1.04, 0.97, 0.91
Threads:   9 total,   1 running,   8 sleeping,   0 stopped,   0 zombie
%Cpu(s):  8.5 us,  1.3 sy,  0.0 ni, 89.9 id,  0.1 wa,  0.0 hi,  0.2 si,  0.1 st
KiB Mem:   4025880 total,  3868888 used,   156992 free,   152108 buffers
KiB Swap:        0 total,        0 used,        0 free.  3097336 cached Mem

   PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND
 35607 root      20   0  629488  31940   2388 R 99.5  0.8 937:27.07 in:imtcp
 35604 root      20   0  629488  31940   2388 S  0.0  0.8   0:28.19 rsyslogd
 35606 root      20   0  629488  31940   2388 S  0.0  0.8   0:10.62 in:imuxsock
 35608 root      20   0  629488  31940   2388 S  0.0  0.8   0:00.51 in:imfile
 35609 root      20   0  629488  31940   2388 S  0.0  0.8   0:01.69 in:imtcp
 35610 root      20   0  629488  31940   2388 S  0.0  0.8   0:00.38 in:imtcp
 35611 root      20   0  629488  31940   2388 S  0.0  0.8   0:00.19 in:imtcp
 35612 root      20   0  629488  31940   2388 S  0.0  0.8   0:00.11 in:imtcp
 35613 root      20   0  629488  31940   2388 S  0.0  0.8   0:28.43 rs:main Q:Reg

This is strace in the case it stucks:

strace -p  35604
Process 35604 attached
select(1, NULL, NULL, NULL, {294, 451452}

This is what gdb gives me:
(gdb) info threads
  Id   Target Id         Frame 
  9    Thread 0x7f342574d700 (LWP 35606) "in:imuxsock" 0x00007f342805c913 in select () at ../sysdeps/unix/syscall-template.S:81
  8    Thread 0x7f342534c700 (LWP 35607) "in:imtcp" 0x00007f3426f15b9b in ?? () from /usr/lib/rsyslog/lmnetstrms.so
  7    Thread 0x7f3424f4b700 (LWP 35608) "in:imfile" 0x00007f342805c913 in select () at ../sysdeps/unix/syscall-template.S:81
  6    Thread 0x7f3424b4a700 (LWP 35609) "in:imtcp" pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  5    Thread 0x7f3424749700 (LWP 35610) "in:imtcp" pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  4    Thread 0x7f341ffff700 (LWP 35611) "in:imtcp" pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  3    Thread 0x7f341fbfe700 (LWP 35612) "in:imtcp" pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  2    Thread 0x7f341f3dc700 (LWP 35613) "rs:main Q:Reg" pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
* 1    Thread 0x7f342939e780 (LWP 35604) "rsyslogd" 0x00007f342805c913 in select () at ../sysdeps/unix/syscall-template.S:81

### Environment
- rsyslog version: 8.34.0-0adiscon3trusty1
- platform: Ubuntu 14.04
- VM 2 CPUs, 4 GB Memory

- for configuration questions/issues, include rsyslog.conf:
```
#  /etc/rsyslog.conf	Configuration file for rsyslog.
#
#			For more information see
#			/usr/share/doc/rsyslog-doc/html/rsyslog_conf.html


#################
#### MODULES ####
#################

$ModLoad imuxsock # provides support for local system logging
#$ModLoad imklog   # provides kernel logging support
#$ModLoad immark  # provides --MARK-- message capability

# provides UDP syslog reception
#$ModLoad imudp
#$UDPServerRun 514

# provides TCP syslog reception
#$ModLoad imtcp
#$InputTCPServerRun 514

#$DebugFile /data/debug.log
#$DebugLevel 2


###########################
#### GLOBAL DIRECTIVES ####
###########################

#
# Use traditional timestamp format.
# To enable high precision timestamps, comment out the following line.
#
$ActionFileDefaultTemplate RSYSLOG_TraditionalFileFormat

#
# Set the default permissions for all log files.
#
$FileOwner root
$FileGroup adm
$FileCreateMode 0640
$DirCreateMode 0755
$Umask 0022

#
# Where to place spool and state files
#
$WorkDirectory /var/spool/rsyslog

#
# Include all config files in /etc/rsyslog.d/
#
$IncludeConfig /etc/rsyslog.d/*.conf


###############
#### RULES ####
###############

#
# First some standard log files.  Log by facility.
#
auth,authpriv.*			/data/logs/general/auth.log
*.*;auth,authpriv.none		-/data/logs/general/syslog
#cron.*				/data/logs/general/cron.log
daemon.*			-/data/logs/general/daemon.log
kern.*				-/data/logs/general/kern.log
lpr.*				-/data/logs/general/lpr.log
mail.*				-/data/logs/general/mail.log
user.*				-/data/logs/general/user.log

#
# Logging for the mail system.  Split it up so that
# it is easy to write scripts to parse these files.
#
mail.info			-/data/logs/general/mail.info
mail.warn			-/data/logs/general/mail.warn
mail.err			/data/logs/general/mail.err

#
# Logging for INN news system.
#
news.crit			/data/logs/general/news/news.crit
news.err			/data/logs/general/news/news.err
news.notice			-/data/logs/general/news/news.notice

#
# Some "catch-all" log files.
#
*.=debug;\
	auth,authpriv.none;\
	news.none;mail.none	-/data/logs/general/debug
*.=info;*.=notice;*.=warn;\
	auth,authpriv.none;\
	cron,daemon.none;\
	mail,news.none		-/data/logs/general/messages

#
# Emergencies are sent to everybody logged in.
#
*.emerg				:omusrmsg:*

#
# I like to have messages displayed on the console, but only on a virtual
# console I usually leave idle.
#
#daemon,mail.*;\
#	news.=crit;news.=err;news.=notice;\
#	*.=debug;*.=info;\
#	*.=notice;*.=warn	/dev/tty8

# The named pipe /dev/xconsole is for the `xconsole' utility.  To use it,
# you must invoke `xconsole' with the `-file' option:
# 
#    $ xconsole -file /dev/xconsole [...]
#
# NOTE: adjust the list below, or you'll go crazy if you have a reasonably
#      busy site..
#
```

**Comment by rgerhards** [comment]
thx for the bug report. This is probably hard to reproduce. Can you do a stacktrace of the offending thread with gdb, best 3 or for times (stop, do bt, continue, stop, ...). Thanks.
