### ISSUE TITLE
MsgDeserialize out of sync with MsgSerialize for StrucData

### ISSUE THREAD

**Issue by adruch** [rsyslog/rsyslog#264]
In msg.c, the MsgSerialize field order does not match MsgDeserialize. Serialize puts structured data labeled as "pszRcvStrucData" after "pszRcvFromIP". Deserialize expects structured data labeled as "pszStrucData" after "localvars".

**Comment by rgerhards** [comment]
a related PR has been merged a couple of days ago. This is fixed in 8.9.0.
