### ISSUE TITLE
Rsyslog 8.24 and omelasticsearch Content-Type header not supported (HTTP 406 errors)

### ISSUE THREAD

**Issue by jbyers-suse** [rsyslog/rsyslog#2649]
### Expected behavior

The omelasticsearch module obtains JSON from the template

### Actual behavior

I'm attempting to send logs to elasticsearch 6.0.0 using the omelasticsearch module from the rsyslog 8.24 package version on SLES 12 SP3. I'm receiving similar errors to https://github.com/rsyslog/rsyslog/issues/2611 and https://github.com/rsyslog/rsyslog/issues/2070

        "reply":        {
                "error":        "Content-Type header [text/json; charset=utf-8] is not supported",
                "status":       406
        }

### Steps to reproduce the behavior

This is the relevant section of the rsyslog configuration where the tempate is defined

template(name="json-template"
  type="list" option.json="on") {
    constant(value="{")
      constant(value="\"@timestamp\":\"")     property(name="timereported" dateFormat="rfc3339")
      constant(value="\",\"@version\":\"1")
      constant(value="\",\"message\":\"")     property(name="msg")
      constant(value="\",\"sysloghost\":\"")  property(name="hostname")
      constant(value="\",\"severity\":\"")    property(name="syslogseverity-text")
      constant(value="\",\"facility\":\"")    property(name="syslogfacility-text")
      constant(value="\",\"programname\":\"") property(name="programname")
      constant(value="\",\"procid\":\"")      property(name="procid")
    constant(value="\"}\n")
}
action(type="omelasticsearch"
template="json-template"
dynSearchIndex="on"
searchIndex="logstash-index" # Defaults to system
searchType="logs"     # Defaults to events
server="localhost"
serverport="9200"
bulkmode="on"
queue.type="LinkedList" # dynamic allocation of memory
queue.size="10000"    # maximum number of events
queue.dequeuebatchsize="1000" # maximum bulk size
queue.workerthreads="4"
queue.saveonshutdown="on"
errorfile="/var/log/elasticsearch.log"
action.resumeretrycount="-1"
)

I attempted to use option.jsonf="on" in the same template yet rsyslog displayed the following message instead: 

liblogging-stdlog[10384]: error during parsing file /etc/rsyslog.conf, on or before line 49: parameter 'option.jsonf' not known -- typo in config file? [v8.24.0 try http://www.rsyslog.com/e/2207 ]

### Environment

I'll include platform specific details for rsyslog

SUSE Linux Enterprise Server 12 (x86_64)
VERSION = 12
PATCHLEVEL = 3

rsyslogd 8.24.0, compiled with:
        PLATFORM:                               x86_64-suse-linux-gnu
        PLATFORM (lsb_release -d):
        FEATURE_REGEXP:                         Yes
        GSSAPI Kerberos 5 support:              Yes
        FEATURE_DEBUG (debug build, slow code): No
        32bit Atomic operations supported:      Yes
        64bit Atomic operations supported:      Yes
        memory allocator:                       system default
        Runtime Instrumentation (slow code):    No
        uuid support:                           Yes
        Number of Bits in RainerScript integers: 64

See http://www.rsyslog.com for more information.

rsyslog-module-elasticsearch-8.24.0-1.2.x86_64
rsyslog-8.24.0-1.20.x86_64
rsyslog-module-gtls-8.24.0-1.20.x86_64
rsyslog-module-relp-8.24.0-1.20.x86_64
librelp0-1.2.12-3.3.1.x86_64
libgnutls-openssl27-3.3.27-1.10.x86_64
libgnutls28-3.3.27-1.10.x86_64
gnutls-3.3.27-1.10.x86_64

Let me know if you need any further information. 

Is anyone aware of a manual workaround to set the Content-Type header in the configuration using the rsyslog 8.24 package that I'm evaluating?

*Note: rsyslog documentation is available here*:
  [pre-release](http://www.rsyslog.com/doc/master/),
  [current stable release](http://www.rsyslog.com/doc/v8-stable/)

**Comment by deoren** [comment]
> I attempted to use option.jsonf="on" in the same template yet rsyslog displayed the following message instead:
> 
> ```
> liblogging-stdlog[10384]: error during parsing file /etc/rsyslog.conf, on or before line 49: parameter 'option.jsonf' not known -- typo in config file? [v8.24.0 try http://www.rsyslog.com/e/2207 ]
> ```

It appears that option wasn't added until v8.33 (perhaps v8.33.1) with #2347 and #2348.

I'm not familiar enough with Elasticsearch to say what the UTF-8 related error is about.

**Comment by jgerhards** [comment]
This problem was fixed in rsyslog v8.29. You can find the Entry in the changelog here: https://github.com/rsyslog/rsyslog/blob/master/ChangeLog#L1225
It appears that back then it caused only a warning, but now elasticsearch considers it an error.

**Comment by deoren** [comment]
> @jbyers-suse: I upgraded rsyslog and the corresponding modules to version 8.33.1. This seems to resolve the issue. Thank you.

Thank you for the feedback! We'll go ahead and close this ticket since it appears that your question has been answered.
