### ISSUE TITLE
imfile new state file naming results in files being re-read from start.

### ISSUE THREAD

**Issue by n2N8Z** [rsyslog/rsyslog#2662]
### Expected behavior
State files are used to resuming reading from previous offsets.

If state file naming is changed, existing state files are converted to the new naming and internal format.

### Actual behavior
After upgrading to 8.34, all previous state files are ignored, and all watched files are read again from start.

### Steps to reproduce the behavior
Configure some file to be watched.
Upgrade to 8.34.
Start rsyslog.

### Environment
- rsyslog version: 8.29 then upgrade to  8.34
- platform: Red Hat 7.4

**Comment by rgerhards** [comment]
Thanks for the bug report. Unfortunately it is not as easy to reproduce as you assume. Everything works as expected in our environment (including the testbench) and also at all other places I know that did the upgrade. So I would assume that the bug is triggered by something in your config (not say it is wrong, just it is a trigger).

To debug this, it would be best if I could get a debug log for one startup with an old state file. Then I could check what exactly happens. Could you do that?

**Comment by fluential** [comment]
@n2N8Z would you be able to provide required info? 
@rgerhards - it seems to me that "somehow" this comes from the actual state of the "state file directory", I can observe multiple state files for a single logfile mostly corresponding to the restart times. I've managed to remove "obsolete" state files and this somehow (not always the most recent was the correct) fixed the issue, but I can't really say much more as it was ad hoc.

**Comment by n2N8Z** [comment]
With 8.29 the state files had the names of the watched files in them like /var/lib/rsyslog/imfile-state:-path1-path2-path3-filename.
After the upgrade the state files were named based on their inodes e.g. /var/lib/rsyslog/imfile-state:21620797

Based on that new naming scheme, it made sense that the old state files were not used.

Due to the large amount of imfile refactoring, I was concerned that this will not be the only issue, and I don't have the time right now to do a lot of testing on inputs, and hence I've downgraded to 8.33.1.

Later I noticed a couple of permission errors after the 8.34 upgrade as well, which 8.29 did not have:
Apr 24 12:01:20 ip-10-120-20-20 rsyslogd: imfile: cannot watch object '/path1': Permission denied [v8.34.0 try http://www.rsyslog.com/e/2027 ]
Apr 24 12:01:20 ip-10-120-20-20 rsyslogd: imfile: cannot watch object '/path1/path2': Permission denied [v8.34.0 try http://www.rsyslog.com/e/2027 ]
Apr 24 12:01:20 ip-10-120-20-20 rsyslogd: imfile: cannot watch object '/path1/path2/path3': Permission denied [v8.34.0 try http://www.rsyslog.com/e/202

We do have selinux enabled, and I see that there are errors in audit.log corresponding to this.
Looks like I need to allow access to all of the folders leading to the watches files as well. Perhaps that's why the state files have inodes rather than names.

The other thing that was an issue for me was the changed internal structure of the state files, since I wrote a little script for log rotation that was checking whether Rsyslog had finished processing the watched files. I would have been ok if the new state files were properly formed JSON, then I could have easily gotten the offset value out again, but currently it's not well formed JSON, and I see in imfile.c that there's probably going to be some changes to fix that.

**Comment by rgerhards** [comment]
> Based on that new naming scheme, it made sense that the old state files were not used.

no, there is code that reads the old state file and converts it to new format.

> We do have selinux enabled, and I see that there are errors in audit.log corresponding to this.
> Looks like I need to allow access to all of the folders leading to the watches files as well. Perhaps that's why the state files have inodes rather than names.

No, inode numbers are what they should be. This is to survive renames. The name can also contain a hash, but that's right now not the case. Re the selinux errors, the old code possibly just did not output error messages and silently ignore the files.

> but currently it's not well formed JSON

Why is it not well-formed? It should be.  Please show what your issue is. Note that the file is read without complain by libfastjson, which shares the reading code with json-c. So I doubt it is invalid ;-)

**Comment by rgerhards** [comment]
@fluential 

> @rgerhards - it seems to me that "somehow" this comes from the actual state of the "state file directory", I can observe multiple state files for a single logfile mostly corresponding to the restart times.

Can you create a debug log from such a startup run? That would be helpful to understand what is going on here.

**Comment by n2N8Z** [comment]
> Re the selinux errors, the old code possibly just did not output error messages and silently ignore the files.

8.29 may have been silently ignoring the errors, but it wasn't ignoring the files, and neither was 8.34.

>Why is it not well-formed?

e.g.
{ "filename": "\/path1\/path2\/path3\/filename", "prev_was_nl": 0, "curr_offs": 10485768, "strt_offs": 10485768 }"prev_msg_segment": "msg segment " }partial msg segment" }partial msg segment" }partial msg segment" }" }partial msg segment" }

"prev_msg_segment" is not part of an object, and then there are multiple additional partial msg segments and trailing braces. It looks as if the state file is being overwritten, and previous longer entries are left behind. If rsyslog's JSON parser accepts that, then it must because it is discarding trailing text after the end of the vaild JSON object.

**Comment by rgerhards** [comment]
I have crafted a path, but I am not sure if it explains everything discussed here in the tracker. Let's apply that patch and see if the issue goes away.

Can anyone from you build and deploy yourself or do you need a package update (this takes a while longer as I need to involve more folks).
