### ISSUE TITLE
Ask: using Wildcards with imfile

### ISSUE THREAD

**Issue by WuLonghui** [rsyslog/rsyslog#267]
PS: Sorry to create this issue, because I cannot send emil to mail-list

The doc in imfile points that it can konw which file the message originated from, I wan to forward to remote server ,and add filename in the message,  how to use it?
```
The imfile module supports message metadata. It supports the following data items

    filename

    Name of the file where the message originated from. This is most useful when using wildcards inside file monitors, because it then is the only way to know which file the message originated from.
```
This is a example I configure it
```
module(load="imfile" PollingInterval="10")
input(type="imfile"
      file="/var/mylog/*.log"
      tag="tag1"
     )

$template MyFormat, "%filename% -- %msg%\n"
@@ip:port;MyFormat
```

**Comment by zlisinski** [comment]
Replace %filename% with %$!metadata!filename%

**Comment by langzi-zmg** [comment]
I want to keep the source file name and destination file name consistent,this is my 
configuration。
this is my log:test.20170307.172_16_0_3.log
agent：input(
    type="imfile"
    File="/opt/log/test.*"  
 .........
server: 
$template Remote, "/opt/log/%syslogtag%/%$!metadata!filename%"
:fromhost-ip, !isequal, "127.0.0.1" ?Remote

but,after restart server and agent,server host,log is not in /opt/log but in /var/log/syslog under.

**Comment by davidelang** [comment]
On Mon, 6 Mar 2017, langzi-zmg wrote:

> I want to keep the source file name and destination file name consistent,this is my
> configuration。
> this is my log:test.20170307.172_16_0_3.log
> agent：input(
>    type="imfile"
>    File="/opt/log/test.*"
> .........
> server:
> $template Remote, "/opt/log/%syslogtag%/%$!metadata!filename%"
> :fromhost-ip, !isequal, "127.0.0.1" ?Remote
>
> but,after restart server and agent,server host,log is not in /opt/log but in /var/log/syslog under.

what is the config on the client to send the logs to the server? it sounds as if 
you are not sending $!metadata!filename.

whenever you have problems where the logs don't go where you think they should, 
log using the format RSYSLOG_DebugFormat and look at what variables are what. In 
99% of the cases, the problem is that the variables aren't what you thought they 
were.

  David Lang

**Comment by langzi-zmg** [comment]
RSYSLOG_DebugFormat：
Debug line with all properties:
FROMHOST: '10.0.0.153', fromhost-ip: '10.0.0.153', HOSTNAME: 'localhost', PRI: 134,
syslogtag 'ivankagateway', programname: 'ivankagateway', APP-NAME: 'ivankagateway', PROCID: '-', MSGID: '-',
TIMESTAMP: 'Mar  7 18:29:15', STRUCTURED-DATA: '-',
msg: ' {"level":"info","msg":"[prometheus initialized for 1e6a48bbe48edb]","time":"2017-03-07T06:52:35Z"}'
escaped msg: ' {"level":"info","msg":"[prometheus initialized for 1e6a48bbe48edb]","time":"2017-03-07T06:52:35Z"}'
inputname: imtcp rawmsg: '<134>Mar  7 18:29:15 localhost ivankagateway {"level":"info","msg":"[prometheus initialized for 1e6a48bbe48edb]","time":"2017-03-07T06:52:35Z"}'
$!:
$.:
$/:

agent configuration:
   addMetadata="on"  #I already add this  parameter，I just want  server host can 
identify the file name of agent server.

   thanks

**Comment by langzi-zmg** [comment]
i just want find a property that allows template to recognize input filename。
Thank you

**Comment by davidelang** [comment]
On Tue, 7 Mar 2017, langzi-zmg wrote:

> RSYSLOG_DebugFormat：
> Debug line with all properties:
> FROMHOST: '10.0.0.153', fromhost-ip: '10.0.0.153', HOSTNAME: 'localhost', PRI: 134,
> syslogtag 'ivankagateway', programname: 'ivankagateway', APP-NAME: 'ivankagateway', PROCID: '-', MSGID: '-',
> TIMESTAMP: 'Mar  7 18:29:15', STRUCTURED-DATA: '-',
> msg: ' {"level":"info","msg":"[prometheus initialized for 1e6a48bbe48edb]","time":"2017-03-07T06:52:35Z"}'
> escaped msg: ' {"level":"info","msg":"[prometheus initialized for 1e6a48bbe48edb]","time":"2017-03-07T06:52:35Z"}'
> inputname: imtcp rawmsg: '<134>Mar  7 18:29:15 localhost ivankagateway {"level":"info","msg":"[prometheus initialized for 1e6a48bbe48edb]","time":"2017-03-07T06:52:35Z"}'
> $!:
> $.:
> $/:
>
> agent configuration:
>   addMetadata="on"  #I already add this  parameter，I just want  server host can
> identify the file name of agent server.

So if you look at this $! is blank, but $msg contains json data. So you need to 
use mmnormalize or mmjsonparse to parse $msg and populate the $! variables

But even then, you are not sending $!metadata from the client to the server, all 
you are sending is:

{"level":"info","msg":"[prometheus initialized for 1e6a48bbe48edb]","time":"2017-03-07T06:52:35Z"}

so what't the config on the sending side? (and what does debug format show 
there?)

David Lang

**Comment by davidelang** [comment]
On Tue, 7 Mar 2017, langzi-zmg wrote:

> i just want find a property that allows template to recognize input filename。 
> Thank you

on the instance that reads the file, you have the property $!metadata!filename

but you have to send that to the server, otherwise it has no way of seeing it.

David Lang

**Comment by langzi-zmg** [comment]
but how to put this property $!metadata!filename  from the agent to the server side ？

**Comment by davidelang** [comment]
On Tue, 7 Mar 2017, langzi-zmg wrote:

> but how to put this property $!metadata!filename from the agent to the server 
> side ？

you need to include it in the template you are using to deliver the message from 
the agent to the server.

you haven't provided any information about what you are doing there, so I can't 
guess how to modify it to include this added information.

on the agent, write the log message out to a file, one file with the same format 
you use to send it to the server, and one using the RSYSLOG_DebugFormat

David Lang

**Comment by langzi-zmg** [comment]
hear is my agent  debug log:
Debug line with all properties:
FROMHOST: '', fromhost-ip: '', HOSTNAME: 'localhost', PRI: 134,
syslogtag 'ivankagateway', programname: 'ivankagateway', APP-NAME: 'ivankagateway', PROCID: '-', MSGID: '-',
TIMESTAMP: 'Mar  7 20:13:53', STRUCTURED-DATA: '-',
msg: ' message repeated 2 times: [http://test.com/real?en_prod_code=SPX500INDEX,US30INDEX,NASINDEX&fields=prod_name,last_px,px_change,px_change_rate,update_time,trade_status,securities_type,price_precision]'
escaped msg: ' message repeated 2 times: [http://test.com/real?en_prod_code=SPX500INDEX,US30INDEX,NASINDEX&fields=prod_name,last_px,px_change,px_change_rate,update_time,trade_status,securities_type,price_precision]'
inputname: imfile rawmsg: ' message repeated 2 times: [http://test.com/real?en_prod_code=SPX500INDEX,US30INDEX,NASINDEX&fields=prod_name,last_px,px_change,px_change_rate,update_time,trade_status,securities_type,price_precision]'
$!:{ "metadata": { "filename": "\/opt\/log\/ivankagateway.20170307.172_16_0_3.log" } }

agent  have metadata，

**Comment by langzi-zmg** [comment]
why  message repeated 2 times？
thanks

**Comment by langzi-zmg** [comment]
this is my agent configuration.
module(load="imfile")

# Non transparent (LF) frame. (Messages are delimited by an LF.)
ruleset(name="tcpntf") {
    action(
        type="omfwd"
        Protocol="tcp"
        Target="rsyslog-server"
        Port="1514"
	)
    stop
}

# Octet counting frame. (Messages are determined by lengths, and LF's escaped.)
ruleset(name="tcpocf") {
    action(
        type="omfwd"
        Protocol="tcp"
        Target="rsyslog-server"
	TCP_Framing="octet-counted"
        Port="1514")

    stop
}

input(
    type="imfile"
    File="/opt/log/ivankagateway.*.log"
    Facility="local0"
    Severity="info"
    Tag="ivankagateway"
    addMetadata="on"
    #StateFile="gateway.state"
    PersistStateInterval="5"
    Ruleset="tcpntf")
input(
    type="imfile"
    File="/opt/log/ivankaudata.*.log"
    Facility="local0"
    Severity="info"
    Tag="ivankaudata"
    addMetadata="on"
    #StateFile="udata.state"
    PersistStateInterval="5"
    Ruleset="tcpntf")
input(
    type="imfile"
    File="/opt/log/ivankacontent.*.log"
    Facility="local0"
    Severity="info"
    Tag="ivankacontent"
    #StateFile="content.state"
    addMetadata="on"
    PersistStateInterval="5"
    Ruleset="tcpntf")

this is my server configuration.
$AllowedSender tcp, 10.0.0.0/8
$template Remote, "/opt/log/%syslogtag%/%$!metadata!filename%"
:fromhost-ip, !isequal, "127.0.0.1" ?Remote

**Comment by davidelang** [comment]
On Tue, 7 Mar 2017, langzi-zmg wrote:

> why  message repeated 2 times？
> thanks

what message is repeated two times

**Comment by davidelang** [comment]
On Tue, 7 Mar 2017, langzi-zmg wrote:

> $!:{ "metadata": { "filename": "\/opt\/log\/ivankagateway.20170307.172_16_0_3.log" } }
>
> agent  have metadata，

Yes, so the question is if you include this in the template that you use to 
deliver the message.

David Lang

**Comment by davidelang** [comment]
On Tue, 7 Mar 2017, langzi-zmg wrote:

> # Octet counting frame. (Messages are determined by lengths, and LF's escaped.)
> ruleset(name="tcpocf") {
>    action(
>        type="omfwd"
>        Protocol="tcp"
>        Target="rsyslog-server"
> 	TCP_Framing="octet-counted"
>        Port="1514")
>
>    stop
> }

so, since you are not defining a template, you are using the Traditional Forward 
Format, which only includes PRI, Hostname, syslogtag, and msg, nothing else.

If you want to include $! variables in the message, you are going to need to 
create a template that includes it.

the best way to do this probably includes sending the message to the server in 
JSON, the question is what the best way to include your log data in it.

Are all your logs that you are gathering via imfile json like the one you gave 
an example of?

David Lang

**Comment by langzi-zmg** [comment]
yes, all logs from agent to server via imfile json. How to write this template？
thanks

**Comment by davidelang** [comment]
On Tue, 7 Mar 2017, langzi-zmg wrote:

> yes, all logs from agent to server via imfile json. How to write this template？
> thanks

so what I would do is first run mmjsonparse[1] on the message (do this and then 
look at what the debug format looks like)

then I would create a template something like

$template structured="<$PRI>$timestamp $hostname $syslogtag $!"

and then on the server, run mmjsonparse and make use of the results. This may 
require creating a custom template there to get the results you want.

David Lang

[1] you can also use mmnormalize. mmnormalize is far more flexible but there's 
an added config file you will have to learn.

**Comment by langzi1949** [comment]
I tried,but it doesnot work.
server log:
inputname: imtcp rawmsg: '<134>Mar  7 23:33:40 localhost ivankagateway {"app_type":"","bytes_in":0,"bytes_out":4892,"fields.time":"2017-03-07T15:06:23Z","host":"api-sit.wallstreetcn.com","latency":9,"latency_human":"9.748042ms","level":"info","method":"GET","msg":"webaccess","path":"/apiv1/content/articles","referer":"","remote_ip":"123.207.187.22","response_code":20000,"status":200,"time":"2017-03-07T15:06:23Z","topic":"user_activity","trace_id":"8341cb1db86f1","type":"webaccess","uri":"/apiv1/content/articles","user_agent":"","user_id":0}'
$!:{ "msg": "{\"app_type\":\"\",\"bytes_in\":0,\"bytes_out\":4892,\"fields.time\":\"2017-03-07T15:06:23Z\",\"host\":\"api-sit.wallstreetcn.com\",\"latency\":9,\"latency_human\":\"9.748042ms\",\"level\":\"info\",\"method\":\"GET\",\"msg\":\"webaccess\",\"path\":\"\/apiv1\/content\/articles\",\"referer\":\"\",\"remote_ip\":\"123.207.187.22\",\"response_code\":20000,\"status\":200,\"time\":\"2017-03-07T15:06:23Z\",\"topic\":\"user_activity\",\"trace_id\":\"8341cb1db86f1\",\"type\":\"webaccess\",\"uri\":\"\/apiv1\/content\/articles\",\"user_agent\":\"\",\"user_id\":0}" }
$.:
$/:

agent congiuration:
$IncludeConfig /etc/rsyslog.d/*.conf
$template structured,"<$PRI>$timestamp $hostname $syslogtag $!"
$ActionFileDefaultTemplate structured
$ModLoad mmjsonparse
*.* :mmjsonparse:

thanks  very much!!!

**Comment by davidelang** [comment]
On Tue, 7 Mar 2017, langzi1949 wrote:

> Date: Tue, 07 Mar 2017 07:40:39 -0800
> From: langzi1949 <notifications@github.com>
> Reply-To: rsyslog/rsyslog
>     <reply+0021b24f927e86ad0735b4760e98b4b9ad4b503ef13c332c92cf0000000114d6967
>     792a169ce03a27aac@reply.github.com>
> To: rsyslog/rsyslog <rsyslog@noreply.github.com>
> Cc: davidelang <david@lang.hm>, Comment <comment@noreply.github.com>
> Subject: Re: [rsyslog/rsyslog] Ask: using Wildcards with imfile (#267)
> 
> I tried,but it doesnot work.
> server log:
> inputname: imtcp rawmsg: '<134>Mar  7 23:33:40 localhost ivankagateway {"app_type":"","bytes_in":0,"bytes_out":4892,"fields.time":"2017-03-07T15:06:23Z","host":"api-sit.wallstreetcn.com","latency":9,"latency_human":"9.748042ms","level":"info","method":"GET","msg":"webaccess","path":"/apiv1/content/articles","referer":"","remote_ip":"123.207.187.22","response_code":20000,"status":200,"time":"2017-03-07T15:06:23Z","topic":"user_activity","trace_id":"8341cb1db86f1","type":"webaccess","uri":"/apiv1/content/articles","user_agent":"","user_id":0}'

> $!:{ "msg": 
> "{\"app_type\":\"\",\"bytes_in\":0,\"bytes_out\":4892,\"fields.time\":\"2017-03-07T15:06:23Z\",\"host\":\"api-sit.wallstreetcn.com\",\"latency\":9,\"latency_human\":\"9.748042ms\",\"level\":\"info\",\"method\":\"GET\",\"msg\":\"webaccess\",\"path\":\"\/apiv1\/content\/articles\",\"referer\":\"\",\"remote_ip\":\"123.207.187.22\",\"response_code\":20000,\"status\":200,\"time\":\"2017-03-07T15:06:23Z\",\"topic\":\"user_activity\",\"trace_id\":\"8341cb1db86f1\",\"type\":\"webaccess\",\"uri\":\"\/apiv1\/content\/articles\",\"user_agent\":\"\",\"user_id\":0}" 
> }

This shows that you only have one thing in $!, a variable called msg that 
contains a json string, you need to parse that string.

This is not including the $!metadata* info.

> $.:
> $/:
>
> agent congiuration:
> $IncludeConfig /etc/rsyslog.d/*.conf
> $template structured,"<$PRI>$timestamp $hostname $syslogtag $!"
> $ActionFileDefaultTemplate structured
> $ModLoad mmjsonparse
> *.* :mmjsonparse:

it's better to use the action() syntax for this, I think you need to set the 
cookie = "" so that it doesn't look for @cee at the start of the message (see 
the doc page for the exact parameter)

what does debug output on the agent look like just before you send the message?

also, setting the action _file_ default won't help when you are not writing to a 
file. It's far better to specify the template explicitly in the action() syntax

David Lang
