### ISSUE TITLE
rsyslog reorders log file content

### ISSUE THREAD

**Issue by mdreed234** [rsyslog/rsyslog#2673]
When using imfile to tail a log file and write content to either a local (same host) or remote (different host) logging server, the content of the tailed file is reordered in the destination file.  The size of the source and destination files is the same.  The number of lines in each file is the same.

imfile -> omfile
-or-
imfile -> omfwd (tcp) -> omfile

(Non-trivial rules included.)

### Expected behavior
Log entries in the destination file should be in the same order as the source file.

### Actual behavior
Log messages are written out of order.

### Steps to reproduce the behavior
- remove content of /var/lib/rsyslog/ directory
- start rsyslog on local server (reproduces with remote source also)
- rsyslog starts writing existing log files from the beginning (what I want)
- compare source and destination files

---- or -----
-remove content of /var/lib/rsyslog/ directory
- remove source file
- start rsyslog on local server
- start writing a line at a time to the source log file
- rsyslog starts writing lines to the destination log file
- compare source and destination files

Note: if I rate limit the creation of the source log file via a usleep(1) between each line, rsyslog correctly orders all entries in the destination file.

Note: originally observed working with 20 different files.  If I rate limited the writing of the source files via usleep(500) the destination files are the same as the source files.

[rsyslog_issue_config.zip](https://github.com/rsyslog/rsyslog/files/1956916/rsyslog_issue_config.zip)

### Environment
RHEL 7.4.
[root@koufax ISSUE]# rsyslogd -v
rsyslogd 8.34.0, compiled with:
        PLATFORM:                               x86_64-redhat-linux-gnu
        PLATFORM (lsb_release -d):
        FEATURE_REGEXP:                         Yes
        GSSAPI Kerberos 5 support:              Yes
        FEATURE_DEBUG (debug build, slow code): No
        32bit Atomic operations supported:      Yes
        64bit Atomic operations supported:      Yes
        memory allocator:                       system default
        Runtime Instrumentation (slow code):    No
        uuid support:                           Yes
        systemd support:                        Yes
        Number of Bits in RainerScript integers: 64

**Comment by davidelang** [comment]
Yes, this is a common thing. Rsyslog uses multiple threads to process messages, 
and can relay through multiple network connections (and can use UDP which does 
not provide in-order guarantees), plus can be relayed through multiple systems 
in parallel.

As a result of all of these things, we made the decision about a decade ago that 
trying to guarantee in-order delivery was doomed to failure, and so we accept 
the fact that logs may be delivered out of order and work to implement the best 
possible performance/throughput, even in cases where this can cause messages to 
be delivered out of order.

As an example, we allow multiple threads to work to deliver messages that are in 
a queue. They do this by each thread locking the queue, 'claiming' a batch of 
messages, unlocking the queue and then processing them. When thread 1 claims 
messages 1-100, and a bit later thread 2 claims messages 101-200, thread 2 will 
probably process message 101 before thread 1 processes message 100.

There are _many_ features in rsyslog can can end up causing out-of-order 
delivery.

At moderate traffic loads, where you only need a single thread to process the 
messages, you probably will not see any re-ordering. but as the traffic loads 
increase, or you have problems (network interruptions, disk assisted queues, 
multiple worker threads, etc), you become more likely to run into a situation 
where logs will be re-ordered

David Lang

**Comment by mdreed234** [comment]
Thank you for the excellent clarification.

Would you have time to offer some configuration guidance for settings that will minimize the inherent out-of-orderness that you describe above?
