### ISSUE TITLE
Rsyslog kafka 8.26.0 rpm package is removed from rpms adiscon list

### ISSUE THREAD

**Issue by wess1984** [rsyslog/rsyslog#2692]
### Expected behavior
Rsyslog kafka module rpm package version 8.26.0 need to be found in [rpms adiscon list](http://rpms.adiscon.com/v8-stable/epel-6/x86_64/RPMS) 
### Actual behavior
Rsyslog kafka 8.26.0 is removed

### Environment
- rsyslog version:  8.26.0
- platform: Centos 6.9

**Comment by rgerhards** [comment]
This package has been removed because it was heavily broken. You need at least 8.30 for a working kafka version.

**Comment by wess1984** [comment]
We work with rsyslog gnutls and  we got the error  **Ohhhh jeeee: Assertion 'pool_is_locked' failed(random-csprng.c:1078:add_randomness**
The rsyslog gnutls version 8.26.0 is the only version that doesn't generate this problem. That's why we use rsyslog, rsyslog-kafka and rsyslog-gnutls of the version 8.26.0.

Any help ! thanks

**Comment by wess1984** [comment]
That's a good news, thank you @rgerhards . I am eager to see the 8.36 version
