### ISSUE TITLE
logaudit facility name

### ISSUE THREAD

**Issue by jkvbe** [rsyslog/rsyslog#2695]
### Expected behavior
I wanted to filter on  logaudit facility in the rsyslog configuration file using selectors.  This is a facility that is defined in the standard RFC5424

### Actual behavior
This gives the error: unknown facility name. Is there any reason why it's not supported?

### Steps to reproduce the behavior
See above.

### Environment
rsyslogd 8.34.0, compiled with:
	PLATFORM:				x86_64-pc-linux-gnu
	PLATFORM (lsb_release -d):		
	FEATURE_REGEXP:				Yes
	GSSAPI Kerberos 5 support:		No
	FEATURE_DEBUG (debug build, slow code):	No
	32bit Atomic operations supported:	Yes
	64bit Atomic operations supported:	Yes
	memory allocator:			system default
	Runtime Instrumentation (slow code):	No
	uuid support:				Yes
	systemd support:			No
	Number of Bits in RainerScript integers: 64

platform: Ubuntu 14.04.5

**Comment by rgerhards** [comment]
the traditional name for this facility inside syslogds is ```audit```. The RFC does not give mnemonic names but rather a short description (thus the spaces in the names).
