### ISSUE TITLE
Compilation broken if liblogging-stdlog is installed into custom path

### ISSUE THREAD

**Issue by dirker** [rsyslog/rsyslog#2697]
### Expected behavior

The rsyslog configure script should find liblogging-stdlog via pkg-config and add its include and library paths to cflags.

### Actual behavior

The rsyslog configure script find's liblogging-stdlog via pkg-config, but does not add the include nor the library paths to cflags and ldflags. Build fails in imfile.c:

```
Making all in plugins/imfile
  CC       imfile_la-imfile.lo
In file included from imfile.c:51:
In file included from ../../runtime/rsyslog.h:663:
In file included from ../../runtime/obj.h:48:
In file included from ../../runtime/stream.h:73:
../../runtime/glbl.h:35:10: fatal error: 'liblogging/stdlog.h' file not found
```

### Steps to reproduce the behavior

Install liblogging-stdlog to /tmp/liblogging, add /tmp/liblogging/lib/pkgconfig to PKG_CONFIG_PATH and try to build rsyslog.

### Environment
- rsyslog version: 8.34.0

**Comment by ilovezfs** [comment]
This PR fixes it: https://github.com/rsyslog/rsyslog/pull/2703
