### ISSUE TITLE
omhiredis produce "could not load module '/usr/lib64/rsyslog/omhiredis.so', dlopen: /usr/lib64/rsyslog/omhiredis.so: undefined symbol: redisConnectWithTimeout"

### ISSUE THREAD

**Issue by FlyingPengu** [rsyslog/rsyslog#2700]
After rebuilding the rsyslog-RPMs with hiredis, rsyslog always logs
`rsyslogd: could not load module '/usr/lib64/rsyslog/omhiredis.so', dlopen: /usr/lib64/rsyslog/omhiredis.so: undefined symbol: redisConnectWithTimeout  [v8.24.0 try http://www.rsyslog.comand/e/2066 ]`
and the redis-support isn't working.

I already tried the SRPM from Adiscon with the newest version and the SRPMs from RedHat and CentOS. To reproduce this beahivor, I install the SPRM, edit the line 5 in the spec-file to `%global want_hiredis 1` and start the build with `rpmbuild -ba rsyslog.spec`.
This will create all the needed RPMs, including `rsyslog-hiredis-8.24.0-16.el7.centos.x86_64.rpm` for CentOS. I installed the the new main RPM and the hiredis RPM. After editing the config and restarting rsyslog, I get the error.

- rsyslog version: 8.24.0 & 8.34.0
- platform: RHEL7/CentOS7

**Comment by rgerhards** [comment]
mhhh... ```redisConnectWithTimeout``` seems to be a redis API. This would mean that the redis lib is too old  or for some other reason does not support it? Or maybe the lib is actually not linked in? I am guessing here, as omhiredis is a contributed module and I do not have any know-how at all about it... Maybe it still helps.

**Comment by rgerhards** [comment]
not sure if that helps, but: https://bugzilla.redhat.com/show_bug.cgi?id=1056671

**Comment by rgerhards** [comment]
@brianknox do you have an idea what might be causing this?
