### ISSUE TITLE
imrelp.so fails to load from rsyslog-relp-8.35.0-1.el7.centos

### ISSUE THREAD

**Issue by qha** [rsyslog/rsyslog#2717]
### Expected behavior
* imrelp.so loads and listens for messages on configured port.

### Actual behavior
* Rsyslogd complains about undefined symbol in imrelp.so:
```
syslog/err rsyslogd[171468]: could not load module '/usr/lib64/rsyslog/imrelp.so', dlopen: /usr/lib64/rsyslog/imrelp.so: undefined symbol: relpSrvSetOversizeMode  [v8.35.0 try http://www.rsyslog.com/e/2066 ]
syslog/err rsyslogd[171468]: input module name 'imrelp' is unknown [v8.35.0 try http://www.rsyslog.com/e/2209 ]
syslog/err rsyslogd[171468]: error during parsing file /etc/rsyslog-forwarder.conf, on or before line 457: parameter 'port' not known -- typo in config file? [v8.35.0 try http://www.rsyslog.com/e/2207 ]
```
* Rsyslog does not listen on configured port.

### Steps to reproduce the behavior
install Rsyslog and rsyslog-relp from Adiscon yum repo.
Configure Rsyslog to use imrelp.

### Environment

Packages from Adiscon yum repo: http://rpms.adiscon.com/v8-stable/epel-7/x86_64/

- rsyslog-8.35.0-1.el7.centos
- rsyslog-relp-8.35.0-1.el7.centos
- rsyslog-gnutls-8.35.0-1.el7.centos
- librelp-1.2.16-1.el7.centos.x86_64
- platform: Centos 7.5.1804

**Comment by rgerhards** [comment]
thx for the bug report. Can you double-check that librelp 1.2.16 is actually installed?

**Comment by qha** [comment]
My apologies. The rsyslog-relp package only required librelp 1.2.15 (see below) so it only got updated after i downgraded the other packages.

With the latest librelp i get a warning about "imrelp: librelp too old, oversizemode defaults to "abort"" and Rsyslog listens on the configured port.

Thank you for your prompt response!

```
# rpm -qRp rsyslog-relp-8.35.0-1.el7.centos.x86_64.rpm   
libc.so.6()(64bit)
libc.so.6(GLIBC_2.14)(64bit)
libc.so.6(GLIBC_2.2.5)(64bit)
libc.so.6(GLIBC_2.3)(64bit)
libc.so.6(GLIBC_2.3.4)(64bit)
libc.so.6(GLIBC_2.4)(64bit)
librelp >= 1.2.15
librelp.so.0()(64bit)
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(FileDigests) <= 4.6.0-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rsyslog = 8.35.0-1.el7.centos
rtld(GNU_HASH)
rpmlib(PayloadIsXz) <= 5.2-1
```

**Comment by deoren** [comment]
> @qha: With the latest librelp i get a warning about "imrelp: librelp too old, oversizemode defaults to "abort"

Confirmed bug: #2712 (looks to be fixed in the next release?)

**Comment by qha** [comment]
@deoren Yep, thanks!

That bug seems not to be a problem in our configuration so the only remaining part of this bug report is the require librelp version in the rpm spec.

**Comment by rgerhards** [comment]
I hope that  @friedl can apply the fix tomorrow. Re the invalid warning message, I also talk to him if he can apply a local patch to our packages.

**Comment by friedl** [comment]
The patch was applied to the packages, so newer 8.35.0 packages than the first have the imrelp patch.

8.36.0 has the fix included and the patch will be obsolete again.
