### ISSUE TITLE
Rsyslog v8.34.0 omkafka not works,no connection to kafka cluster

### ISSUE THREAD

**Issue by jerry-chen-315** [rsyslog/rsyslog#2728]
## Expected behavior
  omkafka works fine,which can output log to kafka cluster

## Actual behavior
  No log output to kafka cluster.The kafka port 9092 can be telneted on the server,but no rsyslogd process connected the port.
  It should be like below:

    tcp        0      0 10.200.220.5:47993          162.30.10.214:9092          ESTABLISHED 30933/rsyslogd      
    tcp        0      0 10.200.220.5:48561          162.30.10.212:9092          ESTABLISHED 30933/rsyslogd      
    tcp        0      0 10.200.220.5:54325          162.30.10.213:9092          ESTABLISHED 30933/rsyslogd      
    tcp        0      0 10.200.220.5:58418          162.30.10.211:9092          ESTABLISHED 30933/rsyslogd      
    tcp        0      0 10.200.220.5:45658          162.30.10.215:9092          ESTABLISHED 30933/rsyslogd

- my kafka.conf

the same as other server

    module(load="omkafka")
    module(load="imfile")
    
    input(type="imfile" Tag="10.200.220.66;audit" File="/var/log/audit/audit.log" Ruleset="auditlog")
    
    template(name="jsonfmt" type="list" option.jsonf="on") {
        property(outname="@timestamp" name="timereported" dateFormat="rfc3339" format="jsonf")
        property(outname="hostname" name="hostname" format="jsonf")
        property(outname="hostip" name="syslogtag" format="jsonf" field.delimiter="59" field.number="1")
        property(outname="syslog-tag" name="syslogtag" format="jsonf" field.delimiter="59" field.number="2")
        property(outname="message" name="msg" format="jsonf")
        
    }
    
    ruleset(name="auditlog") {
      action (
        type="omkafka"
        topic="auditlog"
        broker=["162.30.10.211:9092","162.30.10.212:9092","162.30.10.213:9092","162.30.10.214:9092","162.30.10.215:9092"]
        template="jsonfmt"
        key="10.200.220.66"
        partitions.auto="on"
        errorfile="/var/log/rsyslog-kafka.err"
      )
    }

 - The debug log

[rsyslogd-nd.log.log](https://github.com/rsyslog/rsyslog/files/2016292/rsyslogd-nd.log.log)

## Environment
rsyslogd 8.34.0
platform: CentOS 6

Any help wil be appreciated

**Comment by lurenx** [comment]
what's the version of your kafka broker?

**Comment by jerry-chen-315** [comment]
kafka version 1.1.0

**Comment by cyber035** [comment]
have you tried turning off selinux, that helped me pin down the problem...

**Comment by jerry-chen-315** [comment]
@cyber035 yes,it has turned off before rsyslog restart.It's works fine since downgrade version of rsyslog to 8.33.1

**Comment by aturetta** [comment]
The same happens with 8.37.0

I've been able to get it working only because kafka is in the same machine, I omitted the 'broker' parameter and it connects just fine to localhost:9092

I think the config parser is mangling something, will get a look at it soon

**Comment by aturetta** [comment]
turns out I'm just being dumb....

kafka was up but not running due to problems with zookeeper, once fixed everything works ok
