### ISSUE TITLE
imjournal: conversion of Journal property names to cee/lumberjack fails

### ISSUE THREAD

**Issue by rgerhards** [rsyslog/rsyslog#273]
Imjournal should convert Journal property names (like "_PID") to their lumberjack equivalents (here: "pid"). This does not happen.

**Comment by timbunce** [comment]
See also #603

**Comment by portante** [comment]
@timbunce, this PR, https://github.com/rsyslog/rsyslog/pull/604, attempts to enable the intended behavior that is blocked by a bug.

It is still not code to do that for all properties exported by journald.

**Comment by rgerhards** [comment]
I assume this is fixed by #604. If not, please report.
