### ISSUE TITLE
imfile wildcart except .gz

### ISSUE THREAD

**Issue by vdmitrief** [rsyslog/rsyslog#2731]
Hi,
I have a directory with the following files:
ssl-proxy-access-yyyyMMDD
ssl-proxy-access-yyyyMMDD.gz
How do I configure File in imfile to collect files of type ssl-proxy-access-yyyyMMDD and ignore files *.gz ?

**Comment by rgerhards** [comment]
you should check with bash ```glob```. imfile essentially uses the same functionality.
