### ISSUE TITLE
rsyslog core dumps at the function rs_send_to_aggr

### ISSUE THREAD

**Issue by akarri** [rsyslog/rsyslog#2737]
### Expected behavior
It shouldn't generate the core dump.
### Actual behavior
The rsyslog core dumps are generated on the node with the name 
core.ubuntulxc.1506454191.rs_send_to_aggr.10688
Type "apropos word" to search for commands related to "word"...
Reading symbols from rsyslogd...Reading symbols from /usr/lib/debug//usr/sbin/rsyslogd...done.
done.
[New LWP 720]
[New LWP 719]
[New LWP 723]
[New LWP 725]
[New LWP 717]
[New LWP 732]
[New LWP 724]
[New LWP 727]
[New LWP 731]
[New LWP 721]
[New LWP 722]
[New LWP 730]
[New LWP 726]
[New LWP 729]
[New LWP 728]
Core was generated by `rsyslogd'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000000000041f01c in doGetUID (val=<optimized out>, val=<optimized out>, param=<optimized out>, valnode=<optimized out>) at rainerscript.c:867
867     rainerscript.c: No such file or directory.
(gdb)

### Steps to reproduce the behavior
In quite race conditions the cores are generated on node while reboot of the system.

### Environment

- rsyslog version: 
rsyslogd 8.29.0, compiled with:
        PLATFORM:                               x86_64-pc-linux-gnu
        PLATFORM (lsb_release -d):
        FEATURE_REGEXP:                         Yes
        GSSAPI Kerberos 5 support:              No
        FEATURE_DEBUG (debug build, slow code): No
        32bit Atomic operations supported:      Yes
        64bit Atomic operations supported:      Yes
        memory allocator:                       system default
        Runtime Instrumentation (slow code):    No
        uuid support:                           Yes
        Number of Bits in RainerScript integers: 64

- platform: 
Ubuntu 14.04
- for configuration questions/issues, include rsyslog.conf and included config files

**Comment by davidelang** [comment]
please post your config.

**Comment by akarri** [comment]
Hi David,
Thanks for consideration of the issue. Here are the config files. 

root@ubuntulxc:~# cat /etc/rsyslog.conf
#Managed by puppet
###########################
#### GLOBAL DIRECTIVES ####
###########################

global(
    MaxMessageSize="32k"
    WorkDirectory="/var/spool/rsyslog"
    )

#
# Set the default permissions for all log files.
#
$FileOwner root
$FileGroup adm
$FileCreateMode 0640
$DirCreateMode 0750
$umask 0027

#$PrivDropToUser root
#$PrivDropToGroup adm

# use FQDN for logging
$PreserveFQDN on
$LocalHostName ubuntulxc.1506454191.test

$MaxOpenFiles 4096

#
# Disk-Assisted Memory Queues, async writes, no escape chars
#
$EscapeControlCharactersOnReceive off
$OMFileASyncWriting on

main_queue(
    queue.type="LinkedList"
    queue.filename="mainmsgqueue"
    queue.saveonshutdown="on"
    queue.dequeueslowdown="1000"
    queue.workerthreads="1"
    queue.timeoutworkerthreadshutdown="-1"
    queue.dequeuebatchsize="128"
    queue.maxfilesize="10m"
    queue.maxdiskspace="500m"
    queue.size="251000"
    queue.discardmark="250000"
    queue.discardseverity="0"
    queue.highwatermark="200000"
    queue.lowwatermark="150000"
    )

# Templates
# RFC3164 emulation with long tags (32+)
template(name="ForwardFormat" type="list") {
  constant(value="<")
  property(name="pri")
  constant(value=">")
  property(name="timestamp" dateFormat="rfc3339")
  constant(value=" ")
  property(name="hostname")
  constant(value=" ")
  property(name="syslogtag" position.from="1" position.to="32")
  property(name="msg" spifno1stsp="on" )
  property(name="msg")
}
template(name="OutLogFileWithPath" type="string" string="/var/log/%$!log_dirname%/%programname%.log")
template(name="OutLogFileWithName" type="string" string="/var/log/%$!log_filename%.log")

#################
#### MODULES ####
#################

module(load="imuxsock" SysSock.UsePIDFromSystem="on") # provides support for local system logging
module(load="imklog")   # provides kernel logging support (previously done by rklogd)
module(load="imudp")    # load UDP input module
# add UDP/514 receiver on localhost and on the mgmt network only
input(type="imudp" address="127.0.0.1" port="514" rcvbufSize="1m")
input(type="imudp" address="192.168.2.28" port="514" rcvbufSize="1m")

#
# Include all config files in /etc/rsyslog.d/
#
$IncludeConfig /etc/rsyslog.d/*.conf






cat /etc/rsyslog.d/00-01-log-aggregator-client.conf
#Managed by puppet

# Action for forwarding events to log aggregator
# ----------------------------------------------#
module(load="omrelp")
ruleset(name="send_to_aggregator"){
    action(name="send_to_aggregator"
        type="omrelp"
        target="192.168.2.30"
        port="20514"
        timeout="120"
        queue.fileName="relay_to_aggregator"
        queue.maxDiskSpace="100M"
        queue.size="50000"
        queue.discardMark="45000"
        queue.discardSeverity="0"
        queue.type="disk"
        queue.checkpointInterval="100"
        queue.saveOnShutdown="on"
        queue.workerthreads="1"
        action.resumeRetryCount="-1")
    stop
}


# Rules for audit events.
# audispd uses the LOG_USER facility by dafault
# vnx-log-fetcher uses the 'vnx' programname
# when auditd isn't running the kernel logs audit events with its own facility
# ----------------------------------------------#
if ($syslogfacility == 1 and $programname == "audispd") or
 ($programname == "vnx") or
 ($syslogfacility == 0 and re_match($msg, "^ \\[.{12}\\] audit: ")) then {
    call send_to_aggregator
}
Regards,
Anil.
