### ISSUE TITLE
FIPS mode

### ISSUE THREAD

**Issue by jonetsu** [rsyslog/rsyslog#274]
Federal Information Processing Standards (FIPS) validation requires, amongst other things, the use of a restricted set of ciphers.  While libraries (GnuTLS, OpenSSL, NSS) assures the use of such a set when running in FIPS mode, the applications using then must also be aware of the limited choice.  Remote secure logging done by rsyslog can benefit from natively supporting FIPS mode when used in systems that are targeted to customers who cares about observing such a standard.

GnuTLS does support FIPS mode.  While running in FIPS mode, GnuTLS can out the list of restricted ciphers, hashes, algorithms allowed to use.  This is the list below.  If needed, compiling GnuTLS for FIPS mode is straightforward (currently needs a patch, though) except for one detail concerning the generation of HMAC files for the library that are in turn checked at run time.  Let me know if more info is needed.

% gnutls-cli -l --priority NORMAL

 Cipher suites for NORMAL
 TLS_ECDHE_ECDSA_AES_128_GCM_SHA256  0xc0, 0x2b      TLS1.2
 TLS_ECDHE_ECDSA_AES_256_GCM_SHA384  0xc0, 0x2c      TLS1.2
 TLS_ECDHE_ECDSA_AES_128_CBC_SHA1    0xc0, 0x09      SSL3.0
 TLS_ECDHE_ECDSA_AES_128_CBC_SHA256  0xc0, 0x23      TLS1.0
 TLS_ECDHE_ECDSA_AES_256_CBC_SHA1    0xc0, 0x0a      SSL3.0
 TLS_ECDHE_ECDSA_AES_256_CBC_SHA384  0xc0, 0x24      TLS1.0
 TLS_ECDHE_ECDSA_3DES_EDE_CBC_SHA1   0xc0, 0x08      SSL3.0
 TLS_ECDHE_RSA_AES_128_GCM_SHA256    0xc0, 0x2f      TLS1.2
 TLS_ECDHE_RSA_AES_256_GCM_SHA384    0xc0, 0x30      TLS1.2
 TLS_ECDHE_RSA_AES_128_CBC_SHA1      0xc0, 0x13      SSL3.0
 TLS_ECDHE_RSA_AES_128_CBC_SHA256    0xc0, 0x27      TLS1.0
 TLS_ECDHE_RSA_AES_256_CBC_SHA1      0xc0, 0x14      SSL3.0
 TLS_ECDHE_RSA_AES_256_CBC_SHA384    0xc0, 0x28      TLS1.0
 TLS_ECDHE_RSA_3DES_EDE_CBC_SHA1     0xc0, 0x12      SSL3.0
 TLS_RSA_AES_128_GCM_SHA256          0x00, 0x9c      TLS1.2
 TLS_RSA_AES_256_GCM_SHA384          0x00, 0x9d      TLS1.2
 TLS_RSA_AES_128_CBC_SHA1            0x00, 0x2f      SSL3.0
 TLS_RSA_AES_128_CBC_SHA256          0x00, 0x3c      TLS1.0
 TLS_RSA_AES_256_CBC_SHA1            0x00, 0x35      SSL3.0
 TLS_RSA_AES_256_CBC_SHA256          0x00, 0x3d      TLS1.0
 TLS_RSA_3DES_EDE_CBC_SHA1           0x00, 0x0a      SSL3.0
 TLS_DHE_RSA_AES_128_GCM_SHA256      0x00, 0x9e      TLS1.2
 TLS_DHE_RSA_AES_256_GCM_SHA384      0x00, 0x9f      TLS1.2
 TLS_DHE_RSA_AES_128_CBC_SHA1        0x00, 0x33      SSL3.0
 TLS_DHE_RSA_AES_128_CBC_SHA256      0x00, 0x67      TLS1.0
 TLS_DHE_RSA_AES_256_CBC_SHA1        0x00, 0x39      SSL3.0
 TLS_DHE_RSA_AES_256_CBC_SHA256      0x00, 0x6b      TLS1.0
 TLS_DHE_RSA_3DES_EDE_CBC_SHA1       0x00, 0x16      SSL3.0
 TLS_DHE_DSS_AES_128_GCM_SHA256      0x00, 0xa2      TLS1.2
 TLS_DHE_DSS_AES_256_GCM_SHA384      0x00, 0xa3      TLS1.2
 TLS_DHE_DSS_AES_128_CBC_SHA1        0x00, 0x32      SSL3.0
 TLS_DHE_DSS_AES_128_CBC_SHA256      0x00, 0x40      TLS1.0
 TLS_DHE_DSS_AES_256_CBC_SHA1        0x00, 0x38      SSL3.0
 TLS_DHE_DSS_AES_256_CBC_SHA256      0x00, 0x6a      TLS1.0
 TLS_DHE_DSS_3DES_EDE_CBC_SHA1       0x00, 0x13      SSL3.0

 Certificate types: CTYPE-X.509

 Protocols: VERS-TLS1.2, VERS-TLS1.1, VERS-TLS1.0, VERS-SSL3.0,
 VERS-DTLS1.2, VERS-DTLS1.0

 Compression: COMP-NULL

 Elliptic curves: CURVE-SECP256R1, CURVE-SECP384R1,
 CURVE-SECP521R1, CURVE-SECP224R1, CURVE-SECP192R1

 PK-signatures: SIGN-RSA-SHA256, SIGN-DSA-SHA256,
 SIGN-ECDSA-SHA256, SIGN-RSA-SHA384, SIGN-ECDSA-SHA384, SIGN-R
 SA-SHA512, SIGN-ECDSA-SHA512, SIGN-RSA-SHA224, SIGN-DSA-SHA224,
 SIGN-ECDSA-SHA224, SIGN-RSA-SHA1, SIGN-DSA-SHA 1, SIGN-ECDSA-SHA1

**Comment by JPvRiel** [comment]
It would be nice if rsyslog could support  protocol support, cipher lists, and sever cipher ordering preference options within the configuration, much like can be done with Apache, etc.

**Comment by psinghbh** [comment]
Is there any plan for implementing this in near future or anyone working on this?

**Comment by davidelang** [comment]
what is FIPS mode for logs? the FIPS I'm familiar with deals with certification 
of encryption code (and due to the way it's managed, it's very ard for 
opensource software to to remain certified, every path requires expensive 
recertification)

David Lang

**Comment by JPvRiel** [comment]
> it's very hard for opensource software to to remain certified

One way to avoid that is to provide configuration directives where users can control their choice of cipher suites, and then it's up to the user to configure it in a FIPS compliant way.

 > what is FIPS mode for logs?

Not an expert with all the FIPS requirements, but I'd assume the scope of this conversation only pertains to `TLS` parts and allowing configuration of GNU lib internals - not everything else FIPS might imply about the other RSyslog features like signing messages (e.g. `rsyslog-ksi-ls12`).

**Comment by rgerhards** [comment]
I, too, think that it would make much sense to provide the ability to configure GnuTLS in-depth. I think @PascalWithopf worked on support for setting the priority string, but I am not sure if that bear any fruit right now. @PascalWithopf can you comment on that?

**Comment by PascalWithopf** [comment]
The GnuTLS priority string can be used since 8.30.0 and is fully functional.
