### ISSUE TITLE
Asynchronous logging may deadlock

### ISSUE THREAD

**Issue by rmetrich** [rsyslog/rsyslog#2741]
### Expected behavior

No deadlock when using Asynchronous logging

### Actual behavior

Deadlock of AsyncWriterThread + deadlock of Main thread (after sending SIGHUP, typically done by logrotate).
I wasn't able to reproduce the issue using the regular rsyslog code, but one of Red Hat's customers is hitting this regularly.
To reproduce in my environment, I modified slightly the rsyslog code (see below) to show the window where the issue happens.
Please refer to the commit description.

### Steps to reproduce the behavior

See branch [Issue_1701_Reproducer](https://github.com/rmetrich/rsyslog/tree/Issue_1701_Reproducer) which modifies rsyslog code to very easily reproduce.
Reading #1701, this looks similar, but there is no stack trace in the issue to be sure, and also the issue has been closed.

For now I cannot propose a fix because I don't understand exactly how async writer is supposed to work.

### Environment
- rsyslog version: latest upstream (8.36.0.master)
- platform: Fedora 27, RHEL 7

**Comment by rgerhards** [comment]
fixed by https://github.com/rsyslog/rsyslog/pull/2794 in v8.37
