### ISSUE TITLE
Invalid config statements recreating socket

### ISSUE THREAD

**Issue by jvymazal** [rsyslog/rsyslog#2744]
### Expected behavior
More explicit error report/failure when this happens. It is very hard to find out what happened in this case. You get basically no hint to what is wrong if you do config typo like the one below.

### Actual behavior
restarting rsyslog recreates /dev/log socket, possibly breaking other input (such as imjournal)

### Steps to reproduce the behavior
-  apply below config
- `stat /dev/log`
- restart rsyslog
- `stat /dev/log` - you see that file is recreated
- `logger test` - message does not get trough

### Environment
- rsyslog version: 8.35.0
- platform: fedora 27
- for configuration questions/issues, include rsyslog.conf and included config files
relevant conf snippet:
`$ModLoad imuxsock`
`$ModLoad imjournal`
`set $var;`

**Comment by jvymazal** [comment]
@rgerhards any ideas on how to make it more clear? Maybe complete abort on such config problems?

**Comment by jvymazal** [comment]
No, they can co-function if configured properly, what I meant is that if you do some kinds of config typos (like the `set $var;` in the example) you break logging and it is very hard to find out what is wrong because rsyslog appears to function.

**Comment by rgerhards** [comment]
there is an ```$AbortOnUncleanConfig``` to make rsyslog abort if something is not right. The core idea - and requirement for many years - was that it is better to keep rsyslog running vs shut it down on all errors. This is what the option controls. See https://www.rsyslog.com/doc/v8-stable/configuration/global/options/rsconf1_abortonuncleanconfig.html

I fear there is no new-style equivalent at the moment.

**Comment by jvymazal** [comment]
Ok, understood, however the new-style equivalent would be nice.

**Comment by rgerhards** [comment]
> however the new-style equivalent would be nice.

definitely!
