### ISSUE TITLE
Rsyslog v5 multiline input and TCP-output 

### ISSUE THREAD

**Issue by vdmitrief** [rsyslog/rsyslog#2745]
Hi, experts!
How do I configure Rsyslog v5 to collect multiline log-file and transport it to TCP-output?
The same thing I do at Rsyslog v8< but I need it on Rsyslog v5 (security policies do not allow updating v5 on v8).
Thanks!

**Comment by rgerhards** [comment]
no way except to change the security policies - sorry for that.

**Comment by vdmitrief** [comment]
Hi, Rgerhards
https://www.rsyslog.com/doc/v5-stable/configuration/examples.html This example shows how you can send by TCP. Can I use this function for my task and could you show an example of a working configuration for rsyslog v5?

**Comment by vdmitrief** [comment]
I got a solution to this task...
Maybe someone will come in handy for my decision.
Here is the working configuration in Rsyslog v5 that sends multiline logs to the tcp-output

```
$ModLoad imfile
#----------------  INPUT ----------------------
# file 1
$InputFileName /tmp/file1.log
$InputFileTag FILE1-tag
$InputFileStateFile FILE1-stat
$InputRunFileMonitor
$InputFileReadMode 2

# file 2
$InputFileName /tmp/file2.log
$InputFileTag FILE2-tag
$InputFileStateFile FILE2-stat
$InputRunFileMonitor
$InputFileReadMode 2
#-------------- ACTIONS -----------------------
$ActionQueueType LinkedList
#------------ TEMPLATES ------------------------
$template ForwardFormat,"%msg:::drop-last-lf%\n"
#-------------  OUTPUT  ----------------------
if $syslogtag =='FILE1-tag' then @@192.168.1.113:2510;ForwardFormat
if $syslogtag =='FILE2-tag' then @@192.168.1.113:2511;ForwardFormat
```

**Comment by davidelang** [comment]
I think that you will find that multiline logs will be broken up on the 
receiving side with this config.

you would need to use octet counting mode on your output

David Lang
