### ISSUE TITLE
I'm getting a build error in /plugins/ommongodb/ommongodb.c 

### ISSUE THREAD

**Issue by mmonson** [rsyslog/rsyslog#2753]
### Expected behavior
No compile errors on the v8-stable or main branch
### Actual behavior
make[2]: Entering directory '/opt/rsyslog/rsyslog/plugins/ommongodb'
  CC       ommongodb_la-ommongodb.lo
ommongodb.c: In function ‘initMongoDB’:
ommongodb.c:204:3: error: unknown type name ‘mongoc_ssl_opt_t’
   mongoc_ssl_opt_t ssl_opts;
   ^
ommongodb.c:205:31: error: ‘mongoc_ssl_opt_t’ undeclared (first use in this function)
   memset(&ssl_opts, 0, sizeof(mongoc_ssl_opt_t));
                               ^
ommongodb.c:205:31: note: each undeclared identifier is reported only once for each function it appears in
ommongodb.c:206:14: error: request for member ‘pem_file’ in something not a structure or union
      ssl_opts.pem_file = pData->ssl_cert;
              ^
ommongodb.c:207:14: error: request for member ‘ca_file’ in something not a structure or union
      ssl_opts.ca_file = pData->ssl_ca;
              ^
ommongodb.c:208:6: error: implicit declaration of function ‘mongoc_client_set_ssl_opts’ [-Werror=implicit-function-declaration]
      mongoc_client_set_ssl_opts (pData->client, &ssl_opts);

### Steps to reproduce the behavior
1.   download clean repo
2   run autoreconf -fvi
3   make

### Environment
- rsyslog version: 8.35.0
- platform: compiled on Ubuntu 16.04 

This all seems to be due to a missing definition for mongoc_ssl_opt_t

**Comment by rgerhards** [comment]
I guess your version of libmongo-c is too old. Configure should probably check for a minimum version.

**Comment by rgerhards** [comment]
@mmonson did you try with an updated libmongo-c?

**Comment by rgerhards** [comment]
alternatively, please post config.log so that we can check what configure saw

**Comment by mmonson** [comment]
Yes that seems to be working 
I tried running (sudo /usr/sbin/rsyslogd -nd) with the attached rsyslog.conf file and I get this error  I get this same error with the TCP and UDP listeners commented out and with 
$ActionFileDefaultTemplate RSYSLOG_TraditionalFileFormat

2688.264121771:main Q:Reg/w0  : ommongodb.c: ommongodb: ts_gen is 0
2688.264146325:main Q:Reg/w0  : ommongodb.c: ommongodb: secfrac is 0, precision 3
2688.264170547:main Q:Reg/w0  : errmsg.c: Called LogMsg, msg: syslogTime2time_t: invalid year 0 in timestamp - returning 1970-01-01 instead
2688.264199312:main Q:Reg/w0  : iminternal.c: signaling new internal message via SIGTTOU: 'syslogTime2time_t: invalid year 0 in timestamp - returning 1970-01-01 instead [v8.36.0]'
2688.264229903:main thread    : janitor.c: janitorRun() called
2688.264253939:main thread    : ratelimit.c: msg repeated 1 times
2688.264263042:main thread    : ratelimit.c: message discarded by ratelimiting
rsyslogd: syslogTime2time_t: invalid year 0 in timestamp - returning 1970-01-01 instead [v8.36.0]
Segmentation fault (core dumped)


[rsyslog-error.zip](https://github.com/rsyslog/rsyslog/files/2142874/rsyslog-error.zip)


[rsyslog.zip](https://github.com/rsyslog/rsyslog/files/2142870/rsyslog.zip)

**Comment by mmonson** [comment]
Thanks ommongodb wasn't in the rsyslog/lib directory. After installing rsyslog-ommongodb things work as long as I don't have a username and password in the action.  Using: 
*.* action(type="ommongodb" server="127.0.0.1" db="syslog" collection="log" uid="user" pwd="pwd")   I get 

Cleanup: popping token $end ()
Cleanup: popping nterm conf ()
2018/06/28 19:45:37.0161: [21338]:    DEBUG:      cluster: Authentication failed: Unsupported mechanism PLAIN
Segmentation fault (core dumped)

if i remove uid and pwd from the action things work
[Downloads.zip](https://github.com/rsyslog/rsyslog/files/2146795/Downloads.zip)

**Comment by davidelang** [comment]
check your mongodb config, it sounds as if it doesn't support the authentication 
method "plain"
k

**Comment by mmonson** [comment]
Looking through Authentication Options here : https://docs.mongodb.com/manual/reference/program/mongo/
authentication method PLAIN is only supported by mongo enterprise edition  default security is now SCRAM.  It appears the PLAIN may have been supported prior to mongo 2.6 (or possibly 3.0)
 
I do not see any way to enable the PLAIN authentication method in mongo

**Comment by davidelang** [comment]
On Fri, 29 Jun 2018, mmonson wrote:

> Looking through Authentication Options here : https://docs.mongodb.com/manual/reference/program/mongo/
> authentication method PLAIN is only supported by mongo enterprise edition  default security is now SCRAM.  It appears the PLAIN may have been supported prior to mongo 2.6 (or possibly 3.0)
>
> I do not see any way to enable the PLAIN authentication method in mongo

If they have removed the ability to do PLAIN authentication, then we will need 
to modify the module to use a different authentication method. Picking the new 
default is convienient for now, but will leave us in a lurch when they change 
the default again. I'm surprised at how limited their authentication options 
are.

Rainer, is this something the core team can tackle? or is the ommongodb module 
contributed and you need assistance from outside to make this sort of 
modifcation to it?

David Lang

**Comment by rgerhards** [comment]
> Rainer, is this something the core team can tackle? or is the ommongodb module
> contributed and you need assistance from outside to make this sort of
> modifcation to it?

Well... it's in the ./plugins tree, so in theory we can check and fix. But my mongo know-how is pretty weak and rusted (nothing done for a couple of years). So it's not very tempting for me to try to fix this, as it probably requires quite a bit of reading and learning again. @HugoSoszynski would you be willing to have a look?

**Comment by rgerhards** [comment]
oh, wait, I see the string "PLAIN" inside the plugin: https://github.com/rsyslog/rsyslog/blob/master/plugins/ommongodb/ommongodb.c#L677

I can patch it. Would someone willing to test that?

**Comment by mmonson** [comment]
I’m no longer set up to build rsyslog, but if someone can send me the omongodb.so plugin I’ll test it…

**Comment by jjourdin** [comment]
In fact there is no need to hardcode "?authMechanism=PLAIN" in ommongo.c as it appears mongo will use the default one: SCRAM-SHA-1 (Tested with SCRAM-SHA-1 on v8.34.0 on mongoDB 3.4.).

Moreover one can choose the appropriate authentication mechanism by providing ?authMechanism=whatever in the uristr.
