### ISSUE TITLE
rsyslog-gnutls: TLS server does not send intermediate certificates, breaking verification

### ISSUE THREAD

**Issue by mbiebl** [rsyslog/rsyslog#2762]
Version: 8.24.0-1

This was filed downstream as https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=887637.

I'm not the original bug submitter but I'm merely forward the issue.

The setup consists of a TLS-enabled rsyslog server and TLS-enbled rsyslog clients without using client certificate authentication.

When DefaultNetstreamDriverCertFile on the server specifies a file with a single cert (which is signed by a top level cert available to the clients),
clients can connect.

When DefaultNetstreamDriverCertFile on the server specifies a file with a cert followed by an intermediate cert (which is signed by a top level cert available to the clients),
clients fail to connect.

Using "openssl s_client" reveals that only the server cert is sent, not the intermediate cert, and thus clients will fail
server cert verification since the intermediate certificate is not available.

The relevant code is in runtime/nsd_gtls.c. Interestingly enough there are two separate functions that read the certificate:

gtlsAddOurCert() uses gnutls_certificate_set_x509_key_file(), which will handle intermediate certs correctly.

gtlsLoadOurCertKey() uses gnutls_x509_crt_import() on the file data, and this function only handles one cert.

The later function seems meant to be used in clients to read the client certificate when using client authentication,
but is also called in gtlsInitSession(). If one changes gtlsInitSession() to read
#if HAVE_GNUTLS_CERTIFICATE_SET_RETRIEVE_FUNCTION && 0
thus disabling the call to gtlsLoadOurCertKey(),
the server will present the intermediate cert and clients will be able to connect.

**Comment by rgerhards** [comment]
@alorbach is this supported by the new openssl driver as well? Do we have a test for it? It may be good to check if the openssl driver works with Let's Encrypt.

**Comment by rgerhards** [comment]
thx @mbiebl for forwardig this!
