### ISSUE TITLE
add support for ip based bind for imtcp (instead 0.0.0.0)

### ISSUE THREAD

**Issue by crackytsi** [rsyslog/rsyslog#277]
Hi,
Please add a config-option (same as imptcp) also to define where to bind the listener socket. 
(Specific address instead of all sockets 0.0.0.0).

imptcp option is:
   address <name>
    Default: all interfaces
    On multi-homed machines, specifies to which local address the listerner should be bound.

Thanks
Chris

**Comment by crackytsi** [comment]
diff -u rsyslog-8.8.0/tcpsrv.c rsyslog-8.8.0-addr/tcpsrv.c
--- rsyslog-8.8.0/tcpsrv.c      2015-02-24 13:05:43.000000000 +0100
+++ rsyslog-8.8.0-addr/tcpsrv.c 2015-03-23 17:53:21.606276899 +0100
@@ -123,7 +123,7 @@
  * rgerhards, 2009-05-21
  */
 static inline rsRetVal
-addNewLstnPort(tcpsrv_t *pThis, uchar *pszPort, int bSuppOctetFram)
+addNewLstnPort(tcpsrv_t *pThis, uchar *pszPort, int bSuppOctetFram, uchar *pszAddr)
 {
        tcpLstnPortList_t *pEntry;
        uchar statname[64];
@@ -134,6 +134,11 @@
        /* create entry */
        CHKmalloc(pEntry = MALLOC(sizeof(tcpLstnPortList_t)));
        CHKmalloc(pEntry->pszPort = ustrdup(pszPort));
+
+       pEntry->pszAddr = NULL; // Initalize address to null
+       /* only if a bind adress is defined copy it in struct */
+       if (pszAddr != NULL) CHKmalloc(pEntry->pszAddr = ustrdup(pszAddr));
+
        strcpy((char*)pEntry->dfltTZ, (char*)pThis->dfltTZ);
        pEntry->bSPFramingFix = pThis->bSPFramingFix;
        pEntry->pSrv = pThis;
@@ -167,29 +172,30 @@
        RETiRet;
 }

-
 /* configure TCP listener settings.
  * Note: pszPort is handed over to us - the caller MUST NOT free it!
  * rgerhards, 2008-03-20
  */
 static rsRetVal
-configureTCPListen(tcpsrv_t *pThis, uchar *pszPort, int bSuppOctetFram)
+configureTCPListen(tcpsrv_t *pThis, uchar *pszPort, int bSuppOctetFram, uchar *pszAddr)
 {
        int i;
        uchar *pPort = pszPort;
+       uchar *pAddr = pszAddr;
        DEFiRet;
-
+
        assert(pszPort != NULL);
        ISOBJ_TYPE_assert(pThis, tcpsrv);
-
+
        /* extract port */
        i = 0;
        while(isdigit((int) *pPort)) {
                i = i * 10 + *pPort++ - '0';
        }
+       printf("%s %s",pszAddr, pszPort);

        if(i >= 0 && i <= 65535) {
-               CHKiRet(addNewLstnPort(pThis, pszPort, bSuppOctetFram));
+               CHKiRet(addNewLstnPort(pThis, pszPort, bSuppOctetFram, pszAddr));
        } else {
                errmsg.LogError(0, NO_ERRCODE, "Invalid TCP listen port %s - ignored.\n", pszPort);
        }
@@ -348,6 +354,7 @@
 {
        DEFiRet;
        uchar *TCPLstnPort;
+       uchar *TCPLstnAddr;

        ISOBJ_TYPE_assert(pThis, tcpsrv);
        assert(pPortEntry != NULL);
@@ -363,8 +370,8 @@
        else
                TCPLstnPort = pPortEntry->pszPort;

-       /* TODO: add capability to specify local listen address! */
-       CHKiRet(netstrm.LstnInit(pThis->pNS, (void*)pPortEntry, addTcpLstn, TCPLstnPort, NULL, pThis->iSessMax));
+       // pPortEntry->pszAddr = NULL ==> bind to all interfaces
+       CHKiRet(netstrm.LstnInit(pThis->pNS, (void*)pPortEntry, addTcpLstn, TCPLstnPort, pPortEntry->pszAddr, pThis->iSessMax));

 finalize_it:
        RETiRet;
@@ -382,14 +389,14 @@
        ISOBJ_TYPE_assert(pThis, tcpsrv);

        /* init all configured ports */
-       pEntry = pThis->pLstnPorts;
-       while(pEntry != NULL) {
-               localRet = initTCPListener(pThis, pEntry);
-               if(localRet != RS_RET_OK) {
-                       errmsg.LogError(0, localRet, "Could not create tcp listener, ignoring port %s.", pEntry->pszPort);
-               }
-               pEntry = pEntry->pNext;
-       }
+        pEntry = pThis->pLstnPorts;
+        while(pEntry != NULL) {
+                 localRet = initTCPListener(pThis, pEntry);
+                 if(localRet != RS_RET_OK) {
+                         errmsg.LogError(0, localRet, "Could not create tcp listener, ignoring port %s address %s.", pEntry->pszPort, pEntry->pszAddr);
+                 }
+                 pEntry = pEntry->pNext;
+        }

        /* OK, we had success. Now it is also time to
         * initialize our connections
diff -u rsyslog-8.8.0/tcpsrv.h rsyslog-8.8.0-addr/tcpsrv.h
--- rsyslog-8.8.0/tcpsrv.h      2015-02-24 13:05:43.000000000 +0100
+++ rsyslog-8.8.0-addr/tcpsrv.h 2015-03-23 17:54:16.394278525 +0100
@@ -37,6 +37,7 @@
 /* list of tcp listen ports */
 struct tcpLstnPortList_s {
        uchar *pszPort;                 /**< the ports the listener shall listen on */
+       uchar *pszAddr;                 /**< the ports the listener shall listen on */
        prop_t *pInputName;
        tcpsrv_t *pSrv;                 /**< pointer to higher-level server instance */
        ruleset_t *pRuleset;            /**< associated ruleset */
@@ -73,10 +74,13 @@
        int iLstnCurr;          /**< max nbr of listeners currently supported */
        netstrm_t **ppLstn;     /**< our netstream listeners */
        tcpLstnPortList_t **ppLstnPort; /**< pointer to relevant listen port description */
+       tcpLstnAddrList_t **ppLstnAddr; /**< pointer to relevant listen port description */
        int iLstnMax;           /**< max number of listeners supported */
        int iSessMax;           /**< max number of sessions supported */
        uchar dfltTZ[8];        /**< default TZ if none in timestamp; '\0' =No Default */
        tcpLstnPortList_t *pLstnPorts;  /**< head pointer for listen ports */
+       tcpLstnAddrList_t *pLstnAddr;   /**< head pointer for listen ports */

        int addtlFrameDelim;    /**< additional frame delimiter for plain TCP syslog framing (e.g. to handle NetScreen) */
        int bDisableLFDelim;    /**< if 1, standard LF frame delimiter is disabled (*very dangerous*) */
@@ -118,7 +122,7 @@
        rsRetVal (*Construct)(tcpsrv_t **ppThis);
        rsRetVal (*ConstructFinalize)(tcpsrv_t __attribute__((unused)) *pThis);
        rsRetVal (*Destruct)(tcpsrv_t **ppThis);
-       rsRetVal (*configureTCPListen)(tcpsrv_t*, uchar *pszPort, int bSuppOctetFram);
+       rsRetVal (*configureTCPListen)(tcpsrv_t*, uchar *pszPort, int bSuppOctetFram, uchar *pszAddr);
        rsRetVal (*create_tcp_socket)(tcpsrv_t *pThis);
        rsRetVal (*Run)(tcpsrv_t *pThis);
        /* set methods */

**Comment by rgerhards** [comment]
This has been done in https://github.com/rsyslog/rsyslog/pull/278 
Present in v8.9.0.
