### ISSUE TITLE
Help with getting help

### ISSUE THREAD

**Issue by DigiAngel** [rsyslog/rsyslog#2770]
Didn't want to do the github route, but here I am...I'll say this in pictures:

forum.adiscon.com:
![2018-06-12 08_50_35-temporarily offline for gdpr reasons](https://user-images.githubusercontent.com/947191/41298022-b9d0aabe-6e1d-11e8-9eae-210734700610.png)

http://lists.adiscon.net/mailman/listinfo/rsyslog:
![2018-06-12 08_51_10-503 service unavailable](https://user-images.githubusercontent.com/947191/41298045-c801e3d2-6e1d-11e8-84d6-135d0d325a92.png)

So anywhere besides github where I can fire off a question?  Thank you.

**Comment by rgerhards** [comment]
Sorry for the issues. Co-incidentally I tried to re-establish the list subscription page a couple of hours ago - it, too, was not GDPR compliant and surprisingly mailman did not support the necessary footer customization. You can access the page via https://www.adiscon.com/adiscon-mailing-lists/ 

Note that https support will be added tomorrow morning CEST. So if you are concerned, you may want to wait another day.

**Comment by rgerhards** [comment]
oh, and I forgot to mention that the forum will be permanently closed as it does not support user data export and removal functionality required by GDPR.

**Comment by DigiAngel** [comment]
Perfect...thanks Rainer..always appreciate your hard work and responsiveness.

**Comment by rgerhards** [comment]
thx for the nice words!
