### ISSUE TITLE
Issue with failover and new Action syntaxe

### ISSUE THREAD

**Issue by DnDDD** [rsyslog/rsyslog#2771]
### Expected behavior
I wanted to test the hability of server failover inside rsyslog to send log to remote a remote server and a backup server in case the central one is failing.

So I visited the page https://www.rsyslog.com/doc/master/tutorials/failover_syslog_server.html to have an exemple on how to do it.

But I'am used to the new Action syntax so instead of 
`local3.* @@server.domain.com:port`

I used
`local3.* Action(type="omfwd" protocol="tcp" target="server.domain.com" port="514")`

With this syntax my configuration looked like
```
*.* Action(type="omfwd" protocol="tcp" target="server1.domain.com" port="514")
$ActionExecOnlyWhenPreviousIsSuspended on
& Action(type="omfwd" protocol="tcp" target="server2.domain.com" port="514")
& /var/log/localbuffer
$ActionExecOnlyWhenPreviousIsSuspended off

```
I checked the configuration with **rsyslogd -N1** and everything seems good

### Actual behavior
With the new **Action** syntax the events are send to both servers

### Steps to reproduce the behavior
Use the following failover configuration 

```
*.* Action(type="omfwd" protocol="tcp" target="server1.domain.com" port="514")
$ActionExecOnlyWhenPreviousIsSuspended on
& Action(type="omfwd" protocol="tcp" target="server2.domain.com" port="514")
& /var/log/localbuffer
$ActionExecOnlyWhenPreviousIsSuspended off

```

I also was able to reproduce with the action syntax for the failover node only

```
*.* @@server1.domain.com:514
$ActionExecOnlyWhenPreviousIsSuspended on
& Action(type="omfwd" protocol="tcp" target="server2.domain.com" port="514")
& /var/log/localbuffer
$ActionExecOnlyWhenPreviousIsSuspended off

```

### Environment
- rsyslog version: 8.24.0
- platform: Debian 9 stretch

There is not special things in my configuratin.
I was able to reproduce it with and without tls enable.

**Comment by rgerhards** [comment]
You cannot mix old and new style in this way. The action object needs to have all parameters in new style. Doc is here:

https://www.rsyslog.com/doc/master/configuration/actions.html

And sorry for the outdated guide. I have asked @PascalWithopf to update it. Hope he'll be able to tomorrow.

**Comment by davidelang** [comment]
On Tue, 12 Jun 2018, DnDDD wrote:

> $ActionExecOnlyWhenPreviousIsSuspended on
> & Action(type="omfwd" protocol="tcp" target="server2.domain.com" port="514")

This is mixing old and new syntax, you can't do that. When you use action() 
anything set via the old multi-line syntax is ignored.

**Comment by DnDDD** [comment]
Ok, thanks for the information, the following configuration work as expected

`
local3.* Action (type="omfwd" Target="server1.domain.com" Port="514" Protocol="tcp")
Action (type="omfwd" Target="server2.domain.com" Port="514" Protocol="tcp"  action.execOnlyWhenPreviousIsSuspended="on")
`
