### ISSUE TITLE
rsyslog rotate failed on Ubuntu 16.04

### ISSUE THREAD

**Issue by waster** [rsyslog/rsyslog#2780]
### Expected behavior
log files are rotated
### Actual behavior
`invoke-rc.d rsyslog rotate` failed
### Steps to reproduce the behavior
`invoke-rc.d rsyslog rotate`
### Environment
- rsyslog version: 8.35.0-0adiscon2xenial1 installed from adiscon ppa 
- platform: Ubuntu 16.04

I guess these problem is related to non-existent pid file as systemd runs syslog with '-iNONE'. So rotate action can't be done and logrotate tasks are also failed (https://github.com/rsyslog/rsyslog/issues/2143)
 
How logrotate can be fixed then? The same `invoke-rc.d rsyslog rotate` command works fine with 8.32.0 with pid file.

**Comment by rgerhards** [comment]
@friedl can you pls comment

**Comment by friedl** [comment]
@waster We have just published a new revision of the packages. The new ones are now creating the pid file again on service startup. This should also solve the logrotate issue.

**Comment by norpol** [comment]
Related commit in [rsyslog-pkg-ubuntu](https://github.com/rsyslog/rsyslog-pkg-ubuntu/commit/0492acfe50836bbf1d26201b9423149a738f63c2).

@friedl Do you think the rsyslog-pkg-debian also needs a fix? Why does the change is so much smaller in the [rpm build repo](https://github.com/rsyslog/rsyslog-pkg-rhel-centos/commit/f04f7a17ebef28a8e0675347ed19d9888fc5469f)? Is this patch going to be merged back into the rsyslog 8.36 release? Right now this didn't got fixed on [rsyslog master](https://github.com/rsyslog/rsyslog/blob/32a4f35d26f61bbf1504b1f16d46e2af14d95f57/rsyslog.service.in).

**Comment by friedl** [comment]
Since we do not provide current packages for Debian, there is no intent to port the patch over to rsyslog-pkg-debian.

Also, this patch will stay for now in the packaging projects and will not be merged into rsyslog master.

**Comment by norpol** [comment]
Hi, thank you for your fast response.
Shall I create a new ticket for fixing this in rsyslog master itself then?
I'm building from the source tarball and the official `.service` file was fine until 8.32 for us too.

**Comment by norpol** [comment]
Just if someone else is building from source, here is my adopted patch-file from @friedl...

```sh
git clone https://github.com/rsyslog/rsyslog/
cd rsyslog
patch -p1 < rsyslog-service.patch
# alternative:
# git am < rsyslog-service.patch # requires git config to have user and mail set
```
```rsyslog-service.patch
diff --git a/rsyslog.service.in b/rsyslog.service.in
--- a/rsyslog.service.in
+++ b/rsyslog.service.in
@@ -6,7 +6,7 @@ 

 [Service]
 Type=notify
-ExecStart=@sbindir@/rsyslogd -n -iNONE
+ExecStart=@sbindir@/rsyslogd -n -i/var/run/rsyslogd.pid
 StandardOutput=null
```
