### ISSUE TITLE
ommail documentation examples incorrect

### ISSUE THREAD

**Issue by hmoffatt** [rsyslog/rsyslog#2789]
### Expected behavior
rsyslog should sent emails with a body following the specified template, when using the example configuration in the documentation: https://www.rsyslog.com/doc/v8-stable/configuration/modules/ommail.html

### Actual behavior
email body is blank.

### Steps to reproduce the behavior
Use the example configuration, log a matching message.

It appears that you need to explicitly set the body template using template="mailBody" on the action clause to make this work.

### Environment
- rsyslog version: 8.34.0
- platform: debian stretch

**Comment by PascalWithopf** [comment]
The default for the parameter enable.body was wrong, so the body was disabled.

You will need to set ```enable.body="on"``` or wait for my pull request to be merged.
