### ISSUE TITLE
Mutex contention in omrabbitmq when using multiple actions/connections

### ISSUE THREAD

**Issue by micoq** [rsyslog/rsyslog#2790]
Currently, all `omrabbitmq` workers share a [single mutex](https://github.com/rsyslog/rsyslog/blob/9411a6e5b6ed9a84438b3f6432a341c0b88c98f4/contrib/omrabbitmq/omrabbitmq.c#L58)

librabbitmq-c doesn't allow multiple threads [to access to the same connection](https://github.com/alanxz/rabbitmq-c) (apparently not even with multiple channels)

However, we could use multiples AMQP connections to distribute the load but the global mutex allow only one connection at a time to send an AMQP message.

I propose to move the pthread mutex in `instanceData` to create one mutex per action like this:
```
typedef struct _instanceData {
    ....
    mutDoAct;
    ...
}

BEGINcreateInstance
CODESTARTcreateInstance
    pthread_mutex_init(&pData->mutDoAct, NULL);
ENDcreateInstance

/* Just replace the mutex references in lock/unlock */
pthread_mutex_lock(&pData->mutDoAct);
pthread_mutex_unlock(&pData->mutDoAct);

BEGINfreeInstance
CODESTARTfreeInstance
    ...
    pthread_mutex_destroy(&pData->mutDoAct);
    ...
ENDfreeInstance
```

With this patch we can achieve 100k messages per second by using 8 concurrent connections to RabbitMQ instances.

Without it, the throughput is capped to 32k regardless of the number of connections (a single connection is limited by the exchange thread on RabbitMQ but with 2 connections or more, it's the mutex which limits the speed).

Rsyslog version: 8.35.0 and older
Librabbitmq: 0.8

**Comment by rgerhards** [comment]
omrabittmq is a contributed module - the core defs do not have insight into it. As such, we would even more appreciate if you could craft a PR against it.

**Comment by rgerhards** [comment]
implemented via https://github.com/rsyslog/rsyslog/pull/2795
