### ISSUE TITLE
omrelp misleading error message

### ISSUE THREAD

**Issue by JustinAzoff** [rsyslog/rsyslog#2793]
### Expected behavior

omrelp error messages should mention the correct error and underlying cause

### Actual behavior

omrelp[xx:1514]: error 'error connecting', object  'conn to srvr xxx:1514' - action may not work as intended [v8.35.0 try http://www.rsyslog.com/e/2353 ]

### Steps to reproduce the behavior

Configure omrelp with a destination that is unreachable for some reason.

### Environment

8.35.0 on centos 7.5

It looks like there are two causes to this issue.  The first is from this code block in omrelp.c:

```
static void
onErr(void *pUsr, char *objinfo, char* errmesg, __attribute__((unused)) relpRetVal errcode)
{
	wrkrInstanceData_t *pWrkrData = (wrkrInstanceData_t*) pUsr;
	errmsg.LogError(0, RS_RET_RELP_AUTH_FAIL, "omrelp[%s:%s]: error '%s', object "
			" '%s' - action may not work as intended",
			pWrkrData->pData->target, pWrkrData->pData->port, errmesg, objinfo);
}

```

I think the RS_RET_RELP_AUTH_FAIL was a copy/paste from onAuthErr and is not correct for this function.  I believe it should be just RS_RET_RELP_ERR, but I am not 100% sure.

The other issue is inside librelp that contributes to this.  One of the code paths in librelp that triggers onErr is:

```
	if(connect(pThis->sock, res->ai_addr, res->ai_addrlen) == -1) {
		if(errno != EINPROGRESS) {
			callOnErr(pThis, "error connecting", RELP_RET_IO_ERR);
			ABORT_FINALIZE(RELP_RET_IO_ERR);
		}
	}
```

I think this could be improved by doing

```
callOnErr(pThis, "error connecting: %s", strerror(errno), RELP_RET_IO_ERR);
```

In our particular instance connect was returning EACCESS due to selinux that we found out by stracing rsyslog, but the error could also be connection refused, no route to host, etc, and it would be useful to know what the underlying error is.

I can file this as a separate issue on librelp if you want.

**Comment by rgerhards** [comment]
> I can file this as a separate issue on librelp if you want.

that would be useful, thx!

**Comment by rgerhards** [comment]
fixed via above-mentioned pr (in librelp)

**Comment by JustinAzoff** [comment]
Was there also the issue with how onErr is using RS_RET_RELP_AUTH_FAIL?

> I think the RS_RET_RELP_AUTH_FAIL was a copy/paste from onAuthErr and is not correct for this function. I believe it should be just RS_RET_RELP_ERR, but I am not 100% sure.
