### ISSUE TITLE
omprog: Add ability to run program as another user

### ISSUE THREAD

**Issue by Ralnoc** [rsyslog/rsyslog#28]
The idea would be to add the ability to declare a 'runAsUser' option for the omprog module. This would allow you to run the specified program as they required user. 

This is extremely useful for things like scripts that interact with hdfs where the user needs to be a specific user that has permissions on the hdfs filesystem.

And example of it in action would be something like:

```
*.*      action(type="omprog"
                binary="/path/to/binary --param1 lala --param2 dada"
                template="hadoopTemplate"
                runAsUser="hdfs")
```

**Comment by eedelk** [comment]
This is exactly what we need right now. Any plans to get it implemented?
Or is it possible to achieve the same with some kind of workaround?

**Comment by jreedcode** [comment]
Great idea! We also have a need for this enhancement.

**Comment by catalinciurea** [comment]
+1 from me.

**Comment by rgerhards** [comment]
@jsiwrk interested?

**Comment by jsiwrk** [comment]
In principle it can be done by wrapping the program within a shell script. The script invokes the program with `su user -c "program"`, and in the omprog configuration one must refer to the script. So a new setting doesn't seem necessary (?).

**Comment by rgerhards** [comment]
Makes a lot of sense.
