### ISSUE TITLE
possible NULL dereference

### ISSUE THREAD

**Issue by jvymazal** [rsyslog/rsyslog#2804]
https://github.com/rsyslog/rsyslog/blob/55b3e4e5e2fae7fb21f95acbf2afb5a1d2b7db88/contrib/mmkubernetes/mmkubernetes.c#L740

Unless I overlooked something in case of fopen() failure we are closing NULL pointer. 
@richm can you please verify?

**Comment by richm** [comment]
This is a valid bug.
