### ISSUE TITLE
omprog: 'forceSingleInstance' flag not working as intended

### ISSUE THREAD

**Issue by jsiwrk** [rsyslog/rsyslog#2813]
The intended purpose of the `forceSingleInstance` flag was to force omprog to start only one instance (process) of the external program. However, all this flag does is serializing the execution of `doAction` between the worker instances (i.e. preventing two worker threads from concurrently executing `doAction`).

See [this conversation](https://github.com/rsyslog/rsyslog/issues/473#issuecomment-392350337) for more details:

@rgerhards said:
> The original intent of forceSingleInstance was (and is) to support program that cannot run in multiple instances. For example, SEC (IIRC), needs to have all data fed to a single instance, else it cannot correlate the data as expected. So it looks like this is a bug, and a bug we should fix.

@jsiwrk said:
> (...) it seems that this feature can be achieved by simply restricting the number of workers to 1 (?).

@rgerhards said:
> Yes, that's right, but other actions on the same queue may want to have more than one worker. So omprog would force everything to one worker without that option.

**Comment by jsiwrk** [comment]
@rgerhards : OK, I think I now understand the use case. To clarify: the situation of having one queue with multiple actions can only happen for the main queue, right? (when no action queues are used).

Implementing the `forceSingleInstance` flag correctly doesn't seem trivial: omprog will need to keep the housekeeping data of the child process (pid, fd's, etc.) in two possible places: in the action data (when the flag is enabled) and in the worker data (when the flag is disabled). Currently, they are kept in the worker data. An important refactoring is required, it seems.

Just to make sure: wouldn't be easier to solve this use case by simply recommending the use of a dedicated single-worker queue for the omprog action? I suppose a simple in-memory queue could do the job with minimum overhead.

Put it in another way: instead of trying to synchronize multiple workers inside the omprog action (with the complexity that this implies), why not let the rsyslog core do this synchronization using a dedicated queue (which is an existing and well-tested mechanism)?

Sorry for my insistence, but I want to make sure that the effort of refactoring omprog to support this flag will be worthwhile. (Also, it seems that very few people are using it: I'm not sure the flag has ever worked... at least it is not working since various releases ago.)

**Comment by rgerhards** [comment]
> @rgerhards : OK, I think I now understand the use case. To clarify: the situation of having one queue with multiple actions can only happen for the main queue, right? (when no action queues are used).

No, it can always happen if a queue is defined at a ruleset-basis (what actually is the case with the main queue and the default rule base). I'd say that's a pretty common scenario for more complex setups.

> Implementing the forceSingleInstance flag correctly doesn't seem trivial: omprog will need to keep the housekeeping data of the child process (pid, fd's, etc.) in two possible places: in the action data (when the flag is enabled) and in the worker data (when the flag is disabled). Currently, they are kept in the worker data. An important refactoring is required, it seems.

I don't remember how it was initially. But how about this: if the flag is enabled, always use worker 0 instance? That still might require an additional data structure. But wait until my final comments below!

> Just to make sure: wouldn't be easier to solve this use case by simply recommending the use of a dedicated single-worker queue for the omprog action? I suppose a simple in-memory queue could do the job with minimum overhead.

Sounds like that thing of config that folks dislike about rsyslog ("too complex"). But there is also one case I forgot to mention in my initial mail. A DA queue will *always* have two workers as soon as it went to disk, that is the mem queue worker and the disk queue worker. So that doesn't solve the issue.

> Put it in another way: instead of trying to synchronize multiple workers inside the omprog action (with the complexity that this implies), why not let the rsyslog core do this synchronization using a dedicated queue (which is an existing and well-tested mechanism)?

Doing it in the core is tricky. We could add a flag "forceSingleInstance" to the action, that may even be useful. But again, in the case of DA queues it will not work, because we are talking about one action on two different queues (mem, disk). Let me think a bit more if we could handle that in the action context - possibly we can (a too-vague "idea" to express now - actually I myself am not clear what exactly I mean ;-) - you know one of these things that requiere good sleep, a bit of jogging and maybe a shower to become "enlightened"...).

> Sorry for my insistence, but I want to make sure that the effort of refactoring omprog to support this flag will be worthwhile. 

> (Also, it seems that very few people are using it: I'm not sure the flag has ever worked... at least it is not working since various releases ago.)

It worked, because I know that we introduced it for SEC. Otherwise, I tend to agree, but want to caution that the newest release in widespread use seems to be 8.24, due to distros not updating timely. That's RHEL 7, other distros are way more behind. So we did not get the full picture yet.

@davidelang do you have an opinion on that?

**Comment by davidelang** [comment]
On Tue, 3 Jul 2018, Rainer Gerhards wrote:

> @davidelang do you have an opinion on that?

this is a bad week to ask me, I've got a fireworks show to get together and 
launch in the next 40 hours or so, so it takes priority.

we do need some way to do this.

SEC is one instance, writing to a compressed file is another instance (which may 
have it's own work-around, but if so, that's just an example of having specific 
solutions for what's really a generic problem)

As a thought experiment, can we make a ruleset that has a single worker 
and put the action in it, and have that ruleset called from multiple places 
without having any problems?

If so, we have the implementation figured out, now we would just need to make 
a reasonable config option to hide the ugly complexity from the user (or come up 
with a cleaner implementation)

Back at the end of the week to be able to pay attention to such things.

David Lang

**Comment by rgerhards** [comment]
> this is a bad week to ask me, I've got a fireworks show to get together and
> launch in the next 40 hours or so, so it takes priority.

definitely! Appreciate the time you have taken, but I think you have now more important things to do ;- The rest of the comments for later, as far as you are concerned!

> SEC is one instance, writing to a compressed file is another instance (which may
> have it's own work-around, but if so, that's just an example of having specific
> solutions for what's really a generic problem)

that's a different thing, as the compression can go on in parallel (and actually gains a lot here), just the final write needs to be synchronized (and I think it is).


> As a thought experiment, can we make a ruleset that has a single worker
> and put the action in it, and have that ruleset called from multiple places
> without having any problems?

We can do, but than we must forbid DA queues. It must be either pure disk or pure in-memory queues than. Not sure if that would really be a viable solution...

**Comment by jsiwrk** [comment]
OK, understood and agreed this flag is useful. The case of the DA queue is a good reason.

After reviewing again the [original code](https://github.com/rsyslog/rsyslog/blob/f75395172eac1dfcc63c06ec050739b952eb5cb8/plugins/omprog/omprog.c#L331-L339), I'm pretty sure the flag has never worked: a lock is performed in `doAction` on the instance data, but the `bIsRunning` flag (and the rest of the child process state) is kept in the worker data (`pWrkrData`). Hence, if more than one worker is in effect, nothing prevents other workers to start its own child process. I.e. the lock is useless.

I would say that, if it worked, it was because the action was in its own queue, and the queue was not disk-assisted. This guarantees that only one worker exists. (And the value of the flag is irrelevant in this situation.)

In the short term, I will submit a PR to correct the documentation, since in my [recent revision](https://github.com/rsyslog/rsyslog-doc/pull/678) I documented the flag as deprecated (the reason was that apparently it had never worked, and I couldn't find a valid use case for it). Now that it is clear that the flag is useful, I will document its intended purpose, explain that it is currently not working, and the workaround (use a dedicated non-DA queue for the action). OK?

Later, in the medium term, I can try to find time to correct the bug in omprog (now that the use case is clear, I think I'm motivated enough to attempt the refactoring ;-)

Unless you come up with a more general solution first... But I imagine this would be more long term?

**Comment by rgerhards** [comment]
> After reviewing again the original code, I'm pretty sure the flag has never worked: a lock is performed in doAction on the instance data, but the bIsRunning flag (and the rest of the child process state) is kept in the worker data (pWrkrData). Hence, if more than one worker is in effect, nothing prevents another worker to start its own child process. I.e. the lock is useless.

I think I broke it in this commit: https://github.com/rsyslog/rsyslog/commit/0453b1670fc34c96d31ee7c9a370f0f5ec24744a#diff-e3cb3014ecfd8b9782b9274c6a7fa343

v7.6.7 (the latest v7) had the working code. So I broke it roughly 3.5 yrs ago after it worked for a couple of yrs :-(

Ack to your other notes!

**Comment by rgerhards** [comment]
@jsiwrk I think you solved this, right? So we could close.

**Comment by jsiwrk** [comment]
No, it isn't solved yet. It's the next item in my (personal) contribution todo (after updating the documentation to add the new settings I have added in my recent PRs). However I cannot provide an estimate on when it will be done, will depend on my short-term availability...
