### ISSUE TITLE
Need urgent help: want to specify date in inputfilename in rsyslog.conf

### ISSUE THREAD

**Issue by bansal2219** [rsyslog/rsyslog#2815]
### Expected behavior
actually i have logs generated in /data1/syslog/ip-2018-07-03.log like this, with current date and after that it will be archived, so my requirement is to give date in inputfilename in below code, can anyone help me in this.

$ModLoad imfile
$InputFileName /data1/syslog/10.112.254.199-2018-07-03.log
$InputFileTag tag_app_log
$InputFileStateFile app_log1
$InputFileFacility local7
$InputRunFileMonitor

if $syslogtag == 'tag_app_log' then @10.111.42.82:514

### Actual behavior
please help me
### Environment
- rsyslog version: 
- platform: 
- for configuration questions/issues, include rsyslog.conf and included config files

**Comment by rgerhards** [comment]
have a look here:

* https://www.slideshare.net/rainergerhards1/using-wildcards-with-rsyslogs-file-monitor-imfile
* https://www.rsyslog.com/doc/master/configuration/modules/imfile.html
