### ISSUE TITLE
extracting message parts by "fields"

### ISSUE THREAD

**Issue by esazarain** [rsyslog/rsyslog#2817]
### Environment
- rsyslog version: 
- platform: 
- for configuration questions/issues, include rsyslog.conf and included config files

Hi
I'm Elham. I am going to create a log manager with rsyslog and elasticsearch.  I used of omelasticsearch module then defined a template for fetching IP from message.
In my template, message string was seprated base on space deliminator and the fieldnumber. The 6th field is my IP. the problem that i faced is that when date changed from "Jun 30 2018" to "Jul  1 2018", the sixth field changed to 7th field. you know i have 2 space in "Jul  1 2018" and it failed my result. I used of compressspace property but it didnt work.
please help me becouse im in force situation.

Thanks alot

**Comment by rgerhards** [comment]
pls post your config and a sample message

**Comment by esazarain** [comment]
Thanks.
This is my template in /etc/rsyslig.d/ap.conf

constant(value="\",\"ip_sender\":\"")    property(name="msg" compressspace="on" field.delimiter="32" field.number="6" format="json")



This is my first message:"Jul  4 17:02:25 wbl03 app3: "172.30.60.25" ..." 

This is my second message:"Jul 14 17:02:25 wbl03 app3: "172.30.60.25" ..." 

At first message "ip_sender" is "app3"

At second "ip_sender" is "172.30.60.25"


You know at first message i have "July  4" with 2 space begore 4 but at "july 14" i have just one space before 14

**Comment by davidelang** [comment]
please log the message with the format RSYSLOG_DebugFormat so that we can see 
what all the pased fields are.

the msg field should not have the contents that you are showing (it should start 
with ' "')

and please post the full config, not just the snippet.

David Lang
k
