### ISSUE TITLE
Question: specify "output channel" and "template" in action

### ISSUE THREAD

**Issue by CliveJL** [rsyslog/rsyslog#2852]
I am running rsyslog 8.36.0 on Ubuntu 16.04. I have some legacy config that works quite happily, but I am working on bringing it up-to-date with the newer syntax; losing all the `$blah` statements.

I've had a deal of success today in migrating to a **template** that outputs properly formatted JSON (option.jsonf="on") solely using a series of `property(outname="field" name="field_value" format="jsonf")` etc. Previously this was a mashup of constants and property values including curly braces, commas etc. that sometimes got the JSON right, but very often didn't...

The last part that I would really appreciate some advice on is how to get the following legacy directive into the `action(type="foo")` format.

My config includes a working template (as mentioned above) called `json_lines` and an `$outchannel` definition as follows:

`$outchannel json_log_rotation,/opt/rsyslog/some_logfile.log,52428800,/opt/rsyslog/bin/logrotate.sh`

The legacy action is as follows:

`if $syslogtag == 'some_tag' then :omfile:$json_log_rotation;json_lines`

I'm struggling to find a working example of an **action** statement that includes the `$outchannel` name and also a template name. The legacy one works fine, but I'm on a mission to get rid of the old stuff.

Any help or advice would be appreciated! TIA

**Comment by rchapin** [comment]
@CliveJL  did you ever find a syntax example that works?  I've been scouring the Internet as well and the only way I was able to get it to work was with the legacy action as well.

**Comment by saukrs** [comment]
Now I am in the search too. My idea was that Output Channels became a legacy and thus aren't being integrated into the RainerScript parser anyway:
https://rsyslog.readthedocs.io/en/latest/configuration/output_channels.html#output-channels

> Output Channels are a new concept first introduced in rsyslog 0.9.0. **As of this writing, it is most likely that they will be replaced by something different in the future.** So if you use them, be prepared to change you configuration file syntax when you upgrade to a later release.

Ping @rgerhards.

**Comment by rgerhards** [comment]
Yes, outchannel is only available in legacy config.

**Comment by lmoellendorf** [comment]
I am new to rsyslog (and logging in general). I read some of the docs and I understood that there are 3 [Configuration Formats](https://www.rsyslog.com/doc/configuration/conf_formats.html):

- basic
- advanced
- obsolete legacy

Obsolete legacy is used for [Log rotation with rsyslog](https://www.rsyslog.com/doc/tutorials/log_rotation_fix_size.html#log-rotation-with-rsyslog) and a [new style equivalent of $outchannel is missing](https://github.com/rsyslog/rsyslog/issues/2479).

I read that all three configuration formats can be mixed. My distribution uses a mixture between obsolete legacy and basic format as default configuration. Log files are defined using basic format. 

I do not understand how I can keep those files and extend my configuration with outchannels in order to do log rotation based on file size.

This from  [Log rotation with rsyslog](https://www.rsyslog.com/doc/tutorials/log_rotation_fix_size.html#log-rotation-with-rsyslog):
```
# start log rotation via outchannel
# outchannel definition
$outchannel log_rotation,/var/log/log_rotation.log, 52428800,/home/me/./log_rotation_script
#  activate the channel and log everything to it
*.* :omfile:$log_rotation
# end log rotation via outchannel
```

If I understand correctly it defines the file (i.e. channel) `/var/log/log_rotation.log` which is then activated. But what if my files are already defined using basic format? Do I have convert those definitions into obsolete legacy format?

Here is the configuration shipped with my distribution:

```
# if you experience problems, check
# http://www.rsyslog.com/troubleshoot for assistance

# rsyslog v3: load input modules
# If you do not load inputs, nothing happens!
# You may need to set the module load path if modules are not found.
#
# Ported from debian's sysklogd.conf

$ModLoad immark   # provides --MARK-- message capability
$ModLoad imuxsock # provides support for local system logging (e.g. via logger command)
$ModLoad imklog   # kernel logging (formerly provided by rklogd)

#
# Set the default permissions
#
$FileOwner root
$FileGroup adm
$FileCreateMode 0640
$DirCreateMode 0755
$Umask 0022

auth,authpriv.*                 /var/log/auth.log
*.*;auth,authpriv.none          -/var/log/syslog
cron.*                          /var/log/cron.log
daemon.*                        -/var/log/daemon.log
kern.*                          -/var/log/kern.log
lpr.*                           -/var/log/lpr.log
mail.*                          -/var/log/mail.log
user.*                          -/var/log/user.log

#
# Logging for the mail system.  Split it up so that
# it is easy to write scripts to parse these files.
#
mail.info                       -/var/log/mail.info
mail.warn                       -/var/log/mail.warn
mail.err                        /var/log/mail.err

# Logging for INN news system
#
news.crit                       /var/log/news.crit
news.err                        /var/log/news.err
news.notice                     -/var/log/news.notice

#
# Some `catch-all' logfiles.
#
*.=debug;\
        auth,authpriv.none;\
        news.none;mail.none     -/var/log/debug
*.=info;*.=notice;*.=warn;\
        auth,authpriv.none;\
        cron,daemon.none;\
        mail,news.none          -/var/log/messages

#
# Emergencies are sent to everybody logged in.
#
*.emerg                         :omusrmsg:*

# Save boot messages also to boot.log
local7.*                                                /var/log/boot.log

# Remote Logging (we use TCP for reliable delivery)
# An on-disk queue is created for this action. If the remote host is
# down, messages are spooled to disk and sent when it is up again.
#$WorkDirectory /var/spool/rsyslog # where to place spool files
#$ActionQueueFileName uniqName # unique name prefix for spool files
$ActionQueueMaxDiskSpace 10m   # 1gb space limit (use as much as possible)
#$ActionQueueSaveOnShutdown on # save messages to disk on shutdown
#$ActionQueueType LinkedList   # run asynchronously
#$ActionResumeRetryCount -1    # infinite retries if host is down
# remote host is: name/ip:port, e.g. 192.168.0.1:514, port optional
#*.* @@remote-host:514


# ######### Receiving Messages from Remote Hosts ##########
# TCP Syslog Server:
# provides TCP syslog reception and GSS-API (if compiled to support it)
#$ModLoad imtcp.so  # load module
#$InputTCPServerRun 514 # start up TCP listener at port 514

# UDP Syslog Server:
#$ModLoad imudp.so  # provides UDP syslog reception
#$UDPServerRun 514 # start a UDP syslog server at standard port 514

#
# Include all config files in /etc/rsyslog.d/
#
$IncludeConfig /etc/rsyslog.d/*.conf
```

I would have written to the community forum, but it is down: [Original site no longer available due to GDPR](http://kb.monitorware.com/rsyslog-f40.html).

**Comment by rgerhards** [comment]
> * `$ActionFileEnableSync off` ist the equivalent to the dash prepending the file path, see [omfile-specific Configuration Statements](https://www.rsyslog.com/doc/configuration/action/index.html#omfile-specific-configuration-statements)

That's the default. The dash has no function for many years now, I am always surprised that distros still carry it ;-)

On quick look, the configuration looks fine. Watch for any errors, SELinux may get into your way.

As a side note, $outchannel has a new replacement. Look at this changelog entry:

```
- 2023-01-16:
  - omfile: add action parameters "rotation.*"
    Add new action parameters
    - rotation.sizeLimit
    - rotation.sizeLimitCommand
    provide automatic output file rotation functionality feature-wise
    equivalent to legacy $outchannel. This finally permits to use
    this feature set in rscript.
```

**Comment by lmoellendorf** [comment]
> As a side note, $outchannel has a new replacement. ...

So that's it:

```diff
diff --git a/meta-oe/recipes-extended/rsyslog/rsyslog/rsyslog.conf b/meta-oe/recipes-extended/rsyslog/rsyslog/rsyslog.conf
index dbfefb759..b30069186 100644
--- a/meta-oe/recipes-extended/rsyslog/rsyslog/rsyslog.conf
+++ b/meta-oe/recipes-extended/rsyslog/rsyslog/rsyslog.conf
@@ -27,7 +27,10 @@ daemon.*                        -/var/log/daemon.log
 kern.*                          -/var/log/kern.log
 lpr.*                           -/var/log/lpr.log
 mail.*                          -/var/log/mail.log
-user.*                          -/var/log/user.log
+
+if prifilt("user.*") then {
+     action(type="omfile" file="/var/log/user.log" rotation.sizeLimit="2097152" rotation.sizeLimitCommand="/usr/sbin/logrotate /etc/logrotate.conf")
+}
 
 #
 # Logging for the mail system.  Split it up so that
```

This issue can be closed then?

**Comment by rgerhards** [comment]
> This issue can be closed then?

yupp
