### ISSUE TITLE
install.html in version 7.4.4

### ISSUE THREAD

**Issue by Silviu-Caprar** [rsyslog/rsyslog#2864]
Hi there,

In the file mentioned in the subject (https://github.com/rsyslog/rsyslog/blob/v7.4.4/doc/install.html)
there is a reference to GNU GPL version 1.2 or higher right at the bottom, after the GNU Free Documentation License, Version 1.2 reference.

Can you please specify if this actually refers to GPL version 2 or later or another license ?
There is no GPL version 1.2 or later license.

Thanks,
Silviu

**Comment by rgerhards** [comment]
The reference should be to GNU FDL 1.2. But this is dead code, so I don't think we intend to fix.

**Comment by Silviu-Caprar** [comment]
Thank you very much.
