### ISSUE TITLE
Rsyslog failed to start

### ISSUE THREAD

**Issue by jithesh9539** [rsyslog/rsyslog#2877]
Main PID: 25195 (code=exited, status=1/FAILURE)

Failed to start System Logging Service.
 Unit rsyslog.service entered failed state.
 rsyslog.service failed.
 rsyslog.service holdoff time over, scheduling restart.
 start request repeated too quickly for rsyslog.service
 Failed to start System Logging Service.
 Unit rsyslog.service entered failed state.
 rsyslog.service failed.

It would be of great help if this issue can be resolved.

**Comment by davidelang** [comment]
there isn't anything we can do without information.

what is your config for example.

**Comment by jithesh9539** [comment]
Linux version 3.10.0-514.10.2.el7.x86_64 (mockbuild@x86-ol7-builder-01) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-11)

**Comment by rgerhards** [comment]
This info is probably appropriate for reporting the issue to Red Hat, but it does not help us here. Please post:

- rsyslog.conf and all included files
- rsyslog version (run rsyslogd -v on command line)
