### ISSUE TITLE
"config directive is unsupported" message unclear

### ISSUE THREAD

**Issue by JohnLyman** [rsyslog/rsyslog#2880]
### Expected behavior
When running a config check and an unsupported config directive is encountered, the message should mention which config directive is not supported.

For example:
> rsyslogd: config directive "$OptimizeForUniprocessor" is no longer supported -- ignored

Without the actual directive name (or at least a file & line number), it's very difficult to determine what the faulty configuration is.

### Actual behavior
> rsyslogd: config directive is no longer supported -- ignored

### Steps to reproduce the behavior
```
cat "$OptimizeForUniprocessor on" > test.conf
rsyslogd -N1 -f test.conf
```
### Environment
- rsyslog version:
```
rsyslogd 8.36.0, compiled with:
        PLATFORM:                               x86_64-redhat-linux-gnu
        PLATFORM (lsb_release -d):
        FEATURE_REGEXP:                         Yes
        GSSAPI Kerberos 5 support:              Yes
        FEATURE_DEBUG (debug build, slow code): No
        32bit Atomic operations supported:      Yes
        64bit Atomic operations supported:      Yes
        memory allocator:                       system default
        Runtime Instrumentation (slow code):    No
        uuid support:                           Yes
        systemd support:                        Yes
        Number of Bits in RainerScript integers: 64
```

- platform: `CentOS Linux release 7.4.1708 (Core)`

**Comment by rgerhards** [comment]
We cannot give the name of the obsolete config param, as the obsolete config system does no provide it and we don't want to make a larger change to it (as it is... well... obsolete). However, we can use the newer error handlers, which means we can indicate file and approximate line number of where the problem occurs. I guess that should be good enough for troubleshooting that issue.
