### ISSUE TITLE
issue with loading omkafka module

### ISSUE THREAD

**Issue by zygisa** [rsyslog/rsyslog#2883]
### Expected behavior
rsyslog should start with omkafka module enabled and should be sending messages to kafka cluster provided in config file.

### Actual behavior
rsyslog errors out when starting:
``
Jul 27 10:40:50 localhost rsyslogd: could not load module '/usr/lib/rsyslog/omkafka.so', dlopen: /usr/lib/rsyslog/omkafka.so: undefined symbol: sqrt  [v8.36.0 try http://www.rsyslog.com/e/2066 ]
Jul 27 10:40:50 localhost rsyslogd: module name 'omkafka' is unknown [v8.36.0 try http://www.rsyslog.com/e/2209 ]
``

### Steps to reproduce the behavior
- Install rsyslogd from http://ppa.launchpad.net/adiscon/v8-stable/ubuntu
- copy config provided below
- restart rsyslogd

### Environment
- rsyslog version: 
``
rsyslogd 8.36.0, compiled with:
	PLATFORM:				x86_64-pc-linux-gnu
	PLATFORM (lsb_release -d):
	FEATURE_REGEXP:				Yes
	GSSAPI Kerberos 5 support:		No
	FEATURE_DEBUG (debug build, slow code):	No
	32bit Atomic operations supported:	Yes
	64bit Atomic operations supported:	Yes
	memory allocator:			system default
	Runtime Instrumentation (slow code):	No
	uuid support:				Yes
	systemd support:			Yes
	Number of Bits in RainerScript integers: 64
``

- platform:
``
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial
``
- packages installed:
``
dpkg -l | grep rsyslog
ii  rsyslog                          8.36.0-0adiscon3xenial1                    amd64        a rocket-fast system for log processing
ii  rsyslog-kafka                    8.36.0-0adiscon3xenial1                    amd64        This module implements an Apache Kafka producer, permitting rsyslog to write data to Kafka.
``

- config used:
```
cat /etc/rsyslog.d/placeholder.conf
module(load="imudp")
module(load="omkafka")

ruleset(name="placeholder") {
  action(
    type="omfile"
    file="/var/log/placeholder.log"
  )
  action(
    broker=["placeholder:9092"]
    type="omkafka"
    topic="placeholder"
    #confParam=["compression.type=lz4"]
  )
}

input(
  type="imudp"
  port="5000"
  ruleset="placeholder"
)
```

**Comment by rgerhards** [comment]
@friedl @alorbach pls have a look

**Comment by zygisa** [comment]
thanks @alorbach! Could you please let me know when was the v8.36 package built with librdkafka 0.11.5? I've done multiple rsyslog installations last week and it seems that those installations are not affected by this issue. Meanwhile, packages installed yesterday has this bug. Does the timing of librdkafka updagre matches?

**Comment by alorbach** [comment]
I believe on wednesday, so on 2018-07-25.

**Comment by zygisa** [comment]
Okay, that makes sense. Any ETA for the fixed package?

**Comment by alorbach** [comment]
No ETA needed, Rollback schon be completed for Ubuntu.

**Comment by friedl** [comment]
@zygisa Just to be sure I am right now pushing a new package version. This should fix the issue. I'll update here when this is complete.

**Comment by friedl** [comment]
@zygisa please try apt-get update && apt-get install rsyslog.

You should now be able to install rsyslog 8.36.0-0adiscon4xenial1. This should work as before again.

**Comment by rgerhards** [comment]
looks like this is solved...
