### ISSUE TITLE
Fix signal handler

### ISSUE THREAD

**Issue by elfring** [rsyslog/rsyslog#2886]
The function “dbgprintf” does not belong to the list of [async-signal-safe functions](https://wiki.sei.cmu.edu/confluence/display/c/SIG30-C.+Call+only+asynchronous-safe+functions+within+signal+handlers "Call only asynchronous-safe functions within signal handlers.").
I guess that a different program design will be needed for your function “[sigusr2Hdlr](https://github.com/rsyslog/rsyslog/blob/d0efa905e45844e99e2f5cc709d047e2bb01b663/runtime/debug.c#L1196 "Update candidate")”.

**Comment by elfring** [comment]
Do you find implementations of the functions “dbgprintf” and “dbgPrintAllDebugInfo” async-signal-safe?

**Comment by rgerhards** [comment]
tell me. If not, suggest a patch. You make the impression you follow some simple search tool without analysis. If you do real analysis, pinpoint what you found out - by source line and concrete description. That way you create weigh on you argument. After all, I don't know if you are a first-grader at programming or a vetran. It really doesn't matter if you know what you do, but you should prove.

**Comment by elfring** [comment]
>You make the impression you follow some simple search tool

This view can be appropriate.


>without analysis.

I suggest to reconsider your conclusion.

-----

* You can look around for more background information on my software contributions.
* Please take another look [at linked information](https://wiki.sei.cmu.edu/confluence/display/c/BB.+Definitions#BB.Definitions-asynchronous-safefunction "Description for asynchronous-signal safety") (from the initial bug description).

**Comment by rgerhards** [comment]
**Humans, take care**: I did some background checks on **elfring: it's highly probably a bot**. Just one reference: https://twitter.com/johnregehr/status/718832080118005760 - also a look at the user profile might be helpful and revealing.

Interestingly, it posts some valid, though not really important parts. The link to Coccinelle here may actually be pretty useful (if someone has time to check it out and integrate into CI).

@github: how about blocking it? At least bots are prohibited by your ToS.

**Comment by elfring** [comment]
Does your message contain a “copy mistake” for this issue?

-----

Do any other code reviewers and developers care any more for [asynchronous-signal safety considerations](https://stackoverflow.com/questions/8493095/what-constitutes-asynchronous-safeness "What constitutes asynchronous-safeness?") also around [this software implementation](https://github.com/rsyslog/rsyslog/blob/d0efa905e45844e99e2f5cc709d047e2bb01b663/runtime/debug.c#L1008 "Checking function properties around r_dbgprintf()")?
