### ISSUE TITLE
Instantly segfaults due to unknown issue on start/restart

### ISSUE THREAD

**Issue by ishmaelen** [rsyslog/rsyslog#2890]
I have inherited a VMWare VM running rsyslog 8.36. It continuously segfaults.

I wonder if it might be due to some config stuff - but I am not very familiar with it and testing config with -N1 gives no errors so perhaps not.

I see "general protection ip" faults as this example:

rs:action 4 que[3593] general protection ip:5634eda4db67 sp:7f6235c05b00 error:0 in rsyslogd[5634eda08000+9e000]

Any clues are appreciated! 

When I run in debug mode this is the end before crash:

....
1885.519655939:main Q:Reg/w0  : rainerscript.c:   
1885.519674250:action 4 queue[DA]:Reg/w0: queue.c: DeleteProcessedBatch: etry 2 state 3
1885.519681641:action 4 queue[DA]:Reg/w0: queue.c: DeleteProcessedBatch: etry 3 state 3
1885.519686230:action 4 queue[DA]:Reg/w0: queue.c: DeleteProcessedBatch: etry 4 state 3
1885.519693612:action 4 queue[DA]:Reg/w0: queue.c: DeleteProcessedBatch: etry 5 state 3
1885.519698155:action 4 queue[DA]:Reg/w0: queue.c: DeleteProcessedBatch: etry 6 state 3
1885.519702538:action 4 queue[DA]:Reg/w0: queue.c: DeleteProcessedBatch: etry 7 state 3
1885.519707069:action 4 queue[DA]:Reg/w0: queue.c: DeleteProcessedBatch: we deleted 8 objects and enqueued 0 objects
1885.519710624:action 4 queue[DA]:Reg/w0: queue.c: doDeleteBatch: delete batch from store, new sizes: log 339499, phys 339499
1885.519720358:action 4 queue[DA]:Reg/w0: strm 0x55920a7da550: stream.c: file 13 read 4096 bytes
1885.519769741:main Q:Reg/w0  : rainerscript.c: SET !syslog!msgid =
1885.519776885:main Q:Reg/w0  : rainerscript.c:       var 'msgid'
1885.519806655:main Q:Reg/w0  : rainerscript.c:     END SET
1885.519815915:main Q:Reg/w0  : rainerscript.c: eval expr 0x55920a7ca020, type 'V'
1885.519820681:main Q:Reg/w0  : rainerscript.c: rainerscript: (string) var 22: '-'
1885.519824344:action 4 queue[DA]:Reg/w0: strm 0x55920a7da550: stream.c: file 13 read 4096 bytes
1885.519839515:main Q:Reg/w0  : rainerscript.c: eval expr 0x55920a7ca020, return datatype 'S':0
1885.519848962:main Q:Reg/w0  : rainerscript.c:     SET !xappname =
1885.519856650:main Q:Reg/w0  : rainerscript.c:       var 'app-name'
1885.519865575:main Q:Reg/w0  : rainerscript.c:     END SET
1885.519872750:main Q:Reg/w0  : rainerscript.c: eval expr 0x55920a7ca100, type 'V'
1885.519876872:main Q:Reg/w0  : rainerscript.c: rainerscript: (string) var 20: 'YoloOlo_YAP_Server_VBAPP2_2'
1885.519880490:main Q:Reg/w0  : rainerscript.c: eval expr 0x55920a7ca100, return datatype 'S':0
1885.519885084:main Q:Reg/w0  : rainerscript.c:     IF
1885.519892442:main Q:Reg/w0  : rainerscript.c:       NOT
1885.519901444:main Q:Reg/w0  : rainerscript.c:               var '!xappname'
1885.519934973:main Q:Reg/w0  : rainerscript.c:             STARTSWITH
1885.519959985:action 4 queue[DA]:Reg/w0: obj.c: error -2031 deserializing property name, offset 32718858, step 3
1885.519969102:action 4 queue[DA]:Reg/w0: strm 0x55920a7da550: stream.c: strmRead ungetc -1, index 3608, max 4096, buf '16:6:+:2:0:
+pszTAG:1:24:YoloOlo_IMS_Log<Obj:1:msg:1:
+iProtocolVersion:2:1:0:
+iSeverity:2:1:7:
+iFacility:2:1:1:
+msgFlags:2:2:32:
+ttGenTime:2:10:1532686333:
+tRcvdAt:3:35:2:2018:7:27:12:12:13:152328:6:+:2:0:
+tTIMESTAMP:3:35:2:2018:7:27:12:12:13:152328:6:+:2:0:
+pszTAG:1:33:AMS.OpModule.ABCD.GW451_Receiver::
+pszRawMsg:1:676:<15>AMS.OpModule.ABCD.GW451_Receiver: [21   ] [(null)] DEBUG DB - 0, exec dbo.sp_Register_ABCD_Delivery_New3 @tel='123456', @referenceid='51edd1ac', @messagestate=2, @description='id:1374540204 sub:001 d', CURR: ':1:
+iProtocolVersion:2:1:0:
+iSeverity:2:1:7:
+iFacility:2:1:1:
+msgFlags:2:2:32:
+ttGenTime:2:10:1532686333:
+tRcvdAt:3:35:2:2018:7:27:12:12:13:152328:6:+:2:0:
+tTIMESTAMP:3:35:2:2018:7:27:12:12:13:152328:6:+:2:0:
+pszTAG:1:33:AMS.OpModule.SMPP.GW451_Receiver::
+pszRawMsg:1:676:<15>AMS.OpModule.SMPP.GW451_Receiver: [21   ] [(null)] DEBUG DB - 0, exec dbo.sp_Register_ABCD_Delivery_New3 @tel='123456', @referenceid='51edd1ac', @messagestate=2, @description='id:1374540204 sub:001 d'
1885.519986500:action 4 queue[DA]:Reg/w0: obj.c: error property name: 'pszTAG'
1885.519991957:action 4 queue[DA]:Reg/w0: obj.c: error var type: '1'
1885.519996745:action 4 queue[DA]:Reg/w0: obj.c: error len: '24'
1885.520039562:main Q:Reg/w0  : rainerscript.c:               string 'AMS'
1885.520062330:main Q:Reg/w0  : rainerscript.c:       Segmentation fault	

### Environment
- rsyslog version:

rsyslogd 8.36.0, compiled with:
        PLATFORM:                               x86_64-redhat-linux-gnu
        PLATFORM (lsb_release -d):
        FEATURE_REGEXP:                         Yes
        GSSAPI Kerberos 5 support:              No
        FEATURE_DEBUG (debug build, slow code): No
        32bit Atomic operations supported:      Yes
        64bit Atomic operations supported:      Yes
        memory allocator:                       system default
        Runtime Instrumentation (slow code):    No
        uuid support:                           Yes
        systemd support:                        No
        Number of Bits in RainerScript integers: 64

- platform: CentOS 6.10

Linux syslog02.vianettdom.com 2.6.32-754.2.1.el6.x86_64 #1 SMP Fri Jul 13 12:50:12 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

- config files:

syslogd.conf - https://pastebin.com/TdWsTcrZ
*.conf from /etc/rsyslog.d - https://pastebin.com/FNdVLeVB

**Comment by ishmaelen** [comment]
Was due to some data in .qi - unsure if it was corrupt but removing them sorted the issue.

**Comment by rgerhards** [comment]
> Was due to some data in .qi - unsure if it was corrupt but removing them sorted the issue.

do you happen to still have the .qi file? -- would be interesting to fix that it segfault in that case, but we need a way to reproduce.
