### ISSUE TITLE
action processing: add ability to SUSPEND an action intentionally

### ISSUE THREAD

**Issue by rgerhards** [rsyslog/rsyslog#2924]
It has been reported that some TCP receivers exists that accept syslog tcp messages at any rate, even if they do not manage to actually process them. Instead, they silently drop the message. This behavior is not configurable. All in all, it can lead to considerate message loss.

To support such use cases, we need to provide an ability to externally trigger actions suspension and resumption. One proposal is to do this via a configured file which contains the status of the action. Rsyslog shall periodically (configurable) read the file and if it contains SUSPEND suspend the action (and likewise for resume).

**Comment by selivan** [comment]
> Rsyslog shall periodically (configurable) read the file

Just an assumption. May be better to use inotify watch on that file? It's faster then periodic reading file.

**Comment by rgerhards** [comment]
> Rsyslog shall periodically (configurable) read the file
> 
> Just an assumption. May be better to use inotify watch on that file? It's faster then periodic reading file.

good idea, but inotify is

* linux-only, so we cannot use it in general
* racy, so not guaranteed to work (see man page)
