### ISSUE TITLE
imfile fails to send logs remoteafter logrotate

### ISSUE THREAD

**Issue by ladean** [rsyslog/rsyslog#2929]
### Expected behavior

Rsyslog imfine should continue to send logs to remote site after logrotate.

### Actual behavior

The inode of /var/log/syslog changes during logrotate and a new state file is not created. Logs are not send to remote site. 

### Steps to reproduce the behavior

The new state file is not created for the new inode during logrotate. However if I issue a restart the new state file is created and logs are shipped to remote site just fine. So the difference in rsyslog getting a HUP and a restart is that the state file for the inode of the new log file only gets created 
during the stop phase of the restart command.

Happens during logrotate.

### Environment
- rsyslog version: 
<pre>
rsyslogd 8.37.0, compiled with:
	PLATFORM:				x86_64-pc-linux-gnu
	PLATFORM (lsb_release -d):
	FEATURE_REGEXP:				Yes
	GSSAPI Kerberos 5 support:		No
	FEATURE_DEBUG (debug build, slow code):	No
	32bit Atomic operations supported:	Yes
	64bit Atomic operations supported:	Yes
	memory allocator:			system default
	Runtime Instrumentation (slow code):	No
	uuid support:				Yes
	systemd support:			Yes
	Number of Bits in RainerScript integers: 64
</pre>
- platform: 

ubuntu 16.04

- for configuration questions/issues, include rsyslog.conf and included config files

rsyslog.conf:
<pre>
#  /etc/rsyslog.conf	Configuration file for rsyslog.
#
#			For more information see
#			/usr/share/doc/rsyslog-doc/html/rsyslog_conf.html
#
#  Default logging rules can be found in /etc/rsyslog.d/50-default.conf

#################
#################

module(load="imuxsock") # provides support for local system logging
module(load="imklog")   # provides kernel logging support
#module(load="immark")  # provides --MARK-- message capability

# provides UDP syslog reception
#module(load="imudp")
#input(type="imudp" port="514")

# provides TCP syslog reception
#module(load="imtcp")
module(load="imfile" PollingInterval="10")
#input(type="imtcp" port="514")

# Enable non-kernel facility klog messages
#$KLogPermitNonKernelFacility on

###########################
###########################

#
# Use traditional timestamp format.
# To enable high precision timestamps, comment out the following line.
#
$ActionFileDefaultTemplate RSYSLOG_TraditionalFileFormat

# Filter duplicated messages
$RepeatedMsgReduction on

#
# Set the default permissions for all log files.
#
$FileOwner syslog
$FileGroup adm
$FileCreateMode 0640
$DirCreateMode 0755
$Umask 0022
$PrivDropToUser syslog
$PrivDropToGroup adm

#
# Where to place spool and state files
#
$WorkDirectory /var/spool/rsyslog

#
# Include all config files in /etc/rsyslog.d/
#
$IncludeConfig /etc/rsyslog.d/*.conf

$PreserveFQDN on
</pre>

remote configuration:
<pre>
$template DatadogFormat,"xxxxxxxxxxxxxxxxxxxxxxx <%pri%>%protocol-version% %timestamp:::date-rfc3339% %HOSTNAME% %app-name% - - [metas ddsource=\"syslog\"] %msg%\n"

ruleset(name="infiles") {
    action(type="omfwd" target="intake.logs.datadoghq.com" protocol="tcp" port="10514" template="DatadogFormat")
}

input(type="imfile" ruleset="infiles" Tag="syslog" File="/var/log/syslog")
input(type="imfile" ruleset="infiles" Tag="auth" File="/var/log/auth.log")
</pre>

Status:
<pre>
● rsyslog.service - System Logging Service
   Loaded: loaded (/lib/systemd/system/rsyslog.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2018-08-10 14:38:24 UTC; 3 days ago
     Docs: man:rsyslogd(8)
           http://www.rsyslog.com/doc/
 Main PID: 31313 (rsyslogd)
   CGroup: /system.slice/rsyslog.service
           └─31313 /usr/sbin/rsyslogd -n -i/var/run/rsyslogd.pid

Aug 13 12:22:20 SAPI-ccc-172.23.2.145 rsyslogd[31313]: omfwd: TCPSendBuf error -2027, destruct TCP Connection to intake.logs.datadoghq.com:10514 [v8.37.0 try http://www.rsyslog.com/e/2027 ]
Aug 13 12:22:20 SAPI-ccc-172.23.2.145 rsyslogd[31313]: action 'action-13-builtin:omfwd' suspended (module 'builtin:omfwd'), retry 0. There should be messages before this one giving the reason for suspension. [v8.37.0 try http://www.rsyslog.com/e/2007 ]
Aug 13 12:22:20 SAPI-ccc-172.23.2.145 rsyslogd[31313]: action 'action-13-builtin:omfwd' resumed (module 'builtin:omfwd') [v8.37.0 try http://www.rsyslog.com/e/2359 ]
Aug 13 12:26:18 SAPI-ccc-172.23.2.145 rsyslogd[31313]: omfwd: TCPSendBuf error -2027, destruct TCP Connection to intake.logs.datadoghq.com:10514 [v8.37.0 try http://www.rsyslog.com/e/2027 ]
Aug 13 12:26:18 SAPI-ccc-172.23.2.145 rsyslogd[31313]: action 'action-13-builtin:omfwd' suspended (module 'builtin:omfwd'), retry 0. There should be messages before this one giving the reason for suspension. [v8.37.0 try http://www.rsyslog.com/e/2007 ]
Aug 13 12:26:18 SAPI-ccc-172.23.2.145 rsyslogd[31313]: action 'action-13-builtin:omfwd' resumed (module 'builtin:omfwd') [v8.37.0 try http://www.rsyslog.com/e/2359 ]
Warning: Journal has been rotated since unit was started. Log output is incomplete or unavailable.
</pre>

Log file pre rotate (hostname removed):
<pre>
Aug 12 06:25:01  rsyslogd: imfile: internal error? inotify provided watch descriptor 6 which we could not find in our tables - ignored [v8.37.0 try http://www.rsyslog.com/e/2175 ]
Aug 12 06:25:01  rsyslogd:  [origin software="rsyslogd" swVersion="8.37.0" x-pid="31313" x-info="http://www.rsyslog.com"] rsyslogd was HUPed
Aug 12 06:25:01  rsyslogd: imfile: cannot watch object '/var/log/auth.log': Permission denied [v8.37.0 try http://www.rsyslog.com/e/2027 ]
Aug 12 06:25:01  rsyslogd: file '/var/log/auth.log': open error: Permission denied [v8.37.0 try http://www.rsyslog.com/e/2433 ]
Aug 12 06:25:01  rsyslogd:  [origin software="rsyslogd" swVersion="8.37.0" x-pid="31313" x-info="http://www.rsyslog.com"] rsyslogd was HUPed
Aug 13 06:25:02  rsyslogd: imfile: cannot watch object '/var/log/syslog': Permission denied [v8.37.0 try http://www.rsyslog.com/e/2027 ]
Aug 13 06:25:02  rsyslogd: file '/var/log/syslog': open error: Permission denied [v8.37.0 try http://www.rsyslog.com/e/2433 ]</pre>

Log file post rotate (hostname removed):
<pre>
Aug 13 06:25:02  rsyslogd:  [origin software="rsyslogd" swVersion="8.37.0" x-pid="31313" x-info="http://www.rsyslog.com"] rsyslogd was HUPed
Aug 13 12:22:20  rsyslogd: omfwd: TCPSendBuf error -2027, destruct TCP Connection to intake.logs.datadoghq.com:10514 [v8.37.0 try http://www.rsyslog.com/e/2027 ]
Aug 13 12:22:20  rsyslogd: action 'action-13-builtin:omfwd' suspended (module 'builtin:omfwd'), retry 0. There should be messages before this one giving the reason for suspension. [v8.37.0 try http://www.rsyslog.com/e/2007 ]
Aug 13 12:22:20  rsyslogd: action 'action-13-builtin:omfwd' resumed (module 'builtin:omfwd') [v8.37.0 try http://www.rsyslog.com/e/2359 ]
Aug 13 12:26:18  rsyslogd: omfwd: TCPSendBuf error -2027, destruct TCP Connection to intake.logs.datadoghq.com:10514 [v8.37.0 try http://www.rsyslog.com/e/2027 ]
Aug 13 12:26:18  rsyslogd: action 'action-13-builtin:omfwd' suspended (module 'builtin:omfwd'), retry 0. There should be messages before this one giving the reason for suspension. [v8.37.0 try http://www.rsyslog.com/e/2007 ]
Aug 13 12:26:18  rsyslogd: action 'action-13-builtin:omfwd' resumed (module 'builtin:omfwd') [v8.37.0 try http://www.rsyslog.com/e/2359 ]
</pre>

inode of logs after file rotate:

<pre>
131406 -rw-r----- 1 syslog root 4003372 Aug 13 15:55 syslog
132095 -rw-r----- 1 syslog root 117372 Aug 13 15:55 auth.log
</pre>

The state files in /var/spool/rsyslog

<pre>
# ls -l /var/spool/rsyslog/
total 4
-rw------- 1 syslog adm 98 Aug 12 06:25 imfile-state:131919
</pre>

Permissions of /var/spool/rsyslog directory:

<pre>
drwx------  2 syslog adm  4096 Aug 13 06:25 rsyslog
</pre>

Log rotate config:
<pre>
/var/log/syslog
{
    rotate 7
    daily
    maxsize 1G
    missingok
    notifempty
    delaycompress
    compress
    postrotate
    invoke-rc.d rsyslog rotate > /dev/null
    endscript
}

/var/log/mail.info
/var/log/mail.warn
/var/log/mail.err
/var/log/mail.log
/var/log/daemon.log
/var/log/kern.log
/var/log/auth.log
/var/log/user.log
/var/log/lpr.log
/var/log/cron.log
/var/log/debug
/var/log/messages
{
    rotate 4
    weekly
    missingok
    notifempty
    compress
    delaycompress
    sharedscripts
    postrotate
        invoke-rc.d rsyslog rotate > /dev/null
    endscript
}
</pre>

logrotate version:
<pre>
logrotate 3.8.7
</pre>

**Comment by rgerhards** [comment]
I think the issues is rooted in missing permissions. From the error messages you posted:
```
Aug 12 06:25:01  rsyslogd: imfile: cannot watch object '/var/log/auth.log': Permission denied [v8.37.0 try http://www.rsyslog.com/e/2027 ]
Aug 12 06:25:01  rsyslogd: file '/var/log/auth.log': open error: Permission denied [v8.37.0 try http://www.rsyslog.com/e/2433 ]
Aug 12 06:25:01  rsyslogd:  [origin software="rsyslogd" swVersion="8.37.0" x-pid="31313" x-info="http://www.rsyslog.com"] rsyslogd was HUPed
```
Does logrotate create the files with the wrong ids?

Could you try to remove the privdrop statements, so that rsyslog runs as root. I would assume that it then works, what would confirm the permission issue.

**Comment by rgerhards** [comment]
The state file is only created on shutdown (except if otherwise configured). Run state is kept in memory. But if we cannot open the to-be-monitored file itself, we neither create state file nor run state simply because we cannot monitor the file as we cannot open and thus read it.

**Comment by davidelang** [comment]
On Wed, 29 Aug 2018, ladean wrote:

> Thanks for the information on the state file. This does make sense.
>
> I tested running rsyslog as root by commenting the Drop priv statements. The behaviour was the same. The remote logs where sent immediately after a restart however stopped sending after logrotate. The real crazy thing here is that it seems random. At first I had thought that the logs just stopped sending after logrotate, however after watching this for a while I'd also see the reverse where I would see logs in the remote location when I didn't the day before. The syslog is rotated daily.
>
> I'm not quite sure where to go from here. I've put the logs back as running under the non root user.

set the log rotation to happen very frequently (every few min)

how are you rotating the file?

David Lang

**Comment by fttyX** [comment]
@rgerhards
Same issue here (but with 8.34.0, centos 7.5.1804, file /var/log/mariadb/slow.log).

> @ladean does the issue still exist for you? If so, can you answer the open question:
> > how are you rotating the file?

He posted his logrotate config above. But here's mine:

```
/var/log/mariadb/slow.log {
        create 640 mysql mysql
        notifempty
        hourly
        rotate 3
        missingok
        compress
    postrotate
       # just if mysqld is really running
       if test -x /usr/bin/mysqladmin && \
          /usr/bin/mysqladmin ping &>/dev/null
       then
          /usr/bin/mysqladmin flush-logs
       fi
    endscript
}
```

Also, sometimes restart doesn't help as well. But if I stop rsyslog, delete everything in /var/lib/rsyslog/ and start again -- then new logs are delivered fine.

With broken delivery this directory looks like this (I'm reading 2 log files, actually):
```
# ls -l /var/lib/rsyslog/
total 12
-rw-------. 1 root root  99 Oct  1 14:58 imfile-state:1073847181
-rw-------. 1 root root 105 Oct  1 14:58 imfile-state:1074008877
-rw-r--r--. 1 root root 126 Oct  1 15:01 imjournal.state
```

Rsyslog is running under root.

**Comment by ladean** [comment]
Hi,
Sorry I've been swamped with a few other projects that I haven't been focused with this. However the issue still exsists. Here is my logrotate config. 

```/var/log/syslog
{
    rotate 7
    daily
    maxsize 1G
    missingok
    notifempty
    delaycompress
    compress
    postrotate
    invoke-rc.d rsyslog rotate > /dev/null
    endscript
}
```

**Comment by rgerhards** [comment]
This should be solved by https://github.com/rsyslog/rsyslog/pull/3051

I think I overlooked this issue in the close message. Let us know if it does not help, than I'll return the issue.

**Comment by ladean** [comment]
Cool thanks!
