### ISSUE TITLE
rsyslog v7 takes large memory

### ISSUE THREAD

**Issue by chenkunxiao** [rsyslog/rsyslog#2939]
Hello, everyone, now I meet a memory problem about rsyslog, I find that it takes large number of virtual memory. In x86 envirenment, it takes about 320m memory. I want to know there is any way to reduce the memory. Thank you!

**Comment by davidelang** [comment]
On Thu, 16 Aug 2018, chenkunxiao wrote:

> Hello, everyone, now I meet a memory problem about rsyslog, I find that it 
> takes large number of virtual memory. In x86 envirement, it takes about 320m 
> memory. I want to know there is any way to reduce the memory. Thank you!

change your config. have it do less and have smaller queues.

but without seeing your config and having some idea of what's happening, we 
can't begin to guess what's causing it.

post the config, then we may need you to enable impstats so we can see how full 
the queues are.

David Lang

**Comment by chenkunxiao** [comment]
Thank you! The following is my config file:

#### MODULES ####

$ModLoad imuxsock # provides support for local system logging (e.g. via logger command)
$ModLoad imklog # reads kernel messages (the same are read from journald)
$ModLoad immark  # provides --MARK-- message capability

# Provides UDP syslog reception
#$ModLoad imudp
#$UDPServerRun 514

# Provides TCP syslog reception
#$ModLoad imtcp
#$InputTCPServerRun 514


#### GLOBAL DIRECTIVES ####
$FileGroup root
$FileOwner root
$FileCreateMode 0640

# Where to place auxiliary files
$WorkDirectory /var/lib/rsyslog

# Use default timestamp format
$ActionFileDefaultTemplate RSYSLOG_FileFormat

# File syncing capability is disabled by default. This feature is usually not required,
# not useful and an extreme performance hit
#$ActionFileEnableSync on

# Include all config files in /etc/rsyslog.d/
$IncludeConfig /etc/rsyslog.d/*.conf


#### RULES ####

# Log all kernel messages to the console.
# Logging much else clutters up the screen.
#kern.*                                                 /dev/console

# Log anything (except mail) of level info or higher.
# Don't log private authentication messages!
*.debug;mail.none;                                       /var/log/messages

# The authpriv file has restricted access.
authpriv.*                                              /var/log/secure

# Log all the mail messages in one place.
mail.*                                                  -/var/log/maillog


# Log cron stuff
cron.*                                                  /var/log/cron

# Everybody gets emergency messages
*.emerg                                                 :omusrmsg:*

# Save news errors of level crit and higher in a special file.
uucp,news.crit                                          /var/log/spooler

# Save boot messages also to boot.log
local7.*                                                /var/log/boot.log

**Comment by davidelang** [comment]
anything in the included /etc/rsyslog.d directory?

enable impstats and show us the output.

It's possible that what you are seeing is just the memory used by the logsin 
your system

what version of rsyslog is this?

**Comment by chenkunxiao** [comment]
There is anything in the included /etc/rsyslog.d directory. The version of rsyslog is 7.4.7 and I find that if I load a more module, it will cost 64m anon pages more, but I don't know why.

**Comment by rgerhards** [comment]
It's probably just virtual name space reservation. Seems to depend on build options. You should check the actual physical memory allocation.

**Comment by chenkunxiao** [comment]
Today, I know that why rsyslog takes so much virtual memory, because it is a multithreading software. If we malloc memory in multi-thread program in 64bits envirenment, it will takes about 64m virtual memory when we malloc memory in one more thread.

program:
/* Per thread arena example. */
#include <stdio.h>
#include <stdlib.h>
#include <pthread.h>
#include <unistd.h>
#include <sys/types.h>

void* threadFunc(void* arg) {
    printf("Before malloc in thread 1\n");
    getchar();
    char* addr = (char*) malloc(1000);
    printf("After malloc and before free in thread 1\n");
    getchar();
    free(addr);
    printf("After free in thread 1\n");
    getchar();
}

int main() {
    pthread_t t1;
    void* s;
    int ret;
    char* addr;

    printf("Welcome to per thread arena example::%d\n",getpid());
    printf("Before malloc in main thread\n");
    getchar();
    addr = (char*) malloc(1000);
    printf("After malloc and before free in main thread\n");
    getchar();
    free(addr);
    printf("After free in main thread\n");
    getchar();
    ret = pthread_create(&t1, NULL, threadFunc, NULL);
    if(ret)
    {
        printf("Thread creation error\n");
        return -1;
    }
    ret = pthread_join(t1, &s);
    if(ret)
    {
        printf("Thread join error\n");
        return -1;
    }
    return 0;
}

after the program, I can get the following infomation:
in 【4】stage, we can see that it costs 64m virtual memory more when I malloc memory in other thread.
7f98000000-7f98021000 rw-p 00000000 00:00 0
7f98021000-7f9c000000 ---p 00000000 00:00 0
【1】After malloc and before free in main thread
00400000-00401000 r-xp 00000000 00:11 10419 /tmp/thread_malloc
00411000-00412000 rw-p 00001000 00:11 10419 /tmp/thread_malloc
099b1000-099d2000 rw-p 00000000 00:00 0 [heap]
7f9d022000-7f9d042000 rw-p 00000000 00:00 0
7f9d042000-7f9d194000 r-xp 00000000 00:02 6341 /lib64/libc-2.20.so
7f9d194000-7f9d1a3000 ---p 00152000 00:02 6341 /lib64/libc-2.20.so
7f9d1a3000-7f9d1a7000 r--p 00151000 00:02 6341 /lib64/libc-2.20.so
7f9d1a7000-7f9d1a9000 rw-p 00155000 00:02 6341 /lib64/libc-2.20.so
7f9d1a9000-7f9d1ad000 rw-p 00000000 00:00 0
7f9d1ad000-7f9d1c5000 r-xp 00000000 00:02 6269 /lib64/libpthread-2.20.so
7f9d1c5000-7f9d1d5000 ---p 00018000 00:02 6269 /lib64/libpthread-2.20.so
7f9d1d5000-7f9d1d6000 r--p 00018000 00:02 6269 /lib64/libpthread-2.20.so
7f9d1d6000-7f9d1d7000 rw-p 00019000 00:02 6269 /lib64/libpthread-2.20.so
7f9d1d7000-7f9d1db000 rw-p 00000000 00:00 0
7f9d1db000-7f9d1fc000 r-xp 00000000 00:02 6338 /lib64/ld-2.20.so
7f9d206000-7f9d209000 rw-p 00000000 00:00 0
7f9d209000-7f9d20a000 r--p 00000000 00:00 0 [vvar]
7f9d20a000-7f9d20b000 r-xp 00000000 00:00 0 [vdso]
7f9d20b000-7f9d20c000 r--p 00020000 00:02 6338 /lib64/ld-2.20.so
7f9d20c000-7f9d20e000 rw-p 00021000 00:02 6338 /lib64/ld-2.20.so
7fedef4000-7fedf15000 rw-p 00000000 00:00 0 [stack]
【2】After free in main thread
00400000-00401000 r-xp 00000000 00:11 10419 /tmp/thread_malloc
00411000-00412000 rw-p 00001000 00:11 10419 /tmp/thread_malloc
099b1000-099d2000 rw-p 00000000 00:00 0 [heap]
7f9d022000-7f9d042000 rw-p 00000000 00:00 0
7f9d042000-7f9d194000 r-xp 00000000 00:02 6341 /lib64/libc-2.20.so
7f9d194000-7f9d1a3000 ---p 00152000 00:02 6341 /lib64/libc-2.20.so
7f9d1a3000-7f9d1a7000 r--p 00151000 00:02 6341 /lib64/libc-2.20.so
7f9d1a7000-7f9d1a9000 rw-p 00155000 00:02 6341 /lib64/libc-2.20.so
7f9d1a9000-7f9d1ad000 rw-p 00000000 00:00 0
7f9d1ad000-7f9d1c5000 r-xp 00000000 00:02 6269 /lib64/libpthread-2.20.so
7f9d1c5000-7f9d1d5000 ---p 00018000 00:02 6269 /lib64/libpthread-2.20.so
7f9d1d5000-7f9d1d6000 r--p 00018000 00:02 6269 /lib64/libpthread-2.20.so
7f9d1d6000-7f9d1d7000 rw-p 00019000 00:02 6269 /lib64/libpthread-2.20.so
7f9d1d7000-7f9d1db000 rw-p 00000000 00:00 0
7f9d1db000-7f9d1fc000 r-xp 00000000 00:02 6338 /lib64/ld-2.20.so
7f9d206000-7f9d209000 rw-p 00000000 00:00 0
7f9d209000-7f9d20a000 r--p 00000000 00:00 0 [vvar]
7f9d20a000-7f9d20b000 r-xp 00000000 00:00 0 [vdso]
7f9d20b000-7f9d20c000 r--p 00020000 00:02 6338 /lib64/ld-2.20.so
7f9d20c000-7f9d20e000 rw-p 00021000 00:02 6338 /lib64/ld-2.20.so
7fedef4000-7fedf15000 rw-p 00000000 00:00 0 [stack]

【3】Before malloc in thread 1
00400000-00401000 r-xp 00000000 00:11 10419 /tmp/thread_malloc
00411000-00412000 rw-p 00001000 00:11 10419 /tmp/thread_malloc
099b1000-099d2000 rw-p 00000000 00:00 0 [heap]
7f9c822000-7f9c823000 ---p 00000000 00:00 0
7f9c823000-7f9d042000 rw-p 00000000 00:00 0 [stack:1877]
7f9d042000-7f9d194000 r-xp 00000000 00:02 6341 /lib64/libc-2.20.so
7f9d194000-7f9d1a3000 ---p 00152000 00:02 6341 /lib64/libc-2.20.so
7f9d1a3000-7f9d1a7000 r--p 00151000 00:02 6341 /lib64/libc-2.20.so
7f9d1a7000-7f9d1a9000 rw-p 00155000 00:02 6341 /lib64/libc-2.20.so
7f9d1a9000-7f9d1ad000 rw-p 00000000 00:00 0
7f9d1ad000-7f9d1c5000 r-xp 00000000 00:02 6269 /lib64/libpthread-2.20.so
7f9d1c5000-7f9d1d5000 ---p 00018000 00:02 6269 /lib64/libpthread-2.20.so
7f9d1d5000-7f9d1d6000 r--p 00018000 00:02 6269 /lib64/libpthread-2.20.so
7f9d1d6000-7f9d1d7000 rw-p 00019000 00:02 6269 /lib64/libpthread-2.20.so
7f9d1d7000-7f9d1db000 rw-p 00000000 00:00 0
7f9d1db000-7f9d1fc000 r-xp 00000000 00:02 6338 /lib64/ld-2.20.so
7f9d206000-7f9d209000 rw-p 00000000 00:00 0
7f9d209000-7f9d20a000 r--p 00000000 00:00 0 [vvar]
7f9d20a000-7f9d20b000 r-xp 00000000 00:00 0 [vdso]
7f9d20b000-7f9d20c000 r--p 00020000 00:02 6338 /lib64/ld-2.20.so
7f9d20c000-7f9d20e000 rw-p 00021000 00:02 6338 /lib64/ld-2.20.so
7fedef4000-7fedf15000 rw-p 00000000 00:00 0 [stack]

【4】After malloc and before free in thread 1
00400000-00401000 r-xp 00000000 00:11 10419 /tmp/thread_malloc
00411000-00412000 rw-p 00001000 00:11 10419 /tmp/thread_malloc
099b1000-099d2000 rw-p 00000000 00:00 0 [heap]
7f98000000-7f98021000 rw-p 00000000 00:00 0
7f98021000-7f9c000000 ---p 00000000 00:00 0
7f9c822000-7f9c823000 ---p 00000000 00:00 0
7f9c823000-7f9d042000 rw-p 00000000 00:00 0 [stack:1877]
7f9d042000-7f9d194000 r-xp 00000000 00:02 6341 /lib64/libc-2.20.so
7f9d194000-7f9d1a3000 ---p 00152000 00:02 6341 /lib64/libc-2.20.so
7f9d1a3000-7f9d1a7000 r--p 00151000 00:02 6341 /lib64/libc-2.20.so
7f9d1a7000-7f9d1a9000 rw-p 00155000 00:02 6341 /lib64/libc-2.20.so
7f9d1a9000-7f9d1ad000 rw-p 00000000 00:00 0
7f9d1ad000-7f9d1c5000 r-xp 00000000 00:02 6269 /lib64/libpthread-2.20.so
7f9d1c5000-7f9d1d5000 ---p 00018000 00:02 6269 /lib64/libpthread-2.20.so
7f9d1d5000-7f9d1d6000 r--p 00018000 00:02 6269 /lib64/libpthread-2.20.so
7f9d1d6000-7f9d1d7000 rw-p 00019000 00:02 6269 /lib64/libpthread-2.20.so
7f9d1d7000-7f9d1db000 rw-p 00000000 00:00 0
7f9d1db000-7f9d1fc000 r-xp 00000000 00:02 6338 /lib64/ld-2.20.so
7f9d206000-7f9d209000 rw-p 00000000 00:00 0
7f9d209000-7f9d20a000 r--p 00000000 00:00 0 [vvar]
7f9d20a000-7f9d20b000 r-xp 00000000 00:00 0 [vdso]
7f9d20b000-7f9d20c000 r--p 00020000 00:02 6338 /lib64/ld-2.20.so
7f9d20c000-7f9d20e000 rw-p 00021000 00:02 6338 /lib64/ld-2.20.so
7fedef4000-7fedf15000 rw-p 00000000 00:00 0 [stack]

**Comment by rgerhards** [comment]
looks like the queston is answered
