### ISSUE TITLE
Trailing space on hostname with inline comments

### ISSUE THREAD

**Issue by teran-mckinney** [rsyslog/rsyslog#295]
Hi rsyslog developers and all,

I found a strange bug with rsyslogd. If you tell rsyslog to send messages to a server (*.* @ or @@), if you suffix it with a space and a hash, it reads the hostname as "hostname ". If it's just a trailing space, it reads it without the space. If it's a comment without a space, it's fine.

This works as expected:
```
*.* @somedomain.somehost.probably.doesnt.exist.net
*.* @somedomain.somehost.probably.doesnt.exist.net (trailing space)
*.* @somedomain.somehost.probably.doesnt.exist.net#inlinecomment
*.* @somedomain.somehost.probably.doesnt.exist.net#inline comment
```

This does not:
```
*.* @somedomain.somehost.probably.doesnt.exist.net #inline
*.* @somedomain.somehost.probably.doesnt.exist.net #inline comment
```

This is what happens with the trailing space and comment:

```
21:19:10.947927 IP (tos 0x0, ttl 64, id 25201, offset 0, flags [DF], proto UDP (17), length 92)
    23.253.229.217.35283 > 72.3.128.241.53: 23730+ A? somedomain.somehost.probably.doesnt.exist.net . (64)
21:19:10.947940 IP (tos 0x0, ttl 64, id 25202, offset 0, flags [DF], proto UDP (17), length 92)
    23.253.229.217.35283 > 72.3.128.241.53: 612+ AAAA? somedomain.somehost.probably.doesnt.exist.net . (64)
21:19:10.952986 IP (tos 0x0, ttl 59, id 58487, offset 0, flags [none], proto UDP (17), length 167)
    72.3.128.241.53 > 23.253.229.217.35283: 23730 NXDomain 0/1/0 (139)
21:19:10.953192 IP (tos 0x0, ttl 59, id 58488, offset 0, flags [none], proto UDP (17), length 167)
    72.3.128.241.53 > 23.253.229.217.35283: 612 NXDomain 0/1/0 (139)
```

Obviously the hostname is not intended to resolve, but if you look closely you'll see the space between the period and hostname. With valid hostnames this will subtly break it.

I have not tested with the latest code in Github, but haven't found any issues mentioning this. This happens on Precise and Wheezy.

Let me know what you guys think about this.

Thanks,
Teran

PS: These are the affected versions I have tested:
Precise: 5.8.6-1ubuntu8.9
Wheezy: 5.8.11-3+deb7u2

**Comment by rgerhards** [comment]
You are using a very outdated version no longer supported by the project. I think the current one (v8.9.0) does not have this issue. So I am closing this bug. Please re-open if the problem persists with the supported version.
