### ISSUE TITLE
Can i get array like python syntax range(m,n)

### ISSUE THREAD

**Issue by jerry-chen-315** [rsyslog/rsyslog#2951]
### Expected behavior
I wanna get a array by a random number which come from log argument.
Like python range(5,10),it will return [5,6,7,8,9]

Can I do this in RainerScript ?

### Environment
- rsyslog version: 8.33.1
- platform: CentOS 6 or 7

**Comment by rgerhards** [comment]
no, it's not supported.

The config script is also not meant as a general purpose programming language. For complex logic, it is recommended to call e.g. a python script via omprog.

**Comment by jerry-chen-315** [comment]
thanks for your advice
