### ISSUE TITLE
Supplementary groups not being added when dropping privileges, causing problems with imfile and inotify.

### ISSUE THREAD

**Issue by zlisinski** [rsyslog/rsyslog#296]
When dropping privileges to syslog:syslog, imfile using inotify fails to monitor files if they are not world readable or owned by the syslog user or group, even if the syslog user is part of the group that owns the file. On Ubuntu, the syslog user is a member of the adm group, and inotify_add_watch() returns with errno set to EACCES when set to watch a file with apache:adm ownership and 640 permissions. It is also present on RHEL/CentOS, although they don't drop privileges by default. The supplementary groups from /etc/group for the user are not being applied. The workarounds are to not drop privileges, make files/directories readable to everyone, or change the file's group to syslog, none of which are very appealing.

This was fixed in packages from the official Ubuntu repositories, but is still an issue with packages from the Adiscon repositories.

The patch can be found here:
http://bazaar.launchpad.net/~cjwatson/ubuntu/trusty/rsyslog/repair-groups/revision/57/debian/patches/10-initgroups.patch

I can submit this as a pull request if that works better.

**Comment by rgerhards** [comment]
A PR would be fantastic, as it saves me some time.

**Comment by rgerhards** [comment]
merged into master-candidate, will automatically propagate to master from there. To be released with 8.10.0.

**Comment by rgerhards** [comment]
to be released with 8.10.0
