### ISSUE TITLE
imfile module: File reading based on rate limit

### ISSUE THREAD

**Issue by dpkkumar01** [rsyslog/rsyslog#2960]
I am using imfile module to read my file and sending the logs to kafka. I want to restrict the file reading logic at imfile module based on number of lines or size to maintain my rsyslog resource usage constant. 

whenever i am stopping  and starting the process, it is taking maximum logs and sending to kafka module during the time my system resource utilisation was going to very High which is creating the trouble on my other running applications.

Please suggest on the same.

Thanks..

**Comment by rgerhards** [comment]
you can do rate-limiting at the output, albeit it is limited. However, decent queue size for the worker should solve the problem by itself. Please post full config and impstats log.

**Comment by dpkkumar01** [comment]
@rgerhards ,  I think we should have a control at input side to restrict the entry data instead of making the data in queue at output side. This may break in some case depends on the number of input data.

Please provide your suggestions.....

**Comment by davidelang** [comment]
On Wed, 5 Sep 2018, dpkkumar01 wrote:

> @rgerhards , I think we should have a control at input side to restrict the 
> entry data instead of making the data in queue at output side. This may break 
> in some case depends on the number of input data.

As a general rule, I would disagree with throttling the input, but reading from 
files is a special case where the inputs can appear in _very_ large chunks 
(minutes to hours worth of logs appearing instantly).

We already have limits that say 'only read X messages from a file before moving 
on to the next file' to try and provide some fairness and prevent one file from 
overwelming all other files, it makes sense to me to add additional limits so 
that we can provide some sort of limit/fairness between file input and other 
inputs.

David Lang

**Comment by rgerhards** [comment]
yeah, but you can solve this with a dedicated rule set and proper queue settings for this one. Doesn't look to me like a top priority feature request.

**Comment by rgerhards** [comment]
I just notice I hadn't commented on the queue size, thought I had. It's configured pretty large at 2,000,000 so it's clear that imfile pushes two million log lines before throtteling. I suggest reducing that to whatever is appropriate, maybe 2000? The let's see if any issue at all exists.

**Comment by davidelang** [comment]
On Thu, 6 Sep 2018, Rainer Gerhards wrote:

> yeah, but you can solve this with a dedicated rule set and proper queue 
> settings for this one. Doesn't look to me like a top priority feature request.

can you provide an example of how you would setup this separate queue to rate 
limit how fast the queue outputs logs into the default ruleset?

David Lang

**Comment by rgerhards** [comment]
oh no, that was even the librdkafka queue. rsyslog's is at 3 million messages, so the action buffers 5 million before anypushback happens.

**Comment by rgerhards** [comment]
The default ruleset is not used by imfile. Setting the queue sizes appropriate on ruleset MTFW_CDR above should probably solve the issue. Then kafka can push back and the ruleset can oushback to imfile.

**Comment by rgerhards** [comment]
As a compromise, I can introduce a per-line delay into the file reader. That should be easy to implement and do rough rate limiting. But please nobody complain if we loose data because the reader cannot keep up ;-)

**Comment by davidelang** [comment]
On Thu, 6 Sep 2018, Rainer Gerhards wrote:

> As a compromise, I can introduce a per-line delay into the file reader. That 
> should be easy to implement and do rough rate limiting. But please nobody 
> complain if we loose data because the reader cannot keep up ;-)

I would make the delay be per batch to not be too inefficiant in the processing.

one nice thing about imfile, until you start deleting files, no data will be 
lost. you may fall _way_ behind, but you won't loose data.

I don't see this as a very high priority feature, but it is something I have run 
across a few times. I'm seeing it more as people do cloud/container stuff where 
logs go into odd places and then get gathered to a common point periodically 
(who would have thought that the old, broken approach of 'log to local files and 
then ftp them out every X minutes' would make a comeback, but aside from 
replacing ftp with a different transport, it really is :-( ) This is part of 
the reason wildcard input filenames are needed so much. As a result, you 
havea batch of logs that can take tens of seconds to minutes to process show up 
instantly, and we really do want to not have this essentially block messages 
from other sources that can't wait (imuxsoc, tcp, udp) for such lengthy periods.

We should add an example of how to throttle imfile inputs to the imfile 
documentation.

David Lang

**Comment by rgerhards** [comment]
I think I can do this quickly...

**Comment by davidelang** [comment]
On Thu, 6 Sep 2018, Rainer Gerhards wrote:

> The default ruleset is not used by imfile. Setting the queue sizes appropriate 
> on ruleset MTFW_CDR above should probably solve the issue. Then kafka can push 
> back and the ruleset can oushback to imfile.

I'mresponding to the general problem and why you would want a rate limit, not a 
specific config (I'll login later to see the specific config in this post)

**Comment by rgerhards** [comment]
To do it quickly, the rate limiter needs to be on the message level. Else it's a more considerate change.

**Comment by rgerhards** [comment]
In https://github.com/rsyslog/rsyslog/pull/2999 I have added a new input parameter ```delay.message``` which specifies a delay in microseconds after each line read. No time to add a specific test for this feature. As such I would appreciate if @dpkkumar01 could merge it and give it a try.

**Comment by rgerhards** [comment]
I would still suggest to use more suitable queue sizes, and be it only to avoid OOM conditions.

**Comment by davidelang** [comment]
On Thu, 6 Sep 2018, Rainer Gerhards wrote:

> To do it quickly, the rate limiter needs to be on the message level. Else it's a more considerate change.

doesn't imfile read in batches?

If not, at least document that this is per-batch, even if the current batch size 
is 1

otherwise we have to sacrafice all batching as soon as any limits are set, which 
is a bad thing to do.

David Lang

**Comment by dpkkumar01** [comment]
I have tried to turn the Queue size(queue.buffering.max.messages) between
(2000-10000) & initiated the load , many messages were dropped with the
below error.

Sep  7 11:02:14 rsyslogd[11574]: omkafka: Failed to produce to topic
'mtfw_cdr' (rd_kafka_producev)*partition -1: -184/Local: Queue full *
[v8.37.0 try http://www.rsyslog.com/e/2424 ]
Sep  7 11:02:14  rsyslogd[11574]: action 'action-8-omkafka' suspended
(module 'omkafka'), retry 0. There should be messages before this one
giving the reason for suspension. [v8.37.0 try http://www.rsyslog.com/e/2007
]
Sep  7 11:02:14  rsyslogd[11574]: action 'action-8-omkafka' resumed (module
'omkafka') [v8.37.0 try http://www.rsyslog.com/e/2359 ]
Sep  7 11:02:14  rsyslogd[11574]: omkafka: Failed to produce to topic
'mtfw_cdr' (rd_kafka_producev)*partition -1: -184/Local: Queue full *
[v8.37.0 try http://www.rsyslog.com/e/2424 ]

If i increase queue size to 100000 then rsyslog CPU usage was going  beyond
300%

**Comment by rgerhards** [comment]
El vie., 7 sept. 2018 a las 7:49, dpkkumar01 (<notifications@github.com>)
escribió:

> I have tried to turn the Queue size(queue.buffering.max.messages) between
> (2000-10000) & initiated the load , many messages were dropped with the
> below error.
>
> Sep 7 11:02:14 rsyslogd[11574]: omkafka: Failed to produce to topic
> 'mtfw_cdr' (rd_kafka_producev)*partition -1: -184/Local: Queue full *
> [v8.37.0 try http://www.rsyslog.com/e/2424 ]
> Sep 7 11:02:14 rsyslogd[11574]: action 'action-8-omkafka' suspended
> (module 'omkafka'), retry 0. There should be messages before this one
> giving the reason for suspension. [v8.37.0 try
> http://www.rsyslog.com/e/2007
> ]
> Sep 7 11:02:14 rsyslogd[11574]: action 'action-8-omkafka' resumed (module
> 'omkafka') [v8.37.0 try http://www.rsyslog.com/e/2359 ]
> Sep 7 11:02:14 rsyslogd[11574]: omkafka: Failed to produce to topic
> 'mtfw_cdr' (rd_kafka_producev)*partition -1: -184/Local: Queue full *
> [v8.37.0 try http://www.rsyslog.com/e/2424 ]
>
>
The action is suspended. This is good. You need to tell it to wait and
retry in this case. That's exactly the pushback. By default, no wait is
done.

See "action.resumeRetryCount" in action params:
   https://www.rsyslog.com/doc/v8-stable/configuration/actions.html

Rainer

If i increase queue size to 100000 then rsyslog CPU usage was going beyond

**Comment by dpkkumar01** [comment]
I have updated failure retry configuration & done the  couple of test cases by adjusting the queue size which reduced the CPU usage but couple of points i have observed during this testing.

1.  Rsyslog memory usage went more than 300 MB during the testing but not getting release after stopping the load. 
2.  Able to retrieve the failure data. But some time i am not able to get the complete data sent to kafka which i will do the retest and confirm.
3.  Getting queue full error even incoming message limit is less than the queue size 
I am pushing constant load of 2500  and my queue  limit is 4000. Messages are getting drop and re sending again in retry. 

My current configuration
-----------------------------

input(type="imfile"
     File="/home/mis/cdrs/DN*.log"
     Tag="cdr: "
     PersistStateInterval="10000"
     deleteStateOnFileDelete="off"
     ruleset="MTFW_CDR")

ruleset(name="MTFW_CDR") {
     action(type="mmnormalize" rulebase="/etc/MTFW_CDR.rb")
     action(
            type="omkafka"
            template="MTFW_CDR"
            topic="mtfw_cdr"
            action.resumeRetryCount="-1"
            action.resumeInterval="1"
            action.reportSuspension="on"
            action.reportSuspensionContinuation="on"
            resubmitOnFailure="on"
            broker=["X.X.X.X:9092"]
            partitions.auto="on"
            errorFile="/var/log/kafka_error.log"
            confParam=[
                       "socket.timeout.ms=1000",
                       "socket.keepalive.enable=true",
                       "reconnect.backoff.jitter.ms=1000",
                       "queue.buffering.max.messages=4000",
                       "queue.buffering.max.ms=1000",
                       "compression.codec=gzip"
                       ]
                       queue.workerThreads="5"
                       queue.dequeueBatchSize="1000"
                       queue.highWatermark="3000000"
                       queue.lowWatermark="750000"
                       queue.spoolDirectory="/var/run/rsyslog/queues"
                       queue.fileName="stats_ruleset"
                       queue.maxDiskSpace="5g"
                       queue.size="5000000"
                       queue.saveOnShutdown="on"
           )stop
}
