### ISSUE TITLE
test issue - DO NOT USE, WILL BE DELETED

### ISSUE THREAD

**Issue by rgerhards** [rsyslog/rsyslog#2988]
### Environment
- rsyslog version: 
- platform: 
- for configuration questions/issues, include rsyslog.conf and included config files

**Comment by rgerhards** [comment]
test 2 @PascalWithopf

**Comment by rgerhards** [comment]
test 3

**Comment by PascalWithopf** [comment]
tests 4

**Comment by rgerhards** [comment]
test 5

**Comment by rgerhards** [comment]
test 6

**Comment by rgerhards** [comment]
test 7

**Comment by rgerhards** [comment]
test 8 @PascalWithopf
