### ISSUE TITLE
If flex is not installed, build fails during make, instead of during configure.

### ISSUE THREAD

**Issue by zlisinski** [rsyslog/rsyslog#300]
configure or autogen.sh should fail if flex is not installed. Instead it reports 'no' for flex/lex and continues. You will then get an error that lexer.c can't be found when compiling. The file lexer.c isn't in git, and I assume it is created by flex from grammar/lexer.l.

Output from `configure` or `autogen.sh`:
    `checking for flex... no`
    `checking for lex... no`

Output from make:
`make[3]: Entering directory '/root/rsyslog/grammar'`
`LEX      lexer.c`
`CC       libgrammar_la-lexer.lo`
`gcc: error: ./lexer.c: No such file or directory`
`gcc: fatal error: no input files`
`compilation terminated.`

My autotools knowledge isn't that great, so I'm submitting this in the hopes that someone else can fix it.

**Comment by jaywayjayway** [comment]
the same with me , I'am  in the soup ):

**Comment by rgerhards** [comment]
As far as I know, everything related to flex is done in autoconf.ac. So the problem looks unavoidable to me. If someone has a patch, a PR is most welcome.

**Comment by krawiec** [comment]
Well... it is kinda weird and i cannot imagine why somebody would do that ... ever.


Well... user can obtain sources from:
1) git clone (which contains .git directory but does not contain .tarball-version)
2) official release tarballed source (which contains .tarball-version file, but does not contain .git directory)

But in file configure.ac is weird block which looks like this:

```
# Running from git source?
in_git_src=no
AS_IF([test -d "$srcdir"/.git && ! test -f  "$srcdir"/.tarball-version], [in_git_src=yes])
```

and inside that block we have checks for FLEX and YACC.

i guess it was made by huge mistake, and if should contain only this line:

`
have_to_generate_man_pages=yes
`

Because in .git we do not have generated man pages , which are distributet only in release tarball.

tests for lex and yacc shoult be outside this big if block.
period.

cheers

**Comment by rgerhards** [comment]
This was specifically introduced by @Whissi IIRC. @Whissi can you please comment.

**Comment by Whissi** [comment]
@jaywayjayway: Which rsyslog version do you use? Can you please attach your *config.log* file?

Also please see https://github.com/rsyslog/rsyslog/blob/v8.21.0/configure.ac#L1746 I.e. `flex` is only required when building from git src, not when build from release tarball. So if you hit this with recent rsyslog you probably have a rsyslog src without ".git" (i.e. exported instead of cloned).

**Comment by krawiec** [comment]
@Whissi  
But whyyy ?

checks for yacc and flex should be independent from source (.git clone or release tarball)
Why? Because you cannot build rsyslog without these two.

i guess in this if block should contains only this line:
`
 have_to_generate_man_pages=yes

`

which probably is not needed at all because these checks are already done ??:
https://github.com/rsyslog/rsyslog/blob/v8.21.0/configure.ac#L1721

**Comment by Whissi** [comment]
We check for `flex` and `yacc` independent from source. If they are available the programs detected will be used.

But we only break (=configure error) when they are really required, i.e. when building from git source.

Otherwise we would have to add a hard requirement on `yacc` and `flex` all the time which we want to avoid.

If you follow official supported ways (i.e. using release tarball or git source) everything works. Well, there will be corner case if you modify a lexer file so it must be re-generated... but if you do something like that we expect that you have `yacc` or `flex` in place.

**Comment by Whissi** [comment]
So I don't really understand the problem: Are you hitting a build issue while trying to build from a supported source (git clone or release tarball)? If not then you are on your own. And the only problem seems to be that configure doesn't show an error (or do I miss anything?). In this case please record that requirement for your build environment on your own and it should work in your environment as well (or call `touch .tarball-version` to fake a release tarball).

**Comment by krawiec** [comment]
libtool: link: gcc -std=gnu99 -shared  -fPIC -DPIC  .libs/lmtcpclt_la-tcpclt.o   -llogging-stdlog  -g -O2   -Wl,-soname -Wl,lmtcpclt.so -o .libs/lmtcpclt.so
libtool: link: ( cd ".libs" && rm -f "lmtcpclt.la" && ln -s "../lmtcpclt.la" "lmtcpclt.la" )
make[2]: Leaving directory '/home/krawiec/rsyslog-release/rsyslog-8.21.0/runtime'
Making all in grammar
make[2]: Entering directory '/home/krawiec/rsyslog-release/rsyslog-8.21.0/grammar'
/bin/bash ../ylwrap grammar.y y.tab.c grammar.c y.tab.h `echo grammar.c | sed -e s/cc$/hh/ -e s/cpp$/hpp/ -e s/cxx$/hxx/ -e s/c++$/h++/ -e s/c$/h/` y.output grammar.output -- yacc -d
../ylwrap: line 176: yacc: command not found
Makefile:523: recipe for target 'grammar.c' failed
make[2]: *** [grammar.c] Error 127
make[2]: Leaving directory '/home/krawiec/rsyslog-release/rsyslog-8.21.0/grammar'
Makefile:796: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/krawiec/rsyslog-release/rsyslog-8.21.0'
Makefile:623: recipe for target 'all' failed
make: *** [all] Error 2
krawiec@debian:~/rsyslog-release/rsyslog-8.21.0$


1. used release tarball.
2. did not modified ANY files
3. used ./configure with few parameters.

**Comment by Whissi** [comment]
Please attach (or pastebin) *config.log* so I can try to reproduce.

**Comment by rgerhards** [comment]
I think grammar.c is not include in the release tarball, as i consider it a
temporary file. Can not verify at the moment. If so, we could think about
adding it (just like the man files).

Rainer

Sent from phone, thus brief.

Am 24.08.2016 17:14 schrieb "Thomas Deutschmann" <notifications@github.com>:

**Comment by Whissi** [comment]
I run
```
mv /usr/bin/flex /usr/bin/flex.off
mv /usr/bin/yacc /usr/bin/yacc.off
```
and re-emerged rsyslog-8.21.0 from release tarball without any problems.

From configure output:
```
checking whether it is safe to define __EXTENSIONS__... yes
checking for flex... no
checking for lex... no
checking for bison... bison -y
```
...and *build.log* doesn't contain any `yacc` call.

So I cannot reproduce this at the moment.

**Comment by Whissi** [comment]
> I think grammar.c is not include in the release tarball, as i consider it a temporary file. Can not verify at the moment. If so, we could think about adding it (just like the man files).

```
$ wget http://www.rsyslog.com/files/download/rsyslog/rsyslog-8.21.0.tar.gz
$ tar -tvf rsyslog-8.21.0.tar.gz | grep 'grammar'
drwxrwxr-x 1000/1000         0 2016-08-23 14:21 rsyslog-8.21.0/grammar/
-rw-rw-r-- 1000/1000       507 2016-08-03 11:58 rsyslog-8.21.0/grammar/Makefile.am
-rw-rw-r-- 1000/1000      4309 2016-08-22 17:51 rsyslog-8.21.0/grammar/grammar.h
-rw-rw-r-- 1000/1000     11577 2016-08-04 14:34 rsyslog-8.21.0/grammar/rainerscript.h
-rw-rw-r-- 1000/1000     25739 2016-08-23 14:21 rsyslog-8.21.0/grammar/Makefile.in
-rw-rw-r-- 1000/1000    133262 2016-08-22 17:51 rsyslog-8.21.0/grammar/lexer.c
-rw-rw-r-- 1000/1000      8312 2016-08-23 14:15 rsyslog-8.21.0/grammar/grammar.y
-rw-rw-r-- 1000/1000     71012 2016-08-23 14:17 rsyslog-8.21.0/grammar/grammar.c
-rw-rw-r-- 1000/1000    119233 2016-08-04 14:34 rsyslog-8.21.0/grammar/rainerscript.c
-rw-rw-r-- 1000/1000     14274 2016-08-04 14:34 rsyslog-8.21.0/grammar/lexer.l
-rw-rw-r-- 1000/1000      1412 2016-08-04 14:34 rsyslog-8.21.0/grammar/parserif.h
```
However @krawiec error was
```
../ylwrap: line 176: yacc: command not found
```
... @zlisinski and @jaywayjayway reported
```
 gcc: error: ./lexer.c: No such file or directory
```
(but this file is included like shown).

**Comment by JindongChen** [comment]
grammar/lexer.c is not included in archive file v8.21.0.tar.gz from github.

```
$ curl -LO https://github.com/rsyslog/rsyslog/archive/v8.21.0.tar.gz
$ tar -tvf v8.21.0.tar.gz | grep 'grammar'
drwxrwxr-x root/root         0 2016-08-23 20:16 rsyslog-8.21.0/grammar/
-rw-rw-r-- root/root         8 2016-08-23 20:16 rsyslog-8.21.0/grammar/.gitignore
-rw-rw-r-- root/root       507 2016-08-23 20:16 rsyslog-8.21.0/grammar/Makefile.am
-rw-rw-r-- root/root      3715 2016-08-23 20:16 rsyslog-8.21.0/grammar/conf-fmt
-rw-rw-r-- root/root      2786 2016-08-23 20:16 rsyslog-8.21.0/grammar/debian.conf
-rw-rw-r-- root/root      4763 2016-08-23 20:16 rsyslog-8.21.0/grammar/debian.new
-rw-rw-r-- root/root      8312 2016-08-23 20:16 rsyslog-8.21.0/grammar/grammar.y
-rw-rw-r-- root/root     14274 2016-08-23 20:16 rsyslog-8.21.0/grammar/lexer.l
-rw-rw-r-- root/root       297 2016-08-23 20:16 rsyslog-8.21.0/grammar/makefile.stand-alone
-rw-rw-r-- root/root       800 2016-08-23 20:16 rsyslog-8.21.0/grammar/mini.samp
-rw-rw-r-- root/root      1412 2016-08-23 20:16 rsyslog-8.21.0/grammar/parserif.h
-rw-rw-r-- root/root    119233 2016-08-23 20:16 rsyslog-8.21.0/grammar/rainerscript.c
-rw-rw-r-- root/root     11577 2016-08-23 20:16 rsyslog-8.21.0/grammar/rainerscript.h
-rw-rw-r-- root/root       224 2016-08-23 20:16 rsyslog-8.21.0/grammar/samp
-rw-rw-r-- root/root      2260 2016-08-23 20:16 rsyslog-8.21.0/grammar/testdriver.c
```

**Comment by Whissi** [comment]
OK. That's the problem: The release tarballs GitHub provides aren't official. They are created automatically after tagging...

@rgerhards: We should

- Ask GitHub support if there's a way to disable the automatic release feature
- Change your release workflow to auto-upload to GitHub, too
- Change configure's logic from "in_git_src" to "from_release_tarball". I.e. always depend on `flex` & Co. unless `.tarball-version` file was found.

**Comment by xrl** [comment]
I am building from a release tar.gz, downloaded from the rsyslog website (not github releases) and I can trigger this bug by doing `make && make clean` from the release folder.

**Comment by ding1986** [comment]
@xrl  You are right.

@Whissi  You can reproduce it through these steps:
    tar -zxvf rsyslog-8.39.0.tar.gz > res
    cd rsyslog-8.39.0/
    ./configure > ../res
    make -j8 > ../res
    make clean > ../cleans
    make -j8 > ../res
    from now on , the error show on the teminal:
             gcc: error: ./lexer.c: No such file or directory;
             gcc: fatal error: no input files
  
   when run "make clean", execute this step:
             Making clean in grammar
             make[1]: enter directory: “/home/ding/work/test/rsyslog-8.39.0/grammar”
             test -z "grammar.h grammar.c lexer.c" || rm -f grammar.h grammar.c lexer.c
    that's the reason, but i am not ability to repair it.

**Comment by ding1986** [comment]
@Whissi 
Maybe you can repair it through remove this line from the Makefile.am
 cd grammar/
cat Makefile.am | grep lexer.c
CLEANFILES = grammar.h grammar.c lexer.c
remove the CLEANFILES value

i am poor in english.

**Comment by dmolik** [comment]
Is this something that can be revisited with GitHub Actions?

**Comment by 474914041** [comment]
I install the `yacc` and `flex`, then `./configure`and the lexer.c is success created. Maybe you can try int this way

**Comment by 474914041** [comment]
I install the `yacc` and `flex`, then `./configure`and the lexer.c is success created. Maybe you can try int this way
