### ISSUE TITLE
rsyslogd regurgitates old syslog messages at random times

### ISSUE THREAD

**Issue by nickandrew** [rsyslog/rsyslog#301]
I'm running rsyslog 7.4.4-1ubuntu2.3 under an lxc container (this may be relevant).

Sometimes messages logged to rsyslog don't appear in syslog output for days.

Example: A check-net shell script runs every minute (it uses /usr/bin/logger to log its messages). Running this simple script:

```
while true ; do logger "hello $(date)" ; sleep 1 ; done
```

I see the regular every-second output logged in /var/log/syslog as well as older messages from check-net which, I think, were not logged at the time. It is as if rsyslogd is receiving the log packet and holding it (for duplicate detection?) and not releasing it for a very very long time. The output was:

```
Apr 13 01:45:25 gateway5 root: hello Mon Apr 13 01:45:25 AEST 2015
Apr 13 01:45:26 gateway5 root: hello Mon Apr 13 01:45:26 AEST 2015
Apr 13 01:45:27 gateway5 root: hello Mon Apr 13 01:45:27 AEST 2015
Apr  8 09:21:00 gateway5 check-net[1415]: Intermediate state: prefer=iinet, defaultroute=iinet  Keep
Apr 13 01:45:28 gateway5 root: hello Mon Apr 13 01:45:28 AEST 2015
Apr  2 04:51:01 gateway5 check-net[1415]: Intermediate state: prefer=iinet, defaultroute=iinet  Keep
Apr 13 01:45:29 gateway5 root: hello Mon Apr 13 01:45:29 AEST 2015
Apr 13 01:45:30 gateway5 root: hello Mon Apr 13 01:45:30 AEST 2015
Apr 13 01:45:31 gateway5 root: hello Mon Apr 13 01:45:31 AEST 2015
Apr 13 01:45:32 gateway5 root: hello Mon Apr 13 01:45:32 AEST 2015
```

As you can see, the check-net messages appearing were held around 5 and 11 days respectively.

It's not just check-net, syslog from CRON and other logging sources may be similarly delayed.

**Comment by rgerhards** [comment]
Can you try this with the current project supported version (8.9.0 as of this writing) and let me know if the problem persists.

**Comment by rgerhards** [comment]
same issue in https://github.com/rsyslog/rsyslog/issues/315

**Comment by nickandrew** [comment]
I don't understand your question. The old messages weren't "replayed" in the sense of being logged to a file, and weeks or months later, logged again. I went back to the old syslog files and checked: the old messages which appear have been _cached_ within rsyslogd and emitted after weeks or months.

I didn't find any way to trigger the emission. Once an old message is emitted, it doesn't get emitted again at some later time, if that's what you were asking.

I'm sure this is the same issue as #315.

**Comment by lkslawek** [comment]
BTW in my case this was also an lxc container. But as I mentioned I did not have original logs to compare to thus the assumption of replaying.

**Comment by toolforger** [comment]
This might be the same as http://bugzilla.adiscon.com/show_bug.cgi?id=527 , which also proposes a fix.

**Comment by s19n** [comment]
Tha bugzilla at http://bugzilla.adiscon.com is currently unavailable, someone knows what was the "proposed fix"?

**Comment by mostolog** [comment]
I think I may experienced this a few days ago. It happened until I decided to delete my queue.

If it happens again, I'll let you know

**Comment by ParthKolekar** [comment]
It happened to me. I managed to trace out the root cause of my issue happening due to my disk becoming full, due to which rsyslogd forks multiple processes of itself, and they all do some crazy stuff together. 

Version 3.21.1
CentOS release 6.8 (Final)
