### ISSUE TITLE
build fails with GnuTLS 3.4

### ISSUE THREAD

**Issue by andreasstieger** [rsyslog/rsyslog#302]
Build fails after GnuTLS 3.4 upgrade as follows:

> libtool: compile:  gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I.. -pthread -I../runtime -I.. -I../grammar -I/usr/include/json-c -W -Wall -Wformat-security -Wshadow -Wcast-align -Wpointer-arith -Wmissing-format-attribute -Werror=implicit-function-declaration -g -I/usr/include/p11-kit-1 -fomit-frame-pointer -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables -g -fno-strict-aliasing -W -Wall -I../grammar -I../../grammar -c nsdsel_gtls.c  -fPIC -DPIC -o .libs/lmnsd_gtls_la-nsdsel_gtls.o
> nsd_gtls.c:234:15: error: unknown type name 'gnutls_retr_st'
>                gnutls_retr_st *st)
>                ^
[...]
> nsd_gtls.c: In function 'Connect':
> nsd_gtls.c:1676:3: error: implicit declaration of function 'gnutls_certificate_client_set_retrieve_function' [-Werror=implicit-function-declaration]
>    gnutls_certificate_client_set_retrieve_function(xcred, gtlsClientCertCallback);
>    ^
> nsd_gtls.c:1676:58: error: 'gtlsClientCertCallback' undeclared (first use in this function)
>    gnutls_certificate_client_set_retrieve_function(xcred, gtlsClientCertCallback);
>                                                           ^
> nsd_gtls.c:1676:58: note: each undeclared identifier is reported only once for each function it appears in
> nsd_gtls.c:1683:2: error: implicit declaration of function 'gnutls_certificate_type_set_priority' [-Werror=implicit-function-declaration]
>   CHKgnutls(gnutls_certificate_type_set_priority(pThis->sess, cert_type_priority));
>   ^
> cc1: some warnings being treated as errors
> Makefile:1315: recipe for target 'lmnsd_gtls_la-nsd_gtls.lo' failed
> make[2]: *** [lmnsd_gtls_la-nsd_gtls.lo] Error 1
> make[2]: *** Waiting for unfinished jobs....
> make[2]: Leaving directory '/home/abuild/rpmbuild/BUILD/rsyslog-8.9.0/runtime'
> Makefile:919: recipe for target 'all-recursive' failed
> make[1]: *** [all-recursive] Error 1
> make[1]: Leaving directory '/home/abuild/rpmbuild/BUILD/rsyslog-8.9.0'
> Makefile:672: recipe for target 'all' failed
> make: *** [all] Error 2
> error: Bad exit status from /var/tmp/rpm-tmp.xVtwte (%build)

Probably header issue, will investigate later.

**Comment by andreasstieger** [comment]
GnuTLS 3.4 removed functions previously deprecated:
gnutls_certificate_client_set_retrieve_function: Removed
gnutls_certificate_server_set_retrieve_function: Removed 

http://www.gnutls.org/manual/gnutls.html#Upgrading-from-previous-versions

old:
gnutls_certificate_client_set_retrieve_function
gnutls_certificate_server_set_retrieve_function

Replacement:
gnutls_certificate_set_retrieve_function

**Comment by ametzler** [comment]
Hello,

for completeness sake I have two comments about the fix included in 8.13.

**A** the comment in nsd_gtls.c  says:
> The gnutls_certificate_type_set_priority function is deprecated
> and not available in recent GnuTLS versions. However, there is no
> doc how to properly replace it with gnutls_priority_set_direct.

The documentation has been fixed, http://gnutls.org/manual/html_node/Priority-Strings.html includes the certificate type keywords:
> Certificate type	CTYPE-OPENPGP, CTYPE-X509. Catch all is CTYPE-ALL.

i.e. you'd replace
> const int cert_type_priority[3] = { GNUTLS_CRT_X509, GNUTLS_CRT_OPENPGP, 0 };
> gnutls_certificate_type_set_priority(session, cert_type_priority);
with
> gnutls_priority_set_direct(session, "NORMAL:+CTYPE-OPENPGP", NULL);

*B* The fix applied in rsyslog simply drops the call of *gnutls_certificate_type_set_priority()* if it is not available. FWIW this is the correct thing to do, rsyslog uses
cert_type_priority[2] = { GNUTLS_CRT_X509, 0 };
which is the gnutls default value:
> the defaults (in preference order) are for [...] certificate types X.509.

cu Andreas
