### ISSUE TITLE
openssl requires mutual ssl auth even when mode anon is configured

### ISSUE THREAD

**Issue by ctramnitz** [rsyslog/rsyslog#3037]
### Expected behavior

when using
StreamDriver.AuthMode="anon"
client certificates should not be validated.

### Actual behavior

When creating a SSL connection using the ossl stream driver a client certificate is required.

### Steps to reproduce the behavior

Start rsyslog with ossl stream driver and create a SSL session, i.e. using OpenSSL:
openssl s_client -connect <hostname>:6514

Client (openssl s_client) error messages:
140189478406032:error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:s3_pkt.c:1493:SSL alert number 40
140189478406032:error:140790E5:SSL routines:ssl23_write:ssl handshake failure:s23_lib.c:177:

Server (rsyslog with ossl in debug mode) error messages:
3211.367079535:main Q:Reg/w0  : omfile.c: omfile: write to stream, pData->pStrm 0x7f3bb4008200, lenBuf 154, strt data Sep 20 13:06:51 my-rsyslog-server rsyslogd: Error Stack: error:140890C7:SSL routines:ssl3_get_client_certificate:peer did not retur
3211.367086683:main Q:Reg/w0  : omfile.c: omfile: write to stream, pData->pStrm 0x7f3bb4008200, lenBuf 166, strt data Sep 20 13:06:51 my-rsyslog-server rsyslogd: netstream session 0x7f3bb0017e60 from 1.2.3.4 will be closed due to error [v8.37.
3211.367093603:main Q:Reg/w0  : omfile.c: omfile: write to stream, pData->pStrm 0x7f3bb4008200, lenBuf 82, strt data Sep 20 13:06:51 my-rsyslog-server rsyslogd: SSL_ERROR_SSL in 'osslEndSess' [v8.37.0]
3211.367101593:main Q:Reg/w0  : omfile.c: omfile: write to stream, pData->pStrm 0x7f3bb4008200, lenBuf 128, strt data Sep 20 13:06:51 my-rsyslog-server rsyslogd: Error Stack: error:140E0197:SSL routines:SSL_shutdown:shutdown while in init [v8.37.0]

### Environment
- rsyslog version: 8.37.0
- platform: RHEL 7, packages from adiscon repo (not from RH)
- config snippet:
module(load="imtcp"
  StreamDriver.Name="ossl"
  StreamDriver.Mode="1"
  StreamDriver.AuthMode="anon"
  NotifyOnConnectionClose="on"
  MaxSessions="10000"
)

This was (partially) working before with gtls, but I switched due to gtls problems. No with ossl it is even worse...

**Comment by ctramnitz** [comment]
Any idea what might be causing this?

**Comment by alorbach** [comment]
I believe that certless communication is not yet working properly in rsyslog. 
We can implement and allow anon ciphers like we are doing in librelp right now, but this needs to be implemented and ciphers that allow certless communication need to be enabled first.

**Comment by rgerhards** [comment]
@alorbach as far as I understood @ctramnitz this works for gtls. do we have a test for gtls? If not, we should probably add one and validate our assumption.

**Comment by ctramnitz** [comment]
I'm not talking about certless but about "no client authentication" as documented here https://www.rsyslog.com/doc/ns_gtls.html (called "anonymous authentication").
Using that mode the client verifies the server cert, but the server does not require the client to present a cert. From TLS perspective, this is the same as browsing a https resource from your browser...

**Comment by ctramnitz** [comment]
And yes, it does work fine with gtls (but I can't use gtls because the *server* cert cannot be verified, see #2547 )

**Comment by rgerhards** [comment]
Going through this in some more depth. A source of confusion is that by the final RFC5425, "anon" mode authentication is actually prohibited. While it existed in the 12-version of the IETF syslog-wg draft, the final decision was that this is too insecure (and indeed it is, as you never know who acts as man in the middle). And so it was removed from the final version. **The RFC idea is to deploy the same certificate to all clients and use fingerprint auth.**

That said, there still seems to exist a community which wants to use anon mode despite its inherent insecurity. Given the fact that our implementation supported it traditionally, we probably should continue to do so.

side-note: the bug in #2547 for sure can be viewed as a RFC violation (albeit and as always these things could be discussed at length ;-))

**Comment by ctramnitz** [comment]
Can you please reference how this is prohibited? It is described in section 5.3

RFC5425
5.3.  Unauthenticated Transport Sender

   In some environments the authenticity of syslog data is not important
   or is verifiable by other means, so transport receivers may accept
   data from any transport sender.  To achieve this, the transport
   receiver can skip transport sender authentication (by not requesting
   client authentication in TLS or by accepting any certificate).  In
   this case, the transport receiver is authenticated and authorized,
   however this policy does not protect against the threat of transport
   sender masquerade described in Section 2.  The use of this policy is
   generally NOT RECOMMENDED for this reason.

We are talking about the lack of **client** certificates here, the server still has a cert. So this is a standard TLS connection (as mentioned, much a like a browser to a https server). When using a client cert it would be mutual TLS authentication, but there are other methods to authenticate/restrict the clients. The gtls driver did not require a client cert to be used, ossl currently does.

**Comment by rgerhards** [comment]
The GnuTLS driver uses symbol `GTLS_AUTH_CERTANON` for this mode. Quick review (and weak memory) reminds me that in this case it requests a cert, but does more or less no checks at all on it. See https://github.com/rsyslog/rsyslog/blob/master/runtime/nsd_gtls.c#L1141.

I guess we did it that way because that was what the internet draft required to do, in expecting it to become the RFC (maybe even to prove that this mode make no sense, I don't remember...). More smart would obviously have been to use e.g. Diffie-Hellman and not require a certs at all.

For OpenSSL, it looks like the code actually tries to implement the same as in the GnuTLS case, but fails for some reason. Here, the define is `OSSL_AUTH_CERTANON` and is **is** being handled. See these example places:
* https://github.com/rsyslog/rsyslog/blob/master/runtime/nsd_ossl.c#L533
* https://github.com/rsyslog/rsyslog/blob/master/runtime/nsd_ossl.c#L825 (basically same code as in GnuTLS)

To me, this strongly sounds like the intent was to support it, but some bug happened.

I see even a tests inside the testbench, e.g. https://github.com/rsyslog/rsyslog/blob/master/tests/sndrcv_tls_ossl_anon_ipv4.sh. This makes me wonder if something in the tests is wrong or if some environment thingy is triggering a bug. One issue I see is that the cert used seems to be valid, so maybe we should invalidate it to get a more robust test (I assume this would be needed for the equvaltent GnuTLS tests as well).

@ctramnitz do you see any other issue inside the test configuration?

@alorbach With that information, can you check what is going wrong? And maybe update the tests?

**Comment by rgerhards** [comment]
@ctramnitz 

> Can you please reference how this is prohibited? It is described in section 5.3

yup, you are right. I was too focussed on section 4.2, which says
```
Both syslog transport sender (TLS client) and syslog transport
   receiver (TLS server) MUST implement certificate-based
   authentication. 
```
Looks like we did not work hard enough to detect that this is a bit contradictory to Sect. 5.3 and 5.4 (which seems to apply more to the id version 12 "anon" mode). Maybe I can dig out some of the discussion around this (just an academic exercise as we already know what needs to be done).

**Comment by JPvRiel** [comment]
I'm not sure this issue should've been closed

> client certificates should not be validated.

Could be better phrased as 'anon' implies client certificates are optional and may be omitted.

Nonetheless, I opened a new issue related to this given it's not just about skipping client cert validation, but rather, allowing a client to not supply a client cert.

**Comment by ctramnitz** [comment]
This what the config option is currently called. I agree that the naming is not ideal, but this what it is being called, so referencing the official option name makes most sense imho.
