### ISSUE TITLE
omprog: most of the signals blocked

### ISSUE THREAD

**Issue by emilbart** [rsyslog/rsyslog#3050]
Hello,
I use the omprog module in order to send syslog messages to my application written in C.
I noticed that most of the signals are blocked in my program. I figured out that they are blocked by rsyslog. 
I wonder what is the reason for that behaviour (blocked signals)? 
I wonder if I could unblock that signals in my application. Are there any potential risks of that?

PS: I use quite old version of rsyslog (5.10) but I suspect the same behaviour in the latest one.

**Comment by rgerhards** [comment]
As far as I remember, this was necessary to guard the called program against rsyslog's internal signaling. But I am not very sure at the moment. @jsiwrk can you comment?

**Comment by jsiwrk** [comment]
In the current version, rsyslog does not block any signal when forking the child process, except SIGINT ([code](https://github.com/rsyslog/rsyslog/blob/v8.38.0/plugins/omprog/omprog.c#L209-L222)). No idea if it did in version 5.10.

**Comment by emilbart** [comment]
Ok, thanks for answer.
Unfortunately I can not upgrade rsyslog to the latest version. In the version 5.10 the signals are blocked (I checked it). As a workaround I will unblock signals in my C application.
