### ISSUE TITLE
imfile: add a test for "copytruncate" via logrotate itself

### ISSUE THREAD

**Issue by rgerhards** [rsyslog/rsyslog#3053]
@alorbach has created a test with no copytruncate, and it would be useful to have one with copytruncate as well - so that we test "the real thing".

**Comment by alorbach** [comment]
Are you rererring to the imfile-logrotate.sh test? 
We dont have any tests with copytruncate in name.

**Comment by rgerhards** [comment]
I was talking about the mode being used inside the test. But I think it's the one, AFIK we currently have only a single test.

**Comment by rgerhards** [comment]
Thx, I've just seen that test does not explicitely contain "nocopytruncate". I don't remember how I came up with this when I opened the tracker. Maybe it is the default mode.

That said, we probably should better make this explicit and make sure we have two tests, one for each mode.

**Comment by rgerhards** [comment]
doh! it's a typo: it should not have been "nocopytruncate" but "no copytruncate" note the space. At least so it makes sense. 

**BE AWARE: If edit the starter posting and fix the typo!**
