### ISSUE TITLE
Is it possible to request $!metadata!filename without imfile?

### ISSUE THREAD

**Issue by ghost** [rsyslog/rsyslog#3055]
Hi everyone,

I currently have an omprog action configured to send all of my log messages to a python script. The script does some light processing and then sends each log to a database. For querying purposes, I was interested to know whether [the name of the local log file that will receive a log] is available outside of imfile, such as in a template property.

You could use imfile to subscribe to a log file, thereby making $!metadata!filename available to the omprog action. But is it possible to achieve something similar for _all log messages at once_ via a *.* ruleset and / or a template property rather than specifying imfile actions for every log file?

Thank you for your time.

**Comment by davidelang** [comment]
On Mon, 24 Sep 2018, Jackson Parsons wrote:

> I currently have an omprog action configured to send all of my log messages to 
> a python script. The script does some light processing and then sends each log 
> to a database. For querying purposes, I was interested to know whether [the 
> name of the local log file that will receive a log] is available outside of 
> imfile, such as in a template property.

you can't know what file will receive a log (it can be many different files in 
different formats)

> You could use imfile to subscribe to a log file, thereby making 
> $!metadata!filename available to the omprog action. But is it possible to 
> achieve something similar for _all log messages at once_ via a *.* ruleset and 
> / or a template property rather than specifying imfile actions for every log 
> file?

$!metadata!filename is where the log came FROM, not where it is going to go to.

you can make whatever $! or $. variables you want, and set them to whatever 
value you want.

so you could replace:

authpriv.*                                              /var/log/secure

with

authpriv.* {
    /var/log/secure
    set $.type="/var/log/secure";
}

and then use $.type in your omprog logic.

David Lang
