### ISSUE TITLE
testbench: kafka test instabilities

### ISSUE THREAD

**Issue by rgerhards** [rsyslog/rsyslog#3057]
unfortunately, we still have them. 

All recorded kafka test failures: http://build.rsyslog.com/testbench-showtest.php?testname=%kafka%.sh

Samples:

* sequence error
  * https://build.rsyslog.com/#/builders/142/builds/1619
  * https://build.rsyslog.com/#/builders/142/builds/1620
  * https://build.rsyslog.com/#/builders/142/builds/1621
  * https://build.rsyslog.com/#/builders/142/builds/1624
  * https://build.rsyslog.com/#/builders/138/builds/762
  ... and many more - looks like it now fails in 90% of the cases

  * https://build.rsyslog.com/#/builders/137/builds/984 - different one, broker die while rsyslog runs
    For things like this, we could check for "broker died" error messages from rsyslog and, if found, skip the test.

* topic creation error
  * https://build.rsyslog.com/#/builders/137/builds/962

**Comment by rgerhards** [comment]
@alorbach `sndrcv_kafka.sh` skipped in CI as it causes lots of false positives

**Comment by rgerhards** [comment]
I disabled kafka tests in most of the buildbot runs, except where absolutely needed. Add a special builder to carry them out (named "... FLACKY").

**Comment by alorbach** [comment]
PR https://github.com/rsyslog/rsyslog/pull/3101 may solve many of thes instability issues we have seen under load. Because under load, the kafka / zookeeper server may not be finished within previous timeframe of 2 seconds, and shutting down zookeeper before kafka resulted in a hanging kafka server instance (Because kafka tries to connect to zookeeper and this blocks the shutdown).

**Comment by rgerhards** [comment]
see also https://github.com/rsyslog/rsyslog/issues/3088

**Comment by alorbach** [comment]
I guess this can be closed by now?

**Comment by rgerhards** [comment]
Not sure, I see a couple of failures: http://build.rsyslog.com/testbench-showtest.php?testname=%kafka%

Exit code 177 is "system error" (so not of our concern) but 1 should be real failures. We need to investigate if they are indeed real or some part of the test is using wrong exit code.

**Comment by alorbach** [comment]
I see what you mean .

**Comment by rgerhards** [comment]
The past couple of weeks seem to indicate we have fixed this by now.
