### ISSUE TITLE
ommysql support for bulk insert or load file 

### ISSUE THREAD

**Issue by techwizardg** [rsyslog/rsyslog#3083]
We are using rsyslog to parse log files and insert some of the files into mysql using ommysql. The incoming transactions per second for logs is around 4500 TPS and we are able to parse and insert around 900 log entries per second. Is there a way to improve 

a) Does the template support bulk insert to mysql?

Or there are other ways to achieve high throughput. Let me know

**Comment by syed-wasim** [comment]
Try using queues and increase number of threads. I am using rsyslog  for similar purpose and could see around 20K inserts per sec.
