### ISSUE TITLE
rsyslogd: action 'XXX' resumed (module 'omrelp') [v8.31.0 try http://www.rsyslog.com/e/2359 ]

### ISSUE THREAD

**Issue by amazelong** [rsyslog/rsyslog#3087]
### Expected behavior
rsyslog receiver receives normal logs
### Actual behavior
rsyslog receiver receives retransmitted logs about 10 times

/var/log/messages
rsyslogd: omrelp[vendor.log.trpcdn.net:19095]: error 'TLS record write failed [gnutls error -53: Error in the push function.]', object  'conn to srvr vendor.log.trpcdn.net:19095' - action may not work as intended [v8.31.0 try http://www.rsyslog.com/e/2353 ]
rsyslogd: action 'fwd_baishanbilibilicloudlog' suspended (module 'omrelp'), retry 0. There should be messages before this one giving the reason for suspension. [v8.31.0 try http://www.rsyslog.com/e/2007 ]
rsyslogd: action 'fwd_baishanbilibilicloudlog' resumed (module 'omrelp') [v8.31.0 try http://www.rsyslog.com/e/2359 ]

### Steps to reproduce the behavior
TLS link is unreachable at that time ,then the action resumed
### Environment
- rsyslog version: 
- platform: 
- for configuration questions/issues, include rsyslog.conf and included config files
[handler.zip](https://github.com/rsyslog/rsyslog/files/2430452/handler.zip)

rsyslogd 8.31.0, compiled with:
	PLATFORM:				x86_64-unknown-linux-gnu
	PLATFORM (lsb_release -d):		
	FEATURE_REGEXP:				Yes
	GSSAPI Kerberos 5 support:		No
	FEATURE_DEBUG (debug build, slow code):	Yes
	32bit Atomic operations supported:	Yes
	64bit Atomic operations supported:	Yes
	memory allocator:			system default
	Runtime Instrumentation (slow code):	No
	uuid support:				Yes
	Number of Bits in RainerScript integers: 64
centos 
Linux  4.11.8-1.el6.elrepo.x86_64 #1 SMP Thu Jun 29 11:59:49 EDT 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by davidelang** [comment]
rsyslog.conf please

there are failure modes in relp that will cause the log to be retransmitted 
(there are cases where the sender cannot know for sure that the receiver got the 
message, so in those cases, it retransmits it until it gets a positive 
acknowledgement)

However, a system not being up or TLS error should not trigger the failure modes 
that I know about, so I suspect there is something else in the config.

Also, where are you seeing the logs duplicated? on the destination machine (once 
the connectivity is re-established), or on the sender machine in other log 
files?

David Lang

**Comment by amazelong** [comment]
Here is all the config[etc.zip](https://github.com/rsyslog/rsyslog/files/2556792/etc.zip)
Someone see the duplicated logs on the destination, and he told me. I can't access that destination machine

**Comment by rgerhards** [comment]
does the client connect to the same server when the session is re-established? Or is there a load-balancer in between that connects it to another one? RELP resumption requires both client and server to stay the same - or a load balancer who understands RELP protocol.

**Comment by amazelong** [comment]
the client connect to the same server when re-established. no load-balancer.  the client directly to the server using TLS

**Comment by rgerhards** [comment]
I guess this is all caused by the load balancer.

**Comment by rgerhards** [comment]
> i think when TLS down and reconnect, maybe not the same server.

this is not supported by relp
