### ISSUE TITLE
/run/rsyslogd.pid has world writable permissions

### ISSUE THREAD

**Issue by jhelfman** [rsyslog/rsyslog#3103]
### Expected behavior
Permissions on rsyslogd.pid should only be writable by the user and owner that created it.
### Actual behavior
Permission on rsyslod.pid are more open
### Steps to reproduce the behavior
Start ryslogd review permission on /run/ryslogd.pid

### Environment
rsyslog-8.24.0-16.el7_5.4.x86_64

> rsyslogd -v
rsyslogd 8.24.0, compiled with:
	PLATFORM:				x86_64-redhat-linux-gnu
	PLATFORM (lsb_release -d):		
	FEATURE_REGEXP:				Yes
	GSSAPI Kerberos 5 support:		Yes
	FEATURE_DEBUG (debug build, slow code):	No
	32bit Atomic operations supported:	Yes
	64bit Atomic operations supported:	Yes
	memory allocator:			system default
	Runtime Instrumentation (slow code):	No
	uuid support:				Yes
	Number of Bits in RainerScript integers: 64

I am opening this bug as part of a CIS Hardening issue.
CIS Red Hat Enterprise Linux 7 Benchmark v2.2.0
6.1.10 Ensure no world writable files exist

**Comment by jgerhards** [comment]
Does this also occur with the current version (as of now 8.38.0)?

**Comment by jhelfman** [comment]
> Does this also occur with the current version (as of now 8.38.0)?

I am unable to confirm this, as we are running against a supported version from RedHat Enterprise, and haven't attempted to install or upgrade a package that is outside of their update process. I am very familiar to do so, however. Is there any indication in code that this would be fixed in this version as compared to the version I had reported the bug against (v8.24.0)? I suspect that not much would change in a minor release version update, but this is an assumption.

**Comment by strikaco** [comment]
This is not the case on 8.39:

```Nov 29 22:51:51 ip-172-31-20-78 rsyslogd[32408]:  [origin software="rsyslogd" swVersion="8.39.0" x-pid="32408" x-info="http://
Nov 29 22:52:34 ip-172-31-20-78 rsyslogd[32408]:  [origin software="rsyslogd" swVersion="8.39.0" x-pid="32408" x-info="http://
Nov 29 22:52:34 ip-172-31-20-78 systemd[1]: Stopping System Logging Service...
Nov 29 22:52:34 ip-172-31-20-78 systemd[1]: Stopped System Logging Service.

ubuntu@ip-xyz:~$ ls -lh /run/rsyslogd.pid
-rw-r--r-- 1 root root 5 Nov 29 22:54 /run/rsyslogd.pid
```
