### ISSUE TITLE
testbench: es-bulk-retry test unreliable

### ISSUE THREAD

**Issue by alorbach** [rsyslog/rsyslog#3104]
Sometimes elasticsearch tests fail like: 
es-bulk-retry.sh 

**recorded failures: http://build.rsyslog.com/testbench-showtest.php?testname=es-bulk-retry.sh**

See buildbot logs: 
* https://build.rsyslog.com/#/builders/138/builds/809/steps/4/logs/test-suite_log
* https://build.rsyslog.com/#/builders/181/builds/256

**Comment by rgerhards** [comment]
The problem persists, we see frequent failures. Just one sample from today: https://build.rsyslog.com/#/builders/138/builds/1032/steps/4/logs/test-suite_log

@richm can you explain what exactly the error is? "assertion failed" is not very informative ;-) I guess the test is racy, but to try to find better syn we need to better understand what exactly fails.

**Comment by rgerhards** [comment]
@richm Good progress! Here we have a case with the new output: https://build.rsyslog.com/#/builders/144/builds/975/steps/3/logs/test-suite_log

I think the most relevant part is:
```
rsyslogd debug: info: trying to cooperatively stop input impstats, timeout 60000 ms
stopping ES with pid 21129
good - no missing or unexpected records were found in Elasticsearch
FAIL: expected 50 successful responses but omelasticsearch stats reported 49
FAIL: The sum of the number of successful responses and bad argument errors and bulk index rejections 217 did not equal the number of requests actually submitted to Elasticsearch 218
```

From that, I would guess that it is "the usual race" we have during shutdown. We should find a way, while rsyslog runs, to check that we got all lines and timeout if not. I'll also see to have a look at the test as soon as a I can.

**Comment by rgerhards** [comment]
yeah, that was my first thought. But it's actually counter values, so we cannot do a simple `grep`. Would it be a solution to not reset counters and then do a `grep` for the exact line? Else we probably need to extend the python a bit, this time probably as real script that we can use in two places. @richm what do you think?

**Comment by richm** [comment]
> Would it be a solution to not reset counters and then do a grep for the exact line?

not sure - how would you reset counters?

**Comment by rgerhards** [comment]
let me check - I thought you had enabled that impstats option...

**Comment by rgerhards** [comment]
@richm my fault - it's not set. So let me see if I can simply `grep` for it...

**Comment by rgerhards** [comment]
I am pretty sure that the `sleep` that is used during shutdown processing is the culprit. I will change this to a better method, but need to complete some related work that I then can build upon - hopefully tomorrow.

@richm thanks again for the new error messages, this is very helpful!
