### ISSUE TITLE
lmsig_ksils12: the module skips the signature of the last block in the file in certain conditions

### ISSUE THREAD

**Issue by allanpark** [rsyslog/rsyslog#3105]
### Expected behaviour
All blocks in the blocks file file must have matching signature element inthe signatures file

### Actual behaviour
In case of async mode and http protocol and certain conditions the last block can lack the 
signature. 

### Steps to reproduce the behaviour
* Configure the module with async mode and http protocol
* Flood the daemon with messages
* During flooding stop or -HUP the module

### Environment
- rsyslog version: 8.38
- platform: centos 7

**Comment by jgerhards** [comment]
Does this occur when using dynafile or regular? Could you post your rsyslog.conf file?

**Comment by allanpark** [comment]
This was tested using regular log file but would happen with dynafile too and it is caused by a bug in runtime/lib_ksils12.c:1281 and a fix can be seen here:
https://github.com/allanpark/rsyslog/commit/52e58be929a0c72c38a2b66f64df55f4b370da31
