### ISSUE TITLE
error message on missing .qi file on clean queue startup (which is normal)

### ISSUE THREAD

**Issue by ChristopheHubert72** [rsyslog/rsyslog#3117]
### Expected behavior
disk assisted queue Files are created

### Actual behavior
Error saying that files are absent
rsyslogd - - -  file '/opt/rsyslog/work/mainq.qi': open error: No such file or directory [v8.38.0 try http://www.rsyslog.com/e/2040 ]
Files are not created

### Steps to reproduce the behavior
Create a queue with a folder for assisted queue file

### Environment
- rsyslog version: rsyslog-8.38.0-1.el7.x86_64 from repo
- platform: Centos7 with home made 4.18 Kernel

Extract of the configuration : 
[...]
main_queue(
  queue.type="linkedList"
  queue.spoolDirectory="/opt/rsyslog/work"
  queue.fileName="mainq"
[...]

I have strace the process at start, and it tries to open the file but it does not use O_CREAT, so as the file does not exist, it fails :
13324 10:41:45.013177 open("/opt/rsyslog/work/srvfwd2.qi", O_RDONLY|O_NOCTTY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
13324 10:41:45.013381 stat("/opt/rsyslog/work/mainq.qi", 0x7ffcd653fd20) = -1 ENOENT (No such file or directory)
13324 10:41:45.013412 open("/opt/rsyslog/work/mainq.qi", O_RDONLY|O_NOCTTY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
13324 10:41:45.013455 write(2, "rsyslogd: file '/opt/rsyslog/work/mainq.qi': open error: No such file or directory [v8.38.0 try http://www.rsyslog.com/e/2040 ]\n", 128) = 128
13324 10:41:45.013511 open("/opt/rsyslog/work/mainq.qi", O_RDONLY|O_NOCTTY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

 Folder exist (tmpfs), is writable for all (777) and have enough free space (200M)

**Comment by rgerhards** [comment]
There seems to be a regression that the open file error is displayed. At this point, it is totally normal that the .qi file does not exist (assuming the queue had a clean shutdown and stores no data).

More info on when files are created: https://rainer.gerhards.net/2013/07/rsyslog-why-disk-assisted-queues-keep-a-file-open.html

**Comment by rgerhards** [comment]
assigning "potential bug" in regard to the invalid error message.

**Comment by ChristopheHubert72** [comment]
My bad, I though they were created at start. But, yes, the error message is misleading in that case.

**Comment by rgerhards** [comment]
> Here this seems to be a real problem – rsyslog is switching to pure in-memory mode.

From your postings, this indeed sounds problematic. However, it has nothing to do with the message that you see (99.9% sure, will verify). I would expect that we see a more explanatory error message, though.

If you can reproduce this, could you create a debug log for me to review? That should clearly show what is happening.

**Comment by rgerhards** [comment]
@DirkSchmitt if you can reproduce the problem with the queue files, please create a new issue for that. This one here will be closed when the invalid error message is fixed.
