### ISSUE TITLE
rsyslogd SIGSEGV during Linux shutdown

### ISSUE THREAD

**Issue by showalski** [rsyslog/rsyslog#3122]
### Expected behavior
Rsyslogd should be shutdown without errors
#### Console info got from kernel

> [16638.279145] rsyslogd[22747]: unhandled level 0 translation fault (11) at 0x30312d38313032, esr 0x92000004, in libc-2.22.so[ffffb25db000+115000]
> [16638.292065] CPU: 1 PID: 22747 Comm: rsyslogd Tainted: G           O    4.14.16 #1
> [16638.305178] task: ffff8080bd62f140 task.stack: ffff00000bad0000
> [16638.311110] PC is at 0xffffb264b508
> [16638.314594] LR is at 0x418310
> [16638.317563] pc : [<0000ffffb264b508>] lr : [<0000000000418310>] pstate: 00000000
> [16638.324959] sp : 0000fffff2d888b0
> [16638.328274] x29: 0000fffff2d888b0 x28: 0000000000000000
> [16638.333585] x27: 0000000000000000 x26: 0000000000000000
> [16638.338904] x25: 00000000004646f9 x24: 00000000004646f9
> [16638.344215] x23: 0000000000468f71 x22: 0000fffff2d88928
> [16638.349532] x21: 2d30312d38313032 x20: 000000000000014e
> [16638.354843] x19: 0000ffffac004500 x18: 0000000000000000
> [16638.360162] x17: 0000ffffb264b480 x16: 000000000048a528
> [16638.365472] x15: 0000000000000018 x14: 0033db2580000000
> [16638.370789] x13: 000000005bbdf60f x12: 0101010101010101
> [16638.376100] x11: 0000000000000020 x10: 0101010101010101
> [16638.381418] x9 : 0000000000000004 x8 : 7f7f7f7f7f7f7fff
> [16638.386729] x7 : 2d30312d3877bf43 x6 : 0000000000000001
> [16638.392050] x5 : 000000000000017f x4 : 000000000000007c
> [16638.397369] x3 : 0000000000001745 x2 : 0000000000001f40
> [16638.402681] x1 : 0000000000468f71 x0 : 2d30312d38313032
>
Below info was got from core file

> #0  0x0000ffffb264b508 in ?? ()
> #1  0x0000000000418310 in msgDestruct (ppThis=ppThis@entry=0xfffff2d88928) at msg.c:932
> #2  0x0000000000431248 in queueDrain (pThis=pThis@entry=0x15830490) at queue.c:337
> #3  0x0000000000431294 in qDestructFixedArray (pThis=0x15830490) at queue.c:554
> #4  0x0000000000432a0c in qqueueDestruct (ppThis=ppThis@entry=0x4917a0 <loadModConf>) at queue.c:2683
> #5  0x000000000040e970 in deinitAll () at rsyslogd.c:1600
> #6  main (argc=<optimized out>, argv=<optimized out>) at rsyslogd.c:1663

> (gdb) print *(struct queue_s*)0x15830490
> $13 = {objData = {pObjInfo = 0x15819970, iObjCooCKiE = 195948526, pszName = 0x15837080 "main Q"}, qType = QUEUETYPE_FIXED_ARRAY, nLogDeq = 336, bShutdownImmediate = 0,
>   bEnqOnly = 1 '\001', bSaveOnShutdown = 1 '\001', bQueueStarted = 1 '\001', iQueueSize = 334, iMaxQueueSize = 8000, iNumWorkerThreads = 2, iCurNumWrkThrd = 0,
>   iMinMsgsPerWrkr = 4000, pWtpDA = 0x0, pWtpReg = 0x0, pAction = 0x0, iUpdsSincePersist = 26250964, iPersistUpdCnt = 0, bSyncQueueFiles = 0 '\000', iHighWtrMrk = 7200,
>   iLowWtrMrk = 0, iDiscardMrk = 1600, iFullDlyMrk = 3600, iLightDlyMrk = 5600, iDiscardSeverity = 7, bNeedDelQIF = 0 '\000', toQShutdown = 1500, toActShutdown = 1000,
>   toWrkShutdown = 60000, toDeleteLst = 0x0, toEnq = 0, iDeqBatchSize = 256, iDeqSlowdown = 0, iDeqtWinFromHr = 0, iDeqtWinToHr = 25, pConsumer = 0x445710 <msgConsumer>,
>   qConstruct = 0x432c10 <qConstructFixedArray>, qDestruct = 0x431280 <qDestructFixedArray>, qAdd = 0x430a38 <qAddFixedArray>, qDeq = 0x430a68 <qDeqFixedArray>,
>   qDel = 0x430a9c <qDelFixedArray>, MultiEnq = 0x4332e4 <qqueueMultiEnqObjNonDirect>, mutThrdMgmt = {__data = {__lock = 0, __count = 0, __owner = 0, __nusers = 0, __kind = -1,
>       __spins = 0, __list = {__prev = 0x0, __next = 0x0}}, __size = '\000' <repeats 16 times>, "\377\377\377\377", '\000' <repeats 27 times>, __align = 0}, mut = 0x15830920,
>   notFull = {__data = {__lock = 1, __futex = 0, __total_seq = 18446744073709551615, __wakeup_seq = 0, __woken_seq = 0, __mutex = 0x0, __nwaiters = 0, __broadcast_seq = 0},
>     __size = "\001\000\000\000\000\000\000\000\377\377\377\377\377\377\377\377", '\000' <repeats 31 times>, __align = 1}, belowFullDlyWtrMrk = {__data = {__lock = 1,
>       __futex = 0, __total_seq = 18446744073709551615, __wakeup_seq = 0, __woken_seq = 0, __mutex = 0x0, __nwaiters = 0, __broadcast_seq = 0},
>     __size = "\001\000\000\000\000\000\000\000\377\377\377\377\377\377\377\377", '\000' <repeats 31 times>, __align = 1}, belowLightDlyWtrMrk = {__data = {__lock = 1,
>       __futex = 0, __total_seq = 18446744073709551615, __wakeup_seq = 0, __woken_seq = 0, __mutex = 0x0, __nwaiters = 0, __broadcast_seq = 0},
>     __size = "\001\000\000\000\000\000\000\000\377\377\377\377\377\377\377\377", '\000' <repeats 31 times>, __align = 1}, bThrdStateChanged = 0,
>   pszSpoolDir = 0x15837ea0 "/tmp/sw", lenSpoolDir = 7, pszFilePrefix = 0x15830900 "actionq", lenFilePrefix = 7, pszQIFNam = 0x0, lenQIFNam = 0, iNumberFiles = 0,
>   iMaxFileSize = 1048576, sizeOnDiskMax = 8388608, deqIDAdd = 12975145, deqIDDel = 12975146, bIsDA = 1, pqDA = 0x0, pqParent = 0x0, bDAEnqOnly = 0, tVars = {farray = {
>       deqhead = 5958, head = 5621, tail = 5956, pBuf = 0x1586bef0}, linklist = {pDeqRoot = 0x0, pDelRoot = 0x0, pLast = 0x0}, disk = {sizeOnDisk = 0, deqOffs = 0,
>       deqFileNumIn = 0, deqFileNumOut = 0, pWrite = 0x0, pReadDeq = 0x0, pReadDel = 0x0, nForcePersist = 0}}, useCryprov = 0 '\000', cryprovName = 0x0, cryprov = {
>     ifVersion = 0, ifIsLoaded = 0, Construct = 0x0, SetCnfParam = 0x0, Destruct = 0x0, OnFileOpen = 0x0, Encrypt = 0x0, Decrypt = 0x0, OnFileClose = 0x0,
>     DeleteStateFiles = 0x0, GetBytesLeftInBlock = 0x0, SetDeleteOnClose = 0x0}, cryprovData = 0x0, cryprovNameFull = 0x0, mutQueueSize = {__data = {__lock = 0, __count = 0,
>       __owner = 0, __nusers = 0, __kind = -1, __spins = 0, __list = {__prev = 0x0, __next = 0x0}},
>     __size = '\000' <repeats 16 times>, "\377\377\377\377", '\000' <repeats 27 times>, __align = 0}, mutLogDeq = {__data = {__lock = 0, __count = 0, __owner = 0, __nusers = 0,
>       __kind = -1, __spins = 0, __list = {__prev = 0x0, __next = 0x0}}, __size = '\000' <repeats 16 times>, "\377\377\377\377", '\000' <repeats 27 times>, __align = 0},
>   statsobj = 0x15886aa0, ctrEnqueued = 0, mutCtrEnqueued = {__data = {__lock = 0, __count = 0, __owner = 0, __nusers = 0, __kind = 0, __spins = 0, __list = {__prev = 0x0,
>         __next = 0x0}}, __size = '\000' <repeats 47 times>, __align = 0}, ctrFull = 0, mutCtrFull = {__data = {__lock = 0, __count = 0, __owner = 0, __nusers = 0, __kind = 0,
>       __spins = 0, __list = {__prev = 0x0, __next = 0x0}}, __size = '\000' <repeats 47 times>, __align = 0}, ctrFDscrd = 0, mutCtrFDscrd = {__data = {__lock = 0, __count = 0,
>       __owner = 0, __nusers = 0, __kind = 0, __spins = 0, __list = {__prev = 0x0, __next = 0x0}}, __size = '\000' <repeats 47 times>, __align = 0}, ctrNFDscrd = 0,
>   mutCtrNFDscrd = {__data = {__lock = 0, __count = 0, __owner = 0, __nusers = 0, __kind = 0, __spins = 0, __list = {__prev = 0x0, __next = 0x0}},
>     __size = '\000' <repeats 47 times>, __align = 0}, ctrMaxqsize = 0}
> (gdb) info locals
> pMsg = 0xffffac004500
>
### Steps to reproduce the behavior
System reboot
### Environment
- rsyslog version: 8.21.0
- platform: Linux 7ABD44F80040 4.14.16 #3 SMP Fri Oct 12 04:51:05 UTC 2018 aarch64 GNU/Linux
- for configuration questions/issues, include rsyslog.conf and included config files. Recently we made changes to rsyslog rules:
>  $OMUxSockSocket /tmp/sw/fm_sock5
> +$WorkDirectory /tmp/sw
> +$ActionQueueFileName actionq5
> +$ActionQueueMaxDiskSpace 1m
> +$ActionQueueTimeoutEnqueue 0
> +$ActionQueueDiscardMark 2000
> +$ActionQueueSize 10000
> +$ActionQueueDiscardSeverity 6

I think this issue should be freeing invalid memory in msgDestruct(). In queueDrain() value of local variable pMsg is :
> pMsg = 0xffffac004500
>
which is assigned from qDeqFixedArray(). It should be an invalid address and should be 0x15877920 based on `pThis->tVars.farray.pBuf[pThis->tVars.farray.deqhead]`. By the way msg_t decoded from  0x15877920 is invalid also.

Please help to check this issue. Thanks in advance.

**Comment by jgerhards** [comment]
This is an old version of rsyslog - does this also happen in the current (now: 8.38.0) version?

**Comment by showalski** [comment]
Thanks for replying. 

We are using rsyslog in production box and haven't test on 8.38 yet.  below rules were newly added:

```
 $OMUxSockDefaultTemplate Fault_manager_fmt
+$WorkDirectory /tmp/sw
+$MainMsgQueueFileName actionq
+$MainMsgQueueMaxDiskSpace 8m
+$MainMsgQueueDiscardMark 1600
+$MainMsgQueueSize 8000
+$MainMsgQueueDiscardSeverity 7
+$MainMsgQueueTimeoutEnqueue 0
 
 $OMUxSockSocket /tmp/sw/fm_sock0
+$WorkDirectory /tmp/sw
+$ActionQueueFileName actionq0
+$ActionQueueMaxDiskSpace 1m
+$ActionQueueTimeoutEnqueue 0
+$ActionQueueDiscardMark 2000
+$ActionQueueSize 10000
+$ActionQueueDiscardSeverity 6
 if ($msg startswith " INSTANCE_ID0-66070" or $msg startswith " INSTANCE_ID0-0x8009") then :omuxsock:
 
 $OMUxSockSocket /tmp/sw/fm_sock1
+$WorkDirectory /tmp/sw
+$ActionQueueFileName actionq1
+$ActionQueueMaxDiskSpace 1m
+$ActionQueueTimeoutEnqueue 0
+$ActionQueueDiscardMark 2000
+$ActionQueueSize 10000
+$ActionQueueDiscardSeverity 6
 if ($msg startswith " INSTANCE_ID1-66070" or $msg startswith " INSTANCE_ID1-0x8009") then :omuxsock:
 
 $OMUxSockSocket /tmp/sw/fm_sock2
+$WorkDirectory /tmp/sw
+$ActionQueueFileName actionq2
+$ActionQueueMaxDiskSpace 1m
+$ActionQueueTimeoutEnqueue 0
+$ActionQueueDiscardMark 2000
+$ActionQueueSize 10000
+$ActionQueueDiscardSeverity 6
 if ($msg startswith " INSTANCE_ID2-66070" or $msg startswith " INSTANCE_ID2-0x8009") then :omuxsock:
 
 $OMUxSockSocket /tmp/sw/fm_sock3
+$WorkDirectory /tmp/sw
+$ActionQueueFileName actionq3
+$ActionQueueMaxDiskSpace 1m
+$ActionQueueTimeoutEnqueue 0
+$ActionQueueDiscardMark 2000
+$ActionQueueSize 10000
+$ActionQueueDiscardSeverity 6
 if ($msg startswith " INSTANCE_ID3-66070" or $msg startswith " INSTANCE_ID3-0x8009") then :omuxsock:
 
 $OMUxSockSocket /tmp/sw/fm_sock4
+$WorkDirectory /tmp/sw
+$ActionQueueFileName actionq4
+$ActionQueueMaxDiskSpace 1m
+$ActionQueueTimeoutEnqueue 0
+$ActionQueueDiscardMark 2000
+$ActionQueueSize 10000
+$ActionQueueDiscardSeverity 6
 if ($msg startswith " INSTANCE_ID4-66070" or $msg startswith " INSTANCE_ID4-0x8009") then :omuxsock:
 
 $OMUxSockSocket /tmp/sw/fm_sock5
+$WorkDirectory /tmp/sw
+$ActionQueueFileName actionq5
+$ActionQueueMaxDiskSpace 1m
+$ActionQueueTimeoutEnqueue 0
+$ActionQueueDiscardMark 2000
+$ActionQueueSize 10000
+$ActionQueueDiscardSeverity 6
 if ($msg startswith " INSTANCE_ID5-66070" or $msg startswith " INSTANCE_ID5-0x8009") then :omuxsock:
```
After issuing reboot command in Linux terminal, I think everything in the /tmp/sw was deleted and rsyslog might trying to free memory in /tmp/sw. Is it possible?

**Comment by rgerhards** [comment]
Well, if on startup the work directory is empty, rsyslog just accepts that fact.

In order to proceed forward, we would need to see this with the current version, especially as yours is veeeery old. To be blunt, I have too often (almost always) seen that it is waste of my time to try to troubleshoot these things in old versions - it usually turns out (after some hours...) that this is a known and fixed issue. If you absolutely want to keep the old version, you could give Adiscon's professional service a try, where we support old versions in addition to the current ones:  https://www.rsyslog.com/professional-services/

**Comment by rgerhards** [comment]
> If need upgrade, which version is the best? 8.38?

The community only supports the *current* version. Well, sometimes we look at old ones, but as I said... Right now, the current version is 8.38.

**Comment by showalski** [comment]
Got it. Please close this issue
