### ISSUE TITLE
GnuTLS error -64, message: 'Error while reading file.', key: '(null)', cert: '(null)'

### ISSUE THREAD

**Issue by MiiguelTeleco** [rsyslog/rsyslog#3156]
Hi,
I am trying to configure TLS in rsyslog but GnuTLS is returning an error while reading parm certificate.
I tried these two configurations:

> 
> $DefaultNetstreamDriver gtls
> $DefaultNetstreamDriverCAFile /etc/rsyslog.pem/qradar.pem
> $ActionSendStreamDriverMode 1
> $ActionSendStreamDriverAuthMode anon
> *.* @@(o)host:6514

> *.* action(type="omfwd" protocol="tcp" Target="host" Port="6514" StreamDriverMode="1" StreamDriver="gtls" StreamDriverAuthMode="anon")

I always get next error in messages:

> Oct 22 16:29:50 kernel: imklog 5.8.10, log source = /proc/kmsg started.
Oct 22 16:29:50  rsyslogd: [origin software="rsyslogd" swVersion="5.8.10" x-pid="18454" x-info="http://www.rsyslog.com"] start
Oct 22 16:29:51 rsyslogd-2078: error adding our certificate. GnuTLS error -64, message: 'Error while reading file.', key: '(null)', cert: '(null)' [try http://www.rsyslog.com/e/2078 ]
Oct 22 16:29:51 rsyslogd-2078: Could not create tcp listener, ignoring port 514. [try http://www.rsyslog.com/e/2078 ]

The parm file should be correctly because It is downloaded directly from a Qradar system. It also has the correct permissions. 

I post some information about my rsyslog (I know It is too old but It is not under my control..)

> rsyslogd -v
> rsyslogd 5.8.10, compiled with:
> 	FEATURE_REGEXP:				Yes
> 	FEATURE_LARGEFILE:			No
> 	GSSAPI Kerberos 5 support:		Yes
> 	FEATURE_DEBUG (debug build, slow code):	No
> 	32bit Atomic operations supported:	Yes
> 	64bit Atomic operations supported:	Yes
> 	Runtime Instrumentation (slow code):	No

> 
> Platform: 
> CentOS release 6.8 (Final)

Rsyslog.conf:

> 
> $ModLoad imuxsock 
> $ModLoad imklog   
> #$ModLoad immark 
> 
> $ModLoad imudp
> $UDPServerRun 514
> 
> $ModLoad imtcp
> $InputTCPServerRun 514
> 
> $ModLoad imfile
> $InputFileName log.log
> $InputFileTag log-log
> $InputFileStateFile stat-log-log
> $InputFileSeverity debug
> $InputFileFacility local3
> $InputRunFileMonitor
> 
> $ActionFileDefaultTemplate RSYSLOG_TraditionalFileFormat
> $IncludeConfig  /etc/rsyslog.d/*.conf
> :fromhost-ip, isequal, "some_ip" /var/log/some_host.log
> & ~
> *.info;mail.none;authpriv.none;cron.none                /var/log/messages
> authpriv.*                                              /var/log/secure
> mail.*                                                  -/var/log/maillog
> cron.*                                                  /var/log/cron
> *.emerg                                                 *
> uucp,news.crit                                          /var/log/spooler
> local7.*                                                /var/log/boot.log
> local3.*                                                @@some_machine
> 
> $DefaultNetstreamDriver gtls
> $DefaultNetstreamDriverCAFile /etc/rsyslog.pem/qradar.pem
> $ActionSendStreamDriverMode 1
> $ActionSendStreamDriverAuthMode anon
> *.* @@(o)host:6514
> 
> 

Thanks!

**Comment by rgerhards** [comment]
Honestly, I do not remember how it worked 6+ years ago. I suggest to update to the current community supported-version (8.38.0). The error messages doesn't trigger anything in my mind, maybe it's just a bug.

**Comment by rgerhards** [comment]
side-note: gnutls is extremely picky in regard to certificate fields and provides very bad error messages. so maybe something is wrong with the cert. I would usually suggest to use the openssl driver instead, but that was written this year.

**Comment by MiiguelTeleco** [comment]
Hi, thanks for your answer. I will try to update rsyslog version. However, despite the fact that openssl have been written this year, can I use it with 5.8.10?
Thanks!

**Comment by MiiguelTeleco** [comment]
Okey no, I can't. From official documentation:  Available since: | 8.36.0.
Thanks. I close this issue because, as you said, my rsyslog version has no sense at this time.
