### ISSUE TITLE
error starting up disk queue, using pure in-memory mode

### ISSUE THREAD

**Issue by DirkSchmitt** [rsyslog/rsyslog#3164]
### Actual behavior

see also comment to  #3117:

Here this seems to be a real problem – rsyslog is switching to pure in-memory mode.
After reboot I see on several machines running debian stretch the following error messages:

Oct 18 10:13:09 kelly rsyslogd[15953]: imuxsock: Acquired UNIX socket '/run/systemd/journal/syslog' (fd 3) from systemd.  [v8.38.0]
Oct 18 10:13:09 kelly rsyslogd[15953]: error starting up disk queue, using pure in-memory mode [v8.38.0 try http://www.rsyslog.com/e/2026 ]
Oct 18 10:13:09 kelly rsyslogd[15953]: action-0-omrelp.so queue: error creating disk queue - giving up. [v8.38.0 try http://www.rsyslog.com/e/2026 ]
Oct 18 10:13:09 kelly rsyslogd[15953]: file '/var/spool/rsyslog/queueMain.qi': open error: No such file or directory [v8.38.0 try http://w…om/e/2040 ]

### Steps to reproduce the behavior

Not after every reboot - but recurring.

### Environment
Debian stretch –  rsyslog  8.38.0-1~bpo9+1   amd64

**Comment by rgerhards** [comment]
can you provide a debug log?

**Comment by DirkSchmitt** [comment]
For 7 days below: http://user.computer42.org/~dirk/tmp/rsyslog.debug.log.xz

**Comment by rgerhards** [comment]
thx, relevant part of debug log (for easier review):
```
3663.124127995:main thread    : stream.c: file '/var/spool/rsyslog/queueCentralLogging.qi' opened as #8 with mode 384
3663.124153314:main thread    : strm 0x55a976f3c510: stream.c: opened file '/var/spool/rsyslog/queueCentralLogging.qi' for READ as 8
3663.124171290:main thread    : strm 0x55a976f3c510: stream.c: file 8 read 0 bytes
3663.124184405:main thread    : obj.c: objDeserializePropBag error -2026 during header - trying to recover
3663.124199645:main thread    : strm 0x55a976f3c510: stream.c: file 8 read 0 bytes
3663.124212401:main thread    : obj.c: deserializer has possibly been able to re-sync and recover, state -2026
3663.124225720:main thread    : strm 0x55a976f3c510: stream.c: file 8(/var/spool/rsyslog/queueCentralLogging.qi) closing, bDeleteOnClose 0
3663.124246887:main thread    : action-0-omrelp.so queue[DA]: queue.c: state -2026 reading .qi file - can not read persisted info (if any)
3663.124261071:main thread    : errmsg.c: Called LogMsg, msg: error starting up disk queue, using pure in-memory mode
```

**Comment by rgerhards** [comment]
state -2016 is EOF. And indeed `strm 0x55a976f3c510: stream.c: file 8 read 0 bytes` shows that the state file is empty. So it looks like it was/could not properly persisted on shutdown. Unfortunately this means I need to get hold of a debug form a run A during shutdown where the next run B experiences the issue. Otherwise we cannot know what happens... :-(

**Comment by DirkSchmitt** [comment]
Shutdown? Do you mean shutdown of the rsyslog daemon or the whole machine?

**Comment by rgerhards** [comment]
shutdown of rsyslog - but maybe the problem occurs only when the whole machine is shutdown.

**Comment by rgerhards** [comment]
Any chance to get the debug log (of shutdown)?

**Comment by mattpr** [comment]
Howdy.  I have the same issue.  Captured two cycles of start and shutdown of debug.  Hope it helps.

https://www.dropbox.com/s/xvr8pxjl3tttoin/rsyslog-disk-queue.log.zip?dl=0

**Comment by Ajith0888** [comment]
I also faced the same issue and it increases my server load very badly. Like a workaround, I have performed the restart of the *rsyslog.service* and helps to fix the issue. 

systemctl restart rsyslog.service

**Comment by rgerhards** [comment]
no debug info ever received

**Comment by rawal1500** [comment]
6409.051845968:main thread    : rsconf.c: Main queue size 100000 messages.
6409.051851062:main thread    : rsconf.c: Main queue worker threads: 8, wThread shutdown: 60000, Perists every 0 updates.
6409.051856263:main thread    : rsconf.c: Main queue timeouts: shutdown: 1500, action completion shutdown: 1000, enq: 2000
6409.051861631:main thread    : rsconf.c: Main queue watermarks: high: 80000, low: 20000, discard: 98000, discard-severity: 8
6409.051867651:main thread    : rsconf.c: Main queue save on shutdown 1, max disk space allowed 0
6409.051874409:main thread    : rsconf.c: Work Directory: '/var/spool/rsyslog'.
6409.051880462:main thread    : rsconf.c: Modules used in this configuration:

**Comment by rawal1500** [comment]
@rgerhards please provide the solution 

facing error: Jan 30 06:35:02 sfsgplvtmlf01 rsyslogd[1862344]: error starting up disk queue, using pure in-memory mode [v8.2112.0 try https://www.rsyslog.com/e/2026 ]
Jan 30 06:35:02 sfsgplvtmlf01 rsyslogd[1862344]: main Q: error creating disk queue - giving up. [v8.2112.0 try https://www.rsyslog.com/e/2026 ]

**Comment by rawal1500** [comment]
here is my rsyslog configuration:  
# Eventus Security Data Lake Logger Configuration for on premises

module(
  load="impstats"
  interval="10"             # how often to generate stats
  resetCounters="off"        # to get deltas (e.g. # of messages submitted in the last 10 seconds)
  log.file="/tmp/stats"     # file to write those stats to
  log.syslog="off"          # don't send stats through the normal processing pipeline. More on that in a bit
)


# /etc/rsyslog.conf configuration file for rsyslog
#
# For more information install rsyslog-doc and see
# /usr/share/doc/rsyslog-doc/html/configuration/index.html
#
# Default logging rules can be found in /etc/rsyslog.d/50-default.conf

#################
#### MODULES ####
#################

module(load="imuxsock") # provides support for local system logging
module(load="immark")  # provides --MARK-- message capability

module(load="imudp")  # Allocate for imudp
input(type="imudp" port="9002")

module(load="imtcp")  # Allocate for imtcp
input(type="imtcp" port="9001")

module(load="imklog" permitnonkernelfacility="off") # provides kernel logging support and enables non-kernel klog messages
module(load="omrelp" tls.tlslib="openssl")  # Load omrelp with OpenSSL TLS support

$MainMsgQueueFileName disk-assisted
$MaxMessageSize 64k
$MainMsgQueueWorkerThreads 8

###########################
#### GLOBAL DIRECTIVES ####
###########################

$ActionFileDefaultTemplate RSYSLOG_TraditionalFileFormat
$RepeatedMsgReduction on

$FileOwner syslog
$FileGroup adm
$FileCreateMode 0640
$DirCreateMode 0755
$Umask 0022
$PrivDropToUser syslog
$PrivDropToGroup syslog

$WorkDirectory /var/spool/rsyslog
$IncludeConfig /etc/rsyslog.d/*.conf

###############
#### RULES ####
###############

#auth,authpriv.*                 /var/log/auth.log
*.*;auth,authpriv.none          -/var/log/esdl.log
daemon.*                        -/var/log/daemon.log
kern.*                          -/var/log/kern.log
lpr.*                           -/var/log/lpr.log
mail.*                          -/var/log/mail.log
#user.*                          -/var/log/user.log

mail.info                       -/var/log/mail.info
mail.warn                       -/var/log/mail.warn
mail.err                        /var/log/mail.err

*.=debug;\
        auth,authpriv.none;\
        mail.none               -/var/log/debug
#*.=info;*.=notice;*.=warn;\
 #       auth,authpriv.none;\
  #      cron,daemon.none;\
   #     mail.none               -/var/log/messages

*.emerg                         :omusrmsg:*

# Set gtls driver
$DefaultNetstreamDriver gtls

$template FortigateTemplate,"%msg% tenant=StraitsFinancial productName=Fortigate productType=firewall logType=network\n"
$template DeepSecurityTemplate,"%msg% tenant=StraitsFinancial productName=Deep Security productType=Server Security logType=endpoint\n"
$template ErrorTemplate,"%msg% tenant=StraitsFinancial logType=error\n"
$template NoTemplate,"%msg% tenant=StraitsFinancial logType=other\n"


# Queue configuration
$ActionQueueType LinkedList
$ActionQueueFileName disk-assisted
$ActionResumeRetryCount -1
$ActionResumeInterval 1
$ActionQueueSize 250000
$ActionQueueMaxDiskSpace 10g
$ActionQueueSyncQueueFiles on
$ActionQueueDequeueBatchSize 4096
$ActionQueueWorkerThreads 6  # Use the remaining 6 threads for queue processing and other tasks
$ActionQueueWorkerThreadMinimumMessages 25000
$ActionQueueSaveOnShutdown on
$ActionQueueTimeoutEnqueue 10

if $msg contains "devid=" then {
    action(
        type="omrelp"
        target="listener01-sg.eventussecurity.com"
        port="20515"
        timeout="5"
        conn.timeout="3"
        tls="on"
        template="FortigateTemplate"
        tls.cacert="/etc/ssl/rsyslog/CA.pem"
        tls.mycert="/etc/ssl/rsyslog/client-cert.pem"
        tls.myprivkey="/etc/ssl/rsyslog/client-key.pem"
        tls.authmode="certvalid"
        tls.permittedpeer="eventus"
    )
}

else if $msg contains "Deep Security Agent" then {
    action(
        type="omrelp"
        target="listener01-sg.eventussecurity.com"
        port="20515"
        timeout="5"
        conn.timeout="3"
        tls="on"
        template="DeepSecurityTemplate"
        tls.cacert="/etc/ssl/rsyslog/CA.pem"
        tls.mycert="/etc/ssl/rsyslog/client-cert.pem"
        tls.myprivkey="/etc/ssl/rsyslog/client-key.pem"
        tls.authmode="certvalid"
        tls.permittedpeer="eventus"
    )
}

else if $msg contains "www.rsyslog.com" then {
    action(
        type="omrelp"
        target="listener01-sg.eventussecurity.com"
        port="20515"
        timeout="5"
        conn.timeout="3"
        tls="on"
        template="ErrorTemplate"
        tls.cacert="/etc/ssl/rsyslog/CA.pem"
        tls.mycert="/etc/ssl/rsyslog/client-cert.pem"
        tls.myprivkey="/etc/ssl/rsyslog/client-key.pem"
        tls.authmode="certvalid"
        tls.permittedpeer="eventus"
    )
}

else {
    action(
        type="omrelp"
        target="listener01-sg.eventussecurity.com"
        port="20515"
        timeout="5"
        conn.timeout="3"
        tls="on"
        template="NoTemplate"
        tls.cacert="/etc/ssl/rsyslog/CA.pem"
        tls.mycert="/etc/ssl/rsyslog/client-cert.pem"
        tls.myprivkey="/etc/ssl/rsyslog/client-key.pem"
        tls.authmode="certvalid"
        tls.permittedpeer="eventus"
    )
}

# Completed our ESDL Logger Configuration

**Comment by rawal1500** [comment]
Please let us know if any mistake in the config and provide remedy for solution.
