### ISSUE TITLE
Multiple rsyslog instance running in single machine

### ISSUE THREAD

**Issue by dpkkumar01** [rsyslog/rsyslog#3183]
I have default rsyslog version 5.8.10 installed in one of my server (Rhel-6.4) which was used for other audit purpose.  I want to run the latest rsyslog version 8.38 in the same machine without upgrading the existing rsyslog version ( Multiple instance).

Please suggest me the available options to achieve the same.

**Comment by davidelang** [comment]
look at how to specify the config file to use and the pid file to use

then make sure you don't have both of them listening to the same sources

It should be pretty simple.

David Lang

**Comment by dpkkumar01** [comment]
Thanks for your response @davidelang 

I want to install the new rsyslog in a separate directory environment. So that it won't disturb the old rsyslog packages/services. Can you please share the procedure or reference link for the same.

**Comment by dpkkumar01** [comment]
I have compiled the required packages and rectified the issue. 

Thanks for your support
