### ISSUE TITLE
rsyslog ignores /etc/services

### ISSUE THREAD

**Issue by ma9e** [rsyslog/rsyslog#3196]
### Expected behavior

rsyslogd should respect the port setting in /etc/services when it is defined for tcp/udp streams.

### Actual behavior

I changed the syslog port in /etc/services to 5514/udp and restarted rsyslogd, but I'm still receiving remote syslogs on port 514.

### Steps to reproduce the behavior

Change the port in /etc/services to anything other than 514.

### Environment
- rsyslog version: 
```
/home/root# rsyslogd -v
rsyslogd 8.29.0, compiled with:
        PLATFORM:                               arm-poky-linux-gnueabi
        PLATFORM (lsb_release -d):
        FEATURE_REGEXP:                         Yes
        GSSAPI Kerberos 5 support:              No
        FEATURE_DEBUG (debug build, slow code): No
        32bit Atomic operations supported:      Yes
        64bit Atomic operations supported:      No
        memory allocator:                       system default
        Runtime Instrumentation (slow code):    No
        uuid support:                           Yes
        Number of Bits in RainerScript integers: 64

See http://www.rsyslog.com for more information.
```

- platform: armv7l Poky Linux

**Comment by ma9e** [comment]
@rgerhards Does this mean I need to switch from using the old syntax?

**Comment by rgerhards** [comment]
Honestly, I don't know anymore. You can try to specify the name with the legacy statement. Could be it works. Converting to new style of course is a quick job, so...
