### ISSUE TITLE
Imfile module: state files update logic issue

### ISSUE THREAD

**Issue by dpkkumar01** [rsyslog/rsyslog#3204]
I have enabled state file writing in imfile module. My application is creating approximately 800 files per day. I can see the 800 imfile-state file are generating per day in **"/var/lib/rsyslog"** directory which is increasing my inode usage day by day.

I would like to store my state files in common files to avoid this issue. 

Kindly suggest me the available options.

Rsyslog version --> 8.38

**My imfile module configuration:**
 
$WorkDirectory /var/lib/rsyslog
module(load="imfile" Mode="inotify")
input(type="imfile"
     File="/home/DNA/rsyslog/cdrs/DNA-AegisGw-CDR_PREPAID*.log"
     Tag="cdr: "
     PersistStateInterval="100"
     #StateFile="stat-test"
     deleteStateOnFileDelete="off"
     ruleset="MTFW_CDR")

**Comment by dpkkumar01** [comment]
Hi Team,
Can anyone check this issue and update.

**Comment by dpkkumar01** [comment]
Hi Team,

Please check this issue ASAP which is impacting our main application processes.
inode usage is keep increasing due to this state files update.

Thanks

**Comment by Turgon37** [comment]
Hello,
Have you any news about this issue ?
I'm encountering the same problems

Regards

**Comment by Turgon37** [comment]
I'm using debian, so I've tried to switch from 8.24.0-1 to 8.1901.0-1
Under 8.24.0-1, the statefile statement was working but under 8.1901 I've a lots of imfile-state:[inode]:[hash] in spool directory. So theses are not documented in https://www.rsyslog.com/doc/v8-stable/configuration/modules/imfile.html
The state filename must contains the path to the input file, not it's inode or a hash.

**Comment by rgerhards** [comment]
> So theses are not documented in https://www.rsyslog.com/doc/v8-stable/configuration/modules/imfile.html

Sorry, this is a doc omission. Thanks for pointing it out. Actually, the doc was far more specific than useful. State file name is an rsyslog internal. What you see is right. I'll update the doc.
