### ISSUE TITLE
Unable to compile ./configure: command not found

### ISSUE THREAD

**Issue by hyperfocus1337** [rsyslog/rsyslog#321]
When present in the downloaded archive of rsyslog 8.9.0 you can't do ```./configure```. So how do I compile rsyslog? What folder should I be in? For clarification ```pwd``` returns ```/home/vagrant/rsyslog-8.9.0```

**Comment by andreasstieger** [comment]
Hmm, this is not an issue, this is a question.

Anyway, it looks like you used the non-bootstrapped github tarball from https://github.com/rsyslog/rsyslog/releases   As scm tree snapshots will not be autotools bootstrapped and thus not contain a configure script, you will either have to do that yourself (autogen.sh), or use the official release tarball available at http://www.rsyslog.com/files/download/rsyslog/rsyslog-8.9.0.tar.gz (recommended)

**Comment by hyperfocus1337** [comment]
Thank you! Maybe include it in the install from source documentation on the website? There are no recommended download locations specified.
