### ISSUE TITLE
Rsyslog writing many times to syslog log file

### ISSUE THREAD

**Issue by sampleuser4** [rsyslog/rsyslog#3216]
Hi,

  I configure rsyslog with java log4 to write messages on local facility local1 to a log file in /var/log/app.log. But  whenever my app writes to applog, rsyslog is writing the log many times to /var/log/app.log. Due to this size of app.log  is increasing enormously. Is there any configuration i can make so that syslog can write entries only once.

In syslog i am using 7.4 version and using 
```
$ModLoad imfile
$RepeatedMsgReduction on


$InputFileName /var/log//app.log
$InputFileTag tag_audit_log:
$InputFileStateFile javaapplication_log
$InputFileSeverity info
$InputFileFacility local1
$InputRunFileMonitor
```
Can you please provide pointers how i can make syslog write entries only once to /var/log/app.log

Thanks

**Comment by jgerhards** [comment]
Hi,
Looks like you are using an old version of rsyslog. Please consider updating as this one is no longer community supported.
Could you also please upload you whole rsyslog.conf and include files since this one seems to be incomplete?
