### ISSUE TITLE
Compilation error configure: error: Package requirements (json-c) were not met:  No package 'json-c' found

### ISSUE THREAD

**Issue by hyperfocus1337** [rsyslog/rsyslog#322]
Error in the title. How can I get json-c on Debian 8 jessie? Could find pkgconfig and libestr easily but I can't find this one.

**Comment by rgerhards** [comment]
Have a look at README.md. It has the package manager commands for the dependencies for many distros. For others, that's the starting point to search for.

**Comment by andreasstieger** [comment]
Not everything that happens while compiling $SOFTWARE is an issue of $SOFTWARE. Please consider this when filing "issues".

**Comment by hyperfocus1337** [comment]
Unfortunately it only includes the dependencies of CentOS 6 and openSUSE 13.

**Comment by rgerhards** [comment]
google "debian json-c package" has this as first result:

https://packages.qa.debian.org/j/json-c.html

**Comment by hyperfocus1337** [comment]
I'm sorry this is just way more convenient then email list, the barrier to ask questions there is to high for me.

**Comment by hyperfocus1337** [comment]
root@vagrant:/home/vagrant/rsyslog-8.9.0# sudo apt-get install json-c
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package json-c

**Comment by andreasstieger** [comment]
Well if it is all for your convenience, I am contented.

**Comment by andreasstieger** [comment]
Hint: look at the Debian package control files for rsyslog, which for Debian sid is at 8.4.2 and specifies the required -devel package.

**Comment by hyperfocus1337** [comment]
I could share the Ansible script I'm building to automate rsyslog install from source once I'm done with it. I'm sure many other people would benefit from it. When looking at the dependencies of the rsyslog package: https://packages.debian.org/jessie/rsyslog

I see ```libjson-c2```, but when I try to install it:

```
root@vagrant:/home/vagrant/rsyslog-8.9.0# apt-get install libjson-c2
Reading package lists... Done
Building dependency tree
Reading state information... Done
libjson-c2 is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

**Comment by andreasstieger** [comment]
As you are compiling things, you need the development package, which should be libjson-c-dev.

**Comment by hyperfocus1337** [comment]
Yeah I found that one before and installed it but still ```No package 'json-c' found``` when ```./configure```

**Comment by hyperfocus1337** [comment]
Do you still love me?

**Comment by chenbowalker** [comment]
apt-get install libjson-c-dev
