### ISSUE TITLE
test-suite failures if gcrypt support is disabled.

### ISSUE THREAD

**Issue by mbiebl** [rsyslog/rsyslog#3228]
Version: 8.39.0

I'm building rsyslog with gcrypt support disabled. This results in the following 4 tests to fail:
```
FAIL: queue-encryption-disk.sh
FAIL: queue-encryption-disk_keyfile.sh
FAIL: queue-encryption-disk_keyprog.sh
FAIL: queue-encryption-da.sh
```

I think those tests should be skipped if rsyslog is built with ```--disable-libgcrypt```
Full build log is attached

[build-log.txt](https://github.com/rsyslog/rsyslog/files/2532918/build-log.txt)

**Comment by rgerhards** [comment]
thx for the report; it's unfortunately impossible to test all possible cases. However, I think I will see that I add one builder who runs ./configure just with the default options enabled. That should catch such things in the future.
