### ISSUE TITLE
No error message on permission denied

### ISSUE THREAD

**Issue by friedl** [rsyslog/rsyslog#323]
When having a disk-assisted queue, no error message gets shown when the access permissions to folders/files is denied. Such messages are shown in the debug output, but not when starting rsyslog without debug support.

**Comment by krawiec** [comment]
+1

**Comment by mostolog** [comment]
Related: https://github.com/rsyslog/rsyslog/issues/548

**Comment by rgerhards** [comment]
@PascalWithopf please check if this still exists - I think it is solved in the mean time. If not, please consider fixing it :-)

**Comment by rgerhards** [comment]
@PascalWithopf  does this still exist?

**Comment by PascalWithopf** [comment]
When permission is denied following error is given.
```rsyslogd: error starting up action queue [v8.38.0.master try http://www.rsyslog.com/e/2027 ]```
Followed by a memory leak, detected by Address Sanitizer.

**Comment by rgerhards** [comment]
ok, thx, so the actual error message is missing
