### ISSUE TITLE
A lot spam with 'action-4-builtin:omfile' resumed (module 'builtin:omfile')

### ISSUE THREAD

**Issue by ZerooCool** [rsyslog/rsyslog#3287]
### Expected behavior
Hi, i hive a lot spam line every second, after my first install.

### Actual behavior
uID 	153806
Date 	Today 15:27:07
Host 	alpha
Messagetype 	Syslog
Syslogtag 	rsyslogd
Message 	action 'action-4-builtin:omfile' resumed (module 'builtin:omfile') [v8.39.0 try http://www.rsyslog.com [More Information] /e/2359 ]

### Steps to reproduce the behavior
Gnu Linux Mint Tata
I install rsyslog and loganalyser with this tutorial : 
And, syslog with Diskfile.

https://www.visionduweb.eu/wiki/index.php?title=Sommaire_S%C3%A9curit%C3%A9#Adiscon_LogAnalyzer

### Environment
rsyslogd -v
rsyslogd 8.39.0, compiled with:
	PLATFORM:				x86_64-pc-linux-gnu
	PLATFORM (lsb_release -d):		
	FEATURE_REGEXP:				Yes
	GSSAPI Kerberos 5 support:		No
	FEATURE_DEBUG (debug build, slow code):	No
	32bit Atomic operations supported:	Yes
	64bit Atomic operations supported:	Yes
	memory allocator:			system default
	Runtime Instrumentation (slow code):	No
	uuid support:				Yes
	systemd support:			Yes
	Number of Bits in RainerScript integers: 64

Mint Tara 19.

**Comment by rgerhards** [comment]
That's interesting. Could you create a debug log that contains some of the instances?

**Comment by ZerooCool** [comment]
I search how to. Debug rsyslog, or, loganalyser ?

**Comment by rgerhards** [comment]
have a look here: https://www.rsyslog.com/doc/v8-stable/troubleshooting/debug.html

**Comment by ZerooCool** [comment]
Hi @rgerhards 
I have found the good way to create debug log :

It would be best to write the path rather than the name.
The translation already complicates the understanding, I replaced name by path, and, the log file is well created.

 $DebugFile <filename> - sets the debug file name
 $DebugLevel <0|1|2> - sets the respective debug level, where 0 means debug off, 1 is debug on demand activated (but debug mode off) and 2 is full debug mode.

**Here is the link for the logs : https://pastebin.com/J2rytYvP**

In the meantime, I advanced to discover LogAnalyzer.
I first tested the use of the source syslog disk.
Then, I was able to set up the syslog source with MySQL.
The error message that is looping is always there.

Tutoriel : https://www.visionduweb.eu/wiki/index.php?title=Gestion_des_logs#Installer_Rsyslog

**Comment by ZerooCool** [comment]
Ok, with this config : https://pastebin.com/nPBn8XFm

I corrected my file, work better.
I no longer have the repetitive alerts mentioned initially.

However, I still see that I have duplicates on display.
Off, I added the parameter to have no duplicates in the configuration.

I am also surprised that the TCP UDP configuration if enabled, causes the duplicate error messages I encountered.
I do not use a Rsyslog client, I only use Rsyslog on one machine, maybe that's why having UDP TCP listening enabled causes alerts?
Unless it's because I did not open the Firewall?

However, for my local need, it seems to work better.

It remains to correct the duplicates.
I can repost a new debug file tomorrow, if you can help me.

**Comment by rgerhards** [comment]
The debug log does not contain any suspend or resume message. We need a look that contains these.

**Comment by ZerooCool** [comment]
Hello.
How to obtain them?
The same method to create Debug logs?
I would have had to copy more lines?

**Comment by davidelang** [comment]
we just need a debug log that covers the time when these resume logs happen

it's just that the one you provided didn't happen to include a time range when 
these messages were happening

David Lang

**Comment by ZerooCool** [comment]
Like the atom, when I try to fix it to observe it, I can not get it.
That is, when I put the capture of logs in place, the error does not occur, or, not at the right moment. I give up for the moment because, for the rest, it seems to work.

I share my configuration, if you want to observe, and, validate its syntax:
https://www.visionduweb.eu/wiki/index.php?title=Gestion_des_logs#Exemple_de_configuration_par_d.C3.A9faut

This is to complete the tutorial on my wiki:
Here, I tested with a VM Virtualbox Mint.

The tutorial will be added on the Debian wiki, once my tests on a Debian VM done.
https://wiki.debian.org/fr/Rsyslog

**Comment by rgerhards** [comment]
I still need a debug log that shows the problem. If I don't get hold of one, I'll close the issue.
