### ISSUE TITLE
How mmpstrucdata and mmrfc5424addhmac works?

### ISSUE THREAD

**Issue by RanjodhKaur** [rsyslog/rsyslog#329]
I am trying to log messages with structured data . But it is showing null value for structured data. I am working with rsyslog 8.9.0.Can someone exlain me how these two modules mmpstrucdata and mmrfc5424addhmac will be effected?

**Comment by rgerhards** [comment]
I guess you are trying to **generate** syslog data. Unfortuantely, this is beyond the scope of rsyslog. The modules you mention are used to *exctract* this data from messages that contain it.

Unfortunately, the regular syslog API does not provide support for adding structured data. I could check if  liblogging (https://github.com/rsyslog/liblogging) currently supports it, but that would require to use this as an additional library.

**Comment by LilyChadha** [comment]
I am trying to log messages with structured data . But it is showing "null value" for structured data. I am working with rsyslog 8.9.0.Can someone tell me either i need to load some module or modify source to get structure data SD-IDs in logged message.

#Template:
"<%PRI%>%TIMESTAMP:::daterfc3339%%HOSTNAME%%syslogtag%%APPNAME%%PROCID% %MSGID% %msg% %STRUCTURED-DATA%\n”

getting message format as below:
<142> 2015-01-29T06:43:53.081641-05:00 localhost login[2116]: login 2116 - [2116 : 2116 INFO]SERIAL Login from IP:127.0.0.1 user:admin -

**Comment by rgerhards** [comment]
You confirmed what I said. That's not a RFC5424 message.

**Comment by LilyChadha** [comment]
Okay.Can you please tell me how can i get structured data in logged messages?

**Comment by rgerhards** [comment]
would liblognorm be an option for you? If so, I could see that I have a look of what it currently does. On the other hand, you could use cee format -- that doesn't require a different API, **but** is not RFC5424 (if that is a requirement).
