### ISSUE TITLE
imfile and symlink error

### ISSUE THREAD

**Issue by falon** [rsyslog/rsyslog#3291]
### Expected behavior
rsyslog collects files into symlink path
### Actual behavior
When I start rsyslog I see immediately:
```
rsyslogd[9203]: imfile: '/usr/local/dmarc-report-processor/var/dmarc_splunk/latest' is FILE but DIRECTORY expected - ignored [v8.39.0]
```
### Steps to reproduce the behavior
Config of imfile:
```
input(type="imfile"
      File="/usr/local/dmarc-report-processor/var/dmarc_splunk/latest/*.log"
      Tag="DMARCReport"
      Facility="mail"
      PersistStateInterval="100")
```
I start rsyslog and I immediately see:
```
rsyslogd[9203]: imfile: '/usr/local/dmarc-report-processor/var/dmarc_splunk/latest' is FILE but DIRECTORY 
```
`latest` is a symlink:
```
# ll /usr/local/dmarc-report-processor/var/dmarc_splunk/latest
lrwxrwxrwx 1 root root 62 Nov 13 00:00 /usr/local/dmarc-report-processor/var/dmarc_splunk/latest -> /usr/local/dmarc-report-processor/var/dmarc_splunk/12-Nov-2018
```

If I configure the directory in place of the symlink, rsyslog works well:
```
input(type="imfile"
      File="/usr/local/dmarc-report-processor/var/dmarc_splunk/12-Nov-2018/*.log"
      Tag="DMARCReport"
      Facility="mail"
      PersistStateInterval="100")
```
with this config rsyslog works as expected.

### Environment- rsyslog version: 8.39.0
- platform: Red Hat Enterprise Linux Server release 7.4 (Maipo)

With 8.38.0 I see the same issue. With previous version instead rsyslog works well and it collect files from symlink without errors.

**Comment by rgerhards** [comment]
@jvymazal I don't think we support symlinks in the directory part of the path?

**Comment by rgerhards** [comment]
@jvymazal  That was a bit hidden:

> With 8.38.0 I see the same issue. With previous version instead rsyslog works well and it collect files from symlink without errors.

If so, I think the symlink support code caused a regression. Could you have a look?

**Comment by jvymazal** [comment]
@falon, just to clarify, now rsyslog actually does NOT collect from files in configured directory? Or it does collect and just shows above error despite it?

Thanks

**Comment by falon** [comment]
@jvymazal I'm confused... with 8.38.0 I saw lack of log... But with 8.39.0 the logs are collected, only this warning is added. I'll check again, but rsyslog seems to works well despite this warning.

**Comment by jvymazal** [comment]
> I'll check again, but rsyslog seems to works well despite this warning.

Please do, it is very well possible the actual logic is correct and only the reporting piece has to be fix to not report error in this case. I would check myself however from past experience it is better when people actually having problems in field verify it. Thanks.

**Comment by falon** [comment]
I'll leave another feedback within few days. Thank you very much

**Comment by brenoack** [comment]
We're seeing this too, the log files are still logged correctly, but the spurious warnings are continually emitted. 
Using rsyslogd 8.24.0-34.el7 in a Red Hat Enterprise Linux Server release 7.6 (Maipo).

**Comment by falon** [comment]
I confirm too that with 8.39.0 this is only a warning: rsyslog collects from files in configured symlink.
Thank you

**Comment by jvymazal** [comment]
Ok, I will put up an PR to stop the symlink-related errors (I think the switch was there in one phase but was somehow forgotten in the final version that got merged)
Thank you for your reports.

**Comment by rgerhards** [comment]
@jvymazal thx for taking care of this!
