### ISSUE TITLE
rsyslogd: could not load module 'omhttp'

### ISSUE THREAD

**Issue by darakian** [rsyslog/rsyslog#3302]
I'm trying to get the new contrib module omhttp working for my logging system, however when I try to load the module I get
```
rsyslogd: version 8.39.0, config validation run (level 1), master config /etc/rsyslog.conf
rsyslogd: could not load module 'omhttp', errors: trying to load module /lib64/rsyslog/omhttp.so: /lib64/rsyslog/omhttp.so: cannot open shared object file: No such file or directory [v8.39.0 try http://www.rsyslog.com/e/2066 ]
```

This is using the centOS 6 repo for rsyslog_v8 which is configured with the following yum repo
```
[rsyslog_v8]
name=Adiscon CentOS-$releasever - local packages for $basearch
baseurl=http://rpms.adiscon.com/v8-stable/epel-6/$basearch
enabled=1
gpgcheck=0
gpgkey=http://rpms.adiscon.com/RPM-GPG-KEY-Adiscon
protect=1
```

Additionally I do not see a specific omhttp package in yum when I search for it.

**Comment by jgerhards** [comment]
Sadly, the omhttp module is currently **not** part of the default packages, so you'll have to build it from source (github). Quick side note aswell: since this module is contributed, it does not have any affiliation with the official rsyslog project, so we can't guarantee it's working correctly (or that it even installs correctly for that matter). This is also the reason why there is no package containing the module. However, i might try to build a package for a later release, since it didn't work with the standard settings on this one.

**Comment by darakian** [comment]
Thanks for the reply and the link to the bug. Looking at the build error it seems that there was a redeclaration of a variable and the PR #3304 seems to fix that. Assuming that is the only issue, would it be safe to assume that omhttp would show up in some future release? 8.40 or 8.40 perhaps?

**Comment by darakian** [comment]
Awesome. Having omhttp available via a repo would be very helpful to me. Out of curiosity what would it take to make omhttp )an( official package(s)?

**Comment by rgerhards** [comment]
> Awesome. Having omhttp available via a repo would be very helpful to me. Out of curiosity what would it take to make omhttp )an( official package(s)?

either large demand or someone who actually maintains it

**Comment by darakian** [comment]
@jgerhards Sorry to bug, but where can I find the omhttp package (assuming it has been built).

**Comment by jgerhards** [comment]
@darakian as of right now, i'm still working on including it (harder than i thought); it should work for CentOs6 already, i think you can download it here (can't check right now, as the link is down for maintainance):
https://software.opensuse.org//download.html?project=home%3Argerhards&package=rsyslog

**Comment by darakian** [comment]
It's just included in the 8.40.0-1.1 rpm? Many thanks for the effort as well :)

**Comment by jgerhards** [comment]
The best way to install the packages is to add the package repository as given in the first link on
https://software.opensuse.org//download.html?project=home%3Argerhards&package=rsyslog
if you click through the definitions, you will find this page (this link may change)
http://download.opensuse.org/repositories/home:/rgerhards/CentOS_6/x86_64/
please note: if you do not install everything manually, this may lead to problems.

**Comment by darakian** [comment]
I've reverted to compiling from source for the time being. Would love to have this in the official repo.

**Comment by sahya** [comment]
@jgerhards i want to biluld the omhttp module for centos. how to build the omhttp module?
sorry, please tell me procedure or specfile.

**Comment by darakian** [comment]
@sahya build off of this branch
https://github.com/rsyslog/rsyslog/pull/3423

**Comment by sahya** [comment]
@darakian thank you for your guide. 
Sorry without asking. Is it also possible to rpmbuild?

**Comment by ammaree** [comment]
I would like to use this module (omhttp) on Ubuntu 16.04 LTS to escalate priority 0-4 messages to PushOver.
Since I am not a Linux developer (mainly embedded work in C) what would be the easiest/safest route to install?

**Comment by sahya** [comment]
@ammaree could you try this following link:
rsyslog-omhttp_build-cmd.bash https://gist.github.com/sahya/b663b57db2d9ff66e8f644fb4f9d4fc3
