### ISSUE TITLE
Request to support an alternative format to gzip to quickly search inside big logs

### ISSUE THREAD

**Issue by circulosmeos** [rsyslog/rsyslog#3306]
This is just a request for a new feature:
Could **dictzip** format be supported when compressing ?
Like in

> local4.*  action(type="omfile" file="/var/log/app.log.gz" zipLevel="6")

`dictzip` is compatible with gzip, so even the .gz extension could be retained, and
with `dictzip`,  searching inside big log files (>>1 GiB) could be done inexpensively whereas with `gzip`/`zlib`, this is not possible.

**Comment by davidelang** [comment]
I am not familiar with dictzip (link please), does it put the index at the 
beginning or the end? if it puts it at the beginning, doesn't that mean that the 
file can't be written until all the contents are known? how would that work in 
this streaming environment.

David Lang

**Comment by circulosmeos** [comment]
Dammit, you're right: I was led to delusion by the 

> [...] completely compatible with the gzip file format

but in [dictzip](https://linux.die.net/man/1/dictzip)

> [...] parts of the header must be updated after a write when compressing

I am looking for a way to **quickly look inside parts of gzipped rsyslog files**, and traditional `gzip`/`zlib` are not an option, as complete decompression is mandatory. This can/could be *easily* done simply by introducing gzip compatible markers to signal independent blocks of compressed data, as stated (but not (yet) available as lib) [here](https://stackoverflow.com/a/14242594/778533). Also, the cmdline utility for searching doesn't exist, but it could be easily developed (even a script would suffice).

Another possibility that I've seen is [bgzip](http://www.htslib.org/doc/bgzip.html), which seems able to compress streaming data:

> If no files are specified on the command line, bgzip will compress (or decompress if the -d option is used) standard input to standard output.

If one of these methods could be integrated in rsyslog, management of gzipped rsyslog files would be totally time-inexpensive and even more effective than without compression. **And moreover, a `tail -f` alike would be possible!**. This is important for sysadmins...

**Comment by circulosmeos** [comment]
[bgzip ](http://www.htslib.org/doc/bgzip.html) would be perfect (`b` is for `block`): 

- it compresses streams 
- it is fully compatible with gzip, and even uses the same file extension, so it can be decompressed unnoticed as a gzipped file
- compression factor is not affected why the little overhead of [compressing blocks and adding some little headers](http://samtools.github.io/hts-specs/SAMv1.pdf)

Later, in order to make random accesses to the bgzipped file, an index need to be made: 
I think it is not really generated on-the-fly while compressing but after all contents are written (see [code for bgzip.c](https://github.com/samtools/htslib/blob/develop/bgzip.c#L237)), in any case its creation is **way faster** than reading the entire file...

The only work would be to convert the bgzip.c in a library, if that is how rsyslog interfaces gzip: bgzip() would be totally compatible with the previous code!

I think this would be a very useful feature for all sysadmins!

**Comment by jay7x** [comment]
@circulosmeos you may consider using filesystem with compression support (ZFS/BTRFS) as workaround :)
This feature seems interesting anyway. So my +1 here

**Comment by circulosmeos** [comment]
I've done a [pull request to support `--on-the-fly` generation of the index](https://github.com/samtools/htslib/pull/877) with `bgzip`, and I've also developed the [Perl script `bgztail`](https://github.com/circulosmeos/bgztail) to have a "`tail -f`" for bgzipped files.

All to create the appropriate ecosystem for the proposed rsyslog-compression-to-`bgzip` !

**Comment by rgerhards** [comment]
@circulosmeos interested to do a similar PR for rsyslog? That would definitely increase the likelihood for this feature to appear quickly. I am happy to answer questions along that way.

**Comment by circulosmeos** [comment]
I can take a look at it: if you could just tell me what source/s file/s to start with... I don't know anything about the internals of this project, apart from having used it :-)

**Comment by davidelang** [comment]
On Sun, 23 Jun 2019, circulosmeos wrote:

> I've done a [pull request to support `--on-the-fly` generation of the index](https://github.com/samtools/htslib/pull/877) with `bgzip`, and I've also developed the [Perl script `bgztail`](https://github.com/circulosmeos/bgztail) to have a "`tail -f`" for bgzipped files.
>
> All to create the appropriate ecosystem for the proposed rsyslog-compression-to-`bgzip` !

I would suggest that you look at xv, my understanding is that it produces 
better, faster results than bzip in pretty much every setting.

A coulple issues to look at (and ones we sometimes have a problem with 
using gz):

  how does the format handle data trickling in over time (does it buffer it all 
until close? how long does it take to process the buffered data at close?).

  how does the format handle the case where a file is closed and then we need to 
add more data to it?

David Lang

**Comment by circulosmeos** [comment]
Hi @davidelang 
You mean `xz`? I'm not trying to add a brand new different format, but to generate the old-fashion good compressed gzip files in a more manageable way (but transparent for the not advised) for sysadmins.
As for the questions, bgzip is like gzip but in blocks of 64 kiB of input, so that seems the minimum to write new outputs, and new data can be appended to any bgzipped file as they will be just new blocks.

**Comment by circulosmeos** [comment]
As a related work, I've developed [`gztool`, a command line tool that creates little file indexes for gzip files](https://github.com/circulosmeos/gztool/), so they can be accessed at any random position without any time penalty (after the index is created). `gztool` can extract data at the same time it creates the index files, and these can be stopped at any moment and increased/reused later.

The tool has a `-S` option that can *supervise* any growing gzip file, creating a companion growing index for it, this way reducing the time of index creation in the practice to zero.

This is obviously a side attack to this problem. Though it works ;-)

Hope I can take a closer look at rsyslog code in the future to add bgzip functionality.

**Comment by circulosmeos** [comment]
Now that I've developed [`gztool`](https://github.com/circulosmeos/gztool/) with [`-S` (supervise) and `-T` (supervise and tail) options](https://github.com/circulosmeos/gztool/tree/master#examples-of-use), adding `bgzip` format doesn't seem like a **`MUST`** because `gztool` indexes are very small (<<%1/gzip): even if never as small as `bgzip` ones, the complexity of the format change doesn't justify the effort.

In order to just use hardened gzipped logs now I think it would suffice to change the way the `VeryRobustZip` manages writes at `doZipWrite()` by increasing the number of bytes accepted before doing the `doZipFinish()` call: in my tests `VeryRobustZip` writes buffer so aggressively that compressed logs in fact occupy almost the same size than the uncompressed data!

Changing this behaviour to accept up to 32 or 64 kiB of data before calling `doZipFinish()` would certainly make `VeryRobustZip` exactly the same as `bgzip`. 

I have to test if using `VeryRobustZip` with `ioBufferSize`>=64 kiB will suffice for this **and then no change to code would be needed to achieve effective bgzip robustness**. And with [`gztool`](https://github.com/circulosmeos/gztool/) at hand any sysadmin can do a *like*-`tail -f` tailing of a gzip file that would be also robust to interruptions.

**Comment by circulosmeos** [comment]
I haven't been able to increase the very little gzip block size when using `VeryRobustZip` neither using `ioBufferSize="128k"` nor with something like `flushOnTextEnd="off" asyncWriting="on" flushInterval="2"`.

Maybe a code change is needed to increase the gzip block size when using `VeryRobustZip`.

**Comment by circulosmeos** [comment]
Note for geeks: the size of the gzip completed blocks used with `veryRobustZip` can be traced with [`gztool`](https://github.com/circulosmeos/gztool/) using `-v3` when extracting data as they produce a zlib's ERR=1 (Z_STREAM_END) message; for example:
`$ gztool -b0 -v3 mylog.gz`

**Comment by davidelang** [comment]
yes a code change would be needed.

**Comment by circulosmeos** [comment]
> yes a code change would be needed.

No, it is possible to increase `veryRobustZip` block using `rsysog` options: see previous comment with `ioBufferSize` and `asyncWriting`!

**Comment by circulosmeos** [comment]
With the rsyslog configuration previously tested and the use of [`gztool`](https://github.com/circulosmeos/gztool/) this request can be closed! :-o

I've learnt how to correctly configure `veryRobustZip` with `rsyslog` and I've developed [`gztool`](https://github.com/circulosmeos/gztool/), so:
Thanks to all the people who have tried to guide me through this journey!

**Comment by rgerhards** [comment]
Thanks for all your help! Would you be interested to add the relevant information to the rsyslog-doc project? I am sure this would make it much more accessible to the community at large.

see https://github.com/rsyslog/rsyslog-doc/

**Comment by circulosmeos** [comment]
ok, I'll try to add these infos
