### ISSUE TITLE
Debug symbol packages for Ubuntu build

### ISSUE THREAD

**Issue by hakman** [rsyslog/rsyslog#331]
A few days ago we got into this [issue] (https://github.com/rsyslog/rsyslog/commit/0181d341b7b875f05436f6a15205c7eb291ba141) and Rsyslog kept crashing.
We tried to find the root cause, but core files were not very useful because the debug symbols were missing. In the end, we compiled Rsyslog locally and traced the crashes to this issue.

Could we have debug symbol package(s) for Rsylog and plugins for Ubuntu & Debian stable builds?
I see that the RHEL/CentOS repo has such packages but could not find for Ubuntu.

Thanks in advance.

**Comment by radu-gheorghe** [comment]
BTW, if there's something @hakman or I could do to make put the debug symbols in those packages (I assume a separate set of packages would be needed?), please let us know!

**Comment by rgerhards** [comment]
This should probably be reported against the packaging project.

Anyways, I was of the impression that debug symbols are always included. As that doesn't seem to be the case, I'd appreciate a pull request to implement that for Ubuntu. I close this tracker, as I think it's not related to rsyslog itself but rather the Ubuntu packaging project.
