### ISSUE TITLE
Imfile module max files??

### ISSUE THREAD

**Issue by kojix** [rsyslog/rsyslog#3315]
### Expected behavior
We're rotating various tomcat installation logs via imfile module using wildcards.
We've a monthly script wich erases old log files (tomcat generates daily log files for some logs and we do'nt want to keep them because we're also getting them with rsyslog), but recently it has failed and we've noted that some log files aren't being sent to the rsyslog server.

### Actual behavior

It seems that there's is a maximum limit for imfile module, but if there is (I haven't seen it in the documentation), as far as I've seen there's no advertisement when restarting the local rsyslog...

When there are lots of files for the module, some of them aren't being sent to the server.

### Steps to reproduce the behavior

-Use imfile with wildcards
-Create various files wich get into the wildcard (I've seen it with les than 200)...
-Check if all of them are being sent to the rsyslog server...

### Environment
- rsyslog version: 8.34.0
- platform: Solaris 10

**Comment by rgerhards** [comment]
Thereis no limit, but there were quite some bugs in the old version. Please use the current supported one (8.39 as of this writing). If the problem re-occurs, please open a new issue tracker.
