### ISSUE TITLE
Support for FreeBSD 12 move to RFC5424

### ISSUE THREAD

**Issue by woodsb02** [rsyslog/rsyslog#3316]
The upcoming FreeBSD 12.0 release includes a number of changes to support #rfc5424 which may require changes in rsyslog.

The most significant change is the libc function syslog(3) now generates #rfc5424 style messages.

It is recommended that rsyslog is tested with FreeBSD 12.0-RC2 snapshot.

**Comment by woodsb02** [comment]
The following FreeBSD commits by @EdSchouten are the important changes.

Add RFC5424 message parsing to syslogd:
https://svnweb.freebsd.org/base?view=revision&revision=332099

Add RFC5424 message output to syslogd:
https://svnweb.freebsd.org/base?view=revision&revision=332510

Make syslog(3) libc function generate RFC5424 format (and add instructions to UPDATING):
https://svnweb.freebsd.org/base?view=revision&revision=332100

**Comment by woodsb02** [comment]
The following text was included in the FreeBSD UPDATING entry for the RFC5424 change, which explains the changes required for rsyslog to work with the updated syslog(3) libc:

When using rsyslog, disable the 'SysSock.UseSpecialParser' option of the 'imuxsock' module to let messages be processed by the regular RFC 3164/5424 parsing pipeline:

		module(load="imuxsock" SysSock.UseSpecialParser="off")

**Comment by rgerhards** [comment]
fixed in 8.1907.0 (actually default is different now on FreeBSD)

**Comment by woodsb02** [comment]
This issue was a duplicate of #3694 
The commit which fixed this issue is referenced in #3694
