### ISSUE TITLE
rsyslog not sending data to kafka 

### ISSUE THREAD

**Issue by ellouminisrine** [rsyslog/rsyslog#3318]
Hello ! 
I'm using Rsyslog to send a simple log file to kafka (omkafka)
### Expected behavior
Data in the broker  with kafka consumer.
### Actual behavior
No data in my broker.
### Steps to reproduce the behavior
```
$ModLoad omkafka
$ModLoad imfile
input(type="imfile"
  File="/opt/logs/example*.log")
template(name="kafkamsg" type="string" string="%msg%")
action(type="omkafka"
           name="log1_kafka"
           brokers="........................:6667"
           topic="kafkadyntopic"
           errorfile="/var/log/omkafka/log1_kafka_failures.log"
           template="kafkamsg")
```

### Environment
- rsyslog version: 
- platform: 
- for configuration questions/issues, include rsyslog.conf and included config files

**Comment by rgerhards** [comment]
pls provide version/platform info
