### ISSUE TITLE
imfile stuck at large file under inotify mode

### ISSUE THREAD

**Issue by Dieken** [rsyslog/rsyslog#3319]
https://github.com/rsyslog/rsyslog/blob/master/plugins/imfile/imfile.c#L1526

```
pollFileReal(act_obj_t *act, cstr_t **pCStr)

...
	/* loop below will be exited when strmReadLine() returns EOF */
	while(glbl.GetGlobalInputTermState() == 0) {
		if(inst->maxLinesAtOnce != 0 && nProcessed >= inst->maxLinesAtOnce)
break;
```

Under inotify mode, `maxLinesAtOnce` is always zero,  so a heavily written log file will make imfile very busy and not collect other log files in time.

Seems imfile doesn't use multi-thread to consume files, and inotify event will be lost if `pollFileReal()` exits early,  no idea how to make file consuming fair :-(

**Comment by rgerhards** [comment]
yup, contributions for this are happily accepted. It is it creating a real problem for you (we never heard it actually creates problems)?

**Comment by Dieken** [comment]
Yes, in our performance test environment,  we have nginx access log and many log4j log files to collect, under heavy load the total size of these log4j files increases about 10MB/s, so the poor little nginx log is consumed very slowly.

Currently imfile read and process inotify events one by one, maybe better to read a bunch, deduplicate and sort to prefer small files and less frequently written files?

Not sure how much it helps.

**Comment by Dieken** [comment]
I'm using PersistStateInterval=1000,  will increase this to 1000000 and try again. It's a pity this "interval" isn't time based,  it's not friendly to infrequently written log files.

Another similar issue, FreshStartTail=on doesn't consider small files, I use Kubernetes to manage services and have a helper periodically running script to generate rsyslogd config files.  When a pod fails to start, its error log file is very short, rsyslogd will lose the error log because rsyslogd is just being restarted.

If FreshStartTail can accept a number which means a offset to the file end, so rsyslogd can start from (file_end - offset),  this will be much more pleasant.  Usually people use FreshStartTail=on to avoid collecting existed huge log files from beginning, not really mean to always collect from the end.

**Comment by jay7x** [comment]
@Dieken JFYI, you may configure nginx to send logs into rsyslog directly as a workaround. Check http://nginx.org/en/docs/syslog.html

**Comment by Dieken** [comment]
@jay7x Thank you very much! I tried nginx syslog logging support, it's a pity there is no way to carry file path, k8s namespace, k8s pod name and so on for both access log and error log.

**Comment by davidelang** [comment]
On Tue, 4 Dec 2018, Liu Yubao wrote:

> @jay7x Thank you very much! I tried nginx syslog logging support, it's a pity there is no way to carry file path, k8s namespace, k8s pod name and so on for both access log and error log.

encapsulate the log message in JSON, then you can add metadata as needed

set $!msg=$msg
then change your template to use $! instead of $msg

I then put the metadata that I add under $!trusted so that it isn't going to 
conflict with other stuff, but pick something that doesn't conflict.

David Lang

**Comment by Dieken** [comment]
jay7x suggested "nginx ---> remote rsyslogd",   I can't change nginx to output json format log.  Originally I used "nginx ---> local file ---> local rsyslogd ---> remote rsyslogd", but this has the issue described in this issue, the nginx log can't be read by local rsyslogd in time.

Since the "nginx ---> remote rsyslogd" solution doesn't support rich meta data, I'm trying to use multiple rsyslogd processes to collect logs from nginx and other services,  stupid but simple :-(

**Comment by davidelang** [comment]
On Tue, 4 Dec 2018, Liu Yubao wrote:

> jay7x suggested "nginx ---> remote rsyslogd",   I can't change nginx to output json format log.
>  Originally I used "nginx ---> local file ---> local rsyslogd ---> remote 
> rsyslogd", but this has the issue described in this issue, the nginx log can't 
> be read by local rsyslogd in time.
>
> Since the "nginx ---> remote rsyslogd" solution doesn't support rich meta 
> data, I'm trying to use multiple rsyslogd processes to collect logs from nginx 
> and other services, stupid but simple :-(

you can have one rsyslog process on the local box and multiple inputs (either 
ports or unix sockets) and have logic to let rsyslog add metadata based on the 
input it has rather than running separate processes.

nginx doesn't have a nice flag to flip to make it output in json, but it looks 
like you can define a custom format, and that format can 'just happen' to be 
able to be parsed by a json parser.

you could also (ab)use the tag setting to give each instance it's own tag and 
have rsyslog parse the tag and convert it to metadata.

David Lang

**Comment by Dieken** [comment]
The file path of nginx log on kubernetes cluster is dynamic,  the number of nginx pod is also dynamic, so I can't do a stable mapping in rsyslogd config file from rsyslogd ports or unix sockets to nginx file paths,  I can have a dirty helper script to periodically update nginx and rsyslogd config files, but that's toooooo dirty,  especially when I already have a dirty helper script to generate rsyslogd config files to discover new log files under kubernetes :-(

nginx access log has a "log_format" directive, error log doesn't have.  But even with "log_format" directive,  it can't properly escape strings to be valid JSON strings.

It's a pity nginx syslog tag can't be longer than 32bytes so that I can't put much meta data, although this limits conforms to RFC.

**Comment by davidelang** [comment]
On Tue, 4 Dec 2018, Liu Yubao wrote:

> The file path of nginx log on kubernetes cluster is dynamic, the number of 
> nginx pod is also dynamic, so I can't do a stable mapping in rsyslogd config 
> file from rsyslogd ports or unix sockets to nginx file paths, I can have a 
> dirty helper script to periodically update nginx and rsyslogd config files, 
> but that's toooooo dirty, especially when I already have a dirty helper script 
> to generate rsyslogd config files to discover new log files under kubernetes 
> :-(

take a look at the mmkubernetes module, and how you can use wildcards in imfile 
to get the logs.

David Lang
