### ISSUE TITLE
some TCP tests seems to buffer some messages

### ISSUE THREAD

**Issue by rgerhards** [rsyslog/rsyslog#3325]
When the openssl TLS driver is selected, it does not always send all data to the remote peer. This can be reproduced by running the `sndrcv_tls_ossl_anon_ipv6.sh` test a couple of times. Before doing so, you need to remove the work around for this issues (search the test for "work-around").

Once stuck, the messages are at least not delivered within 90 seconds. I would assume it actually will be delivered only when the next message is processed by the sender.

@alorbach could you have a look?

**Comment by rgerhards** [comment]
The problems seems not to be tied to openssl, it also happens with other tests. See https://github.com/rsyslog/rsyslog/pull/3326- it's a bit strange seeing this. Some messages sometimes seem to be processed (either by sender or receiver) on session closure.

**Comment by alorbach** [comment]
Does the test fail at some point? 
I have run it in loop 50 times without a failure.

**Comment by rgerhards** [comment]
yup, with the new change (NOT the unmodified test) it fails for me fairly frequently (not always, but always inside the loop). #3326 also has these failures.

**Comment by alorbach** [comment]
I have traced this down to a bug within the "ptcp Network Stream Driver" which both openssl and gnutls drivers are using as underlaying base. 

I can also reproduce the problem now with only 200 messages, even without encryption enabled:
StreamDriver.Mode="0"

However I cant find anything going wrong right now, it just looks likes that the last packet is vanishing on the receiver side (sender successfully reports the last package was send).
