### ISSUE TITLE
emit at least a warning message for ultra-large queues

### ISSUE THREAD

**Issue by rgerhards** [rsyslog/rsyslog#3334]
We see error reports from users who have configured excessively large queues and receive an OOM condition. So we should at least warn if a queue is configured very large (e.g. greater than 100,000 messages).

For an example see https://github.com/rsyslog/rsyslog/issues/3314

**Comment by davidelang** [comment]
One reason for this is that people have no idea how much space a message takes 
in a queue.

How hard would it be to add per-queue stats about memory used? (current and 
peak, just like size and maxsize)

David Lang

**Comment by rgerhards** [comment]
Pretty hard, we would need to count each and every  allocation plus guess the malloc overhead. More complicated with libs like json.
