### ISSUE TITLE
Template inserting unexpected hyphen into string

### ISSUE THREAD

**Issue by strikaco** [rsyslog/rsyslog#3341]
### Expected behavior
A random number is generated at startup and assigned to a global. The value is appended to the filename being written to.

### Actual behavior
When the template for the filename is rendered, rsyslog is inserting an unexpected hyphen in front of the global's value, making it appear to be a negative number.

### Steps to reproduce the behavior
```
# /etc/rsyslog.conf
set $/gid = cstr(random(999999));

# /etc/rsyslog.d/10-stuff.conf
# Create a template for the filename
template(name="PTemplate" type="string"
    string="/var/log/received/%$year%/%$month%/%$day%/%$!token_ext%/%$year%_%$month%_%$day%_%$!token_ext%_%$myhostname%_%$/gid%.log"
)

# do action; output to file

root@ip-172-31-20-78:/var/log/received/2018/12/10/0c9e6947-ebd9-4970-835b-9d185ae92ba3# ls
2018_12_10_0c9e6947-ebd9-4970-835b-9d185ae92ba3_ip-172-31-20-78_-433431.log
# Why is 433431 negative?
```

### Environment
- rsyslog version: 8.39.0
- platform: Ubuntu 16.04

**Comment by davidelang** [comment]
whenever you get something odd, it's a good idea to write a log out with the 
template RSYSLOG_DebugFormat so we can see exactly what you have.

I suspect that it will show the negative number here as well, but it will be 
good confirmation

as a side note, Global variables ($/) are far more expensive than other variable 
types, you may want to use $. instead. The only reason to use $/ is if you need 
the value to persist to other log messages, but here you are setting it for 
every log message.

David Lang

**Comment by rgerhards** [comment]
I did a couple of tests (with rsyslog current, 8.40.0) but cannot reproduce the issue.

**Comment by rgerhards** [comment]
will close when we do not hear back from @strikaco 

it would probably also be good to run rsyslog under valgrind and see if there is some misadressing somewhere.

**Comment by strikaco** [comment]
This turned out to be the result of an erroneous leading hyphen in a logrotate extension template, not anything to do with rsyslog.

Thanks for your time, sorry to distract.

**Comment by rgerhards** [comment]
NP, great it now works!
