### ISSUE TITLE
Built-in function substring() starts the count from 0.

### ISSUE THREAD

**Issue by anatolyborodin** [rsyslog/rsyslog#3344]
### Expected behavior

`substring("1234567890", 2, 4)` returns `"2345"`.

See https://github.com/rsyslog/rsyslog-doc/blob/master/source/rainerscript/functions/rs-substring.rst:

```
The first character of the string has the value 1. So if you set start to '3', the substring will start with the third character.
```

### Actual behavior

`substring("1234567890", 2, 4)` returns `"3456"`.

### Steps to reproduce the behavior

```
...
set $.x = substring("1234567890", 2, 4);
template(name="X" type="string" string="test substring(): %.x%\n")
...
```

### Environment
- rsyslog version:  8.32.0
- platform: x86_64-pc-linux-gnu (Ubuntu 18.04)

Related issue https://github.com/rsyslog/rsyslog-doc/issues/610

**Comment by anatolyborodin** [comment]
The implementation is inconsistent with the documentation and the `position.from/position.to` and `field:from:to:` logic.

**Comment by anatolyborodin** [comment]
https://github.com/rsyslog/rsyslog/blob/master/grammar/rainerscript.c#L2272 is the place where `es_newStrFromSubStr()` is called.

https://github.com/rsyslog/libestr/blob/master/include/libestr.h#L123 says:

```c
/**
 * Create a new string object from a substring of an existing string.
 * This involves copying the substring.
 *
 * @param[in] str original string
 * @param[in] start beginning position of substring (0-based)
 * @param[in] len length of substring to extract
 * @returns pointer to new object or NULL on error
 *
 * If start > strlen, a valid (!) empty string will be returned. If
 * start+len > strlen, the rest of the string starting at start will be
 * returned.
 */
es_str_t* es_newStrFromSubStr(es_str_t *str, es_size_t start, es_size_t len);
```

**Comment by PascalWithopf** [comment]
The documentation was changed and describes the behaviour correctly.
