### ISSUE TITLE
lost  log messages in kafka (using udp input)

### ISSUE THREAD

**Issue by whxloveyrh** [rsyslog/rsyslog#3347]
### Expected behavior
Rsyslog does not lose messages
### Actual behavior
messages are lost

### Steps to reproduce the behavior
Not sure. Happens unexpectedly.

### Environment
[root@instance-9vpkj6o4 etc]# rsyslogd -v
rsyslogd 8.24.0-34.el7, compiled with:
	PLATFORM:				x86_64-redhat-linux-gnu
	PLATFORM (lsb_release -d):
	FEATURE_REGEXP:				Yes
	GSSAPI Kerberos 5 support:		Yes
	FEATURE_DEBUG (debug build, slow code):	No
	32bit Atomic operations supported:	Yes
	64bit Atomic operations supported:	Yes
	memory allocator:			system default
	Runtime Instrumentation (slow code):	No
	uuid support:				Yes
	Number of Bits in RainerScript integers: 64

See http://www.rsyslog.com for more information.

client:
my client is nginx, configuraiton in nginx.conf  file as follow:

http {

    log_format jsonlog '{'
                   '"remote_addr": "$remote_addr",'
                   '"remote_user": "$remote_user",'
                   '"time_local": "$time_local",'
                   '"request": "$request",'
                   '"status": "$status",'
                   '"body_bytes_sent": "$body_bytes_sent",'
                   '"http_referer": "$http_referer",'
                   '"http_user_agent": "$http_user_agent",'
                   '"http_x_forwarded_for": "$http_x_forwarded_for"'
                   '}';
    access_log syslog:server=X.X.X.X,facility=local7,tag=access_nginx_log,severity=info jsonlog;
...
}

server:

 in /etc/rsyslog.d/kafka_cluster.conf file

[root@instance-9vpkj6o4 rsyslog.d]# cat kafka_cluster.conf
module(load="imudp")
input(type="imudp" port="514")

# nginx access log ==> rsyslog server(local) ==> kafka
module(load="omkafka")

template(name="nginxLog" type="string" string="%msg%")

if $inputname == "imudp" then {
    if ($programname == "access_nginx_log") then
        action(type="omkafka"
            template="nginxLog"
            broker=["127.0.0.1:9092"]
            topic="nginxTest"
            partitions.auto="on"
            confParam=[
                "socket.keepalive.enable=true"
            ]
        )
}

:rawmsg, contains, "access_nginx_log" ~

method: ab -n 10000 -c 400 http://client_ip/

I capture packet with wireshark/tcpdump in server. I can find there are 10000 udp record.

but, I find the module of kafka consumer  only 400~500 record.

Why is there a risk of data loss.

**Comment by rgerhards** [comment]
I would bet the prime loss is by kafaka - we know the version used does not work. So all but an update is fruitless effort.
