### ISSUE TITLE
Seg. fault when no hostname defined

### ISSUE THREAD

**Issue by hassonofer** [rsyslog/rsyslog#335]
On FreeBSD 10.1 (amd64), if no hostname is defined, rsyslogd crashes with seg fault.
After defining a hostname, it works perfect.

**Comment by rgerhards** [comment]
Can you please provide some more details, e.g which input you try to use.

**Comment by hassonofer** [comment]
It crashed right after 'service rsyslogd start'.
It happened on qemu, using the official vm-image. (ftp://ftp.freebsd.org/pub/FreeBSD/releases/VM-IMAGES/10.1-RELEASE/amd64/Latest/).
It happened in a "closed" (disconnected) lab, so I could not take logs or other information to post here.

**Comment by rgerhards** [comment]
confirmed and analyzed via #1040
