### ISSUE TITLE
Can't load modules like mmnormalize & omelasticsearch in rsyslog v 8.24.0 using the module(load) command.

### ISSUE THREAD

**Issue by shannider** [rsyslog/rsyslog#3379]
The rsyslogd -N1 shows the following message on terminal:

rsyslogd: could not load module '/usr/lib64/rsyslog/mmnormalize.so', dlopen: /usr/lib64/rsyslog/mmnormalize.so: cannot open shared object file: No such file or directory

**Comment by shannider** [comment]
I am using Centos 7. I have tried removing & reinstalling rsyslog. The imjournal module is already loaded. What seem to be the issue here?

**Comment by rgerhards** [comment]
mmnormalize and omelasticsearch are in separate packages. you need to install them. Note the 8.24.0 is pretty old and there are most probably a couple of bugs compared to the current version. In our repository, the package is rsyslog-packagename, e.g. rsyslog-mmnormalize.

**Comment by shannider** [comment]
Thanks :)
