### ISSUE TITLE
imfile read not working after the upgrade 

### ISSUE THREAD

**Issue by jehanzaibkiani** [rsyslog/rsyslog#3396]
Hi team,

I have just upgraded the rsyslog version to v8.24.0-34.el7 a few days back and now my logs are not working. I can't see anything wrong with my configuration. I have followed the stable release documentation. I can see one message in /var/log/messages
2019-01-07T11:24:26.097366+13:00 auth1 rsyslogd: command 'SystemLogSocketName' is currently not permitted - did you already set it via a RainerScript command (v6+ config)? [v8.24.0-34.el7 try http://www.rsyslog.com/e/2222 ]

My application is writing to the /var/log/myfile.log quite frequently. I cant see anything to be written in /var/log/messages either and nothing is sent to my other log server either.

### Environment
- rsyslog version: v8.24.0-34.el7
- platform: CentOS Linux release 7.6.1810 (Core)

Her is my config

module(load="imfile")
module(load="imuxsock") 
module(load="imklog")   
input(type="imfile"
File="/var/log/myfile.log"
Tag="myfile-log:"
MaxLinesAtOnce="0"
addMetadata="on"
Facility="local7")
$WorkDirectory /var/lib/rsyslog
$IncludeConfig /etc/rsyslog.d/*.conf
auth,authpriv.*                 /var/log/auth.log
*.*;auth,authpriv.none          -/var/log/messages
cron.*                          /var/log/cron.log
daemon.*                        -/var/log/daemon.log
kern.*                          -/var/log/kern.log
lpr.*                           -/var/log/lpr.log
mail.*                          -/var/log/mail.log
user.*                          -/var/log/user.log
 * .  *                         @xx.xx.xx.xx:1514

**Comment by rgerhards** [comment]
8.24 is pretty old. Most importantly, `imfile` has received a full refactoring and many bugfixes since them. I suggest to update to the current version (8.40 as of this writing) and see if the problem persists.
