### ISSUE TITLE
Memory issue using mmexternal

### ISSUE THREAD

**Issue by ShimiTaNaka** [rsyslog/rsyslog#3399]
### Environment
- rsyslog version: 8.35.0
- platform: CentOS release 6.10 (Final)
- for configuration questions/issues, include rsyslog.conf and included config files

I have the following configuration:
```
module (load="mmexternal")
module (load="imudp")
input(
  type="imudp"
  address="127.0.0.1"
  port="514"
  ruleset="haproxy_filter"
)

ruleset(name="haproxy_filter") {
  action(
    name="token_remover"
    type="mmexternal"
    binary="/usr/local/filter.py"
    interface.input="msg"
  )
  action(
    type="omfile"
    dirCreateMode="0700"
    FileCreateMode="0644"
    FileOwner="haproxy"
    File="/var/log/haproxy/haproxy.log"
  )
  stop
}
```
we have the setup running on 2 different servers, however, only on the active server we see rsyslog consuming more and more memory
We added statistics, and we don't see any queue being accumulated.
The memory increase is clearly on the rsyslog and not on the filter.
Per graphs, the action processes about 1.2k event per second.

**Comment by imriz** [comment]
Some more on this issue. It seems to be happening when the script returns non empty json (that is, there are changes to be made to the original message).

I am not expert, but should "json" be free`ed too here -> https://github.com/rsyslog/rsyslog/blob/f748ff9383487a1ba0498f0859bb17109ba2a028/runtime/msg.c#L4581

**Comment by imriz** [comment]
Could it be that there is a missing "json_object_put()" in
https://github.com/rsyslog/rsyslog/blob/f748ff9383487a1ba0498f0859bb17109ba2a028/runtime/msg.c#L4639 ?

**Comment by rgerhards** [comment]
This sounds like a bug fixed in 8.38 four month ago. I highly suggest to update to the currently supported version 8.41.

**Comment by ShimiTaNaka** [comment]
I see in the repos that only 8.40 is available (?)

**Comment by rgerhards** [comment]
> I see in the repos that only 8.40 is available (?)

sorry, my bad. 8.40 it is.

**Comment by imriz** [comment]
It seems 8.40 resolves it. Looking at the commits (https://github.com/rsyslog/rsyslog/commit/77193c307734bb6076a069b2d282c3579ca9410e#diff-c364c534d201059111306d3411287567) it seems it was indeed a missing json_object_put() ?

**Comment by rgerhards** [comment]
> It seems 8.40 resolves it. Looking at the commits ([77193c3#diff-c364c534d201059111306d3411287567](https://github.com/rsyslog/rsyslog/commit/77193c307734bb6076a069b2d282c3579ca9410e#diff-c364c534d201059111306d3411287567)) it seems it was indeed a missing json_object_put() ?

TBH I would not like to dig in deep into a resolved issue. I remember it was complex.
