### ISSUE TITLE
add action.resumeIntervalMax (or similar) config setting

### ISSUE THREAD

**Issue by rgerhards** [rsyslog/rsyslog#3401]
The idea is to have an upper limit for the retry interval. This is most useful when a target has extended outage, in which case retries can happen very infrequently.

**Comment by davidelang** [comment]
we should have this default to a sane value (every hour???) rather than 
defaulting to be unlimited.

**Comment by rgerhards** [comment]
> we should have this default to a sane value (every hour???) rather than defaulting to be unlimited.

ack - I think this also is not a backward compatibility problem. I'd say half an hour is also good as well?

**Comment by davidelang** [comment]
On Thu, 10 Jan 2019, Rainer Gerhards wrote:

>> we should have this default to a sane value (every hour???) rather than defaulting to be unlimited.
>
> ack - I think this also is not a backward compatibility problem. I'd say half an hour is also good as well?

Yes, I'd say 30 min max retry is pleanty long enough as a default.
