### ISSUE TITLE
could not load module 'lmnet', errors

### ISSUE THREAD

**Issue by whxloveyrh** [rsyslog/rsyslog#3405]
7065.990482400:main thread    : rsyslogd.c: rsyslogd 8.38.0 startup, module path '', cwd:/home/test/output
7065.990557680:main thread    : glbl.c: rsyslog/glbl: using '127.0.0.1' as localhost IP
7065.990596250:main thread    : obj.c: caller requested object 'net', not found (iRet -3003)
7065.990604727:main thread    : modules.c: Requested to load module 'lmnet'
7065.990615513:main thread    : modules.c: loading module '/home/rsyslog/lib/rsyslog/lmnet.so'
7065.990652210:main thread    : errmsg.c: Called LogMsg, msg: could not load module 'lmnet', errors: trying to load module /home/rsyslog/lib/rsyslog/lmnet.so: /home/rsyslog/lib/rsyslog/lmnet.so: cannot open shared object file: No such file or directory
rsyslog internal message (3,-2066): could not load module 'lmnet', errors: trying to load module /home/rsyslog/lib/rsyslog/lmnet.so: /home/rsyslog/lib/rsyslog/lmnet.so: cannot open shared object file: No such file or directory [v8.38.0 try http://www.rsyslog.com/e/2066 ]
Error during class init for object 'conf' - failing...
rsyslogd initializiation failed - global classes could not be initialized.
Did you do a "make install"?
Suggested action: run rsyslogd with -d -n options to see what exactly fails.
rsyslogd: run failed with error -2066 (see rsyslog.h or try http://www.rsyslog.com/e/2066 to learn what that number means)

**Comment by rgerhards** [comment]
This looks like a problem with the installation. How did you install
rsyslog?

Sent from phone, thus brief.

Am Mi., 9. Jan. 2019, 13:38 hat whxloveyrh <notifications@github.com>
geschrieben:

**Comment by rgerhards** [comment]
You should check that you use correct values for --bindir, --sbindir, --libdir, ...

check that `make install` actually installs to where you want. Be sure to copy the files to the exact same locations. Also, ensure that build and target system are identical.
