### ISSUE TITLE
Difference between openssl and gtls client config requirements

### ISSUE THREAD

**Issue by tedg** [rsyslog/rsyslog#3413]
Hi, I'm looking to switch my rsyslog client configuration from gtls to the newer openssl driver, and I'm finding that when I change the driver to `ossl` it won't start up, whereas with `gtls` everything is fine. I was under the impression this was a drop-in replacement, but I'm not able to get this working.

Here's a snippet of my config.
```
$DefaultNetstreamDriverCAFile /path/to/provider-cert.crt

action(type="omfwd" protocol="tcp" target="logs-01.provider.com" port="6514" template="FormatFile" StreamDriver="ossl" StreamDriverMode="1" StreamDriverAuthMode="x509/name" StreamDriverPermittedPeers="*.provider.com")
```

As you can see I'm only defining `DefaultNetstreamDriverCAFile` and it works fine on `gtls`, but `ossl` complains about missing cert files. 

```
rsyslogd: Error: Certificate file is not set, cannot continue [v8.40.0 try https://www.rsyslog.com/e/2330 ]
rsyslogd: could not load module '/lib64/rsyslog/lmnsd_ossl.so', rsyslog error -2330  [v8.40.0 try https://www.rsyslog.com/e/2068 ]
rsyslogd: action 'action-8-builtin:omfwd' suspended (module 'builtin:omfwd'), retry 0. There should be messages before this one giving the reason for suspension. [v8.40.0 try https://www.rsyslog.com/e/2007 ]
```

I checked the source code and found that `ossl` does indeed require the cert file and key file directives. I created a self signed cert and added `DefaultNetstreamDriverCertFile` and `DefaultNetstreamDriverKeyFile` to my config and rsyslog started but did not send anything.

My question is why does the driver for `ossl` require `DefaultNetstreamDriverCertFile` and `DefaultNetstreamDriverKeyFile`? Other documentation I have read indicates that for a client rsyslog process, just including `DefaultNetstreamDriverCAFile` should be fine

Thank you for your time, here's my version info for completeness.

```
rsyslogd 8.40.0, compiled with:
        PLATFORM:                               x86_64-redhat-linux-gnu
        PLATFORM (lsb_release -d):
        FEATURE_REGEXP:                         Yes
        GSSAPI Kerberos 5 support:              No
        FEATURE_DEBUG (debug build, slow code): No
        32bit Atomic operations supported:      Yes
        64bit Atomic operations supported:      Yes
        memory allocator:                       system default
        Runtime Instrumentation (slow code):    No
        uuid support:                           Yes
        systemd support:                        No
        Number of Bits in RainerScript integers: 64
```

**Comment by rgerhards** [comment]
Thx for the report. From a design point of view, these should be working interchangeable with no need to modify (except if GnuTLS priority string is used). So this sounds like a bug.

@alorbach could you have a look? Maybe best to craft a testcase for both gtls and ossl based on provided config?

**Comment by alorbach** [comment]
The driver requires certificates because we do not support certless communciation (anon ciphers) at the moment. Simular things were discussed in #3037 and #2547. 

We need to allow anon ciphers, when no cert/key is configured then we can remove the need to configure both.

**Comment by rgerhards** [comment]
@alorbach well... the point is: if **gtls supports this (!)** why does ossl not? So far I was under the impression that was a general thing.

**Comment by alorbach** [comment]
@tedg : Can you check all of your configuration if? Are you sure it works without defaultNetstreamDriverCertFile/defaultNetstreamDriverKeyFile? 
 
I am using the testcase sndrcv_tls_anon_ipv4.sh and once I remove the defaultNetstreamDriverCertFile/defaultNetstreamDriverKeyFile the whole test fails.

**Comment by alorbach** [comment]
@tedg Yes using self made cert/key is always the recommended way. 
However that it works without cert/key is very suspicious. 
Because at the moment, when no cert/key is configured it will fail to init gtls session properly.

**Comment by rgerhards** [comment]
@tedg just a general note on certless mode: it is pretty insecure. Without cert, you don't know who you talk to. So the connection can still be spoofed. But you don't need a full PKI or paid certs to make things secure: this is what fingerprint mode is for. Create your self-singned cert, make the peer check the fingerprint and you are done. If you want to weaken security a bit in favor of simplicity, you can deploy your self-signed cert (the same one!) to all clients. The fingerprint is always the same, but you still know that it is one of *your* systems you are talking to. Plus, no spoofing possible. That's why we originally have no certless mode and that is why RFC5425 recommends against it.

**Comment by rgerhards** [comment]
@tedg nevertheless, I would like to see why gnutls works without cert in your case. Can you create a debug log of rsyslog startup with your gnutls config and post it? Instructions: https://www.rsyslog.com/doc/v8-stable/troubleshooting/howtodebug.html If you don't want to post, you can also email my privately.

**Comment by tedg** [comment]
Sent to your email

**Comment by tedg** [comment]
@rgerhards @alorbach Just trying to make sure we are on the same page here. Every cloud log provider I can find has these same instructions for encrypting with gtls. Obviously the CAFile is different for each, but that's what they tell their users to do, and it works with gtls.

```
$DefaultNetstreamDriverCAFile /etc/rsyslog.d/keys/ca.d/logs-01.loggly.com_sha12.crt
$ActionSendStreamDriver gtls
$ActionSendStreamDriverMode 1
$ActionSendStreamDriverAuthMode x509/name
$ActionSendStreamDriverPermittedPeer *.loggly.com
```

Are you saying that all of these instructions are actually an insecure configuration? Or are you talking above about another use-case that does not apply to me.

Here are some examples of log providers that have these instructions to only set `DefaultNetstreamDriverCAFile `

https://docs.logentries.com/docs/rsyslog
https://docs.datadoghq.com/integrations/rsyslog/?tab=datadogusappdatadoghqcom
https://www.loggly.com/docs/rsyslog-tls-configuration/
https://help.papertrailapp.com/kb/configuration/encrypting-remote-syslog-with-tls-ssl/#rsyslogconf

**Comment by rgerhards** [comment]
@tedg thx for the debug log, will have a look tomorrow. The instructions are save, because you check the remote peer. Well, actually the cloud provider does not know if a wrong system sends data to it, except if it would verify that systems cert (I guess they rely on other auth, what is not too bad but also not really great). But I now need to work with @alorbach to see why there is a discrepancy between what we think and what actually happens - the debug log should help to sort that out.
