### ISSUE TITLE
parameter "tmp_cursor" need free after used.

### ISSUE THREAD

**Issue by ChenQianCQ** [rsyslog/rsyslog#3433]
https://github.com/rsyslog/rsyslog/blob/792f1e50e0bc2eac17cf7ee0b9a1a71c4a6b5707/plugins/imjournal/imjournal.c#L624

**Comment by jvymazal** [comment]
looks correct (that is, the bug is there), will follow with PR.

**Comment by rgerhards** [comment]
@jvymazal thx a ton! Do you think we could try to reproduce this with a CI test (and valgrind?). That would be a nice addition.

**Comment by rgerhards** [comment]
@ChenQianCQ thx again! Are you willing to submit a PR? That would really be phantastic! Also everyone would see from the commit history that you did great work. I am happy to help with get it going.
