### ISSUE TITLE
omkafka socket question

### ISSUE THREAD

**Issue by Entiy** [rsyslog/rsyslog#3434]
### Actual behavior
   As rsyslog pushes data into kafka, the number of socket connections to the broker keeps increasing, and when I restart rsyslog, those socket connections don't close

### Steps to reproduce the behavior
When I restart rsyslog, I see on the broker that the previous socket is not closed

I use this command to view the connection status on the broker

lsof -i:9092 | grep 'ESTABLISHED'  | grep 10.85.206.153

### Environment
- rsyslog version:  8.37.0

**Comment by rgerhards** [comment]
The sockets are opened by `librdkafka`, which is known to use many sockets under high activity, see https://github.com/edenhill/librdkafka/issues/825.

I guess the sockets remain open after shutdown only for a short period of time. After all, if the process went away, the OS cleans up. Not sure if librdkafka did not cleanup properly or they are actually in linger state.

**Comment by Entiy** [comment]
> The sockets are opened by `librdkafka`, which is known to use many sockets under high activity, see [edenhill/librdkafka#825](https://github.com/edenhill/librdkafka/issues/825).
> 
> I guess the sockets remain open after shutdown only for a short period of time. After all, if the process went away, the OS cleans up. Not sure if librdkafka did not cleanup properly or they are actually in linger state.

These socket connections don't just exist for a short time, they exist all the time. However, with the 8.40 version of rsyslog, this did not happen.

**Comment by Entiy** [comment]
@rgerhards 
My kafka version is 0.8.
You can reproduce this problem with version 8.37 of rsyslog

**Comment by rgerhards** [comment]
> However, with the 8.40 version of rsyslog, this did not happen.

ok, so the solutions seems to be simple: just upgrade.

**Comment by Entiy** [comment]
@rgerhards 
However, I would like to confirm that the 8.37 version of rsyslog does have the code to cause this problem.

**Comment by Entiy** [comment]
@rgerhards 
Can you help me? Thank you Mr.

**Comment by rgerhards** [comment]
well, I have no time to check something that appears to be either a) fixed or b) not inside rsyslog. Maybe someone else want's to jump in that old stuff. If this if for biz use, you can also look into https://www.rsyslog.com/professional-services/ where old versions are supported.

**Comment by Entiy** [comment]
@rgerhards 
Okay, thanks
