### ISSUE TITLE
Kernel messages logged with delay of several minutes

### ISSUE THREAD

**Issue by sla89** [rsyslog/rsyslog#3439]
### Expected behavior
Kernel log messages are logged immediately. 

### Actual behavior
The kernel log messages are logged with a huge delay (in my case several minutes).
I can see the kernel log messages already using `dmesg` but they are not in my log file. Other messages, e.g. genererated by applications, are logged immediately.

I don't know yet what triggers rsyslog to process the messages that I have seen minutes before using `dmesg`. These are the messages I see with a delay in my syslog file:

```shell
[  384.461864] CPU0: Package temperature above threshold, cpu clock throttled (total events = 1)
[  384.462886] CPU0: Package temperature/speed normal
[  685.369868] CPU0: Core temperature above threshold, cpu clock throttled (total events = 114)
[  685.369870] CPU0: Package temperature above threshold, cpu clock throttled (total events = 115)
[  685.370838] CPU0: Package temperature/speed normal
```

Some of them are critical messages.

### Steps to reproduce the behavior
In my case, as you can see above, the temperature of my CPU reached a threshold. 

### Environment
rsyslogd 8.39.0.master, compiled with:
	PLATFORM:				x86_64-pc-linux-gnu
	PLATFORM (lsb_release -d):		
	FEATURE_REGEXP:				Yes
	GSSAPI Kerberos 5 support:		No
	FEATURE_DEBUG (debug build, slow code):	No
	32bit Atomic operations supported:	No
	64bit Atomic operations supported:	No
	memory allocator:			system default
	Runtime Instrumentation (slow code):	No
	uuid support:				No
	systemd support:			No
	Number of Bits in RainerScript integers: 64

Configuration:

```shell
# configuration file for rsyslogd

#
# modules
#
module(load="imuxsock") # local messages via unix socket
module(load="imklog")   # kernel messages
module(load="imudp")    # local message via udp socket

#
# udp socket configuration
#
input(type="imudp" port="514" address="127.0.0.1")

#
# Set the default permissions for all log files
# and the rsyslogd process
#
$FileOwner syslog
$FileGroup syslog
$FileCreateMode 0640
$Umask 0027
$PrivDropToUser syslog
$PrivDropToGroup syslog

#
# log rotation via outchannel
# file size limit is in bytes, no abbreviations (k, m, ...) possible
# rotate when file size reaches 1mb
$outchannel syslog_rotation,/var/log/syslog, 1048576, syslog_rotate.sh /var/log/syslog

#
# custom output with high res timestamps and log level for the log file
#
template(name="template_syslog" type="list") {
    property(name="timestamp" dateFormat="rfc3339" position.from="1" position.to="23")
    constant(value=" ")
    property(name="hostname")
    constant(value=" ")
    property(name="syslogfacility-text")
    constant(value=".")
    property(name="syslogseverity-text")
    constant(value=" ")
    property(name="syslogtag")
    property(name="msg" spifno1stsp="on" )
    property(name="msg" droplastlf="on" )
    constant(value="\n")
    }

#
# everything else (no debug messages!)
#
*.info :omfile:$syslog_rotation;template_syslog
```

Do you have an idea what causes the delay? Thank you!

**Comment by rgerhards** [comment]
> Do you have an idea what causes the delay? Thank you!

actually ... no. Can you reproduce this or was it a one-time thing?

**Comment by sla89** [comment]
Yes, I can reproduce this behavior. 

I have tried to debug the issue by extending my configuration by the following lines:

```shell
syslog.=debug /var/log/rsyslog_stats.log

$DebugFile /var/log/syslog_debug.log
$DebugLevel 2
```

All I could see was that the messages really were not processed in any form but rsyslog was processing messages from other application. Suddenly (after some minutes) all the open kernel messages were processed by rsyslog. I could see it in the debug file. After that the missing messages were also in the syslog file.

**Comment by rgerhards** [comment]
can you share the debug file?

**Comment by sla89** [comment]
How shall I share it with you? Do you have any preferred way?

**Comment by rgerhards** [comment]
you could use pastebin or maybe a github gist. Email would also work for me (but exclude others from looking at the case)

**Comment by rgerhards** [comment]
just let us know when you have a log
