### ISSUE TITLE
Rsyslog is Eating my flash,

### ISSUE THREAD

**Issue by arunkvnss** [rsyslog/rsyslog#3443]
### Environment
- rsyslog version: 
- platform: 
- for configuration questions/issues, include rsyslog.conf and included config files

Downloaded a new rsyslog configuration file to /etc and rebooted the device,but unfortunately my configuration contains a wrong line as mentioned below

‘Storage_mode.=$outchannel’

This outchannel is already described in the configuration file for handling the pppd logs!

And I took sshd connection and ran the df -h command in watch, I am using ubifs filesystem and rsyslog version 7.0. Something.the root file system size is increasing and finally reach to the maximum volume size!  When I remove that above mentioned line then everything is perfect!

I went through all my files in file system especially rsyslog log files, there is no big increment and that too rotated by logrotate. Still I don’t know how this daemon utilises my flash

**Comment by jgerhards** [comment]
Since this is a **very** old version of rsyslog (current version: 8.1901.0), the problem will most likely fix itself when updating. If you do not wish to update, I am afraid that the rsyslog version you are using is no longer supported.

**Comment by arunkvnss** [comment]
I am extremely sorry that the rsyslogd version is not 7.0, it is mentioned below.
rsyslogd -version
rsyslogd 8.29.0, compiled with:
        PLATFORM:                               arm-poky-linux-gnueabi
        PLATFORM (lsb_release -d):
        FEATURE_REGEXP:                         Yes
        GSSAPI Kerberos 5 support:              No
        FEATURE_DEBUG (debug build, slow code): No
        32bit Atomic operations supported:      Yes
        64bit Atomic operations supported:      No
        memory allocator:                       system default
        Runtime Instrumentation (slow code):    No
        uuid support:                           Yes
        Number of Bits in RainerScript integers: 64

**Comment by arunkvnss** [comment]
Actually i have not deleted any files in my filesystem, When i remove the below line it works perfect.

Storage_mode.=$outchannel’

What is the significance in the above line in rsyslogd

**Comment by davidelang** [comment]
On Wed, 30 Jan 2019, arunkvnss wrote:

> Actually i have not deleted any files in my filesystem, When i remove the below line it works perfect.
>
> Storage_mode.=$outchannel’
>
> What is the significance in the above line in rsyslogd

I believe that that would be a syntax error if it stands by itself.

David Lang

**Comment by arunkvnss** [comment]
"I believe that would be a syntax error if it stands by itself. "

That i agree, But how come the flash utilization is increasing ?  :)

**Comment by davidelang** [comment]
if you have a syntax error in your config, who knows what it's doing (especially 
since we don't have the rest of your config).

once there is a syntax error, it could make the rest of the config invalid and 
the config parser can do all sorts of odd things.

David Lang

**Comment by rgerhards** [comment]
I would guess it treats it as filename that it then writes to. To be sure,
I'd need to check the grammar. The debug log would easily tell what it does.

Rainer

Sent from phone, thus brief.

Am Do., 31. Jan. 2019, 21:10 hat David Lang <notifications@github.com>
geschrieben:

**Comment by arunkvnss** [comment]
Yes ! I have ran the rsyslog manualy with debug and interactive mode, Observed some configuration error, It did not quite the execution,
I will send you those logs as soon as possible, And observed one more thing that if I run with verbose mode even if the wrong configuration element is there it won’t utilise my flash!


Thank you so much for your immediate replay,
Have a great day
