### ISSUE TITLE
Rsyslog module "imfile.c" monitor only 100 files so far with an option MAX_INPUT_FILES

### ISSUE THREAD

**Issue by naikganesh** [rsyslog/rsyslog#3447]
### Expected behaviour
Need to increase the limit of an option "MAX_INPUT_FILES" in rsyslog module "imfile.c".
Currently, only 100 files can be monitored.

### Actual behaviour
Rsyslog module "imfile.c" monitor only 100 files so far with an option MAX_INPUT_FILES.
Upstream link: https://www.rsyslog.com/doc/v5-stable/configuration/modules/imfile.html

### Environment

[root@rhel7 ~]# rsyslogd -version
rsyslogd 8.24.0-34.el7, compiled with:
	PLATFORM:				x86_64-redhat-linux-gnu
	PLATFORM (lsb_release -d):		
	FEATURE_REGEXP:				Yes
	GSSAPI Kerberos 5 support:		Yes
	FEATURE_DEBUG (debug build, slow code):	No
	32bit Atomic operations supported:	Yes
	64bit Atomic operations supported:	Yes
	memory allocator:			system default
	Runtime Instrumentation (slow code):	No
	uuid support:				Yes
	Number of Bits in RainerScript integers: 64

See http://www.rsyslog.com for more information.
[root@rhel7 ~]# 

- Platform: RHEL7 and RHEL8

[root@rhel7 ~]# more /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.3 (Maipo)
[root@workstation ~]# uname -r
3.10.0-514.el7.x86_64
[root@rhel7 ~]# 

######################################

It will be nice to have a higher value for the limit something as 100000 for MAX_INPUT_FILES in imfile.c.

So, it will limit the number of files descriptor to limit the number of files by the classical Unix/Linux way by the ulimit.

Below the way, I it should be managed. Check current limits form rsyslog pid process:
By example:

[root@rhel7 rsyslog.d]# ps -ef | grep rsyslog | grep -v grep
root     22193     1  0 Jan19 ?        00:00:00 /usr/sbin/rsyslogd -n
[root@rhel7 rsyslog.d]# cat /proc/22193/limits | grep "Max open files"
Max open files            1024                 4096                 files

So just need to duplicate change: /usr/lib/systemd/system/rsyslog.service 

[root@rhel7 rsyslog.d]# cat /usr/lib/systemd/system/rsyslog.service
[Unit]
Description=System Logging Service
;Requires=syslog.socket
After=network.target

[Service]
Type=notify
EnvironmentFile=-/etc/sysconfig/rsyslog
ExecStart=/usr/sbin/rsyslogd -n $SYSLOGD_OPTIONS
Restart=on-failure
UMask=0066
StandardOutput=null

[Install]
WantedBy=multi-user.target
;Alias=syslog.service

to

/etc/systemd/system/rsyslog.service

[root@rhel7 rsyslog.d]# cat /etc/systemd/system/rsyslog.service
[Unit]
Description=System Logging Service
;Requires=syslog.socket
After=network.target

[Service]
Type=notify
EnvironmentFile=-/etc/sysconfig/rsyslog
ExecStart=/usr/sbin/rsyslogd -n $SYSLOGD_OPTIONS
Restart=on-failure
UMask=0066
StandardOutput=null
LimitNOFILE=2000     <= customer adap Limit on it neeeds

[Install]
WantedBy=multi-user.target
;Alias=syslog.service
[root@rhel7 rsyslog.d]#

And after runs:
systemctl daemon-reload rsyslog after modifying the existing unit file.

######################################

**Comment by jgerhards** [comment]
Since you are using an old version of rsyslog(8.24.0), I suggest updating to the current one (8.1901.0). This might fix the problem. Also, please note that the doc you linked refers to the very outdated version developed around 2010.

**Comment by jgerhards** [comment]
quick FYI: As far as i checked, the limit you are refering to was in earlier versions, but is neither in the current version nor in 8.24.0. It is possible to monitor unlimited files.
