### ISSUE TITLE
Support RELP+TLS on tcpflood

### ISSUE THREAD

**Issue by StrongestNumber9** [rsyslog/rsyslog#3448]
```sh
 * -T   transport to use. Currently supported: "udp", "tcp" (default), "tls" (tcp+tls), relp-plain
```
Add support for RELP + TLS. This would be tremendously helpful for testing components that use authenticated imrelp+tls.

**Comment by rgerhards** [comment]
Thx, this is a very good suggestion! I'll see if we can add it to the next release.
