### ISSUE TITLE
How to distinguish a line

### ISSUE THREAD

**Issue by yfliuyanyan** [rsyslog/rsyslog#3450]
### Expected behavior
I use rsyslog to collect log. The collecting is based on line, but how to distinguish a line in rsyslog?

### Environment
- rsyslog version: [e.g. 8.36.0 -- see rsyslogd -v]
- platform: [e.g. Ubuntu 16.04]
- for configuration questions/issues, include rsyslog.conf and included config files

**Comment by jgerhards** [comment]
Unfortunatly, I do not understand. Could you please explain in other words?

**Comment by davidelang** [comment]
a newline distinuishes a line.

if you have a more detailed question, we need to see the config you are trying 
to use and a sample of the logs you are talking about.

**Comment by davidelang** [comment]
the *nix standard is \n, that's the default for rsyslog.

David Lang

**Comment by yfliuyanyan** [comment]
What about Mac and Windows?

**Comment by davidelang** [comment]
On Tue, 29 Jan 2019, yfliuyanyan wrote:

> What about Mac and Windows?

Mac is *nix, I don't know what imfile does on Windows.

David Lang

**Comment by yfliuyanyan** [comment]
Yes, I use imfile. It just support *nix, not support Windows, right?

**Comment by davidelang** [comment]
I am not familiar with the features of rsyslog for windows, it's a commercial 
product. I would suggest that you look over it's features and contact Adiscon 
directly.

I tend to use nxlog to gather logs from windows and send them to the syslog 
infrastruture.

David Lang

**Comment by rgerhards** [comment]
> Yes, I use imfile. It just support *nix, not support Windows, right?

ah! The rsyslog windows agent is a different kind of software. It is optimized for Windows. It uses \r\n by default but also can be configured to match what you need. More info at https://www.rsyslog.com/windows-agent/

**Comment by rgerhards** [comment]
I should mention that you can also ask support@adiscon.com w/ questions on the Windows agent.
