### ISSUE TITLE
error 2207; liblogging-stdlog: error during config processing: STOP is followed by unreachable statements! 

### ISSUE THREAD

**Issue by meem6** [rsyslog/rsyslog#3457]
Hello,
I am getting this error in messages, when starting rsyslogd ver 8.24

liblogging-stdlog: error during config processing: STOP is followed by unreachable statements!  [v8.24.0 try http://www.rsyslog.com/e/2207

I added those lines to rsyslog.conf to save all logs to dir structure by IP and host

$ModLoad imudp
$UDPServerRun 514
$InputUDPServerBindRuleset remote

$template RemoteLogs, "/LOGS/remote/%FROMHOST-IP%/%HOSTNAME%.%timegenerated:1:10:date-rfc3339%.log"
*.* ?RemoteLogs
& stop

The logging is working OK, but I think the configuration can be done better.
(error during config processing: STOP is followed by unreachable statements)

### Environment
rsyslogd 8.24.0
"SUSE Linux Enterprise Server 12 SP3"

**Comment by davidelang** [comment]
we would need to see the full config to see what's happening, but you have an 
unconditional stop, so the error message that statements after that point will 
never be processed is correct. How much of a problem this depends on your config

David Lang

**Comment by meem6** [comment]
the conf is rather default one, just lines for remote logging were add.

grep -v ^# /etc/rsyslog.conf |grep -v ^$
$ModLoad immark.so
$MarkMessagePeriod      3600
$ModLoad imuxsock.so
$RepeatedMsgReduction   on
$ModLoad imklog.so
$klogConsoleLogLevel    1
$ModLoad imudp
$UDPServerRun 514
$InputUDPServerBindRuleset remote
$template RemoteLogs, "/LOGS/remote/%FROMHOST-IP%/%HOSTNAME%.%timegenerated:1:10:date-rfc3339%.log"
*.* ?RemoteLogs
& stop
$IncludeConfig /run/rsyslog/additional-log-sockets.conf
$IncludeConfig /etc/rsyslog.d/*.conf
$FileOwner root
$FileGroup root
$FileCreateMode 0640
$DirCreateMode 0750
$Umask 0022
if      ( \
            /* kernel up to warning except of firewall  */ \
            ($syslogfacility-text == 'kern')      and      \
            ($syslogseverity <= 4 /* warning */ ) and not  \
            ($msg contains 'IN=' and $msg contains 'OUT=') \
        ) or ( \
            /* up to errors except of facility authpriv */ \
            ($syslogseverity <= 3 /* errors  */ ) and not  \
            ($syslogfacility-text == 'authpriv')           \
        ) \
then {
        /dev/tty10
        |/dev/xconsole
}
*.emerg                                  :omusrmsg:*
if      ($syslogfacility-text == 'kern') and \
        ($msg contains 'IN=' and $msg contains 'OUT=') \
then {
        -/var/log/firewall
        stop
}
if      ($programname == 'acpid' or $syslogtag == '[acpid]:') and \
        ($syslogseverity <= 5 /* notice */) \
then {
        -/var/log/acpid
        stop
}
if      ($programname == 'NetworkManager') or \
        ($programname startswith 'nm-') \
then {
        -/var/log/NetworkManager
        stop
}
mail.*                                  -/var/log/mail
mail.info                               -/var/log/mail.info
mail.warning                            -/var/log/mail.warn
mail.err                                 /var/log/mail.err
news.crit                               -/var/log/news/news.crit
news.err                                -/var/log/news/news.err
news.notice                             -/var/log/news/news.notice
*.=warning;*.=err                       -/var/log/warn
*.crit                                   /var/log/warn
*.*;mail.none;news.none                 -/var/log/messages
local0.*;local1.*                       -/var/log/localmessages
local2.*;local3.*                       -/var/log/localmessages
local4.*;local5.*                       -/var/log/localmessages
local6.*;local7.*                       -/var/log/localmessages

**Comment by davidelang** [comment]
On Thu, 7 Feb 2019, meem6 wrote:

> the conf is rather default one, just lines for remote logging were add.

yes, you say to write all logs to files using the remotelogs template, and then 
to stop processing all logs, so nothing after that will be processed.

The warning message is telling you that you have a lot of config that isn't 
being processed because of the stop action.

what are you intending to happen?

> grep -v ^# /etc/rsyslog.conf |grep -v ^$
> $ModLoad immark.so
> $MarkMessagePeriod      3600
> $ModLoad imuxsock.so
> $RepeatedMsgReduction   on
> $ModLoad imklog.so
> $klogConsoleLogLevel    1
> $ModLoad imudp
> $UDPServerRun 514
> $InputUDPServerBindRuleset remote
> $template RemoteLogs, "/LOGS/remote/%FROMHOST-IP%/%HOSTNAME%.%timegenerated:1:10:date-rfc3339%.log"
> *.* ?RemoteLogs
> & stop

nothing after this is processed.

David Lang

> $IncludeConfig /run/rsyslog/additional-log-sockets.conf
> $IncludeConfig /etc/rsyslog.d/*.conf
> $FileOwner root
> $FileGroup root
> $FileCreateMode 0640
> $DirCreateMode 0750
> $Umask 0022
> if      ( \
>            /* kernel up to warning except of firewall  */ \
>            ($syslogfacility-text == 'kern')      and      \
>            ($syslogseverity <= 4 /* warning */ ) and not  \
>            ($msg contains 'IN=' and $msg contains 'OUT=') \
>        ) or ( \
>            /* up to errors except of facility authpriv */ \
>            ($syslogseverity <= 3 /* errors  */ ) and not  \
>            ($syslogfacility-text == 'authpriv')           \
>        ) \
> then {
>        /dev/tty10
>        |/dev/xconsole
> }
> *.emerg                                  :omusrmsg:*
> if      ($syslogfacility-text == 'kern') and \
>        ($msg contains 'IN=' and $msg contains 'OUT=') \
> then {
>        -/var/log/firewall
>        stop
> }
> if      ($programname == 'acpid' or $syslogtag == '[acpid]:') and \
>        ($syslogseverity <= 5 /* notice */) \
> then {
>        -/var/log/acpid
>        stop
> }
> if      ($programname == 'NetworkManager') or \
>        ($programname startswith 'nm-') \
> then {
>        -/var/log/NetworkManager
>        stop
> }
> mail.*                                  -/var/log/mail
> mail.info                               -/var/log/mail.info
> mail.warning                            -/var/log/mail.warn
> mail.err                                 /var/log/mail.err
> news.crit                               -/var/log/news/news.crit
> news.err                                -/var/log/news/news.err
> news.notice                             -/var/log/news/news.notice
> *.=warning;*.=err                       -/var/log/warn
> *.crit                                   /var/log/warn
> *.*;mail.none;news.none                 -/var/log/messages
> local0.*;local1.*                       -/var/log/localmessages
> local2.*;local3.*                       -/var/log/localmessages
> local4.*;local5.*                       -/var/log/localmessages
> local6.*;local7.*                       -/var/log/localmessages
>
>
>

**Comment by meem6** [comment]
what I want seems to be working OK, maybe I could do some performance tuning for remote logging.

all logs from remote servers (few 100s) and also the localhost, are sent to NAS "/LOGS/remote/%FROMHOST-IP%/%HOSTNAME%.%timegenerated:1:10:date-rfc3339%.log"

there is nothing in /var/log/messages (but I dont mind as the logs are on different location, same as the remote servers)

so the error is more like a warning, I have "strange" configuration, if I remove the "extra" lines then I will be ok.
Thank you David.

**Comment by davidelang** [comment]
On Thu, 7 Feb 2019, meem6 wrote:

> what I want seems to be working OK, maybe I could do some performance tuning for remote logging.
>
> all logs from remote servers (few 100s) and also the localhost, are sent to NAS "/LOGS/remote/%FROMHOST-IP%/%HOSTNAME%.%timegenerated:1:10:date-rfc3339%.log"
>
> there is nothing in /var/log/messages (but I dont mind as the logs are on different location, same as the remote servers)

that is because you have told rsyslog to throw away the log before getting to 
the point that you would write to /var/log/messages.

> so the error is more like a warning, I have "strange" configuration, if I remove the "extra" lines then I will be ok.

yes, if you remove all the actions after the stop, the warning will go away.

David Lang
