### ISSUE TITLE
Send Seprate Line Messages With OMAMQP1

### ISSUE THREAD

**Issue by alah64** [rsyslog/rsyslog#3467]
### Actual behavior
When I Send Multiple Messages To Rsyslog (eg: 100 eps)  , OMAMQP1 Sends Them In One Or More Messages Together.

### Steps to reproduce the behavior
I Need Something To Configure Rsyslog And Tell Him Send Every Message Seperatly  .

### Environment
- rsyslog version: 8.1901.0
- platform:  Ubuntu 18.04

**Comment by davidelang** [comment]
set your batchsize to 1 for that action.

David Lang

**Comment by alah64** [comment]
> 
> set your batchsize to 1 for that action. David Lang

Thanks
I Use This :
```config
input(type="imtcp" port="514" ruleset="singleMessage"  )
ruleset(name="singleMessage"
        queue.type="fixedArray"
        queue.size="1000"
        queue.dequeueBatchSize="1"
        queue.workerThreads="4"
        queue.workerThreadMinimumMessages="250"
       ) {
	
if $msg contains "mytest" then 
{
  action(
    type="omamqp1"
    host="127.0.0.1:5672" 
    target="mytest"
   )
   stop

 }  }

if $msg contains "AAA" then 
{
# Other Outputs
}
```
Is This The Way You Had Proposed?
In This Way I Think workerThreads Does Not Work Correctly . Is That Right?
The Other Is Whether The dequeueBatchSize="1" Will Have a Negative Effect On Other Outputs?

**Comment by rgerhards** [comment]
The main problem is that omqmqp1 is a contributed module - we need someone who looks into the code. Maybe best to try to contact the original author.

**Comment by davidelang** [comment]
On Thu, 14 Feb 2019, alah64 wrote:

>> set your batchsize to 1 for that action. David Lang
>
> Thanks
> I Use This :
> ```config
> input(type="imtcp" port="514" ruleset="singleMessage"  )
> ruleset(name="singleMessage"
>        queue.type="fixedArray"
>        queue.size="1000"
>        queue.dequeueBatchSize="1"
>        queue.workerThreads="4"
>        queue.workerThreadMinimumMessages="250"

you probably don't want to set threads=4 unless you test first. I also don't 
think you want to set minimum messages=250 if you are setting the batchsize 
(maximum messages) = 1

David Lang
