### ISSUE TITLE
imfile: rsyslog stops watching certain files

### ISSUE THREAD

**Issue by malsumis** [rsyslog/rsyslog#3468]
Hi,

I have a problem with rsyslog in that imfile stops ingesting files and sending them over to a remote server. Most of the log files are generated and maintained using logback or log4j. 

I have noticed that the state files have stale info in them, and that each monitored file has up to 3 state files. For example:

\# ls -i 
2152637302 /var/log/misc/app/app.log (size is 83380)

/var/spool/rsyslog\# ls -1i *2152637302*
 1633700 -rw------- 1 syslog syslog 144 Feb  5 00:02 /var/spool/rsyslog/imfile-state:2152637302
 1657220 -rw------- 1 syslog syslog 144 Feb  4 23:28 /var/spool/rsyslog/imfile-state:2152637302:0b2a8dee974302b1
14807902 -rw------- 1 syslog syslog 144 Jan 24 23:17 /var/spool/rsyslog/imfile-state:2152637302:2204f10cd2aad7ab

these are all 144 bytes in size and contain roughly the same content, for example:
{ "filename": "\/var\/log\/misc\/app\/app.log", "prev_was_nl": 1, "curr_offs": 1853906, "strt_offs": 1853906 }

Let me add that there are a lot of state files: 

\#:/var/spool/rsyslog# ls -l  | wc -l
1686

What might be the reason that rsyslog stops checking the files? Might this be a configuration problem? Too many files to monitor? Might the inotify watch limit be the case? What else can I do to troubleshoot this?

Relevant config:

input(type="imfile"
  File="/var/log/misc/\*/\*.log"
  addMetadata="on"
  escapeLF="off"
  PersistStateInterval="100"
  Tag="dotlog"
  startmsg.regex="^[^[:space:]\t]+"
  readTimeout="1"
  ruleset="dotlog")

ruleset(name="dotlog") {
  action(type="mmjsonparse" cookie="")
  action(type="omfwd"
        Template="JsonForwardTemplate"
        tcp_framing="octet-counted"
        action.resumeRetryCount="-1"
        queue.type="linkedlist"
        queue.size="1000"
        queue.discardmark="512"
        queue.timeoutenqueue="0"
        queue.dequeueSlowdown="1024"
        target="central-log-server" port="5550" protocol="tcp")
}

### Environment
- rsyslog version:  8.1901.0
- platform: Ubuntu 18.04

Also, same as in issue https://github.com/rsyslog/rsyslog/issues/3465 deleting the im-state files and subsequent restart causes rsyslog to resume the expected behaviour.

**Comment by davidelang** [comment]
The first thing todoto understand what is going on is to enable the impstats 
module and show the output from it during the timeframe when things are stuck.

David Lang

**Comment by malsumis** [comment]
Ok, so, I can give you the output from impstats from a server that is currently stuck. I cannot, right now, give any output from a longer period, when the issue actually starts - that is on log rotation. For this we will have to wait until tommorow, hopefully things will go wrong on another server, so I can paste more stats as soon as possible. 

Also, Is there any configuration in particular that I should enable on impstats module?

`Wed Feb 13 06:39:38 2019: global: origin=dynstats 
Wed Feb 13 06:39:38 2019: action-0-mmjsonparse: origin=core.action processed=489 failed=0 suspended=0 suspended.duration=0 resumed=0 
Wed Feb 13 06:39:38 2019: action-1-builtin:omfwd: origin=core.action processed=489 failed=0 suspended=0 suspended.duration=0 resumed=0 
Wed Feb 13 06:39:38 2019: action-2-mmjsonparse: origin=core.action processed=0 failed=0 suspended=0 suspended.duration=0 resumed=0 
Wed Feb 13 06:39:38 2019: action-3-builtin:omfwd: origin=core.action processed=0 failed=0 suspended=0 suspended.duration=0 resumed=0 
Wed Feb 13 06:39:38 2019: resource-usage: origin=impstats utime=108000 stime=76000 maxrss=5004 minflt=594 majflt=16 inblock=6504 oublock=32 nvcsw=1850 nivcsw=11 openfiles=63 
Wed Feb 13 06:39:38 2019: action-1-builtin:omfwd queue: origin=core.queue size=0 enqueued=489 full=0 discarded.full=0 discarded.nf=0 maxqsize=11 
Wed Feb 13 06:39:38 2019: action-3-builtin:omfwd queue: origin=core.queue size=0 enqueued=0 full=0 discarded.full=0 discarded.nf=0 maxqsize=0 
Wed Feb 13 06:39:38 2019: main Q: origin=core.queue size=0 enqueued=489 full=0 discarded.full=0 discarded.nf=0 maxqsize=9 
Wed Feb 13 06:44:38 2019: global: origin=dynstats 
Wed Feb 13 06:44:38 2019: action-0-mmjsonparse: origin=core.action processed=998 failed=0 suspended=0 suspended.duration=0 resumed=0 
Wed Feb 13 06:44:38 2019: action-1-builtin:omfwd: origin=core.action processed=998 failed=0 suspended=0 suspended.duration=0 resumed=0 
Wed Feb 13 06:44:38 2019: action-2-mmjsonparse: origin=core.action processed=4 failed=0 suspended=0 suspended.duration=0 resumed=0 
Wed Feb 13 06:44:38 2019: action-3-builtin:omfwd: origin=core.action processed=4 failed=0 suspended=0 suspended.duration=0 resumed=0 
Wed Feb 13 06:44:38 2019: resource-usage: origin=impstats utime=244000 stime=156000 maxrss=5004 minflt=676 majflt=16 inblock=6504 oublock=72 nvcsw=4105 nivcsw=50 openfiles=66 
Wed Feb 13 06:44:38 2019: action-1-builtin:omfwd queue: origin=core.queue size=0 enqueued=998 full=0 discarded.full=0 discarded.nf=0 maxqsize=11 
Wed Feb 13 06:44:38 2019: action-3-builtin:omfwd queue: origin=core.queue size=0 enqueued=4 full=0 discarded.full=0 discarded.nf=0 maxqsize=3 
Wed Feb 13 06:44:38 2019: main Q: origin=core.queue size=0 enqueued=1002 full=0 discarded.full=0 discarded.nf=0 maxqsize=9 
Wed Feb 13 06:49:38 2019: global: origin=dynstats 
Wed Feb 13 06:49:38 2019: action-0-mmjsonparse: origin=core.action processed=1303 failed=0 suspended=0 suspended.duration=0 resumed=0 
Wed Feb 13 06:49:38 2019: action-1-builtin:omfwd: origin=core.action processed=1303 failed=0 suspended=0 suspended.duration=0 resumed=0 
Wed Feb 13 06:49:38 2019: action-2-mmjsonparse: origin=core.action processed=4 failed=0 suspended=0 suspended.duration=0 resumed=0 
Wed Feb 13 06:49:38 2019: action-3-builtin:omfwd: origin=core.action processed=4 failed=0 suspended=0 suspended.duration=0 resumed=0 
Wed Feb 13 06:49:38 2019: resource-usage: origin=impstats utime=320000 stime=220000 maxrss=5004 minflt=678 majflt=16 inblock=6504 oublock=104 nvcsw=5496 nivcsw=57 openfiles=66 
Wed Feb 13 06:49:38 2019: action-1-builtin:omfwd queue: origin=core.queue size=0 enqueued=1303 full=0 discarded.full=0 discarded.nf=0 maxqsize=11 
Wed Feb 13 06:49:38 2019: action-3-builtin:omfwd queue: origin=core.queue size=0 enqueued=4 full=0 discarded.full=0 discarded.nf=0 maxqsize=3 
Wed Feb 13 06:49:38 2019: main Q: origin=core.queue size=0 enqueued=1307 full=0 discarded.full=0 discarded.nf=0 maxqsize=9 
Wed Feb 13 06:54:38 2019: global: origin=dynstats 
Wed Feb 13 06:54:38 2019: action-0-mmjsonparse: origin=core.action processed=1597 failed=0 suspended=0 suspended.duration=0 resumed=0 
Wed Feb 13 06:54:38 2019: action-1-builtin:omfwd: origin=core.action processed=1597 failed=0 suspended=0 suspended.duration=0 resumed=0 
Wed Feb 13 06:54:38 2019: action-2-mmjsonparse: origin=core.action processed=6 failed=0 suspended=0 suspended.duration=0 resumed=0 
Wed Feb 13 06:54:38 2019: action-3-builtin:omfwd: origin=core.action processed=6 failed=0 suspended=0 suspended.duration=0 resumed=0 
Wed Feb 13 06:54:38 2019: resource-usage: origin=impstats utime=400000 stime=272000 maxrss=5004 minflt=680 majflt=16 inblock=6504 oublock=144 nvcsw=6879 nivcsw=84 openfiles=66 
Wed Feb 13 06:54:38 2019: action-1-builtin:omfwd queue: origin=core.queue size=0 enqueued=1597 full=0 discarded.full=0 discarded.nf=0 maxqsize=11 
Wed Feb 13 06:54:38 2019: action-3-builtin:omfwd queue: origin=core.queue size=0 enqueued=6 full=0 discarded.full=0 discarded.nf=0 maxqsize=3 
Wed Feb 13 06:54:38 2019: main Q: origin=core.queue size=0 enqueued=1603 full=0 discarded.full=0 discarded.nf=0 maxqsize=9 
Wed Feb 13 06:59:38 2019: global: origin=dynstats 
Wed Feb 13 06:59:38 2019: action-0-mmjsonparse: origin=core.action processed=1902 failed=0 suspended=0 suspended.duration=0 resumed=0 
Wed Feb 13 06:59:38 2019: action-1-builtin:omfwd: origin=core.action processed=1902 failed=0 suspended=0 suspended.duration=0 resumed=0 
Wed Feb 13 06:59:38 2019: action-2-mmjsonparse: origin=core.action processed=7 failed=0 suspended=0 suspended.duration=0 resumed=0 
Wed Feb 13 06:59:38 2019: action-3-builtin:omfwd: origin=core.action processed=7 failed=0 suspended=0 suspended.duration=0 resumed=0 
Wed Feb 13 06:59:38 2019: resource-usage: origin=impstats utime=476000 stime=328000 maxrss=5004 minflt=684 majflt=16 inblock=6504 oublock=184 nvcsw=8309 nivcsw=92 openfiles=66 
Wed Feb 13 06:59:38 2019: action-1-builtin:omfwd queue: origin=core.queue size=0 enqueued=1902 full=0 discarded.full=0 discarded.nf=0 maxqsize=11 
Wed Feb 13 06:59:38 2019: action-3-builtin:omfwd queue: origin=core.queue size=0 enqueued=7 full=0 discarded.full=0 discarded.nf=0 maxqsize=3 
Wed Feb 13 06:59:38 2019: main Q: origin=core.queue size=0 enqueued=1909 full=0 discarded.full=0 discarded.nf=0 maxqsize=9 
`

**Comment by malsumis** [comment]
One more from a similar server that also got stuck on some files:

`Wed Feb 13 06:39:37 2019: global: origin=dynstats 
Wed Feb 13 06:39:37 2019: action-0-mmjsonparse: origin=core.action processed=361 failed=0 suspended=0 suspended.duration=0 resumed=0 
Wed Feb 13 06:39:37 2019: action-1-builtin:omfwd: origin=core.action processed=361 failed=0 suspended=0 suspended.duration=0 resumed=0 
Wed Feb 13 06:39:37 2019: action-2-mmjsonparse: origin=core.action processed=3 failed=0 suspended=0 suspended.duration=0 resumed=0 
Wed Feb 13 06:39:37 2019: action-3-builtin:omfwd: origin=core.action processed=3 failed=0 suspended=0 suspended.duration=0 resumed=0 
Wed Feb 13 06:39:37 2019: resource-usage: origin=impstats utime=124000 stime=60000 maxrss=5104 minflt=660 majflt=16 inblock=6632 oublock=24 nvcsw=1644 nivcsw=3 openfiles=66 
Wed Feb 13 06:39:37 2019: action-1-builtin:omfwd queue: origin=core.queue size=0 enqueued=361 full=0 discarded.full=0 discarded.nf=0 maxqsize=22 
Wed Feb 13 06:39:37 2019: action-3-builtin:omfwd queue: origin=core.queue size=0 enqueued=3 full=0 discarded.full=0 discarded.nf=0 maxqsize=1 
Wed Feb 13 06:39:37 2019: main Q: origin=core.queue size=0 enqueued=364 full=0 discarded.full=0 discarded.nf=0 maxqsize=16 
Wed Feb 13 06:44:37 2019: global: origin=dynstats 
Wed Feb 13 06:44:37 2019: action-0-mmjsonparse: origin=core.action processed=886 failed=0 suspended=0 suspended.duration=0 resumed=0 
Wed Feb 13 06:44:37 2019: action-1-builtin:omfwd: origin=core.action processed=886 failed=0 suspended=0 suspended.duration=0 resumed=0 
Wed Feb 13 06:44:37 2019: action-2-mmjsonparse: origin=core.action processed=6 failed=0 suspended=0 suspended.duration=0 resumed=0 
Wed Feb 13 06:44:37 2019: action-3-builtin:omfwd: origin=core.action processed=6 failed=0 suspended=0 suspended.duration=0 resumed=0 
Wed Feb 13 06:44:37 2019: resource-usage: origin=impstats utime=212000 stime=184000 maxrss=5104 minflt=686 majflt=16 inblock=6632 oublock=72 nvcsw=3990 nivcsw=40 openfiles=68 
Wed Feb 13 06:44:37 2019: action-1-builtin:omfwd queue: origin=core.queue size=0 enqueued=886 full=0 discarded.full=0 discarded.nf=0 maxqsize=22 
Wed Feb 13 06:44:37 2019: action-3-builtin:omfwd queue: origin=core.queue size=0 enqueued=6 full=0 discarded.full=0 discarded.nf=0 maxqsize=1 
Wed Feb 13 06:44:37 2019: main Q: origin=core.queue size=0 enqueued=892 full=0 discarded.full=0 discarded.nf=0 maxqsize=16 
Wed Feb 13 06:49:37 2019: global: origin=dynstats 
Wed Feb 13 06:49:37 2019: action-0-mmjsonparse: origin=core.action processed=1208 failed=0 suspended=0 suspended.duration=0 resumed=0 
Wed Feb 13 06:49:37 2019: action-1-builtin:omfwd: origin=core.action processed=1208 failed=0 suspended=0 suspended.duration=0 resumed=0 
Wed Feb 13 06:49:37 2019: action-2-mmjsonparse: origin=core.action processed=12 failed=0 suspended=0 suspended.duration=0 resumed=0 
Wed Feb 13 06:49:37 2019: action-3-builtin:omfwd: origin=core.action processed=12 failed=0 suspended=0 suspended.duration=0 resumed=0 
Wed Feb 13 06:49:37 2019: resource-usage: origin=impstats utime=300000 stime=232000 maxrss=5104 minflt=699 majflt=16 inblock=6632 oublock=104 nvcsw=5477 nivcsw=52 openfiles=68 
Wed Feb 13 06:49:37 2019: action-1-builtin:omfwd queue: origin=core.queue size=0 enqueued=1208 full=0 discarded.full=0 discarded.nf=0 maxqsize=22 
Wed Feb 13 06:49:37 2019: action-3-builtin:omfwd queue: origin=core.queue size=0 enqueued=12 full=0 discarded.full=0 discarded.nf=0 maxqsize=3 
Wed Feb 13 06:49:37 2019: main Q: origin=core.queue size=0 enqueued=1220 full=0 discarded.full=0 discarded.nf=0 maxqsize=16 
Wed Feb 13 06:54:37 2019: global: origin=dynstats 
Wed Feb 13 06:54:37 2019: action-0-mmjsonparse: origin=core.action processed=1497 failed=0 suspended=0 suspended.duration=0 resumed=0 
Wed Feb 13 06:54:37 2019: action-1-builtin:omfwd: origin=core.action processed=1497 failed=0 suspended=0 suspended.duration=0 resumed=0 
Wed Feb 13 06:54:37 2019: action-2-mmjsonparse: origin=core.action processed=12 failed=0 suspended=0 suspended.duration=0 resumed=0 
Wed Feb 13 06:54:37 2019: action-3-builtin:omfwd: origin=core.action processed=12 failed=0 suspended=0 suspended.duration=0 resumed=0 
Wed Feb 13 06:54:37 2019: resource-usage: origin=impstats utime=380000 stime=284000 maxrss=5104 minflt=700 majflt=16 inblock=6632 oublock=136 nvcsw=6854 nivcsw=64 openfiles=68 
Wed Feb 13 06:54:37 2019: action-1-builtin:omfwd queue: origin=core.queue size=0 enqueued=1497 full=0 discarded.full=0 discarded.nf=0 maxqsize=22 
Wed Feb 13 06:54:37 2019: action-3-builtin:omfwd queue: origin=core.queue size=0 enqueued=12 full=0 discarded.full=0 discarded.nf=0 maxqsize=3 
Wed Feb 13 06:54:37 2019: main Q: origin=core.queue size=0 enqueued=1509 full=0 discarded.full=0 discarded.nf=0 maxqsize=16 
Wed Feb 13 06:59:37 2019: global: origin=dynstats 
Wed Feb 13 06:59:37 2019: action-0-mmjsonparse: origin=core.action processed=1806 failed=0 suspended=0 suspended.duration=0 resumed=0 
Wed Feb 13 06:59:37 2019: action-1-builtin:omfwd: origin=core.action processed=1806 failed=0 suspended=0 suspended.duration=0 resumed=0 
Wed Feb 13 06:59:37 2019: action-2-mmjsonparse: origin=core.action processed=15 failed=0 suspended=0 suspended.duration=0 resumed=0 
Wed Feb 13 06:59:37 2019: action-3-builtin:omfwd: origin=core.action processed=15 failed=0 suspended=0 suspended.duration=0 resumed=0 
Wed Feb 13 06:59:37 2019: resource-usage: origin=impstats utime=484000 stime=332000 maxrss=5104 minflt=702 majflt=16 inblock=6632 oublock=176 nvcsw=8289 nivcsw=64 openfiles=68 
Wed Feb 13 06:59:37 2019: action-1-builtin:omfwd queue: origin=core.queue size=0 enqueued=1806 full=0 discarded.full=0 discarded.nf=0 maxqsize=22 
Wed Feb 13 06:59:37 2019: action-3-builtin:omfwd queue: origin=core.queue size=0 enqueued=15 full=0 discarded.full=0 discarded.nf=0 maxqsize=3 
Wed Feb 13 06:59:37 2019: main Q: origin=core.queue size=0 enqueued=1821 full=0 discarded.full=0 discarded.nf=0 maxqsize=16 
Wed Feb 13 07:04:38 2019: global: origin=dynstats 
Wed Feb 13 07:04:38 2019: action-0-mmjsonparse: origin=core.action processed=2471 failed=0 suspended=0 suspended.duration=0 resumed=0 
Wed Feb 13 07:04:38 2019: action-1-builtin:omfwd: origin=core.action processed=2471 failed=0 suspended=0 suspended.duration=0 resumed=0 
Wed Feb 13 07:04:38 2019: action-2-mmjsonparse: origin=core.action processed=23 failed=0 suspended=0 suspended.duration=0 resumed=0 
Wed Feb 13 07:04:38 2019: action-3-builtin:omfwd: origin=core.action processed=23 failed=0 suspended=0 suspended.duration=0 resumed=0 
Wed Feb 13 07:04:38 2019: resource-usage: origin=impstats utime=628000 stime=448000 maxrss=5368 minflt=719 majflt=16 inblock=6632 oublock=232 nvcsw=10989 nivcsw=70 openfiles=68 
Wed Feb 13 07:04:38 2019: action-1-builtin:omfwd queue: origin=core.queue size=0 enqueued=2471 full=0 discarded.full=0 discarded.nf=0 maxqsize=22 
Wed Feb 13 07:04:38 2019: action-3-builtin:omfwd queue: origin=core.queue size=0 enqueued=23 full=0 discarded.full=0 discarded.nf=0 maxqsize=3 
Wed Feb 13 07:04:38 2019: main Q: origin=core.queue size=0 enqueued=2494 full=0 discarded.full=0 discarded.nf=0 maxqsize=16`

**Comment by malsumis** [comment]
I'd like to drop in some  (hopefully) relevant debug logs and im-state file contents from a running, stuck rsyslog.

Please notice, that the filename in one of the state-files ( /var/spool/rsyslog/imfile-state\:1585050) is different than in others.

`2788.821549194:imfile.c       : imfile.c: node walk: 0x5580e5a184b0 edges:
2789.172508480:imfile.c       : imfile.c: INOTIFY event: watch was MODIFID
2789.172613762:imfile.c       : imfile.c: in_processEvent process Event 2 for -
2789.172632717:imfile.c       : imfile.c: in_processEvent process Event 2 is_file 1, act->name '/var/log/misc/app/app.log'
2789.172645727:imfile.c       : imfile.c: fs_node_notify_file_update: act->name '/var/log/misc/app/app.log'
2789.172662801:imfile.c       : imfile.c: pollFileReal enter, act 0x7fd8980fa9e0, pStrm 0x7fd8980faae0, name '/var/log/misc/app/app.log'
2789.172675695:imfile.c       : imfile.c: pollFileReal enter, edge 0x5580e5a18440
2789.172687150:imfile.c       : imfile.c: pollFileReal enter, edge->instarr 0x5580e5a184f0
2789.172710047:imfile.c       : strm 0x7fd8980faae0: stream.c: file 49 read 0 bytes
2789.172724194:imfile.c       : strm 0x7fd8980faae0: stream.c: file '/var/log/misc/app/app.log' (49) EOF, rotationCheck 0
2789.172767986:imfile.c       : stream.c: strmHandleEOFMonitor: stream checking for file change on '/var/log/misc/app/app.log', inode 1585050/1585050 size 20959707/1097227
2789.234788544:imfile.c       : imfile.c: INOTIFY event: watch was MODIFID
2789.234837893:imfile.c       : imfile.c: in_processEvent process Event 2 for -
2789.234843284:imfile.c       : imfile.c: in_processEvent process Event 2 is_file 1, act->name '/var/log/misc/app/app.log'
2789.234847234:imfile.c       : imfile.c: fs_node_notify_file_update: act->name '/var/log/misc/app/app.log'
2789.234852443:imfile.c       : imfile.c: pollFileReal enter, act 0x7fd8980fa9e0, pStrm 0x7fd8980faae0, name '/var/log/misc/app/app.log'
2789.234856203:imfile.c       : imfile.c: pollFileReal enter, edge 0x5580e5a18440
2789.234859276:imfile.c       : imfile.c: pollFileReal enter, edge->instarr 0x5580e5a184f0
2789.234874849:imfile.c       : strm 0x7fd8980faae0: stream.c: file 49 read 0 bytes
2789.234893564:imfile.c       : strm 0x7fd8980faae0: stream.c: file '/var/log/misc/app/app.log' (49) EOF, rotationCheck 0
2789.234907547:imfile.c       : stream.c: strmHandleEOFMonitor: stream checking for file change on '/var/log/misc/app/app.log', inode 1585050/1585050 size 20959707/1097425
2790.235958651:imfile.c       : imfile.c: readTimeouts are configured, checking if some apply
`
# cat /var/spool/rsyslog/imfile-state\:1585050
{ "filename": "\/var\/log\/misc\/app\/other-app.log", "prev_was_nl": 1, "curr_offs": 20959707, "strt_offs": 20959707, "prev_line_segment": "2019-01-25 23:59:48,700 log line edited for brevity" }
	
# cat /var/spool/rsyslog/imfile-state\:1585050\:894f1509d0b3e6a3
{ "filename": "\/var\/log\/misc\/app\/app.log", "prev_was_nl": 1, "curr_offs": 20959707, "strt_offs": 20959707, "prev_line_segment": "2019-01-25 23:59:48,700 log line edited for brevity" }

# cat /var/spool/rsyslog/spool/imfile-state\:1585050\:de70511d891b45c8 
{ "filename": "\/var\/log\/misc\/app\/other-app.log", "prev_was_nl": 0, "curr_offs": 20945233, "strt_offs": 20945233 }

**Comment by alorbach** [comment]
rsyslog version:  8.19 is very old and there have been big improvements and partitional rewrites of the whole imfile module since then. 

I recommend to use a newer rsyslog version, you can use our ppa repository from rsyslog.com

**Comment by malsumis** [comment]
I think you misread the version number. I am using 8.1901.0 which is the newest stable version available.

**Comment by davidelang** [comment]
shouldn't the pstats output show the inputs as well?

or am I overlooking the imfile line in these samples?

David Lang

**Comment by alorbach** [comment]
My bad sorry. 
I will try to get a test made for this issue.

**Comment by malsumis** [comment]
@davidelang I don't know, but I let impstats run from early morning here (about 6 hours now), and there are no lines containing imfile in it. Grepping it returns an empty string.

I configured impstats like so:

>module(load="impstats"
       interval="300"
       severity="7"
       log.syslog="off"
       log.file="/var/log/impstats.log")

**Comment by waster** [comment]
We also had  problems with  some recent versions of rsyslog with omelasticsearch and omrelp modules. For some reason rsyslog stops to monitoring some files and no longer processes new lines. And even worse, it just seems to hang and stop writing any logs, even local ones. Older versions like  8.35 do not have such problems.

**Comment by waster** [comment]
And with v8.1901.0 (simple imfile without wildcard) we have some random 'open error: Permission denied' after logrotate and rsyslog stops to process new lines (seems like some race condition).

**Comment by alorbach** [comment]
We nailed the problem down to the inaccuracy of INOTIFY generating events. 
PR #3503 adds a new option to workaround this problem. 
We cannot the code because otherwise tracking of moved files won't work properly which is needed by certain customers. 

So you either can use this "statefilealwaysremove" workaround option or do not use INOTIFY together with logrotated files.

**Comment by waster** [comment]
@alorbach Thanks for the suggested new option and a way to resolve this annoying issue. It seems to me that at least in linux systems logrotate is used everywhere. In general, log rotation is a standard procedure. It turns out that this option should be enabled in most cases when using INOTIFY (which is enabled by default for imfile)? Or it is only logrotate-related problem?

**Comment by alorbach** [comment]
@waster Problem only happens in inotify, switch to polling and it should work.

**Comment by rgerhards** [comment]
> Problem only happens in inotify, switch to polling and it should work.

I don't think so. The code paths are more or less equal (inotify just initiates a polling cycle).

That said, I have looked into more depth into the issue. It looks like the real root cause, contrary to what we initially thought, is improper state handling. I will continue to investigate this.
