### ISSUE TITLE
Solaris is missing strndup

### ISSUE THREAD

**Issue by dago** [rsyslog/rsyslog#347]
Hi,

I am trying to compile rsyslog on Solaris and notice that `strndup` is used although `HAVE_STRNDUP` is not defined. Also I noticed that there is this section in the `ChangeLog`:
```
Version 1.14.2 (RGer), 2007-07-03
...
7500	- integrate patch from Bartosz Kuźma to make rsyslog compile under
7501	  Solaris again (the patch replaced a strndup() call, which is not
7502	  available under Solaris
```
Unfortunately the Git history doesn't seem to go back that far so I can't see what the method was to substitute `strndup`.

Additionally I connected our OpenCSW Buildbot to the gitrepo so that commits automatically try to compile on Solaris: https://buildfarm.opencsw.org/buildbot/waterfall?category=rsyslog

Also I noticed that the `Solaris/`directory contains a license file without anything else among some hints to Blastwave which does not exist any more. OpenCSW is more or less the successor of Blastwave.

Best regards

  -- Dago

**Comment by rgerhards** [comment]
Would you be willing to provide a patch? I guess strndup was manually written. I do not have Solaris sufficiently fast at hand to look into this very soon...

**Comment by rgerhards** [comment]
well, I can at least check strndup usage. Then I can see what happens on your build farm...

**Comment by dago** [comment]
Sure, how are the substitutions normally done? Should I add a replacement `strndup.c`which is pulled in when `HAVE_STRNDUP` is not set? If it helps I can offer an account on our buildfarm: https://www.opencsw.org/extend-it/signup/to-upstream-maintainers/
Additionally, the buildbot setup is there to stay, feel free to add a link to the developer resources.

**Comment by rgerhards** [comment]
Thx! The build farm sounds pretty good,will look into it. For this case, stay tuned, I've seen the occasion where strndup is used. We have some compatibility code in ./compat. It's contributed. I admit there are some other places with compatibility settings as well, but ./compat sounds like the best one. I'll push a patch and then we can see what happens.

**Comment by rgerhards** [comment]
I would appreciate if you could update ./solaris/README as far as the environment is related. I guess you know this muuuuuch better than I ;)

**Comment by dago** [comment]
Sure, currently I am working on an OpenCSW package enabling as much features as possible. I'll then update the ' README` accordingly with my findings.

**Comment by rgerhards** [comment]
excellent, thx. so let's ignore this on this tracker here, I've set the strndup fix commit to close it (when it finally works ;)).

**Comment by dago** [comment]
The builedbot only picks up the `master` branch. If you want to test things before merging I can setup another builder which listens for commits to the `solaris` (or similar) branch.

**Comment by rgerhards** [comment]
master-candidate would be great. This is what my build farm looks for. Just be warned that it is occasinally rebased (master never, of course).

**Comment by dago** [comment]
I added the branch to buildbot, all are available now under project `rsyslog`:
  https://buildfarm.opencsw.org/buildbot/waterfall?category=rsyslog
You can now try to switch contents of `master-candidate`.

**Comment by rgerhards** [comment]
to be released with 8.11.0

**Comment by dago** [comment]
It looks like that `strndup` is not properly linked:
```
  CC       rsyslogd-smtradfwd.o
  CC       rsyslogd-iminternal.o
  CCLD     rsyslogd
Undefined			first referenced
 symbol  			    in file
strndup                             rsyslogd-rsyslogd.o
ld: fatal: symbol referencing errors. No output written to rsyslogd
collect2: error: ld returned 1 exit status
```
https://buildfarm.opencsw.org/buildbot/builders/rsyslog-mc-solaris10-i386/builds/4/steps/shell_2/logs/stdio

**Comment by rgerhards** [comment]
could you check if this is solved by now. There were a couple of different branches fighting with each other and by now everything outstanding is merged.

**Comment by dago** [comment]
The problem seems to be that the compat library is not linked during the final phase for `rsyslogd`:
```
mv -f .deps/rsyslogd-iminternal.Tpo .deps/rsyslogd-iminternal.Po
/bin/bash ../libtool  --tag=CC   --mode=link /opt/csw/bin/gcc -std=gnu99  -I/opt/csw/include -export-dynamic -Wl,--whole-archive,../runtime/.libs/librsyslog.a,--no-whole-archive -L/opt/csw/lib -o rsyslogd rsyslogd-syslogd.o rsyslogd-rsyslogd.o rsyslogd-omshell.o rsyslogd-omusrmsg.o rsyslogd-omfwd.o rsyslogd-omfile.o rsyslogd-ompipe.o rsyslogd-omdiscard.o rsyslogd-pmrfc5424.o rsyslogd-pmrfc3164.o rsyslogd-smtradfile.o rsyslogd-smfile.o rsyslogd-smfwd.o rsyslogd-smtradfwd.o rsyslogd-iminternal.o ../grammar/libgrammar.la ../runtime/librsyslog.la -L/opt/csw/lib -lz   -lpthread ../runtime/librsyslog.la -L/opt/csw/lib -lestr   -L/opt/csw/lib -ljson-c   -lsocket -lnsl -luuid -L/opt/csw/lib -llogging-stdlog   
libtool: link: /opt/csw/bin/gcc -std=gnu99 -I/opt/csw/include -Wl,--whole-archive -Wl,../runtime/.libs/librsyslog.a -Wl,--no-whole-archive -o rsyslogd rsyslogd-syslogd.o rsyslogd-rsyslogd.o rsyslogd-omshell.o rsyslogd-omusrmsg.o rsyslogd-omfwd.o rsyslogd-omfile.o rsyslogd-ompipe.o rsyslogd-omdiscard.o rsyslogd-pmrfc5424.o rsyslogd-pmrfc3164.o rsyslogd-smtradfile.o rsyslogd-smfile.o rsyslogd-smfwd.o rsyslogd-smtradfwd.o rsyslogd-iminternal.o  -L/opt/csw/lib ../grammar/.libs/libgrammar.a -lz -lpthread ../runtime/.libs/librsyslog.a -lrt -lestr -ljson-c -lsocket -lnsl -luuid -llogging-stdlog
Undefined			first referenced
 symbol  			    in file
strndup                             rsyslogd-rsyslogd.o
ld: fatal: symbol referencing errors. No output written to rsyslogd
collect2: error: ld returned 1 exit status
Makefile:672: recipe for target 'rsyslogd' failed
```

**Comment by rgerhards** [comment]
At least for me (on the build farm), it now builds on Solaris 10 and 11. On 9 there is an issue with the build system, but I guess we can ignore that (9 seems acient, isn't it?). I'll merge this soon to master-candidate.

**Comment by rgerhards** [comment]
OK, buildbot also seems to be happy now. So closing again, please re-open if needed.
