### ISSUE TITLE
Rsyslog does not recognize Line Feed

### ISSUE THREAD

**Issue by Skypex** [rsyslog/rsyslog#3484]
Hi,

I currently have some Splunk servers that forward logs to another server running rsyslog.

However, for some reason rsyslog does not recognize the LF and so it writes just the whole TCP packet payload to the file, and not as expected line by line.

The weird thing is that when I look into the tcpdump using Wireshark I can see the within the TCP payload every logline ends with an HEX "0a" and this should be NUL and LF.
Also other messages that are spitted correctly have this sequence in the tcpdump. 

### Environment
- rsyslog 8.38
- Debian Jessie

**Comment by rgerhards** [comment]
`0a` is a single character, which is LF. That is fine. Can you post the output of a sample capture? Please also post config.

**Comment by Skypex** [comment]
Hi @rgerhards,

Thank you for your fast response!

Here is my configuration:
**rsyslog.conf**
```
module(load="imuxsock")
module(load="imklog")
module(load="immark")
module(load="imfile" Mode="polling" PollingInterval="1")
module(load="mmrfc5424addhmac")
module(load="builtin:omfile" dirCreateMode="0755" FileCreateMode="0644")
module(load="imrelp")
module(load="omrelp")
module(load="imudp")
module(load="imtcp" MaxSessions="10000" MaxListeners="550" KeepAlive="on" KeepAlive.Probes="3" KeepAlive.Time="30")   # needs to be done just once
module(load="imptcp")
module(load="mmutf8fix")


##################
#### TEMPLATES ####
##################

template(name="raw-to-json" type="string"
         string="{\"host\":\"%FROMHOST%\",\"EventReceivedTime\":\"%timegenerated:::date-rfc3339%\",\"SourceModuleName\":\"%inputname%\",\"message\":\"%rawmsg:::json%\"}\n"
        )

##################
#### SETTINGS ####
##################

# Specify the maximum supported message size
$MaxMessageSize 64k
$EscapeControlCharactersOnReceive off
#
# Use traditional timestamp format.
# To enable high precision timestamps, comment out the following line.
#
$ActionFileDefaultTemplate RSYSLOG_TraditionalFileFormat
#
# Set the default permissions for all log files.
#
$FileOwner root
$FileGroup adm
$FileCreateMode 0644
$DirCreateMode 0755
$Umask 0022
  
#
# Where to place spool and state files
#
$WorkDirectory /var/spool/rsyslog
  
#
# Include all config files in /etc/rsyslog.d/
#
$IncludeConfig /etc/rsyslog.d/*.conf

###############
#### RULES ####
###############

#
# First some standard log files.  Log by facility.
#
auth,authpriv.*			/var/log/auth.log
*.*;auth,authpriv.none		-/var/log/syslog
#cron.*				/var/log/cron.log
daemon.*			-/var/log/daemon.log
kern.*				-/var/log/kern.log
lpr.*				-/var/log/lpr.log
mail.*				-/var/log/mail.log
user.*				-/var/log/user.log

#
# Logging for the mail system.  Split it up so that
# it is easy to write scripts to parse these files.
#
mail.info			-/var/log/mail.info
mail.warn			-/var/log/mail.warn
mail.err			/var/log/mail.err

#
# Logging for INN news system.
#
news.crit			/var/log/news/news.crit
news.err			/var/log/news/news.err
news.notice			-/var/log/news/news.notice

#
# Some "catch-all" log files.
#
*.=debug;\
	auth,authpriv.none;\
	news.none;mail.none	-/var/log/debug
*.=info;*.=notice;*.=warn;\
	auth,authpriv.none;\
	cron,daemon.none;\
	mail,news.none		-/var/log/messages

#
# Emergencies are sent to everybody logged in.
#
*.emerg				:omusrmsg:*
```

**listener:**
```
input(type="imptcp"
        name="splunk-input"
        port="10000"
        ruleset="splunk-input")

ruleset(name="splunk-input"){
	action(type="omfile"
                File="/var/log/rsyslog/splunk-input/log.log"
                template="raw-to-json")
        stop
}
```

Here is the piece of the tcpdump, on the 2 line you can see `0a` that indicates the Line Feed:
![packet_dump](https://user-images.githubusercontent.com/5459132/53008570-fcc41580-3439-11e9-8c13-68e1e12e7c95.png)

Many thanks!

**Comment by davidelang** [comment]
can you write a lot message with the template RSYSLOG_DebugFormat and post it as 
well?

also, removing the line
$EscapeControlCharactersOnReceive off

may help us understand what's happening.

David Lang

**Comment by rgerhards** [comment]
> Here is the piece of the tcpdump, on the 2 line you can see `0a` that indicates the Line Feed:
> ![packet_dump](https://user-images.githubusercontent.com/5459132/53008570-fcc41580-3439-11e9-8c13-68e1e12e7c95.png)

do you have the decoded form instead of just hex?

**Comment by rgerhards** [comment]
pls also show content from `/var/log/rsyslog/splunk-input/log.log`, best if matching the capture.

so far, I see no problem in the conf (but I may overlook something...).

**Comment by Skypex** [comment]
Hi,

here is a log line produced with the `RSYSLOG_DebugFormat` and commented out `$EscapeControlCharactersOnReceive off` as sugested by @davidelang:

```
Debug line with all properties:
FROMHOST: '10.0.195.14', fromhost-ip: '10.0.195.14', HOSTNAME: '10.0.195.14', PRI: 13,
syslogtag '02-19T12:', programname: '02-19T12', APP-NAME: '02-19T12', PROCID: '-', MSGID: '-',
TIMESTAMP: 'Feb 19 12:02:57', STRUCTURED-DATA: '-',
msg: '02:54.464+01:00 192.168.40.94 CEF:0|Check Point| ...message... src=10.0.0.1 #0122019-02-19T12:02:54.464+01:00 192.168.40.94 CEF:0|Check Point| ...message... src=10.0.0.2 #0122019-02-19T12:02:54.464+01:00 192.168.40.94 CEF:0|Check Point| ...message... src=10.0.0.3 #0122019-02-19T12:02:54.464+01:00 192.168.40.94 CEF:0|Check Point| ...message... '
escaped msg: '02:54.464+01:00 192.168.40.94 CEF:0|Check Point| ...message...  src=10.0.0.1 #0122019-02-19T12:02:54.464+01:00 192.168.40.94 CEF:0|Check Point| ...message... src=10.0.0.2 #0122019-02-19T12:02:54.464+01:00 192.168.40.94 CEF:0|Check Point| ...message... src=10.0.0.3 #0122019-02-19T12:02:54.464+01:00 192.168.40.94 CEF:0|Check Point| ...message... '
inputname: splunk-input 
rawmsg: '02-19T12:02:54.464+01:00 192.168.40.94 CEF:0|Check Point| ...message... src=10.0.0.1 #0122019-02-19T12:02:54.464+01:00 192.168.40.94 CEF:0|Check Point| ...message... src=10.0.0.2 #0122019-02-19T12:02:54.464+01:00 192.168.40.94 CEF:0|Check Point| ...message... src=10.0.0.3 #0122019-02-19T12:02:54.464+01:00 192.168.40.94 CEF:0|Check Point| ...message... '
$!:
$.:
$/:
```
Unfortunately this is firewall data that is somewhat sensitiv so I had to strip a few things. 
However there are no other `#XXX` characters in the message that might interfere the message processing.

Many thanks!

**Comment by rgerhards** [comment]
This looks like the terminator is NOT correct. Don't you have any warnings regarding oversize messages? We probably need a debug log, but not sure if we can proceed if you need to hide so much, as this makes it almost impossible to create a debug log.

**Comment by rgerhards** [comment]
side-note: I would bet that the checkpoint firewall uses invalid framing (NUL instead of LF) - but that's hard to see if we can't get real data. Just a small snippet isn't enough.

**Comment by Skypex** [comment]
Thank you for the response!

May I ask why you guess the framing is wrong? Shouldn't be `#012` be the correct char?

I looked up the logs for rsyslog messages but there is nothing. But I am a bit suspicious why there is absolutely nothing, I need to give it a closer look.

I will also try do get more data but it will take me a bit!

Thank you very much!

**Comment by rgerhards** [comment]
> May I ask why you guess the framing is wrong? Shouldn't be `#012` be the correct char?

I have only a handful of bytes. Not sure if they really correlate to the log you show and if you interpret things correctly. Far too few info. But from experience, rawmsg exactly looks like it looks if the sender uses invalid framing.

**Comment by Skypex** [comment]
Hi,

I managed to get this reproduced in my test VM and there I can activate debug.
This shows me the following:
```
7505.084488547:imptcp.c       : imptcp.c: TCP Message with octet-counter, size 2019.
7505.084515381:imptcp.c       : errmsg.c: Called LogMsg, msg: Framing Error in received TCP message from peer: (hostname) 192.168.56.10, (ip) 192.168.56.10: delimiter is not SP but has ASCII value 45.
7505.084529060:imptcp.c       : operatingstate.c: osf: MSG Framing Error in received TCP message from peer: (hostname) 192.168.56.10, (ip) 192.168.56.10: delimiter is not SP but has ASCII value 45.: signaling new internal message via SIGTTOU: 'Framing Error in received TCP message from peer: (hostname) 192.168.56.10, (ip) 192.168.56.10: delimiter is not SP but has ASCII value 45. [v8.40.0]'
```
So for me this look like you are right @rgerhards.

However, to be honest, I am not sure what to do now...

I tried to fix it with `AddtlFrameDelimiter="45"`, but this does not help.

Is there a way to solve this from rsyslog side or do I need start troubleshooting in the sender side?

**Comment by Skypex** [comment]
After some testing I figured out that the `supportOctetCountedFraming="off"` solved the issue.

However, documentation says that this option should be used with caution, as described here: [SupportOctetCountedFraming](https://www.rsyslog.com/doc/v8-stable/configuration/modules/imtcp.html#supportoctetcountedframing)

**Comment by rgerhards** [comment]
Well, I guess the Frame starts with a number and so it is treated as frame length.

**Comment by davidelang** [comment]
On Tue, 26 Feb 2019, Daniel Pauler wrote:

> After some testing I figured out that the `supportOctetCountedFraming="off"` solved the issue.
>
> However, documentation says that this option should be used with caution, as 
> described here: 
> [SupportOctetCountedFraming](https://www.rsyslog.com/doc/v8-stable/configuration/modules/imtcp.html#supportoctetcountedframing)

turning it off should be safe, unless you are sending messages with it on. 
Enabling Octet framing is the unusual situation.

David Lang
