### ISSUE TITLE
rulesets ignoring stop - listening for different ports per ruleset

### ISSUE THREAD

**Issue by MikaJustas** [rsyslog/rsyslog#3489]
Hi all,

Have the following configured in an external .conf file with name: zportsplitter.conf.

template(name="logs1_logs" type="string" string="/var/log/logs1/%FROMHOST%/%FROMHOST%/%$YEAR%-%$MONTH%-%$DAY%.log")
template(name="logs2_logs" type="string" string="/var/log/logs2/%FROMHOST%/%FROMHOST%/%$YEAR%-%$MONTH%-%$DAY%.log")

ruleset(name="logs1"){
        action(type="omfile" dirCreateMode="0750" FileCreateMode="0750" fileGroup="user1" dirGroup="user1" DynaFile="logs1_logs")
        stop
}
ruleset(name="logs2"){
        action(type="omfile" dirCreateMode="0750" FileCreateMode="0750" fileGroup="user1" dirGroup="user1" DynaFile="logs2_logs")
        stop
}

input(type="imudp" port="11514" ruleset="logs1")
input(type="imudp" port="12514" ruleset="logs2")

input(type="imtcp" port="11514" ruleset="logs1")
input(type="imtcp" port="12514" ruleset="logs2")

### Expected behavior
Message would not reach /var/log/messages independently of facility.severity.

### Actual behavior
Some messages (not all) reach /var/log/messages.

### Environment
- rsyslog version:  8.24.0
- platform: x86_64-suse-linux-gnu

**Comment by rgerhards** [comment]
What I see from the config looks good. The `stop` actually is not even needed here, as message processing automatically stops when the end of ruleset is reached,

So my guess is that the messages you see in `/var/log/messages` originate from some place in the missing parts of the config.

**Comment by MikaJustas** [comment]
I have added stop as a test expecting that what was causing the issue but did not work and just left it there (it didnt have any effect at all). 

The external config import is at the top of the rsyslog.conf:
$ModLoad immark.so
$MarkMessagePeriod      3600
$ModLoad imuxsock.so
$RepeatedMsgReduction   on
$ModLoad imklog.so
$klogConsoleLogLevel    1
$IncludeConfig /etc/rsyslog.d/*.conf
------ standard rsyslog definitions-----------

then, the external config should be evaluated before the standard rsyslog configs, correct? I see no path how messages can reach /var/log/messages.

**Comment by rgerhards** [comment]
> then, the external config should be evaluated before the standard rsyslog configs, correct? I see no path how messages can reach /var/log/messages.

well, first of all we do not know which other external config files exist.

I assume that the messages that reach `/var/log/messages` originate from a different input. Those inputs that are directly bound to the shown rulesets will not reach another file - except if this is a bug in the version you use. I think this is not likely, but I need to say that your version is pretty old, I guess roughly 2+ years. It is 18 releases past the current 8.1901.0 release.

**Comment by MikaJustas** [comment]
the only external config that exists besides the above is actually forwarding, to an external server, so no inputs. Hm, I will try to ask system owner to upgrade it.

**Comment by rgerhards** [comment]
If you would let us know the full config, we could probably provide more clues. But that's up to you.

**Comment by MikaJustas** [comment]
Just got the actual version:  rsyslog-8.24.0-3.19.1. So it does not seem completely clean version, but Suse packaged.

thats actually all the config. 

/etc/rsyslog.conf
The external config import is at the top of the rsyslog.conf:
$ModLoad immark.so
$MarkMessagePeriod 3600
$ModLoad imuxsock.so
$RepeatedMsgReduction on
$ModLoad imklog.so
$klogConsoleLogLevel 1
$IncludeConfig /etc/rsyslog.d/*.conf
------ standard rsyslog definitions, no inputs there-----------

/etc/rsyslog.d/remote.conf
*.info;mail.none;authpriv.none;cron.none                @loggingserver1:514

/etc/rsyslog.d/zportsplitter.conf
module(load="imudp")
module(load="imtcp")

template(name="logs1_logs" type="string" string="/var/log/logs1/%FROMHOST%/%FROMHOST%/%$YEAR%-%$MONTH%-%$DAY%.log")
template(name="logs2_logs" type="string" string="/var/log/logs2/%FROMHOST%/%FROMHOST%/%$YEAR%-%$MONTH%-%$DAY%.log")

ruleset(name="logs1"){
action(type="omfile" dirCreateMode="0750" FileCreateMode="0750" fileGroup="user1" dirGroup="user1" DynaFile="logs1_logs")
}
ruleset(name="logs2"){
action(type="omfile" dirCreateMode="0750" FileCreateMode="0750" fileGroup="user1" dirGroup="user1" DynaFile="logs2_logs")
}

input(type="imudp" port="11514" ruleset="logs1")
input(type="imudp" port="12514" ruleset="logs2")

input(type="imtcp" port="11514" ruleset="logs1")
input(type="imtcp" port="12514" ruleset="logs2")

**Comment by rgerhards** [comment]
If it is the full config, then it is not the active config ;-) Why? It does not even mention `/var/log/messages`, so it is impossible that rsyslog writes to that file with this config.

**Comment by MikaJustas** [comment]
sorry, I have added extra to rsyslog.conf, the definitions which are writing to /var/log/messages and /var/log/localmessages. Both are having messages which should not leave zportsplitter.conf.

**Comment by rgerhards** [comment]
ok, good luck

**Comment by MikaJustas** [comment]
the issue is still open, if anyone has any ideas, let me know. I will try to find a solution and will post here if I come to one.

**Comment by davidelang** [comment]
we cannot solve the problem without the full config (and a better explination 
about what's happening that's not expected)

you may also want to double check for syntax errors (rsyslog -N2) If there is a 
syntax error, all bets are off as to what is actually happening.

David Lang

**Comment by MikaJustas** [comment]
Problem description: multiple ports are listening for incoming traffic and each port has an assign log file to which it writes received messages. Problem - it writes not only to the dedicated file, but also to /var/log/messages. Example, yy.yy.yy.yy sending logs to xx.xx.xx.xx:1154. At xx.xx.xx.xx logs should end up in /var/log/logs1/yy.yy.yy.yy/yy.yy.yy.yy/year-month-day.log ONLY, however some messages are seen in /var/log/messages from the sender. It seems to ignore the rulesets to some extent, as by definition messages should not escape the ruleset assigned to receiving port. 

$ rsyslogd -N2 
rsyslogd: version 8.24.0, config validation run (level 2), master config /etc/rsyslog.conf
rsyslogd: End of config validation run. Bye.

Here is the full configuration:

/etc/rsyslog.conf
```
$ModLoad immark.so
$MarkMessagePeriod      3600
$ModLoad imuxsock.so
$RepeatedMsgReduction   on
$ModLoad imklog.so
$klogConsoleLogLevel    1
$IncludeConfig /run/rsyslog/additional-log-sockets.conf


$IncludeConfig /etc/rsyslog.d/*.conf


# print most important on tty10 and on the xconsole pipe

if      ( \
            /* kernel up to warning except of firewall  */ \
            ($syslogfacility-text == 'kern')      and      \
            ($syslogseverity <= 4 /* warning */ ) and not  \
            ($msg contains 'IN=' and $msg contains 'OUT=') \
        ) or ( \
            /* up to errors except of facility authpriv */ \
            ($syslogseverity <= 3 /* errors  */ ) and not  \
            ($syslogfacility-text == 'authpriv')           \
        ) \
then {
        /dev/tty10
        |/dev/xconsole
}


# Emergency messages to everyone logged on (wall)
*.emerg                                  :omusrmsg:*


# firewall messages into separate file and stop their further processing

if      ($syslogfacility-text == 'kern') and \
        ($msg contains 'IN=' and $msg contains 'OUT=') \
then {
        -/var/log/firewall
        stop
}
if      ($programname == 'acpid' or $syslogtag == '[acpid]:') and \
        ($syslogseverity <= 5 /* notice */) \
then {
        -/var/log/acpid
        stop
}

# NetworkManager into separate file and stop their further processing
if      ($programname == 'NetworkManager') or \
        ($programname startswith 'nm-') \
then {
        -/var/log/NetworkManager
        stop
}

# email-messages
mail.*                                  -/var/log/mail
mail.info                               -/var/log/mail.info
mail.warning                            -/var/log/mail.warn
mail.err                                 /var/log/mail.err


# news-messages
news.crit                               -/var/log/news/news.crit
news.err                                -/var/log/news/news.err
news.notice                             -/var/log/news/news.notice

# Warnings in one file
*.=warning;*.=err                       -/var/log/warn
*.crit                                   /var/log/warn


# the rest in one file
*.*;mail.none;news.none                 -/var/log/messages

# Some foreign boot scripts require local7
local0.*;local1.*                       -/var/log/localmessages
local2.*;local3.*                       -/var/log/localmessages
local4.*;local5.*                       -/var/log/localmessages
local6.*;local7.*                       -/var/log/localmessages
```
/etc/rsyslog.d/remote.conf
`*.info;mail.none;authpriv.none;cron.none @loggingserver1:514`

/etc/rsyslog.d/zportsplitter.conf
```
module(load="imudp")
module(load="imtcp")

template(name="logs1_logs" type="string" string="/var/log/logs1/%FROMHOST%/%FROMHOST%/%$YEAR%-%$MONTH%-%$DAY%.log")
template(name="logs2_logs" type="string" string="/var/log/logs2/%FROMHOST%/%FROMHOST%/%$YEAR%-%$MONTH%-%$DAY%.log")

ruleset(name="logs1"){
action(type="omfile" dirCreateMode="0750" FileCreateMode="0750" fileGroup="user1" dirGroup="user1" DynaFile="logs1_logs")
}
ruleset(name="logs2"){
action(type="omfile" dirCreateMode="0750" FileCreateMode="0750" fileGroup="user1" dirGroup="user1" DynaFile="logs2_logs")
}

input(type="imudp" port="11514" ruleset="logs1")
input(type="imudp" port="12514" ruleset="logs2")

input(type="imtcp" port="11514" ruleset="logs1")
input(type="imtcp" port="12514" ruleset="logs2")
```

**Comment by davidelang** [comment]
what is the contents of  /run/rsyslog/additional-log-sockets.conf?

**Comment by MikaJustas** [comment]
empty

**Comment by rgerhards** [comment]
If that's all, then it is probably indeed an idea to update to rsyslog current (8.1901.0).

**Comment by MikaJustas** [comment]
I will try to import to rsyslog.conf as well, I have suspicion that it has to do also with external .conf sequence.
