### ISSUE TITLE
Rsyslog sometimes fails some tests due to the maximum time expiration

### ISSUE THREAD

**Issue by kulikjak** [rsyslog/rsyslog#3493]
Since the version **8.1901.0** some tests sometimes fail for us on Solaris, namely _imfile-basic-2GB-file.sh_ and _imfile-truncate-2GB-file.sh_. From my digging it seems like expiration of the maximum run time newly set by _$IMDiagAbortTimeout_ variable is the reason for that.

I tried to make the expiration time higher and it solved the issue, however I am not sure if this is the only problem as there can be a good reason why is that variable set to _500_.

I attached log of one of those tests. As mentioned before, this doesn't happen all the time and some build servers are fast enough so that it never occurs there.

[imfile-basic-2GB-file.log](https://github.com/rsyslog/rsyslog/files/2885651/imfile-basic-2GB-file.log)

Thanks

**Comment by rgerhards** [comment]
on what machine do you test this? The value 500 was "heuristically chosen", what actually means it worked fine on our sometimes veeeeeeery slow CI system. We can increase it, but we might then run in other time experations.

**Comment by rgerhards** [comment]
maybe we should override it for that specific test, btw (need to check if it's possible without code change, was not something we thought about).

**Comment by kulikjak** [comment]
It is a Solaris machine with two Xeon CPU E5-2697 v2 @ 2.70GHz so it's not that slow and that is why I was a little bit surprised by those results. Especially when you say that 500 is enough even for your sometimes slow CI server (I wasn't sure how you chose that number).

I will try to truss the test process to see what exactly is it doing - it might be some Solaris related thing or just wrongly set environment.

**Comment by rgerhards** [comment]
can you experimentally increase it and tell how long it needs?

**Comment by kulikjak** [comment]
I ran each failing test five times and got the following results:

**imfile-truncate-2GB-file.sh**
real    7m46.304s
real    7m49.242s
real    13m7.944s
real    13m0.446s
real    14m6.355s

**imfile-basic-2GB-file.sh:**
real    7m38.630s
real    7m44.968s
real    7m40.184s
real    12m11.479s
real    13m4.428s

It looks like for some reason, sometimes they take roughly twice the time to complete. I trussed the process and found nothing unexpected so I am not sure what is going on. As I have said it might be some problem with our build server.

Do you maybe have some advice how to debug why is this the case?

Thanks

**Comment by rgerhards** [comment]
OK, I double-checked. It's one of the extended tests, so we do not run it always. Sry for not noticing earlier.

* I have increased the MAX RUNTIME, but there actually is a useful upper bound: https://github.com/rsyslog/rsyslog/pull/3501
* I will change that test to include a different runtime allowance

Q: 
* do you run the test manually or within the testbench? If the later, are parallel runs enabled?
* do you use network file system? That  could explain the runtime difference, as the test is very i/o intense

**Comment by kulikjak** [comment]
We run the testsuite directly from the tests folder with `make check` command without `-j` flag so no parallel runs enabled (if this is what you meant).

There are no nfs mounted foders except for my home but that should not be a problem and from truss output it looks like it really isn't.

**Comment by rgerhards** [comment]
This should be fixed now by the new time allowance given in #3510. Let me know if you still see issues.

**Comment by kulikjak** [comment]
Just tested it with your new changes and all is fixed now. Thanks

**Comment by rgerhards** [comment]
thx!
