### ISSUE TITLE
install rsyslog by source code using non-root Permission denied

### ISSUE THREAD

**Issue by whxloveyrh** [rsyslog/rsyslog#3498]
install rsyslog by source code on centos7.6 use non-root account.

compile log:
...... 
make[2]: Nothing to be done for `install-data-am'.
make[2]: Leaving directory `/home/aaaa/rsyslog_test/rsyslog-8.39.0/runtime'
make[1]: Leaving directory `/home/aaaa/rsyslog_test/rsyslog-8.39.0/runtime'
Making install in grammar
make[1]: Entering directory `/home/aaaa/rsyslog_test/rsyslog-8.39.0/grammar'
make  install-am
make[2]: Entering directory `/home/aaaa/rsyslog_test/rsyslog-8.39.0/grammar'
make[3]: Entering directory `/home/aaaa/rsyslog_test/rsyslog-8.39.0/grammar'
make[3]: Nothing to be done for `install-exec-am'.
make[3]: Nothing to be done for `install-data-am'.
make[3]: Leaving directory `/home/aaaa/rsyslog_test/rsyslog-8.39.0/grammar'
make[2]: Leaving directory `/home/aaaa/rsyslog_test/rsyslog-8.39.0/grammar'
make[1]: Leaving directory `/home/aaaa/rsyslog_test/rsyslog-8.39.0/grammar'
Making install in .
make[1]: Entering directory `/home/aaaa/rsyslog_test/rsyslog-8.39.0'
make[2]: Entering directory `/home/aaaa/rsyslog_test/rsyslog-8.39.0'
 /usr/bin/mkdir -p '/usr/lib/systemd/system'
 /usr/bin/install -c -m 644 rsyslog.service '/usr/lib/systemd/system'
**/usr/bin/install: cannot remove '/usr/lib/systemd/system/rsyslog.service': Permission denied**
make[2]: *** [install-nodist_systemdsystemunitDATA] Error 1
make[2]: Leaving directory `/home/aaaa/rsyslog_test/rsyslog-8.39.0'
make[1]: *** [install-am] Error 2
make[1]: Leaving directory `/home/aaaa/rsyslog_test/rsyslog-8.39.0'
make: *** [install-recursive] Error 1
[aaaa@instance-01 rsyslog-8.39.0]$

....

**Comment by rgerhards** [comment]
That's expected behavior: if you don't have permission to write to where you want to write to, the system will deny that.
