### ISSUE TITLE
check third-party patches for solaris

### ISSUE THREAD

**Issue by rgerhards** [rsyslog/rsyslog#352]
- https://hg.java.net/hg/solaris-userland~gate/file/feeaeac8a97c/components/rsyslog/patches
- https://github.com/joyent/pkgsrc/tree/trunk/sysutils/rsyslog/patches

Patches are Solaris-only and some for older versions. Need review and cannot be applied as is.

**Comment by h0lzi** [comment]
Oracle "updated" to 8.4.2 just one patch left there: https://hg.java.net/hg/solaris-userland~gate/file/bf30d46ab06e/components/rsyslog/patches

**Comment by rgerhards** [comment]
@alorbach can you please check to integrate this in your work. Please comment and/out close when done

**Comment by mamash** [comment]
Hey guys, the current pkgsrc patches that deal with SunOS and some BSD flavors are here (and not the seldom updated Joyent trunk branch):

https://github.com/NetBSD/pkgsrc/tree/trunk/sysutils/rsyslog/patches

**Comment by rgerhards** [comment]
@mamash Thanks for the link, very useful. We'll see that we evaluate them and get the into rsyslog.

**Comment by rgerhards** [comment]
so far not merged:
* https://github.com/NetBSD/pkgsrc/blob/trunk/sysutils/rsyslog/patches/patch-plugins_imfile_imfile.c
* https://github.com/NetBSD/pkgsrc/blob/trunk/sysutils/rsyslog/patches/patch-plugins_imptcp_imptcp.c
* https://github.com/NetBSD/pkgsrc/blob/trunk/sysutils/rsyslog/patches/patch-runtime_nsd__ptcp.c

**Comment by mamash** [comment]
The SOL_TCP problem (in plugins/imptcp/imptcp.c) is still not fixed by the commit. SOL_TCP doesn't exist on Darwin and SunoS either, and should just be replaced by the portable IPPROTO_TCP everywhere (including Linux).

**Comment by rgerhards** [comment]
> The SOL_TCP problem (in plugins/imptcp/imptcp.c) is still not fixed by the commit. SOL_TCP doesn't exist on Darwin and SunoS either

Mhhhh...  I did a define of SOL_TCP if not existing.  That should work. doesn't it? Also, your Solaris buildbot slaves passed the build. They also run sunstudio compiler, so I thought that should have found that -- shouldn't it?

Anyhow, I'll explore the IPPROTO_TCP path, which indeed sounds better.

**Comment by mamash** [comment]
I apologize, I tested the build and realized that imptcp doesn't get built on SunOS at all, so my point is moot. And your current commit does fix the problem on BSD.

**Comment by rgerhards** [comment]
NP -- your comment helped my to understand I can use IPPROTO_TCP - PR #2260 is underway :-)

**Comment by alorbach** [comment]
If the "dirs" error still was an issue, it should be fixed with this PR  
https://github.com/rsyslog/rsyslog/pull/2227

**Comment by rgerhards** [comment]
yup, that's why I didn't touch it

**Comment by rgerhards** [comment]
@mamash SOL_TPC removed now -- thx!
