### ISSUE TITLE
faild to use rsyslog mrelp with tls

### ISSUE THREAD

**Issue by qqq1484043** [rsyslog/rsyslog#3524]
### Expected behavior
this would start ok~
### Actual behavior
Mar  2 01:42:29 Hawkeye systemd: Starting System Logging Service...
Mar  2 01:42:39 Hawkeye rsyslogd: [origin software="rsyslogd" swVersion="8.24.0-34.el7" x-pid="8551" x-info="http://www.rsyslog.com"] start
Mar  2 01:42:39 Hawkeye rsyslogd: imrelp[514]: error 'Failed to set certificate trust files [gnutls error -64: Error while reading file.]', object  'lstn 514' - input may not work as intended [v8.24.0-34.el7 try http://www.rsyslog.com/e/2353 ]
Mar  2 01:42:39 Hawkeye rsyslogd: imrelp: could not activate relp listener, code 10031 [v8.24.0-34.el7 try http://www.rsyslog.com/e/2291 ]
Mar  2 01:42:39 Hawkeye systemd: Started System Logging Service.
############################################################
and cert dir like this:

[root@yang rsyslog_cert]# pwd
/root/install_history/rsyslog_cert
[root@yang rsyslog_cert]# ls -tlr
总用量 24
-r--------. 1 root root 5823 3月   1 15:31 ca-key.pem
-rw-r--r--. 1 root root 1354 3月   1 15:35 ca.pem
-rwxrwxrwx. 1 root root 5813 3月   1 15:35 key.pem
-rwxrwxrwx. 1 root root 1399 3月   1 15:39 cert.pem
[root@yang rsyslog_cert]# 
#####################################################
### Steps to reproduce the behavior
my conf like this:/etc/rsyslog.d/relp.conf
module(load="imrelp")
input(type="imrelp" port="514"
TLS="on"
TLS.caCert="/root/install_history/rsyslog_cert/ca.pem"
TLS.myCert="/root/install_history/rsyslog_cert/cert.pem"
TLS.myPrivKey="/root/install_history/rsyslog_cert/key.pem"
#tls.authmode="fingerprint"
#tls.authmode="name"
#tls.permittedpeer=["client1.galaxywind.com"]
)
### Environment
- rsyslog version: <rsyslogd 8.24.0-34.el7>
- platform: <Centos7>
- for configuration questions/issues, include rsyslog.conf and included config files

**Comment by rgerhards** [comment]
There is a problem with the certificates, e.g.
* no access permissons
* files do not exist
* file content is not correct for GnuTLS (GnuTLS has very special requirements)

Unfortunately, GnuTLS does not report more precisely what the problem is, so we cannot provide a better clue. Upcoming version 8.1903.0 will permit you to switch to openSSL via rsyslog.conf. OpenSSL is much more tolerant in regard to cert format and also provides much better error messages.

**Comment by qqq1484043** [comment]
> 
> 
> There is a problem with the certificates, e.g.
> 
>     * no access permissons
> 
>     * files do not exist
> 
>     * file content is not correct for GnuTLS (GnuTLS has very special requirements)
> 
> 
> Unfortunately, GnuTLS does not report more precisely what the problem is, so we cannot provide a better clue. Upcoming version 8.1903.0 will permit you to switch to openSSL via rsyslog.conf. OpenSSL is much more tolerant in regard to cert format and also provides much better error messages.

thank you !~
what do you mean at version 8.1903.0?
now I'm sure my cert files is existd and I write 777 for all pem.But it doesn't work~ - -#
################
[root@Hawkeye rsyslog_cert]# ls -tlr
总用量 24
-r--------. 1 root root 5823 3月   1 15:31 ca-key.pem
-rw-r--r--. 1 root root 1354 3月   1 15:35 ca.pem
-rwxrwxrwx. 1 root root 5813 3月   1 15:35 key.pem
-rwxrwxrwx. 1 root root 1399 3月   1 15:39 cert.pem
[root@Hawkeye rsyslog_cert]# pwd
/root/install_history/rsyslog_cert
[root@Hawkeye rsyslog_cert]#

**Comment by rgerhards** [comment]
> what do you mean at version 8.1903.0?

That's the next version. We are currently at 8.1901.0. 

Version 8.24.0 is roughly 2 years old and not supported by the community. It misses many fixes.

> now I'm sure my cert files is existd and I write 777 for all pem.But it doesn't work~ - -

did you follow our guide for certificate creation?

**Comment by qqq1484043** [comment]
> 
> 
> > what do you mean at version 8.1903.0?
> 
> That's the next version. We are currently at 8.1901.0.
> 
> Version 8.24.0 is roughly 2 years old and not supported by the community. It misses many fixes.
> 
> > now I'm sure my cert files is existd and I write 777 for all pem.But it doesn't work~ - -
> 
> did you follow our guide for certificate creation?

Yeah，I really did that. I reinsalll rsyslog to 8.1901.0 now. the error like this.
#############################################################
Mar  4 16:03:24 Hawkeye systemd[1]: Stopping System Logging Service...
Mar  4 16:03:24 Hawkeye rsyslogd[16530]: [origin software="rsyslogd" swVersion="8.1901.0" x-pid="16530" x-info="https://www.rsyslog.com"] exiting on signal 15.
Mar  4 16:03:24 Hawkeye systemd[1]: Stopped System Logging Service.
Mar  4 16:03:24 Hawkeye systemd[1]: Starting System Logging Service...
Mar  4 16:03:35 Hawkeye rsyslogd[16631]: error: certificate file /root/install_history/rsyslog_cert/ca.pem couldn't be accessed: Permission denied  [v8.1901.0 try https://www.rsyslog.com/e/2039 ]
Mar  4 16:03:35 Hawkeye systemd[1]: Started System Logging Service.
Mar  4 16:03:35 Hawkeye rsyslogd[16631]: error: certificate file /root/install_history/rsyslog_cert/cert.pem couldn't be accessed: Permission denied  [v8.1901.0 try https://www.rsyslog.com/e/2039 ]
Mar  4 16:03:35 Hawkeye rsyslogd[16631]: error: certificate file /root/install_history/rsyslog_cert/key.pem couldn't be accessed: Permission denied  [v8.1901.0 try https://www.rsyslog.com/e/2039 ]
Mar  4 16:03:35 Hawkeye rsyslogd[16631]: imrelp[514]: error 'Failed to set certificate trust files [gnutls error -64: Error while reading file.]', object  'lstn 514' - input may not work as intended [v8.1901.0 try https://www.rsyslog.com/e/2353 ]
Mar  4 16:03:35 Hawkeye rsyslogd[16631]: imrelp: could not activate relp listener, code 10031 [v8.1901.0 try https://www.rsyslog.com/e/2291 ]
####################################
the *pem file like this
###################################
[root@Hawkeye rsyslog_cert]# ls -tlr
总用量 24
-r--------. 1 root root 5823 3月   1 15:31 ca-key.pem
-rw-r--r--. 1 root root 1354 3月   1 15:35 ca.pem
-rwxrwxrwx. 1 root root 5813 3月   1 15:35 key.pem
-rwxrwxrwx. 1 root root 1399 3月   1 15:39 cert.pem
[root@Hawkeye rsyslog_cert]# pwd
/root/install_history/rsyslog_cert
[root@Hawkeye rsyslog_cert]# 
#########################
it says like Permission denied. I don't know why. please help me

**Comment by rgerhards** [comment]
SELinux?

**Comment by qqq1484043** [comment]
> 
> 
> SELinux?

you are right.very thanks.^_^
#######################
Mar  4 16:22:17 Hawkeye dbus-daemon[4302]: dbus[4302]: avc:  received setenforce notice (enforcing=0)
Mar  4 16:22:17 Hawkeye dbus[4302]: avc:  received setenforce notice (enforcing=0)
Mar  4 16:23:58 Hawkeye systemd[1]: Stopping System Logging Service...
Mar  4 16:23:58 Hawkeye rsyslogd[16631]: [origin software="rsyslogd" swVersion="8.1901.0" x-pid="16631" x-info="https://www.rsyslog.com"] exiting on signal 15.
Mar  4 16:23:58 Hawkeye systemd[1]: Stopped System Logging Service.
Mar  4 16:23:58 Hawkeye systemd[1]: Starting System Logging Service...
Mar  4 16:24:08 Hawkeye rsyslogd[17703]: [origin software="rsyslogd" swVersion="8.1901.0" x-pid="17703" x-info="https://www.rsyslog.com"] start
Mar  4 16:24:08 Hawkeye systemd[1]: Started System Logging Service.
#########################

**Comment by rgerhards** [comment]
glad it helped! :-)
