### ISSUE TITLE
 omrelp: could not connect to remote server, librelp error 10014 [v8.1901.0 try https://www.rsyslog.com/e/2291 ]

### ISSUE THREAD

**Issue by qqq1484043** [rsyslog/rsyslog#3530]
### Expected behavior
my client can connect server through relp with tls.
### Actual behavior
Mar  5 01:31:18 galaxywind rsyslogd:  [origin software="rsyslogd" swVersion="8.1901.0" x-pid="113065" x-info="https://www.rsyslog.com"] start
Mar  5 01:31:18 galaxywind rsyslogd: omrelp[10.2.18.21:514]: error 'error opening connection to remote peer', object  'conn to srvr 10.2.18.21:514' - action may not work as intended [v8.1901.0 try https://www.rsyslog.com/e/2353 ]
Mar  5 01:31:18 galaxywind rsyslogd: omrelp: could not connect to remote server, librelp error 10014 [v8.1901.0 try https://www.rsyslog.com/e/2291 ]
Mar  5 01:31:18 galaxywind rsyslogd: action 'action-0-omrelp' suspended (module 'omrelp'), retry 0. There should be messages before this one giving the reason for suspension. [v8.1901.0 try https://www.rsyslog.com/e/2007 ]
Mar  5 01:31:18 galaxywind rsyslogd: omrelp[10.2.18.21:514]: error 'error opening connection to remote peer', object  'conn to srvr 10.2.18.21:514' - action may not work as intended [v8.1901.0 try https://www.rsyslog.com/e/2353 ]
Mar  5 01:31:18 galaxywind rsyslogd: action 'action-0-omrelp' suspended (module 'omrelp'), next retry is Tue Mar  5 01:31:48 2019, retry nbr 0. There should be messages before this one giving the reason for suspension. [v8.1901.0 try https://www.rsyslog.com/e/2007 ]
### Environment
- rsyslog version: <8.1901.0>
- platform: <Centos7>
- for configuration questions/issues, include rsyslog.conf and included config files
my conf file is /etc/rsyslog.d/relp.conf   like this:
[root@Hawkeye rsyslog.d]# cat relp.conf 
module(load="omrelp")
action(type="omrelp" target="10.2.18.21" port="514" tls="on"
tls.caCert="/home/client1/ca.pem"
tls.myCert="/home/client1/client1-cert.pem"
tls.myPrivKey="/home/client1/client1-key.pem"
tls.authmode="name"
tls.permittedpeer=["server.qwer.com"]
)

**Comment by rgerhards** [comment]
firewall?

**Comment by qqq1484043** [comment]
> 
> 
> firewall?

you are right. but now ...
server print:
############################################
Mar  5 09:14:49 Hawkeye rsyslogd[20672]: imrelp[514]: error 'TLS handshake failed [gnutls error -54: Error in the pull function.]', object  'lstn 514: conn to clt 10.2.18.20/10.2.18.20' - input may not work as intended [v8.1901.0 try https://www.rsyslog.com/e/2353 ]
Mar  5 09:14:49 Hawkeye rsyslogd[20672]: imrelp[514]: error 'TLS record write failed [gnutls error -10: The specified session has been invalidated for some reason.]', object  'lstn 514: conn to clt 10.2.18.20/10.2.18.20' - input may not work as intended [v8.1901.0 try https://www.rsyslog.com/e/2353 ]

**Comment by rgerhards** [comment]
Is the other side NOT using TLS?

**Comment by qqq1484043** [comment]
> 
> 
> Is the other side NOT using TLS?
you mean the client? TLS is opened.
the client conf like this :
#########################################
module(load="omrelp")
action(type="omrelp" target="10.2.18.21" port="514" tls="on"
tls.caCert="/home/ca.pem"
tls.myCert="/home/cert.pem"
tls.myPrivKey="/home/key.pem"
tls.authmode="name"
tls.permittedpeer=["server.galaxywind.com"]
)

**Comment by rgerhards** [comment]
to be sure: use wireshark and check which packets are sent / received

**Comment by qqq1484043** [comment]
> 
> 
> to be sure: use wireshark and check which packets are sent / received
I captured the packets at the server port.

![tls](https://user-images.githubusercontent.com/48122017/53798695-bad7bb00-3f73-11e9-8125-0c37e893d595.jpeg)

**Comment by rgerhards** [comment]
mhhh @davidelang do you have an idea? I think it is environment- induced. GnuTLS says "The specified session has been invalidated for some reason". Unfortunately we do not get more info from GnuTLS. 

@qqq1484043 maybe you should wait for 8.1903.0 packages today and re-try with openssl. They have much better error messages in general.

**Comment by qqq1484043** [comment]
> 
> 
> mhhh @davidelang do you have an idea? I think it is environment- induced. GnuTLS says "The specified session has been invalidated for some reason". Unfortunately we do not get more info from GnuTLS.
> 
> @qqq1484043 maybe you should wait for 8.1903.0 packages today and re-try with openssl. They have much better error messages in general.

thank you~I will try 8.1903.0 today.

**Comment by qqq1484043** [comment]
I'm so boring.I I updated rsyslog to  8.1903.0. and I update my librelp to 1.4.0. what should I do next?
how do I re-try this with openssl? I' m so sorry make too much trouble with you.- -#

**Comment by qqq1484043** [comment]
> 
> 
> I'm so boring.I I updated rsyslog to 8.1903.0. and I update my librelp to 1.4.0. what should I do next?
> how do I re-try this with openssl? I' m so sorry make too much trouble with you.- -#

I'm so boring.I I updated rsyslog to 8.1903.0. and I update my librelp to 1.4.0. what should I do next?
how do I re-try this with openssl? I' m so sorry make too much trouble with you.- -#

**Comment by qqq1484043** [comment]
> 
> 
> mhhh @davidelang do you have an idea? I think it is environment- induced. GnuTLS says "The specified session has been invalidated for some reason". Unfortunately we do not get more info from GnuTLS.
> 
> @qqq1484043 maybe you should wait for 8.1903.0 packages today and re-try with openssl. They have much better error messages in general.

I'm so boring.I I updated rsyslog to 8.1903.0. and I update my librelp to 1.4.0. what should I do next?
how do I re-try this with openssl? I' m so sorry make too much trouble with you.- -#

**Comment by rgerhards** [comment]
no problem! add `tls.tlslib="openssl"` to the `module(...)` config object for relp.

**Comment by qqq1484043** [comment]
> tls.tlslib="openssl"

that's a error with tls.tlslib !~~
####################
Mar  7 01:20:07 localhost systemd: Stopping System Logging Service...
Mar  7 01:20:07 localhost rsyslogd: [origin software="rsyslogd" swVersion="8.1903.0" x-pid="38448" x-info="https://www.rsyslog.com"] exiting on signal 15.
Mar  7 01:20:07 localhost systemd: Starting System Logging Service...
Mar  7 01:20:07 localhost rsyslogd: error during parsing file /etc/rsyslog.d/relp.conf, on or before line 34: parameter 'tls.tlslib' not known -- typo in config file? [v8.1903.0 try https://www.rsyslog.com/e/2207 ]
Mar  7 01:20:07 localhost rsyslogd: [origin software="rsyslogd" swVersion="8.1903.0" x-pid="38598" x-info="https://www.rsyslog.com"] start
Mar  7 01:20:07 localhost systemd: Started System Logging Service.
Mar  7 01:20:07 localhost rsyslogd: imjournal: journal reloaded... [v8.1903.0 try https://www.rsyslog.com/e/0 ]
Mar  7 01:20:07 localhost systemd[1]: Stopping System Logging Service...
Mar  7 01:20:07 localhost rsyslogd[38448]: [origin software="rsyslogd" swVersion="8.1903.0" x-pid="38448" x-info="https://www.rsyslog.com"] exiting on signal 15.
Mar  7 01:20:07 localhost systemd[1]: Starting System Logging Service...
Mar  7 01:20:07 localhost rsyslogd[38598]: error during parsing file /etc/rsyslog.d/relp.conf, on or before line 34: parameter 'tls.tlslib' not known -- typo in config file? [v8.1903.0 try https://www.rsyslog.com/e/2207 ]
Mar  7 01:20:07 localhost rsyslogd[38598]: [origin software="rsyslogd" swVersion="8.1903.0" x-pid="38598" x-info="https://www.rsyslog.com"] start
Mar  7 01:20:07 localhost systemd[1]: Started System Logging Service.
Mar  7 01:20:07 localhost rsyslogd[38598]: imjournal: journal reloaded... [v8.1903.0 try https://www.rsyslog.com/e/0 ]
##################################
my env is 
[root@localhost etc]# rpm -qa | grep rsyslog
rsyslog-relp-8.1903.0-1.el7.x86_64
rsyslog-8.1903.0-1.el7.x86_64
rsyslog-openssl-8.1903.0-1.el7.x86_64
rsyslog-gnutls-8.1903.0-1.el7.x86_64
rsyslog-crypto-8.1903.0-1.el7.x86_64
[root@localhost etc]# rpm -qa | grep librelp
librelp-1.4.0-1.el7.x86_64
[root@localhost etc]#  
#######################
my relp.conf is 

module(load="imrelp")
input(type="imrelp" port="20514"
TLS="on"
TLS.caCert="/home/ca.pem"
TLS.myCert="/home/cert.pem"
TLS.myPrivKey="/home/key.pem"
tls.tlslib="openssl"
tls.authmode="name"
tls.permittedpeer=["*.example.net"]
)
ruleset (name="relp") { action(type="omfile" file="/var/log/relp_log") }

**Comment by davidelang** [comment]
unfortunantly I don't have a good handle on TLS related errors.

**Comment by rgerhards** [comment]
As I wrote, you need to add that setting to `module()`, not `input()`:
```
module(load="imrelp" tls.tlslib="openssl")

input(type="imrelp" port="20514"
TLS="on"
TLS.caCert="/home/ca.pem"
TLS.myCert="/home/cert.pem"
TLS.myPrivKey="/home/key.pem"
tls.authmode="name"
tls.permittedpeer=["*.example.net"]
)
```

**Comment by livelace** [comment]
**2netwalkers**. I have spent about an hour to realise that error:

rsyslogd: omrelp: could not connect to remote server, librelp error 10015 [v8.1908.0 try https://www.rsyslog.com/e/2291 ]

arises from SELinux. 

The whole hour I was checking routes, firewalls, syslog versions etc.
