### ISSUE TITLE
no omhttp package found in binary repositories

### ISSUE THREAD

**Issue by darakian** [rsyslog/rsyslog#3534]
### Expected behavior
Omhttp fails to parse prior working actions

### Actual behavior
Parse error
```
root@machine rsyslog.d]# rsyslogd -N1
rsyslogd: version 8.1903.0, config validation run (level 1), master config /etc/rsyslog.conf
rsyslogd: could not load module 'omhttp', errors: trying to load module /lib64/rsyslog/omhttp.so: /lib64/rsyslog/omhttp.so: cannot open shared object file: No such file or directory [v8.1903.0 try https://www.rsyslog.com/e/2066 ]
rsyslogd: module name 'omhttp' is unknown [v8.1903.0 try https://www.rsyslog.com/e/2209 ]
rsyslogd: error during parsing file /etc/rsyslog.d/my.conf, on or before line 15: errors occured in file '/etc/rsyslog.d/my.conf' around line 15 [v8.1903.0 try https://www.rsyslog.com/e/2207 ]
```

### Steps to reproduce the behavior
Use the first example action here
https://www.rsyslog.com/doc/v8-stable/configuration/modules/omhttp.html

### Environment
- rsyslog version:8.1903.0
- Amazon Linux 1 (More or less centos 6)
example action line
`action(type="omhttp" server="my.domain.com" serverport="8080" restpath="events" dynRestPath="off" usehttps="off" template="jsonRfc5424Template")`
Packages installed via `http://rpms.adiscon.com/v8-stable/epel-6/x86_64`

Failure to parse also occurs with the following action 
```
action(
    type="omhttp"
    server="127.0.0.1"
    serverport="8080"
    restpath="events"
    template="tpl1"
    action.resumeRetryCount="3"
)
```
Taken from https://www.rsyslog.com/doc/v8-stable/configuration/modules/omhttp.html
The failure always occurs on the last line ex. `)` in the tpl1 example above.

**Comment by rgerhards** [comment]
You need to install the module:
```
rsyslogd: could not load module 'omhttp', errors: trying to load module /lib64/rsyslog/omhttp.so: /lib64/rsyslog/omhttp.so: cannot open shared object file: No such file or directory
```

**Comment by darakian** [comment]
So I do. My bad on that. Looking at http://rpms.adiscon.com/v8-stable/epel-6/x86_64 I don't see an rpm for omhttp. Do I still need to make the module myself?

**Comment by jgerhards** [comment]
You can either build it yourself or use the repositories at

https://software.opensuse.org//download.html?project=home%3Argerhards&package=rsyslog

note: For some platforms, there is no omhttp package because of missing or too old dependencies.

**Comment by darakian** [comment]
@jgerhards I don't see omhttp available for centos6 via your link. Is this due to old dependencies?

**Comment by jgerhards** [comment]
unfortunately, it is not available for CentOs6 due to the dependencies. However, it looks like the backwards compatibility broke with https://github.com/rsyslog/rsyslog/pull/3423. Could you try to build the module yourself and tell me, if it works or if it is broken for you as well?

**Comment by darakian** [comment]
Build is working for me, but I think I'm bundling omhttp into the rsyslog binary. Build steps are
```
1. clone
2. ./configure --enable-omhttp
3. make
4. run /usr/sbin/rsyslog
```
I had to install `libfastjson4-devel`, `libfastjson4`, and `libestr-devel` from rpms at 
http://rpms.adiscon.com/v8-stable/epel-6/x86_64 as well

**Comment by jgerhards** [comment]
that's interesting. Maybe @rgerhards can have a closer look inside CI.

**Comment by mbonsack** [comment]
Not there for CentOS 7 either?  Don't see it here:
http://rpms.adiscon.com/v8-stable/epel-7/x86_64/RPMS/
So, for what distros is there a pre-compiled omhttp module?

**Comment by mymtw** [comment]
same error for ubuntu
```
Mar 24 00:39:06 mtw rsyslogd[16710]: could not load module 'omhttp', errors: trying to load module /usr/lib/rsyslog/omhttp.so: /usr/lib/rsyslog/omhttp.so: cannot open shared object file: No such file or directory [v8.…syslog.com/e/2066 ]
Mar 24 00:39:06 mtw rsyslogd[16710]: module name 'omhttp' is unknown [v8.1903.0 try https://www.rsyslog.com/e/2209 ]
```
I have installed rsyslog via apt-get wtf?!

**Comment by davidelang** [comment]
On Sat, 23 Mar 2019, Igor Komar wrote:

> same error for ubuntu
> ```
> Mar 24 00:39:06 mtw rsyslogd[16710]: could not load module 'omhttp', errors: trying to load module /usr/lib/rsyslog/omhttp.so: /usr/lib/rsyslog/omhttp.so: cannot open shared object file: No such file or directory [v8.…syslog.com/e/2066 ]
> Mar 24 00:39:06 mtw rsyslogd[16710]: module name 'omhttp' is unknown [v8.1903.0 try https://www.rsyslog.com/e/2209 ]
> ```
> I have installed rsyslog via apt-get wtf?!

what repo are you using? I believe you need to use the Adiscon (or PPA) repo, 
not the stock Ubuntu repo.

David Lang

**Comment by mymtw** [comment]
@davidelang thx ofc, 
repo `sudo add-apt-repository ppa:adiscon/v8-stable`
as in documentation
I do not know repo `Adiscon`

**Comment by mymtw** [comment]
https://github.com/rsyslog/rsyslog-pkg-ubuntu/issues/89

**Comment by davidelang** [comment]
and if you do apt search rsyslog what do you get?
a lot of modules require separate packages to be installed.

David Lang

**Comment by mymtw** [comment]
@davidelang 
```
gosa-plugin-rsyslog/bionic,bionic 2.7.4+reloaded3-3 all
  rsyslog plugin for GOsa²

librelp-dev/bionic 1.4.0-0adiscon1bionic1 amd64
  Reliable Event Logging Protocol (RELP) library - development files

librelp0/bionic 1.4.0-0adiscon1bionic1 amd64
  Reliable Event Logging Protocol (RELP) library

puppet-module-saz-rsyslog/bionic,bionic 2.2.1-1 all
  Puppet module for rsyslog

resource-agents/bionic 1:4.1.0~rc1-1ubuntu1 amd64
  Cluster Resource Agents

rsyslog/bionic,now 8.1903.0-0adiscon1bionic1 amd64 [installed]
  a rocket-fast system for log processing

rsyslog-czmq/bionic 8.32.0-1ubuntu4 amd64
  ZeroMQ protocol support for rsyslog via CZMQ

rsyslog-doc/bionic,bionic 8.1903.0-0adiscon1bionic1 all
  documentation for rsyslog

rsyslog-elasticsearch/bionic 8.1903.0-0adiscon1bionic1 amd64
  Elasticsearch output support for rsyslog

rsyslog-fmhash/bionic 8.1903.0-0adiscon1bionic1 amd64
  Function module for rainerscript function hash.

rsyslog-fmhttp/bionic 8.1903.0-0adiscon1bionic1 amd64
  Function module for rainerscript function http_request.

rsyslog-gnutls/bionic 8.1903.0-0adiscon1bionic1 amd64
  TLS protocol support for rsyslog

rsyslog-gssapi/bionic 8.32.0-1ubuntu4 amd64
  GSSAPI authentication and encryption support for rsyslog

rsyslog-hiredis/bionic 8.32.0-1ubuntu4 amd64
  Redis output plugin for rsyslog

rsyslog-imptcp/bionic 8.1903.0-0adiscon1bionic1 amd64
  High-performance, threaded TCP input module for rsyslog

rsyslog-kafka/bionic 8.1903.0-0adiscon1bionic1 amd64
  This module implements an Apache Kafka producer, permitting rsyslog to write data to Kafka.

rsyslog-mmanon/bionic 8.1903.0-0adiscon1bionic1 amd64
  IP Address Anonimization Module (mmanon).

rsyslog-mmfields/bionic 8.1903.0-0adiscon1bionic1 amd64
  Parse all fields of the message into structured data inside the JSON tree.

rsyslog-mmjsonparse/bionic 8.1903.0-0adiscon1bionic1 amd64
  Parsing/handling of CEE/Lumberjack JSON messages in rsyslog

rsyslog-mmkubernetes/bionic 8.1903.0-0adiscon1bionic1 amd64
  Message modification module to add Kubernetes metadata to a messages.

rsyslog-mmnormalize/bionic 8.1903.0-0adiscon1bionic1 amd64
  The rsyslog-mmnormalize package provides log normalization

rsyslog-mmrm1stspace/bionic 8.1903.0-0adiscon1bionic1 amd64
  The mmrm1stspace module permits to strip the leading space from

rsyslog-mmutf8fix/bionic 8.1903.0-0adiscon1bionic1 amd64
  The mmutf8fix module permits to fix invalid UTF-8 sequences. Most often, such invalid sequences result from syslog sources sending in non-UTF character sets, e.g. ISO 8859. As syslog does not have a way to convey the character set information, these sequences are not properly handled.

rsyslog-mongodb/bionic 8.1903.0-0adiscon1bionic1 amd64
  MongoDB output plugin for rsyslog

rsyslog-mysql/bionic 8.1903.0-0adiscon1bionic1 amd64
  MySQL output plugin for rsyslog

rsyslog-omstdout/bionic 8.1903.0-0adiscon1bionic1 amd64
  This module provides omstdout functionality.

rsyslog-openssl/bionic 8.1903.0-0adiscon1bionic1 amd64
  TLS protocol support for rsyslog

rsyslog-pgsql/bionic 8.1903.0-0adiscon1bionic1 amd64
  PostgreSQL output plugin for rsyslog

rsyslog-pmnormalize/bionic 8.1903.0-0adiscon1bionic1 amd64
  The rsyslog-pmnormalize package provides a parser module based

rsyslog-redis/bionic 8.1903.0-0adiscon1bionic1 amd64
  This module implements Redis support, permitting ryslog to write to redis.

rsyslog-relp/bionic 8.1903.0-0adiscon1bionic1 amd64
  RELP protocol support for rsyslog

rsyslog-utils/bionic 8.1903.0-0adiscon1bionic1 amd64
  rsyslog utilities

uwsgi-core/bionic-updates,bionic-security 2.0.15-10.2ubuntu2.1 amd64
  fast, self-healing application container server (core)
```

**Comment by mbonsack** [comment]
Again, it looks like none of the repos include pre-built modules for omhttp() -- neither ubuntu nor CentOS/RHEL.

**Comment by jgerhards** [comment]
As i wrote, you need to use the OBS repositories. More info at:
http://jan.gerhards.net/2019/03/rsyslog-packages-on-obs.html

Direct link to repository:

https://software.opensuse.org//download.html?project=home%3Argerhards&package=rsyslog

**Comment by mymtw** [comment]
Still do not understand how to fix strange errors about not installed omhttp package for ubuntu

**Comment by mbonsack** [comment]
Those links do _not_ show show the OP how to get a binary package that includes the omhttp output module.  In fact, when searching this repo, it shows that omhttp_fs_ is available, but not omhttp.  Can you outline the _exact_ steps needed to do download an installation of rsyslog containing this output module?

**Comment by rgerhards** [comment]
using a docker container and following the instructions from posted link:
```
    1  apt update
    2  apt install wget gnupg sudo
    3  wget -nv https://download.opensuse.org/repositories/home:rgerhards/xUbuntu_16.04/Release.key -O Release.key
    4  sudo apt-key add - < Release.key
    5  sudo sh -c "echo 'deb http://download.opensuse.org/repositories/home:/rgerhards/xUbuntu_16.04/ /' > /etc/apt/sources.list.d/home:rgerhards.list"
    6  sudo apt-get update
    7  sudo apt-get install rsyslog
    8  sudo apt-get install rsyslog-omhttp
    9  history
```
This was on Ubuntu 16.04 (`docker run ubuntu:16.04`).

**Comment by mymtw** [comment]
@rgerhards 
mtw@mtw:/etc/rsyslog.d$ sudo apt-get install rsyslog-omhttp
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package rsyslog-omhttp

**Comment by rgerhards** [comment]
platform? did you all steps I did - most importantly add the **right** repository?

**Comment by mymtw** [comment]
18.04 ...

**Comment by mymtw** [comment]
sorry, it installed, but, I still get same error:
```
Mar 25 11:25:06 mtw rsyslog[9081]: rsyslogd: could not load module 'omhttp', errors: trying to load module /usr/lib/rsyslog/omhttp.so: /usr/lib/rsyslog/omhttp.so: cannot open shared object file: No such file or directory [v8.1903.0 try h
Mar 25 11:25:06 mtw rsyslog[9081]: rsyslogd: module name 'omhttp' is unknown [v8.1903.0 try https://www.rsyslog.com/e/2209 ]
```

**Comment by rgerhards** [comment]
aha! This is interesting. Let's check what can be the cause.

**Comment by rgerhards** [comment]
pls do: `sudo dpkg -l|grep rsyslog`

**Comment by mymtw** [comment]
```
mtw@mtw:/etc/rsyslog.d$ sudo dpkg -l|grep rsyslog
ii  rsyslog                                   8.1903.0-1                                  amd64        a rocket-fast system for log processing
ii  rsyslog-gnutls                            8.1903.0-1                                  amd64        TLS protocol support for rsyslog
ii  rsyslog-omhttp                            8.1903.0-1                                  amd64        omhttp module (contributed).
```

**Comment by rgerhards** [comment]
not sure if that is the best way to list install sources, but pls do `grep "deb " /etc/apt/sources.list /etc/apt/sources.list.d/*`

**Comment by mymtw** [comment]
`/etc/apt/sources.list.d/home:rgerhards.list:deb http://download.opensuse.org/repositories/home:/rgerhards/xUbuntu_16.04/ /
`

**Comment by mymtw** [comment]
maybe smth wrong with my config
```
module(load="omhttp")

template(name="tpl_echo" type="string" string="%msg%")
ruleset(name="rs_retry_forever") {
    action(
        type="omhttp"
        server="https://api.telegram.org"
        serverport="443"
        restpath="bot731686324:AAElGaB6MLCil7o0cYX6Sjfg1hK5ngma8vs/sendMessage"
        template="tpl_echo"

        batch="on"
        batch.format="jsonarray"
        batch.maxsize="10"

        retry="off"
        retry.ruleset="rs_retry_forever"
        errorfile="/tmp/mopedgoa.log"
    )
}

template(name="tpl1" type="string" string="{\"type\":\"syslog\", \"host\":\"%HOSTNAME%\"}")
action(
    type="omhttp"
    server="https://api.telegram.org"
    serverport="443"
    restpath="botsometoken/sendMessage"
    template="tpl1"

    batch="on"
    batch.format="jsonarray"
    batch.maxsize="10"

    retry="on"
    retry.ruleset="rs_retry_forever"
)
```

**Comment by rgerhards** [comment]
interesting use case! I wish we would know more about such use cases so that they could be documented...

On the problem: I think it's packaging related. Unfortunately, this is the first report, so we need to investigate (alongside with the other activities).

**Comment by mbonsack** [comment]
I have two questions:

1. What does the package listing (still) show "contributed" for omhttp?  I thought it was released to master:
rsyslog-omhttp                            8.1903.0-1                                  amd64        omhttp module (contributed).
2. Why, when you search here: 
https://software.opensuse.org//download.html?project=home%3Argerhards&package=rsyslog
does omhttpfs show up, but *not* omhttp?

**Comment by rgerhards** [comment]
> * What does the package listing (still) show "contributed" for omhttp?  I thought it was released to master:
>   rsyslog-omhttp                            8.1903.0-1                                  amd64        omhttp module (contributed).

because there is nobody on the rsyslog core team who maintains it. for contributed modules, we can not guarantee they are maintained.

> * Why, when you search here:
>   https://software.opensuse.org//download.html?project=home%3Argerhards&package=rsyslog
>   does omhttpfs show up, but _not_ omhttp?

I don't know - as I said a myriad of times, we are not packagers. And nobody wants to help with packaging. Maybe we should stop providing binary packages, it gets more any more annoying.

> * Does this affect CentOS/RHEL as well?  That is the distro I am interested in as well as Ubuntu.

It would help if you folllowed the posted links and actually read them. Does it say CentOS or not?

https://software.opensuse.org//download.html?project=home%3Argerhards&package=rsyslog

**Comment by mbonsack** [comment]
OK, at least in my case I believe I have it sorted; I'll also respond to rgherhards comments above:
1.  I thought when a module transitioned to "master", that the core team _did_ maintain it.  I apologize if this is not the case.  
2.  I am a simple administrator who simply wants to use what I thought was a new capability in the core product.  Packaging in OSS is a challenging thing; I understand your frustration.
3.  I did follow the procedure, but thought it might be a bigger issue.  In my case, omhttp did indeed get installed properly.  _However_ (and to your point above), I want to use _both_ http and kafka as output modules.  Alas, Adiscon has the latest Kafka modules, but *not* omhttp.  The Opensuse does have omhttp, but not Kafka.  Furthermore, the base package name for rsyslog itself is named differently in the Adiscon and Suse repos, causing dependency issues for rsyslog-kafka.  After force-installing rsyslog-kafka from  Adiscon I think I now have a 1903 with both http and kafka that will work...

**Comment by darakian** [comment]
@rgerhards Not to badger, but is the plan to not include omhttp in the rsyslog repos for the foreseeable future? I wouldn't mind helping with the packaging process, but I'm also have zero packaging experience.

**Comment by rgerhards** [comment]
Well, the OBS repository **is** a rsyslog repo. The plan is to transfer all package build to it and dump the legacy ones. But we probably need to have a larger discussion as nobody seems to want to help - so probably goodby to the idea to provide packages not only for Ubuntu and CentOS.

**Comment by darakian** [comment]
Yes, but the omttp package isn't in the OBS repo.
https://download.opensuse.org/repositories/home:/rgerhards/CentOS_6/x86_64/
Listing the packages I see
```

  | libestr-debuginfo-0.1.11-1.1.x86_64.rpm | 01-Nov-2018 10:33 | 23K | Details
-- | -- | -- | -- | --
  | libestr-devel-0.1.11-1.1.x86_64.rpm | 01-Nov-2018 10:33 | 11K | Details
  | libestr0-0.1.11-1.1.x86_64.rpm | 01-Nov-2018 10:33 | 10K | Details
  | libfastjson-debuginfo-0.99.8-3.2.x86_64.rpm | 04-Jul-2018 03:38 | 64K | Details
  | libfastjson-devel-0.99.8-3.2.x86_64.rpm | 04-Jul-2018 03:38 | 21K | Details
  | libfastjson4-0.99.8-3.2.x86_64.rpm | 04-Jul-2018 03:38 | 22K | Details
  | liblogging-debuginfo-1.0.6-9.2.x86_64.rpm | 04-Jul-2018 03:39 | 166K | Details
  | liblogging-devel-1.0.6-9.2.x86_64.rpm | 04-Jul-2018 03:39 | 97K | Details
  | liblogging0-1.0.6-9.2.x86_64.rpm | 04-Jul-2018 03:39 | 48K | Details
  | liblognorm-debuginfo-2.0.6-1.1.x86_64.rpm | 10-Nov-2018 12:06 | 191K | Details
  | liblognorm-devel-2.0.6-1.1.x86_64.rpm | 10-Nov-2018 12:06 | 35K | Details
  | liblognorm5-2.0.6-1.1.x86_64.rpm | 10-Nov-2018 12:06 | 83K | Details
  | librelp-debuginfo-1.4.0-1.1.x86_64.rpm | 06-Mar-2019 14:16 | 199K | Details
  | librelp-devel-1.4.0-1.1.x86_64.rpm | 06-Mar-2019 14:16 | 49K | Details
  | librelp0-1.4.0-1.1.x86_64.rpm | 06-Mar-2019 14:16 | 49K | Details
  | rsyslog-8.1903.0-3.1.x86_64.rpm | 08-Mar-2019 09:48 | 705K | Details
  | rsyslog-debuginfo-8.1903.0-3.1.x86_64.rpm | 08-Mar-2019 09:48 | 2.0M | Details
  | rsyslog-elasticsearch-8.1903.0-3.1.x86_64.rpm | 08-Mar-2019 09:48 | 123K | Details
  | rsyslog-gnutls-8.1903.0-3.1.x86_64.rpm | 08-Mar-2019 09:48 | 122K | Details
  | rsyslog-libdbi-8.1903.0-3.1.x86_64.rpm | 08-Mar-2019 09:48 | 114K | Details
  | rsyslog-mmanon-8.1903.0-3.1.x86_64.rpm | 08-Mar-2019 09:48 | 117K | Details
  | rsyslog-mmfields-8.1903.0-3.1.x86_64.rpm | 08-Mar-2019 09:48 | 111K | Details
  | rsyslog-mmjsonparse-8.1903.0-3.1.x86_64.rpm | 08-Mar-2019 09:48 | 113K | Details
  | rsyslog-mmnormalize-8.1903.0-3.1.x86_64.rpm | 08-Mar-2019 09:48 | 114K | Details
  | rsyslog-mmrm1stspace-8.1903.0-3.1.x86_64.rpm | 08-Mar-2019 09:48 | 110K | Details
  | rsyslog-mmutf8fix-8.1903.0-3.1.x86_64.rpm | 08-Mar-2019 09:48 | 111K | Details
  | rsyslog-mysql-8.1903.0-3.1.x86_64.rpm | 08-Mar-2019 09:48 | 115K | Details
  | rsyslog-ommail-8.1903.0-3.1.x86_64.rpm | 08-Mar-2019 09:48 | 115K | Details
  | rsyslog-omstdout-8.1903.0-3.1.x86_64.rpm | 08-Mar-2019 09:48 | 112K | Details
  | rsyslog-pgsql-8.1903.0-3.1.x86_64.rpm | 08-Mar-2019 09:48 | 114K | Details
  | rsyslog-pmaixforwardedfrom-8.1903.0-3.1.x86_64.rpm | 08-Mar-2019 09:48 | 110K | Details
  | rsyslog-pmciscoios-8.1903.0-3.1.x86_64.rpm | 08-Mar-2019 09:48 | 111K | Details
  | rsyslog-relp-8.1903.0-3.1.x86_64.rpm | 08-Mar-2019 09:48 | 122K | Details
  | rsyslog-snmp-8.1903.0-3.1.x86_64.rpm | 08-Mar-2019 09:48 | 114K | Details
  | rsyslog-sysvinit-8.1903.0-3.1.x86_64.rpm | 08-Mar-2019 09:48 | 109K | Details
```

**Comment by mbonsack** [comment]
@darakian It's in the CentOS 7 one though.  Dependencies may be inhibiting its inclusion in CentOS 6.  Where _I_ have the problem is that the kafka destination is in one repo, and the http one in another.  And the base rsyslog packages are named differently, so you can't install one with the other!

**Comment by darakian** [comment]
Ah, so it is. Thanks for the clarification @mbonsack

**Comment by davidelang** [comment]
On Wed, 3 Apr 2019, mbonsack wrote:

> Where _I_ have the problem is that the kafka destination is in one repo, and 
> the http one in another.  And the base rsyslog packages are named differently, 
> so you can't install one with the other!

This is why we need someone to help with this. Is there anyone who either knows, 
or has time to dig in and learn the OBS stuff to figure out what's happening?

David Lang

**Comment by mbonsack** [comment]
I'm with @darakian; I have no packaging experience and would be starting from ground zero.

**Comment by davidelang** [comment]
On Wed, 3 Apr 2019, mbonsack wrote:

> I'm with @darakian; I have no packaging experience and would be starting from 
> ground zero.

Even starting from ground zero, if you have the time and interest to figure it 
out you can be a big help. Rainer is pulled in many directions, and I'd 
(somewhat selfishly) prefer that he work on core rsyslog functionality and 
bugfixes rather than fighting to figure out OBS :-)

we all had to start somewhere. I have made packages that work in my environment, 
but would be starting at ground zero for anything with OBS as well.

David Lang

**Comment by rgerhards** [comment]
Sent from phone, thus brief.

David Lang <notifications@github.com> schrieb am Mi., 3. Apr. 2019, 21:23:

> On Wed, 3 Apr 2019, mbonsack wrote:
>
> > Where _I_ have the problem is that the kafka destination is in one repo,
> and
> > the http one in another. And the base rsyslog packages are named
> differently,
> > so you can't install one with the other!
>

Kafka is a different beast. The version of the client library (librdkafka)
that is in most distros segfaults and/or leaks memory and/or loses
messages. Adiscon has done some quite dirty tricks to create a
rsyslog-kafka package that works.

I don't like to reproduce this. We really need help that can tell how to do
it right.

Rainer


This is why we need someone to help with this. Is there anyone who either

**Comment by mbonsack** [comment]
Are you saying Adiscon had to create code to work around librdkafka bugs, or did you rewrite portions of librdkafka and ship that, or both?

**Comment by rgerhards** [comment]
El mié., 3 abr. 2019 a las 23:08, mbonsack (<notifications@github.com>)
escribió:

> Are you saying Adiscon had to create code to work around librdkafka bugs,
> or did you rewrite portions of librdkafka and ship that, or both?
>

Neither - we just use the current version ;-) Distros tend to ship buggy
old versions with only commonly visible bugs fixed.

BUT: this means we need to package librdkafka, and that opens a can of
worms. If I have time, I'll describe it in more depth. Its along the same
issue why omhttp will not work on CentOS6 - the heavily outdated version of
libcurl is simply insufficient.

Rainer

**Comment by zhang-jc** [comment]
I have compiled omhttp.so successfully. You can download it for CentOS 6.5 from http://zhang-jc.github.io/2019/04/06/CentOS-6-5-%E7%BC%96%E8%AF%91-omhttp-so-%E4%B8%8B%E8%BD%BD/.

**Comment by rgerhards** [comment]
How did you solve the libcurl issue?

Sent from phone, thus brief.

zhang-jc <notifications@github.com> schrieb am Sa., 6. Apr. 2019, 18:22:

**Comment by mymtw** [comment]
@rgerhards earlier I wrote in this issue (above) that rsyslog "could not load module omhttp". I've just got update for ubuntu of omhttp module, it looks like it resolved the problem. thx

**Comment by mymtw** [comment]
I configure rsyslog for sending messages to telegram
```
module(load="omhttp")

template(name="tpl_echo" type="string" string="%msg%")
ruleset(name="rs_retry_forever") {
    action(
        type="omhttp"
        server="https://api.telegram.org"
        serverport="443"
        restpath="bot731686324:AAElGaB6MLCil7o0cYX6Sjfg1hK5ngma8vs/sendMessage"
        template="tpl_echo"

        batch="on"
        batch.format="jsonarray"
        batch.maxsize="10"

        retry="off"
        retry.ruleset="rs_retry_forever"
        errorfile="/tmp/mopedgoa.log"
    )
}

template(name="tpl1" type="string" string="{\"type\":\"syslog\", \"host\":\"%HOSTNAME%\"}")
action(
    type="omhttp"
    server="https://api.telegram.org"
    serverport="443"
    restpath="MYTOKENHERE/sendMessage"
    template="tpl1"

    batch="on"
    batch.format="jsonarray"
    batch.maxsize="10"

    retry="on"
    retry.ruleset="rs_retry_forever"
)
```
but rsyslog writing:
`rsyslogd: omhttp: checkResult error http status code: 400 reply: {"ok":false,"error_code":400,"description":"Bad Request: message text is empty"}`
how to fix it?

**Comment by davidelang** [comment]
This is a message from the server you are trying to post to. I would guess that 
the format you are sending doesn't match what the server you are posting to is 
expecting.

you don't indicate which action is having the problem.

David Lang

**Comment by mymtw** [comment]
@davidelang yes, error in restpath `restpath="bot731686324:AAElGaB6MLCil7o0cYX6Sjfg1hK5ngma8vs/sendMessage?chat_id=370756877&text="`
But maybe you know how to send log message in text arg like &text=mylogmsg as `GET` request?

**Comment by nokiabaitanik** [comment]
I have build omhttp so for redhat7. but when I take that so file ,and copy it some other rhel system, while reloading rsyslog it is giving following error .

 could not load module '/usr/lib64/rsyslog/omhttp.so', dlopen: /usr/lib64/rsyslog/omhttp.so: undefined symbol: r_dbgprintf  [v8.24.0 ...com/e/2066 ]

I have used  ./configure --enable-omhttp to build it

**Comment by darakian** [comment]
@nokiabaitanik you'll probably also need the `libfastjson4` and `libestr` packages. My deploy uses those in addition to the base rsyslog package, gnutls, and omhttp.

**Comment by davidelang** [comment]
you should build all of rsyslog, not just one module.

in theory you can build just one module, but there are so many things that have 
to be the same (including possible issues with RedHat modifying the source for 
their packages) that it's just not worth tracking down the problems.

David Lang

**Comment by nokiabaitanik** [comment]
yeah.. .. the omhttp.so file I built from the latest source code in rhel7. and then copied omhttp.so to a node (rhel7) where rsyslog verison is 8.24.0. 
Probably that is why it is not able to load.

**Comment by darakian** [comment]
Didn't expect this to be open for two months, but I've gotten more than I expected out of the issue. Thanks @rgerhards and @jgerhards for the help. I'll be closing this now.
