### ISSUE TITLE
omkafka.c:40:32: fatal error: librdkafka/rdkafka.h: No such file or directory

### ISSUE THREAD

**Issue by hxwang1024** [rsyslog/rsyslog#3536]
compile rsyslog with general account.

export LIBRDKAFKA_CFLAGS=-I$LIBKAFKA_OBJ"/include"
export LIBRDKAFKA_LIBS=-L$LIBKAFKA_OBJ"/lib/ -lrdkafka"

enable omkafka module, compile error info:

[2019-03-06 21:48:58] omkafka.c:40:32: fatal error: librdkafka/rdkafka.h: No such file or directory
[2019-03-06 21:48:58]  #include <librdkafka/rdkafka.h>
[2019-03-06 21:48:58]                                 ^
[2019-03-06 21:48:58] compilation terminated.
[2019-03-06 21:48:58] make[2]: *** [omkafka_la-omkafka.lo] Error 1

But, I can find librdkafka/rdkafka.h in $LIBKAFKA_OBJ"/include" directory

**Comment by hxwang1024** [comment]
I have try compile rsyslog on version 8.38.0/8.39.0. and it is same error info.

**Comment by rgerhards** [comment]
your dependency is not properly installed. check config.log. I guess the pkgconfig file for librdkafka is not correct.

**Comment by hxwang1024** [comment]
> your dependency is not properly installed. check config.log. I guess the pkgconfig file for librdkafka is not correct.

I install librdkafka:
tar -zxvf librdkafka-1.0.0-RC8-test-deps9.tar.gz
cd librdkafka-1.0.0-RC8-test-deps9
./configure --prefix=$LIBKAFKA_OBJ



os:  centos6.3

**Comment by hxwang1024** [comment]
I find there not found sasl/sasl.h file in config.log.

where can find gssapi source code ?
I  want to install gssapi by source code way.

**Comment by jgerhards** [comment]
> I find there not found sasl/sasl.h file in config.log.
> 
> where can find gssapi source code ?
> I want to install gssapi by source code way.

do you mean librdkafka or rsyslog?

**Comment by alorbach** [comment]
You can find the dependencies in our package control files:
https://github.com/rsyslog/rsyslog-pkg-ubuntu/blob/master/rsyslog/bionic/v8-stable/debian/control
