### ISSUE TITLE
Reproducible slow disk assisted queue drain with Elasticsearch output

### ISSUE THREAD

**Issue by radu-gheorghe** [rsyslog/rsyslog#3543]
There have been multiple reports of the disk part of the disk-assisted queues draining slowly (more recently https://github.com/rsyslog/rsyslog/issues/2646). This time **I'm able to reproduce it consistently in an isolated environment**. I'm attaching [an archive](https://github.com/rsyslog/rsyslog/files/2961131/rsyslog_queues.zip) with the following:
- a docker-compose with Dockerfiles for rsyslog, Elasticsearch and Kibana
- Kibana is in the mix just for monitoring. impstats is set up to send data to the same Elasticsearch and in the archive you can find an export.json file that you can import in Kibana to have a dashboard of impstats set up

Below you can see a screenshot with that dashboard in **three different test runs**: one between roughly 12:30 and 12:38, one between 12:45 and 12:47 and one started around 12:52 that's not finished in this screenshot.

<img width="1692" alt="Screen Shot 2019-03-13 at 12 56 22" src="https://user-images.githubusercontent.com/1482088/54274320-78743680-4590-11e9-8d5c-9270c29104d2.png">

The first and the last test were done with a disk-assisted queue (the rsyslog.conf is in the archive). To reproduce it, you'd do `docker-compose up`, then log in to the ubuntu box and run:

```for i in {1..200}; do cat apache.log; done | nc rsyslog 514```

to send 1M logs. As `apache.log` has 5K messages.

With disk-assisted queues, this is the behaviour people complain about:
- **as long as the memory queue has data in it, there's good throughput**: about 7-8K EPS on my laptop with this configuration
- **draining from the disk part of the queue is very slow**: under 2K EPS, even with no data coming in. Meanwhile, CPU usage is low (~20% of one core)

The second test (between 12:45 and 12:47) was with pure disk queues (I just commented out the watermarks). The Kibana dashboard registered its metrics as "memory" because the search was `-DA` 😄 

**The pure disk queue gave a constant 15K EPS throughout the whole test**, twice that of the in-memory part of the disk-assisted queue. Maybe this is unusual because I have a good SSD, or Docker maybe did some caching. Interesting result, nonetheless.

I didn't try with pure memory queues. But I did try with both LinkedList (first test) and FixedArray (third test) for the disk-assisted memory queue.

Is there something we can do to make the disk part of the DA queue faster? Judging from @davidelang 's comment in https://github.com/rsyslog/rsyslog/issues/2646#issuecomment-381278360 it may be a problem of batching or priority? Also according to the same issue (thanks @portante for writing it!) this slowness doesn't seem to be related to omelasticsearch.

**Comment by rgerhards** [comment]
thx for sharing this. Will try to look ASAP, but have been away for some days and now the pile of work is even larger ;-)

**Comment by rgerhards** [comment]
> Is there something we can do to make the disk part of the DA queue faster? Judging from @davidelang 's comment in [#2646 (comment)](https://github.com/rsyslog/rsyslog/issues/2646#issuecomment-381278360) it may be a problem of batching or priority? Also according to the same issue (thanks @portante for writing it!) this slowness doesn't seem to be related to omelasticsearch.

Can answer this quickly in a generic way: I would really love to do a rewrite of the disk queue subsystem, but it's a real big bunch or work. I do not have enough free time and nobody wants to sponsor it...

**Comment by radu-gheorghe** [comment]
Thanks for following up on this! I totally get the "pile of work" situation :)

I would like to understand more about how the disk queue subsystem currently works. Any place of me to look at besides the code?

I'm also curious why the pure disk queue is faster (at least in these tests) than the disk-assisted queue. Because by the logic of it, disk-assisted should be faster - I can even see in stats how stuff is indexed in memory, when size drops below the high watermark. It has all the ingredients to be faster.

**Comment by rgerhards** [comment]
> I would like to understand more about how the disk queue subsystem currently works. Any place of me to look at besides the code?

actually I'd say the code is best bet nowadays -- all doc on it is 10+ yrs old

> I'm also curious why the pure disk queue is faster (at least in these tests) than the disk-assisted queue. Because by the logic of it, disk-assisted should be faster - I can even see in stats how stuff is indexed in memory, when size drops below the high watermark. It has all the ingredients to be faster.

I agree this should be the case. My gut feeling might be locking contention. Maybe a strace would show what is going on.

In a nutshell, the in-mem queue (on n threads) runs in parallel to a real disk queue (on one thread). But they use the same lock (and need to). The mem queue forwards to disk queue if it goes above the threshold.

**Comment by radu-gheorghe** [comment]
Also, regarding the disk queue subsystem rewrite: can you give more details? Like, what's wrong with it now, what can be improved and how. I can totally get that some items might not be 100% clear, but I'm curious what you have in mind.

**Comment by radu-gheorghe** [comment]
Oh, wow! So the disk queue is single-threaded even if I set workerthreads to N? Or is it single-threaded just in the context of a DA queue? If it's the latter, it would explain everything.

**Comment by rgerhards** [comment]
El mar., 19 mar. 2019 a las 12:53, Radu Gheorghe (<notifications@github.com>)
escribió:

> Oh, wow! So the disk queue is single-threaded even if I set workerthreads
> to N? Or is it single-threaded just in the context of a DA queue? If it's
> the latter, it would explain everything.
>

It's always single-threaded. We use sequential files, and we cannot handle
far different i/o ops on different places on them. Did I mention I think a
rewrite would be desirable? ;-)

Rainer

>

**Comment by radu-gheorghe** [comment]
Sorry if my question sounds dumb, then: if I have a disk queue, I'm only going to write to Elasticsearch on one thread? That would explain a lot, indeed...

**Comment by rgerhards** [comment]
Not a dumb question. That's exactly how it is.

**Comment by radu-gheorghe** [comment]
Thanks a million for explaining this, Rainer! The whole behavior makes a LOT more sense now.

**Comment by rgerhards** [comment]
@radu-gheorghe let me drop this link: https://www.rsyslog.com/doc/v8-stable/concepts/queues.html

not sure if you were aware of it - it is an in-depth description of queues. Granted, it needs some love, and the "diskq is single-threaded" probably is hidden too much in the wall of text ;-) Still thought I let you know.

That said, I think the disk queue part of a DA queue should not be that much slower than a pure disk queue.

**Comment by davidelang** [comment]
On Tue, 19 Mar 2019, Rainer Gerhards wrote:

>> I'm also curious why the pure disk queue is faster (at least in these tests) than the disk-assisted queue. Because by the logic of it, disk-assisted should be faster - I can even see in stats how stuff is indexed in memory, when size drops below the high watermark. It has all the ingredients to be faster.
>
> I agree this should be the case. My gut feeling might be locking contention. Maybe a strace would show what is going on.

does the DA thread move the messages to the in-memory queue and then deliver 
them? or does it deliver them directly from the disk queue?

David Lang

**Comment by radu-gheorghe** [comment]
@rgerhards thanks, I was aware of that article and read it many times, but it sounds like I still don't know it well enough :(

@davidelang I believe it delivers data directly from the disk queue. i.e. the two queues run in parallel rather than being chained. Which is where the lock that Rainer was talking about may come in.

**Comment by rgerhards** [comment]
> I believe it delivers data directly from the disk queue. i.e. the two queues run in parallel rather than being chained. Which is where the lock that Rainer was talking about may come in.

yes, it really is independent. If mem queue gets full, it simply does not process data but enq in disk queue. Disk queue then totally independently dequeues messages and processes them. They only share the queue mutex, as at the higher level all must look like one queue.

So with an active disk queue, a DA queue has a minimum of 2 wrkr threads (one for each queue). wrkrmax for mem queue is configured limit, worker max for disk queue is always 1.

**Comment by rgerhards** [comment]
@radu-gheorghe given the current state of discussion - does it make sense to pursue this any further or should I close?

**Comment by rgerhards** [comment]
@radu-gheorghe sorry for being late in trying to fully reproduce your environment. Do you think the docker-compose should still work nowadays? I ask because it starts rsyslog and kibana container but than hangs... Starting the es01 container, I see
```
[2019-10-08T12:48:18,294][INFO ][o.e.t.TransportService   ] [wZAhQvV] publish_address {172.17.0.2:9300}, bound_addresses {0.0.0.0:9300}
[2019-10-08T12:48:18,307][INFO ][o.e.b.BootstrapChecks    ] [wZAhQvV] bound or publishing to a non-loopback address, enforcing bootstrap checks
ERROR: [1] bootstrap checks failed
```
could you lend me a helping hand getting it up?

**Comment by rgerhards** [comment]
I assume this is solved now by https://github.com/rsyslog/rsyslog/pull/3926 - please re-open (or let me know) if not.
