### ISSUE TITLE
there is not lexer.c in grammar directory in rsyslog latest version.

### ISSUE THREAD

**Issue by hxwang1024** [rsyslog/rsyslog#3545]
compile fail. 
There is not lexer.c file in grammar directory in rsyslog latest version.

I add lexer.c into grammar directory, successfully compile.

**Comment by rgerhards** [comment]
`lexer.c` is an **output** file generated by `flex`. So it MUST NOT be present. It looks like you build incorrectly, `make` will generate it Follow `autoreconf`, `./configure.sh`, `make` build sequence.
