### ISSUE TITLE
can not exit rsyslog

### ISSUE THREAD

**Issue by hxwang1024** [rsyslog/rsyslog#3547]
![image](https://user-images.githubusercontent.com/33044973/54357392-f15eb580-4698-11e9-86b2-0d64e35878c0.png)

**Comment by rgerhards** [comment]
version?

**Comment by hxwang1024** [comment]
> version?

rsyslog version: 8.38.0

**Comment by rgerhards** [comment]
If you want to cancel rsyslog via ctl-c, you need to enable it: `shutdown.enable.ctlc`

doc: https://www.rsyslog.com/doc/master/rainerscript/global.html?highlight=ctlc
