### ISSUE TITLE
rsyslog imfile to reread full file on timestamp change

### ISSUE THREAD

**Issue by AnjanMukherje** [rsyslog/rsyslog#3548]
### Expected behavior
I'm using rsyslog 8.36.0 version on CS6.0 . I have an application which writes to a file "/tmp/1". This file gets overwritten everytime the application runs (every 20mins/30mins).

We want rsyslog to read this file using imfile. The issue we are facing here is that, rsyslog reads full file initially and sends to /var/log/messages. Then when there are updates to the file where character count is less than the previous , rsyslog will not read that file/will not send it to /var/log/messages.

For Ex: 1st time below full line is sent to /var/log/messages: "rsyslog is used for logging"

Next, below message is not sent as it has less character count or offset value is less that previous read "imfile in rsyslog"

Next, below is message is only partially sent (contents after read) "rsyslog uses imfile to read arbitrary file"

Can someone suggest a solution by which i can have rsyslog read the file fully whenever there is change in timestamp of the file.
### Environment
- rsyslog version: <rsyslog 8.36.0>
- platform: <Centos 6>

**Comment by rgerhards** [comment]
timestamp is not evaluated, as this does not provide a reliable indication of a rewritten file. You need to set `reopenOnTruncate="on"` as this tries to support overwrites. However, the version you are using has probably some issues with truncation detection. I recommend moving to the current 8.1903.0.

doc on imfile options: https://www.rsyslog.com/doc/master/configuration/modules/imfile.html

**Comment by AnjanMukherje** [comment]
Thank You Rainer , yes it solved the issue . But this is working only on polling mode not in notify mode .So I have also added following 

module(load="imfile" PollingInterval="10")
reopenOnTruncate="on" PersistStateInterval="1"

Right now i am not going for latest version since this require lot of changes in my setup.

**Comment by rgerhards** [comment]
> But this is working only on polling mode not in notify mode

maybe with your old version - I don't remember. With rsyslog current, it works in all modes.
