### ISSUE TITLE
Grouping similiar messages by identical field set

### ISSUE THREAD

**Issue by DpoBoceka** [rsyslog/rsyslog#3569]
Is it possible to group, say, firewall messages by the same ip_dest && port_dest && ip_src values?
I need to combine those messages into single one with enumeration  of used source ports.

**Comment by davidelang** [comment]
what do you mean by 'combine these messages'?

do you mean to combine them into one file or into one message?

David Lang

**Comment by DpoBoceka** [comment]
I meant into one message. Basically, I'd discard every message that meets the filter and produce just one message every "t" time or every "n" grouped messages.
So I just need a message with an array of src_ports instead having many of them separately

**Comment by davidelang** [comment]
Rsyslog operates on each message individually (and potentially in parallel), 
what you are looking for is event correlation, which is not what rsyslog is 
designed for.

depending on exactly what you are looking for, you may be able to use the 
dyn_stats to create counts for messages and periodically output one message with 
that info in it. Search for the impstats module and dyn_stats to set your own 
stats.

you may also want to look at other tools like Simple Event Correlator (SEC) that 
are designed to look across multiple messages to summarize them.

David Lang

**Comment by DpoBoceka** [comment]
Yes, I've seen through dyn_stats topic already, but it does counting, not consolidation.
Thank you for advices!
