### ISSUE TITLE
Module omhttp not included in omhttp package for debian

### ISSUE THREAD

**Issue by questmaster** [rsyslog/rsyslog#3576]
### Expected behavior
Installing rsyslog-omhttp package for Debian 9 from https://software.opensuse.org//download.html?project=home%3Argerhards&package=rsyslog#
should include omhttp.so module to be used with rsyslog.

### Actual behavior
omhttp.so module is not included. rsyslog cannot use/load/find omhttp module.

### Steps to reproduce the behavior
Install rsyslog-omhttp package from apt source:
deb http://download.opensuse.org/repositories/home:/rgerhards/Debian_9.0/ /

### Environment
- rsyslog version: Installed from same repo; v8.1903
- platform: Debian 9

**Comment by questmaster** [comment]
Is there a way to contribute a PR to the debian package config?

I checked the debian/rules file and there is a `--enable-omhttp` missing for the parameters of `configure` to build the omhttp.so module.
Additionally a `rsyslog-omhttp.install` file has to be added with the following content to include the built module into the deb-package.

> #!/usr/bin/dh-exec
> usr/lib/rsyslog/omhttp.so

**Comment by rgerhards** [comment]
improvement to the packaging would be appreciated. Please create a "PR" via OBS. Instructions are found on that platform (I am far from being an expert as well).

**Comment by rgerhards** [comment]
side-note: as far as I can see, the package is actually there. http://download.opensuse.org/repositories/home:/rgerhards/Debian_9.0/i386/

Which error do you get when you try to install it?

**Comment by questmaster** [comment]
Yes the package is there, but when you list its contents with `dpkg -c <package>.deb` there is no omhttp.so included. So, the module is not installed. 

I'll check OBS for PR instructions...

**Comment by questmaster** [comment]
Created request on OBS -> https://build.opensuse.org/request/show/692361

**Comment by rgerhards** [comment]
@questmaster Thanks a lot, much appreciated! Just merged it, package rebuild is in process. It would be great if you would also be interested in helping with the packaging project in general - we really need some help here.
