### ISSUE TITLE
discardTruncatedMsg bug that caused the log format to be garbled

### ISSUE THREAD

**Issue by huoarter** [rsyslog/rsyslog#3580]
### Expected behavior
The docker log is transferred to rsyslog, rsyslog trims the data so that the single-line log is less than 64k.However, after the first line of the multi-line log pruning data, the following lines of the log will add characters to change the programname, causing the rsyslog to match the log of the specified programname.
### Actual behavior
Only trim the current line log, it does not affect other logs
### Environment
rsyslog version: 8.39.0
platform: Centos 7.2
for configuration questions/issues, include rsyslog.conf and included config files
``` 
/etc/rsyslog.conf
# rsyslog configuration file

$MaxMessageSize 64k

#### MODULES ####

$ModLoad imudp
$UDPServerRun 514

module(load="imtcp" DiscardTruncatedMsg="on")
input(type="imtcp" port="514")

#### GLOBAL DIRECTIVES ####

$WorkDirectory /var/lib/rsyslog
$ActionFileDefaultTemplate RSYSLOG_TraditionalFileFormat
$IncludeConfig /etc/rsyslog.d/*.conf


#### RULES ####

*.info;mail.none;authpriv.none;cron.none                /var/log/messages
```

```
 /etc/rsyslog.d/30-container-logs.conf
$template ContainerFile,"/var/log/container.log"

if $programname == 'docker' then ?ContainerFile;
&
```
``` 
logs.txt
aaaa....80k
bbb.....80k
```
```
Right message:
 Apr  1 16:49:39 localhost docker/9348a8da7693[6128]: aaaaaaaaaaaaaaaaaaaa...
 Apr  1 16:49:39 localhost docker/9348a8da7693[6128]: bbbbbbbbbbbbbbbbbb...

Now Error message：
Apr  1 16:49:39 localhost docker/9348a8da7693[6128]: aaaaaaaaaaaaaaaaaaaa...
Apr  1 16:50:51 localhost a<30>Apr  1 16:50:51 docker/9348a8da7693[6128]: bbbbbbbbbbbbb
```

**Comment by rgerhards** [comment]
does this happen with the current version (as of this writing: 8.1903.0) as well?

**Comment by huoarter** [comment]
My rsyslog version:
```
[root@dev-lain-001 ~]# rsyslogd -version
rsyslogd 8.39.0, compiled with:
	PLATFORM:				x86_64-redhat-linux-gnu
	PLATFORM (lsb_release -d):
	FEATURE_REGEXP:				Yes
	GSSAPI Kerberos 5 support:		Yes
	FEATURE_DEBUG (debug build, slow code):	No
	32bit Atomic operations supported:	Yes
	64bit Atomic operations supported:	Yes
	memory allocator:			system default
	Runtime Instrumentation (slow code):	No
	uuid support:				Yes
	systemd support:			Yes
	Number of Bits in RainerScript integers: 64

See http://www.rsyslog.com for more information.
```

**Comment by huoarter** [comment]
Thank you for your help in your busy schedule.
I upgraded rsyslog to the new version （ 8.1903.0. The same problem is still exists.
The error message:
```
Apr  2 14:08:05 localhost a<30>Apr  2 14:08:05 docker/768e890fd573[6128]: bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb...```

**Comment by huoarter** [comment]
@rgerhards  Hello, new version, I can still measure the problem.

**Comment by rgerhards** [comment]
> Hello, new version, I can still measure the problem.

great, so we know it's not an already-fixed issue. Could you create and post a debug log of when this happens? https://www.rsyslog.com/doc/v8-stable/troubleshooting/howtodebug.html

**Comment by huoarter** [comment]
[rsyslog.debug.log](https://github.com/rsyslog/rsyslog/files/3046366/rsyslog.debug.log)
Thanks again. This is my a debug log.

**Comment by rgerhards** [comment]
Thx, looks useful on first look.

**Comment by rgerhards** [comment]
mhhh... strange. I don't see why it does not work and also cannot reproduce. Can you submit a debug log that contains rsyslog startup as well (some info is only emitted on startup).

**Comment by huoarter** [comment]
[rsyslog.debug.log](https://github.com/rsyslog/rsyslog/files/3050186/rsyslog.debug.log)
Dear, this is all the debug logs you want from the start.

**Comment by huoarter** [comment]
@rgerhards Dear Rainer, is this a bug ?

**Comment by davidelang** [comment]
if you truncate a structured message (say JSON) the result will be corrupted, 
there's no way to truncate the message and not corrupt structured message. you 
probably want to not truncate, but flag the message in some way for manual 
attention.

or are you talking about some other type of corruption?

David Lang

**Comment by huoarter** [comment]
@davidelang This scenario is like: Multi-line log larger than MaxMessageSize. When the first line is trimmed, the head of the next line will insert some extra characters, which can not be used by (if $programname == 'docker' then ?ContainerFile;&) match this condition

**Comment by rgerhards** [comment]
> @rgerhards Dear Rainer, is this a bug ?

unfortunately I could not work on this in the mean time. But it's still on the plate.

@davidelang from what  I have seen so far, it looks like there is a bug somewhere

**Comment by rgerhards** [comment]
sorry it took a while to come back to this. Good news: I can now reproduce the issue with a testbench test!
