### ISSUE TITLE
Unable to define a "catch-all" input in new configuration syntax

### ISSUE THREAD

**Issue by saurabhnanda** [rsyslog/rsyslog#3601]
### Expected behavior

**All** messages should be output to `/tmp/debug.log`

### Actual behavior

_Most_ messages are being output to `/tmp/debug.log` **except** those generated by the `znapzend` program.

Messages generated by the `znapzend` programs seem to be matching the following config line written in the old syntax...

```
*.*;auth,authpriv.none          /var/log/syslog
```

...but do not seem to be matching the following config written in the new syntax:

```
input(type="imuxsock" ruleset="dbrules" socket="/dev/log")
```

Is there some other unix socket that is being used as an input that is not covered by the config line given above?

### Steps to reproduce the behavior

Configuration files given below.

### Environment
- rsyslog version: 

```
rsyslogd  8.1903.0 (aka 2019.03) compiled with:
        PLATFORM:                               x86_64-pc-linux-gnu
        PLATFORM (lsb_release -d):
        FEATURE_REGEXP:                         Yes
        GSSAPI Kerberos 5 support:              No
        FEATURE_DEBUG (debug build, slow code): No
        32bit Atomic operations supported:      Yes
        64bit Atomic operations supported:      Yes
        memory allocator:                       system default
        Runtime Instrumentation (slow code):    No
        uuid support:                           Yes
        systemd support:                        Yes
        Config file:                            /etc/rsyslog.conf
        PID file:                               /var/run/rsyslogd.pid
        Number of Bits in RainerScript integers: 64
```

- platform: 

```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.2 LTS"
```

- for configuration questions/issues, include rsyslog.conf and included config files

Modules loaded in `/etc/rsyslog.conf` - 

```
$ModLoad imuxsock # provides support for local system logging
$ModLoad imklog   # provides kernel logging support (previously done by rklogd)
```

Inputs & ruleset defined in `/etc/rsyslog.d/01-pgsql.conf`

```
ruleset(name="dbrules" queue.type="LinkedList" queue.filename="dbq"){
  action(type="omfile" dirCreateMode="0755" fileCreateMode="0644" file="/tmp/debug.log" template="RSYSLOG_DebugFormat")
 
  # More conditions and actions come here
}
input(type="imuxsock" ruleset="dbrules" socket="/dev/log")
input(type="imuxsock" ruleset="dbrules" socket="/var/lib/haproxy/dev/log")
```

Inputs & ruleset defined in `/etc/rsyslog.d/50-default.conf` - 

```
auth,authpriv.*                 /var/log/auth.log

#################
# logs from znapzend seem to matching this line
# and getting output to /var/log/syslog
#################
*.*;auth,authpriv.none          /var/log/syslog

syslog.*                        /var/log/rsyslog.log #rsyslog error messages
kern.*                          /var/log/kern.log
mail.*                          /var/log/mail.log

mail.err                        /var/log/mail.err

news.crit                       /var/log/news/news.crit
news.err                        /var/log/news/news.err
news.notice                     /var/log/news/news.notice
```

**Comment by davidelang** [comment]
do you have systemd running on your system? if so, it takes over /dev/log and 
you have to fetch the messages from journald.

try writing logs using the template RSYSLOG_DebugFormat so that we can see what 
one of the logs you are missing looks like

the fact that you have imuxsock loaded with the old syntax (which defaults to 
listening to /dev/log) and then have another input for /dev/log added may cause 
some issues. Try a simplified config and see what shows up.

nothing in your config would filter out znapzend but it's possible that the app 
isn't logging the way you think it is.

David Lang

**Comment by saurabhnanda** [comment]
> do you have systemd running on your system? if so, it takes over /dev/log and you have to fetch the messages from journald.

Yes, I have systemd running. If it takes over `/dev/log`, how is the following working in all cases _except` znapzend?

```
input(type="imuxsock" ruleset="dbrules" socket="/dev/log")
```
> try writing logs using the template RSYSLOG_DebugFormat so that we can see what one of the logs you are missing looks like

I've tried that by making this the first action within the ruleset, but it seems to be working for everything _except_ znapzend:

```
ruleset(name="dbrules" queue.type="LinkedList" queue.filename="dbq"){
  action(type="omfile" dirCreateMode="0755" fileCreateMode="0644" file="/tmp/debug.log" template="RSYSLOG_DebugFormat")
 
  # More conditions and actions come here
}
```

> the fact that you have imuxsock loaded with the old syntax (which defaults to listening to /dev/log) and then have another input for /dev/log added may cause some issues. Try a simplified config and see what shows up.

Will try this, but if this is a misconfiguration, shouldn't this behave similarly for every log source? Now that I think about it, is this the classical case of single input being bound to multiple rulesets? If yes, how come everything is working fine _except_ znapzend? 

> nothing in your config would filter out znapzend but it's possible that the app isn't logging the way you think it is.

Is there some other log-source that only znapzend is using? Is is possible that znapzend is using `imklog`, which is not covered by the following...

```
input(type="imuxsock" ruleset="dbrules" socket="/dev/log")
input(type="imuxsock" ruleset="dbrules" socket="/var/lib/haproxy/dev/log")
```

...but is covered by the following?

```
*.*;auth,authpriv.none          /var/log/syslog
```

**Comment by davidelang** [comment]
On Fri, 5 Apr 2019, Saurabh Nanda wrote:

>> do you have systemd running on your system? if so, it takes over /dev/log and you have to fetch the messages from journald.
>
> Yes, I have systemd running. If it takes over `/dev/log`, how is the following working in all cases _except` znapzend?

thanks to journald, /dev/log doesn't go directly to rsyslog, it goes to journald 
which then sends it to another socket.

in addition, you have two statement that listen to /dev/log, one going to the 
default ruleset, one going to the dbrules ruleset. This can create race 
conditions as to where the messages go.

>> nothing in your config would filter out znapzend but it's possible that the app isn't logging the way you think it is.
>
> Is there some other log-source that only znapzend is using? Is is possible that znapzend is using `imklog`, which is not covered by the following...

I don't know that app, so I don't know how it's generating it's logs

> ```
> input(type="imuxsock" ruleset="dbrules" socket="/dev/log")
> input(type="imuxsock" ruleset="dbrules" socket="/var/lib/haproxy/dev/log")
> ```
>
> ...but is covered by the following?
>
> ```
> *.*;auth,authpriv.none          /var/log/syslog
> ```

you are mixing up inputs and output filtering.

if you can use the config where you see the logs, log them with the debug format 
and it will show you what input it comes in through (along with everything else)

If the logs are not delivered to rsyslog through the input you define, nothing 
will cause them to be output.

I would also look at the logs that go through the default ruleset, if they 
aren't going through the dbrules ruleset, they should be in the other ruleset.

unless they are going to journald and not being forwarded from journald to 
rsyslog.

David Lang

**Comment by saurabhnanda** [comment]
> in addition, you have two statement that listen to /dev/log, one going to the default ruleset, one going to the dbrules ruleset. This can create race conditions as to where the messages go.

It's pretty interesting that this is causing a race condition for _exactly_ the znapzend program. Btw, shouldn't rsyslog refuse to start if this one input is attached to multiple rulesets (if that is known to cause bizarre behaviour?)

> you are mixing up inputs and output filtering.

Isn't the `*.*` part supposed to be conceptually similar to `input(type=...)` ? Or, am I confused?

Btw, I've tried a simplified log format, where I've commented out everything in the old syntax, notably the following line:

```
 *.*;auth,authpriv.none          /var/log/syslog
```

So, now we should have a _single_ statement listening to /dev/log, right? And surprisingly, in `/tmp/debug.log`, I can see statements from all programs, _except_ znapzend:

```
# grep programname /tmp/debug.log | cut -f 6 -d ' ' | sort | uniq
'barman',
'CRON',
'rsyslogd',
'sshd',
'zed',
```

**Comment by saurabhnanda** [comment]
Again, I can re-confirm -- it's ONLY the following line that is able to process incoming log messages from znapzend. If you remove this line, logs from znapzend are lost.

```
 *.*;auth,authpriv.none          /var/log/syslog
```

**Comment by saurabhnanda** [comment]
Okay, now I have the following config _outline_ with TWO debug actions:

```
ruleset(dbrules) {
  action(type="omfile" file="/tmp/debug.log" template="RSYSLOG_DebugFormat")
}

input(type="imuxsock" ruleset="dbrules" socket="/dev/log")

action(type="omfile" file="/tmp/debug2.log" template="RSYSLOG_DebugFormat")
*.*;auth,authpriv.none          /var/log/syslog
```

And I can confirm that znapzend logs are showing up ONLY in /tmp/debug2.log and NOT in /tmp/debug.log. Here's what shows up in /tmp/debug2.log:

```
Debug line with all properties:
FROMHOST: 'prod-backup', fromhost-ip: '127.0.0.1', HOSTNAME: 'prod-backup', PRI: 31,
syslogtag 'znapzend[12992]:', programname: 'znapzend', APP-NAME: 'znapzend', PROCID: '12992', MSGID: '-',
TIMESTAMP: 'Apr  6 07:37:18', STRUCTURED-DATA: '-',
msg: ' SIGHUP received.'
escaped msg: ' SIGHUP received.'
inputname: imuxsock rawmsg: '<31>Apr  6 07:37:18 znapzend[12992]: SIGHUP received.'
$!:
$.:
$/:

Debug line with all properties:
FROMHOST: 'prod-backup', fromhost-ip: '127.0.0.1', HOSTNAME: 'prod-backup', PRI: 30,
syslogtag 'znapzend[12992]:', programname: 'znapzend', APP-NAME: 'znapzend', PROCID: '12992', MSGID: '-',
TIMESTAMP: 'Apr  6 07:37:18', STRUCTURED-DATA: '-',
msg: ' refreshing backup plans...'
escaped msg: ' refreshing backup plans...'
inputname: imuxsock rawmsg: '<30>Apr  6 07:37:18 znapzend[12992]: refreshing backup plans...'
$!:
$.:
$/:
```

If I compare this with a cron log from /tmp/debug.log...

```
Debug line with all properties:
FROMHOST: 'prod-backup', fromhost-ip: '127.0.0.1', HOSTNAME: 'prod-backup', PRI: 86,
syslogtag 'CRON[12025]:', programname: 'CRON', APP-NAME: 'CRON', PROCID: '12025', MSGID: '-',
TIMESTAMP: 'Apr  6 07:41:01', STRUCTURED-DATA: '-',
msg: ' pam_unix(cron:session): session closed for user barman'
escaped msg: ' pam_unix(cron:session): session closed for user barman'
inputname: imuxsock rawmsg: '<86>Apr  6 07:41:01 CRON[12025]: pam_unix(cron:session): session closed for user barman'
$!:
$.:
$/:
```

...I see no reason why the znapzend logs should behave so differently. Am I missing anything?

**Comment by davidelang** [comment]
On Sat, 6 Apr 2019, Saurabh Nanda wrote:

>> in addition, you have two statement that listen to /dev/log, one going to the default ruleset, one going to the dbrules ruleset. This can create race conditions as to where the messages go.
>
> It's pretty interesting that this is causing a race condition for _exactly_ the znapzend program. Btw, shouldn't rsyslog refuse to start if this one input is attached to multiple rulesets (if that is known to cause bizarre behaviour?)

I don't know what's going on with that one type.

>> you are mixing up inputs and output filtering.
>
> Isn't the `*.*` part supposed to be conceptually similar to `input(type=...)` ? Or, am I confused?

no, input() is defining a source of logs. Any logs from this source are added to 
the queue

*.* is a filter for which of the logs that are in the queue and being processed 
should by output by this action() statement

*.* is everything, so you can just leave it out in the new format

the equivalent of

*.*;auth,authpriv.none          /var/log/syslog

in the new format is


*.*;auth,authpriv.none action( type='omfile' filename='/var/log/syslog')

or

if pri("*.*;auth,authpriv.none") then action( type='omfile' filename='/var/log/syslog')

the equivalent to input() is the $*filerun type parameters in the old config 
format.

> Btw, I've tried a simplified log format, where I've commented out everything in the old syntax, notably the following line:
>
> ```
> *.*;auth,authpriv.none          /var/log/syslog
> ```
>
> So, now we should have a _single_ statement listening to /dev/log, right? And surprisingly, in `/tmp/debug.log`, I can see statements from all programs, _except_ znapzend:
>
> ```
> # grep programname /tmp/debug.log | cut -f 6 -d ' ' | sort | uniq
> 'barman',
> 'CRON',
> 'rsyslogd',
> 'sshd',
> 'zed',
> ```

your full config please?

David Lang

**Comment by davidelang** [comment]
On Sat, 6 Apr 2019, Saurabh Nanda wrote:

> Again, I can re-confirm -- it's ONLY the following line that is able to process incoming log messages from znapzend. If you remove this line, logs from znapzend are lost.
>
> ```
> *.*;auth,authpriv.none          /var/log/syslog
> ```

This tells me nothing because I don't know what ruleset this is part of or what 
inputs feed into that ruleset.

David Lang

**Comment by saurabhnanda** [comment]
> your full config please?

Does https://github.com/rsyslog/rsyslog/issues/3601#issuecomment-480483200 give enough context about the config? Or should I post all config files here?

**Comment by davidelang** [comment]
On Sat, 6 Apr 2019, Saurabh Nanda wrote:

> Okay, now I have the following config _outline_ with TWO debug actions:
>
> ```
> ruleset(dbrules) {
>  action(type="omfile" file="/tmp/debug.log" template="RSYSLOG_DebugFormat")
> }
>
> input(type="imuxsock" ruleset="dbrules" socket="/dev/log")
>
> action(type="omfile" file="/tmp/debug2.log" template="RSYSLOG_DebugFormat")
> *.*;auth,authpriv.none          /var/log/syslog
> ```
>
> And I can confirm that znapzend logs are showing up ONLY in /tmp/debug2.log and NOT in /tmp/debug.log. Here's what shows up in /tmp/debug2.log:
>
> ```
> Debug line with all properties:
> FROMHOST: 'prod-backup', fromhost-ip: '127.0.0.1', HOSTNAME: 'prod-backup', PRI: 31,
> syslogtag 'znapzend[12992]:', programname: 'znapzend', APP-NAME: 'znapzend', PROCID: '12992', MSGID: '-',
> TIMESTAMP: 'Apr  6 07:37:18', STRUCTURED-DATA: '-',
> msg: ' SIGHUP received.'
> escaped msg: ' SIGHUP received.'
> inputname: imuxsock rawmsg: '<31>Apr  6 07:37:18 znapzend[12992]: SIGHUP received.'
> $!:
> $.:
> $/:

ok, this says that it's on the input imuxsock, but it's not being written inside 
the dbrules ruleset, it's being written by the default ruleset, so that says 
that the log messages are not being processed by your input line. This may be 
because your module load is grabbing /dev/log. And I have no idea why it would 
be doing so for only some sources of logs and not others.

look at 
https://www.rsyslog.com/doc/v8-stable/configuration/modules/imuxsock.html

and especially the link to how things work differently under systemd
https://www.rsyslog.com/doc/v8-stable/configuration/modules/imuxsock.html#imuxsock-systemd-details-label

Then update the config so that it uses the new format for loading the module as 
well.

David Lang

**Comment by davidelang** [comment]
On Sat, 6 Apr 2019, Saurabh Nanda wrote:

>> your full config please?
>
> Does https://github.com/rsyslog/rsyslog/issues/3601#issuecomment-480483200 give enough context about the config? Or should I post all config files here?

Since you are changing the config, please post the full config you are currently 
testing here (probably after you make the changes that I just outlined in 
another e-mail)

David Lang

**Comment by saurabhnanda** [comment]
I have a feeling the subtle difference in behaviour is due to this line in the docs:

> Otherwise, if rsyslog is running under systemd AND /run/systemd/journal/syslog exists, (AND the user has not explicitly set SysSock.Use="off") then the default listener socket name is overwritten with /run/systemd/journal/syslog.

In my case, I can confirm that `/run/systemd/journal/syslog` exists. Further, `dbrules` ruleset is explicitly binding to `/dev/log`. I tried removing the `socket` param, but it doesn't work:

```
# rsyslogd -N1
rsyslogd: version 8.1903.0, config validation run (level 1), master config /etc/rsyslog.conf
rsyslogd: error during parsing file /etc/rsyslog.d/01-pgsql.conf, on or before line 103: parameter 'socket' required but not specified - fix config [v8.1903.0 try https://www.rsyslog.com/e/2207 ]
rsyslogd: imuxsock: required parameter are missing  [v8.1903.0 try https://www.rsyslog.com/e/2211 ]
rsyslogd: module 'ompgsql' already in this config, cannot be added  [v8.1903.0 try https://www.rsyslog.com/e/2221 ]
```

So, we're looking at two things, which are subtly different:

- the `dbrules` ruleset that is explicitly bound to `/dev/log`
- vs the `default` ruleset that is bound to the imuxsock input, with whatever is the default behaviour.

How do I get the _true_ default behaviour with `input(type="imuxsock" ruleset="dbrules")`?

**Comment by saurabhnanda** [comment]
I tried the following...

```
input(type="imuxsock" ruleset="dbrules" SysSock.Use="on")
```

... but it's throwing the following error:

```
rsyslogd: version 8.1903.0, config validation run (level 1), master config /etc/rsyslog.conf
rsyslogd: error during parsing file /etc/rsyslog.d/01-pgsql.conf, on or before line 103: parameter 'socket' required but not specified - fix config [v8.1903.0 try https://www.rsyslog.com/e/2207 ]
rsyslogd: imuxsock: required parameter are missing  [v8.1903.0 try https://www.rsyslog.com/e/2211 ]
rsyslogd: error during parsing file /etc/rsyslog.d/01-pgsql.conf, on or before line 103: parameter 'SysSock.Use' not known -- typo in config file? [v8.1903.0 try https://www.rsyslog.com/e/2207 ]
rsyslogd: module 'ompgsql' already in this config, cannot be added  [v8.1903.0 try https://www.rsyslog.com/e/2221 ]
```

**Comment by davidelang** [comment]
On Sat, 6 Apr 2019, Saurabh Nanda wrote:

> I have a feeling the subtle difference in behaviour is due to this line in the docs:
>
>> Otherwise, if rsyslog is running under systemd AND 
>> /run/systemd/journal/syslog exists, (AND the user has not explicitly set 
>> SysSock.Use="off") then the default listener socket name is overwritten with 
>> /run/systemd/journal/syslog.
>
> In my case, I can confirm that `/run/systemd/journal/syslog` exists. Further, 
> `dbrules` ruleset is explicitly binding to `/dev/log`. I tried removing the 
> `socket` param, but it doesn't work:
>
> ```
> # rsyslogd -N1
> rsyslogd: version 8.1903.0, config validation run (level 1), master config /etc/rsyslog.conf
> rsyslogd: error during parsing file /etc/rsyslog.d/01-pgsql.conf, on or before line 103: parameter 'socket' required but not specified - fix config [v8.1903.0 try https://www.rsyslog.com/e/2207 ]
> rsyslogd: imuxsock: required parameter are missing  [v8.1903.0 try https://www.rsyslog.com/e/2211 ]
> rsyslogd: module 'ompgsql' already in this config, cannot be added  [v8.1903.0 try https://www.rsyslog.com/e/2221 ]
> ```
>
> So, we're looking at two things, which are subtly different:
>
> - the `dbrules` ruleset that is explicitly bound to `/dev/log`
> - vs the `default` ruleset that is bound to the imuxsock input, with whatever is the default behaviour.

try doing

lsof |grep /dev/log

and see what is returned

> How do I get the _true_ default behaviour with `input(type="imuxsock" ruleset="dbrules")`?

I believe that you will need to set SysSock.use='no' in the module() statement 
(replacing the $modload line from your original config), and then you can set an 
input statement that binds to /dev/log with a ruleset defined. Although, since 
journald has already grabbed /dev/log, I think you are going to have trouble. 
You really should use imjournal or listen to the socket that journald is going 
to write logs to (which isn't /dev/log, it's /run/systemd/journal/syslog so that 
is what you would need to read)

David Lang

**Comment by davidelang** [comment]
On Sat, 6 Apr 2019, Saurabh Nanda wrote:

> I tried the following...
>
> ```
> input(type="imuxsock" ruleset="dbrules" SysSock.Use="on")
> ```

SysSock.Use is a parameter for the module() command, not for the input() 
command.

David Lang

> ... but it's throwing the following error:
>
> ```
> rsyslogd: version 8.1903.0, config validation run (level 1), master config /etc/rsyslog.conf
> rsyslogd: error during parsing file /etc/rsyslog.d/01-pgsql.conf, on or before line 103: parameter 'socket' required but not specified - fix config [v8.1903.0 try https://www.rsyslog.com/e/2207 ]
> rsyslogd: imuxsock: required parameter are missing  [v8.1903.0 try https://www.rsyslog.com/e/2211 ]
> rsyslogd: error during parsing file /etc/rsyslog.d/01-pgsql.conf, on or before line 103: parameter 'SysSock.Use' not known -- typo in config file? [v8.1903.0 try https://www.rsyslog.com/e/2207 ]
> rsyslogd: module 'ompgsql' already in this config, cannot be added  [v8.1903.0 try https://www.rsyslog.com/e/2221 ]
> ```
>
>

**Comment by saurabhnanda** [comment]
> SysSock.Use is a parameter for the module() command, not for the input() command.

So, if I'm understanding this correctly, the `$ModLoad imuxsock` directive (or the equivalent in new syntax), not only loads the module, but also establishes an input channel, right? And the exact input that this establishes, in presence of `systemd`, is governed by the complex set of rules specified at https://www.rsyslog.com/doc/v8-stable/configuration/modules/imuxsock.html#imuxsock-systemd-details-label ?

How does one bind a ruleset to this implicitly defined input channel?

**Comment by davidelang** [comment]
On Sun, 7 Apr 2019, Saurabh Nanda wrote:

>> SysSock.Use is a parameter for the module() command, not for the input() command.
>
> So, if I'm understanding this correctly, the `$ModLoad imuxsock` directive (or the equivalent in new syntax), not only loads the module, but also establishes an input channel, right? And the exact input that this establishes, in presence of `systemd`, is governed by the complex set of rules specified at https://www.rsyslog.com/doc/v8-stable/configuration/modules/imuxsock.html#imuxsock-systemd-details-label ?
>
> How does one bind a ruleset to this implicitly defined input channel?

you can't.

you can tell the module() command to not implicitly define this input and then 
define it yourself (where you can specify a ruleset)

David Lang

**Comment by saurabhnanda** [comment]
I am trying to make sense of https://www.freedesktop.org/wiki/Software/systemd/syslog/ Do you know what the following means...

> Note that it is now the journal that listens on /dev/log, no longer the BSD syslog daemon directly. If your logging daemon wants to get access to all logging data then it should listen on /run/systemd/journal/syslog instead via the syslog.socket unit file that is shipped along with systemd. On a systemd system it is no longer OK to listen on /dev/log directly, and your daemon may not bind to the /run/systemd/journal/syslog socket on its own. If you do that then you will lose logging from STDOUT/STDERR of services (as well as other stuff).

..especially the following sentence:

>  On a systemd system it is no longer OK to listen on /dev/log directly, and your daemon may not bind to the /run/systemd/journal/syslog socket on its own.

You can't bind to /dev/log because you will lose logs sent to STDOUT and STDERR. But  you cannot bind to /run/systemd/journal/syslog as well. What exactly do you bind to, then?

**Comment by saurabhnanda** [comment]
I can confirm that the following works, but I am not sure if this is the best way to achieve this. Any thoughts?

```
module(load="imuxsock" SysSock.Use="off")
module(load="ompgsql")

ruleset(name="dbrules" queue.type="LinkedList" queue.filename="dbq"){
  action(type="omfile" dirCreateMode="0755" fileCreateMode="0644" file="/tmp/debug.log" template="RSYSLOG_DebugFormat")
  # more actions and if-then-else conditions
}

input(type="imuxsock" ruleset="dbrules" socket="/run/systemd/journal/syslog")
input(type="imuxsock" ruleset="dbrules" socket="/var/lib/haproxy/dev/log")
```

**Comment by saurabhnanda** [comment]
I found a problem, the following command used to work earlier, but with the new config, it throws as an error:

```
# logger "hello"
logger: socket /dev/log: Connection refused
```

**Comment by davidelang** [comment]
On Sun, 7 Apr 2019, Saurabh Nanda wrote:

> I am trying to make sense of https://www.freedesktop.org/wiki/Software/systemd/syslog/ Do you know what the following means...
>
>> Note that it is now the journal that listens on /dev/log, no longer the BSD syslog daemon directly. If your logging daemon wants to get access to all logging data then it should listen on /run/systemd/journal/syslog instead via the syslog.socket unit file that is shipped along with systemd. On a systemd system it is no longer OK to listen on /dev/log directly, and your daemon may not bind to the /run/systemd/journal/syslog socket on its own. If you do that then you will lose logging from STDOUT/STDERR of services (as well as other stuff).
>
> ..especially the following sentence:
>
>>  On a systemd system it is no longer OK to listen on /dev/log directly, and your daemon may not bind to the /run/systemd/journal/syslog socket on its own.
>
> You can't bind to /dev/log because you will lose logs sent to STDOUT and STDERR. But  you cannot bind to /run/systemd/journal/syslog as well. What exactly do you bind to, then?

you can either bind to /run/systemd/journal/syslog where journald sends a copy 
of the logs, or you use imjournal (which is what most people do) to use the 
systemd APIs to get the logs.

David Lang

**Comment by davidelang** [comment]
On Mon, 8 Apr 2019, Saurabh Nanda wrote:

> I can confirm that the following works, but I am not sure if this is the best way to achieve this. Any thoughts?
>
> ```
> module(load="imuxsock" SysSock.Use="off")
> module(load="ompgsql")
>
> ruleset(name="dbrules" queue.type="LinkedList" queue.filename="dbq"){
>  action(type="omfile" dirCreateMode="0755" fileCreateMode="0644" file="/tmp/debug.log" template="RSYSLOG_DebugFormat")
>  # more actions and if-then-else conditions
> }
>
> input(type="imuxsock" ruleset="dbrules" socket="/run/systemd/journal/syslog")
> input(type="imuxsock" ruleset="dbrules" socket="/var/lib/haproxy/dev/log")
> ```

you either do this or you use imjournald instead of imuxsock

test both, and watch the CPU usage of not only rsyslog, but also of journald to 
compare the load.

David Lang

**Comment by davidelang** [comment]
that is a systemd problem, it's what manages /dev/log

I would love to know how you managed to disable this.

David Lang

**Comment by saurabhnanda** [comment]
I think I understood how I managed to get my system in such a horribly confused state.

- after a fresh reboot, `/dev/log` is a symlink to `/run/systemd/journal/dev-log` and `lsof | grep /dev/log` proves that no process is explicitly listening to `/dev/log`

```
# ls -l /dev/log
lrwxrwxrwx 1 root root 28 Apr  4 13:18 /dev/log -> /run/systemd/journal/dev-log

# lsof | grep /dev/log
# 
```

- however, during my experimentation, I ended up doing the following, which clobbered the `/dev/log` symlink and created a fresh socket, which was completely independent of `systemd`

```
input(type="imuxsock" ruleset="dbrules" socket="/dev/log")
```

- ideally, upon removing that configuration line, and restarting rsyslog, the socket should be removed completely, as per the docs at https://www.rsyslog.com/doc/v8-stable/configuration/modules/imuxsock.html#step-3-shutdown-log-sockets however this did not happen (bug?), and I ended-up with a dangling socket in `/dev/log`

> If the socket was not passed in via systemd AND the configuration permits rsyslog to do so (the default setting), rsyslog will unlink/remove the log socket. If not permitted to do so (the user specified otherwise), then rsyslog will not unlink the log socket and will leave that cleanup step to the user or application that created the socket to remove it.

- `logger` command writes to `/dev/log` which was being redirected to `/run/systemd/journal/syslog` due to the symlink. After all the experimentation, it's a dangling socket, hence the error.

**Comment by davidelang** [comment]
glad that you have things working.

going back to the original problem, with rsyslog and systemd fighting each other 
for ownership of /dev/log, I'll bet that the app you weren't seeing was getting 
it's logs to journald while everything else was going to rsyslog due to the race 
condition of when each app started and what /dev/log looked like at that point 
in time.

David Lang

**Comment by saurabhnanda** [comment]
> going back to the original problem, with rsyslog and systemd fighting each other for ownership of /dev/log, I'll bet that the app you weren't seeing was getting it's logs to journald while everything else was going to rsyslog due to the race condition of when each app started and what /dev/log looked like at that point in time.

I think here's what was happening originally:

- the default ruleset was bound to `/run/systemd/journal/syslog` which is why the following was receiving `znapzend` logs (probably because that's where znapzend sends them, by default):

```
action(type="omfile" file="/tmp/debug2.log" template="RSYSLOG_DebugFormat")
*.*;auth,authpriv.none          /var/log/syslog
```

- however, since the `dbrules` ruleset was explicitly bound to `/dev/log` **and** it ended up breaking the `/dev/log -> /run/systemd/journal/syslog` symlink, it introduced a "split brain syndrome". Some programs were writing to `/run/systemd/journal/syslog` and some were writing to `/dev/log` and both were being processed by different rulesets.

- however, what is not clear is why this didn't introduce a 100% split-brain. Some logs were appearing on both rule-sets, which is very bizarre.
