### ISSUE TITLE
omhttp how to use rest api interface

### ISSUE THREAD

**Issue by mymtw** [rsyslog/rsyslog#3614]
### Expected behavior
```
module(load="omhttp")
module(load="imfile")

input(type="imfile" File="/tmp/telegram.log" tag="")


template(name="tpl_echo" type="string" string="%msg%")
ruleset(name="rs_retry_forever") {
    action(
        type="omhttp"
        server="https://api.telegram.org"
        serverport="443"
        restpath="mytoken/sendMessage?chat_id=370756877&text="
        template="tpl_echo"

        batch="on"
        batch.format="jsonarray"
        batch.maxsize="10"

        retry="off"
        retry.ruleset="rs_retry_forever"
        errorfile="/tmp/mopedgoa.log"
    )
}

template(name="tpl1" type="string" string="{\"type\":\"syslog\", \"host\":\"%HOSTNAME%\"}")
action(
    type="omhttp"
    server="https://api.telegram.org"
    serverport="443"
    restpath="mytoken/sendMessage?chat_id=370756877&text="
    template="tpl1"

    batch="on"
    batch.format="jsonarray"
    batch.maxsize="10"

    retry="on"
    retry.ruleset="rs_retry_forever"
)
```
### Actual behavior
omhttp: checkResult error http status code: 400 reply: {"ok":false,"error_code":400,"description":"Bad Request: message text is empty"} [v8.1903.0 try https://www.rsyslog.com/e/2218 ]

### Environment
- rsyslog version: latest
- platform: Ubuntu 18.04

How to use restful api interface for send messages from rsyslog?
e.g. how to make POST request?
how to make GET request?
how can I pass my log message to this url in arg `text` e.g. restpath="mytoken/sendMessage?chat_id=370756877&text=???" ?

**Comment by rgerhards** [comment]
does this help? https://www.rsyslog.com/doc/master/configuration/modules/omhttp.html

**Comment by mymtw** [comment]
> does this help? https://www.rsyslog.com/doc/master/configuration/modules/omhttp.html
unfortunately no.

I did not get from `omhttp` docs, how to pass `log message` as `query string argument`

1. I wanted smth like `restpath="myroute/sendMessage?text={$MY_LOG_MESSAGE}"`
2. Also there are not info how to set query type: `GET` or `DELETE`, or `POST`, or `PUT` request

where {$MY_LOG_MESSAGE} - `2019-04-29 my log message`

anyway, thx for your reply

**Comment by rgerhards** [comment]
@gintrator can you help?

**Comment by gintrator** [comment]
@mymtw I think the `dynrestpath` parameter should allow you to create a dynamic path based on your log message. This allows you to use the output of a template as the path + query string. See https://www.rsyslog.com/doc/master/configuration/modules/omhttp.html#dynrestpath.

Currently on POST is supported in omhttp, though it should be relatively straightforward to add support for other HTTP methods. This would probably be set at module load time -- are you looking to dynamically set methods on a per-request basis? POST/PUT make sense to me, not sure about GET/DELETE in the context of rsyslog.

**Comment by mymtw** [comment]
@gintrator `DELETE` request is really not make sense, but `GET` yes, the reason why I did mention `GET` request - is that in `telegram` messenger for posting message to users you need to `GET` request, and provide message as argument (?text=) in query string (here is api https://core.telegram.org/bots/api#sendmessage)

**Comment by gintrator** [comment]
Looks like GET and POST requests do the same thing, if I understand this section correctly?
>All queries to the Telegram Bot API must be served over HTTPS and need to be presented in this form: https://api.telegram.org/bot<token>/METHOD_NAME. Like this for example:
`https://api.telegram.org/bot123456:ABC-DEF1234ghIkl-zyx57W2v1u123ew11/getMe`
We support GET and POST HTTP methods. 

From https://core.telegram.org/bots/api#making-requests.

In any case, there's a valid use case to specify the HTTP method via a `method="GET"|"POST"|"PUT"` parameter to omhttp, this is a good feature to add. Seems most http writers for other logging agents provide it.

**Comment by mymtw** [comment]
> Looks like GET and POST requests do the same thing, if I understand this section correctly?

tested, yes, they are taking both types

> In any case, there's a valid use case to specify the HTTP method via a method="GET"|"POST"|"PUT" parameter to omhttp, this is a good feature to add. Seems most http writers for other logging agents provide it.

+1

**Comment by davidelang** [comment]
On Mon, 29 Apr 2019, Gabriel Intrator wrote:

> Looks like GET and POST requests do the same thing, if I understand this section correctly?

they are similar, but not the same. There are cases where they do very different 
things.

> In any case, there's a valid use case to specify the HTTP method via a 
> `method="GET"|"POST"|"PUT"` parameter to omhttp, this is a good feature to 
> add. Seems most http writers for other logging agents provide it.

I agree.

David Lang

**Comment by rgerhards** [comment]
looks solved
