### ISSUE TITLE
lmsig_gt & helpers: TLV file format changes

### ISSUE THREAD

**Issue by rgerhards** [rsyslog/rsyslog#363]
When the integration was done, the KSI spec was still in early development stages and now the TLV encoding in rsyslog is slightly different form the one in current KSI spec. This is not a bug as such, but would make future KSI integration troublesome, as there would be two deceptively similar encodings mixed in the same file. So we should adjust accordingly.

Note: **breaks tlv file format compatibility**

**Comment by alorbach** [comment]
Problem solved with different file extensions.
