### ISSUE TITLE
imjournal: double free error

### ISSUE THREAD

**Issue by jmbills** [rsyslog/rsyslog#3633]
### Expected behavior
No double free error in log

### Actual behavior
The error message 'free(): double free detected in tcache 2' is added to my log file and rsyslog stops logging.

### Steps to reproduce the behavior
I'm having trouble reproducing the "double free" message at the moment, but it happened when I was running a test that added to the log and rotated the journal (`journalctl --rotate`).  Rotating the journal still causes rsyslog to stop running, but I don't see the "double free" message in my testing while writing this.

### Environment
- rsyslog version: 8.1903.0
- platform: OpenBMC with Linux kernel 5.0.7

The error does not happen when I use the previous rsyslog release (8.1901.0).

**Comment by rgerhards** [comment]
@jvymazal might this be related to https://github.com/rsyslog/rsyslog/pull/3435?

**Comment by rgerhards** [comment]
or a glibc bug? https://bugzilla.redhat.com/show_bug.cgi?id=1652495

**Comment by jvymazal** [comment]
Yes, it was introduced by #3435, however was caught quickly after release and should be fixed in #3566 
(see https://github.com/rsyslog/rsyslog/pull/3566/files#diff-b1ea6478b8060f07cd30ecde78bfdc49L452 )

**Comment by rgerhards** [comment]
ah, I see. #3566 was in 8.1904.0 @jmbills you need to upgrade (or backport the patch to your version)
