### ISSUE TITLE
RFE: Mention external lookup table use on reload and restart

### ISSUE THREAD

**Issue by atc0005** [rsyslog/rsyslog#3639]
### Expected behavior

rsyslog mentions that it is referencing a lookup table on reload and restart.

### Actual behavior

rsyslog mentions external lookup table file(s) upon reload only.

### Steps to reproduce the behavior

Here is a reference to the lookup table being used when reloading rsyslog:

```
2019-04-29T11:34:41.842584-05:00 sawmill1 rsyslogd: [origin software="rsyslogd" swVersion="8.1904.0" x-pid="841" x-info="https://www.rsyslog.com"] rsyslogd was HUPed
2019-04-29T11:34:41.842837-05:00 sawmill1 rsyslogd: lookup table 'ip_hostname_mappings' reloaded from file '/etc/rsyslog/common/ip_hostname_mappings.json' [v8.1904.0 try https://www.rsyslog.com/e/0 ]
```

A useful enhancement (e.g., for troubleshooting purposes) would be to mention use of such files when reloading (as is already being done) *and* when restarting rsyslog (not currently being done).

### Environment
- rsyslog version: 8.1904.0
- platform: Ubuntu 16.04

**Comment by rgerhards** [comment]
well... I think it is absolutely clear that when you stop and start rsyslog it will load the lookup table on start. Do we **really** need to log a message each time we start?

**Comment by atc0005** [comment]
> Do we **really** need to log a message each time we start?

I don't think there is a *need* for this, but I believe it could be a useful enhancement.This would provide an indication (aside from the results of using the file) that the file was indeed read and that no issues were encountered. In other words, this would be a useful "checkbox" of sorts to use when troubleshooting to confirm that not having a mapping available for use by rsyslog is not due to a case of the file not being read.

**Comment by rgerhards** [comment]
@davidelang @mbiebl @Whissi @richm what do you think?

**Comment by davidelang** [comment]
logging on reload makes sense as you are changing the behavior (new file)

At startup, it's much less clear. The "Unix Way" is to say nothing when things are working, only log when something has gone wrong, so a failed load of the file needs to be logged. I'm far less confident that a successful load needs to be logged. If it is logged, it should be at a very log severity (debug)

I don't see that logging it hurts much, we are only talking about one line at startup.

If we do log such successful events at startup, are there other things we will need to log as well? (how far does this slippery slope go?)

so I would lean towards not logging at startup, but wouldn't mind if it did.

**Comment by davidelang** [comment]
If you start enabling debugging logs, I'm pretty sure that the reading of the file will show up there, as will any issues with doing a lookup

**Comment by rgerhards** [comment]
> If we do log such successful events at startup, are there other things we will need to log as well? (how far does this slippery slope go?)

I should have mentioned that. Along the same lines we should/could log module load. And opening of output file as part of the action. Success in connecting to remote system. IMHO they are all in the same class. We don't even mention file closure at HUP as this seemed to be too verbose.

**Comment by rgerhards** [comment]
plus: I added more diagnostic messages the past year or so. Idea is to help users detect issues. I got more than one complaint about verbosity and irritating users. I also do not want to add a ton of options to enable/disable various messages.

**Comment by Whissi** [comment]
I think @davidelang is right. Normal start don't need to mention such details. Would be the first software I am aware of which would show such information. If you want to see what's going on you start in debug mode or increase verbosity.

So in theory I would also remove the output from reload command in default mode. Should be enough to log that signal X was received and processed.

**Comment by atc0005** [comment]
Many good points here.

@rgerhards thanks for considering this request, but after reading the points against accepting it, I understand why this may not be worth implementing.

> So in theory I would also remove the output from reload command in default mode. Should be enough to log that signal X was received and processed.

As this GitHub issue indicates, I'm biased towards more feedback than less, but I would suggest keeping it as it seems a useful indicator that the `reloadOnHUP` setting has taken effect as intended. 

Reference:

```
lookup_table(
    name="ip_hostname_mappings"
    file="/etc/rsyslog/common/ip_hostname_mappings.json"
    reloadOnHUP="on"
)
```

**Comment by rgerhards** [comment]
let's keep the issue open for a moment - I think it may be useful to have a generic severity filter for internally-generated messages. That would be just one setting and still give a bit flexibility. Thinking about it...

**Comment by davidelang** [comment]
something between 'log only when something goes wrong' and the super-verbose 
debug logs would be useful to have.

**Comment by rgerhards** [comment]
> something between 'log only when something goes wrong' and the super-verbose debug logs would be useful to have.

well... we kind of have/had this. The reload message, e.g.  is logged via info severity. So in rsyslog.conf you can filter rsyslog messages on severity, just like any other. But with systemd, we now emit primarily to the journal, and this does not filter. So here the problem begins. Logging to journal is good, because finally folks begin to see the messages. I'll implement a global setting for a severity-based filter for internal messages, before submitted to journal. So it's not 100% of what rsyslog can do, but at least some way to customize.
