### ISSUE TITLE
Having trouble forwarding original source IP

### ISSUE THREAD

**Issue by travis5491811** [rsyslog/rsyslog#3643]
Hello, I'm having trouble forwarding original source IP.

### Expected behavior

Appending the following to the bottom of `/etc/rsyslog.conf` to forward the traffic unmodified (including origin IP) to port `1514`
```
*.* @@127.0.0.1:1514

# also tried
*.* @127.0.0.1:1514
```

### Actual behavior

The application listening on port '1514' always see's data as coming from `127.0.0.1` instead of it's real origin.

### Steps to reproduce the behavior
- Install rsyslog on `Ubuntu 18.04LTS Server` and enable for logging on port `514`
- Install graylog or some other logging tool and make it listen on port `1514`
- Test to make sure logs are being received in syslog.
- Now append `*.* @127.0.0.1:1514` to the bottom of `/etc/rsyslog.conf` and run `systemctl restart rsyslog.service` to make changes take affect.
- Notice the source ip of all data for `1514` is always localhost instead of the original source.

How do i forward the original source? What am i doing wrong? 
No luck using iptables and it really would be cleaner if my default logging tool (`rsyslog`) could forward the origin since it forwards everything else.

### Environment
```
$ rsyslogd -v
rsyslogd 8.32.0, compiled with:
	PLATFORM:				x86_64-pc-linux-gnu
	PLATFORM (lsb_release -d):		
	FEATURE_REGEXP:				Yes
	GSSAPI Kerberos 5 support:		Yes
	FEATURE_DEBUG (debug build, slow code):	No
	32bit Atomic operations supported:	Yes
	64bit Atomic operations supported:	Yes
	memory allocator:			system default
	Runtime Instrumentation (slow code):	No
	uuid support:				Yes
	systemd support:			Yes
	Number of Bits in RainerScript integers: 64

See http://www.rsyslog.com for more information.

$ hostnamectl
           Chassis: vm
    Virtualization: vmware
  Operating System: Ubuntu 18.04.2 LTS
            Kernel: Linux 4.15.0-48-generic
      Architecture: x86-64


$ cat /etc/rsyslog.conf
module(load="imuxsock") # provides support for local system logging
module(load="imklog" permitnonkernelfacility="on")

$ActionFileDefaultTemplate RSYSLOG_TraditionalFileFormat

# Filter duplicated messages
$RepeatedMsgReduction on

#
# Set the default permissions for all log files.
#
$FileOwner syslog
$FileGroup adm
$FileCreateMode 0640
$DirCreateMode 0755
$Umask 0022
$PrivDropToUser syslog
$PrivDropToGroup syslog

#
# Where to place spool and state files
#
$WorkDirectory /var/spool/rsyslog

#
# Include all config files in /etc/rsyslog.d/
#
$IncludeConfig /etc/rsyslog.d/*.conf

# The following must be enabled to accept msg on 514 by rsyslogd
# provides UDP syslog reception
module(load="imudp")
input(type="imudp" port="514")
# provides TCP syslog reception
module(load="imtcp")
input(type="imtcp" port="514")
# Tell rsyslogd to forward logs to port 1514 which inputs configured in graylog are listening on, this eliminates the need to modify iptables
*.* @127.0.0.1:1514
```

**Comment by davidelang** [comment]
This is because the app receiving the logs on port 1514 is ignoring the hostname 
in the message and instead only paying attention to what IP address it received 
the log from.

This is what the omudpspoof module was created to deal with. It doesn't have 
nearly the performanceof regular UDP messages, but it lets you deal with broken 
receivers like this.

David Lang

**Comment by travis5491811** [comment]
> This is because the app receiving the logs on port 1514 is ignoring the hostname
> in the message and instead only paying attention to what IP address it received
> the log from.

Hello @davidelang the app on `1514` is recording the correct `hostname` from all sources. The only thing i can see that it's not receiving correctly is the original source ip address. And just to be sure it's not the app (graylog in this case) i've tested sending logs directly to `1514` and it has no problems recognizing both the correct source `IP` and `hostname`. The issue is only when logs are forwarded via `*.* @127.0.0.1:1514`.

> This is what the omudpspoof module was created to deal with. It doesn't have
> nearly the performanceof regular UDP messages, but it lets you deal with broken
> receivers like this.

I'm not familiar with `omudpspoof`. [This link ](https://www.rsyslog.com/doc/v8-stable/configuration/modules/omudpspoof.html) has some info but it assumes the user is trying to spoof a single address. I need to forward the original address so that the app on `1514` gets the real source address that `rsyslog` got instead of the address of the machine that forwarded the message (`localhost` in this case). How do i do this?

**Comment by davidelang** [comment]
On Wed, 1 May 2019, travis5491811 wrote:

>> This is because the app receiving the logs on port 1514 is ignoring the hostname
>> in the message and instead only paying attention to what IP address it received
>> the log from.
>
> Hello @davidelang the app on `1514` is recording the correct `hostname` from 
> all sources. The only thing i can see that it's not receiving correctly is the 
> original source ip address. And just to be sure it's not the app (graylog in 
> this case) i've tested sending logs directly to `1514` and it has no problems 
> recognizing both the correct source `IP` and `hostname`. The issue is only 
> when logs are forwarded via `*.* @127.0.0.1:1514`.

When you forward a message, the source IP of the connection is the relay box, 
that's the way normal network communications work. The packet is generated by 
rsyslog on the relay box, so when it arrives at the destination, the source IP 
on the packet is the relay box.

>> This is what the omudpspoof module was created to deal with. It doesn't have
>> nearly the performanceof regular UDP messages, but it lets you deal with broken
>> receivers like this.
>
> I'm not familiar with `omudpspoof`. [This link 
> ](https://www.rsyslog.com/doc/v8-stable/configuration/modules/omudpspoof.html) 
> has some info but it assumes the user is trying to spoof a single address. I 
> need to forward the original address so that the app on `1514` gets the real 
> source address that `rsyslog` got instead of the address of the machine that 
> forwarded the message (`localhost` in this case). How do i do this?

you set a template for the source template to be fromhost-ip (which is the 
default according to that page)

in a multi-tier relay situation, you can either spoof at each relay, or you can 
embed the real source IP in the message as metadata on the first hop, and 
extract it to use in a template at the final hop.

David Lang

**Comment by travis5491811** [comment]
@davidelang thanks. i will try the `omudpspoof` this week and post back with a working config if i figure it out. I need to learn/understand more about how templates work before i change `/etc/rsyslog.conf`. I'm not sure on how the changes will affect the current logs or even the correct place/config to write. Especially after reading the following which to me suggest my change might not change anything.

> ...build-in default template RSYSLOG_omudpspoofDfltSourceTpl is used. This template is defined as follows: $template RSYSLOG_omudpspoofDfltSourceTpl,”%fromhost-ip%” So in essence, the default template spoofs the address of the system the message was received from

**Comment by davidelang** [comment]
On Wed, 1 May 2019, travis5491811 wrote:

> @davidelang thanks. i will try the `omudpspoof` this week and post back with a 
> working config if i figure it out. I need to learn/understand more about how 
> templates work before i change `/etc/rsyslog.conf`.

> I'm not sure on how the changes will affect the current logs or even the 
> correct place/config to write.

each action is completely independent, so changes to one or to templates have no 
effect on the other actions (as long as those actions don't also use the 
template you change)

> Especially after reading the following which to me suggest my change 
> might not change anything.

>> ...build-in default template RSYSLOG_omudpspoofDfltSourceTpl is used. This 
>> template is defined as follows: $template 
>> RSYSLOG_omudpspoofDfltSourceTpl,”%fromhost-ip%” So in essence, the default 
>> template spoofs the address of the system the message was received from

the defaults for omudpspoof probably do what you want.

David Lang

**Comment by travis5491811** [comment]
In `/etc/rsyslog.conf` I replaced
```
*.* @127.0.0.1:1514
```

with 

```
module(load="omudpspoof") # UDP spoofing output module
Template (
  name="spoofaddr"
  type="string"
  string="%fromhost-ip%"
)
Action (
  type="omudpspoof"
  target="127.0.0.1"
  port="1514"
  sourcetemplate="spoofaddr"
```

But i get the error `module name 'omudpspoof' is unknown [v8.32.0 try http://www.rsyslog.com/e/2209 ]`. The URL comments: `Module (config name) is unknown. This is a stub entry: If you have questions please post a comment or visit the github issue tracker`

The rest of my config is the same as original post. Any idea what is wrong?

**Comment by rgerhards** [comment]
> Any idea what is wrong?

it's a module that is very infrequently needed, thus it is not in the rsyslog core package. You need to install it. Usually there should be a package named along the lines of `rsyslog-omudpspoof`.

**Comment by travis5491811** [comment]
These are the options that show up for `apt install` with `rsyslog` autocomplete
```
rsyslog                rsyslog-doc            rsyslog-gnutls         rsyslog-hiredis        rsyslog-mongodb        rsyslog-pgsql          
rsyslog-czmq           rsyslog-elasticsearch  rsyslog-gssapi         rsyslog-kafka          rsyslog-mysql          rsyslog-relp
```

**Comment by rgerhards** [comment]
I have update the error description (thx btw for mentioning the issue!). It should now have all the info: https://www.rsyslog.com/rsyslog-error-2209/

**Comment by travis5491811** [comment]
thanks for the update
