### ISSUE TITLE
orphaned imfile-state file after log deletion

### ISSUE THREAD

**Issue by lhycz** [rsyslog/rsyslog#3645]
### Expected behavior
After deleting watched logfile, the associated persisted state file should be deleted as well.

### Actual behavior
Statefile cleanup works when logfile is small, and statefile filename is in format `imfile-state:<inode>`. When the logfile is big enough and the statefile changes to `imfile-state:<inode>:<hash>`, then it is not deleted on log deletion.
From debug log it seems it still tries to unlink `imfile-state:<inode>` instead.

```
7287.895010525:main Q:Reg/w0  : wti.c: main Q:Reg/w0: worker IDLE, waiting for work.
7304.876839128:imfile.c       : imfile.c: INOTIFY event: watch IN_DELETE
7304.876858795:imfile.c       : imfile.c: in_processEvent process Event 200 for test.log
7304.876866454:imfile.c       : imfile.c: in_processEvent process Event 200 is_file 0, act->name '/var/log'
7304.876872960:imfile.c       : imfile.c: node walk: 0x556ea8365540 edges:
7304.876878959:imfile.c       : imfile.c: node walk: child 0x556ea8365610 'test.log'
7304.876885265:imfile.c       : imfile.c: poll_tree: chld 0x556ea83655a0, name 'test.log', path: /var/log/test.log
7304.876891207:imfile.c       : imfile.c: detect_updates checking active obj '/var/log/test.log'
7304.876900339:imfile.c       : imfile.c: object gone away, unlinking: '/var/log/test.log'
7304.876906262:imfile.c       : imfile.c: act_obj_unlink 0x7f800c000c60: /var/log/test.log, pStrm 0x7f800c002df0
7304.876913514:imfile.c       : imfile.c: act_obj_destroy: act 0x7f800c000c60 '/var/log/test.log' (source '---'), wd 4, pStrm 0x7f800c002df0, is_deleted 1, in_move 0
7304.876920077:imfile.c       : imfile.c: pollFileReal enter, act 0x7f800c000c60, pStrm 0x7f800c002df0, name '/var/log/test.log'
7304.876925609:imfile.c       : imfile.c: pollFileReal enter, edge 0x556ea83655a0
7304.876930899:imfile.c       : imfile.c: pollFileReal enter, edge->instarr 0x556ea8365650
7304.876938901:imfile.c       : stream.c: checkTruncation, file /var/log/test.log, iBufPtrMax 705
7304.876945173:imfile.c       : stream.c: checkTruncation, currpos 4801
7304.876953583:imfile.c       : stream.c: checkTruncation, file /var/log/test.log last buffer unchanged
7304.876959928:imfile.c       : strm 0x7f800c002df0: stream.c: file 13 read 0 bytes
7304.876965675:imfile.c       : strm 0x7f800c002df0: stream.c: file '/var/log/test.log' (13) EOF, rotationCheck 0
7304.876973240:imfile.c       : imfile.c: getStateFileName for '/var/log/test.log'
7304.876987415:imfile.c       : imfile.c: getStateFileName:  state file name now is imfile-state:10556517
7304.876997539:imfile.c       : imfile.c: getStateFileName for '/var/log/test.log'
7304.877003940:imfile.c       : imfile.c: getStateFileName:  state file name now is imfile-state:10556517
7304.877014084:imfile.c       : imfile.c: persisting state for '/var/log/test.log', state file '/var/spool/rsyslog/imfile-state:10556517:d8bffdcae7c306d3'
7304.877140979:imfile.c       : strm 0x7f800c002df0: stream.c: file 13(/var/log/test.log) closing, bDeleteOnClose 0
7304.877180362:imfile.c       : imfile.c: act_obj_destroy: deleting state file /var/spool/rsyslog/imfile-state:10556517
7304.877191855:imfile.c       : imfile.c: wd 4 deleted, was idx 3
7304.877200519:imfile.c       : imfile.c: poll_tree: glob returned 3
7304.877206243:imfile.c       : imfile.c: node walk: 0x556ea8365610 edges:
7304.877212815:imfile.c       : imfile.c: INOTIFY event: watch was REMOVED
7304.877217847:imfile.c       : imfile.c: imfile: got IN_IGNORED event
7311.702282264:imfile.c       : imfile.c: INOTIFY event: file was CREATED: rsyslog.debug-bad
7311.702379593:imfile.c       : imfile.c: in_processEvent process Event 100 for rsyslog.debug-bad
7311.702398951:imfile.c       : imfile.c: in_processEvent process Event 100 is_file 0, act->name '/var/log'
7311.702406473:imfile.c       : imfile.c: node walk: 0x556ea8365540 edges:
7311.702412577:imfile.c       : imfile.c: node walk: child 0x556ea8365610 'test.log'
7311.702419275:imfile.c       : imfile.c: poll_tree: chld 0x556ea83655a0, name 'test.log', path: /var/log/test.log
7311.702429427:imfile.c       : imfile.c: poll_tree: glob returned 3
7311.702435519:imfile.c       : imfile.c: node walk: 0x556ea8365610 edges:
```
and from the log and brief look into code it seems that at this point act->file_id should still have the hash available, as seen in line
`persisting state for '/var/log/test.log', state file '/var/spool/rsyslog/imfile-state:10556517:d8bffdcae7c306d3'`
right before the deletion attempt

### Environment
- rsyslog version: 8.1904.0
- platform: Amazon Linux AMI release 2018.03(rhel based distro)

**Comment by lhycz** [comment]
[patch-issue-3645.txt](https://github.com/rsyslog/rsyslog/files/3198136/patch-issue-3645.txt)
Hi, this change seems to fix this issue for me.
The patch contains quick fix in imfile.c and some tests, without the patch only one of them passes.
But I don't see deep enough into the codebase, so hopefully it doesn't break something else.

**Comment by mdreed234** [comment]
I don't know if it's related or not, but I've got 24316 imfile-state files in /var/lib/rsyslog.  It appears there are multiple imfile-state files for the same actual file.  I'm happy to submit a new bug if that's the right course of action.

For example:
imfile-state:69572949:{ "filename": "\/var\/log\/xxx\/mesos-slave.log", "prev_was_nl": 0, "curr_offs": 540135, "strt_offs": 540135 }
imfile-state:69637441:{ "filename": "\/var\/log\/xxx\/mesos-slave.log", "prev_was_nl": 0, "curr_offs": 40761302, "strt_offs": 40761302 }
imfile-state:69782991:{ "filename": "\/var\/log\/xxx\/mesos-slave.log", "prev_was_nl": 0, "curr_offs": 255505, "strt_offs": 255505 }
imfile-state:69940735:{ "filename": "\/var\/log\/xxx\/mesos-slave.log", "prev_was_nl": 0, "curr_offs": 90094029, "strt_offs": 90094029 }
imfile-state:70778:3efef128d38b56fa:{ "filename": "\/var\/log\/xxx\/mesos-slave.log", "prev_was_nl": 0, "curr_offs": 38477, "strt_offs": 38477 }
imfile-state:70778:c4fe121a5571e46d:{ "filename": "\/var\/log\/xxx\/mesos-slave.log", "prev_was_nl": 0, "curr_offs": 38007, "strt_offs": 38007 }
imfile-state:70778:dbac4baad6d972f3:{ "filename": "\/var\/log\/xxx\/mesos-slave.log", "prev_was_nl": 0, "curr_offs": 38288, "strt_offs": 38288 }
imfile-state:70802:9caa00c3e6f7c5f0:{ "filename": "\/var\/log\/xxx\/mesos-slave.log", "prev_was_nl": 0, "curr_offs": 38250, "strt_offs": 38250 }
...
imfile-state:763:{ "filename": "\/var\/log\/xxx\/mesos-slave.log", "prev_was_nl": 0, "curr_offs": 5030, "strt_offs": 5030 }
imfile-state:763:a966fb1510f39a64:{ "filename": "\/var\/log\/xxx\/mesos-slave.log", "prev_was_nl": 0, "curr_offs": 76012, "strt_offs": 76012 }
imfile-state:763:d43b8dc32c829ec6:{ "filename": "\/var\/log\/xxx\/mesos-slave.log", "prev_was_nl": 0, "curr_offs": 26098, "strt_offs": 26098 }
imfile-state:763:fc53f955dd23f3f2:{ "filename": "\/var\/log\/xxx\/mesos-slave.log", "prev_was_nl": 0, "curr_offs": 95290, "strt_offs": 95290 }

It seems that there should be some rsyslog clean up to prevent this.  After all, there should only be a single instance of the file.  The current inode for the file is 763. I'm not in a position to try the patch.  At least not today... 

I'm running rsyslogd version 8.39.0.

**Comment by spiritmonger** [comment]
i see this too... version v8.1904

**Comment by lhycz** [comment]
Yes, this seems related - I had the same problem and while debugging found this issue and issue #3646 :)

**Comment by mdreed234** [comment]
I built the supplied patch-issue-3465.txt patch into v8.1907 and tested.  (I did not patch anything but imfile.c.)  System is still accumulating imfile-state files for the associated log files. This appears to happen when kafka rotates its logs.

/var/log/xxx/yyy/kafka/controller.log            /var/lib/rsyslog/imfile-state:100:714e516edad39881
/var/log/xxx/yyy/kafka/controller.log            /var/lib/rsyslog/imfile-state:92:1f791c690fc4050d
/var/log/xxx/yyy/kafka/controller.log            /var/lib/rsyslog/imfile-state:98:7f6790e7d1a9144e
/var/log/xxx/yyy/kafka/server.log                /var/lib/rsyslog/imfile-state:97
/var/log/xxx/yyy/kafka/server.log                /var/lib/rsyslog/imfile-state:99

Does anyone have any insight as to whether the left over imfile-state files cause any operational issues with rsyslog?  Does rsyslog identify the correct state file to use when it restarts?

I'm happy to help debug my flavor of this issue, but I'll need guidance.

**Comment by rgerhards** [comment]
I need to check this in-depth. We have a requirement by quite a number of users to be able to detect that a file 

* moved outside a monitored location for 
* keept outside for a while
* moved back to the monitored location

is re-detected and not treated as a new file. So we need to keep state files for "quite a while". I am right now not sure if we have a cleanup process or if what you see is an issue in current code.

**Comment by mdreed234** [comment]
My test system is idle.  After16 hours there are roughly 16 "extra" imfile-state files.  The files being rotated are created by kafka logging.  Kafka is idle.  The content of the log files doesn't generally get changed prior to its next hourly rotation.  Let me know if you need anything or want to try something.

Here's the content of the 8 imfile-state files associated with the "server.log" log file.

{ "filename": "\/var\/log\/xxx\/yyy\/kafka\/server.log", "prev_was_nl": 0, "curr_offs": 984, "strt_offs": 984 }
{ "filename": "\/var\/log\/xxx\/yyy\/kafka\/server.log", "prev_was_nl": 0, "curr_offs": 984, "strt_offs": 984 }
{ "filename": "\/var\/log\/xxx\/yyy\/kafka\/server.log", "prev_was_nl": 0, "curr_offs": 984, "strt_offs": 984 }
{ "filename": "\/var\/log\/xxx\/yyy\/kafka\/server.log", "prev_was_nl": 0, "curr_offs": 984, "strt_offs": 984 }
{ "filename": "\/var\/log\/xxx\/yyy\/kafka\/server.log", "prev_was_nl": 0, "curr_offs": 984, "strt_offs": 984 }
{ "filename": "\/var\/log\/xxx\/yyy\/kafka\/server.log", "prev_was_nl": 0, "curr_offs": 984, "strt_offs": 984 }
{ "filename": "\/var\/log\/xxx\/yyy\/kafka\/server.log", "prev_was_nl": 0, "curr_offs": 984, "strt_offs": 984 }

and the eight associated imfile-state file names.

/var/log/xxx/yyy/kafka/server.log                /var/lib/rsyslog/imfile-state:111
/var/log/xxx/yyy/kafka/server.log                /var/lib/rsyslog/imfile-state:115
/var/log/xxx/yyy/kafka/server.log                /var/lib/rsyslog/imfile-state:122
/var/log/xxx/yyy/kafka/server.log                /var/lib/rsyslog/imfile-state:124
/var/log/xxx/yyy/kafka/server.log                /var/lib/rsyslog/imfile-state:126
/var/log/xxx/yyy/kafka/server.log                /var/lib/rsyslog/imfile-state:97
/var/log/xxx/yyy/kafka/server.log                /var/lib/rsyslog/imfile-state:99

(If you haven't already guessed, xxx/yyy is not the actual path to the log.  The path is changed to protect the innocent.)

Perhaps this is a configuration issue that can be worked around?

Just some speculation:  rsyslogd hasn't been restarted since removing all imfile-state files and restarting.  Perhaps kafka is doing a "rename / recreate" type of log rotation and these state files correspond to currently open logs with the specified inode?  Then, when a restart of rsyslogd eventually happens, there are leftover imfile-state files which no longer correspond to the current log.

The rsyslog rule monitoring this has "reopenontruncate" set to "on" and "persiststateinterval" set to "200".  The log file is being selected by a wildcard  /var/log/xxx/yyy/*/*.log rule.  "reopenontruncate" is set to detect other applications that do a copy/truncate type of rotation.

If considered appropriate, I can likely hardcode separate rules for kafka and the "copy/truncate" applications so that "reopenontruncate" is only set for those applications that rotate via "copy/truncate" mechanism.  Obviously, a "generic" imfile selector is more convenient as new logs can be added with less likelihood of having to change rsyslogd configuration.

**Comment by spiritmonger** [comment]
imfile log:
```
input(type="imfile"
  File="/var/log/tomcat8/test-app.log"
  Tag="test-app:"
  ReadMode="2"
  Facility="local5"
  PersistStateInterval="128"
  trimLineOverBytes="129024"
  discardTruncatedMsg="on"
  msgDiscardingError="off"
  deleteStateOnFileDelete="on"
  # reopenOnTruncate="on" # It still is highly recommended NOT to turn on "reopenOnTruncate" in imfile (release notes v8.39)
)
```

>>> inotify watching specify file:
```
> inotifywait -m -r /var/log/tomcat8/test-app.log
.
.
.
.
/var/log/tomcat8/test-app.log MODIFY
/var/log/tomcat8/test-app.log ACCESS
/var/log/tomcat8/test-app.log MODIFY
/var/log/tomcat8/test-app.log ACCESS
/var/log/tomcat8/test-app.log CLOSE_WRITE,CLOSE
/var/log/tomcat8/test-app.log MOVE_SELF
/var/log/tomcat8/test-app.log OPEN
/var/log/tomcat8/test-app.log ACCESS
/var/log/tomcat8/test-app.log CLOSE_NOWRITE,CLOSE
/var/log/tomcat8/test-app.log ATTRIB
/var/log/tomcat8/test-app.log ACCESS
/var/log/tomcat8/test-app.log CLOSE_NOWRITE,CLOSE
/var/log/tomcat8/test-app.log DELETE_SELF
```
>>> no-more-inotifywait-events

>>> inotify watching directory:
```
> inotifywait -m -r /var/log/tomcat8/

.
.
.
/var/log/tomcat8/ MODIFY test-app.log
/var/log/tomcat8/ ACCESS test-app.log
/var/log/tomcat8/ MODIFY test-app.log
/var/log/tomcat8/ ACCESS test-app.log
/var/log/tomcat8/ MODIFY test-app.log
/var/log/tomcat8/ ACCESS test-app.log
/var/log/tomcat8/ MODIFY test-app.log
/var/log/tomcat8/ MODIFY test-app.log
/var/log/tomcat8/ ACCESS test-app.log
/var/log/tomcat8/ CLOSE_WRITE,CLOSE test-app.log
/var/log/tomcat8/ MOVED_FROM test-app.log
/var/log/tomcat8/ MOVED_TO test-app.log.2019-07-30-12-39.021897639245331.tmp
/var/log/tomcat8/ CLOSE_NOWRITE,CLOSE test-app.log.2019-07-30-12-39.021897639245331.tmp
/var/log/tomcat8/ OPEN test-app.log.2019-07-30-12-39.021897639245331.tmp
/var/log/tomcat8/ CREATE test-app.log.2019-07-30-12-39.0.gz
/var/log/tomcat8/ OPEN test-app.log.2019-07-30-12-39.0.gz
/var/log/tomcat8/ MODIFY test-app.log.2019-07-30-12-39.0.gz
/var/log/tomcat8/ ACCESS test-app.log.2019-07-30-12-39.021897639245331.tmp
/var/log/tomcat8/ ACCESS test-app.log.2019-07-30-12-39.021897639245331.tmp
/var/log/tomcat8/ CLOSE_NOWRITE,CLOSE test-app.log.2019-07-30-12-39.021897639245331.tmp
/var/log/tomcat8/ MODIFY test-app.log.2019-07-30-12-39.0.gz
/var/log/tomcat8/ CLOSE_WRITE,CLOSE test-app.log.2019-07-30-12-39.0.gz
/var/log/tomcat8/ DELETE test-app.log.2019-07-30-12-39.021897639245331.tmp
/var/log/tomcat8/ CREATE test-app.log
/var/log/tomcat8/ OPEN test-app.log
/var/log/tomcat8/ MODIFY test-app.log
/var/log/tomcat8/ DELETE test-app.log.2019-07-30-12-36.0.gz
/var/log/tomcat8/ OPEN test-app.log
/var/log/tomcat8/ ACCESS test-app.log
/var/log/tomcat8/ OPEN test-app.log
/var/log/tomcat8/ ACCESS test-app.log
/var/log/tomcat8/ MODIFY test-app.log
/var/log/tomcat8/ ACCESS test-app.log
```

>>> every rotate created new imfile-state file and sometimes is lost last offset, and i lost log messages:
```
imfile-state:269110:d70c35074d06b65d
{ "filename": "\/var\/log\/tomcat8\/test-app.log", "prev_was_nl": 1, "curr_offs": 33626, "strt_offs": 33072, "prev_line_segment": "test-app: 2019-07-30T12:36:58,991 [http-nio-8080-exec-227] INFO  [] message }
imfile-state:266545:9e62d6b95a3bb9ac
{ "filename": "\/var\/log\/tomcat8\/test-app.log", "prev_was_nl": 1, "curr_offs": 33626, "strt_offs": 33198, "prev_line_segment": "test-app: 2019-07-30T12:37:59,012 [http-nio-8080-exec-131] INFO  [] message }
imfile-state:266545:6ebbece543f85c47
{ "filename": "\/var\/log\/tomcat8\/test-app.log", "prev_was_nl": 1, "curr_offs": 33623, "strt_offs": 33195, "prev_line_segment": "test-app: 2019-07-30T12:38:59,078 [http-nio-8080-exec-226] INFO  [] message }
imfile-state:269125:3e49240d83626d41
{ "filename": "\/var\/log\/tomcat8\/test-app.log", "prev_was_nl": 1, "curr_offs": 33620, "strt_offs": 33192, "prev_line_segment": "test-app: 2019-07-30T12:39:59,149 [http-nio-8080-exec-136] INFO  [] message }
imfile-state:269125:44a419314ce088fb
{ "filename": "\/var\/log\/tomcat8\/test-app.log", "prev_was_nl": 1, "curr_offs": 33623, "strt_offs": 33195, "prev_line_segment": "test-app: 2019-07-30T12:40:59,191 [http-nio-8080-exec-254] INFO  [] message }
imfile-state:269110:d2fca33f96d263bb
{ "filename": "\/var\/log\/tomcat8\/test-app.log", "prev_was_nl": 1, "curr_offs": 33626, "strt_offs": 33198, "prev_line_segment": "test-app: 2019-07-30T12:41:59,260 [http-nio-8080-exec-235] INFO  [] message }
imfile-state:269125:95f0cc3f8578664e
{ "filename": "\/var\/log\/tomcat8\/test-app.log", "prev_was_nl": 1, "curr_offs": 33626, "strt_offs": 33198, "prev_line_segment": "test-app: 2019-07-30T12:42:59,324 [http-nio-8080-exec-201] INFO  [] message }
imfile-state:269110:97b669695fa49b2f
{ "filename": "\/var\/log\/tomcat8\/test-app.log", "prev_was_nl": 1, "curr_offs": 33626, "strt_offs": 33198, "prev_line_segment": "test-app: 2019-07-30T12:43:59,387 [http-nio-8080-exec-159] INFO  [] message }
```

**Comment by rgerhards** [comment]
> Perhaps this is a configuration issue that can be worked around?

The key point to understand is that rsyslog needs to keep old state files, even for quite a while. This is because we have the requirement that old log files are moved back to the monitored location.

That said, I still need to look if anything is wrong in detail.

**Comment by davidelang** [comment]
rsyslog tries really hard to provide mechanisms and not dictate policy (leaving 
that up to the sysadmin)

In this case, due to the desire from many people to not re-read files if they 
get moved away and come back (and/or get renamed), we don't remove state files 
automatically.

it's probably a useful enahancement request to be able to set a flag to remove 
the state files when the files can no longer be read, but the current behavior 
is notabug :-)

David Lang

**Comment by davidelang** [comment]
enhancement request https://github.com/rsyslog/rsyslog/issues/3777 submitted

**Comment by davidelang** [comment]
hmm, having each rotation create a new state file because the file has a new inode does seem like an issue.

**Comment by lhycz** [comment]
Hi mdreed234,
just a quick response to this message
> My test system is idle. After16 hours there are roughly 16 "extra" imfile-state files. The files being rotated are created by kafka logging. Kafka is idle. The content of the log files doesn't generally get changed prior to its next hourly rotation. Let me know if you need anything or want to try something.
> 
> Here's the content of the 8 imfile-state files associated with the "server.log" log file.
> 
> { "filename": "/var/log/xxx/yyy/kafka/server.log", "prev_was_nl": 0, "curr_offs": 984, "strt_offs": 984 }
> { "filename": "/var/log/xxx/yyy/kafka/server.log", "prev_was_nl": 0, "curr_offs": 984, "strt_offs": 984 }
> { "filename": "/var/log/xxx/yyy/kafka/server.log", "prev_was_nl": 0, "curr_offs": 984, "strt_offs": 984 }
> { "filename": "/var/log/xxx/yyy/kafka/server.log", "prev_was_nl": 0, "curr_offs": 984, "strt_offs": 984 }
> { "filename": "/var/log/xxx/yyy/kafka/server.log", "prev_was_nl": 0, "curr_offs": 984, "strt_offs": 984 }
> { "filename": "/var/log/xxx/yyy/kafka/server.log", "prev_was_nl": 0, "curr_offs": 984, "strt_offs": 984 }
> { "filename": "/var/log/xxx/yyy/kafka/server.log", "prev_was_nl": 0, "curr_offs": 984, "strt_offs": 984 }
> 
> and the eight associated imfile-state file names.
> 
> /var/log/xxx/yyy/kafka/server.log /var/lib/rsyslog/imfile-state:111
> /var/log/xxx/yyy/kafka/server.log /var/lib/rsyslog/imfile-state:115
> /var/log/xxx/yyy/kafka/server.log /var/lib/rsyslog/imfile-state:122
> /var/log/xxx/yyy/kafka/server.log /var/lib/rsyslog/imfile-state:124
> /var/log/xxx/yyy/kafka/server.log /var/lib/rsyslog/imfile-state:126
> /var/log/xxx/yyy/kafka/server.log /var/lib/rsyslog/imfile-state:97
> /var/log/xxx/yyy/kafka/server.log /var/lib/rsyslog/imfile-state:99
> 

this is actualy exactly the state I would expect even after applying the patch :)
the patch was supposed to take care of orphaned files like  /var/log/xxx/yyy/kafka/server.log /var/lib/rsyslog/imfile-state:99:934cbdf43dae... (or some other hash)

these orphaned imfiles with only "imfile-state:<inode>" in their name is a different bug - #3646 (but it leaves old imfiles behind as well)

maybe I should have reported both bugs in one issue, this split into two issues is a bit confusing :)

**Comment by rgerhards** [comment]
> hmm, having each rotation create a new state file because the file has a new inode does seem like an issue.

This is one reason why I say I need to have a closer look. While the behavior sounds OK in general, there may be some quirks.

**Comment by rgerhards** [comment]
A known issue we cannot work around is rotation of very small files. We add a hash (the "file ID") once the file has sufficient size. I think it is 512 bytes. This ID uniquely identifies the file. But if the file is smaller, we have only the inode to differentiate. That's better than nothing, but not great. Thus we cannot delete these files. The inode-only state files should be replaced by the inode+file-id state files, which is where #3646 comes into the play.

**Comment by rgerhards** [comment]
@jvymazal I think this should be fixed now - do you agree?

**Comment by rgerhards** [comment]
potentially fixed by https://github.com/rsyslog/rsyslog/pull/3990

**Comment by rgerhards** [comment]
I think it is fixed now. If not, let me know and I'll re-open.

**Comment by jvymazal** [comment]
@rgerhards agree, currently we should be good for any reasonable use cases.
