### ISSUE TITLE
Why not change allocator to jemalloc?

### ISSUE THREAD

**Issue by snaix** [rsyslog/rsyslog#3647]
Hi rsyslog
Recently, I'm using rsyslog in a very busy system(about 2w logs per seconds per instance with complex rules).
Rsyslog is a significant heap memory user, so it will call malloc/free frequently.
Usually I can see that malloc/free takes up a lot of CPU time.  In my test, it can even trigger bugs in Linux([major performance problem in glibc malloc _int_free](https://partner-bugzilla.redhat.com/show_bug.cgi?id=1255506)). 
After replacing it with jemalloc, there is a significant performance improvement.(An imprecise estimate, about 3-5x improvement)

Jemalloc is a widely used and well tested library, I've seen jemalloc in the rsyslog compile configure, but it isn't default. 
So why? Is it possible to be default?

**Comment by rgerhards** [comment]
We used it for a couple of months but had often enough segfaults. Not using it solved that. You are free to use but then need to build yourself.
