### ISSUE TITLE
imfile-state with inode

### ISSUE THREAD

**Issue by tru-cstavares** [rsyslog/rsyslog#3665]
### Expected behavior
The state filename must contains the path to the input file, not it's inode or a hash.

Example:
> $ cd /var/lib/rsyslog
> -rw------- 1 root root      231 Mar  7 15:18 imfile-state:-var-log-docker-mycontainer.log

### Actual behavior
rsyslog started creating state file with inode instead of input file name.

Example:
> $ cd /var/lib/rsyslog
> -rw------- 1 root root      503 Apr  5 09:09 imfile-state:8448952
> -rw------- 1 root root      422 Apr  5 09:09 imfile-state:8447346

### Steps to reproduce the behavior
NA

### Environment
- rsyslog version: 8.24.0-34.el7
- platform: CentOS Linux release 7.6.1810 (Core)
- for configuration questions/issues, include rsyslog.conf and included config files

My rsyslog config is two files as follows:

**10-docker.conf:**
> $ cat /etc/rsyslog.d/10-docker.conf
> $template myContainerLogs,"/var/log/docker/mycontainer.log"
> if ($inputname == 'imudp' and $syslogtag contains 'mycontainer') then ?myContainerLogs
> & stop

**15-remote-logging.conf**
> $ cat /etc/rsyslog.d/15-remote-logging.conf
> module(load="imfile" PollingInterval="10")
> 
> ruleset (name="fwd2graylog"){
>   action(type="omfwd"
>   Target=<my_destination_host>
>   Port="514"
>   Protocol="tcp")
> }
> 
> input(type="imfile"
>   File="/var/log/docker/mycontainer.log"
>   Tag="mycontainer"
>   PersistStateInterval="10"
>   Facility="local4"
>   startmsg.regex="^[a-zA-Z]{3}\\s+[[:digit:]]{1,2}.*[[:digit:]]{4}-[[:digit:]]{1,2}-[[:digit:]]{1,2}"
>   Ruleset="fwd2graylog"
> )

**Comment by rgerhards** [comment]
can you double check that you actually use 8.24? It sounds like a much more current build. This is expected behavior.

**Comment by tru-cstavares** [comment]
Hi @rgerhards,

Thanks for replying. Yes, rsyslog version is correct.

> [user@hostname ~]$ rsyslogd -v
> rsyslogd 8.24.0-34.el7, compiled with:
> 	PLATFORM:				x86_64-redhat-linux-gnu
> 	PLATFORM (lsb_release -d):
> 	FEATURE_REGEXP:				Yes
> 	GSSAPI Kerberos 5 support:		Yes
> 	FEATURE_DEBUG (debug build, slow code):	No
> 	32bit Atomic operations supported:	Yes
> 	64bit Atomic operations supported:	Yes
> 	memory allocator:			system default
> 	Runtime Instrumentation (slow code):	No
> 	uuid support:				Yes
> 	Number of Bits in RainerScript integers: 64
> 
> See http://www.rsyslog.com for more information.
> [user@hostname ~]$

The strange is starting from 5 of April rsyslog started to right imfile-state with inode instead of path to input file. Here a printout of dir:

> [user@hostname ~]$ sudo ls -lrt /var/lib/rsyslog/
> -rw------- 1 root root      231 Mar  7 15:18 imfile-state:-var-log-docker-mycontainer1.log
> -rw------- 1 root root      258 Mar  7 15:18 imfile-state:-var-log-docker-mycontainer2.log
> -rw------- 1 root root      503 Apr  5 09:09 imfile-state:8448952
> -rw------- 1 root root      422 Apr  5 09:09 imfile-state:8447346
> [user@hostname ~]$

Which conditions makes rsyslog to use inode on filename?

BR

**Comment by rgerhards** [comment]
> Which conditions makes rsyslog to use inode on filename?

using a current version and file too small to generate a hash. There actually is doc on this, but I noticed that the doc gen process seems stuck, so the doc on site seems to be outdated. I am checking this. Will post more when current is online.

**Comment by rgerhards** [comment]
ah, the doc fix was appliead post 8.1904. Check the fixed doc in current master branch: https://www.rsyslog.com/doc/master/configuration/modules/imfile.html

**Comment by rgerhards** [comment]
@tru-cstavares Whatever happened on the system, the state file name are a clear indication this is not a plain 8.24.0. Did you mix some packages?

**Comment by tru-cstavares** [comment]
Seems that lastest version is instaled on my system. I do not see nothing wrong here..

> [user@hostname ~]$ sudo yum search all rsyslog
> (...)
> Installed Packages
> rsyslog.x86_64                                                                                                                       8.24.0-34.el7                                                                                                                       @base
> Available Packages
> rsyslog.x86_64                                                                                                                       8.24.0-34.el7                                                                                                                       base
> [user@hostname ~]$

BR

**Comment by rgerhards** [comment]
8.24.0 does not have the code that generates new-style state files. Maybe Red Hat has backported some things - unsupportable for me. But in any case, all seems to be well except for the strange version.
