### ISSUE TITLE
problem using ( & stop ) / STOP is followed by unreachable statements!  

### ISSUE THREAD

**Issue by josuegonzalezm** [rsyslog/rsyslog#3668]
### Expected behavior
● rsyslog.service - System Logging Service
   Loaded: loaded (/usr/lib/systemd/system/rsyslog.service; enabled; vendor preset: enabled)
   Active: **active (running)** since Wed 2019-05-15 16:53:50 EDT; 15h ago **...**

May 15 16:53:50 syslog002.ny5.pragmafs.com systemd[1]: Stopped System Logging Service.
May 15 16:53:50 syslog002.ny5.pragmafs.com systemd[1]: Starting System Logging Service...
May 15 16:53:50 syslog002.ny5.pragmafs.com rsyslogd[20753]:  [origin software="rsyslogd" swVersion="8.24.0-34.el7" x-pid="20753" x-info="http://www.rsyslog.com"] start
May 15 16:53:50 syslog002.ny5.pragmafs.com systemd[1]: Started System Logging Service.

### Actual behavior
● rsyslog.service - System Logging Service
   Loaded: loaded (/usr/lib/systemd/system/rsyslog.service; enabled; vendor preset: enabled)
   Active: **active (running)** since Thu 2019-05-16 08:50:07 EDT; 5s ago **...**

May 16 08:50:07 syslog002.ny5.pragmafs.com rsyslogd[3604]:  [origin software="rsyslogd" swVersion="8.24.0-34.el7" x-pid="3604" x-info="http://www.rsyslog.com"] start
**May 16 08:50:07 syslog002.ny5.pragmafs.com rsyslogd[3604]: error during config processing: STOP is followed by unreachable statements!  [v8.24.0-34.el7 try http://www.rsyslog.com/e/2207 ]**
May 16 08:50:07 syslog002.ny5.pragmafs.com systemd[1]: Started System Logging Service.

### Steps to reproduce the behavior
In the rsyslog.conf, to get the current behavior i put " & stop" and it just works when i don't use it. I need to use that command to discard the log that matches the conditions 
### Environment
- rsyslog version: 8.24.0-34.el7.
- platform: CentOS Linux release 7.6.1810 
-  rsyslog.conf

```
#$ MODULES 

#$The imjournal module bellow is now used as a message source instead of imuxsock.
$ModLoad imuxsock # provides support for local system logging (e.g. via logger command)
$ModLoad imjournal # provides access to the systemd journal
#$ModLoad imklog # reads kernel messages (the same are read from journald)
#$ModLoad immark  # provides --MARK-- message capability

#$Provides UDP syslog reception
$ModLoad imudp
$UDPServerRun 514

#$Provides TCP syslog reception
$ModLoad imtcp
$InputTCPServerRun 5000


#$ GLOBAL DIRECTIVES ####

#$Where to place auxiliary files
$WorkDirectory /var/lib/rsyslog

#$Use default timestamp format
$ActionFileDefaultTemplate RSYSLOG_TraditionalFileFormat

#$File syncing capability is disabled by default. This feature is usually not required,
#$not useful and an extreme performance hit
#$ActionFileEnableSync on

#$Include all config files in /etc/rsyslog.d/
$IncludeConfig /etc/rsyslog.d/*.conf

#$Turn off message reception via local log socket;
#$local messages are retrieved through imjournal now.
$OmitLocalLogging on

#$File to store the position in the journal
$IMJournalStateFile imjournal.state

**#$---------------------Template--------------------------------**


template(name="Stor_Temp" type="string" string="/syslog/%fromhost%/programname/%programname%.log")
template(name="Messages" type="string" string="/syslog/%fromhost%/messages")

#$---------------------Conditions-----------------------------**

*.info,mail.none,cron.none ?Stor_Temp
*.* ?Messages
& stop

#$RULES ####

#$Log all kernel messages to the console.
#$Logging much else clutters up the screen.
#$kern.*                                                 /dev/console

#$Log anything (except mail) of level info or higher.
#$Don't log private authentication messages!
*.info;mail.none;authpriv.none;cron.none                /var/log/messages

#$The authpriv file has restricted access.
authpriv.*                                              /var/log/secure

#$Log all the mail messages in one place.
mail.*                                                  -/var/log/maillog

#$Log cron stuff
cron.*                                                  /var/log/cron

#$Everybody gets emergency messages
*.emerg                                                 :omusrmsg:*

#$Save news errors of level crit and higher in a special file.
uucp,news.crit                                          /var/log/spooler

#$Save boot messages also to boot.log
local7.*                                                /var/log/boot.log
```

**Comment by rgerhards** [comment]
Is this a dot at the start of the second line? If so, what do you think it does?
```
*.infp,mail.none,cron.none ?Stor_Temp
. ?Messages
& stop
```

**Comment by rgerhards** [comment]
I also guess you meant `info` instead of `infp`?

**Comment by josuegonzalezm** [comment]
thanks for your response @rgerhards , it was just a visual error, edit the publication and I also saw the word "information", I changed it, but unfortunately, it is not the problem, I have corrected it before (I am referring to the word "information"). The template works when I comment "& stop", but if I do not, i receive that error and I do not know why.

**Comment by rgerhards** [comment]
Back to the dot: what do you think it does?

**Comment by josuegonzalezm** [comment]
i really do not know why i am receiving this error: / ... i need to discard all the logs that are being evaluated on the templates before to pass through the local rules because i receiving logs from multiple applications and servers and if i do not stop then, the logs going to be stored in my local folders. I used a template in other server that runs Rsyslog version 5 and there i am using the command "& ~" and that's working properly in the same part where is this template, so, for that reason, i don't understand what could be the problem..

**Comment by rgerhards** [comment]
I want to help you - but you need to tell me what `. ?Messages` is supposed to do. Else I can't help.

**Comment by josuegonzalezm** [comment]
oh sorry, it was just a visual error on the post... this are the command on the rsyslof.conf

```
#$---------------------Template--------------------------------**
template(name="Stor_Temp" type="string" string="/syslog/%fromhost%/programname/%programname%.log")
template(name="Messages" type="string" string="/syslog/%fromhost%/messages")
#$---------------------Conditions-----------------------------**
*.info,mail.none,cron.none ?Stor_Temp
*.* ?Messages
& stop
```

**Comment by rgerhards** [comment]
ah! OK, now it is easy.

You tell rsyslog the following: For all messages (*.*) store them the the dynafile Messages and then stop processing. This means no matter what you configure below these lines will ever be done by rsyslog. Thus it emits a warning. Old versions did not warn you.

**Comment by rgerhards** [comment]
so the solution is to remove the rest of the config, if that really is what you desire. Sorry, skipped that part ;-)

**Comment by rgerhards** [comment]
giving your previous postings, I guess this is not what you want. Can you give a textual description of what shall happen in regard to `store_temp` and `messages`?

**Comment by josuegonzalezm** [comment]
@rgerhards  well, i am trying just to move all the logs except all the logs with cron and mail to the path:/syslog/%fromhost%/programname/%programname%.log" and also store all the logs messages in all facilities and levels on a file called messages. And also i want to discard then after evaluating them in order to store the local logs in the default folders

**Comment by rgerhards** [comment]
so you intend this (in pseudo-code)?
```
if  message has *.info,mail.none,cron.none priority then
  do ?Stor_Temp
  do ?Messages
  stop
end if
```

**Comment by josuegonzalezm** [comment]
@rgerhards ok, i going to try it, and let you know in a moment. Thanks!

**Comment by rgerhards** [comment]
no, no, no ;-) I asked if this is what you want. These are not config statements!

**Comment by rgerhards** [comment]
I expect a "yes" or "no, I instead want ..." response from you.

**Comment by josuegonzalezm** [comment]
ohhh yes, well i would like to have all the logs even cron and email in the "messages" file but actually, those do not matter...

**Comment by rgerhards** [comment]
ok, this sounds you just need to reverse order of statement in legacy configuration:

```
*.* ?Messages
*.infp,mail.none,cron.none ?Stor_Temp
& stop
```

Is this what you want. This time it's actual config statements. If this is what you want, I will suggest a better way to do it in the next posting.

**Comment by josuegonzalezm** [comment]
well, if you know a better form, of course, i will prefer it and i could try it i just want to see is the " & stop" command won't generate me again a problem :-)

**Comment by rgerhards** [comment]
please try this - I admit I am not 100% sure this is what you want (@davidelang could you step in?).

The `& stop` is **not** a command. It means: "whatever the previous action was, append 'stop' to it". So the filter you select in the previous action applies. The current config format makes such cases much more obvious. But first let's see if what I posted really is what you want.

**Comment by josuegonzalezm** [comment]
@rgerhards yes i know that is not a command i just said that as an expression sorry ;-) and yes i tested it and it didn't give me an error! This is amazing .. I don't understand why if i put 
```
*.info,mail.none,cron.none ?Stor_Temp
*.* ?Messages
& stop
```
during config processing: STOP is followed by unreachable statements! but if i write your answer this doesn't give it

```
*.* ?Messages
*.info,mail.none,cron.none ?Stor_Temp
& stop
```
anywise, thanks ! i going to generat some of logs and see what happen

**Comment by davidelang** [comment]
Rsyslog is doing exactly what you are telling it to do, but it's generating a 
warning that what you are telling it is probably not what you intended

What you told it to do is to stop processing message, and then follow that with 
additional actions to process the log (which will never be used because you 
told it to stop processing)

It's far clearer to use {} to group messages than to use the &

what you told it to do was (in psudocode)

if info, except for mail and cron then write to Stor_temp

for all messages then write to Messages and throw away the log (don't process 
anything else in the config)

Since there are then actions that will never be executed, rsyslog warns about 
this.

a better way to write this would be

```
*.* ?Messages
*.info,mail.none,cron.none {
   ?Stor_Temp
   stop
}
```

this makes it much more clear about what statements you intend to be grouped. If 
you used this syntax, the original would have been

*.info,mail.none,cron.none ?Stor_Temp
*.* {
   ?Messages
   stop
}

and since the *.* means everything, this is the equivalent of:

*.info,mail.none,cron.none ?Stor_Temp
{
   ?Messages
   stop
}

and since there is no condition for the block, this is the equivalent of:

*.info,mail.none,cron.none ?Stor_Temp
?Messages
stop
<followed by the rest of your config>

does this make it clear why your original config wasn't working the way you
expected and why the warning message was correct?

David Lang

**Comment by josuegonzalezm** [comment]
Now it is so clear! I had not seen the {} before and now i understand some more things. I tested and works! Now i just going to try to get all the logs that are separated using% programname% by Stor_Temp and storage also in the messages file. I really appreciate your time and your help @rgerhards @davidelang

**Comment by josuegonzalezm** [comment]
@rgerhards well .... i am testing the configuration generating some of logs. I used the first solution that you gave me 
```
*.* ?Messages
*.info,mail.none,cron.none ?Stor_Temp
& stop
```
and it is capturing some logs, but not all of them ... i really don't know why ... the only logs that it is taking are: 
E. g: May 16 14:54:01 app102 CROND[12355]: (root) CMD (/usr/lib64/sa/sa1 1 1)

nothing else  :-(

**Comment by josuegonzalezm** [comment]
I solved the problem, i just change the form of the templates for the legacy form and everything starts to work again, it's not clear the reason but that works for me. 

before:
```
template(name="Stor_Temp" type="string" string="/syslog/%fromhost%/programname/%programname%.log")
template(name="Messages" type="string" string="/syslog/%fromhost%/messages")

#---------------------Conditions-----------------------------

*.* ?Messages
*.info,mail.none,cron.none ?Stor_Temp
& stop
```

after
```
$template Stor_Temp, "/syslog/%fromhost%/programname/%programname%.log"
$template Messages, "/syslog/%fromhost%/messages"

#---------------------Conditions-----------------------------

*.* ?Messages
*.info;mail.none;cron.none ?Stor_Temp
& stop
```
Thank you !
@rgerhards @davidelang
