### ISSUE TITLE
How to install imkafka omkafka?

### ISSUE THREAD

**Issue by thangld322** [rsyslog/rsyslog#3669]
### Expected behavior
---{ input plugins }---
    file input module enabled:                yes
    imkafka module will be compiled:          yes

---{ output plugins }---
    omelasticsearch module will be compiled:  yes
    omkafka module will be compiled:          yes

### Actual behavior
---{ input plugins }---
    file input module enabled:                no
    imkafka module will be compiled:          no

---{ output plugins }---
    omelasticsearch module will be compiled:  no
    omkafka module will be compiled:          no

### Steps to reproduce the behavior
`nano /etc/rsyslog.conf`
```
module(load="imuxsock")  # will listen to your local syslog
module(load="imfile")    # if you want to tail files
module(load="omkafka")   # lets you send to Kafka

input(type="imfile"
  File="/home/sf/rsyslog/text.txt"
  Tag="examplelogs"
)

template(name="json_lines" type="list" option.json="on") {
  constant(value="{")
  constant(value=""timestamp":"")
  property(name="timereported" dateFormat="rfc3339")
  constant(value="","message":"")
  property(name="msg")
  constant(value="","host":"")
  property(name="hostname")
  constant(value="","severity":"")
  property(name="syslogseverity-text")
  constant(value="","facility":"")
  property(name="syslogfacility-text")
  constant(value="","syslog-tag":"")
  property(name="syslogtag")
  constant(value=""}")
}

main_queue(
  queue.workerthreads="1"      # threads to work on the queue
  queue.dequeueBatchSize="100" # max number of messages to process at once
  queue.size="10000"           # max queue size
)

action(
  broker=["localhost:9092"]
  type="omkafka"
  topic="logsSIRC"
  template="json"
)
```
`service rsyslog restart`
`Job for rsyslog.service failed. See 'systemctl status rsyslog.service' and 'journalctl -xn' for details.`

**How can I install input module for kafka and output module for redis, kafka, elasticsearch?**
**Is there any documents/tutorials for this?**
Thanks!

### Environment
- rsyslog version: 
- platform: 
- for configuration questions/issues, include rsyslog.conf and included config files

**Comment by rgerhards** [comment]
Version? Platform? Did you build yourself (looks so)? How?

Sent from phone, thus brief.

thangld322 <notifications@github.com> schrieb am Fr., 17. Mai 2019, 11:04:

**Comment by thangld322** [comment]
Hi,

I downloaded rsyslog from here
[rsyslog-8.1904.0](https://www.rsyslog.com/downloads/download-daily-build/) 

After I installed rsyslog following this
[guide](https://www.rsyslog.com/tag/installation/) , it told me this:

```

---{ input plugins }---

file input module enabled: no

imkafka module will be compiled: no



---{ output plugins }---

omelasticsearch module will be compiled: no

omkafka module will be compiled: no

```

I overwrited the default rsyslog.conf with the about config I copied from
[here](https://sematext.com/blog/recipe-rsyslog-apache-kafka-logstash/) 

**OS version** = Debian GNU/Linux 8 (jessie)

**Comment by rgerhards** [comment]
you need to add `--enable-imkafka --enable-omkafka` to the configure command. Any specific reason you do not use the binary packages - I am just curios...

Rainer

**Comment by thangld322** [comment]
@rgerhards Thank you sir! Work like a charm!

I solved my problem with this line:

`./configure --prefix=/usr --enable-omkafka --enable-omelasticsearch
--enable-omhiredis --with-hiredis-dir=/usr/include`



I think you should add enable module guide to the documents. Newbies like
me are very confusing to start using rsyslog :D

**Comment by thangld322** [comment]
@rgerhards Thank you sir! I successfully cònfigure with line:

`./configure --prefix=/usr --enable-omkafka --enable-omelasticsearch
--enable-omhiredis --with-hiredis-dir=/usr/include`

Then, I run `make`, it gives me this error:

```

make[2]: Entering directory
'/home/sf/thangld13/rsyslog/rsyslog-8.1904.0/plugins/omkafka'

  CC       omkafka_la-omkafka.lo

omkafka.c: In function ‘createTopic’:

omkafka.c:437:4: error: implicit declaration of function
‘rd_kafka_last_error’ [-Werror=implicit-function-declaration]

    rd_kafka_err2str(rd_kafka_last_error()));

    ^

omkafka.c:437:4: warning: nested extern declaration of
‘rd_kafka_last_error’ [-Wnested-externs]

omkafka.c: In function ‘do_rd_kafka_destroy’:

omkafka.c:1101:4: error: implicit declaration of function ‘rd_kafka_flush’
[-Werror=implicit-function-declaration]

    const int flushStatus = rd_kafka_flush(pData->rk, pData->closeTimeout);

    ^

omkafka.c:1101:4: warning: nested extern declaration of ‘rd_kafka_flush’
[-Wnested-externs]

omkafka.c: In function ‘errorCallback’:

omkafka.c:1180:20: error: ‘RD_KAFKA_RESP_ERR__AUTHENTICATION’ undeclared
(first use in this function)

  } else if (err == RD_KAFKA_RESP_ERR__AUTHENTICATION) {

                    ^

omkafka.c:1180:20: note: each undeclared identifier is reported only once
for each function it appears in

omkafka.c: In function ‘openKafka’:

omkafka.c:1290:27: warning: passing argument 1 of
‘rd_kafka_conf_set_log_cb’ from incompatible pointer type

  rd_kafka_conf_set_log_cb(pData->rk, kafkaLogger);

                           ^

In file included from omkafka.c:39:0:

/usr/include/librdkafka/rdkafka.h:333:6: note: expected ‘struct
rd_kafka_conf_t *’ but argument is of type ‘struct rd_kafka_t *’

void rd_kafka_conf_set_log_cb (rd_kafka_conf_t *conf,

      ^

cc1: some warnings being treated as errors

Makefile:541: recipe for target 'omkafka_la-omkafka.lo' failed

make[2]: *** [omkafka_la-omkafka.lo] Error 1

make[2]: Leaving directory
'/home/sf/thangld13/rsyslog/rsyslog-8.1904.0/plugins/omkafka'

Makefile:906: recipe for target 'all-recursive' failed

make[1]: *** [all-recursive] Error 1

make[1]: Leaving directory '/home/sf/thangld13/rsyslog/rsyslog-8.1904.0'

Makefile:733: recipe for target 'all' failed

make: *** [all] Error 2

```

**Comment by thangld322** [comment]
@rgerhards after reinstall all dependencies, I have successfully installed
rsyslog with imkafka and omredis but I can't not install omelasticsearch.
Error:

`configure: WARNING: unrecognized options: --enable-omelasticsearch`

Please help!
