### ISSUE TITLE
Key signature in Debian 9 repository is invalid

### ISSUE THREAD

**Issue by Programie** [rsyslog/rsyslog#3670]
Trying to fetch packages using `apt-get update` on Debian Stretch currently fails with a "BADSIG C6326869D2017333" error. On Debian Jessie it works fine.

I checked the Release.gpg and Release.key file in Debian_8.0 and Debian_9.0 and it looks like the Release.key is the same while the Release.gpg file is different.

Full error returned by `apt-get update`:

```
Err http://download.opensuse.org/repositories/home:/rgerhards/Debian_9.0  Release.gpg
  The following signatures were invalid: BADSIG C6326869D2017333 home:rgerhards OBS Project <home:rgerhards@build.opensuse.org>
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://download.opensuse.org/repositories/home:/rgerhards/Debian_9.0  Release: The following signatures were invalid: BADSIG C6326869D2017333 home:rgerhards OBS Project <home:rgerhards@build.opensuse.org>
W: Failed to fetch http://download.opensuse.org/repositories/home:/rgerhards/Debian_9.0/Release.gpg: The following signatures were invalid: BADSIG C6326869D2017333 home:rgerhards OBS Project <home:rgerhards@build.opensuse.org>
```

**Comment by rgerhards** [comment]
I just tried a fresh docker Debian 9 container and followed the instructions on the OBS site. This works for me without any issues. Did you download the key file from there?

https://software.opensuse.org//download.html?project=home%3Argerhards&package=rsyslog

If this does not work, we need to open an issue with OBS or create a forum post. It would speed up things considerably if you could do that.

**Comment by Programie** [comment]
I just checked the Release.key:

```
$ md5sum Release.key
8496242f5699902ef12df6a565268bf3  Release.key
```

```
$ apt-key list
...
pub   rsa2048 2017-11-30 [SC] [expires: 2020-02-08]
      4B26 8629 2312 675E E69D  D7E3 C632 6869 D201 7333
uid           [ unknown] home:rgerhards OBS Project <home:rgerhards@build.opensuse.org>
...
```

I also tried to add the repository in a newly set up Debian Stretch Vagrant VM (using the box image "debian/stretch64") which works fine. So I guess there is something wrong on my side.

**Comment by Programie** [comment]
I just found the issue: Our internal proxy seems to cache the Release.gpg file which has been updated today.

**Comment by rgerhards** [comment]
I admit it's a bit strange, but I also do admit that I do not know how exactly OBS handles this. It's an OBS key, not mine.
