### ISSUE TITLE
CONTRIBUTING.md broken link

### ISSUE THREAD

**Issue by DG12** [rsyslog/rsyslog#3673]
on page
https://github.com/rsyslog/rsyslog/blob/master/CONTRIBUTING.md

help with the documentation; you can either contribute
to the rsyslog doc directory, which is shown on http://rsyslog.com/doc

The **rsyslog doc directory** points to 
https://github.com/rsyslog/rsyslog/tree/master/doc

produces. 404

**Comment by rgerhards** [comment]
fixed via #3673
