### ISSUE TITLE
freshStartOnTail does not appear to be working

### ISSUE THREAD

**Issue by RobChrystie** [rsyslog/rsyslog#3674]
While using imfile module I have the following configuration to tail /var/log/audit/audit.log:
`...
input(type="imfile" tag="sys-audit" file="/var/log/audit/audit.log" freshStartTail="on")
...`
I go ahead and start rsyslog and stream audits to the receiving machine without any issues. I shut down the rsyslog service for 15 minutes then I start rsyslog service and it picks up where it left off in the audit.log file. 

I expected it to ignore all the audits in the 15 minutes the service was off and start a "fresh tail" using only the new audits. 

Any configuration I may be missing?

Environment:
- rsyslog version: 8.39
- platform: RHEL 7.6

**Comment by rgerhards** [comment]
See doc: https://www.rsyslog.com/doc/v8-stable/configuration/modules/imfile.html

Works exactly like it should.

**Comment by RobChrystie** [comment]
Okay I did read it but must of not understood. The first time rsyslog is started it will ignore all old logs and the first time only? All subsequent stop and starts will pick up where they left off?

**Comment by davidelang** [comment]
If there is not a state file, it will ignore everything in the file (the other 
option is to send everything in the file)

but if you have a state file, it knows where it left off and makes use of that 
knowledge.

so yes, the config option only matters the first time rsyslog sees the file, but 
if you remove the state file, it will again be the 'first' time rsyslog sees the 
file :-)

David Lang

**Comment by rgerhards** [comment]
I also wonder why one want to actively loose logs just because rsyslog is stopped for a while. I can somewhat understand to not get logs from existing files when rsyslog is first installed, but after that...?

**Comment by RobChrystie** [comment]
Thank you for the responses I figured out that workaround shortly after my post! 

Sometimes in a maintenance situation we do not care to stream the logs so stopping rsyslog then restarting it would flood the listening server with logs we don't need. Similar to the freshStartOnTail situation.
