### ISSUE TITLE
function 'ipv42num' not found

### ISSUE THREAD

**Issue by strikaco** [rsyslog/rsyslog#3676]
Not sure if I'm doing something wrong but I thought this was a built-in function not requiring any external utilities? The `ipv42num` function does not seem to exist in my environment.

### Actual behavior
```
rsyslogd: error during parsing file /etc/rsyslog.d/30-sshd.conf, on or before line 165: function 'ipv42num' not found [v8.1904.0 try https://www.rsyslog.com/e/2207 ]
rsyslogd: error during parsing file /etc/rsyslog.d/30-sshd.conf, on or before line 165: Invalid function ipv42num [v8.1904.0 try https://www.rsyslog.com/e/2207 ]
```
### Steps to reproduce the behavior
```
set $.src_ip = "192.168.0.1";
set $.src_ip_int = ipv42num($.src_ip);
```

### Environment
- rsyslog version: v8.1904.0
- platform: Ubuntu 16.04
[http _localhost 5000_services_.txt](https://github.com/rsyslog/rsyslog/files/3199272/http._localhost.5000_services_.txt)

**Comment by rgerhards** [comment]
This problem is pretty strange. The function is in rsyslog core, and it is checked with every CI run. Maybe a mix of different rsyslog modules on the system?

If you can provide a debug log from startup, we may be able to provide a clue.

**Comment by mabobr** [comment]
Doc says ipv42num(), but it is a mistake, use **ip42num()** which is implemented and working.

**Comment by rgerhards** [comment]
> Doc says ipv42num(), but it is a mistake, use **ip42num()** which is implemented and working.

interesting - I overlooked this everywhere. Actually the doc is right, but the code has a typo. I'll correct it so that both names can be used.

**Comment by strikaco** [comment]
Thanks @mabobr and Rainer!
