### ISSUE TITLE
Losing logs

### ISSUE THREAD

**Issue by josuegonzalezm** [rsyslog/rsyslog#3677]
### Expected behavior
I am running a new Rsyslog server in Centos v7.6 and my old server is running in Centos v6.5. The version of the new one is Rsyslog v8.24 and in the old is Rsyslog v7.4. My problem is that in my old server i am receiving all the logs for example when i do ssh connection, but in my new one i am just receiving a part of them.. so to test what is the problem, i installed Rsyslog in another server that uses Centos v6.5 and i put the same configurations that i put in the new one and i realized that i am receiving everything that i suppose to receive .... So some know if this happens for the Centos version or could be for another reason.

Old server Example ssh: 
May 20 **13:52:06** app002 sshd[24444]: Accepted password for root from 10.80.1#.## port 1#### ssh2
May 20 **13:52:06** app002 sshd[24444]: pam_unix(sshd:session): session opened for user root by (uid=0)
May 20 14:00:07 app002 sshd[3655]: Accepted publickey for pragma from 10.70.4#.## port 48### ssh2
May 20 14:00:07 app002 sshd[3655]: pam_unix(sshd:session): session opened for user pragma by (uid=0)
May 20 14:00:07 app002 sshd[3657]: Received disconnect from 10.70.4.91: 11: disconnected by user
May 20 14:00:07 app002 sshd[3655]: pam_unix(sshd:session): session closed for user pragma
May 20 14:00:07 app002 sshd[3660]: Accepted publickey for pragma from 10.70.4#.## port 48### ssh2
May 20 14:00:07 app002 sshd[3660]: pam_unix(sshd:session): session opened for user pragma by (uid=0)
May 20 14:00:07 app002 sshd[3662]: Received disconnect from 10.70.4#.##: 11: disconnected by user (uid=0)
May 20 14:00:07 app002 sshd[3667]: Received disconnect from 10.70.4#.##: 11: disconnected by user
May 20 14:00:07 app002 sshd[3670]: Accepted publickey for pragma from 10.70.4#.## port 48### ssh2
May 20 14:00:07 app002 sshd[3670]: pam_unix(sshd:session): session opened for user pragma by (uid=0)
May 20 14:00:08 app002 sshd[3674]: Received disconnect from 10.70.4#.##: 11: disconnected by user
May 20 14:00:08 app002 sshd[3670]: pam_unix(sshd:session): session closed for user pragma
May 20 **14:02:58** app002 sshd[24444]: pam_unix(sshd:session): session closed for user root

### Actual behavior

New Rsyslog Server Example ssh:
May 20 **13:52:06** app002 sshd[24444]: Accepted password for root from 10.80.1#.## port 1### ssh2
May 20 **13:52:06** app002 sshd[24444]: pam_unix(sshd:session): session opened for user root by (uid=0)
May 20 **14:02:58** app002 sshd[24444]: pam_unix(sshd:session): session closed for user root

### Environment
- rsyslog version ( New server ): Rsyslog v8.24
- rsyslog version ( Old server ): Rsyslog v7.4.
- rsyslog version ( server using to test the problem ): Rsyslog v7.4.
- platform ( New Server): Centos v7.6
- platform ( Old Server): Centos v6.5
- platform ( Server using to test the problem): Centos v6.5
- for configuration questions/issues, include rsyslog.conf and included config files

Config New 

```
#### MODULES ####

# The imjournal module bellow is now used as a message source instead of imuxsock.
$ModLoad imuxsock # provides support for local system logging (e.g. via logger command)
$ModLoad imjournal # provides access to the systemd journal
#$ModLoad imklog # reads kernel messages (the same are read from journald)
#$ModLoad immark  # provides --MARK-- message capability

# Provides UDP syslog reception
$ModLoad imudp
$UDPServerRun 514

# Provides TCP syslog reception
#$ModLoad imtcp
#$InputTCPServerRun 514

#### GLOBAL DIRECTIVES ####

# Where to place auxiliary files
$WorkDirectory /var/lib/rsyslog

# Use default timestamp format
$ActionFileDefaultTemplate RSYSLOG_TraditionalFileFormat

# File syncing capability is disabled by default. This feature is usually not required,
# not useful and an extreme performance hit
#$ActionFileEnableSync on

# Include all config files in /etc/rsyslog.d/
$IncludeConfig /etc/rsyslog.d/*.conf

# local messages are retrieved through imjournal now.
$OmitLocalLogging on

# File to store the position in the journal
$IMJournalStateFile imjournal.state

$template Stor_Temp, "/syslog/%fromhost%/programname/%programname%.log"
$template Messages, "/syslog/%fromhost%/messages"

#---------------------Conditions-----------------------------
*.* ?Messages
*.info;mail.none;cron.none ?Stor_Temp
& stop

```
Old Server

```
#### MODULES ####

$ModLoad imuxsock # provides support for local system logging (e.g. via logger command)
$ModLoad imklog   # provides kernel logging support (previously done by rklogd)
#$ModLoad immark  # provides --MARK-- message capability

# Provides UDP syslog reception
$ModLoad imudp
$UDPServerRun 514

# Provides TCP syslog reception
$ModLoad imtcp
$InputTCPServerRun 514

#### GLOBAL DIRECTIVES ####

# Use default timestamp format
$ActionFileDefaultTemplate RSYSLOG_TraditionalFileFormat

# File syncing capability is disabled by default. This feature is usually not required,
# not useful and an extreme performance hit
#$ActionFileEnableSync on

# Include all config files in /etc/rsyslog.d/
$IncludeConfig /etc/rsyslog.d/*.conf

$template TmplAuth, "/var/log/servers/%HOSTNAME%/%PROGRAMNAME%.log"
$template TmplMsg,  "/var/log/servers/%HOSTNAME%/%PROGRAMNAME%.log"
$template Msgs, "/var/log/servers/%HOSTNAME%/messages"

authpriv.*   ?TmplAuth
 *.info,mail.none,authpriv.none,cron.none   ?TmplMsg
*.* ?Msgs
& ~
```
Server using to test the problem

```
#### MODULES ####

$ModLoad imuxsock # provides support for local system logging (e.g. via logger command)
$ModLoad imklog   # provides kernel logging support (previously done by rklogd)
#$ModLoad immark  # provides --MARK-- message capability

#module(load="ommail")   #Module of Email

# Provides UDP syslog reception
$ModLoad imudp
$UDPServerRun 514

# Provides TCP syslog reception
$ModLoad imtcp
$InputTCPServerRun 514


#### GLOBAL DIRECTIVES ####

# Use default timestamp format
$ActionFileDefaultTemplate RSYSLOG_TraditionalFileFormat

# File syncing capability is disabled by default. This feature is usually not required,
# not useful and an extreme performance hit
#$ActionFileEnableSync on

# Include all config files in /etc/rsyslog.d/
$IncludeConfig /etc/rsyslog.d/*.conf

$template Stor_Temp,"/var/log/rsyslog_test1/%fromhost%/programname/%programname%.log"
$template Messages, "/var/log/rsyslog_test1/%fromhost%/messages"

*.* ?Messages
*.info;mail.none;cron.none ?Stor_Temp
& ~

```

**Comment by davidelang** [comment]
are the messages you are loosing from the local server, or from a remote host?

if it's from the local server, it could be a journald issue, or an imjournal 
issue (there have been a lot of fixes to imjournal in the recent releases adn 
8.24 is about two years old now)

if these are from a remote system, are they arriving over TCP or UDP?

David Lang

**Comment by josuegonzalezm** [comment]
@davidelang the logs are arriving from a remote system using UDP, but i ran the New, the Old and the Test server with "tail -f " to see if they received the logs and the Old and the Test server received the logs but the New server just a part of them as you can see in the top ( Expected behavior / Actual behavior ). I tried 3 times with the same result. But checking the difference between the configuration i can see that the New server who has the problem has also the **$ModLoad imjournal**
that it is something that the other ones don't have ...

**Comment by davidelang** [comment]
imjournal is not involved with logs arriving viea UDP

If you are having problems receiving logs via UDP, the first thing I would check 
is the OS buffers.

David Lang

**Comment by josuegonzalezm** [comment]
okay i going to check that to see if it's that

**Comment by josuegonzalezm** [comment]
@davidelang i did a test where i sent a message to my email and checking if i could see it in the folder but the result was this one:
 received email: Rsyslog alert for app002 msge=' pam_sss(sshd:auth): authentication success; logname= uid=0 euid=0 tty=ssh ruser= rhost=10.80.1#.## user=testlogin'

but in the folder 

May 20 16:17:01 app002 sshd[31077]: Accepted publickey for pragma from 10.70.4.91 port 59288 ssh2
May 20 16:18:43 app002 sshd[31257]: pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=10.80.17.42  user=testlogin

This is at the same time and the same machine. Any idea?

**Comment by josuegonzalezm** [comment]
Hello, if someone can guide me a little bit more about this issue this would be great. Thank you @davidelang

**Comment by josuegonzalezm** [comment]
I solved it downgrading the version of Rsyslog from 8 stable to 7 stable.
Thanks

**Comment by davidelang** [comment]
version 7 stable is over 5 years old, not maintained, and there have been many 
bigfixes since then. go to an older 8.x instead.

David Lang
