### ISSUE TITLE
How can I get time from logs field: timestamp, @timestamp

### ISSUE THREAD

**Issue by thangld322** [rsyslog/rsyslog#3678]
Logstash -> rsyslog -> elasticsearch

### Expected behavior
Writing to ES index: logstash-2019-05-19
### Actual behavior
Writing to ES index: logstash-2019-05-22
### Steps to reproduce the behavior
I use rsyslog to write this event into elasticsearch:
`{"@timestamp":"2019-05-19T16:58:09.327Z","message":"lalaland","timestamp":"1558285089327"} `

My rsyslog.conf:
```
$template EStemplate, "%msg%"
$template date-days, "logstash-%timereported:1:10:date-rfc3339%"

module(load="imkafka")
input(type="imkafka" topic="rsyslog" broker="myhost:9092"
consumergroup="dx190522")

module(load="omelasticsearch")
action(type="omelasticsearch"
server="myhost"
serverport="9200"
template="EStemplate"
searchIndex="date-days"
dynSearchIndex="on"
searchType="event")
```
I want it to write into logstash-2019-05-19 like the time in field @timestamp but instead it writes into logstash-2019-05-22 (current time).
How can I do it? Thanks!

### Environment
- rsyslog version: 
```
rsyslogd 8.1904.0 (aka 2019.04) compiled with:
PLATFORM: x86_64-pc-linux-gnu
PLATFORM (lsb_release -d):
FEATURE_REGEXP: Yes
GSSAPI Kerberos 5 support: No
FEATURE_DEBUG (debug build, slow code): No
32bit Atomic operations supported: Yes
64bit Atomic operations supported: Yes
memory allocator: system default
Runtime Instrumentation (slow code): No
uuid support: Yes
systemd support: No
Config file: /etc/rsyslog.conf
PID file: /var/run/rsyslogd.pid
Number of Bits in RainerScript integers: 64
```
- platform: Debian 9 stretch

**Comment by davidelang** [comment]
you need to write out logs with the template RSYSLOG_DebugFormat so you can see 
how the message has been parsed.

you can also write logs using the template the omelastcsearch uses when 
delivering the message

By using timerported, you are telling rsyslog to use the time that the message 
arrived at rsyslog (IIRC).

The logstash message you show is not a valid syslog message, and so the 
@timestamp field means nothing to rsyslog. you can configure rsyslog to parse 
the message and then use the resulting variables in your output,but you have to 
configure that.

When logstash is sent a syslog message, you have to configure logstash to parse 
it before it can use the fields.

producing debug output with RSYSLOG_DebugFormat and using mmnormalize (or the 
much more limited mmjsonparse) to parse the message, then creating a template to 
use the variables produces in your outputs is where you will want to go.

David Lang

  On Tue, 21 May 
2019, thangld322 wrote:

> Date: Tue, 21 May 2019 19:35:25 -0700
> From: thangld322 <notifications@github.com>
> Reply-To: rsyslog/rsyslog
>     <reply@reply.github.com>
> To: rsyslog/rsyslog <rsyslog@noreply.github.com>
> Cc: Subscribed <subscribed@noreply.github.com>
> Subject: [rsyslog/rsyslog] How can I get time from logs field: timestamp,
>     @timestamp (#3678)
> 
> Logstash -> rsyslog -> elasticsearch
>
> ### Expected behavior
> Writing to ES index: logstash-2019-05-19
> ### Actual behavior
> Writing to ES index: logstash-2019-05-22
> ### Steps to reproduce the behavior
> I use rsyslog to write this event into elasticsearch:
> `{"@timestamp":"2019-05-19T16:58:09.327Z","message":"lalaland","timestamp":"1558285089327"} `
>
> My rsyslog.conf:
> ```
> $template EStemplate, "%msg%"
> $template date-days, "logstash-%timereported:1:10:date-rfc3339%"
>
> module(load="imkafka")
> input(type="imkafka" topic="rsyslog" broker="myhost:9092"
> consumergroup="dx190522")
>
> module(load="omelasticsearch")
> action(type="omelasticsearch"
> server="myhost"
> serverport="9200"
> template="EStemplate"
> searchIndex="date-days"
> dynSearchIndex="on"
> searchType="event")
> ```
> I want it to write into logstash-2019-05-19 like the time in field @timestamp but instead it writes into logstash-2019-05-22 (current time).
> How can I do it? Thanks!
>
> ### Environment
> - rsyslog version: 
> - platform: 
>
>
>
>
