### ISSUE TITLE
rsyslogd segfaults when an mmexternal client requests rewriting of $!

### ISSUE THREAD

**Issue by davidboles** [rsyslog/rsyslog#368]
Files to reproduce this behavior (at least as a starting place) can be found at:

https://github.com/davidboles/snowflake.git

This issue is seen on v8.9 - I have not confirmed it against 8.10.

**Comment by rgerhards** [comment]
I am pretty sure it's the same in 8.10

**Comment by davidboles** [comment]
I've tried using "json" as the property name in the mmexternal client's return line. That also segfaults. Roughly speaking, it appears that any activity relating to $! after doing the mmexternal action causes problems.

**Comment by davidelang** [comment]
possible dup of #475
