### ISSUE TITLE
Send email when certain log received

### ISSUE THREAD

**Issue by erickonavarro** [rsyslog/rsyslog#3680]
I'm currently working on a project that involves receiving events from my /var/log/conpot/conpot.log file in my rsyslog client. My rsyslog server receives them though TCP on /var/log/conpot/CONPOT.log; what I want to do is use ommail whenever there is an event that has "HTTP" on it that comes from conpot.log
I have created a .conf file on /etc/rsyslog.d with the following:

```
module=(load="ommail")
template (name="mailBody" type="string" string="RSYSLOG Alert \\r\\nmsg='%msg%'")
template (name="mailSubject" type="string" string="Activity on %hostname%")
if $msg contains "HTTP" then {
        SMTPServer="smtp.gmail.com"
        SMTPPoty="587"
        mailfrom="<email1>@gmail.com"
        mailto="<email2>@gmail.com"
        subject.template="mailSubject"
        action.execonlyconceveryinterval="60")
        }
```

I'm a missing something?

**Comment by davidelang** [comment]
don't you have to authenticate to gmail to send the message?

David Lang

**Comment by erickonavarro** [comment]
Already did. I activated the access for non-secure apps.

**Comment by strikaco** [comment]
I'm not sure if this is valid syntax but I've never seen or used it myself:

```
module=(load="ommail")
```

IME it should be `module(load="ommail")`.

Also, you appear to be missing the actual `action()` invocation-- I just see an if-then and a bunch of parameters. You load the module but nothing says to actually call `ommail` and do anything with it.

Your action block should look more like this (change settings to taste):

```
if $msg contains "hard disk fatal failure" then {
   action(type="ommail"                                    # missing this
          server="mail.example.net" port="25"
          mailfrom="rsyslog@example.net"
          mailto="operator@example.net"
          subject.template="mailSubject"
          action.execonlyonceeveryinterval="21600" 
    )                                                      # don't forget to close
}
```

For what it's worth, I've had a lot of issues pushing system-generated emails through Gmail even with their nonsense "allow less secure apps" setting enabled. If you continue to have trouble sending mail using Gmail, consider testing using not-holier-than-thou provider like gmx.de.

**Comment by rgerhards** [comment]
As far as I remember ommail cannot directly talk to gmail. The solution is to deliver to the local MTA and make it deliver to gmail.
