### ISSUE TITLE
Reopen TCP sockets on HUP signal

### ISSUE THREAD

**Issue by skupkosk** [rsyslog/rsyslog#3683]
### Expected behavior
Would be nice to be able to reopen TCP sockets on HUP (or other) signal.
It might help in LVS balanced setups where after unavailability of one LVS node, the other took over all the connections. The reopening of omfwd/omrelp TCP sockets on clients might help to balance connections again.
Maybe other signal can be used for reopening sockets.

### Actual behavior
TCP sockets are not reopened. Full rsyslog restart on clients is needed to establish new connections.

### Steps to reproduce the behavior
systemctl kill -s HUP rsyslog.service

### Environment
- rsyslog version: 8.24
- platform: Debian 9

**Comment by skupkosk** [comment]
[Syslog-ng](https://www.syslog-ng.com/technical-documents/doc/syslog-ng-premium-edition/7.0.10/administration-guide/24) behave exactly the proposed way.
This proves syslog-ng code is more mature in many aspects. Rsyslog might learn from the syslog-ng project. There is always something we can learn from each other and the thinking "will do it my way" is not the best - if not completely wrong.

> client-side (destination) connections are always reopened after receiving a HUP signal unless the keep-alive option is enabled for the destination

**Comment by davidelang** [comment]
I agree we can learn from each other, but that doesn't mean that just because 
someone else does things one way, that you must copy them.

That said, I can see this as being a valid option, but do not think that we want 
to change the default. Should this be a per output option, or a global option?

re-establishing network connections can be significantly more expensive than 
opening existing files and we also have the rebindinterval option (by the way, 
does syslog-ng have that option?)

David Lang

**Comment by davidelang** [comment]
On Thu, 30 May 2019, skupkosk wrote:

> It might help in LVS balanced setups where after unavailability of one LVS 
> node, the other took over all the connections. The reopening of omfwd/omrelp 
> TCP sockets on clients might help to balance connections again.

this is why we have rebindinterval to let load balancers like LVS have a chance 
of redistributing the load every so often.

David Lang

**Comment by skupkosk** [comment]
> On Thu, 30 May 2019, skupkosk wrote: It might help in LVS balanced setups where after unavailability of one LVS node, the other took over all the connections. The reopening of omfwd/omrelp TCP sockets on clients might help to balance connections again.
> this is why we have rebindinterval to let load balancers like LVS have a chance of redistributing the load every so often. David Lang

Thank you, David.
This make sense. Did not know about that option. Will test it. Seems to be the solution for this case.

From the point of view on sockets as 'files' the reopening on HUP make much more sense for me.
Rebindinterval is doing the same, but on different trigger. Maybe even better as it is balancing without the need of any interaction with rsyslog process.

Closing this issue. Reopen if considered valuable.
