### ISSUE TITLE
Keep a few previous releases of the same stable in the package repositories

### ISSUE THREAD

**Issue by andvgal** [rsyslog/rsyslog#3687]
### Expected behavior

Keep a few previous releases of the same stable branch.

### Actual behavior

Once a new version is released, the previous version packages are removed from the repo.

### Steps to reproduce the behavior

`apt-cache show rsyslog` - shows only the last released version.

### Environment
- rsyslog version: 8.1905.0-0adiscon1bionic1
- platform: Ubuntu 18.04

Related problem: https://github.com/rsyslog/rsyslog/issues/3681

**Comment by rgerhards** [comment]
This is how PPAs work - I don't like it either. That's one reason why we work on OBS: https://www.rsyslog.com/downloads/download-other/

**Comment by atc0005** [comment]
> This is how PPAs work - I don't like it either. That's one reason why we work on OBS: https://www.rsyslog.com/downloads/download-other/

@rgerhards 

How stable would you consider the OBS repo in comparison to the `ppa:adiscon/v8-stable` repo?

**Comment by andvgal** [comment]
BTW, I see some projects use scheme with two or more repositories on Launchpad. One is for proven stable, and another is for testing.

To motivate testing, it may be worth to keep the current as is, but to add some new "oldstable" repository with previous well tested versions.

The case of segfault seems have caused serious issues for a number of deployments and it was quite problematic to rollback.

**Comment by atc0005** [comment]
> > This is how PPAs work - I don't like it either. That's one reason why we work on OBS: https://www.rsyslog.com/downloads/download-other/
> 
> @rgerhards
> 
> How stable would you consider the OBS repo in comparison to the `ppa:adiscon/v8-stable` repo?

Follow-up:

I switched over to OBS and found that the v8.1904.0 packages are missing files.

```
root@rsyslog-obs-testing:~# dpkg -l | grep rsyslog
ii  rsyslog                          8.1904.0-1                                 amd64        a rocket-fast system for log processing
ii  rsyslog-imptcp                   8.1904.0-1                                 amd64        High-performance, threaded TCP input module for rsyslog
ii  rsyslog-mmjsonparse              8.1904.0-1                                 amd64        Parsing/handling of CEE/Lumberjack JSON messages in rsyslog
ii  rsyslog-mmnormalize              8.1904.0-1                                 amd64        The rsyslog-mmnormalize package provides log normalization
ii  rsyslog-mmrm1stspace             8.1904.0-1                                 amd64        The mmrm1stspace module permits to strip the leading space from
ii  rsyslog-mysql                    8.1904.0-1                                 amd64        MySQL output plugin for rsyslog
ii  rsyslog-relp                     8.1904.0-1                                 amd64        RELP protocol support for rsyslog
```

```
root@rsyslog-obs-testing:~# ls -l /usr/lib/rsyslog/{imptcp,mmrm1stspace}.so
ls: cannot access '/usr/lib/rsyslog/imptcp.so': No such file or directory
ls: cannot access '/usr/lib/rsyslog/mmrm1stspace.so': No such file or directory
```

```
root@rsyslog-obs-testing:~# ls -l /usr/lib/rsyslog/
total 310
-rw-r--r-- 1 root root 49504 May 28 18:17 imfile.so
-rw-r--r-- 1 root root 19912 May 28 18:17 imklog.so
-rw-r--r-- 1 root root 10912 May 28 18:17 immark.so
-rw-r--r-- 1 root root 19856 May 28 18:17 impstats.so
-rw-r--r-- 1 root root 28640 May 28 18:17 imrelp.so
-rw-r--r-- 1 root root 20176 May 28 18:17 imtcp.so
-rw-r--r-- 1 root root 28608 May 28 18:17 imudp.so
-rw-r--r-- 1 root root 33168 May 28 18:17 imuxsock.so
-rw-r--r-- 1 root root 27696 May 28 18:17 lmnet.so
-rw-r--r-- 1 root root 20736 May 28 18:17 lmnetstrms.so
-rw-r--r-- 1 root root 29312 May 28 18:17 lmnsd_ptcp.so
-rw-r--r-- 1 root root 14560 May 28 18:17 lmregexp.so
-rw-r--r-- 1 root root 10400 May 28 18:17 lmtcpclt.so
-rw-r--r-- 1 root root 33920 May 28 18:17 lmtcpsrv.so
-rw-r--r-- 1 root root 10336 May 28 18:17 lmzlibw.so
-rw-r--r-- 1 root root 23040 May 28 18:17 mmanon.so
-rw-r--r-- 1 root root 18944 May 28 18:17 mmexternal.so
-rw-r--r-- 1 root root 14704 May 28 18:17 mmjsonparse.so
-rw-r--r-- 1 root root 18864 May 28 18:17 mmnormalize.so
-rw-r--r-- 1 root root 14624 May 28 18:17 mmpstrucdata.so
-rw-r--r-- 1 root root 14720 May 28 18:17 mmsequence.so
-rw-r--r-- 1 root root 10464 May 28 18:17 mmutf8fix.so
-rw-r--r-- 1 root root 19456 May 28 18:17 ommail.so
-rw-r--r-- 1 root root 27376 May 28 18:17 omprog.so
-rw-r--r-- 1 root root 23808 May 28 18:17 omrelp.so
-rw-r--r-- 1 root root 15072 May 28 18:17 omuxsock.so
```

Installing the packages from the Adiscon PPA provides the missing files:

```
root@rsyslog-adiscon-ppa-testing:~# dpkg -l | grep rsyslog
ii  rsyslog                          8.1905.0-0adiscon1xenial1                  amd64        a rocket-fast system for log processing
ii  rsyslog-imptcp                   8.1905.0-0adiscon1xenial1                  amd64        High-performance, threaded TCP input module for rsyslog
ii  rsyslog-mmjsonparse              8.1905.0-0adiscon1xenial1                  amd64        Parsing/handling of CEE/Lumberjack JSON messages in rsyslog
ii  rsyslog-mmnormalize              8.1905.0-0adiscon1xenial1                  amd64        The rsyslog-mmnormalize package provides log normalization
ii  rsyslog-mmrm1stspace             8.1905.0-0adiscon1xenial1                  amd64        The mmrm1stspace module permits to strip the leading space from
ii  rsyslog-mysql                    8.1905.0-0adiscon1xenial1                  amd64        MySQL output plugin for rsyslog
ii  rsyslog-relp                     8.1905.0-0adiscon1xenial1                  amd64        RELP protocol support for rsyslog
```

```
root@rsyslog-adiscon-ppa-testing:~# ls -l /usr/lib/rsyslog/{imptcp,mmrm1stspace}.so
-rw-r--r-- 1 root root 45536 May 28 09:20 /usr/lib/rsyslog/imptcp.so
-rw-r--r-- 1 root root 10368 May 28 09:20 /usr/lib/rsyslog/mmrm1stspace.so
```

**Comment by davidelang** [comment]
I recommend pulling any Internet sources into a local repo that you then install 
from. Keep the old copies locally.

Besides the PPA problem, there have been many cases where something has 
happened to a project and they have completely taked down the source. I don't 
expect this to ever happen with rsyslog, but just as a general practice, you 
should never make yourself dependent on the Internet to be able to rebuild a 
machine with the exact same versions that you have on the machine now.

Note: I think it is good for rsyslog to figure out how to keep multiple versions 
of packages available, I just don't think it's good to rely on projects like 
rsyslog to do so.

David Lang

**Comment by andvgal** [comment]
@davidelang I agree when you build something in-house, but that does not work for open source automation like [cflogsink](https://github.com/codingfuture/puppet-cflogsink).

I've used to maintain FireHOL mirror for older OS versions, but it's not a good approach for open source when package repos get scattered.

**Comment by davidelang** [comment]
all automation should be able to point at local repos that can have old 
versions.

The idea that an install MUST install the latest version is a concept that can 
only be held by people who are lacking real-world experience in maintaining 
production systems. It also indicates someone who is willing to bet their 
company on the security of systems maintained by unknown people on the Internet 
and the idea that the software there has not been tampered with (including 
archives of older versions)

While I am an advocate for patching frequently and running the lastest version 
of software (at least for software that is the purpose of a system), there are 
always going to be times when a new release has a bug, and there will be times 
when the bug slips through all your testing and only shows up in production. As 
a result, you always need a way to run an older version. In addition, there are 
times when you need to be able to duplicate an older system (to troubleshoot how 
it differs from the latest version for example), and bugs may not manifest 
themselves in visible problems immediately. (My personal standard is to be able 
to go back at least 6 months)

I have twice setup systems that download all updates daily to a local mirror, 
install the daily update on some smoke test systems, and then periodically (I 
prefer weekly) a repo that has not caused problems with the test systems gets 
promoted to QA and migrates from there to production.

This approach doesn't try to prove that the updates cannot cause a problem, but 
insteads takes the approach that first, it's impossible to prove a negative 
(that the update cannot cause a problem) and second, that almost all updates do 
not cause problems, so rather than trying to prove that the update can not cause 
a problem, accept that some update, some time, WILL cause a problem and setup an 
gradual update process that minimizes the impact of any problem that does happen 
and gives you an ability to revert to the prior version

Which (looping back to the topic at hand), requires that you have the ability to 
recreate the build/image with the prior versions.

David Lang

**Comment by andvgal** [comment]
Yep, that's exactly what can be solved with local apt repo + git mirrors. That's the only option for setups with high security requirements in fact. That's why all repository URL gets [parameterized for example](https://github.com/codingfuture/puppet-cflogsink/blob/master/manifests/rsyslog/ubuntuapt.pp#L9). 

However, such approach does require major resources to track and analyze all dependencies even with proper tools at hand. Finally, it ends up in a custom operating system for purpose like in payment card industry (where my roots come from).

In most other cases, without a dedicated qualified personnel, there is a much higher risk of not getting CVE flagged updates in time. For most user security requirements, only original maintainers provide a good balance unfortunately.

So, @rgerhards  & @davidelang please reconsider to maintain "oldstable" or similar repo, if you have difficulties keeping the old versions in Launchpad. It should not require any source changes.

**Comment by davidelang** [comment]
On Sun, 2 Jun 2019, Andrey Galkin wrote:

> So, @rgerhards  & @davidelang please reconsider to maintain "oldstable" or similar repo, if you have difficulties keeping the old versions in Launchpad. It should not require any source changes.

the ODS should have old versions in it, and if there are files missing, that's a 
bug to be solved.

trying to maintain an oldstable or similar repo seems to be to be a time sink 
(the build scripts are available on github, so if you see a way to modify them 
to manage it automatically, I'm sure the updates would be accepted)

David Lang

**Comment by davidelang** [comment]
On Sun, 2 Jun 2019, Andrey Galkin wrote:

> Yep, that's exactly what can be solved with local apt repo + git mirrors. That's the only option for setups with high security requirements in fact. That's why all repository URL gets [parameterized for example](https://github.com/codingfuture/puppet-cflogsink/blob/master/manifests/rsyslog/ubuntuapt.pp#L9).
>
> However, such approach does require major resources to track and analyze all dependencies even with proper tools at hand. Finally, it ends up in a custom operating system for purpose like in payment card industry (where my roots come from).

no, just mirror all the repos that you use (I agree that cpan and pip pose 
problems, but they are also major causes of unexpected changes)

> In most other cases, without a dedicated qualified personnel, there is a much higher risk of not getting CVE flagged updates in time.

I agree. But you don't need to go to every binaries public repo, use your distro 
repo + a handful of projects that are the 'important' apps you are running 
(apache for your webservers, rsyslog for your log relays's etc). There are 
hundreds to thousands of packages that you do not need to be expert on, so you 
rely on your distro for those.

David Lang
(off my soapbox)
