### ISSUE TITLE
[ enhancement ] Turning off UseSpecialParser for FreeBSD imuxsock

### ISSUE THREAD

**Issue by zeising** [rsyslog/rsyslog#3694]
### Summary
FreeBSD switched logging to use rfc5424 behaviour by defalt on logs arriving on log sockets and elsewhere. This seem to confuse rsyslog parsing, and the result is that rsyslog fails to parse out things like program name. This can be fixed by turning off the special parser, using `useSpecialParser=off`. This should probably be made the default for FreeBSD (or handled in another way, if appropriate)
Some more information is available in this mail thread:
http://rsyslog-users.1305293.n2.nabble.com/imuxsock-needs-UseSpecialParser-off-quot-to-parse-var-run-log-correctly-on-FreeBSD-td7594964.html

### Expected behavior
Proper parsing of things like programname, syslogtag, and so on. See this debug log with useSpecialParser turned off:
```
Debug line with all properties:
FROMHOST: 'test', fromhost-ip: '127.0.0.1', HOSTNAME: 'test.daemonic.se', PRI: 133,
syslogtag 'blah[35820]', programname: 'blah', APP-NAME: 'blah', PROCID: '35820', MSGID: '-',
TIMESTAMP: 'Jun  6 11:32:34', STRUCTURED-DATA: '-',
msg: 'blahblah'
escaped msg: 'blahblah'
inputname: imuxsock rawmsg: '<133>1 2019-06-06T11:32:34.666+02:00 test.daemonic.se blah 35820 - - blahblah'
$!:
$.:
$/:
```

### Actual behavior
Here is a snippet of a log (from logger), with using the `RSYSLOG_DebugFormat` template

```
Debug line with all properties:
FROMHOST: 'test', fromhost-ip: '127.0.0.1', HOSTNAME: 'test', PRI: 133,
syslogtag '1', programname: '1', APP-NAME: '1', PROCID: '-', MSGID: '-',
TIMESTAMP: 'Jun  6 10:49:22', STRUCTURED-DATA: '-',
msg: ' 2019-06-06T10:49:22.311548+02:00 test.daemonic.se blah 1065 - - blahblah'
escaped msg: ' 2019-06-06T10:49:22.311548+02:00 test.daemonic.se blah 1065 - -
blahblah'
inputname: imuxsock rawmsg: '<133>1 2019-06-06T10:49:22.311548+02:00
test.daemonic.se blah 1065 - - blahblah'
$!:
$.:
$/:
```
Note how programname and other things are not set correctly.
### Steps to reproduce the behavior
Set up rsyslogd on FreeBSD
Use the follwing conf:
```
module(load="imklog")
module(load="immark")
module(load="imuxsock"
        SysSock.Use="off"
        SysSock.FlowControl="on")

input(type="imuxsock"
        Socket="/var/run/log")

*.*     action(type="omfile"
                file="/var/log/all.log.debug"
                template="RSYSLOG_DebugFormat"
)
```
Generate log messages:
`logger -i -p local0.notice -t blah blahblah`

### Environment
- rsyslog version: 8.40.0
- platform: FreeBSD 12.0 amd64, FreeBSD 13-CURRENT amd64
- for configuration questions/issues, include rsyslog.conf and included config files

**Comment by rgerhards** [comment]
Would you be willing to help with FreeBSD 12 installation for CI purposes? I can provision a VM, but I need help with customizing it.

**Comment by zeising** [comment]
> Would you be willing to help with FreeBSD 12 installation for CI purposes? I can provision a VM, but I need help with customizing it.

Of course!
Looking at the repo, it looks like you're using travis. I don't know very much about it, but I'm willing to learn. I know cirrus CI has good github integration and FreeBSD support out of the box, that might be an option otherwise, but I'll run with whatever you feel is best.

**Comment by rgerhards** [comment]
Travis Supports only Linux, but we have large buildbot infrastructure.
There is an older FreeBSD in it, so that should run without issues. We have
vms e.g. sponsored by digital ocean.

https://build.rsyslog.com/#/


Sent from phone, thus brief.

**Comment by zeising** [comment]
Ah, I didn't know about that infrastructure.
Just let me know what you need help with or want me to do, and I'll help out!

**Comment by rgerhards** [comment]
Great! I'll see if I can provision a VM today ... but I may need until next week. Big holiday weekend is in front of use here in Germany and I still have to tackle the backlog... ;-)

**Comment by rgerhards** [comment]
@zeising pls send me a mail to rgerhards@adiscon.com so that we can get into direct contact

**Comment by rgerhards** [comment]
I will try to fix this without a test first. Getting testbench ready ATM, but would like to ensure the solution goes into the next scheduled release.

**Comment by zeising** [comment]
> I will try to fix this without a test first. Getting testbench ready ATM, but would like to ensure the solution goes into the next scheduled release.

Sounds good.  Just let me know if you need help with the test bench.
Regards

**Comment by rgerhards** [comment]
@zeising for sure will do; actually, I created the VM instance and am more or less ready to install. But lots of other things so I thought better do the fix now than let it slip ;-)

**Comment by rgerhards** [comment]
@zeising #3733 has a fix. would be good if you could give it a manual test.

**Comment by zeising** [comment]
I'll give it a spin, might take until tonight CEST before I have time, but I'll try to get to it asap.
