### ISSUE TITLE
Multi-line message separator is "\\n"

### ISSUE THREAD

**Issue by hakman** [rsyslog/rsyslog#370]
startmsg.regex allows to assemble multi-line messages. The separator for each line is [hardcoded as "\\\n"](https://github.com/rsyslog/rsyslog/blob/master/runtime/stream.c#L862).
The problem that I see it that all other control characters are left as they are read, for example "\t".

I propose to change the separator to "\n" instead of "\\\n" to have all control characters unescaped.

**Comment by rgerhards** [comment]
This is tricky, because if we keep \n, we again have a multi-line message, with all the problem associated with it. I think there was an option for escaping, which I did not really look at for the first try. Will check what it usually is used for.

**Comment by hakman** [comment]
I think you refer to the escapeLF option for imfile.
My idea was to do this later, in the template, using `format="json"` or something else.

**Comment by rgerhards** [comment]
yeah, that's the option and it is not properly implemented. I'll do that now.

**Comment by hakman** [comment]
Thank you!
