### ISSUE TITLE
[enhancement][imjournal] read journal received from other hosts

### ISSUE THREAD

**Issue by frantz45** [rsyslog/rsyslog#3703]
### Expected behavior
journald can forward events thanks to systemd-journal-upload/systemd-journal-remote.
By default received events are written to /var/log/journal/remote/.
imjournal should be able to read these logs.
Maybe add a parameter Path to configure where imjournal should read events.

### Actual behavior
imjournal only reads the local journal.

### Steps to reproduce the behavior
On the server configure systemd-journal-remote to listen to events.
On the client configure systemd-journal-upload to push events to server.
On the server configure imjournal.

### Environment
- rsyslog version: 8.40
- platform: CentOS 7

**Comment by rgerhards** [comment]
@jvymazal is this something we should intend to support? Given the problems with journal files, I am very hesitant to do that...

**Comment by jvymazal** [comment]
@rgerhards in theory it is very simple, just add an option based on which I will drop the LOCAL_ONLY flag when opening journal, however (as usual with journald) there is no guarantee that nothing breaks up during all use-cases and operational modes.

**Comment by rgerhards** [comment]
yeah that's my experience and fear. Probably better stay with local support rather than opening a new can of worms

@davidelang what do you think?

**Comment by jvymazal** [comment]
Currently I do not see anything particular that could break, so If we want to do this I would suggest to just add the option and document it as "beta" or whatever status you use for uncertain things and wait few releases before someone starts to use it and finds out whether there are some problems.

**Comment by jvymazal** [comment]
yes, looks like my mention in #3878 did not get picked up.

**Comment by frantz45** [comment]
I may be wrong but if I well understand the PR https://github.com/rsyslog/rsyslog/pull/3878 we can now pull journald records from outside local machine.
It's not what I describe in this issue.
I would like rsyslog to be able to get journald records received on the local machine.

**Comment by jvymazal** [comment]
> I may be wrong but if I well understand the PR #3878 we can now pull journald records from outside local machine.
Yes
> It's not what I describe in this issue.
> I would like rsyslog to be able to get journald records received on the local machine.
That is the default behavior, with "normal" settings imjournal picks up all local records

**Comment by frantz45** [comment]
> > It's not what I describe in this issue.
> > I would like rsyslog to be able to get journald records received on the local machine.
> 
> That is the default behavior, with "normal" settings imjournal picks up all local records
So can you please explain me how to get journald records received in /var/log/journal/remote/.

**Comment by jvymazal** [comment]
> So can you please explain me how to get journald records received in /var/log/journal/remote/.

I am not that familiar with remote journald feature, however it looks like those are actually logs from outside of local machine (originally) and journald treats them as such. In that case imjournal with the new option from #3878 should be able to pick them up alongside the standard ones.

**Comment by frantz45** [comment]
> 
> 
> > So can you please explain me how to get journald records received in /var/log/journal/remote/.
> 
> I am not that familiar with remote journald feature, however it looks like those are actually logs from outside of local machine (originally) and journald treats them as such. In that case imjournal with the new option from #3878 should be able to pick them up alongside the standard ones.

On hostA configure systemd-journal-upload to push journald records to hostB.
On hostB configure systemd-journal-remote to listen and wait journald records.
I did it on CentOS but this link explain how to do on Ubuntu, it's quite the same : https://serverfault.com/questions/758244/how-to-configure-systemd-journal-remote

**Comment by rgerhards** [comment]
looks like it is done ;-)
