### ISSUE TITLE
'action 3' was resumed (module 'builtin: mfwd') 2359

### ISSUE THREAD

**Issue by aremai** [rsyslog/rsyslog#3705]
Hello,

I'm receiving lots of errors as below:

liblogging-stdlog: action 'action 3' resumed (module 'builtin:omfwd') [v8.24.0 try http://www.rsyslog.com/e/2359 ]
[rsyslog.conf.txt](https://github.com/rsyslog/rsyslog/files/3290865/rsyslog.conf.txt)

Any idea what this means and what is triggering this event?

### Environment
- rsyslog version: v8.24.0
- platform: Suse Linux Enterprise 11

**Comment by jchivian** [comment]
A. That's an ancient version, you should update if possible.
B. rsyslog assigns names like "action 3" to actions that aren't explicitly named.  So, the third action encountered in your configs is causing the issue.  To tell what that is you must also include the content of the following as they appear early in your master config file.
$IncludeConfig /run/rsyslog/additional-log-sockets.conf
$IncludeConfig /etc/rsyslog.d/*.conf
C. The output of "rsyslogd -N5 -d" may help.

**Comment by aremai** [comment]
hello @jchivian 

thank you for your fast response.
the problem is that we cannot upgrade the ancient rsyslog version, because it's running on a read-only SLES12 image (on an SAP environment) and therefore we cannot upgrade it at the moment, without swapping the whole OS/read-only image.

currently the only sub-config that's being read from /etc/rsyslog.d/ is this one:

`module(load="imfile" PollingInterval="10")
input(type="imfile"
        File="/home/appusers/abcadm/test.log"
        Tag="abc-adm-test"
        Severity="info"
        Facility="local7")
local7.* @@ip-of-remote-syslog-server:514`

Also attached the output of rsyslogd -N5 -d output.

[rsyslogd_N5_d.txt](https://github.com/rsyslog/rsyslog/files/3301386/rsyslogd_N5_d.txt)

**Comment by jchivian** [comment]
Actually, multiple files from /etc/rsyslog.d are being included.

3917.463553551:main thread    : config parser: reached end of file 
/run/rsyslog/additional-log-sockets.conf
3917.463622050:main thread    : config parser: resume parsing of file 
/etc/rsyslog.conf at line 57
3917.467180910:main thread    : requested to include config file 
'/etc/rsyslog.d/remote.conf'
3917.467804665:main thread    : config parser: pushed file 
/etc/rsyslog.d/remote.conf on top of stack
3917.467910424:main thread    : requested to include config file 
'/etc/rsyslog.d/09_nxlog.conf'
3917.468468667:main thread    : config parser: pushed file 
/etc/rsyslog.d/09_nxlog.conf on top of stack
3917.468568340:main thread    : requested to include config file 
'/etc/rsyslog.d/02_security.conf'
3917.469122856:main thread    : config parser: pushed file 
/etc/rsyslog.d/02_security.conf on top of stack
3917.469218218:main thread    : requested to include config file 
'/etc/rsyslog.d/01_appl.conf'
3917.469848600:main thread    : config parser: pushed file 
/etc/rsyslog.d/01_appl.conf on top of stack

Is this intended?

**Comment by aremai** [comment]
Hi @jchivian 

yes this is intended, however only /etc/rsyslog.d/09_nxlog.conf is currently being used for my use-case at the moment.

**Comment by rgerhards** [comment]
old version only, so no way to see if there actually is a bug
