### ISSUE TITLE
Dead Link in Readme

### ISSUE THREAD

**Issue by mlh758** [rsyslog/rsyslog#3712]
### Expected behavior

Instructions for building from source should be a valid link

### Actual behavior

https://www.rsyslog.com/doc/build_from_repo.html linked to from readme is dead

**Comment by mlh758** [comment]
The documentation on the [newbie guide](https://www.rsyslog.com/newbie-guide-to-rsyslog/) is also a bit out of date.

I'm working on compiling it now so I'll just use this comment to document what appears to need updating.

1. `libee` doesn't appear to be necessary anymore
2. `libfastjson` is necessary now
3. `zlib` is necessary now

**Comment by rgerhards** [comment]
I think the requirements are not 100% correct - they depend on configure options. Some features require special packages. Or do you need `libuuid-devel` and `libcurl-devel` in any case? That would sound like a program bug.

**Comment by mlh758** [comment]
I'm building with the defaults. Looks like `libuuid` can be disabled with options to the autogen script. If it is required by default then it seems like it should be in the docs.

`fmhttp` is enabled by default and that requires `libcurl-devel`.

`libgcrypt-config` is also required by default.

If they weren't enabled by default then I'd understand not listing them as requirements but you can't run the autoconfigure script without either installing these packages or figuring out which features to turn off.

Maybe the docs could specify a set of minimal build options?

**Comment by mlh758** [comment]
`./autogen.sh --disable-libgcrypt` Doesn't seem to remove the need to have `libgcrypt-config` for me.

**Comment by mlh758** [comment]
This [compile link](https://www.rsyslog.com/doc/v8-stable/installation/install_from_source.html) mentions running `./configure` but there is only a `configure.ac` in the tarball. I've had some luck running `./autogen.sh` with my options instead. Is that the appropriate route?

Something like:
```sh
PID_FILE_PATH=/var/run/syslogdv8.pid CONF_FILE_PATH=/etc/rsyslogv8.conf ./autogen.sh \
  --enable-imfile --disable-libgcrypt --disable-uuid --enable-imfile
```

**Comment by davidelang** [comment]
autogen.sh creates the configure and makefile

David Lang

**Comment by mlh758** [comment]
Yeah, I went and looked at some of your PR builds and I'm using autoreconf now, then putting all the configure parameters on `./configure` where they make more sense.

```
autoreconf --force --verbose --install
PID_FILE_PATH=/var/run/syslogdv8.pid CONF_FILE_PATH=/etc/rsyslogv8.conf ./configure \
  --enable-imfile --disable-libgcrypt --disable-uuid --enable-imfile
```

Looks to be more correct, but it isn't reflected in the docs. I also keep getting stuck on this error in make when gcc starts to run:

```
make[2]: Entering directory `/home/rsyslog/rsyslog-8.1905.0/compat'
  CC     compat_la-getifaddrs.lo
  CC     compat_la-strndup.lo
  CC     compat_la-asprintf.lo
  CC     compat_la-solaris_elf_fix.lo
gcc: gcc: cannot specify -o with -c or -S with multiple files
cannot specify -o with -c or -S with multiple files
make[2]: *** [compat_la-solaris_elf_fix.lo] Error 1
gcc: cannot specify -o with -c or -S with multiple files
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [compat_la-getifaddrs.lo] Error 1
make[2]: *** [compat_la-strndup.lo] Error 1
gcc: cannot specify -o with -c or -S with multiple files
make[2]: *** [compat_la-asprintf.lo] Error 1
```

**Comment by rgerhards** [comment]
what are your CFLAGS?

**Comment by mlh758** [comment]
On the [new link](https://www.rsyslog.com/doc/v8-stable/installation/build_from_repo.html) in the repo it says to follow the installation guide at [this link](https://www.rsyslog.com/doc/v8-stable/installation/install.html) which is also dead.

As for CFLAGS, I ran `echo $CFLAGS` in the container and there are none set.

**Comment by rgerhards** [comment]
> As for CFLAGS, I ran `echo $CFLAGS` in the container and there are none set.

That's pretty strange. Can you do a `make V=1 ...other options...` so that we see how the compiler is called.

Also, can you share:
* the container you use
* the exact commands you use
So that I can try to reproduce the compile issue?

**Comment by mlh758** [comment]
This is the dockerfile I've been using: https://gist.github.com/mlh758/89fd89bf5a2b7c2357af751e328d340a

**Comment by mlh758** [comment]
This is the output from`make V=1`

```
make  all-recursive
make[1]: Entering directory `/home/rsyslog/rsyslog-8.1905.0'
Making all in compat
make[2]: Entering directory `/home/rsyslog/rsyslog-8.1905.0/compat'
/bin/sh ../libtool  --tag=CC   --mode=compile gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I..  -I.. -pthread -I../runtime -I.. -I../grammar /usr/include/libestr.h /usr/include/libfastjson  -W -Wall -Wformat-security -Wshadow -Wcast-align -Wpointer-arith -Wmissing-format-attribute -Werror=implicit-function-declaration -g    -g -O2 -W -Wall -Wformat-security -Wshadow -Wcast-align -Wpointer-arith -Wmissing-format-attribute -g -MT compat_la-getifaddrs.lo -MD -MP -MF .deps/compat_la-getifaddrs.Tpo -c -o compat_la-getifaddrs.lo `test -f 'getifaddrs.c' || echo './'`getifaddrs.c
libtool: compile:  gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I.. -I.. -pthread -I../runtime -I.. -I../grammar /usr/include/libestr.h /usr/include/libfastjson -W -Wall -Wformat-security -Wshadow -Wcast-align -Wpointer-arith -Wmissing-format-attribute -Werror=implicit-function-declaration -g -g -O2 -W -Wall -Wformat-security -Wshadow -Wcast-align -Wpointer-arith -Wmissing-format-attribute -g -MT compat_la-getifaddrs.lo -MD -MP -MF .deps/compat_la-getifaddrs.Tpo -c getifaddrs.c  -fPIC -DPIC -o .libs/compat_la-getifaddrs.o
```

**Comment by mlh758** [comment]
I was doing a few things wrong.

1. I was looking at the documentation for autoconf for how to use the `--enable-<whatever>` properties. That was the wrong place. It was just `--enable-uuid=no` and so on.
2. Setting `PKG_CONFIG_PATH` instead of manually setting the varaiblesfor LIBFASTJSON_LIBS and LIBFASTJSON_CFLAGS fixed the error in make
