### ISSUE TITLE
Fractional seconds dropped from %timegenerated:::date-rfc3339% when queue added to ruleset

### ISSUE THREAD

**Issue by mikesphar** [rsyslog/rsyslog#3716]
I admit this one is baffling and I can't imagine how the two things would be related, but still...

I'm experiencing a problem where I'm forwarding logs to an aggregator using %timegenerated:::date-rfc3339% for the timestamp of the message. The messages are sent to a ruleset which has actions configured for failover, and all of that is working correctly when no queues are configured.  However, when I define queue parameters on the ruleset, the aggregator receiving the logs starts complaining that the timestamps no longer match the expected format.  Without the queue, the timestamp is formatted like "2019-06-21T19:59:31.745313+00:00".  With the queue enabled the timestamp's are arriving as "2019-06-21T19:58:17+00:00". It appears the fractional settings are disappearing.

I'll note that I tried to replicate this by changing the action to write to a local file and could not replicate it this way. It only seems to happen when the action is omfwd to another host.

I took a tcpdump on the server receiving the messages to confirm.

This is from a tcpdump of the received message without the queue:
```2019-06-21T19:59:31.745313+00:00 hostname service[14984]:  Connect from 127.0.0.1:40348 to 127.0.0.1:8080 (monitoring/HTTP)```

This is from a tcpdump of a received message with the queue:
```2019-06-21T19:58:17+00:00 hostname service[14984]:  Connect from 127.0.0.1:39610 to 127.0.0.1:8080 (monitoring/HTTP)```

### Expected behavior
Output of %timegenerated:::date-rfc3339% stays consistent with fractional seconds included

### Actual behavior
Fractional seconds are dropped when a queue is defined for a ruleset with actions using omfwd via TCP.

### Steps to reproduce the behavior
Using the sample configuration as-is, and with removing the queue parameters from the ruleset.

### Environment
- rsyslog version: rsyslogd  8.1903.0 (aka 2019.01) compiled with:
        PLATFORM:                               x86_64-pc-linux-gnu
        PLATFORM (lsb_release -d):
        FEATURE_REGEXP:                         Yes
        GSSAPI Kerberos 5 support:              Yes
        FEATURE_DEBUG (debug build, slow code): No
        32bit Atomic operations supported:      Yes
        64bit Atomic operations supported:      Yes
        memory allocator:                       system default
        Runtime Instrumentation (slow code):    No
        uuid support:                           Yes
        systemd support:                        Yes
        Config file:                            /etc/rsyslog.conf
        PID file:                               /run/rsyslogd.pid
        Number of Bits in RainerScript integers: 64

- platform: Debian Stretch 4.14.31.bt9-amd64

Sample config:

```
template(name="StructuredTemplate" type = "string"
  string="%timegenerated:::date-rfc3339% %HOSTNAME% %syslogtag% %msg%"
)

ruleset(name="StructuredPipeline"
  queue.type="LinkedList"
  queue.size="10000"
  ) {
  action(type="omfwd" protocol="tcp" port="1095" target="XXX"
  name="log-worker-172.23.33.214"
  template="StructuredTemplate"
)

  action(type="omfwd" protocol="tcp" port="1095" target="YYY"
  name="log-worker-172.23.33.212"
  template="StructuredTemplate"
  action.execOnlyWhenPreviousIsSuspended="on"
)

  action(type="omfwd" protocol="tcp" port="1095" target="ZZZ"
  name="log-worker-172.23.33.177"
  template="StructuredTemplate"
  action.execOnlyWhenPreviousIsSuspended="on"
)

}

call StructuredPipeline
```

**Comment by rgerhards** [comment]
thx for the bug report. I could reproduce the issue, even with a simpler config:
```
template(name="all_properties" type = "string"
	string="%timegenerated:::date-rfc3339% %HOSTNAME% %syslogtag% %msg%\n"
)

ruleset(name="rs_with_queue" queue.type="LinkedList" queue.size="10000") {
	action(type="omfile" file="'$RSYSLOG_OUT_LOG'" template="all_properties")
	# works on a duplicated message thanks to the queue
}

if $msg contains "msgnum:" then {
	call rs_with_queue
	action(type="omfile" file="'$RSYSLOG2_OUT_LOG'" template="all_properties")
	# works on original, non-duplicated, message
}
```

It's a problem with message duplication. I think I have already isolated it. Working on patch...
