### ISSUE TITLE
on FreeBSD, console output is made of lines that do not start at the first column

### ISSUE THREAD

**Issue by AlexandreFenyo** [rsyslog/rsyslog#372]
Here is a bug report about rsyslog, that occurs on FreeBSD.

# Here is the description of the bug
When logging on the console, rsyslog writes "\n" (NL) instead of "\r\n" (CRNL). Therefore, console output is made of lines that do not start at the first column.

This bug and the proposed patch have already been recently discussed on the rsyslog-user mailing list, but I've not seen any answer to the last suggestion of the FreeBSD port maintainer. So, I open this github issue to track the discussion about this bug.

# Here is a patch to correct this bug
https://bz-attachments.freebsd.org/attachment.cgi?id=156857
This patch changes rsyslog behaviour only on FreeBSD.

# Here is the original analysis about the bug
When logging on the console, rsyslog writes "\n" (NL) instead of "\r\n" (CRNL). Therefore, console output is made of lines that do not start at the first column, because every FreeBSD console drivers need CRNL. One may think it is not necessary to patch rsyslog since it could be possible to automatically convert any "\n" char that rsyslog writes to the console to "\r\n", simply setting the opost and onlcr output mode flags on the console (using /etc/gettytab). But for some tricky reasons that are explained in FreeBSD bug report 199767 https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=199767#c4 , it is not possible for those flags to be set at any time, specifically because of this getty behaviour: when getty is waiting for a login, it clears the opost flag to handle the line-mode by itself (the console device is in raw mode during this step, the output flag opost is cleared and line-mode processing, like handling backspaces or ^U, is done by getty, not by the console driver).

# Here is an abstract about the discussion on the rsyslog-user mailing list
1. The patch modifies a C function that is at the core of rsyslog, so a potential regression could occur
2. Anyway, no need to patch the source code, FreeBSD users could use a template to change EOL
3. But this would make the rsyslog examples not being correct for FreeBSD users

# Here are complementary thoughts about the whole discussion
1. a regression could occur only for FreeBSD users, since the patch makes use of \#ifdef \_\_FreeBSD\_\_
2. applying the patch to rsyslog is the only way for the user to get rsyslog work properly on a FreeBSD console without having to make changes in the configuration files
3. without this patch, rsyslog configuration files can not be imported from other operating systems to FreeBSD without having to modify them to include a specific template for some rules

**Comment by rgerhards** [comment]
OK, I'll merge it. If a regression comes up, we need to check further. Thx for your persistence.

**Comment by rgerhards** [comment]
I think this got merged and I just forgot to close the bug. Need to investigate to be sure.
