### ISSUE TITLE
ca certificate is not set

### ISSUE THREAD

**Issue by pavanrangain** [rsyslog/rsyslog#3731]
Getting error ca certificate is not set
could not load module '/usr/lib/rsyslog/lmnsd_gtls.so', rsyslog error -2329  [v8.37.0 try http://www.rsyslog.com/e/2068 ]

My rsyslog conf is as below

$DefaultNetstreamDriver gtls
$ActionSendStreamDriverAuthMode anon
$ActionSendStreamDriverMode 1

if $programname startswith "haproxy" then {
  @@syslog2.mydomain.com:514
}

Indeed i have not provided CA certificate file. The server is having a valid cert from the well know CA. Do we still need to provide the CA certificate in this case?

### Expected behavior
For well known CA's no need to provide CA certificate
### Actual behavior
CA certificate seems mandatory configuration
### Steps to reproduce the behavior
with above config try restarting rsyslog service. we will get error
### Environment
- rsyslog version: rsyslogd 8.37.0, compiled with:
	PLATFORM:				x86_64-unknown-linux-gnu
	PLATFORM (lsb_release -d):		
	FEATURE_REGEXP:				Yes
	GSSAPI Kerberos 5 support:		No
	FEATURE_DEBUG (debug build, slow code):	No
	32bit Atomic operations supported:	Yes
	64bit Atomic operations supported:	Yes
	memory allocator:			system default
	Runtime Instrumentation (slow code):	No
	uuid support:				Yes
	systemd support:			Yes
	Number of Bits in RainerScript integers: 64

See http://www.rsyslog.com for more information.
- platform: Photon OS Vmware

**Comment by rgerhards** [comment]
> For well known CA's no need to provide CA certificate

No, this is not expected in regard to syslog and would be very insecure - a myriad of systems can have a matching cert. But if you do not care about man-in-the-middle attacks, you can use completely anonymous mode. Maybe your version is too old to support this. Try the current one. But it's still a bad idea IMHO.
