### ISSUE TITLE
rsyslog-imptcp package on OBS for Debian Unstable missing module

### ISSUE THREAD

**Issue by skupkosk** [rsyslog/rsyslog#3734]
### Expected behavior
The imptcp.so should be installed.

### Actual behavior
Only changelogs are installed with package.
```
~# dpkg -L rsyslog-imptcp
/.
/usr
/usr/share
/usr/share/doc
/usr/share/doc/rsyslog-imptcp
/usr/share/doc/rsyslog-imptcp/changelog.Debian.gz
/usr/share/doc/rsyslog-imptcp/changelog.gz
```

### Steps to reproduce the behavior
Install package.

### Environment
- rsyslog version: 8.1905 from OBS repositories
- platform: Debian 10

**Comment by rgerhards** [comment]
I fixed this yesterday.
