### ISSUE TITLE
Rsyslog 8.32.0 is still writing in syslog simultaneously with specified log file

### ISSUE THREAD

**Issue by sigtryggr** [rsyslog/rsyslog#3742]
Rsyslog 8.32.0 on Ubuntu 18.04 is still writing in /var/log/syslog simultaneously with specified log file. 
There's a configguration of /etc/rsyslog.d/iptables.conf:

**:msg,contains,"**dropped_ones**" /var/log/iptables_dropped.log
&stop**

By the way, there is no difference whether **&stop** or **&~** is used in configuration. Using or avoiding of space (**&stop** or **& stop**) also haven't any effect.

**Comment by davidelang** [comment]
please post your entire config, if this is after the write to /var/log/syslog, 
this is what is expected.

it's going to depend on where the include statement is in /etc/rsyslog.conf

stop and ~ have identical meaning.

David Lang

**Comment by sigtryggr** [comment]
module(load="imuxsock") # provides support for local system logging
module(load="immark")  # provides --MARK-- message capability

# provides UDP syslog reception
#module(load="imudp")
#input(type="imudp" port="514")

# provides TCP syslog reception
#module(load="imtcp")
#input(type="imtcp" port="514")

# provides kernel logging support and enable non-kernel klog messages
module(load="imklog" permitnonkernelfacility="on")

###########################
#### GLOBAL DIRECTIVES ####
###########################

#
# Use traditional timestamp format.
# To enable high precision timestamps, comment out the following line.
#
$ActionFileDefaultTemplate RSYSLOG_TraditionalFileFormat

# Filter duplicated messages
$RepeatedMsgReduction on

#
# Set the default permissions for all log files.
#
$FileOwner syslog
$FileGroup adm
$FileCreateMode 0640
$DirCreateMode 0755
$Umask 0022
$PrivDropToUser syslog
$PrivDropToGroup syslog

#
# Where to place spool and state files
#
$WorkDirectory /var/spool/rsyslog

#
# Include all config files in /etc/rsyslog.d/
#
$IncludeConfig /etc/rsyslog.d/*.conf

**Comment by davidelang** [comment]
Ok, you have all output in files in /etc/rsyslog.d

please post all of those files (including their filename)

note, if you were using the latest version, there is a -o option that has 
rsyslogd output the config as it sees it, which makes seeing what happens very 
easy.

I'm pretty sure that the problem here is just that the order isn't what you 
think it is.

there were some versions (I think older than 8.32) where files were included in 
reverse alpha sort order due to a bug

David Lang

**Comment by sigtryggr** [comment]
There's a file 50-default.conf contents:

#  Default rules for rsyslog.
#
#                       For more information see rsyslog.conf(5) and /etc/rsyslog.conf

#
# First some standard log files.  Log by facility.
#
auth,authpriv.*                 /var/log/auth.log
*.*;auth,authpriv.none          -/var/log/syslog
#cron.*                         /var/log/cron.log
#daemon.*                       -/var/log/daemon.log
kern.*                          -/var/log/kern.log
#lpr.*                          -/var/log/lpr.log
mail.*                          -/var/log/mail.log
#user.*                         -/var/log/user.log

#
# Logging for the mail system.  Split it up so that
# it is easy to write scripts to parse these files.
#
#mail.info                      -/var/log/mail.info
#mail.warn                      -/var/log/mail.warn
mail.err                        /var/log/mail.err

#
# Some "catch-all" log files.
#
#*.=debug;\
#       auth,authpriv.none;\
#       news.none;mail.none     -/var/log/debug
#*.=info;*.=notice;*.=warn;\
#       auth,authpriv.none;\
#       cron,daemon.none;\
#       mail,news.none          -/var/log/messages

#
# Emergencies are sent to everybody logged in.
#
*.emerg                         :omusrmsg:*

#
# I like to have messages displayed on the console, but only on a virtual
# console I usually leave idle.
#
#daemon,mail.*;\
#       news.=crit;news.=err;news.=notice;\
#       *.=debug;*.=info;\
#       *.=notice;*.=warn       /dev/tty8

**Comment by sigtryggr** [comment]
file iptables.conf contents:

:msg,contains,"dropped_ones" /var/log/iptables_dropped.log
&stop

**Comment by sigtryggr** [comment]
Another question - what's a meaning of such naming like 50-default.conf? Why not a simple "default.conf"?

**Comment by davidelang** [comment]
On Thu, 11 Jul 2019, sigtryggr wrote:

> Another question - what's a meaning of such naming like 50-default.conf? Why not a simple "default.conf"?

when you read a bunch of files in, the order matters, and so by putting a number 
at the beginning you can specify the order.

In this case, 50-* is before iptables-* in an alphabetical sort, so it delivers 
the logs to every destination specified in 50-* and then also delivers it to 
your iptables-* destination, and then throws the log away.

you need your iptables snippet to be ahead of the stuff in the 50-* file.

David Lang

**Comment by alesbobek** [comment]
I can confirm same behavior on 18.04.3 LTS, 8.32.0-1ubuntu4. Rsyslog route to specified location according to filter, but still also continue to syslog.

**Comment by alesbobek** [comment]
Solved issue. Solution is to place custom filter BEFORE default one.

Previous rsyslog versions had include line /etc/rsyslog.d/ before defaults.

**Comment by rgerhards** [comment]
> Previous rsyslog versions had include line /etc/rsyslog.d/ before defaults.

that's why we (the rsyslog team) recommend to not overdue includes. The way ubuntu has set up it's rules is not in the spirit it was designed for. The drop-in directory is not meant for user config, just for snippets that OS packages want to drop. Best is to keep all config in one file.

**Comment by davidelang** [comment]
On Tue, 26 Nov 2019, Rainer Gerhards wrote:

>> Previous rsyslog versions had include line /etc/rsyslog.d/ before defaults.
>
> that's why we (the rsyslog team) recommend to not overdue includes. The way 
> ubuntu has set up it's rules is not in the spirit it was designed for. The 
> drop-in directory is not meant for user config, just for snippets that OS 
> packages want to drop. Best is to keep all config in one file.

This sort of thing is why rsyslog gained the -o flag recently to let it dump the 
config as rsyslog actually sees it (the 'one file' version), unfortuantly this 
actually requires starting rsyslog, not just going through the parsing portions, 
so it's not as good a debugging tool as it could be)

When you have your config managed by some other tools (and especially when there 
are multiple other tools), dropping files in the directory is a very valuable 
thing to do. Unfortunantly people tend to make the mistake of thinking that 
things they do in one of these included files only affect that file

David Lang
