### ISSUE TITLE
Template and regex extraction failes when lowercase s i found

### ISSUE THREAD

**Issue by PejeDK** [rsyslog/rsyslog#3744]
### Expected behavior
Expeced to find the full username regarding of numbers and letters in the name.

### Actual behavior
Finds the string user=XXXX and it extract the XXXX part for the custom property.
But, if a user has lowercase s in its login name it stop the extraction.
Example: If the username is networkusr001 the username extracted would be networku

Uppercase S works fine only the lowercase s is affected.

Is this a knonw behaviour / bug or am i misunderstanding something in the config.

### Steps to reproduce the behavior
Using the logger command to input the same log entry where the username are changed so can test different scenarios .

### Environment
rsyslog version : 8.32.0
Ubuntu version : 18.04

Template property:  constant(value="\",\"user\":\"") property(name="msg" regex.type="ERE" regex.submatch="1" regex.expression="\\buser=\\b([^\\s]+)" regex.nomatchmode="DFLT")

Regex : \buser=\b([^\s]+)

template(name="testtemplate" type="list" option.json="on") {
  constant(value="{")
    constant(value="\"@timestamp\":\"") property(name="timereported" dateFormat="rfc3339")
    constant(value="\",\"message\":\"") property(name="msg")
    constant(value="\",\"host\":\"") property(name="hostname")
    constant(value="\",\"severity\":\"") property(name="syslogseverity-text")
    constant(value="\",\"facility\":\"") property(name="syslogfacility-text")
    constant(value="\",\"syslogtag\":\"") property(name="syslogtag")
    constant(value="\",\"name\":\"") property(name="programname")
    constant(value="\",\"pid\":\"") property(name="procid")

    constant(value="\",\"user\":\"") property(name="msg" regex.type="ERE" regex.submatch="0" regex.expression="\\buser=\\b([^\\s]+)" regex.nomatchmode="DFLT")

constant(value="\"}")
}

**Comment by rgerhards** [comment]
This doesn't look like a correct ERE expression to me, but I am not really fluent with them. See https://en.wikibooks.org/wiki/Regular_Expressions/POSIX-Extended_Regular_Expressions

Note: we just pass the string to the regex lib. It does whatever it does...

**Comment by PejeDK** [comment]
Within the template the \ are escaped.
Is that what you find strange looking ??

**Comment by rgerhards** [comment]
No - I do not see a description for `\s` in ERE. Did you try the regex checker at https://www.rsyslog.com/regex/ - It's not perfect, because OS libs may be different but it provides a first idea.

**Comment by PejeDK** [comment]
Gotcha.
Found it here: https://remram44.github.io/regex-cheatsheet/regex.html

Regarding the https://www.rsyslog.com/regex/, i have never received a result from the test.
Tried multiple things in different browers, i just get a empty result every time.
Have even tried 1234 lamplight PO box 9 and regex [[:digit:]] and still no result

**Comment by PejeDK** [comment]
Changed it to \buser=\b([^[:space:]]+) and it seems to work now.
I will test further but thanks for the hint
