### ISSUE TITLE
Is there a way to wait for buffers to flush?

### ISSUE THREAD

**Issue by ClydeByrdIII** [rsyslog/rsyslog#3749]
### Problem
I have a systemd service that is only activated on failure of some critical service.
This unit just logs to rsyslogd via logger command and then restarts the container.
The issue is that I'm not seeing the messages in the logs. 

Things I tried that didn't work:
Attempt 1:
ExecStart=/usr/bin/logger -p daemon.emerg "Failure service"
ExecStart=/bin/pkill --signal HUP rsyslogd

Attempt 2:
ExecStart=/usr/bin/logger -p daemon.emerg "Failure service"
ExecStart=/bin/pkill --signal HUP rsyslogd
ExecStopPost=/bin/systemctl stop rsyslog

Things that did work:
Attempt 3:
ExecStart=/usr/bin/logger -p daemon.emerg "Failure service"
ExecStart=/bin/sleep 1

Attempt 4:
ExecStart=/usr/bin/logger -p daemon.emerg "Failure service"
ExecStopPost=/bin/systemctl restart rsyslog

How can I guarantee that buffers are flushed to disk on shutdown of rsyslogd or at least wait until buffers are flushed to disk?

I realize pkill --signal HUP is an asynchronous operation so it's possible for my system to shut down before the janitor is ran. 

Is there a way for a service to wait until rsyslogd flushes buffers? Or a way to invoke the janitor process and wait for it to finish? The sleep/restart daemon before shutdown approach seems very hacky and I want something guaranteed to work.

### Expected behavior
I expect the messages to be flushed to disk on shutdown of rsyslogd

### Actual behavior
Messages are lost.

### Steps to reproduce the behavior
The logfile is setup via
  action(type="omfile"
    template="Container"
    dirCreateMode="0755"
    fileCreateMode="0644"
    file="/logs/stderr"
    dynafile="ContainerStdErr"
  )

I execute systemctl start failure.service and check the logs on disk after the container restarts.
[Unit]
Description=Failure Service
After=rsyslog.service
SuccessAction=exit
SuccessActionExitStatus=6
FailureAction=exit
FailureActionExitStatus=6

[Service]
Type=oneshot
ExecStart=/usr/bin/logger -p daemon.emerg "Failure service"

### Environment
rsyslogd 8.24.0
PLATFORM: x86_64-redhat-linux-gnu
systemd: 241

**Comment by rgerhards** [comment]
Are there many messages to write out? With few messages, writing should be very quickly. The janitor is irrelevant - it just does housekeeping. Files are written as soon as data is ready.

You could build the imdiag module yourself. It is a testbench tool which has the capability to query internal queue status and wait until the queues are empty.

I remember that quite a while ago we had a bug where buffers were not flushed immediately. Maybe your version has this bug (8.24 is from January 2017, roughly 35 versions back to current).

**Comment by ClydeByrdIII** [comment]
Thanks for the response!

> Are there many messages to write out?

These are the only two log messages that are needed to write out at the time.

> You could build the imdiag module yourself.

I'm not able to find much docs on imdiag, but would I have to significantly duplicate what omfile does on top of adding this "wait until queues are empty" during shutdown functionality?

> Maybe your version has this bug

I'll try to update to a later version first. It's a bit complicated because I'd need to update it for millions of hosts + their containers, so it's usually not my first option, but it's the best option right now.

In general is it true to say that rsyslogd should flushes buffers on shutdown??

**Comment by ClydeByrdIII** [comment]
Installed the latest in a single container. Seems like it still failed to flush :( Guess I'll just have to go  with the hacky sleep/restart rsyslog solution.

**Comment by rgerhards** [comment]
It might be that the message arrives after rsyslog shutdown. Could you create a debug log so that I can see what exactly happens? If there is still interest, of course...
