### ISSUE TITLE
Rsyslog - imkafka: consumers iddle

### ISSUE THREAD

**Issue by Karl90** [rsyslog/rsyslog#3765]
Dear Rsyslog Team,

First of all, I want you to thank you by developing such great software,
it is robust, scalable and flexible which let us meet our goals.

I'd like to let you know that we've discovered an undesired behaviour - it is present on the kafka module for consumption (omkafka)

I have 8 instances of rsyslog running, consuming from certain Kafka topic with the same consumer group (this is done on pourpouse)

rsyslog-consumer-data-loader-7bb99d54f7-9zxhs   2/2     Running   0          31m
rsyslog-consumer-data-loader-7bb99d54f7-bxnz5   2/2     Running   0          31m
rsyslog-consumer-data-loader-7bb99d54f7-gcjwg   2/2     Running   0          31m
rsyslog-consumer-data-loader-7bb99d54f7-gz8g6   2/2     Running   0          31m
rsyslog-consumer-data-loader-7bb99d54f7-krttm   2/2     Running   0          31m
rsyslog-consumer-data-loader-7bb99d54f7-qnk9c   2/2     Running   0          31m
rsyslog-consumer-data-loader-7bb99d54f7-tngfp   2/2     Running   0          31m
rsyslog-consumer-data-loader-7bb99d54f7-tsj62   2/2     Running   0          31m

However, we've realized that actually only one of the instances is actually receiving messages, the rest (7 instances) of them doesn't, when enabling the debug:

2112.347935347:7fe7eabfb700: imkafka.c: imkafka: msgConsume EMPTY Loop on proxy-uat/rsyslog-subscribed-cg/kafka-cluster-broker:9093
2113.447221544:7fe7eabfb700: imkafka.c: imkafka: msgConsume EMPTY Loop on proxy-uat/rsyslog-subscribed-cg/kafka-cluster-broker:9093
2114.546512540:7fe7eabfb700: imkafka.c: imkafka: msgConsume EMPTY Loop on proxy-uat/rsyslog-subscribed-cg/kafka-cluster-broker:9093
2115.645840937:7fe7eabfb700: imkafka.c: imkafka: msgConsume EMPTY Loop on proxy-uat/rsyslog-subscribed-cg/kafka-cluster-broker:9093

My goal is to have 8 instances consuming from the topic (proxy-uat), under the same consumer group (rsyslog-subscribed-cg) - to distribute the load. 
In theory, all the records and processing should be load balanced: Each message would be consumed by one consumer of the group only. Each partition is connected to at most one consumer from a group.
We have 24 partitions for the topic on the Kafka cluster, so enough room to process these messages - so we should not have iddle consumers (which seems to be the case)

Note that all of them has exactly the same configuration and runs independently in their own host (actually are docker instances),
we've also seen that once the "rsyslog active instance" is stopped, another one takes the lead and began to process.

Should you have any questions, or need more info, just let me know it.
So, please, can you review this?

Best regards,

Karl.

~      

### Expected behavior

All the Rsyslog Instances should consume the messages from the same consumer group, in a load balanced way.

### Actual behavior

Only one rsyslog instance is actually consuming (all) the messages from the consumer group.

### Steps to reproduce the behavior

run multiple rsyslog instances with the same kafka config for consumption: subscribed to the same topic under the same consumer group (of course in the same kafka cluster)

Note that you should have >1 topic's partitions, otherwise with just 1 partition it is expected: have more consumers under the same consumer group with just 1 partition make the rest iddle.

In the example shown, we have 8 consumers under the same consumer group for a topic with 24 partitions and only 1 consumer is actually working.

### Environment
- rsyslog version: 8.1905.0 

# rsyslogd -v
rsyslogd  8.1905.0 (aka 2019.05) compiled with:
        PLATFORM:                               x86_64-redhat-linux-gnu
        PLATFORM (lsb_release -d):
        FEATURE_REGEXP:                         Yes
        GSSAPI Kerberos 5 support:              Yes
        FEATURE_DEBUG (debug build, slow code): No
        32bit Atomic operations supported:      Yes
        64bit Atomic operations supported:      Yes
        memory allocator:                       system default
        Runtime Instrumentation (slow code):    No
        uuid support:                           Yes
        systemd support:                        Yes
        Config file:                            /etc/rsyslog.conf
        PID file:                               /var/run/syslogd.pid
        Number of Bits in RainerScript integers: 64

See https://www.rsyslog.com for more information.
#

- platform: CentOS Linux release 7.6.1810 (Core) (running as container) 
- for configuration questions/issues, include rsyslog.conf and included config files: we don't have config question/issue, it seems to be a bug.

**Comment by rgerhards** [comment]
@alorbach is that an issue in rsyslog code or in librdkafka?

**Comment by Karl90** [comment]
Hi,

librrdkafka does supports balanced consumer groups:

https://github.com/edenhill/librdkafka/wiki/FAQ
https://github.com/edenhill/librdkafka/issues/601#issuecomment-208354621

Please, can you take a look on rsyslog side?

Thanks in advance!

regards,

karl.

**Comment by alorbach** [comment]
Could be a configuration issue. 
Can you post minimal configuration sets (with 2 rsyslgo configurations) needed to reproduce the problem? Also including a minimal kafka zookeeper configuration.

**Comment by Karl90** [comment]
Hi,

Sure, this is the configuration used by the rsyslog instances for imkafka:

input(
        type="imkafka"
        topic="proxy-uat"
        broker=["kafka-cluster-broker:9093"]
        confParam=["security.protocol=SASL_SSL", "sasl.mechanisms=PLAIN", "sasl.username=<UserName>", "sasl.password=<Password>"]
        consumergroup="rsyslog-subscribed-cg"
        ruleset="subscribed_eh_messages"
)

all the instances has exactly the same configuration. I've also tested on bare servers with the same result: only one instance is actively receiving messages while the other one is idle. once I shutdown the "active one" the other began to receive messages.

I've also tried playing with another properties such as:

#Attempt1:
        confParam=["partition.assignment.strategy=roundrobin", "topic.offset.store.method=broker", "session.timeout.ms=60000", "group.id=rsyslog", "security.protocol=SASL_SSL", "sasl.mechanisms=PLAIN", "sasl.username=<UserName>", "sasl.password=<Password>"]

#Attempt2:
        confParam=["partition.assignment.strategy=roundrobin", "topic.offset.store.method=broker", "topic.enable.auto.commit=false", "session.timeout.ms=60000", "group.id=rsyslog", "security.protocol=SASL_SSL", "sasl.mechanisms=PLAIN", "sasl.username=<UserName>", "sasl.password=<Password>"]

but nothing changes, only one instance is actively receiving the messages.
These are the properties available for the library: https://docs.confluent.io/2.0.0/clients/librdkafka/CONFIGURATION_8md.html

BTW, I don't have the zookeeper configuration, I'm using a Kafka PaaS - Azure Event Hubs,
which does supports the consumer group:
https://docs.microsoft.com/en-us/azure/event-hubs/event-hubs-features#consumer-groups

Thanks in advance for the help!

regards,

Karl.

**Comment by Karl90** [comment]
I also update the title, since this affects to the message consumption - the module imkafka, not the output one.

**Comment by Karl90** [comment]
Dear Team,

Could you verify the issue described?

Regards,

Karl

**Comment by alorbach** [comment]
Sorry for the delayed response. I have reviewed your rsyslog part configuration and don't see any problem with it. 

As the other consumers start to get data when you turn of the primary one, it looks to be that this behavior is wanted by the server side kafka configuration. 

If you review the kafka configuration there are many options to control the behavior (Like group.max.size): https://kafka.apache.org/documentation/

If you can't get to the kafka configuration I would recommend to just use seperated consumer groups per rsyslog instance like our testbench test imkafka_multi_many.sh does: 
https://github.com/rsyslog/rsyslog/blob/master/tests/imkafka_multi_many.sh

**Comment by Karl90** [comment]
Hi Team,

I don’t think that it is caused by the Kafka Cluster configuration, It is
actually supposed to support multiple consumers inside a consumer group,
but I will double check it.

So, have you been able to launch 2 instances and consume messages in both
of them ?

Note that have 2 different consumer groups is not a solution, since both of
them would receive the same messages - then I would process duplicate
messages and not splitting the load across the consumers ,

Regards,

Karl

**Comment by alorbach** [comment]
@Karl: We can create a test case for this particular environment with 2 consumers, and see what happens.

**Comment by rgerhards** [comment]
@alorbach If I understood the postings right, the applications needs to provide some callbacks. Link to sample code is posted somewhere above. Not sure if we do that. I'd say a test would be a good starting point. I guess, though, it's not something you need to rush before taking off some time.

**Comment by alorbach** [comment]
No I think the callback is only needed if you want to decide which consumer gets the partition yourself. If no callback is set, librdkafka will use random assigment: 
https://github.com/edenhill/librdkafka/blob/d3f6e5e9d46ed4877c9f8e07f86dfe0698447177/src/rdkafka.h#L1578

So this should actually work with our code., thats why I want to create a test to verify it.

**Comment by alorbach** [comment]
@Karl90 I have created a testcase for this issue and it appears to be working properly with our kafka testbench configuration.

The test uses two rsyslog instances with one imkafka input assigned to the same consumergroup. I always had like 49-51% of all messages on each instance during testing.

**Comment by Karl90** [comment]
Hi Team,

Thanks a lot for your feedback, 
Please, just in case, can you share the config used? 

From your description, rsyslog does works properly and seems to be kafka cluster issue, so we can close this one.

Thanks a lot for your attention, 

Regards, 

Karl.

**Comment by rgerhards** [comment]
Have a look at the kafka files inside the testbench

  https://github.com/rsyslog/rsyslog/tree/master/tests/testsuites

especially https://github.com/rsyslog/rsyslog/blob/master/tests/testsuites/kafka-server.dep_wrk1.properties

@alorbach's PR contains the full test, so you can check exactly what it does.

**Comment by Karl90** [comment]
Dear Team,

Thanks a lot for your clarifications,

Regards,

Karl.
