### ISSUE TITLE
rsyslog coredump,

### ISSUE THREAD

**Issue by y123456yz** [rsyslog/rsyslog#3766]
root@fd-mongos-p00.ys:/home/yyz/rsyslog-master$ /usr/sbin/rsyslogd -n
*** Error in `/usr/sbin/rsyslogd': free(): invalid pointer: 0x00007f05e9a18c71 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x7cfe1)[0x7f05e7592fe1]
/lib64/libjansson.so.4(json_delete+0x41)[0x7f05e6685911]
/lib64/libjansson.so.4(json_delete+0x85)[0x7f05e6685955]
/lib64/libnss_sven.so.2(+0x11ea)[0x7f05e688b1ea]
/lib64/libnss_sven.so.2(get_entry_by_name+0x16b)[0x7f05e688b357]
/lib64/libnss_sven.so.2(_nss_sven_getpwnam_r+0x4c)[0x7f05e688bdb2]
/lib64/libc.so.6(getpwnam_r+0xdd)[0x7f05e75d25ad]
/usr/sbin/rsyslogd(+0x4b887)[0x7f05e8db5887]
/usr/sbin/rsyslogd(processCfSysLineCommand+0xef)[0x7f05e8db619f]
/usr/sbin/rsyslogd(cfsysline+0x54)[0x7f05e8d94044]
/usr/sbin/rsyslogd(cnfDoCfsysline+0x2c)[0x7f05e8d973fc]
/usr/sbin/rsyslogd(yylex+0x161b)[0x7f05e8d898fb]
/usr/sbin/rsyslogd(yyparse+0x60b)[0x7f05e8d86deb]
/usr/sbin/rsyslogd(load+0xc44)[0x7f05e8d96d44]
/usr/sbin/rsyslogd(realMain+0x963)[0x7f05e8d7c323]
/lib64/libc.so.6(__libc_start_main+0xf5)[0x7f05e7537b15]
/usr/sbin/rsyslogd(+0x106b9)[0x7f05e8d7a6b9]
======= Memory map: ========
7f05e0000000-7f05e0021000 rw-p 00000000 00:00 0 
7f05e0021000-7f05e4000000 ---p 00000000 00:00 0 
7f05e667e000-7f05e6689000 r-xp 00000000 08:03 1860897                    /usr/lib64/libjansson.so.4.4.0
7f05e6689000-7f05e6888000 ---p 0000b000 08:03 1860897                    /usr/lib64/libjansson.so.4.4.0
7f05e6888000-7f05e6889000 r--p 0000a000 08:03 1860897                    /usr/lib64/libjansson.so.4.4.0
7f05e6889000-7f05e688a000 rw-p 0000b000 08:03 1860897                    /usr/lib64/libjansson.so.4.4.0
7f05e688a000-7f05e688e000 r-xp 00000000 08:03 1860208                    /usr/lib64/libnss_sven.so
7f05e688e000-7f05e6a8d000 ---p 00004000 08:03 1860208                    /usr/lib64/libnss_sven.so
7f05e6a8d000-7f05e6a8e000 rw-p 00003000 08:03 1860208                    /usr/lib64/libnss_sven.so
7f05e6a8e000-7f05e6a99000 r-xp 00000000 08:03 1836006                    /usr/lib64/libnss_files-2.17.so
7f05e6a99000-7f05e6c98000 ---p 0000b000 08:03 1836006                    /usr/lib64/libnss_files-2.17.so
7f05e6c98000-7f05e6c99000 r--p 0000a000 08:03 1836006                    /usr/lib64/libnss_files-2.17.so
7f05e6c99000-7f05e6c9a000 rw-p 0000b000 08:03 1836006                    /usr/lib64/libnss_files-2.17.so
7f05e6c9a000-7f05e6ca0000 rw-p 00000000 00:00 0 
7f05e6ca0000-7f05e6ca4000 r-xp 00000000 08:03 2230224                    /usr/lib64/rsyslog/imudp.so
7f05e6ca4000-7f05e6ea4000 ---p 00004000 08:03 2230224                    /usr/lib64/rsyslog/imudp.so
7f05e6ea4000-7f05e6ea5000 r--p 00004000 08:03 2230224                    /usr/lib64/rsyslog/imudp.so
7f05e6ea5000-7f05e6ea6000 rw-p 00005000 08:03 2230224                    /usr/lib64/rsyslog/imudp.so
7f05e6ea6000-7f05e6eaa000 r-xp 00000000 08:03 2230219                    /usr/lib64/rsyslog/imklog.so
7f05e6eaa000-7f05e70a9000 ---p 00004000 08:03 2230219                    /usr/lib64/rsyslog/imklog.so
7f05e70a9000-7f05e70aa000 r--p 00003000 08:03 2230219                    /usr/lib64/rsyslog/imklog.so
7f05e70aa000-7f05e70ab000 rw-p 00004000 08:03 2230219                    /usr/lib64/rsyslog/imklog.so
7f05e70ab000-7f05e7108000 r-xp 00000000 08:03 2230225                    /usr/lib64/rsyslog/imuxsock.so
7f05e7108000-7f05e7307000 ---p 0005d000 08:03 2230225                    /usr/lib64/rsyslog/imuxsock.so
7f05e7307000-7f05e730a000 r--p 0005c000 08:03 2230225                    /usr/lib64/rsyslog/imuxsock.so
7f05e730a000-7f05e730f000 rw-p 0005f000 08:03 2230225                    /usr/lib64/rsyslog/imuxsock.so
7f05e730f000-7f05e7310000 rw-p 00000000 00:00 0 
7f05e7310000-7f05e7315000 r-xp 00000000 08:03 2230226                    /usr/lib64/rsyslog/lmnet.so
7f05e7315000-7f05e7514000 ---p 00005000 08:03 2230226                    /usr/lib64/rsyslog/lmnet.so
7f05e7514000-7f05e7515000 r--p 00004000 08:03 2230226                    /usr/lib64/rsyslog/lmnet.so
7f05e7515000-7f05e7516000 rw-p 00005000 08:03 2230226                    /usr/lib64/rsyslog/lmnet.so
7f05e7516000-7f05e76cc000 r-xp 00000000 08:03 1835988                    /usr/lib64/libc-2.17.so
7f05e76cc000-7f05e78cc000 ---p 001b6000 08:03 1835988                    /usr/lib64/libc-2.17.so
7f05e78cc000-7f05e78d0000 r--p 001b6000 08:03 1835988                    /usr/lib64/libc-2.17.so
7f05e78d0000-7f05e78d2000 rw-p 001ba000 08:03 1835988                    /usr/lib64/libc-2.17.so
7f05e78d2000-7f05e78d7000 rw-p 00000000 00:00 0 
7f05e78d7000-7f05e78ec000 r-xp 00000000 08:03 1831443                    /usr/lib64/libgcc_s-4.8.5-20150702.so.1
7f05e78ec000-7f05e7aeb000 ---p 00015000 08:03 1831443                    /usr/lib64/libgcc_s-4.8.5-20150702.so.1
7f05e7aeb000-7f05e7aec000 r--p 00014000 08:03 1831443                    /usr/lib64/libgcc_s-4.8.5-20150702.so.1
7f05e7aec000-7f05e7aed000 rw-p 00015000 08:03 1831443                    /usr/lib64/libgcc_s-4.8.5-20150702.so.1
7f05e7aed000-7f05e7af1000 r-xp 00000000 08:03 1836451                    /usr/lib64/libuuid.so.1.3.0
7f05e7af1000-7f05e7cf0000 ---p 00004000 08:03 1836451                    /usr/lib64/libuuid.so.1.3.0
7f05e7cf0000-7f05e7cf1000 r--p 00003000 08:03 1836451                    /usr/lib64/libuuid.so.1.3.0
7f05e7cf1000-7f05e7cf2000 rw-p 00004000 08:03 1836451                    /usr/lib64/libuuid.so.1.3.0
7f05e7cf2000-7f05e7cfc000 r-xp 00000000 08:03 1836840                    /usr/lib64/libjson-c.so.2.0.1
7f05e7cfc000-7f05e7efb000 ---p 0000a000 08:03 1836840                    /usr/lib64/libjson-c.so.2.0.1
7f05e7efb000-7f05e7efc000 r--p 00009000 08:03 1836840                    /usr/lib64/libjson-c.so.2.0.1
7f05e7efc000-7f05e7efd000 rw-p 0000a000 08:03 1836840                    /usr/lib64/libjson-c.so.2.0.1
7f05e7efd000-7f05e7f00000 r-xp 00000000 08:03 1852921                    /usr/lib64/libestr.so.0.0.0
7f05e7f00000-7f05e80ff000 ---p 00003000 08:03 1852921                    /usr/lib64/libestr.so.0.0.0
7f05e80ff000-7f05e8100000 r--p 00002000 08:03 1852921                    /usr/lib64/libestr.so.0.0.0
7f05e8100000-7f05e8101000 rw-p 00003000 08:03 1852921                    /usr/lib64/libestr.so.0.0.0
7f05e8101000-7f05e8108000 r-xp 00000000 08:03 1836018                    /usr/lib64/librt-2.17.so
7f05e8108000-7f05e8307000 ---p 00007000 08:03 1836018                    /usr/lib64/librt-2.17.so
7f05e8307000-7f05e8308000 r--p 00006000 08:03 1836018                    /usr/lib64/librt-2.17.so
7f05e8308000-7f05e8309000 rw-p 00007000 08:03 1836018                    /usr/lib64/librt-2.17.so
7f05e8309000-7f05e830c000 r-xp 00000000 08:03 1835994                    /usr/lib64/libdl-2.17.so
7f05e830c000-7f05e850b000 ---p 00003000 08:03 1835994                    /usr/lib64/libdl-2.17.so
7f05e850b000-7f05e850c000 r--p 00002000 08:03 1835994                    /usr/lib64/libdl-2.17.so
7f05e850c000-7f05e850d000 rw-p 00003000 08:03 1835994                    /usr/lib64/libdl-2.17.so
7f05e850d000-7f05e8523000 r-xp 00000000 08:03 1836014                    /usr/lib64/libpthread-2.17.so
7f05e8523000-7f05e8723000 ---p 00016000 08:03 1836014                    /usr/lib64/libpthread-2.17.so
7f05e8723000-7f05e8724000 r--p 00016000 08:03 1836014                    /usr/lib64/libpthread-2.17.so
7f05e8724000-7f05e8725000 rw-p 00017000 08:03 1836014                    /usr/lib64/libpthread-2.17.so
7f05e8725000-7f05e8729000 rw-p 00000000 00:00 0 
7f05e8729000-7f05e873e000 r-xp 00000000 08:03 1836420                    /usr/lib64/libz.so.1.2.7
7f05e873e000-7f05e893d000 ---p 00015000 08:03 1836420                    /usr/lib64/libz.so.1.2.7
7f05e893d000-7f05e893e000 r--p 00014000 08:03 1836420                    /usr/lib64/libz.so.1.2.7
7f05e893e000-7f05e893f000 rw-p 00015000 08:03 1836420                    /usr/lib64/libz.so.1.2.7
7f05e893f000-7f05e8945000 r-xp 00000000 08:03 1051676                    /usr/local/gundam/gundam_client/preload/lib64/gundam_preload.so
7f05e8945000-7f05e8b44000 ---p 00006000 08:03 1051676                    /usr/local/gundam/gundam_client/preload/lib64/gundam_preload.so
7f05e8b44000-7f05e8b45000 r--p 00005000 08:03 1051676                    /usr/local/gundam/gundam_client/preload/lib64/gundam_preload.so
7f05e8b45000-7f05e8b46000 rw-p 00006000 08:03 1051676                    /usr/local/gundam/gundam_client/preload/lib64/gundam_preload.so
7f05e8b46000-7f05e8b67000 r-xp 00000000 08:03 1835981                    /usr/lib64/ld-2.17.so
7f05e8d3e000-7f05e8d45000 rw-p 00000000 00:00 0 
7f05e8d65000-7f05e8d67000 rw-p 00000000 00:00 0 
7f05e8d67000-7f05e8d68000 r--p 00021000 08:03 1835981                    /usr/lib64/ld-2.17.so
7f05e8d68000-7f05e8d69000 rw-p 00022000 08:03 1835981                    /usr/lib64/ld-2.17.so
7f05e8d69000-7f05e8d6a000 rw-p 00000000 00:00 0 
7f05e8d6a000-7f05e8de7000 r-xp 00000000 08:03 1860779                    /usr/sbin/rsyslogd
7f05e8fe7000-7f05e8fe9000 r--p 0007d000 08:03 1860779                    /usr/sbin/rsyslogd
7f05e8fe9000-7f05e8fef000 rw-p 0007f000 08:03 1860779                    /usr/sbin/rsyslogd
7f05e8fef000-7f05e8ff0000 rw-p 00000000 00:00 0 
7f05e99f8000-7f05e9a34000 rw-p 00000000 00:00 0                          [heap]
7ffd5ee1d000-7ffd5ee3e000 rw-p 00000000 00:00 0                          [stack]
7ffd5ee8a000-7ffd5ee8c000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
Aborted (core dumped)

centos7
Linux fd-mongos-p00.ys 3.10.0-327.36.3.el7.x86_64 #1 SMP Mon Oct 24 16:09:20 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

root@fd-mongos-p00.ys:/home/yyz/rsyslog-master$ rpm -qa | grep rsyslog
rsyslog-7.4.7-12.el7.x86_64
rsyslog-mmjsonparse-7.4.7-12.el7.x86_64

**Comment by rgerhards** [comment]
Please upgrade to rsyslog current. This is a very outdated version. Else please contact your distro support.
