### ISSUE TITLE
rsyslog 8.1901.0 stuck on recvfrom with imtcp and gnutls

### ISSUE THREAD

**Issue by filippog** [rsyslog/rsyslog#3770]
### Expected behavior
rsyslog TLS listener keeps accepting connections and processing traffic

### Actual behavior
rsyslog receiver gets stuck in a `recvfrom` loop similar to what's described in #318

### Steps to reproduce the behavior
Unclear, although anecdotally related to sender hosts or going down. See also task https://phabricator.wikimedia.org/T199406 for more information/context

### Environment
- rsyslog version: rsyslogd  8.1901.0 (aka 2019.01)
- platform: Debian 10 (Buster) with gnutls 3.6.7, happens on Debian Jessie with gnutls 3.3.30 too
- for configuration questions/issues, include rsyslog.conf and included config files

There are two central rsyslog servers receiving logs over a number of inputs (tcp, udp, kafka) the busiest one is tcp + (gnu)tls at ~5k messages/s from ~1.5k hosts. From time to time rsyslog would get stuck in a `recvfrom` loop:

```
21108 recvfrom(1465, 0x7f5e053eee63, 278, 0, NULL, NULL) = -1 EAGAIN (Resource temporarily unavailable)
21108 recvfrom(1465, 0x7f5e053eee63, 278, 0, NULL, NULL) = -1 EAGAIN (Resource temporarily unavailable)
21108 recvfrom(1465, 0x7f5e053eee63, 278, 0, NULL, NULL) = -1 EAGAIN (Resource temporarily unavailable)
21108 recvfrom(1465, 0x7f5e053eee63, 278, 0, NULL, NULL) = -1 EAGAIN (Resource temporarily unavailable)
21108 recvfrom(1465, 0x7f5e053eee63, 278, 0, NULL, NULL) = -1 EAGAIN (Resource temporarily unavailable)
21108 recvfrom(1465, 0x7f5e053eee63, 278, 0, NULL, NULL) = -1 EAGAIN (Resource temporarily unavailable)
```

From `lsof` that fd indeed pertains to an host that went down around the same time the busy loop started:

```
rsyslogd 21094 root 1465u     IPv4           28025343        0t0        TCP centrallog1001.eqiad.wmnet:syslog-tls->cloudvirt1015.eqiad.wmnet:34854 (ESTABLISHED)
```

**Comment by filippog** [comment]
Hi, any ideas on what could be causing this or a possible fix ?

**Comment by rgerhards** [comment]
The version you are using is very old and no longer supported by the community. It is also very probable that the problem stems back to long-solved issues. As such, please update to the currently supported version and retry. Report back if the problem persists.

The rsyslog project provides packages for current versions: https://www.rsyslog.com/downloads/download-other/

If you insist on using an outdated version, you can also contact your distro or consider [rsyslog professional services](https://www.rsyslog.com/professional-services/enterprise-support/).

**Comment by filippog** [comment]
Thank you for helpful pointers, we'll try again with 8.2008.0 and report back.

**Comment by filippog** [comment]
I can't reproduce this with 8.2008.0 anymore, closing. Thanks @rgerhards !
