### ISSUE TITLE
fix "make distcheck"

### ISSUE THREAD

**Issue by rgerhards** [rsyslog/rsyslog#378]
While it looks like "make distcheck" worked after the recent changes, it did not fully. This wasn't noticed due to a bug in the testbench plumbing, which did not execute the error-exit correctly in all cases (which lead to a false ok status).

**Comment by alorbach** [comment]
Appears to be working now, Issue can proberly be closed.

**Comment by rgerhards** [comment]
jup, works, probably forgotten to close it.

**Comment by rgerhards** [comment]
now a duplicate of #174 as make distcheck tests were totally disable some time ago. Will handle as part of #174.
