### ISSUE TITLE
imjournal plugin truncates messages to 64K regardless of MaxMessageSize or journald's LineMax

### ISSUE THREAD

**Issue by rwdalpe** [rsyslog/rsyslog#3784]
### Expected behavior

If journald and rsyslog have both been configured to allow for messages longer than 64K and the imjournal module is being used, then rsyslog should receive the full content of messages longer than 64K when they're read from the journal (up to the $MaxMessageSize limit).

### Actual behavior

Any message from the journal longer than 64K is truncated to 64K by imjournal, regardless of configuration.

### Steps to reproduce the behavior

1. Configure journald to allow for long lines. Sample `/etc/systemd/journald.conf`:

```
[Journal]
LineMax=100K
```

2. Configure rsyslog to use imjournal and allow for similarly large messages:

```
$MaxMessageSize 102400 
...
$ModLoad imjournal
...
$IMJournalStateFile imjournal.state
# Make sure the systemd unit that you want to use for testing is logging to disk so we can see results. Here's a catch-all as an example:
#*.*;auth,authpriv.none        -/var/log/syslog
```

3. Have any systemd unit that logs to journald produce a log line around 100K in size
4. Check the output file on disk and see that it was truncated to 64K

### Environment
- rsyslog version: 8.24.0
- platform: Amazon Linux 2
- systemd version: 219

### Notes

I think this is happening because of [how imjournal calls sd_journal_get_data](https://github.com/rsyslog/rsyslog/blob/master/plugins/imjournal/imjournal.c#L312).

As described at https://www.freedesktop.org/software/systemd/man/sd_journal_get_data.html :

>Also note that, by default, data fields larger than 64K might get truncated to 64K. This threshold may be changed and turned off with sd_journal_set_data_threshold() (see below).

Maybe a fix is as straightforward as calling sd_journal_set_data_threshold with the value of the $MaxMessageSize when the journal is opened.

**Comment by davidelang** [comment]
8.24 is about 2.5 years old, there have been some pretty significant 
modificatiosn to imjournal over that time. Could you please check that the 
problem still exists with a current version? (at least 8.1904)

David Lang

**Comment by rgerhards** [comment]
@jvymazal can you pls have a look

**Comment by jvymazal** [comment]
will for sure needs verification but in theory this sound about right

**Comment by jvymazal** [comment]
> 8.24 is about 2.5 years old, there have been some pretty significant modificatiosn to imjournal over that time. Could you please check that the problem still exists with a current version? (at least 8.1904) David Lang

There should not be much difference in this particular case, firstly this is part of journal which was touched the least from 8.24 and this being reported on Amazon Linux I would expect my journal patches keeping imjournal on 8.24 up-to-date eventually flow there as well.

**Comment by rwdalpe** [comment]
Unfortunately those versions of rsyslog and systemd are the highest available on a stock Amazon Linux 2 image. I'll see if I can upgrade them somehow this week.

On my local machine, I was not able to reproduce the bug. Here are the versions:

platform: Arch Linux
rsyslog version: 8.1904.0-1
systemd version:  242.84-1

I'll try downgrading just rsyslog locally to see if I can reproduce it. Downgrading just systemd will take a bit longer as I'll need to set up a different environment for that.

**Comment by rwdalpe** [comment]
Could not reproduce the bug on

platform: Arch Linux
rsyslog version: 8.24.0-1
systemd version: 242.84-1

Maybe a default for the data size returned by the `sd_journal_get_data` function changed between systemd 219 and 242.84. I'll work on getting an environment with downgraded systemd for testing.

**Comment by davidelang** [comment]
we don't make fixes for old versions (especially if the current version is 
already fixed). If you can't upgrade from the version that amazon provides, you 
couldn't install a fixed version we provide either.

(note, you can pay Adiscon professional services to fix an old version, but you 
still have the problem of upgrading to it)

David Lang

**Comment by rwdalpe** [comment]
I was able to reproduce the bug on

platform: Centos 7
rsyslog version: 8.1908.0
systemd version: 219.62

Unfortunately, getting a newer version of systemd on centos 7 is a bit more difficult. I'll keep working on that to see if I can demonstrate that upgrading systemd is sufficient to "resolve" the bug.

**Comment by rwdalpe** [comment]
Upgrading from systemd 219 to a newer version requires so many other changes (kernel versions, major libraries, etc.) that I'm not having much success putting together a test of just the systemd upgrade.

Even though the tests were on different platforms, it looks like systemd's behavior (with respect to how imjournal is using it) changed between 219 and current versions. At the very least, the rsyslog version doesn't appear to affect the outcome.

I'm not sure how we want to proceed with this issue report, since upgrading systemd appears to "resolve" the problem. Centos 7 and Amazon Linux 2 are pinned to systemd 219 by default, and so I would imagine that this behavior would continue to appear on those platforms.

The documentation leads me to believe it's the call to sd_journal_get_data that is truncating data. If that's true, my concern would be that the problem resurfaces if systemd's default behavior changes in future releases. It will take me a while to put together a change and test that theory in earnest.

**Comment by rgerhards** [comment]
@jvymazal can you provide some advise?

**Comment by jvymazal** [comment]
If I am reading the report correctly, it seems that problem is tied to old systemd version, in that case my advice is to take this to systemd maintainers and push for a fix there (patching the CentOS/amazon Linux versions as rebases in these are not likely). Other than that I am not sure how I could help.

**Comment by rwdalpe** [comment]
Just to keep this issue updated: I did some more digging and found a potentially interesting patch that Centos7 (and thus presumably Amazon Linux 2) makes to systemd in their RPMs. It _might_ explain this issue. 

I tried to get some confirmation of my theory from the systemd-devel mailing list: https://lists.freedesktop.org/archives/systemd-devel/2019-September/043462.html . There was just one reply, but it seemed to support the hypothesis.

I'll try investigating a little further. If my current theory is accurate (any systemd installation which utilizes libxz instead of liblz4 has this problem), then this could still be an issue for current versions of rsyslog with some current installations of systemd.

**Comment by rwdalpe** [comment]
OK, I think I was able to confirm my hypothesis. I have an Arch Linux VM where I've installed:

* rsyslog 8.1907.0-1
* systemd 243.51-1

Then I cloned the systemd package from https://www.archlinux.org/packages/core/x86_64/systemd/ and rebuilt the package with lz4 support disabled (`-Dlz4=false` as a build option). After installing the rebuilt package, I was able to reproduce the issue. Rebuilding with `-Dlz4=true` and reinstalling made the issue unreproduceable.

So this issue will happen on any system where systemd is using XZ compression instead of LZ4. That happens to be the case for Centos7 and Amazon Linux 2.

**Comment by rwdalpe** [comment]
I'll try making a change to imjournal to see if using sd_journal_set_data_threshold can resolve the problem even when XZ compression is being used.

**Comment by rgerhards** [comment]
@jvymazal do you have an opinion on this?

**Comment by jvymazal** [comment]
If journald `LineMax` setting is not honored, it night make sense to workaround it by explicitly calling threshold. However I am not as familiar with systemd code to be able to say if it will actually help. @rwdalpe, if you get it working, definitely post the patch as PR.

**Comment by rwdalpe** [comment]
Just to not let the thread die:

I have what I believe to be a working fix that's pretty simple (calling sd_journal_set_data_threshold when we open the journal appears to be sufficient). I'm trying to get familiar with the test suites and having a bit of trouble with that. I do hope to get a PR up at some point, though.

**Comment by jvymazal** [comment]
If you get stuck with it, just ping me, if it is as simple as you write, I can spin up such PR pretty quickly.

**Comment by rwdalpe** [comment]
I'm not 100% sure what the correct workflow for this issue is since a fix was merged. But I will assume that I am supposed to close it.
