### ISSUE TITLE
relp with openssl Certificate error

### ISSUE THREAD

**Issue by keros** [rsyslog/rsyslog#3806]
Hi

I have the following setup:
1.) Server:
```
module(load="imuxsock")
module(load="imrelp" tls.tlslib="openssl" ruleset="relp")
input(type="imrelp"
	port="2514"
	maxDataSize="10k"
	keepAlive="on"
	keepAlive.Probes="6"
	keepAlive.Interval="5"
	keepAlive.Time="5"
	tls="on"
	tls.dhbits="4096"
	ls.cacert="/etc/my/rsyslog/ca.crt"
	tls.mycert="/etc/my/rsyslog/my-core01.crt"
	tls.myprivkey="/etc/my/rsyslog/my-core01.key"
	tls.authmode="name"
	tls.permittedpeer=["my-hub01", "my-hub02"]
)
```

2.) Client:
```
module(load="imuxsock") 
module(load="imtcp")
module(load="omrelp" tls.tlslib="openssl")
action(type="omrelp"
	target="my-core01"
	port="2514"
	timeout="90"
	conn.timeout="10"
	tls="on"
	tls.cacert="/etc/my/rsyslog/ca.crt"
	tls.mycert="/etc/my/rsyslog/my-hub01.crt"
	tls.myprivkey="/etc/my/rsyslog/my-hub01.key"
	tls.authmode="name"
	tls.permittedpeer="my-core01"
)

*.*  :omrelp:my-core01:2514
```

I created the certs with easyrsa (all the certs work fine for openvpn, ipsec, apache client auth, ...)
I tested the certs:
On Server:
```
sha256sum /etc/my/rsyslog/ca.crt
21e80e0b80b581921456d66fa3096e755388a68af9d5171a93a59e5dd66d4749  /etc/my/rsyslog/ca.crt

verify -CAfile /etc/my/rsyslog/ca.crt /etc/my/rsyslog/my-core01.crt
/etc/my/rsyslog/my-core01.crt: OK

openssl x509 -in /etc/my/rsyslog/my-core01.crt -noout -modulus  | sha256sum
de4c5146e6fcca02f8810ece4e5e77c65ba0e9d3b1ffb1aee73a168091e177c1  -
openssl rsa -in /etc/my/rsyslog/my-core01.key -noout -modulus  | sha256sum
de4c5146e6fcca02f8810ece4e5e77c65ba0e9d3b1ffb1aee73a168091e177c1  -

openssl x509 -in /etc/my/rsyslog/my-core01.crt -noout -text | grep "CN"
        Issuer: CN = my_Rsyslog_CA
        Subject: CN = my-core01
                DirName:/CN=my_Rsyslog_CA

openssl x509 -in /etc/my/rsyslog/my-core01.crt -noout -text | grep "Subject Alternative Name" -A 1
            X509v3 Subject Alternative Name: 
                DNS:my-core01
```

On Client:
```
sha256sum /etc/my/rsyslog/ca.crt
21e80e0b80b581921456d66fa3096e755388a68af9d5171a93a59e5dd66d4749  /etc/my/rsyslog/ca.crt

verify -CAfile /etc/my/rsyslog/ca.crt /etc/my/rsyslog/my-hub01.crt
/etc/my/rsyslog/my-hub01.crt: OK

openssl x509 -in /etc/my/rsyslog/my-hub01.crt -noout -modulus | sha256sum
88a186c739505e90cd51faf572fe7bcdc9c1e44b8eb4ef1aa07584d8a5b92d46  -
openssl rsa -in /etc/my/rsyslog/my-hub01.key -noout -modulus | sha256sum
88a186c739505e90cd51faf572fe7bcdc9c1e44b8eb4ef1aa07584d8a5b92d46  -

openssl x509 -in /etc/my/rsyslog/my-hub01.crt -noout -text | grep "CN"
        Issuer: CN = my_Rsyslog_CA
        Subject: CN = my-hub01
                DirName:/CN=my_Rsyslog_CA

openssl x509 -in /etc/my/rsyslog/my-hub01.crt -noout -text | grep "Subject Alternative Name" -A 1
            X509v3 Subject Alternative Name: 
                DNS:my-hub01
```

The CA itself is self signed (I created it)
Both servers have the same ca file.
Both servers can validate their certs against the ca.
Both servers have a matching public private keypair (cert and key files)
Both servers name is in the `CN` and in the `X509v3 Subject Alternative Name`

If I now start the rsyslog server and after that the rsyslog client I get the following in `/var/log/syslog`:
```
Aug 10 15:45:54 my-core01 rsyslogd: imrelp[2514]: authentication error 'Certificate error in verify_callback at depth: 1   issuer  = /CN=my_Rsyslog_CA  subject = /CN=my_Rsyslog_CA  err 19:self signed certificate in certificate chain ', peer is 'self signed certificate in certificate chain' [v8.1907.0 try https://www.rsyslog.com/e/2353 ]
```
Why does rsyslog check the CA certificate? The CA is always self signed (the root can not be signed by someone else).
It needs to check the peer certificate against the CA certificate.
Have I maybe done an error in the config?
I also tried it with gnutls where the same setup works but all 30 seconds I get an error in the logs that the connection is broken (I think this happens because of my timeout config, but makes also not much sense for me)
This message only happens if a log message comes in.

My tests systems are both debian10.
At first I tired it with `rsyslog 8.1901.0` which is rolled out with debian.
But beacuse of the strange ?timeout? errors I installed `rsyslog 8.1907.0` from the rsyslog repo (Debian_Unstable because there is currently no debian 10 repo yet)
https://software.opensuse.org//download.html?project=home%3Argerhards&package=rsyslog

It is also recommended to use openssl (https://www.rsyslog.com/doc/v8-stable/configuration/modules/imrelp.html)
Has someone an idea what is going wrong here?

**Comment by keros** [comment]
If I on the sever change the `tls.authmode` to `fingerprint` with the same certs I get on openssl the same error message.
With gnutls everything works fine. I use this now as workaround but need to change this in the future.

**Comment by keros** [comment]
ok this drives me nuts.
I have not changed the config but I got the strange `An unexpected TLS packet was received` error again.
After that I switched from relp to simple tcp.
Here I get the same errors. Then I recreated the certificates with `certtool` like in the docu:
https://www.rsyslog.com/doc/v8-stable/tutorials/tls_cert_summary.html

I also changed from gnutls tcp to openssl tcp which only changes the error message:
`rsyslogd: OpenSSL Error Stack: error:1408F10B:SSL routines:ssl3_get_record:wrong version number [v8.1907.0]`

I don't think its an debian10 bug beacause I installed rsyslog from the rsyslog repo.
Is this maybe a general issue in rsyslog if you try to use client and server authentication with certificates?
All the guides I see use `Authmode="anon"`. Sometimes there is a guide with `fingerprint`.
Am I the only one who has tested such a config?

I change now to plain text and do the security with openvpn.
At least this should work without problems.

**Comment by rgerhards** [comment]
I think we need to wait until @alorbach has time to look at this issue. As far as I know, we use self-signed certs in the testbench as well.

**Comment by alorbach** [comment]
In the initial configuration, there is a typo making this line invalid: 
`ls.cacert="/etc/my/rsyslog/ca.crt"`
it should be: 
`tls.cacert="/etc/my/rsyslog/ca.crt"`

Without that config property, rsyslog wont be able to verify your selfmade certs and thats why the error "Certificate error in verify_callback at depth: 1   issuer  = /CN=my_Rsyslog_CA  subject = /CN=my_Rsyslog_CA  err 19:self signed certificate in certificate chain ', peer is 'self signed certificate in certificate chain'" happens.

**Comment by keros** [comment]
I'm my worst enemy -.-
Without the typo the first config works fine on my tests.
Big thanks for the help
