### ISSUE TITLE
How to turn "systemd support " to "Yes" ?

### ISSUE THREAD

**Issue by huiwanheshang** [rsyslog/rsyslog#3840]
### OS:
CentOS 7.6 x64

### Actions:
`# ./configure --prefix=/usr CC="gcc -m64" PKG_CONFIG_PATH="/usr/lib64/pkgconfig" --libdir=/usr/lib64 --enable-ommongodb --enable-mmnormalize --enable-pmnormalize --enable-omprog`

`# make && make install`

### Results:
rsyslogd  8.1907.0 (aka 2019.07) compiled with:
        PLATFORM:                               x86_64-pc-linux-gnu
        PLATFORM (lsb_release -d):
        FEATURE_REGEXP:                         Yes
        GSSAPI Kerberos 5 support:              No
        FEATURE_DEBUG (debug build, slow code): No
        32bit Atomic operations supported:      Yes
        64bit Atomic operations supported:      Yes
        memory allocator:                       system default
        Runtime Instrumentation (slow code):    No
        uuid support:                           Yes
        **systemd support:                        No**
        Config file:                            /etc/rsyslog.conf
        PID file:                               /var/run/rsyslogd.pid
        Number of Bits in RainerScript integers: 64

----
### Question:
How to turn "**systemd support** " to "**Yes**" ?  
Thanks for your help.

**Comment by rgerhards** [comment]
I guess libsystemd-dev is missing on your systems. config.log tells the details, you may want to post it.

**Comment by huiwanheshang** [comment]
THX very much, dear Gerhards . 

But:
When I install rsyslog(8.1907.0) with yum( http://rpms.adiscon.com/v8-stable/rsyslog.repo  added)
"systemd support" is "Yes". 

So, what's going on here?  thx

**Comment by skupkosk** [comment]
As Rainer wrote, configure script check whether the libsystemd-dev is
available, in that case the systemd support is enabled. If not found, then
is will be disabled.

Have a look on following lines in configure.ac:
https://github.com/rsyslog/rsyslog/blob/71801b4b60d8cb194f0d7177cc8c09e8f2191678/configure.ac#L563

Peter
