### ISSUE TITLE
[question] rsyslog, single msg via tcpdump - multilines in network.log

### ISSUE THREAD

**Issue by thymikon** [rsyslog/rsyslog#3846]
### Expected behavior
when I sent syslog from cisco (2960) to rsyslog (arch) I expect to get 1 line in 'network.log' file
`Aug 28 18:22:27 hostname 17237: Aug 28 18:22:23.679: %SYS-5-CONFIG_I: Configured from console by username on vty0 (192.168.1.1)`
### Actual behavior
for real I got the same multilines
`Aug 28 18:22:27 hostname 17237: Aug 28 18:22:23.679: %SYS-5-CONFIG_I: Configured from console by username on vty0 (192.168.1.1)
Aug 28 18:22:27 hostname 17237: Aug 28 18:22:23.679: %SYS-5-CONFIG_I: Configured from console by username on vty0 (192.168.1.1)
Aug 28 18:22:27 hostname 17237: Aug 28 18:22:23.679: %SYS-5-CONFIG_I: Configured from console by username on vty0 (192.168.1.1)
Aug 28 18:22:27 hostname 17237: Aug 28 18:22:23.679: %SYS-5-CONFIG_I: Configured from console by username on vty0 (192.168.1.1)
Aug 28 18:22:27 hostname 17237: Aug 28 18:22:23.679: %SYS-5-CONFIG_I: Configured from console by username on vty0 (192.168.1.1)
Aug 28 18:22:27 hostname 17237: Aug 28 18:22:23.679: %SYS-5-CONFIG_I: Configured from console by username on vty0 (192.168.1.1)
Aug 28 18:22:27 hostname 17237: Aug 28 18:22:23.679: %SYS-5-CONFIG_I: Configured from console by username on vty0 (192.168.1.1)
Aug 28 18:22:27 hostname 17237: Aug 28 18:22:23.679: %SYS-5-CONFIG_I: Configured from console by username on vty0 (192.168.1.1)
Aug 28 18:22:27 hostname 17237: Aug 28 18:22:23.679: %SYS-5-CONFIG_I: Configured from console by username on vty0 (192.168.1.1)
Aug 28 18:22:27 hostname 17237: Aug 28 18:22:23.679: %SYS-5-CONFIG_I: Configured from console by username on vty0 (192.168.1.1)
Aug 28 18:22:27 hostname 17237: Aug 28 18:22:23.679: %SYS-5-CONFIG_I: Configured from console by username on vty0 (192.168.1.1)
Aug 28 18:22:27 hostname 17237: Aug 28 18:22:23.679: %SYS-5-CONFIG_I: Configured from console by username on vty0 (192.168.1.1)
Aug 28 18:22:27 hostname 17237: Aug 28 18:22:23.679: %SYS-5-CONFIG_I: Configured from console by username on vty0 (192.168.1.1)
Aug 28 18:22:27 hostname 17237: Aug 28 18:22:23.679: %SYS-5-CONFIG_I: Configured from console by username on vty0 (192.168.1.1)
Aug 28 18:22:27 hostname 17237: Aug 28 18:22:23.679: %SYS-5-CONFIG_I: Configured from console by username on vty0 (192.168.1.1)`
LOTS of them
### Steps to reproduce the behavior
my config - rsyslog.conf
```
$ActionFileDefaultTemplate RSYSLOG_TraditionalFileFormat
$FileOwner root
$FileGroup root
$FileCreateMode 0640
$DirCreateMode 0755
$Umask 0022
$WorkDirectory /var/log/rsyslog // тут пусто // empty folder
$IncludeConfig /etc/rsyslog.d/*.conf //этого каталога у меня нет // have no rsyslog.d/ folder
$ModLoad imudp
$UDPServerRun 514
syslog.*                        -/var/log/network.log
*.* @192.168.15.73:514
```

~~**solve multilines problem with**~~ **fail**
syslog.*                        -/var/log/network.log
**$RepeatedMsgReduction on** - ** again got multiplelines**
^(
will try different OS (

so my question is - is that fine? or I have to use other OS maybe, or build rsyslog from source (this time I installed it with trizen)

### Environment
- rsyslog version: rsyslogd  8.1907.0 
- platform: Linux arch 5.2.9-arch1-1-ARCH 
- for configuration questions/issues, include rsyslog.conf and included config files

**Comment by davidelang** [comment]
can you do a tcpdump to validate that only one copy of the message is being sent?

**Comment by thymikon** [comment]
> can you do a tcpdump to validate that only one copy of the message is being sent?

I was... but forget to paste it to main body

> [leorikz@arch log]$ sudo tcpdump -vvv -nn -i ens32 udp port 514
tcpdump: listening on ens32, link-type EN10MB (Ethernet), capture size 262144 bytes
18:28:57.951069 IP (tos 0x0, ttl 254, id 33, offset 0, flags [none], proto UDP (17), length 138)
    hostip.52666 > server.514: [udp sum ok] SYSLOG, length: 110
        Facility syslog (5), Severity notice (5)
        Msg: 17238: Aug 28 18:28:54.420: %SYS-5-CONFIG_I: Configured from console by username on vty0 (192.168.1.1)

right now install centos minimal to vbox, wanna test 
rsyslog version is:
[leorikz@centos-temp ~]$ rsyslogd -v
```
rsyslogd 8.24.0-34.el7, compiled with:
        PLATFORM:                               x86_64-redhat-linux-gnu
        PLATFORM (lsb_release -d):
        FEATURE_REGEXP:                         Yes
        GSSAPI Kerberos 5 support:              Yes
        FEATURE_DEBUG (debug build, slow code): No
        32bit Atomic operations supported:      Yes
        64bit Atomic operations supported:      Yes
        memory allocator:                       system default
        Runtime Instrumentation (slow code):    No
        uuid support:                           Yes
        Number of Bits in RainerScript integers: 64

See http://www.rsyslog.com for more information.
```
looks like fresh one)

**Comment by thymikon** [comment]
well, nvm
did not get it work in that setup

**Comment by davidelang** [comment]
so the problem went away or you gave up on using rsyslog?

David Lang

**Comment by thymikon** [comment]
> 
> so the problem went away or you gave up on using rsyslog? David Lang
Hello David, I am give up with rsyslogd 8.1907.0 & arch 5.2.9-arch1
nvm, because archlinux is my notebook OS and sandbox also
if I have to use any syslog in prod I will use different OS (centos)
so thank you
