### ISSUE TITLE
omfwd: setting the default template always fails

### ISSUE THREAD

**Issue by rgerhards** [rsyslog/rsyslog#385]
```module(load="builtin:omfwd" template="outfmt")```

always results in a startup error.

**Comment by kamaradclimber** [comment]
Hello @rgerhards ,

are you going to merge this patch into master ? Currently it is present only in clang branch.

**Comment by rgerhards** [comment]
I guess I committed it when in the wrong branch. But that really doesn't matter, this will be merged before the next release. And you can of course apply the patch immediately.

**Comment by kamaradclimber** [comment]
thanks
