### ISSUE TITLE
Python 2 removal (in Debian sid/bullseye)

### ISSUE THREAD

**Issue by mbiebl** [rsyslog/rsyslog#3853]
Bug-Debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=938417

Copied verbatim from the downstream bug report:

> Python2 becomes end-of-live upstream, and Debian aims to remove
> Python2 from the distribution, as discussed in
> https://lists.debian.org/debian-python/2019/07/msg00080.html
> 
> Your package either build-depends, depends on Python2, or uses Python2
> in the autopkg tests.  Please stop using Python2, and fix this issue
> by one of the following actions.
> 
> - Convert your Package to Python3. This is the preferred option.  In
>   case you are providing a Python module foo, please consider dropping
>   the python-foo package, and only build a python3-foo package.  Please
>   don't drop Python2 modules, which still have reverse dependencies,
>   just document them.
>   
>   This is the preferred option.
> 
> - If the package is dead upstream, cannot be converted or maintained
>   in Debian, it should be removed from the distribution.  If the
>   package still has reverse dependencies, raise the severity to
>   "serious" and document the reverse dependencies with the BTS affects
>   command.  If the package has no reverse dependencies, confirm that
>   the package can be removed, reassign this issue to ftp.debian.org,
>   make sure that the bug priority is set to normal and retitle the
>   issue to "RM: PKG -- removal triggered by the Python2 removal".
> 
> - If the package has still many users (popcon >= 300), or is needed to
>   build another package which cannot be removed, document that by
>   adding the "py2keep" user tag (not replacing the py2remove tag),
>   using the debian-python@lists.debian.org user.  Also any
>   dependencies on an unversioned python package (python, python-dev)
>   must not be used, same with the python shebang.  These have to be
>   replaced by python2/python2.7 dependencies and shebang.
> 
>   This is the least preferred option.
> 
> If the conversion or removal needs action on another package first,
> please document the blocking by using the BTS affects command, like
> 
>   affects <bug number of blocking py2removal bug> + src:rsyslog
> 
> If there is no py2removal bug for that reverse-dependency, please file
> a bug on this package (similar to this bug report).
> 
> If there are questions, please refer to the wiki page for the removal:
> https://wiki.debian.org/Python/2Removal, or ask for help on IRC
> #debian-python, or the debian-python@lists.debian.org mailing list.

Afaics, this only affects the test-suite.

**Comment by Whissi** [comment]
FYI: You can run current test suite with Python3+ only. In the past there were some tests written with Python2 in mind but after filling bugs they were fixed.

**Comment by mbiebl** [comment]
That's good to know. Maybe only the shebang needs to changed then?

**Comment by mbiebl** [comment]
@rgerhards how would you prefer this to be handled? Should we simply switch from python to python3 and be done with it or should this be configurable via ./configure?

**Comment by davidelang** [comment]
I think it should be configurable. We want to have the option to continue to 
support older systems and non-linux systems that may not have python3 installed 
by default

David Lang

**Comment by mbiebl** [comment]
As a side note: Python 2 will be officially unsupported by the end of this year.
I wonder which older systems do not support Python 3?

**Comment by mbiebl** [comment]
Also, keep in mind that Python is only needed for the test-suite, not for building (or running) rsyslog. So I wonder if the additional complexity of making it configurable is justified.

**Comment by rgerhards** [comment]
Just to keep you informed: I am working towards a solution, but I'd like to integrate some python3-only system into CI first. Will probably do this with CentOS 8, where the docker image is available now. We may also need to remove some tests until their contributors have updated them (depends on my python skills, of course ;-)).

**Comment by mbiebl** [comment]
Fwiw, I've applied this in the mean time:
https://salsa.debian.org/debian/rsyslog/commit/e57669c34d47ac497e66e655440661b2dae4c26e

I hope I didn't miss a spot. The results look ok so far
https://buildd.debian.org/status/package.php?p=rsyslog

**Comment by mbiebl** [comment]
@rgerhards fwiw, if you'd prefer a solution based on `AM_PATH_PYTHON`, I could have a look at that.

**Comment by rgerhards** [comment]
FYI: I have set up a new system inside CI. There may be other issues (I have not checked yet), but for sure it detects the python2 based ones now: https://build.rsyslog.com/#/builders/204/builds/11

**Comment by rgerhards** [comment]
> if you'd prefer a solution based on `AM_PATH_PYTHON`, I could have a look at that.

Thx for the offer, much appreciated. Please let me do a bit of testing with a sample test. I guess `AM_PATH_PYTHON` might be better to support other platforms (e.g. solaris). Not sure if some will stick to python2 albeit it's flagged "dead". New testing PR will show.

**Comment by rgerhards** [comment]
@mbiebl looking at the CI results, I would say help with `AM_PATH_PYTHON` would be appreciated ;-)

https://build.rsyslog.com/#/builders/175/builds/2412/steps/5/logs/test-suite_log

Note: all CI containers have a default config as much as possible. So it looks like the older distros have python 2 by default and I would think it is a plus to be able to work with it. Thinking about some regular users who compile and sometimes runs tests (I see those questions every now and then).

I have also noticed some scripts which are not python 3 compatible (e.g. print). I will try to address these issues. Can check now easily on the new CentOS 8 worker.

**Comment by mbiebl** [comment]
A short update: With 8.2001.0-1 this issue is mostly fixed. Most of the test-suite now respects when I set `PYTHON=/usr/bin/python3`.

Only a few spots remain, where the python interpreter is hard-coded:
```
$ grep "/usr/bin/env python" -R
tests/urlencode.py:#!/usr/bin/env python
tests/snmptrapreceiver.py:#!/usr/bin/env python
tests/omhttp_server.py:#!/usr/bin/env python
tests/rscript_parse_time_get-ts.py:#!/usr/bin/env python
tests/testsuites/mmexternal-SegFault-mm-python.py:#!/usr/bin/env python
tests/testsuites/omprog-output-capture-mt-bin.py:#!/usr/bin/env python
tests/improg-multiline-test.py:#!/usr/bin/env python
```

**Comment by rgerhards** [comment]
> Only a few spots remain, where the python interpreter is hard-coded:

mhhh... I thought that this shebang picks up the system default python interpreter. What should be used instead?

**Comment by mbiebl** [comment]
`/usr/bin/env python` will resolve to `/usr/bin/python`, which is Python 2 (at least on the vast majority of distros).
We could use `AM_PATH_PYTHON` again and set the shebang using @PYTHON@, which would mean a bit of seddery like for the .sh.in scripts.

**Comment by rgerhards** [comment]
mmmhhh... why is it a problem if we use python2 if it is available? The same scripts should work with python 3 -- at least I think I have setup at least one CI env with python 3 and made sure everything works both with 2 and 3 (minus some oversight, maybe).

**Comment by mbiebl** [comment]
The point is, that our buildds will no longer have python2. There won't be a `/usr/bin/python` in the future

**Comment by mbiebl** [comment]
Only `/usr/bin/python3`.
I heard that some distros wanted to symlink `/usr/bin/python` to `python3`, but afair this was frowned upon and at least the  Debian/Ubuntu family will not do that.

**Comment by rgerhards** [comment]
Shouldn't the Shebang than resolve to python3? I think I changed it because of this,. Ineed to run to a meeting now. Will check the last commit tomorrow.

**Comment by mbiebl** [comment]
No, it won't. env is really simple. I just looks for a binary named `python` in `$PATH`

**Comment by mbiebl** [comment]
Afair, the reasoning for not symlinking `/usr/bin/python3` to `/usr/bin/python` was, that not all Python code is Python 3 ready. Some Python code might crash, some might just slightly misbehave.
It was deemed preferable if scripts simply stopped with a clean error if `/usr/bin/python` was missing.

**Comment by mbiebl** [comment]
Ok, I did some more digging. Turns out, almost all .py scripts are not executed directly but instead we use `$PYTHON script.py`.
So the shebang in those scripts will be ignored. The only notable exception is tests/mmexternal-SegFault-empty-jroot-vg.sh which contains

```
 binary="testsuites/mmexternal-SegFault-mm-python.py"
```
In contrast, tests/mmexternal-SegFault-vg.sh uses
```
 binary="'$PYTHON' '${srcdir}'/testsuites/mmexternal-SegFault-mm-python.py")
```

So, I guess we are mostly ok here (aside from fixing mmexternal-SegFault-empty-jroot-vg.sh) and the wrong shebang on a Python3-only system is more or less a cosmetic issue.
I suspect those .py scripts are not supposed to be executed directly?

**Comment by rgerhards** [comment]
Thx! I guess I remember now, I have probably changed a couple of tests to call the python interpreter explicitly. Will see that I finalize the changes - as these are pure testing tools, it doesn't matter that they cannot be called by pure script name. I'll probably remove the shebang to be on the save side.

side-note: could you suggest what I need to change inside the Dockerfile to get a pure python 3 debian10? I'd love to add it to the CI system. https://github.com/rsyslog/rsyslog-docker/tree/master/dev_env/debian/base/10

**Comment by rgerhards** [comment]
@mbiebl I have fixed as much as I could see in https://github.com/rsyslog/rsyslog/pull/4148 -- hope that's all for now. The shebangs are gone, so we should spot an invocation without explicit python call. Still would be good to get a pure python 3 debian into CI.

**Comment by mbiebl** [comment]
> side-note: could you suggest what I need to change inside the Dockerfile to get a pure python 3 debian10? I'd love to add it to the CI system. https://github.com/rsyslog/rsyslog-docker/tree/master/dev_env/debian/base/10

There are three packages in you `apt-get install` line which will pull in Python2:
- clang (via Depends: clang-7 -> Recommends: python)
- python-pysnmp4
- python-docutils

The two python packages I'd replace with the python3 counterpart, i.e python3-pysnmp4 and python3-docutils. As for clang, you could use `apt install --no-install-recommends`. This will install a lot fewer packages (including the `python` package). Maybe this a change you want to do anyway.

See, no python package in the list:
```
root@35890975e30c:/# apt-get install --no-install-recommends \
> autoconf \
> autoconf-archive \
> automake \
> autotools-dev \
> bison \
> clang \
> curl \
> default-jdk \
> faketime \
> flex \
> gdb \
> git \
> libcurl4-gnutls-dev \
> libdbd-mysql \
> libdbi-dev \
> libgcrypt20-dev \
> libglib2.0-dev \
> libgnutls28-dev \
> libgrok1 libgrok-dev \
> libhiredis-dev \
> libkrb5-dev \
> liblz4-dev \
> default-libmysqlclient-dev \
> libnet1-dev \
> libpcap-dev \
> libpq-dev \
> libsasl2-dev \
> libsnmp-dev \
> libssl-dev \
> libsystemd-dev \
> libtokyocabinet-dev \
> libtool \
> default-mysql-server \
> net-tools \
> pkg-config \
> postgresql-client \
> python3-docutils \
> python3-pysnmp4 \
> software-properties-common \
> tcl-dev \
> uuid-dev \
> valgrind \
> vim \
> wget \
> zlib1g-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
autoconf is already the newest version (2.69-11).
autoconf-archive is already the newest version (20180313-1).
automake is already the newest version (1:1.16.1-4).
autotools-dev is already the newest version (20180224.1).
bison is already the newest version (2:3.3.2.dfsg-1).
The following additional packages will be installed:
  binutils binutils-common binutils-x86-64-linux-gnu bzip2 ca-certificates ca-certificates-java clang-7 comerr-dev
  cpp cpp-8 default-jdk-headless default-jre default-jre-headless distro-info-data docutils-common dpkg-dev file
  fontconfig-config fonts-dejavu-core galera-3 gawk gcc gcc-8 gir1.2-glib-2.0 gir1.2-packagekitglib-1.0 git-man
  iso-codes java-common krb5-multidev lib32gcc1 lib32stdc++6 libaio1 libapt-inst2.0 libasan5 libasound2
  libasound2-data libatomic1 libavahi-client3 libavahi-common-data libavahi-common3 libbabeltrace1 libbinutils
  libblkid-dev libbsd0 libc-dev-bin libc6-dbg libc6-dev libc6-i386 libcc1-0 libclang-common-7-dev libclang1-7
  libconfig-inifiles-perl libcups2 libcurl3-gnutls libcurl4 libdbi-perl libdbi1 libdbus-1-3 libdpkg-perl
  libdrm-amdgpu1 libdrm-common libdrm-intel1 libdrm-nouveau2 libdrm-radeon1 libdrm2 libdw1 libedit2 liberror-perl
  libevent-2.1-6 libexpat1 libfaketime libffi-dev libfontconfig1 libfreetype6 libgc1c2 libgcc-8-dev libgif7
  libgirepository-1.0-1 libgl1 libgl1-mesa-dri libglapi-mesa libglib2.0-0 libglib2.0-bin libglib2.0-data
  libglib2.0-dev-bin libglvnd0 libglx-mesa0 libglx0 libgmp-dev libgmpxx4ldbl libgnutls-dane0 libgnutls-openssl27
  libgnutlsxx28 libgomp1 libgpg-error-dev libgpm2 libgssapi-krb5-2 libgssrpc4 libhiredis0.14 libidn2-dev libipt2
  libisl19 libitm1 libjpeg62-turbo libk5crypto3 libkadm5clnt-mit11 libkadm5srv-mit11 libkdb5-9 libkeyutils1
  libkrb5-3 libkrb5support0 liblcms2-2 libldap-2.4-2 libldap-common libllvm7 liblsan0 libmagic-mgc libmagic1
  libmariadb-dev libmariadb-dev-compat libmariadb3 libmount-dev libmpc3 libmpdec2 libmpfr6 libmpx2 libncurses6
  libnet1 libnghttp2-14 libnspr4 libnss3 libobjc-8-dev libobjc4 libp11-kit-dev libpackagekit-glib2-18 libpcap0.8
  libpcap0.8-dev libpci-dev libpci3 libpciaccess0 libpcre16-3 libpcre2-8-0 libpcre3-dev libpcre32-3 libpcrecpp0v5
  libpcsclite1 libpng16-16 libpopt0 libpq5 libprocps7 libpsl5 libpython3-stdlib libpython3.7 libpython3.7-minimal
  libpython3.7-stdlib libquadmath0 libreadline5 libreadline7 librtmp1 libsasl2-2 libsasl2-modules-db
  libselinux1-dev libsensors-config libsensors4-dev libsensors5 libsepol1-dev libsnappy1v5 libsnmp-base libsnmp30
  libssh2-1 libssl1.1 libstdc++-8-dev libtasn1-6-dev libtcl8.6 libtokyocabinet9 libtsan0 libubsan1 libudev-dev
  libunbound8 libwrap0 libwrap0-dev libx11-6 libx11-data libx11-xcb1 libxau6 libxcb-dri2-0 libxcb-dri3-0
  libxcb-glx0 libxcb-present0 libxcb-sync1 libxcb1 libxdamage1 libxdmcp6 libxext6 libxfixes3 libxi6 libxrender1
  libxshmfence1 libxtst6 libxxf86vm1 linux-libc-dev lsb-base lsb-release lsof make mariadb-client-10.3
  mariadb-client-core-10.3 mariadb-common mariadb-server-10.3 mariadb-server-core-10.3 mime-support mysql-common
  nettle-dev openjdk-11-jdk openjdk-11-jdk-headless openjdk-11-jre openjdk-11-jre-headless openssl patch
  postgresql-client-11 postgresql-client-common procps psmisc python-apt-common python3 python3-apt python3-dbus
  python3-distutils python3-gi python3-lib2to3 python3-minimal python3-ply python3-pyasn1 python3-pycryptodome
  python3-pycurl python3-pysmi python3-roman python3-software-properties python3.7 python3.7-minimal
  readline-common rsync sgml-base socat tcl tcl8.6 tcl8.6-dev ucf vim-common vim-runtime x11-common xml-core xxd
  xz-utils
Suggested packages:
  binutils-doc bzip2-doc clang-7-doc doc-base cpp-doc gcc-8-locales debian-keyring build-essential flex-doc
  gawk-doc gcc-multilib manpages-dev gcc-doc gcc-8-multilib gcc-8-doc libgcc1-dbg libgomp1-dbg libitm1-dbg
  libatomic1-dbg libasan5-dbg liblsan0-dbg libtsan0-dbg libubsan1-dbg libmpx2-dbg libquadmath0-dbg gdb-doc
  gdbserver gettext-base git-daemon-run | git-daemon-sysvinit git-doc git-el git-email git-gui gitk gitweb git-cvs
  git-mediawiki git-svn isoquery krb5-doc libasound2-plugins alsa-utils glibc-doc cups-common libcurl4-doc
  libidn11-dev libldap2-dev librtmp-dev libssh2-1-dev libclone-perl libmldbm-perl libnet-daemon-perl
  libsql-statement-perl gnupg | gnupg2 bzr libgcrypt20-doc libglib2.0-doc libgdk-pixbuf2.0-bin
  | libgdk-pixbuf2.0-dev libxml2-utils gmp-doc libgmp10-doc libmpfr-dev dns-root-data gnutls-bin gnutls-doc gpm
  krb5-user liblcms2-utils pciutils pcscd postgresql-doc-11 lm-sensors snmp-mibs-downloader libssl-doc
  libstdc++-8-doc libtool-doc gfortran | fortran95-compiler gcj-jdk lsb make-doc mailx mariadb-test netcat-openbsd
  tinyca openjdk-11-demo openjdk-11-source visualvm libnss-mdns fonts-dejavu-extra fonts-ipafont-gothic
  fonts-ipafont-mincho fonts-wqy-microhei | fonts-wqy-zenhei fonts-indic ed diffutils-doc postgresql-11
  python3-doc python3-tk python3-venv python3-apt-dbg python-apt-doc python-dbus-doc python3-dbus-dbg docutils-doc
  fonts-linuxlibertine | ttf-linux-libertine texlive-lang-french texlive-latex-base texlive-latex-recommended
  python-ply-doc python3-pkg-resources python-pycurl-doc python3-pycurl-dbg python3.7-venv python3.7-doc
  binfmt-support readline-doc openssh-client openssh-server sgml-base-doc tcl-doc tcl-tclreadline tcl8.6-doc
  valgrind-mpi kcachegrind alleyoop valkyrie ctags vim-doc vim-scripts debhelper
Recommended packages:
  llvm-7-dev python libomp-7-dev build-essential fakeroot gnupg | gnupg2 libalgorithm-merge-perl libfl-dev less
  ssh-client manpages manpages-dev dbus libfile-fcntllock-perl shared-mime-info xdg-user-dirs krb5-locales
  packagekit publicsuffix libsasl2-modules libtasn1-doc libltdl-dev libdbd-mysql-perl libterm-readkey-perl
  libhtml-template-perl libxt-dev libatk-wrapper-java-jni fonts-dejavu-extra libpaper-utils python3-pil
  python3-pygments unattended-upgrades valgrind-dbg
The following NEW packages will be installed:
  binutils binutils-common binutils-x86-64-linux-gnu bzip2 ca-certificates ca-certificates-java clang clang-7
  comerr-dev cpp cpp-8 curl default-jdk default-jdk-headless default-jre default-jre-headless
  default-libmysqlclient-dev default-mysql-server distro-info-data docutils-common dpkg-dev faketime file flex
  fontconfig-config fonts-dejavu-core galera-3 gawk gcc gcc-8 gdb gir1.2-glib-2.0 gir1.2-packagekitglib-1.0 git
  git-man iso-codes java-common krb5-multidev lib32gcc1 lib32stdc++6 libaio1 libapt-inst2.0 libasan5 libasound2
  libasound2-data libatomic1 libavahi-client3 libavahi-common-data libavahi-common3 libbabeltrace1 libbinutils
  libblkid-dev libbsd0 libc-dev-bin libc6-dbg libc6-dev libc6-i386 libcc1-0 libclang-common-7-dev libclang1-7
  libconfig-inifiles-perl libcups2 libcurl3-gnutls libcurl4 libcurl4-gnutls-dev libdbd-mysql libdbi-dev
  libdbi-perl libdbi1 libdbus-1-3 libdpkg-perl libdrm-amdgpu1 libdrm-common libdrm-intel1 libdrm-nouveau2
  libdrm-radeon1 libdrm2 libdw1 libedit2 liberror-perl libevent-2.1-6 libexpat1 libfaketime libffi-dev
  libfontconfig1 libfreetype6 libgc1c2 libgcc-8-dev libgcrypt20-dev libgif7 libgirepository-1.0-1 libgl1
  libgl1-mesa-dri libglapi-mesa libglib2.0-0 libglib2.0-bin libglib2.0-data libglib2.0-dev libglib2.0-dev-bin
  libglvnd0 libglx-mesa0 libglx0 libgmp-dev libgmpxx4ldbl libgnutls-dane0 libgnutls-openssl27 libgnutls28-dev
  libgnutlsxx28 libgomp1 libgpg-error-dev libgpm2 libgrok-dev libgrok1 libgssapi-krb5-2 libgssrpc4 libhiredis-dev
  libhiredis0.14 libidn2-dev libipt2 libisl19 libitm1 libjpeg62-turbo libk5crypto3 libkadm5clnt-mit11
  libkadm5srv-mit11 libkdb5-9 libkeyutils1 libkrb5-3 libkrb5-dev libkrb5support0 liblcms2-2 libldap-2.4-2
  libldap-common libllvm7 liblsan0 liblz4-dev libmagic-mgc libmagic1 libmariadb-dev libmariadb-dev-compat
  libmariadb3 libmount-dev libmpc3 libmpdec2 libmpfr6 libmpx2 libncurses6 libnet1 libnet1-dev libnghttp2-14
  libnspr4 libnss3 libobjc-8-dev libobjc4 libp11-kit-dev libpackagekit-glib2-18 libpcap-dev libpcap0.8
  libpcap0.8-dev libpci-dev libpci3 libpciaccess0 libpcre16-3 libpcre2-8-0 libpcre3-dev libpcre32-3 libpcrecpp0v5
  libpcsclite1 libpng16-16 libpopt0 libpq-dev libpq5 libprocps7 libpsl5 libpython3-stdlib libpython3.7
  libpython3.7-minimal libpython3.7-stdlib libquadmath0 libreadline5 libreadline7 librtmp1 libsasl2-2 libsasl2-dev
  libsasl2-modules-db libselinux1-dev libsensors-config libsensors4-dev libsensors5 libsepol1-dev libsnappy1v5
  libsnmp-base libsnmp-dev libsnmp30 libssh2-1 libssl-dev libssl1.1 libstdc++-8-dev libsystemd-dev libtasn1-6-dev
  libtcl8.6 libtokyocabinet-dev libtokyocabinet9 libtool libtsan0 libubsan1 libudev-dev libunbound8 libwrap0
  libwrap0-dev libx11-6 libx11-data libx11-xcb1 libxau6 libxcb-dri2-0 libxcb-dri3-0 libxcb-glx0 libxcb-present0
  libxcb-sync1 libxcb1 libxdamage1 libxdmcp6 libxext6 libxfixes3 libxi6 libxrender1 libxshmfence1 libxtst6
  libxxf86vm1 linux-libc-dev lsb-base lsb-release lsof make mariadb-client-10.3 mariadb-client-core-10.3
  mariadb-common mariadb-server-10.3 mariadb-server-core-10.3 mime-support mysql-common net-tools nettle-dev
  openjdk-11-jdk openjdk-11-jdk-headless openjdk-11-jre openjdk-11-jre-headless openssl patch pkg-config
  postgresql-client postgresql-client-11 postgresql-client-common procps psmisc python-apt-common python3
  python3-apt python3-dbus python3-distutils python3-docutils python3-gi python3-lib2to3 python3-minimal
  python3-ply python3-pyasn1 python3-pycryptodome python3-pycurl python3-pysmi python3-pysnmp4 python3-roman
  python3-software-properties python3.7 python3.7-minimal readline-common rsync sgml-base socat
  software-properties-common tcl tcl-dev tcl8.6 tcl8.6-dev ucf uuid-dev valgrind vim vim-common vim-runtime wget
  x11-common xml-core xxd xz-utils zlib1g-dev
0 upgraded, 295 newly installed, 0 to remove and 0 not upgraded.
Need to get 461 MB of archives.
After this operation, 1471 MB of additional disk space will be used.
Do you want to continue? [Y/n] 
```

**Comment by mbiebl** [comment]
no recommends:
```
0 upgraded, 295 newly installed, 0 to remove and 0 not upgraded.
Need to get 461 MB of archives.
After this operation, 1471 MB of additional disk space will be used.
```
vs with recommends
```
0 upgraded, 486 newly installed, 0 to remove and 0 not upgraded.
Need to get 647 MB of archives.
After this operation, 2026 MB of additional disk space will be used.
```
