### ISSUE TITLE
glibc detected *** /sbin/rsyslogd: realloc()

### ISSUE THREAD

**Issue by Uni-lovenix** [rsyslog/rsyslog#3855]
glibc detected *** /sbin/rsyslogd: realloc(): invalid next size: 0x00007fde200064f0 ***
Backtrace: =========
Memory map: ========
00000000 00:00 0
00000000 00:00 0
00000000 00:00 0
00000000 00:00 0
00000000 00:00 0
00000000 00:00 0
00000000 00:2d 2015 /lib64/rsyslog/lmnsd_ptcp.so
00004000 00:2d 2015 /lib64/rsyslog/lmnsd_ptcp.so

note: my rsyslog's version is 4.6.2

Here is the new configuration:
$FailOnChownFailure off
$ModLoad imuxsock.so # provides support for local system logging (e.g. via logger command)
$ModLoad imklog.so # provides kernel logging support (previously done by rklogd)
$ActionFileDefaultTemplate RSYSLOG_TraditionalFileFormat

kern.warning;.err;authpriv.none /dev/tty10
.info;mail.none;authpriv.none;cron.none /var/log/messages
authpriv. /var/log/secure
mail. -/var/log/maillog
cron.* /var/log/cron
uucp,news.crit /var/log/spooler
local7.* /var/log/boot.log

$ModLoad imfile

$InputFileName /usr/local/app/stream/logs/gunicorn_error.log
$InputFileTag tag1:stream
$InputFileStateFile /usr/local/app/stat-file1
$InputFileSeverity info
$InputFileFacility local7
$InputRunFileMonitor
$InputFilePollInterval 1
$InputFilePersistStateInterval 1

. @@localhost:8898

THANK YOU, SO MUCH

**Comment by rgerhards** [comment]
Please provide the actual config - the attached one has too few lines and as such cannot be correct.

posted config:
```
#rsyslog v3 config file

# if you experience problems, check
# http://www.rsyslog.com/troubleshoot for assistance

#### MODULES ####

$ModLoad imuxsock.so	# provides support for local system logging (e.g. via logger command)
$ModLoad imklog.so	# provides kernel logging support (previously done by rklogd)
#$ModLoad immark.so	# provides --MARK-- message capability

# Provides UDP syslog reception
#$ModLoad imudp.so
#$UDPServerRun 514

# Provides TCP syslog reception
$ModLoad imtcp.so  
$InputTCPServerRun 8899

$InputTCPServerRun 8890

$InputTCPServerRun 8891
```

**Comment by rgerhards** [comment]
side note: you can three backticks to delimit text parts like the config "````"

**Comment by Uni-lovenix** [comment]
I recommand I used 4.6.0 version in my client PC, so I put the option '-c4' in the first then it worked, but has some permission problem. like:file '/var/log/messages': Permission denied

**Comment by davidelang** [comment]
if all of this is one config file, then you have problems because you are 
loading things with both the obsolete legacy format ($InputECPServerRun) and 
with the new format (input())

when you are doing multiple rulesets, you will want to be using the new format.

I'm amazed that you aren't getting errors with this.

you don't want to try to use -c4 on current versions, it doesn't do anything 
useful any longer.

David Lang

**Comment by Uni-lovenix** [comment]
I used -c4 option then it works, but I got error as below:
0612.213177218:7f4fb474d700: file '/dev/tty10' opened as #-1 with mode 416
0612.213181920:7f4fb474d700: strm 0x7f4fb6b459b0: open error 13, file '/dev/tty10': Permission denied
0612.213187714:7f4fb474d700: testing filter, f_pmask 127
0612.213192099:7f4fb474d700: Called action, logging to builtin-file
0612.213197232:7f4fb474d700: file to log to: /var/log/messages
0612.213201478:7f4fb474d700: doWrite, pData->pStrm 0x7f4fb6b46570, lenBuf 178
0612.213205840:7f4fb474d700: strm 0x7f4fb6b46570: file -1(messages) flush, buflen 178
0612.213214179:7f4fb474d700: file '/var/log/messages' opened as #-1 with mode 416
0612.213219016:7f4fb474d700: strm 0x7f4fb6b46570: open error 13, file '/var/log/messages': Permission denied

**Comment by davidelang** [comment]
The permission problems are caused by your system, wht are the permission on /dev/tty10  and /var/log/messages (or the /var/log directory)? this could be SELinux or AppArmor permissions that are blocking you

**Comment by Uni-lovenix** [comment]
> Please provide the actual config - the attached one has too few lines and as such cannot be correct.
> 
> posted config:
> 
> ```
> #rsyslog v3 config file
> 
> # if you experience problems, check
> # http://www.rsyslog.com/troubleshoot for assistance
> 
> #### MODULES ####
> 
> $ModLoad imuxsock.so	# provides support for local system logging (e.g. via logger command)
> $ModLoad imklog.so	# provides kernel logging support (previously done by rklogd)
> #$ModLoad immark.so	# provides --MARK-- message capability
> 
> # Provides UDP syslog reception
> #$ModLoad imudp.so
> #$UDPServerRun 514
> 
> # Provides TCP syslog reception
> $ModLoad imtcp.so  
> $InputTCPServerRun 8899
> 
> $InputTCPServerRun 8890
> 
> $InputTCPServerRun 8891
> ```

Now it can worked, but reported a memory leak error. I checked the redhat's issue at there:[https://access.redhat.com/solutions/66500](url)
So I only use one file to be input file. but it still report this error. I confused.
Please help me, Thank you so much
