### ISSUE TITLE
Rsyslog doesn't start, complains about not be able to find ommysql module

### ISSUE THREAD

**Issue by lusbyr** [rsyslog/rsyslog#3857]
### Environment
root@rsyslog2:~# rsyslogd -v
rsyslogd  8.1908.0 (aka 2019.08) compiled with:
        PLATFORM:                               x86_64-pc-linux-gnu
        PLATFORM (lsb_release -d):              Description:    Ubuntu 18.04.3 LTS
        FEATURE_REGEXP:                         Yes
        GSSAPI Kerberos 5 support:              No
        FEATURE_DEBUG (debug build, slow code): No
        32bit Atomic operations supported:      Yes
        64bit Atomic operations supported:      Yes
        memory allocator:                       system default
        Runtime Instrumentation (slow code):    No
        uuid support:                           Yes
        systemd support:                        No
        Config file:                            /etc/rsyslog.conf
        PID file:                               /var/run/rsyslogd.pid
        Number of Bits in RainerScript integers: 64

See https://www.rsyslog.com for more information.

**Comment by lusbyr** [comment]
Sorry wrong library path initially indicated it is the default /usr/local/lib/rsyslog

**Comment by rgerhards** [comment]
actual rsyslog error message?

> Steps to reproduce the behavior - compile rsyslog 8.1908.0 from source with --enable-mysql and --enable-omudpspoof options. Try and run rsyslog and it fails

nope, this works ;-)

**Comment by rgerhards** [comment]
> Sorry wrong library path initially indicated it is the default /usr/local/lib/rsyslog

might be the issue - is this path in the system's library search path?

**Comment by lusbyr** [comment]
Thanks for the response.  Is the LD_LIBRARY_PATH environment variable what your are referring to?  Did you run your test compile on Ubuntu 18.04 LTS?

Thanks.

**Comment by rgerhards** [comment]
> Is the LD_LIBRARY_PATH environment variable what your are referring to?

IIRC yes

> Did you run your test compile on Ubuntu 18.04 LTS?

This and 41 other platforms - it's all done in CI ;-)

**Comment by lusbyr** [comment]
Rainier, OK here is what I just did...

root@rsyslog2:~# export LD_LIBRARY_PATH=/usr/local/lib:/usr/local/lib/rsyslog;
root@rsyslog2:~# systemctl restart rsyslog
Job for rsyslog.service failed because a timeout was exceeded.
See "systemctl status rsyslog.service" and "journalctl -xe" for details.
root@rsyslog2:~# systemctl status rsyslog
● rsyslog.service - System Logging Service
   Loaded: loaded (/lib/systemd/system/rsyslog.service; enabled; vendor preset: enabled)
   Active: activating (start) since Thu 2019-09-05 17:46:09 UTC; 20s ago
     Docs: man:rsyslogd(8)
           https://www.rsyslog.com/doc/
 Main PID: 16086 (rsyslogd)
    Tasks: 3 (limit: 4661)
   CGroup: /system.slice/rsyslog.service
           └─16086 /usr/local/sbin/rsyslogd -n -iNONE

Sep 05 17:46:09 rsyslog2 systemd[1]: rsyslog.service: Service hold-off time over, scheduling restart.
Sep 05 17:46:09 rsyslog2 systemd[1]: rsyslog.service: Scheduled restart job, restart counter is at 2.
Sep 05 17:46:09 rsyslog2 systemd[1]: Stopped System Logging Service.
Sep 05 17:46:09 rsyslog2 systemd[1]: Starting System Logging Service...
Sep 05 17:46:09 rsyslog2 rsyslogd[16086]: could not load module 'ommyqsl', errors: trying to load module /usr/local/lib/rsyslog/ommyqsl.so: /usr/local/lib/rsyslog/ommyqsl.so: cannot open shared object file: No such file o
Sep 05 17:46:09 rsyslog2 rsyslogd[16086]: [origin software="rsyslogd" swVersion="8.1908.0" x-pid="16086" x-info="https://www.rsyslog.com"] start
root@rsyslog2:~# systemctl status rsyslog.service
● rsyslog.service - System Logging Service
   Loaded: loaded (/lib/systemd/system/rsyslog.service; enabled; vendor preset: enabled)
   Active: activating (start) since Thu 2019-09-05 17:49:10 UTC; 9s ago
     Docs: man:rsyslogd(8)
           https://www.rsyslog.com/doc/
 Main PID: 16135 (rsyslogd)
    Tasks: 3 (limit: 4661)
   CGroup: /system.slice/rsyslog.service
           └─16135 /usr/local/sbin/rsyslogd -n -iNONE

Sep 05 17:49:10 rsyslog2 systemd[1]: Starting System Logging Service...
Sep 05 17:49:10 rsyslog2 rsyslogd[16135]: could not load module 'ommyqsl', errors: trying to load module /usr/local/lib/rsyslog/ommyqsl.so: /usr/local/lib/rsyslog/ommyqsl.so: cannot open shared object file: No such file o
Sep 05 17:49:10 rsyslog2 rsyslogd[16135]: [origin software="rsyslogd" swVersion="8.1908.0" x-pid="16135" x-info="https://www.rsyslog.com"] start
root@rsyslog2:~#

It is still not working.  Are there other files or information I can send you to help?

Thanks.

**Comment by rgerhards** [comment]
you need to export the environment variable in the service, not your terminal.

Probably better set the default-OS libdir during configure : `--libdir=/usr/lib`

**Comment by rgerhards** [comment]
note that it may actually be `/usr/lib64` - check your system if in doubt

**Comment by Uni-lovenix** [comment]
It's can be worked! I configed the file by v5's style, then it worked! 
but unfortunately, it will put a memory leak error.
as below:
glibc detected *** /sbin/rsyslogd: realloc(): invalid next size: 0x00007fde200064f0 ***
Backtrace: =========
Memory map: ========
00000000 00:00 0 
00000000 00:00 0 
00000000 00:00 0 
00000000 00:00 0 
00000000 00:00 0 
00000000 00:00 0 
00000000 00:2d 2015                       /lib64/rsyslog/lmnsd_ptcp.so
00004000 00:2d 2015                       /lib64/rsyslog/lmnsd_ptcp.so

**Comment by Uni-lovenix** [comment]
Here is the new configuration:

#rsyslog v3 config file

$FailOnChownFailure off

#### MODULES ####

$ModLoad imuxsock.so	# provides support for local system logging (e.g. via logger command)
$ModLoad imklog.so	# provides kernel logging support (previously done by rklogd)

#### GLOBAL DIRECTIVES ####

# Use default timestamp format
$ActionFileDefaultTemplate RSYSLOG_TraditionalFileFormat

#### RULES ####

# Log all kernel messages to the console.
# Logging much else clutters up the screen.
#kern.*                                                 /dev/console
kern.warning;*.err;authpriv.none        		/dev/tty10


# Log anything (except mail) of level info or higher.
# Don't log private authentication messages!
*.info;mail.none;authpriv.none;cron.none                /var/log/messages

# The authpriv file has restricted access.
authpriv.*                                              /var/log/secure

# Log all the mail messages in one place.
mail.*                                                  -/var/log/maillog


# Log cron stuff
cron.*                                                  /var/log/cron

# Everybody gets emergency messages
#*.emerg                                                 *

# Save news errors of level crit and higher in a special file.
uucp,news.crit                                          /var/log/spooler

# Save boot messages also to boot.log
local7.*                                                /var/log/boot.log

$ModLoad imfile

# File 1
$InputFileName /usr/local/app/stream/logs/gunicorn_error.log
$InputFileTag tag1:stream
$InputFileStateFile /usr/local/app/stat-file1

$InputFileSeverity info
$InputFileFacility local7
$InputRunFileMonitor

$InputFilePollInterval 1
$InputFilePersistStateInterval 1

# Send msg to remote by tcp
*.* @@localhost:8898


THANK YOU, SO MUCH

**Comment by rgerhards** [comment]
Question: why do you build yourself?

**Comment by lusbyr** [comment]
Because I need the UDP spoofing and MySQL integration.   As far as I know this is not part of the apt-get or yum package options for rsyslog.

**Comment by rgerhards** [comment]
MySQL for sure is in the default distro repositories. I think both are
present in the rsyslog repositories linked to from the rsyslog.com site.

Rainer

Sent from phone, thus brief.

lusbyr <notifications@github.com> schrieb am Mi., 11. Sep. 2019, 22:14:

**Comment by davidelang** [comment]
those modules are not in the default rsyslog package, but there are other 
packages that do include them. check your distro for all rsyslog* packages

They aren't included by default because they require additional dependencies.

David Lang

**Comment by lusbyr** [comment]
I solved this issue by running on CentOS.  Couldn't get it to work on Ubuntu, but needed to get this project moving forward.  Thanks for your help.
