### ISSUE TITLE
Rsyslog->Kafka

### ISSUE THREAD

**Issue by MasterpieceRoy** [rsyslog/rsyslog#3861]
Hi. I am trying to send a log file which is in human readable format to kafka via rsyslog. The file is present in /var/log/example.log

The problem which I am facing is that when I check the topic to which I am sending in kafka it doesn't show any messages. So I guess it's not able to send any messages. Below is my example.conf file which I have configured in /etc/rsyslog.d/.
`module(load="imfile")` 
`module(load="omkafka")`                              

`template(name="examplelog" type="list") { `
` property(name="rawmsg")`
`}`

`input(`
`  type="imfile"`
`  File="/var/log/example.log"`
`  Tag="example_log"`
`  PersistStateInterval="1000"`
`  ruleset="example_log"`
`)`

`ruleset(name="example_log") {`
`  action(`
`    type="omkafka"`
`    topic="example_metrics"`
`    broker= "kafka-1:9092"`
`    template="examplelog"`
`    confParam=[`
`      "socket.timeout.ms=1000",`
`      "socket.keepalive.enable=true",`
`      "queue.buffering.max.messages=1000",`
`      "queue.buffering.max.ms=100"`
`    ]`
`    queue.type="LinkedList"`
`    queue.spoolDirectory="/tmp/example"`
`    queue.filename="example_log"`
`    queue.size="3000"`
`    queue.saveonshutdown="on"`
`    queue.highwatermark="2000"`
`    queue.lowwatermark="200"`
`    queue.discardmark="2500"`
`    queue.dequeuebatchsize="1"`
`    action.resumeRetryCount="-1"                          `   
`  )`
`} `

**Comment by rgerhards** [comment]
any error message (or any messages at all) from rsyslog? rsyslog version?

**Comment by MasterpieceRoy** [comment]
There are no error messages from rsyslog. The rsyslog version is rsyslogd 8.23.0

**Comment by rgerhards** [comment]
rsyslog version is most probably the issue - 8.32.0 is veeeeery old (~3yrs) and known to have broken kafka. Try with current (8.1908.0).

**Comment by MasterpieceRoy** [comment]
Ok.Cool. Let me check and report back.

**Comment by MasterpieceRoy** [comment]
Btw is the configuration correct ? Just to be sure.

**Comment by rgerhards** [comment]
I don't know exactly but would need to dig deeper. Not a kafka expert. But I **do know** about the defects in early versions ;-)

**Comment by MasterpieceRoy** [comment]
Lol. Well, I can't update the rsyslog version as I have lots of servers and updating in all of them is troublesome. Any workarounds ? Will appreciate it though. :)

**Comment by rgerhards** [comment]
backport patches, build your own [io]mkafka, distribute it

**Comment by MasterpieceRoy** [comment]
And I have a different .conf file where it seems to work. The input module is imudp and the output module is omkafka. It works for that. But when I use the imfile and omkafka combination it doesn't work.

**Comment by rgerhards** [comment]
Just to name a few...
* https://github.com/rsyslog/rsyslog/issues/1515
* https://github.com/rsyslog/rsyslog/issues/1584
* https://github.com/rsyslog/rsyslog/issues/1052

**Comment by MasterpieceRoy** [comment]
Appreciate it. Thank for the help. I'll check and pester you again if needed.

**Comment by MasterpieceRoy** [comment]
Hey. So is there any such thing that we can't use imfile modules in 2 different configs at the same time. Say for example a.conf also has imfile and b.conf also has imfile. Is it not possible ?

**Comment by davidelang** [comment]
you can only load a module once, but you can define as many inputs as you want.

David Lang

**Comment by MasterpieceRoy** [comment]
So if we load it once in a file it should work even for other config files,right ?

**Comment by davidelang** [comment]
yes. when you include a file, it's exactly as if you pasted that file at the 
point of the include.

the latest versions offer a -o flag that will dump out a version of the combined 
config files the way that rsyslog understands it (it's not perfect yet, but it's 
very helpful)

David Lang

**Comment by MasterpieceRoy** [comment]
Sounds good. Let me try. Thanks !!! :)
