### ISSUE TITLE
Doc request: OBS repo setup

### ISSUE THREAD

**Issue by darakian** [rsyslog/rsyslog#3863]
Hey, I'm trying to add the ubuntu repo from your OBS account (http://download.opensuse.org/repositories/home:/rgerhards/) and am running into issues getting it added. Can I request a quick doc on adding this repo? I'm using this instead of the ppa for the omhttp package.

**Comment by rgerhards** [comment]
Doc is provided by OBS: https://software.opensuse.org//download.html?project=home%3Argerhards&package=rsyslog (this is also linked to from main rsyslog site).
