### ISSUE TITLE
Unable to acknowledge message in OmProg. Version table:  8.24.0-1 500

### ISSUE THREAD

**Issue by sachin09** [rsyslog/rsyslog#3864]
Error while using below params in OmProg: 
1. fileCreateMode
2. killUnresponsive
3. confirmTimeout
4. confirmMessages

My Config is as follows:
action(type="omprog"
       name="parser"
       binary="/tmp/parser.py"
       queue.type="Disk"
       queue.size="100000"
       queue.saveOnShutdown="on"
       queue.workerThreads="5"
       queue.maxdiskspace="1g"
       queue.maxfilesize="10m"
       queue.spoolDirectory="/var/run/rsyslog"
       queue.filename="ib_queue"
       action.resumeInterval="5"
       confirmMessages="on"
       confirmTimeout="30000"
       killUnresponsive="on"
       fileCreateMode="600"
       output="/tmp/queue.log"
       )

Below are syslogs. Please help

Sep 16 10:50:13 fk-cloud-g1a-ms-1272298 rsyslogd: error during parsing file /etc/rsyslog.d/50.0-cosmos-mothership-stats.conf, on or before line 39: parameter 'fileCreateMode' not known -- typo in config file? [v8.27.0.11. try http://www.rsyslog.com/e/2207 ]
Sep 16 10:50:13 fk-cloud-g1a-ms-1272298 rsyslogd: error during parsing file /etc/rsyslog.d/50.0-cosmos-mothership-stats.conf, on or before line 39: parameter 'killUnresponsive' not known -- typo in config file? [v8.27.0.11. try http://www.rsyslog.com/e/2207 ]
Sep 16 10:50:13 fk-cloud-g1a-ms-1272298 rsyslogd: error during parsing file /etc/rsyslog.d/50.0-cosmos-mothership-stats.conf, on or before line 39: parameter 'confirmTimeout' not known -- typo in config file? [v8.27.0.11. try http://www.rsyslog.com/e/2207 ]
Sep 16 10:50:13 fk-cloud-g1a-ms-1272298 rsyslogd: error during parsing file /etc/rsyslog.d/50.0-cosmos-mothership-stats.conf, on or before line 39: parameter 'confirmMessages' not known -- typo in config file? [v8.27.0.11. try http://www.rsyslog.com/e/2207 ]

**Comment by rgerhards** [comment]
The version is simply too old.

**Comment by sachin09** [comment]
Sample is mentioned here: https://www.rsyslog.com/doc/v8-stable/configuration/modules/omprog.html#forcesingleinstance

Like:
action(type="omprog"
       name="db_forward"
       binary="/usr/share/logging/db_forward.py"
       confirmMessages="on"
       confirmTimeout="30000"
       queue.type="LinkedList"
       queue.saveOnShutdown="on"
       queue.workerThreads="5"
       action.resumeInterval="5"
       killUnresponsive="on"
       output="/var/log/db_forward.log")

**Comment by sachin09** [comment]
What is the recommended version of rsyslog for Debian Stretch and Jessie?

**Comment by davidelang** [comment]
the only version the community officially supports is the current one (8.1908 
currently) We are always going to recommend that you run a supported version ;-) 
In practice, we support older versions where it's not too much work.

if your distro opts to give you an older version and claims to offer support, 
they are deciding to support the older versions that they ship.

8.24 is almost 3 years old (16 versions released before we switched the 
numbering and then another 5 or 6 versions after that). the version of the docs 
that it shipped with didn't list these options, but the most current version of 
the docs that is online is always for the most current version

David Lang
