### ISSUE TITLE
install omrabbitmq in production servers

### ISSUE THREAD

**Issue by alah64** [rsyslog/rsyslog#3867]
hello.
i need to use omrabbitmq but ./configure --enable-omrabbitmq and make rsyslog is not avalable scenario on our customers .(some systems didnt have internet , many packages need to install before and some times there is a problem with the installation process.)

for install other packages exists scripts like `apt install rsyslog-hiredis` and so.
is there any other way to install omrabbitmq in production servers ?

os : debian 9
thanks.

**Comment by ubellavance** [comment]
You could create your own package and copy them on the servers, or make a private repo and use apt.

**Comment by dunkboy** [comment]
I find you can excute yum install -y rsyslog-rabbitmq,but use module(load='omrabbitmq')
action(type="omrabbitmq"
       host="localhost"
       virtual_host="/"
       user="guest"
       password="guest"
       ssl="on"
       verify_peer="off"
       verify_hostname="off"
       heartbeat_interval="20"
       exchange="syslog"
       routing_key="syslog.all")  can not connection rabbitmq server ,I don't know why

**Comment by davidelang** [comment]
what error do you get? is there a config error in rsyslog when you run rsyslogd 
-N1 ?

do you have authenticatin problems connecting to rabbitmq? (does it log any 
errors?)

do you have ssl authentication issues?

we can't know your system

David Lang
