### ISSUE TITLE
rsyslogd segfaults when given empty forwarders

### ISSUE THREAD

**Issue by gcoxmoz** [rsyslog/rsyslog#3868]
rsyslogd was working fine.  We then had a goof with our configuration management, and our UDP-forwarding lines went from `local0.* @10.x.y.z` to `local0.* @` and rsyslogd was told to restart in this condition.

Now, it gets a little handwavey at this point.  That's obviously a bad config, and if you try to **start** rsyslog with that config it will refuse (yay), but if you **restart** in this condition, it will keep running, but it puts systemd-journald into a bad state, such that we had to `systemctl restart systemd-journald.socket` to get most of our logging back.

I haven't figured out that issue enough to file an issue on it.  It's hard because it's killing our logging right at the moment I need it to triage what's killing our logging.  So if that makes sense, feel free to look into it, but that's not why I'm filing an issue right now.

We got occasional segfaults during those restarts: `rsyslogd[29425]: segfault at 1a8 ip 00005627b6e32ac1 sp 00007ffe09014f50 error 4 in rsyslogd[5627b6df6000+95000]`  My suspicion is that something (maybe tools/omfwd.c parseSelectorAct ?) is not happy when there's no characters after the @ sign in the config file, and maybe it assumes there will always be SOME character afterwards?

### Expected behavior
No segfaults, logging continues / journald doesn't hang

### Actual behavior
Segfaults, journald hangs

### Steps to reproduce the behavior
Unfortunately I've not been able to reliably cause the segfault to occur on demand, but when I have, it's these steps:

- Start rsyslogd with an acceptable config file that has forwarders.
- Edit the config file, delete all the forwarding IPs
- restart rsyslogd
- Check for a logged segfault in /var/log/messages

### Environment
- rsyslog version: 8.24.0-34.el7
- platform: CentOS 7.6

Conf file in regular configuration (I know, the directives are old.  I just started looking at this setup).

```$PreserveFQDN on
$ModLoad imuxsock.so	# provides support for local system logging (e.g. via logger command)
$ModLoad imklog.so	# provides kernel logging support (previously done by rklogd)
$ModLoad imudp.so
$UDPServerRun 514
$ActionFileDefaultTemplate RSYSLOG_TraditionalFileFormat
$IncludeConfig /etc/rsyslog.d/*.conf
:msg, regex, "type=[0-9]* audit" ~
:msg, contains, "rate limit exceeded" ~
:msg, contains, "audit_lost=" ~
:msg, contains, "dispatch err (pipe full) event lost" ~
:msg, contains, "dispatch error reporting limit reached - ending report notification." ~
:msg, contains, "error converting sid to string" ~
:msg, contains, "queue is full - dropping event" ~
*.info;local3.none;mail.none;authpriv.none;cron.none;local2.none;local5.none;local6.none;local7.!*	    /var/log/messages
authpriv.*                                              /var/log/secure
mail.*                                                  -/var/log/maillog
cron.*                                                  /var/log/cron
*.emerg;local3.!*                                                 *
uucp,news.crit                                          /var/log/spooler
authpriv.*                                              @10.50.75.54
daemon.*                                                @10.50.75.54
kern.*                                                  @10.50.75.54
auth.*							@10.50.75.54
cron.*							@10.50.75.54
local1.*                                                @10.50.75.54
local3.*                                                @10.50.75.54
local4.*                                                @10.50.75.54
local6.*                                                @10.50.75.54
# (postgres)
local0.*                                                @10.50.75.54
```

**Comment by rgerhards** [comment]
Can you reproduce this with a current version? 8.24 is almost 3 years old. We are now at 8.1908.0.

**Comment by davidelang** [comment]
a HUP doesn't re-read the config, and a restart should be a full stop/start (at 
lest as far as the config parsing goes) so what I would expect to see is that it 
stops, but fails to start throwing an error somewhere that it's probably 
ignored/lost :-/

David Lang

**Comment by gcoxmoz** [comment]
I'm sorry, this turned out to be not-an-issue, after a much deeper investigation.  I do have a bug to file, but it's not this.  The segfault was cropping up when as I hit the bug in the RHEL7 version, and I thought that the segfault was an issue, when in fact it was unrelated.  In upstream this problem exists in <=8.34 and is gone in >=8.35, and whatever the exact patch was wasn't cherry-picked back into RHEL.  So, nothing to see here, sorry for the noise.  I'll be back with a better issue when I've got it written up.
