### ISSUE TITLE
Error in rule action causes global directive to be ignored

### ISSUE THREAD

**Issue by gcoxmoz** [rsyslog/rsyslog#3871]
When parsing a config file that contains an error, it is possible to end up skipping/missing other lines in the config that happen before the broken line and do not contain errors.

In the example below, a rule with a bad action leads to ignoring a global directive.

While this example does use obsolete'd syntax, since the syntax is accepted and used correctly in the most modern version (and the issue could be part of parsing decisions made against modern syntax (I don't know)) I thought this was worth raising as an issue.

### Expected behavior
Configuration directives that are correct are used.

### Actual behavior
$SystemLogSocketName is ignored and unexpectedly falls back to its default.

### Steps to reproduce the behavior
Cut-pasteable:
```
cat <<EOF > /tmp/repro-good
\$ModLoad imuxsock
\$SystemLogSocketName /run/systemd/journal/syslog
authpriv.* @10.50.75.54
EOF
cat <<EOF > /tmp/repro-bad
\$ModLoad imuxsock
\$SystemLogSocketName /run/systemd/journal/syslog
authpriv.* @
EOF
# backslashes are just there because of bash/pasting
# The 'bad' file has an '@' with no UDP forwarder specified.

systemctl restart systemd-journald.socket
/bin/cp /tmp/repro-good /etc/rsyslog.conf
service rsyslog restart
lsof | grep /run/systemd/journal/syslog
lsof | grep /dev/log
# notice rsyslog uses /run/systemd/journal/syslog, systemd uses /dev/log : good and expected

systemctl restart systemd-journald.socket
/bin/cp /tmp/repro-bad /etc/rsyslog.conf
service rsyslog restart
lsof | grep /run/systemd/journal/syslog
lsof | grep /dev/log
# notice rsyslog and systemd both use /dev/log : bad and unexpected
```

### Environment
- rsyslog version: 8.1908.0
- platform: CentOS 7.6 and 7.7
- config:
```
[root@localhost ~]# cat /tmp/repro-good
$ModLoad imuxsock
$SystemLogSocketName /run/systemd/journal/syslog
authpriv.* @10.50.75.54
[root@localhost ~]# cat /tmp/repro-bad
$ModLoad imuxsock
$SystemLogSocketName /run/systemd/journal/syslog
authpriv.* @
```

**Comment by davidelang** [comment]
sorry I didn't respond earlier.

Yes, when you have errors in the config, it confuses the parser and can cause 
other things in the config to not be parsed. Depending on exactly what the error 
is (for example, unmatched quotes), I don't see a good way to fix this 
fundamental problem.

I'm not sure how much effort it would be worth to make the rsyslog config engine 
make guesses about what you mean. It's far safer to just error out, reporting 
that the config is invalid. Right now we do a midpoint between these that I'm 
not sure is really good for anyone, but it has been this way a long time, so to 
change the behavior I think we would need to justify why the new behavior is an 
improvement (especially in a world where stdout from daemons is frequently lost)

David Lang

**Comment by rgerhards** [comment]
> I'm not sure how much effort it would be worth to make the rsyslog config engine make guesses about what you mean. It's far safer to just error out, reporting that the config is invalid.

Is dangerous and a loooooooooot of work. Right now we use standard lex/yycc parsers. To handle this, we would need to write the parsing by ourselves. Even then I think it would not necessarily be possible, because the grammar is not context-free. Instead, it actually has some context-sensitive parts to support legacy constructs.  I think I can also mathematically proof that deterministically skipping error cases (and just them) is not always possible. But I don't like to craft the proof ;-)
