### ISSUE TITLE
asynwr_deadlock2 fails on s390x, sparc64, hppa, ppc64, mips, powerpc

### ISSUE THREAD

**Issue by mbiebl** [rsyslog/rsyslog#3885]
Version: 8.1908.0

Since 8.1908.0, rsyslog fails to build on s390x on Debian, specifically it fails during `make check` when running the test-suite.

```
FAIL: asynwr_deadlock2
======================

testbench: TZ env var not set, setting it to UTC
------------------------------------------------------------
12:32:33[0]  Test: ./asynwr_deadlock2.sh
------------------------------------------------------------
config rstb_171544_e7e00756_.conf is:
     1	module(load="../plugins/imdiag/.libs/imdiag")
     2	global(inputs.timeout.shutdown="60000"
     3	       default.action.queue.timeoutshutdown="20000"
     4	       default.action.queue.timeoutEnqueue="20000")
     5	$MainmsgQueueTimeoutEnqueue 20000 # use legacy-style so that we can override if needed
     6	$IMDiagListenPortFileName rstb_171544_e7e00756.imdiag.port
     7	$IMDiagServerRun 0
     8	$IMDiagAbortTimeout 580
     9	
    10	:syslogtag, contains, "rsyslogd"  ./rstb_171544_e7e00756.started
    11	###### end of testbench instrumentation part, test conf follows:
    12	
    13	$ModLoad ../plugins/imtcp/.libs/imtcp
    14	$MainMsgQueueTimeoutShutdown 10000
    15	$InputTCPServerRun 45093
    16	
    17	$template outfmt,"%msg:F,58:3%,%msg:F,58:4%,%msg:F,58:5%\n"
    18	$template dynfile,"rstb_171544_e7e00756.%msg:F,58:2%.log" # use multiple dynafiles
    19	
    20	$OMFileFlushOnTXEnd on
    21	$OMFileFlushInterval 10
    22	$OMFileIOBufferSize 10k
    23	$OMFileAsyncWriting on
    24	$DynaFileCacheSize 4
    25	local0.* ?dynfile;outfmt
rsyslogd: NOTE: RSYSLOG_DEBUG_TIMEOUTS_TO_STDERR activated
rsyslogd: info: imdiag does 20 empty checks due to CI_SHUTDOWN_QUEUE_EMPTY_CHECKS
main Q:Reg: worker start requested, num workers currently 0
main Q:Reg: wrkr start initiated with state 0, num workers now 1
rsyslog debug: main Q:Reg: worker 0x2aa3a159d60 started
rsyslog debug: main Q:Reg: started with state 3, num workers now 1
12:32:33[0]  rstb_171544_e7e00756:.pid found, pid 44859
12:32:33[0]  rsyslogd startup msg seen, pid  44859
waiting for file rstb_171544_e7e00756.imdiag.port
imdiag port: 45559
starting run 1
Sending 20000 messages.
rsyslogd: file './rstb_171544_e7e00756.3.log': open error: Too many open files [v8.1908.0 try https://www.rsyslog.com/e/2433 ]
rsyslogd: file './rstb_171544_e7e00756.1.log': open error: Too many open files [v8.1908.0 try https://www.rsyslog.com/e/2433 ]
rsyslogd: file './rstb_171544_e7e00756.4.log': open error: Too many open files [v8.1908.0 try https://www.rsyslog.com/e/2433 ]
rsyslogd: file './rstb_171544_e7e00756.0.log': open error: Too many open files [v8.1908.0 try https://www.rsyslog.com/e/2433 ]
rsyslogd: file './rstb_171544_e7e00756.2.log': open error: Too many open files [v8.1908.0 try https://www.rsyslog.com/e/2433 ]

[100s of such lines snipped]

rsyslogd: file './rstb_171544_e7e00756.2.log': open error: Too many open files [v8.1908.0 try https://www.rsyslog.com/e/2433 ]
rsyslogd: file './rstb_171544_e7e00756.4.log': open error: Too many open files [v8.1908.0 try https://www.rsyslog.com/e/2433 ]
rsyslogd: file './rstb_171544_e7e00756.0.log': open error: Too many open files [v8.1908.0 try https://www.rsyslog.com/e/2433 ]
rsyslogd: file './rstb_171544_e7e00756.3.log': open error: Too many open files [v8.1908.0 try https://www.rsyslog.com/e/2433 ]
rsyslogd: file './rstb_171544_e7e00756.4.log': open error: Too many open files [v8.1908.0 try https://www.rsyslog.com/e/2433 ]
rsyslogd: file './rstb_171544_e7e00756.0.log': open error: Too many open files [v8.1908.0 try https://www.rsyslog.com/e/2433 ]
rsyslogd: file './rstb_171544_e7e00756.3.log': open error: Too many open files [v8.1908.0 try https://www.rsyslog.com/e/2433 ]
timeoutGuard: rsyslog still active after expiry of guard period (strtTO 1569760353, endTO 1569760933, time now 1569760933, diff 580), pid 44859 - initiating abort()
receiving response: Connection reset by peer
./diag.sh: line 504: 44859 Aborted                 (core dumped) LD_PRELOAD= ../tools/rsyslogd -C -n -irstb_171544_e7e00756:.pid -M../runtime/.libs:../.libs -frstb_171544_e7e00756_.conf
trying to obtain crash location info
note: this may not be the correct file, check it
./diag.sh: line 1161: gdb: command not found
not reporting failure as RSYSLOG_STATSURL is not set
rsyslog pid file still exists, trying to shutdown...
./diag.sh: line 843: kill: (44859) - No such process
12:42:13[580]  FAIL: Test ./asynwr_deadlock2.sh (took 580 seconds)
FAIL asynwr_deadlock2.sh (exit status: 1)
```

I can reliably reproduce the issue on a s390x porter box. Running git bisect points at 7ad178cea388dd1ffc9ac17ae2fecae32c8443b3 as the first faulty commit.
Reverting that commit makes asynwr_deadlock2.sh pass.
Unfortunately, reverting that commit also has the effect that it causes gzipwr_hup_multi_file and
gzipwr_hup_single_file to fail.

Since the issue is easily reproducible on the porter box, I can run further diagnostics, test patches etc.

**Comment by rgerhards** [comment]
Would it be possible to generate a debug log on the porter box?

**Comment by mbiebl** [comment]
Can you give me some guidance how I can generate such a debug log?

**Comment by rgerhards** [comment]
can you run a test manually? e.g:
```
$ cd tests
$ ./asynwr_deadlock2.sh
```

If so, it is sufficient to change ./tests/diag.sh, uncommenting the debug support: https://github.com/rsyslog/rsyslog/blob/master/tests/diag.sh#L79 -- lines 79 and 80 should be enabled. Then, after the run, the file `log` contains the debug log.

**Comment by mbiebl** [comment]
[log.gz](https://github.com/rsyslog/rsyslog/files/3680835/log.gz)
The file was 73M, so I gzipped it.

**Comment by rgerhards** [comment]
Thx - very interesting. Looks a bit like a file handle leak (missing close). Will investigate!

**Comment by mbiebl** [comment]
Lemme know if when you have code to test. If you have a wip/ git branch I can pull from there.

**Comment by rgerhards** [comment]
I am trying to reproduce the issue. It think part of the picture is that the scheduler on s390 has different timing and so the check is always called when the output file is not yet open. I would like to be able to reproduce that. We then would also have a permanent test in CI, which would be really good.

**Comment by mbiebl** [comment]
@rgerhards do you suspect this is a real bug which was found by the test suite or should I ignore the test suite failure?
Currently this test suite failure is blocking newer versions of rsyslog to enter testing.

**Comment by mbiebl** [comment]
Looking at https://buildd.debian.org/status/logs.php?pkg=rsyslog&ver=8.1908.0-1&suite=sid, rsyslog fails on several more architectures.
https://wiki.debian.org/ArchitectureSpecificsMemo → This might be an endian issue, since afaics all those architectures are big endian

**Comment by rgerhards** [comment]
> @rgerhards do you suspect this is a real bug which was found by the test suite or should I ignore the test suite failure?

I would tend to say it is a real bug, but NOT a new one. I guess it's timing related, but I may be wrong. I just got #3909 in. If the issue repeatedly does not occur on older versions, it would be a regression but I really don't think so. I am looking at the issue, but I still have to somewhat recover from the work involved with last month visit to Tallinn.

**Comment by rgerhards** [comment]
@mbiebl could you retry with current master branch? Analyzing this further, it looks like https://github.com/rsyslog/rsyslog/commit/7ad178cea388dd1ffc9ac17ae2fecae32c8443b3#diff-8e18a52e9e4e4d9759f1e62eb4b5d6d7 could have fixed the issues as a "side-effect". Unfortunately I cannot reproduce the issue, so I cannot check myself.

**Comment by rgerhards** [comment]
@mbiebl I forgot to mention:  this patch was part of 8.1910.0. So if that failed as well, we do not need a retry.

**Comment by rgerhards** [comment]
@mbiebl lol, sry, this is the commit that you pointed to by "git bisect" ;-) Will further investigate and also remove the last three postings from github history to avoid confusion.

**Comment by rgerhards** [comment]
@mbiebl good news: I can "reproduce" the issue if I disable `flushOnTXEnd`. While it's a different config, I think the root cause is the same. I will concentrate on that now.

If you like, you can apply the patch from PR #3921 - just be careful: I am not yet sure if there are other dangling issues and so the fix needs to be different. But would still be good to know if I am on the right path.

**Comment by mbiebl** [comment]
Applying the patch from #3921 makes the test-suite pass on s390x (haven't tested with other archs)

**Comment by mbiebl** [comment]
#3922 fixes it as well for me (tested on s390x). 
I've applied this PR on top of v8.1910.0 fwiw.
