### ISSUE TITLE
Crush & restart "kernel: traps: in:imfile"

### ISSUE THREAD

**Issue by 1lyasam** [rsyslog/rsyslog#3886]
###Expected behavior
logs being sent in syslog protocol to syslog server with UDP port 514
from various log files with imfile module
### Actual behavior
logs being sent repeatedly, probably because rsyslog crushes and restarts
every few minutes
found error log repeated in /var/log/messages
`" kernel: traps: in:imfile[117323] general protection ip:555555574325 sp:7fffec054868 error:0 in rsyslogd[555555554000+95000]"`
same setup was done in many servers , but on few specific we have those crushes
(looks like the servers where those file written massivly)

### Steps to reproduce the behavior
Couldn't reproduce behaviour
### Environment
- rsyslog version: 
`rsyslogd 8.24.0-41.el7_7, compiled with:
        PLATFORM:                               x86_64-redhat-linux-gnu
        PLATFORM (lsb_release -d):
        FEATURE_REGEXP:                         Yes
        GSSAPI Kerberos 5 support:              Yes
        FEATURE_DEBUG (debug build, slow code): No
        32bit Atomic operations supported:      Yes
        64bit Atomic operations supported:      Yes
        memory allocator:                       system default
        Runtime Instrumentation (slow code):    No
        uuid support:                           Yes
        Number of Bits in RainerScript integers: 64`

- platform: Red Hat Enterprise Linux Server release 7.7 (Maipo)

Configuration Attached
I obfiscated most of the paths/Tags/ip 
[Rsyslog Template for GitHub.txt](https://github.com/rsyslog/rsyslog/files/3686827/Rsyslog.Template.for.GitHub.txt)

Thanks in advance :)

**Comment by rgerhards** [comment]
This is a very old version. Please check if you can reproduce the issue with the currently supported version (8.10.0). I doubt.

**Comment by 1lyasam** [comment]
Thanks for response !
is 8.10 is newer than 8.24 ? what am i missing here ? :)

**Comment by rgerhards** [comment]
sry - there was a typo in my message. Current is 8.1910.0.

**Comment by redy01** [comment]
same here, 
RHEL 7.7,
rsyslog.x86_64 ver. 8.24.0-41.el7_7
This issue occurs after reboot only, on few servers only and not always.

**Comment by davidelang** [comment]
8.24 was released almost 3 years ago, imfile has been refactored at least once since then.

Try the current version or ask RedHat to investigate why their custom version still has this problem (they backport some, but not all fixes from later versions to the 8.24 they ship)
