### ISSUE TITLE
transactional error handling has memcpy issue

### ISSUE THREAD

**Issue by kortemik** [rsyslog/rsyslog#3898]
### Expected behavior
Failed messages would be resubmitted to omfile properly

### Actual behavior
Failed messages break dynafile output filesystem structure and are written all over the filesystem, message part is used as dynafile path. This is due to improper copying of memory structure.

### Steps to reproduce the behavior
omfile plugin with dynafile and cause part of the batched messages to fail, then pass some through and cause some others to fail. Fail more than 1 messages.

### Environment
- rsyslog version: latest
- platform: linux
- for configuration questions/issues, include rsyslog.conf and included config files
omfile plugin with dynafile

# Fixed in #3869

**Comment by rgerhards** [comment]
fixed via #3869
