### ISSUE TITLE
DoDie written to queue data file

### ISSUE THREAD

**Issue by adruch** [rsyslog/rsyslog#390]
The message "DoDie called" is being printed inside the data file for the queue when rsyslog is stopped when running DebugLevel=2 (DEBUG_FULL).

In the function rsyslogdDoDie(), this die message is being written to file descriptor 1. In the debug log, I also noticed that this queue data file has a file descriptor of 1. I believe this extra text could be the reason why I see objDeserialize errors when I start rsyslog again.

**Comment by rgerhards** [comment]
this seems to have been fixed long ago.
