### ISSUE TITLE
rsyslog in docker: Route received sylogs (UDP) to remote syslog server and local logs to stdout for Docker logs API collection?

### ISSUE THREAD

**Issue by sgreszcz** [rsyslog/rsyslog#3914]
# Expected behavior

I'm trying to build a syslog forwarder appliance in Docker that forwards received syslog packets on UDP 514 to a remote syslog destination.  I also want to monitor the rsyslog container and would like to send the localhost syslogs only to stdout so that they can be collected/viewed by the "docker logs' API. 

I don't want the local syslogs forwarded to the remote server, nor do I want the received UDP syslogs to be written to stdout.

### Actual behavior

I can do one or the other (route all to stdout or forward all) but I don't know how to tag or filter the inputs and route to specific outputs.

### Environment
- rsyslog version: 
- platform: 

rsyslogd 8.40.0, compiled with:
	PLATFORM:				x86_64-alpine-linux-musl

- for configuration questions/issues, include rsyslog.conf and included config files

I've referenced https://github.com/jabenninghoff/rsyslog-forwarder which is a very minimal config using only supervisord and rsyslogd:
```
rsyslog.conf:

# local system logging, commented out for now as want to write to stdout, not remote syslog server
#module(load="imuxsock")
#input(type="imuxsock" Socket="/var/run/rsyslog/dev/log" CreatePath="on")

# run UDP syslog on syslog port 514
module(load="imudp")
input(type="imudp" port="514")

# configure outputs

#forward to remote syslog server
*.*  action(type="omfwd" target="my-remote-server.com" port="514" protocol="udp")

# default is to send all output to stdout, but want only localfiles - not sure how to do this
#$ModLoad omstdout.so
#*.* :omstdout:
```

**Comment by davidelang** [comment]
the easiest way to do this is to define a ruleset and have the logs arriving 
remotely go to that ruleset (part of the input() sttement) and then the default 
ruleset (i.e. things not in your new ruleset) is used for locally generated 
stuff.

David Lang

**Comment by sgreszcz** [comment]
> the easiest way to do this is to define a ruleset and have the logs arriving remotely go to that ruleset (part of the input() sttement) and then the default ruleset (i.e. things not in your new ruleset) is used for locally generated stuff. David Lang

Thanks, I'll have to study some more about rulesets then and how to bind them to inputs/outputs.  It's not that obvious how after reading the docs and googling for examples.  I have done something like this with InfluxDB's telegraf and it was really easy with tagging and "tagpass"

**Comment by rgerhards** [comment]
This may be useful: https://rainer.gerhards.net/2019/10/rsyslog-relay-messages-only-no-local-storage.html

**Comment by sgreszcz** [comment]
> This may be useful: https://rainer.gerhards.net/2019/10/rsyslog-relay-messages-only-no-local-storage.html - note that it talks about rulesets in the lower half.

I actually did sort of get it working, but not the way I expected.  My working configuration had one ruleset bound to the 514 UDP input, and the rest *.* goes to stdout.

```
# configure inputs

# local system logging
module(load="imuxsock")
input(type="imuxsock" Socket="/var/run/rsyslog/dev/log" CreatePath="on")

# run UDP syslog on syslog port 514
module(load="imudp")
input(type="imudp" port="514" ruleset="syslogin")

# configure output actions with rulesets for UDP 514 outbound

ruleset(name="syslogin"){
        action(type="omfwd" target="cdc-alln-stg.cisco.com" port="514" protocol="udp")
}

# default is to send all output to stdout, in this case only localfiles, as UDP 514 input is forwarded to 514 UDP.
$ModLoad omstdout.so
*.* :omstdout:
```

However, when I tried to make two rulesets with two different outputs and bind one to each of the inputs, that didn't work: only the UDP 514 logs were received (not stdout).  Any ideas why this syntax wouldn't work?

```
$ModLoad omstdout.so

# configure inputs

# local system logging
module(load="imuxsock")
input(type="imuxsock" Socket="/var/run/rsyslog/dev/log" CreatePath="on" ruleset="local")

# run UDP syslog on syslog port 514
module(load="imudp")
input(type="imudp" port="514" ruleset="syslogin")

# configure output actions via rulesets

ruleset(name="syslogin"){
        action(type="omfwd" target="cdc-alln-stg.cisco.com" port="514" protocol="udp")
}

ruleset(name="local"){
        action(type="omstdout")
}
```

**Comment by davidelang** [comment]
On Fri, 18 Oct 2019, sgreszcz wrote:

>> the easiest way to do this is to define a ruleset and have the logs arriving remotely go to that ruleset (part of the input() sttement) and then the default ruleset (i.e. things not in your new ruleset) is used for locally generated stuff. David Lang
>
> Thanks, I'll have to study some more about rulesets then and how to bind them to inputs/outputs.  It's not that obvious how after reading the docs and googling for examples.  I have done something like this with InfluxDB's telegraf and it was really easy with tagging and "tagpass"

in the input() statement you just say ruleset='name of ruleset'

then in the main section you have a section
ruleset(name="name of ruleset"){
  list of actions you want to happen for the logs
}

David Lang

**Comment by davidelang** [comment]
P.S. any suggestions on how to make the docs clearer, or even better patches for 
the docs are extremely welcome. Most of the people who have written the docs are 
far too experienced and don't see gaps in the docs that hinder newcomers.

David Lang

**Comment by davidelang** [comment]
I think imuxsock didn't support rulesets until a very recent version (I'm not 
sure it does now, I know it didn't a couple years ago), but that's one of the 
very few input modules that didn't.

David Lang

**Comment by sgreszcz** [comment]
It is:

rsyslogd 8.40.0, compiled with:
PLATFORM:	x86_64-alpine-linux-musl

That might be the problem, rule sets don’t work with imuxsock or something. The ruleset applied to the imudp seems to work, and the default rule seems to capture the container localhost (socket) syslog and route to Stdout. 

I’m ok with that. Next week I’ll try outputting the udp514 input to multiple output types.

Thank you very much for your help!

**Comment by davidelang** [comment]
Ok, 8.40 was released at the end of 2018 (just before we switched version 
numbers), 8.1910 is the current version.

I am not remembering for sure if imuxsock ws ever modified to support rulesets, 
so that could be your problem. If it doesn't, just put the statements that you 
want to be used for local logs outside of any ruleset definition.

David Lang
