### ISSUE TITLE
imuxsock slow processing

### ISSUE THREAD

**Issue by Rampa33** [rsyslog/rsyslog#3917]
I am using the latest version of rsylsog-8.39.0

For our application, we do not want to invoke syslog() in the main code path, as it could block. So we created a AF_UNIX DGRAM socket to /dev/log in Non-blocking mode. The range at which we generate logs is around 1500-2500 logs per second. 

rsylogd has been configured to output the logs to remote collectors. When we start logging from application, I end up getting lot of ERRNO 11(resource temporarily unavailable). Is it due to slow processing by rsyslogd compared to send speed?

Is imudp better than imuxsock for this kind of input? Or shall i make rsyslogd to listen to multiple Unix sockets and try to loadbalance logs from the application?

Or to decouple application & rsyslogd, going with imfile is better off? But compared with imuxsock & imudp, imfile method is very slower. Also it is creating lots of stat files under work directory.

I also tried to increase socket SO_SNDBUF size to around 180000, which did not help. I keep getting ERRNO 11. Please help.

notify @davidelang @rgerhards

**Comment by davidelang** [comment]
enable impstats to show what's happening inside rsyslog, but I doubt that 
rsyslog is the bottleneck at

On Mon, 21 Oct 2019, Rampa33 wrote:

> I am using the latest version of rsylsog-8.39.0

This is not the latest version, the latest version is 8.1910 (almost a year 
newer than 8.39)

> For our application, we do not want to invoke syslog() in the main code path, 
> as it could block.

it ould only block if ryslog as a whole blocks

> So we created a AF_UNIX DGRAM socket to /dev/log in 
> Non-blocking mode.

I don't think this is going to block any less if you write to /dev/log this way 
vs the standard syslog() api (I'd have to dig, but I think you have effectively 
recreate the syslog() function :-) )

> The range at which we generate logs is around 1500-2500 
> logs per second.

This shoudl not be a problem for rsyslog

> rsylogd has been configured to output the logs to remote collectors. When we 
> start logging from application, I end up getting lot of ERRNO 11(resource 
> temporarily unavailable). Is it due to slow processing by rsyslogd compared to 
> send speed?

impstats will show what's happening and if the main queue is filling up.

> Is imudp better than imuxsock for this kind of input? Or shall i make rsyslogd 
> to listen to multiple Unix sockets and try to loadbalance logs from the 
> application?

probably not. I've used rsyslog up to several hundred thousand messages/sec. but 
we would need the pstats info to see what's actually happening in your config 
(and see the config as well)

David Lang

**Comment by Rampa33** [comment]
HI @davidelang ,

I shall give a brief overview on the setup. My application generates high rate logs (1500 logs per second), and uses non-blocking send to /dev/log/, which will be picked by rsyslogd. Then it will write to local log file and export it to two other external syslog collectors. Based on your input, i got the below impstats when i used to get errno 11 for send()

`Wed Oct 23 06:57:29 2019: global: origin=dynstats
Wed Oct 23 06:57:29 2019: imuxsock: origin=imuxsock submitted=15940 ratelimit.discarded=0 ratelimit.numratelimiters=0
Wed Oct 23 06:57:29 2019: action-0-builtin:omfile: origin=core.action processed=15940 failed=0 suspended=0 suspended.duration=0 resumed=0
Wed Oct 23 06:57:29 2019: collector-1: origin=core.action processed=15934 failed=0 suspended=0 suspended.duration=0 resumed=0
Wed Oct 23 06:57:29 2019: collector-2: origin=core.action processed=15934 failed=0 suspended=0 suspended.duration=0 resumed=0
Wed Oct 23 06:57:29 2019: resource-usage: origin=impstats utime=2162821 stime=1681414 maxrss=5764 minflt=1400 majflt=5 inblock=960 oublock=39272 nvcsw=53802 nivcsw=176134 openfiles=15
Wed Oct 23 06:57:29 2019: collector-1 queue: origin=core.queue size=0 enqueued=15934 full=0 discarded.full=0 discarded.nf=0 maxqsize=264
Wed Oct 23 06:57:29 2019: collector-2 queue: origin=core.queue size=0 enqueued=15934 full=0 discarded.full=0 discarded.nf=0 maxqsize=240
Wed Oct 23 06:57:29 2019: main Q: origin=core.queue size=0 enqueued=15940 full=0 discarded.full=0 discarded.nf=0 maxqsize=1472






Wed Oct 23 06:57:39 2019: global: origin=dynstats
Wed Oct 23 06:57:39 2019: imuxsock: origin=imuxsock submitted=15940 ratelimit.discarded=0 ratelimit.numratelimiters=0
Wed Oct 23 06:57:39 2019: action-0-builtin:omfile: origin=core.action processed=15940 failed=0 suspended=0 suspended.duration=0 resumed=0
Wed Oct 23 06:57:39 2019: collector-1: origin=core.action processed=15934 failed=0 suspended=0 suspended.duration=0 resumed=0
Wed Oct 23 06:57:39 2019: collector-2: origin=core.action processed=15934 failed=0 suspended=0 suspended.duration=0 resumed=0
Wed Oct 23 06:57:39 2019: resource-usage: origin=impstats utime=2162878 stime=1681458 maxrss=5764 minflt=1400 majflt=5 inblock=960 oublock=39272 nvcsw=53803 nivcsw=176134 openfiles=15
Wed Oct 23 06:57:39 2019: collector-1 queue: origin=core.queue size=0 enqueued=15934 full=0 discarded.full=0 discarded.nf=0 maxqsize=264
Wed Oct 23 06:57:39 2019: collector-2 queue: origin=core.queue size=0 enqueued=15934 full=0 discarded.full=0 discarded.nf=0 maxqsize=240
Wed Oct 23 06:57:39 2019: main Q: origin=core.queue size=0 enqueued=15940 full=0 discarded.full=0 discarded.nf=0 maxqsize=1472

Wed Oct 23 06:57:49 2019: global: origin=dynstats
Wed Oct 23 06:57:49 2019: imuxsock: origin=imuxsock submitted=20665 ratelimit.discarded=0 ratelimit.numratelimiters=0
Wed Oct 23 06:57:49 2019: action-0-builtin:omfile: origin=core.action processed=20665 failed=0 suspended=0 suspended.duration=0 resumed=0
Wed Oct 23 06:57:49 2019: collector-1: origin=core.action processed=20659 failed=0 suspended=0 suspended.duration=0 resumed=0
Wed Oct 23 06:57:49 2019: collector-2: origin=core.action processed=20659 failed=0 suspended=0 suspended.duration=0 resumed=0
Wed Oct 23 06:57:49 2019: resource-usage: origin=impstats utime=2648135 stime=2097444 maxrss=7024 minflt=2073 majflt=5 inblock=960 oublock=51752 nvcsw=63057 nivcsw=219539 openfiles=15
Wed Oct 23 06:57:49 2019: collector-1 queue: origin=core.queue size=0 enqueued=20659 full=0 discarded.full=0 discarded.nf=0 maxqsize=264
Wed Oct 23 06:57:49 2019: collector-2 queue: origin=core.queue size=0 enqueued=20659 full=0 discarded.full=0 discarded.nf=0 maxqsize=240
Wed Oct 23 06:57:49 2019: main Q: origin=core.queue size=0 enqueued=20665 full=0 discarded.full=0 discarded.nf=0 maxqsize=2673

Wed Oct 23 06:57:59 2019: global: origin=dynstats
Wed Oct 23 06:57:59 2019: imuxsock: origin=imuxsock submitted=20665 ratelimit.discarded=0 ratelimit.numratelimiters=0
Wed Oct 23 06:57:59 2019: action-0-builtin:omfile: origin=core.action processed=20665 failed=0 suspended=0 suspended.duration=0 resumed=0
Wed Oct 23 06:57:59 2019: collector-1: origin=core.action processed=20659 failed=0 suspended=0 suspended.duration=0 resumed=0
Wed Oct 23 06:57:59 2019: collector-2: origin=core.action processed=20659 failed=0 suspended=0 suspended.duration=0 resumed=0
Wed Oct 23 06:57:59 2019: resource-usage: origin=impstats utime=2648230 stime=2097519 maxrss=7024 minflt=2073 majflt=5 inblock=960 oublock=51752 nvcsw=63058 nivcsw=219542 openfiles=15
Wed Oct 23 06:57:59 2019: collector-1 queue: origin=core.queue size=0 enqueued=20659 full=0 discarded.full=0 discarded.nf=0 maxqsize=264
Wed Oct 23 06:57:59 2019: collector-2 queue: origin=core.queue size=0 enqueued=20659 full=0 discarded.full=0 discarded.nf=0 maxqsize=240
Wed Oct 23 06:57:59 2019: main Q: origin=core.queue size=0 enqueued=20665 full=0 discarded.full=0 discarded.nf=0 maxqsize=2673
`

In my rsyslog.conf, i have configured main_queue(queue.size="1000000"). But in impstats, the size says 0. and max queue size is also smaller. May i know the reason? I have also done setsockopt for my application socket to /dev/log/ as 180000. In such a case, it should never get full at my rate right?

notify @rgerhards

**Comment by davidelang** [comment]
please post your config, the size is the size of the queue at the time the stats 
are dumped, the maxqsize is the max number of items that have been in the queue 
since the last time the stats were reset (which is either startup, or the last 
run, depending on your config)

This shows that noneof your ueues are coming close to filling up. There are ways 
that you can end up causing excessive locking overhead (this usually happens to 
people who try to use every possible way to make things asynchronous).

Back with rsyslog 3.22 I was doing 8000 logs/sec, and by early v5 I was doing 
300,000 logs/sec (wiht the limiting factor being gig-e wire speed), so 1500 
logs/sec should not be a problem with the right config.

If you have created too many queues and too many threads, you can end up with 
far more overhead from locking than time spent actully processing the logs.


so this is good info that rules out a lot of possible problems, now please post 
a config so we can check for others.

David Lang

**Comment by Rampa33** [comment]
@davidelang ,

Somehow i am able to achieve my expectation by logging to rsyslogd using imudp module. Logging to localhost:514 seems to be faster than /dev/log. I did not want to dig further into that, as we are ok with model that works for our logs.
