### ISSUE TITLE
imfile doesn't process logs after log has been truncated

### ISSUE THREAD

**Issue by rmetrich** [rsyslog/rsyslog#3918]
### Expected behavior

Log file processed after being truncated (Same inode for log file after rotation)

### Actual behavior

Log file not processed until offset has been reached or rsyslog has been restarted

### Steps to reproduce the behavior

1. Install nginx and modify /etc/logrotate.d/nginx to add "copytruncate"

2. Setup imfile on /var/log/nginx/access.log with polling or inotify (both reproducible)

   ~~~
   # cat /etc/rsyslog.d/imfile.conf 
   module(load="imfile" mode="polling")
   $InputFileName /var/log/nginx/access.log
   $InputFileTag nginx_tag
   $InputFileSeverity notice
   $InputFileFacility local6
   $InputFilePersistStateInterval 0
   $InputRunFileMonitor
   
   # systemctl restart rsyslog
   ~~~

3. Monitor /var/log/messages

   ~~~
   # tail -f /var/log/messages | grep nginx_tag
   ~~~

4. Create many nginx logs

   ~~~
   # for i in $(seq 1 1000); do curl http://localhost/step3 >/dev/null 2>&1; done
   ~~~

5. Rotate once logs are found in /var/log/messages

   ~~~
   # logrotate -f /etc/logrotate.d/nginx
   ~~~

6. Create some nginx logs

   ~~~
   # curl http://localhost/step6 >/dev/null 2>&1
   ~~~

--> Log never reaches /var/log/messages

### Environment
- rsyslog version: 8.36.0.master (rsyslog-8.1907.0-1.fc30.x86_64)
- platform: Fedora 30

**Comment by rgerhards** [comment]
please upgrade to rsyslog current (8.1910.0 as of this writing). Many bugs have been fixed in imfile since the version you use.

**Comment by rmetrich** [comment]
Hi @rgerhards 
Issue reproduces with 8.1911.0.master

**Comment by rgerhards** [comment]
I just noticed that the "reopenOnTruncate" parameter is missing, doc here:
https://www.rsyslog.com/doc/v8-stable/configuration/modules/imfile.html#reopenontruncate

There seems to be no obsolete legacy format statement for this parameter. So you need to convert to advanced config style.

**Comment by rmetrich** [comment]
All right, in fact I was trying to reproduce another bug where in some cases after log rotation of a file monitored by imfile, without using copytruncate, imfile was not processing new logs until the offset recorded in the state file was reached.
There were known issues in the recent past. I was able to reproduce with 8.1907.0 but don't know exactly how. Will now try with very latest.
Thanks for the tips anyway.
