### ISSUE TITLE
omfwd tcp - First message always lost after remote syslog restart

### ISSUE THREAD

**Issue by slb985** [rsyslog/rsyslog#3929]
### Expected behavior
When forwarding over tcp to a remote syslog server and after the remote syslog server is gracefully restarted, the client should reconnect and all messages should be sent and received successfully.

### Actual behavior
This is working fine under version rsyslog-8.40.0-1.el7.x86_64 but under version rsyslog-8.1901.0-1.el7.x86_64 and above the first message is always lost, it doesn't acknowledge that the established connection was broken 

### Steps to reproduce the behavior
- On client install version rsyslog-8.1901.0-1.el7.x86_64 or above and set up a tcp omfwd action with the following config:
```
  action(type="omfwd"
    target="<remote syslog server>"
    port="20514"
    protocol="tcp"
    ResendLastMSGOnReconnect="on"
    Keepalive="on"
    action.resumeInterval="1"
    action.resumeRetryCount="-1"
  )
```

- Restart syslog on remote server.
- Check client server connection status, shows CLOSED_WAIT.
- Send two messages. 
- 1st Message is never recevied

### Environment
Rsyslog version:
rsyslogd 8.40.0, compiled with:
        PLATFORM:                               x86_64-redhat-linux-gnu
        PLATFORM (lsb_release -d):
        FEATURE_REGEXP:                         Yes
        GSSAPI Kerberos 5 support:              Yes
        FEATURE_DEBUG (debug build, slow code): No
        32bit Atomic operations supported:      Yes
        64bit Atomic operations supported:      Yes
        memory allocator:                       system default
        Runtime Instrumentation (slow code):    No
        uuid support:                           Yes
        systemd support:                        Yes
        Number of Bits in RainerScript integers: 64

Platform:
Red Hat Enterprise Linux Server release 7.7 (Maipo)

Configuration:
```
global(workDirectory="/var/lib/rsyslog"
  preserveFQDN="on"
  action.reportSuspension="on"
  action.reportSuspensionContinuation="on"
  net.ipprotocol="ipv4-only"
  debug.logFile="/var/lib/rsyslog/debug"
)

include(file="/etc/rsyslog.d/*.conf")
module(load="imrelp" ruleset="lx-syslog")
input(type="imrelp" port="20514")

ruleset(name="lx-syslog" queue.filename="relp-queue" queue.type="LinkedList" queue.maxFileSize="1g" queue.saveonshutdown="on" ) {
  action(type="omfwd"
    target="<remote syslog server>"
    port="20514"
    protocol="tcp"
    ResendLastMSGOnReconnect="on"
    Keepalive="on"
    action.resumeInterval="1"
    action.resumeRetryCount="-1"
  )
}
```

[Debug of 1st message v8.1901 - Failing.txt](https://github.com/rsyslog/rsyslog/files/3767074/Debug.of.1st.message.v8.1901.-.Failing.txt)
[Debug of 1st message v8.40 - Working.txt](https://github.com/rsyslog/rsyslog/files/3767075/Debug.of.1st.message.v8.40.-.Working.txt)

**Comment by rgerhards** [comment]
This is due to the way plain text TCP syslog works. See https://rainer.gerhards.net/2008/04/on-unreliability-of-plain-tcp-syslog.html

Cure is to use RELP.

**Comment by slb985** [comment]
Hi Rainer

This configuration worked perfectly in version 8.40.0, its only an issue after an rsyslog upgrade to version 8-1901 onwards that I see the issue. In version 8.40 you see a 'CheckConnection detected broken connection - closing it' but in subsequent versions it does not detect the connection failure.

For info, I am using RELP across the estate but need to forward the logs to a remote desination that does not support RELP.

Regards

Dave

**Comment by slb985** [comment]
It seems to be the change to nsd_ptcp.c that was introuduced with this commit

https://github.com/rsyslog/rsyslog/commit/937dbcb8012e33d637952bac7c6051172e345928#diff-f2d38f68f7dcdff904107e0f91fbd866 

From:
`if(rc == 0) {`
To:
`if(rc == 0 && errno != EAGAIN) {`

**Comment by rgerhards** [comment]
> It seems to be the change to nsd_ptcp.c that was introuduced with this commit

That was a necessary change to fix something that didn't work **as specified**. We cannot undo this to make something work instead that is **not specified to work**. Sorry for that.
