### ISSUE TITLE
Not sending old logs if tampered with filenames

### ISSUE THREAD

**Issue by amisk** [rsyslog/rsyslog#3933]
Hi,

I don't have much rsyslog experience, so this might be something trivial.

I am sending log messages to another server. I have disk queuetype because I don't want to lose any messages in case the receiving server is down. To test what happens if the server is not reachable, I've shut it down. The logs are then kept, as files like fwd2.00000135. When I start the receiver again, all saved logs are sent and deleted locally.
Then I disabled it again, and renamed fwd2.00000135 to fwd2.00000139 to see what happens. After I retarted the rsyslog service, it started again at fwd2.00000001. If I start the receiver again, the old logs are no longer sent, even after a reboot.

Is there way to force rsyslog to send everything in the working directory when the service starts?

And a different questions: What happens if the counter reaches fwd2.99999999? Will it start at 1 again, or increase the number of digits?

Thx.

### Expected behavior
Don't actually know
### Actual behavior
Not sending old logs
### Steps to reproduce the behavior
have disk type for an action queue. Send logs to a server. Shutdown Server, so that the logs are not deleted.
Stop rsyslog service. Rename last file to a higher digit. Restart service.

### Environment
- rsyslog version: 8.19
- platform: Sparky, something new. Debian based.

**Comment by rgerhards** [comment]
is this really rsyslog 8.19 or 8.19xx? - if it is 8.19 it is veeeeery old.

**Comment by rgerhards** [comment]
oh.. in any case: do not mess up with the queue files. If you change their name and content, you'll break the system. This is actually the problem you face.

**Comment by amisk** [comment]
Sorry, 8.1901.0

**Comment by davidelang** [comment]
rsyslog keeps track of what files it has read and how far it's read through 
them, if you want to eliminate this knowledge, delete the stats file for that 
input.

It is specifically looking to not send files thare renamed (as that is a normal 
part of rolling log files)

David Lang

**Comment by amisk** [comment]
I see. Thanks.
Now it did not send 17 minutes of logs without tampering. Can I continue here or do you want me start a new issue?

**Comment by davidelang** [comment]
a new issue please
