### ISSUE TITLE
unable to configure tls1.2 using openssl 1.0.2t

### ISSUE THREAD

**Issue by tapakund** [rsyslog/rsyslog#3939]
### Expected behavior
I have building rsyslog version 8.1910.0 with the below configs:
```
./configure \
    --prefix=%{_prefix} \
    --enable-relp \
    --enable-gnutls\
    --enable-imfile \
    --enable-imjournal \
    --enable-impstats \
    --enable-imptcp \
    --enable-openssl
```
Below is the rsyslog config i am adding to disable TLS1 and TLS1.1.
```
module( load="imtcp"
        StreamDriver.Name="ossl"
        StreamDriver.Mode="1"
        StreamDriver.AuthMode="anon"
        gnutlsPriorityString="Protocol=ALL,-SSLv2,-TLSv1.0,-TLSv1.1
        MinProtocol=TLSv1.2"
       )
input(type="imtcp" port="1514")
```
So, i am getting error saying Openssl is to old for setting gnutlsPriorityString.

But as per this documentation: https://www.rsyslog.com/doc/v8-stable/configuration/modules/imtcp.html

It says:

gnutlsPriorityString
type	default	mandatory	obsolete legacy directive
string	none	no	none
New in version 8.29.0.

This strings setting is used to configure driver specific properties. Historically, the setting was only meant for gnutls driver. However with version v8.1905.0 and higher, the setting can also be used to set openssl configuration commands.

For GNUTls, the setting specifies the TLS session’s handshake algorithms and options. These strings are intended as a user-specified override of the library defaults. If this parameter is NULL, the default settings are used. More information about priority Strings here

For OpenSSL, the setting can be used to pass configuration commands to openssl libray. OpenSSL Version 1.0.2 or higher is required for this feature. A list of possible commands and their valid values can be found in the documentation:

I  am using Openssl 1.0.2t version.

root@tkundu-photon-1 [ /WS/photon-1.0/photon/stage/RPMS/x86_64 ]# openssl version
OpenSSL 1.0.2t-fips  10 Sep 2019
root@tkundu-photon-1 [ /WS/photon-1.0/photon/stage/RPMS/x86_64 ]#

So, i modified this line to make sure this code is executed with openssl 1.0.2t.
https://github.com/rsyslog/rsyslog/blob/1771f861203f67b57c340884c40c880714fc2786/runtime/nsd_ossl.c#L1795

### Actual behavior

After doing this change, no TLS version support i could see in the tcp port selected in imtcp.

### Environment
- rsyslog version: 
- platform: 
- for configuration questions/issues, include rsyslog.conf and included config files

Adding some logs:
```
root@tkundu-photon-1 [ /WS/photon-1.0/photon/stage/RPMS/x86_64 ]# rsyslogd -v
rsyslogd  8.1910.0 (aka 2019.10) compiled with:
	PLATFORM:				x86_64-unknown-linux-gnu
	PLATFORM (lsb_release -d):		
	FEATURE_REGEXP:				Yes
	GSSAPI Kerberos 5 support:		No
	FEATURE_DEBUG (debug build, slow code):	No
	32bit Atomic operations supported:	Yes
	64bit Atomic operations supported:	Yes
	memory allocator:			system default
	Runtime Instrumentation (slow code):	No
	uuid support:				Yes
	systemd support:			Yes
	Config file:				/etc/rsyslog.conf
	PID file:				/var/run/rsyslogd.pid
	Number of Bits in RainerScript integers: 64

See https://www.rsyslog.com for more information.
root@tkundu-photon-1 [ /WS/photon-1.0/photon/stage/RPMS/x86_64 ]# 
See http://www.rsyslog.com for more information.
root@tkundu-photon-1 [ /WS/photon-1.0/photon ]# 
```
```
rsyslog.conf file:

$IncludeConfig /etc/rsyslog.d/

#### MODULES ####

module(load="imuxsock")    # provides support for local system logging (e.g. via logger command)
module(load="imklog")      # provides kernel logging support (previously done by rklogd)
module(load="imjournal")   # provides access to the systemd journal
#module(load="immark")      # provides --MARK-- message capability

module( load="imtcp"
        StreamDriver.Name="ossl"
        StreamDriver.Mode="1"
        StreamDriver.AuthMode="anon"
        gnutlsPriorityString="Protocol=ALL,-SSLv2,-TLSv1.0,-TLSv1.1
        MinProtocol=TLSv1.2"
       )

# Provides UDP syslog reception
#module(load="imudp")
#input(type="imudp" port="514")

# Provides TCP syslog reception
input(type="imtcp" port="1514")

#### GLOBAL DIRECTIVES ####

$umask 0033


#### REMOTE RULES ####

#### LOCAL RULES ####

# Log all kernel messages to the console.
#kern.*                                                 /dev/console

# The authpriv file has restricted access.
authpriv.*                                              /var/log/messages

# Log all the mail messages in one place.
mail.*                                                  /var/log/maillog"
# Log cron stuff
cron.*                                                  /var/log/cron

# Everybody gets emergency messages
*.emerg                                                 :omusrmsg:*

# Save news errors of level crit and higher in a special file.
uucp,news.crit                                          /var/log/spooler

# Save boot messages also to boot.log
local7.*                                                /var/log/boot.log
~                                                                            
```
```
Below warnings i could see in journalctl logs as well:
 rsyslogd[5485]: OpenSSL Error Stack: error:140E0197:SSL routines:SSL_shutdown:shutdown while in init [v8.1910.0]
 rsyslogd[5485]: Failed to added Command: Protocol:'ALL,-SSLv2,-TLSv1.0,-TLSv1.1' in gnutlsPriorityString with error '0' [v8.1910.0 try https://www.rsysl
rsyslogd[5485]: SSL_ERROR_SSL in 'osslHandshakeCheck Server' [v8.1910.0]
 rsyslogd[5485]: OpenSSL Error Stack: error:140760FC:SSL routines:SSL23_GET_CLIENT_HELLO:unknown protocol [v8.1910.0]
rsyslogd[5485]: netstream session 0x7ffa44081480 from 10.173.23.77 will be closed due to error [v8.1910.0 try https://www.rsyslog.com/e/2089 ]
rsyslogd[5485]: SSL_ERROR_SSL in 'osslEndSess' [v8.1910.0]
rsyslogd[5485]: OpenSSL Error Stack: error:140E0197:SSL routines:SSL_shutdown:shutdown while in init [v8.1910.0]
rsyslogd[5485]: Failed to added Command: Protocol:'ALL,-SSLv2,-TLSv1.0,-TLSv1.1' in gnutlsPriorityString with error '0' [v8.1910.0 try https://www.rsysl
rsyslogd[5485]: SSL_ERROR_SSL in 'osslHandshakeCheck Server' [v8.1910.0]
rsyslogd[5485]: OpenSSL Error Stack: error:140760FC:SSL routines:SSL23_GET_CLIENT_HELLO:unknown protocol [v8.1910.0]
rsyslogd[5485]: netstream session 0x7ffa440814b0 from 10.173.23.77 will be closed due to error [v8.1910.0 try https://www.rsyslog.com/e/2089 ]
rsyslogd[5485]: SSL_ERROR_SSL in 'osslEndSess' [v8.1910.0]
rsyslogd[5485]: OpenSSL Error Stack: error:140E0197:SSL routines:SSL_shutdown:shutdown while in init [v8.1910.0]
 ```

Could you help to provide some pointers to move forward.

**Comment by rgerhards** [comment]
please use the current daily stable build - the fix you applied was not a real fix. Current master branch has the proper one.

**Comment by tapakund** [comment]
Thanks for replying.

I built the latest code in master branch and removed my fix.

I still see its complaining openssl is too old, so its not calling openssl API for setting gnutlsPriorityString. But I am have openssl 1.0.2t installed.

```
root@sc1-10-78-91-148 [ / ]# rsyslogd -v
rsyslogd  8.1911.0.master (aka 2019.11) compiled with:
	PLATFORM:				x86_64-unknown-linux-gnu
	PLATFORM (lsb_release -d):		
	FEATURE_REGEXP:				Yes
	GSSAPI Kerberos 5 support:		No
	FEATURE_DEBUG (debug build, slow code):	Yes
	32bit Atomic operations supported:	Yes
	64bit Atomic operations supported:	Yes
	memory allocator:			system default
	Runtime Instrumentation (slow code):	No
	uuid support:				Yes
	systemd support:			Yes
	Config file:				/etc/rsyslog.conf
	PID file:				/var/run/rsyslogd.pid
	Number of Bits in RainerScript integers: 64

See https://www.rsyslog.com for more information.
root@sc1-10-78-91-148 [ / ]# openssl version
OpenSSL 1.0.2t-fips  10 Sep 2019
root@sc1-10-78-91-148 [ / ]# 
```

Logs:
```
Nov 01 05:05:32 sc1-10-78-91-148 systemd[1]: Stopped System Logging Service.
Nov 01 05:05:32 sc1-10-78-91-148 systemd[1]: Starting System Logging Service...
Nov 01 05:05:32 sc1-10-78-91-148 rsyslogd[14367]: imuxsock: Acquired UNIX socket '/run/systemd/journal/syslog' (fd 3) from systemd.  [v8.1911.0.master]
Nov 01 05:05:32 sc1-10-78-91-148 rsyslogd[14367]: Warning: OpenSSL Version too old to set gnutlsPriorityString ('Protocol=ALL,-SSLv2,-TLSv1.0,-TLSv1.1')by SSL_CONF_cmd API. For more se
Nov 01 05:05:32 sc1-10-78-91-148 rsyslogd[14367]: Warning: OpenSSL Version too old to set gnutlsPriorityString ('Protocol=ALL,-SSLv2,-TLSv1.0,-TLSv1.1')by SSL_CONF_cmd API. For more se
Nov 01 05:05:32 sc1-10-78-91-148 rsyslogd[14367]: [origin software="rsyslogd" swVersion="8.1911.0.master" x-pid="14367" x-info="https://www.rsyslog.com"] start
Nov 01 05:05:32 sc1-10-78-91-148 systemd[1]: Started System Logging Service.
Nov 01 05:06:02 sc1-10-78-91-148 rsyslogd[14367]: SSL_ERROR_SSL in 'osslHandshakeCheck Server' [v8.1911.0.master]
Nov 01 05:06:02 sc1-10-78-91-148 rsyslogd[14367]: OpenSSL Error Stack: error:140760FC:SSL routines:SSL23_GET_CLIENT_HELLO:unknown protocol [v8.1911.0.master]
Nov 01 05:06:07 sc1-10-78-91-148 rsyslogd[14367]: Warning: OpenSSL Version too old to set gnutlsPriorityString ('Protocol=ALL,-SSLv2,-TLSv1.0,-TLSv1.1')by SSL_CONF_cmd API. For more se
Nov 01 05:06:07 sc1-10-78-91-148 rsyslogd[14367]: SSL_ERROR_SYSCALL in 'osslRecordRecv' [v8.1911.0.master]
Nov 01 05:06:07 sc1-10-78-91-148 rsyslogd[14367]: netstream session 0x7fe798028110 from 127.0.0.1 will be closed due to error [v8.1911.0.master]
Nov 01 05:06:07 sc1-10-78-91-148 rsyslogd[14367]: Warning: OpenSSL Version too old to set gnutlsPriorityString ('Protocol=ALL,-SSLv2,-TLSv1.0,-TLSv1.1')by SSL_CONF_cmd API. For more se
Nov 01 05:06:07 sc1-10-78-91-148 rsyslogd[14367]: SSL_ERROR_SYSCALL in 'osslRecordRecv' [v8.1911.0.master]
Nov 01 05:06:07 sc1-10-78-91-148 rsyslogd[14367]: netstream session 0x7fe798027a70 from 127.0.0.1 will be closed due to error [v8.1911.0.master]
Nov 01 05:06:07 sc1-10-78-91-148 rsyslogd[14367]: Warning: OpenSSL Version too old to set gnutlsPriorityString ('Protocol=ALL,-SSLv2,-TLSv1.0,-TLSv1.1')by SSL_CONF_cmd API. For more se
Nov 01 05:06:07 sc1-10-78-91-148 rsyslogd[14367]: SSL_ERROR_SYSCALL in 'osslRecordRecv' [v8.1911.0.master]
Nov 01 05:06:07 sc1-10-78-91-148 rsyslogd[14367]: netstream session 0x7fe7980148d0 from 127.0.0.1 will be closed due to error [v8.1911.0.master]
Nov 01 05:06:16 sc1-10-78-91-148 rsyslogd[14367]: Warning: OpenSSL Version too old to set gnutlsPriorityString ('Protocol=ALL,-SSLv2,-TLSv1.0,-TLSv1.1')by SSL_CONF_cmd API. For more se
Nov 01 05:06:16 sc1-10-78-91-148 rsyslogd[14367]: SSL_ERROR_SSL in 'osslHandshakeCheck Server' [v8.1911.0.master]
Nov 01 05:06:16 sc1-10-78-91-148 rsyslogd[14367]: OpenSSL Error Stack: error:140760FC:SSL routines:SSL23_GET_CLIENT_HELLO:unknown protocol [v8.1911.0.master]
Nov 01 05:06:16 sc1-10-78-91-148 rsyslogd[14367]: netstream session 0x7fe798015400 from 10.173.23.77 will be closed due to error [v8.1911.0.master try https://www.rsyslog.com/e/2089 ]
Nov 01 05:06:16 sc1-10-78-91-148 rsyslogd[14367]: SSL_ERROR_SSL in 'osslEndSess' [v8.1911.0.master]
```

**Comment by rgerhards** [comment]
@alorbach can you pls have a look

**Comment by tapakund** [comment]
As per rsyslog documentation, gnutlsPriorityString can be used to configure
right TLS as needed. But as per one commit: https://github.com/alorbach/rsyslog-1/commit/2f20fdd8c28b4a07364b164e17416bc2d10fe8c0

Looks like the openssl version number is not right, due to which even we have
openssl 1.0.2 it says openssl is too old.

As per this documentation: https://www.rsyslog.com/doc/v8-stable/configuration/modules/imtcp.html

It says This support is present in Openssl from 1.0.2 release onwards. 

So added this fix and it works fine.

--- a/runtime/nsd_ossl.c_org	2019-11-04 05:43:02.421331614 +0000
+++ b/runtime/nsd_ossl.c	2019-11-04 05:43:24.861332692 +0000
@@ -1790,7 +1790,7 @@ SetGnutlsPriorityString(__attribute__((u
 		RETiRet;
 	} else {
 		dbgprintf("gnutlsPriorityString: set to '%s'\n", gnutlsPriorityString);
-#if OPENSSL_VERSION_NUMBER >= 0x10020000L
+#if OPENSSL_VERSION_NUMBER >= 0x10002000L
 		char *pCurrentPos;
 		char *pNextPos;
 		char *pszCmd;

Request you to take a look and let us know if this is fine and i can raise a PR for this?

**Comment by alorbach** [comment]
Its a little configuration string fault: 

> module( load="imtcp"
>         StreamDriver.Name="ossl"
>         StreamDriver.Mode="1"
>         StreamDriver.AuthMode="anon"
>         gnutlsPriorityString="Protocol=ALL,-SSLv2,-TLSv1.0,-TLSv1.1
>         MinProtocol=TLSv1.2"
>        )

TLSv1.0 should be TLSv1, see "-min_protocol, -max_protocol" in: https://www.openssl.org/docs/man1.1.1/man3/SSL_CONF_cmd.html

This should work: 

> module( load="imtcp"
>         StreamDriver.Name="ossl"
>         StreamDriver.Mode="1"
>         StreamDriver.AuthMode="anon"
>         gnutlsPriorityString="Protocol=ALL,-SSLv2,-TLSv1,-TLSv1.1
>         MinProtocol=TLSv1.2"
>        )

**Comment by rgerhards** [comment]
@alorbach did you see https://github.com/rsyslog/rsyslog/issues/3939#issuecomment-549264904 ? this looks like a code issue to me, possibly in addition to the typo you mention.

**Comment by alorbach** [comment]
@rgerhards: I need to check this on a machine with OpenSSL 1.0.2, but it appears to be a good catch: 
The check actually is still wrong, it needs to be: 
0x100000200
(See https://www.openssl.org/docs/man1.1.0/man3/OPENSSL_VERSION_NUMBER.html).

I will create PR for this

**Comment by tapakund** [comment]
Thanks @alorbach for your comments. Today i corrected "TLSv1.0 to TLSv1" and with the patch mentioned in #3939 (comment)  it worked fine.

Will go through the man page you mentioned. 

I see in Openssl 1.0.2t:
# define OPENSSL_VERSION_NUMBER  0x1000214fL

**Comment by alorbach** [comment]
@tapakund interesting, the openssl doc page says little bit different format. I will look into this while fixing the version check issue.
