### ISSUE TITLE
 gnutls returned error on handshake: An unexpected TLS packet was received.

### ISSUE THREAD

**Issue by yueguifang** [rsyslog/rsyslog#3940]
rsyslogd: gnutls returned error on handshake: An unexpected TLS packet was received.  [v8.24.0-34.el7 try http://www.rsyslog.com/e/2083 ]

**Comment by yueguifang** [comment]
I am building a centralized log processing server. The client machine uses tls to forward logs to the log server. I have configured it according to the official documentation, as follows,

client:
#$DefaultNetstreamDriver gtls
#$DefaultNetstreamDriverCAFile /cert/myCA.pem
#$DefaultNetstreamDriverCertFile /cert/client.pem
#$DefaultNetStreamDriverKeyFIle /cert/key.pem

#$ActionSendStreamDriverMode 1 # require TLS for the connection
#$ActionSendStreamDriverAuthMode x509/name
#$ActionSendStreamDriverPermittedPeer *

server:
$DefaultNetstreamDriver gtls
# certificate files
$DefaultNetstreamDriverCAFile /cert/myCA.pem
$DefaultNetstreamDriverCertFile /cert/server.pem
$DefaultNetstreamDriverKeyFile /cert/serverkey.pem
$InputTCPServerStreamDriverAuthMode x509/name # client is NOT authenticated
$InputTCPServerStreamDriverPermittedPeer *
$InputTCPServerStreamDriverMode 1 # run driver in TLS-only mode
$InputTCPServerRun 10514 # start up listener at port 10514

 but it log a error message in server log file  when forwarding:
error message is :

Oct 31 06:09:51 localhost rsyslogd: gnutls returned error on handshake: An unexpected TLS packet was received.  [v8.24.0-34.el7 try http://www.rsyslog.com/e/2083 ]

**Comment by rgerhards** [comment]
> client:
> #$DefaultNetstreamDriver gtls
> #$DefaultNetstreamDriverCAFile /cert/myCA.pem
> #$DefaultNetstreamDriverCertFile /cert/client.pem
> #$DefaultNetStreamDriverKeyFIle /cert/key.pem
> 
> #$ActionSendStreamDriverMode 1 # require TLS for the connection
> #$ActionSendStreamDriverAuthMode x509/name
> #$ActionSendStreamDriverPermittedPeer *

This is commented out, so the client is not configured to use TLS.

**Comment by yueguifang** [comment]
hi&nbsp;
Sorry , my question is why handshake failed,is my cofiguration is error&nbsp;
Thanks very much for your attention.



发自我的iPhone


------------------ Original ------------------

**Comment by rgerhards** [comment]
Both client and server must be configured to use TLS. Your client is not. This is the problem.

**Comment by yueguifang** [comment]
I checked my config files ,and update it as below. After I restart rsyslog service, client and server service both recieve the errors 
client error message is :
rsyslogd: error: peer name not authorized -  not permitted to talk to it. Names: CN: GE;  [v8.24.0-34.el7 try http://www.rsyslog.com/e/2088 ]
server error message is :
unexpected GnuTLS error -110 in nsd_gtls.c:536: The TLS connection was non-properly terminated.  [v8.24.0-34.el7 try http://www.rsyslog.com/e/2078 ]

server config :
# make gtls driver the default
$DefaultNetstreamDriver gtls

# certificate files
$DefaultNetstreamDriverCAFile /cert/last/myCA.pem
$DefaultNetstreamDriverCertFile /cert/last/servercert.pem
$DefaultNetstreamDriverKeyFile /cert/last/serverkey.pem

$ModLoad imtcp # TCP listener
$InputTCPServerStreamDriverAuthMode anon #x509/name # client is NOT authenticated
#$InputTCPServerStreamDriverPermittedPeer *GE
$InputTCPServerStreamDriverMode 1 # run driver in TLS-only mode
$InputTCPServerRun 10514 # start up listener at port 10514

clieng config:$DefaultNetstreamDriver gtls

# certificate files
$DefaultNetstreamDriverCAFile /cert/last/myCA.pem

$DefaultNetstreamDriverCertFile /cert/last/clientcert.pem
$DefaultNetstreamDriverKeyFile /cert/last/clientkey.pem
$ActionSendStreamDriverMode 1 # run driver in TLS-only mode
$ActionSendStreamDriverAuthMode anon #x509/name # client is NOT authenticated
#$ActionSendStreamDriverPermittedPeer *GE

**Comment by rgerhards** [comment]
the error message does not match the config. Please provide debug logs of both client and server.

**Comment by sandeshChandra** [comment]
I also got the same error after configuring client and server conf files.
 
 Aug 18 07:32:54 SC-1 rsyslogd[22131]: error: peer name not authorized -  not permitted to talk to it. Names: CN: SC-1;  [v8.2106.0 try https://www.rsyslog.com/e/2088 ]
Aug 18 07:32:54 SC-1 rsyslogd[22131]: netstream session 0x7f3d74008280 from 214.2.62.29 will be closed due to error [v8.2106.0 try https://www.rsyslog.com/e/2089 ]

**Comment by yueguifang** [comment]
您的邮件我已收到

**Comment by davidelang** [comment]
The most commone cause of this error is that the sender is not doing a TLS 
connection (a vulnerability scanner or similar), check that the source really is 
doing what it is supposed to

also, post the full config. From the error message, you may have it configured 
to restrict who can talk to you, we need to see that.

David Lang

**Comment by sandeshChandra** [comment]
Hi David,

Thanks for the quick response I am thank full that you are looking into this.
Here are the configurations for both client and server side.

Server 
# load module for imtcp
module(load="imtcp"
       StreamDriver.Name="gtls"
       StreamDriver.Mode="1"
       StreamDriver.AuthMode="x509/name")
       
# make gtls driver the default

# certificate files
global(
DefaultNetstreamDriver = "gtls"
DefaultNetstreamDriverCAFile = "/etc/rsyslog.d/ca.crt"
DefaultNetstreamDriverCertFile = "/etc/rsyslog.d/server.crt"
DefaultNetstreamDriverKeyFile = "/etc/rsyslog.d/server.key"
)

# Listen for logs over TCP with mTLS
input(type="imtcp" port="514")


Client
global(
DefaultNetstreamDriver = "gtls"
DefaultNetstreamDriverCAFile = "/etc/rsyslog.d/ca.crt"
DefaultNetstreamDriverCertFile = "/etc/rsyslog.d/client.crt"
DefaultNetstreamDriverKeyFile = "/etc/rsyslog.d/client.key"
)
# Forward all logs to remote server
*.* action(
    type="omfwd"
    target="214.2.36.4"
    port="514"
    protocol="tcp"
    template="RSYSLOG_ForwardFormat"
    streamDriver="gtls"
    streamDriverMode="1"
    streamDriverAuthMode="x509/name"
)


command used at server side to check handshake is:

openssl s_client -connect 214.2.36.4:514 -CAfile /etc/rsyslog.d/ca.crt -cert /etc/rsyslog.d/client.crt -key /etc/rsyslog.d/client.key


Thanks.

**Comment by davidelang** [comment]
you are setting the authmode to x509/name, so, the cert is not getting validated 
correctly.

try changing it to x509/certvalid to see if the problem is the cert being 
invalid or the cert name not matching. If it's the cert not being valid, it's 
your CA or how the cert is generated. If it's the name, check DNS and see how 
the IP is getting resolved.

David Lang

**Comment by sandeshChandra** [comment]
It works, Changing "x509/name" to "x509/certvalid" the Handshake is successful. 

But I think "x509/certvalid" this can be used for test environment, But in production environment we need to configure with  "x509/name" for more robust security.

Am I right?

**Comment by rgerhards** [comment]
> But I think "x509/certvalid" this can be used for test environment,

Not really, it depends on your requirement (if you do not want/need to authenticate thousends of clients and deploy your cert securely, this is a fairly secure mode).

On your root problem: I've checked that last config you posted. There, the name given in the error message is actually not permitted to talk to the server (directive commented out), and so the error was absolutely correct.

**Comment by sandeshChandra** [comment]
Yea the configuration works. Thanks for guiding.

Here I have an another question. In the same configuration file on client side I have added Queuing as below. 

$WorkDirectory /var/spool/rsyslog
$ActionQueueFileName uniqName
$ActionQueueMaxDiskSpace 1g
$ActionQueueSaveOnShutdown on
$ActionQueueType LinkedList
$ActionResumeRetryCount -1



So the question here is even after closing the connection with remote server the logs are been not captured in the mentioned que directory, in fact the file is not seen under the directory. What can be the possible reason? 

I have checked the permission which is "root".

**Comment by yueguifang** [comment]
您的邮件我已收到

**Comment by davidelang** [comment]
a couple things, creating queues that way works, but not allways as expected, 
that makes a queue for the next action listed (which you don't show here). This 
is one of the big reasons to switch to the new action() syntax, you don't get 
unexpected side effects (or lack of them) from the old approach.

please create a unified config and post that using rsyslogd -N1 -o /path/to/file

David Lang

**Comment by sandeshChandra** [comment]
Hello, 
I am now testing the configuration with external server to check if everything is working fine as inteneded. But I am now facing 
this error at external remote server 
"Oct 06 06:30:35 seliius06114 rsyslogd[2080666]: can not read file '/etc/rsyslog.d/extServer.pem': Permission denied [v8.2001.0 try https://www.rsyslog.co>
Oct 06 06:30:35 seliius06114 rsyslogd[2080666]: gtlsInitSession failed to INIT Session 0 [v8.2001.0 try https://www.rsyslog.com/e/2040 ]" 

Even after giving read permission "chmod 644 /etc/rsyslog.d/extServer.pem"
and " chown syslog:syslog /etc/rsyslog.d/server.key"  the error still remains. 

Kindly, need quick support.

**Comment by davidelang** [comment]
in the latest full config you posted, there wasn't a reference to 
/etc/rsyslog.d/extServer.pem please post your updated config file

what distro are you using? it's possible the SELinux or AppArmor is blocking 
your access to those files even if the simple unix permissions say you should 
have access.

David Lang

**Comment by sandeshChandra** [comment]
Yes this is configured correctly. I can change it to /etc/rsyslog.d/extServer.crt not an issue. 

"it's possible the SELinux or AppArmor is blocking
your access to those files even if the simple unix permissions say you should
have access." 

Any particular way to get rid of this issue. I have tried  changing the permission but not working. I am using ubuntu dabian.

**Comment by yueguifang** [comment]
您的邮件我已收到

**Comment by rgerhards** [comment]
The usual suspicion is that the client does not have tls enabled. In any case, it is a very good idea to switch to the openssl driver ("ossl"), as open ssl provides much better error messages in general.

I will also close that 5 year old thread now as it probably contains a lot of outdated information. If you still have issues, please open a new issue.
