### ISSUE TITLE
Centos 7 restart rsyslog show "imfile: on startup file '/root/test_one.log' does not exist", actually it existed before restart

### ISSUE THREAD

**Issue by mitolH** [rsyslog/rsyslog#3942]
### Expected behavior
Restart normally

### Actual behavior
```
Nov 03 06:17:34 192-168-123-218 rsyslogd[104982]: imfile: on startup file '/root/test_one.log' does not exist but is configured in static file monitor - this may indicate a misconfiguration. If the file appears at a later time, it will automatically be processed. Reason: Permission denied [v8.24.0-34.el7]
```

### Steps to reproduce the behavior
- add file `/etc/rsyslog.d/test_one.conf`:
```
# Config for file input test
$ModLoad imfile

$InputFileName /root/test_one.log
$InputFileTag  test_one:
$InputFileSeverity notice
$InputFileStateFile  state_test_one
$InputFilePersistStateInterval  25000
$InputFileFacility local0
$InputRunFileMonitor

local0.* /var/log/test_one.log
&~
```

- create a crontab `*/1 * * * * /bin/date >> /root/test_one.log`
- systemctl restart systemd-journald.socket
- systemctl restart rsyslog
- then `systemctl status rsyslog -l` show the message

By the way, also I had tried to stop service use `systemctl stop rsyslog`, just use simple command as folllow `/usr/sbin/rsyslogd -n -f /etc/rsyslog.conf` the log was ran will. So I can't sure is this a issuse for centos or rsyslog.

### Environment
- rsyslog version: v8.24.0-34.el7
- platform: CentOS Linux release 7.6.1810 (Core), kernel 3.10.0-957.10.1.el7.x86_64

**Comment by rgerhards** [comment]
Have a look at the error message: **Reason: Permission denied ** ;-)

**Comment by mitolH** [comment]
Thanks for your reply. @rgerhards 

Also I had tried to change the file mod like this `chmod 777 /root/test_one.log` and `chmod 777 /var/log/test_one .log`, the same message still shown.

**Comment by rgerhards** [comment]
I guess the problem then is within SELinux. In any case, the permission error message comes directly from the OS - so it is all rsyslog knows about what is wrong.

**Comment by mitolH** [comment]
I got it, TKS your suggestion.  Command `chcon -t var_log_t /root/test_one.log` solved my problem.

The SELinux type of `var_log_t` is from `ls -Z /var/log/test_one .log` shown, but can't set `syslogd_t` the same with `rsyslog` process.
