### ISSUE TITLE
rsyslog1908+tls/ossl   rsyslogd: gnutls returned error on handshake: A TLS packet with unexpected length was received.  [v8.1908.0 try https://www.rsyslog.com/e/2083 ] + https://kc.mcafee.com/corporate/index?page=content&id=KB91194 sending to rsyslog getting rsyslog server errors

### ISSUE THREAD

**Issue by mike1li** [rsyslog/rsyslog#3946]
### Expected behavior
Error free but experiencing following:
rsyslog1908+tls/ossl   rsyslogd: gnutls returned error on handshake: A TLS packet with unexpected length was received.  [v8.1908.0 try https://www.rsyslog.com/e/2083 ] + https://kc.mcafee.com/corporate/index?page=content&id=KB91194 sending to rsyslog getting rsyslog server errors
I've been asked to use ossl, but McAfee EPO syslog only sends to tls
so StreamDriver.Name="gtls"
[rsyslogdebug-114-gtls.log](https://github.com/rsyslog/rsyslog/files/3804516/rsyslogdebug-114-gtls.log)

### Actual behavior
rsyslog1908+tls/ossl   rsyslogd: gnutls returned error on handshake: A TLS packet with unexpected length was received.  [v8.1908.0 try https://www.rsyslog.com/e/2083 ] + https://kc.mcafee.com/corporate/index?page=content&id=KB91194 sending to rsyslog getting rsyslog server errors. Rsyslog1908+tls is behind pass through AWS NLB on tcp10514
### Steps to reproduce the behavior
Used steps in https://www.rsyslog.com/how-to-use-debug-on-demand/
### Environment
- rsyslog version: 
rsyslog-8.1908.0-2.el6.x86_64
rsyslog-gnutls-8.1908.0-2.el6.x86_64
rsyslog-openssl-8.1908.0-2.el6.x86_64

- platform: 
cat /etc/os-release
NAME="Amazon Linux AMI"
VERSION="2018.03"
ID="amzn"
ID_LIKE="rhel fedora"
VERSION_ID="2018.03"
PRETTY_NAME="Amazon Linux AMI 2018.03"
ANSI_COLOR="0;33"
CPE_NAME="cpe:/o:amazon:linux:2018.03:ga"
HOME_URL="http://aws.amazon.com/amazon-linux-ami/"

- for configuration questions/issues, include rsyslog.conf and included config files

module(load="imuxsock") # provides support for local system logging (e.g. via logger command)
module(load="imklog")   # provides kernel logging support (previously done by rklogd)

module(load="imudp" SchedulingPolicy="fifo" SchedulingPriority="5" threads="2" timeRequery="8" batchSize="128")
input(type="imudp" port="514")

module(load="imptcp") # needs to be done just once
input(type="imptcp" port="514")

$MaxOpenFiles 102400

$ActionFileDefaultTemplate RSYSLOG_TraditionalFileFormat

$template snippedFileFormat, "%$year% %timegenerated% %HOSTNAME% %msg%\n"
$template snippedXDPFileFormat, "%msg%\n"
$template PanFileFormat, "%HOSTNAME%\,%msg%\r\n"
$template VormetricFF, "%$year% %timegenerated% %HOSTNAME% %syslogtag% %structured-data%\n"

$IncludeConfig /etc/rsyslog.d/*.conf
$IncludeConfig /etc/rsyslog.d/snipped/*.conf

global(
defaultNetstreamDriverCAFile="/opt/snipped/etc/apps/proofpoint/certs/cis-eng-ca.pem"
defaultNetstreamDriverCertFile="/opt/snipped/etc/apps/proofpoint/certs/logforwarder.snipped.pem"
defaultNetstreamDriverKeyFile="/opt/snipped/etc/apps/proofpoint/certs/logforwarder.snipped.pem"
)
module(
load="imtcp"
#3944 StreamDriver.Name="ossl"
StreamDriver.Name="gtls"
StreamDriver.mode="1"
StreamDriver.AuthMode="anon"
)
input(type="imtcp" port="10514")

if $programname == 'puppet-agent' then                   -/var/log/all/puppet
if $programname == 'puppet-master' then                  -/var/log/all/puppet
if $programname == 'puppet-user' then                    -/var/log/all/puppet

*.info;mail.none;authpriv.none;cron.none                /var/log/messages

authpriv.*                                              /var/log/secure

mail.*                                                  /var/log/maillog

cron.*                                                  /var/log/cron

*.emerg                                                 :omusrmsg:*
uucp,news.crit                                          /var/log/spooler
local7.*                                                /var/log/boot.log

auth.debug      -/var/log/all/auth.log
authpriv.debug  -/var/log/all/authpriv.log
cron.debug      -/var/log/all/cron.log
daemon.debug    -/var/log/all/daemon.log
ftp.debug       -/var/log/all/ftp.log
kern.debug      -/var/log/all/kern.log
lpr.debug       -/var/log/all/lpr.log
mail.debug      -/var/log/all/mail.log
news.debug      -/var/log/all/news.log
syslog.debug    -/var/log/all/syslog.log
user.debug      -/var/log/all/user.log
uucp.debug      -/var/log/all/uucp.log
local0.debug    -/var/log/all/local0.log
local1.debug    -/var/log/all/local1.log
local2.debug    -/var/log/all/local2.log
local3.debug    -/var/log/all/local3.log
local4.debug    -/var/log/all/local4.log
local5.debug    -/var/log/all/local5.log
local6.debug    -/var/log/all/local6.log
local7.debug    -/var/log/all/local7.log

if $programname == 'snipped-drupal' then /var/log/drupal/drupal.log

template (name="Trend" type="string" string="/var/log/trend/trend_ds.log")
if ( $source == 'localhost' or $fromhost-ip == '127.0.0.1' ) and $syslogfacility-text == 'local5' then
{
action(type="omfile" dynaFile="Trend" template="RSYSLOG_TraditionalFileFormat")
stop
}

**Comment by mike1li** [comment]
when McAfeeEPO sending syslog also seeing: rsyslogd: unexpected GnuTLS error -9 in nsdsel_gtls.c:178: A TLS packet with unexpected length was received.  [v8.1908.0 try https://www.rsyslog.com/e/2078 ]

**Comment by rgerhards** [comment]
This looks like the remote peer did not respond properly. Check it's configuration.

**Comment by mike1li** [comment]
Rainer, please advise what should be proper response from the remote peer, McAfee EFO syslog service? It will be useful to send to McAfee EFO syslog developers who are recommending syslog-ng compatible TLS receiver. Thanks.

**Comment by mike1li** [comment]
I read the following from McAfee https://kc.mcafee.com/corporate/index?page=content&id=KB87927 : OpenSSL: Required to generate a certificate because ePO only supports encrypted connections to communicate with the syslog server: Specifically the ePO syslog integration is only supported for TCP with TLS receivers following RFC 5424 and RFC 5425 (known as syslog-ng)

**Comment by rgerhards** [comment]
> RFC 5424 and RFC 5425 (known as syslog-ng)

actually, McAfee is incorrect. RFC 5424 and 5425 have nothing to do with syslog-ng, and they are probably the only ones that "know" it under that name ;-)

rsyslog support both RFCs since the very beginning, actually before the beginning. When I wrote RFC 5424, we used rsyslog as test implementation.

**Comment by mike1li** [comment]
@rgerhards thanks.
