### ISSUE TITLE
rsyslog keeps writing to old log files after logrotate

### ISSUE THREAD

**Issue by UnPure** [rsyslog/rsyslog#3952]
### Expected behavior
Write to new files after logrotate

### Actual behavior
Writes to *.log.1 instead of *.log

### Steps to reproduce the behavior
Happens at every logrotate for me with default configs on Debian 10.1

### Environment
- rsyslog version: 8.1901.0
- platform: Debian 10.1 x64

If you need any other informations/files/logs, let me know

**Comment by davidelang** [comment]
what is your logrotate config? it's probably not sending a HUP to rsyslog when 
it's rotating the files

David Lang

**Comment by UnPure** [comment]
I'm using the default configs from Debian 10.1 fro logrotate and rsyslog. No changes to the main or any of the .d configs

`
# see "man logrotate" for details
# rotate log files weekly
weekly

# keep 4 weeks worth of backlogs
rotate 4

# create new (empty) log files after rotating old ones
create

# use date as a suffix of the rotated file
#dateext

# uncomment this if you want your log files compressed
#compress

# packages drop log rotation information into this directory
include /etc/logrotate.d

# system-specific logs may be also be configured here.
`

**Comment by davidelang** [comment]
ok, but I don't have a default debian 10.1 config to look at. there is nothing 
in what you posted here that would rotate log files, it's probably in one of the 
files under /etc/logrotate.d

somewhere in the config it gives a list of files to be rotated, and can include 
things to do after the files are moved. With rsyslog, this should include 
sending a HUP to rsyslogd. my guess is that it isn't doing this.

sometime in the last year or so, there was a push to have rsyslog no longer 
write a pid file, I don't remember if it was debian pushing this or not, and if 
it was, they had some other way of identifying the process to send the HUP to 
(probably through systemd, but I don't remember the details)

but if we can see the config, we can tell what's wrong with it.

David Lang

**Comment by UnPure** [comment]
You probably didnt see it because you replied through email but shortly after creating my last comment I edited it and added a second config which looks like it has what you are talking about. In case you cant open the issue and look at my edited comment, here the important parts:

/etc/logrotate.d/rsyslog includes:
`/usr/lib/rsyslog/rsyslog-rotate`

That file pretty much just has 2 commands which when entered by hand produce an error:

```
# systemctl kill -s HUP rsyslog.service
# invoke-rc.d rsyslog rotate
[FAIL] Closing open files: rsyslogd failed!
```

**Comment by davidelang** [comment]
someone is being too clever for their own good. I'm pretty sure this config is 
not something rsyslog provides, but something that Debin is providing.

try doing

killall -HUP rsyslogd

or
pkill -HUP rsyslogd

David Lang

**Comment by UnPure** [comment]
You mean replace `systemctl kill -s HUP rsyslog.service` in `/usr/lib/rsyslog/rsyslog-rotate` with one of them? And do I replace the whole line or just the kill with killall/pkill? 

/usr/lib/rsyslog/rsyslog-rotate:
```
#!/bin/sh

if [ -d /run/systemd/system ]; then
    systemctl kill -s HUP rsyslog.service
else
    invoke-rc.d rsyslog rotate > /dev/null
fi
```

**Comment by davidelang** [comment]
I would replace the call to rsyslog-rotate in the logrotate script with one of 
them

and as always, check that I didn't make a supid typo when I typed the e-mail, 
make sure the command works (and if you aren't familiar with the command, check 
the man page so you know what it's doing, blindly running commands as root from 
some random person on the Internet is bad for your system's health)

David Lang

**Comment by UnPure** [comment]
I changed all lines in /etc/logrotate.d/rsyslog to `killall -HUP rsyslogd` and after forcing a logrotate it seems like everything is working. I'm currently waiting for the next daily rotate to see if everything is working there. I'll edit later and give feedback.
