### ISSUE TITLE
omczmq fails to build with -Werror=implicit-function-declaration

### ISSUE THREAD

**Issue by Whissi** [rsyslog/rsyslog#3957]
```
omczmq.c: In function ‘outputCZMQ’:
omczmq.c:260:10: error: implicit declaration of function ‘zframe_set_group’; did you mean ‘zframe_set_more’? [-Werror=implicit-function-declaration]
  260 |     rc = zframe_set_group(frame, topic);
      |          ^~~~~~~~~~~~~~~~
      |          zframe_set_more
omczmq.c:260:10: warning: nested extern declaration of ‘zframe_set_group’ [-Wnested-externs]
cc1: some warnings being treated as errors
```

Tested with rsyslog-8.1910.0 and current git master.

**Comment by rgerhards** [comment]
This sounds like some czmq header is not properly present? @brianknox can you help?

**Comment by Whissi** [comment]
Found the problem. zframe_set_group [was added in czmq-4](https://github.com/zeromq/czmq/commit/09bb24771bf2acc0a59016003e833f599ed5effe) but [rsyslog only checks for czmq-3](https://github.com/rsyslog/rsyslog/blob/v8.2004.0/configure.ac#L2226). So we need to bump this requirement.
