### ISSUE TITLE
Incomplete folder name when using template 

### ISSUE THREAD

**Issue by uday3110** [rsyslog/rsyslog#3958]
I am using rsyslog 8.16.0

```
root@xxxx-rsyslog-server01-prod:~# rsyslogd -v
rsyslogd 8.16.0, compiled with:
	PLATFORM:				x86_64-pc-linux-gnu
```

I have the following config for template
```$template ODC-DYNAFILE,"/logs/odc/%hostname%/%app-name%.log-%$YEAR%-%$MONTH%-%$DAY%"

### FILTER(S) ###
if $syslogfacility-text == 'local2' and $syslogseverity-text == 'info' then {
  action(type="omfile" template="MESSAGE" dynaFile="ODC-DYNAFILE" DirCreateMode="0755")
  stop
}
```

However i get a lot of garbage folders like below

![image](https://user-images.githubusercontent.com/3020683/68633612-5debb780-04a7-11ea-8f8e-d960af7f35b7.png)

the client is sending traffic to rsyslog over tcp 514. Since TCP is reliable why does this happen? I just can't figure this out.

**Comment by davidelang** [comment]
The usual cause is that the message is too long and do the maxmessagelength 
parameter is kicking in and splitting the message at that lenth. Parsing the 
'new' message is resulting in garbage like this.

David Lang

**Comment by rgerhards** [comment]
yeah, current versions drop the oversize part (configurable), so this will not happen with them. 8.16 is quite a couple of years old.
