### ISSUE TITLE
relp: add support for setting TLS custom parameters

### ISSUE THREAD

**Issue by alorbach** [rsyslog/rsyslog#3959]
Add support for set SSL_CONF_cmd properties using: 
- relpCltSetTlsConfigCmd
- relpSrvSetTlsConfigCmd

see also #3959

**Comment by rgerhards** [comment]
@alorbach isn't there an active PR for this?

**Comment by alorbach** [comment]
Yes it this one: 
https://github.com/rsyslog/rsyslog/pull/3962
