### ISSUE TITLE
Imfile rename to hash-style state file limited

### ISSUE THREAD

**Issue by jvymazal** [rsyslog/rsyslog#3960]
### Expected behavior
When monitored file exceeds the hash-style state file limit, old (inode-only) state file is removed

### Actual behavior
When monitored file exceeds the hash-style state file limit (currently 512B) old inode-style state file is left and can later cause log loss if the same inode is reused for another monitored file. State file renaming (so the old one is not present) only happens when file grows over hash threshold with rsyslog **not** running , which is in reality very rare condition combination.

### Steps to reproduce the behavior
Configure file monitor
Input test data (less than 512B)
Restart rsyslog
Input more data
Now there are two state files for one file

### Environment
- rsyslog version: 8.1910.0 
- platform:Fedora 
- for configuration questions/issues, include rsyslog.conf and included config files

**Comment by jvymazal** [comment]
The renaming code was added in #2953

**Comment by jvymazal** [comment]
@rgerhards I believe that the original intent was the rename state file also when running, and probably most clean way is to separate the renaming code so it can be used in more places, do you agree?

As for timing, provided I would mange put this into PR today, would this go into 8.1911 or the next one?

Thanks

**Comment by rgerhards** [comment]
quick reply: 8.1911 is closed - it's in package build and final QA already.

**Comment by jvymazal** [comment]
ok, will still try to spin up that PR once I get a while for it

**Comment by rgerhards** [comment]
@jvymazal 

> I believe that the original intent was the rename state file also when running, and probably most clean way is to separate the renaming code so it can be used in more places, do you agree?

something is indeed fishy here. Have a look at this test (and a similarly-named):

https://github.com/rsyslog/rsyslog/blob/master/tests/imfile-statefile-no-file_id.sh

Comments indicate it intends to check state file rename and removal, but code is not in place for it...

**Comment by jvymazal** [comment]
well the code is in place, however it is only run upon rsyslog startup (file opening) which is also exactly what the test does. But when the actual reaching of `FILE_ID_SIZE`  happens when rsyslog is running then no renaming happens which is not covered by the test

**Comment by jvymazal** [comment]
I have been looking on the code some more and perhaps only moving the renaming code (along with inode state file check) inside the `persistStrmState()` function would be enough to do it in all cases we need without any code duplication or crating new functions.

**Comment by rgerhards** [comment]
> I have been looking on the code some more and perhaps only moving the renaming code (along with inode state file check) inside the `persistStrmState()` function would be enough to do it in all cases we need without any code duplication or crating new functions.

@jvymazal I haven't reviewed the code in question yet, but this sounds pretty much like a solution.

**Comment by rgerhards** [comment]
releated/dup (?): #3646

**Comment by jvymazal** [comment]
yes, both look like duplicates

**Comment by sopos** [comment]
I think that generally if a new state file is created any old state file related to that specific inode should be removed as we are sure it is out of date at than point. This should happen not only for growed file but also for shrinked file.
