### ISSUE TITLE
forwarding when suspended not working

### ISSUE THREAD

**Issue by amisk** [rsyslog/rsyslog#3961]
### Expected behavior
Sending messages to backup server in case primary is gone
### Actual behavior
Not sending to backup server
### Environment
- rsyslog version: 8.1901.0
- platform: lates debian

Hi,

I tried a configuration to send messages to a second server in case the first fails.
this is this conf:

```
if ($syslogfacility-text=="local4") then {action(type="omrelp"
					target="10.0.2.15"
					port="514"
					queue.type="LinkedList"
					queue.filename="fwd-relp1"
)

					action(type="omrelp"
					target="10.0.2.9"
					port="514"
					queue.type="LinkedList"
					queue.filename="fwd-relp2"
					action.execOnlyWhenPreviousIsSuspended="on"
)
}

```

It does not forward the messages to the second server when I disconnect the first. If I remove the execonly ... part, it happily sends it to both servers. If I disconnect the first, and do a service rsyslog status, it does tell me that the action has been suspended. To my understanding of this parameter, in that case it should be activated.

**Comment by davidelang** [comment]
Working as designed (although I agree it surprises many people)

When you have a queue on one action and follow it with 
execOnlyWhenPreviousIsSuspended, the 'action' that it is looking at is putting 
the message into the queue of the first action, not delivery of the message. 
When there is a queue, you introduce an async action and cannot know when/if the 
message is finally delivered

the normal answer to this is to create a ruleset, but the queue on the ruleset, 
and have your two actions inside the ruleset, then in your if statement, call 
the ruleset

David Lang

**Comment by amisk** [comment]
Ok, I will try it, thanks.

But, this is given as an example in the documentation.
https://www.rsyslog.com/doc/master/tutorials/failover_syslog_server.html
Did that change at one point?

**Comment by rgerhards** [comment]
> edit: Never mind, the example has no queue at all :)

I'll see that I mention this explicitly inside the doc. Thx for the hint.

**Comment by rgerhards** [comment]
@amisk I have now updated the doc. There is a preview available for the next couple of hours at http://ubuntu16.rsyslog.com/doc/doc-2019-11-13-12-18-32-df755d0/tutorials/failover_syslog_server.html It will also migrate to doc master branch later today on the rsyslog site. Any further suggestions are welcome.

**Comment by amisk** [comment]
You misspelled prerequisit on the second line.

**Comment by rgerhards** [comment]
@amisk thx!
