### ISSUE TITLE
imjournal: why is the delay 10s on error retry？

### ISSUE THREAD

**Issue by wsp1991** [rsyslog/rsyslog#3969]
### Steps to reproduce the behavior
in imjournal.c
```
static void
tryRecover(void) {
        LogMsg(0, RS_RET_OK, LOG_INFO, "imjournal: trying to recover from unexpected "
                "journal error");
        STATSCOUNTER_INC(statsCounter.ctrRecoveryAttempts, statsCounter.mutCtrRecoveryAttempts);
        closeJournal();
        srSleep(10, 0); // do not hammer machine with too-frequent retries
        openJournal();
}
```
here, srSleep(10, 0);Why is the delay 10 s？Can it be shortened or removed？
if produce log fastly and journald buffer set small, delay 10s, Logs will be lost.
### Environment
- rsyslog version: 
- platform: 
- for configuration questions/issues, include rsyslog.conf and included config files

**Comment by rgerhards** [comment]
good question - it somehow looks like 10s was not the real intent...
