### ISSUE TITLE
Cannot Set IP Address for IMRELP

### ISSUE THREAD

**Issue by kaizen1** [rsyslog/rsyslog#3992]
The parser throws an error because address field is unknown.
 parameter 'address' not known 

NOTE: imtcp allows us to input an IP address. Many people do not want to listen on 0.0.0.0 to minimize attack surface. Please enable IP address input. Thanks.

input(type="imrelp" port="10555" address="10.128.0.29" maxDataSize="5k")

**Comment by rgerhards** [comment]
I checked the code, and this capability is present. I guess you version is simply too old. Current is 8.1911.0.

**Comment by kaizen1** [comment]
rsyslog-relp package version is 8.32.0-1ubuntu4 
Is this too old for IP support?

**Comment by rgerhards** [comment]
> Is this too old for IP address input support?

yup, just checked: it came in August 2018 with 8.37. I notice doc does not have this info, so will fix doc :-)

**Comment by kaizen1** [comment]
OK. Thanks. Wow. Google is using some old stuff in their Ubuntu images :)

**Comment by davidelang** [comment]
8.32 only two years old (Jan 2018), it's better than RedHat (using 8.24 which is 
3 years old) ;-p

David Lang

**Comment by kaizen1** [comment]
Incredible....how they charge $ for support is beyond me. There's a sucker born every day :))
