### ISSUE TITLE
fix testbench openssl issues on debian10

### ISSUE THREAD

**Issue by alorbach** [rsyslog/rsyslog#4003]
See build log: 
https://build.rsyslog.com/#/builders/212/builds/3/steps/4/logs/test-suite_log

**Comment by alorbach** [comment]
Could not reproduce the probkem with docker image: 
rsyslog/rsyslog_dev_base_debian:10

**Comment by rgerhards** [comment]
This did not reoccur. Thus closing, at least for now.
