### ISSUE TITLE
Option to disable(SSLv3) for POODLE at 5.10.1

### ISSUE THREAD

**Issue by mdborhanuddin** [rsyslog/rsyslog#401]
Hi,

I'm using rsyslog-module-gtls-5.10.1 and rsyslog-5.10.1
with 
$DefaultNetstreamDriver gtls

Is there anyway to disable SSLv3 on this netstream setup?

Thanks,
Borhan.

**Comment by alorbach** [comment]
Try to post this question into our mailinglist: http://lists.adiscon.net/mailman/listinfo/rsyslog
But I doubt that it is possible to configure TLS/SSL modes in this old rsyslog version.
