### ISSUE TITLE
parameter 'config.enabled' not known

### ISSUE THREAD

**Issue by jvymazal** [rsyslog/rsyslog#4011]
### Expected behavior
`config.enabled` parameter is recognized
### Actual behavior
getting parameter 'config.enabled' not known error on rsyslog startup
### Steps to reproduce the behavior
put any action() statement with `config.enabled="on"` into your config file

note that `config.enabled="off"`seems to work correctly
### Environment
- rsyslog version: 8.1911.0 
- platform: fedora 31 
- for configuration questions/issues, include rsyslog.conf and included config files

**Comment by jvymazal** [comment]
@rgerhards, this is sort of followup to #2520, were some related problems were addressed, however in some case it seems that it still does not work.

**Comment by rgerhards** [comment]
do you have a test case?

**Comment by jvymazal** [comment]
well, it is enough to put `module(load="imtcp" config.enabled="on")` in config, start rsyslog and following lines are from debug output:
`7660.072456834:main thread    : rsconf.c: cnf:global:obj: obj: 'module'`
`7660.072459953:main thread    : rainerscript.c: nvlst 0x5575701b37a0:`
`7660.072461887:main thread    : rainerscript.c: 	name: 'config.enabled', value 'on'`
`7660.072467250:main thread    : rainerscript.c: 	name: 'load', value 'imtcp'`
`7660.072469679:main thread    : rainerscript.c: nvlstGetParam: name 'load', type 13, valnode->bUsed 0`
...
`errmsg.c: Called LogMsg, msg: error during parsing file /etc/rsyslog.conf, on or before line 14: parameter 'config.enabled' not known -- typo in config file?`
`operatingstate.c: osf: MSG error during parsing file /etc/rsyslog.conf, on or before line 14: parameter 'config.enabled' not known -- typo in config file?: rsyslogd: error during parsing file /etc/rsyslog.conf, on or before line 14: parameter 'config.enabled' not known -- typo in config file? [v.. ]`
and after a while:
`ruleset.c: processBATCH: next msg 3: error during parsing file /etc/rsyslog.conf, on or before line 14: parameter 'config.enabled' not known -- typo in config file?`

so while functionally it seems to work, the error is really misleading and unless you test it or look into debug you do not know whether the config statement did apply or not.

**Comment by rgerhards** [comment]
ah ok - I had the impression that it only occasionally happens. I am out of office tomorrow til the end of week but will look into it early next week - pls ping me if you do not hear back.

**Comment by rgerhards** [comment]
bug confirmed via testbench test
