### ISSUE TITLE
How to parse "::" regex using mmnormalize

### ISSUE THREAD

**Issue by sathishkgit** [rsyslog/rsyslog#4015]
Input Data:

DATATYPE::HOSTPERFDATA TIMET::1575451791       HOSTNAME::st    HOSTPERFDATA::rta=0.544000ms;3000.000000;5000.000000;0.000000 pl=0%;80;100;0    HOSTCHECKCOMMAND::hostalive     HOSTSTATE::UP   HOSTSTATETYPE::HARD

Rulebase:
version=2
rule=host:%datatype:word%::%datatypevalue:word%%-:whitespace%%time:word%::%timevalue:number%%-:whitespace%%blob:rest%

Template:
template(name="mmnorm" type="list"){
        constant(value=" ")
        property(name="$!datatype")
}

action(type="mmnormalize" rulebase="/home/cogniz/rsyslog/hosts.rb")
action(type="omfile" File="/home/cogniz/rsyslog/parsed" template="mmnorm")

Output is coming as empty, I am looking for the output $!datatype value which is DATATYPE. Please help

**Comment by sathishkgit** [comment]
Able to parse with below rule.

rule=@host:%datatype:char-to{"extradata":"::"}%::%datetypevalue:char-to{"extradata":"\t"}%%-:whitespace%%time:char-to{"extradata":"::"}%::%timevalue:char-to{"extradata":"\t"}%%-:whitespace%%hostname:char-to{"extradata":"::"}%::%hostnamevalue:char-to{"extradata":"\t"}%%blob:rest%

**Comment by davidelang** [comment]
the other thing you can do is to use the escaped sequence for a : (my memory is 
saying it's something like %38, but I'm probably not remembering it correctly)

David Lang
