### ISSUE TITLE
Rsyslog Doesn't Recover After Shutdown

### ISSUE THREAD

**Issue by kaizen1** [rsyslog/rsyslog#4018]
Everything was running fine OMRELP forwarding to a central server using this sending server config:

if $msg contains 'ALERT' then {action(type="omrelp" target="10.128.0.34" port="10514"     queue.filename="forwarding" action.resumeRetryCount="100" queue.type="linkedList" 
queue.size="10000")}

I shutdown the central server AND the sending server at about the same time. Yeah I know this is a tough case but I'm trying to find the weak points before going into production. 

When I open the Sending server, I see these errors

syslogd: file '/var/spool/rsyslog/forwarding.00000002': open error: No such file or directory [v8.32.0 try http://www.rsyslog.com/e/2040 ]
Dec  9 03:27:32 server-a rsyslogd: action 5 queue[DA]: qDeqDisk error happened at around offset 0 [v8.32.0 try http://www.rsyslog.com/e/2040 ]
Dec  9 03:27:32 server-a rsyslogd: action 5 queue[DA]: error dequeueing element - ignoring, but strange things may happen [v8.32.0 try http://www.rsyslog.com/e/2040 ]
Dec  9 03:27:32 server-a rsyslogd: fatal error on disk queue 'action 5 queue[DA]', emergency switch to direct mode [v8.32.0 try http://www.rsyslog.com/e/2040 ]

**1. How do I "hard reset" an rsyslog server without concern for losing past messages? Delete all queues etc.
2. Any thoughts on this error message?**

Thanks.

**Comment by rgerhards** [comment]
This looks like you did a kill -9 - rsyslog can not guard against this. You may harden the queues with very frequent checkpoints or use pure disk queues. But this will thrash your performance.

**Comment by kaizen1** [comment]
I did a shutdown of the VM via power off. I hardened the queues. Seems fine now.
