### ISSUE TITLE
Increase queue size on shutdown if action queue is full

### ISSUE THREAD

**Issue by StrongestNumber9** [rsyslog/rsyslog#4020]
We think that increasing queue size on shutdown when queues are full is useful feature to prevent losing any messages and to further ensure reliablity of the system. [Reference discussion](https://github.com/rsyslog/rsyslog/issues/3941#issuecomment-549765813)

**Comment by rgerhards** [comment]
@StrongestNumber9 I think #4069 will do the trick. Could you test in your environment?
