### ISSUE TITLE
imfile: log duplication and multiple statefiles for a single input logfile

### ISSUE THREAD

**Issue by nerdquadrat** [rsyslog/rsyslog#4021]
### Expected behavior
rsyslog should not re-read the full logfile when doing a regular restart (without config change), but instead use a statefile to proceed where it last stopped reading for that specific logfile, resulting in no logline beeing dupliated.

### Actual behavior
during a restart rsyslog fully re-reads a logfiles content, producing duplicated logs. additionally we see two statefiles for the same logfile but with a different hash in the filename, where we would rather expect a single statefile.

### Steps to reproduce the behavior
1. configure new input with imfile
2. log some lines to the logfile to create it
3. restart rsyslog to make new config active
4. log some more lines to the logfile (i.e. 20 lines with 50 bytes each)
5. restart rsyslog again (and force writing new statefiles to disk)
6. find two statefiles for same input file and dupliated logs in output file

i have a shellscript that seems to reliably trigger log duplication, but it fails to upload here possibly due to restrictions.
To trigger duplication of logs and statefiles, it seems necessary that the logfile exists, before rsyslog is restarted with the new config (or at least is created before rsyslog fully started up), and before the second restart, enough log data (somewhere above 500bytes)  needs to be written to the logfile, otherwise nothing happens.

When triggered, i get dupliated log data and i see two statefiles for the same imfile:
grep in.100.log /var/lib/rsyslog/imfile-state\:*
/var/lib/rsyslog/imfile-state:183:43e8141b0a668d06:{ "filename": "\/tmp\/statefile_duplicate_test_in.100.log", "prev_was_nl": 0, "curr_offs": 722, "strt_offs": 722 }
/var/lib/rsyslog/imfile-state:183:cf21cb0c1b931e89:{ "filename": "\/tmp\/statefile_duplicate_test_in.100.log", "prev_was_nl": 0, "curr_offs": 518, "strt_offs": 518 }

### Environment
- rsyslog version: rsyslogd  8.1911.0 (aka 2019.11)
- platform: x86_64-redhat-linux-gnu
- for configuration questions/issues, include rsyslog.conf and included config files
ruleset(name="outfile") {
    action(
        type="omfile"
        file="/tmp/out.log")
}
input(type="imfile"
    file="/tmp/statefile_duplicate_test_in.log"
    ruleset="outfile"
    tag="test_statefile_dupliate:"
)

**Comment by rgerhards** [comment]
give the daily stable build a try - I think this is solved by https://github.com/rsyslog/rsyslog/pull/3990

**Comment by nerdquadrat** [comment]
Seems to be fixed, cannot reproduce with nightly version 8.2001.0.master-1575936106 (from http://rpms.adiscon.com/v8-stable-nightly/epel-6/x86_64/RPMS/)

**Comment by rgerhards** [comment]
thx for the confirmation!
