### ISSUE TITLE
elasticsearch module not found

### ISSUE THREAD

**Issue by amisk** [rsyslog/rsyslog#4026]
### Expected behavior
Finding the module

### Actual behavior
Not finding the module

### Steps to reproduce the behavior
module(load="omelasticsearch")

### Environment
- rsyslog version: 8.37.0-9.el8 / 8.1901.0
- platform: CentOS 8 / Sparky (Debian based)

Well, that  basically says it all. I want to try elasticsearch, but on two different machines running two different versions of rsyslog, it can not find the module.

`could not load module '/usr/lib64/rsyslog/omelasticsearch.so'`

At least on the CentOS 8 machine, I have installed elasticsearch, and afterwards also tried reinstalling rsyslog from the main repository.

**Comment by amisk** [comment]
Never mind. I did not realize that this is a different package that I have to install.

I'm closing it.

**Comment by davidelang** [comment]
rsyslog has lots of modules that depend on other packages, in order to have the 
packaging system pull in dependencies automatically, we split the modules into 
different packages so that an install of rsyslog doesn't pull in a ton of 
things.

David Lang
