### ISSUE TITLE
Rsyslog 8.24 and omelasticsearch Content-Type header not supported (HTTP 406 errors)

### ISSUE THREAD

**Issue by funtolinux** [rsyslog/rsyslog#4027]
### Expected behavior
The omelasticsearch module obtains JSON from the template

### Actual behavior
I'm attempting to send logs to elasticsearch 7.5.0 using the omelasticsearch module from the rsyslog 8.24 package version on  RHEL7 running systemd.

### Environment
- for configuration questions/issues, include rsyslog.conf and included config files
module(load="mmjsonparse")          # for parsing CEE-enhanced syslog messages
module(load="omelasticsearch")      # for outputting to Elasticsearch

#try to parse a structured log
action(type="mmjsonparse")

# this is for index names to be like: rsyslog-YYYY.MM.DD
template(name="rsyslog-index" type="string" string="rsyslog-%$YEAR%.%$MONTH%.%$DAY%")

#try to parse a structured log
*.* :mmjsonparse:

# this is for formatting our syslog in JSON with @timestamp
template(name="json-syslog" type="list" option.json="on") {
    constant(value="{")
      constant(value="\"@timestamp\":\"")     property(name="timereported" dateFormat="rfc3339")
      constant(value="\",\"host\":\"")        property(name="hostname")
      constant(value="\",\"severity\":\"")    property(name="syslogseverity-text")
      constant(value="\",\"facility\":\"")    property(name="syslogfacility-text")
      constant(value="\",\"program\":\"")     property(name="programname")
      constant(value="\",\"tag\":\"")         property(name="syslogtag" format="json")
      constant(value="\",")                   property(name="$!all-json" position.from="2")
    # closing brace is in all-json
}

# this is where we actually send the logs to Elasticsearch (localhost:9200 by default)
#action(type="omelasticsearch" template="json-syslog" searchIndex="rsyslog-index" dynSearchIndex="on")
action(type="omelasticsearch"
       server="192.168.10.1"
       serverport="9200"
       template="json-syslog"
       searchIndex="rsyslog-index"
       searchType="test-type"
       dynSearchIndex="on"
       maxbytes="100m"
       queue.type="linkedlist"
       queue.size="5000"
       queue.dequeuebatchsize="300"
       action.resumeretrycount="-1")

- rsyslog version: 
rsyslog-8.24.0-16
rsyslog-elasticsearch-8.24.0-16
rsyslog-mmjsonparse-8.24.0-16

Error: 
3494.218511878:action 4 queue:Reg/w0: omelasticsearch: pWrkrData reply: '{"error":"Content-Type header [text/json; charset=utf-8] is not supported","status":406}'
3494.218519574:action 4 queue:Reg/w0: omelasticsearch: no local error logger defined - ignoring ES error information

- platform:

**Comment by rgerhards** [comment]
your version is way to old (3+ years). Update to current (we are right now at 8.1911.0). Packages at rsyslog.com homepage (right hand side, top).
