### ISSUE TITLE
Does the private key of rsyslog support encryption?

### ISSUE THREAD

**Issue by leijie0358** [rsyslog/rsyslog#4030]
### Expected behavior
The private key of rsyslog supports encrypted storage.
### Actual behavior
If the private key of rsyslog is encrypted, the client cannot connect to the server. I guess, it's because the rsyslog cannot decrypt the ciphertext private key, and no configuration file is used to save the encryption password.
How to solve the problem? Thank you.

### Environment
- rsyslog version: 8.24.0
- platform: redhat 6.5
- for configuration questions/issues, include rsyslog.conf and included config files

**Comment by leijie0358** [comment]
@rgerhards ,how to solve my problem? Help me . Thank you!

**Comment by rgerhards** [comment]
you can use a key-program to read the private key via an elsewhere-provided file. I don't think we have native support for this.
