### ISSUE TITLE
Run rsyslog as ont-shot instead of daemon

### ISSUE THREAD

**Issue by bmy4415** [rsyslog/rsyslog#4034]
Hi, I'm new to rsyslog.

I'm using rsyslog to process log files. Currently I'm using `imfile` input module.
My program makes log files every 10 minutes so I want to run rsyslog every when log files are created and terminate it after processing all log files.

I tried to find related options but nothing was found.
Is there any ways to do this?
Thanks

For your information I attached this.
```
$ /usr/sbin/rsyslogd -v
rsyslogd 8.24.0, compiled with:
	PLATFORM:				x86_64-redhat-linux-gnu
	PLATFORM (lsb_release -d):
	FEATURE_REGEXP:				Yes
	GSSAPI Kerberos 5 support:		Yes
	FEATURE_DEBUG (debug build, slow code):	No
	32bit Atomic operations supported:	Yes
	64bit Atomic operations supported:	Yes
	memory allocator:			system default
	Runtime Instrumentation (slow code):	No
	uuid support:				Yes
	Number of Bits in RainerScript integers: 64

See http://www.rsyslog.com for more information.
```

**Comment by davidelang** [comment]
the -n option will tell it not to daemonize itself,but you will have to detect 
thatit's finifhed processing the file and kill it.

This is just not a use case we design for, it's designed to keep running and 
detect that a new file was created and process it.

David Lang

**Comment by bmy4415** [comment]
Thanks David,

Yes this may not be normal use case but I'm considering this to fit into my environment.
By the way what do you mean `kill it`? Do you mean kill rsyslog from external with, e.g, with command like `killall -9 rsyslogd` or is there any options inside rsyslog conf itself?

**Comment by davidelang** [comment]
external kill command

David Lang

**Comment by bmy4415** [comment]
I got what you mean.
Thanks David.
I will close this issue.

**Comment by rgerhards** [comment]
just don't do a `-9` kill - let it terminate gracefully!

**Comment by bmy4415** [comment]
Oh, can you give an example how to terminate gracefullly?

**Comment by rgerhards** [comment]
`killall rsyslogd`
