### ISSUE TITLE
SSL_set_verify_depth restricts certificate verification

### ISSUE THREAD

**Issue by amarkelov** [rsyslog/rsyslog#4035]
### Expected behavior
Unlimited depth. 

### Actual behavior
If client is issued TLS certificate by CA from a different branch than the server's and the depth is greater than the hardcoded limit, TLS connection fails.

### Steps to reproduce the behavior
Create root CA with two branches of sub-CAs of different depth greater than 2 for the CA that issues certificate for client for example. TLS handshake will fail because root CA is higher up the chain.

### Environment
- rsyslog version: 
    $ rpm -qa | grep rsyslog
    rsyslog-openssl-8.1901.0-1.el7.x86_64
    rsyslog-8.1901.0-1.el7.x86_64
    rsyslog-gnutls-8.1901.0-1.el7.x86_64
    $ rsyslogd -v
    rsyslogd  8.1901.0 (aka 2019.01) compiled with:
        PLATFORM:               x86_64-redhat-linux-gnu
        PLATFORM (lsb_release -d):      
        FEATURE_REGEXP:             Yes
        GSSAPI Kerberos 5 support:      Yes
        FEATURE_DEBUG (debug build, slow code): No
        32bit Atomic operations supported:  Yes
        64bit Atomic operations supported:  Yes
        memory allocator:           system default
        Runtime Instrumentation (slow code):    No
        uuid support:               Yes
        systemd support:            Yes
        Number of Bits in RainerScript integers: 64

    See https://www.rsyslog.com for more information.
- platform: CentOS 7.5
- for configuration questions/issues, include rsyslog.conf and included config files

### Suggested fix

Do not limit the verification depth or make it an optional parameter in configuration file:

    diff --git a/runtime/nsd_ossl.c b/runtime/nsd_ossl.c
    index 4f8dd845a..76cc132fa 100644
    --- a/runtime/nsd_ossl.c
    +++ b/runtime/nsd_ossl.c
    @@ -626,7 +626,6 @@ osslInitSession(nsd_ossl_t *pThis) /* , nsd_ossl_t *pServer) */
                    dbgprintf("osslInitSession: enable certificate checking (Mode=%d)\n", pThis->authMode);
                    /* Enable certificate valid checking */
                    SSL_set_verify(pThis->ssl, SSL_VERIFY_PEER|SSL_VERIFY_FAIL_IF_NO_PEER_CERT, verify_callback);
    -               SSL_set_verify_depth(pThis->ssl, 2);
            }
     
            if (bAnonInit == 1) { /* no mutex needed, read-only after init */

**Comment by amarkelov** [comment]
Looks like the depth was limited to 4 initially (still hardcoded) and then in commit 9c60ae361e538203f6bb1b5de7b0f988c2941094 it was reduced to 2.

**Comment by rgerhards** [comment]
@alorbach can you comment on this?

**Comment by alorbach** [comment]
I need to research why we used 4 and now 2 but as far as I can see, there is no deeper reason why thge SSL_set_verify_depth and depth was reduced from 4 to 2, most likely because it was taken from openssl sample code.

We can change this default back to 4 and make it configurable.

**Comment by alorbach** [comment]
@rgerhards 
My recommendation would be to change the default back to 4 as this should cover 99.99% of all existing certificates. I don't see a reason to make this configurable.

**Comment by amarkelov** [comment]
No, changing back to 4 is not going to cut for me. Why would you restrict it at all to begin with?
openssl is not doing it by default, you'd need to pass the depth limit as an optional argument.

**Comment by amarkelov** [comment]
@alorbach I have clients for which even depth 20 is not going to work for x509/name authentication. I have a very good reason to have it configurable ;-)

**Comment by davidelang** [comment]
is there a reason not to just make it unreasonably large (say 100)? or is this 
something that could be used as a DOS attack on the system if it's set too 
large? (memory or cpu)

David Lang

**Comment by alorbach** [comment]
If we remove the "SSL_set_verify_depth" API calls, the internal default will be actually 100 as the API description tells us: https://www.openssl.org/docs/man1.1.0/man3/SSL_set_verify.html

I cannot find anmmy specific reason why to lower this count in the API description.

**Comment by rgerhards** [comment]
would it be a real problem to make it configurable? I know it's pain to shuffle this through the object interface, but possibly not more than an hour's worth or work? If so, we should go for maybe 25 by default and permit to override it. Just my 2cts, maintainer head off.

**Comment by alorbach** [comment]
Well allright then lets go for it... I will create a PR for this later.

**Comment by alorbach** [comment]
Closed by https://github.com/rsyslog/rsyslog/pull/4091
