### ISSUE TITLE
Using "TCPSendBuf error -2027, destruct TCP Connection" as failover condition

### ISSUE THREAD

**Issue by amisk** [rsyslog/rsyslog#4038]
Hi,

failover often takes time, and everytime I lose the one message that would go out before the primary server goes down. While experimentng with values in /proc/sys/net/ipv4/tcp_retries2, I saw that if it is very small, which means that it tells the system almost immediately that the tcp connection is dead, the error "TCPSendBuf error -2027, destruct TCP Connection to ..." appears. But it would still not change to the other server.
Is there a way to set the action to be suspended as soon as this error is received?
Thx.

**Comment by rgerhards** [comment]
> Is there a way to set the action to be suspended as soon as this error is received?

this is what actually happens. As soon as we get the error status, we suspend. See this on TCP:

https://rainer.gerhards.net/2008/04/on-unreliability-of-plain-tcp-syslog.html

**Comment by davidelang** [comment]
first read 
https://rainer.gerhards.net/2008/04/on-unreliability-of-plain-tcp-syslog.html

then switch to RELP :-)

(and ask any questions you still have after reading that post)

David Lang

**Comment by amisk** [comment]
Sorry, I was a bit confused, because it wouldn't switch receivers for about 15 minutes or so...

I do have one question though, but certainly not an issue.

If I remember correctly, in a ruleset an action and the following action containing an execOnlyWhenPreviousIsSuspended are executed asynchronously, if a queue is defined, right?
So, without setting any queue, neither in the ruleset, nor in the action, the two actions are run sequentally?

Because, curiously, if I use relp, the one message after disconnect ist lost, and if I use tcp its always the first three messages after disconnect. In both cases it is independent of the time between between the last message and the disconnect. Its always the same number of lost messages.

I could imagine, that if it is still run in parallel, the first message after disconnect comes in, is processed by both actions, and since it is not yet failed because the first action is not done while the second starts, it is lost. But if it is run sequentally, the execOnly... should work becuase the first action would notice that the delivery failed.

Where is the error in my thought?

**Comment by davidelang** [comment]
if you would read the post we sent you, the network acts as a queue, so even 
after the receiver stops accepting messages, the network allows you to 'deliver' 
some additional messages (how many depends on the exact network path). Rsyslog 
doesn't know those messages do not arrive.

If there is not a queue on an action, the actions happen in order, and if one 
has problems, it delays delivery to any later actions (so one will retry to it's 
limit before the one after that gets a chance to evaluate the 'only if the last 
didn't work' criterial)

with RELP, there is one condition where one message can get lost, it's a known 
issue, but nobody has been willing to sponsor the development to fix this last 
issue and it hasn't made it up the to-do list far enough to get work done.

David Lang
