### ISSUE TITLE
imfile wildcard path length limit

### ISSUE THREAD

**Issue by bmy4415** [rsyslog/rsyslog#4039]
### Expected behavior
imfile input module can track all files in specified directory

### Actual behavior
When I starts rsyslogd with -d option, imfile prints error
```imfile: ignoring file '<file path>' cannot stat(): No such file or directory```
But \<file path\> is only substring of real path, not a full path. And it's length is always 199.

### Steps to reproduce the behavior
Make any files whose path is longer than 199.
This will reproduce my error.

### Environment
```
$ /usr/sbin/rsyslogd -v
rsyslogd 8.24.0, compiled with:
	PLATFORM:				x86_64-redhat-linux-gnu
	PLATFORM (lsb_release -d):
	FEATURE_REGEXP:				Yes
	GSSAPI Kerberos 5 support:		Yes
	FEATURE_DEBUG (debug build, slow code):	No
	32bit Atomic operations supported:	Yes
	64bit Atomic operations supported:	Yes
	memory allocator:			system default
	Runtime Instrumentation (slow code):	No
	uuid support:				Yes
	Number of Bits in RainerScript integers: 64

See http://www.rsyslog.com for more information.
```

**Comment by rgerhards** [comment]
The version you are using is very old and no longer supported by the community. It is also very probable that the issues stems back to a long-solved issues. As such, please update to the currently supported version and retry. Report back if the problem persists.

The rsyslog project provides packages for current versions: https://www.rsyslog.com/downloads/download-other/

If you insist on using an outdated version, you can also contact your distro or consider [rsyslog professional services](https://www.rsyslog.com/professional-services/enterprise-support/).
