### ISSUE TITLE
Json timezone bug.

### ISSUE THREAD

**Issue by splitice** [rsyslog/rsyslog#404]
Hi,

The following configuration has ceased working in my upgrade to v8.

```
$template ls_json,"{%timestamp:::date-rfc3339,jsonf:@timestamp%,%source:::jsonf:@source_host%,\"@source\":\"syslog://%fromhost-ip:::json%\",\"@message\":\"%timestamp% %app-name%:%msg:::json%\",\"@fields\":{%syslogfacility-text:::jsonf:facility%,%syslogseverity-text:::jsonf:severity%,%app-name:::jsonf:program%,%procid:::jsonf:processid%}}"
```

I have also tried to use:
```
template(name="ls_json"
         type="list"
         option.json="on") {
           constant(value="{")
             constant(value="\"@timestamp\":\"")     property(name="timereported" dateFormat="rfc3339")
             constant(value="\",\"@version\":\"1")
             constant(value="\",\"message\":\"")     property(name="msg")
             constant(value="\",\"host\":\"")        property(name="hostname")
             constant(value="\",\"severity\":\"")    property(name="syslogseverity-text")
             constant(value="\",\"facility\":\"")    property(name="syslogfacility-text")
             constant(value="\",\"programname\":\"") property(name="programname")
             constant(value="\",\"procid\":\"")      property(name="procid")
           constant(value="\"}\n")
         }
```

It now outputs something like:
```
{"@timestamp":"2015-06-19T05:06:20U23:/*","@version":"1
```

Note the garbled timezone.

**Comment by splitice** [comment]
In a fluke of good luck I just noticed that the incomming messages to the udp input are themselves missing a timezone. I guess this is the cause of the bug.

```
.<182>Jun 19 08:17:53 us13.xxxx nginx: ...
```

**Comment by splitice** [comment]
Issue workaround:
```
input(type="imudp" ... defaultTZ="+00:00")
```

**Comment by rgerhards** [comment]
The missing input time zone is regular for RFC3164 messages, so rsyslog should handle that correctly. Smells like a bug.

**Comment by alorbach** [comment]
@splitice Can you test with the latest rsyslog v8 build? Or post a minimal working sample configuration. 

I made a test with your template, and my output looks like this (RFC3164 sample messages received by UDP): 

{"@timestamp":"2015-07-09T10:25:46-07:00","@version":"1","....

**Comment by splitice** [comment]
Unfortunately I am no longer running v8, had to roll back due to segfaults. Adding a defaultTZ to imudp resolved this issue.

Looks like it was un-initialized by default.

**Comment by alorbach** [comment]
Strange, the Init of defaultTZ is ok as far I can see.

**Comment by rgerhards** [comment]
I think we'll close this bug for now, because I've never seen any case where it doesn't work. So I guess it's related to the environment and we can debug it only if we have someone with an env to help. If someone else experiences that problem and is willing to help debugging, please re-open this issue.
