### ISSUE TITLE
Segfault in releaseDoActionParams function

### ISSUE THREAD

**Issue by nemuineko** [rsyslog/rsyslog#4040]
First post here, let me know if you need any more info.

### Issue
#3019  is still actual and doesn't seem to have been patched

### Expected behavior
Execute the function **releaseDoActionParams**  in **tplToString** (template.c:233) without any issue every time

### Actual behavior
Segfault in memcpy when executing in **template.c:233** at some times, but not all

The "offending" line in question:
**`memcpy(iparam->param + iBuf, pVal, iLenVal);`**

### Steps to reproduce the behavior
Same situation heare, as @snaix described in #3019
We can't reproduce at runtime, but the circumstances and variable values are the same as described there

```
Program terminated with signal SIGSEGV, Segmentation fault.                                                                                                                                             [240/1943]
#0  0x00007fbd57edcf96 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
[Current thread is 1 (Thread 0x7fbc59ffb700 (LWP 4008))]
(gdb) bt full
#0  0x00007fbd57edcf96 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
No symbol table info available.
#1  0x000055de1f4050f4 in memcpy (__len=<optimized out>, __src=<optimized out>, __dest=<optimized out>) at /usr/include/x86_64-linux-gnu/bits/string3.h:53
No locals.
#2  tplToString (pTpl=0x55de201cec40, pMsg=pMsg@entry=0x7fbd38b5c7f0, iparam=iparam@entry=0x55de2033db30, ttNow=ttNow@entry=0x7fbc59ff9560) at ../template.c:233
        iRet = RS_RET_OK
        pTpe = 0x55de201cecf0
        iBuf = 0
        bMustBeFreed = 0
        pVal = 0x7fbd38b5ca27 "1576587428"
        iLenVal = 10
        extra_space = <optimized out>
#3  0x000055de1f3ff789 in prepareDoActionParams (ttNow=0x7fbc59ff9560, pMsg=0x7fbd38b5c7f0, pWti=0x55de2033d640, pAction=0x55de20262490) at ../action.c:997
        i = 1
        json = 0x55de2033d670
        iparams = 0x55de2033d670
        iRet = RS_RET_OK
        pWrkrInfo = <optimized out>
```

The variables:

```
(gdb) frame 2
#2  tplToString (pTpl=0x55de201cec40, pMsg=pMsg@entry=0x7fbd38b5c7f0, iparam=iparam@entry=0x55de2033db30, ttNow=ttNow@entry=0x7fbc59ff9560) at ../template.c:233
233     ../template.c: No such file or directory.
(gdb) print iparam->lenBuf
$1 = 128
(gdb) print iparam->lenStr
$2 = 10
(gdb) print iparam->param
$3 = (uchar *) 0x0

```

### Environment
- rsyslog version: 
rsyslogd  8.1901.0 (aka 2019.01) compiled with:
        PLATFORM:                               x86_64-pc-linux-gnu
        PLATFORM (lsb_release -d):              Description:    Debian GNU/Linux 9.9 (stretch)

### Solution

Looks like #3019 never was merged to the main branch (we've checked the current version and compared historically etc.) and it looks like it was just never merged to main.

So the only things that remains seems to be to merge this commit https://github.com/rgerhards/rsyslog/commit/b65baa5ecf2b5300c95e463ebf0357c28a564d11 to main branch

**Comment by davidelang** [comment]
can you try the current version (8.1912 I believe) there's been a lot of changes 
since the version you are trying that was released in January.

David Lang

**Comment by nemuineko** [comment]
Hello, thank you for the suggestion.
The latest version available was v8.1911.0 one in sid for Debian.

I tried it out today, but we're still getting the same issue.
So unfortunately, it did not help.

```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/sbin/rsyslogd -n -iNONE'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fac9ca39f96 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
[Current thread is 1 (Thread 0x7fabcd7fa700 (LWP 6861))]
(gdb) bt
#0  0x00007fac9ca39f96 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x000055f1e044bfb4 in memcpy (__len=<optimized out>, __src=<optimized out>, __dest=<optimized out>) at /usr/include/x86_64-linux-gnu/bits/string3.h:53
#2  tplToString (pTpl=0x55f1e1aa5c40, pMsg=pMsg@entry=0x7fac7824d620, iparam=iparam@entry=0x55f1e1c179e0, ttNow=ttNow@entry=0x7fabcd7f8560) at ../template.c:233
```
```
(gdb) frame 2
#2  tplToString (pTpl=0x55f1e1aa5c40, pMsg=pMsg@entry=0x7fac7824d620, iparam=iparam@entry=0x55f1e1c179e0, ttNow=ttNow@entry=0x7fabcd7f8560) at ../template.c:233
233     ../template.c: No such file or directory.
(gdb) print iparam->lenBuf
$1 = 128
(gdb) print iparam->lenStr
$2 = 10
(gdb) print iparam->param
$3 = (uchar *) 0x0
```
```
root@hgd0-t2logstash-1:/home/unstable-rsyslog# rsyslogd -v
rsyslogd  8.1911.0 (aka 2019.11) compiled with:
        PLATFORM:                               x86_64-pc-linux-gnu
        PLATFORM (lsb_release -d):              Description:    Debian GNU/Linux 9.9 (stretch)
```

This was not very surprising as we've checked the latest versions code for the fix that's needed and it doesn't have it. And due to the nature of the issue, it won't stop happening as long as the variables in iparam look like they do now.

**Comment by rgerhards** [comment]
> So the only things that remains seems to be to merge this commit [rgerhards@b65baa5](https://github.com/rgerhards/rsyslog/commit/b65baa5ecf2b5300c95e463ebf0357c28a564d11) to main branch

This is strange. I double-checked and the patch actually is not present. Don't know what happened. I'll see that I add it now.

**Comment by nemuineko** [comment]
Stuff happens :)
Thank you!
