### ISSUE TITLE
Rsyslogd aborts when writing to disk queue from multiple workers

### ISSUE THREAD

**Issue by miztake** [rsyslog/rsyslog#4041]
### Expected behavior
Rsyslogd does not abort.

### Actual behavior
Rsyslogd aborts.

### Environment
Some action queues were defined for each rule with the same filter.

   /etc/rsyslog.conf
   --------
    $ActionQueueType LinkedList
    $ActionQueueFileName queue_fwd1
    $ActionResumeRetryCount -1
    $ActionQueueSaveOnShutdown on
    *.info;mail.none;authpriv.none;cron.none        @@11.11.11.11:514

    $ActionQueueType LinkedList
    $ActionQueueFileName queue_fwd2
    $ActionResumeRetryCount -1
    $ActionQueueSaveOnShutdown on
    *.info;mail.none;authpriv.none;cron.none        @@22.22.22.22:514

    $ActionQueueType LinkedList
    $ActionQueueFileName queue_fwd3
    $ActionResumeRetryCount -1
    $ActionQueueSaveOnShutdown on
    *.info;mail.none;authpriv.none;cron.none        @@33.33.33.33:514
   --------

Because the destination does not exist, the queue is full.
When multiple action queues became full at the same time and tried to write to disk at the same time, the json library terminated abnormally.

  backtrace
  --------
    Program received signal SIGABRT, Aborted.
    [Switching to Thread 0x7fffe4ff9700 (LWP 11752)]
    0x00007ffff69c1207 in raise () from /lib64/libc.so.6
    (gdb) bt
    #0  0x00007ffff69c1207 in raise () from /lib64/libc.so.6
    #1  0x00007ffff69c28f8 in abort () from /lib64/libc.so.6
    #2  0x00007ffff6a03cc7 in __libc_message () from /lib64/libc.so.6
    #3  0x00007ffff6a0a574 in malloc_printerr () from /lib64/libc.so.6
    #4  0x00007ffff6a0ffa3 in _int_realloc () from /lib64/libc.so.6
    #5  0x00007ffff6a10e42 in realloc () from /lib64/libc.so.6
    #6  0x00007ffff71959f9 in printbuf_extend (p=p@entry=0x7fffc80008f0, min_size=<optimized out>) at printbuf.c:79
    #7  0x00007ffff7195b20 in printbuf_memappend_no_nul (p=p@entry=0x7fffc80008f0, buf=0x7fffe8083348 "16472", size=5)
        at printbuf.c:105
    #8  0x00007ffff7190555 in fjson_escape_str (pb=pb@entry=0x7fffc80008f0, str=<optimized out>) at json_object.c:179
    #9  0x00007ffff719058f in fjson_object_string_to_json_string (jso=0x7fffe8083320, pb=0x7fffc80008f0, level=<optimized out>,
        flags=<optimized out>) at json_object.c:821
    #10 0x00007ffff71908fb in fjson_object_object_to_json_string (jso=<optimized out>, pb=0x7fffc80008f0, level=0, flags=1)
        at json_object.c:320
    #11 0x00007ffff7190e1c in fjson_object_to_json_string_ext (jso=0x7fffe8082910, flags=flags@entry=1) at json_object.c:256
    #12 0x00007ffff7190e6a in fjson_object_to_json_string (jso=<optimized out>) at json_object.c:266
    #13 0x00007ffff71916df in fjson_object_get_string (jso=<optimized out>) at json_object.c:888
    #14 0x0000000000437486 in MsgSerialize (pThis=0x7fffe8084dd0, pStrm=0x6cffd0) at msg.c:1245
    #15 0x000000000044d954 in qAddDisk (pThis=0x6cfbe0, pMsg=0x7fffe8084dd0) at queue.c:1027
    #16 0x000000000044e237 in qqueueAdd (pMsg=0x7fffe8084dd0, pThis=0x6cfbe0) at queue.c:1162
    #17 doEnqSingleObj (pThis=pThis@entry=0x6cfbe0, flowCtlType=<optimized out>, flowCtlType@entry=eFLOWCTL_NO_DELAY,
        pMsg=0x7fffe8084dd0) at queue.c:3094
    #18 0x0000000000451218 in qqueueEnqMsg (pThis=0x6cfbe0, flowCtlType=flowCtlType@entry=eFLOWCTL_NO_DELAY, pMsg=<optimized out>)
        at queue.c:3195
    #19 0x00000000004513a6 in ConsumerDA (pThis=0x6c33f0, pWti=0x6cf500) at queue.c:2203
    #20 0x000000000044cd5e in wtiWorker (pThis=pThis@entry=0x6cf500) at wti.c:428
    #21 0x000000000044b707 in wtpWorker (arg=0x6cf500) at wtp.c:435
    #22 0x00007ffff79b0dd5 in start_thread () from /lib64/libpthread.so.0
    #23 0x00007ffff6a89b3d in clone () from /lib64/libc.so.6
    (gdb)
  --------

It is assumed that the json library (libfastjson) is not thread-safe.

**Comment by davidelang** [comment]
what version of rsyslog is this?

David Lang

**Comment by miztake** [comment]
Hi, @davidelang

Thank you for your confirmation.

The issue occurred in rsyslogd, which built the latest version of the master branch.
The latest git log is as follows.

    commit 7e1b40427bf4c6791a2c4ea3b38119c53f10a02b
    Author: Rainer Gerhards <rgerhards@adiscon.com>
    Date:   Tue Dec 10 10:33:21 2019 +0100

        maintain ChangeLog

The result of rsyslogd -v is as follows.

    # /usr/local/sbin/rsyslogd -v
    rsyslogd  8.2001.0.master (aka 2020.01) compiled with:
            PLATFORM:                               x86_64-unknown-linux-gnu
            PLATFORM (lsb_release -d):
            FEATURE_REGEXP:                         Yes
            GSSAPI Kerberos 5 support:              No
            FEATURE_DEBUG (debug build, slow code): No
            32bit Atomic operations supported:      Yes
            64bit Atomic operations supported:      Yes
            memory allocator:                       system default
            Runtime Instrumentation (slow code):    No
            uuid support:                           Yes
            systemd support:                        Yes
            Config file:                            /etc/rsyslog.conf
            PID file:                               /var/run/rsyslogd.pid
            Number of Bits in RainerScript integers: 64

    See https://www.rsyslog.com for more information.
    #

**Comment by davidelang** [comment]
sorry, I mis-read the version

David Lang

**Comment by rgerhards** [comment]
fixed by #4042 (at least as a work-around)
