### ISSUE TITLE
APP-NAME in RFC5424 must be at least length 1

### ISSUE THREAD

**Issue by onet-git** [rsyslog/rsyslog#4043]
### Expected behavior

APP-NAME can be of length zero, for example if programname="/foo".

Under RFC 5424 that APP-NAME should be sent as "-".

### Actual behavior

APP-NAME is sent as "", which makes many parsers.

### Steps to reproduce the behavior

make sure that parser.permitSlashInProgramName is off

inject a syslog message with programname "/foo"

### Environment
- rsyslog version: 8.1911.0
- platform: Ubuntu 16.04

I also verified this in the source code, there is no special handling of zero length APP-NAME.

**Comment by rgerhards** [comment]
confirmed via new testbench test
