### ISSUE TITLE
rsyslog-imdocker as Alpine package

### ISSUE THREAD

**Issue by Nkmol** [rsyslog/rsyslog#4054]
### Expected behaviour
Module to be available as Alpine Package (https://pkgs.alpinelinux.org/packages?name=rsyslog-imdocker)

### Actual behaviour
This is not available.

### Steps to reproduce the behaviour
run `docker pull alpine && docker run alpine apk add rsyslog-imdocker`

### Environment
- rsyslog version: v8.1911.0
- platform: Linux Alpine 3.10.3

---

Additional questions, would there be any way for me to easily build a _contrib_ independently (https://github.com/rsyslog/rsyslog/tree/master/contrib/imdocker)? Or even build this from an Alpine state in a modular way.

**Comment by rgerhards** [comment]
FYI: you need to request the alpine package from the Alpine community. They will most likly not read rsyslog's issue tracker.

**Comment by Nkmol** [comment]
Link to the Alpine request: https://gitlab.alpinelinux.org/alpine/aports/issues/11073
