### ISSUE TITLE
Sellinux

### ISSUE THREAD

**Issue by spacecabbie** [rsyslog/rsyslog#4055]
### Expected behavior
sellinux should not be triggert but i am not sure.
### Actual behavior
selinux is triggert and blocking appends
### Steps to reproduce the behavior
unknownm
### Environment
rsyslogd 8.24.0-41.el7_7.2, compiled with:
        PLATFORM:                               x86_64-redhat-linux-gnu
        PLATFORM (lsb_release -d):
        FEATURE_REGEXP:                         Yes
        GSSAPI Kerberos 5 support:              Yes
        FEATURE_DEBUG (debug build, slow code): No
        32bit Atomic operations supported:      Yes
        64bit Atomic operations supported:      Yes
        memory allocator:                       system default
        Runtime Instrumentation (slow code):    No
        uuid support:                           Yes
        Number of Bits in RainerScript integers: 64

centos-release-7-7.1908.0.el7.centos.x86_64
I am encountering issues with selinux set to permissive so i can soord all potential issues.
Basicaly it would block almost all appends to log files. (not the default ones as far as i can see.

> type=AVC msg=audit(1576778703.971:602266): avc:  denied  { append } for  pid=13373 comm=72733A6D61696E20513A526567 path="/var/remotelog/vps/python.log" dev="dm-0" ino=402671676 scontext=system_u:system_r:syslogd_t:s0 tcontext=system_u:object_r:var_t:s0 tclass=file permissive=1
        Was caused by:
                Missing type enforcement (TE) allow rule.

                You can use audit2allow to generate a loadable module to allow this access.

That pid is rsyslogd its nothing really big and i can make a policy to allow it but a it bugs me why only a pid ? no name and shouldn't selinux by default ignore this ?

I am wondering what I must have F.... eh (changed yea lets go with that.) to cause this. Since i cannot believe this is default behaviour. 

I am an absolute novice when it comes to rsyslog i have always ignored how linux loged things just recently i have start setting it up. So forgive me if this is something basic i missed.

**Comment by davidelang** [comment]
I'll bet that if you look at your distro's selinux config, you will find that 
they let rsyslog write to /var/log but you have configured your system to use 
/var/remotelog which the distro maintainers don't know about, so they don't 
allow rsyslog to write there.

The rsyslog project does not provide any selinux config, so you will need to 
take this issue up with RedHat

We can help you with your rsyslog config, but I would suggest that you upgrade 
to a current version (8.24 is about 3 years old now) to allow us to better help 
you (this won't make any difference to your selinux issue, but will make a big 
difference if you run into other issues)

David Lang

**Comment by spacecabbie** [comment]
> I'll bet that if you look at your distro's selinux config, you will find that they let rsyslog write to /var/log but you have configured your system to use /var/remotelog 

Oh shit missed that now it makes sense those are remote incoming logs. now i know why there are not accepted and can safely add them cool !

> which the distro maintainers don't know about, so they don't allow rsyslog to write there. The rsyslog project does not provide any selinux config, so you will need to take this issue up with RedHat We can help you with your rsyslog config, but I would suggest that you upgrade to a current version (8.24 is about 3 years old now) to allow us to better help you (this won't make any difference to your selinux issue, but will make a big difference if you run into other issues) David Lang

Thanks for that for now i am focusing on selinux. Then I'll return to syslog config.
I'll definitely update rsyslog since that might solve some other issues i had.
thank you for the quick solve !
