### ISSUE TITLE
omfile: Mixed messages received on imudp

### ISSUE THREAD

**Issue by skupkosk** [rsyslog/rsyslog#4058]
### Expected behavior
messages being logged to files not mixed

### Actual behavior
messages are mixed; in the middle of one message the another begins and the rest of original message logged on new line

> Dec 19 06:55:09 10.0.0.1 user.info RT_FLOW<14>1 2019-12-19T06:55:09.735+01:00 FW01 RT_FLOW - RT_FLOW_SESSION_CLOSE [junos@2636.1.1.1.2.86 reason="TCP CLIENT RST" source-address="9.5.4.3" source-port="53674" destination-address="9.5.4.152" destination-port="443" service-name="junos-https" nat-source-address="9.5.4.3" nat-source-port="53674" nat-destination-address="10.1.0.3" nat-destination-port="443" src-nat-rule-type="N/A" src-nat-rule-name="N/A" dst-nat-rule-type="static rule" dst-nat-rule-name="rule1" protocol-id="6" policy-name="policy1" source-zone-name="untrust" destination-zone-name="trust" session-id-32="336820" packets-from-client="11" **bytes-from-client="1399" pDec** 19 06:55:09 10.0.0.194 local0.info sfalert: Protocol: TCP, SrcIP: 37.128.181.209, OriginalClientIP: ::, DstIP: 10.1.0.5, SrcPort: 16559, DstPort: 443, TCPFlags: 0x0, IngressInterface: s1p7, IngressZone: passive, DE: Primary Detection Engine (46aec3be-7f65-11e8-a24f-897533c50a4f), Policy: ACP, ConnectType: Start, AccessControlRuleName: hosting, AccessControlRuleAction: Allow, Prefilter Policy: Unknown, UserName: No Authentication Required, InitiatorPackets: 2, ResponderPackets: 1, InitiatorBytes: 130, ResponderBytes: 70, NAPPolicy: NA-BASE-DMZ, DNSResponseType: No Error, Sinkhole: Unknown, URLCategory: Unknown, URLReputation: Risk unknown
> Dec 19 06:55:09 10.0.0.194 local0.info sfalert: Protocol: TCP, SrcIP: 159.253.66.199, OriginalClientIP: ::, DstIP: 10.1.0.6, SrcPort: 25782, DstPort: 443, TCPFlags: 0x0, IngressInterface: s1p7, IngressZone: passive, DE: Primary Detection Engine (46aec3be-7f65-11e8-a24f-897533c50a4f), Policy: ACP, ConnectType: Start, AccessControlRuleName: hosting, AccessControlRuleAction: Allow, Prefilter Policy: Unknown, UserName: No Authentication Required, InitiatorPackets: 2, ResponderPackets: 1, InitiatorBytes: 130, ResponderBytes: 70, NAPPolicy: NA-BASE-DMZ, DNSResponseType: No Error, Sinkhole: Unknown, URLCategory: Unknown, URLReputation: Risk unknown
> **ackets-from-server="11"** bytes-from-server="4469" elapsed-time="2" application="UNKNOWN" nested-application="UNKNOWN" username="N/A" roles="N/A" packet-incoming-interface="reth0.11" encrypted="UNKNOWN"]
> Dec 19 06:55:09 10.0.0.1 user.info RT_FLOW<14>1 2019-12-19T06:55:09.735+01:00 FW01 RT_FLOW - RT_FLOW_SESSION_CLOSE [junos@2636.1.1.1.2.86 reason="TCP FIN" source-address="212.174.38.188" source-port="51841" destination-address="9.5.4.120" destination-port="443" service-name="junos-https" nat-source-address="212.174.38.188" nat-source-port="51841" nat-destination-address="10.1.0.6" nat-destination-port="443" src-nat-rule-type="N/A" src-nat-rule-name="N/A" dst-nat-rule-type="static rule" dst-nat-rule-name="rule1" protocol-id="6" policy-name="policy1" source-zone-name="untrust" destination-zone-name="trust" session-id-32="118290" packets-from-client="11" bytes-from-client="1251" packets-from-server="11" bytes-from-server="4995" elapsed-time="3" application="UNKNOWN" nested-application="UNKNOWN" username="N/A" roles="N/A" packet-incoming-interface="reth0.11" encrypted="UNKNOWN"]

### Environment
- rsyslog version: 
- platform: 
- for configuration questions/issues, include rsyslog.conf and included config files

**Comment by skupkosk** [comment]
Seems it can be closed as this config is probably not _supported_:

> :fromhost-ip, isequal, "10.0.0.1" -/var/log/net/net-all.log;rawmsgTemplate
> :fromhost-ip, !isequal, "10.0.0.1" -/var/log/net/net-all.log

**Comment by rgerhards** [comment]
I don't get the report and why you see that given config is not supported. 

If you would like pursue this issue, please provide:

* rsyslog version:
* platform:
* for configuration questions/issues, include rsyslog.conf and included config files

**Comment by davidelang** [comment]
On Fri, 20 Dec 2019, skupkosk wrote:

> - rsyslog version: 

This version is over a year old, could you please test with the current version?

David Lang

**Comment by davidelang** [comment]
two actions writing to the same file? I would also have assumed that this is a 
problem (my work-around in the past would be to populate a variable and then 
call a ruleset that outputs the message with a template that just dumps that 
variable out)

David Lang

**Comment by skupkosk** [comment]
> I don't get the report and why you see that given config is not supported.
> 
> If you would like pursue this issue, please provide:
> 
 * rsyslog version: 8.15 (even older than @davidelang supposed)
 * platform: Debian 8

As @davidelang wrote - it is related to question whether two actions can write to the same file. If not on that archaic rsyslog - was it implemented in versions later?

**Comment by rgerhards** [comment]
> two actions writing to the same file? I would also have assumed that this is a problem

It's not a problem for regular files. It doesn't work well for compressed or encrypted files.

For the issue here, I think 8.15 is just a version with a bug that mixes lines together. I remember having something like this fixed years ago.

@skupkosk 
The version you are using is very old and no longer supported by the community. It is also very probable that the problem stems back to long-solved issues. As such, please update to the currently supported version and retry. Report back if the problem persists.

The rsyslog project provides packages for current versions: https://www.rsyslog.com/downloads/download-other/

If you insist on using an outdated version, you can also contact your distro or consider [rsyslog professional services](https://www.rsyslog.com/professional-services/enterprise-support/).

**Comment by skupkosk** [comment]
@rgerhards thank you for quick and helpful answer. It is nice to read the rsyslog support multi-threading writes to files.
ATM we are upgrading our syslog infrastructure. Decided to use the official Debian distribution packages available in current stable release. Will report back once the problem will persist on new versions.

**Wish peaceful Christmas holidays to all.**

**Comment by davidelang** [comment]
even the official debian is going to be old compared to what the rsyslog 
community can support (although not as ancient as 8.15), this is a common distro 
problem, not specific to any one distro.

David Lang
