### ISSUE TITLE
omfwd SetInstrParamDefaults not called

### ISSUE THREAD

**Issue by alorbach** [rsyslog/rsyslog#4060]
While working on another issue, I was woundering why the default values are not used in omfwd

It is only done in  newActInst here: 
https://github.com/rsyslog/rsyslog/blob/c7b5979752d182533424c1484660d0696bafb06c/tools/omfwd.c#L1167

However in parseSelectorAct, setInstParamDefaults is not called to init the pData 
https://github.com/rsyslog/rsyslog/blob/c7b5979752d182533424c1484660d0696bafb06c/tools/omfwd.c#L1361

Is this done by intention?

**Comment by rgerhards** [comment]
I don't think so, this looks like a bug.

**Comment by rgerhards** [comment]
mhhh... as you say, it *is actually called* in `parseSelectorAct`, so I do not see your point here. Can you pls elaborate?

**Comment by alorbach** [comment]
issue solved, understanding issue on my side ;)
