### ISSUE TITLE
Error: omfwd: error 1 sending via udp: Operation not permitted

### ISSUE THREAD

**Issue by annh-dev** [rsyslog/rsyslog#4062]
I have a solution for centralizing system logs with rsyslog and Graylog but am having an error connecting to UDP, Information in documents and on the internet does not mention much about this error. 

I have built a DirectAdmin server and managed the website on it and I also need to manage logs via gui (so I chose Graylog) the perfect setup process until the UDP error came from rsyslogd

===Steps to reproduce the behavior:

chmod -R +r /var/log/DirectAdmin:

Create file name da.conf in /etc/rsyslog.d/:

$ModLoad imfile
$InputFilePollInterval 10
$InputFileName /var/log/directadmin/error.log
$InputFileName /var/log/directadmin/errortaskq.log
$InputFileName /var/log/directadmin/system.log
$InputFileName /var/log/directadmin/csf_install.log
$InputFileName /var/log/httpd/error_log
$InputFileName /var/log/httpd/access_log
$InputFileName /var/log/messages
$InputFileName /var/log/exim/mainlog
$InputFileName /var/log/exim/rejectlog
$InputFileName /var/log/cron
$InputFileTag da
$InputFileFacility local6
$InputRunFileMonitor

![image](https://user-images.githubusercontent.com/59111676/71305990-a8007b00-240d-11ea-86cd-9eaa7bf123e3.png)

Make confiig: /etc/rsyslog.conf:

local6.*                                                @my-ip-graylog-server

*.* @my-ip-graylog-server:port;RSYSLOG_SyslogProtocol23Format

Save file and restart rsyslog, i get this error: 

omfwd: error 1 sending via udp: Operation not permitted

![image](https://user-images.githubusercontent.com/59111676/71306038-147b7a00-240e-11ea-8934-dc4b74399842.png)

Hope too see any idea to fix this problem

Best regards

### Environment
- rsyslog version: 
- platform: 
- for configuration questions/issues, include rsyslog.conf and included config files

**Comment by rgerhards** [comment]
Version?

**Comment by annh-dev** [comment]
> Version?

rsyslogd 8.24.0-41.el7_7.2 - CentOS 7

**Comment by rgerhards** [comment]
The version you are using is very old and no longer supported by the community. It is also very probable that the problem stems back to long-solved issues. As such, please update to the currently supported version and retry. Report back if the problem persists.

The rsyslog project provides packages for current versions: https://www.rsyslog.com/downloads/download-other/

If you insist on using an outdated version, you can also contact your distro or consider [rsyslog professional services](https://www.rsyslog.com/professional-services/enterprise-support/).

**Comment by annh-dev** [comment]
Dear rgerhards,

Thanks for your feedback, I have updated the version for rsyslog, restarted the service and a few other problem have been shown. 

rsyslogd -v : rsyslogd  8.1911.0 (aka 2019.11)

![image](https://user-images.githubusercontent.com/59111676/71306944-02073d80-241a-11ea-90d2-3eaae259c1a0.png)

Error:

omfwd/udp: socket 19: sendto() error: Operation not permitted
omfwd: socket 19: error 1 sending via udp: Operation not permitted

![image](https://user-images.githubusercontent.com/59111676/71306941-f87dd580-2419-11ea-8b8e-68ccfd1663b9.png)

Any idea, thanks

**Comment by rgerhards** [comment]
This is a bit strange.

Please create a debug log. Instructions: https://www.rsyslog.com/doc/v8-stable/troubleshooting/howtodebug.html

Be sure that the problem in question occurs at least once during the debug run. Once this is done, please post the debug log (e.g. via pastbin or github). After that, we can review the contents and check how exactly rsyslog processing worked.

**Comment by annh-dev** [comment]
Yes, I have sent screenshot below:

![image](https://user-images.githubusercontent.com/59111676/71307213-a0e16900-241d-11ea-8ea2-a26ba9b8bc5b.png)

**Comment by rgerhards** [comment]
I need the debug log.

**Comment by annh-dev** [comment]
I added it to my repo, do not know that you could view them. Thanks

https://github.com/annh-dev/Rsyslogd/blob/master/rsyslog.debug

Best regards

**Comment by annh-dev** [comment]
Dear @rgerhards , any update for this issue ?

**Comment by rgerhards** [comment]
Interestingly, there is no additional information in the debug log, so no extra info on why the OS does not permit sending. Looking at google search results (https://www.google.com/search?q=udp+sendto+operation+not+permitted&rlz=1C1GCEU_deDE823DE823&oq=udp+sendto+operation+&aqs=chrome.1.69i57j0l2.3471j0j7&sourceid=chrome&ie=UTF-8 ) it looks like iptable is involved, connection tracking in specific.

Possibly this post is helpful:
https://stackoverflow.com/questions/23859164/linux-udp-socket-sendto-operation-not-permitted

From the rsyslog PoV there is nothing we can do - the OS does not permit sending, and we do not know any more than that. You could also look into SELinux, maybe.

**Comment by davidelang** [comment]
I believe that SELinux can also block probram from being able to send messages.

David Lang

**Comment by annh-dev** [comment]
Dear @davidelang , I make sure that i have disable selinux and csf firewall

**Comment by annh-dev** [comment]
Dear @rgerhards  @davidelang , vấn đề đã được giải quyết bởi firewall trên CentOS, thank for support
