### ISSUE TITLE
[question] rtrim/ltrim a variable

### ISSUE THREAD

**Issue by lmayorga1980** [rsyslog/rsyslog#4076]
The `$!usr!uname` variable is set correctly but the unameparsed is getting a value of `0`. 

```
 set $!usr!uname = field($msg, 124, 4);
  set $!usr!unameparsed = ltrim($!usr!uname);
```
I wonder if the following is supported...

```
  set $!usr!unameparsed = rtrim(ltrim(field($msg, 124, 4)));

```

**Comment by rgerhards** [comment]
> I wonder if the following is supported...
> 
> ```
>   set $!usr!unameparsed = rtrim(ltrim(field($msg, 124, 4)));
> ```

yes, of course. Expressions can be as complex as necessary

**Comment by lmayorga1980** [comment]
I was not working from me. I will post some of the details of the current rsyslog version and os with a simple example. 

Was not working for me under Ubuntu Xenial.

**Comment by rgerhards** [comment]
> I was not working from me. I will post some of the details of the current rsyslog version and os with a simple example.

pls do

**Comment by lmayorga1980** [comment]
Sample Data from https://confluence.atlassian.com/bitbucketserverkb/how-to-read-the-bitbucket-server-log-formats-779171668.html

```


172.24.12.153 | https | i@PZQFBCx921x19253x0 | - | 2015-09-09 15:21:08,431 | "GET /status HTTP/1.1" | "" "" | - | - | - | - | - | 1irez8i |
172.24.12.153 | https | o@PZQFBCx921x19253x0 | - | 2015-09-09 15:21:08,437 | "GET /status HTTP/1.1" | "" "" | 200 | 0 | 19 | - | 6 | 1irez8i |
172.24.12.146 | https | i*1Y8NA7Ox764x406x0 | - | 2015-09-10 12:44:32,515 | "GET /status HTTP/1.1" | "" "" | - | - | - | - | - | 1hpn738 |
172.24.12.146 | https | o*1Y8NA7Ox764x406x0 | - | 2015-09-10 12:44:32,523 | "GET /status HTTP/1.1" | "" "" | 200 | 0 | 19 | - | 7 | 1hpn738 |
172.24.36.105 | ssh | o*N65BDNx354x326903x0 | username | 2015-03-02 05:54:25,425 | SSH - git-upload-pack '/foo/bar.git' | - | 0 | 123 | 1024 | cache:miss, refs, ssh:id:610, ssh:label:'sshek@atlassian.com' | 1cl58rd |
172.24.36.105 | ssh | i*N65BDNx354x326907x0 | bamboo_user | 2015-03-02 05:54:25,733 | SSH - git-upload-pack '/bar/support-tools-base.git' | "SSH-2.0-OpenSSH_7.2p2 Ubuntu-4ubuntu2.1" | - | - | y3r3kf |
172.24.36.105 | ssh | o*N65BDNx354x326907x0 | bamboo_user | 2015-03-02 05:54:25,802 | SSH - git-upload-pack '/bar/support-tools-base.git' | "SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.3" | 0 | 101 | 4398 | cache:miss, refs, ssh:id:2754, ssh:label:'https://ecosystem-bamboo.internal.atlassian.com' | 69 | y3r3kf |
```

I am using the `field` function in order to split the message using the `|` symbol

`set $!usr!uname = field($msg, 124, 4)` This line will get me the 4th column but it has an extra space at the beginning and at the end of the string.

So far, the thing is working for me is `set $!usr!unmeparsed = replace($!usr!uname, " ", "")` but using `set $!usr!uname = ltrim(rtrim(field($msg, 124, 4)))` is not working for me

**Comment by rgerhards** [comment]
Rsyslog version?

**Comment by lmayorga1980** [comment]
rsyslogd `8.1911.0 (aka 2019.11)`

**Comment by rgerhards** [comment]
I did a quick check by modifying the `rscript_trim` testbench test and added this:
`set $!str!c1 = ltrim(rtrim(field("172.24.12.153 | https | i@PZQFBCx921x19253x0 | - | 2015-09-09 15:21:08,431 ", 124, 4)));`
This works correctly. So the problem must be somewhere either in your config or actual input data.

Please create a debug log. Instructions: https://www.rsyslog.com/doc/v8-stable/troubleshooting/howtodebug.html

Be sure that the problem in question occurs at least once during the debug run. Once this is done, please post the debug log (e.g. via pastbin or github). After that, we can review the contents and check how exactly rsyslog processing worked.
