### ISSUE TITLE
"Username" property/placeholder?

### ISSUE THREAD

**Issue by sburkett** [rsyslog/rsyslog#4082]
This is more of a question than an issue, per se. I searched past issues here, as well as the web but didn't seem to find an answer anywhere. Hopefully someone here might have some insights.

I have a bunch of sftp users that I need to log sftp transfers for. I have it set up and working, but unfortunately, it seems I have to add configuration lines such as the following for each user:

```
$AddUnixListenSocket /home/joe/dev/log
$AddUnixListenSocket /home/susie/dev/log
$AddUnixListenSocket /home/bob/dev/log
...
```

Is there some way to just use some sort of username property to just have a single line? In others, replacing "joe", "susie", etc. with the authenticated user's username? Something like:

```
$AddUnixListenSocket /home/%USERNAME%/dev/log
```

Thanks in advance for any insights or guidance!

**Comment by davidelang** [comment]
unfortunantly the variables only exist for the duration of processing a log 
message, while the socket setup happens once at startup (not during the 
processing of any message)


I have proposed adding an API to allo for additional inputs to be added after 
setup (specifically to be able to handle things like you are doing) but this has 
mot made it high enough on the to-do list and nobody has been willing to sponsor 
the development of this feature.
Rainer will be getting online in a few hours and may have some additional ideas 
(contact adsicon if you are in a position to sponsor the development of this 
feature)

David Lang

**Comment by sburkett** [comment]
Thanks for the quick reply! I poked around but didn't see your proposal (perhaps it was done out-of-band from GitHub?).  At any rate, I suppose for now we can just script up a separate file in `/etc/rsyslog.d` to contain all of the necessary line for each user. Of course, one issue which will invariably arise is the co-mingling of session data within the log file. Obviously having separate log files for each user isn't terribly scalable, unless they are only open for writing in an on-demand scenario.

I could write something that parses the `PID` from the log when the sftp session is initially opened, and then search for all other lines matching that, but that seems to be less than ideal. I'll fiddle with things to see how I fare with it.

I might be interested in sponsoring the feature, provided I can get some sort of estimated scope of effort and associated cost.

Cheers.

**Comment by davidelang** [comment]
look at what the $input value is for logs from each source, you may be able to 
add that to the log message to be able to fileter on it later.

I think my initial proposal pre-dates our use of github, contct adiscon 
https://www.rsyslog.com/contact-us/ and Rainer can work up an estimate.

David Lang
