### ISSUE TITLE
omfwd and PermitExpiredCerts

### ISSUE THREAD

**Issue by phr0gz** [rsyslog/rsyslog#4098]
### Expected behavior
Controls how expired certificates will be handled when stream driver is in TLS mode.
It seems a future rsyslog update will change the default value from "warn" to "no", so I want to set it explicitly to "warn".

### Actual behavior
```error during parsing file /etc/rsyslog.d/test-syslog.conf, on or before line 59: parameter 'StreamDriver.PermitExpiredCerts' not known -- typo in config file? [v8.1911.0 try https://www.rsyslog.com/e/2207 ]```

### Steps to reproduce the behavior
As described in the doc https://www.rsyslog.com/doc/v8-stable/configuration/modules/omfwd.html

1/ Add the following parameter for the omfwd module:
StreamDriver.PermitExpiredCerts="warn"

2/ Start rsyslog

### Environment
- rsyslog version: v8.1911.0
- platform: RHEL 7
omfwd part in the config file:
```RuleSet (name="remote_tcp_secure_6514")
{
        action(
          type="omfwd"
          name="SendToSyslogFrom514"
          target="test.somedomain.lan"
          port="6514"
          protocol="tcp"
          StreamDriverMode="1"
          StreamDriver="gtls"
          StreamDriverAuthMode="x509/name"
          StreamDriver.PermitExpiredCerts="warn"
          StreamDriverPermittedPeers="test.somedomain.lan"
          action.resumeRetryCount="-1"
          queue.type="linkedList"
          queue.filename="ToSyslog1"
          queue.spoolDirectory="/apps/rsyslog/spool"
          queue.maxDiskSpace="80g"
          queue.saveOnShutdown="on"
          queue.dequeuebatchsize="2000"
          RebindInterval="1000"
          queue.workerthreads="4"
          queue.highwatermark="500000"
          queue.lowwatermark="100000"
          template="SyslogSource"
          queue.size="10000000000"
          action.reportSuspension="on"
          action.reportSuspensionContinuation="on"
        )
}
```

Thanks,
L.

**Comment by rgerhards** [comment]
this is more than strange - The parameter is checked in CI.

Please create a debug log. Instructions: https://www.rsyslog.com/doc/v8-stable/troubleshooting/howtodebug.html

Be sure that the problem in question occurs at least once during the debug run. Once this is done, please post the debug log (e.g. via pastbin or github). After that, we can review the contents and check how exactly rsyslog processing worked.

**Comment by phr0gz** [comment]
I quickly created a fresh rsyslog server on CentOS 7 using the repo: rpms.adiscon.com.

Here is the test config:
```
$MaxMessageSize 64k
global(
  defaultNetstreamDriver="gtls"
  #debug.gnutls="10"
  #TCP TLS
  defaultNetstreamDriverCAFile="/root/test/GeoTrust_Primary_CA.pem"
)
module(load="imptcp")

template(name="SyslogSource" type="string"
         string="<%pri%>%timestamp:::date-rfc3339% %hostname% %fromhost-ip% %syslogtag% %msg%\n"
        )

/* Input entries */

input(type="imptcp" port="514" ruleset="remote_tcp_secure_6514")

/* Remote Logging */

RuleSet (name="remote_tcp_secure_6514")
{
        action(
          type="omfwd"
          name="SendToSyslogFrom514"
          target="test.somedomain.lan"
          port="6514"
          protocol="tcp"
          StreamDriverMode="1"
          StreamDriver="gtls"
          StreamDriverAuthMode="x509/name"
          StreamDriver.PermitExpiredCerts="warn"
          StreamDriverPermittedPeers="test.somedomain.lan"
        )
}
```

And the link to pastebin for the debug log: https://pastebin.com/dSHr2tB9

**Comment by rgerhards** [comment]
sry, I overlooked an important detail: `streamDriverAuthMode` is a **module** parameter, so you must set it in the `load()` object. It currently applies to all listeners being defined.

doc: https://www.rsyslog.com/doc/v8-stable/configuration/modules/imtcp.html

**Comment by rgerhards** [comment]
and my bad again... - I just came accross this while working on CI, but your's in `omfwd`. Let me check...

**Comment by rgerhards** [comment]
It looks like there is indeed a bug in the parameter description table... I think I somehow had always read "AuthMode"...

**Comment by rgerhards** [comment]
@alorbach can you pls have a look - don't we have any tests for this?

**Comment by rgerhards** [comment]
I already checked - there are not tests :-( will see that I get this done very soon.

**Comment by phr0gz** [comment]
Many thanks!
