### ISSUE TITLE
Crash on joining threads

### ISSUE THREAD

**Issue by jvymazal** [rsyslog/rsyslog#4099]
### Expected behavior
no crash
### Actual behavior
after some time rsyslog crashes one way of another, still determining exact code path and whether it is rsyslog core or actually libfastjson problem
### Steps to reproduce the behavior
- set both journald and imjournal ratelimiting off (0 for both interval and burst)
- restart journald
- configure 3 omfwd actions with no other output (dummy targets suffice), example below
- start a busy loop feding messages to logger
- wait for crash (sometimes it can take long time, hour or more)

### Environment
- rsyslog version:8.1911.0 
- platform:fedora 
- for configuration questions/issues, include rsyslog.conf and included config files
```
module(load="imjournal"
        StateFile="imjournal.state"
        Ratelimit.Interval="0"
        Ratelimit.Burst="0")

$ActionQueueType LinkedList
$ActionQueueFileName fwd1
$ActionResumeRetryCount -1
$ActionQueueSaveOnShutdown on
*.*        @@dummy-host.org:10514

$ActionQueueType LinkedList
$ActionQueueFileName fwd1
$ActionResumeRetryCount -1
$ActionQueueSaveOnShutdown on
*.*        @@dummy-host.org:10515

$ActionQueueType LinkedList
$ActionQueueFileName fwd1
$ActionResumeRetryCount -1
$ActionQueueSaveOnShutdown on
*.*        @@dummy-host.org:10516
```

**Comment by jvymazal** [comment]
@rgerhards, so far this looks like crash at msgSerialize when two threads meet there at json serialization and then try to extend the same printbuf two times at once.

As for solution I might try adding another mutex which would lock the json of the message, however I wanted to first ask whether it would be possible to guard whole message object on serialization which seems simpler approach, however I have no idea of performance impact of such lock. ideas?

**Comment by rgerhards** [comment]
have a look here https://github.com/rsyslog/rsyslog/pull/4042

**Comment by jvymazal** [comment]
great, thank you, this should work, will verify that the with that commit fixes it and will close is if it does.

**Comment by jvymazal** [comment]
First testing results look good, seems that the linked patch works.
