### ISSUE TITLE
How to use dynamic topic name while processing the data. 

### ISSUE THREAD

**Issue by sathishkgit** [rsyslog/rsyslog#4101]
Input data:

**Sample 1:**

DATATYPE::SERVICEPERFDATA	TIMET::1578464605	HOSTNAME::139 Campaign Manager	SERVICEDESC::Basic_Service_Disk	SERVICEPERFDATA::/=15384MB;51172;51170;0;51175 /home=1558MB;93255;93253;0;93258 /boot=206MB;1011;1009;0;1014	SERVICECHECKCOMMAND::disk	HOSTSTATE::UP	HOSTSTATETYPE::HARD	SERVICESTATE::OK SERVICESTATETYPE::HARD

**Sample 2**

DATATYPE::SERVICEPERFDATA	TIMET::1578464584	HOSTNAME::130Campaign Manager	SERVICEDESC::check_traffic	SERVICEPERFDATA::eth0-rx-kbit/s=0, eth0-tx-kbit/s=0, eth1-rx-kbit/s=0, eth1-tx-kbit/s=0, eth2-rx-kbit/s=0, eth2-tx-kbit/s=0, eth3-rx-kbit/s=0, eth3-tx-kbit/s=0, lo-rx-kbit/s=0, lo-tx-kbit/s=0,	SERVICECHECKCOMMAND::check_traffic	HOSTSTATE::UP	HOSTSTATETYPE::HARD	SERVICESTATE::OK	SERVICESTATETYPE::HARD

I will use rulebase to filter my service_name as "Basic_Service_Disk" or "check_traffic" from above sample data. 

My ruleset is as below, currently i am hard coding the topic name. Instead I would like to pass the topic name dynamically as my service name with some prefix like e.g "Site1_Basic_Service_Disk" and "Site1_check_traffic". Ideally each message will have the service name and the same has to go to the corresponding topic.

How to achieve this? 
```
ruleset(name="host") {
     #action(type="mmfields" separator=" ")
     action(type="mmnormalize" rulebase="/home/rsyslog/hosts.rb")
     action(broker=["X.X.X.X:9092"]
            type="omkafka"
            topic="hosts"
            key="mmnorm"
            dynaKey="on"
            template="host"
            partitions.auto="on"
            #partitions.number="4"
            errorFile="/home/rsyslog/kafka_error.log"
            )stop
        }
```

**Comment by davidelang** [comment]
what you need to do is to extract what you want to be the topic into a variable 
(mmnormalize is what I would first reach for to do that), then you will have a 
variable that you can use in the dynatype parameter.

David Lang

**Comment by sathishkgit** [comment]
@davidelang thanks for your suggestion. But i want to do some conditional check on each message, for example if my variable name is "test", then the message would go to "test" topic. Because the variable name which will extracted using mmnormalize will be different for each message. 

Please suggest.

**Comment by davidelang** [comment]
On Tue, 7 Jan 2020, sathishkgit wrote:

> @davidelang thanks for your suggestion. But i want to do some conditional 
> check on each message, for example if my variable name is "test", then the 
> message would go to "test" topic. Because the variable name which will 
> extracted using mmnormalize will be different for each message.

I'd need examples to give examples, but there's  good chance that mmnormalize 
can be used to do this.

once you have something in a variable, you can do all sorts of tests against it 
and set another variable

or

it may be possible to have mmnormalize extract your constant value into a 
variable, and so you just have lots of patterns, one (or more) for each topic 
you want to use.

or

again with lots of patterns for mmnormalize, you can set a label and use that as 
your variable.

David Lang

**Comment by sathishkgit** [comment]
thanks @davidelang 

I am able to do it with below configuration. 

template(name="mmnorm-service" type="list"){
        constant(value="Site1_")
        property(name="$!servicename")
}

template(name="mmnorm-key" type="list"){
        constant(value="")
        property(name="$!hostnamevalue")
}


ruleset(name="services") {
     action(type="mmnormalize" rulebase="/home/rsyslog/services.rb")
     action(broker=["x.x.x.x:9092"]
            template="test"
            type="omkafka"
            dynatopic="on"
            topic="mmnorm-service"
            key="mmnorm-key"
            dynaKey="on"
            partitions.auto="on"
           errorFile="/home/rsyslog/kafka_error.log"
           )stop
       }
