### ISSUE TITLE
test-suite failes with 8.2001.0

### ISSUE THREAD

**Issue by mbiebl** [rsyslog/rsyslog#4120]
Version: 8.2001.0
Debian sid

Trying to build the latest version of rsyslog for Debian, I get

```
PASS: immark.sh
... [SNIPPED by admin for easier readability]
SKIP: imfile-logrotate-nocopytruncate.sh
FAIL: imfile-growing-file-id.sh
PASS: glbl-oversizeMsg-truncate-imfile.sh
PASS: config_enabled-on.sh
PASS: config_enabled-off.sh
PASS: imfile-endmsg.regex-with-example.sh
make[6]: Entering directory '/home/test/rsyslog-8.2001.0/tests'
make[6]: Nothing to be done for 'imfile-escapelf.replacement.log'.
make[6]: Nothing to be done for 'imfile-escapelf.replacement-empty.log'.
make[6]: Leaving directory '/home/test/rsyslog-8.2001.0/tests'
fatal: making test-suite.log: failed to create imfile-escapelf.replacement.trs
fatal: making test-suite.log: failed to create imfile-escapelf.replacement.log
fatal: making test-suite.log: failed to create imfile-escapelf.replacement-empty.trs
fatal: making test-suite.log: failed to create imfile-escapelf.replacement-empty.log
make[5]: *** [Makefile:3414: test-suite.log] Error 1
```

**Comment by mbiebl** [comment]
Multiple issues here
- `make check` doesn't complete and doesn't produce a summary and test-suite.log
- imfile-growing-file-id.sh fails
- imfile-statefile-no-file_id-TO-file_id.sh

The problem is reproducible, so I'm happy to run further diagnostics

**Comment by mbiebl** [comment]
Fortunately, individual log files have been written.
[imfile-growing-file-id.log](https://github.com/rsyslog/rsyslog/files/4061664/imfile-growing-file-id.log)
[imfile-statefile-no-file_id-TO-file_id.log](https://github.com/rsyslog/rsyslog/files/4061665/imfile-statefile-no-file_id-TO-file_id.log)

**Comment by mbiebl** [comment]
I'm running `make check -j1` as unprivileged user.

**Comment by mbiebl** [comment]
git bisect points at ac30968b7858d4ca3743d2b4d296eca543864fe2 as the first faulty commit
```
commit ac30968b7858d4ca3743d2b4d296eca543864fe2 (HEAD, refs/bisect/bad)
Author: Jiri Vymazal <jvymazal@redhat.com>
Date:   Fri Nov 22 14:25:59 2019 +0100

    Thorougher state-file renaming and cleaning
    
    Now checking if file-id changes and reanming - cleaning state file
    accordingly and always checking and cleaning old inode-only style
    state files.
```

Reverting that commit makes the test-suite pass again.

/cc @jvymazal

**Comment by rgerhards** [comment]
@mbiebl @jvymazal it looks like I made a mistake: we introduced `--enable-imfile-tests` with a default of **no**. I guess this should really have been **yes**. At least I did not update the CI system to actually enable this. As far as I can see ATM, CI didn't run any imfile-related tests since then (whenever that was, did not yet look up).

The test fails in my local environment as well.

@jvymazal I would appreciate if you could have a look.

**Comment by rgerhards** [comment]
@jvymazal TSAN brings also something up, I guess it is related: https://build.rsyslog.com/#/builders/72/builds/2771/steps/6/logs/test-suite_log

**Comment by mbiebl** [comment]
Any news? Should I just disable the test-suite or is this test-suite failure pointing at a real problem and I should hold back with the update in Debian?

**Comment by rgerhards** [comment]
I hope that @jvymazal has some time to look into this. At worst, I'll revert the commit, but would like to give a couple of more days.

I think there is a real problem at the root, albeit I do not yet have any reports from our users. It might not be a bad idea to hold back the release in Debian, though.

**Comment by jvymazal** [comment]
I am sorry for delay, sometimes github notifications get snowed under different work, feel free to re-mention me if there is no reply for a few days.

So current status is that with `[ac3096](https://github.com/rsyslog/rsyslog/commit/ac30968b7858d4ca3743d2b4d296eca543864fe2)` some imfile tests started failing?

**Comment by mbiebl** [comment]
> So current status is that with [`ac3096`](https://github.com/rsyslog/rsyslog/commit/ac30968b7858d4ca3743d2b4d296eca543864fe2) some imfile tests started failing?

Correct. Specifically for me it is imfile-growing-file-id.sh and imfile-statefile-no-file_id-TO-file_id.sh.
You can find log files at https://github.com/rsyslog/rsyslog/issues/4120#issuecomment-574384214

You need to build rsyslog with `--enable-imfile-tests`

**Comment by mbiebl** [comment]
Thank you @jvymazal 
I can confirm that cherry-picking 2ff1e7a73d727b457e6f91698b50d97502e2e66d fixes the failures with imfile-growing-file-id.sh and imfile-statefile-no-file_id-TO-file_id.sh.

The test-suite still doesn't successfully complete though. Will file a separate issue for that.
