### ISSUE TITLE
error in regex

### ISSUE THREAD

**Issue by aminbaik** [rsyslog/rsyslog#4121]
### Environment
- rsyslog version: 
- platform: 
- for configuration questions/issues, include rsyslog.conf and included config files

**Comment by aminbaik** [comment]
Hello, 
I want to log all rysylog I configure and everything is fine.
I create a new template that is:
`template(name="stdSQLformat" type="string" option.sql="on" 
string="insert into SystemEvents (Message, Message2, Facility, FromHost, Priority, DeviceReportedTime, ReceivedAt, InfoUnitID, SysLogTag) values ('%msg%','%msg:R,ERE,0,DFLT,1:([0-9]+\.){3}[0-9]+[:]?([0-9]+)?"--end%', %syslogfacility%, '%HOSTNAME%', %syslogpriority%, '%timereported:::date-mysql%', '%timegenerated:::date-mysql%', %iut%, '%syslogtag%')")`

but when I run rsyslog I get:
` error during parsing file /etc/rsyslog.d/mysql.conf, on or before line 8: invalid character '"' in object definit`

I know that the problem is with  
`%msg:R,ERE,0,DFLT,1:([0-9]+\.){3}[0-9]+[:]?([0-9]+)?"--end%`
but I don't understand what I have to do !
thanks.

**Comment by rgerhards** [comment]
pls add - these info request is there for a reason ;-)

* rsyslog version:
* platform:
* for configuration questions/issues, include rsyslog.conf and included config files

**Comment by aminbaik** [comment]
Hello,
mysql.conf
`module (load="ommysql")
template(name="stdSQLformat" type="string" option.sql="on" 
string="insert into SystemEvents (Message, Message2, Facility, FromHost, Priority, DeviceReportedTime, ReceivedAt, InfoUnitID, SysLogTag) values ('%msg%','%msg:R,ERE,0,DFLT,1:([0-9]+\.){3}[0-9]+[:]?([0-9]+)?--end%', '%syslogfacility%', '%HOSTNAME%', '%syslogpriority%', '%timereported:::date-mysql%', '%timegenerated:::date-mysql%', '%iut%', '%syslogtag%')")

$
 *.* :ommysql:127.0.0.1,Syslog,rsyslog,password;stdSQLformat

`

rsyslog.conf
`module(load="imuxsock") # provides support for local system logging
#module(load="immark")  # provides --MARK-- message capability
#module(load="ommysql")
# provides UDP syslog reception
module(load="imudp")
input(type="imudp" port="514")

# provides TCP syslog reception
#module(load="imtcp")
#input(type="imtcp" port="514")

# provides kernel logging support and enable non-kernel klog messages
module(load="imklog" permitnonkernelfacility="on")

###########################
#### GLOBAL DIRECTIVES ####
###########################

#
# Use traditional timestamp format.
# To enable high precision timestamps, comment out the following line.
#
$ActionFileDefaultTemplate RSYSLOG_TraditionalFileFormat

# Filter duplicated messages
$RepeatedMsgReduction on

#
# Set the default permissions for all log files.
#
$FileOwner syslog
$FileGroup adm
$FileCreateMode 0640
$DirCreateMode 0755
$Umask 0022
$PrivDropToUser syslog
$PrivDropToGroup syslog

#
# Where to place spool and state files
#
$WorkDirectory /var/spool/rsyslog

#
# Include all config files in /etc/rsyslog.d/
#
$IncludeConfig /etc/rsyslog.d/*.conf

`

rsyslog version:
`rsyslogd 8.32.0, compiled with:
        PLATFORM:                               x86_64-pc-linux-gnu
        PLATFORM (lsb_release -d):
        FEATURE_REGEXP:                         Yes
        GSSAPI Kerberos 5 support:              Yes
        FEATURE_DEBUG (debug build, slow code): No
        32bit Atomic operations supported:      Yes
        64bit Atomic operations supported:      Yes
        memory allocator:                       system default
        Runtime Instrumentation (slow code):    No
        uuid support:                           Yes
        systemd support:                        Yes
        Number of Bits in RainerScript integers: 64
`

**Comment by rgerhards** [comment]
the config is only partial; most importantly the parts that cause the problems are missing. We can't help you without all info.

**Comment by aminbaik** [comment]
hello, this all configurations that I put it  ! all config in rsyslog.con and mysql.conf
thanks.

**Comment by davidelang** [comment]
we need all the configs that rsyslog sees. We are not familiar with all the 
default configuratons that the different distros ship, so if you want us to be 
able to help you, we need to see everything.

David Lang

**Comment by rgerhards** [comment]
my bad ... I actually overlooked that part of the config. There is a quote character (") within the regex. This needs to be escape with a backslash in front (`\"`).

**Comment by rgerhards** [comment]
more precisely, here it is: `"--end`. That quote terminates the rsyslog string object. Consequently, rsyslog complains about the "garbage" following.

You need to change it to `\"--end`.
