### ISSUE TITLE
omelasticsearch failure parsing elasticsearch reply in  8.2001.0 

### ISSUE THREAD

**Issue by iashwash** [rsyslog/rsyslog#4127]
### Expected behavior
omelasticsearch can parse an elasticsearch response from a bulkmode insert

### Actual behavior
After rsyslog was upgraded to 8.2001.0, omelasticsearch fails to parse valid reply that includes "items"
```
2020-01-15T20:54:10.461319+00:00 our-hostname rsyslogd: omelasticsearch: error in elasticsearch reply: bulkmode insert does not return array, reply is: 1579121650 20:54:10 elk-production green 8 4 550 275 0 0 0 0 - 100.0% {"took":10,"errors":false,"items":[{"index":{"_index":"rsyslog-2020.01.15","_type":"rsyslog","_id":"TpX8qm8BhsTOmI8LK9EE","_version":1,"result":"created","_shards":{"total":2,"successful":2,"failed":0},"_seq_no":43071185,"_primary_term":1,"status":201}}]} [v8.200
1.0 try https://www.rsyslog.com/e/2218 ]
```
### Steps to reproduce the behavior

I am not too sure. I think it has to do with logic in this PR: https://github.com/rsyslog/rsyslog/pull/4073

But basically increasing the buffer and then trying to send messages smaller than that increase. The problem persists after restart of rsyslogd, but maybe that's just due to the volume of messages in our buffer.

### Environment
- rsyslog version: 8.2001.0 (aka 2020.01) 
- platform: Ubuntu 18.04

Note: we are running Ubuntu 18.04 hosts that still have rsyslogd  `8.1911.0 (aka 2019.11)` which aren't experiencing issues to the same elasticsearch cluster.

On hosts experiencing this error, I do not see any logged allocation errors `"realloc failed in curlResult"` in the log history.

**Comment by rgerhards** [comment]
Please create a debug log. Instructions: https://www.rsyslog.com/doc/v8-stable/troubleshooting/howtodebug.html

Be sure that the problem in question occurs at least once during the debug run. Once this is done, please post the debug log (e.g. via pastbin or github). After that, we can review the contents and check how exactly rsyslog processing worked.

**Comment by iashwash** [comment]
Sorry for the delay on this, wanted to set-up a simpler environment to grab the debug log from. You can grab it from this gist, just remove REMOVETHISPARTOFTHELINK from it (a lazy attempt against scraping):
https://gist.github.com/iashwash/7bb39ca54REMOVETHISPARTOFTHELINKc505baf6b20f934785bd9a7

**Comment by andreaf74** [comment]
Hello,

same problem here, after upgrade to 8.2004.
Versions before 8.2001 didn't show to problem.

Thanks

**Comment by julthomas** [comment]
Hello,

By any chance, you wouldn't have more  than one ES server defined in your action?

I wonder if that patch would fix it because checkConn() gets passed the same pWrkrData context and will play with reply and replyLen through curl write function curlResult(). So I believe the result of the health check will still be in the reply buffer, before the result of the actual POST.

```
diff --git a/plugins/omelasticsearch/omelasticsearch.c b/plugins/omelasticsearch/omelasticsearch.c
index 55c6f9994..b94d7860c 100644
--- a/plugins/omelasticsearch/omelasticsearch.c
+++ b/plugins/omelasticsearch/omelasticsearch.c
@@ -1564,7 +1564,6 @@ curlPost(wrkrInstanceData_t *pWrkrData, uchar *message, int msglen, uchar **tpls
 
        PTR_ASSERT_SET_TYPE(pWrkrData, WRKR_DATA_TYPE_ES);
 
-       pWrkrData->replyLen = 0;
        if ((pWrkrData->pData->rebindInterval > -1) &&
                (pWrkrData->nOperations > pWrkrData->pData->rebindInterval)) {
                curl_easy_setopt(curl, CURLOPT_FRESH_CONNECT, 1);
@@ -1585,6 +1584,7 @@ curlPost(wrkrInstanceData_t *pWrkrData, uchar *message, int msglen, uchar **tpls
                /* needs to be called to support ES HA feature */
                CHKiRet(checkConn(pWrkrData));
        }
+       pWrkrData->replyLen = 0;
        CHKiRet(setPostURL(pWrkrData, tpls));
 
        curl_easy_setopt(curl, CURLOPT_POSTFIELDS, (char *)message);
```

**Comment by yacn** [comment]
we can confirm that the patch @julthomas proposed has fixed it for us -- we're running the latest version of the package in 18.04 without issue.

**Comment by iashwash** [comment]
Confirmed the issue is resolved. Thank you!
