### ISSUE TITLE
8.2001.0-2 package is not signed

### ISSUE THREAD

**Issue by barzog** [rsyslog/rsyslog#4138]
As stated in https://github.com/rsyslog/rsyslog/issues/4122 latest rsyslog centos7 package does not contain valid signature:

rpm -qpi rsyslog-8.2001.0-2.el7.x86_64.rpm | grep Signature
Signature   : (none)

**Comment by rgerhards** [comment]
dup of https://github.com/rsyslog/rsyslog/issues/4122
