### ISSUE TITLE
Unable to use regex to produce shortname

### ISSUE THREAD

**Issue by Sc0th** [rsyslog/rsyslog#4162]
### Expected behavior

Use regex to ensure log file names are shortname rather than FQDN

### Actual behavior

Logs to "**NO MATCH"".log - I would have expected even if my regex is bad to log the hostname(source) as per defined by FIELD

### Steps to reproduce the behavior

$template DynamicFile,"/var/log/syslog/%source:R:ERE,0,FIELD:^([^.]+)\\..*$:--end%.log"
*.*    -?DynamicFile

### Environment
- rsyslog version: 8.2001.0
- platform: CentOS6 (Docker running in k8s)
- for configuration questions/issues, include rsyslog.conf and included config files

```
# rsyslog configuration file

# For more information see /usr/share/doc/rsyslog-*/rsyslog_conf.html
# If you experience problems, see http://www.rsyslog.com/doc/troubleshoot.html

#### MODULES ####

$ModLoad imuxsock # provides support for local system logging (e.g. via logger command)
$ModLoad imklog   # provides kernel logging support (previously done by rklogd)
$ModLoad immark   # provides --MARK-- message capability

#Provides UDP syslog reception
$ModLoad imudp
$UDPServerRun 514

#Provides TCP syslog reception
$ModLoad imtcp
$InputTCPServerRun 514

#### GLOBAL DIRECTIVES ####

$IncludeConfig /etc/rsyslog.d/*.conf

#### RULES ####

$template DynamicFile,"/var/log/syslog/%source:R:ERE,0,FIELD:^([^.]+)\\..*$:--end%.log"
*.*    -?DynamicFile
```

**Comment by rgerhards** [comment]
I guess you want `\..` as part of the regex? As such, you need to escape the backslash (it is inside a constant string) --> `\\..`.

**Comment by Sc0th** [comment]
Just tried with 

$template DynamicFile,"/var/log/syslog/%source:R:ERE,0,FIELD:^([^.]+)\\\..*$:--end%.log"

creates - 

-rw-r--r-- 1 root root 202648 Feb  5 18:12 **NO MATCH**.log

I am stumped.

**Comment by Sc0th** [comment]
And it might be just be but the syslog regex checker here - https://www.rsyslog.com/regex/

does not work at all, sample input:

`property: hostname`
`regex: ^([^.]+)\\..*$`
`submatch: 0`
`nomatch: field`
`sample line: 2020-02-05T18:23:39+08:00 ap-be.mydomain.co.uk (none): [Channel Load] Wireless 2.4G: 6 % / 5G: 1 %`

I would expect the match to be `ap-be` yet it returns nothing (no matter what I try...)

**Comment by rgerhards** [comment]
Maybe there is a problem with parsing into fields - the log line you see in the file is not the original one. The transition to file includes processing and may make things look normal albeit they are not.

In order to see how the message is parsed add to the top of your rsyslog.conf:
```
*.* /var/log/msgfields.log;RSYSLOG_DebugFormat
```
This will create a multi-line entry for each message. Review the file and post an entry in question.

**Comment by Sc0th** [comment]
HI, thanks for looking at this...
Debug line with all properties:

FROMHOST: 'ap-be.mydomain.co.uk', fromhost-ip: '192.168.60.83', HOSTNAME: 'ap-be.mydomain.co.uk', PRI: 158,
syslogtag '(none):', programname: '(none)', APP-NAME: '(none)', PROCID: '-', MSGID: '-',
TIMESTAMP: 'Feb  5 20:09:17', STRUCTURED-DATA: '-',
msg: ' [Channel Load] Wireless 2.4G: 11 % / 5G: 0 %'
escaped msg: ' [Channel Load] Wireless 2.4G: 11 % / 5G: 0 %'
inputname: imudp rawmsg: '<158>Feb  5 20:09:17 (none): [Channel Load] Wireless 2.4G: 11 % / 5G: 0 %'
$!:
$.:
$/:

**Comment by davidelang** [comment]
so in your config, you are doing the rege on "source" that does not seem to be a 
variable that is populated, try doing it on fromhost hostname

David Lang

**Comment by Sc0th** [comment]
Hi,

According to the docs source is an alias for HOSTNAME, however I agree with your point, sadly having tried both I can attest it makes no difference the output is the same (tried with both upper & lowecase)

**Comment by Sc0th** [comment]
Do I take away from this that it cannot be done?

**Comment by rgerhards** [comment]
Well... it for sure can, but I right now have unfortunately no time to dig down why it doesn't work in your case.

Maybe you can create a debug log. Instructions: https://www.rsyslog.com/doc/v8-stable/troubleshooting/howtodebug.html

Be sure that the problem in question occurs at least once during the debug run. Once this is done, please post the debug log (e.g. via pastbin or github). After that, we can review the contents and check how exactly rsyslog processing worked.

I am not 100% sure we can see the cause inside the log. But if we can, we probably have an explanation quickly. Else I need to refer you to the end of the month, at least as far as my time is involved.
