### ISSUE TITLE
PrivDropToUser inconsistent operation

### ISSUE THREAD

**Issue by mkrsfcmp** [rsyslog/rsyslog#4164]
### Expected behavior
Failure to drop privileges due to any reason should end up with failure.

### Actual behavior
In case of user lookup error daemon continues but doesn't drop privileges.

### Steps to reproduce the behavior
Define $PrivDropToUser with non-existent account name.

### Additional info
I understand that the current behaviour is consistent with the documentation and is "not a bug, it's a feature" but I want to point out that it's a bad design. Either remove the username lookup completely and allow user only to be specified by UID (ugly but somehow acceptable) or make the daemon fail in case of user lookup error. Currently the situation where the daemon fails silently and doesn't drop privileges is unacceptable from the security POV. The dropping privileges functionality is designed to make the service less susceptible to privilege escalation in case of service compromise. Making the account run with root user when configured to run as a low-privilege user is a fundamental conceptual flaw. The user should be presented with an error message and should be given an opportunity to correct the underlying cause for user lookup error instead of his configuration being silently ignored and the software ran with much less secure configuration.

**Comment by rgerhards** [comment]
@davidelang I think @mkrsfcmp has a point here. Any objection in making a backwards-incompatible change to make rsyslog abort if it cannot resolve the user name?

**Comment by davidelang** [comment]
I agree it's a security problem, so I think we need to do it.

David Lang

**Comment by rgerhards** [comment]
Review shows the problem IMHO is a bit larger: we have the same issue when setting owner etc. information. It's probably not as problematic is privilege drop, but I guess it would be saver to make rsyslog abort in those cases as well.

As such, I will implement a new global setting to enable/disable abort on UID resolution error. The default being to abort.
