### ISSUE TITLE
Cannot save logs to specific directory under template

### ISSUE THREAD

**Issue by JxClur** [rsyslog/rsyslog#4169]
### Expected behavior
I have 5 devices that have logs need to be stored in rsyslog server
I wanna save logs of different devices to specific directories under template rules: for example: with different IP Address
### Actual behavior
have added template commands to config file<rsyslog.conf>
```
$template RemoteLogs,"/var/log/dcmc_syslog_devices/%FROMHOST-IP%/%FROMHOST-IP%-%$YEAR%-%$MONTH%-%$DAY%.log"

*.* ?RemoteLogs

& ~
```
For now, I just can see one device and the rsyslog server were saved to directory as files
![image](https://user-images.githubusercontent.com/32921212/74250660-e6d3f280-4d25-11ea-93dd-5c86d3768422.png)
the other devices' logs can be found by using tcpdump, but cannot be stored to specific directory by following template rules
![image](https://user-images.githubusercontent.com/32921212/74250823-27cc0700-4d26-11ea-9ec7-1923605b7998.png)

### Steps to reproduce the behavior
1.install rsyslog
2.add template command to <rsyslog.conf>
3.restart service

### Environment
- rsyslog version:  8.32.0
- platform: Ubuntu 18.04.3 LTS
- for configuration questions/issues, include rsyslog.conf and included config files
**PS: Both 10.73.2.146 and 10.1.14.1 in the picture are all the Cisco ASA**

```
#  /etc/rsyslog.conf	Configuration file for rsyslog.
#
#			For more information see
#			/usr/share/doc/rsyslog-doc/html/rsyslog_conf.html
#
#  Default logging rules can be found in /etc/rsyslog.d/50-default.conf


#################
#### MODULES ####
#################

module(load="imuxsock") # provides support for local system logging
module(load="immark")  # provides --MARK-- message capability

# provides UDP syslog reception
module(load="imudp")
input(type="imudp" port="514")

# provides TCP syslog reception
module(load="imtcp")
input(type="imtcp" port="514")

# provides kernel logging support and enable non-kernel klog messages
module(load="imklog" permitnonkernelfacility="on")

###########################
#### GLOBAL DIRECTIVES ####
###########################

#
# Use traditional timestamp format.
# To enable high precision timestamps, comment out the following line.
#
$ActionFileDefaultTemplate RSYSLOG_TraditionalFileFormat

# Filter duplicated messages
$RepeatedMsgReduction on

#
# Set the default permissions for all log files.
#
$FileOwner syslog
$FileGroup adm
$FileCreateMode 0640
$DirCreateMode 0755
$Umask 0022
$PrivDropToUser syslog
$PrivDropToGroup syslog

#
# Where to place spool and state files
#
$WorkDirectory /var/spool/rsyslog

#
# Include all config files in /etc/rsyslog.d/
#
$IncludeConfig /etc/rsyslog.d/*.conf

$template RemoteLogs,"/var/log/dcmc_syslog_devices/%FROMHOST-IP%/%FROMHOST-IP%-%$YEAR%-%$MONTH%-%$DAY%.log"

*.* ?RemoteLogs

& ~
```

**Comment by mabobr** [comment]
Hi,
check event handling in files in /etc/rsyslog.d/*.conf  perhaps events having severity==info are terminated there.

**Comment by JxClur** [comment]
Hi mabobr,
I didn't find this string in both 20-ufw.conf and 50-default.conf which were located in the directory "/etc/rsyslog.d/":

**20-ufw.conf:**
`
# Log kernel generated UFW log messages to file
:msg,contains,"[UFW " /var/log/ufw.log

# Uncomment the following to stop logging anything that matches the last rule.
# Doing this will stop logging kernel generated UFW log messages to the file
# normally containing kern.* messages (eg, /var/log/kern.log)
#& stop
`
**50-default.conf**
`
#  Default rules for rsyslog.
#
#			For more information see rsyslog.conf(5) and /etc/rsyslog.conf

#
# First some standard log files.  Log by facility.
#
auth,authpriv.*			/var/log/auth.log
*.*;auth,authpriv.none		-/var/log/syslog
#cron.*				/var/log/cron.log
#daemon.*			-/var/log/daemon.log
kern.*				-/var/log/kern.log
#lpr.*				-/var/log/lpr.log
mail.*				-/var/log/mail.log
#user.*				-/var/log/user.log

#
# Logging for the mail system.  Split it up so that
# it is easy to write scripts to parse these files.
#
#mail.info			-/var/log/mail.info
#mail.warn			-/var/log/mail.warn
mail.err			/var/log/mail.err

#
# Some "catch-all" log files.
#
#*.=debug;\
#	auth,authpriv.none;\
#	news.none;mail.none	-/var/log/debug
#*.=info;*.=notice;*.=warn;\
#	auth,authpriv.none;\
#	cron,daemon.none;\
#	mail,news.none		-/var/log/messages

#
# Emergencies are sent to everybody logged in.
#
*.emerg				:omusrmsg:*

#
# I like to have messages displayed on the console, but only on a virtual
# console I usually leave idle.
#
#daemon,mail.*;\
#	news.=crit;news.=err;news.=notice;\
#	*.=debug;*.=info;\
#	*.=notice;*.=warn	/dev/tty8

`

**Comment by rgerhards** [comment]
Maybe there is a problem with parsing into fields. In order to see how the message is parsed add to the top of your rsyslog.conf:
```
*.* /var/log/msgfields.log;RSYSLOG_DebugFormat
```
This will create a multi-line entry for each message. Review the file and post an entry in question.

**Comment by JxClur** [comment]
Hi rgerhards, thanks for your reply, I had added this line into rsyslog.conf, but cannot see a file named about "msgfields.log"
![rsyslog_ts](https://user-images.githubusercontent.com/32921212/75893256-7d02c080-5e6d-11ea-8930-5a8c6b201634.png)

**Comment by rgerhards** [comment]
pls show full rsyslog.conf. I can't see in what context you entered the line.

**Comment by JxClur** [comment]
Hi rgerhards, here's my config:
```
#  /etc/rsyslog.conf	Configuration file for rsyslog.
#
#			For more information see
#			/usr/share/doc/rsyslog-doc/html/rsyslog_conf.html
#
#  Default logging rules can be found in /etc/rsyslog.d/50-default.conf

*.* /var/log/msgfields.log;RSYSLOG_DebugFormat

#################
#### MODULES ####
#################

module(load="imuxsock") # provides support for local system logging
module(load="immark")  # provides --MARK-- message capability

# provides UDP syslog reception
module(load="imudp")
input(type="imudp" port="514")

# provides TCP syslog reception
module(load="imtcp")
input(type="imtcp" port="514")

# provides kernel logging support and enable non-kernel klog messages
module(load="imklog" permitnonkernelfacility="on")

###########################
#### GLOBAL DIRECTIVES ####
###########################

#
# Use traditional timestamp format.
# To enable high precision timestamps, comment out the following line.
#
$ActionFileDefaultTemplate RSYSLOG_TraditionalFileFormat

# Filter duplicated messages
$RepeatedMsgReduction on

#
# Set the default permissions for all log files.
#
$FileOwner syslog
$FileGroup adm
$FileCreateMode 0640
$DirCreateMode 0755
$Umask 0022
$PrivDropToUser syslog
$PrivDropToGroup syslog

#
# Where to place spool and state files
#
$WorkDirectory /var/spool/rsyslog

#
# Include all config files in /etc/rsyslog.d/
#
$IncludeConfig /etc/rsyslog.d/*.conf

$template RemoteLogs,"/var/log/dcmc_syslog_devices/%FROMHOST-IP%/%FROMHOST-IP%-%$YEAR%-%$MONTH%-%$DAY%.log"

*.* ?RemoteLogs

& ~
```

**Comment by JxClur** [comment]
Hi, I have found the reason which lead to this problem is I forget allow udp 514 on my software firewall, thanks all
