### ISSUE TITLE
imrelp and omrelp do not support SSL_CONF_cmd

### ISSUE THREAD

**Issue by onet-git** [rsyslog/rsyslog#4171]
This is the relp specific version of https://github.com/rsyslog/rsyslog/issues/4170.

Unlike rsyslog nsd, the `TLS.PriorityString` setting in omrelp and imrelp does not silently get converted key-valyes pairs that are passed to SSL_CONF_cmd when librelp is called.

This might be considered a bug in librelp, however an API was already added to librelp for callers to set `tlsConfigCmd` that would parsed similar to how rsyslog nds parses the tls priority string. A parameter to set the tlsConfigCmd was never added to the imrelp or omrelp plugins in rsyslog.

### Environment
- rsyslog version: 8.2001.0

**Comment by alorbach** [comment]
We have the same code within librelp as in rsyslog, so it should be split up into key-value pairs already. 
The parameter was added in PR https://github.com/rsyslog/rsyslog/pull/3962
and is called tls.tlscfgcmd.

**Comment by onet-git** [comment]
It appear the issue what that I was looking at old documentation that did not have this option added yet.
