### ISSUE TITLE
After change the timezone,I see the rsyslog time still displays the previous timzone

### ISSUE THREAD

**Issue by zh4570260** [rsyslog/rsyslog#418]
When I replaced "localtime_r" with "localtime" in function timeval2syslogTime, rsyslog display the new timezone. It is a bug?

diff -ruN a/rsyslog-5.10.1/runtime/datetime.c b/rsyslog-5.10.1/runtime/datetime.c
--- a/rsyslog-5.10.1/runtime/datetime.c	2015-06-27 09:10:02.000000000 +0800
+++ b/rsyslog-5.10.1/runtime/datetime.c	2015-06-27 09:10:51.000000000 +0800
@@ -60,10 +60,9 @@
 timeval2syslogTime(struct timeval *tp, struct syslogTime *t)
 {
 	struct tm *tm;
-	struct tm tmBuf;
 	long lBias;
 
-	tm = localtime_r((time_t*) &(tp->tv_sec), &tmBuf);
+	tm = localtime((time_t*) &(tp->tv_sec));
 
 	t->year = tm->tm_year + 1900;
 	t->month = tm->tm_mon + 1;

**Comment by rgerhards** [comment]
localtime is not thread-safe, so we cannot use it (sooner or later rsyslog would crash and/or generate garbagge timestamps). So the question remains why the difference...?

**Comment by rgerhards** [comment]
oh, I see that is for a long-unsupported version. Please upgrade to 8.11.0 and create a new issue tracker if the problem persists. Closing this one here.

**Comment by zh4570260** [comment]
More, I Notice that 8.11.0 use localtime_r to convert local time, mean that can't update syslog time after timezone changed. And what's your suggestion to resolve this problem? must restart syslog?
