### ISSUE TITLE
imjournal::core dump

### ISSUE THREAD

**Issue by wsp1991** [rsyslog/rsyslog#4180]
### Expected behavior
no core dump
### Actual behavior
imjournal core dump

Core was generated by `/usr/sbin/rsyslogd -n'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000ffff87dad650 in memchr () from /lib64/libc.so.6
[Current thread is 1 (Thread 0xffff82c5d010 (LWP 7766))]
Missing separate debuginfos, use: dnf debuginfo-install glibc-2.28-9.h29.eulerosv2r8.aarch64 libblkid-2.32.1-1.h2.eulerosv2r8.aarch64 libcap-2.25-12.eulerosv2r8.aarch64 libestr-0.1.9-11.h1.eulerosv2r8.aarch64 libfastjson-0.99.8-3.eulerosv2r8.aarch64 libgcc-7.3.0-20190804.h22.eulerosv2r8.aarch64 libgcrypt-1.8.3-3.h3.eulerosv2r8.aarch64 libgpg-error-1.31-2.h2.eulerosv2r8.aarch64 libmount-2.32.1-1.h2.eulerosv2r8.aarch64 libselinux-2.8-4.h2.eulerosv2r8.aarch64 libuuid-2.32.1-1.h2.eulerosv2r8.aarch64 lz4-libs-1.8.2-2.h3.eulerosv2r8.aarch64 pcre2-10.32-3.h1.eulerosv2r8.aarch64 xz-libs-5.2.4-3.h1.eulerosv2r8.aarch64 zlib-1.2.11-14.h1.eulerosv2r8.aarch64
(gdb) bt
#0  0x0000ffff87dad650 in memchr () from /lib64/libc.so.6
#1  0x0000ffff8794783c in readjournal () at imjournal.c:407
#2  runInput (pThrd=<optimized out>) at imjournal.c:783
#3  0x0000aaaabe94aa60 in thrdStarter (arg=0xaaaad34b0f40) at ../threads.c:243
#4  0x0000ffff880538bc in start_thread () from /lib64/libpthread.so.0
#5  0x0000ffff87e0373c in thread_start () from /lib64/libc.so.6
(gdb) p get
$2 = (const void *) 0xffff8515e290
(gdb) x 0xffff8515e290
0xffff8515e290: Cannot access memory at address 0xffff8515e290

(gdb) info proc all
exe = '/usr/sbin/rsyslogd -n'
Mapped address spaces:

          Start Addr           End Addr       Size     Offset objfile
      0xaaaabe8df000     0xaaaabe987000    0xa8000        0x0 /usr/sbin/rsyslogd
      0xaaaabe99b000     0xaaaabe99f000     0x4000    0xac000 /usr/sbin/rsyslogd
      0xaaaabe99f000     0xaaaabe9a6000     0x7000    0xb0000 /usr/sbin/rsyslogd
      0xffff8145b000     0xffff81c5b000   0x800000        0x0 /run/log/journal/234a84f5b7f84b1ebcd07ffe507e4144/system@575564bd9cdc434aa6750114df9f9013-00000001b9eed78b-00059ee5c41f3f78.journal
      0xffff83123000     0xffff83923000   0x800000        0x0 /run/log/journal/234a84f5b7f84b1ebcd07ffe507e4144/system@575564bd9cdc434aa6750114df9f9013-00000001b9ee4373-00059ee5c412e45c.journal
      0xffff83923000     0xffff84123000   0x800000        0x0 /run/log/journal/234a84f5b7f84b1ebcd07ffe507e4144/system@575564bd9cdc434aa6750114df9f9013-00000001b9ee6879-00059ee5c4165acb.journal
      0xffff84123000     0xffff84923000   0x800000        0x0 /run/log/journal/234a84f5b7f84b1ebcd07ffe507e4144/system@575564bd9cdc434aa6750114df9f9013-00000001b9ee8d7f-00059ee5c4190efa.journal
      0xffff84923000     0xffff85123000   0x800000        0x0 /run/log/journal/234a84f5b7f84b1ebcd07ffe507e4144/system@575564bd9cdc434aa6750114df9f9013-00000001b9eeb285-00059ee5c41bcfa5.journal
      0xffff85123000     0xffff85923000   0x800000        0x0 

> **/run/log/journal/234a84f5b7f84b1ebcd07ffe507e4144/system@575564bd9cdc434aa6750114df9f9013-00000001b9edaf5b-00059ee5c404cf3f.journal (deleted)**

      0xffff86123000     0xffff86923000   0x800000        0x0 /run/log/journal/234a84f5b7f84b1ebcd07ffe507e4144/system@575564bd9cdc434aa6750114df9f9013-00000001b9edd461-00059ee5c408770c.journal
      0xffff86923000     0xffff87123000   0x800000        0x0 /run/log/journal/234a84f5b7f84b1ebcd07ffe507e4144/system@575564bd9cdc434aa6750114df9f9013-00000001b9edf967-00059ee5c40b8af8.journal
      0xffff87123000     0xffff87923000   0x800000        0x0 /run/log/journal/234a84f5b7f84b1ebcd07ffe507e4144/system@575564bd9cdc434aa6750114df9f9013-00000001b9ee1e6d-00059ee5c40f7e75.journal

Analysis ：readjournal（）------>equal_sign = memchr(get, '=', l);

the 'get' addr（0xffff8515e290） is in  0xffff85123000  -- 0xffff85923000，but the journal file is delete(0xffff85123000  -- 0xffff85923000),We can't visit the addr。

### Steps to reproduce the behavior
print log to journal fastly
### Environment
- rsyslog version: 
8.37.0
- platform: 
- for configuration questions/issues, include rsyslog.conf and included config files
```
# The imjournal module bellow is now used as a message source instead of imuxsock.
$ModLoad imuxsock # provides support for local system logging (e.g. via logger command)
$ModLoad imjournal # provides access to the systemd journal
#$ModLoad imklog # reads kernel messages (the same are read from journald)
#$ModLoad immark  # provides --MARK-- message capability

# Provides UDP syslog reception
#$ModLoad imudp
#$UDPServerRun 514

# Provides TCP syslog reception
#$ModLoad imtcp
#$InputTCPServerRun 514

$imjournalRatelimitInterval 0

#### GLOBAL DIRECTIVES ####

# Set oversize message input mode
global(oversizemsg.input.mode="accept")

# Replace control characters during reception of the message
$EscapeControlCharactersOnReceive off

# Where to place auxiliary files
$WorkDirectory /var/lib/rsyslog

# Use default timestamp format
#$ActionFileDefaultTemplate RSYSLOG_TraditionalFileFormat

#Use self defined template
$template uvpformat,"%TIMESTAMP:::date-rfc3339%|%syslogseverity-text%|%programname%[%PROCID%]|%msg%\n"
$ActionFileDefaultTemplate uvpformat

$FileCreateMode 0600
# File syncing capability is disabled by default. This feature is usually not required,
# not useful and an extreme performance hit
#$ActionFileEnableSync on

module(load="imfile" PollingInterval="1")
input(type="imfile"
        File="/var/log/yum.log"
        Tag="yum"
        Severity="error"
        reopenOnTruncate="on"
        Facility="local5")
if ($syslogfacility-text == 'local5' and $syslogtag == 'yum')then {
        :omfile:$yum
        stop
}
# Include all config files in /etc/rsyslog.d/
#$IncludeConfig /etc/rsyslog.d/*.conf

# Turn off message reception via local log socket;
# local messages are retrieved through imjournal now.
$OmitLocalLogging on

# File to store the position in the journal
$IMJournalStateFile /run/log/journal/imjournal.state
$RepeatedMsgReduction on
```

**Comment by rgerhards** [comment]
The version you are using is very old and no longer supported by the community. It is also very probable that the problem stems back to long-solved issues. As such, please update to the currently supported version and retry. Report back if the problem persists.

The rsyslog project provides packages for current versions: https://www.rsyslog.com/downloads/download-other/

If you insist on using an outdated version, you can also contact your distro or consider [rsyslog professional services](https://www.rsyslog.com/professional-services/enterprise-support/).
