### ISSUE TITLE
omelasticsearch ruleset issue

### ISSUE THREAD

**Issue by 5x3** [rsyslog/rsyslog#4181]
I am not sure if it is a bug or not.
simplest configuration with omelasticsearch module.
don't work - it don't writes to file.
when I comment OUT "ruleset(name="fwd-access") {" it starts to work - writes to file.
is this bug or my fail?

module(load="omelasticsearch") # Elasticsearch output module

input(
  type="imuxsock"
  Socket="/var/run/nginx_log.sock"
  UseSysTimeStamp="off"
  UseSpecialParser="off"
  ParseHostname="off"
  ruleset="fwd-access"
)
ruleset(name="fwd-access") {
$RepeatedMsgReduction off
action(type="omfile" file="/tmp/fff.txt")
}

**Comment by rgerhards** [comment]
This sounds like you do not receive messages via imuxsock. If you remove the ruleset, the action is part of whatever config else you have.

If that doesn't help, please let us know:
- rsyslog version: 
- platform: 
- for configuration questions/issues, include rsyslog.conf and included config files

**Comment by 5x3** [comment]
@rgerhards 
I receiving it,
I test it by just commenting out ruleset scope like this:
and file /tmp/fff.txt staring to grow immediately after restart rsyslog
#COMMENTED_OUTruleset(name="fwd-access") {
#$RepeatedMsgReduction off
action(type="omfile" file="/tmp/fff.txt")
#COMMENTED_OUT}

Same issue with last rsyslog from github repo and debian 8 default versions.

**Comment by davidelang** [comment]
IIRC, imuxsock doesn't support rulesets yet. (unless there was a recent change I 
missed)

David Lang
