### ISSUE TITLE
RebindInterval not exact

### ISSUE THREAD

**Issue by jvymazal** [rsyslog/rsyslog#4183]
### Expected behavior
Connection is cut after _x_ messages sent per `rebindinterval` setting
### Actual behavior
up 4 more messages then configured are sent 
### Steps to reproduce the behavior
- configure `omfwd` action with `rebindinterval`
- send messages
- capture connection details and look on how many messages have gone trough one port (`uniq -c conn_details`)
### Environment
- rsyslog version:8.1911.0 
- platform:Fedora 31 
- for configuration questions/issues, include rsyslog.conf and included config files
```
module(load="imtcp")
local0.info    action(type="omfwd" Protocol="tcp" port="514" RebindInterval="10" Target="127.0.0.1")
ruleset(name="TestRuleSet"){
local0.info    action(type="omfile" file="/var/log/rsyslog-TCPServerRebind-test.log")
}
```
input(type="imtcp" port="514" ruleset="TestRuleSet")

**Comment by jvymazal** [comment]
@rgerhards this may well end as doc etc. issue and I do realize nobody is probably using `rebindinterval` values so low that the extra 4 messages would matter but I would like to have confirmation from someone else that there is no other problem there.

From my digging trough code so far it seems that rebindinterval implementation itself 
https://github.com/rsyslog/rsyslog/blob/4de426bcf8f70976a0d3f6494e70dfb744f46deb/runtime/tcpclt.c#L301
is actually correct so the extra messages are due to something else.

Ant thoughts?

**Comment by rgerhards** [comment]
@jvymazal  IIRC this feature was introduced to support high-volume scenarios using load balancers. Looking at the code, I would say that the "extra number of messages" could be even higher. Not messages are counted by rather buffer send requests:

https://github.com/rsyslog/rsyslog/blob/master/tools/omfwd.c#L567 

So among others it depends on the batch size. It may be that originally actual messages were counted. However, we switched to batches several years ago, so I personally do not see any issue here. Again, the use case I think is to enable load balancers to get different traffic streams on very busy systems.

**Comment by davidelang** [comment]
yeah, it's technically X batches, not X messages, so by default it could be off 
by a very significant factor (batch size is either 16 or 128 depending on your 
version IIRC), on an idle system the messages per batch will be 1, on a very 
busy system it will be the max batch size.

David Lang

**Comment by jvymazal** [comment]
Ok, many thanks to both of you for explanation. I will submit a doc PR to clear it up there.

**Comment by jvymazal** [comment]
@davidelang, for testing purposes, is there a way to force batches to contain just 1 message? `queue.dequeueBatchSize="1"` does not seem to do the trick and doing sleep after each message is IMHO very poor test practice.

**Comment by rgerhards** [comment]
how about using a `direct` queue?

Also, the testbench has `wait_file_lines` which enables you to wait until a given number of lines is present in a text file. This can be used to sync. Might be useful depending in what you do. In the testbench, this is the preferred way to synchronize such things as on slow testbench machines even `queue.type="direct"` does not give you sufficiently precise timing to avoid false positives.

**Comment by jvymazal** [comment]
> how about using a `direct` queue?
> 
I thought that  `direct` queue is default for actions, unless I override it.

**Comment by rgerhards** [comment]
@jvymazal 

> I thought that `direct` queue is default for actions, unless I override it.

Yes - but I thought you wanted to synchronize with message injection. Then you have the main queue in between, which is not direct. 

Note that for a testbench test the wait_file_lines approach is far superior as otherwise we will fight with occasional flakes.
