### ISSUE TITLE
Using rsyslog in zookeeper and modifying the port does not apply to the default port 514?

### ISSUE THREAD

**Issue by yaojingen** [rsyslog/rsyslog#4197]
### Actual behavior
If set  following configuration parameters in conf/log4j.properties file

log4j.appender.SYSLOG.host=localhost
log4j.appender.SYSLOG.port=515
log4j.appender.SYSLOG.protocol=UDP

It will report the following error in zookeeper log file.

scl:
log4j:WARN No such property [port] in org.apache.log4j.net.SyslogAppender.
log4j:WARN No such property [protocol] in org.apache.log4j.net.SyslogAppender.
log4j:WARN No such property [host] in org.apache.log4j.net.SyslogAppender.

### Environment
- rsyslog version: 
- platform: 
- for configuration questions/issues, include rsyslog.conf and included config files

**Comment by rgerhards** [comment]
sry, this is a log4j question. I has nothing to do with rsyslog.
