### ISSUE TITLE
When rsyslog ends and send EOF to process specified in omprog

### ISSUE THREAD

**Issue by bmy4415** [rsyslog/rsyslog#4207]
### Expected behavior
Rsyslog runs forever since it is daemon.

### Actual behavior
Rsyslog stops after some time. (I did not measure exact time.)

### Steps to reproduce the behavior
Not sure how to reproduce.... I just checked that my target process of omprog stoped. After checking my code, this is due to EOF is passed to stdin.
Currently I use only imfile and omprog plugin.

### Environment
```
rsyslogd 8.24.0-41.el7_7.2, compiled with:
	PLATFORM:				x86_64-redhat-linux-gnu
	PLATFORM (lsb_release -d):
	FEATURE_REGEXP:				Yes
	GSSAPI Kerberos 5 support:		Yes
	FEATURE_DEBUG (debug build, slow code):	No
	32bit Atomic operations supported:	Yes
	64bit Atomic operations supported:	Yes
	memory allocator:			system default
	Runtime Instrumentation (slow code):	No
	uuid support:				Yes
	Number of Bits in RainerScript integers: 64

See http://www.rsyslog.com for more information.
```

### Question
As I mentioned above, I want to make rsyslog run forever.
Here is (I think helpful) segment of configs. I use only imfile and omprog plugins.

```
Ruleset (name="output") {
    Action (type="omprog" binary="python post.py" template="lineFormat" signalOnClose="on")
}

...
Input (
    type="imfile"
    tag="mytag"
    file="mypath.xml"
    addMetadata="on"
    ruleSet="output"
    startmsg.regex="^<msg"
    readTimeout="2"
)
```

I want rsyslog runs forever (At least, does not stop unexpectedly).
But my omprog target process receive EOF from rsyslog process and then stopped.
When rsyslog process stops and send EOF to omprog?

Thanks,
Jaewan

**Comment by rgerhards** [comment]
> Rsyslog stops after some time. (I did not measure exact time.)

If it really happens, this is not normal. You should get a crash report, a journal entry (if you run under systemd journal) or at a minimum a new startup message from rsyslog (assuming that you log rsyslog messages itself).

How did you find out that rsyslog actually stopped? Post this information.

**Comment by bmy4415** [comment]
I cannot reproduce this again. Let's close this for now. I will re-ask if same situation is reproduced.
