### ISSUE TITLE
rsyslog imfile-stat file not closed in version 8.1911.0

### ISSUE THREAD

**Issue by lynnnn12300** [rsyslog/rsyslog#4209]
old file expected imtilf-state:inode file not exists,but in version 8.2002.0/8.1911.0 still exits, this cause when rsyslog restart ,all the logs will retransmit.

this is the receiver's log , can be seen the same log was retransmit ,but after this transmit ,the imfile-stat:inode was closed 
# ls -alh nginx/nginx-6ff8b69cf8-ssblg/logs/nginx-log/access-2020-03-02T22.log.*
-rw-r--r-- 1 root root 24M Mar  2 23:00 nginx/nginx-6ff8b69cf8-ssblg/logs/nginx-log/access-2020-03-02T22.log.2020-03-02-22.gz
-rw-r--r-- 1 root root 24M Mar  4 23:12 nginx/nginx-6ff8b69cf8-ssblg/logs/nginx-log/access-2020-03-02T22.log.2020-03-04-23.gz

rsyslog-client/server version: 8.19.11
# dpkg -l | grep rsyslog
ii  rsyslog                                    8.1911.0-0adiscon1trusty1                  amd64        a rocket-fast system for log processing

can anyone help ?

**Comment by rgerhards** [comment]
The version you are using is very old and no longer supported by the community. It is also very probable that the problem stems back to long-solved issues. As such, please update to the currently supported version and retry. Report back if the problem persists.

The rsyslog project provides packages for current versions: https://www.rsyslog.com/downloads/download-other/

If you insist on using an outdated version, you can also contact your distro or consider [rsyslog professional services](https://www.rsyslog.com/professional-services/enterprise-support/).

**Comment by lynnnn12300** [comment]
thanks，we has this problem all the time since we used rsyslog to gather logs, and we has upgrade once at Jan.9 , I will upgrade the version to 8.2002.0 to check .
add imfile-state：
# ls -al *20554499*
-rw------- 1 root root 157 Mar  5 18:00 imfile-state:20554499
-rw------- 1 root root 169 Mar  5 18:58 imfile-state:20554499:8db88841befb46ee

# cat imfile-state:20554499
{ "filename": "\/R\/nginx\/nginx-6ff8b69cf8-ssblg\/logs\/nginx-log\/access-2020-03-05T18.log", "prev_was_nl": 0, "curr_offs": 918, "strt_offs": 918 }

**Comment by Dieken** [comment]
![image](https://user-images.githubusercontent.com/2365/75989375-1e514b80-5f2e-11ea-9249-e7545c1bf9c0.png)

there are two imfile-state files for same file.

**Comment by rgerhards** [comment]
was that with 8.2002.0? If so, did you delete previous duplicates (the new version does intentionally not clean up existing files as there are use cases which need them)?

**Comment by Dieken** [comment]
we use 8.1911.0-0adiscon1trusty1,   should we delete all old imfile-state files?

**Comment by rgerhards** [comment]
yes, but 8.1911.0 misses patches, so you **need** to update

**Comment by Dieken** [comment]
ok, we will delete imfile-state file and upgrade to latest version,  thanks!
