### ISSUE TITLE
Fix LibreSSL support (does not support for @SECLEVEL and SSL_CONF_CTX_set_flags())

### ISSUE THREAD

**Issue by alorbach** [rsyslog/rsyslog#4210]
See https://github.com/rsyslog/librelp/pull/180 , simular fix needs to be done for rsyslog to enable libressl support. 

@rgerhards  Maybe we need a machine for libressl testing?!

**Comment by rgerhards** [comment]
> @rgerhards Maybe we need a machine for libressl testing?!

That's a good point. Can you find out if we can do this e.g. with Debian? I could then craft a container.

**Comment by alorbach** [comment]
According to this (https://www.libressl.org/), FreeBSD would be the right choice

**Comment by rgerhards** [comment]
ok, than I think it is too much effort. BSD doesn't work in containers.
