### ISSUE TITLE
IP spoof in TCP

### ISSUE THREAD

**Issue by jwendell** [rsyslog/rsyslog#422]
I see there's support for source IP spoofing for UDP.

What about TCP? Is it planned?

**Comment by alorbach** [comment]
I believe this is technical almost impossible due the nature of the TCP protocol.

**Comment by rgerhards** [comment]
As Andre said, there is no regular way to do that. You could use some malware methods, but that would strongly interfere with all network communication to the original sender. So it's impossible.
