### ISSUE TITLE
How to handle high log volume with omhttp and omfile on one input

### ISSUE THREAD

**Issue by nickerokhin** [rsyslog/rsyslog#4226]
Posted this on stackoverflow as well 

https://stackoverflow.com/questions/60764060/handling-large-log-volume-in-rsyslog-with-omhttp-and-omfile

In my use case, I have a service which produces large log volume and the logs must written to a file in addition to loggly (3rd party ELK as a service)

The service is configured to write json logs to port `515`

I'm seeing a problem where the logs in `service_log.jsonl` fall behind at an increasing rate once the service has been running for some time. I suspect this is due to the action queues for both `direct_service_json` and `push_loggly_service` are somehow coupled

Ideally, I'd like to completely decouple `direct_service_json` and `push_loggly_service` such that the `push_loggly_service` writer can take as long as it needs to push logs to loggly while `direct_service_json` stays up to date on the service logs

What is the best way to go about doing this? I have provided the config file I'm using - with this configuration the logs in `service_log.jsonl` start lagging behind within 30 minutes or so

I am running `8.2001.0` on Ubuntu 16.04

```module(load="imudp")
module(load="omhttp")
module(load="mmjsonparse")
module(load="imudp")

template(name="json_logs" type="list") {
    constant(value="{")   property(name="hostname"      outname="hostname"      format="jsonfr")
    constant(value=",")   property(name="timereported"  outname="timestamp" format="jsonfr" dateFormat="rfc3339")
    constant(value=",")   property(name="programname"   outname="proc"      format="jsonfr")
    constant(value=",")   property(name="syslogpriority-text" outname="level"     format="jsonfr")
    constant(value=",")   property(name="$!all-json" position.from="2")
}

template(name="simple" type="list") {
    property(name="syslogtag")
    property(name="msg")
    constant(value="\n")
}


# Write messages to /var/log/service_logs.jsonl
ruleset(name="direct_service_json" queue.Type="LinkedList") {
        action(type="omfile" file="/var/log/service_logs.jsonl" template="simple")
}

# Send messages to Loggly using the json_logs template.
# Using two consumers to handle insane log volume
# Consumers are capped at 4, rsyslog spawns workers when action is backlogged at 100
ruleset(name="push_loggly_service" queue.Type="LinkedList" queue.WorkerThreads="4" queue.workerThreadMinimumMessages="100"){
        action(type="mmjsonparse" cookie="")
        action(type="omhttp"
                server="logs-01.loggly.com"
                errorfile="/var/log/rsyslog.error.log"
                restpath="inputs/SECRET_TOKEN/tag/rsyslog"
                retry="on"
                useHttps="on"
                template="json_logs"
                )
        }

input(type="imudp" port="515" name="json-input")

# Hack - attempt to decouple the file writer from the loggly writer
if $inputname == "json-input" then {
        call direct_service_json
}

if $inputname == "json-input" then {
        call push_loggly_service
}
```

**Comment by davidelang** [comment]
enable impstats to see what's happening with your queues.

4 worker threads probably slows things down more than it helps.

David LAng

**Comment by nickerokhin** [comment]
@davidelang 

I didn't know about impstats. This is game changer 

I successfully managed to decouple the main queue from the action queue. 

With my config the main queue kept growing

I changed my ruleset from this 

```
ruleset(name="push_loggly_service" queue.Type="LinkedList" queue.WorkerThreads="4" queue.workerThreadMinimumMessages="100"){
        action(type="mmjsonparse" cookie="")
        action(type="omhttp"
                server="logs-01.loggly.com"
                errorfile="/var/log/rsyslog.error.log"
                restpath="inputs/SECRET_TOKEN/tag/rsyslog"
                retry="on"
                useHttps="on"
                template="json_logs"
                )
        }
```

to this. I just took the queue parameters out of the ruleset and put them into the omhttp action

```
ruleset(name="push_loggly_service"){
        action(type="mmjsonparse" cookie="")
        action(type="omhttp"
                server="logs-01.loggly.com"
                errorfile="/var/log/rsyslog.error.log"
                restpath="inputs/SECRET_TOKEN/tag/rsyslog"
                retry="on"
                useHttps="on"
                template="json_logs"
                queue.Type="LinkedList"
                queue.Size="300000"
                queue.workerthreadminimummessages="200"
                queue.workerthreads="2"
                )
        }
```

I'm okay with the omhttp queue being backlogged - as long as it doesn't slow down logging as a whole.

Thank you!

**Comment by davidelang** [comment]
you should be able to have a queue on the ruleset just as well as on the action 
(in fact, if you are going to have multiple actions in a ruleset, this is 
probably what you want) One thing you did was to increase the size of the queue, 
that will make it take longer to back up to where it blocks the main queue, but 
if you aren't processing messages fast enough, you will still run into grief 
eventually. but pstats will show you the queues building in size.

note you have more parameters on the action than you had on the ruleset.

if you run top and hit 'H' it will give you per-thread info so you can see all 
the different threads. You only want to setup multiple workers if you see a 
worker hitting 100% cpu or is having trouble keeping up as a result of delays at 
the destination.

Having too many workers does two things

1. the queue is locked more of the time as each worker is checking to see if 
there is data to pull
2. each worker is going to get a smaller batch of messages, resulting in more 
overhead.

increasing batch size is something you should do before adding more workers 
(unless your output can't benefit from batching)

David Lang
