### ISSUE TITLE
imfile module readTimeout does not time out (8.32.0)

### ISSUE THREAD

**Issue by andrewbierbaum** [rsyslog/rsyslog#4229]
This is an almost identical issue as https://github.com/rsyslog/rsyslog/issues/1445

This should be tracking 4 log files (that are gzipped on a daily basis)
```
r1-2020-03-16-1.log.gz
r1-2020-03-17-1.log.gz
r1-2020-03-18-1.log.gz
r1-2020-03-19-1.log.gz
r1-2020-03-21-1.log.gz
r1-2020-03-22-1.log.gz
r1-2020-03-23-1.log.gz
r1_deprecation.log
r1_index_indexing_slowlog.log
r1_index_search_slowlog.log
r1.log
```

using the following partial configuration. 
```
global (
    maxMessageSize="64k"

)
module(load="imfile"
          PollingInterval="10"

)
input(type="imfile"
  Tag="ElasticLogger"
  file="/var/log/elasticsearch/elastic*nlog/{*.log,*/*.log}"
  facility="local7"
  readMode="2"
  readTimeout="2"
)
```
This is configured via the puppet-rsyslog module https://forge.puppet.com/puppet/rsyslog, and when the configuration is updated, a systemctl restart rsyslog.service is run. 

This was tested with 
```echo "testing`date +%y%m%d%T`" >> r1.log```
and waiting several minutes with nothing new appearing in 
```tail -n 10 /var/log/syslog```
rerunning
```echo "testing`date +%y%m%d%T`" >> r1.log```
puts the 2nd to last entry into /var/log/syslog, but the newest will not appear until there is a new entry. Example with <host_name> replaced entered line 6 minutes later when a new line was manually added to the log file.
```Mar 24 19:12:55 <host_name> ElasticLogger testing20032419:06:45```

- rsyslog version: 8.32.0
- platform: Ubuntu 18.04

Thanks for you work on rsyslog :)

**Comment by davidelang** [comment]
the readmode can't be sure that it has the end of a message until it sees the 
beginning of the next message. on current versions of rsyslog, there is a 
timeout you can set to tell rsyslog that if it doesn't see anything new in that 
time, assume that it's at the end of the log message and process it.

I don't know if that was in 8.32 or not (almost 2 years old at this point). 
check the documentation and try the timeout to see if it works on your version 
or update to the latest version (there have been a lot of imfile changes, I 
believe almost a complete rewrite during this time)

David Lang

  On Tue, 24 
Mar 2020, andrewbierbaum wrote:

> Date: Tue, 24 Mar 2020 12:21:59 -0700
> From: andrewbierbaum <notifications@github.com>
> Reply-To: rsyslog/rsyslog
>     <reply@reply.github.com>
> To: rsyslog/rsyslog <rsyslog@noreply.github.com>
> Cc: Subscribed <subscribed@noreply.github.com>
> Subject: [rsyslog/rsyslog] imfile module readTimeout does not time out
>     (8.32.0) (#4229)
> 
> This is an almost identical issue as https://github.com/rsyslog/rsyslog/issues/1445
>
> This should be tracking 4 log files
> ```
> r1.log
> r1_deprecation.log
> r1_index_indexing_slowlog.log
> r1_index_search_slowlog.log
> ```
>
> using the following configuration.
> ```
> global (
>    maxMessageSize="64k"
>
> )
> module(load="imfile"
>          PollingInterval="10"
>
> )
> input(type="imfile"
>  Tag="ElasticLogger"
>  file="/var/log/elasticsearch/elastic*nlog/{*.log,*/*.log}"
>  facility="local7"
>  readMode="2"
>  readTimeout="2"
> )
> ```
> This is configured via the puppet-rsyslog module https://forge.puppet.com/puppet/rsyslog, and when the configuration is updated, a systemctl restart rsyslog.service is run.
>
> This was tested with
> ```echo "testing`date +%y%m%d%T`" >> r1.log```
> and waiting several minutes with nothing new appearing in
> ```tail -n 10 /var/log/syslog```
> rerunning
> ```echo "testing`date +%y%m%d%T`" >> r1.log```
> puts the 2nd to last entry into /var/log/syslog, but the newest will not appear until there is a new entry. Example with <host_name> replaced entered line 6 minutes later when a new line was manually added to the log file.
> ```Mar 24 19:12:55 <host_name> ElasticLogger testing20032419:06:45```
>
>
> - rsyslog version: 8.32.0
> - platform: Ubuntu 18.04
>
>
