### ISSUE TITLE
raise dynafilecachesize from 1000

### ISSUE THREAD

**Issue by davidelang** [rsyslog/rsyslog#4241]
v8.2002 logs:
rsyslogd: error during parsing file /etc/rsyslog.conf, on or before line 14: DynaFileCacheSize maximum is 1,000 (10000 given), changed to 1,000. [v8.1908.0 try https://www.rsyslog.com/e/2207 ]

1000 files may seem like a lot, but in a medium/large installation it's easy to exceed.

**Comment by rgerhards** [comment]
This looks like a left-over in the obsolete legacy configuration format. In new-style I do not see this check. This is also why I initially could not reproduce the issue.
