### ISSUE TITLE
omprog: quotes are passed to argument

### ISSUE THREAD

**Issue by Dystopian** [rsyslog/rsyslog#4249]
### Expected behavior
Quotes are removed from arguments. `argv` contains strings without quotes.
### Actual behavior
Quotes are passed to arguments. This makes not possible configs like `binary="/bin/sh -c \"echo done\""` because `sh` gets `"echo done"` in `argv[1]` not `echo done`.
### Steps to reproduce the behavior

- add to `rsyslog.conf`: 
```
*.err action(type="omprog" binary="/usr/local/bin/test.sh -c \"echo done\"" output="/tmp/o")
```
- `#cat /usr/local/bin/test.sh`
```
#!/bin/sh

echo "$@"
```
- `logger -p mail.err fff`
- check `/tmp/o`: `-c "echo done"`
- run from shell `/usr/local/bin/test.sh -c "echo done"`, check output: `-c echo done`

### Environment
- rsyslog version: 8.1901.0
- platform: Debian 10

**Comment by rgerhards** [comment]
Keep in mind that you provide a constant string to rsyslog. There, backslash is an escape sequence. If you need backslash, you need to escape it as well. Concrete sample:
``` 
*.err action(type="omprog" binary="/usr/local/bin/test.sh -c \\\"echo done\\\"" output="/tmp/o")
```

**Comment by onemans-battle** [comment]
Is it working? I can't seem to use it here

>  `su user -c "program"`
by @jsiwrk in https://github.com/rsyslog/rsyslog/issues/28#issuecomment-418340797_

I try ` binary="/bin/su www -c \\\"/usr/bin/php /path/script log\\\""`, 
syslog echo `rsyslogd: Child 5077 has terminated, reaped by main-loop. [v8.32.0 try http://www.rsyslog.com/e/0 ]`

And this works fine:
`binary="/usr/bin/php /path/script log"`

**Comment by Dystopian** [comment]
> I try ` binary="/bin/su www -c \\\"/usr/bin/php /path/script log\\\""`,

It can't work. With this config `su` gets `\"/usr/bin/php /path/script log\"` as argument and I doubt it can parse it. At least backslashes are wrong. And as I said in report quotes are passed to argument but they shouldn't.

**Comment by jsiwrk** [comment]
As a workaround, try with `binary="my-program-launcher.sh"`, where `my-program-launcher.sh` is:
```
#!/bin/bash
su www -c "/usr/bin/php /path/script log"
```

Omprog only spawns new instances of the program from time to time, so spawning an additional bash process for launching your program should not affect performance noticeably, I would say.
