### ISSUE TITLE
rsyslog memory leak 

### ISSUE THREAD

**Issue by zhoushuling** [rsyslog/rsyslog#4251]
### Steps to reproduce the behavior

run the AddressSanitizer tool，the tool reports  24676 byte(s) leaked in 210 allocation(s).

### Environment
- rsyslog version: rsyslog-8.24.0-17
- platform: centos7.5
- for configuration questions/issues, include rsyslog.conf and included config files

the dump stack：
=================================================================
==rsyslogd==16390==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 4096 byte(s) in 1 object(s) allocated from:
  #0 0x7f6fc55ed3a0 in malloc (/usr/local/gcc-6-4/lib64/libasan.so.3+0xc73a0)  ??:?
  #1 0x7f6fc66551d1 (<unknown module>)
  #2 0x7f6fc665fde3 (<unknown module>)
  #3 0x7f6fc66602f5 (<unknown module>)
  #4 0x7f6fbf8da4f3 (<unknown module>)
  #5 0x55ebd39f35ba (/usr/sbin/rsyslogd+0x1a5ba)  /usr/src/debug/rsyslog-8.24.0/runtime/rsconf.c:774
  #6 0x55ebd3a29113 (/usr/sbin/rsyslogd+0x50113)  /usr/src/debug/rsyslog-8.24.0/tools/rsyslogd.c:1442
  #7 0x55ebd39ee293 in main (/usr/sbin/rsyslogd+0x15293)  /usr/src/debug/rsyslog-8.24.0/tools/rsyslogd.c:1866
  #8 0x7f6fc33f7504 in __libc_start_main (/usr/lib64/libc.so.6+0x22504)  ??:?
  #9 0x55ebd39ee670 (/usr/sbin/rsyslogd+0x15670)  ??:?

Direct leak of 4096 byte(s) in 1 object(s) allocated from:
  #0 0x7f6fc55ed3a0 in malloc (/usr/local/gcc-6-4/lib64/libasan.so.3+0xc73a0)  ??:?
  #1 0x7f6fc66551d1 (<unknown module>)
  #2 0x7f6fc665fdd1 (<unknown module>)
  #3 0x7f6fc66602f5 (<unknown module>)
  #4 0x7f6fbf8da4f3 (<unknown module>)
  #5 0x55ebd39f35ba (/usr/sbin/rsyslogd+0x1a5ba)  /usr/src/debug/rsyslog-8.24.0/runtime/rsconf.c:774
  #6 0x55ebd3a29113 (/usr/sbin/rsyslogd+0x50113)  /usr/src/debug/rsyslog-8.24.0/tools/rsyslogd.c:1442
  #7 0x55ebd39ee293 in main (/usr/sbin/rsyslogd+0x15293)  /usr/src/debug/rsyslog-8.24.0/tools/rsyslogd.c:1866
  #8 0x7f6fc33f7504 in __libc_start_main (/usr/lib64/libc.so.6+0x22504)  ??:?
  #9 0x55ebd39ee670 (/usr/sbin/rsyslogd+0x15670)  ??:?

Direct leak of 48 byte(s) in 1 object(s) allocated from:
  #0 0x7f6fc55ed560 in calloc (/usr/local/gcc-6-4/lib64/libasan.so.3+0xc7560)  ??:?
  #1 0x55ebd3a224c2 in ochConstruct (/usr/sbin/rsyslogd+0x494c2)  /usr/src/debug/rsyslog-8.24.0/runtime/../outchannel.c:47
  #2 0x55ebd3a22538 in ochAddLine (/usr/sbin/rsyslogd+0x49538)  /usr/src/debug/rsyslog-8.24.0/runtime/../outchannel.c:207
  #3 0x55ebd39f1aa9 (/usr/sbin/rsyslogd+0x18aa9)  /usr/src/debug/rsyslog-8.24.0/runtime/conf.c:190
  #4 0x55ebd3a1bd0e in processCfSysLineCommand (/usr/sbin/rsyslogd+0x42d0e)  /usr/src/debug/rsyslog-8.24.0/runtime/cfsysline.c:760
  #5 0x55ebd39f1c03 (/usr/sbin/rsyslogd+0x18c03)  /usr/src/debug/rsyslog-8.24.0/runtime/conf.c:233
  #6 0x55ebd39f539b in cnfDoCfsysline (/usr/sbin/rsyslogd+0x1c39b)  /usr/src/debug/rsyslog-8.24.0/runtime/rsconf.c:483
  #7 0x55ebd3a377d8 in yylex (/usr/sbin/rsyslogd+0x5e7d8)  /usr/src/debug/rsyslog-8.24.0/grammar/lexer.l:288
  #8 0x55ebd3a34a4d in yyparse (/usr/sbin/rsyslogd+0x5ba4d)  /usr/src/debug/rsyslog-8.24.0/grammar/grammar.c:1425
  #9 0x55ebd39f4700 (/usr/sbin/rsyslogd+0x1b700)  /usr/src/debug/rsyslog-8.24.0/runtime/rsconf.c:1306
  #10 0x55ebd3a28e1b (/usr/sbin/rsyslogd+0x4fe1b)  /usr/src/debug/rsyslog-8.24.0/tools/rsyslogd.c:1384
  #11 0x55ebd39ee293 in main (/usr/sbin/rsyslogd+0x15293)  /usr/src/debug/rsyslog-8.24.0/tools/rsyslogd.c:1866
  #12 0x7f6fc33f7504 in __libc_start_main (/usr/lib64/libc.so.6+0x22504)  ??:?
  #13 0x55ebd39ee670 (/usr/sbin/rsyslogd+0x15670)  ??:?

Indirect leak of 6656 byte(s) in 52 object(s) allocated from:
  #0 0x7f6fc55ed750 in realloc (/usr/local/gcc-6-4/lib64/libasan.so.3+0xc7750)  ??:?
  #1 0x55ebd39ffcf2 in cstrAppendChar (/usr/sbin/rsyslogd+0x26cf2)  /usr/src/debug/rsyslog-8.24.0/runtime/stringbuf.c:252
  #2 0x55ebd3a22615 in ochAddLine (/usr/sbin/rsyslogd+0x49615)  /usr/src/debug/rsyslog-8.24.0/runtime/../outchannel.c:108
  #3 0x55ebd39f1aa9 (/usr/sbin/rsyslogd+0x18aa9)  /usr/src/debug/rsyslog-8.24.0/runtime/conf.c:190
  #4 0x55ebd3a1bd0e in processCfSysLineCommand (/usr/sbin/rsyslogd+0x42d0e)  /usr/src/debug/rsyslog-8.24.0/runtime/cfsysline.c:760
  #5 0x55ebd39f1c03 (/usr/sbin/rsyslogd+0x18c03)  /usr/src/debug/rsyslog-8.24.0/runtime/conf.c:233
  #6 0x55ebd39f539b in cnfDoCfsysline (/usr/sbin/rsyslogd+0x1c39b)  /usr/src/debug/rsyslog-8.24.0/runtime/rsconf.c:483
  #7 0x55ebd3a377d8 in yylex (/usr/sbin/rsyslogd+0x5e7d8)  /usr/src/debug/rsyslog-8.24.0/grammar/lexer.l:288
  #8 0x55ebd3a34a4d in yyparse (/usr/sbin/rsyslogd+0x5ba4d)  /usr/src/debug/rsyslog-8.24.0/grammar/grammar.c:1425
  #9 0x55ebd39f4700 (/usr/sbin/rsyslogd+0x1b700)  /usr/src/debug/rsyslog-8.24.0/runtime/rsconf.c:1306
  #10 0x55ebd3a28e1b (/usr/sbin/rsyslogd+0x4fe1b)  /usr/src/debug/rsyslog-8.24.0/tools/rsyslogd.c:1384
  #11 0x55ebd39ee293 in main (/usr/sbin/rsyslogd+0x15293)  /usr/src/debug/rsyslog-8.24.0/tools/rsyslogd.c:1866
  #12 0x7f6fc33f7504 in __libc_start_main (/usr/lib64/libc.so.6+0x22504)  ??:?
  #13 0x55ebd39ee670 (/usr/sbin/rsyslogd+0x15670)  ??:?

Indirect leak of 6656 byte(s) in 52 object(s) allocated from:
  #0 0x7f6fc55ed750 in realloc (/usr/local/gcc-6-4/lib64/libasan.so.3+0xc7750)  ??:?
  #1 0x55ebd39ffcf2 in cstrAppendChar (/usr/sbin/rsyslogd+0x26cf2)  /usr/src/debug/rsyslog-8.24.0/runtime/stringbuf.c:252
  #2 0x55ebd3a22715 in ochAddLine (/usr/sbin/rsyslogd+0x49715)  /usr/src/debug/rsyslog-8.24.0/runtime/../outchannel.c:176
  #3 0x55ebd39f1aa9 (/usr/sbin/rsyslogd+0x18aa9)  /usr/src/debug/rsyslog-8.24.0/runtime/conf.c:190
  #4 0x55ebd3a1bd0e in processCfSysLineCommand (/usr/sbin/rsyslogd+0x42d0e)  /usr/src/debug/rsyslog-8.24.0/runtime/cfsysline.c:760
  #5 0x55ebd39f1c03 (/usr/sbin/rsyslogd+0x18c03)  /usr/src/debug/rsyslog-8.24.0/runtime/conf.c:233
  #6 0x55ebd39f539b in cnfDoCfsysline (/usr/sbin/rsyslogd+0x1c39b)  /usr/src/debug/rsyslog-8.24.0/runtime/rsconf.c:483
  #7 0x55ebd3a377d8 in yylex (/usr/sbin/rsyslogd+0x5e7d8)  /usr/src/debug/rsyslog-8.24.0/grammar/lexer.l:288
  #8 0x55ebd3a34a4d in yyparse (/usr/sbin/rsyslogd+0x5ba4d)  /usr/src/debug/rsyslog-8.24.0/grammar/grammar.c:1425
  #9 0x55ebd39f4700 (/usr/sbin/rsyslogd+0x1b700)  /usr/src/debug/rsyslog-8.24.0/runtime/rsconf.c:1306
  #10 0x55ebd3a28e1b (/usr/sbin/rsyslogd+0x4fe1b)  /usr/src/debug/rsyslog-8.24.0/tools/rsyslogd.c:1384
  #11 0x55ebd39ee293 in main (/usr/sbin/rsyslogd+0x15293)  /usr/src/debug/rsyslog-8.24.0/tools/rsyslogd.c:1866
  #12 0x7f6fc33f7504 in __libc_start_main (/usr/lib64/libc.so.6+0x22504)  ??:?
  #13 0x55ebd39ee670 (/usr/sbin/rsyslogd+0x15670)  ??:?

Indirect leak of 2448 byte(s) in 51 object(s) allocated from:
  #0 0x7f6fc55ed560 in calloc (/usr/local/gcc-6-4/lib64/libasan.so.3+0xc7560)  ??:?
  #1 0x55ebd3a224c2 in ochConstruct (/usr/sbin/rsyslogd+0x494c2)  /usr/src/debug/rsyslog-8.24.0/runtime/../outchannel.c:47
  #2 0x55ebd3a22538 in ochAddLine (/usr/sbin/rsyslogd+0x49538)  /usr/src/debug/rsyslog-8.24.0/runtime/../outchannel.c:207
  #3 0x55ebd39f1aa9 (/usr/sbin/rsyslogd+0x18aa9)  /usr/src/debug/rsyslog-8.24.0/runtime/conf.c:190
  #4 0x55ebd3a1bd0e in processCfSysLineCommand (/usr/sbin/rsyslogd+0x42d0e)  /usr/src/debug/rsyslog-8.24.0/runtime/cfsysline.c:760
  #5 0x55ebd39f1c03 (/usr/sbin/rsyslogd+0x18c03)  /usr/src/debug/rsyslog-8.24.0/runtime/conf.c:233
  #6 0x55ebd39f539b in cnfDoCfsysline (/usr/sbin/rsyslogd+0x1c39b)  /usr/src/debug/rsyslog-8.24.0/runtime/rsconf.c:483
  #7 0x55ebd3a377d8 in yylex (/usr/sbin/rsyslogd+0x5e7d8)  /usr/src/debug/rsyslog-8.24.0/grammar/lexer.l:288
  #8 0x55ebd3a34a4d in yyparse (/usr/sbin/rsyslogd+0x5ba4d)  /usr/src/debug/rsyslog-8.24.0/grammar/grammar.c:1425
  #9 0x55ebd39f4700 (/usr/sbin/rsyslogd+0x1b700)  /usr/src/debug/rsyslog-8.24.0/runtime/rsconf.c:1306
  #10 0x55ebd3a28e1b (/usr/sbin/rsyslogd+0x4fe1b)  /usr/src/debug/rsyslog-8.24.0/tools/rsyslogd.c:1384
  #11 0x55ebd39ee293 in main (/usr/sbin/rsyslogd+0x15293)  /usr/src/debug/rsyslog-8.24.0/tools/rsyslogd.c:1866
  #12 0x7f6fc33f7504 in __libc_start_main (/usr/lib64/libc.so.6+0x22504)  ??:?
  #13 0x55ebd39ee670 (/usr/sbin/rsyslogd+0x15670)  ??:?

Indirect leak of 676 byte(s) in 52 object(s) allocated from:
  #0 0x7f6fc55ed3a0 in malloc (/usr/local/gcc-6-4/lib64/libasan.so.3+0xc73a0)  ??:?
  #1 0x55ebd3a2255d in ochAddLine (/usr/sbin/rsyslogd+0x4955d)  /usr/src/debug/rsyslog-8.24.0/runtime/../outchannel.c:211
  #2 0x55ebd39f1aa9 (/usr/sbin/rsyslogd+0x18aa9)  /usr/src/debug/rsyslog-8.24.0/runtime/conf.c:190
  #3 0x55ebd3a1bd0e in processCfSysLineCommand (/usr/sbin/rsyslogd+0x42d0e)  /usr/src/debug/rsyslog-8.24.0/runtime/cfsysline.c:760
  #4 0x55ebd39f1c03 (/usr/sbin/rsyslogd+0x18c03)  /usr/src/debug/rsyslog-8.24.0/runtime/conf.c:233
  #5 0x55ebd39f539b in cnfDoCfsysline (/usr/sbin/rsyslogd+0x1c39b)  /usr/src/debug/rsyslog-8.24.0/runtime/rsconf.c:483
  #6 0x55ebd3a377d8 in yylex (/usr/sbin/rsyslogd+0x5e7d8)  /usr/src/debug/rsyslog-8.24.0/grammar/lexer.l:288
  #7 0x55ebd3a34a4d in yyparse (/usr/sbin/rsyslogd+0x5ba4d)  /usr/src/debug/rsyslog-8.24.0/grammar/grammar.c:1425
  #8 0x55ebd39f4700 (/usr/sbin/rsyslogd+0x1b700)  /usr/src/debug/rsyslog-8.24.0/runtime/rsconf.c:1306
  #9 0x55ebd3a28e1b (/usr/sbin/rsyslogd+0x4fe1b)  /usr/src/debug/rsyslog-8.24.0/tools/rsyslogd.c:1384
  #10 0x55ebd39ee293 in main (/usr/sbin/rsyslogd+0x15293)  /usr/src/debug/rsyslog-8.24.0/tools/rsyslogd.c:1866
  #11 0x7f6fc33f7504 in __libc_start_main (/usr/lib64/libc.so.6+0x22504)  ??:?
  #12 0x55ebd39ee670 (/usr/sbin/rsyslogd+0x15670)  ??:?

SUMMARY: AddressSanitizer: 24676 byte(s) leaked in 210 allocation(s).

**Comment by rgerhards** [comment]
The version you are using is very old and no longer supported by the community. It is also very probable that the problem stems back to long-solved issues. As such, please update to the currently supported version and retry. Report back if the problem persists.

The rsyslog project provides packages for current versions: https://www.rsyslog.com/downloads/download-other/

If you insist on using an outdated version, you can also contact your distro or consider [rsyslog professional services](https://www.rsyslog.com/professional-services/enterprise-support/).

**Comment by davidelang** [comment]
also note that rsyslog-8.24.0-17 is not a codebase that the rsyslog project ever 
released, it's 8.24 that we released with some set of patches created/backported 
by RedHat.

They may be able to use your report on this version, but we have many years of 
additional development between that version and the current release.

David Lang
