### ISSUE TITLE
CLOSE_WAIT socket stays in for a long time

### ISSUE THREAD

**Issue by khfayzullaev** [rsyslog/rsyslog#4252]
### Context

I have an EC2 instance with Ubuntu 18.04 running on it. I have configured Rsyslog to ship logs to Elasticsearch through Logstash. I have the following flow:

_Rsyslog &rarr; AWS Network Load Balancer &rarr; Logstash Instances &rarr; Elasticsearch_

I am using the following configuration for the [_omfwd_](https://www.rsyslog.com/doc/v8-stable/configuration/modules/omfwd.html) module:

```
action(
  type="omfwd"
  Target="aws.nlb.domain"
  Port="10516"
  Protocol="tcp"
  RebindInterval="1000"
  KeepAlive="on"
  KeepAlive.Probes="3"
  KeepAlive.Interval="15"
  KeepAlive.Time="30"
  Template="default"
)
```

I am running three instances of Logstash behind the load balancer. Most of the time, everything works fine. I have a problem when one of the Logstash instances, running behind the load balancer, goes out (either it goes down or I deliberately restart it for an upgrade).

When I restart the Logstash instance, Rsyslog receives the first _FIN_ signal from the load balancer and marks the connection as _CLOSE_WAIT_. The active and passive close steps finish pretty quickly ([ref. information](https://benohead.com/blog/2013/07/21/tcp-about-fin_wait_2-time_wait-and-close_wait/)).

However, I am encountering some issues when I terminate the Logstash instance.

### Expected behavior

When the Logstash instance gets terminated (from [AWS Doc](shttps://docs.aws.amazon.com/AWSEC2/latest/UserGuide/terminating-instances.html#what-happens-terminate), it looks like that EC2 will try to go through the graceful shutdown; and Logstash is set up via systemd), Rsyslog receives the first _FIN signal_. And the connection state changes to _CLOSE_WAIT_.  I would expect Rsyslog to execute _close()_ on the _CLOSE_WAIT_ socket faster, even if the remote server is dead after sending the first _FIN_ signal.

### Actual behavior

But, I can see from the _tcpdump_ output, the passive close takes up a substantial amount of time (from 3 to 20 minutes). Though, it looks like, Rsyslog eventually executes _close()_ on that socket.

### Steps to reproduce the behavior

I suppose that the above information would be enough to reproduce the issue. For Logstash, I used the [TCP plugin](https://www.elastic.co/guide/en/logstash/current/plugins-inputs-tcp.html) with TCP KeepAlive enabled.

### Notes

1. If an instance generates enough logs to hit the _RebindInterval_ limit, the new connection gets created pretty quickly. And the lingering _CLOSE_WAIT_ socket is not an issue in that case (it closes eventually). However, the instances that do not generate enough messages to hit the limit and re-establish new connections, they do suffer from that very socket. Or to have something like https://github.com/rsyslog/rsyslog/issues/2199, would have been great!

2. I do not consider RELP at this time. Though, It looks like a similar behavior was noticed before https://github.com/rsyslog/rsyslog/issues/1463 with [_omrelp_](https://www.rsyslog.com/doc/v8-stable/configuration/modules/omrelp.html). I should admit that I am not quite sure if they are related anyhow. The reliability of message delivery is not a priority for me. My main concern is properly handling opening and closing connections.

### Environment
- rsyslog version: 8.2002.0
- platform: ubuntu 18.04
- logstash version: 7.6.2

**Comment by rgerhards** [comment]
We don't do anything special. So I think that the load balancer does not properly follow the TCP close procedure.

**Comment by khfayzullaev** [comment]
Thanks for the quick response! I am not fully aware of the AWS NLB implementation. From quick debugging (using `ss` and `tcpdump`), I can see that Rsyslog interacts exclusively with AWS NLB. Although I also see that Logstash is opening a new direct connection to Rsyslog. And the whole interaction looks like a direct interaction between these two hosts (which, I think, is expected within the Logstash instance).

AWS NLB implantation seems to be based on some form of DSR. I will try to check my settings with a different load balancer. If I cannot reproduce the problem with the new load balancer, I will close the issue.

**Comment by khfayzullaev** [comment]
I have tried to use NGINX to proxy and load balance TCP traffic instead of AWS NLB. I was not able to reproduce the problem. I am closing this issue.

**Comment by khfayzullaev** [comment]
Hey, @rgerhards! I was able to reproduce the issue without using any load balancer. The new setup involved only two instances with Rsyslog and Logstash. I have opened a new GitHub issue with more details - https://github.com/rsyslog/rsyslog/issues/4257
