### ISSUE TITLE
Why is the time complexity of lookup_tables O(log(n)) for string keys?

### ISSUE THREAD

**Issue by gintrator** [rsyslog/rsyslog#4262]
### ~Expected behavior~ Question

I'm interested in utilizing [Lookup Tables](https://www.rsyslog.com/doc/master/configuration/lookup_tables.html) to store a potentially large amount of string keys. Looking through the documentation, I noticed that the time complexity of the `lookup` function depends on the type of keys you are storing: Array is `O(1)`, SparseArray is `O(log(n))`, and String is also `O(log(n))`, per the [Implementation Details](https://www.rsyslog.com/doc/master/configuration/lookup_tables.html#implementation-details) section.

Why is String lookup implemented using an `log(n)` algorithm? Looking at the source, it seems to share a similar implementation to the SparseArray, using a Binary Search to find matching keys. What is the rationale here? Is there a reason this can't be `O(1)` using a hashtable?

It's also true that in practice, `log(n)` is still pretty good, even as "potentially large" gets to 1k or 10k .. is there some guidance on using lookup tables to store this amount of keys/values? Is this big? Small?

I could also implement something smarter than sending global config to each rsyslog instance to limit the size of the table, e.g. shard the tables by node, since events are sourced on the same node rsyslog is running on, in this case.

Thanks for any pointers here.

**Comment by davidelang** [comment]
Just an implementation detail from the original work that was done.

very few tables are large, so rather than changing the existing string based 
table, I would suggest a 'largestring' table for what you are looking for.

There isn't a lot of guidence for your situation as there just haven't been that 
many people doing it.

David Lang

**Comment by rgerhards** [comment]
@gintrator don't underestimate the fixed time use in O(1) hashtables. Even at 10k, we have log2(10k) ~ 14, which isn't really bad. But the short answer is someone would need to implement hash tables. I didn't consider the potential win to be worth the effort.

**Comment by gintrator** [comment]
Appreciate the input! Sounds like overall this is probably a non-issue, then. And if it is, I could always look into implementing it.
