### ISSUE TITLE
relp forwarding log error

### ISSUE THREAD

**Issue by dzhcool** [rsyslog/rsyslog#4264]
**client:**
`
action(
        type="omrelp"
        Template="kafkaFileMsgOnlyFormat"
        Target="172.22.1.8"
        Port="8514"
        queue.size="10000"
        queue.maxdiskspace="1024M"
        queue.spoolDirectory="/var/log/rsyslog"
        queue.filename="push_remote"
        queue.highwatermark="6000"
        queue.lowwatermark="2000"
        queue.type="LinkedList"
        queue.saveonshutdown="on"
        queue.workerThreads="1"
        RebindInterval="2000"
)
`

**server:**
`
ruleset(name="remotelog_common"){         
        action(                               
                type="omfile"                 
                dynaFile="kafkaCommonFormat"  
                asyncWriting="off"            
                ioBufferSize="64k"            
        )                               
        stop                              
}                                         
input(type="imrelp" port="8514" Ruleset="remotelog_common") 
`

**Then the server error message:**
`
Apr 29 15:44:06 vm172-22-0-39 rsyslogd[4108]: imrelp[8514]: error 'error when receiving data, session broken', object  'lstn 8514: conn to clt 100.64.11.2/100.64.11.2' - input may not work as intended [v8.2002.0 try https://www.rsyslog.com/e/2353 ]
Apr 29 15:44:06 vm172-22-0-39 rsyslogd[4108]: imrelp[8514]: error 'error sending relp: Broken pipe', object  'lstn 8514: conn to clt 100.64.11.2/100.64.11.2' - input may not work as intended [v8.2002.0 try https://www.rsyslog.com/e/2353 ]
Apr 29 15:44:06 vm172-22-0-39 rsyslogd[4108]: netstream session 0x7f3644002330 from 100.64.11.2 will be closed due to error: Connection reset by peer [v8.2002.0 try https://www.rsyslog.com/e/2165 ]
Apr 29 15:44:07 vm172-22-0-39 rsyslogd[4108]: netstream session 0x7f3644002330 from 100.64.12.2 will be closed due to error: Connection reset by peer [v8.2002.0 try https://www.rsyslog.com/e/2165 ]
`

**Comment by rgerhards** [comment]
looks like a network problem

**Comment by dzhcool** [comment]
100.64.11.2/100.64.11.2 is not a LAN IP.

LAN ip : 172.22.1.0/24  172.22.0.0/24
