### ISSUE TITLE
inconsistent include behavior

### ISSUE THREAD

**Issue by davidelang** [rsyslog/rsyslog#4271]
### Expected behavior
include files in alpha sort order
### Actual behavior
it works differently on centos 6 vs centos 7 (also a ubuntu of some unknown version)
in my examples, the result ends up correct, but an inconsistancy like this (processing file by file vs recursive-like processing) worries me

### Environment
8.2001

on centos 6

# cat include1
# include1

# cat include2
#include2

# cat test.conf
$IncludeConfig ./include*

# rsyslogd -o test.result -f test.conf
rsyslogd: there are no active actions configured. Inputs would run, but no output whatsoever were created. [v8.2001.0 try https://www.rsyslog.com/e/2103 ]
rsyslogd: run failed with error -2103 (see rsyslog.h or try https://www.rsyslog.com/e/2103 to learn what that number means)

# cat test.result
##### BEGIN CONFIG: test.conf
$IncludeConfig ./include*./include*
##### BEGIN CONFIG: ./include1
# include1

##### END   CONFIG: ./include1
#include2

##### END   CONFIG: test.conf

on centos 7

# cat include1
#1

# cat include2
#2

# cat test.conf
$IncludeConfig include*

# rsyslogd -f test.conf -o test.results
rsyslogd: there are no active actions configured. Inputs would run, but no output whatsoever were created. [v8.2002.0 try https://www.rsyslog.com/e/2103 ]
rsyslogd: run failed with error -2103 (see rsyslog.h or try https://www.rsyslog.com/e/2103 to learn what that number means)
[root@s8392cplv ~]# cat test.results
##### BEGIN CONFIG: test.conf
$IncludeConfig include*include*
##### BEGIN CONFIG: include1
#1

##### END   CONFIG: include1
#2

**Comment by rgerhards** [comment]
I guess this is a problem with the `-o'  option. It possibly takes the input buffer too early. The actual order is correct (99.99999% sure). Will verify.

**Comment by davidelang** [comment]
I initially thought I had a sample that included files in the wrong order 
(resulting in a stop happening at the wrong place) but was not able to reproduce 
it

I started looking at this because things weren't behaving properly on one 
machine, and it looked like the include order was wrong (20*.conf after 
35*.conf) but the real problem ended up being elsewhere.

David Lang

**Comment by alorbach** [comment]
I think the reverse read order of the configuration files is done intentional after reading the comments in the code: 
https://github.com/rsyslog/rsyslog/blob/a8e9a90888ed07ac1ffe245aeecfb0400dae0c14/grammar/rainerscript.c#L5304

```
/* note: bison "stacks" the files, so we need to submit them
	 * in reverse order to the *stack* in order to get the proper
	 * parsing order. Also see
	 * http://bugzilla.adiscon.com/show_bug.cgi?id=411
	 */
```

I will see if I can get this bugzilla bug from our internal backups.

**Comment by rgerhards** [comment]
I remember this case, but that does not reverse the order, but put them *in the right order* on the BISON stack - so they get pulled and processed in the correct order. Can you check that this actually happens correctly by doing a test?

**Comment by alorbach** [comment]
I did a quick test on ubuntu 20 and it loads my config files in reserve order:


> /git/rsyslog$ sudo /usr/sbin/rsyslogd -dn -f /etc/rsyslog.conf -o test.results 2>&1 | grep "requested"
> 5678.052026127:main thread    : obj.c: caller requested object 'net', not found (iRet -3003)
> 5678.052080331:main thread    : modules.c: source file conf.c requested reference for module 'lmnet', reference count now 1
> 5678.052099068:main thread    : modules.c: source file rsyslogd.c requested reference for module 'lmnet', reference count now 2
> 5678.052382085:main thread    : modules.c: source file omfwd.c requested reference for module 'lmnet', reference count now 3
> 5678.053150281:main thread    : rainerscript.c: requested to include config file '/etc/rsyslog.d/50-default.conf'
> 5678.053163427:main thread    : rainerscript.c: requested to include config file '/etc/rsyslog.d/20-ufw.conf'
>

**Comment by alorbach** [comment]
I deleted my previous comment, it was misleading. Yes the configuration files are put in reverse order on BISON stack, so that the last configuration file is on top of the BISON stack. It then gets processed in correct order. 

The "BEGIN CONFIG:" outputs maybe misleading as they happen when the config file is put on BISON stack.

**Comment by rgerhards** [comment]
Thx, I'll change that text a bit as it seems to be misleading.
