### ISSUE TITLE
Swtiching rsyslog client to rsyslog server not working

### ISSUE THREAD

**Issue by Priyanka2092** [rsyslog/rsyslog#4289]
### Expected behavior

It is expected from an rsyslog server machine to log events from rsyslog client machine. I am expecting a new directory in /var/log/RemoteHost with rsylog client IP-address. 

### Actual behavior
But, it is only logging its own events under the directory named localhost inside /var/log/RemoteHost

### Steps to reproduce the behavior
Initially, I had configured my CentOS 7 machine to act as rsyslog client by adding the following entry in rsyslog.conf file in forwarding rule section at the end of the file:

`*.* @<server-IP-Address>:514`

It worked perfectly fine. 

Now, I added below entries in rsyslog.conf file above GLOBAL DIRECTIVES section in order to make it rsyslog server machine:

```
$template RemoteLogs,"/var/log/RemoteHost/%fromhost%/programname/%programname%.log"
*.* ?RemoteLogs
```

After I restart rsylog using
`systemctl restart rsyslog`

### Environment
- rsyslog version: rsyslogd 8.24.0-38.e17 
- platform: CentOS 7 (1908)

**Comment by rgerhards** [comment]
use `fromhost-ip` instead of `fromhost` if you want the IP address. `fromhost` is the hostname and falls back to IP only if hostname cannot be resolved.

**Comment by Priyanka2092** [comment]
Thank you for your reply.
After the changes you mentioned. I started getting the server local IP address (127.0.0.1) directory (/var/log/RemoteHost/127.0.0.1). it has same entries as before
what I want to do is to get the logs from the client machine inside /var/log/RemoteHost.
Currently, i am only getting its own logs.

I am sending logger "test from client" from my client machine but I am not getting this in my server.

**Comment by Priyanka2092** [comment]
Here are my rsyslog.conf for server and client machines.
**Server rsyslog.conf file:**
```
# rsyslog configuration file

# For more information see /usr/share/doc/rsyslog-*/rsyslog_conf.html
# If you experience problems, see http://www.rsyslog.com/doc/troubleshoot.html

#### MODULES ####

# The imjournal module bellow is now used as a message source instead of imuxsock.
$ModLoad imuxsock # provides support for local system logging (e.g. via logger command)
$ModLoad imjournal # provides access to the systemd journal
#$ModLoad imklog # reads kernel messages (the same are read from journald)
#$ModLoad immark  # provides --MARK-- message capability

# Provides UDP syslog reception
$ModLoad imudp
$UDPServerRun 514

# Provides TCP syslog reception
#$ModLoad imtcp
#$InputTCPServerRun 514

$template RemoteLogs,"/var/log/RemoteHost/%fromhost%/programname/%programname%.log"
*.* ?RemoteLogs


#### GLOBAL DIRECTIVES ####

# Where to place auxiliary files
$WorkDirectory /var/lib/rsyslog

# Use default timestamp format
$ActionFileDefaultTemplate RSYSLOG_TraditionalFileFormat

# File syncing capability is disabled by default. This feature is usually not required,
# not useful and an extreme performance hit
#$ActionFileEnableSync on

# Include all config files in /etc/rsyslog.d/
$IncludeConfig /etc/rsyslog.d/*.conf

# Turn off message reception via local log socket;
# local messages are retrieved through imjournal now.
$OmitLocalLogging on

# File to store the position in the journal
$IMJournalStateFile imjournal.state


#### RULES ####

# Log all kernel messages to the console.
# Logging much else clutters up the screen.
#kern.*                                                 /dev/console

# Log anything (except mail) of level info or higher.
# Don't log private authentication messages!
*.info;mail.none;authpriv.none;cron.none                /var/log/messages

# The authpriv file has restricted access.
authpriv.*                                              /var/log/secure

# Log all the mail messages in one place.
mail.*                                                  -/var/log/maillog


# Log cron stuff
cron.*                                                  /var/log/cron

# Everybody gets emergency messages
*.emerg                                                 :omusrmsg:*

# Save news errors of level crit and higher in a special file.
uucp,news.crit                                          /var/log/spooler

# Save boot messages also to boot.log
local7.*                                                /var/log/boot.log


# ### begin forwarding rule ###
# The statement between the begin ... end define a SINGLE forwarding
# rule. They belong together, do NOT split them. If you create multiple
# forwarding rules, duplicate the whole block!
# Remote Logging (we use TCP for reliable delivery)
#
# An on-disk queue is created for this action. If the remote host is
# down, messages are spooled to disk and sent when it is up again.
#$ActionQueueFileName fwdRule1 # unique name prefix for spool files
#$ActionQueueMaxDiskSpace 1g   # 1gb space limit (use as much as possible)
#$ActionQueueSaveOnShutdown on # save messages to disk on shutdown
#$ActionQueueType LinkedList   # run asynchronously
#$ActionResumeRetryCount -1    # infinite retries if host is down
# remote host is: name/ip:port, e.g. 192.168.0.1:514, port optional
#*.* @@remote-host:514
# ### end of the forwarding rule ###
```
**Client rsyslog.conf file:**

```
# rsyslog configuration file

# For more information see /usr/share/doc/rsyslog-*/rsyslog_conf.html
# If you experience problems, see http://www.rsyslog.com/doc/troubleshoot.html

#### MODULES ####

# The imjournal module bellow is now used as a message source instead of imuxsock.
$ModLoad imuxsock # provides support for local system logging (e.g. via logger command)
$ModLoad imjournal # provides access to the systemd journal
#$ModLoad imklog # reads kernel messages (the same are read from journald)
#$ModLoad immark  # provides --MARK-- message capability

# Provides UDP syslog reception
#$ModLoad imudp
#$UDPServerRun 514

# Provides TCP syslog reception
#$ModLoad imtcp
#$InputTCPServerRun 514


#### GLOBAL DIRECTIVES ####

# Where to place auxiliary files
$WorkDirectory /var/lib/rsyslog

# Use default timestamp format
$ActionFileDefaultTemplate RSYSLOG_TraditionalFileFormat

# File syncing capability is disabled by default. This feature is usually not required,
# not useful and an extreme performance hit
#$ActionFileEnableSync on

# Include all config files in /etc/rsyslog.d/
$IncludeConfig /etc/rsyslog.d/*.conf

# Turn off message reception via local log socket;
# local messages are retrieved through imjournal now.
$OmitLocalLogging on

# File to store the position in the journal
$IMJournalStateFile imjournal.state


#### RULES ####

# Log all kernel messages to the console.
# Logging much else clutters up the screen.
#kern.*                                                 /dev/console

# Log anything (except mail) of level info or higher.
# Don't log private authentication messages!
*.info;mail.none;authpriv.none;cron.none                /var/log/messages

# The authpriv file has restricted access.
authpriv.*                                              /var/log/secure

# Log all the mail messages in one place.
mail.*                                                  -/var/log/maillog


# Log cron stuff
cron.*                                                  /var/log/cron

# Everybody gets emergency messages
*.emerg                                                 :omusrmsg:*

# Save news errors of level crit and higher in a special file.
uucp,news.crit                                          /var/log/spooler

# Save boot messages also to boot.log
local7.*                                                /var/log/boot.log


# ### begin forwarding rule ###
# The statement between the begin ... end define a SINGLE forwarding
# rule. They belong together, do NOT split them. If you create multiple
# forwarding rules, duplicate the whole block!
# Remote Logging (we use TCP for reliable delivery)
#
# An on-disk queue is created for this action. If the remote host is
# down, messages are spooled to disk and sent when it is up again.
#$ActionQueueFileName fwdRule1 # unique name prefix for spool files
#$ActionQueueMaxDiskSpace 1g   # 1gb space limit (use as much as possible)
#$ActionQueueSaveOnShutdown on # save messages to disk on shutdown
#$ActionQueueType LinkedList   # run asynchronously
#$ActionResumeRetryCount -1    # infinite retries if host is down
# remote host is: name/ip:port, e.g. 192.168.0.1:514, port optional
#*.* @@remote-host:514
*.* @<server-ip-address>:514
# ### end of the forwarding rule ###
```

**Comment by rgerhards** [comment]
If you do not want to have the local logs logged somehwere else, delete everything at the server machine after

```
$template RemoteLogs,"/var/log/RemoteHost/%fromhost%/programname/%programname%.log"
*.* ?RemoteLogs
```

Processing logs does not automatically stop when one action is triggered - it flows through... (else you could never do more than one "thing" per message).

**Comment by rgerhards** [comment]
Oh, I see the question on the clients... are you sure server address is correct? Any firewall in between? Can you verify via e.g. Wireshark that the packages really arrive?

BTW: troubleshooting is easier if you use TCP logging instead of UDP as rsyslog can then detect connection issues.

**Comment by Priyanka2092** [comment]
Using TCP also didn't work.

I try to elaborate my problem

1. I have one CentOS minimal install machine 
2. second CentOS minimal install machine (Virtual Box).
3. Both machines are reachable (checked via Ping command)

**1st Test:**
1. I made (machine 1) as **rsyslog client.**
2. And (machine 2-VirtualBox) as **rsyslog server.**
(rsyslog.conf file of both machines are given in the above comment)

**Test Worked Perfectly fine**
- sent a command (`logger "test from client"`) from client machine
- Could see this event in` /var/log/RemoteHost/<client-ip-address/programname/programname.log> `on the server machine.

**2nd Test**

**(switching the Roles of client and server).**

1. I made (machine 1) as **rsyslog server.**
2. And (machine 2-VirtualBox) as **rsyslog client**.
(rsyslog.conf file of both machines are given in the above comment)

**Test Failed**
- sent a command (`logger "test from client"`) from client machine
- Could NOT see any event logging from client machine (RemoteHost just has server log directory).

**Comment by rgerhards** [comment]
> 3\. Both machines are reachable (checked via Ping command)

This doesn't tell you anything about the syslog ports.

Which error messages did rsyslog emit?

**Comment by Priyanka2092** [comment]
rsyslog doesn't give any error message on both machines when I start my rsyslog service using`
systemctl restart rsyslog`

And` netstat -an | grep 514` gives the following result:
```
udp 0 0 0.0.0.0:514 0.0.0.0:*  
udp6 0 0 :::514 :::*
```

**Comment by rgerhards** [comment]
> rsyslog doesn't give any error message on both machines when I start my rsyslog service using

have you checked the logs or at least `systemctl status rsyslog`?

If they are clean, it looks like the journal does not forward logger messages - at least there is no other explanation. From the rsyslog side, it looks good.

Note: inability to establish a TCP connection results in an error message.

**Comment by Priyanka2092** [comment]
Yes. the `systemctl status rsyslog` of both machines is clean. 

The thing strange for me is that it works perfectly when I make the machine 1 as client and the other as server.

When I change the roles of the machines by changing the entries of the rsyslog.conf files. Everything stops.

It looks like, if we configure one machine as a client, we can never configure it as server again. is it true?

**Comment by rgerhards** [comment]
> It looks like, if we configure one machine as a client, we can never configure it as server again. is it true?

no, rsyslog just reads its config file, and that's all as far as rsyslog is concerned. That said, I have no idea why it does not work (and not report errors) in your case. 

Possibly this stems back to a bug in the old version you are using. It is possible that the problem stems back to long-solved issues. As such, please update to the currently supported version and retry. Report back if the problem persists.

The rsyslog project provides packages for current versions: https://www.rsyslog.com/downloads/download-other/

If you insist on using an outdated version, you can also contact your distro or consider [rsyslog professional services](https://www.rsyslog.com/professional-services/enterprise-support/).

**Comment by Priyanka2092** [comment]
Will it make any difference, if I remove the rsyslog service from both machines and re-install it and then configure them as client and server?

**Comment by rgerhards** [comment]
> Will it make any difference, if I remove the rsyslog service from both machines and re-install it and then configure them as client and server?

I don't think so. As I say, rsyslog processes the config file - that's it. It does not talk to the firewall or something different...

**Comment by Priyanka2092** [comment]
Thank you so much for your response. It was my mistake. 
The firewall on server machine was somehow enabled, that was stopping the reception of logs from the client.

I disabled it, and now it is working.
Thank you once again!
