### ISSUE TITLE
read_file from backtick `cat` call causes rsyslog to segfault

### ISSUE THREAD

**Issue by Mskeffington** [rsyslog/rsyslog#4290]
https://github.com/rsyslog/rsyslog/blob/7f79730e496e7bee559d83f69c10826e094f5032/grammar/lexer.l#L150

There should be a NULL check here so es_newStrFromCStr doesnt segfault.  Otherwise, including `cat <file that doesnt exist>` will crash rsyslog and prevent it from correctly starting. 

the docs explicitly state 
> cat filename - It will evaluate to the content of the given file. Only a single file name is supported. If the file is not readable, it will evaluate to an empty string.

https://www.rsyslog.com/doc/master/rainerscript/constant_strings.html

rsyslog 8.37.0
libestr version 0.1.11 
built from Yocto Linux build

**Comment by davidelang** [comment]
what version of rsyslog on what OS?

David Lang

**Comment by Mskeffington** [comment]
see above.  I edited report like 2 minutes after filing it to add that info.

**Comment by rgerhards** [comment]
bug confirmed in current master
