### ISSUE TITLE
Wrong month in datestamp of operating state file messages

### ISSUE THREAD

**Issue by ebsf1** [rsyslog/rsyslog#4292]
### Expected behavior

The datestamp of messages in the rsyslog operating state file reflects the current month.

### Actual behavior

The datestamp of messages in the rsyslog operating state file reflects the prior month.

From today (20 May 2020):
- System 1 (Ubuntu 16.04, rsyslog 8.2004):
`20200420-125812: STATE INITIALIZING 8.2004.0`
- System2 (Ubuntu 18.04, rsyslog 8.2004):
`20200420-124142: STATE INITIALIZING 8.2004.0`

### Steps to reproduce the behavior

`sudo cat rsyslog.opg-state`

### Environment
- rsyslog version: 8.2004
- platform: Both Ubuntu 16.04 & 18.04
- for configuration questions/issues, include rsyslog.conf and included config files

**Comment by rgerhards** [comment]
I can confirm the bug, thx for reporting.

Info: bug is obvious and unlikely to re-appear in this exact case. Adding CI test thus does not make sense.
