### ISSUE TITLE
imrelp binds on restart, not on boot; Then, fails to connect

### ISSUE THREAD

**Issue by ebsf1** [rsyslog/rsyslog#4293]
I posted to the mailing list just now what is essentially an update to this post.  The relevant parts are as follows:

Several problems with RELP, including listener dependencies and connection.

The RELP listener is failing to bind to its configured port on boot but succeeds on restart (i.e., systemctl restart rsyslog).  This suggests a dependency issue but I'm not sufficiently familiar with the rsyslog dependencies to intelligently revise rsyslog.service.  Perhaps this may only require changing Restart=on-failure to Restart=always (with corresponding addition of StartLimitIntervalSec=0, so as not to limit restarts) but I imagine a more elegant solution, i.e., revising the dependencies with an After= or Requires= parameter, exists.

From the operating state file (also note the incorrect datestamp, which reflects the prior month) after boot:

```
20200425-061625: STATE INITIALIZING 8.2004.0
20200425-061625: MSG   debug log file is '/var/log/rsyslog.debug', fd 7
20200425-061625: MSG   imrelp[20514]: error 'error while binding relp tcp socket on port '20514'', object  'lstn 20514' - input may not work as intended
20200425-061625: MSG   imrelp: could not activate relp listener, code 10005
```

After restart  (i.e., systemctl restart rsyslog), the two imrelp entries no longer appear and ss reveals that the port is being listened on.

This reveals the next problem, which is the absence of a RELP connection.  Oddly, this connection existed briefly last week but I then was in the process of learning that socket= is a mandatory input parameter for imuxsock (even for the system socket) and so no sender log files exist then--the only evidence is the presence of sender message files on the receiver.  Also, because I hadn't then realized the RELP listener only was bound after a restart, it was only on by chance and there are only a handful of messages, none relevant.

SELinux is not configured.

I also note that messages from a third device via imudp are written as configured, so a bit is working.

The current error messages (as follow) suggest a librelp issue, but it persists even after tls="off" is expressly set, on both the sender's omrelp action statement and the receiver's imrelp input statement.  This also does not explain last week's brief connection.

From the sender's operating state file (also note the datestamp issue exists on this system also (U18.04/r8.2004):
```

20200425-075506: MSG   rsyslogd fully started up and initialized - begin actual processing
20200425-075516: MSG   omrelp[192.168.1.2:20514]: error 'error opening connection to remote peer', object  'conn to srvr 192.168.1.2:20514' - action may not work as intended
20200425-075516: MSG   omrelp[192.168.1.2:20514]: error 'error opening connection to remote peer', object  'conn to srvr 192.168.1.2:20514' - action may not work as intended
20200425-075516: MSG   omrelp: could not connect to remote server, librelp error 10015
20200425-075516: MSG   action 'act.omrelp' suspended (module 'omrelp'), retry 0. There should be messages before this one giving the reason for suspension.
20200425-075516: MSG   omrelp: could not connect to remote server, librelp error 10015
20200425-075516: MSG   action 'act.omrelp' suspended (module 'omrelp'), retry 0. There should be messages before this one giving the reason for suspension.
```

From the sender's rsyslog.conf:

```
module(
                load="omrelp"
)

ruleset(name="rst.omrelp"){
                action(
                                name="act.omrelp"
                                type="omrelp"
                                target="192.168.1.2"
#                             port="601"
                                port="20514"
                                template="tpl.msg-basic"
                                action.errorFile="act.omrelp.error"
                                action.reportSuspension="on"
                                action.reportSuspensionContinuation="on"
                                action.resumeInterval="5"
                                action.resumeIntervalMax="30"
                                action.resumeRetryCount="-1"
                                queue.checkpointInterval="100"
                                queue.filename="relp.queue"
                                queue.highWatermark="600"
                                queue.lightDelayMark="0"
                                queue.lowWatermark="10"
                                queue.maxDiskSpace="15g"
                                queue.maxFilesize="10m"
                                queue.saveonshutdown="on"
                                queue.size="1000"
                                queue.spooldirectory="/var/log"
                                queue.syncqueuefiles="on"
                                queue.type="LinkedList"
                                tls="off"
                )
                call rst.omfile
}

input(
                type="imuxsock"
                ruleset="rst.omrelp"
                socket="/run/systemd/journal/syslog"
)
```

### Expected behavior

omrelp loads, binds to the configured port, activates the listener, and accepts a connection.

### Actual behavior

imrelp fails to bind to the tcp socket on boot but does, on restart (i.e., systemctl restart rsyslog).  Once bound and listening, no connection occurs.

### Steps to reproduce the behavior

See 
[rsyslog.conf.txt](https://github.com/rsyslog/rsyslog/files/4678417/rsyslog.conf.txt)

**Comment by ebsf1** [comment]
Revising rsyslog.service to restart always has no effect on the failure of the RELP listener to bind on boot.  The procedure was to first disable the service (symlink to /lib/systemd/...), copy rsyslog.service (from /lib/systemd/... to /etc/systemd/...), edit, enable (to create symlink to /etc/systemd/...), and reboot.

From the operating state file after boot but before restart:

```
20200428-203101: STATE INITIALIZING 8.2004.0
20200428-203101: MSG   debug log file is '/var/log/rsyslog.debug', fd 7
20200428-203101: MSG   imrelp[20514]: error 'error while binding relp tcp socket on port '20514'', object  'lstn 20514' - input may not work as intended
20200428-203101: MSG   imrelp: could not activate relp listener, code 10005
20200428-203101: MSG   imuxsock: Acquired UNIX socket '/run/systemd/journal/syslog' (fd 3) from systemd.

20200428-203101: MSG   imuxsock: Acquired UNIX socket '/run/systemd/journal/syslog' (fd 3) from systemd.

20200428-203101: MSG   act.ipt-file-F queue: queue files exist on disk, re-starting with 1 messages. This will keep the disk queue file open, details: https://rainer.gerhards.net/2013/07/rsyslog-why-disk-assisted-queues-keep-a-file-open.html
20200428-203101: MSG   file '/var/log/ipt-file.queue-F.00000002': open error
20200428-203101: MSG   act.ipt-file-F queue: qDeqDisk error happened at around offset 0
20200428-203101: MSG   act.ipt-file-F queue: error dequeueing element - ignoring, but strange things may happen
20200428-203101: MSG   fatal error on disk queue 'act.ipt-file-F queue', emergency switch to direct mode
20200428-203101: MSG   rsyslogd fully started up and initialized - begin actual processing
```
From the operating state file after restart (systemctl restart rsyslog)(note the absence of the imrelp errors appearing above):

```
20200429-062109: MSG   rsyslogd shutting down
20200429-062109: STATE CLEAN CLOSE
20200429-062109: STATE INITIALIZING 8.2004.0
20200429-062109: MSG   debug log file is '/var/log/rsyslog.debug', fd 7
20200429-062109: MSG   imuxsock: Acquired UNIX socket '/run/systemd/journal/syslog' (fd 3) from systemd.

20200429-062109: MSG   imuxsock: Acquired UNIX socket '/run/systemd/journal/syslog' (fd 3) from systemd.

20200429-062109: MSG   act.ipt-file-F queue: queue files exist on disk, re-starting with 1 messages. This will keep the disk queue file open, details: https://rainer.gerhards.net/2013/07/rsyslog-why-disk-assisted-queues-keep-a-file-open.html
20200429-062109: MSG   file '/var/log/ipt-file.queue-F.00000002': open error
20200429-062109: MSG   act.ipt-file-F queue: qDeqDisk error happened at around offset 0
20200429-062109: MSG   act.ipt-file-F queue: error dequeueing element - ignoring, but strange things may happen
20200429-062109: MSG   fatal error on disk queue 'act.ipt-file-F queue', emergency switch to direct mode
20200429-062109: MSG   rsyslogd fully started up and initialized - begin actual processing
```
ss -tulpen returns (note listening but no connection):

`tcp   LISTEN     0      55                          192.168.1.2:20514                                             *:*                   ino:92470 sk:c <->`

**Comment by alorbach** [comment]
Can you enable debug logging in rsyslog configuration and attach a debug log to this issue? 
The debug log will contain the actual errno which shows the reason why the relp port could not be bound.

**Comment by ebsf1** [comment]
Thanks for your response.  The file is attached.  It is a bit long because I configured it to generate from boot, and then rsyslogd would not respond to kill signals, so I had to take some time to reconfigure rsyslog.service before rebooting to stop the debug logging process.  I split the file into five because the interface here rejected files >10MB.  It may be that only the first is relevant.

I should say that I was alarmed when reading the log to see rsyslog recursing through data directories on this machine, which it obviously has no business doing.  I noted several files were accessed and am doing what I can to evaluate the extent of any corruption.  Please consider that another issue, which I would expect to be troublesome to the entire installed base.

[debug00.txt](https://github.com/rsyslog/rsyslog/files/4730318/debug00.txt)
[debug01.txt](https://github.com/rsyslog/rsyslog/files/4730319/debug01.txt)
[debug02.txt](https://github.com/rsyslog/rsyslog/files/4730320/debug02.txt)
[debug03.txt](https://github.com/rsyslog/rsyslog/files/4730322/debug03.txt)
[debug04.txt](https://github.com/rsyslog/rsyslog/files/4730323/debug04.txt)

**Comment by rgerhards** [comment]
> I should say that I was alarmed when reading the log to see rsyslog recursing through data directories on this machine, which it obviously has no business doing. I noted several files were accessed and am doing what I can to evaluate the extent of any corruption.

can you let us know some of the files/dirs that you are concerned about -- that makes it easier to verify if it is correct or not.

**Comment by ebsf1** [comment]
Thanks for responding.  Run

`cat _filename_ | grep 'data'`

In the consolidated debug file, this yields 11897 lines.

**Comment by rgerhards** [comment]
as the debug log is not from the rsyslog start, the problem section related to RELP binding is not included and so the log cannot be used to get further insight. Pls post one immediately from the start.

**Comment by ebsf1** [comment]
Thanks for responding, and understood.

Regarding your first point, I split the debug log file into five because this interface would not accept files >10MB.  Are you referring to the file debug00.txt when you say it is not from the start of the run?

If so, then that is curious because I ran rsyslogd with the -d option by editing the rsyslog.service file to include it in the ExecStart= directive, then rebooting.  The idea was to begin capturing debug information as soon as rsyslogd launched during the normal boot process.  If you are referring to debug00.txt, then this approach must be missing something.  I can try disabling the .service and generating another log file by running rsyslogd interactively instead.  Please let me know.

Regarding your second point, understood that another process is sending these messages but I now am wondering how to discern which because none is obvious.  I'll start with the rsyslogd logs and go from there but any suggestions on this front would be helpful.

**Comment by alorbach** [comment]
@ebsf1 we need the debug log from the syslog start at boot time where the relp port binding fails. 
Enable it using configuration options $DebugFile and $DebugLevel (See here https://www.rsyslog.com/doc/v8-stable/troubleshooting/debug.html?highlight=debugfile ) and reboot the machine.

**Comment by ebsf1** [comment]
@alorbach , thanks.  This time, I substituted the following in /etc/environment for the -d option in rsyslog.service:
```
RSYSLOG_DEBUG="Debug"
RSYSLOG_DEBUGFILE="/var/log/rsyslog.debug"
```
It looks as if this approach captures debug information earlier in the boot process, and that the file may have the relevant information this time.

Thanks again
[rsyslog.debug.txt](https://github.com/rsyslog/rsyslog/files/4736448/rsyslog.debug.txt)

**Comment by rgerhards** [comment]
@ebsf1 does rsyslog run under systemd control? I guess so. If yes, then please post the systemd unit file.

**Comment by rgerhards** [comment]
could this be related? https://github.com/rsyslog/rsyslog-pkg-rhel-centos/issues/72

**Comment by ebsf1** [comment]
@rgerhards yes, it does run under systemd.  In fact, I wondered in my initial post on this issue whether this was a dependency issue.  The rsyslog.service is attached but to save the suspense, it lacks the two dependencies mentioned in your link.

While you are reviewing this debug file, I wanted also to call your attention to the fact that I also am observing certain rules in an imuxsock ruleset operate on restart but not on boot.  I noted these in https://github.com/rsyslog/rsyslog/issues/4299  There are additional problems with the ruleset but those probably should be discussed under that issue.

I'll revise rsyslog.service to add the dependencies mentioned in your link, and advise.  Pending that, the current rsyslog.service is attached.
[rsyslog.service.txt](https://github.com/rsyslog/rsyslog/files/4736961/rsyslog.service.txt)

**Comment by ebsf1** [comment]
@rgerhards adding the dependencies in your link (then disabling and re-enabling rsyslog.service, then rebooting) had some effect but not complete effect.  The new rsyslog.service file is attached.

[rsyslog.service.new.txt](https://github.com/rsyslog/rsyslog/files/4737446/rsyslog.service.new.txt)

So, this:

- Fixed the listener
- Fixed the imuxsock ruleset rules containing filters (a) if programname == "rsyslogd" and (b) :programname,isequal,"rsyslogd"

What continues to fail is:

- The above imuxsock ruleset rule :programname,isequal,"rsyslogd" continues to ignore the module parameters concerning directory and file, but observes the module parameter concerning template, as noted in (https://github.com/rsyslog/rsyslog/issues/4299)
- Also as noted in (https://github.com/rsyslog/rsyslog/issues/4299) , imuxsock rules with filters (a) if $msg contains "iptb" and (b) :msg,contains,"iptb" continue to fail but operate when not in an imuxsock ruleset.
- No RELP connection occurs notwithstanding that the listener has bound to the port (i.e., the same behavior as before, after restart) BUT does occur after the sender (U18.05/r8.2004) is rebooted.  The sender's operating state file reads:

```
20200505-070706: MSG   omrelp: could not connect to remote server, librelp error 10014
20200505-070706: MSG   action 'act.omrelp' suspended (module 'omrelp'), retry 0. There should be messages before this one giving the reason for suspension.
20200505-070706: MSG   omrelp[192.168.1.2:20514]: error 'error opening connection to remote peer', object  'conn to srvr 192.168.1.2:20514' - action may not work as intended
```
with the last message appearing repeatedly until reboot.  The sender's rsyslog.conf file also is attached.
[rsyslog.conf.txt](https://github.com/rsyslog/rsyslog/files/4737455/rsyslog.conf.txt)

Thanks again

**Comment by ebsf1** [comment]
I tinkered a bit with the dependencies yesterday and found that the only one necessary (for these purposes, at least) is:

`After=network-online.target`

The other continuing failures mentioned above remain, however.

I should note that imudp (_i.e._, rules in a ruleset called by an imudp input module) has been working without this dependency, however.

I'm not certain how adding this dependency may affect the logging of local system messages before this target is reached and after syslog.socket.

**Comment by ebsf1** [comment]
I now note that once the RELP listener (imrelp) binds to its port, the remote RELP sending system is able to connect and transmit its messages.

The above-mentioned issues with selective rule operation and selective implementation of imuxsock module parameters, persist.

**Comment by rgerhards** [comment]
so this issue is solved. Let's not complicate things by mixing up issues. IIRC there is a separate one for the (different) issue of imuxsock problems you experience.
