### ISSUE TITLE
rsyslog does not forward logs to new IP address, when DNS A record is updated

### ISSUE THREAD

**Issue by CaledoniaProject** [rsyslog/rsyslog#4298]
### Software version

I'm testing this behavior on CentOS 6, if it's already fixed I can recompile and test a newer version:

```
# rpm -qa | grep rsyslog
rsyslog-5.8.10-10.el6_6.x86_64
```

### Step to reproduce

Configured rsyslogd to forward logs to `log1.example.com`

```
*.* @log1.example.com:514
```

Create a test log with `logger` command

```
logger -t test RANDOM_STRING
```

And I confirm it's received on the remote host by grepping the files.

Then I change the DNS A record of `log1.example.com` to another IP, wait for TTL to expire, and confirm the IP has changed with `dig` command.

If I execute the logger command again, the log is still sent to the old IP address.

### Conclusion

rsyslogd would never update the IP address, unless I manually restart the rsyslog daemon. Is it by design?

**Comment by davidelang** [comment]
rsyslog doesn't check the DNS for every message sent, at most it will check the 
IP when you do a HUP, but it may require a restart.

David Lang

**Comment by CaledoniaProject** [comment]
As discussed in the mailing list, the following configuration can resolve this problem

* $ActionSendTCPRebindInterval (>= 4.5.1)
* $ActionSendUDPRebindInterval (>= 4.3.2)

Closing this thread.
