### ISSUE TITLE
Reading rotating logs with "imfile"

### ISSUE THREAD

**Issue by naveenCyberSpace** [rsyslog/rsyslog#4308]
### Expected behavior
Hi Experts,

Please help

I am fairly new to Rsyslog
My requirement is to copy log trail to another server.

ServerA  - Log Sending server
ServerB - Log Receiving server

ServerA receives syslogs through Rsyslog and are store in a file location like below:

/fixedPath/symlinkPath/fixedFolder/_rotatingFileName.log_

For example:
 /fixedPath/symlinkPath/fixedFolder/**2020-06-02T14-35-21.330227Z.log**

"rotatingFileName.log" changes after file size reaches a limit.

**Config file is as below:**

module(load="imfile" mode="inotify") #needs to be done just once
input(type="imfile"
     File="/fixedPath/symlinkPath/fixedFolder/*.log"
     Tag="RAWLOG"
     Severity="info"
     Facility="local7")

:syslogtag, isequal, "RAWLOG" {
   local7.* action(type="omfwd" target="1.2.3.4" port="514" protocol="udp")
   &stop
}
### Actual behavior

Whenever "_**rotatingFileName.log**_" changes, logs are stops from being forwarded to target syslog server.
But if I restart, then the data starts moving again. As soon as the file is rotated, it stops again.

### Question

How do I make rsyslog read the rotated filename? 

### Environment
- rsyslog version: rsyslogd 8.24.0, compiled with:
        PLATFORM:                               x86_64-pc-linux-gnu
        PLATFORM (lsb_release -d):
        FEATURE_REGEXP:                         Yes
        GSSAPI Kerberos 5 support:              Yes
        FEATURE_DEBUG (debug build, slow code): No
        32bit Atomic operations supported:      Yes
        64bit Atomic operations supported:      Yes
        memory allocator:                       system default
        Runtime Instrumentation (slow code):    No
        uuid support:                           Yes
        Number of Bits in RainerScript integers: 64

- platform: Debian 4
- for configuration questions/issues, include rsyslog.conf and included config files

Thanks

**Comment by rgerhards** [comment]
You need to add the `reopenOnTruncate="on"` parameter to your input definition. Note that truncation always almost results in loss of some messages (because of the method used, not a bug).

Full doc: https://www.rsyslog.com/doc/v8-stable/configuration/modules/imfile.html
