### ISSUE TITLE
Question: Have only one entry logged

### ISSUE THREAD

**Issue by silvio** [rsyslog/rsyslog#4320]
Is it possible to have only one entry logged in the logfile at a time? The use case is as follows: I have a program which generates data every few seconds, which is then sent via `logger` and `syslog()` to `RSYSLOG`. This data is processed by another process, but this process can handle only one instance of that data. 

For debugging purposes another file is created which contains all instances of the data.

I assume that this can be solved with a 'ruleset', but I am not sure. Maybe someone has some pointers for me.

### Environment

~~~text
# rsyslogd -v
rsyslogd 8.22.0, compiled with:
        PLATFORM:                               arm-poky-linux-gnueabi
        PLATFORM (lsb_release -d):
        FEATURE_REGEXP:                         Yes
        GSSAPI Kerberos 5 support:              No
        FEATURE_DEBUG (debug build, slow code): No
        32bit Atomic operations supported:      Yes
        64bit Atomic operations supported:      No
        memory allocator:                       system default
        Runtime Instrumentation (slow code):    No
        uuid support:                           Yes
        Number of Bits in RainerScript integers: 64
~~~

If necessary, a more recent RSyslog version can be used.

**Comment by rgerhards** [comment]
You may want to look into the `action.execOnlyOnceEveryInterval` action parameter. 

Doc: https://www.rsyslog.com/doc/master/configuration/actions.html
