### ISSUE TITLE
remove rsyslog.service[.in] file and provide platform samples instead

### ISSUE THREAD

**Issue by rgerhards** [rsyslog/rsyslog#4333]
This is a systemd unit file. Over the past month, we received numerous complains from the RH'ish community because of the "wrong" content of this file. Thus, we changed it to silence these complains. Now, very similar complains come from the Debian'ish community (https://github.com/rsyslog/rsyslog/pull/4317#discussion_r445907950).

The root cause of these problems is that this is not really a ryslog-related file. It is a systemd unit file, and obviously very highly depending on distro policies. It was an excellent idea to add this file back in the early days of systemd when nobody knew about unit files. Nowadays, however, a single "proposed" unit file causes more trouble than it solves.

As such, we will remove the file in rsyslog's project root. Instead, we will provide distro-specific sample files in the platform subdirectory (https://github.com/rsyslog/rsyslog/tree/master/platform).

This way each distro can maintain its (considerably different) rsyslog.service without the rsyslog interfering with it.

**Comment by mbiebl** [comment]
Can you point to such complaints from the RH community, that the rsyslog file provide as-is is wrong?

**Comment by rgerhards** [comment]
> Can you point to such complaints from the RH community, that the rsyslog file provide as-is is wrong?

I need to dig this out, possibly most are via private mail. But if you look at the current default, which is based on RH, you noticed that it is very different from what you need for Debian. As this is a very distro specific file, I am sure we should not provide a "this should it be" sample. We neither do so for sys V init, nor for rsyslog.conf. rsyslog.service is in the same camp. I wonder what might be the problem if we do not provide a "one and only" rsyslog.service?

**Comment by rgerhards** [comment]
Here is one complaint that I could quickly get my hands on: https://github.com/rsyslog/rsyslog-pkg-rhel-centos/issues/72

**Comment by mbiebl** [comment]
Do you enable remote syslog (imrelp/imudp/imtcp etc) by default on RHEL?
Isn't the problem very user specific, only manifested if he binds to a certain IP address?
If that is indeed a custom user configuration, wouldn't it be somewhat logical that users also create a drop-in for rsyslog.service which adds
```
[Service]
Wants=network-online.target
After=network-online.target
```
Keep in mind, that network-online.target will only be useful anyway, if the user explicitly enables a service like
`NetworkManager-wait-online.service` or `systemd-networkd-wait-online.service`.

I think the best you can do is document this.

**Comment by mbiebl** [comment]
The `After=network.target` ordering is only really relevant on shutdown, to make sure rsyslog is stopped before the networking stack is stopped. Is this really an issue for rsyslog?
If not, why was this added?

Basically, what I'm missing is a proper reasoning for this change.

**Comment by rgerhards** [comment]
> Do you enable remote syslog (imrelp/imudp/imtcp etc) by default on RHEL?

*I do not do anything, that's exactly the point.* RH does, you do, Gentoo does, Ubuntu does different. I do not care what they do, as I do not know what is best for each distros. Thus I do not any longer recommend anything that others know better. But still provide, as "so they do it" samples the distro specific files for other users who may package themselves.

Accordingly, I cannot answer your questions. RH can.

**Comment by mbiebl** [comment]
Ok, I was confused then, because I thought rsyslog/rsyslog-pkg-rhel-centos is provided by the rsyslog project.

**Comment by mbiebl** [comment]
Anyway, seems I plucked a nerve there. So I won't bother you on this issue anymore. 
I thought there is value in shipping a rsyslog.service with some sane defaults in the upstream project but I acknowledge your point. I can certainly manage to ship an rsyslog.service downstream.
I wouldn't bother with shipping an upstream sample config, as this would go stale anyway and is then probably not helpful to anyone.

**Comment by rgerhards** [comment]
> Ok, I was confused then, because I thought rsyslog/rsyslog-pkg-rhel-centos is provided by the rsyslog project.

FYI: I tries to stay as close at RHEL as possible. Same for the other packages. It's "just" new versions. Whenever we tried to be smarter than distro maintainers, this lead to Desaster ;-) So I've strongly opted years ago not to try this.

> I wouldn't bother with shipping an upstream sample config, as this would go stale anyway and is then probably not helpful to anyone.

In a sense, it's no extra effort. We need to maintain this for the current-version-packages anyway. If we do this in the packaging repos or inside rsyslog does not complicate things - at least I currently think so. Let me see if I run into trouble with that approach, than I'll for sure take your advise to just drop the file.

On the value of providing a rsyslog.service: as I wrote in my initial message, I think there *was* indeed value in that at the time it was added by you. But times changed, systemd is now everywhere and everybody knows how to deal with unit files. Also, different distros have taken quite different approaches in the interaction of rsyslog, systemd and journald, and so the distro-default unit files are quite diverse as well. I would say there is no longer a sane default. Thus (and only because of this), it is time to move ahead and remove that file from rsyslog's root. But it was very useful for many years.
