### ISSUE TITLE
Log rotation in rsyslog

### ISSUE THREAD

**Issue by Ravikiran7161** [rsyslog/rsyslog#4337]
Just a question, Is it possible to configure log rotation in rsyslog.conf itself?

**Comment by davidelang** [comment]
On Fri, 26 Jun 2020, Ravikiran7161 wrote:

> Just a question, Is it possible to configure log rotation in rsyslog.conf 
> itself?

there is a little used feature of outchannels (or something close to that), but 
it's very limited in what it can do (rotate by size IIRC).

David Lang

**Comment by Ravikiran7161** [comment]
How many rsyslog instances can we run on a server? Also can we run one instance on muliple ports?

**Comment by davidelang** [comment]
as long as you avoid referencing the same files and ports, the only limit to the 
number of instances you can run is the cpu/ram of the system.

one instance of rsyslog can listen or output to many ports.

David Lang

**Comment by Ravikiran7161** [comment]
Okay. Thank you. Suppose, the rsyslog writing solace logs continuously to log files, when we run log rotation job at the time of writing, do we miss any data? How log rotate/rsyslog handles it?

**Comment by davidelang** [comment]
to properly rotate rsyslog logs

rename the logs (mv)
   at this point rsyslog is still writing to the files under their new names

send rsyslog a HUP signal
   this tells rsyslog to close it's outputs and re-open them, it will create new files

At this point you can compress or archive the renamed files

no data will be lost in this process (note you send rsyslog a HUP, you do not 
restart rsyslog)

David Lang

**Comment by Ravikiran7161** [comment]
What happens when we send a HUP signal to rsyslog? does it stop the process for a instance? 
Don't we lose not even a single message while closing its output and re-opening because the messages will come continuously?

Note: In our case. the client won't send messages again if there is a drop in messages.

**Comment by rgerhards** [comment]
HUP does not stop the process. All that happens is that the file is closed. When the next write is needed, it is reopened again. Thus no message loss.

**Comment by davidelang** [comment]
when rsyslog recieves a message it adds it to a queue (if the queue gets full it 
stops accepting messages).

when it gets a HUP, it continues to accept messages and closes it's outputs, it 
does not loose any messages in the process.

David Lang

**Comment by Ravikiran7161** [comment]
So. by default rsyslog add the messages to queue or do we need to configure anything in rsyslog.conf file?

**Comment by davidelang** [comment]
you have to go to extreme measures to disable it :-)

David Lang

**Comment by Ravikiran7161** [comment]
That's Great 👍. How long does it keep them in the queue? and what is the maximum amount of data it can keep in the queue?

**Comment by davidelang** [comment]
On Fri, 3 Jul 2020, Ravikiran7161 wrote:

> How long does it keep them in the queue?

until they are delivered or some condition that you configure throws them away.

> and what is the maximum amount of data it can keep in the queue?

the number of messages the queue is configured to hold (the default varies on 
different rsyslog versions, I believe it's around 100,000 currently)

David Lang

**Comment by Ravikiran7161** [comment]
Okay. I am using v8.

Is there any way to monitor the rsyslog service that it is always running and receiving messages? if not send alerts ?

**Comment by davidelang** [comment]
v8 is not specific enough, V8 has been out for bout 7 years now and has lots of 
changes over that time.

David Lang

**Comment by Ravikiran7161** [comment]
Okay. So, any suggestion on this:
Is there any way to monitor the rsyslog service that it is always running and receiving messages? if not send alerts ?

**Comment by rgerhards** [comment]
you need to check the full stack. So regularly send test message, write them to some file and have a process check that they actually arrive there.

**Comment by qingxiyingyue** [comment]
hi,where is the  code from receive hup to close and reopen new fd?
