### ISSUE TITLE
imkmsg does not load and is not included in 8.2006.0

### ISSUE THREAD

**Issue by ebsf1** [rsyslog/rsyslog#4339]
### Expected behavior

module(
        load="imkmsg"
)

loads imkmsg, which then operates to read system kernel messages.

### Actual behavior

From the rsyslog operating state file:

`20200630-190622: MSG   could not load module 'imkmsg', errors: trying to load module /usr/lib/rsyslog/imkmsg.so: /usr/lib/rsyslog/imkmsg.so: cannot open shared object file: No such file or directory`

Further inspection reveals that the file does not in fact exist.

### Steps to reproduce the behavior

Include the above module() configuration object and reboot.

### Environment
- rsyslog version: 8.2006.0; Ubuntu 16.04

[rsyslog.conf.txt](https://github.com/rsyslog/rsyslog/files/4855422/rsyslog.conf.txt)

**Comment by rgerhards** [comment]
Where did you install from? I am working on the packaging and this looks like a regression.

**Comment by ebsf1** [comment]
The Adiscon ppa repository.  According to /etc/apt/sources.list:

`http://ppa.launchpad.net/adiscon/v8-stable/ubuntu`

**Comment by ebsf1** [comment]
I just downloaded the .deb package from the Adiscon site using:

`sudo apt download rsyslog`

and received rsyslog_8.2006.0-0adiscon2xenial1_amd64.deb.

Expanding the .deb package, I did not find imkmsg.so

**Comment by rgerhards** [comment]
I have added an `imklog` package to the OBS builds for Ubuntu: https://software.opensuse.org//download.html?project=home%3Argerhards&package=rsyslog

**Comment by ebsf1** [comment]
Apologies, there was a typo in the headline of my original post, although the body was correct.

It is imkmsg that is missing, not imklog.

**Comment by rgerhards** [comment]
Lol, analogous  typo here - meant kmsg (I am not so used to that name...)

**Comment by ebsf1** [comment]
Thanks, I've downloaded them and will take it further tomorrow.

**Comment by ebsf1** [comment]
Thanks for this.

 

I just checked through all the builds and imkmsg still does not appear in any of them for U16.04-20.04.

 

Your note below refers to adding imklog, not imkmsg, to the builds, so there may have been a mix-up.

 

-ERB

 

PS:  improg also is missing in case it also might be added.

**Comment by rgerhards** [comment]
I guess you picked the wrong. Repository. I just gave it a try and everything works as intended. Please have a look here: https://youtu.be/L-13DP1JbMQ

**Comment by ebsf1** [comment]
Yes, I had been using the main Adiscon repository instead of the OBS.

rsyslog-imkmsg had unmet dependencies when the 8.2006.0-0adiscon2bionic1 package was installed (from the main Adiscon repository).  Purging it and installing 8.2006.0-0adiscon1bionic1 (from the OBS site) got imkmsg to install on the Ubuntu 18.04 machine.

So far, so good but no public key exists in the Ubuntu 16.04 OBS package, however, so it won't install at all:

```
Err:7 http://download.opensuse.org/repositories/home:/rgerhards/xUbuntu_16.04  InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY C6326869D2017333
```

Is imkmsg included in the daily stable build repository ppa:adiscon/v8-devel?

**Comment by rgerhards** [comment]
> So far, so good but no public key exists in the Ubuntu 16.04 OBS package, however, so it won't install at all:

Is this only for 16.04? Did you follow the instructions from the video? The key download was part of them. But I tested with 18.04.

**Comment by ebsf1** [comment]
Yes, only 16.04.  The 18.04 machine worked fine, although both had the same issue with unmet dependencies.  The solution was to remove and purge rsyslog, and obviously remove references to other rsyslog repositories, before re-installing.

The video procedure worked fine (on the 18.04 machine, at least), assuming no existing rsyslog installation, conflicting repositories, or residual package caches.

**Comment by ebsf1** [comment]
I commented by mistake in another string, but it turns out the pubkey issue is a simple matter of permissions.  The pubkey in /etc/apt/trusted.gpg.d is root:root/640 and should be 644 (for the 16.04 machine).  The permissions are correct on the 18.04 machine.

**Comment by rgerhards** [comment]
implemented
