### ISSUE TITLE
Unexpected imfile-state file created

### ISSUE THREAD

**Issue by bmy4415** [rsyslog/rsyslog#4347]
### Expected behavior
imfile-state file is created only when `PersistStateInterval` is set

### Actual behavior
I have several Input() blocks with `imfile` type and only 3 of them have `PersistStateInterval` variable.
But there is imfile-state file whose filename contains target files that do not have `PersistStateInterval` variable.

### Steps to reproduce the behavior
Here is fraction of my config file.
```
$PrivDropToUser <myusername>
$WorkDirectory <myworkingdir>

Module (load="imfile" mode="inotify")
Module (load="omprog")


Template (name="lineFormat" type="string" string="%$!metadata!filename%----%programname%----%rawmsg%\n")

Ruleset (name="output") {
    Action (type="omprog" binary="<my binary path>" template="lineFormat" signalOnClose="on")
}

# Input() block with no PersistStateInterval
Input (
    type="imfile"
    tag="mytag"
    file="<target file>"
    addMetadata="on"
    ruleSet="output"
    startmsg.regex="^<msg"
    readTimeout="2"
)
...
# Input() block with PersistStateInterval
Input (
    type="imfile"
    tag="mytag2"
    file="<target file>"
    addMetadata="on"
    ruleSet="output"
    # yyyy-mm-ddThh:mm:ss,
    startmsg.regex="^\\[[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2},"
    readTimeout="2"
    PersistStateInterval="1"  # interval to write to statefile
)
...
```

I'm using rsyslog8.24 which is somewhat old version but cannot upgrade it to later one now.
If there already found similar issue, let me know.

P.S
After commeting out all `PersistStateInterval` from all Input() blocks, imfile-state file is still created.

Thanks,
Jaewan

**Comment by bmy4415** [comment]
After commeting all `PersistStateInterval` from all Input() blocks, imfile-state file is still created.

**Comment by rgerhards** [comment]
8.24 is heavily outdated and I guess two refactorings behind the current version. The simple cure is to use the current version. As you cannot update, I guess there is no solution for your case.

**Comment by bmy4415** [comment]
Thanks, I will find another way to solve this issue.
