### ISSUE TITLE
Questions related to manual build

### ISSUE THREAD

**Issue by bmy4415** [rsyslog/rsyslog#4353]
### Environment
- rsyslog version: 8.2008.0
- platform: Red Hat Enterprise Linux Server release 7.7 (Maipo)
- for configuration questions/issues, include rsyslog.conf and included config files

### Question
I'm working on an environment where
- internet access is restricted
- do not have root permission
- cannot use docker container
So I'm wondering if there is a way to install and use rsyslogd easily, for example, just carrying zip file and installing with this zip file. 

Thanks in advance for you reply!

**Comment by rgerhards** [comment]
> * So I'm wondering if there is a way to install and use rsyslogd easily, for example, just carrying zip file and installing with this zip file.

just use a regular release tarball (as you find on the rsyslog site) and your are fine :-)
