### ISSUE TITLE
how to specify the soure ip send syslog

### ISSUE THREAD

**Issue by zyboy2000** [rsyslog/rsyslog#4359]
I have a loopback ip(for example 1.1.1.1),how can i use this ip as the source ip to send syslog. Thanks!

**Comment by davidelang** [comment]
look at the docs for the omfwd module, it will list the option for doing this 
(check that it's implemented in the version you are running if it's not pretty 
current)

**Comment by zyboy2000** [comment]
Thank you!

**Comment by zyboy2000** [comment]
I update rsyslog 8.40.0
in etc/rsyslog.conf  i add
*.* action(type="omfwd" Target="10.3.22.201" Address="18.18.18.18" Port="541" Protocol="udp")
but i can not recevive any syslog,  from 10.3.22.201 ping 18.18.18.18 is ok

**Comment by skupkosk** [comment]
Hi,
be more precise in describing what the syslog flow looks like and what you
would like to achieve with the configuration.
From the words you sent to us it is not obvious/clear enough.

**Comment by rgerhards** [comment]
stale, no reply from OP. Probably solved.
