### ISSUE TITLE
Double imupd stats entries

### ISSUE THREAD

**Issue by skupkosk** [rsyslog/rsyslog#4364]
### Expected behavior
One line per imudp input in stats file.

### Actual behavior
The imudp line is printed twice, with the second line with counters equal to zero.
Fri Jul 17 18:06:46 2020: imudp(*:1514): origin=imudp submitted=1216 disallowed=0
Fri Jul 17 18:06:46 2020: imudp(*:1514): origin=imudp submitted=0 disallowed=0

### Steps to reproduce the behavior
Configure imudp input (with port and name options) and impstats.

### Environment
- rsyslog version: 8.1901 (maybe older), 8.2006 reported as affected also
- platform: Debian 10
- for configuration questions/issues, include rsyslog.conf and included config files
module(load="imudp")
input(type="imudp" port="1514")
module(load="impstats"
  interval="15"
  severity="7"
  ResetCounters="on"
  log.syslog="off"
  log.file="/var/spool/rsyslog/rsyslog.stats")

**Comment by skupkosk** [comment]
With use of address configuration option of imudp input there are not duplicite entries logged.

input(type="imudp" port="1514" address="10.0.0.8" name="bo-u")
input(type="imudp" port="1514" address="10.0.0.2" name="bs-u1")
input(type="imudp" port="1514" address="10.0.0.3" name="bs-u2")

Wed Jul 22 06:24:43 2020: bo-u(10.0.0.8:1514): origin=imudp submitted=0 disallowed=0
Wed Jul 22 06:24:43 2020: bs-u1(10.0.0.2:1514): origin=imudp submitted=0 disallowed=0
Wed Jul 22 06:24:43 2020: bs-u2(10.0.0.3:1514): origin=imudp submitted=48917 disallowed=0

**Comment by davidelang** [comment]
in your first config, could you add a name= section to the imudp input to see 
which of the two gets the name?

and can you double check that you don't have any included files that add an 
input

David Lang

**Comment by skupkosk** [comment]
> in your first config, could you add a name= section to the imudp input to see which of the two gets the name? and can you double check that you don't have any included files that add an input David Lang

That was already [tested and reported on rsyslog-users](http://rsyslog-users.1305293.n2.nabble.com/Double-imupd-stats-entries-tp7595893p7595899.html). Both lines report the same name.
There is no other imudp input configured.

**Comment by jay7x** [comment]
Just want to confirm I saw the same behavior just now. Was heading to report it. I *guess* records are for IPv4 and IPv6 stack (guessing from `imptcp` module stats).

**Comment by rgerhards** [comment]
yupp, sounds like IPv4 vs. IPv6; maybe we should add a suffix...

**Comment by jay7x** [comment]
This is what we have for `imptcp`:
```
{ "name": "debug(*\/5445\/IPv4)", "origin": "imptcp", "submitted": 0, "sessions.opened": 0, "sessions.openfailed": 0, "sessions.closed": 0, "bytes.received": 0, "bytes.decompressed": 0 }
{ "name": "debug(*\/5445\/IPv6)", "origin": "imptcp", "submitted": 0, "sessions.opened": 0, "sessions.openfailed": 0, "sessions.closed": 0, "bytes.received": 0, "bytes.decompressed": 0 }
```

Can we do the same for `imudp`? Not sure about `imtcp` btw..

**Comment by jay7x** [comment]
Just did check for `imtcp`.. there is no duplicated records as I see:
```
input(type="imtcp" name="debug1" port="5534" ruleset="debug")
input(type="imtcp" name="debug2" port="5535" ruleset="debug")
```

```
{ "name": "debug1(5534)", "origin": "imtcp", "submitted": 0 }
{ "name": "debug2(5535)", "origin": "imtcp", "submitted": 0 }
```

But maybe we should split IPv4/IPv6 here as well (if this input can be used with IPv6 at all).

**Comment by rgerhards** [comment]
> This is what we have for `imptcp`:
> 
> ```
> { "name": "debug(*\/5445\/IPv4)", "origin": "imptcp", "submitted": 0, "sessions.opened": 0, "sessions.openfailed": 0, "sessions.closed": 0, "bytes.received": 0, "bytes.decompressed": 0 }
> { "name": "debug(*\/5445\/IPv6)", "origin": "imptcp", "submitted": 0, "sessions.opened": 0, "sessions.openfailed": 0, "sessions.closed": 0, "bytes.received": 0, "bytes.decompressed": 0 }
> ```
> 
> Can we do the same for `imudp`? Not sure about `imtcp` btw..

Unfortunately, imudp uses `:` instead of `/` to separate the parts. I have just written code to add the suffix, so the name looks like this:
```
imudp(*:55675:IPv4)

I am a bit split-minded if I should switch to slash, to become more consistent. In any way, it's no longer fully compatible to old analysis scripts. Comments @jay7x @davidelang 
```

**Comment by rgerhards** [comment]
> But maybe we should split IPv4/IPv6 here as well (if this input can be used with IPv6 at all).

All components are IPv6 safe (really, we have 2021 ;-)). BUT... I checked the code, and stats gathering is done for imtcp and friends (imgssapi uses the same plumbing) on a higher level. There, we do not see IPv4 vs. IPv6. I would tend to leave things for now as they are. It's probably not worth the effort to make the change.

**Comment by davidelang** [comment]
I don't like the risk of breaking scripts, but I think this is reasonable to do.

David Lang

**Comment by jay7x** [comment]
> I am a bit split-minded if I should switch to slash, to become more consistent. In any way, it's no longer fully compatible to old analysis scripts. Comments? @jay7x @davidelang

I'm always positive for breaking changes if those changes making things consistent :) I'd say if someone is parsing stats then they are likely parsing `imptcp` stats as well. That means they have support for slashes already. Then name is not parsed usually I guess..

> All components are IPv6 safe (really, we have 2021 ;-)). BUT... I checked the code, and stats gathering is done for imtcp and friends (imgssapi uses the same plumbing) on a higher level. There, we do not see IPv4 vs. IPv6. I would tend to leave things for now as they are. It's probably not worth the effort to make the change.

Agree on this. Let's keep `imtcp` as it is.

**Comment by rgerhards** [comment]
@jay7x I have changed the delimiter to `/`, but still thinking if changing in imptcp is the better idea. After all `addr:port` is "network speak while `addr/port` is not - and `addr:port:ipv4|6` would be an extension to that scheme. What do you think?

**Comment by jay7x** [comment]
TBH, I see no big difference here..

I can propose a bit better but harder to implement way.. we may display listeners like Linux tools do e.g.:
```
LISTEN    0         128                0.0.0.0:22               0.0.0.0:*        users:(("sshd",pid=707,fd=3))                                                  
LISTEN    0         128                   [::]:22                  [::]:*        users:(("sshd",pid=707,fd=4))                                                  
```

I.e. `0.0.0.0:22` is IPv4 listener, while `[::]:22` is IPv6 listener. So it'd be `imudp(0.0.0.0:514)` and `imudp([::]:514)` e.g.
Same for `imptcp`. Though I'm not sure about few things:
- `*` -> `0.0.0.0` change is not that straightforward
- this may break `imptcp` parsing scripts (which is acceptable from my point of view).

**Comment by rgerhards** [comment]
@jay7x no big difference ... indeed, I think I am overcomplicating. I'll keep the `/` as it works and is relatively free of effort and confusion ;-)

**Comment by jay7x** [comment]
So I overcomplicated it even more then :-D I'm fine with `/` at the moment.
