### ISSUE TITLE
RSYSLOG_SyslogProtocol23Format has "\n" at the end

### ISSUE THREAD

**Issue by anatolyborodin** [rsyslog/rsyslog#4384]
### Expected behavior

`"<174>1 2020-08-21T13:32:18.596113+02:00 host TestLogging - - -  test"`

### Actual behavior

`"<174>1 2020-08-21T13:32:18.596113+02:00 host TestLogging - - -  test\n"`

### Steps to reproduce the behavior

Forward test messages to a remote server, check out WireShark.

### Environment

- rsyslog version: 8.2002.0
- platform: Linux/Buildroot
- for configuration questions/issues, include rsyslog.conf and included config files

```
...
*.*    @192.168.10.110;RSYSLOG_SyslogProtocol23Format
```

**Comment by rgerhards** [comment]
@anatolyborodin sry... I think **you** were right in the first place. I re-visited this issue and I guess the \n is not really necessary. Maybe I was wrong from the time I implemented it. We have release tomorrow, and I will not mess with it. After it, I'll do some more experiements just to be totally sure.

And ACK on the shorter name.

**Comment by rgerhards** [comment]
sry for taking so long... at least there will finally be a PR in a couple of minutes.
