### ISSUE TITLE
Deprecation warning when using omelasticsearch with Elasticsearch 7.x (will break with ES 8.x)

### ISSUE THREAD

**Issue by fpoirotte** [rsyslog/rsyslog#4387]
### Expected behavior
I expect no warning in ``/var/log/elasticsearch/cluster-es_deprecation.log``

### Actual behavior
```
[2020-08-24T10:28:51,375][WARN ][o.e.d.a.b.BulkRequestParser] [node-es] [types removal] Specifying types in bulk requests is deprecated.
```
Note: the warning only appears once after Elasticsearch is restarted. However, the real issue is that starting with Elasticsearch 8.x, ``types`` will not be allowed at all, meaning that this will trigger fatal errors. See https://www.elastic.co/guide/en/elasticsearch/reference/current/removal-of-types.html#_schedule_for_removal_of_mapping_types for more information.

### Steps to reproduce the behavior
* Install Elasticsearch 7.x
* Use the following rsyslog configuration:
```
template(name="logTemplate" type="list"){
  constant(value="{" )
  constant(value="\"timereported\":\"")    property(name="timereported" dateFormat="rfc3339"  mandatory="on")
  constant(value="\",\"hostname\":\"")      property(name="hostname" format="json")
  constant(value="\",\"message\":\"")   property(name="msg" format="json" )
  constant(value="\"}")
}

   action(type="omelasticsearch"
          server="127.0.0.1"
          serverport="9200"
          usehttps="off"
          template="logTemplate"
          searchIndex="logs"
          # Note: removing the following line still triggers the warning because the value then defaults to "events"
          searchType="_doc" # <-- This line triggers the deprecation warning
          dynSearchIndex="off"
          bulkmode="on"
   )
```

### Environment
- rsyslog version: 8.2006.0
- elasticsearch version: 7.8.1
- platform: CentOS 7.8.2003 (64 bits)

See https://www.elastic.co/guide/en/elasticsearch/reference/current/removal-of-types.html for more information about types removal and how it impacts the various Elasticsearch APIs.

**Comment by jishnuc** [comment]
Is there any work around for this ? 
I am facing same error in Elasticsearch version 7.7.0
The searchType defaults to events and I found no way to exclude it.

4364.140382582:main Q:Reg/w0  : omelasticsearch.c: omelasticsearch: using REST URL: 'https://localhost:9200/_bulk'
4364.238795038:main Q:Reg/w0  : omelasticsearch.c: curl returned 0
4364.238811860:main Q:Reg/w0  : omelasticsearch.c: omelasticsearch: pWrkrData replyLen = '416'
4364.238816588:main Q:Reg/w0  : omelasticsearch.c: omelasticsearch: pWrkrData reply: '**{"took":14,"errors":true,"items":[{"index":{"_index":"logstash-log-2020.12.04","_type":"events","_id":null,"status":400,"error":{"type":"illegal_argument_exception","reason":"[_default_] mappings are not allowed on new indices and should no longer be used. See [https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking-changes-7.0.html#default-mapping-not-allowed] for more information."}}}]}**'
4364.238849604:main Q:Reg/w0  : omelasticsearch.c: omelasticsearch: Entire request {"index":{"_index": "logstash-log-2020.12.04","_type":"events"}}
{ "@timestamp":"2020-12-04T03:59:24.048142+00:00",  "metadata": { "filename": "\/logs\/mylog.log", "fileoffset": "307527" }, "timeMillis": 1607054364047, "thread": "boundedElastic-16", "level": "WARN", "loggerName": "com.github.test.Test", "message": "This is a test messaage", "endOfBatch": false, "loggerFqcn": "org.apache.log4j.Category", "threadId": 38, "threadPriority": 5 }

**Comment by Whissi** [comment]
It's hardcoded https://github.com/rsyslog/rsyslog/blob/v8.2012.0/plugins/omelasticsearch/omelasticsearch.c#L2092-L2093 ... we will probably need a new option.

I had to disable deprecation log because of this for now.

**Comment by caraar12345** [comment]
Downsides of using the Elasticsearch 8.0 snapshot...

```{
  "request": {
    "url": "http:\/\/localhost:9200\/_bulk",
    "postdata": "{"index":{"_index": "rsyslog-2021.03.18","_type":"events"}}
{"@timestamp":"2021-03-18T20:33:19.295056+00:00","host":"aaroncarsonpi","severity-num":3,"facility-num":5,"severity":"err","facility":"syslog","syslogtag":"rsyslogd:","message":" omelasticsearch: error in elasticsearch reply: bulkmode insert does not return array, reply is: {\"error\":{\"root_cause\":[{\"type\":\"illegal_argument_exception\",\"reason\":\"Action\/metadata line [1] contains an unknown parameter [_type]\"}],\"type\":\"illegal_argument_exception\",\"reason\":\"Action\/metadata line [1] contains an unknown parameter [_type]\"},\"status\":400} [v8.1901.0 try https:\/\/www.rsyslog.com\/e\/2218 ]"}
"
  },
  "reply": {
    "error": {
      "root_cause": [
        {
          "type": "illegal_argument_exception",
          "reason": "Action\/metadata line [1] contains an unknown parameter [_type]"
        }
      ],
      "type": "illegal_argument_exception",
      "reason": "Action\/metadata line [1] contains an unknown parameter [_type]"
    },
    "status": 400
  }
}```

**Comment by oranenj** [comment]
I sent in a PR with a patch that provides a way to omit the field. I might have time to test it with a real setup later, but I'm not sure if that'll be this week.

**Comment by frikilax** [comment]
Just tested again with a running ELS 8.x and couldn't get past it, this will soon become very troublesome

**Comment by rgerhards** [comment]
as of my understanding, this should have been fixed with https://github.com/rsyslog/rsyslog/pull/4808

Please let me know if that is not the case.
