### ISSUE TITLE
imkmsg (probably also imklog): If filedescriptor becomes invalid, logspam is caused.

### ISSUE THREAD

**Issue by incase** [rsyslog/rsyslog#4395]
### Expected behavior

If the filedescriptor for /dev/kmsg becomes invalid for whatever reason, rsyslog should try to reopen the file or shut down

### Actual behavior

Using a lot of CPU, the log gets spammed with:
rsyslogd: imkmsg: error reading kernel log - shutting down: Bad file descriptor

The code if readkmsg says:
```
			/* something went wrong - error or zero length message */
			if (i < 0 && errno != EINTR && errno != EAGAIN) {
				/* error occured */
				imkmsgLogIntMsg(LOG_ERR,
				       "imkmsg: error reading kernel log - shutting down: %s",
					rs_strerror_r(errno, errmsg, sizeof(errmsg)));
				fklog = -1;
			}
			break;
```
Equivalent code is in the imklog plugin. However, nothing seems to check fklog value and shut anything down, it appears that readkmsg is just called over and over again.
Similarly, I couldn't find anything in imklog either which would actually result in a shutdown of the plugin or rsyslog as the message would indicate, but I might have missed something and the module is actually shut down and restarted, but if so, it fails to re-open the file in the process.

### Steps to reproduce the behavior

Unclear, we are seeing this on some machines, but not all of them, sometimes this re-occurs shortly after a restart of rsyslog, sometimes it doesn't.

### Environment
- rsyslog version: 8.2004.0
- platform: Debian bullseye

**Comment by hsaliak** [comment]
There seems to be a bug in the code below - the read's return value is checked for  -EPIPE, but read always returns -1 on error, and ERRNO is set. So they should be checking if errno == EPIPE instead.
When that happens fklog FD is set to -1 and wrongly concludes that it shuts down and spams.

I saw this happen - and the errno at the start of the spam was an EPIPE (Broken Pipe)

``` i = read(fklog, pRcv, 8192);

		if (i > 0) {
			/* successful read of message of nonzero length */
			pRcv[i] = '\0';
		} else if (i == -EPIPE) {
			imkmsgLogIntMsg(LOG_WARNING,
					"imkmsg: some messages in circular buffer got overwritten");
			continue;
		} else {
			/* something went wrong - error or zero length message */
			if (i < 0 && errno != EINTR && errno != EAGAIN) {
				/* error occured */
				imkmsgLogIntMsg(LOG_ERR,
				       "imkmsg: error reading kernel log - shutting down: %s",
					rs_strerror_r(errno, errmsg, sizeof(errmsg)));
				fklog = -1;
			}
			break;
		}

		submitSyslog(pRcv);
	}
