### ISSUE TITLE
Rsyslog Writing logs into moved files( through log rotate).  

### ISSUE THREAD

**Issue by raunaktiwari177** [rsyslog/rsyslog#4397]
### Expected behavior
It should Write a log file to .log not to rotated one.
### Actual behavior
Its started writing all the logs to rotated files.
### Steps to reproduce the behavior
Its very frequent in my environment.
### Environment
- rsyslog version: 8.32.0 
- platform: x86_64-redhat-linux-gnu
- for configuration questions/issues, include rsyslog.conf and included config files

[rsyslog.conf.txt](https://github.com/rsyslog/rsyslog/files/5146398/rsyslog.conf.txt)

Logrotate used to move the Files
/usr/app/syslog/hosts/Radio.prod.mobistar.be/Radio.prod.mobistar.be.log {
        rotate 1
        missingok
        postrotate
                # /etc/init.d/rsyslog force-reload;
                /bin/kill -HUP `cat /var/run/syslogd.pid 2> /dev/null` 2> /dev/null || true;
                Date=$(date +\%Y\%m\%d\%H\%M\%S);
                mv  /usr/app/syslog/hosts/Radio.prod.mobistar.be/Radio.prod.mobistar.be.log.1 /usr/app/syslog/hosts/Radio.prod.mobistar.be/"Radio.prod.mobistar.be.log-$Date.log";
                gzip /usr/app/syslog/hosts/Radio.prod.mobistar.be/Radio.*log ;
                chmod 660 /usr/app/syslog/hosts/Radio.prod.mobistar.be/Radio.*log.gz
                mv /usr/app/syslog/hosts/Radio.prod.mobistar.be/Radio*.log.gz /usr/app/SyslogArchive/To_Turtle/FW-PaloAlto/ ;
        endscript
}

**Comment by rgerhards** [comment]
You need to HUP or restart rsyslog after rotation. It looks like you do, but it also looks like it is not done correctly. Check on that.

Also, you version is very old and may still have a long-solved bug. To ensure this is not the case, upgrade to the currently supported version of rsyslog (8.2006 or 8.2008).

**Comment by raunaktiwari177** [comment]
Thanks for response,

this issue is frequent but it occurs once in 2 days, for further modification i am really not sure what will be the best i can use to stop the log processing to rotated file.

As you said i can try to upgrade it to latest version but before let me know if i could use other parameter.

**Comment by rgerhards** [comment]
try to execute the HUP command under the same user as logrotate (`sudo -u username <HUP-cmd>`). Check if it brings up a (permission?) error.

**Comment by raunaktiwari177** [comment]
@rgerhards Apologies for delay.

i have tried above suggestion but since we use root access for all the commands and script. it doesn't throw any error.

i am not sure its due to a bug or something else causing this issue, but this problem is getting Critical in my environment.
I remember First time this issue has been occurred after i have added additional UDP port to collect the Events for devices and after that we are having this issue.

a kill -HUP signal sent to rsyslog should make it close open files and creating new ones; However, on some times, this signal is not efficient anymore => so rsyslog doesn't close files, and goes-on writing to now "deleted" files.

This writing bufferizes and finish by fully filling the file system.
Only solution is to full restart rsyslog, so that I really closes files and empty buffers.

can we trace such issue?

**Comment by rgerhards** [comment]
I still suggest to update to the current version, especially as a bug seems to be the most likely explanation for what you see.

**Comment by skupkosk** [comment]
Are those virtual servers? What is the disk scheduler?
Are those writes to rotated files permanent or just for some time after
rotation took place?
Try to run logrotate in debug, that might show what is going on.

-- 
Peter

**Comment by raunaktiwari177** [comment]
@skupkosk 

yes! i am running Rsyslog on Virtual Server.

Logs writes to rotated file after some time rotation took Place and since i am moving the file immediately after the rotation its getting Marked as "Deleted" files by Syslog and it starts writing to deleted file.

**Comment by rgerhards** [comment]
We had at least a fix for HUP in 8.1907, over a year ago. V8.32.0 is around two years old. So I strongly suggest not to try to debug this with the outdated version. It will most probably not fail. I have not really glanced of which bugs were fixed between 8.1907 and 8.32, but I saw HUP mentioned there as well in ChangeLog.

**Comment by raunaktiwari177** [comment]
I am planning upgrade for Rsyslog. let wait for result after upgrade.
