### ISSUE TITLE
Rsyslog holds open deleted files, occupies file meta descriptor and takes up a lot of disk space

### ISSUE THREAD

**Issue by WillireamAngel** [rsyslog/rsyslog#4398]
### Expected behavior
rsyslog freed disk space when I deleted log file.

### Actual behavior
rsyslog occupy file meta descriptor and takes up a lot of disk space after I deleted log file.

### Steps to reproduce the behavior
/etc/rsyslog.conf：
```
#MODULE
module(load="imuxsock" SysSock.RateLimit.Interval="0" SysSock.RateLimit.Burst="0")
module(load="imklog")
module(load="builtin:omfile" template="RSYSLOG_TraditionalFileFormat" dirCreateMode="0755" fileOwner="root" fileGroup="adm" fileCreateMode="0644")
#
$MaxMessageSize 2M
$IncludeConfig /etc/rsyslog.d/*.conf
#$RepeatedMsgReduction on
```
/etc/rsyslog.d/data.conf:
```
$FileOwner data
$FileGroup data
$FileCreateMode 0644
$Umask 0022
$template ServerLogFormat,"%msg:2:$%\n"
$template ServerLogFile,"/home/data/log/server.%$now%.%$hour%.log"
local1.* -?ServerLogFile;ServerLogFormat
```
after rsyslog log to file, use rm to delete log when need:
```
find /home/data/log/ -type f -name "server.*.log" -mmin +${debuglog_time} -exec rm {} \;
```
then you can see the deleted file by using `lsof` to find deleted file occupied:  
![image](https://user-images.githubusercontent.com/22117826/91655524-bbf39500-eae3-11ea-931f-b9e533159396.png)

the size of every serverlog file is about 5 GiB or more, and you can see the file meta descriptor released after 6-8 hours on the hour when log file rotate to new hour and new file.  

It is a general question at many versions.

### Environment
- rsyslog version: 8.24.0 & 8.4.2
- platform: debian9.11 (rsyslog 8.24.0) , debian 8.8 (rsyslog 8.4.2)

mv file will occupy file meta descriptor too see #4397

**Comment by rgerhards** [comment]
see https://github.com/rsyslog/rsyslog/issues/4397#issuecomment-683409644

**Comment by WillireamAngel** [comment]
> see [#4397 (comment)](https://github.com/rsyslog/rsyslog/issues/4397#issuecomment-683409644)

Why rsyslog cannot auto release file meta descriptor after file is deleted? Rsyslog designed for this?Are there any relevant design logic instructions? 

Server logs depend on rsyslog process so I can't restart or HUP rsyslog after rotation, some logs may lose when I restart or HUP rsyslog, it is a high-risk operation.

Any useful method to solve the problem?

**Comment by rgerhards** [comment]
> Why rsyslog cannot auto release file meta descriptor after file is deleted? Rsyslog designed for this?Are there any relevant design logic instructions?

That's just the way things work under linux and have done so "since ever". Every syslodg does it that way. HUP is *no* high-risk activity. It just closes the files and does a few other non-intrusive things. It's designed exactly for your use case.

**Comment by WillireamAngel** [comment]
> > Why rsyslog cannot auto release file meta descriptor after file is deleted? Rsyslog designed for this?Are there any relevant design logic instructions?
> 
> That's just the way things work under linux and have done so "since ever". Every syslodg does it that way. HUP is _no_ high-risk activity. It just closes the files and does a few other non-intrusive things. It's designed exactly for your use case.

Thanks a lot, I will learn more design principles related to syslog and Liinux
