### ISSUE TITLE
Disk assisted omrelp queue never kicks in when network drops 50% of packets

### ISSUE THREAD

**Issue by tgeoghegan** [rsyslog/rsyslog#4401]
I set up a test harness that runs two instances of the [Alpine Linux rsyslog appliance](https://hub.docker.com/r/rsyslog/syslog_appliance_alpine). One forwards messages to the other (forwarder and loghost, respectively), using either imtcp/omtcp or imrelp/omrelp (the goal of the experiment is to assess how much more reliable RELP is over TCP). The test harness can then tamper with the network connection between the two rsyslogds by using either `ip link down/up` to completely stop the loghost's network or `tc(8)` to drop 50% of traffic. From outside either container, a test program sends messages into forwarder containing a timestamp and a sequence number. Later, we can use this data to detect missing messages and to measure per-message latency, as well as network utilization on either container. The test sets up the forwarder, waits 20 minutes, then tampers with the network connection, waits another 30 minutes, and then restores the network connection. It then waits 70 more minutes, to allow forwarder's rsyslogd enough time to drain any queued up messages. Whether omtcp or omrelp, the forwarding action on forwarder is configured to use a disk-assisted queue.

### Expected behavior
TCP syslog should lose messages in the face of a network link that is down or unreliable for an extended period of time. RELP should recover and all messages should eventually get through.

### Actual behavior
RELP does recover from the link being down altogether, and all messages get through. But if we drop 50% of packets on the loghost's network interface (effectively doing `tc qdisc add dev veth<whatever> root netem 50`), we lose messages. Further, if we examine the pstats logs after the experiment, we see that in the case where 50% of traffic was dropped, the DA queue was never used!

At the end of the experiment where RELP was in use, the loghost network link was down for 30 minutes, we see in the forwarder's pstats:

```
2020-08-28T22:55:05.452583+00:00 6ac75c489a70 rsyslogd-pstats: action 4 queue[DA]: origin=core.queue size=0 enqueued=1810945 full=0 discarded.full=0 discarded.nf=0 maxqsize=1804033 
2020-08-28T22:55:05.452586+00:00 6ac75c489a70 rsyslogd-pstats: action 4 queue: origin=core.queue size=0 enqueued=6001408 full=0 discarded.full=0 discarded.nf=0 maxqsize=904 
```

At the end of the experiment where RELP was in use, the loghost network link was dropping 50% of packets for 30 minutes, we see in the forwarder's pstats:

```
2020-08-28T20:10:39.359028+00:00 34f450668d78 rsyslogd-pstats: action 4 queue[DA]: origin=core.queue size=0 enqueued=0 full=0 discarded.full=0 discarded.nf=0 maxqsize=0 
2020-08-28T20:10:39.359030+00:00 34f450668d78 rsyslogd-pstats: action 4 queue: origin=core.queue size=0 enqueued=5602502 full=2888 discarded.full=1538 discarded.nf=0 maxqsize=1000 
```
Note maxqsize for the [DA] queue is 0 in the second case, suggesting nothing was ever enqueued into the disk assisted queue, even as its in-memory counterpart dropped 1538 messages due to being full.

When we run similar experiments but with imtcp/omtcp, the pstats make it clear that the DA queue kicked in in both the case where the link was down and where 50% of traffic was dropped.

The symptom I'm observing is that messages are lost, but I think the question is: why didn't the disk queue assisting the forwarding queue ever kick in when the network was unreliable? The in-memory queue must have gone above the default high watermark of 90% because maxqsize is 1000 (which is the default for queue.size).

### Steps to reproduce the behavior

Run test harness described above.

### Environment
- rsyslog version: 8.36.0
- platform: Alpine Linux syslog appliance container, running on top of Fedora 32

Forwarder queue configuration:
```
action(
	type="omrelp"
	target="10.89.0.21"
	port="1601"
	action.resumeRetryCount="-1"
	queue.fileName="forwarding"
	queue.maxDiskSpace="1g"
	queue.saveOnShutdown="on"
	queue.type="LinkedList"
	template="RSYSLOG_ForwardFormat"
)
```
The config on loghost is otherwise the same as the default in the syslog-appliance-alpine image.

**Comment by tgeoghegan** [comment]
I can repro this behaviour pretty easily, so it's no problem to re-run the experiment with more verbose logging or to fetch this-or-that logfile from within the container.

**Comment by tgeoghegan** [comment]
I attempted to enable debug logging while reproducing but rsyslogd crashes if I do that. I've filed that as a separate issue: #4404

**Comment by rgerhards** [comment]
The version you are using is very old and no longer supported by the community. It is also very probable that the problem stems back to long-solved issues. As such, please update to the currently supported version and retry. Report back if the problem persists.

The rsyslog project provides packages for current versions: https://www.rsyslog.com/downloads/download-other/

If you insist on using an outdated version, you can also contact your distro or consider [rsyslog professional services](https://www.rsyslog.com/professional-services/enterprise-support/).

**Comment by tgeoghegan** [comment]
Thanks for responding to my issues, I really appreciate it! I will attempt to reproduce on a current rsyslogd and will report back with my findings.

**Comment by tgeoghegan** [comment]
I cannot consistently reproduce this behavior on rsyslog 8.2004: messages still get lost, but the pstats do show the DA queue being used. I've found other issues where it's explained that even RELP makes no claims to _perfect_ reliability so I don't think there's anything else to investigate here.
