### ISSUE TITLE
Problem with upgrading rsyslog in datacenters

### ISSUE THREAD

**Issue by onionka** [rsyslog/rsyslog#4403]
Hello rsyslog team,

I have a problem with upgrading rsyslog, which I am dealing with for months. It is well known issue and the only solution that I have found was that I should remove the old rsyslog version before installing the new one. But in my case, I cannot uninstall the old version, as it will remove all packages that are depending on the rsyslog. As I am managing a lot of servers using saltstack, there are a lot of different packages installed depending on rsyslog, not just few core linux packages mentioned in articles I have found (see references).

So if I would remove rsyslog from one of them, it will remove the ones that I expected, but also it will remove packages that are running and being used in production. There are many more servers/services with similar issue, and I need to implement a salt state that would upgrade rsyslog in these servers without stopping hosted services or uninstalling them.

We are using RPM based systems mostly, so there was one proposition about removing rsyslog rpm package with `--nodeps` flag. It would remove package without its dependencies, but I am not sure if it won't break something or if we loose logs. 

Could you help me with this problem? What approach would you suggest to resolve this issue?

References:
https://www.thegeekdiary.com/how-to-install-rsyslog7-when-rsyslog5-is-already-installed-in-centos-rhel/

**Comment by rgerhards** [comment]
OMG... just use the rsyslog project repository, do a yum update and be happy ;-)

https://www.rsyslog.com/downloads/download-other/

**Comment by onionka** [comment]
Thanks for answer, but I don't understand how it would solve this problem.

**Comment by onionka** [comment]
Thanks for answer :D we didn't know about this repository (I wasn't implementing it initially, I am just fixing it) - it will be tricky to use it though, but we will figure it out somehow.
