### ISSUE TITLE
nightly builds unavailable

### ISSUE THREAD

**Issue by nerdquadrat** [rsyslog/rsyslog#4409]
this issue is generally related to rsyslog fixes, but might be misplaced however. I would not know where to place it instead.

### Expected behavior
new fixes are available as nightly builds

### Actual behavior
latest fix available in nightly build repo is from Tue 11 Aug 01:05:32 CEST 2020 while lots of fixes appeared meanwhile

### Steps to reproduce the behavior
try to check if https://github.com/rsyslog/rsyslog/issues/4282 fixes your segfaults on shutdown
nightly build is not available in repo and also looking at:
http://rpms.adiscon.com/v8-stable-nightly/epel-7/x86_64/RPMS/
changes made after 11.8. are not available there for use or testing

i am expecting a file like rsyslog-8.20$month.0.master-$epoch.src.rpm
with $epoch > 1597100732 or a file with a creation date later than 11.08. but cannot find any.

### Environment
- irrelevant here

**Comment by alorbach** [comment]
Thanks for the hint. 
The problem should be fixed now.
