### ISSUE TITLE
[Bug] thread unsafe ratelimiter in imudp

### ISSUE THREAD

**Issue by antmat** [rsyslog/rsyslog#441]
Hello!
Combination of using imudp module with several threads and with "$RepeatedMsgReduction on" leads to memory corruption and segmentation faults.
This happens because imudp module has shared ratelimiter object and it is not safe to put a message inside ratelimiter in doLastMessageRepeatedNTimes and use it to produce message about repeated logs in several threads. I think better solution is to pass message separately to ratelimitGenRepMsg instead of putting it inside ratelimiter.
If you want I can create a pull request for this or you can fix it yourself :)
If you need clarification or more details please feel free to ask.

**Comment by rgerhards** [comment]
I need to think about the best way this can be done, as there are many side branches. If you like, you can porpose a PR, which would probably be a good starting point. I just can't guarantee I don't need to change details.

**Comment by rgerhards** [comment]
oh, and a side-note: I think some code in this code path is still under (L)GPLv3. We are moving towards ASL 2.0. If you do a PR, please permit us to use your patch under ASL 2.0. Thanks!
