### ISSUE TITLE
junk characters are being added to msgid while using RSYSLOG_SyslogProtocol23Format template

### ISSUE THREAD

**Issue by shardgupta** [rsyslog/rsyslog#4414]
### DebugFormat Output 
FROMHOST: 'localhost', fromhost-ip: '127.0.0.1', HOSTNAME: 'regfeadf', PRI: 134,
syslogtag 'myprog[16850]', programname: 'myprog', APP-NAME: 'myprog', PROCID: '16850', MSGID: '**Authenticationrator**',
TIMESTAMP: 'Sep  8 13:03:43', STRUCTURED-DATA: '[1@mycom type="Authentication" tenant="regfeadf"]',
msg: '﻿*****@**** User regfeadf@gmail.com logged in via API from 10.30.53.98.'
inputname: imudp **rawmsg**: '<134>1 2020-09-08T13:03:43.462745+00:00 regfeadf myprog 16850 **Authentication** [1@mycom type="Authentication" tenant="regfeadf"] ﻿*****@**** User regfeadf@gmail.com logged in via API from 10.30.53.98.'

### Expected behavior
msgid should be same as msgid in rawmsg.
### Actual behavior
Few additional characters are being added to the msgid
### Steps to reproduce the behavior
RSYSLOG_SyslogProtocol23Format use this format and try to send the messages using different length msgid.
### Environment
rsyslogd 8.32.0, compiled with:
    PLATFORM:                x86_64-pc-linux-gnu
    PLATFORM (lsb_release -d):        
    FEATURE_REGEXP:                Yes
    GSSAPI Kerberos 5 support:        Yes
    FEATURE_DEBUG (debug build, slow code):    No
    32bit Atomic operations supported:    Yes
    64bit Atomic operations supported:    Yes
    memory allocator:            system default
    Runtime Instrumentation (slow code):    No
    uuid support:                Yes
    systemd support:            Yes
    Number of Bits in RainerScript integers: 64

**Comment by rgerhards** [comment]
The version you are using is very old and no longer supported by the community. It is also very probable that the problem stems back to long-solved issues. As such, please update to the currently supported version and retry. Report back if the problem persists.

The rsyslog project provides packages for current versions: https://www.rsyslog.com/downloads/download-other/

If you insist on using an outdated version, you can also contact your distro or consider [rsyslog professional services](https://www.rsyslog.com/professional-services/enterprise-support/).

**Comment by shardgupta** [comment]
Yes, it was indeed the problem in the old version. On the latest stable build the issue is on longer seen. Thank you.
