### ISSUE TITLE
v8.11 compile fails on freebsd

### ISSUE THREAD

**Issue by rgerhards** [rsyslog/rsyslog#442]
/bin/sh ../libtool  --tag=CC   --mode=compile cc -DHAVE_CONFIG_H -I. -I..  -pthread -I../runtime -I.. -I../grammar -I/usr/local/include -I/usr/local/include/json-c -W -Wall -Wformat-security -Wshadow -Wcast-align -Wpointer-arith -Wmissing-format-attribute -Werror=implicit-function-declaration -g -I/usr/local/include   -g -O2 -c -o lmnet_la-net.lo `test -f 'net.c' || echo './'`net.c
libtool: compile:  cc -DHAVE_CONFIG_H -I. -I.. -pthread -I../runtime -I.. -I../grammar -I/usr/local/include -I/usr/local/include/json-c -W -Wall -Wformat-security -Wshadow -Wcast-align -Wpointer-arith -Wmissing-format-attribute -Werror=implicit-function-declaration -g -I/usr/local/include -g -O2 -c net.c -o lmnet_la-net.o
net.c:495:9: error: no member named 's6_addr32' in 'struct in6_addr'
                addr->s6_addr32[i++] &= htonl(0xffffffff << (32 - (bits % 32)));
                ~~~~  ^
net.c:496:27: error: no member named 's6_addr32' in 'struct in6_addr'
        for (; i < (sizeof addr->s6_addr32)/4; i++)
                           ~~~~  ^
net.c:497:9: error: no member named 's6_addr32' in 'struct in6_addr'
                addr->s6_addr32[i] = 0;
                ~~~~  ^

**Comment by alorbach** [comment]
Invalid because "--build=x86_64-pc-linux-gnu" was set in the configure. 
This caused OS_BSD not to be defined (As configure was done for LINUX). 

Fixed by removing "--build=x86_64-pc-linux-gnu" from configure.
