### ISSUE TITLE
Case insensitive variants of 'regex' and 'ereregex' Property-Based Filter compare-operations

### ISSUE THREAD

**Issue by nickbroon** [rsyslog/rsyslog#4429]
### Enhancement

Case insensitive variants of 'regex' and 'ereregex' Property-Based Filter compare-operations would be very useful

https://www.rsyslog.com/doc/v8-stable/configuration/filters.html#compare-operations
Extended Posix regular expressions do not have as case modifier, (unlike PCRE, which has `?i`), but some posix regex libraries do support disabling case sensitivity (eg https://www.boost.org/doc/libs/1_41_0/libs/regex/doc/html/boost_regex/ref/syntax_option_type/syntax_option_type_extended.html) 

Could rsyslog support case insensitivity ereregex?

### Environment
- rsyslog version: 8.2002.0
- platform: Debian

**Comment by nickbroon** [comment]
Could a `ereregex_i`  filter be added, and the underlying `rsCStrSzStrMatchRegex()` functions that is called take another parameter that results in adding the `REG_ICASE` flag to  the `regexp.regcomp()` function that abstracts the posix regex library?

https://www.gnu.org/software/libc/manual/html_node/Flags-for-POSIX-Regexps.html

**Comment by rgerhards** [comment]
@nickbroon that sounds like a good idea, especially if we can keep existing lib and it's only an option

**Comment by nickbroon** [comment]
As well as adding as new a `ereregex_i` property-based filter that basically extends `ereregex`, could a new function `re_match_i()` be similarly added that extends the existing `re_match()` function with case insensitive matching?

**Comment by rgerhards** [comment]
@nickbroon do you think we absolutely need an old-style property based filter? In #4574 I have added a new script function `re_match_i()`. Looking at the old system, it is considerably more work to add it there, even requires upgrades of support libs, something I really want to avoid.

**Comment by nickbroon** [comment]
Thanks @rgerhards for looking at this, and your PR. For the use case I was looking at the `re_match_i()` function is probably sufficient.

https://github.com/danos/vyatta-syslog/blob/master/lib/Vyatta/Syslog.pm#L249
https://github.com/danos/vyatta-syslog/blob/master/yang/vyatta-system-syslog-enhanced-v1.yang#L108

https://github.com/danos/vyatta-syslog/blob/master/tests/fixture/syslog/json-input/enhanced_dampened#L52
https://github.com/danos/vyatta-syslog/blob/master/tests/fixture/syslog/good-rsyslog.d/enhanced_dampened#L40

**Comment by rgerhards** [comment]
@nickbroon thx for the feedback, so I'll keep it to the new function for now. It's not only simpler, it also reduces code clutter.
