### ISSUE TITLE
accessing a non-existing key creates an empty parent object

### ISSUE THREAD

**Issue by julthomas** [rsyslog/rsyslog#4430]
Hello,

Here is a behavior that is a bit annoying.
I tried to have a look at it a while ago but seems to be a bit difficult for me...

### Expected behavior

I would expect that rainerscript statement  `if ($!foo!bar != "") then ...` do not create a `$!foo` empty object if `$!foo` did not exist before the statement is executed.

### Actual behavior

Performing a condition (eg: check for an empty string) on a subtree key that do not exists (depth > 1 from the root container), creates an empty "parent" object. Depending on your context, you may end up with (kind of...) annoying garbage when producing object documents (for instance to index in ES).

I think I could live with it if I was able to check for object type on the parent before performing the condition, or maybe just having a sort of isset() test function. However that really feels like a bug, so I felt it was a good idea to start sharing on this topic, because Rainer or someone else could have an idea for a quick fix!

### Steps to reproduce the behavior

```
unset $!; 

if ($!source!ip == "") then
    set $!source_ip_was_empty_or_not_set = 1;
else
    set $!source_ip_was_empty_or_not_set = 0;

if ($!a!b!c!d == "") then
    set $!a_b_c_d_was_empty_or_not_set = 1;
else
    set $!a_b_c_d_was_empty_or_not_set = 0;  
```
Produces:
```
{ "$!": { "source_ip_was_empty_or_not_set": 1, "a": { "b": { "c": { } } }, "a_b_c_d_was_empty_or_not_set": 1 } }
```

### Environment
- rsyslog version: 8.2006.0
- platform: CentOS 8

**Comment by julthomas** [comment]
I did not pay attention before, but I actually just realized that the `unset $!` on top made the issue with the first test go away.

See the difference if I set some key at depth 1 just after the `unset $!`.

```
unset $!;
set $!something = "abc";

if ($!source!ip == "") then
    set $!source_ip_was_empty_or_not_set = 1;
else
    set $!source_ip_was_empty_or_not_set = 0;

if ($!a!b!c!d == "") then
    set $!a_b_c_d_was_empty_or_not_set = 1;
else
    set $!a_b_c_d_was_empty_or_not_set = 0;
```
Now produces:
```
{ "$!": { "something": "abc", "source": { }, "source_ip_was_empty_or_not_set": 1, "a": { "b": { "c": { } } }, "a_b_c_d_was_empty_or_not_set": 1 } } 
```
We get an empty `"source": { }` and (like before) an empty `"a": { "b": { "c": { } } }`.

**Comment by julthomas** [comment]
Here is another example:
```
unset $!;
set $!x = $!a!b!c!d!e;
set $!y = $!z!y!x!w!v;
```
Produces:
```
{ "$!": { "x": "", "z": { "y": { "x": { "w": { } } } }, "y": "" } }
```

`"x": ""` OK
`"y": ""` OK
`"z": { ...` makes an unexpected appearance!

**Comment by rgerhards** [comment]
milestone tentatively assigned

@julthomas I think this also brings up the (old) topic of an `exit($!var)` function

**Comment by davidelang** [comment]
this is a problem in perl as well in that testing a hash element creates it.

This is one reason that an exists() type of function is needed without it, you 
have to jump through hoops to decide when to instantiate a path and when not to.

David Lang

**Comment by julthomas** [comment]
Hello guys, thanks for your input on this.
For information the proposed patch did not seam to cause harm so far on the env I'm testing it.
Julien
