### ISSUE TITLE
Messages stop recording and /run space continues to grow until it is full

### ISSUE THREAD

**Issue by ZhongxinLV** [rsyslog/rsyslog#4431]
### Expected behavior
Messages continues to be recorded, /run space usage is limited
### Actual behavior
Messages stop recording and /run space continues to grow until it is full
### Steps to reproduce the behavior
journald.conf: Storage=volatile, so journal files were saved in /run/log/. Other space config:
   RateLimitInterval=0
   RateLimitBurst=0
   SystemMaxUse=600M
   RuntimeMaxUse=30M
rsyslog.conf: *.info;mail.none;authpriv.none;cron.none;news.none                /var/log/messages
With high load logger and last for some days, messages stops recording，and /run space starts grow slowly until full;When I check the size of files in /run, it actually much smaller than the occupied space. This will recovery by "systemctl restart rsyslog".
There is a probability of occurrence, not every time. I have met several times.
	Line 17: 2020-08-22 00:01:01 Shmem:            827416 kB 
	Line 47467: 2020-08-23 00:01:54 Shmem:            953136 kB 
	Line 94958: 2020-08-24 00:01:01 Shmem:           1077224 kB 
	Line 142412: 2020-08-25 00:01:03 Shmem:           1205872 kB 
	Line 189893: 2020-08-26 00:01:02 Shmem:           1331612 kB 
	Line 237342: 2020-08-27 00:01:05 Shmem:           1457912 kB 
	Line 284813: 2020-08-28 00:01:07 Shmem:           1585644 kB 
	Line 332316: 2020-08-29 00:01:10 Shmem:           1708676 kB 
	Line 379779: 2020-08-30 00:01:12 Shmem:           1835248 kB 
	Line 427265: 2020-08-31 00:01:38 Shmem:           1962512 kB 
	Line 474757: 2020-09-01 00:01:34 Shmem:           2088624 kB 
	Line 522312: 2020-09-02 00:01:21 Shmem:           2215972 kB 
	Line 569739: 2020-09-03 00:01:33 Shmem:           2340484 kB 
	Line 617226: 2020-09-04 00:01:51 Shmem:           2465908 kB 
	Line 664690: 2020-09-05 00:01:33 Shmem:           2593876 kB 
	Line 712169: 2020-09-06 00:01:43 Shmem:           2721320 kB 
	Line 759658: 2020-09-07 00:01:49 Shmem:           2843984 kB 
	Line 807127: 2020-09-08 00:01:45 Shmem:           2969532 kB 
	Line 854641: 2020-09-09 00:01:48 Shmem:           3097384 kB 
	Line 902105: 2020-09-10 00:01:42 Shmem:           3224732 kB 
	Line 949625: 2020-09-11 00:01:56 Shmem:           3350960 kB 
	Line 1044607: 2020-09-13 00:01:48 Shmem:           3606636 kB 
	Line 1092138: 2020-09-14 00:01:53 Shmem:           3732824 kB 
	Line 1187083: 2020-09-16 00:01:45 Shmem:           3983612 kB 
	Line 1234549: 2020-09-17 00:01:01 Shmem:           4093332 kB 
	Line 1282013: 2020-09-18 00:01:28 Shmem:           4105860 kB 
	Line 1329531: 2020-09-19 00:01:27 Shmem:           4105928 kB 
	Line 1377080: 2020-09-20 00:01:46 Shmem:           4104392 kB 
	Line 1424631: 2020-09-21 00:01:39 Shmem:           4105188 kB 

### Environment
- rsyslog version: rsyslog-8.24
- platform: centos 7
The space problem might related to the #4365 ，but I don't know why messages stop.
The version is very old, and it is probabilistic. If some new versions have changed something related, who can point it?
I will have a try to check it.

Thank you.

**Comment by rgerhards** [comment]
sounds like log is rotated and no HUP sent. Might also be that HUP is incorrectly processed, IIRC there was a bug in this regard in that version. If you want to patch your old version, do a `git log` on rsyslog's git repository and try to find the commit that fixed the bug. Obviously, it is far easier to just install the current version ;-)

**Comment by ZhongxinLV** [comment]
> sounds like log is rotated and no HUP sent. Might also be that HUP is incorrectly processed, IIRC there was a bug in this regard in that version. If you want to patch your old version, do a `git log` on rsyslog's git repository and try to find the commit that fixed the bug. Obviously, it is far easier to just install the current version ;-)

Do you means it is similar to #4397 ?
I did configure a logrotate strategy of 100M compression for messages and keep 10 copies, but it includes restarting rsyslog afterwards. 
/var/log/messages {
    compress
    size 102400k
    sharedscripts
    prerotate
        rm /var/log/messages.1 2>/dev/null || true
    endscript
    copytruncate
    sharedscripts
    postrotate
        systemctl restart rsyslog.service
    endscript
    rotate 10
}
This process may cause messages to stop recording and leak space, right? Compared to directly updating the new version, I hope to know the exact location of this problem. After that, updating version will be more rigorous.

**Comment by rgerhards** [comment]
ok, this looks indeed different. If you need the exact location, check the commit logs.
