### ISSUE TITLE
omfwd stops forwarding at high message rates

### ISSUE THREAD

**Issue by awelzel** [rsyslog/rsyslog#4437]
### Expected behavior

At high message rates forwarding to the omfwd target continues.

### Actual behavior

Sending messages as fast as possible to `rsyslogd` with the provided `fast-spam.c` program fairly reliably manages to "hang" rsyslogd and forwarding to the omfwd target stops.

Sending SIGTERM to the hung rsyslog process triggers a segfault.

Our config may be unusual, but the observed behavior is rather suboptimal.

### Steps to reproduce the behavior

Terminal 1 - start the target:
```
$ nc -k -l -p 10514 | pv -b -r > /dev/null
```
Terminal 2, run rsyslogd with provided configuration:
```
$ while true ; do rsyslogd -f /etc/rsyslog/rsyslog.conf -n ; sleep 2 ; done 
```
Terminal 3:
```
$ ./fast-spam
```

The rate shown in Terminal 1 goes up when messages are received, but usually after a few seconds plummets down to 0. It doesn't need to go through `pv`, but it's a nice indicator this way.

Sending SIGTERM to the rsyslogd process (`kill $(pgrep rsyslogd)` then causes a segfault.

Terminal 2:

```
while true ; do rsyslogd -f /etc/rsyslog/rsyslog.conf -n ; sleep 2 ; done
Segmentation fault (core dumped)
Segmentation fault (core dumped)
Segmentation fault (core dumped)
Segmentation fault (core dumped)
```

### Environment
- rsyslog version: latest master today df1f698a06f
 - platform: Reproduced on Ubuntu 20.04 as described above, but seeing this in custom Linux environment as well.
- configuration
```
$ModLoad imuxsock

template(name="myformat" type="list") {
    constant(value="{ ")
    property(name="timereported" dateFormat="unixtimestamp" format="jsonf")
    constant(value=", ")
    property(name="syslogseverity-text" format="jsonf")
    constant(value=", ")
    property(name="programname" format="jsonf")
    constant(value=", ")
    property(name="msg" format="jsonf")
    constant(value=" }")
}

main_queue(
    queue.timeoutEnqueue="20"
    queue.discardSeverity="3"
)

action(
    type="omfwd"
    Target="127.0.0.1"
    Port="10514"
    Protocol="tcp"
    TCP_Framing="octet-counted"
    ResendLastMSGOnReconnect="on"


    Template="myformat"

    queue.discardMark="500"
    queue.discardSeverity="3"

    queue.timeoutEnqueue="20"
    queue.type="linkedlist"
)
```
fast-spam.c
```
#include <syslog.h>

int main(int argc, char *argv[])
{
        const char *msg = "info info info";
        while (1)
                syslog(LOG_INFO, msg);
        return 0;
}
```
Edited: Removed wrong `sizeof(msg)` in `syslog()` call.

**Comment by rgerhards** [comment]
could you get me a debug log of such a run?

**Comment by rgerhards** [comment]
I think I got a similar reproducer which works inside the testbench; still unsure what happens (so a debug log may still be useful).

**Comment by rgerhards** [comment]
no, cannot yet reproduce in testbench. Was a problem with my environment (some left-over from a failed test).

**Comment by awelzel** [comment]
Hey @rgerhards ,

here's a link to ~600MB  (6 000 000 lines) debug output compressed down to ~40MB.
https://github.com/awelzel/rsyslog-debug/raw/master/rsyslog.debug.1.xz

There were 3 "fast-spam" producers running and it took a lot more attempts to reproduce the issue with `-d` (and also stay under GBs of debug output).

Unfortunately I do not what to look for in these, so can only hope that helps.

Thanks,
   Arne

**Comment by rgerhards** [comment]
@awelzel thx for the log, will have a look soon. Actually, ATM I do also not know precisely of what I am looking for. I want to see what it carries out when the problems occur. Most probably the interesting stuff is at the end of the log, but you never know...

**Comment by rgerhards** [comment]
mhh this looks a bit like some queue counter is off; need to dig much deeper into the log

**Comment by rgerhards** [comment]
@awelzel could you, just for a test, set `queue.discardMark="900"` -- it somehow "feels" like this would change matters. I am still investigating, but that would be nice to know. I tried to get around of setting up a complete env for this, but maybe I really need to -- just takes up even more time :-(

**Comment by rgerhards** [comment]
To keep this on the record maybe for just me: a potential problem could be that when a message is discarded (due to discard mark), the queue size counter is not properly maintained. One cause might be a decrement operation which actually is not atomic albeit it is assumed to be so. What I see in the debug log might indicate the size counter is too high, ending up with a "full queue" which actually is empty (and thus stalling processing). This looks a bit like what I saw in my testing yesterday when there were some env problems.

Right now I cannot further investigate due to time limit, but that's a point to pick up from again. 

Note to others: this is a wild and unconfirmed theory, but I wanted to keep record of it.

**Comment by awelzel** [comment]
Hello @rgerhards ,

thanks you for looking into this.

> could you, just for a test, set queue.discardMark="900" -- it somehow "feels" like this would change matters.

Changing the discardMark to 900 changes matters in that it takes much longer to reproduce. In the order of ~20minutes. I'm not sure what triggers it. Collecting a debug log was impractical here.

Conversely, if discardMark is set to 100 it reproduces almost immediately.

Hope this helps.

**Comment by alorbach** [comment]
@awelzel I have tried to create a testcase for this issue which was difficult as I cannot specify a custom socket when using syslog api directly. So I have tried to create tests with imdiag as input and imtcp (tcpflood). Both tests work well, but I had to fix an issue within imdiag (See commits).

Can you let me know if you can still reproduce the issue? If yes would it be possible to get a gdb stacktrace (thread apply all bt) from a crash dump? That would at least give us an hint where the crash is happening.

**Comment by alorbach** [comment]
@awelzel : It looks like we most likely caught and fixed the issue with this PR: 
https://github.com/rsyslog/rsyslog/pull/4674
