### ISSUE TITLE
Can rsyslog run as non-root user with the immark loaded?

### ISSUE THREAD

**Issue by Johnny4Fun** [rsyslog/rsyslog#4450]
### Expected behavior
Just run rsyslog with immark and imuxsock as non-root, and config the mark log into local file. Rsyslog should be okay from my perspective. And at least, there should be a file generated at /tmp/mark.log
### Actual behavior
Non-root user has no privilege to create the default unix domain socket at `/dev/log` which can be created only by root.
### Steps to reproduce the behavior
1. load imuxsock
2. load immark
3. run `rsyslog -f my.conf -iNONE`
### Environment
- rsyslog version:  8.2008.0
- platform:  CentOS
- for configuration questions/issues, include rsyslog.conf and included config files
Here is my configuration:
```
$MaxMessageSize 4096

$EscapeControlCharactersOnReceive off

$FileCreateMode 0600

module(load="imuxsock")
module(load="immark" interval="1")

$outchannel mark_log,/tmp/marklog,10000,logrotation /tmp/marklog 1

# get mark output and stop
:msg, contains, "-- MARK --"   :omfile:$mark_log;
& stop
```

### My question
I would like to change the UDS into /tmp/uds by setting the config
`module(load="imuxsock" SysSock.Name="/tmp/uds")`. However, it seems that immark has no corresponding option for us to realize the change of location of local uds. So rsyslog could not get the message from uds. Is there any workaround to run rsyslog as non-root with the module immark loaded.

**Comment by Johnny4Fun** [comment]
Or is there any alternative for immark?

**Comment by davidelang** [comment]
it seems that you are mixing up issues, the creation of /dev/log is not immark, 
it's imuxsock (and if systemd is running, you would probably use imjournal 
instead) you would get the problem without immark (please show the actual error 
message and the full config you are trying to test)

I find immark to be pretty useless, if I want a heartbeat from the system, I 
will do something like:

iostat -nt 60 |logger -t vmstat

that puts actual useful info into the logs (vmstat is a huge amount of info in a 
very dense format)

David Lang

**Comment by Johnny4Fun** [comment]
@davidelang Hi, thanks for you reply. 
> it seems that you are mixing up issues, the creation of /dev/log is not immark,
it's imuxsock 

Yes. But it seems that the msg from immark will be forwarded to `/dev/log` And I have tried the command `iostat -nt 60 |logger -t vmstat` but logger also depend on `/dev/log`. 

To summarize, the key problem is that I want a mechanism that can prove the rsyslog is alive and available rather than stuck and dead without accessing to `/dev/log`.

**Comment by Johnny4Fun** [comment]
@davidelang immark actually calls `syslog` to write periodic heartbeat messages, i.e. write messages into /dev/log.

Since the remote rsyslog server exposed TCP port, I turned to use the command below to produce similar heartbeat messages via TCP.
`logger --tcp --server 127.0.0.1 -t "" --port 1025 -- "-- MARK --"`

Anyway, thanks for your help again!

**Comment by davidelang** [comment]
I tend to do something like

iostat 60 |logger -t iostat

that way the periodic report includes useful info rather than just MARK :-)

Davod :amg
