### ISSUE TITLE
TLS error logged on connection check

### ISSUE THREAD

**Issue by skupkosk** [rsyslog/rsyslog#4458]
### Expected behavior
No error logged.

### Actual behavior
Error message being logged
`gnutls returned error on handshake: The TLS connection was non-properly terminated.  [v8.1901.0 try https://www.rsyslog.com/e/2083 ]`

### Steps to reproduce the behavior
telnet on TLS listener and properly close TCP session wiht ^]

> ~$ telnet localhost 12514
> Trying 127.0.0.1...
> Connected to localhost.
> Escape character is '^]'.
> ^]
> telnet> quit
> Connection closed.

and check rsyslog errors in /var/log/syslog

### Environment
- rsyslog version: 8.1901
- platform: Debian 10
- for configuration questions/issues, include rsyslog.conf and included config files

Standard GnuTLS listener configuration

> global(
> DefaultNetstreamDriverCAFile="/etc/rsyslog.d/host/tls/ca.pem"
> DefaultNetstreamDriverCertFile="/etc/rsyslog.d/host/tls/host-lin-cert.pem"
> DefaultNetstreamDriverKeyFile="/etc/rsyslog.d/host/tls/host-lin-key.pem"
> )
> 
> module(
> load="imtcp"
> KeepAlive="on"
> StreamDriver.Name="gtls"
> StreamDriver.Mode="1"
> StreamDriver.AuthMode="x509/certvalid"
> )
> 
> input(type="imtcp" port="12514")

**Comment by davidelang** [comment]
That is exactly what I would expect if you telnet and don't do a TLS handshake, 
it's logging that the TLS handshake was not completed properly.

David Lang

**Comment by alorbach** [comment]
I think this is not a real issue at all, so I will close it.

**Comment by yrro** [comment]
I've got a couple of rsyslogs behind a TCP load balancer. The load balancer connectivity checks are triggering this warning message. For me this condition isn't exceptional or notable so it would be really handy if there was a way to disable it.
