### ISSUE TITLE
Need a hint for regex

### ISSUE THREAD

**Issue by systemcrash** [rsyslog/rsyslog#4460]
### Expected behavior

Trying to capture an IP found in some JSON. Been going in circles in the documentation. What am I doing wrong?

A 'column' indication of where the error is would be nice here 😄 

### Actual behavior

`invalid character '"' in object definition - is there an invalid escape sequence somewhere?`
then
`on or before line 31: syntax error on token 'remote_addr'`

### Steps to reproduce the behavior

config section:

```
template(name="ip" type="list") {
property(
name="msg"
regex.type="ERE"
regex.match="1"
regex.nomatchmode="BLANK"
regex.expression="remote_addr\":\W+\"([0-9\.:]+\)\",")
}
```

test data:

```
... "remote_addr": "185.191.171.5",  ...
```

### Environment
- rsyslog version: 
```
rsyslogd  8.1911.0-3.el8 (aka 2019.11) compiled with:
	PLATFORM:				x86_64-redhat-linux-gnu
	PLATFORM (lsb_release -d):
	FEATURE_REGEXP:				Yes
	GSSAPI Kerberos 5 support:		Yes
	FEATURE_DEBUG (debug build, slow code):	No
	32bit Atomic operations supported:	Yes
	64bit Atomic operations supported:	Yes
	memory allocator:			system default
	Runtime Instrumentation (slow code):	No
	uuid support:				Yes
	systemd support:			Yes
	Config file:				/etc/rsyslog.conf
	PID file:				/var/run/rsyslogd.pid
	Number of Bits in RainerScript integers: 64
```

- platform: 
- for configuration questions/issues, include rsyslog.conf and included config files

**Comment by systemcrash** [comment]
Tried: https://www.rsyslog.com/regex/ and https://www.rsyslog.com/rainerscript-constant-string-escaper/ - my regex seems legit.

**Comment by okket** [comment]
This is just a drive-by comment and I am not a rsyslog or regex expert, but in `"remote_addr\":\W+\"([0-9\.:]+\)\"` the escape of the closing match bracket `\)` seems wrong to me?

**Comment by rgerhards** [comment]
You need to escape the escape char (as needed e.g. in all scripting languages). I guess `\)` is meant literally. In a string, this needs to be `"\\)"`.

**Comment by systemcrash** [comment]
Thank you people - I'm quite certain I tried those permutations (intention was a grouping, not to match a ")" ). I'll go give those another shot - but it seems I could never get it to work.
