### ISSUE TITLE
Disk Assisted Queue Threads Worker Pool

### ISSUE THREAD

**Issue by frantz45** [rsyslog/rsyslog#4487]
### Expected behavior
When the parameter queue.workerThreads is set to 1 inside an action, there should never be a 2nd thread started.

### Actual behavior
When the high watermark is reached, the disk queue begins and a 2nd thread is started.
I want to use dequeueBatchSize and dequeueSlowdown to limit the output rate of an action, but it seems these parameters are bound to 1 thread, so when the 2nd threads starts, it doubles the output rate.

### Steps to reproduce the behavior
action(
  name="test"
  type="omfwd"
  Target="x.x.x.x"
  Port="514"
  Protocol="tcp"
  queue.filename="test"
  queue.maxdiskspace="1g"
  queue.type="LinkedList"
  queue.size="10000"
  queue.dequeuebatchsize="128"
  queue.dequeueslowdown="1000000"
  queue.workerThreads="1"
)

Use **ps -eLl | grep $(cat /var/run/syslogd.pid)** to display rsyslog threads.
Send many logs to reach the high watermark.
Observe that a 2nd thread is started (and the output rate is doubled).

### Environment
- rsyslog version: 8.2010.0
- platform: CentOS 7.9.2009

**Comment by rgerhards** [comment]
That's not a bug, but works as designed. As the doc says, a disk assisted queue "is two queues in one", one in-memory queue and one disk queue. Both need threads.  I agree it's unfortunate in this use case, but that's the way it is supposed to work.
