### ISSUE TITLE
Question on the queue.size parameter with a disk only queue

### ISSUE THREAD

**Issue by frantz45** [rsyslog/rsyslog#4488]
When using a disk only queue (queue.type="Disk"), what does queue.size mean ?
I understand that with DA and memory only queues queue.size refers to the maximum number of logs stored in memory, but I don't understand it with a disk only queue.
I know you can limit the disk queue size with queue.maxDiskSpace, but does queue.size also limit it ? Does the first of these two parameters reached will be the real limit ?
Maybe queue.size is just not used with a disk only queue ?
The documentation is not clear.

**Comment by rgerhards** [comment]
it's more or less ignored, so leave it as default. As a side-note, pure disk queues are often NOT what you want.

**Comment by frantz45** [comment]
Ok thank you.
I want a queue to buffer logs in case the destination is not available.
And I also need to limit the output rate (in case of a message burst or when the destination is available again).
I initially used a DA queue but I have an issue limiting the output rate (see issue https://github.com/rsyslog/rsyslog/issues/4487).
Si I can only use a pure memory or pure disk queue.
In a pure memory I can't store as much logs as in a disk queue (for example 5 GB).
And I think a pure memory queue is quite risked, I don't want to loose all buffered logs in case of rsyslog or system crash.
So in my opinion the pure disk queue is the only available option. Am I true ?
