### ISSUE TITLE
hash / pound / octothorpe character being added to the end of messages with imfile and readmode > 0

### ISSUE THREAD

**Issue by mikesphar** [rsyslog/rsyslog#4491]
This behavior might well be expected, but I couldn't find any documentation around it. Maybe I'm just looking in the wrong places?

I'm finding that with imfile ingesting log files with readMode set to 2 (or 1), the resulting messages all have a `#` character at the end. I noticed this because in some cases where the logs are json payloads, the resulting log message is failing our json parser because of the extra character, such as `{  "foo": "bar" }#`

### Expected behavior
No unexpected characters added to log messages

### Actual behavior

Messages have `#` added at the end when readmode > 0 (whether the logs are actually multiline or not)

### Steps to reproduce the behavior
Create a simple imfile input using readmode 1 or 2

Write lines to the file

Ingested log messages all have `#` added to the end

Change readmode to 0, the extra `#` character stops being added

### Environment
- rsyslog version: 8.2008.0-1
- platform: Debian 9 Stretch

I have a fairly simply test input

```
module(load="imfile")
input(
  type="imfile"
  file="/tmp/msphartest.log"
  readMode="2"
  tag="msphartest"
  reopenOnTruncate="on"
)
```

and I'm just reading the resulting logs written to /var/log/syslog

```
$ grep msphartest /var/log/syslog
Dec 30 16:03:59 host1 msphartest test3#
Dec 30 16:07:19 host1 msphartest test4#
```

**Comment by rgerhards** [comment]
Please create a debug log. Instructions: https://www.rsyslog.com/doc/v8-stable/troubleshooting/howtodebug.html

Be sure that the problem in question occurs at least once during the debug run. Once this is done, please post the debug log (e.g. via pastbin or github). After that, we can review the contents and check how exactly rsyslog processing worked.

**Comment by mikesphar** [comment]
Okay, I setup a dockerfile to install and run rsyslog in debug mode in a debian:testing container and reproduced the effect.

Version of rsyslog installed:  8.2102.0-2

These are the lines written to the test input file while rsyslogd was running
```
root@a506e1ad704e:/# cat /tmp/msphartest.log
testmessage 1
testmessage 2
testmessage 3
testmessage 4
```

And this is what was logged by rsyslog:
```
root@a506e1ad704e:/# grep msphartest /var/log/messages
Mar 26 21:50:09 a506e1ad704e msphartest testmessage 1#
Mar 26 21:50:18 a506e1ad704e msphartest testmessage 2#
Mar 26 21:50:23 a506e1ad704e msphartest testmessage 3#
```

Attached debug log:
[rsyslog.debug.gz](https://github.com/rsyslog/rsyslog/files/6214527/rsyslog.debug.gz)

Also attaching a tarfile of the docker config I used to reproduce:
[rsyslog-issue-4491.tar.gz](https://github.com/rsyslog/rsyslog/files/6214552/rsyslog-issue-4491.tar.gz)

As an additional datapoint, I was unable to reproduce this on a host running rsyslog version 8.1901.0-1

**Comment by rgerhards** [comment]
Thx - this seems to be related to readmode 2.

Would you like to give the method with `startmsg.regex` a try - I guess this could at least be a work-around.

doc; https://www.rsyslog.com/doc/v8-stable/configuration/modules/imfile.html

**Comment by mikesphar** [comment]
Thanks, I've worked around the issue for now later in my pipeline but I'll keep this in mind if I need to come back and prevent it earlier.

**Comment by davidelang** [comment]
we really should rewrite readmode 1 and 2 to use the regex match internally at 
some point.

David Lang

**Comment by rgerhards** [comment]
> we really should rewrite readmode 1 and 2 to use the regex match internally at some point.

well... it is actually faster as-is...

**Comment by davidelang** [comment]
Ok, that's justification for keeping these modes, I thought at one point you had 
told me there wasn't a speed penalty for the regex match (given suitably small 
regexes like mode 1 and 2 would have)

David Lang

**Comment by rgerhards** [comment]
Thx for the reply. On second thought I begin to think I should actually evaluate it once again... (Y)

**Comment by rgerhards** [comment]
OMG... this was just an off-by-one error inside one constant :-( Sorry it took so long to get to it and the bug was so trivial...

For that reason, I have not looked into the change of readmodes into regex - it would be much more complex. PR coming up.
