### ISSUE TITLE
rsyslog leaves imfile state files behind (these get never deleted)

### ISSUE THREAD

**Issue by rmetrich** [rsyslog/rsyslog#4494]
### Expected behavior

`imfile-state:INODE:HASH` get deleted once rsyslog finished processing the file corresponding to that inode after a log rotation occurred.

### Actual behavior

No deletion happening at all

### Steps to reproduce the behavior

1. Compile rsyslog with imfile support

   ~~~
   $ ./configure --enable-imfile
   $ make
   $ sudo make install
   ~~~

2. Create a dedicated mount point for the test (formatted with XFS preferably, so that inodes get reused)

   ~~~
   # mkdir -p /disk2/rsyslog
   ~~~

3. Create rsyslog.conf configuration file

   ~~~
   global(workDirectory="/disk2/rsyslog")
   module(load="imfile" mode="inotify")
   input(type="imfile"
      File="/disk2/input.log"
      Tag="imfile:"
      Severity="info"
      Facility="local6"
   )
   local6.info			/disk2/output.log
   ~~~

4. Create the following `logger.sh` script

~~~
#!/bin/sh

file="/disk2/input.log"
maxfilesize=$((8 * 1024 * 1024))

maxlogs=20

rotatelogs() {
	if [ -e "$file.$maxlogs" ]; then
		rm "$file.$maxlogs"
	fi

	for i in $(seq $(($maxlogs - 1)) -1 1); do
		[ -e "$file.$i" ] || continue
		mv "$file.$i" "$file.$(($i + 1))"
	done
	mv "$file" "$file.1"
	touch "$file"
}

statlogs() {
	echo
	date
	echo "$file $(stat -c "%i" $file)"
	for i in $(seq 1 $maxlogs); do
		[ -e "$file.$i" ] || break
		echo "$file.$i $(stat -c "%i" $file.$i)"
	done
}

seqnum=1
filler=$(printf "X%.0s" $(seq 1 250))
msgsize=$(printf "%09d $filler\n" $seqnum | wc -c)

writelog() {
	printf "%09d $filler\n" $seqnum >> "$file"
	let seqnum++
}

iters=$(($maxfilesize / $msgsize))
while :; do
	i=0; while [ $i -le 32140 ]; do
		if [ $(($seqnum % 1000)) -eq 0 ]; then
			echo $seqnum
		fi
		writelog
		let i++
	done
	rotatelogs
	statlogs
done
~~~

5. Execute rsyslogd with this configuration

   ~~~
   # /usr/local/sbin/rsyslogd -f ./rsyslog.conf -n
   ~~~

6. Generate logs using `logger.sh`

   ~~~
   # ./logger.sh
   ~~~

7. Wait for at least 20/30 rotations to occur, this will take a few minutes

8. Check content of `/disk2/rsyslog` directory, there are state files for files not existing anymore (INODE is gone)

### Environment
- rsyslog version: 8.2102.0.master
- platform: Fedora Rawhide (but doesn't apply really, I built from rsyslog master branch)

**Comment by rmetrich** [comment]
[repro.zip](https://github.com/rsyslog/rsyslog/files/5786976/repro.zip)

**Comment by rmetrich** [comment]
I understand that `filename` is not used for the imfile-state name because it's unreliable due to moving files (usually after logrotation), only the inode is actually right.

Unfortunately cleaning old state files is not easy since it's not possible to know if an inode is in use on the file system or not, this would require doing a `find -inum` or similar, which costs too much for sure.
I do not see how this could be improved easily for now.

The only optimization I can think of is if we found a state file for a given node and hash (what makes the name `imfile-state:INODE:HASH`, then `imstate-file:INODE:*` other files can probably be safely deleted, since they reference something deprecated for sure.

@rgerhards what do you think?

But then comes a new potential issue: the state file is based on INODE, but there is no distinction between device ids. So how could we know that a given state file prefix `imstate-file:INODE:` is not used by a file monitored hosted on another file system ...

**Comment by rmetrich** [comment]
See #4500

**Comment by rmetrich** [comment]
Hi @rgerhards my reproducer shows that the PR #4633 doesn't fix the issue at all, I still see leaks of state files.

**Comment by tapakund** [comment]
This issue seems to be there with v8.2202.0 rsyslog as well. I see https://github.com/rsyslog/rsyslog/pull/4500 in WIP state, kindly let us know if there are any updates in this area.
