### ISSUE TITLE
ommysql not writing to database but no logging of the extension either

### ISSUE THREAD

**Issue by jedvod** [rsyslog/rsyslog#4496]
### Expected behavior
Once configured with  
mail.*                                                  :ommysql:127.0.0.1,database,username,password
(with correct database and credentials)
The service should write all logs to the database specified under SystemEvents table.
### Actual behavior
No logs are written but there are mail logs flowing when viewing the logs manually
No results when using SELECT on database.
### Steps to reproduce the behavior
Not sure if this is a local configuration issue or more widespread.
Database and credentials verified as working -> Configured /etc/rsyslog.conf -> restarted rsyslogd -> sent a test mail for logging purposes -> no logs written to database
### Environment
rsyslogd  8.1911.0-7.el8 (aka 2019.11) compiled with:
        PLATFORM:                               x86_64-redhat-linux-gnu
        PLATFORM (lsb_release -d):
        FEATURE_REGEXP:                         Yes
        GSSAPI Kerberos 5 support:              Yes
        FEATURE_DEBUG (debug build, slow code): No
        32bit Atomic operations supported:      Yes
        64bit Atomic operations supported:      Yes
        memory allocator:                       system default
        Runtime Instrumentation (slow code):    No
        uuid support:                           Yes
        systemd support:                        Yes
        Config file:                            /etc/rsyslog.conf
        PID file:                               /var/run/rsyslogd.pid
        Number of Bits in RainerScript integers: 64

Running CentOS8-Stream

**Comment by jedvod** [comment]
I had rsyslog-gnutls installed but once I read a few other issues, I uninstalled it to test - didn't fix the issue and I'll leave it uninstalled at least until the underlying issue has been advised upon.

Thanks

**Comment by jedvod** [comment]
I also used the template for the database/table creation, (for MySQL)

**Comment by rgerhards** [comment]
full config pls

**Comment by jedvod** [comment]
`# rsyslog configuration file

# For more information see /usr/share/doc/rsyslog-*/rsyslog_conf.html
# or latest version online at http://www.rsyslog.com/doc/rsyslog_conf.html
# If you experience problems, see http://www.rsyslog.com/doc/troubleshoot.html

#### MODULES ####

module(load="imuxsock"    # provides support for local system logging (e.g. via logger command)
       SysSock.Use="off") # Turn off message reception via local log socket;
                          # local messages are retrieved through imjournal now.
module(load="imjournal"             # provides access to the systemd journal
       StateFile="imjournal.state") # File to store the position in the journal
#module(load="imklog") # reads kernel messages (the same are read from journald)
#module(load="immark") # provides --MARK-- message capability

# Provides UDP syslog reception
# for parameters see http://www.rsyslog.com/doc/imudp.html
#module(load="imudp") # needs to be done just once
#input(type="imudp" port="514")

# Provides TCP syslog reception
# for parameters see http://www.rsyslog.com/doc/imtcp.html
module(load="imtcp") # needs to be done just once
#input(type="imtcp" port="514")

$template RemoteLogs,"/var/log/rsyslog/%HOSTNAME%/%PROGRAMNAME%.log"
*.* ?RemoteLogs


#### GLOBAL DIRECTIVES ####

# Where to place auxiliary files
global(workDirectory="/var/lib/rsyslog")

# Use default timestamp format
module(load="builtin:omfile" Template="RSYSLOG_TraditionalFileFormat")

# Include all config files in /etc/rsyslog.d/
include(file="/etc/rsyslog.d/*.conf" mode="optional")


module(load="ommysql")
#### RULES ####


ruleset(name="RsyslogToMysql") {
*.* action(
type="ommysql"
server="localhost"
serverport="3306"
db="*REDACTED*"
uid="*REDACTED*"
pwd="*REDACTED*"
)
}

ruleset(name="RsyslogDB") {
*.* action(
type="ommysql"
server="localhost"
serverport="3306"
db="*REDACTED*"
uid="*REDACTED*"
pwd="*REDACTED*"
)
}


input(
type="imtcp"
port="514"
ruleset="RsyslogDB"
)


# Log all kernel messages to the console.
# Logging much else clutters up the screen.
#kern.*                                                 /dev/console

# Log anything (except mail) of level info or higher.
# Don't log private authentication messages!
*.info;mail.none;authpriv.none;cron.none                /var/log/messages

# The authpriv file has restricted access.
authpriv.*                                              /var/log/secure

# Log all the mail messages in one place.
#mail.*                                                  -/var/log/maillog
mail.*                                                  :ommysql:127.0.0.1,*REDACTED*,*REDACTED*,*REDACTED*


# Log cron stuff
cron.*                                                  /var/log/cron

# Everybody gets emergency messages
*.emerg                                                 :omusrmsg:*

# Save news errors of level crit and higher in a special file.
uucp,news.crit                                          /var/log/spooler

# Save boot messages also to boot.log
local7.*                                                /var/log/boot.log


# ### sample forwarding rule ###
#action(type="omfwd"
# An on-disk queue is created for this action. If the remote host is
# down, messages are spooled to disk and sent when it is up again.
#queue.filename="fwdRule1"       # unique name prefix for spool files
#queue.maxdiskspace="1g"         # 1gb space limit (use as much as possible)
#queue.saveonshutdown="on"       # save messages to disk on shutdown
#queue.type="LinkedList"         # run asynchronously
#action.resumeRetryCount="-1"    # infinite retries if host is down
# Remote Logging (we use TCP for reliable delivery)
# remote_host is: name/ip, e.g. 192.168.0.1, port optional e.g. 10514
#Target="remote_host" Port="XXX" Protocol="tcp")

$PrivDropToUser rsyslog
`

**Comment by rgerhards** [comment]
ah, that's what I suspected. You have a ruleset `RsyslogToMysql`, but you never call it. The same with `rsyslogDB`. you need to either call them or add the actions into the default ruleset (which makes more sense IMHO).

**Comment by jedvod** [comment]
So what should I put into the config if I wanted all mail (mail.*) to be out into RsyslogToMysql?

And then put RsyslogDB to default actions?

**Comment by rgerhards** [comment]
I am not sure if I understand your need fully, but:
```
...
# The authpriv file has restricted access.
authpriv.*                                              /var/log/secure

# Log all the mail messages in one place.
mail.* action(type="ommysql" server="localhost" serverport="3306" db="*REDACTED*" uid="*REDACTED*" pwd="*REDACTED*")
action(type="ommysql" server="localhost" serverport="3306" db="*REDACTED*" uid="*REDACTED*" pwd="*REDACTED*")
...
````
and also remove the two unneeded rulesets.

By this I notice you have indeed a legacy mysql action configured for mail.* - that one should fire. Nevertheless, let's clean up the config and see what remains to trouble-shoot.

**Comment by jedvod** [comment]
I want mail going to db1 with separate u/n and p/w and everything else going to db2

**Comment by jedvod** [comment]
I'll try the suggestions and then let you know.

Thanks very much!

**Comment by jedvod** [comment]
testing now, also, RsyslogDB was originally called for the imtcp input

**Comment by jedvod** [comment]
my db2 looks to have entries now, but db1 for mail.* is empty and I've sent multiple mails which have been received on the recipient's end, (after I changed the rsyslog config).

**Comment by rgerhards** [comment]
write to a file instead of the database. Let's check if there is something present inside that file.

**Comment by jedvod** [comment]
nothing yet.


Current, (updated), configuration:
`
# rsyslog configuration file

# For more information see /usr/share/doc/rsyslog-*/rsyslog_conf.html
# or latest version online at http://www.rsyslog.com/doc/rsyslog_conf.html
# If you experience problems, see http://www.rsyslog.com/doc/troubleshoot.html

#### MODULES ####

module(load="imuxsock"    # provides support for local system logging (e.g. via logger command)
       SysSock.Use="off") # Turn off message reception via local log socket;
                          # local messages are retrieved through imjournal now.
module(load="imjournal"             # provides access to the systemd journal
       StateFile="imjournal.state") # File to store the position in the journal
#module(load="imklog") # reads kernel messages (the same are read from journald)
#module(load="immark") # provides --MARK-- message capability

# Provides UDP syslog reception
# for parameters see http://www.rsyslog.com/doc/imudp.html
#module(load="imudp") # needs to be done just once
#input(type="imudp" port="514")

# Provides TCP syslog reception
# for parameters see http://www.rsyslog.com/doc/imtcp.html
##module(load="imtcp") # needs to be done just once
#input(type="imtcp" port="514")

module(load="ommysql")

$template RemoteLogs,"/var/log/rsyslog/%HOSTNAME%/%PROGRAMNAME%.log"
#*.* ?RemoteLogs
#*.*;mail.none action(type="ommysql" server="localhost" serverport="3306" db="*REDACTED*" uid="*REDACTED*" pwd="*REDACTED*")


#### GLOBAL DIRECTIVES ####

# Where to place auxiliary files
global(workDirectory="/var/lib/rsyslog")

# Use default timestamp format
module(load="builtin:omfile" Template="RSYSLOG_TraditionalFileFormat")

# Include all config files in /etc/rsyslog.d/
include(file="/etc/rsyslog.d/*.conf" mode="optional")

#### RULES ####

#input(
#type="imtcp"
#port="514"
#ruleset="RsyslogDB"
#)


# Log all kernel messages to the console.
# Logging much else clutters up the screen.
#kern.*                                                 /dev/console

# Log anything (except mail) of level info or higher.
# Don't log private authentication messages!
*.info;mail.none;authpriv.none;cron.none                /var/log/messages

# The authpriv file has restricted access.
authpriv.*                                              /var/log/secure

# Log all the mail messages in one place.
#mail.*                                                 -/var/log/maillog
#mail.*                                                 action(type="ommysql" server="localhost" serverport="3306" db="*REDACTED*" uid="*REDACTED*" pwd="*REDACTED*")
mail.*                                                  /var/log/mailtemplog
*.*;mail.none                                           action(type="ommysql" server="localhost" serverport="3306" db="*REDACTED*" uid="*REDACTED*" pwd="*REDACTED*")

# Log cron stuff
cron.*                                                  /var/log/cron

# Everybody gets emergency messages
*.emerg                                                 :omusrmsg:*

# Save news errors of level crit and higher in a special file.
uucp,news.crit                                          /var/log/spooler

# Save boot messages also to boot.log
local7.*                                                /var/log/boot.log


# ### sample forwarding rule ###
#action(type="omfwd"
# An on-disk queue is created for this action. If the remote host is
# down, messages are spooled to disk and sent when it is up again.
#queue.filename="fwdRule1"       # unique name prefix for spool files
#queue.maxdiskspace="1g"         # 1gb space limit (use as much as possible)
#queue.saveonshutdown="on"       # save messages to disk on shutdown
#queue.type="LinkedList"         # run asynchronously
#action.resumeRetryCount="-1"    # infinite retries if host is down
# Remote Logging (we use TCP for reliable delivery)
# remote_host is: name/ip, e.g. 192.168.0.1, port optional e.g. 10514
#Target="remote_host" Port="XXX" Protocol="tcp")

$PrivDropToUser rsyslog
`

**Comment by rgerhards** [comment]
If there is also nothing inside the file, your MTA does not log with `mail` facility. A bit strange, but...

Maybe there is a problem with parsing into fields. In order to see how the message is parsed add to the top of your rsyslog.conf:
```
*.* /var/log/msgfields.log;RSYSLOG_DebugFormat
```
This will create a multi-line entry for each message. Review the file and post an entry in question.

**Comment by rgerhards** [comment]
I should add you need to make sure that at least one "mail-line" is processed while this setting is active.

**Comment by jedvod** [comment]
It is a weird one - previously, my MTA was writing to /var/log/maillog along with dovecot but nothing in that file since I changed to DB config and then commented out to file. 

Testing again now with your recent info.

**Comment by jedvod** [comment]
Also, my MTA is configured to send into the mail facility.

(FYI)

**Comment by jedvod** [comment]
not writing to it without file being created automatically 
Also
not writing to it with the file being created automatically and having the owner changed to the rsyslog user, (RE the PrivDropToUser)

**Comment by jedvod** [comment]
current config
```
# rsyslog configuration file

*.* /var/log/msgfields.log;RSYSLOG_DebugFormat

# For more information see /usr/share/doc/rsyslog-*/rsyslog_conf.html
# or latest version online at http://www.rsyslog.com/doc/rsyslog_conf.html
# If you experience problems, see http://www.rsyslog.com/doc/troubleshoot.html

#### MODULES ####

module(load="imuxsock"    # provides support for local system logging (e.g. via logger command)
       SysSock.Use="off") # Turn off message reception via local log socket;
                          # local messages are retrieved through imjournal now.
module(load="imjournal"             # provides access to the systemd journal
       StateFile="imjournal.state") # File to store the position in the journal
#module(load="imklog") # reads kernel messages (the same are read from journald)
#module(load="immark") # provides --MARK-- message capability

# Provides UDP syslog reception
# for parameters see http://www.rsyslog.com/doc/imudp.html
#module(load="imudp") # needs to be done just once
#input(type="imudp" port="514")

# Provides TCP syslog reception
# for parameters see http://www.rsyslog.com/doc/imtcp.html
##module(load="imtcp") # needs to be done just once
#input(type="imtcp" port="514")

module(load="ommysql")

$template RemoteLogs,"/var/log/rsyslog/%HOSTNAME%/%PROGRAMNAME%.log"
#*.* ?RemoteLogs
#*.*;mail.none action(type="ommysql" server="localhost" serverport="3306" db="Syslog" uid="rsyslog" pwd="GKHoyYUTAG4JfMXDrkPh")


#### GLOBAL DIRECTIVES ####

# Where to place auxiliary files
global(workDirectory="/var/lib/rsyslog")

# Use default timestamp format
module(load="builtin:omfile" Template="RSYSLOG_TraditionalFileFormat")

# Include all config files in /etc/rsyslog.d/
include(file="/etc/rsyslog.d/*.conf" mode="optional")

#### RULES ####

#input(
#type="imtcp"
#port="514"
#ruleset="RsyslogDB"
#)


# Log all kernel messages to the console.
# Logging much else clutters up the screen.
#kern.*                                                 /dev/console

# Log anything (except mail) of level info or higher.
# Don't log private authentication messages!
*.info;mail.none;authpriv.none;cron.none                /var/log/messages

# The authpriv file has restricted access.
authpriv.*                                              /var/log/secure

# Log all the mail messages in one place.
#mail.*                                                 -/var/log/maillog
#mail.*                                                 action(type="ommysql" server="localhost" serverport="3306" db="postfix" uid="portfix-logs" pwd="qBmRHujKVUbxY7cwGgNe")
mail.*                                                  /var/log/mailtemplog
*.*;mail.none                                           action(type="ommysql" server="localhost" serverport="3306" db="Syslog" uid="rsyslog" pwd="GKHoyYUTAG4JfMXDrkPh")

# Log cron stuff
cron.*                                                  /var/log/cron

# Everybody gets emergency messages
*.emerg                                                 :omusrmsg:*

# Save news errors of level crit and higher in a special file.
uucp,news.crit                                          /var/log/spooler

# Save boot messages also to boot.log
local7.*                                                /var/log/boot.log


# ### sample forwarding rule ###
#action(type="omfwd"
# An on-disk queue is created for this action. If the remote host is
# down, messages are spooled to disk and sent when it is up again.
#queue.filename="fwdRule1"       # unique name prefix for spool files
#queue.maxdiskspace="1g"         # 1gb space limit (use as much as possible)
#queue.saveonshutdown="on"       # save messages to disk on shutdown
#queue.type="LinkedList"         # run asynchronously
#action.resumeRetryCount="-1"    # infinite retries if host is down
# Remote Logging (we use TCP for reliable delivery)
# remote_host is: name/ip, e.g. 192.168.0.1, port optional e.g. 10514
#Target="remote_host" Port="XXX" Protocol="tcp")

$PrivDropToUser rsyslog
```

**Comment by jedvod** [comment]
errors gone all of a sudden - imjournal now working due to commenting out the PrivDropToUser and db1 for mail.* is now logging many requests from things like the MTA and dovecot.

Not sure what was wrong with the mail one as the priv drop shouldn't have affected that, (creds are set in DB not unix user).

Anyway -- fixed. That's what matters.

Thank you very much for all of your assistance! It has been very much appreciated.
