### ISSUE TITLE
omelasticsearch https support has curle_ssl_cacert errors

### ISSUE THREAD

**Issue by akorchemniy** [rsyslog/rsyslog#452]
omelasticsearch works fine over http but fails with https. openssl s_client shows the server certs as valid, include chain certificates. 

```
# strace -e trace=file -f rsyslog -dn
64605 stat("/etc/ssl/certs/f081611a.0", {st_mode=S_IFREG|0644, st_size=1448, ...}) = 0
64605 open("/etc/ssl/certs/f081611a.0", O_RDONLY) = 7
64605 stat("/etc/ssl/certs/f081611a.1", 0x7ffc93ffe110) = -1 ENOENT (No such file or directory)
```
No further attempts are made to find additional root certs. curle_ssl_cacert (60) in omelasticsearch.c leading to run away loop hammering the server.

Work around on Ubuntu 14.04:
```
curl_easy_setopt(curl, CURLOPT_CAINFO, "/etc/ssl/certs/ca-certificates.crt");
```

**Comment by alorbach** [comment]
We could add an option to set the "CURLOPT_CAINFO" option in omelasticsearch. 
This should be a workaround for cases like this.

**Comment by rgerhards** [comment]
looks like there was no further interest, also not from someone else. Thus closing. If there is interest again, feel free to re-open.
