### ISSUE TITLE
The rsyslog-clickhouse module is required

### ISSUE THREAD

**Issue by charlesqing** [rsyslog/rsyslog#4522]
The rsyslog-clickhouse module is required？Is there any official plan to release this module

**Comment by rgerhards** [comment]
The module is already released since a couple of years.

**Comment by charlesqing** [comment]
> The module is already released since a couple of years.

How to connect to a Clickhouse?is there a tutorial？

**Comment by rgerhards** [comment]
Not a real tutorial, but some samples in the doc: https://www.rsyslog.com/doc/master/configuration/modules/omclickhouse.html
