### ISSUE TITLE
Fix librelp tlscommand tests

### ISSUE THREAD

**Issue by alorbach** [rsyslog/rsyslog#4534]
Adapt tlscommand test changes from: 
https://github.com/rsyslog/librelp/pull/225

They work on all openssl versions platforms of the testbench

**Comment by rgerhards** [comment]
you should do a check if the requried librelp version is available on the platform and, if not, skip. We cannout guarantee that all platforms always have the most recent dependencies

**Comment by alorbach** [comment]
The commit changes the tests with multiple tlscommands that should work on all librelp versions that support tlscommands.
