### ISSUE TITLE
Sending data from a log server to an SEIM device

### ISSUE THREAD

**Issue by cwknox** [rsyslog/rsyslog#4539]
### Expected behavior
We accumulate log files from all our servers into a server cleverly named syslog.  The logs arrive reliably and are saved for posterity.  Our Security team has a new SEIM (Security Event and Information Monitor) tool and they want to receive the same data over UDP 514.

Added the following line to the syslogserver.conf file on syslog:

<
*.* @seim-syslog.mydomain.com:514
>

Port 514 is open for both UDP and TCP.  the line is **after** the lines directing data to the local files.

I expected to see syslog data go to both the local files and to the SEIM server.

### Actual behavior

Nothing goes to the SEIM server.  I have tried (temporarily!) hard-coding the address, sending it to the TCP port with @@, and giving it the address of another server.  Nothing seems to send a copy of that data to the SEIM box.  Files continue to accumulate locally.  

### Environment
- rsyslog version: <
- [root@syslog rsyslog.d]# rsyslogd -v
rsyslogd 8.24.0-57.el7_9, compiled with:
        PLATFORM:                               x86_64-redhat-linux-gnu
        PLATFORM (lsb_release -d):
        FEATURE_REGEXP:                         Yes
        GSSAPI Kerberos 5 support:              Yes
        FEATURE_DEBUG (debug build, slow code): No
        32bit Atomic operations supported:      Yes
        64bit Atomic operations supported:      Yes
        memory allocator:                       system default
        Runtime Instrumentation (slow code):    No
        uuid support:                           Yes
        Number of Bits in RainerScript integers: 64
>
- platform: <Linux syslog.mydomain.com 3.10.0-1160.2.2.el7.x86_64 #1 SMP Sat Oct 17 05:06:47 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux>
- for configuration questions/issues, include rsyslog.conf and included config files

[rsyslog.zip](https://github.com/rsyslog/rsyslog/files/5999412/rsyslog.zip)

**Comment by cwknox** [comment]
One further note:  this is what goes to /var/log/messages after cycling the service:
<
Feb 18 00:38:20 syslog.chotel.com systemd: Stopped System Logging Service.
Feb 18 00:38:20 syslog.chotel.com systemd: Starting System Logging Service...
Feb 18 00:38:20 syslog.chotel.com rsyslogd: [origin software="rsyslogd" swVersion="8.24.0-57.el7_9" x-pid="11166" x-info="http://www.rsyslog.com"] start
Feb 18 00:38:20 syslog.chotel.com rsyslogd: imudp: scheduling policy set, but without priority - ignoring settings [v8.24.0-57.el7_9 try http://www.rsyslog.com/e/2205 ]
Feb 18 00:38:20 syslog.chotel.com systemd: Started System Logging Service.
>

**Comment by davidelang** [comment]
it should be as simple as you say, but without seeing your full config we don't 
have any way of guessing what's wrong (is there a stop in your config for 
example)

have you made sure that there is no firewalling blocking the connection?

what you are trying to do is a very basic function of syslog, not something that 
has changed in decades, so the fact that you are running such an old version 
(with some unknown backports by redhat) shouldn't make a difference

David Lang

**Comment by cwknox** [comment]
My entire config is attached in rsyslog.zip.  I have confirmed that Port 514 is open between syslog and the SEIM for both TCP and UDP.  Everything **looks** right, but no data flows to the SEIM.  The version is the default version packaged with RHEL 7.  We're in the process of moving to 8 but this box isn't there yet.

Appreciate any further thoughts.

Chris

**Comment by davidelang** [comment]
if you do a tcpdump on the receiving system, do you see the data?
can you manually send data to the port using nc/telnet/similar?

David Lang

**Comment by cwknox** [comment]
Thanks for following up, David.  The security team got it straightened out on their end and it's working.  We can close this.

**Comment by davidelang** [comment]
that is by far the most common cause of this.

David Lang
