### ISSUE TITLE
Extraneous space being added to messages received over network

### ISSUE THREAD

**Issue by bhaveshdavda** [rsyslog/rsyslog#4548]
### Expected behavior
For a message received over the network, rsyslog should faithfully write the entire message as is to the configured file:
From strace:
```
20986 recvfrom(7, "[2021-03-08T21:34:18.667965+00:0"..., 131072, MSG_DONTWAIT, NULL, NULL) = 223
```

### Actual behavior
When written to the configured file, it adds an extra space in the embedded timestamp in the message:
From strace:
```
22103 write(8, "Mar  8 21:34:18 10.51.52.231 [20"..., 253) = 253
 | 00000  4d 61 72 20 20 38 20 32  31 3a 33 34 3a 31 38 20  Mar  8 21:34:18  |
 | 00010  31 30 2e 35 31 2e 35 32  2e 32 33 31 20 5b 32 30  10.51.52.231 [20 |
 | 00020  32 31 2d 30 33 2d 30 38  54 32 31 3a 20 33 34 3a  21-03-08T21: 34: |
 | 00030  31 38 2e 36 36 37 39 36  35 2b 30 30 3a 30 30 5d  18.667965+00:00] |
```
Configuration is simple:
```
:msg, contains, "[AUTHPRIV]"    -/var/log/secure.site.log
& ~
```
### Environment
- rsyslog version: 
  rsyslogd 8.24.0-57.el7_9, compiled with:
	PLATFORM:				x86_64-redhat-linux-gnu
	PLATFORM (lsb_release -d):
	FEATURE_REGEXP:				Yes
	GSSAPI Kerberos 5 support:		Yes
	FEATURE_DEBUG (debug build, slow code):	No
	32bit Atomic operations supported:	Yes
	64bit Atomic operations supported:	Yes
	memory allocator:			system default
	Runtime Instrumentation (slow code):	No
	uuid support:				Yes
	Number of Bits in RainerScript integers: 64
- platform:  Oracle Linux 7.9
- for configuration questions/issues, include rsyslog.conf and included config files

**Comment by davidelang** [comment]
please log a sample message with the template RSYSLOG_DebugFormat, that will 
show us exactly what is being received and what is being parsed from it.

I suspect that you want to change the template that you are using to write the 
message to your file. I am not seeing anything incorrect with the timestamp you 
show in the output. The RFC for the date format that is being used by default 
has two characters for the day, and a leading space for single digit days, so 
that is working per spec.

but if you are really wanting the newer timestamp format, you need to select a 
different template to write to disk with.

David Lang

**Comment by bhaveshdavda** [comment]
Here's the result of RSYSLOG_DebugFormat:

```Debug line with all properties:
FROMHOST: '10.51.52.231', fromhost-ip: '10.51.52.231', HOSTNAME: '10.51.52.231', PRI: 13,
syslogtag '[2021-03-08T23:', programname: '', APP-NAME: '', PROCID: '-', MSGID: '-',
TIMESTAMP: 'Mar  8 23:36:42', STRUCTURED-DATA: '-',
msg: '36:42.129371+00:00] [AUTHPRIV] [INFO] [] su: [HOST_ID: XXX] [CTR_ID: -] [HOST_NW_ADDR: 10.51.52.231] --  pam_unix(su:session): session opened for user XXX by (uid=0)'
escaped msg: '36:42.129371+00:00] [AUTHPRIV] [INFO] [] su: [HOST_ID: XXX] [CTR_ID: -] [HOST_NW_ADDR: 10.51.52.231] --  pam_unix(su:session): session opened for user XXX by (uid=0)'
inputname: imtcp rawmsg: '[2021-03-08T23:36:42.129371+00:00] [AUTHPRIV] [INFO] [] su: [HOST_ID: XXX] [CTR_ID: -] [HOST_NW_ADDR: 10.51.52.231] --  pam_unix(su:session): session opened for user XXX by (uid=0)'
$!:
$.:
$/:
```

**Comment by bhaveshdavda** [comment]
Interesting, looks like it tried to parse the message using some expected format, which the sent message was not in, as show in the strace recvfrom() in my original post

**Comment by bhaveshdavda** [comment]
So I introduced a template to work around this. Is this the right way to deal with this sort of thing?

```
$template rawFmt,"%rawmsg%\n"
:msg, contains, "[AUTHPRIV]"    -/var/log/secure.site.log;rawFmt
& ~
```

Results in:
```
[2021-03-09T00:09:42.492375+00:00] [AUTHPRIV] [INFO] [] sshd[26886]: [HOST_ID: XXX] [CTR_ID: -] [HOST_NW_ADDR: 10.51.52.231] --  Did not receive identification string from 127.0.0.1
```

**Comment by rgerhards** [comment]
> Interesting, looks like it tried to parse the message using some expected format

yup, we expect syslog RFC format - after all, this is syslog ;-)

Your work-around is exactly what I would have suggested!
