### ISSUE TITLE
rsyslog stop logging  after 7 minutes since it was started  and only resume logging after user restart it manually.

### ISSUE THREAD

**Issue by kjlau0112** [rsyslog/rsyslog#4556]
### Expected behavior
rsyslog should continue logging after 7 minutes and manually restart is not necessary to trigger continuous  logging

### Actual behavior
rsyslog stop logging after 7 minutes and manually restart is required to trigger continuous  logging

### Steps to reproduce the behavior
1. Install  yocto based  beaglebone with rsyslog recipe and populate rsyslog.conf  with the contents as shown in rsyslog_conf.txt

2. create and run the shell script with following content
a=10
i=0
until [ $a -lt 10 ]
do
   echo $i
   logger -p local0.error "TroubleshootingTest $i" 
   i=`expr $i + 1`
done

3. observe /var/log/syslog size is in creasing using ls -al /var/log/syslog
4. 7 minutes later , observe that /var/log/syslog size no longer increasing.
5. run  systemctl status rsyslog.service, observe that system logging is running
   System Logging Service
     Loaded: loaded (/lib/systemd/system/rsyslog.service; enabled; vendor preset: enabled)
     Active: [[0;1;32mactive (running)[[0m since Wed 2021-03-17 08:39:24 UTC; 8min ago
       Docs: man:rsyslogd(8)
             http://www.rsyslog.com/doc/
   Main PID: 219 (rsyslogd)
      Tasks: 11 (limit: 1138)
     CGroup: /system.slice/rsyslog.service
             └─219 /usr/sbin/rsyslogd -n
6. run  systemctl restart  rsyslog.service
7. observe that /var/log/syslog size is increasing.

### Environment
- rsyslog version: 
rsyslogd 8.29.0, compiled with:
        PLATFORM:                               arm-poky-linux-gnueabi
        PLATFORM (lsb_release -d):
        FEATURE_REGEXP:                         Yes
        GSSAPI Kerberos 5 support:              No
        FEATURE_DEBUG (debug build, slow code): No
        32bit Atomic operations supported:      Yes
        64bit Atomic operations supported:      No
        memory allocator:                       system default
        Runtime Instrumentation (slow code):    No
        uuid support:                           Yes

- platform: beaglebone Yocto

**Comment by kjlau0112** [comment]
[rsyslog_conf.txt](https://github.com/rsyslog/rsyslog/files/6155093/rsyslog_conf.txt)

**Comment by kjlau0112** [comment]
[rsyslog_conf.txt](https://github.com/rsyslog/rsyslog/files/6155152/rsyslog_conf.txt)

**Comment by rgerhards** [comment]
The version you are using is very old and no longer supported by the community. It is also very probable that the problem stems back to long-solved issues. As such, please update to the currently supported version and retry. Report back if the problem persists.

The rsyslog project provides packages for current versions: https://www.rsyslog.com/downloads/download-other/

If you insist on using an outdated version, you can also contact your distro or consider [rsyslog professional services](https://www.rsyslog.com/professional-services/enterprise-support/).

**Comment by davidelang** [comment]
look for logs from rsyslog, and enble the impstats module to dump info about the 
internal state of rsyslog (you can dump it to a separate file so that it's 
independent of log processing)

Also, I would suggest that you migrate your attempt to use outchannel to the 
action() format, I don't think that what your configuration is telling it to do 
matches what you think you are telling it to do.

David Lang

**Comment by kjlau0112** [comment]
Hi all thanks for the quick response, after referring to following link
https://gerrit.openbmc-project.xyz/c/openbmc/openbmc/+/41107/3/meta-openembedded/meta-oe/recipes-extended/rsyslog/rsyslog_8.2102.0.bb 
to update the rsyslogd software to the latest and perform a cleanup build. The issue no longer there.
Thx again.
