### ISSUE TITLE
Syslog Tag character length limit > 511

### ISSUE THREAD

**Issue by ankit167** [rsyslog/rsyslog#4560]
As per doc, max 511 characters are supported in syslog tag
https://www.rsyslog.com/sende-messages-with-tags-larger-than-32-characters/

Is there a way to increase the syslog tag character length limit to more than 511 characters?

Doc references (if any) would be helpful

**Comment by rgerhards** [comment]
more than 511????? You know that 32 is RFC max size? Looks like it is time to re-design an app..

Anyhow: you need to create a fix and compile rsyslog with the new limit.

**Comment by ankit167** [comment]
Thank you for attending the query @rgerhards 

We have been pushing app metadata as part of syslog tags. Due to certain changes, more number of app metadata is being pushed, which is basically breaching the syslog tags character limit.

We are exploring ways to solve this. Hence this query. Thank you for the response, again.

**Comment by davidelang** [comment]
to push an arbitrary amount of metadata, make the body of the message json, that 
way you can add whatever metadata you want and still be able to recover the 
original message.

I do
set $!msg = $msg;
set $!trusted!foo = metadata;
set $!trusted!bar = metadata2;
set $!trusted!baz = metadata3;

makes it really easy without abusing the transport layer

David Lang
