### ISSUE TITLE
imkmsg is not calculating timestamps correctly

### ISSUE THREAD

**Issue by wizeman** [rsyslog/rsyslog#4561]
The imkmsg module is calculating timestamps incorrectly.
It is off by a few seconds on my Raspberry Pi and off by almost 10 hours on my laptop.

I've tracked down the issue to these offending lines:
https://github.com/rsyslog/rsyslog/blob/0be64ea70947ba60565cf503d575b479b4bdf358/contrib/imkmsg/kmsg.c#L132-L150

I suspect that the code I linked above might not be taking into account small time corrections (by an NTP daemon such as chronyd) and/or possibly the time elapsed while the computer has been suspended (potentially hours/days), but I haven't tested this.

This is affecting both the `timereported` and the `timegenerated` properties, so it seems that there is no way to get correct timestamps (with say, up to 1 second delay on an otherwise idle system).

The following patch solves the issue for me, at the expense of ignoring the timestamps in `/dev/kmsg` and just using the time when the messages are processed:
```patch
diff --git a/contrib/imkmsg/kmsg.c b/contrib/imkmsg/kmsg.c
index beb4076ef..379eceb99 100644
--- a/contrib/imkmsg/kmsg.c
+++ b/contrib/imkmsg/kmsg.c
@@ -57,8 +57,6 @@ static void
 submitSyslog(uchar *buf)
 {
    long offs = 0;
-   struct timeval tv;
-   struct sysinfo info;
    unsigned long int timestamp = 0;
    char name[1024];
    char value[1024];
@@ -129,27 +127,7 @@ submitSyslog(uchar *buf)
        json_object_object_add(json, name, jval);
    }
 
-   /* calculate timestamp */
-   sysinfo(&info);
-   gettimeofday(&tv, NULL);
-
-   /* get boot time */
-   tv.tv_sec -= info.uptime;
-
-   tv.tv_sec += timestamp / 1000000;
-   tv.tv_usec += timestamp % 1000000;
-
-   while (tv.tv_usec < 0) {
-       tv.tv_sec--;
-       tv.tv_usec += 1000000;
-   }
-
-   while (tv.tv_usec >= 1000000) {
-       tv.tv_sec++;
-       tv.tv_usec -= 1000000;
-   }
-
-   Syslog(priority, (uchar *)msg, &tv, json);
+   Syslog(priority, (uchar *)msg, NULL, json);
 }
```

I don't know if this is the correct solution and I'm not really interested in spending a lot of time on this so I didn't submit a PR.
That said, feel free to use the above patch as you'd like.

Thank you!

**Comment by davidelang** [comment]
so if I am reading your patch correctly, you are just ignoring the timestamp 
entirely and submitting null on to the rest of rsyslog. Is this correct?

David Lang

**Comment by wizeman** [comment]
That is correct.

I don't know if there is a better solution, because I don't even know exactly where is the source of the error in the timestamp, much less where to obtain the right offset(s) to fix the timestamp. It might even not be possible to obtain those offsets, as that might even require keeping a log of time corrections to fix the timestamps of old messages in /dev/kmsg.

But as far as I can tell, what I did is exactly the same approach as was done in the imklog module when the `ParseKernelTimestamp` module parameter is `off` (which is the default), so it's probably OK.
