### ISSUE TITLE
rsyslog multiple outputs problem

### ISSUE THREAD

**Issue by ghost** [rsyslog/rsyslog#4562]
Hello, 
Please i'm using rsyslog to centralize network devices logs.
I have multiple inputs in my rsyslog.conf file (one port for each type of device)

```
input(type="imudp" port="514") ==> for firewall type 1
input(type="imudp" port="515") ==> for firewall type 2
```

After that i'm trying to forward these inputs to logstash machine. But i want them to be sent on different ports.
I saw an example defining in the output.conf : 

`*.* @private_ip_logstash:10514`

How can i configure the output to send input logs from port 514 to logstash:10514 and input logs from port 515 to logstash:10515 ?

**Comment by rgerhards** [comment]
```
ruleset(name="rs514) {
*.* @private_ip_logstash:10514
}
ruleset(name="rs515) {
*.* @private_ip_logstash:10515
}
input(type="imudp" port="514" ruleset="rs514") 
input(type="imudp" port="515") ruleset="rs515"
```

Not checked for syntax errors.
