### ISSUE TITLE
Debounce - set minium time between same log

### ISSUE THREAD

**Issue by Summer88** [rsyslog/rsyslog#4563]
### Expected behavior
set DEBOUNCE_TIME=10sec
Reduce the duplicate information in file log.

### Actual behavior
Not managed or I cannot find it in docs

### Steps to reproduce the behavior
Remote host send multiple messages with identical $msg content.
Each message will be added in file log, that can became huge in a few time.

### Environment
```
rsyslogd  8.1901.0 (aka 2019.01) compiled with:
	PLATFORM:				x86_64-pc-linux-gnu
	PLATFORM (lsb_release -d):		
	FEATURE_REGEXP:				Yes
	GSSAPI Kerberos 5 support:		Yes
	FEATURE_DEBUG (debug build, slow code):	No
	32bit Atomic operations supported:	Yes
	64bit Atomic operations supported:	Yes
	memory allocator:			system default
	Runtime Instrumentation (slow code):	No
	uuid support:				Yes
	systemd support:			Yes
	Number of Bits in RainerScript integers: 64

```

- platform:  Debian 9

**Comment by rgerhards** [comment]
Why do you think the mentioned environment variable will affect rsyslog?

**Comment by Summer88** [comment]
I'm not referring to an environnment variable, "set DEBOUNCE_TIME=10sec" refer to a possible "future" new configuration parameter, it's an advice.

Maybe in next version some dev can add it to manage the behavior I've explained in the previous post.

**Comment by davidelang** [comment]
In general, throwing away logs because they are duplicates is a bad idea, at the 
very least you would want to count how many copies of the logs exist.

If you are asking for a new feature, you need to give a lot more information 
about the feature and how it would work.

for example, are you just talking about eliminating
a
a
a
a

or are you talking about eliminating duplicates if the pattern is

a
b
a
b
a
b


if the first, look at the repeated message reduction option.

David Lang

**Comment by Summer88** [comment]
Thank you for your advice, that's exactly the case. 

 https://rsyslog.readthedocs.io/en/latest/configuration/action/rsconf1_repeatedmsgreduction.html

**Comment by davidelang** [comment]
As a note, repeatedmsgreduction was created decades ago when all logs were reviewed manually. In that situation, collapsing messages like this is very useful.

However, when you have software doing most of the analysis (including automated searching through the logs), the collapsed messages that result from this tend to hide problems from the analysis, so it's generally best practice to not collapse them if you have the logs going into a SIEM (including Splunk, ELK, etc)
