### ISSUE TITLE
omhttp dynrestpath fails when batching is enabled

### ISSUE THREAD

**Issue by orion84** [rsyslog/rsyslog#4567]
### Expected behavior
I have configured an omhttp action to send events to Splunk. This is working fine until I started testing the use of a templated restpath using dynrestpath="on" (See code below). 

### Actual behavior
When setting dynrestpath="off" and setting the restpath directly using the exact same string from the template it works. When using the templated approach, I get below error:

omhttp: checkResult error http status code: 404 reply: {"text":"The requested URL was not found on this server.","code":404} [v8.2102.0 try https://www.rsyslog.com/e/2218 ]

Temporarily disabling ssl, I see the following in tcpdump:
` POST /restpathhecraw HTTP/1.1`

Which indicates that it is ignoring the `dynrestpath = "on"` and just takes the template name as the restpath.

### Steps to reproduce the behavior
relevant parts of the config:
```
template(name="restpathhecraw" type="string" string="services/collector/raw?sourcetype=syslog&source=centos7_omhttp&host=centos7")

ruleset(name="tcp9001-omhttptest-HEC"){
	action(
		name="tcp9001-omhttptest-HEC"
		type="omhttp"
		...
		dynrestpath = "on"
		restpath="restpathhecraw"
		...
```

### Environment
- rsyslog version: 8.2102.0
- platform: Centos 7

**Comment by alorbach** [comment]
I think you need to specify the restpathhecraw as template parameter: 

> template(name="restpathhecraw" type="string" string="services/collector/raw?sourcetype=syslog&source=centos7_omhttp&host=centos7")
> 
> ruleset(name="tcp9001-omhttptest-HEC"){
> 	action(
> 		name="tcp9001-omhttptest-HEC"
> 		type="omhttp"
> 		...
> 		dynrestpath = "on"
> 		template="restpathhecraw"
> 		...

Thats where omhttp is expected the template when dynrestpath is set to on.

**Comment by orion84** [comment]
@alorbach the template parameter is for the message formatting, not for the dynamic rest path, right? It also says in the documentation:

> dynrestpath
> When this parameter is set to “on” you can specify a template name in the parameter **restpath** instead of the actual path.
(emphasis mine)

You can also see from the `POST /restpathhecraw HTTP/1.1` that I captured of the network that it tries to connect to an endpoint as per the value of the restpath parameter. It just fails to interpret that as a reference to a template rather than a literal value.

If it would be using whatever is specified in the template parameter (which I do also use for formatting the message) I would get very different results.

**Comment by alorbach** [comment]
@orion84 : I am sorry you are right. I took a look to the source code yesterday and missed the part where restPath is copied into the internal template structure - so your configuration is fully valid as far as I can tell. 

Could you create a debug log (See https://www.rsyslog.com/doc/master/troubleshooting/debug.html )? 
I want to see the debug output of omhttp, there maybe a real bug here.

**Comment by orion84** [comment]
@alorbach please see the debug log attached.
[rsyslog_debug.log](https://github.com/rsyslog/rsyslog/files/6308987/rsyslog_debug.log)

**Comment by alorbach** [comment]
@orion84 I tried to create a test to reproduce the problem but I was not able to, see my commit:
https://github.com/alorbach/rsyslog-1/commit/d0984865d5ccdcf8ee9c3cb8a990a35f06f7c458

Could you create a minimal configuration which reproduces the problem?

**Comment by orion84** [comment]
@alorbach I did some further testing creating a simple config file and starting a separate rsyslog process. Just to rule out any peculiarities in the OS's built in rsyslog daemon config that I was adding on to before.

I create below configs and then just started rsyslog like this:
`/usr/sbin/rsyslogd -n -f /opt/rsyslog/omhttptest.conf -i /opt/rsyslog/rsyslog-test.pid`

(The main rsyslog instance of the OS is configured to forward events to that port 9001 so I have some data coming in)

It seems to depend on whether or not batching is enabled. When I disable batching, it works as expected taking the endpoint as per the template, when I enable batching it fails due to taking the template name as the endpoint.

**Working Config:**
```
$DebugFile /home/centos/rsyslog_debug.log
$DebugLevel 2

module(load="imtcp")
module(load="omhttp")

### omhttptest  ###

template(name="hecrestpath" type="string" string="services/collector/raw?sourcetype=syslog&source=centos7_omhttp&host=centos7")

template(name="rawhec" type="list") {
    property(name="rawmsg")
    }

### Rule Sets
ruleset(name="tcp9001-omhttptest-HEC"){
        action(
                name="tcp9001-omhttptest-HEC"
                type="omhttp"
                server="splunk.orion84.nl"
                serverport="8088"
                useHttps = "off"
                dynrestpath = "on"
                restpath="dynrestpath"
                httpheaders=[
                        "Authorization: Splunk ed638a16-f50d-462d-842a-60b2ef16231d",
                        "x-splunk-request-channel: 2cf371f9-c376-480d-897b-157e49fe4ce9"
                ]
                template="rawhec"

                batch="off"


                retry="off"
              )
}

### Listeners
input(type="imtcp" port="9001" ruleset="tcp9001-omhttptest-HEC")
```

**Failing Config:**
```
$DebugFile /home/centos/rsyslog_debug.log
$DebugLevel 2

module(load="imtcp")
module(load="omhttp")

### omhttptest  ###

template(name="hecrestpath" type="string" string="services/collector/raw?sourcetype=syslog&source=centos7_omhttp&host=centos7")

template(name="rawhec" type="list") {
    property(name="rawmsg")
    }

### Rule Sets
ruleset(name="tcp9001-omhttptest-HEC"){
        action(
                name="tcp9001-omhttptest-HEC"
                type="omhttp"
                server="splunk.orion84.nl"
                serverport="8088"
                useHttps = "off"
                dynrestpath = "on"
                restpath="dynrestpath"
                httpheaders=[
                        "Authorization: Splunk ed638a16-f50d-462d-842a-60b2ef16231d",
                        "x-splunk-request-channel: 2cf371f9-c376-480d-897b-157e49fe4ce9"
                ]
                template="rawhec"

                batch="on"


                retry="off"
              )
}

### Listeners
input(type="imtcp" port="9001" ruleset="tcp9001-omhttptest-HEC")
```

**Comment by alorbach** [comment]
I could reproduce the problem, and I have created a patch which is currently running on our testbench;
https://github.com/rsyslog/rsyslog/pull/4575
