### ISSUE TITLE
omfwd action resumed queue blocks ingestion of messages.

### ISSUE THREAD

**Issue by diepes** [rsyslog/rsyslog#4570]
### Expected behavior
as omfwd does tcp forward and destination can't keep up, the queue should start buffering to disk.
this should not slowdown the ingestion of new messages to the relay.

### Actual behavior
the relay starts receiving messages, then after a couple of log alerts related to the forwarded destination, the incoming traffic to the relay is blocked by tcp window size of 0

The setting 
`action.resumeRetryCount="-1"`
seem to be the root cause, changing it to 0 makes the relay non blocking for incoming messages

Log messages - In all cases contain this
`Apr 15 08:26:45 relay rsyslogd[20710]: action 'action 0' resumed (module 'builtin:omfwd') [v8.24.0-52.amzn2 try http://www.rsyslog.com/e/2359 ]`

Log messages - when resumeRetryCount="0" the log also contains this, and relay keeps ingesting new messages
`Apr 15 08:26:45 relay rsyslogd[20710]: action 'action 0' suspended, next retry is Thu Apr 15 08:27:15 2021 [v8.24.0-52.amzn2 try http://www.rsyslog.com/e/2007 ]`

### Environment
- rsyslog version: 
```
# rsyslogd -v
rsyslogd 8.24.0-52.amzn2, compiled with:
        PLATFORM:                               x86_64-koji-linux-gnu
        PLATFORM (lsb_release -d):
        FEATURE_REGEXP:                         Yes
        GSSAPI Kerberos 5 support:              Yes
        FEATURE_DEBUG (debug build, slow code): No
        32bit Atomic operations supported:      Yes
        64bit Atomic operations supported:      Yes
        memory allocator:                       system default
        Runtime Instrumentation (slow code):    No
        uuid support:                           Yes
        Number of Bits in RainerScript integers: 64

See http://www.rsyslog.com for more information.
```
- platform: 
`Amazon Linux2`

- for configuration questions/issues, include rsyslog.conf and included config files
# Config snippets
```
# Provides TCP syslog reception
module(load="imtcp" MaxSessions="100")
input(type="imtcp" port="514")
```
```
# Where to place auxiliary files
$WorkDirectory /var/lib/rsyslog
```
```
*.* action(type="omfwd" target="10.10.10.223" protocol="tcp" port="514"
        template="Template"
        queue.filename="RsyslogQ" queue.type="LinkedList"
        queue.HighWatermark="1000" # max num of logs in ram, ave 512bytes, before using disk.
        queue.LowWatermark="100"  # num of messages in ram, before stopping disk write
        queue.maxDiskSpace="12g" # Disk-Assisted in-memory queues
        queue.saveOnShutdown="on"
        action.resumeRetryCount="-1")

```

**Comment by davidelang** [comment]
please configure impstats to write stats data to a file and show us a couple 
cycles of it's stats while you are experiencing the problem.

changing retrycount to 0 just tells it to give up if it can't deliver the 
message, so that is not what you are trying to do.

David Lang
