### ISSUE TITLE
Rsyslog: Dedicated Log server configuration//$template

### ISSUE THREAD

**Issue by kurianlinu** [rsyslog/rsyslog#4586]
### Expected behavior
I am requesting a support to amend my dedicated rsyslog server to handle forwarded logs. Currently the dedicated server is configured to receive the application logs from a specific server, The current configuration template is..
"$template HostAudit, "/var/log/netscout/%HOSTNAME%/%$YEAR%%$MONTH%%$DAY%-audit.log"
Local7.* ?HostAudit"
[Current config_v3.6rsys.txt](https://github.com/rsyslog/rsyslog/files/6412609/Current.config_v3.6rsys.txt)

But earlier the dedicated server is able to receive the logs from all servers, please see the template below,
"$template RemoteHost,"/var/log/hosts/%FROMHOST%/%$YEAR%/%$MONTH%/%syslogfacility-text%-%$DAY%.log"
$RuleSet remote
*.* -?RemoteHost"
[Old config_v3.1rsys.txt](https://github.com/rsyslog/rsyslog/files/6412610/Old.config_v3.1rsys.txt)

I need to get the logs from all servers into the dedicated server in addition to the application logs from the specific server also, how can I amend the config file with the above two template format.

### Environment
- rsyslog version: rsyslogd 8.24.0
- 
- platform: CentOS Linux release 7.5.1804 (Core)

- for configuration questions/issues, include rsyslog.conf and included config files

**Comment by davidelang** [comment]
you can just put both configs in the config file. (i.e. all 4 lines in the same 
file)

you need to explain a bit more about what is not working the way you expect.

David Lang

**Comment by kurianlinu** [comment]
Earlier the dedicated server is configured to get the logs from all the physical servers. In between we configured a particular physical server to forward the Application logs to the dedicated server, Now the Application log of that particular server only we get in Dedicated log server, no logs from other physical server.
While checking the  "/etc/rsyslog.conf" file of dedicated Log server we noticed the changes in "$template" definition.
We need both the facilities, Application logs as well as All physical server logs, Please advise.

**Comment by davidelang** [comment]
1. are all servers sending to the one server?

2. what happens when you put both sets of config in the file?

David Lang

**Comment by kurianlinu** [comment]
no it is working.
thank you
