### ISSUE TITLE
Rsyslog offline installer for ubuntu

### ISSUE THREAD

**Issue by EA2289** [rsyslog/rsyslog#4591]
Hi, 
I have an Ubuntu server with no internet connection, and I want to install on it rsyslog (currently it does not installed). 
Is there an offline installer that I can download on another host and copy to that offline server ?
If not, how can I install it ?

**Comment by davidelang** [comment]
you can download the .deb packages and install them with dpkg

see the ubuntu/debian documentation for details on how to use dpkg

David Lang
