### ISSUE TITLE
How to set rule so any message NOT from device is sent to a given template?

### ISSUE THREAD

**Issue by dachshund-digital** [rsyslog/rsyslog#4593]
I need to make sure that local messages are handled by the default rules as defined in rsyslog.conf by default.  But all messages not from the local host are routed to a given template.  Something like:

    if` %hostname% != 'localhost' then {
    *.* ?RemoteLogs
    & stop
    }

maybe...

    if %hostname != %thishost% {
    *.* ?RemoteLogs
    & stop
    }

There does not seem to be anyway to test if the message is generated from the local device?

**Comment by davidelang** [comment]
look at $fromhost-ip, I believe it's always going to be 127.0.0.1 (but not 
absolutly sure)

David Lang

**Comment by dachshund-digital** [comment]
Thanks, changed the rules implementation and thus avoid  the issue for now.  But you still can have the rules impacting the local remote log server context, something that is not what I would say should be the default behavior.  But there is nothing in the design to avoid this... just a quirk of the current design.

**Comment by rgerhards** [comment]
Well, it actually depends on what you want to do.

The default behavior matches what is done for many years and deployed to a myriad of systems. Changing it would cause a lot of grief.

For a new config, you can use multiple rulesets, see https://www.rsyslog.com/doc/master/concepts/multi_ruleset.html

There, you bind the new ruleset to the input and it is totally separated from the default one. A tutorial can be found here: https://rainer.gerhards.net/2019/10/rsyslog-relay-messages-only-no-local-storage.html#more-1493

**Comment by dachshund-digital** [comment]
Thanks!  This is really cool.
