### ISSUE TITLE
Recv-Q queue full

### ISSUE THREAD

**Issue by liumingyuan-k** [rsyslog/rsyslog#4596]
### Expected behavior

My rsyslog server uses UDP to receive system log messages, but always loses messages

### Actual behavior

Recv-Q queue is always full, resulting in message loss
Successfully receive 40,000 to 60,000 messages per second
（use 5 server like  mem:64GB  /  nic:10000baseT/Full  /  cpu:Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz)

It looks like rsyslog has insufficient processing power

State     Recv-Q    Send-Q       Local Address:Port        Peer Address:Port                                                                                    
UNCONN    214272    0                  0.0.0.0:514              0.0.0.0:*        users:(("rsyslogd",pid=4187794,fd=6))                                          
UNCONN    0         0                     [::]:514                 [::]:*        users:(("rsyslogd",pid=4187794,fd=7))    

### Environment
- rsyslog version: 8.1901.0
- platform:  Debian GNU/Linux 9.12 (stretch)
- for configuration questions/issues, include rsyslog.conf and included config files

rsyslog server config:

module(load="imudp" threads="20" timeRequery="2" batchSize="1280")
main_queue(queue.filename="main_queue"  queue.size="10000" queue.dequeuebatchsize="1000" queue.type="LinkedList"
	queue.maxdiskspace="10G"
	queue.workerthreads="20"
)	
template(name="kernlog_format" type="list" option.json="on") {
    constant(value="{")
    constant(value="\"host_ip\":\"")
    property(name="fromhost-ip")
    constant(value="\",\"receive_timestamp\":\"")
    property(name="timegenerated" dateFormat="rfc3339" position.from="1" position.to="19")
    property(name="timegenerated" dateFormat="rfc3339" position.from="27" position.to="32")
    constant(value="\",\"send_timestamp\":\"")
    property(name="timestamp" dateFormat="rfc3339")
    constant(value="\",\"facility\":\"")
    property(name="syslogfacility-text")
    constant(value="\",\"serverity\":\"")
    property(name="syslogseverity-text")
    constant(value="\",\"msg_raw\":\"")
    property(name="msg" droplastlf="on")
    constant(value="\",\"app_name\":\"")
    property(name="app-name")
    constant(value="\",\"procid\":\"")
    property(name="procid")
    constant(value="\"}\n")
}

ruleset(name="kernlog") {
    action(type="omfwd" Template="kernlog_format" Target="   < tcp server ip >      " Port="5143" protocol="tcp" queue.filename="forwarding-queue" queue.workerthreads="40" queue.size="100000" queue.dequeuebatchsize="10000" queue.maxdiskspace="50G" queue.maxfilesize="500M"  queue.type="LinkedList" )
    stop
}

input(type="imudp" port="514" ruleset="kernlog")

**Comment by davidelang** [comment]
please enable impstats and give us the output of that

threads =20 is more likely to cause grief than solve problems, what happens if 
you don't have that?

run top and hit H to show per-thread stats, you would only want to increase the 
number of threads if this shows a thread hitting 100%

David Lang

**Comment by liumingyuan-k** [comment]
The screenshot is the top output (I closed the threads parameter), and opened the impstats plugin. It seems that the output of impstats is the received udp message, which writes about 1 million files per minute
![rsyslog_server_top_pic](https://user-images.githubusercontent.com/72058036/120579837-c0762100-c45a-11eb-9e73-d5b710e45e24.png)

**Comment by davidelang** [comment]
this shows the udp input using <7% cpu, so that indicates there is some other 
cause.

what does a round of pstats show? (what config did you use for the pstats 
config)

pstats will be one round of stats every cycle, not the received udp message, so 
if you are looking at the udp message, you have something incorrect in your 
config. the pstats output will also be a single file unless you do something 
very odd with it.

please share your config.

David Lang

**Comment by liumingyuan-k** [comment]
`module(load="imudp"  timeRequery="2" batchSize="128")
module(load="impstats" interval="10")

main_queue(queue.filename="main_queue"  queue.size="10000" queue.dequeuebatchsize="1000" queue.type="LinkedList"
	queue.maxdiskspace="10G"
	queue.workerthreads="20"
)	

# string="%timegenerated:1:19:date-rfc3339% %syslogfacility-text%.%syslogseverity-text%: %msg:::drop-last-lf%\n"
template(name="kernlog_format" type="list" option.json="on") {
    constant(value="{")
    constant(value="\"host_ip\":\"")
    property(name="fromhost-ip")
    constant(value="\",\"receive_timestamp\":\"")
    property(name="timegenerated" dateFormat="rfc3339" position.from="1" position.to="19")
    property(name="timegenerated" dateFormat="rfc3339" position.from="27" position.to="32")
    constant(value="\",\"send_timestamp\":\"")
    property(name="timestamp" dateFormat="rfc3339")
    constant(value="\",\"facility\":\"")
    property(name="syslogfacility-text")
    constant(value="\",\"serverity\":\"")
    property(name="syslogseverity-text")
    constant(value="\",\"msg_raw\":\"")
    property(name="msg" droplastlf="on")
    constant(value="\",\"app_name\":\"")
    property(name="app-name")
    constant(value="\",\"procid\":\"")
    property(name="procid")
    constant(value="\"}\n")
}


ruleset(name="kernlog") {
    action(type="omfile" queue.type="linkedlist" queue.discardmark="980" 
            name="pstats" file="/data00/impstats_rsyslog.log")
    action(type="omfwd" Template="kernlog_format" Target=<tcp server ip> Port="5143" protocol="tcp" queue.filename="forwarding-queue" queue.workerthreads="40" queue.size="100000" queue.dequeuebatchsize="10000" queue.maxdiskspace="50G" queue.maxfilesize="500M"  queue.type="LinkedList" )
    stop
}


input(type="imudp" port="514" ruleset="kernlog")`





and ipmstats log file output like the image
![imp_log](https://user-images.githubusercontent.com/72058036/120581880-21532880-c45e-11eb-9f34-22261c67d386.png)

**Comment by davidelang** [comment]
this config is telling rsyslog to write every log message that arrives via udp 
to the file named impstats)rsyslog.log.

this does not include the pstats logs, which are going to the main ruleset. You 
can configure the module load line for impstats to output to a file.

David Lang

**Comment by liumingyuan-k** [comment]
> this shows the udp input using <7% cpu, so that indicates there is some other cause. what does a round of pstats show? (what config did you use for the pstats config) pstats will be one round of stats every cycle, not the received udp message, so if you are looking at the udp message, you have something incorrect in your config. the pstats output will also be a single file unless you do something very odd with it. please share your config. David Lang
> […](#)
> On Wed, 2 Jun 2021, liumingyuan-k wrote: Date: Wed, 02 Jun 2021 19:59:54 -0700 From: liumingyuan-k ***@***.***> Reply-To: rsyslog/rsyslog ***@***.***> To: rsyslog/rsyslog ***@***.***> Cc: David Lang ***@***.***>, Comment ***@***.***> Subject: Re: [rsyslog/rsyslog] Recv-Q queue full (#4596) The screenshot is the top output (I closed the threads parameter), and opened the impstats plugin. It seems that the output of impstats is the received udp message, which writes about 1 million files per minute ![rsyslog_server_top_pic](https://user-images.githubusercontent.com/72058036/120579837-c0762100-c45a-11eb-9e73-d5b710e45e24.png)

Just now I had some problems with the configuration of impstats, and the following is the output of impstats
[stats.log](https://github.com/rsyslog/rsyslog/files/6588783/stats.log)

**Comment by liumingyuan-k** [comment]
[stats_new.log](https://github.com/rsyslog/rsyslog/files/6588820/stats_new.log)

**Comment by davidelang** [comment]
that's useful, it looks like you are receiving 15-20k messages per 10 seconds.

it's fairly common for your main queue to fill up, and you have limited it's 
size to only 10k, I'd suggest increasing it. It's likely that the messages are 
arriving in bursts, filling and overflowing the main queue, but on average they 
would be handled reasonably well.

this is the type of line indicating problems

Thu Jun  3 11:53:02 2021: main Q: origin=core.queue size=8032 enqueued=19090056 
full=2517 discarded.full=17 discarded.nf=0 maxqsize=10000

the fact that the full count is non-zero and the discarded.full is nonzero are 
indications that either your queue is not big enough, or your outputs are too 
slow. In this case you have made the main queue fairly small compared to the 
message rate, so I'd start by increasing the main queue size a big (besides, I 
can't evaluate your outputs as you have not provided the full config)


another place that you could be losing logs in in the OS buffers, before rsyslog 
has a chance to fetch them (especially if the traffic is extremely bursty)

as root (or via sudo) run cat /proc/net/udp and look for any non-zero values in 
the last column (drops) if there are any, then you need to increase the buffer 
sizes. see 
https://medium.com/@CameronSparr/increase-os-udp-buffers-to-improve-performance-51d167bb1360 
for how and why to do this.

then let's see what pstats looks like under load

**Comment by davidelang** [comment]
by the way, I've had production servers with very complex configs handling 
50-60k messages/sec and test systems with stripped down configs over 300k 
messages/sec (limited by gig-e wire speed, not cpu), so rsyslog is able to 
handle the volume, we just need to track down what's happening.

If increasng the queues doesn't solve the problem, we will need to see a more 
complete config. but I'd lay odds that you are dropping messages at the OS level 
far more than anything happening at the rsyslog level. <7% cpu for the im:udp 
thread doesn't indicate big problems in rsyslog

David Lang

**Comment by davidelang** [comment]
you have timerequery=2, so you check the time every second message, try 
increasing that significantly, say 100. If messages trickle in slowly, the queue 
will empty and rsyslog will check the time again, but if you are getting 
messages at a very high rate, fetching the time frequently doesn't help and can 
be surprisingly expensive.

given the cpu load, I would be surprised if that was the cause, but it's worth 
tinkering with.

David Lang

**Comment by rgerhards** [comment]
I guess that solved the issue? For now I close, but can re-open if required.

**Comment by liumingyuan-k** [comment]
thanks David Lang! 
I will check my system configuration, and then ask our kernel team colleagues to confirm that the system configuration is optimized to solve this problem. If there is progress, I will update it here.
