### ISSUE TITLE
Rsyslog v8.21.0 freezes and blocks incoming messages on the /dev/log file

### ISSUE THREAD

**Issue by balaji-reddy** [rsyslog/rsyslog#4597]
### Expected behavior
Rsyslog should drop or ignore excessive repeated messages irrespective of the property `RepeatedMsgReduction.`

### Actual behavior
I have noticed that Rsyslog freezes and blocks the incoming log messages, means write to /dev/log file becomes a blocked call.

### Steps to reproduce the behavior
I reproduced the problem with two different configurations with the below test code,
1. Enable repeated message reduction property (`$RepeatedMsgReduction on`)
2. Having a rate limit, I kept a below rate limits
     ``` 
     $SystemLogRateLimitInterval 5
     $SystemLogRateLimitBurst 1000
     ``` 

Test code:
**Terminal1:**
```
while true; do echo "Testing rsyslog rate limit or repeated messages"; done | logger -t "rsyslog_test" 
```
**Terminal2:**
```
$> logger "Are you able to log a message" -----> blocked call
```

### Environment
- rsyslog version: v8.21.0
- platform: Custom Linux with Kernel v4.4
- for configuration questions/issues, include rsyslog.conf and included config files

**Comment by rgerhards** [comment]
The version you are using is very old and no longer supported by the community. It is also very probable that the problem stems back to long-solved issues. As such, please update to the currently supported version and retry. Report back if the problem persists.

The rsyslog project provides packages for current versions: https://www.rsyslog.com/downloads/download-other/

If you insist on using an outdated version, you can also contact your distro or consider [rsyslog professional services](https://www.rsyslog.com/professional-services/enterprise-support/).

**Comment by balaji-reddy** [comment]
I tested the v8.1911.0, and it got fixed.
