### ISSUE TITLE
Uncompression of a message failed with return code -3 - enable debug logging if you need further information. Message ignored.

### ISSUE THREAD

**Issue by gartemiev** [rsyslog/rsyslog#4598]
After adding a new host to our infrastructure which starts with "z" letter We noticed a lot of errors: 

`Uncompression of a message failed with return code -3 - enable debug logging if you need further information. Message ignored.`

After having a look into source code of rsyslog parser and going through rsyslog forums We found that everything what starts in message from 'z' letter is evaluated as compressed message and rsyslog tries to uncompress this:
https://github.com/rsyslog/rsyslog/blob/91885676001c9df1c2c91514d144cf71755d5d14/runtime/parser.c#L326

To our opinion this is not correct behavior as long as messages can usually start with 'z' letter. 

We tried may ways of disabling this behavior but none of them didn't work. So to our opinion the single solution is to replace 'z' letter with which message starts to capital 'Z' but it is a dirty fix. 

So questions are:
* Can you provide with any other solutions how to disable that behavior in smarter way?
* Can you fix that hardcoding in parser code and instead provide with parameter for enabling/disabling this?

**Rsyslog version: 8.2001.0
OS: Ubuntu 20.04**

@rgerhards @davidelang

**Comment by davidelang** [comment]
properly formatted messages start with '<' :-)
<pri> date hostname syslogtag message
or
<pri>1 date hostname program pid messageid [structured data] message

so your senders are sending malformed messages, the 'right' answer is to figure 
out why they are sending malformed messages and fix that.

that said, I believe there is an option to disable support for compression in 
the imtcp module options.

David Lang

**Comment by gartemiev** [comment]
@davidelang ,

let me explain: We read JSON files from logs and then send them to Kakfa, then We read them from kafka and send them to Postgres. 

Format of messages which We use - works fine and We can not change it since We use it for our analytics. 

Issues We observe on nodes where We read from kafka and send to Postgres (We don't use on those nodes neither imtcp nor other modules except those 2 ones).

Here is a debug mode for it: 

![image](https://user-images.githubusercontent.com/22891552/121239355-d001c980-c8a1-11eb-9fa9-572c258634f8.png)

Regarding your mentions for imtcp - We don't use them on that node where We observe those errors and in imtcp module by default compression is disabled.

**Comment by davidelang** [comment]
so where are you getting these errors? when you read them from the file via 
imfile? or are you sending the logs to another instance of rsyslog?

David Lag

**Comment by gartemiev** [comment]
@davidelang ,

I am getting these errors when I am reading data from Kafka and send it Postgres

**Comment by rgerhards** [comment]
That's actually a bit unfortunate. Rsyslog still is a syslog daemon, so we work on the assumption that it transports syslog messages and not arbitrary text. For syslog messages, the compression mode is perfectly fine. Note that some RFCs also work with special characters in front of the PRI, which MUST be at begin of message). But the message-by-message compression feature is a rsyslog extension (albeit I am not sure if some others also support it).

I see that many folks transport non-syslog, which mostly works.

I will check if I can add a global option to turn off the compression detection inside the parser module. However, that will cause grief if some well-behaving client is using the extension and you cannot reconfigure it.

**Comment by rgerhards** [comment]
@gartemiev please see #4600 for a patch to turn that capability off.

I would appreciate if you could apply the patch to your rsyslog version and check if it works for you. I will not do any testing for the case `global(parser.supportCompressionExtension=off)` as I think the patch is trivial enough to get it right (if CI works) and the use case is rare. Even more so some feedback would be appreciated.

**Comment by gartemiev** [comment]
@rgerhards , can you please provide with more details how to patch rsyslog to disable this option?

**Comment by rgerhards** [comment]
@gagantrivedi sry, I thought you were used to changing sw and patching it.

In a nutshell:
1. download the patch from https://github.com/rsyslog/rsyslog/commit/50da918ae057f0bf0d85549c0284f8ea4234eb2f.diff to a file named e.g. patch
2.  go to your rsyslog root dir
3. do `patch -p1 <patch`
4. build as usual

That should do the trick.
