### ISSUE TITLE
Is mailing list defunct?

### ISSUE THREAD

**Issue by DG12** [rsyslog/rsyslog#4603]
looking at  https://lists.adiscon.net/mailman/listinfo/rsyslog
archives
most recent archive is May 2018

Is it is defunct, can the reference to it be removed from 
https://www.rsyslog.com
header-top-righjt-menu

**Comment by davidelang** [comment]
the archivemay have failed, but the mailing list is still very active (a dozen 
or so messages today)

David Lang

**Comment by DG12** [comment]
Thanks for the VERY prompt reply. 
I don't seem to be getting any email from it lately.

Is that the preferred place to post a question or
is github preferred.

For example: where is the documentation on command line options like -s, -l (ell), -u  and -Q

**Comment by davidelang** [comment]
mailing list for questions (so more people can see them and learn from them), 
github for bugs, feature requests, etc.

I did see your email question come through on the list a bit ago, but haven't 
had the time to check the documentation. I think it's in the help text, but it 
should also be in the docs. There should be a docs package with your distro that 
matches the version that's installed, and the latest version is on the 
rsyslog.com website.

David Lang

**Comment by DG12** [comment]
Thanks again.
I am on linux mint and aptitude says 8.2001.0-lubun
synaptic package manager does not find rsyslog or rsyslogd
What am I doing wrong?

**Comment by DG12** [comment]
rsyslogd -v
rsyslogd  8.2001.0 (aka 2020.01) compiled with:
	PLATFORM:				x86_64-pc-linux-gnu
	PLATFORM (lsb_release -d):		
	FEATURE_REGEXP:				Yes
	GSSAPI Kerberos 5 support:		Yes
	FEATURE_DEBUG (debug build, slow code):	No
	32bit Atomic operations supported:	Yes
	64bit Atomic operations supported:	Yes
	memory allocator:			system default
	Runtime Instrumentation (slow code):	No
	uuid support:				Yes
	systemd support:			Yes
	Config file:				/etc/rsyslog.conf
	PID file:				/run/rsyslogd.pid
	Number of Bits in RainerScript integers: 64

See https://www.rsyslog.com for more information.

**Comment by davidelang** [comment]
I'm not that familiar with mint, I think that synaptic uses apt under the 
covers, so see if you have dpkg, if so dpkg -l |grep syslog should find the 
package name

FYI the core developers are in Germany, so it's not unusual for responses to US 
questions happen overnight.

David Lang

**Comment by rgerhards** [comment]
El vie, 11 jun 2021 a las 23:57, Dennis German ***@***.***>)
escribió:

> looking at https://lists.adiscon.net/mailman/listinfo/rsyslog
> archives
> most recent archive is May 2018
>
>
>
Mailing list is active (as you now know), but we were forced to shut down
the archive due to GDPR, which caused a lot of legal risk for us
(especially being based in Germany). You can find "non-official" archives
in many places, e.g. here:

http://rsyslog-users.1305293.n2.nabble.com/

Rainer
