### ISSUE TITLE
discarding unwanted messages does not works as the documentation says https://www.rsyslog.com/discarding-unwanted-messages/

### ISSUE THREAD

**Issue by aurelien-git** [rsyslog/rsyslog#4615]
### Expected behavior
to not log something in /var/log/messages
### Actual behavior
it does
### Steps to reproduce the behavior
edit /etc/rsyslog/rsyslog.conf as explain in https://www.rsyslog.com/discarding-unwanted-messages/
and use ~ (it says it is depracated) but if I use stop .. it continue to log the stuff
### Environment
- rsyslog version: 8.1911.0
- platform: RHEL8
- for configuration questions/issues, include rsyslog.conf and included config files

**Comment by aurelien-git** [comment]
using

`:msg, contains, "user nagios" ~`

to not log this for example ...

**Comment by davidelang** [comment]
please include the full config that isn't working.

David Lang

**Comment by aurelien-git** [comment]
I tried to discard all line from /var/log/messages
that contain : enp0s56f8e1u6 from
Jun 25 17:52:05 bob NetworkManager[1412]: <info>  [1654536325.3744] dhcp4 (enp0s56f8e1u6): option subnet_mask          => '255.255.255.0'

**Comment by aurelien-git** [comment]
(I have used many different things) :msg :pri :pri-text ... nothing seems to discard that stuff

**Comment by davidelang** [comment]
I have no idea what config you are starting from, so I have no idea what it 
means to 'delete all the lines with X'

please post your full config

I can say that stop actually does work, so there is something wrong with your 
config, but I need to see the full config and the ordering of lines in the 
config.

David Lang

**Comment by davidelang** [comment]
also, a sample log that you are trying to discard

**Comment by aurelien-git** [comment]
ok so here the thing I try to discard from /var/log/messages

```
Jun 25 18:12:05 bob NetworkManager[1412]: <info>  [1624637525.3711] dhcp4 (enp0s10f1u2i6): option dhcp_lease_time      => '400'
Jun 25 18:12:05 bob NetworkManager[1412]: <info>  [1624637525.3711] dhcp4 (enp0s10f1u2i6): option expiry               => '146853201'
Jun 25 18:12:05 bob NetworkManager[1412]: <info>  [1624637525.3712] dhcp4 (enp0s10f1u2i6): option ip_address           => '165.224.85.10'
Jun 25 18:12:05 bob NetworkManager[1412]: <info>  [1624637525.3712] dhcp4 (enp0s10f1u2i6): option requested_broadcast_address => '1'
Jun 25 18:12:05 bob NetworkManager[1412]: <info>  [1624637525.3712] dhcp4 (enp0s10f1u2i6): option requested_domain_name => '1'
Jun 25 18:12:05 bob NetworkManager[1412]: <info>  [1624637525.3712] dhcp4 (enp0s10f1u2i6): option requested_domain_name_servers => '1'
Jun 25 18:12:05 bob NetworkManager[1412]: <info>  [1624637525.3712] dhcp4 (enp0s10f1u2i6): option requested_domain_search => '1'
Jun 25 18:12:05 bob NetworkManager[1412]: <info>  [1624637525.3712] dhcp4 (enp0s10f1u2i6): option requested_host_name  => '1'
Jun 25 18:12:05 bob NetworkManager[1412]: <info>  [1624637525.3712] dhcp4 (enp0s10f1u2i6): option requested_interface_mtu => '1'
Jun 25 18:12:05 bob NetworkManager[1412]: <info>  [1624637525.3712] dhcp4 (enp0s10f1u2i6): option requested_ms_classless_static_routes => '1'
Jun 25 18:12:05 bob NetworkManager[1412]: <info>  [1624637525.3712] dhcp4 (enp0s10f1u2i6): option requested_nis_domain => '1'
Jun 25 18:12:05 bob NetworkManager[1412]: <info>  [1624637525.3712] dhcp4 (enp0s10f1u2i6): option requested_nis_servers => '1'
Jun 25 18:12:05 bob NetworkManager[1412]: <info>  [1624637525.3712] dhcp4 (enp0s10f1u2i6): option requested_ntp_servers => '1'
Jun 25 18:12:05 bob NetworkManager[1412]: <info>  [1624637525.3712] dhcp4 (enp0s10f1u2i6): option requested_rfc3442_classless_static_routes => '1'
Jun 25 18:12:05 bob NetworkManager[1412]: <info>  [1624637525.3712] dhcp4 (enp0s10f1u2i6): option requested_root_path  => '1'
Jun 25 18:12:05 bob NetworkManager[1412]: <info>  [1624637525.3712] dhcp4 (enp0s10f1u2i6): option requested_routers    => '1'
Jun 25 18:12:05 bob NetworkManager[1412]: <info>  [1624637525.3712] dhcp4 (enp0s10f1u2i6): option requested_static_routes => '1'
Jun 25 18:12:05 bob NetworkManager[1412]: <info>  [1624637525.3712] dhcp4 (enp0s10f1u2i6): option requested_subnet_mask => '1'
Jun 25 18:12:05 bob NetworkManager[1412]: <info>  [1624637525.3712] dhcp4 (enp0s10f1u2i6): option requested_time_offset => '1'
Jun 25 18:12:05 bob NetworkManager[1412]: <info>  [1624637525.3713] dhcp4 (enp0s10f1u2i6): option requested_wpad       => '1'
Jun 25 18:12:05 bob NetworkManager[1412]: <info>  [1624637525.3713] dhcp4 (enp0s10f1u2i6): option subnet_mask          => '255.255.255.0'
```

and here is part of the configuration of /etc/rsyslog.conf

#### RULES ####

# Log all kernel messages to the console.
# Logging much else clutters up the screen.
#kern.*                                                 /dev/console

# Log anything (except mail) of level info or higher.
# Don't log private authentication messages!
*.info;mail.none;authpriv.none;cron.none                /var/log/messages

**# Don't log this interface
:pri-text, contains, "enp0s10f1u2i6"                   stop**

# The authpriv file has restricted access.
authpriv.*                                              /var/log/secure

# Log all the mail messages in one place.
mail.*                                                  -/var/log/maillog

**Comment by davidelang** [comment]
Ok, the answer is simple, you have the line that writes to /var/log/messages 
ahead of the stop line, so it's already written the message before you tell it 
to stop processing the log message.

David Lang

**Comment by aurelien-git** [comment]
Ok ... sorry I finally reduce the log  level from nmcli.
