### ISSUE TITLE
Support for mTLS in omfwd

### ISSUE THREAD

**Issue by johanfleury** [rsyslog/rsyslog#4616]
### Expected behavior

While working on grafana/loki#3907 I figured `omfwd` doesn’t support mTLS (sending a client certificate for authentication).

I thought the following settings would be enough to setup mTLS, but apparently not:

```
global(
  ...
  defaultNetStreamDriverCAFile="/etc/rsyslog.d/ca.pem"
  defaultNetStreamDriverCertFile="/etc/rsyslog.d/cert.pem"
  defaultNetStreamDriverKeyFile="/etc/rsyslog.d/privkey.pem"
)

*.* action(
      type="omfwd"
      protocol="tcp"
      target="syslog.br0.fr"
      port="6514"
      template="RSYSLOG_SyslogProtocol23Format"
      tcp_framing="octet-counted"
      StreamDriver="gtls"
      StreamDriverMode="1"
    )
```

### Actual behavior

omfwd doesn’t support mTLS.

### Steps to reproduce the behavior

1. Setup a TLS server verifying client certificate and setup rsyslog as shown above
2. See that rsyslog doesn’t send a client certificate

### Environment

- rsyslog version:
```
rsyslogd  8.1901.0 (aka 2019.01) compiled with:
        PLATFORM:                               x86_64-pc-linux-gnu
        PLATFORM (lsb_release -d):
        FEATURE_REGEXP:                         Yes
        GSSAPI Kerberos 5 support:              Yes
        FEATURE_DEBUG (debug build, slow code): No
        32bit Atomic operations supported:      Yes
        64bit Atomic operations supported:      Yes
        memory allocator:                       system default
        Runtime Instrumentation (slow code):    No
        uuid support:                           Yes
        systemd support:                        Yes
        Number of Bits in RainerScript integers: 64
```
- platform: Debian 10
- for configuration questions/issues, include rsyslog.conf and included config files

**Comment by johanfleury** [comment]
Also, it would be great to be able to set certificate, key and CA per action.

**Comment by rgerhards** [comment]
> Also, it would be great to be able to set certificate, key and CA per action.

That's part of https://github.com/rsyslog/rsyslog/pull/4613

**Comment by rgerhards** [comment]
in your initial message, you configure the client to check the server. The client cert is sent if the server requests it. For this, you need to configure the server to check the client certificate.

**Comment by johanfleury** [comment]
Actually it has always worked and I’m currently receiving logs.

I was mislead by logs like that (on promtail side) `level=warn ts=2021-06-27T16:00:10.074395488Z caller=syslogtarget.go:207 msg="error initializing syslog stream" err="tls: client didn't provide a certificate"`, but they seems to actually be coming from somewhere else.

I’m sorry for the noise, thanks for you quick answer :)
