### ISSUE TITLE
imptcp module not installed in most recent version

### ISSUE THREAD

**Issue by scottbrien01** [rsyslog/rsyslog#4617]
### Expected behavior

imptcp installed when installing from ppa:adiscon/v8-stable repo

### Actual behavior

no imptcp in /usr/lib/rsyslog folder

### Steps to reproduce the behavior

Install or upgrade rsyslog

### Environment
rsyslogd  8.2008.0.9d70869d4ea5 (aka 2020.08) compiled with:
        PLATFORM:                               x86_64-pc-linux-gnu
        PLATFORM (lsb_release -d):
        FEATURE_REGEXP:                         Yes
        GSSAPI Kerberos 5 support:              No
        FEATURE_DEBUG (debug build, slow code): No
        32bit Atomic operations supported:      Yes
        64bit Atomic operations supported:      Yes
        memory allocator:                       system default
        Runtime Instrumentation (slow code):    No
        uuid support:                           Yes
        systemd support:                        Yes
        Config file:                            /etc/rsyslog.conf
        PID file:                               /var/run/rsyslogd.pid
        Number of Bits in RainerScript integers: 64

- platform: Ubuntu 20.04
 dpkg --listfiles rsyslog | grep imtcp
/usr/lib/rsyslog/imtcp.so

dpkg --listfiles rsyslog | grep imptcp

**Comment by friedl** [comment]
Please check by giving the dpkg command the full package name. Imptcp is an addon module and not included in the base rsyslog package, hence I assume it could not be found.

```
test@ubuntu:~$ dpkg --listfiles rsyslog-imptcp | grep imptcp
/usr/lib/rsyslog/imptcp.so
/usr/share/doc/rsyslog-imptcp
/usr/share/doc/rsyslog-imptcp/changelog.Debian.gz
/usr/share/doc/rsyslog-imptcp/NEWS.Debian.gz
/usr/share/doc/rsyslog-imptcp/copyright
```

Or you could look for the actual module file in the folder and confirm it is (not) present:

```
sudo find / -name imptcp.so
/usr/lib/rsyslog/imptcp.so
```

**Comment by scottbrien01** [comment]
yep - I made a mistake and thought imptcp was installed natively with rsyslog.

Thanks for educating me.

Closing the issue.
