### ISSUE TITLE
Tests do not work on Freebsd 

### ISSUE THREAD

**Issue by alorbach** [rsyslog/rsyslog#462]
Freebsd default shell csh works different in certain cases. 
All scripts use DOT (.) to execute diag.sh scripts in the same context. The script is executes with DOT but the parameters do not survive for some reason. 

Example: 
. $srcdir/diag.sh init

init is not passed to diag.sh script as first parameter. 
All diag.sh script calls fail for this reason.

**Comment by rgerhards** [comment]
Looks like we finally got to the point where we need to require bash?

**Comment by alorbach** [comment]
I guess, csh does not seem to be sufficient for the test suite.

**Comment by rgerhards** [comment]
Yeah I think here it would be more than just hassle to work without bash. So let's do it...

**Comment by brd** [comment]
Where is the source of the script?

I would recommend not using csh for scripting, but /bin/sh.

**Comment by alorbach** [comment]
We have switched to bash, the scripts can be found in the tests folder. Most of the tests do work now on FreeBSD, some do not.

**Comment by brd** [comment]
I'll take a look, thanks. Unless you need arrays, best to use /bin/sh to avoid external deps.
