### ISSUE TITLE
Two different conf files in rsyslog.d one's messages are going into the others log file

### ISSUE THREAD

**Issue by gcstang** [rsyslog/rsyslog#4634]
### Expected behavior
Entries should be separated by configuration which uses programname

### Actual behavior
Error's from:
fwdservice /var/log/osfwd/err.log 
are going into 
temonitorservice /var/log/temonitor/err.log

### Environment
- rsyslog version: 8.24.0-57.0.1.el7_9.1
- platform: Oracle Linux Server 7.7
- for configuration questions/issues, include rsyslog.conf and included config files

First Service Configuration:
StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=fwdservice

First Configuration:

if $programname == 'fwdservice' then /var/log/osfwd/all.log
if $programname == 'fwdservice' and not ($msg contains "ERROR") and not ($msg contains "FATAL") and not ($msg contains "ORA-") then /var/log/osfwd/info.log
if $programname == 'fwdservice' and $msg contains "ERROR" or $msg contains "FATAL" or $msg contains "ORA-" then /var/log/osfwd/err.log
& stop

Second Service Configuration:
StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=temonitorservice

Second Configuration:

if $programname == 'temonitorservice' then /var/log/temonitor/all.log
if $programname == 'temonitorservice' and not ($msg contains "ERROR") and not ($msg contains "FATAL") and not ($msg contains "ORA-") then /var/log/temonitor/info.log
if $programname == 'temonitorservice' and $msg contains "ERROR" or $msg contains "FATAL" or $msg contains "ORA-" then /var/log/temonitor/err.log
& stop

**Comment by davidelang** [comment]
please post the full configs.

Also, v8,24 is very old (4+ years old at this point), you are running a version 
with some backports from RedHat, but we as the community do not know what 
features/fixes they have backported, so our ability to support it is limited. If 
you can upgrade to a currently community supported version (8.210x) we can 
better support you.

David Lang

**Comment by gcstang** [comment]
> please post the full configs. Also, v8,24 is very old (4+ years old at this point), you are running a version with some backports from RedHat, but we as the community do not know what features/fixes they have backported, so our ability to support it is limited. If you can upgrade to a currently community supported version (8.210x) we can better support you. David Lang On Tue, 13 Jul 2021, Gil wrote:
> […](#)
> Date: Tue, 13 Jul 2021 06:58:31 -0700 From: Gil ***@***.***> Reply-To: rsyslog/rsyslog ***@***.***> To: rsyslog/rsyslog ***@***.***> Cc: Subscribed ***@***.***> Subject: [rsyslog/rsyslog] Two different conf files in rsyslog.d one's messages are going into the others log file (#4634) ### Expected behavior Entries should be separated by configuration which uses programname ### Actual behavior Error's from: fwdservice /var/log/osfwd/err.log are going into temonitorservice /var/log/temonitor/err.log ### Steps to reproduce the behavior ### Environment - rsyslog version: 8.24.0-57.0.1.el7_9.1 - platform: Oracle Linux Server 7.7 - for configuration questions/issues, include rsyslog.conf and included config files First Service Configuration: StandardOutput=syslog StandardError=syslog SyslogIdentifier=fwdservice First Configuration: if $programname == 'fwdservice' then /var/log/osfwd/all.log if $programname == 'fwdservice' and not ($msg contains "ERROR") and not ($msg contains "FATAL") and not ($msg contains "ORA-") then /var/log/osfwd/info.log if $programname == 'fwdservice' and $msg contains "ERROR" or $msg contains "FATAL" or $msg contains "ORA-" then /var/log/osfwd/err.log & stop Second Service Configuration: StandardOutput=syslog StandardError=syslog SyslogIdentifier=temonitorservice Second Configuration: if $programname == 'temonitorservice' then /var/log/temonitor/all.log if $programname == 'temonitorservice' and not ($msg contains "ERROR") and not ($msg contains "FATAL") and not ($msg contains "ORA-") then /var/log/temonitor/info.log if $programname == 'temonitorservice' and $msg contains "ERROR" or $msg contains "FATAL" or $msg contains "ORA-" then /var/log/temonitor/err.log & stop

Those are the full config's and unfortunately this is the latest version available for server.
I ended up doing this after much trial and error which worked:

if $programname == 'temonitorservice' then {
    action(type="omfile" file="/var/log/te-monitor/all.log")
    if not ($msg contains "ERROR") and not ($msg contains "FATAL") and not ($msg contains "ORA-") then {
        action(type="omfile" file="/var/log/te-monitor/info.log")
        stop
    } else if $msg contains "ERROR" or $msg contains "FATAL" or $msg contains "ORA-" then {
        action(type="omfile" file="/var/log/te-monitor/err.log")
        stop
    }
    stop
}

**Comment by davidelang** [comment]
On Tue, 13 Jul 2021, Gil wrote:

> Those are the full config's and unfortunately this is the latest version available for server.

we will try to answer where we can, but you may end up having to reach out to 
RedHat for support on that version.

This is the drawback to the distros doing backports of 'important' patches 
rather than updating to the latest version.

It seems that you got it working.

David Lang
