### ISSUE TITLE
thread pegging core at 100% in infinite EAGAIN loop

### ISSUE THREAD

**Issue by snblitz** [rsyslog/rsyslog#4638]
### Expected behavior

No threads in an infinite loop getting EAGAIN

### Actual behavior

infinite loop pegging a single core at 100% forever

### Steps to reproduce the behavior

Unknown.  seems to occur randomly, but occasionally seems to affect several different machines in a pool at the same time.

strace -f -p 526624 (pid_of_rsyslogd_pegged_at_100%) (different from pid below)

[pid 526653] recvfrom(77, 0x7f7f68052a73, 736, 0, NULL, NULL) = -1 EAGAIN (Resource temporarily unavailable)

[pid 526653] recvfrom(77, 0x7f7f68052a73, 736, 0, NULL, NULL) = -1 EAGAIN (Resource temporarily unavailable)

[pid 526653] recvfrom(77, 0x7f7f68052a73, 736, 0, NULL, NULL) = -1 EAGAIN (Resource temporarily unavailable)

forever.

The rsyslogd system looks to be working.  Data is still flowing.  Just one thread stuck at 100%.

Looking via ps -T -p 526624 I find

526624 526653 ?        00:00:00 in:imtcp

And imtcp is configured with

global(
    DefaultNetstreamDriver="gtls"
    DefaultNetstreamDriverCAFile="/etc/ssl/certs/sink-kafka-ext.openvpn.net.bundle.crt"
    DefaultNetstreamDriverCertFile="/etc/ssl/certs/sink-kafka-ext.openvpn.net.crt"
    DefaultNetstreamDriverKeyFile="/etc/ssl/private/sink-kafka-ext.openvpn.net.key"
)

module(
    load="imtcp"
    StreamDriver.Name="gtls"
    StreamDriver.Mode="1"
    StreamDriver.Authmode="anon"
    MaxSessions="2000"
)

input(
    type="imtcp"
    port="20516"
)

### Environment
- rsyslog version: 8.2001.0

- platform: Ubuntu 20.04.2 LTS

- for configuration questions/issues, include rsyslog.conf and included config files

**Comment by davidelang** [comment]
We have seen this problem with TLS connections, there has been a lot of work on 
this over the last year, can you try upgrading from the Jan 2020 release to a 
current one (the latest is 8.2106, June 2021)

David Lang

**Comment by snblitz** [comment]
I will give a more recent version a try.  Since the problem is intermittent it might be a while before I have anything to report back.

**Comment by davidelang** [comment]
that was my experience with the TLS bug as well.

If it still happens with the current version, you may want to switch between 
openssl and gnutls (try using whichever you aren't using now)

if the problem persists, we would need your full config and info on which thread 
is getting stuck.

David Lang

**Comment by alorbach** [comment]
@snblitz: Does the problem still exist with the current rsyslog release?

**Comment by snblitz** [comment]
@alorbach.  we just started deploying the upgraded version to production a couple of days ago.  I plan to post here if the problem recurs.

**Comment by jamespwilliams** [comment]
Like the original commenter, I encountered this problem on an older release. I updated to the newest release (8.2110.0), and it was fine for about a week, but I think I just ran into the same problem again. 100% CPU usage, no logs being written.

In my haste, I forgot to add the `-f` flag to my strace calls, so I can't confirm that the strace contains the EAGAIN lines mentioned in the issue body, but I suspect it would have - it definitely did on the older release.

My config is very similar to that described in the issue body.

I think I'll try and switch to openssl to see if that fixes this.

This might be related to https://github.com/rsyslog/rsyslog/issues/4521

**Comment by snblitz** [comment]
We upgraded our production systems to use 8.2110.0 
The problem usually took a couple of weeks to manifest.
I plan to report back in a few weeks or earlier if the issue shows up sooner.

**Comment by jamespwilliams** [comment]
This problem has occurred for us on the latest rsyslog release (8.2110.0), when using both gnutls and openssl. Config is very similar to that described in the issue body.

**Comment by snblitz** [comment]
The problem occurred today running 8.2110.0.

1 R   104     477       1     878 14  80   0 - 300675 -     ?        1-17:17:55 in:imtcp

is looping using 100% of one core

[pid   878] recvfrom(61, 0x7f398156d013, 4424, 0, NULL, NULL) = -1 EAGAIN (Resource temporarily unavailable)
[pid   878] recvfrom(61, 0x7f398156d013, 4424, 0, NULL, NULL) = -1 EAGAIN (Resource temporarily unavailable)
[pid   878] recvfrom(61, 0x7f398156d013, 4424, 0, NULL, NULL) = -1 EAGAIN (Resource temporarily unavailable)

This is the same behavior as originally reported.
Here is the configuration of rsyslog from the host experiencing the issue

[kafka-node-rsyslog-config.zip](https://github.com/rsyslog/rsyslog/files/7656510/kafka-node-rsyslog-config.zip)

**Comment by opoplawski** [comment]
I'm seeing this very frequently with rsyslog-8.2102.0-5.el8.x86_64 and gtls.  We have lots of systems connecting and disconnecting from the network.

**Comment by snblitz** [comment]
The problem continues to occur with the 8.2110.0 version.  It does seem more rare, but we still occasionally find threads burning up the a core as reported in the original post.

**Comment by jamespwilliams** [comment]
Not sure how useful this'll be, but I'll note it anyway: for us, this bug seems to occur in bursts. We can go weeks without it happening at all, and then it'll occur multiple times in a single day.

I wondered whether this was to do with load on the machine, or the volume of inbound logs, but after a quick look I've not seen any correlation.

**Comment by opoplawski** [comment]
I've updated to 8.2112.0 but still seeing issues fairly frequently.  It also seems to impact other data flows as well though and so is becoming a larger concern.

**Comment by rgerhards** [comment]
closed via https://github.com/rsyslog/rsyslog/pull/4823
