### ISSUE TITLE
Getting error: 'unexpected GnuTLS error -28 in nsd_gtls.c:2173: Resource temporarily unavailable, try again.  [v8.2106.0 try https://www.rsyslog.com/e/2078 ]'

### ISSUE THREAD

**Issue by l00d3r** [rsyslog/rsyslog#4641]
### Expected behavior
Logs successfully sent to my syslog server using gnutls (centos 7 default)

### Actual behavior
Getting an error:
'unexpected GnuTLS error -28 in nsd_gtls.c:2173: Resource temporarily unavailable, try again.  [v8.2106.0 try https://www.rsyslog.com/e/2078 ]'

I'm using syslogtcp input on graylog 4.1.1 with client auth, tried the same config with rsyslog-openssl and it works with that

### Steps to reproduce the behavior
Try sending logs to syslogtcp input 
### Environment
- rsyslog version: 8.2106.0
- platform: CentOS 7

### Debug log and config files:
- [rsyslog-gnutls.log](https://github.com/rsyslog/rsyslog/files/6863763/rsyslog-gnutls.txt)
- [graylog.conf](https://github.com/rsyslog/rsyslog/files/6863776/graylog.txt)
- [listen.conf](https://github.com/rsyslog/rsyslog/files/6863778/listen.txt)
- [rsyslog.conf](https://github.com/rsyslog/rsyslog/files/6863779/rsyslog.txt)

**Comment by davidelang** [comment]
Rsyslog 8.35 is several years old at this point (mid 2018)and no longer 
supported by the community (if it's what your distro provides and you are locked 
into them 'because support' then you need to contact them for support)

There has been a lot of development on TLS support over just the last year, so 
please upgrade to 8.2106 (June 2021) and see if the problem still happens.

we now support openssl as well as gnutls, so if gnutls gives you errors with the 
new version, try openssl (replace gtls with ossl in the config)

if you still have a problem, please provide the full config and info on what's 
connecting to it.

David Lang


  On Thu, 22 Jul 
2021, l00d3r wrote:

> Date: Thu, 22 Jul 2021 16:17:08 +0000 (UTC)
> From: l00d3r ***@***.***>
> Reply-To: rsyslog/rsyslog
>     ***@***.***>
> To: rsyslog/rsyslog ***@***.***>
> Cc: Subscribed ***@***.***>
> Subject: [rsyslog/rsyslog] Getting error: 'unexpected GnuTLS error -28 in
>     nsd_gtls.c:2173: Resource temporarily unavailable,
>     try again.  [v8.2106.0 try https://www.rsyslog.com/e/2078 ]' (#4641)
> 
> ### Expected behavior
>
> ### Actual behavior
>
> ### Steps to reproduce the behavior
>
> ### Environment
> - rsyslog version: 
> - platform: 
> - for configuration questions/issues, include rsyslog.conf and included config files
>
> 
>
>
>

**Comment by l00d3r** [comment]
Hi,

I did provide more info and in github issue and updated to the latest
version, I just accidentaly submitted it empty initially,

**Comment by rgerhards** [comment]
as a quick work-around I would suggest to switch to the oss (openssl) driver.

**Comment by l00d3r** [comment]
Yes, already doing it, created this issue because I believe there is something about gnutls that should be looked at.

I think it may be that the server responds to TLS client hello with an encrypted handshake message which I believe contains a request for the client certificate and gnutls fails on it for some reason. 
Since rsyslog-gnutls works on CentOS 8 it may be that CentOS 7 does not support TLSv1.3?

I have even tried it with a priority string supporting just one TLSv1.2 cipher but it still fails on CentOS 7.
`gnutlsprioritystring="NONE:+VERS-TLS1.2:+ECDHE-RSA:+AES-128-GCM:+SIGN-RSA-SHA256:+AEAD:+COMP-NULL:+CURVE-SECP256R1"`

This same string worked on previous version of graylog but they updated some TLS security settings and looking at a tcpdump I took I think the issue comes from graylog now using Encrypted Handshake Messages

**Comment by l00d3r** [comment]
I got it fixed from graylogs side, it could not access the client certificate CA file and when I fixed that it started working correctly,  thanks for your time and responses.

I don't understand the specifics but it kind of looked like graylog sent its default cacerts certificates when asking for client certificate and looks like maybe gnutls did not know how to handle that many or some certificates in it which is odd since gnutls-cli did not have an issue with that and neither did rsyslog-openssl.

I did some trial and error testing and looks like gnutls fails when Certificate request part length from server side hello exceeds something like 14226 bytes (137 certificate authority DNs)

**Comment by alorbach** [comment]
It is possible that this is a bug in gnutls because the version comes with centos7 is rather old compared to centos8.
Can we close this issue @l00d3r  ?

**Comment by l00d3r** [comment]
Yeah, fine by me, found the cause and maybe this github issue helps solve
it for someone else getting this error.
