### ISSUE TITLE
Logs does not come with new updated hostname 

### ISSUE THREAD

**Issue by fuqianz** [rsyslog/rsyslog#4644]
### Expected behavior
Logs come with new updated hostname
### Actual behavior
Logs does not come with new updated hostname
### Steps to reproduce the behavior
Update nodes hostname without restart rsyslog
### Environment
- rsyslog version: rsyslogd 8.24.0-57.el7_9.1, compiled with:
- platform: Centos 7
- for configuration questions/issues, include rsyslog.conf and included config files

Is restarting rsyslog needed after changing node hostname?

**Comment by davidelang** [comment]
yes, rsyslog only checks the hostname at startup.

David Lang

**Comment by fuqianz** [comment]
ok, so will this be addressed in future release?

**Comment by davidelang** [comment]
the most I could see as being reasonable would be checking on a HUP, it would be 
far too expensive to check for every message

hostname changes are just not a common thing. If someone were to submit a PR 
that checked at HUP time, I would expect that it would be accepted, but checking 
for every message would not be. The TODO list is so long with higher priority 
requests that would affect far more common cases, that I would not expect it to 
happen otherwise.

David Lang

**Comment by fuqianz** [comment]
Is it possible to do on demand reloading configurations?

**Comment by davidelang** [comment]
No, a HUP closes and reopens connections, but a full config reload on-the-fly is 
not possible, that requires a complete restart.

David Lang

**Comment by fuqianz** [comment]
Ok. understand.

Another question: Is there a way to override logs' hostname received in localhost? Locally, I have port 514 opened and with udp enabled. I am trying to transfer these messages to syslog server, However, it seems the hostname can not be override even with LocalHostname given. Any suggestions?

**Comment by davidelang** [comment]
On Thu, 29 Jul 2021, Fu wrote:

> Another question: Is there a way to override logs' hostname received in 
> localhost? Locally, I have port 514 opened and with udp enabled. I am trying 
> to transfer these messages to syslog server, However, it seems the hostname 
> can not be override even with LocalHostname given. Any suggestions?

I'd need to understand better what you are trying to do, but you can create a 
template that will put any value you want in the hostname field, so it is 
possible.

David Lang

**Comment by fuqianz** [comment]
Thanks for the reply. I did use a template and solved problems.
