### ISSUE TITLE
imfile does not get the first log after rotation

### ISSUE THREAD

**Issue by elminus** [rsyslog/rsyslog#4648]
imfile does not get the first log after the files are rotated. The problem occurs in inotify mode, but not in polling mode.

### Expected behavior
All logs are collected after the files are rotated.

### Actual behavior
The first log after rotation is not collected.

### Steps to reproduce the behavior

1. configure rsyslog.conf (described later) to collect 2 files with imfile module.
2. write some messages to the files

```
# cd /var/log/testlog
# echo message1 | tee -a test1.log test2.log
# cat ../test_syslog.log
Jul 29 17:05:04 localhost test1 message1
Jul 29 17:05:04 localhost test2 message1
```

It is ok. 2 messages are collected

3. rotate the files

```
# logrotate /etc/logrotate.d/testlog
# ls
test1.log  test1.log-20210729.gz  test2.log  test2.log-20210729.gz
```

4. write messages

```
# echo message2 | tee -a test1.log test2.log
# cat ../test_syslog.log
Jul 29 17:05:04 localhost test1 message1
Jul 29 17:05:04 localhost test2 message1
Jul 29 17:05:19 localhost test1 message2
```

Something is wrong here. "test2 message2" log is not collected.

5. write messages

```
# echo message3 | tee -a test1.log test2.log
# cat ../test_syslog.log
Jul 29 17:05:04 localhost test1 message1
Jul 29 17:05:04 localhost test2 message1
Jul 29 17:05:19 localhost test1 message2
Jul 29 17:05:31 localhost test1 message3
Jul 29 17:05:31 localhost test2 message3
```

It is ok. 2 messages of "message3" are collected.

### Environment
- rsyslog version: 

```
# rsyslogd -v
rsyslogd  8.1911.0-7.el8_4.2 (aka 2019.11) compiled with:
        PLATFORM:                               x86_64-redhat-linux-gnu
        PLATFORM (lsb_release -d):
        FEATURE_REGEXP:                         Yes
        GSSAPI Kerberos 5 support:              Yes
        FEATURE_DEBUG (debug build, slow code): No
        32bit Atomic operations supported:      Yes
        64bit Atomic operations supported:      Yes
        memory allocator:                       system default
        Runtime Instrumentation (slow code):    No
        uuid support:                           Yes
        systemd support:                        Yes
        Config file:                            /etc/rsyslog.conf
        PID file:                               /var/run/rsyslogd.pid
        Number of Bits in RainerScript integers: 64

See https://www.rsyslog.com for more information.
```

- platform: CentOS 8
- rsyslog.conf:

```
global(workDirectory="/var/lib/rsyslog")
module(load="builtin:omfile" Template="RSYSLOG_TraditionalFileFormat")
module(load="imfile")

input(type="imfile" file="/var/log/testlog/test1.log" tag="test1" facility="local3" severity="notice" ruleset="test")
input(type="imfile" file="/var/log/testlog/test2.log" tag="test2" facility="local3" severity="notice" ruleset="test")

ruleset(name="test") {
  action(type="omfile" file="/var/log/test_syslog.log")
}
```

**Comment by davidelang** [comment]
how are the files being rotated? are they being deleted and a new file created? 
or are the files being truncated and populated again?

David Lang

**Comment by elminus** [comment]
I use this /etc/logrotate.d/testlog file.

```
/var/log/testlog/*.log {
  weekly
  rotate 4
  create
  dateext
  compress
}
```

As I do not use `copytruncate`, the files are deleted and new files are created.

**Comment by davidelang** [comment]
On Thu, 29 Jul 2021, elminus wrote:

> I use this /etc/logrotate.d/testlog file.
>
> ```
> /var/log/testlog/*.log {
>  weekly
>  rotate 4
>  create
>  dateext
>  compress
> }
> ```
>
> As I do not use `copytruncate`, the files are deleted and new files are created.

ok, that should be working. since 8.1911 is nov 2019 release, can you update to 
a current release and see if the problem is still there? I know there has been 
significant work on imfile in the last couple of years.

David Lang

**Comment by davidelang** [comment]
On Thu, 29 Jul 2021, elminus wrote:

> imfile does not get the first log after the files are rotated. The problem occurs in inotify mode, but not in polling mode.
>
> ### Expected behavior
> All logs are collected after the files are rotated.
>
> ### Actual behavior
> The first log after rotation is not collected.
>
> ### Steps to reproduce the behavior
>
> 1. configure rsyslog.conf (described later) to collect 2 files with imfile module.
> 2. write some messages to the files
>
> ```
> # cd /var/log/testlog
> # echo message1 | tee -a test1.log test2.log
> # cat ../test_syslog.log
> Jul 29 17:05:04 localhost test1 message1
> Jul 29 17:05:04 localhost test2 message1
> ```
>
> It is ok. 2 messages are collected
>
> 3. rotate the files
>
> ```
> # logrotate /etc/logrotate.d/testlog
> # ls
> test1.log  test1.log-20210729.gz  test2.log  test2.log-20210729.gz
> ```
>
> 4. write messages
>
> ```
> # echo message2 | tee -a test1.log test2.log
> # cat ../test_syslog.log
> Jul 29 17:05:04 localhost test1 message1
> Jul 29 17:05:04 localhost test2 message1
> Jul 29 17:05:19 localhost test1 message2
> ```

if you rotated the files, why are the message1 entries still there? they should 
have been in the rotated file, not the main file.

looks like something is not working as expected in the rotation.

David Lang

> Something is wrong here. "test2 message2" log is not collected.
>
> 5. write messages
>
> ```
> # echo message3 | tee -a test1.log test2.log
> # cat ../test_syslog.log
> Jul 29 17:05:04 localhost test1 message1
> Jul 29 17:05:04 localhost test2 message1
> Jul 29 17:05:19 localhost test1 message2
> Jul 29 17:05:31 localhost test1 message3
> Jul 29 17:05:31 localhost test2 message3
> ```
>
> It is ok. 2 messages of "message3" are collected.
>
> ### Environment
> - rsyslog version:
>
> ```
> # rsyslogd -v
> rsyslogd  8.1911.0-7.el8_4.2 (aka 2019.11) compiled with:
>        PLATFORM:                               x86_64-redhat-linux-gnu
>        PLATFORM (lsb_release -d):
>        FEATURE_REGEXP:                         Yes
>        GSSAPI Kerberos 5 support:              Yes
>        FEATURE_DEBUG (debug build, slow code): No
>        32bit Atomic operations supported:      Yes
>        64bit Atomic operations supported:      Yes
>        memory allocator:                       system default
>        Runtime Instrumentation (slow code):    No
>        uuid support:                           Yes
>        systemd support:                        Yes
>        Config file:                            /etc/rsyslog.conf
>        PID file:                               /var/run/rsyslogd.pid
>        Number of Bits in RainerScript integers: 64
>
> See https://www.rsyslog.com for more information.
> ```
>
> - platform: CentOS 8
> - rsyslog.conf:
>
> ```
> global(workDirectory="/var/lib/rsyslog")
> module(load="builtin:omfile" Template="RSYSLOG_TraditionalFileFormat")
> module(load="imfile")
>
> input(type="imfile" file="/var/log/testlog/test1.log" tag="test1" facility="local3" severity="notice" ruleset="test")
> input(type="imfile" file="/var/log/testlog/test2.log" tag="test2" facility="local3" severity="notice" ruleset="test")
>
> ruleset(name="test") {
>  action(type="omfile" file="/var/log/test_syslog.log")
> }
> ```
>
> 
>
>
>

**Comment by elminus** [comment]
Ok, I will try a newer release.


> if you rotated the files, why are the message1 entries still there? they should
> have been in the rotated file, not the main file.
> 
> looks like something is not working as expected in the rotation.

In rsyslog.conf, I configure 2 imfile input from /var/log/testlog/test1.log and /var/log/testlog/test2.log and output to /var/log/test_syslog.log.
In /etc/logrotate.d/testlog, I configure to rotate /var/log/testlog/*.
So it is as expected that /var/log/test_syslog.log is not rotated here.

**Comment by elminus** [comment]
I tried the daily stable build. But unfortunately the problem still occurs.

```
# rpm -q rsyslog
rsyslog-8.2108.0.master-1627599722.x86_64
# rsyslogd -v
rsyslogd  8.2108.0.master (aka 2021.08) compiled with:
        PLATFORM:                               x86_64-redhat-linux-gnu
        PLATFORM (lsb_release -d):
        FEATURE_REGEXP:                         Yes
        GSSAPI Kerberos 5 support:              Yes
        FEATURE_DEBUG (debug build, slow code): No
        32bit Atomic operations supported:      Yes
        64bit Atomic operations supported:      Yes
        memory allocator:                       system default
        Runtime Instrumentation (slow code):    No
        uuid support:                           Yes
        systemd support:                        Yes
        Config file:                            /etc/rsyslog.conf
        PID file:                               /var/run/syslogd.pid
        Number of Bits in RainerScript integers: 64

See https://www.rsyslog.com for more information.
```

By the way, I found that the inode of the file is reused.
Is this related to the problem?

Before rotation, the inode of test1.log is 1369604.
```
# ls -li
total 8
1369604 -rw-r--r--. 1 root root 9 Jul 30 15:11 test1.log
1369605 -rw-r--r--. 1 root root 9 Jul 30 15:11 test2.log
```

After rotation, the inode of test2.log is 1369604, which was the inode of test1.log before rotation.
```
# ls -li
total 8
1369607 -rw-r--r--. 1 root root  0 Jul 30 15:11 test1.log
1369608 -rw-r--r--. 1 root root 29 Jul 30 15:11 test1.log-20210730.gz
1369604 -rw-r--r--. 1 root root  0 Jul 30 15:11 test2.log
1369609 -rw-r--r--. 1 root root 29 Jul 30 15:11 test2.log-20210730.gz
```

**Comment by elminus** [comment]
I tried chaging the logrotate configuration to set nocompress. The problem seems to be resolved.

```
/var/log/testlog/*.log {
  weekly
  rotate 4
  create
  dateext
  #compress
  nocompress
}
```

Without compression, inode is not reused and log collection by imfile seems to be working fine.

Before rotation:
```
# ls -li
total 8
1369604 -rw-r--r--. 1 root root 9 Jul 30 15:34 test1.log
1369605 -rw-r--r--. 1 root root 9 Jul 30 15:34 test2.log
```

After rotation:
```
# ls -li
total 8
1369607 -rw-r--r--. 1 root root 0 Jul 30 15:34 test1.log
1369604 -rw-r--r--. 1 root root 9 Jul 30 15:34 test1.log-20210730
1369608 -rw-r--r--. 1 root root 0 Jul 30 15:34 test2.log
1369605 -rw-r--r--. 1 root root 9 Jul 30 15:34 test2.log-20210730
```

Should I stop setting `compress` on the files monitored by imfile?

**Comment by davidelang** [comment]
if the file is the same inode, then it's truncating the file, not creating a new 
one, try explicitly forcing it to not truncate and see if that solves the 
problem, even with compression.

you may be inheriting truncation from elsewhere in the logrotate 
configs/defaults

David Lang

**Comment by elminus** [comment]
I am afraid my explanation was not good. What I meant to say was
the inode of each file do not match before and after rotation but
the inode of one file after rotation matches the inode of the other
file before rotation.

With compression:
inode of test1.log: 1369604 -> 1369607
inode of test2.log: 1369605 -> 1369604

The inode of test2.log after rotation is the same of test1.log before rotation.
At this time, the first log of test2.log after rotation was not collected.

Without compression:
inode of test1.log: 1369604 -> 1369607
inode of test2.log: 1369605 -> 1369608

The inode of test2.log after rotation is not the same of test1.log before rotation.

**Comment by rgerhards** [comment]
With the current version, we do a check on

1. the inode
2. the "file id"

where "file id" is the first (IIRC) 512 bytes of the file as hash (or, if less than 512 bytes, I think we store the actual content).

So in theory it is very unlikely that a file with the same inode is detected as equal. HOWEVER, if rsyslog catches it as size 0, we have no file id, and so we need to resort to the inode only. This is pretty seldom, but can happen. Nevertheless, you say the inode is used for a different file name, so I do not see that it would be affected by this race.

Boils down to being "interesting". If you could create a debug log with a run where something is going wrong, I could probably see what actually happens. To do so, see Instructions: https://www.rsyslog.com/doc/v8-stable/troubleshooting/howtodebug.html

Be sure that the problem in question occurs at least once during the debug run. Once this is done, please post the debug log (e.g. via pastbin or github). After that, we can review the contents and check how exactly rsyslog processing worked.

**Comment by elminus** [comment]
I created a debug log https://gist.github.com/elminus/cee1a10d1abdf6a3ef7511d22d58f146
Could you please check how rsyslog working?

I appended these 2 lines to /etc/rsyslog.conf.
```
$DebugFile /var/log/rsyslog.debug
$DebugLevel 2
```

Reproduction steps are the same as described in issue description (see "Steps to reproduce the behavior")
but rsyslog package is now updated to rsyslog-8.2108.0.master-1627599722.x86_64.

**Comment by rgerhards** [comment]
To ease going through the debug file a bit: could you let me know which file was missing a message after the rotation (and what was the last message before)? So I could search for them inside the debug log ;-)

**Comment by rgerhards** [comment]
mhhh... I looks a bit like there is a race with HUP or HUP is too late. Unfortunately, the current version does not have a clear indication inside the debug log of when HUP happened. I have now added that, but of course it doesn't immediately help.

I am not 100% sure if I looked at the right place, but it looks like the truncation/inode switch happened before the HUP. But not seeing really clear indication. If you can provide some more details re file names, that would possibly be useful.

**Comment by elminus** [comment]
Sorry for late response. I did the following steps.

1. stop rsyslog service
2. modify rsyslog.conf to append debug parameters
```
$DebugFile /var/log/rsyslog.debug
$DebugLevel 2
```

3. remove old input and output files and create new files
```
# rm -f /var/log/testlog/test1.log /var/log/testlog/test2.log /var/log/test_syslog.log
# touch /var/log/testlog/test1.log /var/log/testlog/test2.log
```

4. remove old state files
```
# rm -f /var/lib/rsyslog/imfile-state*
```

5. start rsyslog service
6. write a message to the files and check output
```
# cd /var/log/testlog
# echo message1 | tee -a test1.log test2.log
# cat /var/log/test_syslog.log
```

Both "test1 message1" and "test2 message2" were shown here.

7. rotate the files
At this time, the inode of the files were changed like:
  test1.log: 1369604 -> 1369607
  test2.log: 1369605 -> 1369604

8. write a message
```
# echo message2 | tee -a test1.log test2.log
# cat /var/log/test_syslog.log
```

Only "test1 message2" was shown. "test2 message2" was missed.

9. write a message
```
# echo message3 | tee -a test1.log test2.log
# cat /var/log/test_syslog.log
```

Both "test1 message3" and "test2 message3" were shown.

10. stop rsyslog service


If I understand correctly, rsyslogd did not catch HUP signal because I stop and start rsyslog service to load a new configuration instead of sending SIGHUP.

**Comment by jruere** [comment]
Does `imfile` require `SIGHUP` when rotating the file being read?

AFAICS, the output file is not rotated.

**Comment by rgerhards** [comment]
> Does `imfile` require `SIGHUP` when rotating the file being read?

No, but please do not post a new question to an old thread.
