### ISSUE TITLE
rsyslog send log to log server over omfwd module, TLS

### ISSUE THREAD

**Issue by yqguodataman** [rsyslog/rsyslog#466]
rsyslog send log to log server throuth tls
Here is my configuration
module(load="imfile")
$DefaultNetstreamDriverCAFile /path/to/cafile # trust these CAs
ruleset(name="remote") {
    action(type="omfwd"
        Protocol="tcp"
        Target="dm-may09"
        Port="5001"
        ZipLevel="0"
        StreamDriver = "gtls"
        StreamDriverMode = "1"
        StreamDriverAuthMode = "x509/name"
        StreamDriverPermittedPeers = "dm-may09"
    )
    stop
}
input(type="imfile"
    File=“/path/to/logfile"
    Facility="user"
    Severity="info"
    PersistStateInterval="1000"
    Ruleset="remote"
)

error log:
GnuTLS error: Error in the push function.

environment：

ubuntu 14.04
rsyslog 7.4.4
gnutls 2.12.23

I checked some information some people say this is a BUG

**Comment by alorbach** [comment]
Hrm isn't there any error code like -53 or -54 with the GnuTLS error line? 
This would help for further analysis.

**Comment by yqguodataman** [comment]
error code is -53

**Comment by alorbach** [comment]
Can you add global(debug.gnutls="on") to rsyslog.conf and then run rsyslog again? Perhaps we see some more details then.

**Comment by rgerhards** [comment]
closed due to no response (probably solved by now), also looks like a support issue. Re-open if new information is available.
