### ISSUE TITLE
imuxsock: rate limiting is broken and does not work by default

### ISSUE THREAD

**Issue by gajdusek** [rsyslog/rsyslog#4667]
### Expected behavior

Imuxscock should rate limit messages with severity 1 and lower by default (`useSpecialParser="true"` and `ratelimit.severity="1"`)

### Actual behavior

Messages are not ratelimited.

### Steps to reproduce the behavior

https://github.com/rsyslog/rsyslog/blob/84b45b757bb492609cb2babf842cbc25960390ea/tests/imuxsock_logger_ratelimit.sh

This test suite requires `./configure --enable-liblogging-stdlog`

See my pull request https://github.com/rsyslog/rsyslog/pull/4666

### Cause

When `useSpecialParser` is set to "true" (the default setting) all messages are erroneously treated as having severity 0 and therefore are not subjects to the rate limiting which by default ignores messages with severity 0.

**Comment by rgerhards** [comment]
Note: this is not an imuxsock issue, but rather a broader issue inside the ratelimiting code. It can potentially happen with all inputs.

**Comment by rgerhards** [comment]
closed via #4666
