### ISSUE TITLE
mmkubernetes does never retry connections to kubernetes API

### ISSUE THREAD

**Issue by jayme-github** [rsyslog/rsyslog#4669]
### Expected behavior
mmkubernetes should be suspended rather than error out after failing (possibly temporarily) to connect the kubernetes API so that retries can be configured via general action parameters.

### Actual behavior
Connectivity issues leading to the mmkubernetes module to be disabled. The documentation states it will be suspended, but that does not seem to be the case as it calls `ABORT_FINALIZE(RS_RET_ERR);` instead of `ABORT_FINALIZE(RS_RET_SUSPEND);`:

https://github.com/rsyslog/rsyslog/blob/ca706195b53148b05114e54d8cd2a8080a28629c/contrib/mmkubernetes/mmkubernetes.c#L1741-L1745

```
rsyslogd[19991]: mmkubernetes: failed to connect to [https://kubemaster.local/api/v1/namespaces/kube-system/pods/debug-deployment-8699d89bf-hrh66] - 7:Couldn't connect to server  [v8.1901.0]
rsyslogd[19991]: action 'mmkubernetes' (module 'mmkubernetes') message lost, could not be processed. Check for additional error messages before this one. [v8.1901.0]
```

### Steps to reproduce the behavior
* Block the connection to the kubernetes API server
* Wait for mmkubernetes to fail
* Unblock the connection to the kubernetes API server

### Environment
- rsyslog version: v8.1901.0 (code looks the same in master)
- platform: Debian Stretch

I'm happy to provide a patch, but wanted to discuss this because I'm not familiar with the internals of rsyslog and it's modules. A patched version of the module works okay/reconnects with a config like:
```
action(type="mmkubernetes"
       name="mmkubernetes"
       action.resumeRetryCount="-1"
       action.resumeIntervalMax="300"
       action.reportSuspensionContinuation="on")
```

**Comment by rgerhards** [comment]
@richm I would appreciate if you could have a look :-)

**Comment by rgerhards** [comment]
@jayme-github It may work best if you propose a pull request. Note that this is a contributed module, so the core team does not have sufficient know-how to evaluate kubernetes-specific details.

**Comment by richm** [comment]
looks good to me
