### ISSUE TITLE
[Bug] rsyslog cannot open kernel log (/proc/kmsg)

### ISSUE THREAD

**Issue by dchammond** [rsyslog/rsyslog#467]
When I start up rsyslogd as root, I notice that it doesn't log kernel messages.   I forced rsyslogd to show its debug output and the relevant lines from that were as follows (found via grep "kmsg"):
```
0707.774366527:main Q:Reg/w0  : processBATCH: next msg 0: imklog: cannot open kernel log (/proc/kmsg): Operation not permitted.
0707.808408314:main Q:Reg/w0  : omfile: write to stream, pData->pStrm 0x7fffe80027a0, lenBuf 109, strt data Aug  5 16:05:06 bb80d9a0c4cf rsyslogd: imklog: cannot open kernel log (/proc/kmsg): Operation not permitted.
0707.809529147:main Q:Reg/w0  : omfile: write to stream, pData->pStrm 0x7fffe80062d0, lenBuf 109, strt data Aug  5 16:05:06 bb80d9a0c4cf rsyslogd: imklog: cannot open kernel log (/proc/kmsg): Operation not permitted.
0707.810619900:main Q:Reg/w0  : omfile: write to stream, pData->pStrm 0x7fffe8004dc0, lenBuf 109, strt data Aug  5 16:05:06 bb80d9a0c4cf rsyslogd: imklog: cannot open kernel log (/proc/kmsg): Operation not permitted.
```
I am running as root.  I even did a `chmod a=rw /proc/kmsg` and that did not help.
The system is a docker container created from ubuntu:trusty (~v14.04).

I looked at the source code for rsyslog and i believe the offending code my reside here:
https://github.com/rsyslog/rsyslog/blob/1203a26cd1975efc84e588a92db2e5e83f152092/plugins/imklog/bsd.c#L163
With possibly any of the 6 functions to do with klog after that line. (I may be off target here, it is just a suggestion)

If someone has encountered this issue, can you post how you resolved it?

**Comment by alorbach** [comment]
I am not very familier with docker, but as far as I know it runs in a sandbox and the host kernel shared.
And my guess is that you won't have access to the host kernel log from inside the docker container.

**Comment by dchammond** [comment]
You may be right, as my host machine does not have a /proc/kmsg (OSX 10.10.4).  I ended up simply not loading the imklog module in my rsyslog.conf
If anyone else has more information, they can mention it here, but I am closing the issue for now.

**Comment by steowens** [comment]
I get the same issue running rsyslog in BASH on Windows 10.  Evidently non linux systems do not permit even root to write to /proc.
