### ISSUE TITLE
$wday used in template for dynafile inserts an extraneous \0 and truncates rest of filename

### ISSUE THREAD

**Issue by athivillon** [rsyslog/rsyslog#4670]
### Expected behavior

```
template(name="json_filename" type="string" string="/var/log/remote/%$wday%.log.gz")

ruleset(name="jsonlocal" queue.type="FixedArray" queue.size="4000" queue.filename="file_disk_queue"){
   action(type="omfile" zipLevel="5" dynaFile="json_filename" template="allauthjson")
}
```

should generate "/var/log/remote/0.log.gz" file

### Actual behavior

and instead genearate  "/var/log/remote/0" gzipped file.

### Steps to reproduce the behavior

Create a template with $wday in string, then apply it to a dynaFile in omfile action

### Environment

rsyslogd  8.2001.0 (aka 2020.01) compiled with:
	PLATFORM:				x86_64-pc-linux-gnu
	PLATFORM (lsb_release -d):		
	FEATURE_REGEXP:				Yes
	GSSAPI Kerberos 5 support:		Yes
	FEATURE_DEBUG (debug build, slow code):	No
	32bit Atomic operations supported:	Yes
	64bit Atomic operations supported:	Yes
	memory allocator:			system default
	Runtime Instrumentation (slow code):	No
	uuid support:				Yes
	systemd support:			Yes
	Config file:				/etc/rsyslog.conf
	PID file:				/run/rsyslogd.pid
	Number of Bits in RainerScript integers: 64

- rsyslog version: 8.2001.0 
- platform:  Ubuntu 20.04LTS

#### Bug is in runtime/msg.c

``` C
                case PROP_SYS_WDAY:
                        if((pRes = getNOW(NOW_WDAY, ttNow, TIME_IN_LOCALTIME)) == NULL) {
                                RET_OUT_OF_MEMORY;
                        } else {
                                *pbMustBeFreed = 1;
                                bufLen = 2;
                        }
                        break;
                case PROP_SYS_WDAY_UTC:
                        if((pRes = getNOW(NOW_WDAY, ttNow, TIME_IN_UTC)) == NULL) {
                                RET_OUT_OF_MEMORY;
                        } else {
                                *pbMustBeFreed = 1;
                                bufLen = 2;
                        }
                        break;
```

bufLen should be 1 instead of 2 (getNOW is used in same code block to extract the month or year on 2 and 4 digits and bufLen contains the real len. wday is always 1 byte.   The \\0 generated by getNow is copied in buffer and rest of string is ignored when used later when opening the file.

**Comment by rgerhards** [comment]
Thx for the great issue description. I guess you are right and will check and fix soon.
