### ISSUE TITLE
ruleset config question [Rsyslog ignores actions within ruleset section -- sounds invalid]

### ISSUE THREAD

**Issue by VeeEnDee** [rsyslog/rsyslog#4682]
------- Expected behavior -------

action inside ruleset section is applied to log string with key word:
###examlpe of configuration file Error_handle.conf
ruleset(name=Error_handle) {
    :msg, contains, "Error" /var/log/error_log_file
}
###
so that all messages with Error key word are redirected to file /var/log/error_log_file

------- Actual behavior -------

no action applied to log messages, that contain "Error" key word, so the messages are not redirected into /var/log/error_log_file

------- Steps to reproduce the behavior -------

copy config from examlpe above into /etc/rsyslog.d/ directory and run:
logger -t  test -p local0.err Error
or just 
logger Error

------- Environment -------

- rsyslog version: rsyslogd 8.24.0-57.el7_9.1
- platform: CentOS Linux 7 (Core)
- rsyslog configuration files in attachment
Note: that main config file /etc/rsyslog.conf is default and was not changed 
Note 2: 
if we set up config like this: 
#examlpe of configuration file:
 :msg, contains, "Error" /var/log/error_log_file
 # 
 everything is working fine

------- Additional example -------

The same behavior can be seen in case of config (other configs are in attachment):
ruleset(name=prog_handle) {
    local0.* /var/log/program_error_log_file.log
}
Here expected behavior is to write all messages from local0 programm in sepate log file /var/log/program_error_log_file.log . 
The  actual be havior is this ruleset is ignored and no messages appear within /var/log/program_error_log_file.log file
But when we set up config file for rsyslog like this (without # signs ):
#
local0.* /var/log/program_error_log_file.log 
# 
everything is working fine. 

Here is rsyslog debug file:
[rsyslog_debug.log](https://github.com/rsyslog/rsyslog/files/7144954/rsyslog_debug.log)

-------
[Error_handle.txt](https://github.com/rsyslog/rsyslog/files/7144722/Error_handle.txt)
[programm_log_conf.txt](https://github.com/rsyslog/rsyslog/files/7144730/programm_log_conf.txt)
[rsyslog.conf.txt](https://github.com/rsyslog/rsyslog/files/7144712/rsyslog.conf.txt)
[cloudinit.txt](https://github.com/rsyslog/rsyslog/files/7144714/cloudinit.txt)
[listen.txt](https://github.com/rsyslog/rsyslog/files/7144717/listen.txt)
[output-files-modules.txt](https://github.com/rsyslog/rsyslog/files/7144719/output-files-modules.txt)

**Comment by davidelang** [comment]
please include the full config (so we can see how the ruleset is called) and an 
example of the log message that you think should be matched by this.

David Lang

**Comment by VeeEnDee** [comment]
Hey @davidelang, 
All configuration files are attached into message. 
Duplicating configs here:
# rsyslog configuration file

# For more information see /usr/share/doc/rsyslog-*/rsyslog_conf.html
# If you experience problems, see http://www.rsyslog.com/doc/troubleshoot.html

#### MODULES ####

# The imjournal module bellow is now used as a message source instead of imuxsock.
$ModLoad imuxsock # provides support for local system logging (e.g. via logger command)
$ModLoad imjournal # provides access to the systemd journal
#$ModLoad imklog # reads kernel messages (the same are read from journald)
#$ModLoad immark  # provides --MARK-- message capability

# Provides UDP syslog reception
#$ModLoad imudp
#$UDPServerRun 514

# Provides TCP syslog reception
#$ModLoad imtcp
#$InputTCPServerRun 514


#### GLOBAL DIRECTIVES ####

# Where to place auxiliary files
$WorkDirectory /var/lib/rsyslog

# Use default timestamp format
#$ActionFileDefaultTemplate RSYSLOG_TraditionalFileFormat

# File syncing capability is disabled by default. This feature is usually not required,
# not useful and an extreme performance hit
#$ActionFileEnableSync on

# Include all config files in /etc/rsyslog.d/
$IncludeConfig /etc/rsyslog.d/*.conf

# Turn off message reception via local log socket;
# local messages are retrieved through imjournal now.
$OmitLocalLogging on

# File to store the position in the journal
$IMJournalStateFile imjournal.state


#### RULES ####

# Log all kernel messages to the console.
# Logging much else clutters up the screen.
#kern.*                                                 /dev/console

# Log anything (except mail) of level info or higher.
# Don't log private authentication messages!
*.info;mail.none;authpriv.none;cron.none;local7.none       /var/log/messages

# The authpriv file has restricted access.
authpriv.*                                              /var/log/secure

# Log all the mail messages in one place.
mail.*                                                  -/var/log/maillog


# Log cron stuff
cron.*                                                  /var/log/cron

# Everybody gets emergency messages
*.emerg                                                 :omusrmsg:*

# Save news errors of level crit and higher in a special file.
uucp,news.crit                                          /var/log/spooler

# Save boot messages also to boot.log
local7.*                                                /var/log/boot.log


# ### begin forwarding rule ###
# The statement between the begin ... end define a SINGLE forwarding
# rule. They belong together, do NOT split them. If you create multiple
# forwarding rules, duplicate the whole block!
# Remote Logging (we use TCP for reliable delivery)
#
# An on-disk queue is created for this action. If the remote host is
# down, messages are spooled to disk and sent when it is up again.
#$ActionQueueFileName fwdRule1 # unique name prefix for spool files
#$ActionQueueMaxDiskSpace 1g   # 1gb space limit (use as much as possible)
#$ActionQueueSaveOnShutdown on # save messages to disk on shutdown
#$ActionQueueType LinkedList   # run asynchronously
#$ActionResumeRetryCount -1    # infinite retries if host is down
# remote host is: name/ip:port, e.g. 192.168.0.1:514, port optional
#*.* @@remote-host:514
# ### end of the forwarding rule ###

**Comment by VeeEnDee** [comment]
hey @davidelang 
all configs are attached.
duplicating them here:
# rsyslog configuration file
#### MODULES ####
$ModLoad imuxsock # provides support for local system logging (e.g. via logger command)
$ModLoad imjournal # provides access to the systemd journal

#### GLOBAL DIRECTIVES ####
$WorkDirectory /var/lib/rsyslog
$IncludeConfig /etc/rsyslog.d/*.conf
$OmitLocalLogging on
$IMJournalStateFile imjournal.state

#### RULES ####
*.info;mail.none;authpriv.none;cron.none;local7.none       /var/log/messages
authpriv.*                                              /var/log/secure
mail.*                                                  -/var/log/maillog
cron.*                                                  /var/log/cron
*.emerg                                                 :omusrmsg:*
uucp,news.crit                                          /var/log/spooler
local7.*                                                /var/log/boot.log

**Comment by VeeEnDee** [comment]
#ruleset configuration file in /etc/rsyslog.d/

ruleset(name=Error_handle) {
    :msg, contains, "Error" /var/log/error_log_file
}

**Comment by VeeEnDee** [comment]
Examlpe of message : 
Sep 10 08:46:44 HOST_NAME PROGRAMM[9604]: Error: "(History-Info)"

**Comment by davidelang** [comment]
I do not see anyplace in your config that you call this ruleset. If you don't 
call a ruleset, things in it are never looked at.

**Comment by VeeEnDee** [comment]
@davidelang Thank you for your help, 
indeed, after I have added "call" statement rulesets begane working.
While configuring rulesets I have consulted this documentation page:
https://www.rsyslog.com/doc/master/concepts/multi_ruleset.html
To be honest it is not obvious for me that I should call rulesets from configuration files, maybe you could add this to the docs?
Again, thank you, have a nice day.

**Comment by davidelang** [comment]
the default ruleset gets executed by default

any other rulesets are ignored unless something in the config tells it to use 
them. This can be a call from inside another ruleset, or an input can be 
configured to use a ruleset other than the default (most inputs anyway)

As far as the documentation goes, Rsyslog suffers from too much of the 
documentation being written by people too close to it (things seem obvious and 
don't make it into the docs). As a result, when someone is confused by the docs, 
especially when they aren't experts, they can frequently do a better job of 
fixing the explination.

Please consider suggesting how to improve it.

David Lang

**Comment by VeeEnDee** [comment]
Thank for more detailed explanation, I will try to improve docs. 
as for now closing this issue as it was solved.
