### ISSUE TITLE
Intermittent TLS disconnects when sending over internet

### ISSUE THREAD

**Issue by ManeeshJollyNetsurion** [rsyslog/rsyslog#4699]
### Expected behavior
Configure rsyslog (instance 1) on Linux to send system logs over TLS (GNUTLS) to another instance of rsyslog (instance 2) over the internet. Configure the receiving instance (instance 2) to relay the messages to another receiver (third party application on local network) over UDP 
Expected behavior is that this setup should work without any disconnection between instance 1 and instance 2.

### Actual behavior
Frequent disconnects are observed between the two instances of rsyslog.
 
### Environment
Ubunt18 - rsyslog version 8.34 on both sides

**Comment by rgerhards** [comment]
Hard to diagnose. Maybe a (probably long-fixed) bug in the very old version 8.34 and/or intermittent network problems. I would suggest to upgrade to current and see how things work out.

**Comment by rgerhards** [comment]
I forgot: The rsyslog project provides packages for current versions: https://www.rsyslog.com/downloads/download-other/

**Comment by davidelang** [comment]
adding to this, there has been a LOT of work on the TLS code in the years since 
8.34 was released.

**Comment by ManeeshJolly** [comment]
Thanks Rainer and David, will try with latest version and provide update.

**Comment by ManeeshJollyNetsurion** [comment]
Hi Rainer/David,

It seems to be working after upgrading rsyslog version on both sides.
