### ISSUE TITLE
How to set timestamp

### ISSUE THREAD

**Issue by tbs575** [rsyslog/rsyslog#4721]
### Expected behavior
write right date into  log
### Actual behavior
wrote UTC date into log
### Steps to reproduce the behavior
using rsyslog docker rsyslog/syslog_appliance_alpine:8.36.0-3.7 build rsyslog server, but I can not handle right date (UTC+8) into log.
try mount host localtime into docker container, and enter into contain use 'date' check date, it is right (UTC+8), but check log still using UTC, 
try to set TZ enviroment with docker, but still not wroking.  how to do it?

```
/home/appliance # date
Sun Oct 31 12:02:57 CST 2021
-----------------------
using template to generate log. using %TIMESTAP to write date into log, 
```
:
template(
    name = "filtertemplate"
    type = "string"
    string = "{\"timestamp\":\"%TIMESTAMP:::date-rfc3339%\", \"%$.tmp%\"}\n"
)
:

------------------------------------
checked rsyslog log
{"timestamp":"2021-10-31T04:03:13+00:00", "vsys":"public", "protocol":"17", "source-ip":"172.16.23.2", "source-port":"42578", "destination-ip":"61.139.2.69", "destination-port":"53", "time":"2021/10/31 12:03:13", "source-zone":"trust", "destination-zone":"untrust", "application-name":""}
```


### Environment
- rsyslog version: <!-- e.g. 8.35.0 - use "rsyslogd -v" to obtain the version number -->
- platform: <!-- e.g. Ubuntu 16.04 -->
- for configuration questions/issues, include rsyslog.conf and included config files

<!-- Note: rsyslog documentation is available here:
  - current stable release: http://www.rsyslog.com/doc/v8-stable/
  - pre-release: http://www.rsyslog.com/doc/master/
-->

**Comment by rgerhards** [comment]
what is your rsyslog version?

**Comment by tbs575** [comment]
other method to skip this issue.
