### ISSUE TITLE
Question: How is it possible to use more then one option/replacement to a property 

### ISSUE THREAD

**Issue by sundowner69** [rsyslog/rsyslog#4727]
### Expected behavior
I have a central rsyslog server and receive messages from different devices. The messages are forwarded to a central monitoring system. The %FROMHOST% property should always show the shortname in lowercase letters. 

### Actual behavior
%FROMHOST% comes in like 

- server.domain.com
- SERVER.domain.com
- server
- SERVER

I need a template to translate the %FROMHOST% property in a lowercase short hostname.
For now I can do the one or the other but not both.

- lowercase by %FROMHOST:::lowercase%
- shortname by %FROMHOST:R,ERE,1,FIELD:(([^.*]+){1})--end%

Can you help me? 

### Environment
SLES 12 SP5 
rsyslog-8.24.0-3.39.1

**Comment by rgerhards** [comment]
Use:
```
%FROMHOST:R,ERE,1,FIELD:(([^.*]+){1})--end:lowercase%
```

There are also other, more intuitive approaches via newer config styles. But this is a basic sample. The part after the third colon  has options. Doc: https://www.rsyslog.com/doc/v8-stable/configuration/property_replacer.html

**Comment by sundowner69** [comment]
It works! 
Thanks a lot and stay healthy!

**Comment by rgerhards** [comment]
Perfect! :-)
