### ISSUE TITLE
Inverted ruleset name NULL check logic

### ISSUE THREAD

**Issue by digirati82** [rsyslog/rsyslog#4730]
https://github.com/rsyslog/rsyslog/commit/4a63f8e9629c3c9481a8b6f9d7787e3b3304320b#r59508525

### Expected behavior

A named ruleset will have the name and qtype assigned as defined. An unnamed ruleset will have the name set to "[ruleset]" and qtype set to 3.

### Actual behavior

A named ruleset is named "[ruleset]" and qtype set to 3. An unnamed ruleset name is set to NULL.

### Steps to reproduce the behavior

Define a named ruleset. Ruleset pstats will reflect a name of "[ruleset]"

### Environment
- rsyslog version: 8.2110.0
- platform: Red Hat Enterprise Linux Server release 7.9 (Maipo)

**Comment by rgerhards** [comment]
Please note: the queue type has nothing to do with the ruleset name. For queue type, defaults apply as usual. If there is doubt, please post the relevant config bits.

**Comment by digirati82** [comment]
Our named ruleset works prior to updating, after updating our ruleset name is set to "[ruleset]". You can see the logic inversion at the linked comment.

Relevant line of config that hasn't changed between updates:

ruleset(name="redactedName" ...

Updated code at linked comment:

if(pRuleset->pszName == NULL) {
	rsname = pRuleset->pszName;
	qtype = pRuleset->pQueue->qType;
} else {
	rsname = (uchar*) "[ruleset]";
	qtype = 3;
}

Previously:

rsname = (pRuleset->pszName == NULL) ? (uchar*) "[ruleset]" : pRuleset->pszName;

**Comment by rgerhards** [comment]
ok, so this has nothing to do with queue type. This distracted me.
