### ISSUE TITLE
action.errorfile size management option

### ISSUE THREAD

**Issue by Cropi** [rsyslog/rsyslog#4733]
Do you think it would be appropriate to implement an ```action.errorfile.maxsize``` option rsyslog?

One of our clients is having issues with the huge amount of logs generated by the ```action.errorfile``` option. When forwarding logs to a remote server that is "too often" offline, the number of error messages might grow really quickly.
My understanding is that  ```logrotate``` is the primary tool used for such purpose. However, according to them it is not enough because it has to be executed too many times.
This is more like a question than a request but if it's accepted I can help with the implementation.

**Comment by rgerhards** [comment]
As an option, I think it makes sense for extreme cases. You should warn, however, the customer that this means ultimate loss of messages. I would not object a PR, as long as the default behavior remains the same. I myself am not interested in doing the change.
