### ISSUE TITLE
split based on ip segment

### ISSUE THREAD

**Issue by PJCAfonso** [rsyslog/rsyslog#4734]
### Actual behavior
As service provider rsyslog engineer we neeed split our message based on ip segment, thru diferent topic to omkafka.
for instance:
10.220.6.x  -> topic_1
10.220.15.x -> topic_2
10.221.127.x -> topic_3

How can we implemented this, We are working around dynamic topic but with no sucess.

Any example or any post to help us to implement this features on our sites?

### Environment
- rsyslog version: 8.1910
- platform: Oracle Linux 8.4
- for configuration questions/issues, include rsyslog.conf and included config files

**Comment by mabobr** [comment]
Hi,
  most elegant solution should be using [lookup tables and sparse array](https://www.rsyslog.com/doc/master/configuration/lookup_tables.html) but there is a bug in json lib, which [not going to be fixed](https://github.com/rsyslog/rsyslog/pull/4502). However if ALL your ips are < 127.255.255.255 is may work. You should populate sparse array keys by results of _ipv42num()_ of your ip ranges boundaries. And use kafka topic names as values of sparse array. Then, in omkafka module, use dynamic topic names.

If this is not an option, you can use, something like: 

```
set $.ip_n = ipv42num( $.ip_form_the_event);
if 182191616 <= $.ip_n and $.ip_n <= 182191871 then { set $.topic_name = 'topic_1'; }
else if 182193920 <= $.ip_n and $.ip_n <= 182194175 then { set $.topic_name = 'topic_2'; }
...
action( type="omkafka" DynaTopic="on" topic="your_template_w_topic_name" ... )

 ```

**Comment by PJCAfonso** [comment]
Walk in another direction
