### ISSUE TITLE
/var/log/rsyslog is set to discard the log content of a certain program

### ISSUE THREAD

**Issue by MagicStarTrace** [rsyslog/rsyslog#4755]
OS Version: Ubuntu 18.04 ,  rsyslogd 8.32.0

```
Dec 21 14:17:36 Kubernetes-Node01 virtiofsd[1]: [ID: 00000006] virtio_send_msg: elem 1: with 2 in desc of length 144
Dec 21 14:17:36 Kubernetes-Node01 virtiofsd[1]: [ID: 00000006] fv_queue_worker: elem 1: with 2 out desc of length 53
Dec 21 14:17:36 Kubernetes-Node01 virtiofsd[1]: [ID: 00000006] unique: 7755958, opcode: LOOKUP (1), nodeid: 229, insize: 53, pid: 1637
Dec 21 14:17:36 Kubernetes-Node01 virtiofsd[1]: [ID: 00000006] lo_lookup(parent=229, name=procps-ng.mo)
Dec 21 14:17:36 Kubernetes-Node01 virtiofsd[1]: [ID: 00000006]   229/procps-ng.mo -> 230
Dec 21 14:17:36 Kubernetes-Node01 virtiofsd[1]: [ID: 00000006]    unique: 7755958, success, outsize: 144
Dec 21 14:17:36 Kubernetes-Node01 virtiofsd[1]: [ID: 00000006] virtio_send_msg: elem 1: with 2 in desc of length 144
Dec 21 14:17:36 Kubernetes-Node01 virtiofsd[1]: [ID: 00000006] fv_queue_worker: elem 1: with 2 out desc of length 48
Dec 21 14:17:36 Kubernetes-Node01 virtiofsd[1]: [ID: 00000006] unique: 7755960, opcode: OPEN (14), nodeid: 230, insize: 48, pid: 1637
Dec 21 14:17:36 Kubernetes-Node01 virtiofsd[1]: [ID: 00000006] lo_open(ino=230, flags=32768)
Dec 21 14:17:36 Kubernetes-Node01 virtiofsd[1]: [ID: 00000006]    unique: 7755960, success, outsize: 32
Dec 21 14:17:36 Kubernetes-Node01 virtiofsd[1]: [ID: 00000006] virtio_send_msg: elem 1: with 2 in desc of length 32
Dec 21 14:17:36 Kubernetes-Node01 virtiofsd[1]: [ID: 00000006] fv_queue_worker: elem 1: with 2 out desc of length 64
Dec 21 14:17:36 Kubernetes-Node01 virtiofsd[1]: [ID: 00000006] unique: 7755962, opcode: FLUSH (25), nodeid: 230, insize: 64, pid: 1637
Dec 21 14:17:36 Kubernetes-Node01 virtiofsd[1]: [ID: 00000006]    unique: 7755962, success, outsize: 16
Dec 21 14:17:36 Kubernetes-Node01 virtiofsd[1]: [ID: 00000006] virtio_send_msg: elem 1: with 1 in desc of length 16
Dec 21 14:17:36 Kubernetes-Node01 virtiofsd[1]: [ID: 00000006] fv_queue_worker: elem 1: with 2 out desc of length 80
Dec 21 14:17:36 Kubernetes-Node01 virtiofsd[1]: [ID: 00000006] unique: 7755964, opcode: READ (15), nodeid: 230, insize: 80, pid: 1637
Dec 21 14:17:36 Kubernetes-Node01 virtiofsd[1]: [ID: 00000006] lo_read(ino=230, size=8192, off=0)
Dec 21 14:17:36 Kubernetes-Node01 virtiofsd[1]: [ID: 00000006] virtio_send_data_iov: count=1 len=8192 iov_len=16
Dec 21 14:17:36 Kubernetes-Node01 virtiofsd[1]: [ID: 00000006] virtio_send_data_iov: elem 1: with 3 in desc of length 8208
```

![image](https://user-images.githubusercontent.com/15685376/146881617-c48c1897-af6a-4618-b17c-e3186ebb3cd8.png)

I tried to configure with the following rules:
1) :msg,contains,"* virtiofsd[1] *" stop  
2) :msg,contains,"* virtiofsd[1] *" ~

Both settings are not as expected and still printing

How should I set it up? (If you can expect to be completely discarded or set the log level)

Thanks !

**Comment by rgerhards** [comment]
you are checking the wrong field, the program name is part of the header. Assuming that you just want to get it going and are not interested in the details, use this:
```
:rawmsg,contains,"virtiofsd[1]" stop
```
Note that this matches the exact text. If, for example the number one changes, it won't match.

**Comment by rgerhards** [comment]
and: be sure to place this at the TOP of rsyslog.conf. Things are position dependent.

**Comment by MagicStarTrace** [comment]
> you are checking the wrong field, the program name is part of the header. Assuming that you just want to get it going and are not interested in the details, use this:
> 
> ```
> :rawmsg,contains,"virtiofsd[1]" stop
> ```
> 
> Note that this matches the exact text. If, for example the number one changes, it won't match.

Thank you, it meets expectations

**Comment by MagicStarTrace** [comment]
> and: be sure to place this at the TOP of rsyslog.conf. Things are position dependent.
I put it in /etc/rsyslog.d/x.conf

**Comment by MagicStarTrace** [comment]
> > you are checking the wrong field, the program name is part of the header. Assuming that you just want to get it going and are not interested in the details, use this:
> > ```
> > :rawmsg,contains,"virtiofsd[1]" stop
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Note that this matches the exact text. If, for example the number one changes, it won't match.
> 
> Thank you, it meets expectations



> you are checking the wrong field, the program name is part of the header. Assuming that you just want to get it going and are not interested in the details, use this:
> 
> ```
> :rawmsg,contains,"virtiofsd[1]" stop
> ```
> 
> Note that this matches the exact text. If, for example the number one changes, it won't match.

Can I keep logs of the error level?
