### ISSUE TITLE
imklog bug with nonkernelfacility and new syntax

### ISSUE THREAD

**Issue by jite** [rsyslog/rsyslog#477]
(Pasting description from mail on mailing list 2015-07-08 12:10 GMT+02:00)

If I load imklog with option like this:

$ModLoad imklog
$KLogPermitNonKernelFacility on

it works as expected, I do get non-kernel facility messages, however if
I load it the new way:

module(load="imklog" permitnonkernelfacility="on")

I'm not getting any non-kernel facility messages and I don't see any
warnings in the log either. I've tried other values as "yes", "1", etc
with no luck.

**Comment by alorbach** [comment]
I have run rsyslog in debug mod with "2&>1 | grep permitnonkernelfacility", 

------------------------
module(load="imklog" permitnonkernelfacility="off")
------------------------
7874.791806032:main thread    : 	name: 'permitnonkernelfacility', value 'off'
7874.791894176:main thread    : nvlstGetParam: name 'permitnonkernelfacility', type 4, valnode->bUsed 0
7874.791897753:main thread    : permitnonkernelfacility: 0

------------------------
module(load="imklog" permitnonkernelfacility="on")
------------------------
7912.758151592:main thread    : 	name: 'permitnonkernelfacility', value 'on'
7912.758279489:main thread    : nvlstGetParam: name 'permitnonkernelfacility', type 4, valnode->bUsed 0
7912.758284455:main thread    : permitnonkernelfacility: 1

---------------------------

So technically the property is set correctly.

**Comment by jite** [comment]
Alright, but have you actually tried running it (by logging messages to the kernel log with nonkernel facility set)?

**Comment by alorbach** [comment]
Can you post a minimal working configuration which I need to reproduce the problem? 
I tested on Ubuntu, do I need to run the tests on Freebsd?

**Comment by jite** [comment]
Hmm, I can see if I can scale it down, but it's running on an embedded Linux device right now (mips).

Just to verify: Did you try to write to the kernel log with nonkernel-facility and actually saw the message appear when using the new syntax ? (I just had a *.* /var/log/testfile.log as a rule (and a /dev/console rule too))

**Comment by alorbach** [comment]
I think the configuration I used for testing is not suitable. 
If you share your configuration and method to write nonkernel messages into the kernel log, this would make troubleshooting a lot easier ;)

**Comment by jite** [comment]
Simplest conf file that reproduced the issue for me:

    module(load="imuxsock" SysSock.RateLimit.Interval="0")
    
    module(load="imklog" permitnonkernelfacility="on")                                                            
    
    #$ModLoad imklog
    #$KLogPermitNonKernelFacility on
    
    $WorkDirectory /var/spool/rsyslog
    *.* /var/log/tmp.log

Then just run `echo test1 >/dev/kmsg` and perhaps `echo test2 >/dev/kmsg` when uncommenting the old syntax and commenting out the new.

plugins/imklog/imklog.c:197: I hooked myself in here, and `bPermitNonKernel == 0` no matter the value of `permitnonkernelfacility=""` in the config when using the new syntax.

**Comment by jite** [comment]
Did my last message contain enough information for you to reproduce the issue? Let me know if you need something more/else. Thanks

**Comment by arron-green** [comment]
i too am experiencing the same issue as @jite on ubuntu 14.04 with rsyslog `8.12.0-0adiscon1trusty1`

**Comment by erikanderson** [comment]
Can confirm this issue is present in 8.26.0 on trusty 14.04 as well

**Comment by rgerhards** [comment]
@PascalWithopf Can you please try to reproduce it? A manual repro is fine here IMHO, as we need root permissions anyways (which we do not usually have on the CI machines). But we might discuss how to support that on some environment :-)

**Comment by panlinux** [comment]
Someone sent a patch to the mailing list last year:

http://rsyslog-users.1305293.n2.nabble.com/PATCH-imklog-Fix-permitnonkernelfacility-not-working-tt7591305.html
