### ISSUE TITLE
In imtcp, if we don't close a TCP connection, can we write a log

### ISSUE THREAD

**Issue by ffashion** [rsyslog/rsyslog#4778]
### Expected behavior
I don't want to break the TCP connection  i want to reuse this tcp . Is this possible ?
### Actual behavior
if i dont close this tcp , i can't get all log  message 

### Environment
- rsyslog version: <8.2202.0.master>
- platform: <centos7>

**Comment by davidelang** [comment]
you need to explain the problem more.

unless the sender sends the appropriate end-of-log character, how do you know 
that you have the entire message and should write it?

more details of what your test is that's failing please.

David Lang

**Comment by ffashion** [comment]
thank your responce,  when i load and use  imtcp . i run starce syslogd , i find that i just find recv but i cant find write, and other when i close my tcp, i find the syslogd can write before message to syslog file. but when i use imudp , when a message send to syslogd,  syslogd write this message immediately.  i dont know why , is my sender error ?

**Comment by davidelang** [comment]
On Sun, 16 Jan 2022, ffashion wrote:

> thank your responce,  when i load and use  imtcp . i run starce syslogd , i find that i just find recv but i cant find write, and other when i close my tcp, i find the syslogd can write before message to syslog file. but when i use imudp , when a message send to syslogd,  syslogd write this message immediately.  i dont know why , is my sender error ?

with UDP, a packet is a message, so as soon as the packet is processed, rsyslog 
knows that it has the entire message.

With imtcp, it's looking for a newline (by default) to indicate that the message 
has ended. Can you do a tcpdump so that we can see exactly what has been sent 
over the wire?

David Lang

**Comment by ffashion** [comment]
i find that my code dont have a newline . i add a newline , then  the log can write correctly . thank you again
