### ISSUE TITLE
Compile issues on latest solaris 11.2 (rsyslog 8.12.0)

### ISSUE THREAD

**Issue by janorn** [rsyslog/rsyslog#478]
Standard solaris gcc and rebuilt libestr and liblogging. I get this early which sort of would indicate that sys/types.h is not included but it looks like it is in the glbl.h.

Any idea?

```
$ ./configure --prefix=/appl/local  
...
$ gmake -j 8
gmake  all-recursive
gmake[1]: Entering directory `/data/pkgbuild/tmp/rsyslog-8.12.0'
Making all in compat
gmake[2]: Entering directory `/data/pkgbuild/tmp/rsyslog-8.12.0/compat'
gmake[2]: Nothing to be done for `all'.
gmake[2]: Leaving directory `/data/pkgbuild/tmp/rsyslog-8.12.0/compat'
Making all in runtime
gmake[2]: Entering directory `/data/pkgbuild/tmp/rsyslog-8.12.0/runtime'
  CC       librsyslog_la-glbl.lo
  CC       librsyslog_la-linkedlist.lo
  CC       librsyslog_la-stringbuf.lo
  CC       librsyslog_la-datetime.lo
  CC       librsyslog_la-srutils.lo
  CC       librsyslog_la-errmsg.lo
  CC       librsyslog_la-objomsr.lo
  CC       librsyslog_la-debug.lo
glbl.c: In function ‘setMaxLine’:
glbl.c:372:29: error: ‘INT_MAX’ undeclared (first use in this function)
  } else if(iNew > (int64_t) INT_MAX) {
                             ^
glbl.c:372:29: note: each undeclared identifier is reported only once for each function it appears in
```

**Comment by janorn** [comment]
```
$ grep INT_MAX /usr/include/sys/types.h 
#define INT_MAX         2147483647      /* max value of an "int" */
#define UINT_MAX        4294967295U     /* max value of an "unsigned int" */
```

**Comment by alorbach** [comment]
Can you try without -j8? 
Not sure if the problem is related to a parallel build issue we might have currently.

**Comment by janorn** [comment]
Same result. 

My gcc version is:
```
$ gcc --version
gcc (GCC) 4.8.2
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by alorbach** [comment]
Very strange, can't reproduce yet as I do not have a Solaris 11 machine for testing. 
types.h is also included in glbl.c itself.

**Comment by rgerhards** [comment]
I suggest to work with the solaris community on this one. All the rsyslog project currently can say is that it works on our testbench machines: http://build.rsyslog.com:8010/waterfall?tag=rsyslog-rsyslog 

However, we have almost no Solaris know-how, so there may be a subtle issue in system setup that breaks things. Maybe @dago has an idea?

**Comment by janorn** [comment]
From what I can tell you have installed CSW packages? I try to build it on native solaris. Don't want to bring in third party packages. Would it be possible to get a pkg list from this host:

hostname = unstable11x
uname -m = i86pc
uname -r = 5.11
uname -s = SunOS
uname -v = 11.0

Then I can try to find out which dependencies you have added with the CSW packages.

**Comment by dago** [comment]
Hi, you can find the versions of the installed packages on the buildfarm here:
  http://buildfarm.opencsw.org/versionmatrix.html

**Comment by janorn** [comment]
But this are only the CSW packages. How about the solaris packages? 
I build all our packages for internal use and rsyslog is one of the few I have real issues with building with the native tools. It would be nice if you had a solaris 11 box without CSW at all.

i.e.
$ pkg list

**Comment by janorn** [comment]
Your build farm is basically not solaris but a new gnu environment on top of solaris. Most of all these tools are already available in solaris 11 but in slightly older versions. Latest version I managed to build was 6.2 nothing after that.

**Comment by rgerhards** [comment]
@janorn If you can provide us with a buildbot slave for plain solaris (like CSW does), we can try to fix this issue. Note that we depend on contributors for Solaris builds, as we have extremely limited know-how in that area.

**Comment by janorn** [comment]
How do I provide that to you? I can setup a machine.

**Comment by rgerhards** [comment]
I don't have the specifics, but @alorbach can give you instructions. As far as I know, it's quite easy. To get us continously going, it is necessary to have the machine online at least a couple of hours each day. If possible, ssh access would be great to have for select developers, as this could help us debug quicker.

**Comment by dago** [comment]
You can just use the OpenCSW buildfarm - if you don't add /opt/csw to PATH or PKG_CONFIG_DIR you will get the same build results as from a stock Solaris installation. Unfortunately I am on a tight schedule right now but will be glad to help next month.

**Comment by janorn** [comment]
Ok with you @rgerhards ?

**Comment by rgerhards** [comment]
I think so, but let @alorbach decide. Unfortunately, he got ill over the weekend...

**Comment by alorbach** [comment]
Aso Dago said, use the OpenCSW buildfarm. We are using it too on our solaris buildbots.

**Comment by alorbach** [comment]
I can't get the problem reproduced on our solaris buildbots, even without the environment variables set. @janorn: would it be possible to get ssh access to a testmachine where git, gcc, autotools and all the necessary stuff is installed? You can send login details directly to me alorbach@adiscon.com.

**Comment by rgerhards** [comment]
While I think it would be good to fix the current issue, I think it would be much better if we could integrate the test platform in our buildbot tests. Or  does that mean it's a very environment specific problem?

**Comment by janorn** [comment]
I guess you are still using some CSW tools. Would be nice to se the PATH which is used by the buildbot.
If you don't use the CSW tools you will need to build your dependencies separately and install dom elsewhere. I.e libestr, liblogging and relp. Possibly install them in /usr/local/bin or somewhere build specific. These are the dependencies I add for my build:

```
BuildRequires:  site/library/libestr
BuildRequires:  site/library/liblogging
BuildRequires:  library/json-c
BuildRequires:  web/curl
BuildRequires:  library/python-2/docutils
```

**Comment by janorn** [comment]
Versions:
```
site/library/libestr 0.1.10
site/library/liblogging 1.0.5
library/json-c  0.9
web/curl  7.21.2
```

**Comment by alorbach** [comment]
Our buildbots have these: 
PATH=/usr/bin:/usr/sbin:/opt/csw/bin

So looks like we are still using some parts of csw

**Comment by rgerhards** [comment]
@alorbach just told me he has big issues setting up this environment. We even can't get past autoreconf. Looking at our long TODO list and the fact that we have the opencsw Solution, I think now is the right time to stop looking at this. If @janorn can get us a build environment for continues buildbot use plus hands on help on getting this done, we may be able to complete this (depending on how much work it is). Otherwise I think the best plan is to wait if some commercial sponsor shows up - in my experience non-availability of a sponsor is also a big indicator of no real need for feature. Sorry for the bad news, but I think we should spend our time wisely on the real hot topics (from which we have far too many ;)).

**Comment by janorn** [comment]
Seems like its not a complete solaris development environment setup. I have made a list of packages that needs to be installed. If it is ok by opencsw to install these packages on their hosts? They are part of the solaris repository. They should be possible to install just with pkg install.

List of packages
```
archiver/gnu-tar
crypto/gnupg
developer/assembler
developer/base-developer-utilities
developer/build/ant
developer/build/autoconf
developer/build/automake
developer/build/gnu-make
developer/build/libtool
developer/build/make
developer/build/pkg-config
developer/debug/mdb
developer/documentation-tool/openjade
developer/documentation-tool/opensp
developer/gcc
developer/gnome/gettext
developer/gnu-binutils
developer/library/lint
developer/library/xprofile
developer/macro/cpp
developer/macro/gnu-m4
developer/macro/gnu-m4
developer/versioning/git
developer/versioning/subversion
file/gnu-findutils
library/gnutls
system/header
system/prerequisite/gnu
text/gnu-diffutils
text/gnu-gettext
text/gnu-grep
text/gnu-patch
text/gnu-sed
```

PS
I will be out tomorrow.

**Comment by dago** [comment]
`unstable11s` and `unstable11x` are now update to the latest Solaris 11 release and the above packages have been added.

**Comment by janorn** [comment]
@rgerhards do you need anything more from me at this time? Or can you test now when all packages has been installed?

**Comment by alorbach** [comment]
Something is wrong with the machines, can't even get git to work now: 

fatal: unable to connect to github.com:
github.com[0: 192.30.252.130]: errno=Network is unreachable

**Comment by dago** [comment]
This is intended as the machine do not have direct internet access. Specify something like the git property `http.proxy` set to `http://proxy:3128`. I will also install the public suffix list package later today containing `/opt/csw/share/public_suffix_list.dat`.

**Comment by janorn** [comment]
@dago a symlink to /usr/etc/gitconfig?

**Comment by dago** [comment]
Sure, done.
Oracle: `/usr/etc`, srsly?

**Comment by janorn** [comment]
Strange I admit!
```
# git config --system --list
fatal: unable to read config file '/usr/etc/gitconfig': No such file or directory
```

**Comment by alorbach** [comment]
Ok now we are stuck here ;)

LIBESTR... configure: error: Package requirements (libestr >= 0.1.9) were not met:
No package 'libestr' found

**Comment by janorn** [comment]
You will have to build that as well. libestr and liblogging and even perhaps relp.
I have never got relp to build on native solaris.

**Comment by janorn** [comment]
Perhaps build them and install them in /usr/local? Or build them each time you build rsyslog.

**Comment by janorn** [comment]
Solaris 11 only comes with libestr version 0.1.2.

**Comment by alorbach** [comment]
@dago can you build these libraries and install them?

**Comment by janorn** [comment]
Here is my build config for these libraries.
Libestr:
```
export CC=gcc
export PKG_CONFIG_PATH=%{_prefix}/lib/pkgconfig 
export LDFLAGS=-Wl,-rpath=%{_libdir}
export CFLAGS="-std=gnu99"

./configure\
 --prefix=%{_prefix}\
 --exec-prefix=%{_prefix}\
 --libdir=%{_libdir} \
 --includedir=%{_includedir} \
 --mandir=%{_mandir}

gmake -j$CPUS
```
Liblogging:
```
export CC=gcc
export PKG_CONFIG_PATH=%{_prefix}/lib/pkgconfig 
export LDFLAGS=-Wl,-rpath=%{_libdir}
export CFLAGS="-std=gnu99"

./configure\
 --prefix=%{_prefix}\
 --exec-prefix=%{_prefix}\
 --libdir=%{_libdir} \
 --includedir=%{_includedir} \
 --enable-journal=no \
 --mandir=%{_mandir}

gmake -j$CPUS
```

**Comment by dago** [comment]
The libraries are already install in `/opt/csw` if you need them.

**Comment by janorn** [comment]
But they are linked agains csw libraries... including gcc.

**Comment by janorn** [comment]
In our developer environment (Teamcity) we build dependency libs before we build the actual app. That is for libraries not available on the target platform that is.

**Comment by rgerhards** [comment]
This seems to be solved since quite a while. If not please let us know and we will re-open. Thx
