### ISSUE TITLE
When should I use additional in-memory queues?

### ISSUE THREAD

**Issue by vogelsilvan** [rsyslog/rsyslog#4782]
I'm not sure if this belongs in here, as it has nothing to do with the repository itself _(but i'm asking anyways, because i think my question has the highest possibility to be answered here)_.

So, i've been looking into the different [queue modes](https://www.rsyslog.com/doc/v8-stable/concepts/queues.html) and was wondering **when to make use of additional in-memory queues**, and in which cases they are performance enhancing.

### Usage of (additional) in-memory queues
My current view of _in-memory queues_ is, they are only needed _if_:

**_FixedArray_**
- the syslog server is not always accessible (which would block a queue)
- there is continuous high message output
- you have multiple syslog servers (which i guess automatically creates multiple queues)
 
**_LinkedList_**
- the syslog server is not always accessible (which would block a queue) - and the data needs to be stored
- there is occasional high message output
- you have multiple syslog servers (which i guess automatically creates multiple queues)

Which (if i'm correct) would mean, if none of these cases are met, there is no need for additional queues and the performance enhancement (probably) wouldn't be noticable.

### Question
Is my idea of queues and their usage completely wrong, or are there other use-cases in which they could/should be used?

**Comment by davidelang** [comment]
multiple syslog servers would not automatically create multiple queues.

you create queues when you need to have async processing or have outputs that 
may block and you want other outputs to continue processing messages.

linkedlist vs fixedarray

fixedarray is slightly faster
linkedlist uses less ram when the queue is empty (but not as much less as you 
think since the message object is dynamically allocated in any case)

I always use fixedarray.

David Lang

**Comment by vogelsilvan** [comment]
@davidelang thanks a lot for taking the time to answer my question - and that even though i closed it. 

I thought my question was dumb, or at least some part of it, after reading "There are multiple action queues, one for each configured action." on the rsyslog [documentation](https://www.rsyslog.com/doc/v8-stable/concepts/queues.html).

Also, thanks for your comment about the RAM usage, because i was arguing with myself about which one now really is "better".
