### ISSUE TITLE
rsyslog config help

### ISSUE THREAD

**Issue by AnonymousWebHacker** [rsyslog/rsyslog#4807]
1 - I Search many rsyslog.config examples, but didn't find for these save them in  `/var/log/archive.log`
`pppd` - `xl2tpd` - `vnstat` - `systemd-networkd`

2 - I would also like to know, if I have this output, 
```
systemd-networkd[493]: ppp1: Link DOWN
```
how can I configure rsyslog so that when it detects that line, it saves it in `/var/log/archive.log`

**Comment by davidelang** [comment]
if programname == "systemd-networkd" and $msg == " ppp1: Link DOWN" then 
/var/log/archive.log

for your other question, we'd need to see some sample logs, probably something 
similar with programname, but it's hard to guess accurately without seeing the 
logs.

David Lang

**Comment by AnonymousWebHacker** [comment]
Wow thanks, yesterday I had solved with 
```
:programname, isequal, "systemd-networkd" var/log/archive.log
```
I did not know that I could put conditionals [if], it's great, thanks for your help
