### ISSUE TITLE
variable names case problem

### ISSUE THREAD

**Issue by davidelang** [rsyslog/rsyslog#481]
variable names in templates get forced to be lower case but the variables created by parsers are not always lower case

for example, $!MemTotal won't find the value in { "MemTotal": 8976 } but it will find { "memtotal": 8976 }

this is in v8.12

**Comment by portante** [comment]
So `grammar/lexer.l` uses the case-insensitive option. :(  This means the lexer never sees an uppercase character.  Turn that off, and then stuff starts breaking.  This might be too invasive.

**Comment by rgerhards** [comment]
The route to take here is make sure that variable names are stored in lower case by whoever generates them. We may want to enforce that in those functions that add them.

Back in the dark ages of rsyslog everything was case-sensitive. This caused a lot of trouble. I guess the introduction of (JSON) variables did not properly ensure that everything is lowercase, like it is at other places inside the code.

**Comment by davidelang** [comment]
On Wed, 25 Nov 2015, Rainer Gerhards wrote:

> The route to take here is make sure that variable names are stored in lower case by whoever generates them. We may want to enforce that in those functions that add them.
>
> Back in the dark ages of rsyslog everything was case-sensitive. This caused a lot of trouble. I guess the introduction of (JSON) variables did not properly ensure that everything is lowercase, like it is at other places inside the code.

Is JSON supposed to be case sensitive in it's names? if so and we collapse the 
case, we can end up loosing data from JSON messages if they have two fields that 
differ by case. It would be nice to learn that JSON is not supposed to be case 
sensitive.

Remember that we have only limited control over the JSON we receive. logs from 
logstash will have field names that start wtih @ for example (@timestamp is the 
equivalent of our $timereceived)

David Lang

**Comment by rgerhards** [comment]
ok, you are right. But than it's a much harder question. This means we need to re-introduce case sensitivity in rsyslog :-( something for next year march+

**Comment by portante** [comment]
@davidelang, @rgerhards, perhaps we add an option to mmjsonparse, imjournal, and others, such that they fold variables to lowercase when creating them?  This would be fairly easy to do, and bridge the gap until we can be confident of a solution for case-sensitivity in variable names.

I am trying the case-sensitivity out in a [branch](https://github.com/portante/rsyslog/tree/case-sensitive-vars).  I'll be building a set of packages for EPEL 7 where I can run this to see how it fairs in my environment.

I have also thought about writing my own mm module which would massage the JSON property tree directly to prepare it to be indexed into ElasticSearch the way we need it.  That might be faster than configuration file directives, but certainly less flexible.

**Comment by davidelang** [comment]
On Wed, 25 Nov 2015, Peter Portante wrote:

> @davidelang, @rgerhards, perhaps we add an option to mmjsonparse, imjournal, 
> and others, such that they fold variables to lowercase when creating them? 
> This would be fairly easy to do, and bridge the gap until we can be confident 
> of a solution for case-sensitivity in variable names.

This is probably a good idea, or at least a module that 'fixes' the json names 
to all be lower case (and probably clean up characters that we don't allow in 
rsyslog variable names, like () for example)

it would probably be a good idea to have it take names like foo!bar: value and 
make them foo:{ bar: value}

> I am trying the case-sensitivity out in a 
> [branch](https://github.com/portante/rsyslog/tree/case-sensitive-vars).  I'll 
> be building a set of packages for EPEL 7 where I can run this to see how it 
> fairs in my environment.

changing things to be case sensitive by default will break a lot of existing 
configs, the problem is that there are currently variable that we can't access

> I have also thought about writing my own mm module which would massage the 
> JSON property tree directly to prepare it to be indexed into ElasticSearch the 
> way we need it.  That might be faster than configuration file directives, but 
> certainly less flexible.

what are changes that need to be made? are they something that is going to be 
consistant across installations? or are you just talking about the changes you 
need for your site?

David Lang

**Comment by portante** [comment]
Here is the case-sensitivity branch, 8.14.0 based, build for EPEL 7 and Fedora 21 (Fedora 22 & 23 failed to build because libkafka fails to build, will resolve that later).

I have this deployed on our logging aggregator, taking in about 3,100 logs a minute.

Seems to be working fine.

**Comment by portante** [comment]
Well, it is working fine, for the most part, but I have run into an error where I cannot compare two variables properly.  I have updated the [case-sensitivity branch](https://github.com/portante/rsyslog/tree/case-sensitive-vars) with a few fixes and some new tests that show that the case-sensitivity fixes are needed.  I'll be rebuilding the [COPR](https://copr.fedoraproject.org/coprs/portante/rsyslog-v8.14.0-case-sensitivity-support/monitor/) repo with new bits from these patches.

**Comment by portante** [comment]
I have updated the [case-sensitivity branch](https://github.com/portante/rsyslog/tree/case-sensitive-vars) with fixes and tests that show all the problems I have encountered are solved.

I have also built this for F21 and EPEL 7 and made it available in my COPR [repo](https://copr.fedoraproject.org/coprs/portante/rsyslog-v8.14.0-case-sensitivity-support/monitor/).

**Comment by portante** [comment]
I believe that PR #622 has fixed this.

**Comment by mostolog** [comment]
Dear Mr. @portante , could you have an eye on http://lists.adiscon.net/pipermail/rsyslog/2016-November/043449.html thread?

**Comment by portante** [comment]
@mostolog, looks like the line mentioned in that post was in place before this case-[in]sensitive work.  Perhaps it is worth opening another issue to track that discussion?

**Comment by mostolog** [comment]
Sure. Thanks!
