### ISSUE TITLE
LogMsg segfaults because configuration is not yet loaded

### ISSUE THREAD

**Issue by kulikjak** [rsyslog/rsyslog#4810]
I recently tried bringing Rsyslog 8.2202.0 to Solaris and found out that **rsyslogd** fails with segmentation fault/assertion error when started:
```
Assertion failed: cnf != NULL, file ../../../rsyslog-8.2202.0/runtime/glbl.c, line 194, function glblGetMaxLine
```
with the following stack trace:
```
rsyslogd:core> ::stack
libc.so.1`__lwp_sigqueue+0xa()
libc.so.1`raise+0x1c()
libc.so.1`abort+0xe1()
libc.so.1`_assert_c99+0x81()
glblGetMaxLine+0x2f()
doLogMsg.constprop.0+0xe2()
LogMsg+0xbb()
initAll+0xcfe()
main+0x65()
_start+0x43()
```
The message it's trying to emit is:
_environment variable TZ is not set, auto correcting this to TZ=/etc/localtime [v8.2202.0 try https://www.rsyslog.com/e/2442 ]_

My guess is that this is because of how **glbl.c** was reworked since 8.2104.0 (the last version we have). I did not check how exactly it works but it seems that now there are no default values? IIUIC, configuration is loaded in `initAll()` with
`localRet = rsconf.Load(&ourConf, ConfFile);` but that happens after the TZ env check that calls `LogMsg` and causes this failure because configuration is not loaded yet.

I saw this also when `rsyslogd_InitGlobalClasses()` -> `rsrtInit()` failed due to me having incompatible module **/usr/lib/rsyslog/lmnet.so** from the previous version installed on the machine. While having incompatible libraries is definitely my fault, it should still fail with an error message, not a segmentation fault.

### Expected behavior
Rsyslogd works (or fails with an error message rather than segmentation fault/assertion failure).

### Actual behavior
Quite the opposite.

### Steps to reproduce the behavior
Unset TZ environment variable on non-Linux system (or change `emitTZWarning` in `rsyslogd.c` to always be true) and run rsyslogd.

**Comment by Cropi** [comment]
Hello,

As you already mentioned global parameter handling has been reworked in https://github.com/rsyslog/rsyslog/pull/4760. I accidentally overlooked this one, sorry for that.
May I ask you to include the patch from https://github.com/rsyslog/rsyslog/pull/4812?

**Comment by kulikjak** [comment]
Sure, I will test it and let you know.

**Comment by kulikjak** [comment]
Thanks! I tested rsyslog with your patch and segfault is gone (in all cases mentioned above).
