### ISSUE TITLE
Lookup tables are not reloaded with SIGHUP

### ISSUE THREAD

**Issue by KGuillemot** [rsyslog/rsyslog#4813]
### Expected behavior
When running Rsyslog in "forked" mode (without the -n option), the lookup tables should be reloaded when the signal "HUP" is received by Rsyslog.

### Actual behavior
Actually, when running Rsyslog in forked mode (without the -n option), the lookup tables are not reloaded when the signal "HUP" is received by Rsyslog.
In "no-forked" mode (with the -n option), the lookup tables are correctly reloaded when sending signal "HUP" to Rsyslog.

### Steps to reproduce the behavior
To reproduce the behavior, I used the following configuration file :
```
# Input Modules
module(load="imfile")
# Message Modification Modules
module(load="mmjsonparse")
# Output Modules
module(load="builtin:omfile")
# Lookup table
lookup_table(name="month_str" file="/usr/local/etc/rsyslog.d/_lookup_tables/month_str.json" reloadOnHUP="on")
# Input
input(type="imfile"
      Tag="test"
      File="/var/log/rsyslog_input.log"
      RuleSet="ruleset_test")
# Ruleset
ruleset(name="ruleset_test" queue.workerThreads="8") {
  action(type="mmjsonparse" cookie="")
  if $parsesuccess == "OK" then {
      set $!month = lookup("month_str", $!month_str);
      action(type="omfile" File="/var/log/rsyslog_output.log" template="all_json")
  }
}
# Template
template(name="all_json" type="list") {
    property(name="$!all-json")
    constant(value="\n")
}
```
Il also have a lookup table (as defined in the configuration file above) with the following content : 
```
# /usr/local/etc/rsyslog.d/_lookup_tables/month_str.json
{
    "version" : 1,
    "nomatch" : "-",
    "type" : "string",
    "table" : [
        {"index": "janv.", "value": "01"},
        {"index": "Jan", "value": "01"}
    ]
}
```
To reproduce the issue, I write into file `/var/log/rsyslog_input.log` the following line : 
`{"month_str": "Jan"}`
In the output file `/var/log/rsyslog_output.log` I get the following line : 
`{ "metadata": { "filename": "\/var\/log\/rsyslog_input.log", "fileoffset": "0" }, "month_str": "Jan", "month": "01" }`
Then I modify the following line in my lookup table : 
`{"index": "Jan", "value": "01"},`
to : 
`{"index": "Janxx", "value": "01"},`
I send HUP signal to rsyslog : 
```
# ps auxwww | grep rsyslogd
root 99069  0.0  0.5   41176 19900  -  IsJ  05:15   0:00.88 /usr/local/sbin/rsyslogd -i /var/run/rsyslog.pid -f /usr/local/etc/rsyslog.conf
# kill -HUP 99069
```
And when I re-send the previous line to my rsyslog_input file, I get the same result as above.
__The lookup table has not been reloaded.__

### Environment
I am running Rsyslog on `Hardened BSD` : 
```
root@rsyslog:/ # uname -a 
FreeBSD rsyslog 12.2-STABLE-HBSD FreeBSD 12.2-STABLE-HBSD #0 : Sat Apr 17 17:27:52 UTC 2021     root@updater-01.md.hardenedbsd.lan:/usr/obj/usr/src/amd64.amd64/sys/HARDENEDBSD  amd64
root@rsyslog:/ # freebsd-version -k
12.2-STABLE-HBSD
```
I have the "master" Github version of Rsyslog, compiled just this morning with some extract debug informations concerning lookup tables.
```
root@rsyslog:/ # rsyslogd -vvv
rsyslogd  8.2204.0.master (aka 2022.04) compiled with:
	PLATFORM:				amd64-unknown-freebsd12.2
	PLATFORM (lsb_release -d):		
	FEATURE_REGEXP:				Yes
	GSSAPI Kerberos 5 support:		No
	FEATURE_DEBUG (debug build, slow code):	No
	32bit Atomic operations supported:	Yes
	64bit Atomic operations supported:	Yes
	memory allocator:			system default
	Runtime Instrumentation (slow code):	No
	uuid support:				Yes
	systemd support:			No
	Config file:				/etc/rsyslog.conf
	PID file:				/var/run/rsyslogd.pid
	Number of Bits in RainerScript integers: 64

See https://www.rsyslog.com for more information.
```

### Solving
Regarding this issue, I made some investigation, and I think I found the problem : 
When Rsyslog starts up, it loads lookup tables and create a thread to reload them in case of "SIGHUP" (done in **runtime/lookup.c line 101** : 
```
	CHKiConcCtrl(pthread_create(&pThis->reloader, &pThis->reloader_thd_attr,
		lookupTableReloader, pThis));
```
Those threads are created BEFORE Rsyslog forks (done into **tools/rsyslogd.c in function forkRsyslog**).
It seems that the lookup table reload-thread(s) are killed when the main thread exits, after forking, in **tools/rsyslogd.c line 475** : 
```
	dbgprintf("rsyslogd: parent terminates after successful child startup\n");
	exit(0);
```
I couldn't find an easy way to solve this issue, but I would be glad to if I had some guidelines.

**Comment by KGuillemot** [comment]
Hello,
Any news about this issue please ?
Thank you.

**Comment by frikilax** [comment]
Hello @rgerhards, the issue has been verified again on versions 8.2206.0 and 8.2306.0
This is becoming complicated for us to ensure high availability of Rsyslog, easy reloading of lookup tables and many rulesets/configuration files because of this, is there something we can do to help resolve this issue ?

**Comment by rgerhards** [comment]
@KGuillemot ne need any longer for the debug log. I was able to reproduce. Looks a bit tricky, reload thread seems to run in wrong process ;-)
