### ISSUE TITLE
gtls NetstreamDriver doesn't work since 8.2106.0

### ISSUE THREAD

**Issue by kulikjak** [rsyslog/rsyslog#4816]
I found one more (and it seems pretty old) issue when upgrading to the latest and greatest on Solaris. It seems that between 8.2104.0 (we currently have) and 8.2106.0, something broke gtls features stopped working.

I tracked the issue to this commit https://github.com/rsyslog/rsyslog/commit/a08591be5d9f3e7e076c5a0347dd5df1c790e965 but so far wasn't able to determine what exactly the problem is.

For testing I am using the following configuration:
Server:
```
$DefaultNetstreamDriver gtls
$DefaultNetstreamDriverCAFile /etc/rsyslog.cert/ca-cert.pem
$DefaultNetstreamDriverCertFile /etc/rsyslog.cert/server-cert.pem
$DefaultNetstreamDriverKeyFile /etc/rsyslog.cert/server-key.pem

$ModLoad imtcp

$InputTCPServerStreamDriverMode 1
$InputTCPServerStreamDriverAuthMode anon
$InputTCPServerRun 5822
```

Client:
```
$DefaultNetstreamDriverCAFile /etc/rsyslog.cert/ca-cert.pem
$DefaultNetstreamDriver gtls
$ActionSendStreamDriverMode 1
$ActionSendStreamDriverAuthMode anon

*.* @@A.B.C.D:5822
```

On the old version, I can see messages logged on the client with `logger -p error 'encrypted tcp log'` appear in the server log. With the new version, this doesn't happen, `snoop -d net0 -x 0 port 5822` on server no longer shows communication when I use `logger` on client, and when launching the client, I don't see "_GnuTLS handshake succeeded_" in the log anymore. I played with some debug outputs and it seems that this: https://github.com/rsyslog/rsyslog/blob/dbcef8a0d27ae8308eee928a6560bf2da68c8ac5/runtime/nsd_gtls.c#L2230
never finishes.

Also, the issue seems to be on the server machine as different rsyslog versions on the client don't change anything.

I am happy to continue my search for the root issue, but I am not sure how to continue - can I get some pointers as to what should I look for? Or am I using a configuration that shouldn't be used on newer versions anymore?

**Comment by kulikjak** [comment]
So, I did more digging and got much closer to the issue. The problem is that tls is not being properly initialized on a server because `$InputTCPServerStreamDriverMode 1` is not taken into account (it's initialized as with `Mode 0`).

I added some debug prints into `imtcp.c` and found out that when `createInstance` is called:
https://github.com/rsyslog/rsyslog/blob/fa3ec461333963f510812c15720d499869d73f7c/plugins/imtcp/imtcp.c#L372
`loadModConf->iStrmDrvrMode` is still not set (it's zero).

It is set later in `addListner` here:
https://github.com/rsyslog/rsyslog/blob/fa3ec461333963f510812c15720d499869d73f7c/plugins/imtcp/imtcp.c#L475
but after the change in https://github.com/rsyslog/rsyslog/commit/a08591be5d9f3e7e076c5a0347dd5df1c790e965, `inst` value is being used instead of `loadModConf` and that one is still zero.

I am not sure though when exactly it gets loaded (and why is it after `createInstance` is called).

**Comment by rgerhards** [comment]
@alorbach can you have a look within the next time?

**Comment by rgerhards** [comment]
@kulikjak did you try a blame to see if there really was a recent commit that affected the order?

sry for being brief, I am very busy this week as I was absent last week and there is some urgent work

**Comment by kulikjak** [comment]
> @kulikjak did you try a blame to see if there really was a recent commit that affected the order?

No, not yet, but I will look into it. So, the correct load order should indeed be `BEGINendCnfLoad();` first and `addInstance();` after that? It seems logical, but just to be sure so I am not looking into dead ends...

> sry for being brief, I am very busy this week as I was absent last week and there is some urgent work

No problem, thanks for looking into this!

**Comment by kulikjak** [comment]
So, I tested a few versions (8.2104.0, 8.2004.0, 8.1904.0 and 8.38.0) and all of those have the same call order mentioned above.

**Comment by alorbach** [comment]
From the first look I would say this is an issue related to legacy config format, our testbench uses new configuration format most of the time. 

Can you try to to run rsyslog with new style configuration?
See samples for you below: 

Server:
```
global( defaultNetstreamDriverCAFile="/etc/rsyslog.cert/ca-cert.pem"
	defaultNetstreamDriverCertFile="/etc/rsyslog.cert/server-cert.pem"
	defaultNetstreamDriverKeyFile="/etc/rsyslog.cert/server-key.pem"
	defaultNetstreamDriver="gtls" )

module(load="imtcp"
	StreamDriver.Name="gtls"
	StreamDriver.Mode="1"
	StreamDriver.AuthMode="anon" )
```

Client: 
```
global(
	defaultNetstreamDriverCAFile="/etc/rsyslog.cert/ca-cert.pem"
	defaultNetstreamDriver="gtls"
)

action(
	type="omfwd" 
	protocol="tcp" 
	target="A.B.C.D" 
	port="5822"
	StreamDriver="gtls" 
	StreamDriverMode="1" 
	StreamDriverAuthMode="anon")
```

**Comment by kulikjak** [comment]
With this new style configuration everything works as expected (I only needed to add `input(type="imtcp" port="5822")` to the server configuration).

Client can be both old and new style - it works in both cases.

**Comment by rgerhards** [comment]
Note: this behavior was actually caused by a bug fixed in https://github.com/rsyslog/rsyslog/pull/5022
