### ISSUE TITLE
omfile-hardened: Compile error

### ISSUE THREAD

**Issue by dongheeJeong** [rsyslog/rsyslog#4827]
### Expected behavior

Success compile without error.

### Actual behavior

Compile fails with error.

### Steps to reproduce the behavior

`./configure --enable-omfile-hardened && make`

Error message is like below.
```
...
...

omfile-hardened.c: In function 'janitorChkDynaFiles':
omfile-hardened.c:1005:45: error: dereferencing pointer to incomplete type 'rsconf_t' {aka 'struct rsonf_s'}
 1005 |    pCache[i]->nInactive += runModConf->pConf->globals.janitorInterval;
      |                                             ^~
make[2]: *** [Makefile:564: omfile_hardened_la-omfile-hardened.lo] Error 1

...
...
```

### Environment
- rsyslog version:  rsyslogd  8.2204.0.master (aka 2022.04) 
- platform:  Ubuntu 20.04
- for configuration questions/issues, include rsyslog.conf and included config files

**Comment by rgerhards** [comment]
This is a contributed module which we do not support. I wonder why you use it at all, because it provides very limited benefit and extremely bad performance.

**Comment by rgerhards** [comment]
In any case, I will add a descriptive text that this module is broken and needs a fix.
