### ISSUE TITLE
RSyslog CPU usage > 100%

### ISSUE THREAD

**Issue by Gary-S-ingh** [rsyslog/rsyslog#4834]
### Expected behavior
Service should run with normal CPU usage

### Actual behavior
Hi, We currently have RSyslog Server (On Linux Ubuntu 18.04 VM LTA with Size: Standard D4s v3 4 vcpus, 16 GiB memory) receiving logs from ZScaler Proxy & FortiGate Firewalls and ingesting them into Azure Sentinel. 
The issue is, after a few minutes/hours the CPU starts reaching max 100% and netstat connection to each firewall gets stuck in ESTABLISHED state and ultimately stops processing the logs. 
Below is the sample output:
![image](https://user-images.githubusercontent.com/78245552/160029222-4f015d4e-6302-455d-8d85-1bea30dd9937.png)

It requires restarting the RSyslog service to resume the traffic flow. The traffic between Firewalls and Syslog (TCP 514) is encrypted using TLS 1.2 and Certificates are generated locally on this Syslog Server and distributed across Firewalls

Another important observation is during the CPU max out phase, the load across CPU cores is not equal and shows only one over-utilized as seen in the below screenshot:
![image](https://user-images.githubusercontent.com/78245552/160029251-702794a5-8f04-4748-964a-2cb7802b3c07.png)

Based on recent recommendations, we tried upgrading RSyslog version to the latest rsyslogd  8.2202.0 (aka 2021.12) but the issue still persists

It would be great if someone can please advise what could be the possible issue and how to fix it?

### Environment
- rsyslog version: rsyslogd  8.2202.0 (aka 2021.12) 
- platform: Linux Ubuntu 18.04 VM LTA with Size: Standard D4s v3 4 vcpus, 16 GiB memory
- for configuration questions/issues, include rsyslog.conf and included config files

**Comment by davidelang** [comment]
without seeing the config, it's hard to say for sure, but by any chance are you 
using TLS for the communication? there is work currently being done to track 
down an issue there. There's a proposed patch for people to try.

David Lang

**Comment by Gary-S-ingh** [comment]
> without seeing the config, it's hard to say for sure, but by any chance are you using TLS for the communication? there is work currently being done to track down an issue there. There's a proposed patch for people to try. David Lang
Thanks David, that's correct we are using TLS 1.2 for the communication and generating certificates locally on this same server that is running RSyslog D. I can share the rsyslog configuration file if that helps but would be great if you can please share some more details or a reference link to the proposed patchwork being worked on ..

**Comment by davidelang** [comment]
see https://github.com/rsyslog/rsyslog/issues/4818 and PR 4823

David Lang

**Comment by alorbach** [comment]
If you are using GNUTLS driver for rsyslog, you can Test the following PR which addresses this problem:
https://github.com/rsyslog/rsyslog/pull/4823

**Comment by Gary-S-ingh** [comment]
Hi @alorbach what specific commands/configuration should I run to test if that fixes the CPU issue?

**Comment by davidelang** [comment]
This seems to be a problem with an error path in the encryption code. It's been 
hard to duplicate, and we aren't sure if what we've identified in the entire 
problem or just one possible path to trigger the problem.

So there isn't a trivial way to test this. You would need to run the patched 
version and see if the problem happens again or not.

The issue that's been identified has to do with the encrypted connection getting 
interrupted or having packets dropped during setup, so if you test with 
something that creates lots of connections, but doens't always close them 
correctly, that is more likely to trigger the known issue. But we are most 
interested in testing to find out if there are other problems that we don't know 
about that cause similar symptoms.

David Lang

**Comment by Gary-S-ingh** [comment]
thanks, heaps @davidelang , We are currently running rsyslogd 8.2202.0, should I try upgrading to 8.2204.0 i.e. expected to release this month April 2022? Also in regards to the connections, I believe the problem symptoms are quite similar in our case as the encryption connections from our Firewalls to the Syslog get interrupted after a while. thanks

**Comment by Gary-S-ingh** [comment]
Hi @alorbach @davidelang It would be really great if you can please advise on the patched version we should try? thanks

**Comment by davidelang** [comment]
I will have to defer to @alorbach, but he posted last week to try this PR 
https://github.com/rsyslog/rsyslog/pull/4823

I don't know that there is a precompiled version availble. The Adiscon folks are 
in Germany, so they will be waking up shortly.

David Lang

**Comment by rgerhards** [comment]
closed via https://github.com/rsyslog/rsyslog/pull/4823

**Comment by davidelang** [comment]
Yes, we are expecting 8.2204 to be released in about two weeks. I would guess 
that this fix is going to be in it as it appears to be a real bug (and in 
addition looks like it may solve the problem for some people)

David Lang
