### ISSUE TITLE
test suite fails, tests/mmpstrucdata-invalid-vg.sh  tests/mmpstrucdata-vg.sh missing in the tarball

### ISSUE THREAD

**Issue by mbiebl** [rsyslog/rsyslog#484]
Version: 8.12.0

I tried building rsyslog from the 8.12.0 release tarball. This failed, because valgrind was installed and therefor the test-suite tried to run tests/mmpstrucdata-invalid-vg.sh and  tests/mmpstrucdata-vg.sh, which are missing from the tarball. 
Running a diff -qr git/tests tarball/tests
I get
Only in tests: .gitignore
Only in tests: elasticsearch-error-format-check.py
Only in tests: es_response_get_msgnum.py
Only in tests: filewriter.c
Only in tests: historical
Only in tests: imfile-readmode2-polling.sh
Only in tests: longrun.sh
Only in tests: loop.sh
Only in tests: mmpstrucdata-invalid-vg.sh
Only in tests: mmpstrucdata-vg.sh
Only in tests: mysql-actq-mt-withpause-extended.sh
Only in tests: pmlastmsg.sh
Only in tests: rscript.c
Only in tests: rt-init.c
Only in tests: runtime-dummy.c
Only in tests: sndrcv_tls_anon_rebind.sh
Only in tests: testbench.h
Only in tests: testconfgen.c
Only in tests/testsuites: 1.retry.conf
Only in tests/testsuites: imfile-readmode2-polling.conf
Only in tests/testsuites: master.pmlastmsg
Only in tests/testsuites: mmpstrucdata-invalid.conf
Only in tests/testsuites: mysql-actq-mt-withpause-extended.conf
Only in tests/testsuites: parse1udp.conf
Only in tests/testsuites: pmlastmsg.conf
Only in tests/testsuites: sndrcv_tls_anon_rcvr.conf
Only in tests/testsuites: sndrcv_tls_anon_rebind_rcvr.conf
Only in tests/testsuites: sndrcv_tls_anon_rebind_sender.conf
Only in tests/testsuites: sndrcv_tls_anon_sender.conf
Only in tests/testsuites: upcase-date.parse1
Only in tests/testsuites/x.509: request.pem

**Comment by rgerhards** [comment]
@alorbach can this be closed? (it looks so)

**Comment by alorbach** [comment]
Yes this can be closed.
