### ISSUE TITLE
Why doesn't this short config script work?

### ISSUE THREAD

**Issue by systemdlete** [rsyslog/rsyslog#4843]
A brief script (see below) defining a ruleset for port 513 input does not seem to be working for me.   Maybe I have made a typo somewhere, or forgot to load some module, etc.  I apologize if this should be very obvious.  (But it probably is.)

### Expected behavior
This is a simple "hello world" sort of script.  It is intended as a demonstration of a simple ruleset for use with imudp; it is not intended to do anything useful.   I will of course add more later.  I would expect any message to appear in the file specified (/tmp/test.out)

### Actual behavior
No output appears in /tmp/test.out

### Steps to reproduce the behavior
calling
` logger -P 513 some test message here`
should (I think) cause the message "some test message here" to be logged to /tmp/test.out

### Environment
- rsyslog version: 8.2102.0
- platform: devuan chimaera (debian 11, sans systemd)
- for configuration questions/issues, include rsyslog.conf and included config files

Here is the entire script (completely self-contained, no other scripts are called).   I will call it "simple.conf" so that I launch it, for testing it, with something like
`rsyslogd -iNONE -dn -f simple.conf`

```
module(load="imuxsock")
module(load="imklog")
$ActionFileDefaultTemplate RSYSLOG_TraditionalFileFormat
$FileOwner root
$FileGroup adm
$FileCreateMode 0644
$DirCreateMode 0755
$Umask 0022
$WorkDirectory /var/spool/rsyslog

module(load="imudp")
input(type="imudp" port="513" ruleset="rs-test")

ruleset(name="rs-test")
{
	action(type="omfile" file="/tmp/test.out")
}

#*.* /tmp/oldtest.out
```
### Other
I have tried adding a template definition and calling the action statement that way, but it did not make any difference.

Logging output to a file and examining it seems to indicate that no actual action is taken (which makes sense, given there is no output in the file /tmp/test.out).   rsyslogd definitely gets the logger message, but doesn't seem to do anything with it.

**Comment by rgerhards** [comment]
I am not sure if `logger -P` actually send UDP messages. I guess no. Usually, you need to add `-d` to make it use udp.

**Comment by rgerhards** [comment]
> I believe that rsyslogd is getting the message. It just doesn't seem to do anything with it.

it's not, else the message would show up. firewall? also, `-u` is NOT UDP and should also err out because of missing socket name. Well, maybe things are different on your distro.

**Comment by systemdlete** [comment]
I am running rsyslogd and logger on the same system.   I ran wireshark to see if the packet is getting hung up there, but it wasn't.  I think the loopback might be used for this connection.

I tried again with -d (sorry) and it still did not work.

**Comment by systemdlete** [comment]
nvm.  I think I've got this.   I forgot to pass the name of the server (because I am working on the server!).  logger sends to the log device by default.  So passing the server name seems to coerce it to use the network port.

**Comment by rgerhards** [comment]
excellent, glad it worked for you. So closing this issue.

**Comment by systemdlete** [comment]
Just one thing to note, though.   I did not need to specify -d (use udp) in the call to logger.  It seems that udp is the default.

**Comment by davidelang** [comment]
On Fri, 1 Apr 2022, systemdlete wrote:

> $ActionFileDefaultTemplate RSYSLOG_TraditionalFileFormat
> $FileOwner root
> $FileGroup adm
> $FileCreateMode 0644
> $DirCreateMode 0755
> $Umask 0022

just pointing out that these have zero effect on action() statements, they only 
apply to the legacy format actions. With the action() statement you need to 
include these options in every action()
