### ISSUE TITLE
imfile: Reason: Permission denied 

### ISSUE THREAD

**Issue by longren610** [rsyslog/rsyslog#4846]
Start rsyslog to report an error: Permission denied 
```
rsyslogd: imfile: on startup file '/www/wwwlogs/access.log' does not exist but is configured in static file monitor - this may indicate a misconfiguration. If the file appears at a later time, it will automatically be processed. Reason: Permission denied [v8.2001.0]
```

Permission configuration:
```
root@web:~# ll /www/wwwlogs/access.log
-rwxrwxrwx 1 www www 0 Mar 24 13:54 /www/wwwlogs/access.log*
root@web:~# ls -lZ /www/wwwlogs/access.log
-rwxrwxrwx 1 www www ? 0 Mar 24 13:54 /www/wwwlogs/access.log
```

/etc/rsyslog.d/access.conf configuration:
```
module(load="imfile" PollingInterval="10" statefile.directory="/var/spool/rsyslog/waf-log/")
input(type="imfile"
      File="/www/wwwlogs/access.log"
      Tag="web-info"
      Severity="info"
      Facility="local6")
local6.info        @10.0.0.211:514
```

Changing /www/wwwlogs/access.log to /var/log/access.log works fine,  How do I need to fix this error?

### Environment
- rsyslog version: 8.2001.0
- platform: Ubuntu 20.04.4 LTC
- for configuration questions/issues, include rsyslog.conf and included config files

**Comment by longren610** [comment]
The problem is solved, the parent directory must also be given read permission.

**Comment by aristeosavelli** [comment]
> for future reference, this sort of thing can also be caused by AppArmor (ubuntu) or SELinux (RedHat) David Lang

Hi. I have the same problem "imfile: on startup file '/var/globaleaks/log/globaleaks.log' does not exist but is configured in static file monitor - this may indicate a mis" ad seems to be is caused by AppArmor

**Comment by aristeosavelli** [comment]
> > for future reference, this sort of thing can also be caused by AppArmor (ubuntu) or SELinux (RedHat) David Lang
> 
> Hi. I have the same problem "imfile: on startup file '/var/globaleaks/log/globaleaks.log' does not exist but is configured in static file monitor - this may indicate a mis" ad seems to be is caused by AppArmor

How could I solve this problem?

**Comment by rgerhards** [comment]
pls check the AppArmor documentation on how to permit rsyslog to access this file.

**Comment by aristeosavelli** [comment]
> pls check the AppArmor documentation on how to permit rsyslog to access this file.
Sure. It is right what you write, however if I wrote it is precisely because the documentation is not clear.
Have you any suggest for me?

**Comment by aristeosavelli** [comment]
> pls check the AppArmor documentation on how to permit rsyslog to access this file.

Sure. It is right what you write, however if I wrote it is precisely because the documentation is not clear.
Have you any suggest for me?

**Comment by rgerhards** [comment]
I don't know much about AppArmor (it's not a rsyslog thing). Check the AppArmor documentation (same for SeLinux).

**Comment by kmotrebski** [comment]
`AppArmor` was indeed a problem in my case in latest Ubuntu 24.04!!

Entire day of frustrations because of it. It turned out that latest Ubuntu `24.04 LTS` has much more strict default configuration for `AppArmor` feature - this includes `rsyslog`. Basically AppArmor was preventing `rsyslog` to access a file.

So in my case solution was two-fold:
- adding `syslog` user to the group that is the file owner
```bash
sudo usermod -a -G YOUR_GROUP_OWNING_THE_FILE syslog
```
- disabling `AppArmor` configuration for `rsyslog` - [see docs](https://ubuntu.com/server/docs/apparmor), in my case it was:
```bash
sudo ln -s /etc/apparmor.d/usr.sbin.rsyslogd /etc/apparmor.d/disable/
sudo apparmor_parser -R /etc/apparmor.d/usr.sbin.rsyslogd
sudo aa-status
# the below should return nothing:
sudo aa-status | grep rsyslog
```

**Comment by humitos** [comment]
I had the same problem and solved it **without disabling apparmor on rsyslog**. I created the file `/etc/apparmor.d/rsyslog.d/rsyslog-logfile.apparmor` with the following content:

```
# Access to read & write log file
  {{ path_to_log_file }} rw,
```

(replace `{{ path_to_log_file }}` with the path of the file where rsyslog received "Permission denied")

**Comment by Egor1234567890** [comment]
In my case, it was also necessary to give the rights to execute, and not just read, for the directory in which the file is located.
