### ISSUE TITLE
$LocalHostIPIF

### ISSUE THREAD

**Issue by hanfeng-zz** [rsyslog/rsyslog#4855]
### Expected behavior
In client side ,Change the client ip-address and host-name ， The modification is displayed on the rsyslog service side
### Actual behavior
In rsyslog server side ,host-name was changed,but the ip-address hasn't changed
### Steps to reproduce the behavior

$LocalHostIPIF 192.168.31.7
$LocalHostName tina

### Environment
- rsyslog version: 
- platform: 
- for configuration questions/issues, include rsyslog.conf and included config files
- rsyslog version: !-- e.g. 8.35.0 
- platform: Ubuntu 20.04
- configuration questions: 
- In server side，The following error message is displayed：$LocalHostIPIF: IP address for interface '192.168.31.7' cannnot be obtained - ignoring directive [v8.2008.0.9d70869d4ea5]
- Now what am I supposed to do，thanks

**Comment by rgerhards** [comment]
as the error message says: the IP address either does not exist or the OS does not permit rsyslog to access it:
```
$LocalHostIPIF: IP address for interface '192.168.31.7' cannot be obtained - ignoring directive [v8.2008.0.9d70869d4ea5]
```
Nothing we can do against that.

I you think this is indeed a but, please update to the recent 8.2204.0 version and check if the behavior is the same (I would think so).

**Comment by rgerhards** [comment]
oh - my fault: you need to give the interface name, not the IP Address!

see doc: https://www.rsyslog.com/doc/master/configuration/global/index.html

**Comment by davidelang** [comment]
note that there is a trend in linux distros to mvoe to ip for assigning 
addresses instead of ifconfig. With ip you can have many IP addresses assigned 
to a single interface name (as opposed to with ifconfig you do something like 
eth0:2 eth0:3)

So long term, it may be neccessary to make it able to assign by address rather 
than name.

David Lang
