### ISSUE TITLE
mmanon: IPv6 addresses in shortened form followed by a port greater 4 digits is not rewritten properly

### ISSUE THREAD

**Issue by xshadow** [rsyslog/rsyslog#4856]
Dear rsyslog team, thanks for implementing log anonymization of IPv6 addresses in https://github.com/rsyslog/rsyslog/issues/4725. 

I found a case, where a shortened IPv6 address that lack (hex)digits between two colons and is followed by a port (with more then 4 digits), is not anonymized.

Shortened IPv6:  1a00:c820:1180:c84c::ad3f:d991:ec2e
Long IPv6: 1a00:c820:1180:c84c:0000:ad3f:d991:ec2e

### Expected behavior
A shortened IPv6 address followed by a port of any length should be anonymized

### Actual behavior
A shortened IPv6 address followed by a port with more then 4 digits is not anonymized and completely visible in the logs.

### Steps to reproduce the behavior

A reproducer for a case that isn't caught yet would be the following:
```
logger "Uncatched IPv6 with 5digit port 1a00:c820:1180:c84c::ad3f:d991:ec2e:49255"

results in syslog message:  
Uncatched IPv6 with 5digit port 1a00:c820:1180:c84c::ad3f:d991:ec2e:49255
```

```
logger "Uncatched IPv6 with 6digit port 1a00:c820:1180:c84c::ad3f:d991:ec2e:492555"

results in syslog message:  
Uncatched IPv6 with 6digit port 1a00:c820:1180:c84c::ad3f:d991:ec2e:492555
```

### Environment
```
rsyslogd  8.2110.0 (aka 2021.10) compiled with:
	PLATFORM:				x86_64-pc-linux-gnu
	PLATFORM (lsb_release -d):		
	FEATURE_REGEXP:				Yes
	GSSAPI Kerberos 5 support:		Yes
	FEATURE_DEBUG (debug build, slow code):	No
	32bit Atomic operations supported:	Yes
	64bit Atomic operations supported:	Yes
	memory allocator:			system default
	Runtime Instrumentation (slow code):	No
	uuid support:				Yes
	systemd support:			Yes
	Config file:				/etc/rsyslog.conf
	PID file:				/run/rsyslogd.pid
	Number of Bits in RainerScript integers: 64

See https://www.rsyslog.com for more information.
```

```
#File:  /etc/rsyslog.d/20-anon.conf 
module(load="mmanon")
action(type="mmanon" mode="zero" ipv4.bits="32" ipv6.bits="128")
```

**Comment by davidelang** [comment]
I remember seeing a similar report in the past, while 2110 isn't that old, 
please confirm that the problem still exists on 2204

David Lang

**Comment by rgerhards** [comment]
Actually, the patch was part of scheduled stable 8.2112.0, so 2110 is too old.

**Comment by rgerhards** [comment]
forgot the patch link: https://github.com/rsyslog/rsyslog/pull/4735

**Comment by xshadow** [comment]
The patch you linked was backported into the debian package rsyslog 8.2110.0-4 . 

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1000335

**Comment by rgerhards** [comment]
I can confirm the bug.

**Comment by rgerhards** [comment]
I just wanted to note that there will always be some border cases. Take for example the string
```
49225:1a00:c820:49225:c84c:ad3f::d991:ec2e:49225
```
It will be treated as `4 - 9225....`. As such, it unveils a bit more than intended after anon:
```
49225:1a00:c820:49225:c84c:0:0:0:0:0:0:49225
```
There is no way to avoid this, as any character my be in front of an IP address. If we drop some character classes, we get other weak spots. Just saying this for the record.

**Comment by rgerhards** [comment]
This is another case where the result may be unexpected:
```
1a00:c820:1180:c84c:ad3f::d991:ec2e:4922
```
This is abbreviated, but with 8 number blocks. So it looks like 4922 is the port. HOWEVER, when processing the message, we indeed initially detect that. But than parsing moves over `1a00:` and the rest looks like a valid IPv6 (7 blocks, plus zero abbreviation). As such, we will treat it as such. This results in the following output:
```
1a00:c820:1180:0:0:0:0:0:0
```
With non-IPv6 Text `1a00` followed by the IPv6 address. Of course, this means port is lost, but one more number block is shown un-anonymized. I guess there are a myriad of other samples.

**Comment by xshadow** [comment]
Unfortunately that's true, there might be multiple cases where this can happen. 

I  added examples for 4 digit ports: 

```
logger "IPv6 with 4digit port 1a00:c820:1180:c84c::ad3f:d991:ec2e:4924"
logger "IPv6 with 4digit port 1a00:c820::1180:c84c:ad3f:d991:ec2e:4924"

results in log messages such as

IPv6 with 4digit port 1a00:0:0:0:0:0:0:0:0
IPv6 with 4digit port 1a00:0:0:0:0:0:0:0:0
```

I opened up an issue in the apache2 some month ago, the upstream software which causes the trouble. https://bz.apache.org/bugzilla/show_bug.cgi?id=65696
