### ISSUE TITLE
RSyslog gets stuck when processing logs received via TLS

### ISSUE THREAD

**Issue by irtimmer** [rsyslog/rsyslog#4859]
### Expected behavior
RSyslog should continue processing logs received via TLS

### Actual behavior
When configurating TLS using the OpenSSL plugin, RSyslog will be stuck in a loop and stop processing log received via TLS.

After analyzing the debug log of RSyslog we found the following behavior:
There are two streams A and B. A has the field `rtryCall` set in `nsd_ossl_t` and is not receiving any new data for some time. Therefore any successive call to `osslRecordRecv` will return `RS_RET_RETRY`. Stream B has some data left in the internal buffer. `nsdsel_ossl` therefore will do a dummy select. Wait will returns there is one stream ready to be read. However it will first process stream A and run the function `isReady`. This will return `RS_RET_RETRY` and decrease the variable `nfds` as it's is considered an error. This will stop RSyslog from processing Stream B as it thinks it already processed the one stream ready to be read. So as long Stream A does not receive any new data, RSyslog will be stucked in a dummy select loop.

A suggested fix is provided with #4858

### Steps to reproduce the behavior
Not sure if it can easily be reproduced. We only found this issue at a single server, which stopped processing logs after a few seconds.

### Environment
- rsyslog version: 8.2110.0
- platform: Debian 11

**Comment by alorbach** [comment]
Closed by https://github.com/rsyslog/rsyslog/pull/4858

**Comment by davidelang** [comment]
There are fixes that went in to 8.2204 to address this, can you please test and 
see if that solves your problem?

David Lang
