### ISSUE TITLE
rsyslog and CA_bundle not supported

### ISSUE THREAD

**Issue by diepes** [rsyslog/rsyslog#4864]
### Expected behavior
# Use trusted CA's
global(DefaultNetstreamDriverCAFile="/etc/pki/tls/certs/ca-bundle.trust.crt")

#Send  send out data to provider, not worrying about them updating there certs, changing CA's
       action( type="omfwd" protocol="tcp" target="intake.logs.datadoghq.com" port="10516"
                template="DatadogFormat"
                StreamDriver="gtls" StreamDriverMode="1" StreamDriverAuthMode="x509/name"
                StreamDriverPermittedPeers="*.logs.datadoghq.com" ResendLastMSGOnReconnect="on"
                queue.type="linkedlist"
                queue.filename="dd-logs"
                action.resumeRetryCount="-1"
                queue.saveOnShutdown="on"
                queue.maxDiskSpace="1g"
                queue.size="1000"  # v8.30 action default 1k
                #queue.highWatermark  # default 90% of queue.size -> disk
                #queue.lowWatermark   # default 70% stop using disk
        )

### Actual behavior
rsyslog only supports single certificate for DefaultNetstreamDriverCAFile=

### Steps to reproduce the behavior
change DefaultNetstreamDriverCAFile= to bundle of CA certificates e.g. also containing the required CA.

### Environment
# rsyslogd -v
rsyslogd 8.24.0-57.amzn2.1, compiled with:
        PLATFORM:                               x86_64-koji-linux-gnu
        PLATFORM (lsb_release -d):
        FEATURE_REGEXP:                         Yes
        GSSAPI Kerberos 5 support:              Yes
        FEATURE_DEBUG (debug build, slow code): No
        32bit Atomic operations supported:      Yes
        64bit Atomic operations supported:      Yes
        memory allocator:                       system default
        Runtime Instrumentation (slow code):    No
        uuid support:                           Yes
        Number of Bits in RainerScript integers: 64

# cat /etc/os-release
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"

**Comment by rgerhards** [comment]
The version you are using is very old and no longer supported by the community. More current versions support what you need (there was a lot of work on TLS in recent years).

The rsyslog project provides packages for current versions: https://www.rsyslog.com/downloads/download-other/

If you insist on using an outdated version, you can also contact your distro to backport all relevant patches (hint: many, many).

**Comment by diepes** [comment]
Thanks @rgerhards , i didn't think to look past the latest version in the AWS distro.
Will upgrade to the latest and greatest version.
