### ISSUE TITLE
rsyslogd: Rsyslog with TLS connection error : connect to node3.example.com:514: Connection refused [v8.2206.0.c74f5c8523ef try https://www.rsyslog.com/e/2027 ]

### ISSUE THREAD

**Issue by sachusachin622** [rsyslog/rsyslog#4874]
Hi,
I am trying to do rsyslog with TLS connection with a remote server.
I am able to run rsyslog server with TLS successfully.
But in the Rsyslog client side I am getting certificates loading and reading errors.

Rsyslog-server-configuration:
administrator@ubuntu-2:~$ cat /etc/rsyslog.d/logserver.conf 
$DefaultNetstreamDriver gtls

$DefaultNetstreamDriverCAFile /etc/rsyslog/ca.pem
$DefaultNetstreamDriverCertFile /etc/rsyslog/rslserver-cert.pem
$DefaultNetstreamDriverKeyFile /etc/rsyslog/rslserver-key.pem

$ModLoad imtcp

$InputTCPServerStreamDriverAuthMode anon
$InputTCPServerStreamDriverMode 1 # run driver in TLS-only mode

$ActionSendStreamDriverAuthMode x509/name
$ActionSendStreamDriverPermittedPeer dhcp-blr-kmgm-blk2-4fl-6fl-client-ip.in.oracle.com
$ActionSendStreamDriverMode 1 # run driver in TLS-only mode

$InputTCPServerRun 10514

# Increase the amount of open files rsyslog is allowed, which includes open tcp sockets
# This is important if there are many clients.
# http://www.rsyslog.com/doc/rsconf1_maxopenfiles.html
$MaxOpenFiles 2048
administrator@ubuntu-2:~$ 

Rsyslog-client-configuration:
administrator@ubutnu:~/rsyslog-certificates$ cat /etc/rsyslog.d/log-client.conf
$DefaultNetstreamDriver gtls

$DefaultNetstreamDriverCAFile /home/administrator/RSYSLOG-CERTS/ca.pem
$DefaultNetstreamDriverCertFile /home/administrator/RSYSLOG-CERTS/rslclient-cert.pem
$DefaultNetstreamDriverKeyFile /home/administrator/RSYSLOG-CERTS/rslclient-key.pem

$ActionSendStreamDriverPermittedPeer dhcp-blr-kmgm-blk2-4fl-6fl-remote-ip.in.oracle.com 
$ActionSendStreamDriverMode 1 # run driver in TLS-only mode
$ActionSendStreamDriverAuthMode x509/name

*.* @@<remote-ip>:10514
administrator@ubuntu:~/rsyslog-certificates$ 

Getting Error logs on the client side.
/var/log/rsyslog
May 18 13:14:52 Ubuntu rsyslogd: rsyslogd's groupid changed to 104
May 18 13:14:52 Ubuntu rsyslogd: rsyslogd's userid changed to 101
May 18 13:14:52 Ubuntu rsyslogd: [origin software="rsyslogd" swVersion="8.2206.0.c74f5c8523ef" x-pid="8898" x-info="https://www.rsyslog.com"] start
May 18 13:14:54 Ubuntu rsyslogd: error reading file - a common cause is that the file  does not exist [v8.2206.0.c74f5c8523ef try https://www.rsyslog.com/e/2078 ]
May 18 13:14:54 Ubuntu rsyslogd: error adding our certificate. GnuTLS error -64, message: 'Error while reading file.', key: '/etc/rsyslog/rslclient-key.pem', cert: '/etc/rsyslog/rslclient-cert.pem' [v8.2206.0.c74f5c8523ef try https://www.rsyslog.com/e/2078 ]
May 18 13:14:54 Ubuntu rsyslogd: action 'action-11-builtin:omfwd' suspended (module 'builtin:omfwd'), retry 0. There should be messages before this one giving the reason for suspension. [v8.2206.0.c74f5c8523ef try https://www.rsyslog.com/e/2007 ]
May 18 13:14:55 Ubuntu rsyslogd: error reading file - a common cause is that the file  does not exist [v8.2206.0.c74f5c8523ef try https://www.rsyslog.com/e/2078 ]
May 18 13:14:55 Ubuntu rsyslogd: error adding our certificate. GnuTLS error -64, message: 'Error while reading file.', key: '/etc/rsyslog/rslclient-key.pem', cert: '/etc/rsyslog/rslclient-cert.pem' [v8.2206.0.c74f5c8523ef try https://www.rsyslog.com/e/2078 ]
May 18 13:14:55 Ubuntu rsyslogd: action 'action-11-builtin:omfwd' suspended (module 'builtin:omfwd'), next retry is Wed May 18 13:15:25 2022, retry nbr 0. There should be messages before this one giving the reason for suspension. [v8.2206.0.c74f5c8523ef try https://www.rsyslog.com/e/2007 ]
May 18 13:15:00 Ubuntu rsyslogd: error reading file - a common cause is that the file  does not exist [v8.2206.0.c74f5c8523ef try https://www.rsyslog.com/e/2078 ]
May 18 13:15:00 Ubuntu rsyslogd: error adding our certificate. GnuTLS error -64, message: 'Error while reading file.', key: '/etc/rsyslog/rslclient-key.pem', cert: '/etc/rsyslog/rslclient-cert.pem' [v8.2206.0.c74f5c8523ef try https://www.rsyslog.com/e/2078 ]
May 18 13:15:00 Ubuntu rsyslogd: action 'action-11-builtin:omfwd' suspended (module 'builtin:omfwd'), retry 1. There should be messages before this one giving the reason for suspension. [v8.2206.0.c74f5c8523ef try https://www.rsyslog.com/e/2007 ]
May 18 13:15:05 Ubuntu rsyslogd: error reading file - a common cause is that the file  does not exist [v8.2206.0.c74f5c8523ef try https://www.rsyslog.com/e/2078 ]
May 18 13:15:05 Ubuntu rsyslogd: error adding our certificate. GnuTLS error -64, message: 'Error while reading file.', key: '/etc/rsyslog/rslclient-key.pem', cert: '/etc/rsyslog/rslclient-cert.pem' [v8.2206.0.c74f5c8523ef try https://www.rsyslog.com/e/2078 ]

Please help me to fix this issue if anything i missed.
Thanks and Regards,
Sachin

**Comment by alorbach** [comment]
From the error message it looks like that rsyslog cannot read your certificate files: 

> $DefaultNetstreamDriverCAFile /home/administrator/RSYSLOG-CERTS/ca.pem
> $DefaultNetstreamDriverCertFile /home/administrator/RSYSLOG-CERTS/node3-cert.pem
> $DefaultNetstreamDriverKeyFile /home/administrator/RSYSLOG-CERTS/node3-key.pem

Can you verify that rsyslog has read access to those files and they are valid certificates?

**Comment by sachusachin622** [comment]
Hi,
I used openssl s_client and s_server command to verify my certificates, My certificates are proper.
Now i changed to other paths 
$DefaultNetstreamDriverCAFile /etc/rsyslog/ca.pem
$DefaultNetstreamDriverCertFile /etc/rsyslog/rslclient-cert.pem
$DefaultNetstreamDriverKeyFile /etc/rsyslog/rslclient-key.pem

Here is the certificates permissions:
administrator@ubuntu:~/$ ls -lart 
drwxr-xr-x 148 root root 12288 May 18 11:13 ..
-rw-r--r--   1 root root  1391 May 18 11:13 ca.pem
-rw-------   1 root root  2723 May 18 11:13 request.pem
-rw-r--r--   1 root root  1545 May 18 11:13 rslclient-cert.pem
-rw-------   1 root root  1679 May 18 11:13 rslclient-key.pem
drwxr-xr-x   2 root root  4096 May 18 11:13 .
administrator@ubuntu:~/$ 

still am getting May 18 13:15:05 Ubuntu rsyslogd: error reading file - a common cause is that the file does not exist [v8.2206.0.c74f5c8523ef try https://www.rsyslog.com/e/2078 ]
May 18 13:15:05 Ubuntu rsyslogd: error adding our certificate. GnuTLS error -64, message: 'Error while reading file.', key: '/etc/rsyslog/rslclient-key.pem', cert: '/etc/rsyslog/rslclient-cert.pem' [v8.2206.0.c74f5c8523ef try https://www.rsyslog.com/e/2078 ]

Thanks,
Sachin

**Comment by rgerhards** [comment]
Sounds like selinux...

**Comment by sachusachin622** [comment]
Hi,
In my ubuntu machine selinux status disabled.
administrator@ubuntu:~/rsyslog-certificates$ sestatus
SELinux status:                 disabled
administrator@ubuntu:~/rsyslog-certificates$

Thanks

**Comment by davidelang** [comment]
I think Ubuntu uses AppArmor instead of SELinux

David Lang

**Comment by sachusachin622** [comment]
Hi,
I found out the Root cause, changed the permission of key file. It got worked.

Thanks
