### ISSUE TITLE
Expression Syntax To Discard A Message

### ISSUE THREAD

**Issue by lospinoj** [rsyslog/rsyslog#4877]
### Expected behavior
We have a single filter file and the "Filter In" statements seem to be working, but we can't seem to get the "Filter Out" statements to work.

#Cisco Meraki
##Filter in
if re_match($rawmsg,"[[:digit:]]{10}.[[:digit:]]{6,9}[[:space:]].*_RTR.*[[:space:]](urls|ids-alerts|events|l7_firewall)") then @@127.0.0.1:22033;meraki
& stop

##Filter Out
if re_match($rawmsg,"[[:digit:]]{10}.[[:digit:]]{6,9}[[:space:]].*_RTR.*[[:space:]](flows|ip_flow_start|ip_flow_end)") then stop

#The purpose of this filter is to catch anything that slips by all other filters.
if re_match($rawmsg,".") then @127.0.0.1:25224
& stop

### Actual behavior
The second filter should be discarding messages but we see that these messages are being capture by the last filter.

### Steps to reproduce the behavior
Should be easy to produce or please help us to understand the proper syntax. We've searched hi and low and can't seem to find the solution.

### Environment
[jlospinoso@njiplsyslog01 ~]$ rsyslogd -v
rsyslogd  8.1911.0-7.el8 (aka 2019.11) compiled with:
        PLATFORM:                               x86_64-redhat-linux-gnu
        PLATFORM (lsb_release -d):
        FEATURE_REGEXP:                         Yes
        GSSAPI Kerberos 5 support:              Yes
        FEATURE_DEBUG (debug build, slow code): No
        32bit Atomic operations supported:      Yes
        64bit Atomic operations supported:      Yes
        memory allocator:                       system default
        Runtime Instrumentation (slow code):    No
        uuid support:                           Yes
        systemd support:                        Yes
        Config file:                            /etc/rsyslog.conf
        PID file:                               /var/run/rsyslogd.pid
        Number of Bits in RainerScript integers: 64

See https://www.rsyslog.com for more information.

**Comment by davidelang** [comment]
that should work, but it's clearer to use the syntax

if re_match($rawmsg,".") then {
   @127.0.0.1:25224
   stop
}

I expect that the message isn't quite what you think it is.

write the message out with the template RSYSLOG_DebugFormat and post an example 
of a message that you expect the pattern to match

also note that regular expressions are expensive compared to other tests.

David Lang

**Comment by lospinoj** [comment]
Hello David,

We are trying to understand the expression syntax required to discard a message, then stop processing.

if re_match($rawmsg,".") then {
“discard the message”
stop
}

Thanks,

Jeff

**Comment by rgerhards** [comment]
You discard it, when you stop processing. Because then nothing else can
happen to it, as it's processing is stopped.

HTH
Rainer

Sent from phone, thus brief.

Jeff LoSpinoso ***@***.***> schrieb am Fr., 20. Mai 2022,
14:13:

**Comment by lospinoj** [comment]
Thanks!

**Comment by lospinoj** [comment]
Hello Again,

With this syntax we would be send any message that has “cat” to @127.0.0.1:25224 and then stop processing.

if re_match($rawmsg,"cat") then {
@127.0.0.1:25224
stop
}

But what we want to do is discard all messages that have “cat” and then stop processing?

We have tried many variations of what’s shown below but nothing seems to work.

if re_match($rawmsg,"cat") then {
stop
}

Thank you kindly,

Jeff

**Comment by davidelang** [comment]
no problem, that's the most common cause, and why the response is to suggest the 
debugformat.

David Lang

**Comment by davidelang** [comment]
we would need to see the full config and a sample message.

It's very possible that you are doing this after the message has already been 
processed by other statements.

start rsyslog with -o /path/to/file and the file will contain the combined 
config file (including all includes) as rsyslog sees it.

David Lang
