### ISSUE TITLE
Rsyslog log rotation is not working.

### ISSUE THREAD

**Issue by sachusachin622** [rsyslog/rsyslog#4879]
Hi ,

I am running rsyslog-master on ARM V7 based machine, trying to do rsyslog log rotation.

### Expected behavior
Log rotation should work as mentioned in rsyslog log rotation link https://www.rsyslog.com/doc/master/tutorials/log_rotation_fix_size.html.

### Actual behavior
rsyslog log rotation is not working.
**here its my configuration for rsyslog**
_$outchannel log_rotation,/tmp/all_rsyslog_log.log, 1024,/tmp/log_rotation_script
*.* :omfile:$log_rotation

_# cat /tmp/log_rotation_script 
mv -f /tmp/all_rsyslog_log.log /tmp/all_rsyslog_log.log.1
#__ 

**Note:**
1. when i configure like below instead of log_rotation_script.  rm is working fine in rsyslog.conf file (deleting that log file)
_$outchannel log_rotation,/tmp/all_rsyslog_log.log, 1048576,rm /tmp/all_rsyslog_log.log
*.* :omfile:$log_rotation_

2. when i configure mv -f of log file like below instead of log_rotation_script.  mv is not working in rsyslog.conf file.
_$outchannel log_rotation,/tmp/all_rsyslog_log.log, 1048576,mv -f /tmp/all_rsyslog_log.log /tmp/all_rsyslog_log.log.1
*.* :omfile:$log_rotation_

3. when i configure cp of log file like below instead of log_rotation_script.  cp is not working in rsyslog.conf file.
_$outchannel log_rotation,/tmp/all_rsyslog_log.log, 1048576, cp /tmp/all_rsyslog_log.log /tmp/all_rsyslog_log.log.1
*.* :omfile:$log_rotation_

**Only rm is working but mv and cp is not working in rsyslog.conf file.**

### Environment
- rsyslog version: 8.2206.0.master (aka 2022.06)
	           
Please help to provide some inputs if anything i missed, to resolve this issue.

Thanks,
Sachin

**Comment by rgerhards** [comment]
you may want to create a debug log of cases that do not work. But may I ask why calling the script is problematic? This is actually what we assumed everyone would do.

**Comment by sachusachin622** [comment]
Hi rgerhards,
I am not sure why the script execution is not happening in this particular case. In  ubuntu its working but in ARM v7 based machine it is not working.
I am new to rsyslog code base could you please point me to the piece of code which is executing the script, upon receiving the notification that the file limit is exhausted, i can continue my debugging from there.
Any other tips that you might have will also be much appreciated.
Thanks,
Sachin

**Comment by rgerhards** [comment]
oh, you also want to check ./runtime/srutils.c, which does the actual execution in execProg().

**Comment by sachusachin622** [comment]
Thanks for your update.
