### ISSUE TITLE
rsyslog does not track if file is deleted and creates new

### ISSUE THREAD

**Issue by dhruvanand96** [rsyslog/rsyslog#4880]
it keeps pointing to the same file instead of the creating a new file 

root@ubuntu:/opt/lavelle/var/data/logs/local# lsof -p `pgrep rsyslog` | grep all-
rsyslogd 1142 syslog   21w   REG                8,1    42203     138065 /opt/lavelle/var/data/logs/local/all-986a1800.log.gz (deleted)
rsyslogd 1142 syslog   22w   REG                8,1    40145     138060 /opt/lavelle/var/data/logs/local/all-986a2000.log.gz (deleted)

**Comment by rgerhards** [comment]
sorry, but I do not understand what you mean. Not at all. Can you please elaborate. There are  questions/guidelines when you open a new issue. Please answer them.

**Comment by dhruvanand96** [comment]
### Expected behavior
using omfile to store messages in .gz file if the we use gunzip to extract the data then a new same file should be created for storing new messages

### Actual behavior
currently it is pointing to the old deleted file only
root@ubuntu:/opt/lavelle/var/data/logs/local# lsof -p pgrep rsyslog | grep all-
rsyslogd 1142 syslog 21w REG 8,1 42203 138065 /opt/lavelle/var/data/logs/local/all-986a1800.log.gz (deleted)
rsyslogd 1142 syslog 22w REG 8,1 40145 138060 /opt/lavelle/var/data/logs/local/all-986a2000.log.gz (deleted)

### Steps to reproduce the behavior
1. store messages in .gz file 
2. read the file using gunzip 
3. you will see new messages are also being written to deleted file only

### Environment
- rsyslogd: version 8.2104.0, config validation run (level 1), master config /etc/rsyslog.conf
- Distributor ID: Ubuntu
   Description:    Ubuntu 14.04.6 LTS
  Release:        14.04
  Codename:       trusty

**Comment by davidelang** [comment]
so if I am understanding you:

you are manually running gunzip on the file that rsyslog has open, and gunzip is 
deleting that file, but since rsyslog still has it open, it keeps writing to it.

This is working as expected. There is no easy way to determine that a file that 
you have open has no filename on unix (many filenames can point at one file)

if you are manually uncompressing a file that rsyslog is writing to, you should 
use the flag to not remove the original.

In addition, when rsyslog is writing a compressed file, there is some amount of 
data that is buffered, so if you only look at the file on disk, you will end up 
missing some data.

You should rotate the file and send a HUP to rsyslog to have it close the file 
and open a new one (and give it some time to do so) before you consider the old 
one safe to manipulate.

David Lang

**Comment by dhruvanand96** [comment]
> so if I am understanding you: you are manually running gunzip on the file that rsyslog has open, and gunzip is deleting that file, but since rsyslog still has it open, it keeps writing to it. This is working as expected. There is no easy way to determine that a file that you have open has no filename on unix (many filenames can point at one file) if you are manually uncompressing a file that rsyslog is writing to, you should use the flag to not remove the original. In addition, when rsyslog is writing a compressed file, there is some amount of data that is buffered, so if you only look at the file on disk, you will end up missing some data. You should rotate the file and send a HUP to rsyslog to have it close the file and open a new one (and give it some time to do so) before you consider the old one safe to manipulate. David Lang On Wed, 25 May 2022, Dhruv Anand wrote:
> […](#)
> ### Expected behavior using omfile to store messages in .gz file if the we use gunzip to extract the data then a new same file should be created for storing new messages ### Actual behavior currently it is pointing to the old deleted file only ***@***.***:/opt/lavelle/var/data/logs/local# lsof -p pgrep rsyslog | grep all- rsyslogd 1142 syslog 21w REG 8,1 42203 138065 /opt/lavelle/var/data/logs/local/all-986a1800.log.gz (deleted) rsyslogd 1142 syslog 22w REG 8,1 40145 138060 /opt/lavelle/var/data/logs/local/all-986a2000.log.gz (deleted) ### Steps to reproduce the behavior 1. store messages in .gz file 2. read the file using gunzip 3. you will see new messages are also being written to deleted file only ### Environment - rsyslogd: version 8.2104.0, config validation run (level 1), master config /etc/rsyslog.conf - Distributor ID: Ubuntu Description: Ubuntu 14.04.6 LTS Release: 14.04 Codename: trusty

thanks i also thought about the keep option it seemed to working will also look into HUP implementation
