### ISSUE TITLE
Rsyslog Support For "\" Escape Character on RHEL 8.x

### ISSUE THREAD

**Issue by lospinoj** [rsyslog/rsyslog#4882]
### Expected behavior
The filtering shown below should work. Both of these filters  work in rsyslog.com/regex against the sample lines below them. Rsyslog/regex seems to correctly process the "\\" escape character.

#Filter #1 - Palo Alto Networks
if re_match($rawmsg,"CEF:[[:digit:]]*\\|Palo[[:space:]]Alto[[:space:]]Networks\\|PAN-OS\\|") then @@127.0.0.1:25226
& stop

#Sample
#Msg: May  6 11:26:07 NJIPPAIPS01.tcphq.tcpcorp.local.com CEF:0|Palo Alto Networks|PAN-OS|8.1.16|login|USERID|1|rt=M...

#Filter #2 - Cisco Meraki
if re_match($rawmsg,"TCP[[:digit:]]{4}_RTR[[:space:]](flows|urls|ids-alerts|events|ip_flow_start|ip_flow_end)") then @@127.0.0.1:22033;meraki
& stop

#Sample message
#1649792977.908683742 TCP0987_RTR ip_flow_start src=10.106.39.21 dst=34.98.77.231 protocol=tcp...

### Actual behavior
Rsyslog on RHEL 8.x does not seem to fully support the "\\", the filter itself actually works but causes any subsequent filters to not load.  

### Steps to reproduce the behavior
Just use any a "\\" esacape in POSIX ERE expression in the re_match() function and any filters below that filter will fail to load. If you run the rsyslogd -N1 command it will complain about the line that has the "\\".

### Environment
rsyslogd -v
rsyslogd 8.1911.0-7.el8 (aka 2019.11) compiled with:
PLATFORM: x86_64-redhat-linux-gnu
PLATFORM (lsb_release -d):
FEATURE_REGEXP: Yes
GSSAPI Kerberos 5 support: Yes
FEATURE_DEBUG (debug build, slow code): No
32bit Atomic operations supported: Yes
64bit Atomic operations supported: Yes
memory allocator: system default
Runtime Instrumentation (slow code): No
uuid support: Yes
systemd support: Yes
Config file: /etc/rsyslog.conf
PID file: /var/run/rsyslogd.pid
Number of Bits in RainerScript integers: 64

- rsyslog version: 
- platform: 
- for configuration questions/issues, include rsyslog.conf and included config files

**Comment by rgerhards** [comment]
It's not clear from your message, it looks like \ is missing somewhere.

In any case, please remeber that \ is an escape for an additional character inside a string, e.g. `"\""` results in the string `"`. As such, if you need the backslash inside a constant, it must be escaped as well, e.g. `"\\""` will result in the string `\"`.

**Comment by lospinoj** [comment]
Hello Sir,

Seems that the comments are markdown and a backslash must be escaped, I've corrected that issue explanation but am also uploading a screen shot with comments.

Your Help Is Most Appreciated,

Jeff

![image](https://user-images.githubusercontent.com/43653987/170783657-ff6ac33a-f160-4e59-9c74-277c0a98388e.png)

**Comment by rgerhards** [comment]
Same with rsyslog, as I said 😉

**Comment by lospinoj** [comment]
Please forgive my ignorance, isn't a single backslash "\\" supposed to function as the POSIX ERE escape character, so we can turn off metacharacters and enable other functions like "\\d" means a single digit and so forth? If all backslashes must be "escaped" with a "backslash" that means rsyslog is not able to interpret the a backslash as an escape character, correct?

At the very least this behavior is not consistent with www.rsyslog.com/regex, please see the screen shot below. Using a "\\|" in a filter should and does in fact match on a literal "|", however we have found that it causes subsequent filters to fail to load. Rsyslog -N1 will also report errors.

![image](https://user-images.githubusercontent.com/43653987/170879197-4374e6da-ea22-4e10-aad9-ecfee8c7c388.png)

**Comment by rgerhards** [comment]
The regex tool can need an enhancement to craft a proper string.

- In rsyslog strings, you can escape special characters by backslash. This is needed, e.g. for `"`.
- you specify a **string** for the regex inside the config (not the regex, but a string specifying it)
- if you give in config `"a\["` the regex becomes `a[` after rsyslog has parsed the string
- so a backslash is a special character inside a string.
- special characters are escaped by backslash
- if you want to have backslash in your regex, you need to escape it inside the string `"a\\[`
- this becomes the regex `a\[` after the config string param has been parsed

This is just what github does as well as all programming and script languages (when the use backslash for escaping)

**Comment by lospinoj** [comment]
Got it, thank you Sir.
