### ISSUE TITLE
Is there any way to forward recieved to logs to a internal custom writen service which is trying to listen from a server

### ISSUE THREAD

**Issue by dhruvanand96** [rsyslog/rsyslog#4887]
below is my configuration i am trying to make rsyslog as a server or host and send logs to my listener
  action(                                                                                                         
240                 type="omfwd"                                                                                                                                                                                              
  1                 name="publish_user"                                                                                                                                                              
  2                 template="json_body"                                                                                                                                                                       
  3                 protocol="tcp"                                                                                                                                                
  4                 target="127.0.0.1"                                                                                                                                                            
  5                 port="2002"                                                                                                                                            
  6                 rebindinterval="5"                                                                                                                                                
  7               ) 

is this even supported or i am missing something

**Comment by dhruvanand96** [comment]
this part i got rsyslog only supports server to server

**Comment by davidelang** [comment]
that would send the messages to port 2002/tcp on localhost with the format 
defined in json_body.

not knowing what that template is, or what you have listening, it's impossible 
to say what will happen when you try

do you need linefeeds? do you escape things properly? (and while the template is 
named json_body, is it even json?)

too many unknowns for us to begin to guess.

David Lang
