### ISSUE TITLE
mmnormalize_{variable,tokenized,regex}.sh tests are failing

### ISSUE THREAD

**Issue by Whissi** [rsyslog/rsyslog#489]
The
- mmnormalize_variable.sh
- mmnormalize_tokenized.sh
- mmnormalize_regex.sh

tests are failing:

```
FAIL: mmnormalize_variable.sh
=============================

===============================================================================
[mmnormalize_variable.sh]: basic test for mmnormalize module variable-support
rsyslogd started with pid  25366
starting run 1
Sending file './testsuites/date_time_msg' 1 times.
^M00000001 kb sent
runtime: 0.000
End of tcpflood Run
doing shutdown
imdiag[13500]: mainqueue empty
wait on shutdown
content-check failed
FAIL mmnormalize_variable.sh (exit status: 1)

FAIL: mmnormalize_tokenized.sh
==============================

===============================================================================
[mmnormalize_tokenized.sh]: test for mmnormalize tokenized field_type
rsyslogd started with pid  25409
starting run 1
Sending file './testsuites/tokenized_input' 1 times.
^M00000001 kb sent
runtime: 0.000
End of tcpflood Run
doing shutdown
imdiag[13500]: mainqueue empty
wait on shutdown
content-check failed
FAIL mmnormalize_tokenized.sh (exit status: 1)

FAIL: mmnormalize_regex.sh
==========================

===============================================================================
[mmnormalize_regex.sh]: test for mmnormalize regex field_type
rsyslogd started with pid  25566
starting run 1
Sending file './testsuites/regex_input' 1 times.
^M00000001 kb sent
runtime: 0.000
End of tcpflood Run
doing shutdown
imdiag[13500]: mainqueue empty
wait on shutdown
content-check failed
FAIL mmnormalize_regex.sh (exit status: 1)
```

Confirmed against rsyslog-8.12.0 release tarball and git at 1e26405031390003853f6c11e7221d534dc3a0dd.

**Comment by Whissi** [comment]
OK, this is a problem which only happens with *liblognorm-1.1.2*. It is working fine with *liblognorm-1.1.1*.

Do we need to mask *liblognorm-1.1.2* for rsyslog or does the test requires an update to work with *liblognorm-1.1.2*?

**Comment by alorbach** [comment]
I will look into this.

**Comment by alorbach** [comment]
Are you certain these tests worked with liblognorm-1.1.1? 
I also posted on the mailinglist that at least one of the configs does not work.

**Comment by Whissi** [comment]
100% sure. I just verified again.

If you could bring back 1.1.1 for precise in the ppa Travis would pass, too.

**Comment by rgerhards** [comment]
I think this problem is related to this issue here: https://github.com/rsyslog/liblognorm/issues/57

Maybe the tests in rsyslog also just need to be updated, maybe there indeed was a problem that neither @janmejay nor me noticed after the initial discussion.

**Comment by rgerhards** [comment]
I have probably traced the problem down to the root cause: the testbench generates rulebases with incomplete lines (\n missing). As it looks, the new liblognorm code does not accept such incomplete lines, but the old one seemed to process them. I'll dig into it some more, but thought I share the news (I need to continue tomorrow).

**Comment by rgerhards** [comment]
These tests (plus two not mentioned) now work with the new version of liblognorm, with the exception of the _regex test. It looks like this test does something wrong, the root cause is that it tests regex when it is not supported. Will look into it, but may wait until @janmejay has time to dig further.

**Comment by janmejay** [comment]
Rainer, I'm buried in work add of now, I may take at least a few weeks
before I can look at it. I'm so sorry!

--
Regards,
Janmejay

PS: Please blame the typos in this mail on my phone's uncivilized soft
keyboard sporting it's not-so-smart-assist technology.

**Comment by rgerhards** [comment]
Sent from phone, thus brief.
Am 24.08.2015 19:34 schrieb "Janmejay Singh" <notifications@github.com>:
>
> Rainer, I'm buried in work add of now, I may take at least a few weeks
> before I can look at it. I'm so sorry!

No Problem. If i don't see it quickly enough, I'll comment out the test.
Regex should not be used by regular users anyways, so it's not a big deal
IMHO.

Rainer
>
> --
> Regards,
> Janmejay
>
> PS: Please blame the typos in this mail on my phone's uncivilized soft
> keyboard sporting it's not-so-smart-assist technology.
>
> On Aug 24, 2015 2:58 PM, "Rainer Gerhards" <notifications@github.com>
wrote:
>
> > These tests (plus two not mentioned) now work with the new version of
> > liblognorm, with the exception of the _regex test. It looks like this
test
> > does something wrong, the root cause is that it tests regex when it is
not

**Comment by rgerhards** [comment]
@janmejay as it looks, at least in travis the regex test works now. I still have problems in one environment, may be environment-induced. I would appreciate if you could look into the issue when you have time later. Note that I am not yet sure if we should support regex in v2 natively, so this may become a non-issue within the next few weeks.

**Comment by janmejay** [comment]
I think its valuable to support regexp for odd unforeseen cases. I'll
definitely look at it once I have a little breathing room.

On Tue, Aug 25, 2015 at 1:32 PM, Rainer Gerhards <notifications@github.com>
wrote:

> @janmejay <https://github.com/janmejay> as it looks, at least in travis
> the regex test works now. I still have problems in one environment, may be
> environment-induced. I would appreciate if you could look into the issue
> when you have time later. Note that I am not yet sure if we should support
> regex in v2 natively, so this may become a non-issue within the next few
> weeks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rsyslog/rsyslog/issues/489#issuecomment-134515741>.
>



-- 
Regards,
Janmejay
http://codehunk.wordpress.com

**Comment by rgerhards** [comment]
@janmejay I opened an issue tracker where we can discuss the need to re-introduce regex: https://github.com/rsyslog/liblognorm/issues/143

**Comment by janmejay** [comment]
Sounds good.

On Thu, Aug 27, 2015 at 12:25 PM, Rainer Gerhards <notifications@github.com>
wrote:

> @janmejay <https://github.com/janmejay> I opened an issue tracker where
> we can discuss the need to re-introduce regex: rsyslog/liblognorm#143
> <https://github.com/rsyslog/liblognorm/issues/143>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rsyslog/rsyslog/issues/489#issuecomment-135315292>.
>



-- 
Regards,
Janmejay
http://codehunk.wordpress.com

**Comment by Whissi** [comment]
Short update: We disabled *PCRE* in *liblognorm-1.1.2* like suggested in rsyslog/liblognorm#143 and cherry-picked https://github.com/rgerhards/liblognorm/commit/4b35ca1e6fff50f47eb5419b879b287f49dcf1d8 which fixed the issue for the remaining two tests *mmnormalize_variable.sh* and *mmnormalize_tokenized.sh*.

Now that rsyslog-8.13.0 finally passed the test suite on all our supported plattforms we added it to the tree.

Not sure if this issue should stay open until rsyslog requirements for liblognorm are bumped to require a version with the patch included or not so people experiencing the same problem will find it (and a solution).

**Comment by rgerhards** [comment]
As it looks, this is solved. I do also see no related failures in our CI runs. If the problem re-occurs, let me know and I can re-open.
