### ISSUE TITLE
cache timed-out dns quries at least for a short while

### ISSUE THREAD

**Issue by rgerhards** [rsyslog/rsyslog#49]
The intent is to mitigate the slowdown caused by frequent cache misses. The entry should be cached as "does not resolve" with a moderate time to live. Probably it makes sense to extend this time when multiple resolves fail (just like is done in action suspension).

**Comment by trixpan** [comment]
should this cache match the NXDOMAIN TTL? 

the SOA attribute is quite clear about what the TTL of a NXDOMAIN should be:

example.com.    IN    SOA   ns.example.com. hostmaster.example.com. (
                              2003080800 ; sn = serial number
                              172800     ; ref = refresh = 2d
                              900        ; ret = update retry = 15m
                              1209600    ; ex = expiry = 2w
                              3600       ; nx = nxdomain ttl = 1h
                              )

**Comment by T4cC0re** [comment]
I agree, but the TTL should be configurable, if possible.

**Comment by simmel** [comment]
Well, preferably use the TTL that DNS gives us IMO.

**Comment by rgerhards** [comment]
I will initially implement this with a configurable timeout, not DNS TTL. The latter is more work to do and would not fit in the time I have. We probably should open a new issue tracker for this.

**Comment by davidelang** [comment]
On Fri, 12 Apr 2019, Rainer Gerhards wrote:

> I will initially implement this with a configurable timeout, not DNS TTL. The 
> latter is more work to do and would not fit in the time I have. We probably 
> should open a new issue tracker for this.

not all name resolution comes from DNS, gethostbyname() and equivalent ask the 
system to resolve the name, but don't get info back on how the system gets the 
name.

so a configurable timeout is a good first step, I would say that the ability to 
flush the cach (or possibly flush items in the cache older than X) would be the 
next step. Initially this could be handled like a lookup table reload, but is 
yet another thing that I think helps justify creating a socket to issue commands 
to the rsyslog core while running.

David Lang

**Comment by simmel** [comment]
Not to hijack this thread but it's not possible to make rsyslog never 
cache DNS answers, is it? Maybe that can be included in the first step 
too?

**Comment by davidelang** [comment]
On Fri, 12 Apr 2019, Simon Lundström wrote:

> Not to hijack this thread but it's not possible to make rsyslog never
> cache DNS answers, is it? Maybe that can be included in the first step
> too?

having to do a name lookup on every log message would cripple rsyslog 
performance, and would also probably overload your DNS server. Some amount of 
caching is needed.

David Lang

**Comment by rgerhards** [comment]
> having to do a name lookup on every log message would cripple rsyslog performance, and would also probably overload your DNS server. Some amount of caching is needed.

never the less, if you set the default TTL to 0, nothing will ever be cached ;-)

**Comment by rgerhards** [comment]
> so a configurable timeout is a good first step, I would say that the ability to flush the cach (or possibly flush items in the cache older than X) would be the next step. Initially this could be handled like a lookup table reload, but is yet another thing that I think helps justify creating a socket to issue commands to the rsyslog core while running.

Do you think that an explicit flush is necessary when the cache can be enabled to discard entries older than xx seconds? I see some very few border cases where this may be needed. But I think these few cases could be handled by a restart. I think about changing an IP range in the internal setup.

**Comment by davidelang** [comment]
On Fri, 12 Apr 2019, Rainer Gerhards wrote:

> Do you think that an explicit flush is necessary when the cache can be enabled 
> to discard entries older than xx seconds? I see some very few border cases 
> where this may be needed. But I think these few cases could be handled by a 
> restart. I think about changing an IP range in the internal setup.

I thought you were talking about flusing every X minutes, not flushing all 
entries over X minutes old.

If you do the latter, how frequently do you check for old entries?

It would be a good idea to have pstats on this cache, eventually with an option 
to indicate how long it waits for lookups when there is a cache miss.

David Lang

**Comment by rgerhards** [comment]
@davidelang It will work like DNS TTL: when a lookup is requested, I check if the configured TTL expires. If so, entry is discarded and re-queried. So no periodic checks, just on demand.

**Comment by rgerhards** [comment]
Just to be ultra-clear: TTL is on the scope of a **single** host entry. It is **not** on cache-global scope.

If we decide we need to query DNS (where possible), this enables me to use the same code for DNS-provided entries. All others will still use the configured default TTL. I currently set the default to 24hrs.

**Comment by simmel** [comment]
> On Fri, 12 Apr 2019, Simon Lundström wrote: Not to hijack this thread but it's not possible to make rsyslog never cache DNS answers, is it? Maybe that can be included in the first step too?
> having to do a name lookup on every log message would cripple rsyslog performance, and would also probably overload your DNS server. Some amount of caching is needed.

Well, a local caching resolver would solve that problem. Having DNS cache in multiple layers only makes it harder to debug TBH.

But making it configurable with a sane default is crucial!

**Comment by rgerhards** [comment]
> Well, a local caching resolver would solve that problem. Having DNS cache in multiple layers only makes it harder to debug TBH.

nevertheless, this was a top requested performance enhancement.

But I realize something important: rsyslog's DNS cache is a reverse lookup cache (it takes a socket structure and returns the hostname). It is not used for forward-lookups. So some of the postings should probably go into a different issue. I didn't notice earlier, sorry...
