### ISSUE TITLE
rsyslog silenty discards any received messages for an action if "error starting up action queue" is encountered.

### ISSUE THREAD

**Issue by kortemik** [rsyslog/rsyslog#4902]
### Expected behavior
rsyslog determines that there is an "error starting up action queue" and shuts itself down to prevent any message loss. especially if ```$AbortOnUncleanConfig on``` is set.

### Actual behavior
rsyslog starts up and logs "error starting up action queue". It does not inform that an action is disabled and messages may be lost if no further actions are configured as message receptions is on.

### Steps to reproduce the behavior
reproduce a situation where "error starting up action queue" is encountered.
configure rsyslog with imrelp for reliable event reception and configure an action with disk queue for omrelp to ensure that delivery problems can be mitigated. try sending data in and see that it is nowhere to be found on the omrelp side.

### Environment
- rsyslog version: v8.2102.0
- platform: el7

code responsible for the behaviour
```
/* helper to activateActions, it activates a specific action.                                    
 */                                                                                              
DEFFUNC_llExecFunc(doActivateActions)                                                            
{                                                                                                
        rsRetVal localRet;                                                                       
        action_t * const pThis = (action_t*) pData;                                              
        localRet = qqueueStart(pThis->pQueue);                                                   
        if(localRet != RS_RET_OK) {                                                              
                LogError(0, localRet, "error starting up action queue");                         
                if(localRet == RS_RET_FILE_PREFIX_MISSING) {                                     
                        LogError(0, localRet, "file prefix (work directory?) "                   
                                        "is missing");                                           
                }                                                                                
                actionDisable(pThis);                                                            
        }                                                                                        
        DBGPRINTF("Action %s[%p]: queue %p started\n", modGetName(pThis->pMod),                  
                  pThis, pThis->pQueue);                                                         
        return RS_RET_OK; /* we ignore errors, we can not do anything either way */              
}    
```

**Comment by rgerhards** [comment]
Without special config, the behavior is intended: we consider it preferable to fail one action instead of all processing. This is the original spirit of (r)syslogd for over 30 years.

That said, I see this does not fit all use cases. Not sure if "abortOnUncleanConfig" should address this (after all the config is fine) or a separate param. But this functionality must be added.

**Comment by rgerhards** [comment]
@kortemik I have created https://github.com/rsyslog/rsyslog/pull/4904

CI is currently running, but manual tests look good. Doc is missing, but I will add either tomorrow or begin of week. 

I think you can already apply it. So I am a bit before mid-summer ;-)

**Comment by rgerhards** [comment]
After careful consideration and as we had error message, I do not think this was a bug. So I removed the "bug" label und treat it as "enhancement". Not that it really makes a difference, but just so that everybody knows I am juggling with the labels.

**Comment by kortemik** [comment]
@rgerhards Thank you very much, we will create builds for our end user. It was quite unfortunate to encounter this one. It totally makes sense to have this as default behaviour in case where for example rsyslog is picking up the kernel logging and logging to local disk and to remote location but when encountering in a relay configuration it's a different case ;(

**Comment by rgerhards** [comment]
As you know, we do only change defaults in very, very important cases. Even more so, I think most users will not expect rsyslog abort on a queue startup failure. For many users this will mean total loss of message. For enterprise users, I would expect they monitor the health logs, and so see the issue.

@davidelang what's your turn?

**Comment by davidelang** [comment]
what sorts of things can cause the queue failure? is it a matter of the disk 
portion of a DA queue failing? I am not understanding what could cause one of 
the memory queues to fail that wouldn't either be an out-of-memory situation or 
a config issue.

I tend to agree with not changing the default, ubt I need to understand the 
problem case better.

David Lang

**Comment by rgerhards** [comment]
The most important reason for this probably is not setting a working directory and using disk or disk-assisted queue. In that case, we try to write to  file system root (yes, `/`) and when privileges are dropped this does not work. All other cases are exotic border cases IMHO.

Traditionally (30+ yrs), (r)syslogd fails single actions if they do not work in favor of keeping the other active.

**Comment by rgerhards** [comment]
I forgot to mention: it's checked during startup. If a DA queue fails later on, the Disk part is dropped, just like you say.



> I tend to create two paths to send messages out, a normal queue and a high priority queue that is only used for rsyslog status messages (pstats typically) so that the status messages will get processed ASAP even if there is a flood of other messages that would cause delays in processing.

That would be quite a bit of a change. We already have a similiar thing with the "operating state file", where we could record such issues.

**Comment by rgerhards** [comment]
@davidelang I worded my initial description sloppy. This failure IMHO can only occur for pure disk queues. The rest is later in the process, but this is not where the patch applies.

**Comment by davidelang** [comment]
On Mon, 20 Jun 2022, Rainer Gerhards wrote:

>> I tend to create two paths to send messages out, a normal queue and a high priority queue that is only used for rsyslog status messages (pstats typically) so that the status messages will get processed ASAP even if there is a flood of other messages that would cause delays in processing.
>
> That would be quite a bit of a change. We already have a similiar thing with the "operating state file", where we could record such issues.

I create a second ruleset with a queue and direct the pstats output to that 
ruleset.

I need to sit down and make a set of reference configs with all the fun tricks 
that we can post as an example sometime (when I get the free time)

pstats has the option to write directly to a disk file, it may make sense to 
have an option that spits rsyslog internal errors to a file instead of (or in 
addition to) the normal stdout or log stream.

David Lang

**Comment by davidelang** [comment]
On Mon, 20 Jun 2022, Rainer Gerhards wrote:

> @davidelang I worded my initial description sloppy. This failure IMHO can only occur for pure disk queues. The rest is later in the process, but this is not where the patch applies.

When it's an error that could be detected reliably at startup time, then an 
option to error out makes sense.

That being said, anyone doing pure disk queues, please look at the performance 
impact, when I tested them (a long time ago now) I used a very expensive PCI SSD 
and was able to get ~1k messages/sec on a disk-only queue vs saturating gig-E 
@300k messages/sec with any other option.

David Lang

**Comment by rgerhards** [comment]
> I create a second ruleset with a queue and direct the pstats output to that ruleset.

Yeah, *with config* it's fairly simple to create that kind of things. I though you wanted to change the code so that we move certain messages to the top of the queue, *without config* involvement. That's another beast.

Regarding the operating state file: I just checked code. rsyslog internal messages are already written to it. So this is a kind of priority mechanism, if you want so.

All in all, I think it is OK to leave the PR as-is.
