### ISSUE TITLE
omelasticsearch unable to talk to opensearch 2.0 with bulkmode on

### ISSUE THREAD

**Issue by carljia999** [rsyslog/rsyslog#4908]
### Expected behavior
I use rsyslog omelasticsearch plugin to feed log to Opensearch 2.0. It works well when bulkmode is turned off. It's not practical to turn bulkmode off in production. So I expect it to work well when bulkmode is on.

### Actual behavior

The log data cannot be sent to opensearch when bulkmode is turned on, with error messages like below,

`{ "request": { "url": "https:\/\/localhost:9200\/_bulk", "postdata": "{\"index\":{\"_index\": \"special-2022.06.23\",\"_type\":\"_doc\"}}\n{\"time\":\"2022-06-23T16:25:36.266848+12:00\",\"timereceived\":\"2022-06-23T16:25:36.266848+12:00\",\"severity\":\"INFO\",\"tag\":\"systemd[1]\", \"msg\": \"Started System Logging Service.\", \"pname\": \"systemd\", \"host\": \"host123\", \"fromhost\": \"host123\", \"fac\": \"daemon\", \"pri\": \"30\" }\n\n" }, "reply": { "error": { "root_cause": [ { "type": "illegal_argument_exception", "reason": "Action\/metadata line [1] contains an unknown parameter [_type]" } ], "type": "illegal_argument_exception", "reason": "Action\/metadata line [1] contains an unknown parameter [_type]" }, "status": 400 } }`

### Steps to reproduce the behavior

my config with omelasticsearch,

        type="omelasticsearch"
        server=["localhost:9200"]
        usehttps="on"
        skipverifyhost="on"
        allowunsignedcerts="on"
        dynSearchIndex="on"
        searchIndex="special-index"

        searchType="_doc"

        bulkmode="on"

### Environment

rsyslog is installed from official stable Debian repo,

- rsyslog version: rsyslogd  8.2102.0 (aka 2021.02) compiled with:
        PLATFORM:                               x86_64-pc-linux-gnu
        PLATFORM (lsb_release -d):
        FEATURE_REGEXP:                         Yes
        GSSAPI Kerberos 5 support:              Yes
        FEATURE_DEBUG (debug build, slow code): No
        32bit Atomic operations supported:      Yes
        64bit Atomic operations supported:      Yes
        memory allocator:                       system default
        Runtime Instrumentation (slow code):    No
        uuid support:                           Yes
        systemd support:                        Yes
        Config file:                            /etc/rsyslog.conf
        PID file:                               /run/rsyslogd.pid
        Number of Bits in RainerScript integers: 64

- platform: Debian GNU/Linux 11 (bullseye)

The commit https://github.com/rsyslog/rsyslog/commit/d47b5c9b1c00bc2a107027bae1152d3e171059c2
is related, but it doesn't fix the problem when bulkmode is on.

**Comment by rgerhards** [comment]
The you are using an older version which is no longer supported by the community. I also think that the issue was fixed q few wweks ago. As such, please update to the currently supported version and retry. Report back if the problem persists.

The rsyslog project provides packages for current versions: https://www.rsyslog.com/downloads/download-other/

If you insist on using an outdated version, you can also contact your distro or consider [rsyslog professional services](https://www.rsyslog.com/professional-services/enterprise-support/).

**Comment by carljia999** [comment]
Thanks for your reply.

I cannot test the latest version because there is no Debian 11 package publicly available, neither in the Debian repo nor in rsyslog project repo. So the statement I made was based on information in rsyslog changelog and rsyslog commits. 

Today I revisited the source code, and I believe the problem has been fixed.

Can you add rsyslog packages for Debian 11 to your project repo? This will benefit the community a lot. The Debian 11 has been around for a while. I tried to run the latest version for Debian 10, but the systemd service could not start, which is a pain.

Thanks again.

**Comment by onlyjob** [comment]
FYI Debian maintainers are responsible for backporting packages for https://backports.debian.org/ and I believe the latest release will be eventually uploaded to `bullseye-backports`, like previous releases were uploaded shortly after becoming eligible. Debian maintainers can be contacted through Debian bug tracking system: https://www.debian.org/Bugs/Reporting

**Comment by carljia999** [comment]
thanks. I've submitted one bug report to Debian via email asking them to make new versions available.

**Comment by rgerhards** [comment]
FYI: @carljia999 I have enabled Debian 11 in SUSE OBS - looks like it is available now. I had overlooked to add it.

**Comment by carljia999** [comment]
Thanks a lot. @rgerhards
