### ISSUE TITLE
Omfwd / omelasticsearch message loss after peer restart

### ISSUE THREAD

**Issue by ymattw** [rsyslog/rsyslog#491]
We love rsyslog's high performance and want to use it for a central log collecting solution so tried a lot these days and found this issue.

We use `omfwd` and `omelasticsearch` to forward log messages to other system and saw message loss after receiving end is restarted.

This should be very easy to reproduce with `omfwd`:

1. run `nc -lv 6000 | tee output.log` on the other end
2. generate messages on the rsyslog end
3. stop the nc process
4. write more log messages
5. start the nc process

Rsyslog can reconnect automatically and resume sending process, but according to the timestamp in the receiving end, message written in step 4 were lost.

Similar happened to `omelasticsearch`

I understand the RELP protocol is designed to resolve data loss during peer restart, but my case is messages being forwarded were written **after** peer restart, in this case, rsyslog already know connection is broken, desired behavior is to buffer those new incoming messages written during the window and resend once the connection is recovered.

Our settings are like below.  Is there any special options must be set to work for this situation?

```bash
# cat /etc/rsyslog.d/30-tcp-output.conf
*.* action(type="omfwd"
           Target="192.168.172.29"
           Port="6000"
           resendlastmsgonreconnect="on"
           Protocol="tcp" )

# cat /etc/rsyslog.d/40-es-output.conf
module(load="omelasticsearch")
*.* action(type="omelasticsearch"
           server="192.168.149.141"
           serverport="9200")
```

**Comment by alorbach** [comment]
Hrm I don't think this is a bug. I think it is default behavior
Try using a unique queue in your action by adding these parameters this into your action: 

	action.resumeRetryCount="-1"
	queue.filename="queue" 
	queue.size="100000" 
	queue.saveonshutdown="on" 

You will see that messages are resend when nc is started again.

**Comment by ymattw** [comment]
Wonderful!  Thanks again.  I will give it a try and update this ticket soon.

**Comment by ymattw** [comment]
Verified your suggestion works with rsyslog-7.4.7 on centos 7, `StateFile` is required, though.  Thank you!!
