### ISSUE TITLE
When remote server is down, Sending logs to local file is not happening in http case.

### ISSUE THREAD

**Issue by sachusachin622** [rsyslog/rsyslog#4910]
Hi,

I am trying to send my logs to both local log files and also remote server.
**rsyslog -version:** rsyslogd  8.2204.1

**question 1: when remote server is down, Sending logs to local file is not happening in http case.**
Here am using 2 cases,
case 1:
when i am using both primary and secondary remote server as TCP, when remote server is up Logs are sending properly to both local log files and also remote server.->working fine
Here is my configuration for both primary and secondary remote server as TCP.

cat /tmp/rsyslog.conf 
#########################################################################
module(load="imuxsock") # provides support for local system logging
module(load="imklog")   # provides kernel logging support (previously done by rklogd)
module(load="omhttp")   

$ActionFileDefaultTemplate RSYSLOG_TraditionalFileFormat
$RepeatedMsgReduction on

set $/log_rlevel = 6;
set $/log_llevel = 7;

$IncludeConfig /etc/rsyslog.d/*.conf

$template TraditionalFormatWithPRI, "%HOSTNAME% %pri-text% %syslogtag%%msg:::drop-last-lf%\n"

ruleset(name="sendToLogserver") {
#PRIMARY-IP-ADDRESS#
action(type="omfwd" target="1.1.1.1" port="10514"  protocol="tcp" Template="TraditionalFormatWithPRI" )

#SECONDARY-IP-ADDRESS#
action(type="omfwd" target="2.2.2.2" port="10514"  protocol="tcp" Template="TraditionalFormatWithPRI" action.execOnlyWhenPreviousIsSuspended="on" )

}

if($/log_rlevel == 0) then {
		*.emerg 
		call sendToLogserver
} else if($/log_rlevel == 1) then {
		*.alert 
		call sendToLogserver
} else if($/log_rlevel == 2) then {
		*.crit
		call sendToLogserver
} else if($/log_rlevel == 3) then {
		*.err 
		call sendToLogserver
} else if($/log_rlevel == 4) then {
		*.warn
		call sendToLogserver
} else if($/log_rlevel == 5) then {
		*.notice
		call sendToLogserver
} else if($/log_rlevel == 6) then {
		*.info
		call sendToLogserver
} else {
		**.**
		call sendToLogserver
}

input(type="imuxsock" Socket="/tmp/log" CreatePath="off")

$outchannel log_rotation,/tmp/all_rsyslog.log, 1048576,rm /tmp/all_rsyslog.log
if($/log_llevel == 0) then {
    *.emerg :omfile:$log_rotation;TraditionalFormatWithPRI
} else if($/log_llevel == 1) then {
	*.alert :omfile:$log_rotation;TraditionalFormatWithPRI
} else if($/log_llevel == 2) then {
	*.crit :omfile:$log_rotation;TraditionalFormatWithPRI
} else if($/log_llevel == 3) then {
	*.err :omfile:$log_rotation;TraditionalFormatWithPRI
} else if($/log_llevel == 4) then {
	*.warn :omfile:$log_rotation;TraditionalFormatWithPRI
} else if($/log_llevel == 5) then {
	*.notice :omfile:$log_rotation;TraditionalFormatWithPRI
} else if($/log_llevel == 6) then {
	*.info :omfile:$log_rotation;TraditionalFormatWithPRI
} else {
	*.* :omfile:$log_rotation;TraditionalFormatWithPRI
}

############################# END OF RSYSLOG CONFIGURATION #################

case 2:
when i am using both primary and secondary remote server as http, when remote server is up Logs are sending properly to both local log files and also remote primary server.->working fine.
But when remote server is down logs are not sending to local log file (/tmp/all_rsyslog.log). but in TCP cases logs are sending properly to local log file (/tmp/all_rsyslog.log) even when remote servers are down.
Here is my configuration for both primary and secondary remote server as http.
cat /tmp/rsyslog.conf 
#########################################################################
#########################################################################

module(load="imuxsock") # provides support for local system logging
module(load="imklog")   # provides kernel logging support (previously done by rklogd)
module(load="omhttp")   

$ActionFileDefaultTemplate RSYSLOG_TraditionalFileFormat

$RepeatedMsgReduction on

set $/log_rlevel = 6;
set $/log_llevel = 7;

$IncludeConfig /etc/rsyslog.d/*.conf

#TEMPLATE-FOR-RSYSLOG#
$template TraditionalFormatWithPRI, "%HOSTNAME% %pri-text% %syslogtag%%msg:::drop-last-lf%\n"

######################################################
ruleset(name="sendToLogserver") {
#PRIMARY-IP-ADDRESS#
action(type="omhttp" template="TraditionalFormatWithPRI" useHttps="off" skipverifyhost="off" server="1.1.1.1" serverport="10515" httpheaders=[ "Bearer: <JWT>" ] restpath="rsyslog/" batch="on" batch.format="newline" batch.maxsize="100")

#SECONDARY-IP-ADDRESS#
action(type="omhttp" template="TraditionalFormatWithPRI" useHttps="off" skipverifyhost="off" server="2.2.2.2" serverport="10515" httpheaders=[ "Bearer: <JWT>" ] restpath="rsyslog/" batch="on" batch.format="newline" batch.maxsize="100" action.execOnlyWhenPreviousIsSuspended="on")

}
##########################################################################
if($/log_rlevel == 0) then {
		*.emerg 
		call sendToLogserver
} else if($/log_rlevel == 1) then {
		*.alert 
		call sendToLogserver
} else if($/log_rlevel == 2) then {
		*.crit
		call sendToLogserver
} else if($/log_rlevel == 3) then {
		*.err 
		call sendToLogserver
} else if($/log_rlevel == 4) then {
		*.warn
		call sendToLogserver
} else if($/log_rlevel == 5) then {
		*.notice
		call sendToLogserver
} else if($/log_rlevel == 6) then {
		*.info
		call sendToLogserver
} else {
		**.**
		call sendToLogserver
}

input(type="imuxsock" Socket="/tmp/log" CreatePath="off")

##########################################################################
$outchannel log_rotation,/tmp/all_rsyslog.log, 1048576,rm /tmp/all_rsyslog.log
if($/log_llevel == 0) then {
    *.emerg :omfile:$log_rotation;TraditionalFormatWithPRI
} else if($/log_llevel == 1) then {
	*.alert :omfile:$log_rotation;TraditionalFormatWithPRI
} else if($/log_llevel == 2) then {
	*.crit :omfile:$log_rotation;TraditionalFormatWithPRI
} else if($/log_llevel == 3) then {
	*.err :omfile:$log_rotation;TraditionalFormatWithPRI
} else if($/log_llevel == 4) then {
	*.warn :omfile:$log_rotation;TraditionalFormatWithPRI
} else if($/log_llevel == 5) then {
	*.notice :omfile:$log_rotation;TraditionalFormatWithPRI
} else if($/log_llevel == 6) then {
	*.info :omfile:$log_rotation;TraditionalFormatWithPRI
} else {
	*.* :omfile:$log_rotation;TraditionalFormatWithPRI
}
############################# END OF RSYSLOG CONFIGURATION #################

**question 2: Failover is not happening in http case.**
Here am using 2 cases,
case 1:
when i am using both primary and secondary remote server as TCP, Failover is happening between primary and seconadry server, working fine.
 
case 2:
when i am using both primary and secondary remote server as http, But in this cases Failover is not happening between primary and seconadry server.

Please help me to fix this 2 issues if anything missed.

Thanks,
Sachin.

**Comment by davidelang** [comment]
you need to setup a queue for the actions that can fail so that the other 
actions can continue while the failed action blocks. Once the queue fills up, 
the main thread will block again (but you can configure the queue for the action 
to throw away logs if you don't want things to stop)

David Lang

  On Thu, 23 Jun 2022, 
sachusachin622 wrote:

> Date: Thu, 23 Jun 2022 23:35:04 -0700
> From: sachusachin622 ***@***.***>
> Reply-To: rsyslog/rsyslog
>     ***@***.***>
> To: rsyslog/rsyslog ***@***.***>
> Cc: Subscribed ***@***.***>
> Subject: [rsyslog/rsyslog] When remote server is down,
>     Sending logs to local file is not happening in http case. (Issue #4910)
> 
> Hi,
>
> I am trying to send my logs to both local log files and also remote server.
> **rsyslog -version:** rsyslogd  8.2204.1
>
> **question 1: when remote server is down, Sending logs to local file is not happening in http case.**
> Here am using 2 cases,
> case 1:
> when i am using both primary and secondary remote server as TCP, when remote server is up Logs are sending properly to both local log files and also remote server.->working fine
> Here is my configuration for both primary and secondary remote server as TCP.
>
> cat /tmp/rsyslog.conf
> #########################################################################
> module(load="imuxsock") # provides support for local system logging
> module(load="imklog")   # provides kernel logging support (previously done by rklogd)
> module(load="omhttp")
>
> $ActionFileDefaultTemplate RSYSLOG_TraditionalFileFormat
> $RepeatedMsgReduction on
>
> set $/log_rlevel = 6;
> set $/log_llevel = 7;
>
>
> $IncludeConfig /etc/rsyslog.d/*.conf
>
> $template TraditionalFormatWithPRI, "%HOSTNAME% %pri-text% %syslogtag%%msg:::drop-last-lf%\n"
>
> ruleset(name="sendToLogserver") {
> #PRIMARY-IP-ADDRESS#
> action(type="omfwd" target="1.1.1.1" port="10514"  protocol="tcp" Template="TraditionalFormatWithPRI" )
>
> #SECONDARY-IP-ADDRESS#
> action(type="omfwd" target="2.2.2.2" port="10514"  protocol="tcp" Template="TraditionalFormatWithPRI" action.execOnlyWhenPreviousIsSuspended="on" )
>
> }
>
> if($/log_rlevel == 0) then {
> 		*.emerg
> 		call sendToLogserver
> } else if($/log_rlevel == 1) then {
> 		*.alert
> 		call sendToLogserver
> } else if($/log_rlevel == 2) then {
> 		*.crit
> 		call sendToLogserver
> } else if($/log_rlevel == 3) then {
> 		*.err
> 		call sendToLogserver
> } else if($/log_rlevel == 4) then {
> 		*.warn
> 		call sendToLogserver
> } else if($/log_rlevel == 5) then {
> 		*.notice
> 		call sendToLogserver
> } else if($/log_rlevel == 6) then {
> 		*.info
> 		call sendToLogserver
> } else {
> 		**.**
> 		call sendToLogserver
> }
>
> input(type="imuxsock" Socket="/tmp/log" CreatePath="off")
>
> $outchannel log_rotation,/tmp/all_rsyslog.log, 1048576,rm /tmp/all_rsyslog.log
> if($/log_llevel == 0) then {
>    *.emerg :omfile:$log_rotation;TraditionalFormatWithPRI
> } else if($/log_llevel == 1) then {
> 	*.alert :omfile:$log_rotation;TraditionalFormatWithPRI
> } else if($/log_llevel == 2) then {
> 	*.crit :omfile:$log_rotation;TraditionalFormatWithPRI
> } else if($/log_llevel == 3) then {
> 	*.err :omfile:$log_rotation;TraditionalFormatWithPRI
> } else if($/log_llevel == 4) then {
> 	*.warn :omfile:$log_rotation;TraditionalFormatWithPRI
> } else if($/log_llevel == 5) then {
> 	*.notice :omfile:$log_rotation;TraditionalFormatWithPRI
> } else if($/log_llevel == 6) then {
> 	*.info :omfile:$log_rotation;TraditionalFormatWithPRI
> } else {
> 	*.* :omfile:$log_rotation;TraditionalFormatWithPRI
> }
>
> ############################# END OF RSYSLOG CONFIGURATION #################
>
> case 2:
> when i am using both primary and secondary remote server as http, when remote server is up Logs are sending properly to both local log files and also remote primary server.->working fine.
> But when remote server is down logs are not sending to local log file (/tmp/all_rsyslog.log). but in TCP cases logs are sending properly to local log file (/tmp/all_rsyslog.log) even when remote servers are down.
> Here is my configuration for both primary and secondary remote server as http.
> cat /tmp/rsyslog.conf
> #########################################################################
> #########################################################################
>
> module(load="imuxsock") # provides support for local system logging
> module(load="imklog")   # provides kernel logging support (previously done by rklogd)
> module(load="omhttp")
>
> $ActionFileDefaultTemplate RSYSLOG_TraditionalFileFormat
>
> $RepeatedMsgReduction on
>
> set $/log_rlevel = 6;
> set $/log_llevel = 7;
>
> $IncludeConfig /etc/rsyslog.d/*.conf
>
> #TEMPLATE-FOR-RSYSLOG#
> $template TraditionalFormatWithPRI, "%HOSTNAME% %pri-text% %syslogtag%%msg:::drop-last-lf%\n"
>
> ######################################################
> ruleset(name="sendToLogserver") {
> #PRIMARY-IP-ADDRESS#
> action(type="omhttp" template="TraditionalFormatWithPRI" useHttps="off" skipverifyhost="off" server="1.1.1.1" serverport="10515" httpheaders=[ "Bearer: <JWT>" ] restpath="rsyslog/" batch="on" batch.format="newline" batch.maxsize="100")
>
> #SECONDARY-IP-ADDRESS#
> action(type="omhttp" template="TraditionalFormatWithPRI" useHttps="off" skipverifyhost="off" server="2.2.2.2" serverport="10515" httpheaders=[ "Bearer: <JWT>" ] restpath="rsyslog/" batch="on" batch.format="newline" batch.maxsize="100" action.execOnlyWhenPreviousIsSuspended="on")
>
> }
> ##########################################################################
> if($/log_rlevel == 0) then {
> 		*.emerg
> 		call sendToLogserver
> } else if($/log_rlevel == 1) then {
> 		*.alert
> 		call sendToLogserver
> } else if($/log_rlevel == 2) then {
> 		*.crit
> 		call sendToLogserver
> } else if($/log_rlevel == 3) then {
> 		*.err
> 		call sendToLogserver
> } else if($/log_rlevel == 4) then {
> 		*.warn
> 		call sendToLogserver
> } else if($/log_rlevel == 5) then {
> 		*.notice
> 		call sendToLogserver
> } else if($/log_rlevel == 6) then {
> 		*.info
> 		call sendToLogserver
> } else {
> 		**.**
> 		call sendToLogserver
> }
>
> input(type="imuxsock" Socket="/tmp/log" CreatePath="off")
>
> ##########################################################################
> $outchannel log_rotation,/tmp/all_rsyslog.log, 1048576,rm /tmp/all_rsyslog.log
> if($/log_llevel == 0) then {
>    *.emerg :omfile:$log_rotation;TraditionalFormatWithPRI
> } else if($/log_llevel == 1) then {
> 	*.alert :omfile:$log_rotation;TraditionalFormatWithPRI
> } else if($/log_llevel == 2) then {
> 	*.crit :omfile:$log_rotation;TraditionalFormatWithPRI
> } else if($/log_llevel == 3) then {
> 	*.err :omfile:$log_rotation;TraditionalFormatWithPRI
> } else if($/log_llevel == 4) then {
> 	*.warn :omfile:$log_rotation;TraditionalFormatWithPRI
> } else if($/log_llevel == 5) then {
> 	*.notice :omfile:$log_rotation;TraditionalFormatWithPRI
> } else if($/log_llevel == 6) then {
> 	*.info :omfile:$log_rotation;TraditionalFormatWithPRI
> } else {
> 	*.* :omfile:$log_rotation;TraditionalFormatWithPRI
> }
> ############################# END OF RSYSLOG CONFIGURATION #################
>
> **question 2: Failover is not happening in http case.**
> Here am using 2 cases,
> case 1:
> when i am using both primary and secondary remote server as TCP, Failover is happening between primary and seconadry server, working fine.
>
> case 2:
> when i am using both primary and secondary remote server as http, But in this cases Failover is not happening between primary and seconadry server.
>
>
> Please help me to fix this 2 issues if anything missed.
>
> Thanks,
> Sachin.
>
>

**Comment by sachusachin622** [comment]
Thanks for the update. working fine.
