### ISSUE TITLE
How can i solve that rsyslogd writing cracked string?

### ISSUE THREAD

**Issue by Lee-HyeongSeok** [rsyslog/rsyslog#4917]
Hello, 
recently i'm using rsyslog for log to remote server and have problem.

### Expected behavior
First, the agent program is running on the Linux client and sends a UDP socket for logs that conforms to the syslog protocol format.

This socket payload is "[Incident URL: https://127.0.0.1/Center/incidentsView.popup?guid=11da22a3-1111-11d8-a1f1-ec2dd0aa1eea]|1047872390|GENERIC|HTTP_15.5.52|null".

Second, the log server receives it. And rsyslogd on the log server writes logs to the user-defined path.

Third, users can strings "[Incident URL: https://127.0.0.1/Center/incidentsView.popup?guid=11da22a3-1111-11d8-a1f1-ec2dd0aa1eea]|1047872390|GENERIC|HTTP_15.5.52|null".

### Actual behavior
However, users can only see strings like '/'.
I have not set the string regex in my rsyslog configuration file. When a log string is received by rsyslogd, rsyslogd writes the log to a user-defined path.

### Steps to reproduce the behavior
when i get this steps with tcpdump, socket payload normally received in log server.
However, When log server's writing log with rsyslogd, users can only see strings like '/'.

I'm expect this problem. When rsyslogd received socket payload, parse with default regex.
And '[', ']' strings react to default regex.

Can you please confirm if this is correct?

### Environment
- rsyslog version: 8.24.0-57.el7_9.1
- platform: CentOS 7
- rsyslog configuration file : 

![conf1](https://user-images.githubusercontent.com/55940552/176131190-dddbcc11-2d00-46a9-8cbe-df4cd833aa1c.PNG) 
![conf2](https://user-images.githubusercontent.com/55940552/176131193-5115e044-3917-4998-9c3c-d86978b3d173.PNG)
![conf3](https://user-images.githubusercontent.com/55940552/176131180-a3e6df5a-b74e-435a-a83a-6479c5564d07.PNG)

**Comment by davidelang** [comment]
first off, 8.24 is very old, it was released about 5 years ago (with rsyslog 
releasing new versions every 6 weeks for most of that time and every 8 weeks for 
the rest). The version you have is also not what the rsyslog project released, 
but a version maintained by RedHat that contains some backports and other fixes 
that the rsyslog project does not track. Please update to the current version 
maintained by the community so we can support you (and, if we find that this is 
actually a bug, you would need to be running the community version or you won't 
be able to get the fixed version that we create)

Only RedHat can debug and release a fix for the version you are running.

That said, odds are good that it's not actually a bug, but rather a 
misunderstanding of something.

Please post your full config, and also log with the template RSYLOG_DebugFormat 
so we can see exactly what the full message looks like and understand what 
manipulation you are doing to the message

you are saying that the only string you see is / but the message you are posting 
has very few / in it, so it's not at all clear what you are meaning by 'seeing 
strings'

David Lang

**Comment by Lee-HyeongSeok** [comment]
Thanks for checking out my problem.

As u told me, I'm found out this problem with RSYSLOG_DebugFormat.

first, I know that rsyslogd's msg and raw are different field . rawmsg field is received from network. it has syslog header field. msg field just syslog payload. If your senders are RFC-compliant, both should differ.

Second, I could saw that received syslog packet's content with RSYSLOG_TraditionalFileFormat on RSYSLOG_DebugFormat, before use changed template format.
![debug](https://user-images.githubusercontent.com/55940552/176336821-63cdf6ca-a67c-4f26-9e54-3483238e2896.PNG)

As you can see in this picture, msg field has '/' string and, rawmsg field has expected string. 

And Redhat Rsyslogd's template format of RSYSLOG_TraditionalFileFormat is using ```"%TIMESTAMP% %HOSTNAME% %syslogtag%%msg:::sp-if-no-1st-sp%%msg:::drop-last-lf%\n"```. It use to msg field. 
So the result is: 
![s](https://user-images.githubusercontent.com/55940552/176337218-0f433649-6e85-41e1-978d-5af46ce21d20.PNG)
this problem is that repeat unexpected string output.


So, I'm write User-Defined temlate format on my rsyslog.conf file. It is ```"%TIMESTAMP% %HOSTNAME% %syslogtag%%rawmsg%"```. default format is same to RSYSLOG_TraditionalFileFormat. i was changed msg field to raw field.
