### ISSUE TITLE
Max-Size-Action for $outchannel

### ISSUE THREAD

**Issue by forfcw** [rsyslog/rsyslog#4924]
### Want
Is there a way to slice log file actively when the file size reaches the limit?
Not logrotate or crontab, I found the way below, but it seems out of date.

Looking forward to your recovery.
Thanks

### Actual behavior
a new file /var/log/syslog created with FileGroup **syslog**  instead of **adm**

### Steps to reproduce the behavior
`[root@root:/]# head -n 15 /etc/rsyslog.d/50-default.conf  
module(load="builtin:omfile" FileGroup="adm" DirGroup="adm")
$outchannel                     mysyslog,/var/log/syslog,2048,/1.sh
*.*;auth,authpriv.none          :omfile:$mysyslog

auth,authpriv.*                 /var/log/auth.log
#*.*;auth,authpriv.none         -/var/log/syslog

[root@root:/]# cat /1.sh
#! /bin/bash

mv -f /var/log/syslog /var/log/syslog.1`

### Environment
- rsyslog version: 8.2001.0
- platform:  Ubuntu 20.04

**Comment by jay7x** [comment]
Tbh, I'd prefer to have the log rotation support implemented `omfile` in some way..
E.g. `omfile` may check the file size after the latest flush and if size is greater than some max size value it does the following:
1. Execute a specified template to get the new name for the rotated file ("$filepath/$filename-$timestamp" e.g.). This means file size might be slightly bigger than the max size.
2. Delete existing file with the new name.
3. Rename the old file
4. The new file will be created when first message arrive

So I'd imagine new configuration made in this way:
```
template(name="rotateTmpl" type="string" string="/var/log/testfile.log-$timegenerated")
action(type="omfile" name="testfile"
  file="/var/log/testfile.log"
  rotateSize="1G"
  rotateTemplate="rotateTmpl"
  fileCreateMode="640"
)
```

@rgerhards @davidelang what do you think?

**Comment by jay7x** [comment]
omg.. I just realized it's here already: https://github.com/rsyslog/rsyslog-doc/pull/996/files
