### ISSUE TITLE
rsyslogd leak memory when free action worker data table

### ISSUE THREAD

**Issue by seuzw930** [rsyslog/rsyslog#4938]
### Expected behavior
no mem leak in when free action worker data table
### Actual behavior
the asan reports there is a memory leak when an action finished
### Steps to reproduce the behavior
There is an asan report when rsyslog complete the action operation:
Direct leak of 80 byte(s) in 1 object(s) allocated from:
    #0 0xffff81b5f230 in __interceptor_calloc (/usr/lib64/libasan.so.6+0xa5230)
    #1 0xffff7da8bd0c  (<unknown module>)
    #2 0xaaaae77c9f04 in initTCP /usr/src/debug/rsyslog-8.2110.0-7.eulerosv2r11.aarch64/tools/omfwd.c:1185
    #3 0xaaaae77c9f04 in createWrkrInstance /usr/src/debug/rsyslog-8.2110.0-7.eulerosv2r11.aarch64/tools/omfwd.c:412
    #4 0xaaaae78967c0 in actionCheckAndCreateWrkrInstance ../action.c:984
    #5 0xaaaae789f6b4 in actionPrepare ../action.c:1071
    #6 0xaaaae789f6b4 in processMsgMain ../action.c:1662
    #7 0xaaaae78a0668 in doSubmitToActionQ ../action.c:1834
    #8 0xaaaae788a5f4 in execAct /usr/src/debug/rsyslog-8.2110.0-7.eulerosv2r11.aarch64/runtime/ruleset.c:209
    #9 0xaaaae788a5f4 in scriptExec /usr/src/debug/rsyslog-8.2110.0-7.eulerosv2r11.aarch64/runtime/ruleset.c:599
    #10 0xaaaae788be60 in processBatch /usr/src/debug/rsyslog-8.2110.0-7.eulerosv2r11.aarch64/runtime/ruleset.c:660
    #11 0xaaaae77c03a4 in msgConsumer /usr/src/debug/rsyslog-8.2110.0-7.eulerosv2r11.aarch64/tools/rsyslogd.c:696
    #12 0xaaaae788199c in ConsumerReg /usr/src/debug/rsyslog-8.2110.0-7.eulerosv2r11.aarch64/runtime/queue.c:2198
    #13 0xaaaae7874c9c in wtiWorker /usr/src/debug/rsyslog-8.2110.0-7.eulerosv2r11.aarch64/runtime/wti.c:428
    #14 0xaaaae7871168 in wtpWorker /usr/src/debug/rsyslog-8.2110.0-7.eulerosv2r11.aarch64/runtime/wtp.c:435
    #15 0xffff81773528  (/usr/lib64/libc.so.6+0x7f528)
    #16 0xffff817d97d8  (/usr/lib64/libc.so.6+0xe57d8)
### Environment
- rsyslog version: 8.2110.0
- platform: centos
- for configuration questions/issues, include rsyslog.conf and included config files

**Comment by rgerhards** [comment]
unfortunately, the stack trace does not match v8.2110.0 that we released. Are there some extra patches inside it?

**Comment by seuzw930** [comment]
Yes, there were some patches inside. As I remove these patches, the new asan report as below:
`Direct leak of 80 byte(s) in 1 object(s) allocated from:
#0 0xffff81a5f132 in __interceptor_calloc (/usr/lib64/libasan.so.6+0xa5230)
#1 0xffff7d98bc0e ()
#2 0xaaaae76c9e06 in initTCP /usr/src/debug/rsyslog-8.2110.0.aarch64/tools/omfwd.c:1185
#3 0xaaaae76c9e06 in createWrkrInstance /usr/src/debug/rsyslog-8.2110.0.aarch64/tools/omfwd.c:412
#4 0xaaaae77966c2 in actionCheckAndCreateWrkrInstance ../action.c:975
#5 0xaaaae779f5b6 in actionPrepare ../action.c:1062
#6 0xaaaae779f5b6 in processMsgMain ../action.c:1653
#7 0xaaaae77a056a in doSubmitToActionQ ../action.c:1825
#8 0xaaaae778a4f6 in execAct /usr/src/debug/rsyslog-8.2110.0.aarch64/runtime/ruleset.c:209
#9 0xaaaae778a4f6 in scriptExec /usr/src/debug/rsyslog-8.2110.0.aarch64/runtime/ruleset.c:599
#10 0xaaaae778bd62 in processBatch /usr/src/debug/rsyslog-8.2110.0.aarch64/runtime/ruleset.c:660
#11 0xaaaae76c02a6 in msgConsumer /usr/src/debug/rsyslog-8.2110.0.aarch64/tools/rsyslogd.c:694
#12 0xaaaae778189e in ConsumerReg /usr/src/debug/rsyslog-8.2110.0.aarch64/runtime/queue.c:2164
#13 0xaaaae7774b9e in wtiWorker /usr/src/debug/rsyslog-8.2110.0.aarch64/runtime/wti.c:428
#14 0xaaaae777106a in wtpWorker /usr/src/debug/rsyslog-8.2110.0.aarch64/runtime/wtp.c:435
#15 0xffff8167342a (/usr/lib64/libc.so.6+0x7f528)
#16 0xffff816d96da (/usr/lib64/libc.so.6+0xe57d8)`
