### ISSUE TITLE
Force killing rsyslog causes disk dequeueing errors, repeatedely done eventually segfaults

### ISSUE THREAD

**Issue by StrongestNumber9** [rsyslog/rsyslog#4963]
### Expected behavior
No disk dequeueing errors, maybe last events if killed while writing as this is imtcp and not relp.

### Actual behavior
Seems like events are lost as queues are broken, eventually segfaults
```sh
rsyslogd: receiver queue: error dequeueing element - ignoring, but strange things may happen [v8.2208.0 try https://www.rsyslog.com/e/2031 ]
rsyslogd: file '/rsyslog/var/queue.00000002': open error: No such file or directory [v8.2208.0 try https://www.rsyslog.com/e/2040 ]
rsyslogd: receiver queue: qDeqDisk error happened at around offset 0 [v8.2208.0 try https://www.rsyslog.com/e/2040 ]
rsyslogd: receiver queue: error dequeueing element - ignoring, but strange things may happen [v8.2208.0 try https://www.rsyslog.com/e/2040 ]
/entrypoint.sh: line 23:   104 Segmentation fault      (core dumped) ( rsyslogd -f /rsyslog/rsyslog.conf -i /rsyslog/var/rsyslogd.pid -n )
```

### Steps to reproduce the behavior
All the related files are attached to the ticket, automatic container image that shows the exact issue. It sometimes crashes on the very first attempt, sometimes takes even couple of minutes.

[issue.tar.gz](https://github.com/rsyslog/rsyslog/files/9374412/issue.tar.gz)

```sh
$ ./run.sh 
Sending build context to Docker daemon  82.94kB
Step 1/6 : FROM centos:7
 ---> eeb6ee3f44bd
Step 2/6 : RUN yum -y install wget gnutls emacs-nox gdb strace && wget http://rpms.adiscon.com/v8-stable/rsyslog.repo -O /etc/yum.repos.d/rsyslog.repo && yum -y install rsyslog rsyslog-relp rsyslog-mmjsonparse rsyslog-mmnormalize rsyslog-pmnormalize rsyslog-openssl
 ---> Using cache
 ---> 1dec05bd5c6e
Step 3/6 : COPY certs/ /certs/
 ---> Using cache
 ---> 367611f7b82b
Step 4/6 : COPY rsyslog/ /rsyslog/
 ---> Using cache
 ---> d3230fc1b3fe
Step 5/6 : COPY entrypoint.sh /entrypoint.sh
 ---> Using cache
 ---> 24d596244e63
Step 6/6 : CMD ["/entrypoint.sh"]
 ---> Using cache
 ---> 1641264c5097
Successfully built 1641264c5097
Successfully tagged rsyslog-queue-segfault:latest
Starting receiver
Starting rsyslog
Sleeping a bit before killing
Starting rsyslog
/entrypoint.sh: line 21:    11 Killed                  ( rsyslogd -f /rsyslog/rsyslog.conf -i /rsyslog/var/rsyslogd.pid -n )
rsyslogd: receiver queue: qDeqDisk error happened at around offset 20500 [v8.2208.0 try https://www.rsyslog.com/e/2308 ]
rsyslogd: receiver queue: error dequeueing element - ignoring, but strange things may happen [v8.2208.0 try https://www.rsyslog.com/e/2308 ]
/entrypoint.sh: line 21:    42 Segmentation fault      (core dumped) ( rsyslogd -f /rsyslog/rsyslog.conf -i /rsyslog/var/rsyslogd.pid -n )
```

### Environment

Host:
Fedora release 36 (Thirty Six) running on 5.18.17-200.fc36.x86_64 kernel
Docker version 20.10.17, build aa7e414

Container:
Latest official rsyslog installed from official repository: rsyslog-8.2208.0-1.el7.x86_64
tcpflood is built by us, based on version 8.2102 with gnutls enabled
Running on official centos7 container: CentOS Linux release 7.9.2009 (Core)

**Comment by StrongestNumber9** [comment]
As a note, I found this while trying to reproduce https://github.com/rsyslog/librelp/issues/240 reliably on my own.

**Comment by rgerhards** [comment]
`kill -9` is like poweroff. We cannot handle this, because we do not get control. Rsyslog is not a database system, and handling that situation is far beyond the scope of this project. So what you see is not a bug but a limitation.

**Comment by StrongestNumber9** [comment]
I believe the segmentation fault part is a bug that should not happen and this is just an easy way to expose it.

**Comment by rgerhards** [comment]
As I said, you can also expose it by doing a power off. This is not a bug. If you need something that survives power off/kill -9, you need to use a database-like system. Then rsyslog is the wrong tool.

Technically, we would need to do a two-phase commit to ensure we can survive power off. This was always beyond the spec.

**Comment by davidelang** [comment]
making writes to a file safe in the face of kill -9 or poweroff involves a lot 
of fsync work which kills performance (and disk queues are already way too 
slow).

That said, is there anything that can be done to make the error just result in a 
log entry being lost instead of a segfault?

David Lang

**Comment by rgerhards** [comment]
I agree there are extended possibilities to prevent a segfault. But in practice, I have never seen or heard about these issues and doing several kill -9 in short periods to provoke it doesn't sound like a good method to me.
