### ISSUE TITLE
rsyslog messages doesn't contain PRI headers

### ISSUE THREAD

**Issue by sshedi** [rsyslog/rsyslog#4964]
### Expected behavior
Messages should contain PRI headers

### Actual behavior
No PRI headers in messages

### Steps to reproduce the behavior
Not sure but happens with big packages

### Environment
- rsyslog version: 8.2106.0 (client version), 8.1911.0 (server version)
- platform: Photon OS

Max message size is configured as 63k
Upon packet capture we see that messages doesn't contain PRI headers in them.
Find the attached screen captures, in rsyslog-1.jpg (packet 127694) there is `<1 34>` and rest of them doesn't and this continues until packet number 127710.

Is this expected behavior? Or something going wrong? Please assist.

![rsyslog-4](https://user-images.githubusercontent.com/53473811/185459715-799cc57c-5b0e-4135-bd1b-352294de21b4.jpg)
![rsyslog-3](https://user-images.githubusercontent.com/53473811/185459769-eb2e1487-8b0c-4d66-9327-5b683e8cdcef.jpg)
![rsyslog-2](https://user-images.githubusercontent.com/53473811/185459793-8771abad-68c4-4c04-bb36-afd9bda955cc.jpg)
![rsyslog-1](https://user-images.githubusercontent.com/53473811/185459809-53b1fe95-c6a8-4abe-9044-bdf948e1acae.jpg)

**Comment by davidelang** [comment]
so, half the examples you give have the PRI header and half don't. You seem to 
be highlighting individual packets, and if a message is more than one packet 
long, the header is at the beginning of the message, not the beginning of the 
packet.

with a max message size set to 6k, when rsyslog is receiving a message, if it 
gets a message > 6k long it will make the first 'log' 6k and the next 'log' will 
start at that point (which will not have a header on it)

are you thinking that the message without the PRI header is being sent to 
rsyslog, or that rsyslog is sending it? (it's not clear from your post)

In general, when you have what you think is a problem with rsyslog 
receiving/parsing/handling messages, it's good to log the messages with the 
template RSYSLOG_DebugFormat so that we can see the received message and how 
it's parsed. If the problem is with rsyslog sending messages, then this helps 
less (but could still provide clues if it's an extrememly long message)

David Lang

**Comment by rgerhards** [comment]
Beware: that's a capture of a TCP stream, so "packet" has no meaning here.
The question is if it has proper framing. I guess not.

In most cases LF at end of message is proper framing.

Sent from phone, thus brief.

David Lang ***@***.***> schrieb am Do., 18. Aug. 2022, 20:37:

**Comment by davidelang** [comment]
On Thu, 18 Aug 2022, Rainer Gerhards wrote:

> Beware: that's a capture of a TCP stream, so "packet" has no meaning here.

packet has no meaning in terms of rsyslog parsing messages, but in the interface 
provided, I believe that the OP is highlighting individual packets in the stream 
to show their content. half of the packets highlighted start with proper 
headers, half don't.

David Lang

**Comment by rgerhards** [comment]
Yes, but that's only tcp's concern.  In the TCP API, no such thing as a
packet exists. It's all a single sequential stream. Boundaries between
messages are not indicated by "packets" but the framing. Totally different
beast than UDP.

Sent from phone, thus brief.

David Lang ***@***.***> schrieb am Do., 18. Aug. 2022, 21:15:

**Comment by rgerhards** [comment]
https://www.rfc-editor.org/rfc/rfc6587

Sent from phone, thus brief.

Rainer Gerhards ***@***.***> schrieb am Do., 18. Aug. 2022,
21:18:

**Comment by sshedi** [comment]
Thanks @davidelang & @rgerhards for the detailed explanation.
Yes, it makes sense. The first chunk had PRI in it and subsequent chunks did not. Just wanted to ensure that this is the expected behavior.

>but in the interface provided, I believe that the OP is highlighting individual packets in the stream to show their content.
Yes, for the ease of understanding, I was referring to packet numbers in the attached images.

**Comment by davidelang** [comment]
As Rainer is pointing out, individual packets don't matter for TCP syslog, so 
the information you are providing to explain that you think messages are being 
sent without the PRI value aren't showing what you think they are (which is the 
point I was failing to explain earlier). With TCP syslog, you could have 
multiple syslog messages in a single TCP packet, and you can have TCP packets 
that don't contain a complete message, so looking at individual packets doesn't 
tell you anything.

so let's back up a bit, what is making you think that messages are malformed?

is it that messages aren't being received properly somewhere? if so, what is the 
sender and what is the receiver.

David Lang

**Comment by sshedi** [comment]
In our packet capture, almost all messages have PRI header in them (except the big ones) and like you explained earlier if log is getting transmitted in chunks due to size, only first message has PRI and rest doesn't.

**Comment by davidelang** [comment]
Ok, that comes down to using the wrong tool for the job. if you are looking at 
the data stream in a packet capture, the only reason you see the headers at the 
beginning of the packet is that you have a very low log volume, so the 
connection is going idle between each log message that is being sent. As your 
log volume increases, you will reach a point where your sending system will send 
messages fast enough that it will combine them into fewer packets over the wire, 
at that point you will be far more likely to see packets that don't start with 
the headers.

It sounds as if you may not actually have a problem. Was there some issue that 
caused you to start looking at the packet captures that I'm missing?

David Lang

**Comment by sshedi** [comment]
Thanks @davidelang & @rgerhards for the detailed explanations. It really helped. Have a nice time ahead, closing this issue.
