### ISSUE TITLE
Trying to understand omprog errors.

### ISSUE THREAD

**Issue by Github-Citizen** [rsyslog/rsyslog#4967]
I am using omprog with a perl script. When its working, everything works perfect. Sometimes these errors pop up and i don't understand what the errors mean to know where to trouble shoot. I recently updated rsyslog a few days ago and don't recall having these issue before the update.

If i do a service restart, most of the time everything works, but after a time these errors happen and i have not figured out what triggers them yet. When the errors happen i get dozens of error lines in the logs because of the retry nature of omprog.

```
Aug 20 12:30:06 hostname rsyslogd[849]: action 'perl_script' resumed (module 'omprog') [v8.2208.0 try https://www.rsyslog.com/e/2359 ]
Aug 20 12:30:06 hostname rsyslogd[849]: omprog: error sending message to program: Bad file descriptor [v8.2208.0 try https://www.rsyslog.com/e/2119 ]
Aug 20 12:30:06 hostname rsyslogd[849]: action 'perl_script' suspended (module 'omprog'), retry 0. There should be messages before this one giving the reason for suspension. [v8.2208.0 try https://www.rsyslog.com/e/2007 ]
```

What causes a bad file descriptor? What does that even mean? Which file?
After those errors i did a restart and triggered more logged events to happen which then generated these errors.

```
Aug 20 12:34:50 hostname rsyslogd[1506]: perl_script queue: qDeqDisk error happened at around offset 34198 [v8.2208.0 try https://www.rsyslog.com/e/2031 ]
Aug 20 12:34:50 hostname rsyslogd[1506]: perl_script queue: error dequeueing element - ignoring, but strange things may happen [v8.2208.0 try https://www.rsyslog.com/e/2031 ]
Aug 20 12:34:50 hostname rsyslogd[1506]: perl_script queue: lost 1 messages from diskqueue (invalid .qi file) [v8.2208.0]
Aug 20 12:34:50 hostname rsyslogd[1506]: problem on disk queue 'perl_script queue': queue files contain 1 messages fewer than specified in .qi file -- we lost those messages. That's all we know. [v8.2208.0 try https://www.rsyslog.com/e/0 ]
Aug 20 12:35:55 hostname systemd[1467]: Created slice User Background Tasks Slice.
Aug 20 12:35:55 hostname systemd[1467]: Starting Cleanup of User's Temporary Files and Directories...
Aug 20 12:35:55 hostname systemd[1467]: Finished Cleanup of User's Temporary Files and Directories.
```

Can you point me in the direction of trouble shooting this? Why is the disk queue having issues? What issues? What should i be looking for or at? Isn't the queue file written to drive by user root? Im assuming it isn't a file permission issue.

```
module(load="omprog")
mail.*  action(
    type="omprog"
    name="perl_script"
    binary="/etc/rsyslog.d/perl_script"
    template="RSYSLOG_TraditionalFileFormat"
    output="/etc/rsyslog.d/perl_script.error"
    confirmMessages="on"
    reportFailures="on"
    action.resumeInterval="5"
    action.resumeRetryCount="-1"
    killUnresponsive="on"
    queue.saveOnShutdown="on"
    queue.type="Disk"
    queue.filename="perl_script.queue"
    queue.size="50000"
    queue.maxFileSize="1g"
)
```
and
```
rsyslogd  8.2208.0 (aka 2022.08) compiled with:
        PLATFORM:                               x86_64-redhat-linux-gnu
        PLATFORM (lsb_release -d):
        FEATURE_REGEXP:                         Yes
        GSSAPI Kerberos 5 support:              Yes
        FEATURE_DEBUG (debug build, slow code): No
        32bit Atomic operations supported:      Yes
        64bit Atomic operations supported:      Yes
        memory allocator:                       system default
        Runtime Instrumentation (slow code):    No
        uuid support:                           Yes
        systemd support:                        Yes
        Config file:                            /etc/rsyslog.conf
        PID file:                               /var/run/syslogd.pid
        Number of Bits in RainerScript integers: 64
```
and
```
Red Hat Enterprise Linux release 9.0 (Plow)
Linux hostname 5.15.0-1.43.4.1.el9uek.x86_64 #2 SMP Fri Aug 5 09:33:54 PDT 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by Github-Citizen** [comment]
And i forgot, the perl script only outputs one of the two following during execution.
```
print STDOUT "OK\n";
print STDOUT "Error\n";
```

**Comment by davidelang** [comment]
I would guess that this means that the perl script exited, so when rsyslog 
attempted to deliver the log to the script, the file handle was closed (and 
therefor bad)

David Lang

**Comment by Github-Citizen** [comment]
> I would guess that this means that the perl script exited, so when rsyslog attempted to deliver the log to the script, the file handle was closed (and therefor bad) David Lang

Isn't that a feature of omprog? If there is an issue, an error, a crash, omprog spins up a new instance and tries again? I would assume if it is trying a closed file handle it would kill that process and spin up a new fresh process. Can someone shed light on if that is what happens under the hood?

**Comment by rgerhards** [comment]
This sounds a bit strange. 

If possible, please create a debug log. Instructions: https://www.rsyslog.com/doc/v8-stable/troubleshooting/howtodebug.html

Be sure that the problem in question occurs at least once during the debug run. Once this is done, please post the debug log (e.g. via pastebin or github). After that, we can review the contents and check how exactly rsyslog processing worked.

**Comment by Github-Citizen** [comment]
The only way i have observed how to force the errors to happen is after a reboot. Other times when the error happens it seems random, i have not figured out what's causing it.

For this debug log i...

- stopped rsyslog service
- added debugging to config
- shutdown server
- started server
- triggered an event to be logged
- checked `/var/log/messages` to see issue was happening
- restarted rsyslog service
- observed after service restart the omprog script ran as intended
- stopped rsyslog service
- saved debug log

I redacted hostname/IP out of the debug log.

[rsyslog.debug.txt](https://github.com/rsyslog/rsyslog/files/9390209/rsyslog.debug.txt)

**Comment by Github-Citizen** [comment]
The only way i have observed how to force the errors to happen is after a reboot. Other times when the error happens it seems random, i have not figured out what's causing it.

For this debug log i...

- stopped rsyslog service
- added debugging to config
- shutdown server
- started server
- triggered an event to be logged
- checked `/var/log/messages` to see issue was happening
- restarted rsyslog service
- observed after service restart the omprog script ran as intended
- stopped rsyslog service
- saved debug log

I redacted hostname/IP out of the debug log.

[rsyslog.debug.txt](https://github.com/rsyslog/rsyslog/files/9390242/rsyslog.debug.txt)

**Comment by rgerhards** [comment]
Thx for the debug log. Unfortunately, it does not really have additional information. Could you post your script? Maybe this enables to reproduce. Ensure that you remove sensitive data, but leave it as intact as possible,.

**Comment by Github-Citizen** [comment]
I removed the parsing logic and SQL query from the processing sub function as i do not believe any of it matters, that function returns either `0;` or `1;` when it's done. I left the `main()` function intact.

[perl_script.txt](https://github.com/rsyslog/rsyslog/files/9398110/perl_script.txt)

**Comment by rgerhards** [comment]
mhhh... everything looks good as far as I can see. I need to add debug info the the debug log. Would you be willing to apply a patch to try that out?

**Comment by Github-Citizen** [comment]
Would that require a manual `make` install? I would want to deploy a non-production box to do this with. Let me setup a 'clone' system and i will let you know when ready.

**Comment by Github-Citizen** [comment]
I setup a KVM for testing, running RHEL9 and rsyslog v8.2208.0
I created a test `omprog_script` were i could change on the fly if its returning `OK\n` or `Error\n` responses.

I observed the problem happens when an error is returned on script startup before rsyslog post any log lines.

When the script starts it gives the first `OK` before going into a loop to listen for `STDIN`. As long as that first `OK` is given, if an `Error` is returned during the `STDIN` loop then rsyslog behaves correctly and keeps re-sending the log line at intervals until it gets an `OK`.

But if on script start up an `Error` is given before going into the loop to listen for `STDIN` that is when things break. When this happens, the script exits and omprog does not start up a new script. I watched debuging from the script and i checked `ps aufx` to see no new script instance was being started, but the `/var/log/messages` gets flooded with
```
Aug 25 14:02:21 vps1 rsyslogd[1305]: action 'omprog_script' resumed (module 'omprog') [v8.2208.0 try https://www.rsyslog.com/e/2359 ]
Aug 25 14:02:21 vps1 rsyslogd[1305]: omprog: program '/etc/rsyslog.d/omprog_script' (pid 1340) terminated; will be restarted [v8.2208.0 try https://www.rsyslog.com/e/2119 ]
Aug 25 14:02:21 vps1 rsyslogd[1305]: action 'omprog_script' suspended (module 'omprog'), retry 0. There should be messages before this one giving the reason for suspension. [v8.2208.0 try https://www.rsyslog.com/e/2007 ]
```
every one second (not at the set repeat interval). It repeats those errors in `messages` indefinitely until rsyslog is stopped/restarted. Even if i remove my artificial error condition it doesn't matter at this point because the script never actually runs again until rsyslog service is restarted.

What i have not figured out yet or replicated is sometimes when this issue happens, logs get lost and i've seen errors in `messages` about unrecoverable log lines (see error logs in first post above).

Now that i better understand what is happening, i can work around this by always giving an `OK` on startup even if i don't get an SQL connection and have broken SQL connections generate an error during the `STDIN` loop instead. Tested and confirmed. Makes sense why i only noticed this on server reboots. A race between which service starts first, rsyslog or mysql.

If you still want me to run more testing with a debug patch of rsyslog let me know.

**Comment by rgerhards** [comment]
Thx, that helps! But it sounds like I need to dive in a big area of contributed code. May take a little while.

**Comment by rgerhards** [comment]
Sorry for taking so long to actually look at the case. There is indeed a bug when external program startup does not return "OK". This can also lead to a misadressing with potentially a segfault (very unlikely). 

The problem basically is that for a startup failure, the control data for that external program instance is freed on error. Unfortunately, that state data is needed later on to detect a suspended instance. Potentially the cure is to keep the control data even on init failure (as we then need to do normal control options). In quick testing, this seems to do the trick. However, I will check a bit more. I plan to post a PR soon, but probably not today.
