### ISSUE TITLE
High & low watermark default for disk assisted queues are too high?

### ISSUE THREAD

**Issue by JPvRiel** [rsyslog/rsyslog#4968]
### Expected behavior

Sane defaults which don't lead to excessive memory usage.

Current vs proposed defaults:

| param | current | proposed |
| - | - | - |
| queue.highWatermark | 90% | 10% |
| queue.lowWatermark | 70% | 5% |

Perhaps a logic check that uses smaller defaults when `queue.size > 1000000` (1M messages * 512 ~= 488MB memory use).

### Actual behavior

Setting a large queue size for a disk assisted queue  results in high memory use as per <https://www.rsyslog.com/doc/master/rainerscript/queue_parameters.html#queue-highwatermark> default.

> 90% of queue.size

Surely the inverse would be more sensible? E.g. by default, use 10% of the queue in memory, then use disk, especially if someone intends to have a big disk queue? What is the point of 90% memory use, then just 10% disk use? Or am I misunderstanding something? `queue.size` applies as the upper limit for messages both in memory and on disk (i.e. not just in-memory)?

Ditto for the low watermark.

### Steps to reproduce the behavior

E.g. for a syslog relay / aggregation / forwarder server with very big queues to handle output downtime (100M messages and ~48GB max disk space):

```text
queue.filename="i_like_big_buffers"
queue.type="LinkedList"
queue.size="100000000"
queue.maxDiskSpace="51200000000"
```

Aim it at some dead/non-existent output and observe the RAM used up with hardly any disk space touched.

When leaving out `queue.filename`, rsyslog chews into several GB queuing in memory and crashes out of RAM before bothering to switch to DA mode.

### Environment

- rsyslog version: 8.2108.0-1
- platform: centos 7 in a container

**Comment by davidelang** [comment]
why setup a large memory queue if you don't want it to be used? I would not want 
rsyslog to change it's behavior to use less of the queue if I set the queue size 
large.

you may not be aware that the performance of the disk queue is very slow 
compared to the memory queue, and if you have data in the disk queue, it gets 
delivered interleaved with what's in the memory queue. They are also a pretty 
significant load on the system compared to memory queues.

The disk queue is intended to preserve logs in situations where you would 
otherwise lose the logs or stall (i.e. the system you are delivering to is 
down), they are not something that should be used under normal operating 
conditions.

David Lang

**Comment by rgerhards** [comment]
I agree with @davidelang - if you set the limit to 10% you actually limit the size of the in-memory queue. This is better done (and far more intuitive) by simply reducing the max size.

**Comment by JPvRiel** [comment]
Hi @davidelang & @rgerhards, thanks for looking at this suggestion and considering it. While I respect your decision closing this and leaving the behavior as is, I'd like to motivate that perhaps the design choice and different use-cases should be better documented?

I'd be willing to try contribute a doc PR. But first, please help me avoid confusion here and clarify if `queue.size` applies only to the in-memory portion, or the overall size of the queue?

- I thought `queue.size` is mem + disk msg count? 
- Put another way, do messages sent to disk still count towards this size limit? Or are messages sent to disk not counted towards the limit?

> why setup a large memory queue if you don't want it to be used?

I did not want a large memory queue. I just wanted a large disk queue segment with a modest mem queue segment in case upstream went offline in worst-case scenarios.

If `queue.size` applies to both mem and disk, then the rsyslog queue watermark defaults are leading to only allowing 30% use of disk and expecting RAM to handle 70% of the message queue size in worst-case scenarios!? 

I believe most users would want disk backup/capacity to be big relative to memory capacity. E.g. for a 1M size queue and the size is overall (mem + disk), then with defaults:

- 900K messages stay in RAM (high-watermark 90% default)
- At 900K, disk starts being used.
- At 1000K (just 10% more), messages start getting discarded already?
- Disk only stops being used if queue recovers to 700K.
- So at most, only 300K messages exist in the disk section of the overall queue while memory handles up to 900K.

Please maybe share what actually happens assuming I've misunderstood.

**Comment by rgerhards** [comment]
sry, need to be brief ATM: we are getting closer. The fundamental issue seems to be the max queue size. This is for the MEMORY queue, only. Disk queue is limited via disk space.

What IMHO helps is what is given in queue doc: a DA queue is two queues in one: a memory queue and a disk queue. And this is exactly how it is implemented.

**Comment by JPvRiel** [comment]
@rgerhards, ah, great, thanks for clearing up my misunderstanding. So `queue.size` only applies to memory, not overall. I'll look at the docs and think about sending a PR to make that clear.

**Comment by JPvRiel** [comment]
I was thinking of contributing to the docs with an e.g. for my use case, with is a DA action queue that needs to buffer when an output is down.

Wanted to check if I managed to make sense of how the parameters work. A summary of queue parameters as they apply to actions (not rulesets), plus my own e.g. where I think the defaults are not ideal and would suggest tweaking them:

| Param                  | Action Q Default        | Custom e.g. for DA action Q | Disk-assisted in-memory Q   | In-memory Q           | Disk Q                     |
|------------------------|-------------------------|-----------------|-----------------------------|-----------------------|----------------------------|
| `queue.size`           | 1000                    | 100000          | in-memory message count     | overall message count | N/A                        |
| `queue.maxFileSize`    | 1M                      |                 | on-disk file fragment size  | N/A                   | on-disk file fragment size |
| `queue.maxDiskSpace`   | 0 (no limit)            | 1073741824 (1G) | on-disk message storage use | N/A                   | message storage use        |
| `queue.highWaterMark`  | 90% of queue.size (900) |                 | in-memory message count     | N/A                   | N/A                        |
| `queue.lowWaterMark`   | 70% of queue.size (700) |                 | in-memory message count     | N/A                   | N/A                        |
| `queue.discardMark`    | 80% of queue.size (800) | 95000 (95%)     | in-memory message count     | overall message count | N/A?                       |
| `queue.fullDelaymark`  | 97% of queue.size (970) |                 | in-memory message count     | overall message count | N/A?                       |
| `queue.lightDelayMark` | 70% of queue.size (700) | 0 (disabled)    | in-memory message count     | overall message count | N/A?                       |

Potential problems with defaults as they apply to disk assisted queue mode might be:

- Light delay (70%) starts well before the queue uses disk buffering (90% highWaterMark) and source client systems (inputs) may not have large buffers and end up discarding messages client side before disk buffers on the relay server are put into use?
- Messages begin to be discarded at 70% before the queue uses disk buffering if `queue.discardSeverity` is set to anything lower than the default of 8?

E.g. params for a very busy 10K events per sec+ relay from syslog to kafka.

```text
    # queue config
    queue.type="LinkedList"
    queue.filename="fwd_kafka"
    # queue persistence and size limit
    queue.maxDiskSpace="1073741824"
    queue.maxFileSize="128m"
    queue.size="100000"
    queue.lightDelayMark="0"
    queue.discardMark="95000"
    queue.discardSeverity="7"
    queue.checkpointInterval="10000"
    queue.saveOnShutdown="on"
```
