### ISSUE TITLE
imfile: check that max message size limit is actually obeyed

### ISSUE THREAD

**Issue by rgerhards** [rsyslog/rsyslog#498]
There have been some reports that imfile generates messages larger than the max message size configured.

**Comment by mostolog** [comment]
I just tested this, and seems it's truncating messages. Is that the desired behaviour?

**Comment by rgerhards** [comment]
Yes, this seems reasonable to me. We could also split it to multiple messages (as a new feature request), but I am not sure if that's so useful. Note that the RFCs say that oversize parts of messages can be truncated, so we are inline with that.

**Comment by mostolog** [comment]
Then, I suggest closing both, this and https://github.com/rsyslog/rsyslog/issues/584
@davidelang ?

**Comment by davidelang** [comment]
I think leaving #584 open as an enhancement makes sense.

currently TCP messages that are excessively long get split into multiple messages, so no data is lost. It seems like it makes sense to have an option to do that for files with excessively long lines as well.

There are a number of "interesting" issues when you start getting into log size limits, I think we should have one place to be able to discuss options for dealing with them.

**Comment by mostolog** [comment]
To sum up: seems max message size is obeyed, but what happens with _rest of message_ is up to module. Ok!

**Comment by davidelang** [comment]
maxmessagesize is enforced on input, but I'm not sure what happens if you then create a longer message and send it out

**Comment by mostolog** [comment]
I believe that is exactly what I tested this morning...may I double check?

**Comment by davidelang** [comment]
Please do.

**Comment by mostolog** [comment]
Hi

With attached example.log (a file with 4 events, from 497 to 1838 chars) [example.log.txt](https://github.com/rsyslog/rsyslog/files/575072/example.log.txt) I have made 2 tests. Please, consider I'm using REDIS atm, so if you need a simpler/omfile test, just let me know. Also consider messaged are partly redacted/anonymized, but keep the essence.

**Just detected a new issue while testing this: https://github.com/rsyslog/rsyslog/issues/1248**

### Origin MaxMessageSize="1k" and target MaxMessageSize="2k"

First message (smaller) arrived correctly, the others weren't properly json parsed (because truncated) and went to the wrong list. **So, it seems messages are just truncated.**
```
127.0.0.1:6379> LPOP mykey
"{\"msg\":\"INFO class:000 - User - Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.\"\"file\":\"/logs/apps/app/app.log\"}"

127.0.0.1:6379> LPOP failed
"{\"msg\":\"INFO class:000 - User - Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt\",\"file\":\"/logs/apps/app/app.log\"}"
127.0.0.1:6379> LPOP failed
"{\"msg\":\"INFO class:000 - User - Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt\",\"file\":\"/logs/apps/app/app.log\"}"
```

### Origin MaxMessageSize="2k" and target MaxMessageSize="1k"

Three messages seem to be received properly on target.
```
127.0.0.1:6379> LPOP mykey
"{\"msg\":\" INFO class:000 - User - Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.\",\"file\":\"/logs/apps/app/app.log\"}"
127.0.0.1:6379> LPOP mykey
"{\"msg\":\" INFO class:000 - User - Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.\",\"file\":\"/logs/apps/app/app.log\"}"
127.0.0.1:6379> LPOP mykey
"{\"msg\":\" INFO class:000 - User - Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.\",\"file\":\"/logs/apps/app/app.log\"}"
```

Hope this help you diagnose this.

**Comment by mostolog** [comment]
@davidelang news? Triage?

**Comment by mostolog** [comment]
@davidelang @rgerhards  close?

**Comment by davidelang** [comment]
Is the problem still present? if not don't close.

**Comment by mostolog** [comment]
@davidelang I don't know. I replied what happened to me. https://github.com/rsyslog/rsyslog/issues/498#issuecomment-258801013
If that's how it's expected to work, it would be safe to close.

**Comment by rgerhards** [comment]
I think it is done, a quick source code review should be made to verify.

**Comment by rgerhards** [comment]
It actually is obeyed, but in an inconsitent manner: ```strmReadLine``` and ```strmReadMultiLine``` process it differently, and there are also two different config settings for it. Sounds like some cleanup is due...

**Comment by Benjamintf1** [comment]
```discardTruncatedMsg

type | default | mandatory | obsolete legacy directive
-- | -- | -- | --
binary | off | no | none


When messages are too long they are truncated and the following part is processed as a new message. When this parameter is turned on the truncated part is not processed but discarded.
```

It seems like this documentation implies that long log lines should be split, but in this issue it implies they will always be discarded?

**Comment by rgerhards** [comment]
@Benjamintf1 that's actually an issue with long-open issues: the code has changed since this issue was created. It's actually a change in a some unfortunate, because inconsistent, state. The setting only applies for multiline reads in which a regex is used.

I am now looking at the issue to finally resolve it, and it looks like we need to bear quite some legacy notes with it in the doc.

I am also not sure if the best way is to split messages. After all, from then on they appear as separate entities and some backends may possibly be pretty confused if the get the second (or even more) part(s) of the oversize message. The only correct cure is to increase the max message size limit.

**Comment by rgerhards** [comment]
we need to tackle this from a different angle: as @davidelang suggested, this should probably done inside a core component. MsgSub() and friends sound like a decent choice. I keep the associated PR open, just in case I can re-use something...
