### ISSUE TITLE
Would it be possible to load imuxsock in alpine docker without root?

### ISSUE THREAD

**Issue by narasimhan-coverwallet** [rsyslog/rsyslog#4983]
Hello! 

As part of a standards project at my company, we are rolling out `rsyslog` to all applications. However, we have hit a roadblock with the `imuxsock` module. 

The `imuxsock` module tries to acquire the socket under `/dev/log`. Normally this is fine, but we are running our applications in docker and they all use an `alpine` base image. To alleviate unwanted privilege escalation, the `$USER` that runs the application is set to be a non privileged user with `/sbin/nologin` privileges. 
This creates a situation where when `rsyslogd` is started, it is started as this non-root user and when it tries to load the `imuxsock` module, it fails as it is unable to acquire the `/dev/log` socket

### Expected behavior
```
$ rsyslogd -f rsyslog.conf -iNONE
 $ ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.0 159228 10052 pts/0    Ssl  Sep08   0:02 /usr/bin/qemu-x86_64 /bin/sh
$USER        24  0.0  0.0 172956 10712 ?        Ssl  Sep08   0:00 /usr/bin/qemu-x86_64 /usr/sbin/rsyslogd -f /project/rsyslog.conf -iNONE
root       297  0.0  0.0 158916  9096 ?        Rl+  Sep07   0:00 /bin/ps aux
```

### Actual behavior
```
 $ rsyslogd -f rsyslog.conf -iNONE
rsyslogd: cannot create '/dev/log': Permission denied [v8.2204.1 try https://www.rsyslog.com/e/2176 ]
rsyslogd: imuxsock does not run because we could not acquire any socket  [v8.2204.1]
rsyslogd: activation of module imuxsock failed [v8.2204.1]
```

### Steps to reproduce the behavior
Dockerfile:
```
FROM alpine

USER root
RUN update-ca-certificates --fresh
ENV DISABLE_SSL_REDIRECT=true
RUN apk add rsyslog
RUN chown -R $USER:$GROUP /var/log

USER $USER

RUN chmod +x ./entrypoint.sh

ENTRYPOINT [ "sh", "./entrypoint.sh" ]
```

Entrypoint.sh:
```
#!/bin/sh

cat << EOF > /project/rsyslog.conf
# rsyslog configuration file
\$WorkDirectory /var/lib/rsyslog

\$FileOwner $USER
\$FileGroup $GROUP
\$FileCreateMode 0640
\$DirCreateMode 0755
\$Umask 0022
module(load="imuxsock")
*.*   $SYSLOG_FILE
EOF
rsyslogd -f $DIR/rsyslog.conf -iNONE

# Command to run application
```

On running the container, we get the error above

### Environment
- rsyslog version: v8.2204.1
- platform: Alpine Docker

**Comment by rgerhards** [comment]
use `syssock.use="off"` in the module config object.

Doc: https://www.rsyslog.com/doc/v8-stable/configuration/modules/imuxsock.html

**Comment by narasimhan-coverwallet** [comment]
Thank you for the response. But this does not help as logs generated by the OS and other services are now not collected in the configured log files in the conf file. 

```
/project $ ./rsyslog-populator.sh
/project $ ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
$USER     1  1.8  0.0 159164 10044 pts/0    Ssl  06:31   0:00 /usr/bin/qemu-x86_64 /bin/sh
$USER    24 27.0  0.0 168104 11564 ?        Ssl  06:31   0:00 /usr/bin/qemu-x86_64 /usr/sbin/rsyslogd -f /project/rsyslog.conf -iNONE
$USER    27  0.0  0.0 158916 10780 ?        Rl+  02:03   0:00 /bin/ps aux
/project $ ls -alh /var/log/
total 12K
drwxr-xr-x    1 $USER $USER    4.0K Sep 12 06:31 .
drwxr-xr-x    1 root     root        4.0K Aug 10 02:10 ..
-rw-r--r--    1 $USER $USER       0 Sep 12 06:31 application.log
-rw-r--r--    1 $USER $USER       0 Sep 12 06:31 system.log
/project $ logger "test"
/project $ ls -alh /var/log/
total 12K
drwxr-xr-x    1 $USER $USER    4.0K Sep 12 06:31 .
drwxr-xr-x    1 root     root        4.0K Aug 10 02:10 ..
-rw-r--r--    1 $USER $USER       0 Sep 12 06:31 application.log
-rw-r--r--    1 $USER $USER       0 Sep 12 06:31 system.log
```

**Comment by rgerhards** [comment]
Well, if you need access to `/dev/log`, but do not have sufficient permissions, you run into an unsolvable situation. Or do I misunderstand you?

**Comment by narasimhan-coverwallet** [comment]
No :) This is all the information I need, just wanted to see if there was something else that can be done. I will take this feedback and re-imagine our solution. 
Thank you for your inputs
