### ISSUE TITLE
Data matched by Ruleset, still hitting syslog

### ISSUE THREAD

**Issue by ben-hart-jamf** [rsyslog/rsyslog#4984]
Ruleset's being matched, and following the action specified

Ruleset "ise20529" apparently ignored, syslog traffic to custom port being written to syslog instead

Create ruleset in custom conf under rsyslog.d, rsyslog.conf with port range for module IMUDP.

### Environment
- rsyslog version: 8.2.11.2
- platform: Ubuntu 22.04 LTS
- for configuration questions/issues, include rsyslog.conf and included config files
RSYSLOG.CONF

```
# /etc/rsyslog.conf configuration file for rsyslog
#################
#### MODULES ####
#################

$ModLoad imuxsock # provides support for local system logging
$ModLoad imklog   # provides kernel logging support (previously done by rklogd)
$ModLoad immark  # provides --MARK-- message capability

module(load="imudp")
input(type="imudp" port=["20514","20515","20516","20517","20518","20519","20520","20524","20525","20526","20527","20528","20529"]
      name="" name.appendPort="on")

module(load="impstats" interval="10" log.file="/var/log/rsyslog_stats.log" log.syslog="off")
###########################
#### GLOBAL DIRECTIVES ####
###########################
$ActionFileDefaultTemplate RSYSLOG_TraditionalFileFormat
$RepeatedMsgReduction on

$FileOwner syslog
$FileGroup adm
$FileCreateMode 0640
$DirCreateMode 0755
$Umask 0022
$PrivDropToUser syslog
$PrivDropToGroup syslog

$WorkDirectory /var/spool/rsyslog
$IncludeConfig /etc/rsyslog.d/*.conf
```

05-REMOTE-SYSLOG.CONF
```

##############
#                           #
#  RuleSets          #
#                           #
##############
#
#
# Below line added to stop Nessus attempts to below ports from being logged
if $fromhost-ip == '10.30.160.168/29' then stop
if $fromhost-ip == '10.100.161.160/28' then stop
if $fromhost-ip == '10.101.161.160/28' then stop
if $fromhost-ip == '10.103.161.160/28' then stop
if $fromhost-ip == '10.180.160.168/29' then stop
if $fromhost-ip == '10.144.161.160/28' then stop

ruleset(name="switches20514" queue.type="linkedlist" queue.workerThreads="4" queue.workerThreadMinimumMessages="20000"){
    action(type="omfile" file="/var/log/remote-syslog/switches.log" ioBufferSize="64k" flushOnTXEnd="off")
}

ruleset(name="routers20515" queue.type="linkedlist" queue.workerThreads="4" queue.workerThreadMinimumMessages="20000"){
    action(type="omfile" file="/var/log/remote-syslog/routers.log" ioBufferSize="64k" flushOnTXEnd="off")
}

ruleset(name="wlan20516" queue.type="linkedlist" queue.workerThreads="4" queue.workerThreadMinimumMessages="20000"){
    action(type="omfile" file="/var/log/remote-syslog/wlan.log" ioBufferSize="64k" flushOnTXEnd="off")
}

ruleset(name="firewalls20517" queue.type="linkedlist" queue.workerThreads="4" queue.workerThreadMinimumMessages="20000"){
    action(type="omfile" file="/var/log/remote-syslog/firewalls.log" ioBufferSize="64k" flushOnTXEnd="off")
}

ruleset(name="stealth20518" queue.type="linkedlist" queue.workerThreads="4" queue.workerThreadMinimumMessages="20000"){
    action(type="omfile" file="/var/log/remote-syslog/stealth.log" ioBufferSize="64k" flushOnTXEnd="off")
}

ruleset(name="nexus20519" queue.type="linkedlist" queue.workerThreads="4" queue.workerThreadMinimumMessages="20000"){
    action(type="omfile" file="/var/log/remote-syslog/nexus.log" ioBufferSize="64k" flushOnTXEnd="off")
}

ruleset(name="nas20520" queue.type="linkedlist" queue.workerThreads="4" 
queue.workerThreadMinimumMessages="20000"){
    action(type="omfile" file="/var/log/remote-syslog/nas.log" ioBufferSize="64k" flushOnTXEnd="off")
}

ruleset(name="esxi20524" queue.type="linkedlist" queue.workerThreads="4" queue.workerThreadMinimumMessages="20000"){
    action(type="omfile" file="/var/log/remote-syslog/esxi.log" ioBufferSize="64k" flushOnTXEnd="off")
}

ruleset(name="vcenter20525" queue.type="linkedlist" queue.workerThreads="4" queue.workerThreadMinimumMessages="20000"){
    action(type="omfile" file="/var/log/remote-syslog/vcenter.log" ioBufferSize="64k" flushOnTXEnd="off")
}

ruleset(name="ciscoasa20526" queue.type="linkedlist" queue.workerThreads="4" queue.workerThreadMinimumMessages="20000"){
    action(type="omfile" file="/var/log/remote-syslog/asa.log" ioBufferSize="64k" flushOnTXEnd="off")
}

ruleset(name="pwr20527" queue.type="linkedlist" queue.workerThreads="4" 
queue.workerThreadMinimumMessages="20000"){
    action(type="omfile" file="/var/log/remote-syslog/power.log" ioBufferSize="64k" flushOnTXEnd="off")
}

ruleset(name="amp20528" queue.type="linkedlist" queue.workerThreads="4" queue.workerThreadMinimumMessages="20000"){
    action(type="omfile" file="/var/log/remote-syslog/amp.log" ioBufferSize="64k" flushOnTXEnd="off")
}

ruleset(name="ise20529" queue.type="linkedlist" queue.workerThreads="4" 
queue.workerThreadMinimumMessages="20000"){
    action(type="omfile" file="/var/log/remote-syslog/ise.log" ioBufferSize="64k" flushOnTXEnd="off")
}

input(type="imudp" port="20514" ruleset="switches20514")
input(type="imudp" port="20515" ruleset="routers20515")
input(type="imudp" port="20516" ruleset="wlan20516")
input(type="imudp" port="20517" ruleset="firewalls20517")
input(type="imudp" port="20518" ruleset="stealth20518")
input(type="imudp" port="20519" ruleset="nexus20519")
input(type="imudp" port="20520" ruleset="nas20520")
input(type="imudp" port="20524" ruleset="esxi20524")
input(type="imudp" port="20525" ruleset="vcenter20525")
input(type="imudp" port="20526" ruleset="ciscoasa20526")
input(type="imudp" port="20527" ruleset="pwr20527")
input(type="imudp" port="20528" ruleset="amp20528")
input(type="imudp" port="20528" ruleset="ise20529")
```
Target ruleset is ise20529, source device verified sending to this host:port. Local FirewallD logs show correct traffic from correct source hitting correct port. Specified log file is not written to.

Thanks!

**Comment by davidelang** [comment]
please log the message using the RSYSLOGDebugFormat template so we can see all 
the details about it.

Also, check the config file with rsyslogd -N1

but one thing I see is that you have two sets of input stanzas that specify the 
same ports, but only one specifies a ruleset. I think the odds are good that 
that is causing the grief, and I expect that a syntax check will complain about 
the additional input on the same port.

David Lang

**Comment by ben-hart-jamf** [comment]
I can't believe it.. :SMH: I stared at this for so long that it's embarrassing. 

So yeah.. looks like the one server (out of three) that had identical configs, did not in this instance. So needless to say correcting that resolved the problem.  Something I'd like to ask, since the docs I've found aren't super clear to me.. using rsyslogd -N1, if I specify the rsyslog.conf (or run the command from /etc I get a correct response. Returns show if files have problems, or if not then it's clear. However if I specify an individual /ets/rsyslog.d/*.conf file like the one above I get repeatable errors relating to **parameters not known**, such as:

```
root@server:/etc/rsyslog.d# rsyslogd -N! -f 05-remote-syslog.conf
rsyslogd: input module name 'imudp' is unknown [v8.2208.0 try https://www.rsyslog.com/e/2209 ]
rsyslogd: error during parsing file 05-remote-syslog.conf, on or before line 87: parameter 'ruleset' not known -- typo in config file? [v8.2208.0 try https://www.rsyslog.com/e/2207 ]
rsyslogd: error during parsing file 05-remote-syslog.conf, on or before line 87: parameter 'port' not known -- typo in config file? [v8.2208.0 try https://www.rsyslog.com/e/2207 ]
rsyslogd: input module name 'imudp' is unknown [v8.2208.0 try https://www.rsyslog.com/e/2209 ]
rsyslogd: error during parsing file 05-remote-syslog.conf, on or before line 88: parameter 'ruleset' not known -- typo in config file? [v8.2208.0 try https://www.rsyslog.com/e/2207 ]
rsyslogd: error during parsing file 05-remote-syslog.conf, on or before line 88: parameter 'port' not known -- typo in config file? [v8.2208.0 try https://www.rsyslog.com/e/2207 ]
rsyslogd: input module name 'imudp' is unknown [v8.2208.0 try https://www.rsyslog.com/e/2209 ]
rsyslogd: error during parsing file 05-remote-syslog.conf, on or before line 89: parameter 'ruleset' not known -- typo in config file? [v8.2208.0 try https://www.rsyslog.com/e/2207 ]
```
...and so on thru line 99.

This actually caused me much headache last week thinking I had a problem with this file when in fact there was not. I realize that it's likely due to the modules not being loaded beforehand.  I can't suggest a better way for this to be handled but it's super confusing at best. 

Moving forward, for any future problems I will have to look up how to make use of that Template you suggested, I'm not familiar.

**Comment by davidelang** [comment]
telling rsyslog to check an individual included file doesn't make sense, because 
the file is dependent on other files. -N1 checks all files that are included, 
not just the top level file.

it's like printing out a 100 page computer program, then picking page 38 and 
trying to do checks on that page without seeing anything else, you aren't going 
to be able to tell if it's valid or not because you won't see all the stuff 
ahead of it.

David Lang

**Comment by ben-hart-jamf** [comment]
Totally understood, I just had not found those words, in that order.. in print. :)

Appreciate you David!

**Comment by rgerhards** [comment]
@ben-hart-jamf thx for the info, I will amend the following wording to the -N doc:

Please note that many distros have (unfortunately) begun to split the rsyslog
config into many small config snippets (a.k.a input files), usually in `/etc/rsyslog.d`. From
rsyslog's point of view, only a single config file exists and these snippets
are logically combined into that single config. For that reason, config checking
does usually **not** work on snippets. Because the interdependencies are missing.
For example, binding a ruleset to a module that is not possible if the ruleset is
loaded outside of the snippet.

**As a general guideline, never do config checks on config snippets. Always use
the main configuration file as a starting point** (usually  /etc/rsyslog.conf`).

**Comment by rgerhards** [comment]
PR https://github.com/rsyslog/rsyslog-doc/pull/988

**Comment by davidelang** [comment]
it may be worth noting the -o option to create the combined file for inspection 
at this point

David Lang
