### ISSUE TITLE
It build failed with different test cases on Debian riscv64

### ISSUE THREAD

**Issue by yuzibo** [rsyslog/rsyslog#4985]
### Expected behavior
It can be built on Debian riscv64 arch.
### Actual behavior
Failed. It fails with different test cases each time.
### Environment
- rsyslog version: 8.2208.0-1
- platform: Debian riscv64
- for configuration questions/issues, include rsyslog.conf and included config files
I am sorry if I bring the noisy here.

The fact is that it can be built on Debian riscv64 arch before 8.2208.0, the detailed build history is here:[8.2208.0-1](https://buildd.debian.org/status/logs.php?pkg=rsyslog&ver=8.2208.0-1&arch=riscv64&suite=sid)

So I suspect that rsyslog on 8.2208.0 was introduced by the thing that riscv64 does support.
So should I build it on riscv64 hardware from source code?

**Comment by rgerhards** [comment]
Note that the testbench has some inherent racyness. I guess this is what happened here.

**Comment by yuzibo** [comment]
Oops, sorry, this time it build [successfully](https://buildd.debian.org/status/logs.php?pkg=rsyslog&ver=8.2208.0-1&arch=riscv64&suite=sid), so I first close the issue and reopen it if there are any issues. sorry again

**Comment by bnoctis** [comment]
We have a -j1 flag in debian/rules i.e. makefile. If "racyness" means tests racing with each other, that should rule this out.

Did a few rounds of tests. All tests were run in a temporary chroot and on qemu-user rv64. Debian uses `sbuild` to automate a build and test procedure.

- First vanilla rounds have seen both passes and failures.
- Manual chroots see the `imfile-statefile-delete.sh` test fail.
- `sbuild` runs see `imfile-endregex-timeout.sh` fail.
- Lifting file descriptor limit (`ulimit -n`) didn't help.

**Comment by yuzibo** [comment]
I have to say, on my unmatched boards, it will fail due to different test cases. for example, xx.sh files
