### ISSUE TITLE
[RFE] Dropping capabilities on rsyslogd

### ISSUE THREAD

**Issue by Cropi** [rsyslog/rsyslog#4986]
### Problem description
Executing
```
pscap | grep rsyslogd
```
Shows that rsyslogd is running with full set of capabilities [1]:
```
1     19209 root        rsyslogd            full +
```

**Would it be possible to drop the capabilities to only the necessary set**, to minimize security exposure in case there was ever a mistake in a networking plugin or some other input resource?
Ideally, all apps running as uid 0 should drop privileges. Some can't for good reasons but many can.
In most of the scenarios, I could use the $PrivDropTo{User, Group} config directives to drop privileges by impersonating as another user and/or group after startup. However, occasionally I need to access some files that are not readable by the specified user/group e.g. when using the imfile module, so here root privileges are required but I would prefer to not give rsyslogd full set of capabilities.

### Proposed feature
Introduce ```libcap-ng``` [2] in rsyslog, which provides a clean mechanism to modify/drop capabilities. Thus, we could specify a set of caps that are needed for rsyslog to properly function, but nothing more. Enabled modules would also be included. The feature could be enabled via the "--enable-libcap-ng" configure option and would be turned off by default. Some plugins might require additional capabilities.

Let me know what are your thoughts on this topic. Thank you.

[1] https://man7.org/linux/man-pages/man7/capabilities.7.html
[2] https://github.com/stevegrubb/libcap-ng

**Comment by rgerhards** [comment]
@Cropi This sounds like a cool idea. Would you be willing to craft a PR?

**Comment by Cropi** [comment]
> @Cropi This sounds like a cool idea. Would you be willing to craft a PR?

Sure, I will do that. I just did not want to get into it without accepting the idea first.

**Comment by rgerhards** [comment]
I think it is a very useful addition! :-)

**Comment by rgerhards** [comment]
@Cropi Not sure.., do you think we need to add some specific info to the doc? If so, could you have a look?

**Comment by Cropi** [comment]
> @Cropi Not sure.., do you think we need to add some specific info to the doc? If so, could you have a look?

I will do my best to add it to the documentation, or at least mention it somewhere.

**Comment by rgerhards** [comment]
> I will do my best to add it to the documentation, or at least mention it somewhere.

Perfect. I think I will still merge the PR this week, so that it gets a chance to get used. In that sense, we may see some reports coming up. Just FYI.

**Comment by theodoresi** [comment]
Hi @Cropi , could you help me with this question? It is related to your PR https://unix.stackexchange.com/questions/747224/unable-to-run-rsyslogd-as-non-root-user-on-centos-stream-9

**Comment by Cropi** [comment]
> Hi @Cropi , could you help me with this question? It is related to your PR https://unix.stackexchange.com/questions/747224/unable-to-run-rsyslogd-as-non-root-user-on-centos-stream-9

Hello, this will be fixed via https://github.com/rsyslog/rsyslog/pull/5144.
