### ISSUE TITLE
re_extract fails in 8.12.0

### ISSUE THREAD

**Issue by moorecp** [rsyslog/rsyslog#499]
No matter what I do, my config from 8.9.0 doesn't work with `re_extract` in 8.12.0.

    rsyslogd: error during parsing file <config_file>, on or before line 4: rsyslog logic error in line 3752 of file rainerscript.c  [v8.12.0 try http://www.rsyslog.com/e/2207 ]
The line in question:

    set $!orgstr = re_extract($msg, "organization=([a-zA-Z0-9_]+),", 0, 1, "organization=unknown");
I've tried changing the 5th parameter to ZERO and "ZERO" since, based on what I see in the docs, what I currently have doesn't appear to be valid anymore, but it doesn't fix it.

It looks like when 5779b8337c5c5c74a978874825531da0a908b1dc and f9aa386e2f174e268b3e766885d43b25d7c9497e were added, it had the side effect of causing a check to ensure `re_extract` was only passing 2 parameters, which is not correct as `re_extract` requires 5 parameters.

Both `re_match` (2 parameters) and `re_extract` go through `initFunc_re_match(func);` and thus the 2 parameter check.
https://github.com/rsyslog/rsyslog/blob/7340a8dfd19d7125bc2af844f8c54fe00844048c/grammar/rainerscript.c#L3905

I might be way off here, but I'm guessing that's what's going on.

**Comment by chenryn** [comment]
+1. some fail in 8.13.0.

**Comment by rgerhards** [comment]
merged @janmejay 's patch, will be available in 8.14.0
