### ISSUE TITLE
how to change omfile output template format (was: remove rsyslog prefix)

### ISSUE THREAD

**Issue by mehrdad2000** [rsyslog/rsyslog#4996]
I have client and server of rsyslog, and need to remove prefix that insert by rsyslog in each line.
e.g. I try to send test message like below:

Client
`logger "Test message from the system"
`
Server
`2022-10-08T11:57:28+03:30 server3 root: Test message from the system
`

need to remove this part "**2022-10-08T11:57:28+03:30 server3 root:**"

should I edit server or client configuration?

FYI: all client and server configurations are default.

**Comment by davidelang** [comment]
first of, write the message out with the template RSSYLOG_DebugFormat so that 
you can see how the message is parsed and what the different variables contain, 
then you will want to create a new template that contains what you want.

My guess is that you want something similar to

$template rawformat,"%rawmsg\n"

David Lang


  On Sat, 
8 Oct 2022, Mehrdad wrote:

> I have client and server of rsyslog, and need to remove prefix that insert by rsyslog in each line.
> e.g. I try to send test message like below:
>
> Client
> `logger "Test message from the system"
> `
> Server
> `2022-10-08T11:57:28+03:30 server3 root: Test message from the system
> `
>
> need to remove this part "**2022-10-08T11:57:28+03:30 server3 root:**"
>
> should I edit server or client configuration?
>
>
> FYI: all client and server configurations are default.
>
>
>

**Comment by mehrdad2000** [comment]
@davidelang 

on server I have this line:

```
$template RemInputLogs, "/var/log/remotelogs/%$YEAR%%$MONTH%%$DAY%/%FROMHOST-IP%/%HOSTNAME%.log"
*.* ?RemInputLogs

```

would you please write how add the line that you mention?

**Comment by davidelang** [comment]
that template is for the filename to write the logs to

add the line that I gave you before, and then change your line to

?RemInputLogs;RSYSLOG_DebugFormat

or

?RemInputLogs;rawformat

(the *.* is a noop and can be eliminated with no change in functinoality)

David Lang

**Comment by mehrdad2000** [comment]
@davidelang would you please write complete version. i can't figure out how create template that set format and path at the same time.

**Comment by davidelang** [comment]
you can't.

you create one template to use for the path, and a different template to use for 
the format.

David Lang

**Comment by mehrdad2000** [comment]
@davidelang would you please write complete version.

**Comment by rgerhards** [comment]
see above (here replicated):

```
?RemInputLogs;RSYSLOG_DebugFormat
```

**Comment by rgerhards** [comment]
let me add: if this is still unclear to you, pls post a larger part of your config. We can then embed it, so that it is easier to understand for you.

**Comment by mehrdad2000** [comment]
@rgerhards as I mentioned there is no special thing on my config file and only need to do simple task with rsyslog.
I can’t find any clear example on the documents, that's why I ask here.


1-Again, In simple scenario what should I set on rsyslog server configuration to remove prefix that insert by rsyslog in each line?

Client
logger "Test message from the system" 
Server
2022-10-08T11:57:28+03:30 server3 root: Test message from the system

Expected output on rsyslog server:
Test message from the system

2-how can I set path of log in next step. Here is the path:
/var/log/remotelogs/%$YEAR%%$MONTH%%$DAY%/%FROMHOST-IP%/%HOSTNAME%.log

Please write full version of these two.

Thanks

**Comment by davidelang** [comment]
your config may be 'nothing special', but we don't know what it is, so we can't 
say how you should modify it.

I have given you the lines to add to your config, but I can't tell you where to 
put them without knowing what the rest of the config is.

add the line to create a rawtemplate (you can name it whatever you want)
then you change the line that writes the log out to use the new template for the 
format (without changing the path that it's writing to)

David Lang

**Comment by rgerhards** [comment]
@mehrdad2000 you make it hard for us to help you. With that attitude, chances are slim you will receive the simple solution, which was already posted twice here.

**Comment by rgerhards** [comment]
As a side note, rsyslog has no "default configuration". You distro may have, but we do not know which one it is. Depends also on distro version,.

**Comment by davidelang** [comment]
fresh server of what type? AIX? Solarix? OpenWRT? I don't know what their 
default configurations are.

you are asking volunteers to do work for you, please make it easy for us to help 
you.

David Lang

**Comment by mehrdad2000** [comment]
@rgerhards @davidelang Rhel 8, rsyslog 8.2208.0.

**Comment by davidelang** [comment]
without downloading and installing RHEL 8 on some system, that still doesn't 
tell me what it's default config is. I don't happen to have any such systems 
that I run.

David Lang

**Comment by davidelang** [comment]
yes, but since each distro (and each release of the distro) has different 
contents there (and now many are including files in /etc/rsyslog.conf.d or 
similar), I can't know what the config is.

David Lang

**Comment by mehrdad2000** [comment]
`# rsyslog configuration file

# For more information see /usr/share/doc/rsyslog-*/rsyslog_conf.html
# If you experience problems, see http://www.rsyslog.com/doc/troubleshoot.html

#### MODULES ####

# The imjournal module bellow is now used as a message source instead of imuxsock.
$ModLoad imuxsock # provides support for local system logging (e.g. via logger command)
$ModLoad imjournal # provides access to the systemd journal
#$ModLoad imklog # reads kernel messages (the same are read from journald)
#$ModLoad immark  # provides --MARK-- message capability

# Provides UDP syslog reception
$ModLoad imudp
$UDPServerRun 514

# Provides TCP syslog reception
$ModLoad imtcp
$InputTCPServerRun 514 

#### GLOBAL DIRECTIVES ####

# Where to place auxiliary files
$WorkDirectory /var/lib/rsyslog

# Use default timestamp format
$ActionFileDefaultTemplate RSYSLOG_TraditionalFileFormat

# File syncing capability is disabled by default. This feature is usually not required,
# not useful and an extreme performance hit
#$ActionFileEnableSync on

# Include all config files in /etc/rsyslog.d/
$IncludeConfig /etc/rsyslog.d/*.conf

# Turn off message reception via local log socket;
# local messages are retrieved through imjournal now.
$OmitLocalLogging on

# File to store the position in the journal
$IMJournalStateFile imjournal.state


#### RULES ####

# Log all kernel messages to the console.
# Logging much else clutters up the screen.
#kern.*                                                 /dev/console

# Log anything (except mail) of level info or higher.
# Don't log private authentication messages!
*.info;mail.none;authpriv.none;cron.none                /var/log/messages

# The authpriv file has restricted access.
authpriv.*                                              /var/log/secure

# Log all the mail messages in one place.
mail.*                                                  -/var/log/maillog


# Log cron stuff
cron.*                                                  /var/log/cron

# Everybody gets emergency messages
*.emerg                                                 :omusrmsg:*

# Save news errors of level crit and higher in a special file.
uucp,news.crit                                          /var/log/spooler

# Save boot messages also to boot.log
local7.*                                                /var/log/boot.log


# ### begin forwarding rule ###
# The statement between the begin ... end define a SINGLE forwarding
# rule. They belong together, do NOT split them. If you create multiple
# forwarding rules, duplicate the whole block!
# Remote Logging (we use TCP for reliable delivery)
#
# An on-disk queue is created for this action. If the remote host is
# down, messages are spooled to disk and sent when it is up again.
#$ActionQueueFileName fwdRule1 # unique name prefix for spool files
#$ActionQueueMaxDiskSpace 1g   # 1gb space limit (use as much as possible)
#$ActionQueueSaveOnShutdown on # save messages to disk on shutdown
#$ActionQueueType LinkedList   # run asynchronously
#$ActionResumeRetryCount -1    # infinite retries if host is down
# remote host is: name/ip:port, e.g. 192.168.0.1:514, port optional
#*.* @@remote-host:514
# ### end of the forwarding rule ###`

**Comment by davidelang** [comment]
This has an include statement for /etc/rsyslog.d/*.conf, what if anything, is in 
those files?

David Lang

**Comment by mehrdad2000** [comment]
@davidelang 
only one exist:
cat /etc/rsyslog.d/listen.conf

$SystemLogSocketName /run/systemd/journal/syslog
