### ISSUE TITLE
omkafka module issus when upgrading from 2208 to 2210

### ISSUE THREAD

**Issue by paalja** [rsyslog/rsyslog#5003]
### Expected behavior
omkafka module to load successfully after upgradring from 2208 to 2210

### Actual behavior
rsyslogd: version 8.2210.0, config validation run (level 2), master config rsyslog_etl_pja.conf
rsyslogd: could not load module '/usr/lib64/rsyslog/omkafka.so', errors: trying to load module /usr/lib64/rsyslog/omkafka.so: /usr/lib64/rsyslog/omkafka.so: undefined symbol: rd_kafka_purge [v8.2210.0 try https://www.rsyslog.com/e/2066 ]
rsyslogd: module name 'omkafka' is unknown [v8.2210.0 try https://www.rsyslog.com/e/2209 ]

### Steps to reproduce the behavior
upgrade from 2208 to 2210

### Environment
rsyslogd  8.2210.0 (aka 2022.10) compiled with:
        PLATFORM:                               x86_64-redhat-linux-gnu
        PLATFORM (lsb_release -d):
        FEATURE_REGEXP:                         Yes
        GSSAPI Kerberos 5 support:              Yes
        FEATURE_DEBUG (debug build, slow code): No
        32bit Atomic operations supported:      Yes
        64bit Atomic operations supported:      Yes
        memory allocator:                       system default
        Runtime Instrumentation (slow code):    No
        uuid support:                           Yes
        systemd support:                        Yes
        Config file:                            /etc/rsyslog.conf
        PID file:                               /var/run/syslogd.pid
        Number of Bits in RainerScript integers: 64

See https://www.rsyslog.com for more information.

Red Hat Enterprise Linux Server release 7.9 (Maipo)

**Comment by paalja** [comment]
seems to be the same issue as stated in #4966
RHEL 8 OS family error creating kafka handle and thread

**Comment by JPvRiel** [comment]
Actually while related, this an extra regression. `8.2208.0` could at least build/use the outdated librdkafka on a RHEL 7.x distro base. But latest `8.2210.0` can't even even fallback/use RHEL 7.x anymore. https://github.com/rsyslog/rsyslog/issues/4966 was related to it not being possible with RHEL 8.x. Now both of these major versions have ended up broken on `8.2210.0`
