### ISSUE TITLE
TCP forwarding does not appear to be working in 8.2210.0-1.el7 

### ISSUE THREAD

**Issue by jjasen** [rsyslog/rsyslog#5006]
### Expected behavior
Remote syslog server should receive messages 
### Actual behavior
No messages recieved
### Steps to reproduce the behavior
yum upgrade rsyslog -y && service rsyslogd restart
### Environment
- rsyslog version: 8.2210.0-1.el7 
- platform: CentOS 7, fully patched
- for configuration questions/issues, include rsyslog.conf and included config files
tail /etc/rsyslog.conf:
# Remote loghost
*.*                             @@<my-redacted-log-host-ip-here>
Example imfile:
$ModLoad imfile

ruleset(name="NetworkHttp"){
   action(name="ToLogHost" type="omfwd" Target="<my-redacted-log-host-ip-here>" Port="514" Protocol="tcp" queue.type="linkedlist" queue.filename="httpd-access_fwd" action.resumeRetryCount="-1" queue.saveOnShutdown="on" )
   stop
}

input(type="imfile" ruleset="NetworkHttp"
      File="/var/log/httpd/*access.log"
      Tag="httpd-access"
)

Please note, reverting clients to 8.2208.0-1.el7 solved the issue.

**Comment by davidelang** [comment]
to confirm, with the exact same config files, 8.2208 works but 8.2210 does not?

please double check that there are no complaints of syntax issues with rsyslogd 
-N1

we may end up needing a debug log for this, but that's a lot more work (to 
generate and to go through), so let's check the simple stuff first.

Please post your full config file.

Also, it's a good idea to enable impstats so that we can see what's being 
queued, etc.

David Lang

**Comment by davidelang** [comment]
Also, there is a bug being worked on related to the hostname, so double check if 
the logs are possibly being sent with the incorrect hostname.

David Lang

**Comment by jjasen** [comment]
"Also, there is a bug being worked on related to the hostname, so double check if the logs are possibly being sent with the incorrect hostname." -- 

Thanks for the feedback. Can this affect if you are using hostname to redirect logs on the receiving server? Otherwise, no, and odd that a version rollback on the client would resolve it. 

"to confirm, with the exact same config files, 8.2208 works but 8.2210 does not?"

Correct.

"please double check that there are no complaints of syntax issues with rsyslogd -N1"

It's past time to drop trying to name the state files, on my end. 

I owe a full configuration.

**Comment by jjasen** [comment]
OK. There was no variance in what got dropped into "locahost" on the central server, so I think this is a district problem.

**Comment by davidelang** [comment]
the pstats output on the sender will show if it thinks that it's delivering 
messages or if it thinks there are problems with the network connection.

David Lang

**Comment by jjasen** [comment]
Attached: [rsyslogd-o-out.txt](https://github.com/rsyslog/rsyslog/files/9879943/rsyslogd-o-out.txt)

**Comment by jjasen** [comment]
I will note, this seems to happen with Cent7 and Rocky 8 clients, across the board, using same/similar configurations. As in, every client updated to 8.2210 stopped forwarding via TCP -- about a dozen at this point. 

In each case, reverting to 8.2208 restores functionality.

**Comment by jjasen** [comment]
Preliminary testing indicates this was resolved in 8.202212. Tested on RHEL8 and RHEL7 types.

**Comment by rgerhards** [comment]
Then this was probably an issue with selector processing. We had this in the scheduled stable, and it took the next scheduled stable to fix it. If that was the issue, the daily stable alreday had it for some weeks. Just a reminder that using scheduled stable, by intent, delays fixes and new features.

**Comment by rgerhards** [comment]
just for reference: I refer to this bug: https://github.com/rsyslog/rsyslog/issues/4975
