### ISSUE TITLE
define pattern/path to store logs in rsyslog

### ISSUE THREAD

**Issue by mehrdad2000** [rsyslog/rsyslog#5013]
Hi I have rsyslog server that need to receive data from clients.

need rsyslog server do these steps after receive logs from clients:
1-set pattern of log file content.
2-store on specific path.

here is my rsyslog.conf file:

```
$template RemInputLogs, "%timegenerated:1:10:date-rfc3339% %timegenerated:12:23:date-rfc3339% %HOSTNAME% %msg%\n"
$template RemInputLogs, "/var/log/remotelogs/%$YEAR%%$MONTH%%$DAY%/%fromhost-ip%/%APP-NAME%.log"
*.* ?RemInputLogs

```
only step 2 work correctly, it will store log on defined path correctly, but does not apply pattern of content of log file.

Any idea?
Thanks

**Comment by rgerhards** [comment]
```
$template RemInputLogs, "%timegenerated:1:10:date-rfc3339% %timegenerated:12:23:date-rfc3339% %HOSTNAME% %msg%\n"
$template RemInputLogsPath, "/var/log/remotelogs/%$YEAR%%$MONTH%%$DAY%/%fromhost-ip%/%APP-NAME%.log"
*.* ?RemInputLogs;RemInputLogsPath
```

**Comment by mehrdad2000** [comment]
Thanks, Work perfectly.

**Comment by mehrdad2000** [comment]
@rgerhards is it possible to split hourly log file that generate by rsyslog server ?
e.g jboss.log is the main file and each hour create new file, in the end of the day 24 files has been created:
```
/var/log/remotelogs/20221105/192.168.1.1/jboss.log
/var/log/remotelogs/20221105/192.168.1.1/jboss.2022-11-05-00.log
/var/log/remotelogs/20221105/192.168.1.1/jboss.2022-11-05-01.log
/var/log/remotelogs/20221105/192.168.1.1/jboss.2022-11-05-02.log
/var/log/remotelogs/20221105/192.168.1.1/jboss.2022-11-05-03.log
...
```

Thanks

**Comment by davidelang** [comment]
yes, look at the man page on properties and you will see how you can get all the 
date/time fields you want to use in a filename template.

David Lang

**Comment by mehrdad2000** [comment]
@rgerhards Have another issue, I use local-use-6 on jboss server, and in rsyslog server automatically insert log into the "message" file too!
How can I prevent this?

I think it related to this line, because when I remove *.info it will fix!
*.info;mail.none;authpriv.none;cron.none                /var/log/messages

How can I prevent local-use-6 to insert into the "message" file?

I try this bu not work:
*.info;mail.none;authpriv.none;cron.none;local6.!=*                /var/log/messages

**Comment by davidelang** [comment]
when you get to complex filters, switch to the if..then format, it's far more 
flexible.

The legacy format does an or of all your conditions (as if you had each 
condition on a separate line)

David Lang

**Comment by mehrdad2000** [comment]
@davidelang @rgerhards would you please tell me how can I exclude local-use-6 from "message" this?

**Comment by mehrdad2000** [comment]
after several work around fixed, I use this line to exclude local6
*.info;mail.none;authpriv.none;cron.none;local6.none       /var/log/messages
