### ISSUE TITLE
$InputTCPServerStreamDriverMode legacy config stmt not honored

### ISSUE THREAD

**Issue by tblume** [rsyslog/rsyslog#5021]
### Expected behavior

Legacy configuration format supported according to documentation:

https://www.rsyslog.com/doc/master/configuration/conf_formats.html

-->
Which Format should I Use?

While rsyslog supports all three formats concurrently[...]
--<

### Actual behavior

Since:

https://github.com/rsyslog/rsyslog/issues/4816

the legacy format for configuring gtls doesn't seem to be supported anymore.

There is already the recommendation to not use legacy format.
However, it would be better to state in the documentation that some directives don't work anymore with legacy format.

### Steps to reproduce the behavior

Try to configure gtls in legacy configuration format with rsyslog >= 8.2106.0

**Comment by rgerhards** [comment]
legacy format is still supported. It is just not recommended to use it for complex things.

#4816 seems to have been prematurely closed. There was probably a config error in that case. So it would be best if you describe your actual problem. Still, it eases your life considerably if you stay away from legacy format for complex things.

**Comment by tblume** [comment]
Thanks for the quick response.

Actually the legacy format was used with older rsyslog versions and the customer is not ready to change that to the new format at the moment.
The rsyslog server with legacy config format stopped working after an update to rsyslog version 8.2106.

I suspected a problem with the order of the configuration directives and recommended to use the example config at:
https://www.rsyslog.com/doc/v5-stable/tutorials/tls_cert_server.html

So, it is now:

-->
$ModLoad imtcp

$DefaultNetstreamDriver gtls

$DefaultNetstreamDriverCAFile /root/CA/ca_cert.pem
$DefaultNetstreamDriverCertFile /root/server/server_cert.pem
$DefaultNetstreamDriverKeyFile /root/server/server_key.pem


$InputTCPServerStreamDriverAuthMode x509/name
$InputTCPServerStreamDriverPermittedPeer Log_Streaming_Client
$InputTCPServerStreamDriverMode 1
$InputTCPServerRun 10514
--<

still, the server fails in the TLS handshake therewith.
The debug logs indicate that the tls parameters don't seem to be recognized.
Using the new style syntax on the server:

module(load="imtcp" StreamDriver.Mode="1" StreamDriver.AuthMode="x509/name" PermittedPeer="Log_Streaming_Client")
$DefaultNetstreamDriver gtls
global(
    workDirectory="/var/log"
    defaultNetstreamDriverCAFile="/root/CA/ca_cert.pem"
defaultNetstreamDriverCertFile="/root/server/server_cert.pem"
    defaultNetstreamDriverKeyFile="/root/server/server_key.pem"
    parser.escapecontrolcharactertab="off"
)
input(type="imtcp" port="10514" KeepAlive="on")

the gtls logging works.

**Comment by rgerhards** [comment]
I can now confirm that `$InputTCPServerStreamDriverMode 1" is not correctly handled. Also, I found a bug inside the testbench where invalidly legacy code has been converted to new style where we wanted to test legacy ;-) So This functionality was actually no longer tested.
