### ISSUE TITLE
logical error in nsd_gtls.c

### ISSUE THREAD

**Issue by igorDi86** [rsyslog/rsyslog#5034]
Hello! 
I found unreachable code in nsd_gtls.c:649.
As you can see, expression iRet != RS_RET_CERT_MISSING &&iRet !=RS_RET_CERTKEY_MISSING is always true. And iRet != iRet != RS_RET_OK is always false, because iRet is not used here. Just defined above. So, this condition never works. Why so?

**Comment by rgerhards** [comment]
let's assume iRet := RS_RET_ERROR
then
iRet != RS_RET_OK -> True
iRet != RS_RET_CERT_MISSING -> True
iRet != RS_RET_CERTKEY_MISSING -> True
True && True && True -> True (overall result)

let's assume iRet := RS_RET_OK
then
iRet != RS_RET_OK -> False
iRet != RS_RET_CERT_MISSING -> True
iRet != RS_RET_CERTKEY_MISSING -> True
False && True && True -> False (overall result)

So your claim is false.

**Comment by igorDi86** [comment]
But iRet is defined as RS_RET_OK  at the top. And it is never used in function. So condition is only false.
And why this variable is here if it is not used during execution?

**Comment by rgerhards** [comment]
please read my response (and re-check boolean evaluations).

**Comment by igorDi86** [comment]
Yes, I looked carefully. Therefore, I repeat the question: why these conditions ( iRet != RS_RET_CERT_MISSING , iRet != RS_RET_CERTKEY_MISSING) are here? The variable will never take these values . Even in macro CHKgnutls it becomes RS_RET_GNUTLS_ERR if aborting.   Am I wrong that this is redundant code?
