### ISSUE TITLE
Segfault when loading lmnsd_gtls

### ISSUE THREAD

**Issue by kulikjak** [rsyslog/rsyslog#5058]
I've hit an interesting issue where when I try to load `lmnsd_gtls`, Rsyslog segfaults.

TBH I am not entirely sure what this module does (I didn't find anything in Rsyslog documentation and based on my quick online search, it seems not generally necessary to explicitly load) or if it expects additional configuration, but either way, it shouldn't break this way.

### Expected behavior
When I have `$ModLoad lmnsd_gtls` in `/etc/rsyslog.conf` and call e.g. `/usr/lib/rsyslog/rsyslogd -N1`, rsyslog doesn't segfault.

### Actual behavior
It does segfault.

The stack looks like this:
```
rsyslogd:core> ::stack
GetGnuTLSLoglevel()
lmnsd_gtls.so`nsd_gtlsClassInit+0x11d()
lmnsd_gtls.so`modInit+0x5d()
doModInit+0x52()
Load+0x2db()
doModLoad+0x5a()
processCfSysLineCommand+0x130()
cfsysline+0x46()
cnfDoCfsysline+0x23()
yylex+0x1eac()
yyparse+0x613()
load+0x1045()
initAll+0x63d()
main+0x72()
_start+0x43()
```
and I confirmed that `rsconf_t *cnf` passed into `GetGnuTLSLoglevel` is `NULL`;

### Steps to reproduce the behavior
All I did was to add `$ModLoad lmnsd_gtls` into `/etc/rsyslog.conf`.

### Environment
- rsyslog version: reproducible since version **8.2202.0** up until current **8.2212.0**. **8.2112.0** still works; I suspect that [this change](https://github.com/rsyslog/rsyslog/commit/321fc76f0f52523e085e68f6e0320a1577088c17) might be the culprit. 
- platform: Solaris 11.4 (both SPARC and Intel)

**Comment by rgerhards** [comment]
`lmnsd_*` are library modules for internal rsyslog use. It is not possible to load them manually, that's also why they are not documented. Why do you think you need to load it?

**Comment by kulikjak** [comment]
I don't think I need to load it - I just found this in an older (and possibly incorrect) Rsyslog configuration, and since it didn't cause any harm before and does now, I wanted to report it (I didn't expect segmentation fault) / confirm that it indeed shouldn't be needed.

Thanks for your confirmation; I think we can close this as invalid.
