### ISSUE TITLE
rsyslog file input

### ISSUE THREAD

**Issue by linuxthreads** [rsyslog/rsyslog#5066]
### Expected behavior
logfile to be send to server 192.168.1.120 via udp and Facility local1 and Sevirity notice
### Actual behavior
nothing

### Steps to reproduce the behavior
```
`/etc/rsyslog.d/01-dnsmasq.conf`

global(workDirectory="/var/spool/rsyslog")
 
module(load="imfile" PollingInterval="1") #needs to be done just once
 
# DNSMASQ
 input(type="imfile
        File="/var/log/dnsmasq.log"
        Tag="dnsmasq"
        StateFile="/var/spool/rsyslog/dnsmasq"
        Severity="notice"
        Facility="local1"
        ruleset="dnsmasq")
 ruleset(name="dnsmasq") {
     action(type="omfwd" Target="192.168.1.120" Port="514" Protocol="udp")
     stop
 }
```
### Environment
- [rsyslog version: `(rsyslogd: version 8.1901.0, config validation run (level 1)`
- platform: `Debian 10`

Thank you in advance

Regards

Juan

**Comment by rgerhards** [comment]
This sounds like the receive does either not accept messages from this host or does not listen on port 514/UDP.

**Comment by linuxthreads** [comment]
Hi,

Thank you for the reply,

I did check that with a tcpdump

`sudo tcpdump -i any port 514 and host 192.168.1.120 -nnSXXXX
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on any, link-type LINUX_SLL (Linux cooked), capture size 262144 bytes
^C
0 packets captured
0 packets received by filter
0 packets dropped by kernel`

but by the looks of it the rsyslog client is not sending

Regards

Juan

**Comment by rgerhards** [comment]
Can you write to a local log file? Thinking about selinux and friends.

Sent from phone, thus brief.

linuxthreads ***@***.***> schrieb am Fr., 13. Jan. 2023,
18:05:

**Comment by davidelang** [comment]
do your firewall rules allow this?

David Lang

**Comment by linuxthreads** [comment]
Hi Guys,

Thank you for all the help, I opt out for logstash log shipper, and seems to be working ok Thanks,

RSYSLOG is still an awesome product keep it up guys!

Regards

Juan
