### ISSUE TITLE
How can I use dynamic file names and custom templates at the same time

### ISSUE THREAD

**Issue by Darren-qu** [rsyslog/rsyslog#5072]
The template is as follows：
![image](https://user-images.githubusercontent.com/86956804/213354615-ade72b4a-ccc4-4497-8c23-dc7612139088.png)

The file name does not use variables. What should I do
![image](https://user-images.githubusercontent.com/86956804/213354786-2389c380-ff06-4638-a054-d4224d844637.png)

**Comment by davidelang** [comment]
look at the dynafile option, you define a template for the filename and declare 
it as a dynafile rather than using variables in a file option.

David Lang

**Comment by Darren-qu** [comment]
> 

Thanks for your answer David Lang
