### ISSUE TITLE
Should rsyslog verify the message from journald?

### ISSUE THREAD

**Issue by pengyi37** [rsyslog/rsyslog#5079]
I found the socket file `/run/systemd/journal/dev-log` has `rw-rw-rw-` permissions , so that all users could send message by this socket. For example, the normal user could use `logger` to send message and finally it will be written in system log files, which may cause log injection problem. Should rsyslog promise the validation of message from journal?

**Comment by rgerhards** [comment]
I would think this is a systemd bug.

**Comment by davidelang** [comment]
it's normal for all users to be able to generate log messages.

David Lang

**Comment by pengyi37** [comment]
Thx for the reply!
