### ISSUE TITLE
Changed rpm hashes and files on http://rpms.adiscon.com/

### ISSUE THREAD

**Issue by jsonar-cpapke** [rsyslog/rsyslog#5082]
It looks like many (most?) of the files on http://rpms.adiscon.com/ have been updated just today (2023-02-14) within a short timeframe. The files have new hashes now, and it is not clear if the contents have been modified or not. An example is in http://rpms.adiscon.com/v8-stable/epel-7/x86_64/RPMS/ 
![Screen Shot 2023-02-14 at 4 33 29 PM](https://user-images.githubusercontent.com/72050658/218894724-cbcf32c0-d4f1-47c3-9f59-44e1b2f2d162.png)

I'm not sure if this is the correct place to ask, but I'm hoping someone could tell me why the files changed/where else I should ask about it. Thanks!

**Comment by rgerhards** [comment]
The packages were signed with a more secure key to solve some issues. Please see https://github.com/rsyslog/rsyslog-pkg-rhel-centos/issues/126

**Comment by alorbach** [comment]
The gpg signatures have been updated with a new signing key, the content of the files remains unchanged.

If you turn o gpgcheck in your rsyslog.repo file, our old SHA1 Signing key broke installation on RHEL 9 as support has been removed for SHA1 Keys there. After evaluation, the best solution was to create a new SHA256 Signing key and remove the old SHA1 one from our repositories. As the old key was removed, all packages needed needed to resigned with the new key which is the reason why they all have been changed at a short timefame.

**Comment by jsonar-cpapke** [comment]
Thanks for the update!
