### ISSUE TITLE
Error in setting gnutlsPriorityString

### ISSUE THREAD

**Issue by Omidznlp** [rsyslog/rsyslog#5084]
### Expected behavior
Everything is OK When using TLS settings and my client transmits messages via TLS. I wish to configure the TLS version, cipher suites, and curves and still it works. 

### Actual behavior
I want to configure **gnutlsPriorityString** on both the client and server. When I configure it, everything is OK. However, when I restart the client to reconnect, it encounters the following issue: How do I configure gnutlsPriorityString in rsyslog client and rsyslog server? I reviewed all the instructions and past issues, but they did not assist me in resolving the issue.

**Server Side:** 
● rsyslog.service - System Logging Service
     Loaded: loaded (/lib/systemd/system/rsyslog.service; enabled; vendor preset: enabled)
     Active: active (running) since Wed 2023-02-15 16:04:32 UTC; 20s ago
TriggeredBy: ● syslog.socket
       Docs: man:rsyslogd(8)
             http://www.rsyslog.com/doc/
   Main PID: 146452 (rsyslogd)
      Tasks: 9 (limit: 1066)
     Memory: 1.8M
     CGroup: /system.slice/rsyslog.service
             └─146452 /usr/sbin/rsyslogd -n

Feb 15 16:04:32 RsyslogServer rsyslogd[146452]: imuxsock: Acquired UNIX socket '/run/systemd/journal/syslog' (fd 3) from systemd.  [v8.2212.0]
Feb 15 16:04:32 RsyslogServer rsyslogd[146452]: rsyslogd's groupid changed to 110
Feb 15 16:04:32 RsyslogServer rsyslogd[146452]: rsyslogd's userid changed to 104
Feb 15 16:04:32 RsyslogServer rsyslogd[146452]: [origin software="rsyslogd" swVersion="8.2212.0" x-pid="146452" x-info="https://www.rsyslog.com"] start
Feb 15 16:04:45 RsyslogServer rsyslogd[146452]: Syntax Error in Priority String: "Protocol=ALL,-SSLv2,-SSLv3,-TLSv1,-TLSv1.2"  [v8.2212.0 try https://w>
Feb 15 16:04:45 RsyslogServer rsyslogd[146452]: gnutls returned error on handshake: No or insufficient priorities were set.  [v8.2212.0 try https://www>
Feb 15 16:04:45 RsyslogServer rsyslogd[146452]: tcpsrv listener (inputname: 'imtcp') failed to process incoming connection with error -2083 [v8.2212.0 >
Feb 15 16:04:45 RsyslogServer rsyslogd[146452]: Syntax Error in Priority String: "Protocol=ALL,-SSLv2,-SSLv3,-TLSv1,-TLSv1.2"  [v8.2212.0 try https://w>
Feb 15 16:04:45 RsyslogServer rsyslogd[146452]: gnutls returned error on handshake: No or insufficient priorities were set.  [v8.2212.0 try https://www>
Feb 15 16:04:45 RsyslogServer rsyslogd[146452]: tcpsrv listener (inputname: 'imtcp') failed to process incoming connection 
**"Client Side"**

● rsyslog.service - System Logging Service
   Loaded: loaded (/lib/systemd/system/rsyslog.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2023-02-15 16:04:45 UTC; 2s ago
     Docs: man:rsyslogd(8)
           http://www.rsyslog.com/doc/
 Main PID: 4365 (rsyslogd)
    Tasks: 5 (limit: 4915)
   CGroup: /system.slice/rsyslog.service
           └─4365 /usr/sbin/rsyslogd -n

Feb 15 16:04:45 210-iBorder rsyslogd[4365]: imuxsock: Acquired UNIX socket '/run/systemd/journal/syslog' (fd 3) from systemd.  [v8.32.0]
Feb 15 16:04:45 210-iBorder systemd[1]: rsyslog.service: Job rsyslog.service/start finished, result=done
Feb 15 16:04:45 210-iBorder rsyslogd[4365]: rsyslogd's groupid changed to 106
Feb 15 16:04:45 210-iBorder systemd[1]: Started System Logging Service.
Feb 15 16:04:45 210-iBorder rsyslogd[4365]: rsyslogd's userid changed to 102
Feb 15 16:04:45 210-iBorder rsyslogd[4365]:  [origin software="rsyslogd" swVersion="8.32.0" x-pid="4365" x-info="http://www.rsyslog.com"] start
Feb 15 16:04:45 210-iBorder rsyslogd[4365]: unexpected GnuTLS error -54 in nsd_gtls.c:1838: Error in the pull function.  [v8.32.0 try http://www.rsyslog
Feb 15 16:04:45 210-iBorder rsyslogd[4365]: action 'action 13' suspended (module 'builtin:omfwd'), retry 0. There should be messages before this one giv
Feb 15 16:04:45 210-iBorder rsyslogd[4365]: unexpected GnuTLS error -54 in nsd_gtls.c:1838: Error in the pull function.  [v8.32.0 try http://www.rsyslog
Feb 15 16:04:45 210-iBorder rsyslogd[4365]: action 'action 13' suspended (module 'builtin:omfwd'), next retry is Wed Feb 15
### Steps to reproduce the behavior
Configure Client and Server to Use TLS, add gnutlsPriorityString options to the server, and then restart both client and server.
### Environment
- rsyslog version on both sides:
rsyslogd 8.32.0, compiled with:
	PLATFORM:				x86_64-pc-linux-gnu
	PLATFORM (lsb_release -d):		
	FEATURE_REGEXP:				Yes
	GSSAPI Kerberos 5 support:		Yes
	FEATURE_DEBUG (debug build, slow code):	No
	32bit Atomic operations supported:	Yes
	64bit Atomic operations supported:	Yes
	memory allocator:			system default
	Runtime Instrumentation (slow code):	No
	uuid support:				Yes
	systemd support:			Yes
	Number of Bits in RainerScript integers: 64

- platform for both sides: Ubuntu 18.04 
- for configuration questions/issues, include rsyslog.conf and included config files
**Server Side**
```
#  /etc/rsyslog.conf	Configuration file for rsyslog.
#
#			For more information see
#			/usr/share/doc/rsyslog-doc/html/rsyslog_conf.html
#
#  Default logging rules can be found in /etc/rsyslog.d/50-default.conf


#################
#### MODULES ####
#################

$ModLoad imuxsock # provides support for local system logging
$ModLoad imklog   # provides kernel logging support (previously done by rklogd)
#$ModLoad immark  # provides --MARK-- message capability

# provides UDP syslog reception
#$ModLoad imudp
#$UDPServerRun 514

# provides TCP syslog reception
#$ModLoad imtcp
#$InputTCPServerRun 514
module(load="imtcp" # TCP listener
    StreamDriver.Name="gtls"
    StreamDriver.Mode="1" # run driver in TLS-only mode
    StreamDriver.Authmode="anon"
    StreamDriver.CheckExtendedKeyPurpose="on"
    gnutlsPriorityString="Protocol=ALL,-SSLv2,-SSLv3,-TLSv1,-TLSv1.2"    
)

# make gtls driver the default and set certificate files
global(
DefaultNetstreamDriver="gtls"
DefaultNetstreamDriverCAFile="/etc/rsyslog-keys/ca.pem"
DefaultNetstreamDriverCertFile="/etc/rsyslog-keys/server-cert.pem"
DefaultNetstreamDriverKeyFile="/etc/rsyslog-keys/server-key.pem"
)
input(
        type="imtcp"
        Port="6514"
)
###########################
#### GLOBAL DIRECTIVES ####
###########################

#
# Use traditional timestamp format.
# To enable high precision timestamps, comment out the following line.
#
$ActionFileDefaultTemplate RSYSLOG_TraditionalFileFormat
$ActionSendStreamDriverPermittedPeer dhcp-blr-kmgm-blk2-4fl-6fl-10-178-22-154.in.oracle.com 
$ActionSendStreamDriverMode 1 # run driver in TLS-only mode
$ActionSendStreamDriverAuthMode x509/name
# Filter duplicated messages
$RepeatedMsgReduction on

#
# Set the default permissions for all log files.
#
$FileOwner syslog
$FileGroup adm
$FileCreateMode 0640
$DirCreateMode 0755
$Umask 0022
$PrivDropToUser syslog
$PrivDropToGroup syslog

#
# Where to place spool files
#
$WorkDirectory /var/spool/rsyslog

#
# Include all config files in /etc/rsyslog.d/
#
$IncludeConfig /etc/rsyslog.d/*.conf

```
**Client side:**
```
#  /etc/rsyslog.conf	Configuration file for rsyslog.
#
#			For more information see
#			/usr/share/doc/rsyslog-doc/html/rsyslog_conf.html
#
#  Default logging rules can be found in /etc/rsyslog.d/50-default.conf


#################
#### MODULES ####
#################

module(load="imuxsock") # provides support for local system logging
#module(load="immark")  # provides --MARK-- message capability

# provides UDP syslog reception
#module(load="imudp")
#input(type="imudp" port="514")

# provides TCP syslog reception
#module(load="imtcp")
#input(type="imtcp" port="514")

# provides kernel logging support and enable non-kernel klog messages
module(load="imklog" permitnonkernelfacility="on")

###########################
#### GLOBAL DIRECTIVES ####
###########################

#
# Use traditional timestamp format.
# To enable high precision timestamps, comment out the following line.
#
$ActionFileDefaultTemplate RSYSLOG_TraditionalFileFormat

# Filter duplicated messages
$RepeatedMsgReduction on

#
# Set the default permissions for all log files.
#
$FileOwner syslog
$FileGroup adm
$FileCreateMode 0640
$DirCreateMode 0755
$Umask 0022
$PrivDropToUser syslog
$PrivDropToGroup syslog

#
# Where to place spool and state files
#
$WorkDirectory /var/spool/rsyslog

#
# Include all config files in /etc/rsyslog.d/
#
$IncludeConfig /etc/rsyslog.d/*.conf
# TLS Configuration
#
$DefaultNetstreamDriver gtls
$DefaultNetstreamDriverCAFile /etc/rsyslog-keys/ca.pem
$DefaultNetstreamDriverCertFile /etc/rsyslog-keys/client-cert.pem
$DefaultNetstreamDriverKeyFile /etc/rsyslog-keys/client-key.pem
$ActionSendStreamDriverMode 1
$ActionSendStreamDriverAuthMode x509/name
$ActionSendStreamDriverPermittedPeer 192.168.50.40
# set server ip
*.* @@192.168.50.40:6514
#
# Handle when the syslog server is down
#
$ActionQueueFileName queue
$ActionQueueMaxDiskSpace 1g
$ActionQueuesaveOnShutdown on
$ActionQueueType LinkedList
$ActionResumeRetryCount -1
```

**Comment by alorbach** [comment]
The gnutlsPriorityString string you are using is for OpenSSL, but you are using the GnuTLS driver. 
Change 
StreamDriver.Name="gtls" to StreamDriver.Name="ossl", 
DefaultNetstreamDriver="gtls" to DefaultNetstreamDriver="ossl", and 
the gnutlsPriorityString  should work.

**Comment by Omidznlp** [comment]
@alorbach: thank you so much. Yes I found it at following link. Coresspondig systanx should be used if gtls or ossl drives are enabled.

https://www.rsyslog.com/doc/master/configuration/modules/imtcp.html

New in version 8.29.0.

This strings setting is used to configure driver specific properties. Historically, the setting was only meant for gnutls driver. However with version v8.1905.0 and higher, the setting can also be used to set openssl configuration commands.

For GNUTls, the setting specifies the TLS session’s handshake algorithms and options. These strings are intended as a user-specified override of the library defaults. If this parameter is NULL, the default settings are used. More information about priority Strings [here](https://gnutls.org/manual/html_node/Priority-Strings.html)

For OpenSSL, the setting can be used to pass configuration commands to openssl libray. OpenSSL Version 1.0.2 or higher is required for this feature. A list of possible commands and their valid values can be found in the documentation: https://www.openssl.org/docs/man1.0.2/man3/SSL_CONF_cmd.html
