### ISSUE TITLE
Does rsyslog support RFC6587?

### ISSUE THREAD

**Issue by yipeng0016** [rsyslog/rsyslog#5087]
Hi, I found rsyslog has support for RFC5424 and RFC3164, does rsyslog has the functionality to support RFC6587?

**Comment by davidelang** [comment]
Given that the RFC author is the primary developer of rsyslog, I expect the 
answer is yes (I haven't read through the RFC tp check that all the details are 
implemented, but going through the table of contents doesn't show anything 
unexpected)

David Lang

**Comment by rgerhards** [comment]
Indeed, rsyslog does, even before the RFC was out. It does so for ~20 yrs now.
