### ISSUE TITLE
Can't record local message when using port 514

### ISSUE THREAD

**Issue by pengyi37** [rsyslog/rsyslog#5111]
Hi, my rsyslog didn't log local messages when sending message to an address can't be pinged successfully. I also noticed that it's relavent to the port I used. If I used the port 11514, the rsyslog had the error  `cannot connect to x.x.x.x:11514: Permission denied` and  rsyslog could log local message in `/var/log/messages`. However, if I used the port 514, the rsyslog had the error `cannot connect to x.x.x.x:514: Connection timed out` and rsyslog didn't log any messages in `/var/log/messages`. So I wonder if port 514 has a special role in rsyslog? 
Here is my configure:
```
# rsyslog configuration file

# For more information see /usr/share/doc/rsyslog-*/rsyslog_conf.html
# or latest version online at http://www.rsyslog.com/doc/rsyslog_conf.html
# If you experience problems, see http://www.rsyslog.com/doc/troubleshoot.html

#### GLOBAL DIRECTIVES ####

# Where to place auxiliary files
global(workDirectory="/var/lib/rsyslog")

# Use default timestamp format
module(load="builtin:omfile" Template="RSYSLOG_TraditionalFileFormat")

#### MODULES ####

module(load="imuxsock"    # provides support for local system logging (e.g. via logger command)
       SysSock.Use="off") # Turn off message reception via local log socket;
                          # local messages are retrieved through imjournal now.
module(load="imjournal"             # provides access to the systemd journal
       StateFile="/run/log/imjournal.state") # File to store the position in the journal
#module(load="imklog") # reads kernel messages (the same are read from journald)
#module(load="immark") # provides --MARK-- message capability

$imjournalRatelimitInterval 0

# Include all config files in /etc/rsyslog.d/
include(file="/etc/rsyslog.d/*.conf" mode="optional")
#### RULES ####

# Log all kernel messages to the console.
# Logging much else clutters up the screen.
#kern.*                                                 /dev/console

# Log anything (except mail) of level info or higher.
# Don't log private authentication messages!
*.info;mail.none;authpriv.none;cron.none                /var/log/messages

# The authpriv file has restricted access.
authpriv.*                                              /var/log/secure

# Log all the mail messages in one place.
mail.*                                                  -/var/log/maillog


# Log cron stuff
cron.*                                                  /var/log/cron

# Everybody gets emergency messages
*.emerg                                                 :omusrmsg:*

# Save news errors of level crit and higher in a special file.
uucp,news.crit                                          /var/log/spooler

# Save boot messages also to boot.log
local7.*                                                /var/log/boot.log

# use an IP can't be pinged with port 514
*.* @@x.x.x.x:514

~

``` 
### Expected behavior
There is new message in `/var/log/messages`
### Actual behavior
There is no new message in `/var/log/messages`
### Steps to reproduce the behavior
Add an IP can't be pinged with port 514
### Environment
- rsyslog version: 8.2110

**Comment by davidelang** [comment]
On Sat, 8 Apr 2023, pengyi37 wrote:

> Hi, my rsyslog didn't log local messages when sending message to an address can't be pinged successfully. I also noticed that it's relavent to the port I used. If I used the port 11514, the rsyslog had the error  `cannot connect to x.x.x.x:11514: Permission denied` and  rsyslog could log local message in `/var/log/messages`. However, if I used the port 514, the rsyslog had the error `cannot connect to x.x.x.x:514: Connection timed out` and rsyslog didn't log any messages in `/var/log/messages`. So I wonder if port 514 has a special role in rsyslog?

the port 514 thing is probably a SELinux or AppArmor configuration, it's 
interesting that 'permission denied' and 'failed to connect' produce different 
results.

However, the fact that you fail to log local messages when your delivery to the 
remote system fails is the expected behavior. For each message, rsyslog goes 
down through the list of actions, and when it fails, all message processing 
stalls until enough retries fail to have rsyslog give up on that message, at 
which time it starts processing the next message (which fails at the same 
point), if you were to watch long enough, you would see a very slow trickle of 
messages written, and a lot of messages lost.

the way to address this is to setup a queue for the remote connection, but just 
setting up a queue doesn't solve the problem, because when that queue fills up 
(which could be a very long time if you allow it to use a disk queue and don't 
limit it's space, but that can be even worse as your entire system will halt 
when it's out of disk space), the main processing loop stalls in attempting to 
deliver messages to that queue. You also have to configure rules for the queue 
to tell it when to throw away messages permanently (look at the watermark 
settings in the queues)

it is strongly advised to switch to the action() syntax when adding queues as 
the old syntax was hard enough to understand that it misleads even experienced 
admins as to what is happening.

David Lang

> Here is my configure:
> ```
> # rsyslog configuration file
>
> # For more information see /usr/share/doc/rsyslog-*/rsyslog_conf.html
> # or latest version online at http://www.rsyslog.com/doc/rsyslog_conf.html
> # If you experience problems, see http://www.rsyslog.com/doc/troubleshoot.html
>
> #### GLOBAL DIRECTIVES ####
>
> # Where to place auxiliary files
> global(workDirectory="/var/lib/rsyslog")
>
> # Use default timestamp format
> module(load="builtin:omfile" Template="RSYSLOG_TraditionalFileFormat")
>
> #### MODULES ####
>
> module(load="imuxsock"    # provides support for local system logging (e.g. via logger command)
>       SysSock.Use="off") # Turn off message reception via local log socket;
>                          # local messages are retrieved through imjournal now.
> module(load="imjournal"             # provides access to the systemd journal
>       StateFile="/run/log/imjournal.state") # File to store the position in the journal
> #module(load="imklog") # reads kernel messages (the same are read from journald)
> #module(load="immark") # provides --MARK-- message capability
>
> $imjournalRatelimitInterval 0
>
> # Include all config files in /etc/rsyslog.d/
> include(file="/etc/rsyslog.d/*.conf" mode="optional")
> #### RULES ####
>
> # Log all kernel messages to the console.
> # Logging much else clutters up the screen.
> #kern.*                                                 /dev/console
>
> # Log anything (except mail) of level info or higher.
> # Don't log private authentication messages!
> *.info;mail.none;authpriv.none;cron.none                /var/log/messages
>
> # The authpriv file has restricted access.
> authpriv.*                                              /var/log/secure
>
> # Log all the mail messages in one place.
> mail.*                                                  -/var/log/maillog
>
>
> # Log cron stuff
> cron.*                                                  /var/log/cron
>
> # Everybody gets emergency messages
> *.emerg                                                 :omusrmsg:*
>
> # Save news errors of level crit and higher in a special file.
> uucp,news.crit                                          /var/log/spooler
>
> # Save boot messages also to boot.log
> local7.*                                                /var/log/boot.log
>
> # use an IP can't be pinged with port 514
> *.* @@x.x.x.x:514
>
> ~
>
> ```
> ### Expected behavior
> There is new message in `/var/log/messages`
> ### Actual behavior
> There is no new message in `/var/log/messages`
> ### Steps to reproduce the behavior
> Add an IP can't be pinged with port 514
> ### Environment
> - rsyslog version: 8.2110
>
>
>
>
