### ISSUE TITLE
Apr 11 06:21:44 bxxxxxxxx rsyslogd: netstream session 0x7f1dfc041300 from 157.x.x.x will be closed due to error [v8.2001.0 try https://www.rsyslog.com/e/2089 ]

### ISSUE THREAD

**Issue by Ismailctest** [rsyslog/rsyslog#5113]
### Expected behavior
We need to collect tcp 6514 logs to new file.
### Actual behavior
We can see the log in tcp dump & seeing 2089 error in syslog.log and not getting the logs
### Steps to reproduce the behavior
Presently, we are collecting logs from another server with port 6514 & getting logs properly. (Existing conf adding below)
We need to collect logs from new server as well with same port, logs should be forwarded to new path.
Existing configuration:
------------------------
global( 

    defaultNetstreamDriver         = "gtls" 
    defaultNetstreamDriverCAFile   = "/etc/rsyslog-keys/ca.crt" 
    defaultNetstreamDriverCertFile = "/etc/rsyslog-keys/xxxx.crt" 
    defaultNetstreamDriverKeyFile  = "/etc/rsyslog-keys/xxxx.key" 

) 

module( 

    load                  = "imtcp" 
    StreamDriver.Name     = "gtls" 
    StreamDriver.Mode     = "1" 
    StreamDriver.AuthMode = "anon" 
) 
template (name="remotelogs" type="string" string= %rawmsg-after-pri%\n") 
ruleset(name="remote") { 
    action(type="omfile" File="/var/log/remote_logs/data.log" Template="remotelogs") 
    stop 
} 

input(type="imtcp" port="6514" ruleset="remote") 

### Environment
- rsyslog version: rsyslogd  8.2001.0 (aka 2020.01)
- platform:Ubuntu 20.04.4 LTS, Focal, x86_64-pc-linux-gnu
- for configuration questions/issues, include rsyslog.conf and included config files

**Comment by davidelang** [comment]
there has been a lot of work on encryption since 2020. Please upgrade to the 
current release and see if you still hve the problem.

If you do, we will probably need to see debug logs to get an idea of what the 
error is that it's reporting.

David Lang

**Comment by rgerhards** [comment]
@Ismailctest Did you check other error messages in your syslog log? This message should be preceded by the abort cause. However, I had a quick look at the code and there may be some cases where no real error cause is given. If so, only the debug log will show.

In that case please create a debug log. Instructions: https://www.rsyslog.com/doc/v8-stable/troubleshooting/howtodebug.html

Be sure that the problem in question occurs at least once during the debug run. Once this is done, please post the debug log (e.g. via pastbin or github). After that, we can review the contents and check how exactly rsyslog processing worked.
