### ISSUE TITLE
Metadata filename seems to be empty

### ISSUE THREAD

**Issue by redat00** [rsyslog/rsyslog#5116]
Not sure wether this is a bug or an error on my side (which I would say is more probable).. But I'm not able to use the `filename` metada inside of a template as it is empty.

Here is the configuration on my client that sends logs : 
```
# nginx access logs
input(
        type="imfile"
        File="/var/log/nginx/*access.log"
        Tag="nginx-access"
        Severity="info"
        addMetadata="on"
)

# nginx error logs
input(
        type="imfile"
        File="/var/log/nginx/*error.log"
        Tag="nginx-error"
        Severity="error"
        addMetadata="on"
)
```

And the configuration on the rsyslog server that receives logs : 
```
$template nginx,"/var/log/clients/%fromhost%/nginx/%$!metadata!filename%.log"    
if $syslogtag contains 'nginx' then ?nginx
```

I was expecting to be able to use the `%$!metadata!filename%` to recreate the same file but on the syslog server. 
However this result in a file called `.log` which would mean that somehow the `%$!metadata!filename%` is empty.

### Environment
- rsyslog version: `8.2102.0 (aka 2021.02)`
- platform: `Debian GNU/Linux 11 (bullseye)`

**Comment by rgerhards** [comment]
The issue is that the variables are local the the system where they are set. If you want to use them on a remote system, you need to transfer them. It is highly suggested to transfer only what you need.

This is usually done be creating a special template, use that with omfwd, and then extract the data at the receiver side again.

**Comment by redat00** [comment]
I struggled a lot with RELP at first but in the end I was able to make it works. 

Thanks for the direction !
