### ISSUE TITLE
rsyslogd: child process (pid xxx) exited with status 1 [v8.2102.0]

### ISSUE THREAD

**Issue by piddalagi** [rsyslog/rsyslog#5117]
### Expected behavior
rsyslog should start successfully.

### Actual behavior
rsyslog keeps exiting with below error till it reaches systenctl default restart threshold and then enters in dead and disabled state.

rsyslogd: child process (pid 13808) exited with status 1 [v8.2102.0]

### Steps to reproduce the behavior
I saw it typically when kernel is upgraded. 
Sorry I dont have exact steps of issue recreation.
After systemctl tries to start rsyslog with default threshold number of times, it will label rsyslog as dead and put it in disabled state, as below.

service rsyslog status
● rsyslog.service - System Logging Service
   Loaded: loaded (/lib/systemd/system/rsyslog.service; disabled; vendor preset: enabled)
   Active: inactive (dead)
     Docs: man:rsyslogd(8)
           man:rsyslog.conf(5)
           https://www.rsyslog.com/doc/

Apr 02 23:35:18 systemd[1]: rsyslog.service: Succeeded.
Apr 02 23:35:18  systemd[1]: Stopped System Logging Service.
Apr 02 23:35:18  systemd[1]: Starting System Logging Service...
Apr 02 23:35:18 systemd[1]: Dependency failed for System Logging Service.
Apr 02 23:35:18 systemd[1]: rsyslog.service: Job rsyslog.service/start failed with result 'dependency'.
Apr 12 23:37:35 systemd[1]: Stopping System Logging Service...
Apr 12 23:37:35 systemd[1]: rsyslog.service: Succeeded.
Apr 12 23:37:35 systemd[1]: Stopped System Logging Service.
Apr 12 23:37:35 systemd[1]: Dependency failed for System Logging Service.
Apr 12 23:37:35 systemd[1]: rsyslog.service: Job rsyslog.service/start failed with result 'dependency'.

### Environment
version v8.2102.0

It would be helpful if there is more information available on why child exited with more elaborated debugging info.

Is this a known issue?
If yes, please point me to the ongoing discussion.
If fixed, then please point me to relevant patch and so that I can incorporate the fix.

Below is the logs which I captured during issue state.

/var/log/messages:Apr  3 05:08:01 NONAME rsyslogd: child process (pid 13808) exited with status 1 [v8.2102.0]
/var/log/messages:Apr  3 05:08:01 NONAME rsyslogd: omprog: program '/sbin/rsys2evlog' (pid 13808) terminated; will be restarted [v8.2102.0 try https://www.rsyslog.com/e/2119 ]
/var/log/messages:Apr  3 05:08:01 NONAME rsyslogd: action 'action-0-omprog' suspended (module 'omprog'), retry 0. There should be messages before this one giving the reason for suspension. [v8.2102.0 try https://www.rsyslog.com/e/2007 ]
/var/log/messages:Apr  3 05:08:02 NONAME rsyslogd: action 'action-0-omprog' resumed (module 'omprog') [v8.2102.0 try https://www.rsyslog.com/e/2359 ]
/var/log/messages:Apr  3 05:08:06 NONAME rsyslogd: child process (pid 22870) exited with status 1 [v8.2102.0]
/var/log/messages:Apr  3 05:08:06 NONAME rsyslogd: omprog: program '/sbin/rsys2evlog' (pid 22870) terminated; will be restarted [v8.2102.0 try https://www.rsyslog.com/e/2119 ]
/var/log/messages:Apr  3 05:08:06 NONAME rsyslogd: action 'action-0-omprog' suspended (module 'omprog'), retry 0. There should be messages before this one giving the reason for suspension. [v8.2102.0 try https://www.rsyslog.com/e/2007 ]
/var/log/messages:Apr  3 05:08:07 NONAME rsyslogd: action 'action-0-omprog' resumed (module 'omprog') [v8.2102.0 try https://www.rsyslog.com/e/2359 ]
/var/log/messages:Apr  3 05:08:20 NONAME rsyslogd: child process (pid 23135) exited with status 1 [v8.2102.0]
/var/log/messages:Apr  3 05:08:20 NONAME rsyslogd: omprog: program '/sbin/rsys2evlog' (pid 23135) terminated; will be restarted [v8.2102.0 try https://www.rsyslog.com/e/2119 ]
/var/log/messages:Apr  3 05:08:20 NONAME rsyslogd: action 'action-0-omprog' suspended (module 'omprog'), retry 0. There should be messages before this one giving the reason for suspension. [v8.2102.0 try https://www.rsyslog.com/e/2007 ]
/var/log/messages:Apr  3 05:08:21 NONAME rsyslogd: action 'action-0-omprog' resumed (module 'omprog') [v8.2102.0 try https://www.rsyslog.com/e/2359 ]
/var/log/messages:Apr  3 05:08:22 NONAME rsyslogd: child process (pid 25828) exited with status 1 [v8.2102.0]
/var/log/messages:Apr  3 05:08:22 NONAME rsyslogd: omprog: program '/sbin/rsys2evlog' (pid 25828) terminated; will be restarted [v8.2102.0 try https://www.rsyslog.com/e/2119 ]
/var/log/messages:Apr  3 05:08:22 NONAME rsyslogd: action 'action-0-omprog' suspended (module 'omprog'), retry 0. There should be messages before this one giving the reason for suspension. [v8.2102.0 try https://www.rsyslog.com/e/2007 ]
/var/log/messages:Apr  3 05:08:23 NONAME rsyslogd: action 'action-0-omprog' resumed (module 'omprog') [v8.2102.0 try https://www.rsyslog.com/e/2359 ]
/var/log/messages:Apr  3 05:08:24 NONAME rsyslogd: child process (pid 25843) exited with status 1 [v8.2102.0]
/var/log/messages:Apr  3 05:08:24 NONAME rsyslogd: omprog: program '/sbin/rsys2evlog' (pid 25843) terminated; will be restarted [v8.2102.0 try https://www.rsyslog.com/e/2119 ]
/var/log/messages:Apr  3 05:08:24 NONAME rsyslogd: action 'action-0-omprog' suspended (module 'omprog'), retry 0. There should be messages before this one giving the reason for suspension. [v8.2102.0 try https://www.rsyslog.com/e/2007 ]
/var/log/messages:Apr  3 05:08:25 NONAME rsyslogd: action 'action-0-omprog' resumed (module 'omprog') [v8.2102.0 try https://www.rsyslog.com/e/2359 ]
/var/log/messages:Apr  3 05:09:10 NONAME rsyslogd: child process (pid 25878) exited with status 1 [v8.2102.0]
/var/log/messages:Apr  3 05:09:10 NONAME rsyslogd: omprog: program '/sbin/rsys2evlog' (pid 25878) terminated; will be restarted [v8.2102.0 try https://www.rsyslog.com/e/2119 ]
/var/log/messages:Apr  3 05:09:10 NONAME rsyslogd: action 'action-0-omprog' suspended (module 'omprog'), retry 0. There should be messages before this one giving the reason for suspension. [v8.2102.0 try https://www.rsyslog.com/e/2007 ]
/var/log/messages:Apr  3 05:09:11 NONAME rsyslogd: action 'action-0-omprog' resumed (module 'omprog') [v8.2102.0 try https://www.rsyslog.com/e/2359 ]
/var/log/messages:Apr  3 05:09:15 NONAME rsyslogd: child process (pid 7734) exited with status 1 [v8.2102.0]
/var/log/messages:Apr  3 05:09:15 NONAME rsyslogd: omprog: program '/sbin/rsys2evlog' (pid 7734) terminated; will be restarted [v8.2102.0 try https://www.rsyslog.com/e/2119 ]

**Comment by davidelang** [comment]
what is /sbin/rsys2evlog? that appears to be the program that's failing 
(normally we need the full rsyslog config to diagnose anything, but the errors 
you are reporting indicate that you have soem omprog config using this program 
and it's this program that is failing.

David Lang

**Comment by piddalagi** [comment]
Sorry I forgot to add the config before.

# cat /lib/systemd/system/rsyslog.service
[Unit]
Description=System Logging Service
Requires=syslog.socket
Documentation=man:rsyslogd(8)
Documentation=man:rsyslog.conf(5)
Documentation=https://www.rsyslog.com/doc/

[Service]
Type=notify
ExecStart=/usr/sbin/rsyslogd -n -iNONE
StandardOutput=null
Restart=on-failure

# Increase the default a bit in order to allow many simultaneous
# files to be monitored, we might need a lot of fds.
LimitNOFILE=16384

[Install]
WantedBy=multi-user.target
Alias=syslog.service
#
-------------------------------------------------------------------------------------------

#  /etc/rsyslog.conf    Configuration file for rsyslog.
#  This file is for rsys2evlog - a utility to write log entries to evlog

#################
#### MODULES ####
#################
module(load="omprog")

template(name="evlTemplate" type="string"
         string="%syslogfacility% %syslogpriority% |%TIMESTAMP:::date-rfc3164% %HOSTNAME% %syslogtag%%msg:::sp-if-no-1st-sp%%msg:::drop-last-lf%\n"
        )

action( type="omprog"
        binary="/sbin/rsys2evlog"
        template="evlTemplate")

I will check on /sbin/rsys2evlog and get back shortly.

**Comment by rgerhards** [comment]
This looks like a systemd error condition that is not related to rsyslog but some dependency (which I do not see in the unit file):

```
Apr 02 23:35:18 systemd[1]: Starting System Logging Service...
Apr 02 23:35:18 systemd[1]: Dependency failed for System Logging Service.
Apr 02 23:35:18 systemd[1]: rsyslog.service: Job rsyslog.service/start failed with result 'dependency'.
```

**Comment by piddalagi** [comment]
Hi Team,
I got to know that rsys2evlog is fork-exec when rsyslogd starts. The child rsys2evlog exits with code 1. 
The systemctl retries threshold number of time to start rsyslog and then label the rsyslog as dead and disabled.
I will try to analyze as to why the rsys2evlog is exiting. 

Many thanks for quick suport.
