### ISSUE TITLE
Source code installation failed for rsyslog-7.4.4

### ISSUE THREAD

**Issue by hyderaliva** [rsyslog/rsyslog#5133]
### Expected behavior
Source code installation should work without any issues
### Actual behavior
Source code compilation failed while executing 'sudo make' command
### Environment
- rsyslog version: rsyslog-7.4.4
- platform: Ubuntu 20.04

Followed official documentations for source code installation, installed all dependent package except following.
```
liblogging-stdlog-dev 
libgcrypt11-dev
libjson-c2
libjson0-dev
```

sudo ./configure command ran successfully but the next command from list 'sudo make' failed with below mentioned errors

` sudo make
make  all-recursive
make[1]: Entering directory '/home/hyder/rsyslog-7.4.4'
Making all in doc
make[2]: Entering directory '/home/hyder/rsyslog-7.4.4/doc'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/hyder/rsyslog-7.4.4/doc'
Making all in compat
make[2]: Entering directory '/home/hyder/rsyslog-7.4.4/compat'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/hyder/rsyslog-7.4.4/compat'
Making all in runtime
make[2]: Entering directory '/home/hyder/rsyslog-7.4.4/runtime'
  CC     librsyslog_la-msg.lo
msg.c:46:10: fatal error: json/json_object_private.h: No such file or directory
   46 | #include <json/json_object_private.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [Makefile:930: librsyslog_la-msg.lo] Error 1
make[2]: Leaving directory '/home/hyder/rsyslog-7.4.4/runtime'
make[1]: *** [Makefile:801: all-recursive] Error 1
make[1]: Leaving directory '/home/hyder/rsyslog-7.4.4'
make: *** [Makefile:573: all] Error 2` 

Few of the dependent packages not installed on Ubuntu 20.04, can you please suggest how to install rsyslog using source code.

**Comment by hyderaliva** [comment]
Hi David,

Thanks for the inputs, we are using rsyslog 7.x due to MAXFUNIX parameters.  It provides flexibility to adjust maximum unix sockets for rsyslog whereas latest version have default 50 sockets only and doesn't allow to modify.

Would be very helpful if you could provide latest version details that has MAXFUNIX parameters configured, i checked on latest version MAXFUNIX parameter is removed from config(rsyslog-7.4.4/plugins/imuxsock/imuxsock.c).

Thanks,
Hyder

**Comment by davidelang** [comment]
The core devs are in Germany, so they will be waking up in a few hours and will 
see this then.

but since you are compiling from source, can't you just change the value in the 
source?

David Lang

**Comment by hyderaliva** [comment]
The latest version of rsyslog doesn't have `MAXFUNIX `parameter in `plugins/imuxsock/imuxsock.c` file, that's why we are using old version.

**Comment by rgerhards** [comment]
> The latest version of rsyslog doesn't have `MAXFUNIX `parameter in `plugins/imuxsock/imuxsock.c`

The reason is quite simple: it's no longer needed as rsyslog automatically adjust the array size to the configured number of listeners ;-)

**Comment by hyderaliva** [comment]
Hi Rainer,

Thanks for the inputs, we have specific requirement wherein we want to set  MAXFUNIX  value to higher value(>50).
How can we achieve this thing on latest version, any suggestion or inputs would really help.

Thanks,
Hyder

**Comment by rgerhards** [comment]
> we have specific requirement wherein we want to set MAXFUNIX value to higher value(>50).

jupp - the current limit is "limited by system memory" ;-) That probably is higher than 50...

**Comment by hyderaliva** [comment]
Can we modify this limit using any config parameters.

**Comment by davidelang** [comment]
He is saying that there is now no hard coded limit, you should be able to have 
thousands without needing to do any config change.

The parameter isn't there any more as it's not needed.

David Lang

**Comment by hyderaliva** [comment]
Thanks for the clarification David.
