### ISSUE TITLE
Parsing field problem  - $Hostname is always set

### ISSUE THREAD

**Issue by shinigami35** [rsyslog/rsyslog#5134]
Hello, 

I use Rsyslog to centralize logs from several others sources.

### Expected behavior
I need to use the var "$Hostname" to filter sources of logs with a lookup table. In my problem, the "$hostname" is always full with the source IP of the message.

### Actual behavior

In the documentation of Rsyslog, the "$hostname" is extract from the message. I guess that if the hostname is not in the message received the "$hostname" will be empty. But not, the field "$Hostname" is always fill with the field "$fromhost-IP".

### Steps to reproduce the behavior

For exemple, if I send the logs :
`<134>May 10 12:24:03 test_source This is a test`

I got this  (this is what I want) :
`FROMHOST: '10.122.226.113', fromhost-ip: '10.122.226.113', HOSTNAME: 'test_source', PRI: 134,
syslogtag 'This', programname: 'This', APP-NAME: 'This', PROCID: '-', MSGID: '-',
TIMESTAMP: 'May 10 12:24:03', STRUCTURED-DATA: '-',
msg: ' is a test#015'
escaped msg: ' is a test#015'
inputname: imtcp rawmsg: '<134>May 10 12:24:03 test_source This is a test#015'
$!:
$.:
$/:`

But if i send a log ike this without hostname inside, I got this : 
`FROMHOST: '10.10.10.10', fromhost-ip: '10.10.10.10', HOSTNAME: '10.10.10.10', PRI: 190,
syslogtag 'timestamp=1683715550', programname: 'timestamp=1683715550', APP-NAME: 'timestamp=1683715550', PROCID: '-', MSGID: '-',
TIMESTAMP: 'May 10 10:46:37', STRUCTURED-DATA: '-',
msg: ' devname="Test_log" devid="00000000" vd="User-2" date=2023-05-10 time=11:45:50 logid="105902704" type="utm"#015'
escaped msg: ' devname="Test_log" devid="00000000" vd="User-2" date=2023-05-10 time=11:45:50 logid="105902704" type="utm"'
inputname: imtcp rawmsg: '<190>timestamp=1683715550 devname="Test_log" devid="00000000" vd="User-2" date=2023-05-10 time=11:45:50 logid="105902704" type="utm"'
$!:
$.:
$/:
`

If I understand  the documentation in this case the field "$hostname" must be empty because no hostname are inside the logs. Is it normal ?
In my case, I wanted to get the field "$hostname" empty.

Thanks you for your answer.

### Environment
```
rsyslogd  8.2212.0 (aka 2022.12) compiled with:
        PLATFORM:                               x86_64-redhat-linux-gnu
        PLATFORM (lsb_release -d):
        FEATURE_REGEXP:                         Yes
        GSSAPI Kerberos 5 support:              Yes
        FEATURE_DEBUG (debug build, slow code): No
        32bit Atomic operations supported:      Yes
        64bit Atomic operations supported:      Yes
        memory allocator:                       system default
        Runtime Instrumentation (slow code):    No
        uuid support:                           Yes
        systemd support:                        Yes
        Config file:                            /etc/rsyslog.conf
        PID file:                               /var/run/syslogd.pid
        Number of Bits in RainerScript integers: 64

See https://www.rsyslog.com for more information.
```

**Comment by rgerhards** [comment]
The reason is that the hostname is invalid, underscore characters are not permitted in domain names in accordance with RFC 1035. As such, rsyslog assumes the message does not contain a hostname and uses the IP instead.

**Comment by rgerhards** [comment]
oh, sorry, I was too focussed on the hostname format. Rsyslog uses IP address if hostname is not set, except in RFC5424 mode, where '-' indicates an intentionally empty hostname. Such a mechanism does not exist in RFC3164, and there are also many malformed messages, so we use "best practice guesses" which work reasonably well for the vast majority of cases.

**Comment by shinigami35** [comment]
> oh, sorry, I was too focussed on the hostname format. Rsyslog uses IP address if hostname is not set, except in RFC5424 mode, where '-' indicates an intentionally empty hostname. Such a mechanism does not exist in RFC3164, and there are also many malformed messages, so we use "best practice guesses" which work reasonably well for the vast majority of cases.

Ok I understand

Thanks for your answer.

So if I understand, when $fromhost-ip and $hostname are the same, no hostname are set in the message.

This is not good for my case. Is it possible or not to override this configuration ? For example, if the parser of Rsyslog does not find "hostname" in the message, let this field empty ?

Because, in my case, I receive logs from different sources that are "not well" formated. Lots of messages do not follow the RFC 5424 or the RFC 3164, Syslog headers are missing. 
And I would like to block those message. Do you have a solution to block logs that not respect both RFC ?

Best regards

**Comment by shinigami35** [comment]
Miss click, sorry,


> oh, sorry, I was too focussed on the hostname format. Rsyslog uses IP address if hostname is not set, except in RFC5424 mode, where '-' indicates an intentionally empty hostname. Such a mechanism does not exist in RFC3164, and there are also many malformed messages, so we use "best practice guesses" which work reasonably well for the vast majority of cases.

Ok I understand

Thanks for your answer.

So if I understand, when $fromhost-ip and $hostname are the same, no hostname are set in the message.

This is not good for my case. Is it possible or not to override this configuration ? For example, if the parser of Rsyslog does not find "hostname" in the message, let this field empty ?

Because, in my case, I receive logs from different sources that are "not well" formated. Lots of messages do not follow the RFC 5424 or the RFC 3164, Syslog headers are missing. 
And I would like to block those message. Do you have a solution to block logs that not respect both RFC ?

Best regards

**Comment by shinigami35** [comment]
Hi rgerhards 

@rgerhards : This is not good for my case. Is it possible or not to override this configuration ? For example, if the parser of Rsyslog does not find "hostname" in the message, let this field empty ?

Because, in my case, I receive logs from different sources that are "not well" formated. Lots of messages do not follow the RFC 5424 or the RFC 3164, Syslog headers are missing.
And I would like to block those message. Do you have a solution to block logs that not respect both RFC ?

Best regards,
Shini

**Comment by davidelang** [comment]
No, there is not a way to set the standard parsers to block messages that fail 
to meet the RFC, that's the norm rather than the exception, so rsyslog has 
developed a lot of heuristics over the years to do the best that it can in the 
face of such problems.

What you could look at doing is to create your own parser, either using the 
mmnormalize toolset, or with C code (you could probably fork the regular parser 
to rip out the heuristics) and then either test with those, or set a parser 
stack that used your parser instead of the standard ones.

Or, if you are sure that all your systems are correctly sending messages, and 
they all have hostnames, look to see if the hostname field is an IP address (you 
can disable DNS lookups as well since you will never need them)

David Lang

**Comment by djruss1986** [comment]
set hostname explicitly:
`$LocalHostName yourhostname`
Alternatively, to have rsyslog send with the fully-qualified domain name:
`$PreserveFQDN on`
