### ISSUE TITLE
gnutls returned error on handshake: The TLS connection was non-properly terminated.

### ISSUE THREAD

**Issue by Rahul-20** [rsyslog/rsyslog#5139]
### Expected behavior
The exception should not occur.
### Actual behavior
The exception is continuously reported.
6744.061082301:imtcp.c        : nsd_gtls.c: AcceptConnReq bOurCertIsInit=1 bOurKeyIsInit=1
6744.061085357:imtcp.c        : nsd_gtls.c: AcceptConnReq setting default ciphers
6744.061181846:imtcp.c        : errmsg.c: Called LogMsg, msg: gnutls returned error on handshake: The TLS connection was non-properly terminated.
6744.061195942:imtcp.c        : operatingstate.c: osf: MSG gnutls returned error on handshake: The TLS connection was non-properly terminated.
: signaling new internal message via SIGTTOU: 'gnutls returned error on handshake: The TLS connection was non-properly terminated.  [v8.2112.0 try https://www.rsyslog.com/e/2083 ]'
rsyslogd: gnutls returned error on handshake: The TLS connection was non-properly terminated.  [v8.2112.0 try https://www.rsyslog.com/e/2083 ]
6744.061337865:main thread    : janitor.c: janitorRun() called
rsyslogd: tcpsrv listener (inputname: 'imtcp') failed to process incoming connection with error -2083 [v8.2112.0 try https://www.rsyslog.com/e/2083 ]
6744.061550681:imtcp.c        : tcpsrv.c: tcpsrv: error -2083 during accept
6744.061598379:imtcp.c        : errmsg.c: Called LogMsg, msg: tcpsrv listener (inputname: 'imtcp') failed to process incoming connection with error -2083

### Environment
- rsyslog version:  v8.2112.0
- platform: Ubuntu 22.04
- for configuration questions/issues, include rsyslog.conf and included config files
$DebugFile "/var/log/debug.log"
$DebugLevel 2
global(
  maxMessageSize="100000"
  net.enableDNS="off"
  DefaultNetstreamDriver="gtls"
  DefaultNetstreamDriverCAFile="/run/secrets/sys/trustedcert"
  DefaultNetstreamDriverCertFile="/run/secrets/sys/tls.crt"
  DefaultNetstreamDriverKeyFile="/run/secrets/sys/tls.key"
)
module(load="imtcp"
       KeepAlive="on"
       StreamDriver.Name="gtls"
       StreamDriver.mode="1"
       StreamDriver.authmode="x509/name"
       PermittedPeer="*"
       StreamDriver.PermitExpiredCerts="warn")
module(load="imuxsock")
template(name="logstreamingfmt" type="list" option.jsonf="on") {
  property(outname="priority" name="PRI" format="jsonf")
  property(outname="message" name="msg" format="jsonf")
}
ruleset(name="logstreamingruleset") {
    action(
        type="omfile"
        #dynaFile="logFileName"
        file="/var/log/all.log"
        template="logstreamingfmt"
    )
}
input(MaxSessions="800"
      MaxListeners="60"
      type="imtcp"
      port="514"
      ruleset="logstreamingruleset"
      DiscardTruncatedMsg="on"
      streamDriver.CAFile="/run/secrets/sys/trustedcert"
      streamDriver.KeyFile="/run/secrets/sys/tls.key"
      streamDriver.CertFile="/run/secrets/sys/tls.crt")

**Comment by rgerhards** [comment]
I suggest to change the driver to "ossl" (OpenSSL). It has far better error reporting than GnuTLS. That's basically why we added it.

**Comment by Rahul-20** [comment]
Hi @rgerhards,
Thanks for the input. Will try and update you and do we need to install any specific package for getting the ossl driver ?
Thanks in advance!

**Comment by rgerhards** [comment]
depends. rsyslog-ossl or rsyslog-openssl may be required.

**Comment by rgerhards** [comment]
This looks like the remote client did not send a full response "SSL routines::unexpected eof while reading". Did it terminate the connection prematurely or is it not configured for TLS?

**Comment by rgerhards** [comment]
Looking at a wireshark trace **may** be helpful (I would assume there is cleartext up to this point, but not sure).

**Comment by Rahul-20** [comment]
There is no remote client which is sending logs to the rsyslog server. We are just trying to set up only the rsyslog server with TLS. As soon as rsyslog starts, it keeps on returning the error. I'm not sure why it is throwing this error when there is no client sending logs to the server. Anyhow, as you suggested will try to trace using Wireshark.

**Comment by Rahul-20** [comment]
Yes. I'm not sure how it is getting connection requests without any client sending logs. Just to give to little background about the setup, the rsyslog server is packaged into a helm chart and deployed on the Kubernetes cluster.

![image](https://github.com/rsyslog/rsyslog/assets/25735588/e95cb398-f0b6-4510-9e65-bc2b1fb94e81)

**Comment by davidelang** [comment]
something is sending a connection request to that port, it may not be a 
legitimate client (think a vulnerability scanner, or even an attacker if this is 
exposed) If that thing is not doing a full TLS handshake, this is what it will 
look like in the logs.

how can we see the IP address that this is being sent from?

David Lang

**Comment by Rahul-20** [comment]
Hi @davidelang,
Thanks for the response.
Yes. I could see it getting requests from some IP address but was not able to find out that IP address belongs to which service in the Kubernetes cluster. Do you have any suggestions to find out the client who is sending these requests to the rsyslog server in the Kubernetes cluster or is there any way to keep a strict check on rsyslog to accept only the requests from the particular host which will avoid this error?

**Comment by davidelang** [comment]
iptables would be my approach to blocking unexpected traffic. I'm hoping someone 
else can point at where to look to find the souce IP of this connection

David Lang

**Comment by rgerhards** [comment]
> I'm hoping someone else can point at where to look to find the souce IP of this connection

I think the debug log might show the source - nor sure, but worth a try. I'll try to see why the error message does not contain it. Maybe there is a reason.

Please create a debug log. Instructions: https://www.rsyslog.com/doc/v8-stable/troubleshooting/howtodebug.html

Be sure that the problem in question occurs at least once during the debug run. Once this is done, please post the debug log (e.g. via pastbin or github). After that, we can review the contents and check how exactly rsyslog processing worked.

**Comment by Rahul-20** [comment]
Hi @rgerhards, @davidelang
Thanks for your support. I figured out the problem which is causing the handshake error. Actually, the problem is with the Kubernetes liveness probe and readiness probe. After commenting it out then I'm not seeing the handshake error.
Current Probes Config -
 livenessProbe:
   tcpSocket:
     port: syslog
 readinessProbe:
   tcpSocket:
     port: syslog
Do you have any suggestion to handle the liveness check in case of rsyslog with TLS enabled?

**Comment by davidelang** [comment]
I don't know the kubernetes config, but you should be able to configure 
something to do a full TLS handshake (it would be pretty much the same thing you 
need to do to test if a https website is functional)

David Lang

**Comment by Rahul-20** [comment]
Hi @davidelang, @rgerhards 
Yes, I got it. Thanks for your time in supporting me. I will close this ticket.
