### ISSUE TITLE
Cannot parse messages from TP-Link T1500G-10PS

### ISSUE THREAD

**Issue by alkisg** [rsyslog/rsyslog#5148]
Hi, I configured a TP-Link T1500G-10PS switch to forward the logs and I'm receiving them on Ubuntu 22.04, rsyslog 8.2112.0-2ubuntu2.2. I, with debug format:

```log
FROMHOST: 'sftsw1.example.com', fromhost-ip: '10.32.32.43', HOSTNAME: '2023-05-30', PRI: 134,
syslogtag '12:', programname: '12', APP-NAME: '12', PROCID: '-', MSGID: '-',
TIMESTAMP: 'May 30 12:49:51', STRUCTURED-DATA: '-',
msg: '49:51 sftsw1 61209 Set log host 1, host IP:10.32.32.11, level:6, status:enabled by admin on web (10.32.32.11).'
escaped msg: '49:51 sftsw1 61209 Set log host 1, host IP:10.32.32.11, level:6, status:enabled by admin on web (10.32.32.11).'
inputname: imudp rawmsg: '<134>2023-05-30 12:49:51 sftsw1 61209 Set log host 1, host IP:10.32.32.11, level:6, status:enabled by admin on web (10.32.32.11).'
```

As you can see, rsyslog is unable to parse `2023-05-30 12:49:51` as a date, even with [detect.YearAfterTimestamp="on"](https://www.rsyslog.com/doc/master/configuration/modules/pmrfc3164.html#detect-yearaftertimestamp), and it ends up thinking that `HOSTNAME: '2023-05-30'`.

Is there any way to work around that issue without writing my own custom parser? A plain `date -d "2023-05-30 12:49:51"` in the shell can properly parse that date... thank you!

**Comment by alkisg** [comment]
If "date autodetection" is difficult, it would be nice to support a `detect.DateFormat="x"` directive, that would correspond to the fmt parameter of the [strptime function](https://www.gnu.org/software/libc/manual/html_node/Low_002dLevel-Time-String-Parsing.html).

My C is very rusty, but here's some example code to show what I mean. The rsyslog end user would only have to set DateFormat:

```c
#define _XOPEN_SOURCE 700
#include <time.h>
#include <stdio.h>
#include <string.h>

#define DateFormat "%Y-%m-%d %H:%M:%S"

int main(void)
{
    char *input = "2023-05-30 12:49:51 sftsw1 61209 Message text";
    const char *cp;
    struct tm tm;
    char output[100];

    memset(&tm, '\0', sizeof(tm));
    cp = strptime(input, DateFormat, &tm);
    if (cp == NULL) {
        printf("Can't parse!");
        return 1;
    }
    strftime((char *)&output, sizeof(output), "%F %T", &tm);
    printf("DATE=%s\n", output);
    printf("REST OF STRING=%s\n", cp);

    return 0;
}
```

And the output of the program is:

```console
DATE=2023-05-30 12:49:51
REST OF STRING= sftsw1 61209 Message text
```

**Comment by davidelang** [comment]
There is already a lot of code in place to guess at dates, this sender is not 
sending a RFC compliant date.

The biggest problem I see with a detect.DateFormat option is that you seldom get 
logs from only one source, so you need to have a stack of options not just one.

In your case, you also have the problem that they don't send a valid syslogtag 
as well, instead they have what is probably a sequence number.

see if they have an option to send a RFC-2545 message, they seem more likely to 
get that right.

other than that, you can define a parder using the liblognorm parsing rules and 
insert it into the stack ahead of the default catch-all parser that would be 
able to not only handle the date, but also the sequence number.

David Lang

**Comment by alkisg** [comment]
Hi David, thank you for your input,

> an option to send a RFC-2545 message

Unfortunately no, we have around 20 switches of various vendors that do not have that option (the rest of the switches are fine).

> you can define a parser using the liblognorm parsing rules
> and insert it into the stack ahead of the default catch-all parser

In that solution, would I need to patch and recompile the Ubuntu rsyslog package?
For a long-term solution, I'd like to avoid that. It would mean we'd have to do apt-pinning in our log servers and manually monitor for rsyslog security updates.

**Comment by davidelang** [comment]
On Tue, 30 May 2023, Alkis Georgopoulos wrote:

>> you can define a parser using the liblognorm parsing rules
>> and insert it into the stack ahead of the default catch-all parser
>
> In that solution, would I need to patch and recompile the Ubuntu rsyslog package?
> For a long-term solution, I'd like to avoid that. It would mean we'd have to do apt-pinning in our log servers and manually monitor for rsyslog security updates.

No, this is all in the configuration language. A couple years ago a input parser 
was added that let you define the parsing with the same language that you use 
for mmnormalize

https://www.rsyslog.com/doc/master/configuration/modules/pmnormalize.html
https://www.rsyslog.com/doc/master/configuration/parser.html

David Lang

**Comment by alkisg** [comment]
Thank you. It appears that Ubuntu doesn't have that library built into rsyslog, because rsyslog is in "main" while the library is in "universe":

```console
# zless /usr/share/doc/rsyslog/changelog.Debian.gz
rsyslog (8.2112.0-2ubuntu1) jammy; urgency=low
  * Merge from Debian unstable. Remaining changes:
    - Drop [mm|pm]normalize modules, depending on liblognorm from universe.
      + d/rules: drop --enable-mmnormalize & --enable-pmnormalize
      + d/control: drop build dependency on liblognorm-dev
```

That might be acceptable though. I think Debian Bookworm removed rsyslog from the default installation; if Ubuntu does the same, it might be demoted to universe; in that case, they won't need the Ubuntu-specific patch that removes these modules.

I'll also have a look at developing a small python script that listens on 514, does normalization, and then forwards to rsyslog in a socket or on port 515... Thanks again!

**Comment by alkisg** [comment]
I filed a bug report in Ubuntu about this:
https://bugs.launchpad.net/ubuntu/+source/rsyslog/+bug/2023266

I'll re-compile the Ubuntu package, try pmnormalize and post the solution if I can find it.

**Comment by alkisg** [comment]
I managed to parse the incompatible message but then I got stuck to this question:
**How can I configure rsyslog to use the normal parsers after my own parser fails?**
So that I'm able to parse the messages from the other, compatible switches, in the same IP:port.

Rsyslog config:

```log
module(load="pmnormalize")
parser(name="custom.pmnormalize" type="pmnormalize" undefinedPropertyError="on"
	rule="rule=:<%pri:number%>%date:word% %time:word% %hostname:word% %syslogtag:number% %msg:rest%")
template(name="RawFormat" type="string" string="RAW: %rawmsg%")

ruleset(name="udp-received" parser="custom.pmnormalize") {
    action(type="omfile" file="/var/log/site/normal.log" template="RSYSLOG_SyslogProtocol23Format")
    action(type="omfile" file="/var/log/site/debug.log" template="RSYSLOG_DebugFormat")
    action(type="omfile" file="/var/log/site/raw.log" template="RawFormat")
}

module(load="imudp")
input(type="imudp" port="514" ruleset="udp-received")
```

Example line received by the incompatible switch. It's parsed OK:

```
echo "<133>$(date "+%F %T") Hostname 51891 Message #$RANDOM body" | nc -q0 -u 192.168.67.38 514
```

Example line received by typical rsyslog forwarding. It fails to be parsed with my parser, and I can't get it to fall back to the normal parsers where it would succeed:

```
echo "<155>1 $(date -Iseconds) Hostname Syslogtag Procid Msgid [Structured Data] Message #$RANDOM body" | nc -q0 -u 192.168.67.38 514
```

Thank you!

**Comment by davidelang** [comment]
you can define multiple parsers, it's described here 
https://www.rsyslog.com/doc/v8-stable/concepts/messageparser.html

but I'm not finding an example of the syntax in a quick search right now. 
Hopefully the folks in Germany who will be waking up soon can answer, otherwise 
I'll do more digging tomorrow.

It may just be as simple as defining multiple parser objects (keeping in mind 
that the legacy 3164 parser will match anything), but I'm not 100% sure.

David Lang

**Comment by alkisg** [comment]
Thank you David, you're great!

I grepped the sources, found an example, and indeed this works:

```
ruleset(name="udp-received" parser=["custom.pmnormalize","rsyslog.rfc5424","rsyslog.rfc3164"]) {
```

...I'll go ahead test it in production!

**Comment by alkisg** [comment]
Unfortunately while that syntax allowed me to declare multiple parsers, only the first one is used.
I can't get it to fail and use the next ones, even if I send incompatible lines to it that it can't parse.
Am I missing some syntax that instructs the parser to fail if it can't match?
My latest configuration file is:

```
module(load="pmnormalize")
# http://rsyslog.github.io/liblognorm/doc/_build/html/configuration.html
parser(name="custom.pmnormalize" type="pmnormalize" undefinedPropertyError="on" rule=["rule=:<%pri:number%>%date:date-iso% %time:time-24hr% %hostname:word% %syslogtag:number% %msg:rest%"])
template(name="RawFormat" type="string" string="RAW: %rawmsg%")

ruleset(name="udp-received" parser=["custom.pmnormalize","rsyslog.rfc5424","rsyslog.rfc3164"]) {
    action(type="omfile" file="/var/log/site/normal.log" template="RSYSLOG_SyslogProtocol23Format")
    action(type="omfile" file="/var/log/site/debug.log" template="RSYSLOG_DebugFormat")
    action(type="omfile" file="/var/log/site/raw.log" template="RawFormat")
}

module(load="imudp")
input(type="imudp" port="514" ruleset="udp-received")
```

And as an example, if I send an rfc5424 line, it still gets parsed (wrongly) by my custom parser:

```
$ echo "<155>1 $(date -Iseconds) Hostname Syslogtag Procid Msgid [Structured Data] Message #$RANDOM body" | nc -q0 -u 192.168.67.38 514

$ tail debug.log
Debug line with all properties:
FROMHOST: '192.168.67.1', fromhost-ip: '192.168.67.1', HOSTNAME: '192.168.67.1', PRI: 155,
syslogtag '', programname: '', APP-NAME: '-', PROCID: '-', MSGID: '-',
TIMESTAMP: 'Jun  9 14:35:16', STRUCTURED-DATA: '-',
msg: '<155>1 2023-06-09T14:35:15+03:00 Hostname Syslogtag Procid Msgid [Structured Data] Message #22279 body'
escaped msg: '<155>1 2023-06-09T14:35:15+03:00 Hostname Syslogtag Procid Msgid [Structured Data] Message #22279 body'
inputname: imudp rawmsg: '<155>1 2023-06-09T14:35:15+03:00 Hostname Syslogtag Procid Msgid [Structured Data] Message #22279 body'
$!:
$.:
$/:
```

**Comment by rgerhards** [comment]
It unfortunately looks like there is a bug in pmnormalize, which makes it return the wrong code on parsing failure. :-(

I'll craft a patch. If you run on RHEL-like system, you can use the daily stable after merge, else you need to wait for the scheduled stable or re-build yourself. We will most probably have a new scheduled stable either next Tuesday or on the 20.

**Comment by alkisg** [comment]
Thanks; I tried to apply the patch on Ubuntu 22.04's version, but I got the same build failures like the [CI on github](https://github.com/rsyslog/rsyslog/actions/runs/5221969501/jobs/9426891688?pr=5154):

```
pmnormalize.c:237:3: error: label 'finalize_it' used but not defined
   ABORT_FINALIZE(RS_RET_COULD_NOT_PARSE);
```

**Comment by alkisg** [comment]
I added a `finalize_it:` line right above `ENDparse2` in pmnormalize.c.
And now everything works!

Thank you both!

**Comment by davidelang** [comment]
I'll also point out that mmnormalize is extremely efficient when you have many 
rules. A few jobs ago, I had a 1400 line ruleset to parse my logs (in great 
detail, not just the header vs body) and the difference in peformance between 
matching the first rule vs the last rule was ~30% (which compared especially 
favorably to a 30ish line grok filter where first vs last was a 90% hit IIRC)

so don't be afraid to add additional parsing to your ruleset

@rainer, I haven't dug in to pmnormalize, can it create arbitrary variables? or 
only the standard properties?

David Lang

**Comment by descilla** [comment]
For the records an people with the same issue finding this thread by google (like me).

Since the ``pmnormalize`` is still not part of the ubuntu package and i was not willing to build rsyslog manually (want to update it easily via apt in the future) a played around to find another solution. I discovered that ``mmexternal`` _is_ part of the ubuntu packe, so I build a tiny python script and "corrected" the invalid tp-link syslog format.

my python script:

```python
#!/usr/bin/env python3
import sys
import re
import json

def parse_syslog_line(line):
    regex_pattern = r"<(\d+)>(\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}) (\S+) (\d+) (.+)"
    match = re.match(regex_pattern, line)
    if match:
        pri, iso_date, hostname, procid, msg = match.groups()
        outmsg = {
            "timestamp": iso_date,
            "hostname": hostname,
            "procid": procid,
            "msg": msg
        }
        return json.dumps(outmsg)+"\n"
    return line

for line in sys.stdin:
    parsed_line = parse_syslog_line(line.strip())
    sys.stdout.write(parsed_line)
    sys.stdout.flush()
```

rsyslog config:
```
module(load="mmexternal")
...
ruleset(name="test"){
  action(type="mmexternal" binary="/usr/lib/rsyslog/tplink_rfc_fix.py" interface.input="rawmsg")
  action(type="omfwd" Target="10.0.23.42" Port="10514" Protocol="tcp" Template="RSYSLOG_SyslogProtocol23Format" TCP_Framing="octet-counted" KeepAlive="on")
}
...
```

By using this configuration I was able to extract the hostname properly and obtain a proper logmessage.

Ressources:
- https://www.rsyslog.com/doc/master/configuration/modules/mmexternal.html
- https://github.com/rsyslog/rsyslog/blob/master/plugins/external/INTERFACE.md
