### ISSUE TITLE
Strict TLS with wildcard cert

### ISSUE THREAD

**Issue by MrAtheist** [rsyslog/rsyslog#5152]
### Problem Statement

Trying to stream logs over TLS == strict to a client `syslog.domain.com:443` that runs behind a wildcard cert `*.domain.com`, and on this client i can see TLS handshake happening but no payload to be found. It turns out that the client needs to be behind the single domain cert and that resolves the issue.

Is there a definitive doc that describes this scenario? I'm not sure if [this](https://www.rsyslog.com/doc/v8-stable/tutorials/tls.html) is it...

**Comment by alorbach** [comment]
PermittedPeer might be what you are looking for: 
https://www.rsyslog.com/doc/v8-stable/configuration/modules/imtcp.html#id10

There are sample configurations in some testcases like this one: 
https://github.com/rsyslog/rsyslog/blob/cd3b9b5cc8b297e675a7eac86343b76c921d2619/tests/sndrcv_ossl_cert_chain.sh

**Comment by MrAtheist** [comment]
Thanks for the notes, but i dont quite follow how does it related to `PermittedPeer` when it comes to wildcard vs non-wildcard cert...? It also doesnt explain in https://www.rsyslog.com/doc/v8-stable/configuration/modules/imtcp.html#permittedpeer

<img width="1175" alt="image" src="https://github.com/rsyslog/rsyslog/assets/4513916/ff2ac2fb-1ea0-4022-8e58-6e67c406fa2f">

**Comment by MrAtheist** [comment]
I've stumbled upon this on `PermittedPeer`, let me give this a try, but it still doesnt explain how TLS == strict impacts wildcard vs non-wildcard cert...

```
PermittedPeer["*.domain.com"]
```

https://www.rsyslog.com/doc/v8-stable/tutorials/tls_cert_server.html

**Comment by MrAtheist** [comment]
Closing this as it is still a mystery to me...
