### ISSUE TITLE
Run the rsyslogd -i command to start the second process and then kill the second process. The first process also has an error that cannot write to the log.

### ISSUE THREAD

**Issue by linzhuorong** [rsyslog/rsyslog#5157]
### Expected behavior

Run the rsyslogd -i command to start the second process and then kill the second process. The /var/log/message of the first process is written into the system command log.
### Actual behavior

Run the rsyslogd -i command to start the second process and then kill the second process. The first process also has an error that cannot write to the log.
### Steps to reproduce the behavior
Run the /usr/sbin/rsyslogd -f /tmp/debug_syslog/debug_rsyslog.conf -i /tmp/debug_syslog/debug_rsyslog.pid command to start the second process and kill the process. The size of /var/log/messages does not increase.
![日志log](https://github.com/rsyslog/rsyslog/assets/104970073/0105423e-44e8-4686-af35-c8af4287667d)

/etc/rsyslog.conf
```
# rsyslog configuration file

# For more information see /usr/share/doc/rsyslog-*/rsyslog_conf.html
# If you experience problems, see http://www.rsyslog.com/doc/troubleshoot.html

#### MODULES ####

$ModLoad imuxsock # provides support for local system logging (e.g. via logger command)
$ModLoad imklog # reads kernel messages (the same are read from journald)
$ModLoad immark  # provides --MARK-- message capability

# Provides UDP syslog reception
#$ModLoad imudp
#$UDPServerRun 514

# Provides TCP syslog reception
#$ModLoad imtcp
#$InputTCPServerRun 514


#### GLOBAL DIRECTIVES ####
$FileGroup root
$FileOwner root
$FileCreateMode 0640

# Where to place auxiliary files
$WorkDirectory /var/lib/rsyslog

# Use default timestamp format
$ActionFileDefaultTemplate RSYSLOG_FileFormat

# File syncing capability is disabled by default. This feature is usually not required,
# not useful and an extreme performance hit
#$ActionFileEnableSync on

# Include all config files in /etc/rsyslog.d/
$IncludeConfig /etc/rsyslog.d/*.conf


#### RULES ####

# Log all kernel messages to the console.
# Logging much else clutters up the screen.
#kern.*                                                 /dev/console

# Log anything (except mail) of level info or higher.
# Don't log private authentication messages!
*.info;mail.none                                        /var/log/messages

# The authpriv file has restricted access.
authpriv.*                                              /var/log/secure

# Log all the mail messages in one place.
mail.*                                                  -/var/log/maillog


# Log cron stuff
cron.*                                                  /var/log/cron

# Everybody gets emergency messages
*.emerg                                                 :omusrmsg:*

# Save news errors of level crit and higher in a special file.
uucp,news.crit                                          /var/log/spooler

# Save boot messages also to boot.log
local7.*                                                /var/log/boot.log


# ### begin forwarding rule ###
# The statement between the begin ... end define a SINGLE forwarding
# rule. They belong together, do NOT split them. If you create multiple
# forwarding rules, duplicate the whole block!
# Remote Logging (we use TCP for reliable delivery)
#
# An on-disk queue is created for this action. If the remote host is
# down, messages are spooled to disk and sent when it is up again.
#$ActionQueueFileName fwdRule1 # unique name prefix for spool files
#$ActionQueueMaxDiskSpace 1g   # 1gb space limit (use as much as possible)
#$ActionQueueSaveOnShutdown on # save messages to disk on shutdown
#$ActionQueueType LinkedList   # run asynchronously
#$ActionResumeRetryCount -1    # infinite retries if host is down
# remote host is: name/ip:port, e.g. 192.168.0.1:514, port optional
#*.* @@remote-host:514
# ### end of the forwarding rule ###

```
/debug_syslog/debug_rsyslog.conf
```
*.debug /tmp/debug_syslog/debug_messages
$ModLoad imuxsock
```
### Environment
- rsyslog version:  8.2110.0

**Comment by rgerhards** [comment]
I do not fully undertand the message, sry. You mean the only config that is provided to the second instance is
```
*.debug /tmp/debug_syslog/debug_messages
$ModLoad imuxsock
```

If so, I think you run into problems with the system log socket. You need to disable using it. There can only one rsyslog process listen to the system log socket.

**Comment by linzhuorong** [comment]
So running two rsyslogd at the same time, some modules and configurations are not supported, is there a clear list of this?

**Comment by rgerhards** [comment]
> So running two rsyslogd at the same time, some modules and configurations are not supported, is there a clear list of this?

No, but the system log socket is handled exclusively by rsyslog, and exclusivity is nothing you can share. Similarly, if you write to the same files, problems and truncation can occur, simply by the nature of these writes. Populating the same database will duplicate data, etc, etc.

**Comment by davidelang** [comment]
On Mon, 19 Jun 2023, linzhuorong wrote:

> So running two rsyslogd at the same time, some modules and configurations are not supported, is there a clear list of this?

It is supported, as long as the configurations don't conflict. If you have any 
two programs try to bind to the same port (network or unix port), only one of 
the two will work. This isn't a rsyslog limit, it's a limit imposed by the 
operating system.

There are a couple things for rsyslog internal recordkeeping that can conflict

1. the work directory
   If you configure rsyslog to keep state in a directory, having multiple copies 
of rsyslog using the same directory will cause problems as they will overwrite 
each other's state

2. the pid file
   obviously, if multiple copies of rsyslog write to the same pid file, only the 
last write will be visible to the system

But the biggest problem is going to be the inputs, if you have them read the 
same files, why have multiple copies? if you have them try to listen to the same 
ports, the OS will block the second and later versions as the ports are already 
in use.

David Lang
