### ISSUE TITLE
ommail regex match syntax

### ISSUE THREAD

**Issue by somewhere-or-other** [rsyslog/rsyslog#5170]
Is there a way to use a regex match of some kind, to trigger email in the `ommail` module?  [Examples in the documentation](https://www.rsyslog.com/doc/v8-stable/configuration/modules/ommail.html#example-1) all just use the `contains` syntax, eg:

```
if $msg contains "hard disk fatal failure" then
```

Based on the [compare operations documentation](https://www.rsyslog.com/doc/v8-stable/configuration/filters.html?highlight=regex#compare-operations), I've been trying to use syntax like shown below, but I keep getting a parse error:

```
if $msg regex "Blocking \"([/.0-9]+)\" for ([0-9]+) secs" then
```

Example:
```bash
[root@hostname ~]# rsyslogd -N 1
rsyslogd: version 8.2102.0-113.el9_2, config validation run (level 1), master config /etc/rsyslog.conf
rsyslogd: error during parsing file /etc/rsyslog.d/ommail.conf, on or before line 7: syntax error on token 'regex' [v8.2102.0-113.el9_2 try https://www.rsyslog.com/e/2207 ]
rsyslogd: could not interpret master config file '/etc/rsyslog.conf'. [v8.2102.0-113.el9_2 try https://www.rsyslog.com/e/2207 ]
[root@hostname~]# 
```

Since it's complaining about the `regex` token, I'm assuming this is a general syntax problem, and not something with my regex specifically.  I even get the same message when I use a should-match-everything expression like `".+"`.  I am aware of the [Regular Expression Checker/Generator](https://www.rsyslog.com/regex/), which I will use to validate the specific RE later.

For reference, I'm trying to take action based on messages from `sshguard`, that look like this; it didn't seem like `contains` was going to work well:

```
Blocking "192.168.123.45/32" for 600 secs (14 attacks in 42 secs, after 1 abuses over 42 secs.)
```

### Environment
- rsyslog version: 8.2102.0-113.el9_2
- platform: RHEL 9.2

### Configs
- [rsyslog.conf.txt](https://github.com/rsyslog/rsyslog/files/11897895/rsyslog.conf.txt)
- [ommail.conf.txt](https://github.com/rsyslog/rsyslog/files/11897894/ommail.conf.txt)

**Comment by rgerhards** [comment]
In script, regex is implemented via a function, namely `re_match()`.

See https://www.rsyslog.com/doc/master/rainerscript/functions/idx_built-in_functions.html

The "`regex`" comparison op is used with property based filters, an older approach.

**Comment by somewhere-or-other** [comment]
That explains a great deal, including why I couldn't find the correct documentation examples.

I can verify that syntax like this does work, and triggers the email as expected:

```
if re_match($msg, 'Blocking \"([/.0-9]+)\" for ([0-9]+) secs') then {
```

Danke
