### ISSUE TITLE
help on solution of rotate log with "imfile"

### ISSUE THREAD

**Issue by danielzhanghl** [rsyslog/rsyslog#5182]
Hi expert, 
I have two containers in one k8s pod, these two share some common filesystem.

One is application container, which product logs and write them to file system.

In the other container, there are two processes (rsyslog and logrotate), these two processes are managed by supervisord.
 rsyslog use "imfile" module to read the log file and format them, then forward that to another server, 
while logrotate will rotate the log files time bias.

Now, our user don't like supervisord, they request to use one process only in the second container.
is there any solution on rsyslog side to rotate the log files automatically?

checked rsyslog document, there is omprog module, which could invoke a script:
https://rsyslog.readthedocs.io/en/latest/configuration/modules/omprog.html

 could I invoke a script to rotate the log like below?
module(load="omprog")
action(type="omprog"    execOnlyOnceEveryInterval="1800" binary="rotate_mylog.sh" )

and from expert point of view, will that work or any issue for this approach?

thanks for any feedback!

**Comment by danielzhanghl** [comment]
the major concern is omprog may queue the message and feed that to STD INPUT when call the script, and reply on script to read that, there maybe some overflow when the script invoke only half an hour.

**Comment by davidelang** [comment]
omprog runs the script continually, feeding the log messages that you send to it 
to the stdin of the script. I think your question indicates a misunderstanding 
of how it works.

rsyslog is the wrong tool to use to use to rotate files by other programs, 
especially if you are looking for time based rotation.

omprog could be used, but you would want to create a script that never exits, 
and then either does what you want it to for every log message that you send it 
(and you do the filtering in rsyslog) or that looks for a specific log message 
and take action when you see that.

David Lang

**Comment by danielzhanghl** [comment]
@davidelang thanks for the response!

the plan is to use omprog invoke logrotate with one-shot only: rotate imfiles if need then quit logrotate, don't read any log messages from its stdin.

and after "execOnlyOnceEveryInterval" duration, the same procedure is called.

agree that sounds to strange, mabye need to find anyway for that.

**Comment by davidelang** [comment]
omprog doesn't run the way you wish it did. omprog needs to read messages from 
it's stdin. You can do whatever you want in the program (including having a 
timer and fire off external programs), but if it doesn't get fed a log, it will 
never start (actions get initiated when they first have a log to process)

David Lang

**Comment by danielzhanghl** [comment]
thanks for the clarification, I will find another way to rotate log.
