### ISSUE TITLE
action 'syslog' treated as ':omusrmsg:syslog' - please use ':omusrmsg:syslog' syntax instead, 'syslog' will not be supported in the future

### ISSUE THREAD

**Issue by lug-gh** [rsyslog/rsyslog#5184]
Hi,
I am running a standard install of Debian 11, and want to forward everthing from `/var/log/syslog` and `/var/log/auth.log` to a remote syslog server.
To see what the syntax is, I used /etc/rsyslog.conf as a reference.
<details>
<summary>cat /etc/rsyslog.conf | grep "^[^#]"</summary>

```
module(load="imuxsock") # provides support for local system logging
module(load="imklog")   # provides kernel logging support
$ActionFileDefaultTemplate RSYSLOG_TraditionalFileFormat
$FileOwner root
$FileGroup adm
$FileCreateMode 0640
$DirCreateMode 0755
$Umask 0022
$WorkDirectory /var/spool/rsyslog
$IncludeConfig /etc/rsyslog.d/*.conf
auth,authpriv.*			/var/log/auth.log
*.*;auth,authpriv.none		-/var/log/syslog
daemon.*			-/var/log/daemon.log
kern.*				-/var/log/kern.log
lpr.*				-/var/log/lpr.log
mail.*				-/var/log/mail.log
user.*				-/var/log/user.log
mail.info			-/var/log/mail.info
mail.warn			-/var/log/mail.warn
mail.err			/var/log/mail.err
*.=debug;\
	auth,authpriv.none;\
	mail.none		-/var/log/debug
*.=info;*.=notice;*.=warn;\
	auth,authpriv.none;\
	cron,daemon.none;\
	mail.none		-/var/log/messages
*.emerg				:omusrmsg:*
```

</details>

### Expected behavior
I create a file called `/etc/rsyslog.d/forward.conf` with the content
```
auth,authpriv.* @192.168.0.100:514
syslog @192.168.0.100:514
```
The auth-log part is obvious, but I'm not sure about the syslog part.
With this config it works, but I get these two messages:
```
Jul 13 10:36:13 debian-server rsyslogd[4478]: action 'syslog' treated as ':omusrmsg:syslog' - please use ':omusrmsg:syslog' syntax instead, 'syslog' will not be supported in the future [v8.2102.0 try https://www.rsyslog.com/e/2184 ]
Jul 13 10:36:13 debian-server rsyslogd[4478]: error during parsing file /etc/rsyslog.d/forward.conf, on or before line 2: warnings occured in file '/etc/rsyslog.d/forward.conf' around line 2 [v8.2102.0 try https://www.rsyslog.com/e/2207 ]
```

### Actual behavior
So I adjust the forward.conf like the following:
```
auth,authpriv.* @192.168.0.100:514
:omusrmsg:syslog @192.168.0.100:514
```
That way I don't get any error messages, but also, the syslog is not forwarded anymore.

### Environment
- rsyslog version:  8.2102.0
- platform: Debian 11

**Comment by davidelang** [comment]
On Thu, 13 Jul 2023, lug-gh wrote:

> Hi,
> I am running a standard install of Debian 11, and want to forward everthing from `/var/log/syslog` and `/var/log/auth.log` to a remote syslog server.
> To see what the syntax is, I used /etc/rsyslog.conf as a reference.
> <details>
> <summary>cat /etc/rsyslog.conf | grep "^[^#]"</summary>
>
> ```
> module(load="imuxsock") # provides support for local system logging
> module(load="imklog")   # provides kernel logging support
> $ActionFileDefaultTemplate RSYSLOG_TraditionalFileFormat
> $FileOwner root
> $FileGroup adm
> $FileCreateMode 0640
> $DirCreateMode 0755
> $Umask 0022
> $WorkDirectory /var/spool/rsyslog
> $IncludeConfig /etc/rsyslog.d/*.conf
> auth,authpriv.*			/var/log/auth.log
> *.*;auth,authpriv.none		-/var/log/syslog
> daemon.*			-/var/log/daemon.log
> kern.*				-/var/log/kern.log
> lpr.*				-/var/log/lpr.log
> mail.*				-/var/log/mail.log
> user.*				-/var/log/user.log
> mail.info			-/var/log/mail.info
> mail.warn			-/var/log/mail.warn
> mail.err			/var/log/mail.err
> *.=debug;\
> 	auth,authpriv.none;\
> 	mail.none		-/var/log/debug
> *.=info;*.=notice;*.=warn;\
> 	auth,authpriv.none;\
> 	cron,daemon.none;\
> 	mail.none		-/var/log/messages
> *.emerg				:omusrmsg:*
> ```
>
> </details>
>
> ### Expected behavior
> I create a file called `/etc/rsyslog.d/forward.conf` with the content
> ```
> auth,authpriv.* @192.168.0.100:514
> syslog @192.168.0.100:514

This isn't doing what you intend.

look at the rules above that write to the /var/log/syslog file and use the same 
rule, but with the network destination.

David Lang

> ```
> The auth-log part is obvious, but I'm not sure about the syslog part.
> With this config it works, but I get these two messages:
> ```
> Jul 13 10:36:13 debian-server rsyslogd[4478]: action 'syslog' treated as ':omusrmsg:syslog' - please use ':omusrmsg:syslog' syntax instead, 'syslog' will not be supported in the future [v8.2102.0 try https://www.rsyslog.com/e/2184 ]
> Jul 13 10:36:13 debian-server rsyslogd[4478]: error during parsing file /etc/rsyslog.d/forward.conf, on or before line 2: warnings occured in file '/etc/rsyslog.d/forward.conf' around line 2 [v8.2102.0 try https://www.rsyslog.com/e/2207 ]
> ```
>
> ### Actual behavior
> So I adjust the forward.conf like the following:
> ```
> auth,authpriv.* @192.168.0.100:514
> :omusrmsg:syslog @192.168.0.100:514
> ```
> That way I don't get any error messages, but also, the syslog is not forwarded anymore.
>
>
> ### Environment
> - rsyslog version:  8.2102.0
> - platform: Debian 11
> - for configuration questions/issues, include rsyslog.conf and included config files
>
>
>

**Comment by lug-gh** [comment]
> This isn't doing what you intend. look at the rules above that write to the /var/log/syslog file and use the same rule, but with the network destination. David Lang

Strange, I had already tested it with *.*, but nothing was transferred there. For whatever reason, I will no longer be able to trace.
Now I have configured it like this:
`*.* @192.168.0.100:514`
And it works.

But what is not quite clear to me yet, why beside `*.*` e.g. `authpriv.none` is explicitly specified, if it is already included in `*.*`?

Thanks so far

**Comment by davidelang** [comment]
I can't say why distros do what they do in the configs :-)

so much of it is legacy from decades ago when disks and logs were small and only 
viewed by people manually

personally, I put all logs in /var/log/messages (or send them to a central 
server) and parse them on the central server.

David Lang

**Comment by krzee** [comment]
> But what is not quite clear to me yet, why beside `*.*` e.g. `authpriv.none` is explicitly specified, if it is already included in `*.*`?
> 
> Thanks so far

it's after a `;` not after a `,`
these are exceptions to the `*.*`
