### ISSUE TITLE
How to use the rsyslog configuration option --disable-inet

### ISSUE THREAD

**Issue by linzhuorong** [rsyslog/rsyslog#5188]
### Expected behavior
With the rsyslog configuration option disable-inet, rsyslog is used normally.
### Actual behavior
After using disable-inet, the following error occurs at startup due to the lack of lmnet.so:
```
starting pid 679, tty '': '/usr/sbin/rsyslogd'
rsyslogd: could not load module 'lmnet', errors: trying to load module /usr/lib/rsyslog/lmnet.so: /usr/lib/rsyslog/lmnet.so: cannot open shared object file: No such file or directory [v8.2110.0 try https://www.rsyslog.com/e/2066 ]
Error during class init for object 'net' - failing...
rsyslogd initializiation failed - global classes could not be initialized.
Did you do a "make install"?
Suggested action: run rsyslogd with -d -n options to see what exactly fails.
rsyslogd: run failed with error -2066 (see rsyslog.h or try https://www.rsyslog.com/e/2066 to learn what that number means)
svrmonit:"/usr/sbin/rsyslogd" not find right pid!
process '/usr/sbin/rsyslogd' (pid 679) exited. Scheduling for restart.
```

From . **/runtime/conf.c** you can see that the initialization process uses the 'net' module, and the comment says that it is in the process of resolving the dependency, can you please tell me if it is currently working properly to call --disable-net.

![image](https://github.com/rsyslog/rsyslog/assets/104970073/60223173-fb68-4b8b-a76e-470800a2d8f9)

### Steps to reproduce the behavior
Use the rsyslog configuration option disable-inet to start the rsyslogd binary after compilation.
### Environment
rsyslog_8.2110.0

**Comment by linzhuorong** [comment]
From the code comments it looks like decoupling 'net' has been around since 2008, what is the plan for decoupling 'net' and is it not supported yet?

**Comment by davidelang** [comment]
please post your full config

David Lang

**Comment by rgerhards** [comment]
> From the code comments it looks like decoupling 'net' has been around since 2008, what is the plan for decoupling 'net' and is it not supported yet?

It looks like we forgot to remove the --disable-inet option. As everything is now modular, you do not need to disable any built-in code. Just don't load networking plugins.

**Comment by linzhuorong** [comment]
> > From the code comments it looks like decoupling 'net' has been around since 2008, what is the plan for decoupling 'net' and is it not supported yet?
> 
> It looks like we forgot to remove the --disable-inet option. As everything is now modular, you do not need to disable any built-in code. Just don't load networking plugins.

Can't the --disable-net option be implemented?

**Comment by davidelang** [comment]
On Thu, 20 Jul 2023, linzhuorong wrote:

>>> From the code comments it looks like decoupling 'net' has been around since 2008, what is the plan for decoupling 'net' and is it not supported yet?
>>
>> It looks like we forgot to remove the --disable-inet option. As everything is now modular, you do not need to disable any built-in code. Just don't load networking plugins.
>
> Can't the --disable-net option be implemented?

if anything it should be made into a noop for backwards compatibility, but it's 
just not needed, If you don't have a config file that uses the network by 
loading network modules, rsyslog doesn't try to use the network.

In very old versions, the network code was built-in, so this option was a way to 
disable it, but now that code is loaded as a module, so if you don't load a 
module there is nothing to disable.

And there are now a LOT of different modules that can talk to the network. 
Modifying all of those modules to support this option would be a lot of work. 
What would the benefit be?

David Lang

**Comment by rgerhards** [comment]
Just to be sure, I checked the code. Actually, there is one - important - place where --enable-inet is actually causing code changes: If enabled, omfwd is loaded by default. This is necessary to keep compatible to old configs. As such, I think I'll address the issue and make rsyslog build with --disable-inet. **However, it must be noted that when networking plugins are loaded, network access of course happens.**

The option could also cause some load errors in some networking modules due to the remove of some utility functions. This is then expected behaviour.

**Comment by AlfredWJ** [comment]
After reading this issue, I thought that rsyslog does not need remote logging functionality in many scenarios, so I wonder if we can also configure --disable-fmhttp after configuring --disable-inet？

**Comment by rgerhards** [comment]
> so I wonder if we can also configure --disable-fmhttp after configuring --disable-inet？

of course. You can disable/enable as many settings as you like. They are independet (except for a small set of developer settings).

Keep in mind that `fmhttp` is not active by default. You need to explicitely load it
```
module(load="fmhttp")
```
So, practically speaking, it does not make much of a difference if you disable it's build (of course, than there is no binary present, which securely prevents it from being loaded ;-)).
