### ISSUE TITLE
printk timestamp lost with imjournal

### ISSUE THREAD

**Issue by haoren3696** [rsyslog/rsyslog#519]
hi, I found the printk timestamp lost in kernel logs when using imjournal plugin. It seems that there is no 
configure to get it. Is threre any ways to get printk timestamp with imjournal plugin?

**Comment by rgerhards** [comment]
I don't even know if the journal preserves it. Do you see it in journalctl?

**Comment by haoren3696** [comment]
journal preserves it in _SOURCE_MONOTONIC_TIMESTAMP, but it seems that imjournal does not read it from the journal log,here is my patch to fix it,maybe there is  a better solution

diff --git a/plugins/imjournal/imjournal.c b/plugins/imjournal/imjournal.c
index 7d42b84..126f42a 100755
--- a/plugins/imjournal/imjournal.c
+++ b/plugins/imjournal/imjournal.c
@@ -184,12 +184,15 @@ readjournal() {
 
 	struct timeval tv;
 	uint64_t timestamp;
+	uint64_t monotonic_timestamp;
 
 	struct json_object *json = NULL;
 	int r;
 
 	/* Information from messages */
 	char *message;
+      char *t;
+      char *tpmessage;
 	char *sys_pid;
 	char *sys_iden;
 	char *sys_iden_help;
@@ -393,8 +396,19 @@ readjournal() {
 		tv.tv_usec = timestamp % 1000000;
 	}
 
-	/* submit message */
-	enqMsg((uchar *)message, (uchar *) sys_iden_help, facility, severity, &tv, json);
+	if (sd_journal_get_data(j, "_SOURCE_MONOTONIC_TIMESTAMP", &get, &length) >= 0)
+       {
+		 t = strndup(get+28, length-28);
+                monotonic_timestamp = atoll(t);
+                free(t);
+                tpmessage = (char *)malloc(strlen(message)+20);    
+                snprintf(tpmessage,16,"[%5lu.%06lu] ",monotonic_timestamp/1000000, monotonic_timestamp%1000000);
+                memcpy(tpmessage+15,message,strlen(message)+1);
+                enqMsg((uchar *)tpmessage, (uchar *) sys_iden_help, facility, severity, &tv, json);
+                free(tpmessage);
+       }else
+                /* submit message */
+                enqMsg((uchar *)message, (uchar *) sys_iden_help, facility, severity, &tv, json);
 
 finalize_it:
 	free(sys_iden_help);

**Comment by rgerhards** [comment]
I think this patch tries to modify a message in a way that doesn't look right to me. If the journal says "this is the message" but strips the kernel timestamp and shuffles it to an extended property, then we should use it that way. Otherwise we get too many crappy little rules. Plus, signatures eventually present inside the message do not work.

You could do this with a template if you think this is what you need. Place

``*.* /var/log/msgprops.log;RSYSLOG_DebugFormat``

to the top of your rsyslog.conf. The file contains the message including all properties. You should find the monotonic timestamp as a property, and could use that inside your template.

**Comment by rgerhards** [comment]
@theinric what is your position on this topic?

**Comment by theinric** [comment]
> hi, I found the printk timestamp lost in kernel logs when using imjournal plugin. It seems that there is
> no configure to get it. Is threre any ways to get printk timestamp with imjournal plugin?

> journal preserves it in _SOURCE_MONOTONIC_TIMESTAMP, you can see that with journalctl -o
> verbose,here is the sample output

Hello,

that  information is not lost, imjournal stores all journal variables as json variables which you can access, for example, from a template.
That patch is wrong; tweaking the message content is precisely what templates are for.

(digression: implementing such a configuration - writing to a single file with 2+ templates - touches on the months old discussion about templates not being flexible enough)

This issue should be closed as not-a-bug.
