### ISSUE TITLE
Segmentation fault  on linux system of openeuler arm64

### ISSUE THREAD

**Issue by HaoTien** [rsyslog/rsyslog#5210]
### Expected behavior
running
### Actual behavior
rsyslogd: imudp: scheduling policy set, but without priority - ignoring settings [v8.2110.0 try https://www.rsyslog.com/e/2205 ]
rsyslogd: imudp: module loaded, but no listeners defined - no input will be gathered [v8.2110.0 try https://www.rsyslog.com/e/2212 ]
rsyslogd: omkafka: error creating kafka handle: Failed to create thread: No such file or directory (2)  [v8.2110.0 try https://www.rsyslog.com/e/2422 ]
rsyslogd: action 'action-0-omkafka' (module 'omkafka') message lost, could not be processed. Check for additional error messages before this one. [v8.2110.0 try https://www.rsyslog.com/e/2422 ]
Segmentation fault (core dumped)
### Steps to reproduce the behavior
/usr/sbin/rsyslogd -n -f /etc/rsyslog.conf -i /export/log-agent/rsyslog.pid
### Environment
- rsyslog version: 
8.2110.0 (aka 2021.10)
- platform: 
aarch64-openEuler-linux-gnu
Linux version 5.10.0-1.oe.aarch64 (gcc (GCC) 10.3.1, GNU ld (GNU Binutils) 2.37) #1 SMP Wed May 24 11:11:30 CST 2023
- for configuration questions/issues, include rsyslog.conf and included config files
![image](https://github.com/rsyslog/rsyslog/assets/32786491/8553e831-7612-43c2-a7ab-772db1ddf907)

**Comment by davidelang** [comment]
please post your full config (rsyslog.conf and all included files)

Also, you aew using rsyslog from October 2021, it would be useful if you could 
test with a current version.

David Lang

**Comment by HaoTien** [comment]
我通过使用最新版本解决问题了

**Comment by HaoTien** [comment]
I solved the problem by using the latest version
