### ISSUE TITLE
STOP is followed by unreachable statements!

### ISSUE THREAD

**Issue by maravento** [rsyslog/rsyslog#5214]
### Expected behavior

boot normally without warnings

### Actual behavior

`warning during parsing file /etc/rsyslog.conf, on or before line 64: STOP is followed by unreachable statements!`

### Steps to reproduce the behavior

into `smb.conf`
```
# full audit
   full_audit:logfile = /var/log/samba/fullaudit.log
   full_audit:prefix = %I|%m|%S
   full_audit:success = mkdirat read pread write pwrite renameat unlinkat
   full_audit:failure = none
   full_audit:facility = LOCAL5
   full_audit:priority = notice
```
into `/etc/rsyslog.conf`

`*.none /var/log/samba/fullaudit.log`

I want to exclude from `fullaudit.log` messages related to nmbd, etc., to leave only messages related to the samba full audit module, but the problem is presented below:

into `/etc/rsyslog.d/50-default.conf`

If I configure it as follows:
```
local5.* /var/log/samba/fullaudit.log
:msg, contains, "nmdb" stop
:msg, contains, "winbindd" stop
& stop
```
The following message appears in the rsyslog output:
```
warning during parsing file /etc/rsyslog.conf, on or before line 64: STOP is followed by unreachable statements!
```
note: line 64 is `*.none /var/log/samba/fullaudit.log`

which disappears when I change the settings:
```
local5.* /var/log/samba/fullaudit.log
& stop
:msg, contains, "nmdb" stop
:msg, contains, "winbindd" stop
```
But I'm not sure if this change affects only `fullaudit.log` or the other logs

What is the correct way to do this?

### Environment
```
samba --version
Version 4.15.13-Ubuntu
rsyslogd -N1
rsyslogd: version 8.2112.0
Ubuntu 22.04
```

**Comment by davidelang** [comment]
On Mon, 21 Aug 2023, Maravento wrote:

> If I configure it as follows:
> ```
> local5.* /var/log/samba/fullaudit.log
> :msg, contains, "nmdb" stop
> :msg, contains, "winbindd" stop
> & stop
> ```
> The following message appears in the rsyslog output:
> ```
> warning during parsing file /etc/rsyslog.conf, on or before line 64: STOP is followed by unreachable statements!
> ```
> note: line 64 is `*.none /var/log/samba/fullaudit.log`
>
> which disappears when I change the settings (but I don't know if it works):
> ```
> local5.* /var/log/samba/fullaudit.log
> & stop
> :msg, contains, "nmdb" stop
> :msg, contains, "winbindd" stop
> ```
> What is the correct way to do this?

what is it you are trying to do? those two snippets of config do very different 
things.

the first one says that if the message contains winbindd then throw away the 
message, and throw away the message again (which is the statement that it's 
complaining about, you already threw away the message, so the & stop line is 
unreachable)

the second says that if the message has a facility of local5 write it to a file 
and then throw away the message, a very different thing thatn the first one.

This is why the & syntax is not recommended, instead group the statements you 
want to use the same logic in {}. using that syntax, this is what you are saying 
in the two sections:

first:

local5.* /var/log/samba/fullaudit.log
:msg, contains, "nmdb" stop
:msg, contains, "winbindd" {
    stop
    stop
}

second:

local5.* {
     /var/log/samba/fullaudit.log
     stop
}
:msg, contains, "nmdb" stop
:msg, contains, "winbindd" stop

since I don't know what you are trying to do, I can't say if either does what 
you want.

David Lang

**Comment by rgerhards** [comment]
The message say "on or **before** " for a reason. Grammar parsers often need a couple of lines more to detect errors.

I guess the problem is the second stop for the second filter - because that stop will never be reached. Practically, that's irrelevant, but it still is incorrect. There is also ne real reason for it.

My guess actually is that that stop belongs to the file writing action, Wich does not have one 😉

**Comment by maravento** [comment]
> On Mon, 21 Aug 2023, Maravento wrote: If I configure it as follows: ``` local5.* /var/log/samba/fullaudit.log :msg, contains, "nmdb" stop :msg, contains, "winbindd" stop & stop ``` The following message appears in the rsyslog output: ``` warning during parsing file /etc/rsyslog.conf, on or before line 64: STOP is followed by unreachable statements! ``` note: line 64 is `*.none /var/log/samba/fullaudit.log` which disappears when I change the settings (but I don't know if it works): ``` local5.* /var/log/samba/fullaudit.log & stop :msg, contains, "nmdb" stop :msg, contains, "winbindd" stop ``` What is the correct way to do this?
> what is it you are trying to do? those two snippets of config do very different things. the first one says that if the message contains winbindd then throw away the message, and throw away the message again (which is the statement that it's complaining about, you already threw away the message, so the & stop line is unreachable) the second says that if the message has a facility of local5 write it to a file and then throw away the message, a very different thing thatn the first one. This is why the & syntax is not recommended, instead group the statements you want to use the same logic in {}. using that syntax, this is what you are saying in the two sections: first: local5.* /var/log/samba/fullaudit.log :msg, contains, "nmdb" stop :msg, contains, "winbindd" { stop stop } second: local5.* { /var/log/samba/fullaudit.log stop } :msg, contains, "nmdb" stop :msg, contains, "winbindd" stop since I don't know what you are trying to do, I can't say if either does what you want. David Lang

what I'm trying to do, I explained in the description. But for you to understand, I will explain it again.
I want the `fullaudit.log` to contain no messages related to `nmbd` or `winbind` or anything other than messages from the samba full audit module.

Have I made myself clear enough or do you need more explanation?

**Comment by maravento** [comment]
These are messages that should not appear in the log:
```
  *****
[2023/08/19 15:41:36.562059,  0] ../../source3/smbd/server.c:1734(main)
  smbd version 4.15.13-Ubuntu started.
  Copyright Andrew Tridgell and the Samba Team 1992-2021
[2023/08/19 15:41:36.564168,  1] ../../source3/profile/profile_dummy.c:30(set_profile_level)
  INFO: Profiling support unavailable in this build.
[2023/08/19 15:46:09.620567,  0] ../../source3/nmbd/nmbd_namequery.c:109(query_name_response)
  query_name_response: Multiple (2) responses received for a query on subnet 192.168.1.10 for name WORKGROUP<1d>.
  This response was from IP 192.168.1.31, reporting an IP address of 192.168.122.1.
[2023/08/19 15:51:52.655268,  0] ../../source3/nmbd/nmbd_become_lmb.c:398(become_local_master_stage2)
  *****
  
  [2023/08/19 15:37:22.340577,  0] ../../source3/nmbd/nmbd.c:59(terminate)
  Got SIGTERM: going down...
[2023/08/19 15:37:23.390637,  0] ../../source3/nmbd/nmbd_namequery.c:109(query_name_response)
  query_name_response: Multiple (2) responses received for a query on subnet 192.168.1.10 for name WORKGROUP<1d>.
  This response was from IP 192.168.1.31, reporting an IP address of 192.168.122.1.
[2023/08/19 15:37:24.134618,  0] ../../source3/smbd/server.c:1734(main)
  smbd version 4.15.13-Ubuntu started.
  Copyright Andrew Tridgell and the Samba Team 1992-2021
[2023/08/19 15:37:24.136755,  1] ../../source3/profile/profile_dummy.c:30(set_profile_level)
  INFO: Profiling support unavailable in this build.
[2023/08/19 15:37:55.432548,  0] ../../source3/nmbd/nmbd_become_lmb.c:398(become_local_master_stage2)
  *****
  
  [2023/08/19 18:00:15.197301,  1] ../../source3/smbd/server.c:1417(smbd_parent_sig_hup_handler)
  parent: Reloading services after SIGHUP
[2023/08/19 18:00:15.197818,  1] ../../source3/winbindd/winbindd.c:364(winbindd_sig_hup_handler)
  Reloading services after SIGHUP
  
  [2023/08/19 16:30:15.769059,  1] ../../source3/winbindd/winbindd.c:364(winbindd_sig_hup_handler)
  Reloading services after SIGHUP
[2023/08/19 17:00:16.929998,  1] ../../source3/smbd/server.c:1417(smbd_parent_sig_hup_handler)
  parent: Reloading services after SIGHUP
[2023/08/19 17:00:16.931656,  0] ../../source3/nmbd/nmbd.c:167(nmbd_sig_hup_handler)
  Got SIGHUP dumping debug info.
[2023/08/19 17:00:16.931711,  0] ../../source3/nmbd/nmbd_workgroupdb.c:279(dump_workgroups)
```

**Comment by davidelang** [comment]
any examples of the logs that should appear in the file?

also, these logs are not in a valid syslog format, can you adjust the format on 
the sending side? not being in the correct format will lead to parsing failures 
as the heuristics try to make the best of the data they are given.

David Lang

**Comment by maravento** [comment]
again: only leave the messages that contain `smbd_audit` and discard the rest. example:

```
Aug 20 16:43:53 user smbd_audit: 192.168.1.33|desktop-j31rhnb|shared|renameat|ok|/home/user/shared_folder/ADAC21F7.tmp|/home/user/shared_folder/filetest.xlsx
Aug 20 16:43:54 user smbd_audit: 192.168.1.33|desktop-j31rhnb|shared|unlinkat|ok|/home/user/shared_folder/~$filetest.xlsx
```

**Comment by davidelang** [comment]
In this case,

if $syslogtag == "smbd_audit:" then /path/path/to/file

would be the simplest way.

David Lang

**Comment by maravento** [comment]
> In this case, if $syslogtag == "smbd_audit:" then /path/path/to/file would be the simplest way. David Lang
> […](#)
> On Mon, 21 Aug 2023, Maravento wrote: Date: Mon, 21 Aug 2023 09:50:42 -0700 From: Maravento ***@***.***> Reply-To: rsyslog/rsyslog ***@***.***> To: rsyslog/rsyslog ***@***.***> Cc: David Lang ***@***.***>, Comment ***@***.***> Subject: Re: [rsyslog/rsyslog] STOP is followed by unreachable statements! (Issue #5214) again: only leave the messages that contain `smbd_audit` and discard the rest. example: ``` Aug 20 16:43:53 user smbd_audit: 192.168.1.33|desktop-j31rhnb|shared|renameat|ok|/home/user/shared_folder/ADAC21F7.tmp|/home/user/shared_folder/filetest.xlsx Aug 20 16:43:54 user smbd_audit: 192.168.1.33|desktop-j31rhnb|shared|unlinkat|ok|/home/user/shared_folder/~$filetest.xlsx ```

more noise:

`user smbd_audit: pam_unix(samba:session): session closed for user user`

**Comment by davidelang** [comment]
Ok, how can we identify these smdb_audit logs that you don't want as opposed to 
the ones you do want?

try logging these both with the template RSYSLOG_DebugFormat so we can see 
everything about these logs (is there a severity difference or anything else 
that's a clear differentiator between the logs you want and the logs you don't)

is "smdb_audit" something you are explicitly setting in samba for these logs? 
try changing it to something else (it's possible that some standard logs use 
smdb_audit for their logs)

David Lang

**Comment by maravento** [comment]
> if $syslogtag == "smbd_audit:" then /path/path/to/file

what is wrong with my solution? (works)

```
# this line is for the logs to be saved in "fullaudit.log"
local5.* /var/log/samba/fullaudit.log
# this line is so that messages are not saved in "syslog"
& stop
# this line is to select only the messages that contain "smb_audit" and send them to "fullaudit.log"
:msg, contains, "smbd_audit" /var/log/samba/fullaudit.log
# this line discards any messages other than "smbd_audit"
:msg, !contains, "smbd_audit" stop
```

**Comment by davidelang** [comment]
On Mon, 21 Aug 2023, Maravento wrote:

>> if $syslogtag == "smbd_audit:" then /path/path/to/file
>
> what is wrong with my solution? (works)

if it works, it works. It's not great to have multiple statements writing to the 
same file and may cause some issues.

using & isn't as clear as using {} to group the things you want to use the sane 
filter

> ```
> # this line is for the logs to be saved in "fullaudit.log"
> local5.* /var/log/samba/fullaudit.log

this will write all local5 logs to this file, even if they don't contain 
smbd_audit in them

> # this line is so that messages are not saved in "syslog"
> & stop

they won't be saved anywhere else, and no lines further in the file will be 
processed for the log message that was just saved

> # this line is to select only the messages that contain "smb_audit" and send them to "fullaudit.log"
> :msg, contains, "smbd_audit" /var/log/samba/fullaudit.log

if this is intended to include the things logged as local5, that won't happen as 
they have already been thrown away

> # this line discards any messages other than "smbd_audit"
> :msg, !contains, "smbd_audit" stop

This throws away all logs that don't contain smbd_audit logs, so the only logs 
that will be processed by any later logs in the file (or that are included after 
this point) are going to be the ones that contain smbd_audit and have a facility 
other than local5.

This doesn't seem to match what you stated your desire to be.

David Lang

**Comment by maravento** [comment]
Ok. My solution is wrong. but yours doesn't solve the problem either, and it keeps getting noise in the log:

`if $syslogtag == "smbd_audit:" then /path/path/to/file`

out:

`user smbd_audit: pam_unix(samba:session): session closed for user user`

**Comment by davidelang** [comment]
On Mon, 21 Aug 2023, Maravento wrote:

> Ok. My solution is wrong. but yours doesn't solve the problem either, and it keeps getting noise in the log:
>
> `if $syslogtag == "smbd_audit:" then /path/path/to/file`
>
> out:
>
> `user smbd_audit: pam_unix(samba:session): session closed for user user`

see my prior post to request you to log with the template RSYSLOG_DebugFormat 
and asking if you are setting the string smbd_audit or if that's the default.

in other words, how should be tell the logs you want from the logs you don't 
want. nothing you have provided tells me how to identify that log isn't one that 
you want (and as an audit item, the beginning or ending of a session is 
legitimate)

David Lang

**Comment by maravento** [comment]
You must explain what parameters I declare in template RSYSLOG_DebugFormat, in order to provide them to you

**Comment by davidelang** [comment]
if $syslogtag == "smbd_audit:" then /path/path/to/file;RSYSLOG_DebugFormat

**Comment by maravento** [comment]
> 

https://mega.nz/file/zB0h3BIY#4efjQFFCu2mL9kHmle8OXGZociyL6EF-QseYoqk54F0

PD: contains real and private data, therefore the file will be deleted tomorrow

**Comment by davidelang** [comment]
I get a message that the file is no longer available.

can you just post a sample of the logs you want and the logs you don't want?

David Lang

**Comment by maravento** [comment]
[debug.txt](https://github.com/rsyslog/rsyslog/files/12408459/debug.txt)

**Comment by maravento** [comment]
I tried this rule but it does not record anything in the log:

```
if $syslogtag contains "smbd_audit:" then {
    if not $msg contains "pam_unix" then {
        /var/log/samba/fullaudit.log
        stop
    }
}
```

**Comment by davidelang** [comment]
so from the messages you posted, the pam ones are facility secure/auth and the 
other ones are local5 (which makes me think that you have something set manually 
to create the local5 ones that happens to use the syslogtag that's already used 
by default for the pam ones, and you can change that tag to make it unique)

but as is you could do something like

if $syslogtag == "smb_audit:" and $facilty == "local5" then {
    /var/log/samba/fullaudit.log
    stop
}

I'm not sur why your example below is not working.

David Lang

**Comment by rgerhards** [comment]
My guess is that there is still a `stop` rule between the begin of config and that snippet.. I don't see anything wrong.

**Comment by rgerhards** [comment]
I forgot: You can test my assumption by moving that snippet **to the top of rsyslog.conf**. By "top" I mean line 1, not some other "top".

**Comment by maravento** [comment]
invalid property 'facilty' [v8.2 etc etc

**Comment by davidelang** [comment]
see https://www.rsyslog.com/doc/master/configuration/properties.html

it should have been $syslogfacility-text

David Lang

**Comment by rgerhards** [comment]
@maravento it doesn't help that you ignore my answers, so I will stop looking at this thread.

**Comment by maravento** [comment]
> @maravento it doesn't help that you ignore my answers, so I will stop looking at this thread.

I have read your comments, but so far none of the proposals of the participants have solved the issue, to close it. So if you don't want to participate, don't.

**Comment by maravento** [comment]
> if $syslogtag == "smb_audit:" and $facilty == "local5" then { /var/log/samba/fullaudit.log stop }

No errors and no output logs either with:

```
if $syslogtag == "smb_audit:" and $syslogfacility-text == "local5" then {
    /var/log/samba/fullaudit.log
    stop
}
```

**Comment by davidelang** [comment]
please post your full config (including any included files or the output of 
starting with -o /path/to/file command line options)

David Lang

**Comment by maravento** [comment]
[dataconf.tar.gz](https://github.com/rsyslog/rsyslog/files/12412840/dataconf.tar.gz)

**Comment by maravento** [comment]
I have tried this solution and it is working perfectly. The only drawback is that it duplicates the logs (both in `/var/log/samba/fullaudit.log` and `/var/log/syslog`):

into `/etc/rsyslog.conf`
```
*.info;mail.none;authpriv.none;cron.none;local5.none /var/log/messages
local5.* /var/log/samba/fullaudit.log
```

**Comment by davidelang** [comment]
based on the smb.conf

if $PRI == 173 then {
       /var/log/samba/fullaudit.log
     stop
}


may be good enough, if not try

if ($PRI == 173 and $syslogtag == "smbd_audit:") then {
       /var/log/samba/fullaudit.log
     stop
}

I don't think the () are strictly needed, but I like to have them as it makes it 
more obvious what's happening.

note that since this is the last thing in your config, the stop doesn't really 
do anything. If you want to not have these logs go to the places specified in 
50-default.conf, you would need to move this up above the include.

David Lang

**Comment by davidelang** [comment]
that is because the file /etc/rsyslog.d/50-default.conf is included in your 
config file before the lines you show below. This is why we ask for the full 
config.

if you get look at the combined config that you get if you start rsyslog with -o 
/path/to/file it will be more obvious why.

David Lang

**Comment by maravento** [comment]
> 

Maybe I didn't explain correctly. I removed the settings from `50-default.conf` to default values and I am only applying the settings proposed in `rsyslog.conf` (both the one I proposed and the ones you proposed)

**Comment by davidelang** [comment]
Ok, but are you still putting your changes to rsyslog.conf after the include 
that pulls in 50-default? if so, rsyslog will first write all the logs per the 
actions in 50-default, then process the lines you added below that.

As such, the lines you add below that, can't remove the logs from the files 
already written out to disk.

David Lang

**Comment by davidelang** [comment]
the reason I keep asking for the output of the -o option is that it combines all 
the files and shows you what rsyslog is seeing the config to be. That will make 
it obvious what order the actions across all the files are processed in.

David Lang

**Comment by maravento** [comment]
Please tell which file should I apply the settings you propose, because I removed previous settings in rsyslog.conf and 50-default.conf and applied your settings and it doesn't work

**Comment by maravento** [comment]
What's wrong with my proposal?... It works well. Only `smbd_audit` records are duplicated in `/var/log/syslog`

into `/etc/rsyslog.conf`
```
*.info;mail.none;authpriv.none;cron.none;local5.none /var/log/messages
local5.* /var/log/samba/fullaudit.log
```
into `/etc/rsyslog.d/50-default.conf` no custom rule. contains only the default values that are included during installation

**Comment by davidelang** [comment]
post the full config from -o and I will walk you through why it is doing exactly 
what you are telling it to do.

David Lang

**Comment by davidelang** [comment]
the problem is not with these lines, or what file you are putting the lines in, 
but in the order that you have lines in the files, and since you are not posting 
the lines here, I can't seem to get across the ordering problem to you.

David Lang

**Comment by maravento** [comment]
> 

I don't know exactly what you want me to do. You say `-o /path/to_file` but I don't know what you mean by that. Whether it is to start rsyslog with that statement or something else. Please be more specific and I will gladly provide the information.

**Comment by davidelang** [comment]
add the switch -o to the rsyslog command line, it takes one parameter, the path 
to the file that it will create.

David Lang

**Comment by maravento** [comment]
I still don't understand what you want. But I did the following and now you tell me what you want me to give you

edit `/etc/rsyslog.conf`

add:
```
if $PRI == 173 then {
       -o /var/log/samba/fullaudit.log
     stop
}
```
if there is something else you want me to do, you must explain it in more detail and tell me which file you want me to deliver

**Comment by davidelang** [comment]
no, when you start rsyslog, you have a command line that is rsyslogd with some 
parameters (I don't know what your system has), add -o /etc/rsyslog-combined.conf
and when you start rsyslog it will create the file /etc/rsyslog-combined.conf 
that will have the result of combining all your config files as rsyslog sees 
them

David Lang

**Comment by maravento** [comment]
Since you're still not specific in your instructions, I did the following:

`sudo /etc/init.d/rsyslog restart -o /etc/rsyslog-combined.conf`

out:
`/etc/rsyslog-combined.conf` is empty

**Comment by davidelang** [comment]
I do not know what distro you are using, let alone the details of that distro.

but from this, you have a script /etc/init.d/rsyslog that script somewhere in it 
creates the command line that starts rsyslog. How it does this varies from 
distro to distro. look at that command line and either modify the script, or 
stop rsyslog with the script and run the command line (with the addition) 
manually as root.

David Lang

**Comment by maravento** [comment]
> I do not know what distro you are using, let alone the details of that distro.
> 
> but from this, you have a script /etc/init.d/rsyslog that script somewhere in it 
> creates the command line that starts rsyslog. How it does this varies from 
> distro to distro. look at that command line and either modify the script, or 
> stop rsyslog with the script and run the command line (with the addition) 
> manually as root.
> 
> David Lang
> 
> On Tue, 22 Aug 2023, Maravento wrote:
> 
> > Since you're still not specific in your instructions, I did the following:
> >
> > `sudo /etc/init.d/rsyslog restart -o /etc/rsyslog-combined.conf`
> >
> > out:
> > `/etc/rsyslog-combined.conf` is empty
> >
> >
> 

Again. my system is ubuntu 22.04

**Comment by davidelang** [comment]
On Tue, 22 Aug 2023, Maravento wrote:

> Again. my system is ubuntu 22.04


that does me no good as I don't have such a system available, and I'm not going 
to go to the trouble of building one just to answer this question.

try doing
ps ax |grep rsyslog
so you can see the flags that your system starts rsyslog with
then
/etc/init.d/rsyslog stop
to shut it down

then run the command line manually, but add the -o flag

David Lang

**Comment by maravento** [comment]
According to your instructions, I did this:
```
sudo systemctl stop syslog.socket rsyslog.service
ps ax | grep rsyslog
294480 pts/2    S+     0:00 grep --color=auto rsyslog
sudo /usr/sbin/rsyslogd -o file.txt
ps ax | grep rsyslog
 294400 ?        Ssl    0:00 /usr/sbin/rsyslogd -o file.txt
 294480 pts/2    S+     0:00 grep --color=auto rsyslog
```
[file.txt](https://github.com/rsyslog/rsyslog/files/12419648/file.txt)

the content of `file.txt` is the same as that of rsyslog.conf. I don't know exactly what's the point of what you're asking. I don't see anything new

**Comment by maravento** [comment]
The data is now in 50-default.conf for you to review the new output.

[file.txt](https://github.com/rsyslog/rsyslog/files/12419801/file.txt)

Two things:
1. Your proposal does not work. No output in `fullaudit.log`
```
if $PRI == 173 then {
        /var/log/samba/fullaudit.log
      stop
}
```
2. If I disable the syslog line (`*.*;auth,authpriv.none		-/var/log/syslog`) what exactly does it stop writing? (the smb_audit or all' logs)

**Comment by maravento** [comment]
following your instructions, the rule is now in `50-default.conf`. Check new `file.txt` for you to review.

[file.txt](https://github.com/rsyslog/rsyslog/files/12419885/file.txt)

Two things:

- Your proposal does not work. No output in `fullaudit.log`
```
if $PRI == 173 then {
        /var/log/samba/fullaudit.log
      stop
}
```
- If i comment the syslog line (`*.*;auth,authpriv.none		-/var/log/syslog`) what exactly does it stop writing? (the `smb_audit` only or all logs in `syslog`)

**Comment by davidelang** [comment]
it doesn't matter what file you put it in, what matters is the order of things 
in the file.

you still write it out to /var/log/syslog before you get to your new if 
statement.

start at the top of the file (really the combined file as produced by the -o 
because that's what rsyslog sees) and go down through the file, for each filter 
that matches the log, take the action specified by the filter. If you see a stop 
as an action, stop looking at filters

you have:

*.*;auth,authpriv.none          -/var/log/syslog
and 
if $PRI == 173 then {
      /var/log/samba/fullaudit.log
      stop
}

both of these filters match this log, so it first writes to /var/log/syslog and 
then matches the PRI value, writes to /var/log/samba/fullaudit.log and then hits 
stop to not look at anything else.

It's doing exactly what you told it to do.

As we have been saying since the beginning of this thread, the order matters, 
you need to move the fullaudit.log section ahead of the /var/log/syslog section.

David Lang

**Comment by maravento** [comment]
so far it is working fine. A question. Could you explain what "if $PRI == 173" means? Thanks in advanced

**Comment by davidelang** [comment]
look at the debugformat log you sent me. All the logs that you are wanting has a 
PRI value of 173

this is the same as local5.notice, which is what you set the logs you want to in 
the smb.conf file

see 
https://techdocs.broadcom.com/us/en/symantec-security-software/identity-security/privileged-access-manager/4-0/reference/messages-and-log-formats/syslog-message-formats/syslog-priority-facility-severity-grid.html 
for a table of what facility/severity equates to what pri number

David Lang

**Comment by maravento** [comment]
thanks a lot for your help

**Comment by maravento** [comment]
This one also works:
if ($programname == 'smbd_audit') then {
action(type="omfile" file="/var/log/samba/audit.log")
stop
}
