### ISSUE TITLE
rsyslog crashes on restart in imrelp SIGTTIN

### ISSUE THREAD

**Issue by Alix82** [rsyslog/rsyslog#5219]
### Expected behavior

Should not crash

### Actual behavior

It crashes occasionally

### Steps to reproduce the behavior

To easily reproduce run the following script

`#!/bin/bash

FILE=/coredumps/core-*
count=0
while true ; do
        count=$((count+1))
        echo "restart rsyslog count = $count"
	sudo systemctl restart rsyslog
        if [ -f "$FILE" ]; then
                echo "Found coredump!!!!"
                break
        fi
	sleep 5
done`

While sending SIGTTIN continuously

`while :; do pgrep rsyslogd | xargs kill -21; done`

There are two issues, depending on the configuration

1. debug.unloadModules="off"
2. debug.unloadModules="on" (default)

With configuration (1), the crash is caused by a double free in doSIGTTIN of pRelpEngine
With configuration (2), the signal handler sometimes is called when it is already been unmapped from memory with the following backtrace

`#0  0x00007fbd42518c20 in ?? ()
(gdb) bt
#0  0x00007fbd42518c20 in ?? ()
#1  <signal handler called>
#2  _fini () at ../sysdeps/x86_64/crti.S:80
#3  0x00007fbd42479478 in _dl_fini () at dl-fini.c:161
#4  0x00007fbd416c79c9 in __run_exit_handlers (status=0, listp=0x7fbd41a2c540 <__exit_funcs>, run_list_atexit=run_list_atexit@entry=true)
    at exit.c:82
#5  0x00007fbd416c7a15 in __GI_exit (status=<optimized out>) at exit.c:104
#6  0x00007fbd416b0acc in __libc_start_main (main=0x40fd00 <main>, argc=3, argv=0x7ffcec0f1538, init=<optimized out>, 
    fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffcec0f1528) at libc-start.c:323
#7  0x0000000000410179 in _start () at ../sysdeps/x86_64/start.S:118`

I'm preparing a pull request with patch to fix both issues.

### Environment
rsyslog [v8.2308.0]

**Comment by davidelang** [comment]
full config please

David Lang

**Comment by Alix82** [comment]
It is just standard imrelp omrelp client-server setup, such as [this one](https://gist.github.com/drmalex07/bb178d61f800488446d22de4301160f1)

In our production environment the crash doesn't happen too often, but it is still a problem as it is a security setup (The crash itself depends on SIGTTIN being received at a very specific time while rsyslog is shutting down). 

Sending SIGTTIN continuously helps reproduce the issue more quickly

Thank you.

**Comment by Alix82** [comment]
Any thoughts on this rather tiny fix please?

Thanks.
