### ISSUE TITLE
Journal issues in old and new versions

### ISSUE THREAD

**Issue by junx964** [rsyslog/rsyslog#5221]
### Expected behavior
In the configuration files of earlier versions, the journal module will be introduced by default, for example: 8.24.0
### Actual behavior
In 8.2102.0, the journal module is not loaded in the configuration file, why can the smb audit log be recorded?

At present, I need to know whether in 8.2102.0, when a large number of audit logs arrive, without the journal module, there will be restrictions like using the journal module, and the consequences will not be recorded.

### Environment
- rsyslog version: 8.2102.0 
- platform: debian11

**Comment by rgerhards** [comment]
You need to talk to the Debian project in regard to this. The rsyslog project does not provide any recommended configuration. The distro decides how they handle that.
