### ISSUE TITLE
Mixed case in hostname leads to message ignored

### ISSUE THREAD

**Issue by Touffman78** [rsyslog/rsyslog#5259]
### Expected behavior
Traeted as valid message
### Actual behavior
Message is ignored
### Steps to reproduce the behavior
Receiving mesages from different sources via UDP (port 514) using RFC3164 and forwarding to another host.
When receiving messages from a host like this its OK (message is forwarded) :
`<30>Oct 26 10:00:02 hostnamem22xx systemd: Removed slice User Slice of root.`

But when receiving message from host like this its NOK (message is not forwarded) :
`<30>Oct 26 10:00:02 hostnameS04xx systemd: Removed slice User Slice of root.`

The only different is that in the non working message hostname contains uppercase letters with lowercase ones.
I done some debug and only messages with all lowercase letters in hostname are shown...

### Environment
- rsyslog version: 8.24.0-57.el7_9.2
- platform: RHEL 7.9
- for configuration questions/issues, include rsyslog.conf and included config files

**Comment by rgerhards** [comment]
**In order to fully understand your issue, we need to know how your consolidated rsyslog.conf looks like.** This is rsyslog.conf including all config snippets. We need it, because order of config statements matters. You can easily create it. **Follow this guide by Rainer Gerhards on [how to create a consolidated rsyslog.conf](https://rainer.gerhards.net/2023/09/rsyslog-how-to-debug-rsyslog-conf-problems.html).**

That link also contains additional helpful information on config snippets and how they can introduce subtle issues. That alone might help.

**Comment by Touffman78** [comment]
Hi Rainer,

And thanks for your answer. I need to anonymise some parts of the config file. It's why I didn't post one before. 
Unfortunately, option -o is not recognized :
````
sudo rsyslogd -N 1 -o consolidated-rsyslog.conf -f /etc/rsyslog.conf
usage: rsyslogd [options]
use "man rsyslogd" for details. To run rsyslog interactively, use "rsyslogd -n"to run it in debug mode use "rsyslogd -dn"
For further information see http://www.rsyslog.com/doc
````
```
OPTIONS
       -D     Runs the Bison config parser in debug mode. This may help when hard to find syntax errors are reported. Please note that the output generated is deeply technical and orignally tar‐
              geted towards developers.

       -d     Turns on debug mode. See the DEBUGGING section for more information.

       -f config file
              Specify an alternative configuration file instead of /etc/rsyslog.conf, which is the default.

       -i pid file
              Specify an alternative pid file instead of the default one.  This option must be used if multiple instances of rsyslogd should run on a single machine.

       -n     Avoid auto-backgrounding.  This is needed especially if the rsyslogd is started and controlled by init(8).

       -N  level
              Do  a  coNfig  check.  Do NOT run in regular mode, just check configuration file correctness.  This option is meant to verify a config file. To do so, run rsyslogd interactively in
              foreground, specifying -f <config-file> and -N level.  The level argument modifies behaviour. Currently, 0 is the same as not specifying the -N option at all (so this makes limited
              sense) and 1 actually activates the code. Later, higher levels will mean more verbosity (this is a forward-compatibility option).

       -C     This prevents rsyslogd from changing to the root directory. This is almost never a good idea in production use. This option was introduced in support of the internal testbed.

       -v     Print version and exit.

SIGNALS

```
As I'm using a ruleset, maybe this part is sufficient (remote.conf is in /etc/rsyslog.d directory) :
```
# process remote messages
# Provides UDP syslog reception
module(load="imudp")

# Provides TCP syslog reception
module(load="imtcp")

# define template with PRI
template(name="TraditionalFormatWithPRI" type="string" string="%pri-text%: %timegenerated% %HOSTNAME% %syslogtag%%msg:::drop-last-lf%\n")

# define new ruleset and add rules to it:
ruleset(name="remote_log") {
    if (re_match($hostname, "^(lxxxx|byyyy)")) then {
        local6.* { stop }
    }
    *.=debug;user,local4.*;daemon.=notice { stop }
    if re_match($programname, "^sshd") then {
        if $msg == " sent status No such file [postauth]" then { stop }
        if re_match($msg, "^ (open|close)(dir)? \"") then { stop }
        if re_match($msg, 'Deprecated option R.+Authentication$') then { stop }
    }
    action(type="omfwd" target="10.a.b.c" port="601" protocol="tcp")
}

# bind ruleset to tcp listener
input(type="imtcp" port="601" ruleset="remote_log")

# bind ruleset to udp listener
input(type="imudp" port="514" ruleset="remote_log")

```

Just for supplementary information : _all lowercase hostname_ and _all uppercase hostname_ messages are correctly forwarded, only those with hostnames containing mixed case are ignored.

Regards.

**Comment by rgerhards** [comment]
> Unfortunately, option -o is not recognized

yeah, you are using a heavily outdated version. This might even be the problem you have, but I do not (yet) think so.

From the config snippet I would also assume that all messages are transmitted. But maybe some anonymization removes the actual problem. We could do debug log to dig deeper, but there would be privacy concerns as well. If you need private support, you may consider https://www.rsyslog.com/professional-services/enterprise-support/

**I would tend to think, however, that the problem exists on the receiver.** What is the receivers config? I guess that it receives the messages, but does not process those in upper case because of non-matching case-sensitive rules.

**Comment by Touffman78** [comment]
> I would also assume that all messages are transmitted.
Correct, if don't match the statements to discard messages.

> maybe some anonymization removes the actual problem
Anonymization have only been made on these 2 lines, all the remaining is the actual snippet :
`    if (re_match($hostname, "^(lxxxx|byyyy)")) then {`
and
`    action(type="omfwd" target="10.a.b.c" port="601" protocol="tcp")` 

Receiver is syslog-ng and don't have this problem.

**Comment by rgerhards** [comment]
> Receiver is syslog-ng and don't have this problem.

case-sensitivity is not a problem, but a feature. We have dedicated case sensitive and insensitive comparisons.

In any case, can you confirm that the messages are not sent? If so, we need a debug log.

**Comment by Touffman78** [comment]
Hi Rainer,
After a long time trying lots of debug, I've cracked my issue : just this fcking rp_filter that was active on my server and bad routing table...
Sorry for taking your time for a non-issue....

**Comment by rgerhards** [comment]
Thx for reporting back, that's much appreciated. And, yes, s**t happens. Everybody knows :)
