### ISSUE TITLE
Permission denied while starting TLS session in kali server

### ISSUE THREAD

**Issue by kaniMano** [rsyslog/rsyslog#5272]
### Expected behavior
To 
### Actual behavior
With the certificates, secured connection should be set up properly.
### Steps to reproduce the behavior
1) Install rsyslog and rsyslog-gnutls package in kali server
2) Open TCP port 6514
3) Create SSL certificates and update it in conf file under /etc/rsyslog.d. 
4) Restart rsyslog service and it ends up in permission denied (though i have proper permission and ownership set).
### Environment
- rsyslog version: 
- 
<img width="367" alt="rsyslog_server_version" src="https://github.com/rsyslog/rsyslog/assets/28338717/11f43922-c129-474f-840b-b59a940ee8f2">

- platform: 
<img width="305" alt="kali_server_version" src="https://github.com/rsyslog/rsyslog/assets/28338717/a346f023-73cd-46f3-b533-25682e277fdf">

- for configuration questions/issues, include rsyslog.conf and included config files

**Comment by kaniMano** [comment]
# /etc/rsyslog.conf configuration file for rsyslog
#
# For more information install rsyslog-doc and see
# /usr/share/doc/rsyslog-doc/html/configuration/index.html


#################
#### MODULES ####
#################

module(load="imuxsock") # provides support for local system logging
module(load="imklog")   # provides kernel logging support
#module(load="immark")  # provides --MARK-- message capability

# provides UDP syslog reception
module(load="imudp")
input(type="imudp" port="514")

# provides TCP syslog reception
#module(load="imtcp")
#input(type="imtcp" port="6514")


###########################
#### GLOBAL DIRECTIVES ####
###########################

#
# Set the default permissions for all log files.
#
$FileOwner root
$FileGroup adm
$FileCreateMode 0640
$DirCreateMode 0755
$Umask 0022

#
# Where to place spool and state files
#
$WorkDirectory /var/spool/rsyslog

#
# Include all config files in /etc/rsyslog.d/
#
$IncludeConfig /etc/rsyslog.d/*.conf


###############
#### RULES ####
###############

#
# Log anything besides private authentication messages to a single log file
#
*.*;auth,authpriv.none		-/var/log/syslog

#
# Log commonly used facilities to their own log file
#
auth,authpriv.*			/var/log/auth.log
cron.*				-/var/log/cron.log
kern.*				-/var/log/kern.log
mail.*				-/var/log/mail.log
user.*				-/var/log/user.log
local5.*                        -/var/log/pgsql
local3.*                        -/var/log/audit

#
# Emergencies are sent to everybody logged in.
#
*.emerg				:omusrmsg:*

**Comment by kaniMano** [comment]
##server.conf file
# make gtls driver the default
$DefaultNetstreamDriver gtls

# certificate files
$DefaultNetstreamDriverCAFile /root/certs/ca.pem
$DefaultNetstreamDriverCertFile /root/certs/server-cert.pem
$DefaultNetstreamDriverKeyFile /root/certs/server-key.pem

$ModLoad imtcp  # TCP listener
$InputTCPServerStreamDriverMode 1  # run driver in TLS-only mode
$InputTCPServerStreamDriverAuthMode anon
$InputTCPServerRun 6514  # start up listener at port 10514

**Comment by kaniMano** [comment]
<img width="398" alt="permissions" src="https://github.com/rsyslog/rsyslog/assets/28338717/5928456c-f673-436f-8eaf-f389c543282d">

**Comment by rgerhards** [comment]
has kali some security systems like SELinux? Is rsyslog compiled to drop capabilities?

For a quick try, move the certs to /etc/rsyslog.d -- usually distros permit rsyslog to read all files there. In other locations most often there are restrictions.

**Comment by kaniMano** [comment]
> has kali some security systems like SELinux? Is rsyslog compiled to drop capabilities?
> Havent installed any selinux related package in kali server. For rsyslog, just installed using "apt-get install rsyslog" and apt-get install rsyslog-gnutls
> For a quick try, move the certs to /etc/rsyslog.d -- usually distros permit rsyslog to read all files there. In other locations most often there are restrictions.
Thanks i moved it to /etc/rsyslog.d and now not seeing any permission denied errors.

**Comment by rgerhards** [comment]
> Thanks i moved it to /etc/rsyslog.d and now not seeing any permission denied errors.

Might be a solution for you.

In any case, it shows that kali has limited rsyslog read locations in some way. Just for others coming to this issue.
