### ISSUE TITLE
Multiple tests are failing on Linux SPARC

### ISSUE THREAD

**Issue by glaubitz** [rsyslog/rsyslog#5273]
On Linux SPARC (Debian unstable sparc64), multiple tests are failing in version 8.2310.0:

```
============================================
   rsyslog 8.2310.0: tests/test-suite.log
============================================

# TOTAL: 660
# PASS:  639
# SKIP:  8
# XFAIL: 0
# FAIL:  13
# XPASS: 0
# ERROR: 0
```

The failing tests are:

```
FAIL: asynwr_timeout.sh
(...)
FAIL: asynwr_simple.sh
FAIL: asynwr_simple_2.sh
FAIL: asynwr_timeout_2.sh
FAIL: asynwr_tinybuf.sh
FAIL: asynwr_dynfile_flushtxend-off.sh
FAIL: asynwr_deadlock2.sh
FAIL: gzipwr_hup_single_file.sh
(...)
FAIL: dynfile_invld_async.sh
(...)
FAIL: wr_large_async.sh
(...)
FAIL: asynwr_deadlock4.sh
(...)
FAIL: imfile-logrotate-async.sh
````

Full build log available in: https://buildd.debian.org/status/fetch.php?pkg=rsyslog&arch=sparc64&ver=8.2310.0-2&stamp=1699533418&raw=0

Looks like the failures started to show around version 8.2208.0: https://buildd.debian.org/status/logs.php?pkg=rsyslog&arch=sparc64

The test `imfile-logrotate-async.sh` also fails on 32-bit PowerPC: https://buildd.debian.org/status/fetch.php?pkg=rsyslog&arch=sparc64&ver=8.2310.0-2&stamp=1699533418&raw=0

SSH access to PowerPC and SPARC machines for testing can be obtained through the GCC compile farm: https://gcc.gnu.org/wiki/CompileFarm (NB: Linux SPARC machines are temporarily out of services, Solaris machines are available).

CC @kulikjak

**Comment by rgerhards** [comment]
These are most probably all flakes, possibly caused by too-slow progress. I have seen rsyslog abort because the allocated time frame for test completion was exhausted. The testbench is unfortunately somewhat depending on timing, also when we need to start up things like kafka.

**Comment by kulikjak** [comment]
Hi @glaubitz, on Solaris SPARC, we are currently shipping 8.2308, and we are not seeing any issues. I also tested 8.2310 and it's also clean.

That said, it's on a very powerful machine, so time exhaustion is not to be expected.

**Comment by rgerhards** [comment]
> That said, it's on a very powerful machine, so time exhaustion is not to be expected.

nevertheless, it's shown in the posted logs

Can you re-run the tests for a try?

**Comment by glaubitz** [comment]
Well, the PowerPC test failure that I reported is on a very beefy POWER8 machine, so I'm not sure how fast the machine needs to be.

I can blacklist the `rsyslog` package on the slower SPARCs though and make sure it's build on the faster machines only.

**Comment by glaubitz** [comment]
The problem is that I cannot really run the tests when checking out the sources from git.

Running `make check` doesn't run any tests.

**Comment by rgerhards** [comment]
you need to add `--enable-testbench` to the configure options.

**Comment by rgerhards** [comment]
forgot also `--enable-imdiag --enable-omstdout` if those are not already enabled in your configure command.

**Comment by glaubitz** [comment]
OK, I can confirm now that f4cfd557dff4ecf35bd80678e75986ec2bf15b10 works fine when building from git.

Thus, it might be an issue with the Debian package or the automated build environment. Closing this for now.
