### ISSUE TITLE
Empty /var/log/maillog - Postfix Logs Not Being Recorded by rsyslog

### ISSUE THREAD

**Issue by vishnusghub** [rsyslog/rsyslog#5281]
### Expected behavior
rsyslog should log all the mail related messages in maillog
### Actual behavior
maillog is empty 
### Steps to reproduce the behavior
1. In rhel8, try to send a mail
2. we can able to receive the mail but the issue is maillog always empty
3. Also we can able to view the log messages through "journalctl -u postfix"

### Environment
rsyslog version : 
<img width="439" alt="image" src="https://github.com/rsyslog/rsyslog/assets/152257185/f33ac3b2-9304-45e3-8109-dc8e19eeeb7b">

Platform:
<img width="596" alt="image" src="https://github.com/rsyslog/rsyslog/assets/152257185/afdc92d5-f689-4ef7-be96-e150f8bbc1ad">

- In Centos7, able to log the messages in maillog, the file permissions and config are same in both centos7 and rhel8. 

- In rhel8, other logs like kernal, cron etc., are able to log the messages in /var/log but the maillog alone is empty.

- In centos7, when commented the "mail.*        -/var/log/maillog" in /etc/rsyslog.config we can able to see the logging stopped. But the same line present in rhel8, don't know why it's not working in rhel8.

**Comment by rgerhards** [comment]
Maybe there is a problem with parsing the priority. In order to see how the message is parsed add to **the top** of your rsyslog.conf:
```
*.* /var/log/msgfields.log;RSYSLOG_DebugFormat
```
This will create a multi-line entry for each message. Review the file and post an entry in question.

**Comment by vishnusghub** [comment]
I didn't find any entry regarding to the postfix, so I have posted the above, is that fine?

**Comment by rgerhards** [comment]
> I didn't find any entry regarding to the postfix, so I have posted the above, is that fine?

well, kind of. It tells us that postfix either does not log to syslog, journal does not forward the messages or you are not running imjournal.

This was a catch-all rule, so when you do not see messages of some kind, rsyslog also does not see them.

**Comment by vishnusghub** [comment]
<img width="619" alt="image" src="https://github.com/rsyslog/rsyslog/assets/152257185/3c5ca177-7227-46c1-9219-8e01da8a72cd">

**Comment by rgerhards** [comment]
@Cropi do you have an idea what is going on here?

**Comment by vishnusghub** [comment]
Thanks, now the maillog is getting updated.
