### ISSUE TITLE
rsyslogd segfaults on mariadb error

### ISSUE THREAD

**Issue by bahbarnett** [rsyslog/rsyslog#5288]
### Expected behavior
rsyslogd doesn't bork.

### Actual behavior
It borks

### Steps to reproduce the behavior
Reproducible, create a stored procedure with somethng akin to: 
 
```
RESIGNAL set CLASS_ORIGIN= '', SUBCLASS_ORIGIN= '', MESSAGE_TEXT= 'hi', MYSQL_ERRNO= '2001', CONSTRAINT_CATALOG= '', CONSTRAINT_SCHEMA= '', CONSTRAINT_NAME= '', CATALOG_NAME= '', SCHEMA_NAME= '', TABLE_NAME= '', COLUMN_NAME='', CURSOR_NAME= '';
```

It looks like when this code block is hit:

```
 if(mysql_query(pWrkrData->hmysql, (char*)psz)) {
        const int mysql_err = mysql_errno(pWrkrData->hmysql);
        /* We assume server error codes are non-recoverable, mainly data errors.
         * This also means we need to differentiate between client and server error
         * codes. Unfortunately, the API does not provide a specified function for
         * this. Howerver, error codes 2000..2999 are currently client error codes.
         * So we use this as guideline.
         */
        if(mysql_err < 2000 || mysql_err > 2999) {
            reportDBError(pWrkrData, 0);
            LogError(0, RS_RET_DATAFAIL, "The error statement was: %s", psz);
            ABORT_FINALIZE(RS_RET_DATAFAIL);
        }
```
The segfault happens:

```
Dec  5 03:08:16 dev1 kernel: [492815.095879] rs:aliens queue[51737]: segfault at 480 ip 00007fcb50d48c7d sp 00007fcb50d248d0 error 4 in libmariadb.so.3[7fcb50d3d000+27000] likely on CPU 1 (core 0, socket 1)
Dec  5 03:08:16 dev1 kernel: [492815.098848] Code: 00 e9 c7 fd ff ff 0f 1f 80 00 00 00 00 55 48 89 e5 41 57 41 56 45 31 f6 41 55 49 89 f5 41 54 49 89 d4 53 48 89 fb 48 83 ec 08 <48> 8b 87 80 04 00 00 48 85 c0 74 08 44 0f b6 b0 a8 00 00 00 49 83
Dec  5 03:08:16 dev1 systemd[1]: rsyslog.service: Main process exited, code=killed, status=11/SEGV
Dec  5 03:08:16 dev1 systemd[1]: rsyslog.service: Failed with result 'signal'.
```

### Environment
```
Dec  5 03:17:08 dev1 rsyslogd: [origin software="rsyslogd" swVersion="8.2302.0" x-pid="52367" x-info="https://www.rsyslog.com"] start
Debian Bookworm 12.2
```

**Comment by bahbarnett** [comment]
Note: this is related to issue #5285, this was an attempt to choose a different code path in rsyslogd, when an sql error occurred, to prevent relentless retry/log spamming.

However, this seems like an extremely severe issue on its own.

**Comment by rgerhards** [comment]
Please create a debug log. Instructions: https://www.rsyslog.com/doc/v8-stable/troubleshooting/howtodebug.html

**Be sure that the problem in question occurs at least once during the debug run**. Once this is done, please post the debug log (e.g. via pastebin or github). After that, we can review the contents and check how exactly rsyslog processing worked.

**Comment by bahbarnett** [comment]
[rsyslog.debug.txt.gz](https://github.com/rsyslog/rsyslog/files/13557537/rsyslog.debug.txt.gz)

I do see the SEGV in the debug log, so I seem to have captured it.

FYI, I am triggering this via:

logger -p local6.notice -t booger '{"route":"","server":"testweb","message":"hi","data":"aliens"}'

Which then hits the local rsyslog.  This then is sent to the mysql syslog, which queues the message, and sends it to mysql.  This has worked perfectly fine for years, but we recently noticed that a table definition on one DEV VM, had a missing default for a timestamp column.

This meant, that for the first time, we hit an uncaught error that trickled back up to rsyslogd.

This kicked off the issue in #5285.  Which during my debugging, and my attempts to better catch errors in mysql, kicked off this bug.

Thanks

**Comment by bahbarnett** [comment]
# objdump --syms /usr/sbin/rsyslogd

/usr/sbin/rsyslogd:     file format elf64-x86-64

SYMBOL TABLE:
no symbols

Would it help to run with gdb as is?  I could try to recompile a dpkg with debug symbols on...

**Comment by rgerhards** [comment]
I checked the debug log, unfortunately there is not much in it that helps. Just to confirm:

* the segfault happened directly after startup
* ommysql did not store a single message into the database

Is this right?

The symbols are in a separate package, something along the lines of rsyslog-debugsym.

**Comment by rgerhards** [comment]
In any case, it will be pretty hard to tackle this without a stacktrace, so if you need to and could recompile, that would be great.

Trying to reproduce it myself for such more "esoteric" things is something I have almost given up. Almost always, it does not work out because one needs to have some specific system settings which nobody knows before the debug is discovered. That's at least my experience from the past 20+ yrs.

**Comment by bahbarnett** [comment]
I'm recompiling now.  FYI, outside of this, I can provide a series of examples to reproduce.  I could also setup a VM for you to use (a linode, or something), and SSH into, with a valid test case.

(Will reply once recompile is done).  NOTE: my gdb-fu is rusty.  How should I instantiate gdb/rsyslog?  Suggestions?

**Comment by rgerhards** [comment]
A VM to ssh into would definitely help, but let's first look at the stack trace.

You can run gdb after-the-fact. Look here at the end of this page:

https://www.rsyslog.com/doc/v8-stable/troubleshooting/troubleshoot.html

If you recompile, you could also use CLANG with address sanitizer. That has a very good track record of pinpointing issues or at least providing some starting points.

**Comment by bahbarnett** [comment]
[backtrace.txt.gz](https://github.com/rsyslog/rsyslog/files/13558183/backtrace.txt.gz)

OK. Here's the backtrace as per the doc.
Not sure how to use CLANG, let me know if you still need it.

**Comment by bahbarnett** [comment]
Some additional info.  I have to kick the test two times, for it to segv.  The first just does.. nothing.  No logging back to the syslog file (eg, with warnings/etc of failed mysql).  The second time kicks the segv.

**Comment by rgerhards** [comment]
Interesting... It looks like mariadb does a rollback, for whatever reason. I still need to look in more depth, but wanted to let you know about that fact.

**Comment by rgerhards** [comment]
I checked the trace against the debug log from earlier today and also looked at the code.  The debug log tells us it is in action.c, line 1294. However, I do not find any matching ommysql messages, which should happen as the very next thing. Can you double-check if the debug actually is complete and from  a failed attempt?

**Comment by rgerhards** [comment]
FYI: This is the last message from ommysql I see in the debug log:

```
6269.324085420:main thread    : ../action.c: Action ommysql[0x5578d7bc2050]: queue 0x5578d7bc28d0 started
```

That's just from the startup. I never see even the action being called.

**Comment by bahbarnett** [comment]
I can see it "doing things", for example at line 1476.  One thing that I recall happening, is it SEGV twice.  I believe it loaded the same "bad" insert data from the rsyslog disk queue upon restart.  

On line 72 it sees the config file, and on line 1501 I can see a reference to 'call router', which is the main ingress mariadb stored procedure for rsyslog.

I've looked though, and I agree I don't see anything specific, but at the same time, this is the first debug log for rsyslog I've looked at.  The mysql queue is called 'aliens', there are other queues, one called 'aliens1'.  

# grep aliens rsyslog.debug.txt  | grep action | grep -v aliens1
6269.304452441:main thread    : aliens queue: queue.c: queue.timeoutactioncompletion: 1000
6269.323603833:main thread    : wti.c: aliens queue:Reg/w0: finalizing construction of worker instance data (for 10 actions)
6269.323666254:main thread    : wti.c: aliens queue:Reg/w1: finalizing construction of worker instance data (for 10 actions)
6269.323744740:main thread    : wti.c: aliens queue:DAwpool/w0: finalizing construction of worker instance data (for 10 actions)
6269.323925017:main thread    : wti.c: aliens queue[DA]:Reg/w0: finalizing construction of worker instance data (for 10 actions)
6269.323968259:main thread    : wti.c: aliens queue[DA]:Reg/w1: finalizing construction of worker instance data (for 10 actions)

Would the SEGV have axed some data from a thread making it into the debug log?

Should I increase verbosity?  Do I need to ensure debug is in the action itself?  I can re-do the test easily.  This is, fortunately, and easy to reproduce thing.

**Comment by rgerhards** [comment]
according to the stack trace, ommysql should be running this procedure at the time of the segfault:

https://github.com/rsyslog/rsyslog/blob/master/plugins/ommysql/ommysql.c#L329

But none of these messages show up. On the other hand, we see "rollback" in the stack trace, which implies that ommysql indeed was in that code (otherwise nothing would have been submitted to mariadb). So, debug log and stack trace do not match.

**Comment by rgerhards** [comment]
> I can see it "doing things", for example at line 1476. One thing that I recall happening, is it SEGV twice. I believe it loaded the same "bad" insert data from the rsyslog disk queue upon restart.
> 
> On line 72 it sees the config file, and on line 1501 I can see a reference to 'call router', which is the main ingress mariadb stored procedure for rsyslog.

That's all early startup. For example "call router" is a constant inside a template. Nothing really inside ommysql. There is no call visible in ommysql. I guess if you look at my provided link, you'll see what I mean.

**Comment by bahbarnett** [comment]
[rsyslog.debug2.txt.gz](https://github.com/rsyslog/rsyslog/files/13564763/rsyslog.debug2.txt.gz)

I added debug config, restarted, caused a segfault, then did a mv of the debug log before restarting.
This attached debug log has been running since then.  So it takes off where the last one ends.

My C is quite rusty.  I'm not familiar with START END and not sure whether this code is being triggered in all cases or not.  EG, is this code block being 'called', or just executed in order when this plugin is hit?

I don't see DBGPRINTF("ommysql: commitTransaction\n") happening, and in fact:

# grep DBGPRINTF ommysql.c | awk '{print $2" "$3;}'
suspending due
commitTransaction\n");
server error:
server error:
transaction committed\n");

None of these things seems to appear in the debug2 log either.  I can add additional debug entries if you want?

**Comment by bahbarnett** [comment]
Dec  6 01:20:37 dev1 systemd-coredump[61508]: Process 54093 (rsyslogd) of user 0 dumped core.#012#012Module libsystemd.so.0 from deb systemd-252.17-1~deb12u1.amd64#012Stack trace of thread 61506:#012#0  0x00007fabbe417c7d mysql_real_query (libmariadb.so.3 + 0x22c7d)#012#1  0x00007fabbe4190a5 mysql_rollback (libmariadb.so.3 + 0x240a5)#012#2  0x00007fabbf02b789 n/a (ommysql.so + 0x3789)#012#3  0x00005624352a268f actionCallCommitTransaction (rsyslogd + 0x6b68f)#012#4  0x00005624352a2c5c actionCommit (rsyslogd + 0x6bc5c)#012#5  0x00005624352a432b processBatchMain (rsyslogd + 0x6d32b)#012#6  0x0000562435296fc2 ConsumerReg (rsyslogd + 0x5ffc2)#012#7  0x0000562435293b71 wtiWorker (rsyslogd + 0x5cb71)#012#8  0x000056243529236a wtpWorker (rsyslogd + 0x5b36a)#012#9  0x00007fabbf362044 start_thread (libc.so.6 + 0x89044)#012#10 0x00007fabbf3e261c __clone3 (libc.so.6 + 0x10961c)#012#012Stack trace of thread 54095:#012#0  0x00007fabbf3d10dc __GI___libc_read (libc.so.6 + 0xf80dc)#012#1  0x00007fabbf03b8a2 read (imklog.so + 0x38a2)#012#2  0x00007fabbf03bbe9 klogLogKMsg (imklog.so + 0x3be9)#012#3  0x00007fabbf03ac54 runInput (imklog.so + 0x2c54)#012#4  0x00005624352a59d1 thrdStarter (rsyslogd + 0x6e9d1)#012#5  0x00007fabbf362044 start_thread (libc.so.6 + 0x89044)#012#6  0x00007fabbf3e261c __clone3 (libc.so.6 + 0x10961c)#012#012Stack trace of thread 54094:#012#0  0x00007fabbf3d505f __GI___poll (libc.so.6 + 0xfc05f)#012#1  0x00007fabbf0438b0 poll (imuxsock.so + 0x48b0)#012#2  0x00005624352a59d1 thrdStarter (rsyslogd + 0x6e9d1)#012#3  0x00007fabbf362044 start_thread (libc.so.6 + 0x89044)#012#4  0x00007fabbf3e261c __clone3 (libc.so.6 + 0x10961c)#012#012Stack trace of thread 54101:#012#0  0x00007fabbf35eda6 __futex_abstimed_wait_common64 (libc.so.6 + 0x85da6)#012#1  0x00007fabbf361468 __pthread_cond_wait_common (libc.so.6 + 0x88468)#012#2  0x00007fabbea93c3c wrkr (lmtcpsrv.so + 0x4c3c)#012#3  0x00007fabbf362044 start_thread (libc.so.6 + 0x89044)#012#4  0x00007fabbf3e261c __clone3 (libc.so.6 + 0x10961c)#012#012Stack trace of thread 54099:#012#0  0x00007fabbf35eda6 __futex_abstimed_wait_common64 (libc.so.6 + 0x85da6)#012#1  0x00007fabbf361468 __pthread_cond_wait_common (libc.so.6 + 0x88468)#012#2  0x00007fabbea93c3c wrkr (lmtcpsrv.so + 0x4c3c)#012#3  0x00007fabbf362044 start_thread (libc.so.6 + 0x89044)#012#4  0x00007fabbf3e261c __clone3 (libc.so.6 + 0x10961c)#012#012Stack trace of thread 54103:#012#0  0x00007fabbf35eda6 __futex_abstimed_wait_common64 (libc.so.6 + 0x85da6)#012#1  0x00007fabbf361468 __pthread_cond_wait_common (libc.so.6 + 0x88468)#012#2  0x0000562435293bd0 doIdleProcessing (rsyslogd + 0x5cbd0)#012#3  0x000056243529236a wtpWorker (rsyslogd + 0x5b36a)#012#4  0x00007fabbf362044 start_thread (libc.so.6 + 0x89044)#012#5  0x00007fabbf3e261c __clone3 (libc.so.6 + 0x10961c)#012#012Stack trace of thread 54100:#012#0  0x00007fabbf35eda6 __futex_abstimed_wait_common64 (libc.so.6 + 0x85da6)#012#1  0x00007fabbf361468 __pthread_cond_wait_common (libc.so.6 + 0x88468)#012#2  0x00007fabbea93c3c wrkr (lmtcpsrv.so + 0x4c3c)#012#3  0x00007fabbf362044 start_thread (libc.so.6 + 0x89044)#012#4  0x00007fabbf3e261c __clone3 (libc.so.6 + 0x10961c)#012#012Stack trace of thread 54102:#012#0  0x00007fabbf35eda6 __futex_abstimed_wait_common64 (libc.so.6 + 0x85da6)#012#1  0x00007fabbf361468 __pthread_cond_wait_common (libc.so.6 + 0x88468)#012#2  0x00007fabbea93c3c wrkr (lmtcpsrv.so + 0x4c3c)#012#3  0x00007fabbf362044 start_thread (libc.so.6 + 0x89044)#012#4  0x00007fabbf3e261c __clone3 (libc.so.6 + 0x10961c)#012#012Stack trace of thread 54096:#012#0  0x00007fabbf3d117f __GI___libc_write (libc.so.6 + 0xf817f)#012#1  0x00005624352855e8 dbgprint (rsyslogd + 0x4e5e8)#012#2  0x00005624352859d5 r_dbgprintf (rsyslogd + 0x4e9d5)#012#3  0x000056243526c88b cnfstmtPrintOnly (rsyslogd + 0x3588b)#012#4  0x000056243529b82f scriptExec (rsyslogd + 0x6482f)#012#5  0x000056243529c195 processBatch (rsyslogd + 0x65195)#012#6  0x000056243524ec5c msgConsumer (rsyslogd + 0x17c5c)#012#7  0x0000562435296fc2 ConsumerReg (rsyslogd + 0x5ffc2)#012#8  0x0000562435293b71 wtiWorker (rsyslogd + 0x5cb71)#012#9  0x000056243529236a wtpWorker (rsyslogd + 0x5b36a)#012#10 0x00007fabbf362044 start_thread (libc.so.6 + 0x89044)#012#11 0x00007fabbf3e261c __clone3 (libc.so.6 + 0x10961c)#012#012Stack trace of thread 54093:#012#0  0x00007fabbf3d7941 pselect64_syscall (libc.so.6 + 0xfe941)#012#1  0x000056243525131d wait_timeout (rsyslogd + 0x1a31d)#012#2  0x000056243524e0f4 main (rsyslogd + 0x170f4)#012#3  0x00007fabbf3001ca __libc_start_call_main (libc.so.6 + 0x271ca)#012#4  0x00007fabbf300285 __libc_start_main_impl (libc.so.6 + 0x27285)#012#5  0x000056243524e471 _start (rsyslogd + 0x17471)#012#012Stack trace of thread 54097:#012#0  0x00007fabbf3e1c66 epoll_wait (libc.so.6 + 0x108c66)#012#1  0x00007fabbf01216f n/a (librelp.so.0 + 0x516f)#012#2  0x00007fabbf012a6c relpEngineRun (librelp.so.0 + 0x5a6c)#012#3  0x00007fabbf032a0e n/a (imrelp.so + 0x3a0e)#012#4  0x00005624352a59d1 thrdStarter (rsyslogd + 0x6e9d1)#012#5  0x00007fabbf362044 start_thread (libc.so.6 + 0x89044)#012#6  0x00007fabbf3e261c __clone3 (libc.so.6 + 0x10961c)#012#012Stack trace of thread 54098:#012#0  0x00007fabbf3e1c66 epoll_wait (libc.so.6 + 0x108c66)#012#1  0x00007fabbe3f0516 Wait (lmnsd_ptcp.so + 0x4516)#012#2  0x00007fabbea94760 DoRun (lmtcpsrv.so + 0x5760)#012#3  0x00007fabbea949c9 Run (lmtcpsrv.so + 0x59c9)#012#4  0x00007fabbea9cea1 runInput (imtcp.so + 0x3ea1)#012#5  0x00005624352a59d1 thrdStarter (rsyslogd + 0x6e9d1)#012#6  0x00007fabbf362044 start_thread (libc.so.6 + 0x89044)#012#7  0x00007fabbf3e261c __clone3 (libc.so.6 + 0x10961c)#012ELF object binary architecture: AMD x86-64

I just noticed that systemd, with its weird core dump capture thing, is also dumping into its journal, and then into rsyslog (upon restart via socket), some data.  I've pasted it above, just in case it is helpful in any way.

NOTE: if there are issues with this, again, I am more than happy to setup an external VM, quickly create a test case, and provide any additional stuff you need to help.  I think we've been gifted here, with an easily reproducible issue.

**Comment by rgerhards** [comment]
> is this code block being 'called', or just executed in order when this plugin is hit?

That's the main entry point of the plugin. It is called, when messages need to be written to mariadb. If it is not called, nothing is written to mariadb.

**Comment by rgerhards** [comment]
could you post the stacktrace with line breaks. It's actually unreadable as-is.

To post a preformatted text block, use three consecutive backticks (`) on a separate line before and after the preformatted text (I have changed this in the initial posting, but the one in question has no line breaks at all).

**Comment by rgerhards** [comment]
Thx for the readable stack trace,

But I do still not understand where ommysql is called. The debug log has no trace of that... Is that a version you compiled yourself or is it distro compiled? I ask because the distro may have patched out some debug messages. I don't think so, but as I said, there really is no match between stack trace and debug log.

Can you create a debug log on an instance that is not experiencing the issue?

**Comment by bahbarnett** [comment]
ARG!

Sorry.  I re-compiled the main sha-bang, and didn't click that the individual plugins were separately packaged.  I am very sorry.  So debugging symbols were not on for the plugin.

```
# dpkg -S ommysql
rsyslog-mysql: /usr/lib/x86_64-linux-gnu/rsyslog/ommysql.so
```
However:

```
# strings /usr/lib/x86_64-linux-gnu/rsyslog/ommysql.so | grep -i transaction
beginTransaction
commitTransaction
ommysql: commitTransaction
START TRANSACTION
ommysql: server error: transaction could not be rolled back
ommysql: server error: transaction not committed
ommysql: transaction committed
commitTransaction
endTransaction
beginTransaction
beginTransaction
commitTransaction
```

OK.  New debug and coredump:

```
# coredumpctl info 65824
           PID: 65824 (rsyslogd)
           UID: 0 (root)
           GID: 0 (root)
        Signal: 11 (SEGV)
     Timestamp: Wed 2023-12-06 08:33:39 EST (1min 53s ago)
  Command Line: /usr/sbin/rsyslogd -n -iNONE
    Executable: /usr/sbin/rsyslogd
 Control Group: /system.slice/rsyslog.service
          Unit: rsyslog.service
         Slice: system.slice
       Boot ID: a2e265c7322a46bda40dceeb7ebc56e5
    Machine ID: 7a7b06042e0b4ca58ddba47d277c049f
      Hostname: dev1.dev.bluink.ca
       Storage: /var/lib/systemd/coredump/core.rsyslogd.0.a2e265c7322a46bda40dceeb7ebc56e5.65824.1701869619000000.zst (present)
  Size on Disk: 379.1K
       Message: Process 65824 (rsyslogd) of user 0 dumped core.

                Module libsystemd.so.0 from deb systemd-252.17-1~deb12u1.amd64
                Stack trace of thread 65850:
                #0  0x00007f3a5f4f6c7d mysql_real_query (libmariadb.so.3 + 0x22c7d)
                #1  0x00007f3a5f4f80a5 mysql_rollback (libmariadb.so.3 + 0x240a5)
                #2  0x00007f3a600f2789 commitTransaction (ommysql.so + 0x3789)
                #3  0x000055dca299368f actionCallCommitTransaction (rsyslogd + 0x6b68f)
                #4  0x000055dca2993c5c actionCommit (rsyslogd + 0x6bc5c)
                #5  0x000055dca299532b processBatchMain (rsyslogd + 0x6d32b)
                #6  0x000055dca2987fc2 ConsumerReg (rsyslogd + 0x5ffc2)
                #7  0x000055dca2984b71 wtiWorker (rsyslogd + 0x5cb71)
                #8  0x000055dca298336a wtpWorker (rsyslogd + 0x5b36a)
                #9  0x00007f3a60429044 start_thread (libc.so.6 + 0x89044)
                #10 0x00007f3a604a961c __clone3 (libc.so.6 + 0x10961c)

                Stack trace of thread 65825:
                #0  0x00007f3a6049c05f __GI___poll (libc.so.6 + 0xfc05f)
                #1  0x00007f3a6010a8b0 poll (imuxsock.so + 0x48b0)
                #2  0x000055dca29969d1 thrdStarter (rsyslogd + 0x6e9d1)
                #3  0x00007f3a60429044 start_thread (libc.so.6 + 0x89044)
                #4  0x00007f3a604a961c __clone3 (libc.so.6 + 0x10961c)

                Stack trace of thread 65831:
                #0  0x00007f3a60425da6 __futex_abstimed_wait_common64 (libc.so.6 + 0x85da6)
                #1  0x00007f3a60428468 __pthread_cond_wait_common (libc.so.6 + 0x88468)
                #2  0x00007f3a5f4c8c3c wrkr (lmtcpsrv.so + 0x4c3c)
                #3  0x00007f3a60429044 start_thread (libc.so.6 + 0x89044)
                #4  0x00007f3a604a961c __clone3 (libc.so.6 + 0x10961c)

                Stack trace of thread 65833:
                #0  0x00007f3a60425da6 __futex_abstimed_wait_common64 (libc.so.6 + 0x85da6)
                #1  0x00007f3a60428468 __pthread_cond_wait_common (libc.so.6 + 0x88468)
                #2  0x00007f3a5f4c8c3c wrkr (lmtcpsrv.so + 0x4c3c)
                #3  0x00007f3a60429044 start_thread (libc.so.6 + 0x89044)
                #4  0x00007f3a604a961c __clone3 (libc.so.6 + 0x10961c)

                Stack trace of thread 65834:
                #0  0x00007f3a60425da6 __futex_abstimed_wait_common64 (libc.so.6 + 0x85da6)
                #1  0x00007f3a60428468 __pthread_cond_wait_common (libc.so.6 + 0x88468)
                #2  0x000055dca2984bd0 doIdleProcessing (rsyslogd + 0x5cbd0)
                #3  0x000055dca298336a wtpWorker (rsyslogd + 0x5b36a)
                #4  0x00007f3a60429044 start_thread (libc.so.6 + 0x89044)
                #5  0x00007f3a604a961c __clone3 (libc.so.6 + 0x10961c)

                Stack trace of thread 65826:
                #0  0x00007f3a604980dc __GI___libc_read (libc.so.6 + 0xf80dc)
                #1  0x00007f3a601028a2 read (imklog.so + 0x38a2)
                #2  0x00007f3a60102be9 klogLogKMsg (imklog.so + 0x3be9)
                #3  0x00007f3a60101c54 runInput (imklog.so + 0x2c54)
                #4  0x000055dca29969d1 thrdStarter (rsyslogd + 0x6e9d1)
                #5  0x00007f3a60429044 start_thread (libc.so.6 + 0x89044)
                #6  0x00007f3a604a961c __clone3 (libc.so.6 + 0x10961c)

                Stack trace of thread 65824:
                #0  0x00007f3a6049e941 pselect64_syscall (libc.so.6 + 0xfe941)
                #1  0x000055dca294231d wait_timeout (rsyslogd + 0x1a31d)
                #2  0x000055dca293f0f4 main (rsyslogd + 0x170f4)
                #3  0x00007f3a603c71ca __libc_start_call_main (libc.so.6 + 0x271ca)
                #4  0x00007f3a603c7285 __libc_start_main_impl (libc.so.6 + 0x27285)
                #5  0x000055dca293f471 _start (rsyslogd + 0x17471)

                Stack trace of thread 65827:
                #0  0x00007f3a604a8c66 epoll_wait (libc.so.6 + 0x108c66)
                #1  0x00007f3a600d916f n/a (librelp.so.0 + 0x516f)
                #2  0x00007f3a600d9a6c relpEngineRun (librelp.so.0 + 0x5a6c)
                #3  0x00007f3a600f9a0e n/a (imrelp.so + 0x3a0e)
                #4  0x000055dca29969d1 thrdStarter (rsyslogd + 0x6e9d1)
                #5  0x00007f3a60429044 start_thread (libc.so.6 + 0x89044)
                #6  0x00007f3a604a961c __clone3 (libc.so.6 + 0x10961c)

                Stack trace of thread 65829:
                #0  0x00007f3a60425fbb futex_wait (libc.so.6 + 0x85fbb)
                #1  0x00007f3a6042c2d2 lll_mutex_lock_optimized (libc.so.6 + 0x8c2d2)
                #2  0x000055dca298958b qqueueEnqMsg (rsyslogd + 0x6158b)
                #3  0x000055dca2994fcd doSubmitToActionQ (rsyslogd + 0x6cfcd)
                #4  0x000055dca298c4cf execAct (rsyslogd + 0x644cf)
                #5  0x000055dca298c51d execPROPFILT (rsyslogd + 0x6451d)
                #6  0x000055dca298d195 processBatch (rsyslogd + 0x65195)
                #7  0x000055dca293fc5c msgConsumer (rsyslogd + 0x17c5c)
                #8  0x000055dca2987fc2 ConsumerReg (rsyslogd + 0x5ffc2)
                #9  0x000055dca2984b71 wtiWorker (rsyslogd + 0x5cb71)
                #10 0x000055dca298336a wtpWorker (rsyslogd + 0x5b36a)
                #11 0x00007f3a60429044 start_thread (libc.so.6 + 0x89044)
                #12 0x00007f3a604a961c __clone3 (libc.so.6 + 0x10961c)

                Stack trace of thread 65828:
                #0  0x00007f3a604a8c66 epoll_wait (libc.so.6 + 0x108c66)
                #1  0x00007f3a5f4b5516 Wait (lmnsd_ptcp.so + 0x4516)
                #2  0x00007f3a5f4c9760 DoRun (lmtcpsrv.so + 0x5760)
                #3  0x00007f3a5f4c99c9 Run (lmtcpsrv.so + 0x59c9)
                #4  0x00007f3a5f52cea1 runInput (imtcp.so + 0x3ea1)
                #5  0x000055dca29969d1 thrdStarter (rsyslogd + 0x6e9d1)
                #6  0x00007f3a60429044 start_thread (libc.so.6 + 0x89044)
                #7  0x00007f3a604a961c __clone3 (libc.so.6 + 0x10961c)

                Stack trace of thread 65830:
                #0  0x00007f3a60425da6 __futex_abstimed_wait_common64 (libc.so.6 + 0x85da6)
                #1  0x00007f3a60428468 __pthread_cond_wait_common (libc.so.6 + 0x88468)
                #2  0x00007f3a5f4c8c3c wrkr (lmtcpsrv.so + 0x4c3c)
                #3  0x00007f3a60429044 start_thread (libc.so.6 + 0x89044)
                #4  0x00007f3a604a961c __clone3 (libc.so.6 + 0x10961c)

                Stack trace of thread 65832:
                #0  0x00007f3a60425da6 __futex_abstimed_wait_common64 (libc.so.6 + 0x85da6)
                #1  0x00007f3a60428468 __pthread_cond_wait_common (libc.so.6 + 0x88468)
                #2  0x00007f3a5f4c8c3c wrkr (lmtcpsrv.so + 0x4c3c)
                #3  0x00007f3a60429044 start_thread (libc.so.6 + 0x89044)
                #4  0x00007f3a604a961c __clone3 (libc.so.6 + 0x10961c)
                ELF object binary architecture: AMD x86-64
```

[core.rsyslogd.0.a2e265c7322a46bda40dceeb7ebc56e5.65824.1701869619000000.gz](https://github.com/rsyslog/rsyslog/files/13583538/core.rsyslogd.0.a2e265c7322a46bda40dceeb7ebc56e5.65824.1701869619000000.gz)
[rsyslog.debug.2023-12-06.txt.gz](https://github.com/rsyslog/rsyslog/files/13583539/rsyslog.debug.2023-12-06.txt.gz)

Once again, sorry for the snafu.

**Comment by bahbarnett** [comment]
```
$DebugFile /var/log/rsyslog.debug
$DebugLevel 2
```
As per the debug page you linked me to, I set the following in my rsyslog.conf file.

Is this correct?  Do we need to increase the debug level, or add addition options?

**Comment by bahbarnett** [comment]
I still don't see anything in the debug log, but at the same time, rsyslogd is segfaulting here.  So on a lark, I changed the stored procedure to work as above, so instead of a segfault, we'd get a borked stored procedure, and a disconnect (see my comment above with select now() as now; )

This debug log does have the stuff you're looking for in it, but of course, it didn't segfault.  I can only conclude that the crash happens so fast, it cannot write before dying.

Attached is the output of "grep ommysql" on the file..

[moredebug.txt](https://github.com/rsyslog/rsyslog/files/13587154/moredebug.txt)

**Comment by bahbarnett** [comment]
I can only provide what I have.  I am willing to set up a test infra, if it helps.  For now, I have a workaround, which at least resolves these two bugs (lack of throttling, segfault) for our infra.

If you can think of anything else that will help, please let me know.

**Comment by rgerhards** [comment]
> I can only provide what I have. I am willing to set up a test infra, if it helps.

If you can grant me access to a test vm (best with development evn), I would have a look there. private details: rgerhards@adiscon.com

**Comment by bahbarnett** [comment]
Have replied to email, and test env is setup.

**Comment by rgerhards** [comment]
will hopefully be able to take care today, depends on a tentatively scheduled meeting

**Comment by bahbarnett** [comment]
Once you reply to my email, we can finalize login/etc details.  I'll be around most days, -4h from not to +6h from now, with varying lag to respond.

**Comment by rgerhards** [comment]
Thx again for the VM. I think I nailed it. It happens due to the DB error, which in turn triggers a situation where the DB is closed but not reopened, but rsyslog still later tries to rollback the transaction, now with an invalid (closed) handle. Patch is upcoming. Can you apply the patch? 

Side-Note: the VM is currently in my testing setup, so it's not the same config as your other systems.

**Comment by rgerhards** [comment]
Patch #5292 is now available.

Another side-note: I still have no idea why the debug log did not show the ommysql messages. @bahbarnett if that's ok with you, please keep the VM for a bit longer as I would like to see if I can reproduce that as well. So far, I focussed on the bug itself.

**Comment by bahbarnett** [comment]
Seems like a good fix here on the bookworm version.  It also properly backs off, respecting action.resumeInterval.

I did check, and issue #5285 still exists, which is an error message triggering a different part of the code path.  If you wish, I can easily modify the stored procedure to act that way, once you're happy about debug log issues.

**Comment by rgerhards** [comment]
> I did check, and issue #5285 still exists, which is an error message triggering a different part of the code path. If you wish, I can easily modify the stored procedure to act that way, once you're happy about debug log issues.

yes, pls do. Please note that I am currently pretty busy and as such sluggish. But I'll definitely check within the next couple of days, maybe half an hour here and half an hour there ;-)

**Comment by bahbarnett** [comment]
Right now, it's sort of borked for my test case, as you've (naturally!) modified things for your work.  I don't want to step on your toes, so are you OK with me restoring the configs, and changing things?

I can wait until you've looked at the debug issue before I setup the test case, if that's easier...

**Comment by rgerhards** [comment]
> Just curious as per my last post.

sry, very busy the past days. Yes, please do as you need. If you have a pre-image, just restore.
