### ISSUE TITLE
[CONFIGUATION] How to configure rsyslog to use the imfile module?

### ISSUE THREAD

**Issue by xzizka** [rsyslog/rsyslog#5298]
### Expected behavior

To be able to work with imfile module without errors mentioning missing module or already loaded module.

### Actual behavior

I have Red Hat 9.2 with rsyslog v8.2102.0-113.el9_2.1.

I use default */etc/rsyslog.conf* and a custom configuration called *vums.conf* located in `/etc/rsyslog.d/`.
```
module(load="imfile")
input(type="imfile"
      File="/opt/wildfly/standalone/log/server.log"
      Tag="wildly")
```
When I restart the rsyslog I see the following error when I run systemctl status rsyslog:
```
[root@konor2 rsyslog.d]# systemctl status rsyslog
● rsyslog.service - System Logging Service
     Loaded: loaded (/usr/lib/systemd/system/rsyslog.service; enabled; preset: enabled)
     Active: active (running) since Wed 2023-12-20 07:32:55 CET; 1s ago
       Docs: man:rsyslogd(8)
             https://www.rsyslog.com/doc/
   Main PID: 574855 (rsyslogd)
      Tasks: 4 (limit: 36037)
     Memory: 1.4M
        CPU: 23ms
     CGroup: /system.slice/rsyslog.service
             └─574855 /usr/sbin/rsyslogd -n

Dec 20 07:32:55 konor2 systemd[1]: Starting System Logging Service...
Dec 20 07:32:55 konor2 rsyslogd[574855]: module 'imfile' already in this config, cannot be added  [v8.2102.0-113.el9_2.1 try https://www.rsyslog.com/e/2221 ]
Dec 20 07:32:55 konor2 rsyslogd[574855]: [origin software="rsyslogd" swVersion="8.2102.0-113.el9_2.1" x-pid="574855" x-info="https://www.rsyslog.com"] start
Dec 20 07:32:55 konor2 systemd[1]: Started System Logging Service.
Dec 20 07:32:55 konor2 rsyslogd[574855]: imjournal: journal files changed, reloading...  [v8.2102.0-113.el9_2.1 try https://www.rsyslog.com/e/0 ]
```
The error tells me that "*module 'imfile' already in this config, cannot be added*". In case I commented the `module(load="imfile")` line I receive the following error:
```
[root@konor2 rsyslog.d]# systemctl status rsyslog
● rsyslog.service - System Logging Service
     Loaded: loaded (/usr/lib/systemd/system/rsyslog.service; enabled; preset: enabled)
     Active: active (running) since Wed 2023-12-20 07:34:54 CET; 1s ago
       Docs: man:rsyslogd(8)
             https://www.rsyslog.com/doc/
   Main PID: 576081 (rsyslogd)
      Tasks: 3 (limit: 36037)
     Memory: 5.1M
        CPU: 23ms
     CGroup: /system.slice/rsyslog.service
             └─576081 /usr/sbin/rsyslogd -n

Dec 20 07:34:54 konor2 systemd[1]: Starting System Logging Service...
Dec 20 07:34:54 konor2 rsyslogd[576081]: input module name 'imfile' is unknown [v8.2102.0-113.el9_2.1 try https://www.rsyslog.com/e/2209 ]
Dec 20 07:34:54 konor2 systemd[1]: Started System Logging Service.
Dec 20 07:34:54 konor2 rsyslogd[576081]: error during parsing file /etc/rsyslog.d/vums.conf, on or before line 13: parameter 'Tag' not known -- typo in config file? [v8.2102.0-113.el9_2.1 try https:>
Dec 20 07:34:54 konor2 rsyslogd[576081]: error during parsing file /etc/rsyslog.d/vums.conf, on or before line 13: parameter 'File' not known -- typo in config file? [v8.2102.0-113.el9_2.1 try https>
Dec 20 07:34:54 konor2 rsyslogd[576081]: input module name 'imfile' is unknown [v8.2102.0-113.el9_2.1 try https://www.rsyslog.com/e/2209 ]
Dec 20 07:34:54 konor2 rsyslogd[576081]: error during parsing file /etc/rsyslog.d/vums.conf, on or before line 13: parameter 'Tag' not known -- typo in config file? [v8.2102.0-113.el9_2.1 try https:>
Dec 20 07:34:54 konor2 rsyslogd[576081]: error during parsing file /etc/rsyslog.d/vums.conf, on or before line 13: parameter 'File' not known -- typo in config file? [v8.2102.0-113.el9_2.1 try https>
Dec 20 07:34:54 konor2 rsyslogd[576081]: [origin software="rsyslogd" swVersion="8.2102.0-113.el9_2.1" x-pid="576081" x-info="https://www.rsyslog.com"] start
Dec 20 07:34:54 konor2 rsyslogd[576081]: imjournal: journal files changed, reloading...  [v8.2102.0-113.el9_2.1 try https://www.rsyslog.com/e/0 ]
The error tells that "*input module name 'imfile' is unknown*".
```
I checked both files mentioned above and there is no duplicate load configuration for the module. I also performed stop, checked if the process was down and start of the daemon, but the result was the same.

How to configure rsyslog to be able to use the imfile module and the input definition without the errors above?

There are just 2 files with config:
- /etc/rsyslog.conf
- /etc/rsyslog.d/vums.conf
In `/etc/rsyslog.conf`, there is the following line for loading of the custom configurations.
```
include(file="/etc/rsyslog.d/*.conf" mode="optional")
```
The `module(load=imfile)` line is just in the `vums.conf` file.

### Steps to reproduce the behavior

Use the the default rsyslog.conf in Red Hat 9.2 and add *vums.conf* file to '/etc/rsyslog.d/' with the following content:
```
module(load="imfile")
input(type="imfile"
      File="/opt/wildfly/standalone/log/server.log"
      Tag="wildly")
```

### Environment
- rsyslog version: v8.2102.0-113.el9_2.1.
- platform: Red Hat 9.2
- for configuration questions/issues, include rsyslog.conf and included config files -> Please see the attached ZIP file for both config files mentioned in this issue.
[rsyslog.zip](https://github.com/rsyslog/rsyslog/files/13750025/rsyslog.zip)

**Comment by rgerhards** [comment]
> The `module(load=imfile)` line is just in the `vums.conf` file.

There is also legacy config directive

```
$modLoad imfile
```

In that config file. Did you add it? If not, that's the first load,

**Comment by xzizka** [comment]
Hello @rgerhards,

Yes. I commented that lines with the behaviour I described above.
![image](https://github.com/rsyslog/rsyslog/assets/9096952/977f53dd-fdf3-47bb-a74c-180b68b8f75f)
After restart of the service:
![image](https://github.com/rsyslog/rsyslog/assets/9096952/d1fd4915-f976-43a8-8094-c0964e45d5d6)

If I comment on the load module line...
![image](https://github.com/rsyslog/rsyslog/assets/9096952/9cf42751-551b-4c9e-9321-53c1b9128249)
This is the result:
![image](https://github.com/rsyslog/rsyslog/assets/9096952/24b50ea9-e99b-4403-9ab4-af2d93c95330)

The same behaviour is with the legacy config directive.
![image](https://github.com/rsyslog/rsyslog/assets/9096952/f35755fb-569e-4f82-86e5-b71dd5e50bc4)
Service status:
![image](https://github.com/rsyslog/rsyslog/assets/9096952/e86b87f8-a4c4-4890-af00-d1105b17e71f)

When I comment it:
![image](https://github.com/rsyslog/rsyslog/assets/9096952/f0e4a726-f326-40ec-85e3-3f16370b9b4c)
Service status:
![image](https://github.com/rsyslog/rsyslog/assets/9096952/24c1ec60-0fdc-4cc8-b4f6-7529f4be10c6)

Does there exist a command to list loaded modules? 
Thank you.

**Comment by rgerhards** [comment]
Please create a debug log. Instructions: https://www.rsyslog.com/doc/v8-stable/troubleshooting/howtodebug.html

**Be sure that the problem in question occurs at least once during the debug run**. Once this is done, please post the debug log (e.g. via pastebin or github). After that, we can review the contents and check how exactly rsyslog processing worked.

**Comment by xzizka** [comment]
Thank you @rgerhards 
Here is the debug log file. I tried to repeat the situations from my post above.
[rsyslog.tar.gz](https://github.com/rsyslog/rsyslog/files/13794647/rsyslog.tar.gz)

I see the messages in the log file. Hopefully, the log will be useful. Thank you.

**Comment by xzizka** [comment]
Hello @rgerhards 
Are the uploaded debug files sufficient for your investigation? Would you need any additional info? Thank you.

**Comment by rgerhards** [comment]
I overlooked the posting, but have checked the log now. Unfortunately, it looks like this is a run where imfile is not loaded. I guess I was too unspecific, sorry for that. I need a run, where you load imfile. The idea is to check that there really only is a single load and what happens along the way. Be sure to place the debug enable statements **right at top of rsyslog.conf**, so that we can see the full config load.

**Comment by xzizka** [comment]
Hello @rgerhards 
The configuration you suggested was placed just after the first comment (now commented)... 
```
[root@konor2 ~]# cat /etc/rsyslog.conf
# rsyslog configuration file
#$DebugFile /var/log/rsyslog.debug
#$DebugLevel 2
# For more information see /usr/share/doc/rsyslog-*/rsyslog_conf.html
# or latest version online at http://www.rsyslog.com/doc/rsyslog_conf.html
# If you experience problems, see http://www.rsyslog.com/doc/troubleshoot.html
...
```
Is it necessary to place it above the first comment?
Nevertheless... I placed it above the first comment and repeated the test.
```
[root@konor2 ~]# cat /etc/rsyslog.conf | head -n 10
$DebugFile /var/log/rsyslog.debug
$DebugLevel 2
# rsyslog configuration file
# For more information see /usr/share/doc/rsyslog-*/rsyslog_conf.html
# or latest version online at http://www.rsyslog.com/doc/rsyslog_conf.html
# If you experience problems, see http://www.rsyslog.com/doc/troubleshoot.html

#### GLOBAL DIRECTIVES ####

# Where to place auxiliary files
[root@konor2 ~]#
...
```
Here is the debug file again:
[rsyslog.debug.gz](https://github.com/rsyslog/rsyslog/files/13857304/rsyslog.debug.gz)

Thank you

**Comment by rgerhards** [comment]
Yeah, that answers the question. You actually include /etc/ryslog.d/*.conf **twice**. Thus vums.conf is included twice, thus the double module load. I hadn't seen this initially, but in your /etc/rsyslog.conf the duplicated includes are in line 16 and 37.

**Comment by xzizka** [comment]
@rgerhards That solved the issue. Thank you for your help.

**Comment by Tillmanfiber-sx** [comment]
did the imfile module work properly for you? i was trying to use this module for existing logs, but it worked only once and it stops working after I change the rsyslog.conf

**Comment by ven000** [comment]
did the imfile module work properly for you? i was trying to use this module for existing logs, but it worked only once and it stops working after I change the rsyslog.conf.
