### ISSUE TITLE
Ubuntu 22.04 missing omudpspoof.so module

### ISSUE THREAD

**Issue by dlck014** [rsyslog/rsyslog#5304]
### Expected behavior
apt install rsyslog-udpspoof

### Actual behavior
apt install rsyslog
rsyslog                rsyslog-doc            rsyslog-gnutls         rsyslog-hiredis        rsyslog-kubernetes     rsyslog-mysql          rsyslog-pgsql          rsyslog-snmp           
rsyslog-czmq           rsyslog-elasticsearch  rsyslog-gssapi         rsyslog-kafka          rsyslog-mongodb        rsyslog-openssl        rsyslog-relp 
 
### Steps to reproduce the behavior
check above

### Environment
- rsyslog version:  8.2112.0
- platform: Ubuntu 22.04
- for configuration questions/issues, include rsyslog.conf and included config files

**Comment by rgerhards** [comment]
You need to raise this issue with ubuntu maintainers.
