### ISSUE TITLE
Rsyslogd cannot create Unix sockets for internal-sftp logging

### ISSUE THREAD

**Issue by bandi22** [rsyslog/rsyslog#5312]
### Expected behavior

Chroot jailed users' _internal-sftp_ logging is configured via a Unix socket for rsyslog.
Rsyslog is expected to write the SFTP activity of the users into the configured log file.

### Actual behavior

Rsyslog fails to create or handle the sockets used for logging with the following error message:

```
Jan 17 14:22:58 myhost.example.com rsyslogd[3745]: cannot create '/home/sftp/chroot-user/dev/log': Read-only file system [v8.2102.0-13.el8 try https://www.rsyslog.com/e/2176 ]
```

The logs are not written as expected and no log files were created after _logrotate_ handled the log files.

The configuration was working fine until the most recent OS update, which also included the Rsyslog update to  v8.2102.0-15.el8.

### Steps to reproduce the behavior

- Install / upgrade to 8.2102.0-15
- Set up chroot _internal-sftp_ logging via Unix socket
- Restart _sshd_ and/or _rsyslogd_ service

### Workaround

- Downgraded the Rsyslog package from v8.2102.0-15 to 8.2102.0-13
- Restarted _sshd_ and _rsyslog_ services (with the same configuration)

### Environment
- rsyslog version: 8.2102.0-15.el8
- platform: Oracle Linux 8.9 (4.18.0-513.9.1.el8_9.x86_64 RHEL kernel)

**/etc/ssh/sshd_config (Match Group chroot configuration):**

```
Match Group chroot_group
AllowTCPForwarding yes
AuthorizedKeysFile xxxxxxxxx
ChrootDirectory /home/sftp/chroot-user
ForceCommand internal-sftp -f LOCAL2 -l VERBOSE
```

**/etc/rsyslog.conf (relevant parts):**

```
module(load="imuxsock"    # provides support for local system logging (e.g. via logger command)
       SysSock.Use="off") # Turn off message reception via local log socket;
                          # local messages are retrieved through imjournal now.

# internal-sftp logs
local2.*                                                /var/log/sftp/sftp.log
```

**/etc/rsyslog.d/sftp.conf**

```
input(type="imuxsock" Socket="/home/sftp/chroot-user/dev/log" CreatePath="on")
```

**Comment by davidelang** [comment]
v8.2101 is Febuary 2021, please upgrade to a current version that the community 
can support.

given that the version number you are listing has a -## after it, that's 
probably a distro maintained version where they backport some features from 
newer community releases, but we don't know what they do and don't backport.

According to the error message that you are showing, rsyslog does not have 
permission to create the socket (the filesystem is readonly)

David Lang

**Comment by bandi22** [comment]
Thanks for the info!

>rsyslog does not have
permission to create the socket (the filesystem is readonly)

The service starts as root and then drops the privileges to run as the syslog user, if I am correct (I don't know if this happens before or after creating the socket). Nevertheless, logging was working fine before the version update and no directory or filesystem permissions were changed so it should have sufficient privileges to create the socket. Also, downgrading rsyslog to the previous version solved the issue, without changing any filesystem/directory permissions.

Anyway, I'll open a ticket with the issue for the Oracle Linux support, thanks for pointing me at the right direction!

Andras

**Comment by nbanb** [comment]
Hello

I have the same trouble in 2024-04 when using rsyslogd 8.2102.0-117.el9 on RHEL 9.3 with SELinux in enforcing mode and a jailed SFTP (rsyslog drop privilege but the bind mount chain have to be owned by root) 
The log clearly contains : 
setroubleshoot[47118]: SELinux block /usr/sbin/rsyslogd to access setattr on sock_file /srv/ssh/jail/sirh/dev/log

It' seems it would be a bug as creating an SELinux exception for rsyslog on the log socket is not sufficient to solve the issue
I will maybe open a case at RedHat

Regards
nbanba
