### ISSUE TITLE
log endings are cut and concatenated on remote rsyslog

### ISSUE THREAD

**Issue by mta59066** [rsyslog/rsyslog#5326]
### Expected behavior

Logs are sent from a local rsyslog to a remote rsyslog (imtcp). Excepted behaviour is for the log lines to remain separate and individual, if the log line is longer than what is acceptable it should be cut and the remaining characters truncated.

### Actual behavior

Log lines are cut and the rest of the log line is still processed. For example the following creates random log files, whatever string happens to be at the position of the hostname is used. 

```
$template DynaFile,"/var/log/%HOSTNAME%.log"
*.* -?DynaFile
```

And in some circumstances rest of the following log lines are concatenated behind the remaining log line, and from that point on all remaining log lines are cut in different places based on size instead of log endings. If this happens we are able to see the byte size at the end of the previous log line followed by a space and priority `<166>`, like below.

```
... some text2646 <166>Feb 14 11:10:47 hostname prog[123]: other text ..... 3162 <166>Feb 14 11:10:51 hostname prog[233]: other text ..... 
```

### Steps to reproduce the behavior

We are actively observing the behavior on our running systems, believing that it is because of certain run away very long log lines generated by an application, but I am not able to reproduce it by hand with for example `logger` command.

### Environment
- rsyslog version: rsyslogd  8.2102.0-13.el8 (aka 2021.02)
- platform: x86_64-redhat-linux-gnu

**Comment by davidelang** [comment]
If you log using the template RSYSLOG_DebugFormat we can see exactly what 
rsyslog is receiving, including control characters (#xxx octal representation of 
the control characters)

As Rainer says, odds are good that your sender is not sending a newline at the 
end of the message as the syslog RFCs require.

when you get extremely long lines, you hit the maxmessagesize log length and 
rsyslog chops the message at that point (you can configure it to log what 
follows as a new message or throw it away), but in your case, it looks as if 
it's missing the 'end of message' marker.

David Lang

**Comment by mta59066** [comment]
Thank you for the comments. The sender is rsyslog as well, application on the sender machine logs to rsyslog, and rsyslog sends to another rsyslog via tcp and that rsyslog saves to a `%HOSTNAME%.log` file as well as shipping certain parts to logstash. Above mentioned rsyslogd 8.2102.0-13.el8 runs on RHEL8 and same issue is observed on RHEL7 installation which shows rsyslog version as 8.24.0-57.el7_9.3. I can try to upgrade if you think that might help, instead of using RHEL packages. I'll also try to use the RSYSLOG_DebugFormat to see if I can gather further details.

**Comment by davidelang** [comment]
debugformat on the receiver will help, then we would need to see the sender 
config

8.24 is ancient (with some unknown amount of backports from RedHat) but the only 
way it would be messing up the log ending is if there is a template defined 
incorrectly there.

David Lang

**Comment by mta59066** [comment]
I turned on debug format on the receiving end and here is an example I was able to catch;

Actual log on the originating server (I don't have debug output) 60890 characters not including date, hostname program and pid which are 43 characters:
```
Feb 15 13:43:58 someserver01 someapp[25276]: some log line that ends with REQUEST FOR QUOTATION log line continues '
```

First part of the message on the receiving server with setting `$MaxMessageSize 32k`. The `msg` part is 32292 characters (not including the first space).
```
Debug line with all properties:
FROMHOST: 'someserver01', fromhost-ip: '10.10.10.4', HOSTNAME: 'someserver01', PRI: 166,
syslogtag 'someapp[25276]:', programname: 'someapp', APP-NAME: 'someapp', PROCID: '25276', MSGID: '-',
TIMESTAMP: 'Feb 15 13:43:58', STRUCTURED-DATA: '-',
msg: ' some log line that ends with REQUEST FO'
escaped msg: ' some log line that ends with REQUEST FO'
inputname: imtcp rawmsg: '<166>Feb 15 13:43:58 someserver01 someapp[25276]: some log line that ends with REQUEST FO'
$!:
$.:
$/:
```

Bottom part of the message 28594 characters
```
Debug line with all properties:
FROMHOST: 'someserver01', fromhost-ip: '10.10.10.4', HOSTNAME: 'R', PRI: 13,
syslogtag 'A', programname: 'A', APP-NAME: 'A', PROCID: '-', MSGID: '-',
TIMESTAMP: 'Feb 15 13:43:58', STRUCTURED-DATA: '-',
msg: ' QUOTATION log line continues '
escaped msg: ' QUOTATION log line continues '
inputname: imtcp rawmsg: 'R A QUOTATION log line continues '
$!:
$.:
$/:
```

**Comment by davidelang** [comment]
if you are sending a 60k message and have a maxmessagesize of 32k on the 
receiver, you are going to have the message split into two at the 32k mark.

you would need to set the maxmessagesize >60k toi avoid it

on current versions, you can configure rsyslog to truncate the message instead 
of splitting it.

David Lang

**Comment by mta59066** [comment]
Ahh, ok that was part of my original question, my expectation was to see it truncated but I guess I was not able to find the correct documentation. Thank you.

**Comment by mta59066** [comment]
@davidelang and one more question to clarify, during the splitting the expected behaviour is to also loose other variables such as hostname, appname, etc. and fill them up with the rest of the message?

**Comment by davidelang** [comment]
the version you are running is 3 years old (2102 is Feb 2021) the truncation 
capability was added after that.

David Lang

**Comment by davidelang** [comment]
those variables are based on the new message starting after the split, since it 
doesn't have hostname/appname/etc rsyslog trys to parse something from the 
message, but it's not going to be correct.

fromhost-ip and fromhost are the only things that will be correct.

the rawmesg field you see in the debugformat log is all that it has to work 
with.

David Lang

  On Thu, 15 Feb 2024, Mehmet Tolga 
Avcioglu wrote:

> Date: Thu, 15 Feb 2024 03:54:31 -0800
> From: Mehmet Tolga Avcioglu ***@***.***>
> Reply-To: rsyslog/rsyslog
>     ***@***.***>
> To: rsyslog/rsyslog ***@***.***>
> Cc: David Lang ***@***.***>, Mention ***@***.***>
> Subject: Re: [rsyslog/rsyslog] log endings are cut and concatenated on remote
>     rsyslog (Issue #5326)
> 
> @davidelang and one more question to clarify, during the splitting the expected behaviour is to also loose other variables such as hostname, appname, etc. and fill them up with the rest of the message?
>
>

**Comment by mta59066** [comment]
Thank you
