### ISSUE TITLE
Build with old openssl 1.0.1e (el6) since nsd_ossl.c revamp / dtls

### ISSUE THREAD

**Issue by julthomas** [rsyslog/rsyslog#5342]
### Expected behavior

This issue to let you know rsyslog does not build anymore from 8.2402.0 on an old distribution with openssl 1.0.1e (el6). Note : support for imdtls/omdtls not enabled, at least not explicitly with --enable-imdtls/omdtls. I undestand this is a corner case for a very old version of openssl on a distro that is EOL. This is more for sharing information in case you would like to address the issue.

### Actual behavior

```
...
libtool: compile:  gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I.. -pthread -I../runtime -I.. -I../grammar -I/tmp/../tmp/../tmp/BUILD/rsyslog8z-8.2402.0/libestr-0.1.11/include -I/tmp/../tmp/../tmp/BUILD/rsyslog8z-8.2402.0/libfastjson-1.2304.0 -W -Wall -Wformat-security -Wshadow -Wcast-align -Wpointer-arith -Wmissing-format-attribute -Werror=implicit-function-declaration -g -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -fPIC -g -I/tmp/../tmp/../tmp/BUILD/rsyslog8z-8.2402.0/libmaxminddb-1.9.1/include -I/tmp/../tmp/../tmp/BUILD/rsyslog8z-8.2402.0/civetweb-1.16/include -W -Wall -Wformat-security -Wshadow -Wcast-align -Wpointer-arith -Wmissing-format-attribute -g -MT lmnsd_gtls_la-nsd_gtls.lo -MD -MP -MF .deps/lmnsd_gtls_la-nsd_gtls.Tpo -c nsd_gtls.c  -fPIC -DPIC -o .libs/lmnsd_gtls_la-nsd_gtls.o
mv -f .deps/lmnsd_ptcp_la-nsdpoll_ptcp.Tpo .deps/lmnsd_ptcp_la-nsdpoll_ptcp.Plo
net_ossl.c: In function 'net_ossl_apply_tlscgfcmd':
net_ossl.c:482: error: 'SSL_CONF_CTX' undeclared (first use in this function)
net_ossl.c:482: error: (Each undeclared identifier is reported only once
net_ossl.c:482: error: for each function it appears in.)
net_ossl.c:482: error: 'cctx' undeclared (first use in this function)
net_ossl.c:483: error: implicit declaration of function 'SSL_CONF_CTX_new'
net_ossl.c:485: error: implicit declaration of function 'SSL_CONF_CTX_set_flags'
net_ossl.c:485: error: 'SSL_CONF_FLAG_SERVER' undeclared (first use in this function)
net_ossl.c:487: error: 'SSL_CONF_FLAG_CLIENT' undeclared (first use in this function)
net_ossl.c:489: error: 'SSL_CONF_FLAG_FILE' undeclared (first use in this function)
net_ossl.c:490: error: 'SSL_CONF_FLAG_SHOW_ERRORS' undeclared (first use in this function)
net_ossl.c:491: error: implicit declaration of function 'SSL_CONF_CTX_set_ssl_ctx'
net_ossl.c:510: error: implicit declaration of function 'SSL_CONF_cmd'
net_ossl.c:532: error: implicit declaration of function 'SSL_CONF_CTX_finish'
net_ossl.c:540: error: implicit declaration of function 'SSL_CONF_CTX_free'
...
```

### Steps to reproduce the behavior

Build on old CentOS 6.

### Environment
- rsyslog version: 8.2402.0
- platform: CentOS 6 (openssl 1.0.1e)
- for configuration questions/issues, include rsyslog.conf and included config files

### Analysis

Looking at the changes in patch 679b0b038c81a6456a20179d125085656b21d27c (Initial implementation of imdtls and omdtls modules), the code that is now in net_ossl_apply_tlscgfcmd() was not included before by the preprocessor (`#if OPENSSL_VERSION_NUMBER >= 0x10002000L && !defined(LIBRESSL_VERSION_NUMBER)`).

If you patch as follows, it builds, though I am not sure it the proper way to do since in that case it should probably be forbidden to enable im/omdtls module in configure (openssl version check as in the `#if` condition):

```
--- rsyslog-8.2402.0/runtime/net_ossl.c	2024-02-26 08:24:02.000000000 +0000
+++ rsyslog-8.2402.0.new/runtime/net_ossl.c	2024-02-29 13:48:05.174713344 +0000
@@ -460,6 +460,7 @@
 
 /* initialize tls config commands in openssl context
  */
+#if OPENSSL_VERSION_NUMBER >= 0x10002000L && !defined(LIBRESSL_VERSION_NUMBER)
 rsRetVal net_ossl_apply_tlscgfcmd(net_ossl_t *pThis, uchar *tlscfgcmd)
 {
 	DEFiRet;
@@ -543,6 +544,7 @@
 finalize_it:
 	RETiRet;
 }
+#endif
 
 
 /* Convert a fingerprint to printable data. The  conversion is carried out
```

**Comment by rgerhards** [comment]
@alorbach can you have a look pls - does that have some implications on the feature set, so that we need to document it?

**Comment by alorbach** [comment]
Thanks for the issue. I have created a fix for the problem, see PR https://github.com/rsyslog/rsyslog/pull/5356
omdtls cannot be build on OpenSSL prior 1.0.2, and imdtls needs at least OpenSSL 1.1.0 due the missing OpenSSL API functions.
