### ISSUE TITLE
rsyslog-debug.log  file size rapidly increasing

### ISSUE THREAD

**Issue by srinidks** [rsyslog/rsyslog#5383]
Hello,
The rsyslog-debug.log file size is rapidly increasing due to that root volume  has breached 100% . Please help me figure out how to fix the issue. 
 $ rsyslogd -v
rsyslogd 8.24.0, compiled with:
        PLATFORM:                               x86_64-redhat-linux-gnu
        PLATFORM (lsb_release -d):
        FEATURE_REGEXP:                         Yes
        GSSAPI Kerberos 5 support:              Yes
        FEATURE_DEBUG (debug build, slow code): No
        32bit Atomic operations supported:      Yes
        64bit Atomic operations supported:      Yes
        memory allocator:                       system default
        Runtime Instrumentation (slow code):    No
        uuid support:                           Yes
        Number of Bits in RainerScript integers: 64

========================================
**tail -f rsyslog-debug.log**

802.220361100:main Q:Reg/w0  :     ACTION 9 [builtin:omfwd:@@100.64.54.206:514]
8802.220370144:main Q:Reg/w0  : executing action 9
8802.220373770:main Q:Reg/w0  : action 'action 9': called, logging to builtin:omfwd (susp 0/0, direct q 1)
8802.220377634:main Q:Reg/w0  : action 'action 9': is transactional - executing in commit phase
8802.220381510:main Q:Reg/w0  : actionTryResume: action 0x561fdc41a720 state: susp, next retry (if applicable): 1715938861 [now 1715938802]
8802.220385046:main Q:Reg/w0  : action 'action 9': set suspended state to 1
8802.220388687:main Q:Reg/w0  : processBATCH: next msg 1: Stopping User Slice of root.
8802.220391895:main Q:Reg/w0  :     IF
8802.220400514:main Q:Reg/w0  :         var 'programname'
8802.220414483:main Q:Reg/w0  :       ==
8802.220432296:main Q:Reg/w0  :         string 'authlog'
8802.220453804:main Q:Reg/w0  : eval expr 0x561fdc416bf0, type 'CMP_EQ'
8802.220457707:main Q:Reg/w0  : eval expr 0x561fdc416540, type 'V'
8802.220461960:main Q:Reg/w0  : rainerscript: (string) var 17: 'systemd'
8802.220465854:main Q:Reg/w0  : eval expr 0x561fdc416540, return datatype 'S':0
8802.220469745:main Q:Reg/w0  : eval expr 0x561fdc416bf0, return datatype 'N':0
8802.220476837:main Q:Reg/w0  : if condition result is 0
8802.220480138:main Q:Reg/w0  :     IF
8802.220488695:main Q:Reg/w0  :         var 'programname'
8802.220502563:main Q:Reg/w0  :       ==
8802.220513738:main Q:Reg/w0  :         string 'authlog'
8802.220530641:main Q:Reg/w0  : eval expr 0x561fdc417fb0, type 'CMP_EQ'
8802.220533894:main Q:Reg/w0  : eval expr 0x561fdc418780, type 'V'
8802.220537267:main Q:Reg/w0  : rainerscript: (string) var 17: 'systemd'
8802.220540506:main Q:Reg/w0  : eval expr 0x561fdc418780, return datatype 'S':0
8802.220543745:main Q:Reg/w0  : eval expr 0x561fdc417fb0, return datatype 'N':0
8802.220546879:main Q:Reg/w0  : if condition result is 0
8802.220550030:main Q:Reg/w0  :     PRIFILT 'local6.debug'
8802.220558645:main Q:Reg/w0  :     pmask:  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X FF  X  X  X
8802.220638922:main Q:Reg/w0  : PRIFILT condition result is 0
8802.220642037:main Q:Reg/w0  :     PRIFILT '*.info;mail.none;authpriv.none;cron.none'
8802.220650673:main Q:Reg/w0  :     pmask: 7F 7F  X 7F 7F 7F 7F 7F 7F  X  X 7F 7F 7F 7F 7F 7F 7F 7F 7F 7F 7F 7F 7F 7F 7F
8802.220732424:main Q:Reg/w0  : PRIFILT condition result is 1
8802.220735586:main Q:Reg/w0  :     ACTION 2 [builtin:omfile:/var/log/messages]
8802.220744538:main Q:Reg/w0  : executing action 2
8802.220748081:main Q:Reg/w0  : action 'action 2': called, logging to builtin:omfile (susp 0/1, direct q 1)
8802.220751742:main Q:Reg/w0  : action 'action 2': is transactional - executing in commit phase
8802.220755117:main Q:Reg/w0  : action 'action 2': set suspended state to 0
8802.220758251:main Q:Reg/w0  :     PRIFILT 'authpriv.*'
8802.220766842:main Q:Reg/w0  :     pmask:  X  X  X  X  X  X  X  X  X  X FF  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X
8802.220847178:main Q:Reg/w0  : PRIFILT condition result is 0
8802.220850285:main Q:Reg/w0  :     PRIFILT 'mail.*'
8802.220858838:main Q:Reg/w0  :     pmask:  X  X FF  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X
8802.220939036:main Q:Reg/w0  : PRIFILT condition result is 0
8802.220942112:main Q:Reg/w0  :     PRIFILT 'cron.*'
8802.220950650:main Q:Reg/w0  :     pmask:  X  X  X  X  X  X  X  X  X FF  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X
8802.221036822:main Q:Reg/w0  : PRIFILT condition result is 0
8802.221039964:main Q:Reg/w0  :     PRIFILT '*.emerg'
8802.221048506:main Q:Reg/w0  :     pmask:  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
8802.221130252:main Q:Reg/w0  : PRIFILT condition result is 0
8802.221133386:main Q:Reg/w0  :     PRIFILT 'uucp,news.crit'
8802.221141993:main Q:Reg/w0  :     pmask:  X  X  X  X  X  X  X  7  7  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X
8802.221222226:main Q:Reg/w0  : PRIFILT condition result is 0
8802.221225330:main Q:Reg/w0  :     PRIFILT 'local7.*'
8802.221233890:main Q:Reg/w0  :     pmask:  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X FF  X  X
8802.221314044:main Q:Reg/w0  : PRIFILT condition result is 0
8802.221317174:main Q:Reg/w0  :     ACTION 9 [builtin:omfwd:@@100.64.54.206:514]
8802.221326015:main Q:Reg/w0  : executing action 9
8802.221329528:main Q:Reg/w0  : action 'action 9': called, logging to builtin:omfwd (susp 0/0, direct q 1)
8802.221333159:main Q:Reg/w0  : action 'action 9': is transactional - executing in commit phase
8802.221336812:main Q:Reg/w0  : actionTryResume: action 0x561fdc41a720 state: susp, next retry (if applicable): 1715938861 [now 1715938802]
8802.221340115:main Q:Reg/w0  : action 'action 9': set suspended state to 1
8802.221343443:main Q:Reg/w0  : END batch execution phase, entering to commit phase [processed 2 of 2 messages]
8802.221346991:main Q:Reg/w0  : actionCommitAllDirect: action 0, state 4, nbr to commit 0 isTransactional 1
8802.221350400:main Q:Reg/w0  : actionCommitAllDirect: action 1, state 0, nbr to commit 0 isTransactional 1
8802.221353688:main Q:Reg/w0  : actionCommitAllDirect: action 2, state 1, nbr to commit 0 isTransactional 1
8802.221356935:main Q:Reg/w0  : doTransaction: have commitTransaction IF, using that, pWrkrInfo 0x561fdc429870
8802.221363537:main Q:Reg/w0  : entering actionCallCommitTransaction(), state: itx, actionNbr 2, nMsgs 2
8802.221367363:main Q:Reg/w0  : omfile: write to stream, pData->pStrm 0x7f35a4012b60, lenBuf 74, strt data May 17 15:10:02 gitlab-haproxy systemd: Removed slice User Slice of root.

8802.221371173:main Q:Reg/w0  : omfile: write to stream, pData->pStrm 0x7f35a4012b60, lenBuf 69, strt data May 17 15:10:02 gitlab-haproxy systemd: Stopping User Slice of root.

8802.221375088:main Q:Reg/w0  : strm 0x7f35a4012b60: strmFlushinternal: file 18(/var/log/messages) flush, buflen 143
8802.221378923:main Q:Reg/w0  : strm 0x7f35a4012b60: file 18(/var/log/messages) doWriteInternal: bFlush 1
8802.221382374:main Q:Reg/w0  : strmPhysWrite, stream 0x7f35a4012b60, len 143
8802.221390209:main Q:Reg/w0  : strm 0x7f35a4012b60: file 18 write wrote 143 bytes
8802.221394020:main Q:Reg/w0  : Action 2 transitioned to state: rdy
8802.221397530:main Q:Reg/w0  : actionCommit, action 2, in retry loop, iRet 0
8802.221400903:main Q:Reg/w0  : actionCommitAllDirect: action 3, state 0, nbr to commit 0 isTransactional 1
8802.221404459:main Q:Reg/w0  : actionCommitAllDirect: action 5, state 0, nbr to commit 0 isTransactional 1
8802.221407770:main Q:Reg/w0  : actionCommitAllDirect: action 9, state 4, nbr to commit 0 isTransactional 1
8802.221410956:main Q:Reg/w0  : processBATCH: batch of 2 elements has been processed
8802.221414536:main Q:Reg/w0  : regular consumer finished, iret=0, szlog 0 sz phys 2
8802.221432680:main Q:Reg/w0  : DeleteProcessedBatch: we deleted 2 objects and enqueued 0 objects
8802.221436251:main Q:Reg/w0  : doDeleteBatch: delete batch from store, new sizes: log 0, phys 0
8802.221439942:main Q:Reg/w0  : regular consumer finished, iret=4, szlog 0 sz phys 0
8802.221446596:main Q:Reg/w0  : main Q:Reg/w0: worker IDLE, waiting for work.
8808.760491516:imfile.c       : strm 0x7f35a0003440: file 16 read 0 bytes
8808.760531917:imfile.c       : stream checking for file change on '/var/log/secure', inode 2757093/2757093
8808.760541820:imfile.c       : strm 0x7f35a0002cd0: file 15 read 0 bytes
8808.760552756:imfile.c       : stream checking for file change on '/opt/fortinet/fortisiem/linux-agent/log/phoenix.log', inode 1837144/1837144
8818.770688584:imfile.c       : strm 0x7f35a0003440: file 16 read 0 bytes
8818.770756476:imfile.c       : stream checking for file change on '/var/log/secure', inode 2757093/2757093
8818.770777088:imfile.c       : strm 0x7f35a0002cd0: file 15 read 0 bytes
========
Thank You.

**Comment by rgerhards** [comment]
Well, it's a file purely used for debugging. Just dot no write it. Debugging should *NEVER* be activated on a production system.
