### ISSUE TITLE
Why can't I connect to RabbitMQ Server using omrabbitmq

### ISSUE THREAD

**Issue by dunkboy** [rsyslog/rsyslog#5384]
### Environment
- rsyslog version: rsyslogd  8.2210.0 (aka 2022.10) 
- platform:  openEuler 22.03 (LTS-SP3)  x86_64-openEuler-linux-gnu
- for configuration questions/issues, include rsyslog.conf and included config files
module(load="omrabbitmq")
action(type="omrabbitmq"
       host="10.120.31.207"
       virtual_host="/"
       user="admin"
       password="wnjnjw1111"
       ssl="on"
       exchange="direct_exchange_name"
       routing_key="routing_key")

I configured the connection of rabbitmq according to the example in the official document, and then restarted rsyslog. After checking the status of rsyslog, I found that I have been reconnecting to rabbitmq's service. I can confirm with certainty that rabbitmq's service is normal and can be used because I can connect normally using other methods, such as Java. I am not sure if it is due to version issues. Why does the official document not provide the specific client version that needs to be used?

error like this:
5月 17 19:03:09 xxxx rsyslogd[2395362]: omrabbitmq module 1/2: server 10.120.31.207 port 5672. [v8.2210.0 try https://www.rsyslog.com/e/2449 ]
5月 17 19:03:10 xxxx rsyslogd[2395362]: omrabbitmq module 1/2: server 10.120.31.207 port 5672. [v8.2210.0 try https://www.rsyslog.com/e/2449 ]
5月 17 19:03:10 xxxx rsyslogd[2395362]: omrabbitmq module 1/1: server 10.120.31.207 port 5672. [v8.2210.0 try https://www.rsyslog.com/e/2449 ]
5月 17 19:03:11 xxxx rsyslogd[2395362]: omrabbitmq module 1/2: server 10.120.31.207 port 5672. [v8.2210.0 try https://www.rsyslog.com/e/2449 ]
5月 17 19:03:11 xxxx rsyslogd[2395362]: omrabbitmq module connection failed 3 times on each server. [v8.2210.0 try https://www.rsyslog.com/e/2447 ]

RabbitMQ Server version is 3.13.2 and I installed it using "yum install -y rsyslog-rabbitmq" 
I don't know how to send rsyslog messages to rabbitmq, I have no problem using MySQL (ommysql)

**Comment by davidelang** [comment]
is rabbitmq listening on port 4672 on that server? does iptables allow you to 
connec to that port? is rabbitmq logging any errors (like authentication 
problems or ssl errors?)

David Lang

**Comment by dunkboy** [comment]
I am confident that both the network and rabbitmq services are functioning properly, and the port is also set to 5672 by default. I believe there may be an issue with omrabbit, as the debug logs on the rabbitmq server have not received any connection information or sent any requests. I am using other methods to connect to clients, such as Java, and there is no problem. I suspect it may be a version issue, and I cannot see the specific reason for omrabbitmq's failure

**Comment by davidelang** [comment]
On Fri, 17 May 2024, dunkboy wrote:

> I am confident that both the network and rabbitmq services are functioning 
> properly, and the port is also set to 5672 by default. I believe there may be 
> an issue with omrabbit, as the debug logs on the rabbitmq server have not 
> received any connection information or sent any requests. I am using other 
> methods to connect to clients, such as Java, and there is no problem. I 
> suspect it may be a version issue, and I cannot see the specific reason for 
> omrabbitmq's failure

you can do a tcpdump to see if you ae seeing any packets going from rsyslog to 
rabbitmq. If you see packets moving via tcpdump, but not in the rabbitmq logs, 
I would check iptables and try disabling ssl to see if you are failing at that 
point.

David Lang

**Comment by dunkboy** [comment]
I use tcpdump,But by checking the TCP information, there was no connection information sent to rabbitmq, so omrabbitmq did not connect at all, and then the log information printed directly failed to connect. This is very strange. I don't know which author is maintaining omrabbitmq, or if there is no maintenance at all. I successfully executed the nc zv 10.120.31.207 5672 command, and Rabbitmq also received the log connection information for this command.So omrabbitmq maybe have some problem.

5月 18 16:18:22 aclog rsyslogd[902744]: omrabbitmq module connection failed 3 times on each server. [v8.2210.0 try https://www.rsyslog.com/e/2447 ]
5月 18 16:18:27 aclog rsyslogd[902744]: omrabbitmq module 1/1: server 10.120.31.207 port 5672. [v8.2210.0 try https://www.rsyslog.com/e/2449 ]
5月 18 16:18:28 aclog rsyslogd[902744]: omrabbitmq module 1/1: server 10.120.31.207 port 5672. [v8.2210.0 try https://www.rsyslog.com/e/2449 ]
5月 18 16:18:29 aclog rsyslogd[902744]: omrabbitmq module 1/1: server 10.120.31.207 port 5672. [v8.2210.0 try https://www.rsyslog.com/e/2449 ]
5月 18 16:18:29 aclog rsyslogd[902744]: omrabbitmq module connection failed 3 times on each server. [v8.2210.0 try https://www.rsyslog.com/e/2447 ]
5月 18 16:18:34 aclog rsyslogd[902744]: omrabbitmq module 1/1: server 10.120.31.207 port 5672. [v8.2210.0 try https://www.rsyslog.com/e/2449 ]
5月 18 16:18:35 aclog rsyslogd[902744]: omrabbitmq module 1/1: server 10.120.31.207 port 5672. [v8.2210.0 try https://www.rsyslog.com/e/2449 ]
5月 18 16:18:36 aclog rsyslogd[902744]: omrabbitmq module 1/1: server 10.120.31.207 port 5672. [v8.2210.0 try https://www.rsyslog.com/e/2449 ]
5月 18 16:18:36 aclog rsyslogd[902744]: omrabbitmq module connection failed 3 times on each server. [v8.2210.0 try https://www.rsyslog.com/e/2447 ]
5月 18 16:18:41 aclog rsyslogd[902744]: omrabbitmq module 1/1: server 10.120.31.207 port 5672. [v8.2210.0 try https://www.rsyslog.com/e/2449 ]

**Comment by davidelang** [comment]
make sure you are listening on the correct interface, from the IP address shown 
it's not on loopback.

I'm assuming rsyslog and rabbitmq are on the same system

if you use rsyslogd -N1 does it give you any error messages?

I don't know when the contributed omrabbitmq was last updated, but since you are 
around a year and a half behind the current version, it wouldn't hurt to upgrade 
to current.

David Lang

**Comment by rgerhards** [comment]
all informations on the authors is in the doc page:

https://www.rsyslog.com/doc/configuration/modules/omrabbitmq.html

This is a contributed plugin. I, for example, have never used RabitMQ. I guess this is the same for the rsyslog core team.

**Comment by dunkboy** [comment]
I gave up. Anyway, thank you for your reply

**Comment by dunkboy** [comment]
I gave up. Anyway, thank you for your reply

**Comment by Nikhiladiga** [comment]
I'm facing the same issue, did anyone find the solution for this?
