### ISSUE TITLE
rsyslog debugging message sometimes is wrongly saved in other log files defined by other template.

### ISSUE THREAD

**Issue by stonelzhang** [rsyslog/rsyslog#5404]
### Expected behavior
impstats debug message will be persist in rsyslogstats.log file. 

### Actual behavior
But occasionally it's saved in testlog directory defined by other template. This not often happens, but once or twice a month triggering mis-alerts that monitors data loss.

### Steps to reproduce the behavior
Couldn't re-create the behavior, as this is not happenning under a scheduled operation.

### Environment
- rsyslog version:  8.2
- platform: Red Hat Linux 7.9
- for configuration questions/issues, include rsyslog.conf and included config files
$ActionQueueSize 100000
$ActionQueueWorkerThreads 6
$ActionQueueWOrkerThreadMinimumMessages 10000
$CreateDirs on
$PreserveFQDN on
$MaxMessageSize 64k
$MainMsgQueueDiscardMark 95000
$MainMsgQueueHighWaterMark 90000
$MainMsgQueueSize 100000
$MainMsgQueueWorkerThreadMinimumMessages 10000
$MainMsgQueueWorkerThreads 6
$OMFileASyncWriting on
$OMFileIOBufferSize 64k
$umask 0000

module(load="impstats" interval="60" severity="7")
template(name="d_rsyslog_stats" type="string" string="/var/log/splunk/syslog/slab/syslog/%$YEAR%-%$MONTH%-%$DAY%_%$HOUR%/rsyslogstats.log")
syslog.debug action(
  name="rsyslog_stats_action"
  type="omfile"
  dirCreateMode="0770"
  fileCreateMode="0660"
  fileOwner="loguser"
  fileGroup="loggroup"
  dirOwner="loguser"
  dirGroup="loggroup"
  dynaFile="d_rsyslog_stats"
)

template(name="d_test"          type="string" string="/var/log/splunk/syslog/slab/testlog/%$YEAR%-%$MONTH%-%$DAY%_%$HOUR%/%FROMHOST%/%HOSTNAME%/%SYSLOGFACILITY%.log")

ruleset(name="test" queue.saveonshutdown="on"){
    action(
      name="test_action"
      type="omfile"
      dirCreateMode="0770"
      dirGroup="logmgrgrp"
      dirOwner="loguser"
      fileCreateMode="0660"
      fileGroup="loggroup"
      DynaFile="d_test"
    )

}

input(type="imptcp" port="10514" ruleset="test" KeepAlive="on" KeepAlive.Probes="3" KeepAlive.Time="30")

**Comment by davidelang** [comment]
is this the full config?

please post a sample log that is saved in the wrong place. Ideally also show us 
that log message with the template RSYSLOG_DebugFormat so we can see all the 
properties parsed from the message

Usually in cases like this, the message is not getting parsed the way you expect 
it to be.

David Lang

**Comment by stonelzhang** [comment]
Thank you David for swift response.  This is not the full configuration. The full configuration contains key word match or regex match in order to route the payload to different template. However, that was too long and I've gone through the matching rules bit by bit, rsyslog stats logs should not fall into any one of the matches. 

The log samples are 
Jun 29 02:04:42 fedora rsyslogd-pstats: imuxsock: origin=imuxsock submitted=0 ratelimit.discarded=0 ratelimit.numratelimiters=0 
Jun 29 02:04:42 fedora rsyslogd-pstats: dynafile cache d_rsyslog_stats: origin=omfile requests=19554 level0=19534 missed=20 evicted=0 maxused=3 closetimeouts=18 
Jun 29 02:04:42 fedora rsyslogd-pstats: rsyslog_stats_action: origin=core.action processed=19554 failed=0 suspended=0 suspended.duration=0 resumed=0 
Jun 29 02:04:42 fedora rsyslogd-pstats: dynafile cache d_test: origin=omfile requests=40 level0=30 missed=10 evicted=0 maxused=1 closetimeouts=10 
Jun 29 02:04:42 fedora rsyslogd-pstats: test_action: origin=core.action processed=40 failed=0 suspended=0 suspended.duration=0 resumed=0

**Comment by davidelang** [comment]
without seeing the rules, I have no way of figuring out why a particular log 
message may match more than one rule

David Lang

stonelzhang wrote:

> Thank you David for swift response.  This is not the full configuration. The 
> full configuration contains key word match or regex match in order to route 
> the payload to different template. However, that was too long and I've gone 
> through the matching rules bit by bit, rsyslog stats logs should not fall into 
> any one of the matches.
>
> The log samples are
> Jun 29 02:04:42 fedora rsyslogd-pstats: imuxsock: origin=imuxsock submitted=0 ratelimit.discarded=0 ratelimit.numratelimiters=0
> Jun 29 02:04:42 fedora rsyslogd-pstats: dynafile cache d_rsyslog_stats: origin=omfile requests=19554 level0=19534 missed=20 evicted=0 maxused=3 closetimeouts=18
> Jun 29 02:04:42 fedora rsyslogd-pstats: rsyslog_stats_action: origin=core.action processed=19554 failed=0 suspended=0 suspended.duration=0 resumed=0
> Jun 29 02:04:42 fedora rsyslogd-pstats: dynafile cache d_test: origin=omfile requests=40 level0=30 missed=10 evicted=0 maxused=1 closetimeouts=10
> Jun 29 02:04:42 fedora rsyslogd-pstats: test_action: origin=core.action processed=40 failed=0 suspended=0 suspended.duration=0 resumed=0
>
>

**Comment by stonelzhang** [comment]
This is extremely difficult to re-create in my lab environment. Since it really not often happenning and when it happens, it only occures at an instant, and couldn't rsyslog stats log at that instant time will be permist (mis-considered) in any type of syslog, which has no a certain rules to follow. Once I can make sure how to recreate the situation, I'll spot this in my lab environment, I'll raise new issue. Thank you anyway.

**Comment by davidelang** [comment]
The key thing to remember is that all rules apply to all logs, so if a log 
message matches multiple rules, it will be written out for each of them

the order of rules and inputs in the files does not matter. The inputs are 
processed at startup time, and the rules are processed for each log message.

There are ways to change this (look into rulesets that you can attach a ruleset 
to an input, and the stop instruction to tell rsyslog to stop processing the 
message after it's done)

if you are filtering on properties, writing logs with RSYSLOG_DebugFormat shows 
(almost) all the values that are parsed from the message so you can see what is 
or isn't matching your filters.

David Lang
