### ISSUE TITLE
omkafa `errorFile` parameter not taking affect?

### ISSUE THREAD

**Issue by JPvRiel** [rsyslog/rsyslog#5425]
### Expected behavior

omkafka errors are written to the file path defined by `errorFile`. E.g. if the config for the action has:

```c
errorFile="/tmp/kafka_errors.log"
```

The I expect a file `/tmp/kafka_errors.log` will be created if there are errors.

### Actual behavior

The error file is never created despite Kafka errors occurring. Debug logs show that the config seems to be unset despite the value being supplied in a config file.

### Steps to reproduce the behavior

Send a test message and observe errors in rsyslog debug, but no file is created. E.g. from debug:

```console
...
7816.019195214:main thread    : rainerscript.c: nvlstGetParam: name 'errorfile', type 13, valnode->bUsed 0
...
7816.019918008:main thread    : rainerscript.c: action.errorfile: (unset)
7816.019926210:main thread    : rainerscript.c: action.errorfile.maxsize: (unset)
...
7820.907640268:7f904d11f700: omkafka.c: omkafka: kafka log message [3,FAIL]: [thrd:sasl_ssl://<namespace>.servicebus.windows.net:9093/boo]: sasl_ssl://<namespace>.servicebus.windows.net:9093/bootstrap: SASL authentication error: Invalid SASL PLAIN user name. (after 163ms in state AUTH_REQ)
```

So the errorFile seems to end up with an unset action despite being defined in the config file.

### Environment

- rsyslog version: rsyslogd  8.2404.0
- platform: AlmaLinux release 8.9 (Midnight Oncilla)

E.g. Config:

```c
module(load="omkafka")

ruleset(name="out_kafka_azure_event_hub") {

  action(
    type="omkafka"
    broker="<namespace>.servicebus.windows.net:9093"
    topic="syslog"
    partitions.auto="on"
    confParam=[
      "security.protocol=SASL_SSL",
      "sasl.mechanisms=PLAIN",
      "sasl.username=<SAS Policy/Key Name>",
      "sasl.password=<SAS Key>",
      "compression.codec=gzip",
      "batch.num.messages=1000",
      "queue.buffering.max.ms=1000",
      "socket.keepalive.enable=true"
    ]
    resubmitOnFailure="on"
    keepFailedMessages="on"
    errorFile="/tmp/kafka_errors.log"
    failedMsgFile="/var/lib/rsyslog/kafka_failed.msg"
    template="TmplJSONMetaMsgAndRawMsgNoLF"
  )

}
```

**Comment by alorbach** [comment]
This is indeed the current behavior as the the plugin is only writting into errorfile when writeDataError() is being called (which happens in deliveryCallback callback. The error "kafka log message" is actually from the kafka logger callback.

But it makes sense to log those into the errorfile if the level is RD_KAFKA_LOG_ERR or worse.
