### ISSUE TITLE
MariaDB support?

### ISSUE THREAD

**Issue by robertsilen** [rsyslog/rsyslog#5431]
Hello, I noticed that MariaDB is not mentioned in the documentation like [ommysql: MySQL Database Output Module](https://www.rsyslog.com/doc/configuration/modules/ommysql.html) and [Writing syslog messages to MySQL, PostgreSQL or any other supported Database](https://www.rsyslog.com/doc/tutorials/database.html). I'm thinking it would be fair considering mariadb is the default in most distros - and it would remove any compatibility doubts too. Any reason not to mention mariadb explicitly? Cheers

**Comment by rgerhards** [comment]
It's just so that the doc was written long before the mariadb fork. Feel free to update the doc set, would be much apricated.

https://github.com/rsyslog/rsyslog-doc/

**Comment by robertsilen** [comment]
@rgerhards Thanks, I have a suggestion in [PR #1061](https://github.com/rsyslog/rsyslog-doc/pull/1061) now.
