### ISSUE TITLE
rsyslog losing records

### ISSUE THREAD

**Issue by explorercpp** [rsyslog/rsyslog#5442]
### Expected behavior
rsyslog finishes reading the current file before moving to the next one.
### Actual behavior
the last record in the current file is not read and data loss is equal to the number of rotated files where rsyslog is reading from
### Steps to reproduce the behavior
install postgres db to write to csv files and rsyslog to read all messages and write it to kafka

### Environment
- rsyslog version: 8.2310.0-4.el9 (aka 2023.10)
- platform: x86_64-redhat-linux-gnu
- for configuration questions/issues, include rsyslog.conf and included config files

module(load="omkafka")   # provides omkafka
module(load="imfile") #needs to be done just once
$template Format,"%timegenerated:::date-rfc3339%,%HOSTNAME%,1.1.1.1,%msg%"

# Template for message key ID that will be sent to kafka topic of UC.

$template keyname,"%msg:F,44:6%"

$DebugFile /var/log/rsyslog-debug.log
$DebugLevel 2

module(load="impstats" interval="5" log.syslog="on")
*.* /var/log/rsyslog-stats.log

input(type="imfile" Tag="postgres" File="/var/lib/edb/as16/data/edb_audit3/*.csv" ruleset="kafkaRuleset2")

ruleset(name="kafkaRuleset2") {
       action(type="omkafka"
               template="Format"
               broker=["host.com:9093,host1.com:9093,host2.com:9093"]
               topic="kafka2"
               dynakey = "on"
               key="keyname"
               queue.filename="omkafkaq2-0"
               queue.spoolDirectory="/var/lib/rsyslog"
               queue.size="214748"
               queue.maxdiskspace="536870912"
               queue.lowwatermark="200000"
               queue.highwatermark="128848980"
               queue.discardmark="171798"
               queue.type="LinkedList"
               queue.discardseverity="7"
               queue.saveonshutdown="on"
               queue.dequeuebatchsize="8"
               partitions.auto="on"
	       action.resumeRetryCount="-1"
               action.resumeInterval="10"
               action.reportSuspension="on"
               action.reportSuspensionContinuation="on"
               errorFile="/var/log/rsyslog.err"
               confParam=[ "compression.codec=snappy",
                        "socket.timeout.ms=10000",
			"queue.buffering.max.messages=10000000",
                        "socket.keepalive.enable=true",
                        "security.protocol=ssl",
                        "ssl.ca.location=/tmp/crt/name.crt" ]
               )
}

**Comment by davidelang** [comment]
how are the files that it's reading rotated? or are they created independently?

does each file have a newline at the end? or is the last line not terminated?

David Lang

**Comment by explorercpp** [comment]
The database has config for maximum size of audit files. The new one is created accordingly, when previous reaches the max size.

I don't see newline at the end

**Comment by davidelang** [comment]
mu guess is that is the problem, imfile doesn't know that the message has been fully written to disk.

I think setting readTimeout to something (default value is 0, i.e. wait forever) is what you need to do to get rsyslog to give up on waiting for the newline to appear. even a couple seconds should be enough to not get a partially written message

see https://www.rsyslog.com/doc/configuration/modules/imfile.html
