### ISSUE TITLE
RL9 - External program only crashes when called thru omprog

### ISSUE THREAD

**Issue by alan-netmesh** [rsyslog/rsyslog#5443]
Hello there.
I'm coming here seeking for help, since I'm out of ideas.
We've been discussing this on nodejs/node repo (now moved to nodejs/help) issue tracker, since the external program it's an node app that reads stdin and does some processing with the text line.

nodejs/help#4465

### Background (for context)

The software should match the line using regex and return something like "Match RegEx: Part of the line" or "No matchea el regex, exiting..." (Regex doesn't match, in spanish).

The app was slimmed down to match NNN Hello World NNN (being N numbers) as a test.

At first I throught it was a system issue, but it was reproduced in a FRESH (minimal iso + dnf update + dnf install curl, nano and node) of RL9 without issues.
Same exact setup has been working flawlessly on Debian 11 for more than 2 years.

The app works just fine if it gets called like this: `echo "333 Hello World 111" | node app.js --stdin` or vía a shell script.
Only crashes when using omprog :(

### Expected behavior

`Match RegEx: 333 Hello World 111
`
### Actual behavior

```
#
# Fatal error in , line 0
# Check failed: 12 == (*__errno_location ()).
#
#
#
#FailureMessage Object: 0x7ffe7960a690
----- Native stack trace -----

 1: 0x100d701  [/root/.nvm/versions/node/v22.6.0/bin/node]
 2: 0x28d98cb V8_Fatal(char const*, ...) [/root/.nvm/versions/node/v22.6.0/bin/node]
 3: 0x28e4a87 v8::base::OS::SetPermissions(void*, unsigned long, v8::base::OS::MemoryPermission) [/root/.nvm/versions/node/v22.6.0/bin/node]
 4: 0x14cd3d5 v8::internal::MemoryAllocator::SetPermissionsOnExecutableMemoryChunk(v8::internal::VirtualMemory*, unsigned long, unsigned long, unsigned long) [/root/.nvm/versions/node/v22.6.0/bin/node]
 5: 0x14cd6f1 v8::internal::MemoryAllocator::AllocateAlignedMemory(unsigned long, unsigned long, unsigned long, v8::internal::AllocationSpace, v8::internal::Executability, void*, v8::internal::VirtualMemory*) [/root/.nvm/versions/node/v22.6.0/bin/node]
 6: 0x14cd964 v8::internal::MemoryAllocator::AllocateUninitializedChunkAt(v8::internal::BaseSpace*, unsigned long, v8::internal::Executability, unsigned long, v8::internal::PageSize) [/root/.nvm/versions/node/v22.6.0/bin/node]
 7: 0x14cdb6c v8::internal::MemoryAllocator::AllocatePage(v8::internal::MemoryAllocator::AllocationMode, v8::internal::Space*, v8::internal::Executability) [/root/.nvm/versions/node/v22.6.0/bin/node]
 8: 0x14eb1b0 v8::internal::PagedSpaceBase::TryExpand(v8::internal::LocalHeap*, v8::internal::AllocationOrigin) [/root/.nvm/versions/node/v22.6.0/bin/node]
 9: 0x149a323 v8::internal::PagedSpaceAllocatorPolicy::RefillLab(int, v8::internal::AllocationOrigin) [/root/.nvm/versions/node/v22.6.0/bin/node]
10: 0x14984eb v8::internal::MainAllocator::AllocateRawSlow(int, v8::internal::AllocationAlignment, v8::internal::AllocationOrigin) [/root/.nvm/versions/node/v22.6.0/bin/node]
11: 0x14377e6 v8::internal::Factory::CodeBuilder::AllocateUninitializedInstructionStream(bool) [/root/.nvm/versions/node/v22.6.0/bin/node]
12: 0x144f419 v8::internal::Factory::CodeBuilder::BuildInternal(bool) [/root/.nvm/versions/node/v22.6.0/bin/node]
13: 0x19c5eb2 v8::internal::baseline::BaselineCompiler::Build(v8::internal::LocalIsolate*) [/root/.nvm/versions/node/v22.6.0/bin/node]
14: 0x1291dfa v8::internal::GenerateBaselineCode(v8::internal::Isolate*, v8::internal::Handle<v8::internal::SharedFunctionInfo>) [/root/.nvm/versions/node/v22.6.0/bin/node]
15: 0x12ef40b v8::internal::Compiler::CompileSharedWithBaseline(v8::internal::Isolate*, v8::internal::Handle<v8::internal::SharedFunctionInfo>, v8::internal::Compiler::ClearExceptionFlag, v8::internal::IsCompiledScope*) [/root/.nvm/versions/node/v22.6.0/bin/node]
16: 0x12ef6b2 v8::internal::Compiler::CompileBaseline(v8::internal::Isolate*, v8::internal::Handle<v8::internal::JSFunction>, v8::internal::Compiler::ClearExceptionFlag, v8::internal::IsCompiledScope*) [/root/.nvm/versions/node/v22.6.0/bin/node]
17: 0x19c334b v8::internal::baseline::BaselineBatchCompiler::CompileBatch(v8::internal::Handle<v8::internal::JSFunction>) [/root/.nvm/versions/node/v22.6.0/bin/node]
18: 0x13dda9f v8::internal::TieringManager::OnInterruptTick(v8::internal::Handle<v8::internal::JSFunction>, v8::internal::CodeKind) [/root/.nvm/versions/node/v22.6.0/bin/node]
19: 0x18971fb  [/root/.nvm/versions/node/v22.6.0/bin/node]
20: 0x1898e44 v8::internal::Runtime_BytecodeBudgetInterruptWithStackCheck_Ignition(int, unsigned long*, v8::internal::Isolate*) [/root/.nvm/versions/node/v22.6.0/bin/node]
21: 0x1f50576  [/root/.nvm/versions/node/v22.6.0/bin/node]

```

### Steps to reproduce the behavior

- Setup a template and ruleset, then redirect the line (in my case using filter `if $fromhost-ip == '127.0.0.1' and $msg startswith ' test-alan' then)`  to the app using omprog, like this:
```
    if $fromhost-ip == '127.0.0.1' and $msg startswith ' test-alan' then {
        action(type="omprog" binary="/root/.nvm/versions/node/v22.6.0/bin/node /opt/testapp/app.js --stdin" template="vpn2fa" output="/var/log/myfolder/test-alan.log")
    }
```

- Simulate a log line using netcat `echo "127.0.0.1 whatever,here test-alan: 123 Hello World 456" | nc -u -w1 127.0.0.1 514`

- Catch the crash in the output log file test-alan.log

### Environment
- rsyslog version: **8.2310.0-4.el9**
- platform: **Rocky Linux 9, kernel 5.14.0-427.31.1.el9_4.x86_64**
- Any version of nodejs.

**Comment by rgerhards** [comment]
Keep in mind that the execution environment is pretty different when rsyslog is run as a system process. I would guess that some SELinux or similar restrictions cause the issue - or something like missing environment variables, default PATH and so an.

As a quick test, I would suggest to run rsyslog interactively inside a terminal session. If the process still fails, it is probably easier to debug in that environment. And if it works, you know the problem is rooted in environment differences.

**Comment by alan-netmesh** [comment]
> Keep in mind that the execution environment is pretty different when rsyslog is run as a system process. I would guess that some SELinux or similar restrictions cause the issue - or something like missing environment variables, default PATH and so an.
> 
> As a quick test, I would suggest to run rsyslog interactively inside a terminal session. If the process still fails, it is probably easier to debug in that environment. And if it works, you know the problem is rooted in environment differences.

Hey! Thanks for the quick reply. I'll google up how to run rsyslog interactively then.
SELinux it's disabled, since it was my first thought that could be the culprit. It was quite surprised when it failed on the clean install, since the OG one it's a securized one to meet CIS/NIST standards. 

At this moment I'm trying to replicate it on Ubuntu, in both cases same procedure, clean install with update + bare minimum to work.

Regards,
Alan

**Comment by alan-netmesh** [comment]
Hey @rgerhards sorry to revive an old thread.
I've been back and forth with this, and running rsyslog interactively indeed makes everything work as expected.
Still I don't figure out what differs between Debian and RL9, both clean installs and the last one with SELinux disabled.

A member of nodejs on the parent issue (on their repo) commented this:
`looks like v8 anticipates only ENOMEM (12) as a potential failure from mprotect, and apparently it failed due to some other reason. unfortunately the assertion message did not carry what that error is.`

Could you give me any hint on where or what to look for? I really want to make this to work on RL9 since im way more confortable with RHEL-based systems.

**Comment by rgerhards** [comment]
I would suggest to create a script that outputs the details of the execution environment to an output file. Also include verbose debigging into your script, so that you can see if it starts at all, and how far it progresses. Just the usual things programers do when there is a problem somewhere.

If the script does NOT start at all, a rsyslog debug log could show us potentially more about the root cause in this case (though my educated guess is always permission issues or invalid pathes in this case).

**Comment by davidelang** [comment]
when rsyslog is started by systemd, the environment is very different than when 
you start it as root from the command line (and SELinux and AppArmor just make 
this worse)

since you say the behavior is diffent between Fedora (SELinux) and Ubuntu 
(AppArmor), it could be a different systemd config or the security config.

check the logs for AA/Selinux logs and check for differences in the systemd 
configs.

Beyond that, as Rainer says, the environment variables may be very different.

David Lang

**Comment by rgerhards** [comment]
I have created a list of common causes and debugging techniques. You can follow it. If so, follow it closely :-)

https://www.rsyslog.com/what-to-do-when-an-external-script-does-not-work/
