### ISSUE TITLE
test-suite failures with liblognorm 1.1.2

### ISSUE THREAD

**Issue by mbiebl** [rsyslog/rsyslog#546]
Bug-Debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=800873
Since updating liblognorm to 1.1.2, the rsyslog test suite fails
# FAIL: mmnormalize_variable.sh
# 

[mmnormalize_variable.sh]: basic test for mmnormalize module variable-support
rsyslogd started with pid  29937
starting run 1
Sending file './testsuites/date_time_msg' 1 times.
^M00000001 kb sent
runtime: 0.000
End of tcpflood Run
doing shutdown
imdiag[13500]: mainqueue empty
wait on shutdown
content-check failed
FAIL mmnormalize_variable.sh (exit status: 1)
# FAIL: mmnormalize_tokenized.sh
# 

[mmnormalize_tokenized.sh]: test for mmnormalize tokenized field_type
rsyslogd started with pid  29978
starting run 1
Sending file './testsuites/tokenized_input' 1 times.
^M00000001 kb sent
runtime: 0.000
End of tcpflood Run
doing shutdown
imdiag[13500]: mainqueue empty
wait on shutdown
content-check failed
FAIL mmnormalize_tokenized.sh (exit status: 1)

**Comment by mbiebl** [comment]
Tested with both rsyslog 8.12.0 and 8.13.0

**Comment by rgerhards** [comment]
This is due to a problem with liblognorm that seems to surface under some circumstances. @janmejay and I talked about it a while ago, but we were not yet able to identify the core issue. For the time being, I'll remove these two tests from the rsyslog testbench, because rsyslog really is not at fault here.

**Comment by mbiebl** [comment]
I can reproduce it reliably in an up-to-date sid-chroot. Just let me know if I can run further diagnostics for you.

**Comment by mbiebl** [comment]
Any progress here? Is there any information I can provide?
If you want a reproducer, installing a Debian sid chroot should be simple.

**Comment by janmejay** [comment]
I'll spend some time on this in a few days. Will get a sid VM in aws to
reproduce it. No idea what I'm looking for from failing env yet, I may need
help with some debug-info if I fail to reproduce it.

@Rainer: can you please name the tests one more time?

--
Regards,
Janmejay

PS: Please blame the typos in this mail on my phone's uncivilized soft
keyboard sporting it's not-so-smart-assist technology.

**Comment by alorbach** [comment]
@janmejay the tests are 
mmnormalize_variable.sh and mmnormalize_tokenized.sh

**Comment by janmejay** [comment]
Thanks Andre.

On Thu, Oct 29, 2015 at 1:34 PM, alorbach <notifications@github.com> wrote:

> @janmejay <https://github.com/janmejay> the tests are
> mmnormalize_variable.sh and mmnormalize_tokenized.sh
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rsyslog/rsyslog/issues/546#issuecomment-152107400>.
>



-- 
Regards,
Janmejay
http://codehunk.wordpress.com

**Comment by janmejay** [comment]
https://github.com/rsyslog/rsyslog/pull/627

It was the same newline-missing-in-the-end bug. Enabled the tests again.

**Comment by rgerhards** [comment]
This seems to be fixed. Please let us know if problems persist.
