### ISSUE TITLE
TLS configuration set off error

### ISSUE THREAD

**Issue by baduq** [rsyslog/rsyslog#5483]
Hello,

I am having this issue trying to set up TLS. I am testing this on only a few TCP connections not all. Just for the Linux593. How can I fix the error. I do not see any typos in it. Any help would be greatly appreciated. Thanks!

The configuration I have below
### Steps to reproduce the behavior
$umask 0000

#Netstream drivers operates in TLS-only mode, making gtls driver the default and set certificate file
global(
DefaultNetstreamDriver="gtls"
DefaultNetstreamDriverCAFile="/etc/pki/tls/certs/CA.pem"
DefaultNetstreamDriverCertFile="/etc/pki/tls/certs/H1.pem"
DefaultNetstreamDriverKeyFile="/etc/pki/tls/certs/H1.key.pem"
)

module(load="imtcp")
module(load="imudp")
module(load="lmnsd_gtls")

input(type="imudp" port="514" ruleset="syslog514")
input(type="imtcp" port="1521" ruleset="asa1521")
input(type="imtcp" port="591" ruleset="juniper591")
input(type="imtcp" port="592" ruleset="windows592")
input(type="imtcp" port="593" ruleset="linux593" StreamDriver="gtls" StreamDriverMode="1" StreamDriverAuthMode="anon")
input(type="imtcp" port="5591" ruleset="citrixtest5591")

template (name="temp_syslog" type="string" string="/var/log/splunk/syslog/%fromhost-ip%/%$year%/%$month%/%$day%.log")
template (name="temp_asa" type="string" string="/var/log/splunk/asa/%fromhost-ip%/%$year%/%$month%/%$day%.log")
template (name="temp_juniper" type="string" string="/var/log/splunk/juniper/%fromhost-ip%/%$year%/%$month%/%$day%.log")
template (name="temp_windows" type="string" string="/var/log/splunk/windows/%fromhost-ip%/%$year%/%$month%/%$day%.log")
template (name="temp_linux" type="string" string="/var/log/splunk/linux/%fromhost-ip%/%$year%/%$month%/%$day%.log")
template (name="temp_citrixtest" type="string" string="/var/log/splunk/citrixtest/%fromhost-ip%/%$year%/%$month%/%$day%.log")

ruleset(name="syslog514"){
    if $fromhost-ip == ['10.62.64.113','10.72.64.108','10.52.64.118'] then {
        action(type="omfile" dirCreateMode="0755" FileCreateMode="0644" dynaFile="temp_rsa")
        stop
    }
    if $fromhost-ip == [<IPs>] then {
        action(type="omfile" dirCreateMode="0755" FileCreateMode="0644" dynaFile="temp_voip")
        stop
    }
    action(type="omfile" dirCreateMode="0755" FileCreateMode="0644" dynaFile="temp_syslog")
    stop
}

ruleset(name="asa1521"){
    if $fromhost-ip == [<IPs>] then {
        stop
    }
    action(type="omfile" dirCreateMode="0755" FileCreateMode="0644" dynaFile="temp_asa")
    stop
}

ruleset(name="juniper591"){
    if $fromhost-ip == [<IPs>] then {
        stop
    }
    action(type="omfile" dirCreateMode="0755" FileCreateMode="0644" dynaFile="temp_juniper")
    stop
}

ruleset(name="windows592"){
    if $fromhost-ip == [<IPs>] then {
        stop
    }
    action(type="omfile" dirCreateMode="0755" FileCreateMode="0644" dynaFile="temp_windows")
    stop
}

ruleset(name="linux593"){
    if $fromhost-ip == [<IPs>] then {
        stop
    }
    action(type="omfile" dirCreateMode="0755" FileCreateMode="0644" dynaFile="temp_linux")
    stop
}

I get this error message below when i check the syntax 
 
#Errors I am getting

rsyslogd: version 8.2102.0-15.el8, config validation run (level 1), master config /etc/rsyslog.conf
rsyslogd: error during parsing file /etc/rsyslog.d/splunk.conf, on or before line 56: parameter 'StreamDriverAuthMode' not known -- typo in config file? [v8.2102.0-15.el8 try https://www.rsyslog.com/e/2207 ]
rsyslogd: error during parsing file /etc/rsyslog.d/splunk.conf, on or before line 56: parameter 'StreamDriverMode' not known -- typo in config file? [v8.2102.0-15.el8 try https://www.rsyslog.com/e/2207 ]
rsyslogd: error during parsing file /etc/rsyslog.d/splunk.conf, on or before line 56: parameter 'StreamDriver' not known -- typo in config file? [v8.2102.0-15.el8 try https://www.rsyslog.com/e/2207 ]

### Environment

rsyslogd  8.2102.0-15.el8 (aka 2021.02) compiled with:
        PLATFORM:                               x86_64-redhat-linux-gnu
        PLATFORM (lsb_release -d):
        FEATURE_REGEXP:                         Yes
        GSSAPI Kerberos 5 support:              Yes
        FEATURE_DEBUG (debug build, slow code): No
        32bit Atomic operations supported:      Yes
        64bit Atomic operations supported:      Yes
        memory allocator:                       system default
        Runtime Instrumentation (slow code):    No
        uuid support:                           Yes
        systemd support:                        Yes
        Config file:                            /etc/rsyslog.conf
        PID file:                               /var/run/rsyslogd.pid
        Number of Bits in RainerScript integers: 64

**Comment by alorbach** [comment]
Please see the rsyslog doc, the parameter names have dots after StreamDriver:
https://www.rsyslog.com/doc/configuration/modules/imtcp.html#id4

**Comment by baduq** [comment]
Thank you @alorbach, but I am trying to encrypt only Linux and logs on port 593, but when I add this line "input(type="imtcp" port="593" ruleset="linux593" StreamDriver="gtls" StreamDriverMode="1" StreamDriverAuthMode="anon")" I get error message even if I put the dot after StreamDriver. eg StreamDriver.Mode="1" and StreamDriver.AuthMode="anon". I still get the error. However, when I do not put  SteamDrive's in inputs I do not get an error. This way its global to all TCP traffic, but I only need to encrypt Linux traffic on port 593.

**Comment by rgerhards** [comment]
your version is too old. you need at least 8.2108.0 from August 2021.

**Comment by baduq** [comment]
Thank you for pointing that out @rgerhards
