### ISSUE TITLE
nsd_ptcp.c excessive logging

### ISSUE THREAD

**Issue by yannickwellens** [rsyslog/rsyslog#5485]
sockClose(int *pSock)
{
	fprintf(stderr, "nsd_ptcp: closing socket %d\n", *pSock);
	if(*pSock >= 0) {
		close(*pSock);
		*pSock = -1;
	}
}

I believe this needs to be a logging function and not fprintf directly to stderr. No way to disable the messages now and during operating this floods stderr.

**Comment by rgerhards** [comment]
Thx for reporting, this is indeed a bug (maybe a left-over from debugging, I'll check)-
