### ISSUE TITLE
Outchannel action-on-max-size gets permission denied

### ISSUE THREAD

**Issue by ghost** [rsyslog/rsyslog#5487]
### Expected behavior / Actual behavior
I was originally experimenting with outchannels [that would fire a command when syslog reached a certain size](https://www.rsyslog.com/doc/configuration/output_channels.html). I would get a `exec: Permission denied` error no matter how I changed permissions to various executables/files that are in the process of the logrotation I have setup.

I then decided to dumb down my implementation and try something simpler to isolate the issue and remove my custom log rotation scripts completely out of the picture. I ended up running `echo test` in place of the **action-on-max-size** in an rsyslog config file and receive the following error:

```
Nov 09 17:55:30 ping.devenv.local systemd[1]: Starting rsyslog.service - System Logging Service...
Nov 09 17:55:30 ping.devenv.local systemd[1]: Started rsyslog.service - System Logging Service.
Nov 09 17:55:30 ping.devenv.local rsyslogd[3308]: imuxsock: Acquired UNIX socket '/run/systemd/journal/syslog' (fd 3) from systemd.  [v8.2312.0]
Nov 09 17:55:30 ping.devenv.local rsyslogd[3308]: rsyslogd's groupid changed to 102
Nov 09 17:55:30 ping.devenv.local rsyslogd[3308]: rsyslogd's userid changed to 102
Nov 09 17:55:30 ping.devenv.local rsyslogd[3308]: [origin software="rsyslogd" swVersion="8.2312.0" x-pid="3308" x-info="https://www.rsyslog.com"] start
Nov 09 17:55:30 ping.devenv.local rsyslogd[3312]: exec: Permission denied
Nov 09 17:55:30 ping.devenv.local rsyslogd[3312]: exec program was 'echo' with param 'test'
Nov 09 17:55:30 ping.devenv.local rsyslogd[3308]: rsyslogd: file size limit cmd for file '/var/log/syslog' did no resolve situation  [v8.2312.0]
Nov 09 17:55:30 ping.devenv.local rsyslogd[3308]: child process (pid 3312) exited with status 1 [v8.2312.0]
Nov 09 17:55:30 ping.devenv.local rsyslogd[3308]: file size limit cmd for file '/var/log/syslog' did no resolve situation  [v8.2312.0]
```

### Environment
- rsyslog version: 8.2312.0
- platform: Ubuntu 24.04

File `50-default.conf`

```
$outchannel sizedsyslog,/var/log/syslog,31457000,echo test 
auth,authpriv.*                 -/var/log/auth.log
*.*;auth,authpriv.none          :omfile:$sizedsyslog
#cron.*                         /var/log/cron.log
#daemon.*                       -/var/log/daemon.log
kern.*                          -/var/log/kern.log
#lpr.*                          -/var/log/lpr.log
mail.*                          -/var/log/mail.log
#user.*                         -/var/log/user.log

#
# Logging for the mail system.  Split it up so that
# it is easy to write scripts to parse these files.
#
#mail.info                      -/var/log/mail.info
#mail.warn                      -/var/log/mail.warn
mail.err                        /var/log/mail.err

#
# Some "catch-all" log files.
#
#*.=debug;\
#       auth,authpriv.none;\
#       news.none;mail.none     -/var/log/debug
#*.=info;*.=notice;*.=warn;\
#       auth,authpriv.none;\
#       cron,daemon.none;\
#       mail,news.none          -/var/log/messages

#
# Emergencies are sent to everybody logged in.
#
*.emerg                         :omusrmsg:*

#
# I like to have messages displayed on the console, but only on a virtual
# console I usually leave idle.
#
#daemon,mail.*;\
#       news.=crit;news.=err;news.=notice;\
#       *.=debug;*.=info;\
#       *.=notice;*.=warn       /dev/tty8

**Comment by davidelang** [comment]
you need to give the full path for the program. Especially when running under 
systemd, you may not have the path (and permissions for that matter) that you 
think you have. AppArmor on Ubuntu (and SELinux on redhat) may also limit you in 
ways that don't show up in the normal unix permissions.

David Lang

**Comment by davidelang** [comment]
cob-web-corner wrote:

> Ingeneral I have checked the `syslog` user has access to all files/binaries required by manually running the steps outside of the rsyslog process

When a process is started by systemd, it does not have the same environment and 
permissions that it has if you run it manually.

try starting rsyslog with the same config as root and see if you get the same 
error.

you can try running strace to see exactly what it's trying to do when the OS is 
rejecting the request.

David Lang
