### ISSUE TITLE
All logs are duplicated when I enable rsyslog locally or send them to a remote server

### ISSUE THREAD

**Issue by Benoit34590** [rsyslog/rsyslog#5504]
### Expected behavior
Log lines are sent to a folder/file on the server and eventually to a remote server.

### Actual behavior
Log lines are sent successfully but appear duplicated. In the folder:
/data/LOG/testrsyslog/systemd-logind.log

Nov 26 14:21:56 testrsyslog1 systemd-logind[821]: Session 605719 logged out. Waiting for processes to exit.
Nov 26 14:21:56 testrsyslog1 systemd-logind[821]: Session 605719 logged out. Waiting for processes to exit.
Nov 26 14:21:56 testrsyslog1 systemd-logind[821]: Removed session 605719.
Nov 26 14:21:56 testrsyslog1 systemd-logind[821]: Removed session 605719.
Nov 26 14:22:07 testrsyslog1 systemd-logind[821]: New session 605721 of user centreon.
Nov 26 14:22:07 testrsyslog1 systemd-logind[821]: New session 605721 of user centreon.
Nov 26 14:22:08 testrsyslog1 systemd-logind[821]: Session 605721 logged out. Waiting for processes to exit.
Nov 26 14:22:08 testrsyslog1 systemd-logind[821]: Session 605721 logged out. Waiting for processes to exit.
Nov 26 14:22:08 testrsyslog1 systemd-logind[821]: Removed session 605721.
Nov 26 14:22:08 testrsyslog1 systemd-logind[821]: Removed session 605721.

### Steps to reproduce the behavior
Install Ubuntu 22 server
Add the following lines to the /etc/rsyslog.conf file:

$template RemoteLogs, "/data/LOG/%HOSTNAME%/%PROGRAMNAME%.log"
*.* ?RemoteLogs

Restart the service.

Notice that the log lines are duplicated in /data/LOG/testrsyslog/sshd.log for example.
If the logs come from a remote rsyslog client, I experience the exact same issue.

### Environment
- rsyslogd  8.2112.0 (aka 2021.12) compiled with:
        PLATFORM:                               x86_64-pc-linux-gnu
        PLATFORM (lsb_release -d):
        FEATURE_REGEXP:                         Yes
        GSSAPI Kerberos 5 support:              Yes
        FEATURE_DEBUG (debug build, slow code): No
        32bit Atomic operations supported:      Yes
        64bit Atomic operations supported:      Yes
        memory allocator:                       system default
        Runtime Instrumentation (slow code):    No
        uuid support:                           Yes
        systemd support:                        Yes
        Config file:                            /etc/rsyslog.conf
        PID file:                               /run/rsyslogd.pid
        Number of Bits in RainerScript integers: 64

- platform: Ubuntu 22.04 server

**Comment by Benoit34590** [comment]
hi, 

Here is the consolidated file. Thanks

```shell


$ModLoad imuxsock # provides support for local system logging

$ActionFileDefaultTemplate RSYSLOG_TraditionalFileFormat

$RepeatedMsgReduction on

#
# Set the default permissions for all log files.
#
$FileOwner syslog
$FileGroup adm
$FileCreateMode 0640
$DirCreateMode 0755
$Umask 0022
$PrivDropToUser syslog
$PrivDropToGroup syslog

#
# Where to place spool files
#
$WorkDirectory /var/spool/rsyslog

#
# Include all config files in /etc/rsyslog.d/
#
$IncludeConfig /etc/rsyslog.d/*.conf/etc/rsyslog.d/*.conf
##### BEGIN CONFIG: /etc/rsyslog.d/1-forward-logs.conf (put on stack)
# Définition d'un template pour formater les logs
$template RemoteForwarder,"<%PRI%>%TIMESTAMP% %HOSTNAME% %syslogtag%%msg%\n"

# Envoi des logs au premier serveur avec le module omfwd
*.* @@10.99.251.8:50514;RemoteForwarder

# Redirection vers un second serveur en cas d'échec
$ActionExecOnlyWhenPreviousIsSuspended on
& @@10.99.251.6:50514;RemoteForwarder

# Stockage local des logs
$ActionExecOnlyWhenPreviousIsSuspended on
& /var/log/localbuffer

# Désactiver la suspension après la redirection
$ActionExecOnlyWhenPreviousIsSuspended off
```

**Comment by rgerhards** [comment]
This is strange. Is there a second instance of rsyslog running?

On the config, I wonder why rsyslog is writing to the file in first place, it should only do so if no server is available.

We could try a debug log, if there is only one instance, we would see why it creates duplicate entries. 

To do so, see instructions: https://www.rsyslog.com/doc/v8-stable/troubleshooting/howtodebug.html

**Be sure that the problem in question occurs at least once during the debug run**. Once this is done, please post the debug log (e.g. via pastebin or github). After that, we can review the contents and check how exactly rsyslog processing worked.

**Comment by Benoit34590** [comment]
Hi, 
[rsyslog.debug.log](https://github.com/user-attachments/files/17931905/rsyslog.debug.log)
and thank you for your interest in my issue. Here is the debug file.

**Comment by rgerhards** [comment]
Do you still see duplicates? I wonder because the debug log shows that no duplicates are being written. I have excerpted one relevant part from the debug log below (IP address changed, just so that you know). As you can see, only the first action is executed. I have also searched for the message in question side the debug log. It was only present one, that means once processed.

Might it indeed be that there is some other instance of (any) logger on that system?

Excerpt:
```
8027.732561432:main Q:Reg/w0  : main Q: queue.c: dequeued 1 discarded 0 consumable elements, szlog 0 sz phys 1
8027.732570232:main Q:Reg/w0  : ruleset.c: processBATCH: batch of 1 elements must be processed
8027.732576432:main Q:Reg/w0  : ruleset.c: processBATCH: next msg 0: <38>Nov 27 09:00:27 sshd[1894605]: Accepted publickey for centreon from 10.0.1.1 port 47038 ssh2: RSA SHA256:DGWJbCfU/UzDV
8027.732583032:main Q:Reg/w0  : rainerscript.c:     ACTION 0 [builtin:omfwd:@@10.99.251.8:50514;RemoteForwarder]
8027.732599032:main Q:Reg/w0  : ruleset.c: executing action 0
8027.732606232:main Q:Reg/w0  : ../action.c: action 'action-0-builtin:omfwd': called, logging to builtin:omfwd (susp 0/0, direct q 1)
8027.732617932:main Q:Reg/w0  : ../action.c: action 'action-0-builtin:omfwd': is transactional - executing in commit phase
8027.732624031:main Q:Reg/w0  : ../action.c: actionPrepare[action-0-builtin:omfwd]: enter
8027.732629131:main Q:Reg/w0  : ../action.c: actionTryResume: enter
8027.732634331:main Q:Reg/w0  : ../action.c: actionPrepare[action-0-builtin:omfwd]: after calling actionTryResume
8027.732640131:main Q:Reg/w0  : ../action.c: checking external state file
8027.732645231:main Q:Reg/w0  : ../action.c: done checking external state file, iRet=0
8027.732651031:main Q:Reg/w0  : omfwd.c: omfwd: beginTransaction
8027.732667431:main Q:Reg/w0  : omfwd.c: poolTryResume: oneTargetOK 1, iRet 0
8027.732673531:main Q:Reg/w0  : ../action.c: action[action-0-builtin:omfwd] transitioned to state: itx
8027.732678931:main Q:Reg/w0  : ../action.c: action 'action-0-builtin:omfwd': set suspended state to 0
8027.732683631:main Q:Reg/w0  : rainerscript.c:     ACTION 1 [builtin:omfwd:@@10.99.251.6:50514;RemoteForwarder]
8027.732698231:main Q:Reg/w0  : ruleset.c: executing action 1
8027.732704231:main Q:Reg/w0  : ../action.c: action 'action-1-builtin:omfwd': called, logging to builtin:omfwd (susp 1/0, direct q 1)
8027.732710231:main Q:Reg/w0  : ../action.c: action 'action-1-builtin:omfwd': NOT executing, as previous action was not suspended
8027.732715830:main Q:Reg/w0  : rainerscript.c:     ACTION 2 [builtin:omfile:/var/log/localbuffer]
8027.732730730:main Q:Reg/w0  : ruleset.c: executing action 2
8027.732737330:main Q:Reg/w0  : ../action.c: action 'action-2-builtin:omfile': called, logging to builtin:omfile (susp 1/0, direct q 1)
8027.732742730:main Q:Reg/w0  : ../action.c: action 'action-2-builtin:omfile': NOT executing, as previous action was not suspended
8027.732748030:main Q:Reg/w0  : ruleset.c: END batch execution phase, entering to commit phase [processed 1 of 1 messages]
8027.732753630:main Q:Reg/w0  : ../action.c: actionCommitAllDirect: action 0, state 1, nbr to commit 1 isTransactional 1
8027.732759030:main Q:Reg/w0  : ../action.c: actionCommit[action-0-builtin:omfwd]: enter, 1 msgs
8027.732763830:main Q:Reg/w0  : ../action.c: actionCommit[action-0-builtin:omfwd]: processing...
8027.732768730:main Q:Reg/w0  : ../action.c: actionTryCommit[action-0-builtin:omfwd] enter
8027.732773330:main Q:Reg/w0  : ../action.c: actionPrepare[action-0-builtin:omfwd]: enter
8027.732777730:main Q:Reg/w0  : ../action.c: actionTryResume: enter
8027.732782330:main Q:Reg/w0  : ../action.c: actionPrepare[action-0-builtin:omfwd]: after calling actionTryResume
8027.732787030:main Q:Reg/w0  : ../action.c: doTransaction[action-0-builtin:omfwd] enter
8027.732792130:main Q:Reg/w0  : ../action.c: doTransaction: have commitTransaction IF, using that, pWrkrInfo 0x55b96369ff80
8027.732797530:main Q:Reg/w0  : ../action.c: entering actionCallCommitTransaction[action-0-builtin:omfwd], state: itx, nMsgs 1
8027.732802629:main Q:Reg/w0  : omfwd.c: poolTryResume: oneTargetOK 1, iRet 0
8027.732808729:main Q:Reg/w0  : omfwd.c: pool 10.99.251.8:50514/tcp
8027.732814429:main Q:Reg/w0  : omfwd.c: load balancer: trying actualTarget 0 [7]: try 0, isConnected 1, wrkr 0x7fe9cc000d30
8027.732819329:main Q:Reg/w0  : omfwd.c: RGER: sending to actualTarget 0: try 0
8027.732826429:main Q:Reg/w0  : omfwd.c: omfwd: add 173 bytes to send buffer (curr offs 0, max len 16384) msg: <38>Nov 27 09:00:27 SERVER01 sshd[1894605]: Accepted publickey for centreon from 10.163.111.181 port 47038 ssh2: RSA SHA256:DGWJbCfU/UzDVSNIbioutsou01PUjIKrVBzFF023LNI

8027.732853029:main Q:Reg/w0  : omfwd.c: omfwd: TCP sent 173 bytes, requested 173
8027.732858829:main Q:Reg/w0  : ../action.c: actionCallCommitTransaction[action-0-builtin:omfwd] state: itx mod commitTransaction returned 0
8027.732864329:main Q:Reg/w0  : ../action.c: action[action-0-builtin:omfwd] transitioned to state: rdy
8027.732869629:main Q:Reg/w0  : ../action.c: actionCommit[action-0-builtin:omfwd]: return actionTryCommit 0
8027.732874729:main Q:Reg/w0  : ../action.c: actionCommit[action-0-builtin:omfwd]: done, iRet 0
8027.732879929:main Q:Reg/w0  : ruleset.c: processBATCH: batch of 1 elements has been processed
8027.732885829:main Q:Reg/w0  : queue.c: regular consumer finished, iret=0, szlog 0 sz phys 1
8027.732891529:main Q:Reg/w0  : queue.c: DeleteProcessedBatch: etry 0 state 3
8027.732896528:main Q:Reg/w0  : queue.c: DeleteProcessedBatch: we deleted 1 objects and enqueued 0 objects
8027.732901028:main Q:Reg/w0  : queue.c: rger: deleteBatchFromQStore, nElem 1
8027.732905928:main Q:Reg/w0  : queue.c: doDeleteBatch: delete batch from store, new sizes: log 0, phys 0
8027.732911228:main Q:Reg/w0  : main Q: queue.c: dequeued 0 discarded 0 consumable elements, szlog 0 sz phys 0
```

**Comment by Benoit34590** [comment]
Alright, the files and configurations I uploaded here are from the client side (I was convinced it was the client sending the data twice). I performed debugging on the server by disabling all .conf files, and the duplicates are gone. I’ll refine my approach and identify the one causing the issue.

**Comment by Benoit34590** [comment]
So on the server, I listen on TCP with this file: 10-imudp-entry.conf
and I listen on UDP with this file: 10-imtcp-entry.conf.
Both files used the same template, so the data was processed twice.
Once the UDP configuration file was removed, the duplicates stopped.

Thanks for the help and for pointing me in the right direction.  😊
