### ISSUE TITLE
provide a config option to not escape tabs

### ISSUE THREAD

**Issue by davidelang** [rsyslog/rsyslog#552]
the conversion of tab characters to #011 catches a lot of people by surprise, it would be very handy to continue to have other control characters escaped, but not touch tabs

**Comment by rgerhards** [comment]
It would probably be best to have a table for the 32 possible control chars 0x01-0x1f, 0x7f and permitting control of each of them.

**Comment by davidelang** [comment]
that would be nice to have, it makes it possible to do the hard, odd things. But we don't want to make it hard to do the easy, common things.

If it wasn't for backwards compatibility, I'd argue for making not escaping tabs the default (and if/when we have a 9.0 I may push for such a change then :-)

So if it's simple enough to change the default set of characters to escape to remove the tab and have it be a table, fine. But if it's too ugly, a separate setting would be better (backwards compatibility is going to require keeping the existing config flags a lot longer)

Thinking out loud, it the internals changed to be a table and existing config options modified that table, then something like

modify_escaping("allow","\t")

could be simple enough.

I guess this approach may take this out of the "small" category though :-)

**Comment by rgerhards** [comment]
I don't think it's getting more complex. You need a new config variable in any case, so its more the matter if that variable is a scalar vs. an array.

**Comment by samriang** [comment]
Hi good people,
As I see there is no any out of the box solution for not escaping tabs.
So does the way to not escape tabs even exist?

**Comment by samriang** [comment]
After all I set 
`$EscapeControlCharactersOnReceive off`
Is it safe if I am only dealing with sending nginx logs to kafka through unix socket?

**Comment by davidelang** [comment]
Just a note that some parser modules can force escaping

We really do need a way to skip escaping tabs, but we want to avoid an explosion 
of such options.

The escaping doesn't care what input the message arrives through.

David Lang

**Comment by JPvRiel** [comment]
I tried this and it seemed to work.

```
global(
  parser.escapecontrolcharactertab="off"
)
```
I think the main issue now is that this is not documented anywhere as far as I can tell. E.g. http://rsyslog-doc.readthedocs.io/en/stable/search.html?q=escapecontrolcharactertab&check_keywords=yes&area=default.

I had to dig in the source code to find it. I noticed `parser.escapecontrolcharactertab` is in `runtime/glbl.c`. Also `parser.escapecontrolcharactersonreceive`.

The setting `parser.escapecontrolcharactertab`, sets this:
```
static int bEscapeTab = 1; /* escape tab control character when doing CC escapes: 0 - no, 1 - yes */
```

Also to note, `escape-cc` is available as a property replacer, but again seems to be an all or none escape.

> Is it safe if I am only dealing with sending nginx logs to kafka through unix socket?

A local unix socket (not exposed on network) and known source should be fine to just disable all escaping. 

But when running as a central log server on a network, `$EscapeControlCharactersOnReceive off` is probably a bad idea. From experience seeing another product based on syslog-ng that didn't escape non printable characters, a mess resulted in downstream log processing that expected syslog data to read in text mode and some binary data that snuck in broke things.

**Comment by webash** [comment]
Bah. This is a painful thing to stumble upon in 2018 while my logs fill with "#011" in the place of tab characters. Can someone link me to some valid advice on what to do in the meantime should I want tabs to be saved to disk in the logs, and if I want them forwarded as tab characters, not "#011"?

**Comment by JPvRiel** [comment]
@webdash, did you try this?

> I tried this and it seemed to work.
> 
> ```
> global(
>   parser.escapecontrolcharactertab="off"
> )
> ```

Both files saved to disk and forwarded events should then have tabs, not `#11`

**Comment by rgerhards** [comment]
The `parser.escapecontrolcharactertab` seem to have been introduced by a contribution roughly 5 years ago:

https://github.com/rsyslog/rsyslog/commit/80edcd575b837e4e9871754d9bf194fd1c464676

I guess it was never documented and there also does not seem to exist a CI test for it. Looks like we need to do a bit of cleanup here.

For those complaining: if we do not properly escape tab (' #011'), existing parser scripts may get into big trouble, as this is the traditional (and often expected) behavior. That doesn't mean, of course, that the option should be undocumented ;-)
