### ISSUE TITLE
Rsyslog RPM repository TLS certificate has expired

### ISSUE THREAD

**Issue by davejbax** [rsyslog/rsyslog#5525]
### Expected behavior

Installing Rsyslog on [RHEL](https://www.rsyslog.com/rhelcentos-rpms/) from the Adiscon RPM repository over TLS should work

### Actual behavior

Attempting to install Rsyslog with `dnf` from `https://rpms.adiscon.com/v8-stable/rhel-$releasever/$basearch` produces a 'certificate has expired' error.

The certificate appears to have expired yesterday:

```
$ openssl s_client -connect rpms.adiscon.com:443
Certificate chain
 0 s:CN = rpms.adiscon.com
   i:C = US, O = Let's Encrypt, CN = R11
   a:PKEY: rsaEncryption, 2048 (bit); sigalg: RSA-SHA256
   v:NotBefore: Sep 30 00:57:20 2024 GMT; NotAfter: Dec 29 00:57:19 2024 GMT
 1 s:CN = rpms.adiscon.com
   i:C = US, O = Let's Encrypt, CN = R11
   a:PKEY: rsaEncryption, 2048 (bit); sigalg: RSA-SHA256
   v:NotBefore: Sep 30 00:57:20 2024 GMT; NotAfter: Dec 29 00:57:19 2024 GMT
 2 s:C = US, O = Let's Encrypt, CN = R11
   i:C = US, O = Internet Security Research Group, CN = ISRG Root X1
   a:PKEY: rsaEncryption, 2048 (bit); sigalg: RSA-SHA256
   v:NotBefore: Mar 13 00:00:00 2024 GMT; NotAfter: Mar 12 23:59:59 2027 GMT
```

### Steps to reproduce the behavior

1. Add the following to `/etc/yum.repos.d/rsyslog.repo`:
```
[rsyslog_v8]
name=Adiscon RHEL-$releasever - local packages for $basearch
baseurl=https://rpms.adiscon.com/v8-stable/rhel-$releasever/$basearch
enabled=1
gpgcheck=0
gpgkey=https://rpms.adiscon.com/RPM-GPG-KEY-Adiscon
protect=1
```

2. Run `dnf install rsyslog`

### Environment
- rsyslog version: 8 
- platform: RHEL

**Comment by alorbach** [comment]
Thanks for reporting, the problem should be fixed now. There was an issue with the automatic TLS Certificate update because we moved the rpm server 3 months ago.
