### ISSUE TITLE
imfile tag has max length ?

### ISSUE THREAD

**Issue by tuxknight** [rsyslog/rsyslog#553]
I use  tag to identify my application file as follows:
```
aliyun:madai:loadbalance:nginx:10.1.1.2:8080
```
But it seems that tag has a max length. 
I got
```
aliyun:madai:loadbalance:nginx:10
```
in tag field in remote rsyslog server.

Rsyslog Version is 5.8.10 
CentOS 6.5

**Comment by rgerhards** [comment]
The syslog RFCs limit tags to 32 characters. By default, rsyslog obeys this restriction. You can craft a custom template to remove the limit, but need to know that when you do, you violate the RFCs. I suggest to contact the rsyslog mailing list for further instructions if needed, as the bug tracker is not a good place for tech support (far fewer people are following here).
