### ISSUE TITLE
imptcp: forwarding by relp caused message to be lost

### ISSUE THREAD

**Issue by alorbach** [rsyslog/rsyslog#560]
When receiving syslog messages by imptcp, and forwarding them with omrelp, the messages are not send proberly to the remote system. 

Only invalid syslog headers are send like this: 
Oct 22 02:17:28 ubuntu.fritz.box  <invld>2015-10-22T02:17:28.296671-07:00 ubuntu.fritz.box  
Oct 22 02:17:28 ubuntu.fritz.box  <invld>2015-10-22T02:17:28.296671-07:00 ubuntu.fritz.box  
Oct 22 02:17:28 ubuntu.fritz.box  <invld>2015-10-22T02:17:28.296671-07:00 ubuntu.fritz.box  
Oct 22 02:17:28 ubuntu.fritz.box  <invld>2015-10-22T02:17:28.296671-07:00 ubuntu.fritz.box  
Oct 22 02:17:28 ubuntu.fritz.box  <invld>2015-10-22T02:17:28.296671-07:00 ubuntu.fritz.box  

But it should be this: 
Mar  1 01:00:00 172.20.245.8 tag msgnum:00000000:
Mar  1 01:00:00 172.20.245.8 tag msgnum:00000001:
Mar  1 01:00:00 172.20.245.8 tag msgnum:00000002:
Mar  1 01:00:00 172.20.245.8 tag msgnum:00000003:
Mar  1 01:00:00 172.20.245.8 tag msgnum:00000004:

**Comment by rgerhards** [comment]
Is maybe the default template used by omrelp wrong? In that it uses the file format where forwarding format is required? Just guessing...

**Comment by alorbach** [comment]
Maybe, but when I just switch imptcp with imtcp, the format returns to be just fine. 
Needs to be investigated later I think.

**Comment by alorbach** [comment]
Actually my build environment did not build imptcp, so my rsyslog loaded the system installed one and not the build one. This caused the problem, so this issue is invalid.
