### ISSUE TITLE
KSI: add tool to extract subset of records from log file and keep that verifiable

### ISSUE THREAD

**Issue by rgerhards** [rsyslog/rsyslog#561]
Base this on method described in academic feature. Root use case is the desire to hand over set of relevant records e.g. to authorities without disclosing unnecessary information but yet keep everything verifiable.

**Comment by alorbach** [comment]
More details on the implementation (will be integrated into rsgtutil)

- one file as input parameter
- one file as outout parameter
- extract parameter which understands a list of line numbers and ranges of line
numbers 
sample: --extract "10-22,45,60-71"

- append parameter which lets the tool append to the extraction file. 
sample: --extract "10-22,45,60-71" --append
