### ISSUE TITLE
imfile: rsyslog crashes after log file is deleted and a same name but different inode file created

### ISSUE THREAD

**Issue by zacharyzhao** [rsyslog/rsyslog#565]
Rsyslog: v8.13-0
Platform: CentOS 6.5
Kernel: 2.6.32-358.el6.x86_64

Problem:

```
Rsyslog will crash under such circumstances:

    A log file of about 2 GB is deleted, then a same name but different inode log file moved there, the new file's size is about 1.5 GB.
    Rsyslog read the new file for some minutes, then crashes.


    Backtrace information from core file:
```
#0  0x00000000004384cf in strmReadBuf ()
#1  0x00000000004387fb in strmReadChar ()
#2  0x0000000000438f2c in strmReadMultiLine ()
#3  0x00007fa00bb69846 in pollFile (pLstn=0x7fa0040043e0, pbHadFileData=0x0) at imfile.c:591
#4  0x00007fa00bb6caee in in_handleFileEvent (ev=0x7fa00bb63d80, etry=0x7fa004006600) at imfile.c:1717
#5  0x00007fa00bb6ce01 in in_processEvent (ev=0x7fa00bb63d80) at imfile.c:1778
#6  0x00007fa00bb6cf68 in do_inotify () at imfile.c:1813
#7  0x00007fa00bb6d037 in runInput (pThrd=0xb89ff0) at imfile.c:1845
#8  0x0000000000454a1c in thrdStarter ()
#9  0x00007fa00cf7d851 in start_thread () from /lib64/libpthread.so.0
#10 0x00007fa00c8bf94d in clone () from /lib64/libc.so.6

**Comment by alorbach** [comment]
Can you attach a minimal working configuration for reproducing this issue?

**Comment by Jecht** [comment]
* 00-template.conf
```
template(name="format_json" type="list") {
    constant(value="{\"host\":\"")
    property(name="hostname")
    constant(value="\"")

    constant(value=",\"ip\":\"")
    constant(value="0.0.0.0")
    constant(value="\"")

    constant(value=",\"app-name\":\"")
    property(name="app-name" caseConversion="lower")
    constant(value="\"")

    constant(value=",\"file\":\"")
    property(name="$!metadata!filename")
    constant(value="\"")

    constant(value=",\"msg\":\"")
    property(name="msg" format="json")
    constant(value="\"")

    constant(value=",\"time\":\"")
    property(name="timestamp" dateFormat="rfc3339")
    constant(value="\"")

    constant(value="}")
}
```

* 10-input-imfile.conf
```
module(load="imfile" mode="inotify")
```

* 11-foo.conf
```
module(load="builtin:omfile")

action(type="omfile" file="/tmp/output.log" flushInterval="1")

input(type="imfile"
      addmetadata="on"
      tag="myapp"
      readmode="2"
      escapelf="off"
      file="/tmp/input.log"
)
```

    It seems that rsyslog will crash after I delete the log file it was reading, and the new 'same name but different inode' log file's size grows faster than rsyslog's reading speed. Copying a big file there is just an extreme case.

**Comment by mostolog** [comment]
Just made the following test with 8.22+, and I'm not able to reproduce the crash:

app.log is 2.7MB in 12100 lines. Should I try a bigger one?
```
input(type="imfile" file="/app.log" tag="mytag" addMetadata="on" ruleset="json" startmsg.regex="^[[:digit:]]{2} [[:alpha:]]{3} [[:digit:]]{4}" PersistStateInterval="1")

(wait rsyslog to end processing file)

cp /app2.log /app.log
```

I also tried cp "while reading file", and doesn't see any crash, but:
```
[New Thread 0x7ffff4cac700 (LWP 22108)]
[New Thread 0x7ffff48ab700 (LWP 22109)]
[New Thread 0x7fffeffff700 (LWP 22110)]
[New Thread 0x7fffef3dc700 (LWP 22111)]
[New Thread 0x7fffeebdb700 (LWP 22112)]
[Thread 0x7fffef3dc700 (LWP 22111) exited]
[New Thread 0x7fffef3dc700 (LWP 22113)]
[Thread 0x7fffef3dc700 (LWP 22113) exited]
[New Thread 0x7fffef3dc700 (LWP 22114)]
[Thread 0x7fffef3dc700 (LWP 22114) exited]
[Thread 0x7fffeebdb700 (LWP 22112) exited]
```

**Comment by alorbach** [comment]
Can this issue be closed?

**Comment by zacharyzhao** [comment]
Yeap, it should be closed.
