### ISSUE TITLE
queue: Message can get lost after action is resumed. 

### ISSUE THREAD

**Issue by alorbach** [rsyslog/rsyslog#571]
When sending messages by omrelp, and the server stops and returns, 1 message is always lost when the action is resumed. 

Sample what happens when action resume happens: 

3287.614995867:main Q:Reg/w0  : sendbuf NOT added to unacked list
3287.615036600:main Q:Reg/w0  : resending frame '403 syslog 64 <167>2015-03-01T01:00:00-07:00 172.20.245.8 tag msgnum:00000401:
'
3287.615103710:main Q:Reg/w0  : sendbuf NOT added to unacked list
3287.615147410:main Q:Reg/w0  : after TryReestablish, sess state 4
3287.615362648:main Q:Reg/w0  : actionDoRetry: omrelp action->tryResume returned 0
3287.615693978:main Q:Reg/w0  : actionDoRetry: omrelp had success RDY again (iRet=0)
3287.616549730:main Q:Reg/w0  : Called LogMsg, msg: action 'omrelp' resumed (module 'omrelp')
3287.617773899:main Q:Reg/w0  : main Q: qqueueAdd: entry added, size now log 1471, phys 1727 entries
3287.617847331:main Q:Reg/w0  : main Q: EnqueueMsg advised worker start
3287.618798705:main Q:Reg/w0  : Action 1 transitioned to state: rdy
3287.619336508:main Q:Reg/w0  : omrelp: beginTransaction
3287.619415724:main Q:Reg/w0  : Action 1 transitioned to state: itx
3287.619489099:main Q:Reg/w0  : omrelp: shutdownImmediate ptr now is 0x60bf180
3287.619565093:main Q:Reg/w0  : entering actionCalldoAction(), state: itx, actionNbr 1
3287.619617161:main Q:Reg/w0  :  172.21.0.142:21514/RELP
3287.619669508:main Q:Reg/w0  : relpSessWaitState returns 0
3287.619731770:main Q:Reg/w0  : frame to send: '130 syslog 64 <167>2015-03-01T01:00:00-07:00 172.20.245.8 tag msgnum:00000403:
'
3287.619797715:main Q:Reg/w0  : Warning: exceeding window size, max 129, curr 128
3287.619846655:main Q:Reg/w0  : ADD sess 0x619e750 unacked 129, sessState 5
3287.619903776:main Q:Reg/w0  : sendbuf added to unacked list
3287.620183241:main Q:Reg/w0  : Called LogMsg, msg: action 'omrelp' resumed (module 'omrelp')

This problem is also known in omfwd when using TCP, and a setting called "ResendLastMSGOnReconnect" was added to workaround the problem. Perhaps it is/was the same problem?!

**Comment by alorbach** [comment]
This commit is a partitial solutions to the problem: 
https://github.com/rsyslog/librelp/commit/df184d235f7ab51da913fafea238abe4e26f6a67

However the problem goes much deeper as initially thought.

**Comment by rgerhards** [comment]
fixed via #773
