### ISSUE TITLE
rainerscript: Invalid read of size 4 when field() function does not find a match

### ISSUE THREAD

**Issue by alorbach** [rsyslog/rsyslog#582]
Config: 
$IncludeConfig diag-common.conf

module(load="../plugins/imtcp/.libs/imtcp")
input(type="imtcp" port="13514")

template(name="outfmt" type="string" string="%$!%\n")

set $!tree!here!nbr = field($msg, 58, 2); # Delimiter = :
action(type="omfile" file="rsyslog.out.log" template="outfmt")

stackdump:

==58738== Thread 8 rs:main Q:Reg:
==58738== Invalid read of size 4
==58738==    at 0x46D3A0: doFuncCall (rainerscript.c:1751)
==58738==    by 0x46AA87: cnfexprEval (rainerscript.c:2388)
==58738==    by 0x444960: scriptExec (ruleset.c:218)
==58738==    by 0x44502B: processBatch (ruleset.c:509)
==58738==    by 0x4564C7: msgConsumer (rsyslogd.c:575)
==58738==    by 0x43FDF2: ConsumerReg (queue.c:1898)
==58738==    by 0x43A256: wtiWorker (wti.c:334)
==58738==    by 0x437F45: wtpWorker (wtp.c:389)
==58738==    by 0x5058181: start_thread (pthread_create.c:312)
==58738==    by 0x5D8847C: clone (clone.S:111)
==58738==  Address 0x6198f18 is 24 bytes inside a block of size 26 alloc'd
==58738==    at 0x4C2AB80: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==58738==    by 0x46D53A: doFuncCall (rainerscript.c:1317)
==58738==    by 0x46AA87: cnfexprEval (rainerscript.c:2388)
==58738==    by 0x444960: scriptExec (ruleset.c:218)
==58738==    by 0x44502B: processBatch (ruleset.c:509)
==58738==    by 0x4564C7: msgConsumer (rsyslogd.c:575)
==58738==    by 0x43FDF2: ConsumerReg (queue.c:1898)
==58738==    by 0x43A256: wtiWorker (wti.c:334)
==58738==    by 0x437F45: wtpWorker (wtp.c:389)
==58738==    by 0x5058181: start_thread (pthread_create.c:312)
==58738==    by 0x5D8847C: clone (clone.S:111)
==58738==

**Comment by janmejay** [comment]
Yep, this is the issue. Its fixed in the PR now.

But title is inaccurate. Even if it finds match, valgrind still complains. Its because it doesn't like how strlen reads 4 bytes at a time. 

The allocation now uses multiple of 4-bytes when valgrind switch is enabled.

**Comment by rgerhards** [comment]
fixed via #614, which is now merged.
