### ISSUE TITLE
Discard if message is too long

### ISSUE THREAD

**Issue by friedl** [rsyslog/rsyslog#584]
It sometimes happens that if a message is too long, imtcp will not be able to properly get the end of the message and thus producing 
a) framing errors
b) parse the rest of the message as a new message, thus filling properties with invalid values.

You could now increase the MaxMessageSize of course, but it would probably be good to be able to just discard the excess message part and go on with proper processing. 

This could be done via a new configuration operator.

Opinions?

**Comment by davidelang** [comment]
it's a hard question to answer. Do you want to throw away data or accept it and have the data show up somewhere, even if misparsed?

I don't think the existing behaviour should be eliminated, but I could see a switch to enable this. If/when we restructure the input/output module code to allow easier stacking of features, this would be something to add at that time.

**Comment by mostolog** [comment]
Related https://github.com/rsyslog/rsyslog/issues/498

**Comment by rgerhards** [comment]
This has been implemented in the past couple of months. 8.30 definitely has it.
