### ISSUE TITLE
KSI Signature in wrong container

### ISSUE THREAD

**Issue by vii5ard** [rsyslog/rsyslog#587]
The KSI signature must be in a TLV container with tag 0905 and RFC3161 in 0906. At the moment both of them are encaspulated in a TLV with tag 0906.

**Comment by rgerhards** [comment]
Do you think it is sufficient to fix this or must we think about a conversion utility?

**Comment by vii5ard** [comment]
I think it is ok just to fix the problem for now as there are no actual users atm.

**Comment by alorbach** [comment]
I have to look deeper into this. Currently I see only one position where TLV with TAG 0x906 is written (RFC 3161).
