### ISSUE TITLE
rsyslogd doesn't work inside container

### ISSUE THREAD

**Issue by iamzhout** [rsyslog/rsyslog#594]
I am using rsyslog with imfile and omfwd to monitor file changes and send log changes via tcp to other endpoint,
in ubuntu vm, it does work great; but have no luck when I tried to make rsyslog work inside a container.
I have tried docker images with ubuntu:latest, ubuntu:vivid, ubuntu:wily, all doesn't work.

the configuration file is as below:

```
# Load Modules
global(workDirectory="/var/log")
module(load="imfile" PollingInterval="1")

# components' log from file
input(type="imfile"
         File="/var/log/fwd_test.log"
         Tag=""
         ruleset="fwd_rule")
      
# components' log  Template  
template(name="fwd_template" type="list") {
    property(name="msg")
    constant(value="    ")
    constant(value="\n")
}

# components' log  RuleSets
ruleset(name="fwd_rule") {
    action(type="omfwd" Target="172.16.1.2" Port="5140" Protocol="tcp" template="fwd_template")
}
```

**Comment by iamzhout** [comment]
I have enabled rsyslog debug log, and noticed below message inside it, not sure if it means *omfwd* module has problem inside container?

```
4905.886344430:7fae2640c780: tried selector action for builtin:omfwd: -2001
```

**Comment by mostolog** [comment]
I have been able to run rsyslog inside containers with no issues. Probably you are having network issues.
Do you still have problems or can we close this?

**Comment by mostolog** [comment]
@rgerhards IMHO, you can close this safely.
