### ISSUE TITLE
Enhancement for imjournal - use SYSLOG_PID, then fall back to _PID

### ISSUE THREAD

**Issue by portante** [rsyslog/rsyslog#607]
By default, `imjournal` will pull the systemd user property, `SYSLOG_PID`, value for the `pid` message property.  If the `SYSLOG_PID` property does not exist, the `pid` message property ends up not being defined.

Can we consider having `imjournal` fallback to the `_PID` property if `SYSLOG_PID` is not found?

**Comment by radosroka** [comment]
I'll try to make a PR. There is a problem with "usepidfromsystem" option because it has binary value. I suggest that we should have one option e.g. "usepid" with three states like "system", "syslog" and "both"(default). In Ideal situation we should depricate "usepidfromsystem".

**Comment by rgerhards** [comment]
> I suggest that we should have one option e.g. "usepid" with three states like "system", "syslog" and "both"(default). In Ideal situation we should depricate "usepidfromsystem".

I think this approach makes sense. We should probably support the depricated ```usepidfromsystem``` if only it is given. This keeps old configs working.

**Comment by radosroka** [comment]
> I think this approach makes sense. We should probably support the depricated usepidfromsystem if only it is given. This keeps old configs working.

I agree.

**Comment by rgerhards** [comment]
done via #1591
