### ISSUE TITLE
Compiling rsyslog with --enable-omzmq3 gives compilation error 

### ISSUE THREAD

**Issue by naviens** [rsyslog/rsyslog#62]
Version Tested :  7.4.10,7.4.4,7.4.9,7.6.0,7.6.1,8.2.0
ZMQ version:  4.0.4, 3.2.4

Stack Trace : 

omzmq3.c:247:9: error: void value not ignored as it ought to be
         if(-1 == zsocket_connect(pData->socket, (char*)pData->description)) {
         ^
make[2]: *** [omzmq3_la-omzmq3.lo] Error 1
make[2]: Leaving directory `/home/naveen/Downloads/rsyslog-7.6.1/plugins/omzmq3'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/naveen/Downloads/rsyslog-7.6.1'
make: *** [all] Error 2

**Comment by rgerhards** [comment]
closing as we have new 0mq modules
