### ISSUE TITLE
ompgsql - db server port

### ISSUE THREAD

**Issue by dmdm** [rsyslog/rsyslog#648]
Hello,

is it possible to connect to a pgsql server on a non-default port, e.g. to specify the port number on the action line? If I read the C code correctly, this is not implemented yet.

Thank you.

**Comment by rc9000** [comment]
I was also having this issue and it got a different port to work by setting the PGPORT environment, e.g. 

`logserver:~ # PGPORT=5433 /opt/rsyslog/sbin/rsyslogd `

This will be picked up by libpq and bypasses the default port from rsyslog.

**Comment by rgerhards** [comment]
closed via https://github.com/rsyslog/rsyslog/pull/2172
