### ISSUE TITLE
imtcp-tls-basic-vg.sh is currently failing in git master

### ISSUE THREAD

**Issue by Whissi** [rsyslog/rsyslog#688]
Hi,

I am currently testing git master (fa5a6c9f02460548693179d22d07d331f94ef4e5) with valgrind testbench enabled:
```
FAIL: imtcp-tls-basic-vg.sh
===========================

===============================================================================
[imtcp-tls-basic-vg.sh]: testing imtcp in TLS mode - basic test
==43068== Memcheck, a memory error detector
==43068== Copyright (C) 2002-2015, and GNU GPL'd, by Julian Seward et al.
==43068== Using Valgrind-3.11.0 and LibVEX; rerun with -h for copyright info
==43068== Command: ../tools/rsyslogd -C -n -irsyslog.pid -M../runtime/.libs:../.libs -f./testsuites/imtcp-tls-basic.conf
==43068==
rsyslogd started with pid  43068
startup-vg still running
starting run 1
Sending 50000 messages.
^M00050000 messages sent
runtime: 0.013
End of tcpflood Run
imdiag[13500]: mainqueue empty
./diag.sh: line 166: wait: pid 43068 is not a child of this shell
rsyslogd run exited with 127
scanf error in index i=49152
sequence error detected
FAIL imtcp-tls-basic-vg.sh (exit status: 1)
```

I repeated 3 times and the test was always failing.

```
============================================================================
Testsuite summary for rsyslog 8.15.0.master
============================================================================
# TOTAL: 179
# PASS:  173
# SKIP:  5
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
```

**Comment by alorbach** [comment]
Which Linux version are you using? 
II am on Ubuntu 14.04, test is not failing. 
Also no fails on our buildbot as far as I know. 

Perhaps it is a timing issue? I have seen such fails when rsyslog is not finished properly.

**Comment by Whissi** [comment]
This is happening on my Gentoo build cluster.

Looks like you are correct regarding a timing issue. Inspired by your recent commit d782c9108b4b37d2 I added `sleep 10` after the the *tcpflood* command which seems to be a working workaround.

But that's a bad hack, isn't it? :)
Any idea how we can improve this? I am thinking about a solution like *nginx's* *WINCH* reaction: I.e. after *tcpflood* you would send a signal to *rsyslog* which will tell *rsyslog* to stop accepting new input and to gracefully end (which means finishing everything in queue). This would allow us just to `wait` until *rsyslog* process ends and proceeding would be safe.

**Comment by rgerhards** [comment]
Well, of course it would be nice to have such a functionality for shutdown. But given the fact it only is useful for the testbench and there are so many other things to do, I think it takes a PR from someone else to make it happen.

**Comment by rgerhards** [comment]
@Whissi do you still see this failure? We've had some changes to related components, and I don't see this failure anywhere on the build farm for a while. So I would think it is fixed, but I have not complete confirmation.

**Comment by Whissi** [comment]
Yes, I am still hitting this.

To workaround I applied patches like described in https://github.com/rsyslog/rsyslog/issues/688#issuecomment-163327707, see

- https://gitweb.gentoo.org/repo/gentoo.git/tree/app-admin/rsyslog/files/8-stable/50-rsyslog-8.15.0-imtcp-tls-basic-vg-test-workaround.patch
- https://gitweb.gentoo.org/repo/gentoo.git/tree/app-admin/rsyslog/files/8-stable/50-rsyslog-8.15.0-imfile-readmode2-vg-test-workaround.patch

Never hit a failure with 10s wait period yet.

**Comment by rgerhards** [comment]
I'll try to reproduce this if I can get up an Gentoo instance in our build farm, and address the issue afterwords. I hope to be able to see it, too, which would definitely help in tracing what's going on. I'll move it to the next release goal, as I think you have a work-around. Alternatively, I can apply your patch immediately (experimentally) if you prefer so.

**Comment by rgerhards** [comment]
lol, and now I mis-read your message ;-) I think I have a release candidate tarball by monday. Or should I mail you one (maybe not RC) privately?

**Comment by rgerhards** [comment]
anyways, I think let's not pressure ourselves. I'll move the release target. Still let's see if we can find out next week.

**Comment by rgerhards** [comment]
this is most probably caused by #882. I have traced this down to afterRun() not being called, because the input thread has already terminated.

**Comment by rgerhards** [comment]
side-note: I could reproduce it on the Fedora 64 bit machine in the buildbot environment, thus I am able to work on it.

**Comment by rgerhards** [comment]
with the #882 fix in place, the test still occasionally fails, but with a sequence error. The root cause here most probably is that imdiag has a race in detection when workload ends, and in turn the test framework too early terminates rsyslog. Investigating.
