### ISSUE TITLE
omelasticsearch v8.14.0-6 stalls rsyslog

### ISSUE THREAD

**Issue by jnovack** [rsyslog/rsyslog#698]
I'm having an issue with logging on CentosOS 7 with rsyslog-elasticsearch 8.14.0-6, two separate instances.  Works fine with 8.14.0-1, same config. Running "rsyslog -n" and using the debug options, everything appears to work fine, however running via systemd does not (no extra options in `/etc/systemd/rsyslog`).

Tried ES/Kibana 1.latest and 2.latest, no change. Works under 8.14.0-1, does not work under 8.14.0-6.

I am pulling packages from //rpms.adiscon.com/v8-stable/

The issue is that nothing gets logged. nothing to disk, nothing to elasticsearch. no "starting syslog" message, nothing, 0 bytes.  Completely working under 8.14.0-1.  Broken under 8.14.0-6.  Multiple reboots, always the same.

**Comment by portante** [comment]
Does that package have the "imjournal" plugin, and do you have it enabled in your configuration file?

**Comment by jnovack** [comment]
I have `$ModLoad imjournal # provides access to the systemd journal` within my /etc/rsyslog.conf

**Comment by jnovack** [comment]
https://gist.github.com/jnovack/0f2643acfec4ab21665f

These are basic configs, nothing fancy.

**Comment by portante** [comment]
@jnovack, can you show the rsyslog is actually processing the messages by using the ES template you have?  For example, can you put this line before the omelasticsearch action in elasticsearch.conf, https://gist.github.com/jnovack/0f2643acfec4ab21665f#file-rsyslog-d-elasticsearch-conf-L30:
```
*.* /var/log/rsyslog-debug.log;plain-syslog
```
We should be able to see if any messages are flowing through rsyslog.

Also, are you using UTC on the server sending the messages?  Could there be a timezone skew?

**Comment by jnovack** [comment]
@portante I appreciate you helping.

Line 29 of elasticsearch.conf now has `*.* /var/log/rsyslog-debug.log;plain-syslog`.
Line 41 of elasticsearch.conf now is `action.resumeretrycount="0"`

Upon reboot, it is blank.  Clearing out `/var/log/messages` before reboot, all I see is the "Stopping" commands, and finally:

    rsyslogd: [origin software="rsyslogd" swVersion="8.14.0" x-pid="2607" x-info="http://www.rsyslog.com"] exiting on signal 15.

This brings me to my facepalm moment.  rsyslog and elasticsearch are on the same machine. Clearly, rsyslog is trying to send to elasticsearch, which may not be up yet. However, shouldn't `action.resumeretrycount="-1"` take care of this? IF SO, there has to be state somewhere, that may be clogged or incorrect.

So, at this point, I delete `/var/log/messages` (to clean it), and `systemctl restart rsyslog`, and messages FLOOD into `messages` and `rsyslog-debug.log`.  Here's the bad news. None of these messages actually make it to elasticsearch.  `omelasticsearch.log` is empty.

If I change `action.resumetrycount="-1"`, my logger gets stuck again, logging nothing to nowhere. If I change `action.resumeretrycount="0"`, my logger sends to disk, but not to elasticsearch (despite it being up).  However, when I swap to "-1", then "0", very old messages flood the queue, making me think a statefile is broken somewhere.

**Comment by jnovack** [comment]
This error is showing up in the logs when I `systemctl restart rsyslog` adding more credence to some statefile being bad.  Again, any `systemctl restart rsyslog` prints all the messages in the backlog queue, and not being cleared, resulting in duplicate messages.

    Dec 13 11:27:02 elasticsearch systemd: Socket service syslog.service not loaded, refusing.
    Dec 13 11:27:02 elasticsearch systemd: Failed to listen on Syslog Socket.

**Comment by rgerhards** [comment]
At least as far as the project-supported verision (8.16.0 as of this writing) is concerned, everything seems to be fixed. So I am closing. Feel free to re-open if some problems still persist.

**Comment by AgilDat** [comment]
I'm having the same issue with Centos 7.

Latest from [v8 repo](http://rpms.adiscon.com/v8-stable/rsyslog.repo):
```bash
$ rpm -qa |grep rsyslog
rsyslog-mmjsonparse-8.24.0-1.el7.x86_64
rsyslog-8.24.0-1.el7.x86_64
rsyslog-elasticsearch-8.24.0-1.el7.x86_64
```
**Fail**
Service running with systemd (all default):
```
5650.351742349:main Q:Reg/w0  : omelasticsearch: checkConn(http://192.168.15.11:9200/) failed on attempt 0: Couldn't connect to server
5650.351747825:main Q:Reg/w0  : omelasticsearch: checkConn() failed after 1 attempts.
5650.351751771:main Q:Reg/w0  : Action 0 transitioned to state: rtry
5650.351754021:main Q:Reg/w0  : actionCommit, action 0, in retry loop, iRet -2007
5650.351756309:main Q:Reg/w0  : actionDoRetry: action 0 enter loop, iRetries=0, ResumeInRow 1
5650.351758440:main Q:Reg/w0  : omelasticsearch: tryResume called
5650.351795635:main Q:Reg/w0  : omelasticsearch: checkConn(http://192.168.15.11:9200/) failed on attempt 0: Couldn't connect to server
5650.351799046:main Q:Reg/w0  : omelasticsearch: checkConn() failed after 1 attempts.
5650.351801331:main Q:Reg/w0  : actionDoRetry: action 0 action->tryResume returned -2007
5650.351803601:main Q:Reg/w0  : actionDoRetry: action 0 check for max retries, iResumeRetryCount -1, iRetries 0
```


**Working**
Running as root `/sbin/rsyslogd -n` :
```
6506.972061945:main Q:Reg/w0  : omelasticsearch: checkConn(http://192.168.15.11:9200/) completed with success on attempt 0
6506.972083849:main Q:Reg/w0  : omelasticsearch: using REST URL: 'http://192.168.15.11:9200/_bulk'
6506.984914852:main Q:Reg/w0  : omelasticsearch: pWrkrData replyLen = '364'
6506.984940092:main Q:Reg/w0  : omelasticsearch: pWrkrData reply: '{"took":12,"errors":false,"items":[{"create":{"_index":"logstash-2017.01.13","_type":"events","_id":"AVmXj-Tcm6o_oqeYXQ8Z","_version":1,"_shards":{"total":1,"successful":1,"failed":0},"status":201}},{"create":{"_index":"logstash-2017.01.13","_type":"events","_id":"AVmXj-Tcm6o_oqeYXQ8a","_version":1,"_shards":{"total":1,"successful":1,"failed":0},"status":201}}]}'
6506.984997884:main Q:Reg/w0  : omelasticsearch: Entire request (null)
6506.985016001:main Q:Reg/w0  : omelasticsearch: 2 items in reply
6506.985024814:main Q:Reg/w0  : Action 0 transitioned to state: rdy
6506.985029792:main Q:Reg/w0  : actionCommit, action 0, in retry loop, iRet 0
6506.985035321:main Q:Reg/w0  : actionCommitAllDirect: action 1, state 1, nbr to commit 0 isTransactional 1
6506.985040781:main Q:Reg/w0  : doTransaction: have commitTransaction IF, using that, pWrkrInfo 0x7f962bbab760
6506.985045396:main Q:Reg/w0  : entering actionCallCommitTransaction(), state: itx, actionNbr 1, nMsgs 2
6506.985137380:main Q:Reg/w0  : file stream messages params: flush interval 0, async write 0
6506.985160425:main Q:Reg/w0  : omfile: write to stream, pData->pStrm 0x7f9614014b70, lenBuf 148, strt data Jan 13 11:21:07 node01 rsyslogd: [origin software="rsyslogd" swVersion="8.24.0" x-pid="14142" x-info="http://www.rsyslog.com"] e
6506.985178935:main Q:Reg/w0  : omfile: write to stream, pData->pStrm 0x7f9614014b70, lenBuf 133, strt data Jan 13 11:21:46 node01 rsyslogd: [origin software="rsyslogd" swVersion="8.24.0" x-pid="14202" x-info="http://www.rsyslog.com"] s
6506.985190275:main Q:Reg/w0  : strm 0x7f9614014b70: strmFlushinternal: file -1(messages) flush, buflen 281

```

I don't know if this could help:
# Environ
As systemd service:
```
LANG=en_US.UTF-8PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/binNOTIFY_SOCKET=/run/systemd/notify
```
As root script:
```
XDG_SESSION_ID=6HOSTNAME=node01SHELL=/bin/bashTERM=xtermHISTSIZE=1000USER=rootLS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=01;05;37;41:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=01;36:*.au=01;36:*.flac=01;36:*.mid=01;36:*.midi=01;36:*.mka=01;36:*.mp3=01;36:*.mpc=01;36:*.ogg=01;36:*.ra=01;36:*.wav=01;36:*.axa=01;36:*.oga=01;36:*.spx=01;36:*.xspf=01;36:SUDO_USER=vagrantSUDO_UID=1000USERNAME=rootPATH=/sbin:/bin:/usr/sbin:/usr/binMAIL=/var/spool/mail/vagrantPWD=/home/vagrantLANG=es_ES.UTF-8SHLVL=1SUDO_COMMAND=/bin/suHOME=/rootLOGNAME=rootLC_CTYPE=es_ES.UTF-8LESSOPEN=||/usr/bin/lesspipe.sh %sSUDO_GID=1000_=/sbin/rsyslogd
```

**Comment by pjurkowski** [comment]
Issues on Centos 7 might be connected with selinux.

I had the same issue on version:
rsyslog-elasticsearch-8.25.0-1.el7.x86_64
rsyslog-8.25.0-1.el7.x86_64

If You have selinux enabled, try to disable it (run _setenforce 0_) and restart rsyslog. 
If it helps it means You have to add a selinux exception. By default only port 514 is enabled for this service.

```
yum install policycoreutils-python
semanage port -a -t syslogd_port_t -p tcp 9200 
```

**Comment by JasonChen86899** [comment]
systemctl -l status rsyslog To see the log of ryslog: 
setroubleshoot: SELinux is preventing /usr/sbin/rsyslogd from name_connect access on the tcp_socket port 9200.
Run below to resolve
- yum install policycoreutils-python
- semanage port -a -t syslogd_port_t -p tcp 9200
