### ISSUE TITLE
Memory leak in when using liblognorm and imfile

### ISSUE THREAD

**Issue by hakman** [rsyslog/rsyslog#709]
Lately I noticed that Rsyslog has an increased memory usage as time passes. After some debugging and a long exchange of emails, all signs seem to point a memory leak in the imfile module:
http://lists.adiscon.net/pipermail/rsyslog/2015-December/041669.html

The following link contains the Rsyslog config and Valgrind output with both inotify and polling modes.
https://gist.github.com/hakman/44afddaf4eb67cda28c6

**Comment by davidelang** [comment]
config showing the problem was posted by hakman at https://gist.github.com/hakman/44afddaf4eb67cda28c6

**Comment by hakman** [comment]
Hi guys, any progress in this area? We are getting a lot of trouble because of this memory leak and we need imfile for parsing multiline logs. Thanks!

**Comment by otisg** [comment]
Yeah, rsyslog memory grows and OOM Killer gets it. Regularly. :(

**Comment by rgerhards** [comment]
From what I see, this is a leak in liblognorm's json handling. This strongly smells like another incarnation of https://github.com/rsyslog/rsyslog/issues/717. If so, it should go away with 8.17.0. In any case, this should be tried next.

**Comment by hakman** [comment]
I upgraded Rsylog to 8.17 and left it running for 4 days on a few servers. I see the RES memory at 1187M now, so this is not fixed.

To me it looked like the Valgrind output points to imfile mostly.

**Comment by rgerhards** [comment]
Well, if you look at the **large** chunks in valgrind output, they point to liblognorm and msgDestruct. Which is exactly what libfastjson fixes. I've only seen very small losses with imfile.

Anyhow, as it seems not to be fixed. Can you please get me some valgrind output from the new version.

**Comment by rgerhards** [comment]
I just got an additional idea: could you provide me with an input file for imfile which exposes the memlak and which I can put into rsyslog's public repo? If so, I could add a testbench test for it and that would probably not only help in this case (it's way easier to fix if I can reproduce in my lab) but also guard against similar problems in the future. Please let me know.

**Comment by hakman** [comment]
I created a new Gist with the Valgrind output. Seems different to me:
https://gist.github.com/hakman/4a070e5dec4480dad379

Not sure if one of our log files would help. I can only reproduce this with our production env. Probably related to some timings and some errors rsyslog is receiving.

**Comment by rgerhards** [comment]
Can you please add

global(debug.unloadModules="off")

To rsyslog.conf and re-run the test. This gives us more information (the
question marks will be filled).

Thanks, Rainer

Sent from phone, thus brief.
Am 28.03.2016 21:35 schrieb "Ciprian Hacman" <notifications@github.com>:

**Comment by hakman** [comment]
I think this looks better:
https://gist.github.com/hakman/5e78fa3482f43d712cd6

Thanks for taking a look at this!

**Comment by rgerhards** [comment]
Yeah, it's definitely unrelated to imfile. The main culprit seems to be
mmnormalize. Maybe omelasticsearch also has a leak. Could you use
liblognorm v2, at least for a test?

Sent from phone, thus brief.
Am 28.03.2016 22:50 schrieb "Ciprian Hacman" <notifications@github.com>:

**Comment by hakman** [comment]
The memory leak seems much smaller with liblognorm v2. I enabled this on some production servers also to see if there is any change. Will have to monitor them to see how this works after 2-3 days of log shipping.
https://gist.github.com/hakman/868b88fe17220de5659a

**Comment by rgerhards** [comment]
I forgot to mention: could you also add 

```version=2```

to the top of your rulebase. This will actually activate the new code. It depends on your rule base if you can that. Usually you can, but there are some constructs not directly supported:

https://github.com/rsyslog/liblognorm/blob/master/compatibility-v2

From what I see in the gist, the memleak still exists. That's not so much a surprise, as the v1 compatibility handling is actually done by the old code (the new one is totally different).

Would it be possible to contribute rulebase and a sample log file that exposes the problem? If so, I could add this to a testbench test ... which would also help to speed up a solutions as I could reproduce it in my lab.

**Comment by hakman** [comment]
I used version=2 for my latest test and worked nicely with our rulebase. Did not change anything else.
The rulebase we use is:
```
version=2
prefix=%date:date-iso% %time:time-24hr%
rule=java:,%msec:number% %severity:alpha% [%thread:string-to:\x5d\x20%] %class:word% - %msg:rest%
rule=jetty:.%msec:number%:%severity:alpha%:%thread:char-sep::%:%class:char-sep::%: %msg:rest%
```

I will have to check with @otisg if and how we can provide a log file sample.

**Comment by rgerhards** [comment]
great! could you get me a valgrind run with the new rule base.

side-note: for that run, I guess you can leave out --leak-check=full, as what we are after are large leaks, not config vars that are not deallocated upon termination. but... with it is the safe bet ;)

**Comment by hakman** [comment]
The last gist I provided was run with that ruleset.
I tried running it without --leak-check=full and the output looks like this:
```
==11242== HEAP SUMMARY:
==11242==     in use at exit: 495,973,213 bytes in 100,029 blocks
==11242==   total heap usage: 12,395,250 allocs, 12,295,221 frees, 13,204,416,325 bytes allocated
==11242== 
==11242== LEAK SUMMARY:
==11242==    definitely lost: 322,736 bytes in 96,551 blocks
==11242==    indirectly lost: 486,501,949 bytes in 3,124 blocks
==11242==      possibly lost: 9,072,000 bytes in 58 blocks
==11242==    still reachable: 76,528 bytes in 296 blocks
==11242==         suppressed: 0 bytes in 0 blocks
==11242== Rerun with --leak-check=full to see details of leaked memory
```

**Comment by rgerhards** [comment]
You mean this gist: https://gist.github.com/hakman/868b88fe17220de5659a

If so, are you sure it included the "version=2" line? I ask because I see from the called functions that version 1 code is being used.

On without --leak-check=full: that's interesting. It looks like all memory is being pointed to by an active data structure. Could it be that the queue was not properly emptied at shutdown (due to timeouts, for example?).

**Comment by hakman** [comment]
I think you are right. I thought liblognorm2 was the one shipped with Rsyslog and just had to use set version=2. Is there a simple way to use it, or I have to build it from sources?

Not sure about timeout, but could be possible.

**Comment by rgerhards** [comment]
2016-03-29 12:32 GMT+02:00 Ciprian Hacman <notifications@github.com>:

> I think you are right. I thought liblognorm2 was the one shipped with
> Rsyslog and just had to use set version=2. Is there a simple way to use it,
> or I have to build it from sources?
>

Depends. It is included in the Ubuntu daily build packages. Otherwise you
need to build from source. But...

> Not sure about timeout, but could be possible.
>
... let's first make sure we are doing a proper test. If these "leaks" are
just the left-over of an expired shutdown timeout, then we are looking at
the wrong thing. I would suggest that you increase the timeout. If you can
reproduce at will, it may also make sense to do the run in debug mode, in
parallel to valgrind, like this:

$ valgrind --log-fd=1 ...valgrind-opts.... rsyslogd -d ...rsyslogd opts...
> combined_log

That enables me to see the actual state of objects when valgrind reports.
This would also be useful for some violations I have seen at the start of
the valgrind logs. They are mostly false positives (some versions of
valgrind are known to have these), but it wouldn't hurt to look at bit more
closely.

Rainer

**Comment by hakman** [comment]
Sorry for not getting back sooner, but I tried a lot of various things config related. My main problem debugging was that ubuntu version of Rsyslog doesn't have debug symbols, or I don't know how to install them.

In the end I tried the dev version and enabled liblognorm v2. The memory usage is stable since this morning, compared to a similar server that already is already over 100M of mem usage.

Will let it run over the weekend and see if liblognorm v2 really helps.
Btw, any hint of when it will be part of the stable build?

**Comment by rgerhards** [comment]
2016-04-07 14:57 GMT+02:00 Ciprian Hacman <notifications@github.com>:

> Sorry for not getting back sooner, but I tried a lot of various things
> config related. My main problem debugging was that ubuntu version of
> Rsyslog doesn't have debug symbols, or I don't know how to install them.
>
> In the end I tried the dev version and enabled liblognorm v2. The memory
> usage is stable since this morning, compared to a similar server that
> already is already over 100M of mem usage.
>
> Will let it run over the weekend and see if liblognorm v2 really helps.
>

Please keep me posted on the progress.


> Btw, any hint of when it will be part of the stable build?
>

I currently assume May, 31st.

Rainer

**Comment by hakman** [comment]
Thanks, for the ETA.
Will keep this open while I try to get to a conclusion.

Any idea if there is any simple way to make debug symbols available in Ubuntu, other than build from sources?

**Comment by rgerhards** [comment]
@alorbach @friedl any ide on the public symbols? Aren't they shipped in our packages by default?

**Comment by hakman** [comment]
My conclusion is that using the dev version fixes the issue. I didn't see any memory usage increase since upgrading.

**Comment by mostolog** [comment]
@hakman any news about this? Do you see any leak with stable/8.22? Do you think this issue could be closed?
I haven't found a rsyslog-debug package on Ubuntu neither, so had to build with _--enable-debug_

**Comment by hakman** [comment]
I don't see any more leaks at the moment. Thanks!
