### ISSUE TITLE
Add a UTC equivalent of $NOW family of system properties

### ISSUE THREAD

**Issue by rgerhards** [rsyslog/rsyslog#729]
This is useful if someone wants to add a normalized timestamp to templates. [request via Adiscon support customer]

**Comment by portante** [comment]
+1

Could we also add a modify to convert a given timestamp field in UTC?

**Comment by rgerhards** [comment]
I would suggest to open a new issue tracker for this. It's unfortunately a pretty complex beast to do.

**Comment by portante** [comment]
Would you do something like, `$NOWUTC`?

**Comment by rgerhards** [comment]
upcoming: https://github.com/rgerhards/rsyslog/commit/4d73026d0f804ae106436334ba84275967a7f656

**Comment by rgerhards** [comment]
We actually need to treat this and #731 separately, unfortunately. The reason is that internally the $NOW family of system properties does not generate a timestamp but rather a string. So we cannot use the usual date modifiers with it, the format is fixed. And, yes, we should probably look at some point into refactoring the timestamp-handling code inside rsyslog...
