### ISSUE TITLE
Add a way to emit timestamps in UTC

### ISSUE THREAD

**Issue by portante** [rsyslog/rsyslog#730]
From #729, could we add a way to specify timestamps be emitted in UTC?  Like we have `date-rfc3339`, we could have `dateutc-rfc3339`.  For example, perhaps we have today:
```
template(name="tgtmpl" type="string" string="%timegenerated:::date-rfc3339%")
```
and the possible enhancement might look like:
```
template(name="tgtmpl" type="string" string="%timegenerated:::dateutc-rfc3339%")
```

**Comment by rgerhards** [comment]
Note: as UTC is requested (and not any unspecified timezone), this is simpler than usual TZ conversion. However, it's still more complicated if we don't know the zone (RFC3164). However, the code currently assumes local TZ in that case, and we could extend that to the new format specification.
