### ISSUE TITLE
Segfaults using type=imfile if File has no leading /

### ISSUE THREAD

**Issue by karl-wiebe-op** [rsyslog/rsyslog#741]
Using both 8.9.0 and 8.15.0, if an input of type imfile has a File= without a leading / (as in the case of a typo), rsyslogd will abort on several Linux distros. The culprit would seem to be https://github.com/rsyslog/rsyslog/blob/master/plugins/imfile/imfile.c#L665 which returns the wrong index, as the presence of a / is assumed. Perhaps a more graceful syntax error would be appropriate?

**Comment by rgerhards** [comment]
fixed via https://github.com/rsyslog/rsyslog/pull/840
