### ISSUE TITLE
Race condition in accessing local hostname and related information

### ISSUE THREAD

**Issue by theinric** [rsyslog/rsyslog#743]
The glbl class contains these variables:

static prop_t _propLocalHostName = NULL;/_ our hostname as FQDN - read-only after startup _/
static uchar *LocalHostName = NULL;/_ our hostname  - read-only after startup, except HUP _/
static uchar *LocalFQDNName = NULL;/_ our hostname as FQDN - read-only after startup, except HUP _/
static uchar *LocalDomain = NULL;/_ our local domain name  - read-only after startup, except HUP */

All these are reset during SIGHUP handling. They can be accessed asynchronously from various modules and there doesn't seem to be any synchronization mechanism.

I've notice this when I was checking the feasibility of implementing an (optional) periodic check for hostname changes. Would such a feature be desirable (assuming a synchronization mechanism is added)?

**Comment by rgerhards** [comment]
I think this feature makes sense. Also adding the enhancement label for that part of the issue.

**Comment by rgerhards** [comment]
most probably solved, need to check

**Comment by rgerhards** [comment]
This is solved, see comment starting at https://github.com/rsyslog/rsyslog/blob/master/runtime/glbl.c#L573
