### ISSUE TITLE
im[p]tcp: add option to truncate oversize message

### ISSUE THREAD

**Issue by rgerhards** [rsyslog/rsyslog#745]
Currenty, the oversize part is treated as a separate message, but that part is malformed. So this causes more trouble in most cases than it is worth.

**Comment by ymattw** [comment]
Do you mean the feature implemented in the pending PR #664 ?

**Comment by rgerhards** [comment]
No, sorry for the confusion. Changed the title. It's in regard to receiving oversize messages via TCP.
