### ISSUE TITLE
switch to libsystemd, drop embedded code copy for sd_notify

### ISSUE THREAD

**Issue by mbiebl** [rsyslog/rsyslog#753]
rsyslog uses the sd_notify API() to signal its readyness when running under systemd.
For that it uses an embedded code copy of that API in runtime/sd-daemon.[ch]

upstream no longer recommends to embed that code but to use libsystemd instead.

**Comment by rgerhards** [comment]
Do you happen to have the necessary configure code ;)  A PR would be even better. If not, no problem, I guess that should even be esay for me ;)

**Comment by rgerhards** [comment]
Done with a recent commit.
