### ISSUE TITLE
Unhelpful error given for some invalid certificates

### ISSUE THREAD

**Issue by ScoreUnder** [rsyslog/rsyslog#781]
I've been trying to set up remote logging with rsyslog+gnutls for the past 2 weeks, so it seemed like a bit of a slap in the face when at some point the error changed to:

> rsyslogd: not permitted to talk to peer, certificate invalid: GnuTLS returned no specific reason

Looking into it, this wasn't true. The list of cases for GnuTLS certificate errors wasn't comprehensive, and I was actually getting `GNUTLS_CERT_SIGNER_CONSTRAINTS_FAILURE`.

I suggest two things:
1. Give the raw error code as well as the reason, and not just in debug mode. Since something has already gone wrong I think it's reasonable to assume that someone will want to start debugging the issue at this point.
2. More comprehensively cover the list of errors as listed [in the GnuTLS documentation](https://www.gnu.org/software/gnutls/reference/gnutls-gnutls.html).

---

By the way, for anyone who gets the above error, ensure that your CA certificate lists "Certificate signing" as its usage when you run `certtool --infile=ca.pem --pubkey-info`. By some miracle of poor return-key dexterity I'd managed to generate my CA certificate without this ability.

**Comment by rgerhards** [comment]
well, the list was conclusive when we implemented that check ... what also means it's not simple to extend it and still be able to compile with older gnutls versions.

As you have looked into this already obviously: do you know how to make gnutls convert an ```enum gnutls_certificate_status_t``` to human-readable text? You mentioned it is done in debug mode, but I don't think so. A quick google search also did not bring up any way to do that (but I may be blind :-)).

Thanks.

**Comment by ScoreUnder** [comment]
Sorry, I wasn't very clear about that. In debug mode, the raw error code is printed, so it's possible to find the error type from the docs.

Looking around, I've found `gnutls_certificate_verification_status_print(3)` (it's in my man pages), and it seems to do the job.

If you don't mind a gigantic screenshot, here's a snippet of the function beside its manpage:
https://i.imgur.com/odFtiSa.png
(As an outsider looking in and not having dealt with gnutls before, this whole "datum" thing seems a bit overcomplicated, but I'm sure you guys have more experience in it than I do)

**Comment by rgerhards** [comment]
Thanks for the function name. This I was looking for and did not find :-)

**Comment by rgerhards** [comment]
@PascalWithopf could you look at this?

**Comment by PascalWithopf** [comment]
closed via https://github.com/rsyslog/rsyslog/pull/1617

**Comment by ScoreUnder** [comment]
Is this really fixed with the referenced issue? It doesn't reference any gnutls APIs in the changes, and seems particular to the case when the file is missing (which is not the case in this bug report).
