### ISSUE TITLE
rsyslog omfwd action resumed but no "suspended" given

### ISSUE THREAD

**Issue by schlitzered** [rsyslog/rsyslog#782]
hey,

i have many action resumed messages in my logs for omfwd (tcp). but how can i find out why they have been suspended in the first place?

**Comment by JonZeolla** [comment]
Have you tried the [rsyslog forums](http://kb.monitorware.com/general-f34.html)?

**Comment by schlitzered** [comment]
i tried to check the documentation, and i found that suspension of outputs should always be reported with rsyslog 8,

but this is not tha case for me, see doc:

http://www.rsyslog.com/doc/v8-stable/rainerscript/global.html?highlight=reportsuspension

**Comment by rgerhards** [comment]
can you provide a debug log that showcases this problem? Please make sure that you use the latest supported version, which is 8.16.0 at the time of this writing.

**Comment by rgerhards** [comment]
I have seen some other reports of similar cases on the rsyslog ML, but all without further details. Probably best to search for RS_RET_SUSPENDED inside omfile.

**Comment by schlitzered** [comment]
Hey,

i will reconfigure some of our servers to create these debug logfiles. i will update the ticket as soon as i hove something for you.

**Comment by rgerhards** [comment]
thanks, that would be most useful. Note that I try to tackle this in 8.18 timeframe. 8.17 release is next Tuesday. So I may begin to work starting Wednesday. Just so that you know.

**Comment by schlitzered** [comment]
hey, the log is quite big & i like to share it via dropbox, i hope you do not mind that i send you the download link via your email address...

**Comment by rgerhards** [comment]
2016-03-09 12:37 GMT+01:00 schlitzered <notifications@github.com>:

> hey, the log is quite big & i like to share it via dropbox, i hope you do
> not mind that i send you the download link via your email address...
>
>
Please do, no problem with that (but I am glad you ask :-)).

Rainer

**Comment by schlitzered** [comment]
You should have mail :-)

**Comment by schlitzered** [comment]
any news on this?

**Comment by splitice** [comment]
I too have been trying to debug this. We upgraded from 8.16 to 8.19.0 and somewhere in the middle our omfwd configuration using compression ceased working (no messages arrive remotely).

The only symptom is action resumed messages without any suspension.

**Comment by splitice** [comment]
Some information from a day of debugging:

1. 8.19 does not correctly handle messages received from 8.16 clients. 8.19 <-> 8.19 appears more reliable although I still need to conduct further testing with this.

2. No message is outputted if the connection is interrupted causing suspension, the only message seen is a message on resumption.

Point 2 is most relevant to this issue.

**Comment by davidelang** [comment]
On Sun, 10 Jul 2016, Mathew Heard wrote:

> Some information from a day of debugging:
>
> 1. 8.19 does not correctly handle messages received from 8.16 clients. 8.19 <-> 8.19 appears more reliable although I still need to conduct further testing with this.

what format are you talking about here? Is this RELP, TCP, UDP, other? can you 
give an example of a message that's not handled properly?

> 2. No message is outputted if the connection is interrupted causing suspension, the only message seen is a message on resumption.

there is a parameter to set to tell rsyslog to output suspension messasges.

David Lang

**Comment by schlitzered** [comment]
@davidelang, as the title of this issue suggests i would guess that @splitice is also talking about omfwdm and as written in the comment of 9. feb. with rsyslog 8, reporting suspencsion messages should be the default. i also explicitly switched on these messages.

**Comment by rgerhards** [comment]
I think this is related: https://github.com/rsyslog/rsyslog/issues/1069 or IAW I am currently looking into something that will probably fix this here as well.

**Comment by splitice** [comment]
@rgerhards I agree, at-least in my case.

@davidelang omfwd (TCP) w/ compression & octet-stream. Anyway that bug seems to be unrelated and could probably be split off. It was all messages, something must have changed in the format, upgrading the collector end solved the problem in full and messages began flowing again.

**Comment by rgerhards** [comment]
The root cause of the missing messages seems to be that omfwd did not always emit messages to the error reporting system but instead only to the debug log. Part of that was due to pre-0.26 not being able to emit error messages at all times.

Some of the error messages have already been enabled by the omfwd/udp related work. We should review if other spots are left where error messages may now be generated.
