### ISSUE TITLE
rsyslog fails to start on RHEL 7 due to systemd unit file

### ISSUE THREAD

**Issue by mxcarron** [rsyslog/rsyslog#783]
Hello,

I use rsyslog 8.16.0 and the RPM packages provided on rsyslog repository.

Rsyslog fails on start and *journalctl* provides this messages : 
```
Feb 09 15:27:58 epcfblanud98 systemd[1]: Dependency failed for System Logging Service.
Feb 09 15:27:58 epcfblanud98 systemd[1]: Job rsyslog.service/start failed with result 'dependency'.
```

The dependency missing is *syslog.socket*.

Looking at the rsyslog rpm provided by redhat (v7.4.x) , you can notice that the line 
```Requires=syslog.socket``` is commented out.

Modifying */usr/lib/systemd/system/rsyslog.service* in the same way, let rsyslog starts again.

**Comment by mxcarron** [comment]
[rsyslog-service-patch.txt](https://github.com/rsyslog/rsyslog/files/123354/rsyslog-service-patch.txt)

**Comment by mxcarron** [comment]
Actually, importing the entire RHEL unit file could be nice.

```
[Unit]
Description=System Logging Service
;Requires=syslog.socket

[Service]
Type=notify
EnvironmentFile=-/etc/sysconfig/rsyslog
ExecStart=/usr/sbin/rsyslogd -n $SYSLOGD_OPTIONS
Restart=on-failure
UMask=0066
StandardOutput=null

[Install]
WantedBy=multi-user.target
;Alias=syslog.service
```

**Comment by portante** [comment]
You might want to move this to the rhel/centos repo: https://github.com/rsyslog/rsyslog-pkg-rhel-centos

**Comment by alorbach** [comment]
I have created a patch file to add the changes for CentOS7. Packages should be updated and working now.

**Comment by rgerhards** [comment]
Imho this is the wrong path forward. I think we should align with what the distro does, even if that means we need to run informal.

Just my 2cts (I am not really into packaging)
Rainer

**Comment by lxhunter** [comment]
Same with ubuntu 1604
