### ISSUE TITLE
rsyslog main Q size always growing

### ISSUE THREAD

**Issue by rayshen3** [rsyslog/rsyslog#785]
version: 8.15
os:    centos6.2
module: imudp  imfile  omkafka  impstats

my data stream is: nginx--->imudp--->omkafka

i found the main Q size always growing since rsyslogd start,  this value should be zero or very small, but it's not
i try to increase/reduce the main_queue/action_queue's paramerters
```
queue. workerthreads
queue.size
queue.highwatermark
partitions.number
```
it's not working,  it's still has many logs in the "main Q",  i'm not sure if my configuration has some problems or some other reasons 
can anyone help me :(

my config:

```
module(load="imudp")
module(load="omkafka")
module(load="imfile")
module(load="impstats" interval="10" log.syslog="off" log.file="/home/admin/rsyslog-v8/logs/stats.log")

main_queue(
  queue.spoolDirectory="/home/admin/rsyslog-v8/queuedata"
  queue.filename="main_queue"
  queue.maxdiskspace="50G"
  queue.maxfilesize="2G"
  queue.workerthreads="15"
  queue.dequeueBatchSize="4096"
  queue.size="5000000"
  queue.highwatermark="4000000"
  queue.discardmark="4500000"
  queue.type="linkedlist"
  queue.checkpointinterval="10"
  queue.discardseverity="3"
  queue.timeoutshutdown="10"
  queue.timeoutactioncompletion="10"
  queue.timeoutenqueue="20"
  queue.timeoutworkerthreadshutdown="10"
  #queue.workerthreadminimummessages="7000"
  queue.saveonshutdown="on"
)

$IncludeConfig /home/admin/rsyslog-v8/etc/rsyslog.d/*.conf
$WorkDirectory /home/admin/rsyslog-v8/work


$DebugFile /home/admin/rsyslog-v8/logs/rsyslog-server.log
$DebugLevel 0


input(type="imudp" port="1314" Ruleset="nginx-access")


ruleset(name="nginx-access") {
    local0.*    action(type="omkafka"
	        topic="analytics-nginx-access"
		partitions.number="15"
	        confParam=["queue.buffering.max.messages=2000000"]
                queue.size="3000000"
                queue.highwatermark="2000000"
                queue.discardmark="2500000"
  		queue.maxfilesize="2G"
                queue.type="linkedlist"
                queue.workerthreads="15"
		queue.timeoutenqueue="0"
                queue.spoolDirectory="/home/admin/rsyslog-v8/etc/queuedata"
                queue.filename="omkfk_queue"
                queue.maxdiskspace="50G"
                queue.dequeueBatchSize="4096"
                queue.saveonshutdown="on"
	        broker=["xxxxxxxxxxxxxxxxxxxxxxxxxxxxx"]
            )
    stop
}
```

impstats logs:
```
Sun Feb 14 18:00:16 2016: omkafka: submitted=7845665 maxoutqsize=3611 failures=100 topicdynacache.skipped=0 topicdynacache.miss=0 topicdynacache.evicted=0
Sun Feb 14 18:00:16 2016: action 0: origin=core.action processed=7842700 failed=0 suspended=0 suspended.duration=0 resumed=0
Sun Feb 14 18:00:16 2016: action 1: origin=core.action processed=2984 failed=0 suspended=0 suspended.duration=0 resumed=0
Sun Feb 14 18:00:16 2016: imudp(*:1314): origin=imudp submitted=9835759
Sun Feb 14 18:00:16 2016: resource-usage: origin=impstats utime=2513861834 stime=547165818 maxrss=2540144 minflt=707405 majflt=0 inblock=0 oublock=3000 nvcsw=31345171 nivcsw=1315574
Sun Feb 14 18:00:16 2016: action 0 queue[DA]: origin=core.queue size=0 enqueued=0 full=0 discarded.full=0 discarded.nf=0 maxqsize=0
Sun Feb 14 18:00:16 2016: action 0 queue: origin=core.queue size=23 enqueued=7842691 full=0 discarded.full=0 discarded.nf=0 maxqsize=577
Sun Feb 14 18:00:16 2016: main Q[DA]: origin=core.queue size=0 enqueued=0 full=0 discarded.full=0 discarded.nf=0 maxqsize=0
Sun Feb 14 18:00:16 2016: main Q: origin=core.queue size=2011748 enqueued=9839397 full=0 discarded.full=0 discarded.nf=0 maxqsize=2020421
Sun Feb 14 18:00:16 2016: imudp(w0): origin=imudp called.recvmmsg=9207278 called.recvmsg=0 msgs.received=9835761
```

**Comment by rgerhards** [comment]
I think you have heavily overdone with worker threads, and are receiving very low batch sizes with extreme locking contention. What does it look with the default number of worker threads (worker thread paramter removed)?

**Comment by rayshen3** [comment]
Hello @rgerhards 
Thans for your reply

I remove "queue.workerthreads" from main_queue/action_queue, restarting rsyslogd, But main Q size still increasing
action 0(omkafka) Q size is normal all the time
I debug it for a long time, nginx log qps has only 3k-4k/s
Is there any other reasons?    


thanks  


impstats log("queue.workerthreads" removed):
```
Sun Feb 14 20:01:21 2016: omkafka: submitted=3721353 maxoutqsize=4005 failures=48 topicdynacache.skipped=0 topicdynacache.miss=0 topicdynacache.evicted=0
Sun Feb 14 20:01:21 2016: action 0: origin=core.action processed=3719772 failed=0 suspended=0 suspended.duration=0 resumed=0
Sun Feb 14 20:01:21 2016: action 1: origin=core.action processed=1583 failed=0 suspended=0 suspended.duration=0 resumed=0
Sun Feb 14 20:01:21 2016: imudp(*:1314): origin=imudp submitted=7957563
Sun Feb 14 20:01:21 2016: resource-usage: origin=impstats utime=1773556378 stime=368750941 maxrss=5304632 minflt=1383089 majflt=0 inblock=0 oublock=2152 nvcsw=14424483 nivcsw=1481963
Sun Feb 14 20:01:21 2016: action 0 queue[DA]: origin=core.queue size=0 enqueued=0 full=0 discarded.full=0 discarded.nf=0 maxqsize=0
Sun Feb 14 20:01:21 2016: action 0 queue: origin=core.queue size=1 enqueued=3719771 full=0 discarded.full=0 discarded.nf=0 maxqsize=523
Sun Feb 14 20:01:21 2016: main Q[DA]: origin=core.queue size=0 enqueued=0 full=0 discarded.full=0 discarded.nf=0 maxqsize=0
Sun Feb 14 20:01:21 2016: main Q: origin=core.queue size=4239326 enqueued=7959353 full=0 discarded.full=0 discarded.nf=0 maxqsize=4239326
Sun Feb 14 20:01:21 2016: imudp(w0): origin=imudp called.recvmmsg=5038360 called.recvmsg=0 msgs.received=7957563
```

main Q: origin=core.queue size=**4239326** enqueued=7959353 full=0 discarded.full=0 discarded.nf=0 maxqsize=4239326
action 0 queue: origin=core.queue size=**1** enqueued=3719771 full=0 discarded.full=0 discarded.nf=0 maxqsize=523

imudp(w0): origin=imudp called.recvmmsg=5038360 called.recvmsg=0 msgs.received=**7957563**
omkafka: submitted=**3721353** maxoutqsize=4005 failures=48

**Comment by rgerhards** [comment]
Mhh... Can you reduce the pstats interval to 1 minute and post the complete pstats of a 60 minute run?

**Comment by rayshen3** [comment]
Thanks rgerhards, Sorry for my simple logs

$IncludeConfig/queue.workerthreads   removed

the full logs is here
https://gist.github.com/rayshen3/ee0b8cc418e221e1301b

**Comment by rgerhards** [comment]
Mhhh... I am more than puzzled I have to admit. With this config, you should see almost no messages at all in the main queue. Can you also provide a debug log?

@davidelang do you have an idea?

**Comment by rayshen3** [comment]
hi  @rgerhards   I also think it's very strange,   I've set "$DebugLevel" to 2(others remain unchanged).
producing too many  logs like this
https://gist.github.com/rayshen3/8be916cb0028e1612f0b

Can you help me to analyse, Hope it's usefull for you, thanks.
wait for your reply :)

**Comment by rgerhards** [comment]
It's only a small debug log snippet, but I think it points to the problem: it looks like the disk part of the main queue is corrupt, probably from an earlier try. Please delete all files from the work directory and re-try. Not that you do not really use the main queue, so it is best to remove it's definition from the config.

If after all that the problem persists, please post new pstats and debug log.

**Comment by davidelang** [comment]
a large number of worker threads is almost always wrong. What happens is that the different worker threads end up fighting each other for locks on the queues and only processing one message at a time (no batching of messages). This utterly destroys performance.

You are also setting checkpoint interval which forces rsyslog to do fsyncs every 10 messages. This is also a performance killer.

you need to remove the worker threads from the ruleset queue as well. You should also add a name to the action that delivers logs to Kafka so that it doesn't just show up as 'action #'

The config you are showing us does nothing with any files that don't arrive via UDP, but you include additional config files, what do they do?

You should put the queue parameters for the nginx-access on the ruleset, not on the action.
Rainer, with no queue on the ruleset, does this mean that the main queue does still get used?

Also, I thought that you needed to set the workdirectory in the global() secion, not set spoolDirectory in each queue definition

**Comment by rgerhards** [comment]
2016-02-15 17:09 GMT+01:00 davidelang <notifications@github.com>:

> a large number of worker threads is almost always wrong. What happens is
> that the different worker threads end up fighting each other for locks on
> the queues and only processing one message at a time (no batching of
> messages). This utterly destroys performance.
>
> You are also setting checkpoint interval which forces rsyslog to do fsyncs
> every 10 messages. This is also a performance killer.
>
> you need to remove the worker threads from the ruleset queue as well. You
> should also add a name to the action that delivers logs to Kafka so that it
> doesn't just show up as 'action #'
>

Yupp, but  in this config it really only is one action (can also be seen in
the debug log).

> The config you are showing us does nothing with any files that don't
> arrive via UDP, but you include additional config files, what do they do?
>

he has commented that out


> You should put the queue parameters for the nginx-access on the ruleset,
> not on the action.
> Rainer, with no queue on the ruleset, does this mean that the main queue
> does still get used?
>

argh... yes! I overlooked that. So this definitely needs correction.


> Also, I thought that you needed to set the workdirectory in the global()
> secion, not set spoolDirectory in each queue definition
>

Both is possible.

Rainer

**Comment by rayshen3** [comment]
@davidelang   thanks your detailed reply
I've corrected these problems,  In order to confirm the rootcase, correcting one of them every time 

1. comment out "checkpoint interval"
Not working

2. comment out "queue.spoolDirectory" and use default "$WorkDirectory"
Not working

3. remove the worker threads from the ruleset queue and add a name to the action
Not working

4. put the queue parameters on the ruleset
**It's exciting!  main queue size change to 0 and don't increase anymore!**

@rgerhards  
Reading the manual  http://www.rsyslog.com/doc/v8-stable/rainerscript/queue_parameters.html
I have some questions with the manual

"Queue parameters can be used together with the following statements:
action()
ruleset()
main_queue()
Queues need to be configured in the action or ruleset it should affect. If nothing is configured, default values will be used. Thus, the default ruleset has only the default main queue. Specific Action queues are not set up by default."

In the manual, Queue parameters could be set in the action or ruleset, What's the difference between them, I don't understand that why I got a performance problem on action, But it's normal on ruleset?
I didn't find any statements about the difference in the manual,  Is there something missing ?

Thanks a lot.

**Comment by portante** [comment]
@rayshen3, can you share your final configuration that worked?

**Comment by davidelang** [comment]
I'll bet that the ruleset queue is growing though.

I'll do a writeup a bit later of what is happening here.

David Lang

**Comment by portante** [comment]
@rayshen3, @davidelang, can we share what finally worked here?

**Comment by davidelang** [comment]
I'm not sure he ever got everything completely working, but one thing is that if you set a ruleset to an input, but don't specify a queue on that ruleset, the main queue is still used. If you specify a queue for the ruleset, you have effectively spawned an independent copy of rsyslog, the input threads will post to that queue and worker threads will read from that queue and these threads will be completely independent of the ones working other inputs or the main queue
