### ISSUE TITLE
test dynstats_overflow-vg.sh sometimes fails

### ISSUE THREAD

**Issue by rgerhards** [rsyslog/rsyslog#786]
This test sometimes fails, a typical failure is given below. This might be related to the actual thing that is being tested, but it is also likely caused by some race inside the testbench itself or inside rsyslog. Especially in the later case, this can point into a more severe, general problem. As such, we should try to nail down what is going on [note that at this time we know we have some other racy tests as well, I begin to add issue trackers from them whenever they come up].

@janmejay although there is only a limited chance this might be related to the actual functionality, I would still appreciate if you could find some time to have a look as well.

This can most easily be reproduce by running the test under the loop script like this:
```
./loop.sh ./dynstats_overflow-vg.sh
```
Note: you need to be inside the ./tests directory and $srcdir must be set appropriately.

**Failures seen:**

```
content-missing assertion failed, some line in 'rsyslog.out.stats.log' matched pattern 'corge'
FAIL!
```

**another one:**
```
content-check failed to find 'foo 017 -6', content is
 [origin software="rsyslogd" swVersion="8.17.0.master" x-pid="9736" x-info="http://www.rsyslog.com"] start -1
dynstats: bucket 'msg_stats' is being reset [v8.17.0.master try http://www.rsyslog.com/e/2041 ] -1
foo 001 0
bar 002 0
baz 003 0
foo 004 0
baz 005 0
foo 006 0
quux 007 -6
corge 008 -6
quux 009 -6
foo 010 0
corge 011 -6
grault 012 -6
foo 013 0
dynstats: bucket 'msg_stats' is being reset [v8.17.0.master try http://www.rsyslog.com/e/2041 ] -1
dynstats: bucket 'msg_stats' is being reset [v8.17.0.master try http://www.rsyslog.com/e/2041 ] -1
 [origin software="rsyslogd" swVersion="8.17.0.master" x-pid="9736" x-info="http://www.rsyslog.com"] rsyslogd was HUPed -1
corge 014 0
grault 015 0
quux 016 0
dynstats: bucket 'msg_stats' is being reset [v8.17.0.master try http://www.rsyslog.com/e/2041 ] -1
foo 017 0
corge 018 0
dynstats: bucket 'msg_stats' is being reset [v8.17.0.master try http://www.rsyslog.com/e/2041 ] -1
 [origin software="rsyslogd" swVersion="8.17.0.master" x-pid="9736" x-info="http://www.rsyslog.com"] exiting on signal 15. -1
FAIL!
```

**Comment by janmejay** [comment]
I reasoned this. This is a timing issue.

The log-line highlighted below (its a reset) is to blame. A reset wasn't
expected at that time.

Here is what should have happened:
Step 1. as max-cardinality being set to 3, line 014 to 016 were supposed to
saturate it
Step 2. as dyn-stats bucket is saturated, foo 017 should have been rejected
(for stats gathering)

However a reset played between step 1 and 2. Because of this, the dyn-stats
bucket was not saturated anymore when foo 017 was being processed, so it
didn't reject it.

Let me think of a way to make it more resilient to timing issues. I thought
2-seconds was long enough for stability, but it clearly isn't. One thing I
can do is bump up the time, but may be there is a more elegant way of
testing it which is resilient to timing/slowness issues.

On Mon, Feb 15, 2016 at 3:54 PM, Rainer Gerhards <notifications@github.com>
wrote:

> This test sometimes fails, a typical failure is given below. This might be
> related to the actual thing that is being tested, but it is also likely
> caused by some race inside the testbench itself or inside rsyslog.
> Especially in the later case, this can point into a more severe, general
> problem. As such, we should try to nail down what is going on [note that at
> this time we know we have some other racy tests as well, I begin to add
> issue trackers from them whenever they come up].
>
> @janmejay <https://github.com/janmejay> although there is only a limited
> chance this might be related to the actual functionality, I would still
> appreciate if you could find some time to have a look as well.
>
> This can most easily be reproduce by running the test under the loop
> script like this:
>
> ./loop.sh ./dynstats_overflow-vg.sh
>
> Note: you need to be inside the ./tests directory and $srcdir must be set
> appropriately.
>
> *Typical failure:*
>
> content-check failed to find 'foo 017 -6', content is
>  [origin software="rsyslogd" swVersion="8.17.0.master" x-pid="9736" x-info="http://www.rsyslog.com"] start -1
> dynstats: bucket 'msg_stats' is being reset [v8.17.0.master try http://www.rsyslog.com/e/2041 ] -1
> foo 001 0
> bar 002 0
> baz 003 0
> foo 004 0
> baz 005 0
> foo 006 0
> quux 007 -6
> corge 008 -6
> quux 009 -6
> foo 010 0
> corge 011 -6
> grault 012 -6
> foo 013 0
> dynstats: bucket 'msg_stats' is being reset [v8.17.0.master try http://www.rsyslog.com/e/2041 ] -1
> dynstats: bucket 'msg_stats' is being reset [v8.17.0.master try http://www.rsyslog.com/e/2041 ] -1
>  [origin software="rsyslogd" swVersion="8.17.0.master" x-pid="9736" x-info="http://www.rsyslog.com"] rsyslogd was HUPed -1
> corge 014 0
> grault 015 0
> quux 016 0*dynstats: bucket 'msg_stats' is being reset [v8.17.0.master try http://www.rsyslog.com/e/2041 <http://www.rsyslog.com/e/2041> ] -1*
> foo 017 0
> corge 018 0
> dynstats: bucket 'msg_stats' is being reset [v8.17.0.master try http://www.rsyslog.com/e/2041 ] -1
>  [origin software="rsyslogd" swVersion="8.17.0.master" x-pid="9736" x-info="http://www.rsyslog.com"] exiting on signal 15. -1
> FAIL!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rsyslog/rsyslog/issues/786>.
>



-- 
Regards,
Janmejay
http://codehunk.wordpress.com

**Comment by janmejay** [comment]
The highlighting didn't go very well (I think github formatting
doesn't like it).

So here it is in a more crude form:

corge 014 0
grault 015 0
quux 016 0****This is the unexpected reset*** dynstats: bucket
'msg_stats' is being reset [v8.17.0.master try
http://www.rsyslog.com/e/2041 <http://www.rsyslog.com/e/2041> ] -1*
foo 017 0
corge 018 0


Also, in this case it surely has to do with the way tests expected
timing to be. Implementation is correct, test is not resilient enough.


On Mon, Feb 15, 2016 at 4:38 PM, singh.janmejay <singh.janmejay@gmail.com>
wrote:

> I reasoned this. This is a timing issue.
>
> The log-line highlighted below (its a reset) is to blame. A reset wasn't
> expected at that time.
>
> Here is what should have happened:
> Step 1. as max-cardinality being set to 3, line 014 to 016 were supposed
> to saturate it
> Step 2. as dyn-stats bucket is saturated, foo 017 should have been
> rejected (for stats gathering)
>
> However a reset played between step 1 and 2. Because of this, the
> dyn-stats bucket was not saturated anymore when foo 017 was being
> processed, so it didn't reject it.
>
> Let me think of a way to make it more resilient to timing issues. I
> thought 2-seconds was long enough for stability, but it clearly isn't. One
> thing I can do is bump up the time, but may be there is a more elegant way
> of testing it which is resilient to timing/slowness issues.
>
> On Mon, Feb 15, 2016 at 3:54 PM, Rainer Gerhards <notifications@github.com
> > wrote:
>
>> This test sometimes fails, a typical failure is given below. This might
>> be related to the actual thing that is being tested, but it is also likely
>> caused by some race inside the testbench itself or inside rsyslog.
>> Especially in the later case, this can point into a more severe, general
>> problem. As such, we should try to nail down what is going on [note that at
>> this time we know we have some other racy tests as well, I begin to add
>> issue trackers from them whenever they come up].
>>
>> @janmejay <https://github.com/janmejay> although there is only a limited
>> chance this might be related to the actual functionality, I would still
>> appreciate if you could find some time to have a look as well.
>>
>> This can most easily be reproduce by running the test under the loop
>> script like this:
>>
>> ./loop.sh ./dynstats_overflow-vg.sh
>>
>> Note: you need to be inside the ./tests directory and $srcdir must be set
>> appropriately.
>>
>> *Typical failure:*
>>
>> content-check failed to find 'foo 017 -6', content is
>>  [origin software="rsyslogd" swVersion="8.17.0.master" x-pid="9736" x-info="http://www.rsyslog.com"] start -1
>> dynstats: bucket 'msg_stats' is being reset [v8.17.0.master try http://www.rsyslog.com/e/2041 ] -1
>> foo 001 0
>> bar 002 0
>> baz 003 0
>> foo 004 0
>> baz 005 0
>> foo 006 0
>> quux 007 -6
>> corge 008 -6
>> quux 009 -6
>> foo 010 0
>> corge 011 -6
>> grault 012 -6
>> foo 013 0
>> dynstats: bucket 'msg_stats' is being reset [v8.17.0.master try http://www.rsyslog.com/e/2041 ] -1
>> dynstats: bucket 'msg_stats' is being reset [v8.17.0.master try http://www.rsyslog.com/e/2041 ] -1
>>  [origin software="rsyslogd" swVersion="8.17.0.master" x-pid="9736" x-info="http://www.rsyslog.com"] rsyslogd was HUPed -1
>> corge 014 0
>> grault 015 0
>> quux 016 0*dynstats: bucket 'msg_stats' is being reset [v8.17.0.master try http://www.rsyslog.com/e/2041 <http://www.rsyslog.com/e/2041> ] -1*
>> foo 017 0
>> corge 018 0
>> dynstats: bucket 'msg_stats' is being reset [v8.17.0.master try http://www.rsyslog.com/e/2041 ] -1
>>  [origin software="rsyslogd" swVersion="8.17.0.master" x-pid="9736" x-info="http://www.rsyslog.com"] exiting on signal 15. -1
>> FAIL!
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/rsyslog/rsyslog/issues/786>.
>>
>
>
>
> --
> Regards,
> Janmejay
> http://codehunk.wordpress.com
>



-- 
Regards,
Janmejay
http://codehunk.wordpress.com

**Comment by rgerhards** [comment]
maybe we should try to get the sleep time bump at first. Side-note: I often successfully look into these things via the tests/loop.sh script, which repeatedly executes a test. Then I can often reproduce the issue on my machine as well. Just FYI.

**Comment by janmejay** [comment]
OK, I'll adjust timing. Will send a pr.

--
Regards,
Janmejay

PS: Please blame the typos in this mail on my phone's uncivilized soft
keyboard sporting it's not-so-smart-assist technology.

**Comment by rgerhards** [comment]
Thanks. Please just don't close this issue. I would like to give further verification some try, just to see if we can find a better solution. But if extending the time helps for now, that's useful for everyone.

**Comment by janmejay** [comment]
Sounds good.

--
Regards,
Janmejay

PS: Please blame the typos in this mail on my phone's uncivilized soft
keyboard sporting it's not-so-smart-assist technology.

**Comment by rgerhards** [comment]
See https://github.com/rsyslog/rsyslog/pull/816 for more information and a probable cause.

In any case, we now have these valgrind failures. I currently have no time to find out what it really means, so I think the best cure is to temporarily disable the valgrind test. This doesn't hurt so much because the non-valgrind version still exists and misadressing checks are also done by clang's address sanitizer. Still, we should find the root cause. If it really is the threading lib, we could add valgrind suppressions.

**Comment by rgerhards** [comment]
just FYI: I have created a private branch to work on this issue: https://github.com/rgerhards/rsyslog/tree/testbench-fix-dynstats-vg

**Comment by janmejay** [comment]
Is there a way I can get access to env where this failure is repeatable?

**Comment by rgerhards** [comment]
Would access to buildbot be sufficient or do you need to have ssh access? From what I see, it fails across almost all of the buildbot machines, more often on the slowest ones. So the main trigger seems to be that the machine is slow. ... but while I rwite this, I just got the same failure on a Ubuntu 15.10 VM on my regular work desktop (which is not that slow ;)), so it looks more like a general timing issue. I got it by doing

```$ ./loop.sh . /dynstats_overflow-vg.sh```

and this time it failed on the third try.

**Comment by janmejay** [comment]
Let me CPU starve it and see.

On Sun, Feb 28, 2016 at 4:57 PM, Rainer Gerhards <notifications@github.com>
wrote:

> Would access to buildbot be sufficient or do you need to have ssh access?
> From what I see, it fails across almost all of the buildbot machines, more
> often on the slowest ones. So the main trigger seems to be that the machine
> is slow. ... but while I rwite this, I just got the same failure on a
> Ubuntu 15.10 VM on my regular work desktop (which is not that slow ;)), so
> it looks more like a general timing issue. I got it by doing
>
> $ ./loop.sh . /dynstats_overflow-vg.sh
>
> and this time it failed on the third try.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rsyslog/rsyslog/issues/786#issuecomment-189848212>.
>



-- 
Regards,
Janmejay
http://codehunk.wordpress.com

**Comment by rgerhards** [comment]
just an interim note: I had one more failure after 10 tries, and right now it has 175 runs without a problem in succession (still continues to run).

**Comment by rgerhards** [comment]
FYI: on the fast machine, I do not have any failure within the pas 238+175 runs, but I got access to a slow machine. There, it reproduces rather easily: 92 runs, 24 success, 68 fail. That's why the buildbot so often aborts. It all comes with the same violation, which points into thread local storage. I'll now try to join() the threads after termination. Note that they should already have been joined at that stage, but let's see what happens.

**Comment by rgerhards** [comment]
It strongly looks like pthread_join() actually was the problem .. on the slow machine, I have now 31 runs in succession without a failure. Will not commit to my experimental branch and see what the rest of the testbench and CI env says about it...

**Comment by rgerhards** [comment]
ok, 100 out of 100 runs on the slow machine with success. If travis doesn't complain (not yet finished), I'll give it a try on the full integration platform.

**Comment by rgerhards** [comment]
unfortunately, the simple fix seems not to work correctly. See: https://travis-ci.org/rgerhards/rsyslog/jobs/112417268

So it looks like we need to dig deeper why the thread is not joined. At least we know how to reproduce :-)

**Comment by rgerhards** [comment]
proper fix by @portante: https://github.com/rsyslog/rsyslog/pull/827

I close this now in the hope that's final. If problems re-appear, we can re-open.
