### ISSUE TITLE
Rsyslog omkafka queue problem

### ISSUE THREAD

**Issue by spuzirev** [rsyslog/rsyslog#796]
Hello.

I'm trying to get working following log stream

myapp -> logfile -> rsyslog-imfile -> rsyslog-omkafka -> kafka cluster

using following config:

```
$WorkDirectory /var/lib/rsyslog

module(load="imfile")
module(load="omkafka")

template(
  name="SimpleMsg"
  type="list"
) {
  property(name="msg")
}

input(
  type="imfile"
  File="/var/log/myapp_log"
  Tag="myapp_log"
  Severity="notice"
  Facility="local7"
  PersistStateInterval="1000"
  ruleset="myapp_log"
)

ruleset(name="myapp_log") {
  action(
    type="omkafka"
    topic="myapp_log"
    broker=[
      "kafka1:9092",
      "kafka2:9092",
      "kafka3:9092"
    ]
    template="SimpleMsg"
    confParam=[
      "socket.timeout.ms=1000",
      "socket.keepalive.enable=true",
      "queue.buffering.max.messages=1000",
      "queue.buffering.max.ms=100"
    ]
    queue.type="LinkedList"
    queue.spoolDirectory="/var/lib/rsyslog/buffer"
    queue.filename="myapp_log"
    queue.size="3000"
    queue.saveonshutdown="on"
    queue.highwatermark="2000"
    queue.lowwatermark="200"
    queue.discardmark="2500"
    queue.dequeuebatchsize="1"
  )
}

```

```
$ rsyslogd -v
rsyslogd 8.13.0, compiled with:
        PLATFORM:                               x86_64-koji-linux-gnu
        PLATFORM (lsb_release -d):
        FEATURE_REGEXP:                         Yes
        GSSAPI Kerberos 5 support:              No
        FEATURE_DEBUG (debug build, slow code): No
        32bit Atomic operations supported:      Yes
        64bit Atomic operations supported:      Yes
        memory allocator:                       system default
        Runtime Instrumentation (slow code):    No
        uuid support:                           Yes
        Number of Bits in RainerScript integers: 64

See http://www.rsyslog.com for more information.
```

It's working fine. Logs are successfully transfered to kafka topic.
But I'm trying to get logs buffered locally if kafka brokers are down. So I'm trying to imitate this case using

```
iptables -I OUTPUT -m tcp -p tcp --dport 9092 -j DROP
```

After this and waiting I get only following repeatable messages in rsyslog own log:
```
rsyslogd[943]: rsyslogd: omkafka: Failed to produce to topic 'myapp_log' partition 0: Local: Queue full  [v8.13.0 try http://www.rsyslog.com/e/2424 ]
```

And there is no file in /var/lib/rsyslog/buffer created.

When I open firewall I have recent messages, but older messages are lost.

I think rsyslog in this case doesn't care about messages after pushing them to librdkafka, because if I increase queue.buffering.max.messages=1000 to high values, for example 1 million, buffering working successfully (but rsyslog eats my RAM very intensively). And I want disk queue, because it's too rich to have enough memory for log queue.

If I change queue.*mark parameters nothing changes.

Can you help me?

Thank you.

**Comment by rgerhards** [comment]
*action.resumeRetryCount is missing. Without it, rsyslog suspends the
action after failure and messages are lost. Set it to -1 for eternal wait
or some higher number that makes more sense to you (e.g. 500 tries).*

*HTH*
*Rainer*

2016-02-17 10:20 GMT+01:00 Sergey Puzirev <notifications@github.com>:

**Comment by rgerhards** [comment]
I assume this is solved.
