### ISSUE TITLE
rsgtutil returns segmentation fault when extracting with -x

### ISSUE THREAD

**Issue by friedl** [rsyslog/rsyslog#802]
*Version:* rsgtutil 8.16.0
*Command:* rsgtutil -x 1 messagesTest6 --publications-server http://verify.guardtime.com/ksi-publications.bin

*Note:* "--extract" parameter works correctly

*From core dump:*
Program terminated with signal 11, Segmentation fault.
#0  0x00007faf660077a1 in extractKSI (name=0x7ffde23b17e3 "messagesTest6",
    errbuf=0x7ffde23aee10 "messagesTest6.gtsig: No such file or directory\n", sigfname=0x7ffde23ace10 "messagesTest6.ksisig",
    logfp=0x7faf67c2f010, sigfp=0x7faf67c2f250) at rsgtutil.c:1026
1026            if (strlen(linenumbers) > 0 ) {
Missing separate debuginfos, use: debuginfo-install libidn-1.18-2.el6.x86_64
(gdb) bt full
#0  0x00007faf660077a1 in extractKSI (name=0x7ffde23b17e3 "messagesTest6",
    errbuf=0x7ffde23aee10 "messagesTest6.gtsig: No such file or directory\n", sigfname=0x7ffde23ace10 "messagesTest6.ksisig",
    logfp=0x7faf67c2f010, sigfp=0x7faf67c2f250) at rsgtutil.c:1026
        newsigfname = '\000' <repeats 920 times>"\323, \312\300d\257\177\000\000\000\000\000\000\000\000\000\000\020\360\302g\257\177\000\000\035\000\000\000\000\000\000\000\000\340\377e\257\177\000\000\000\000\000\000\000\000\000\000\205\340\300d\257\177\000\000\001\000\000\000\000\000\000\000\001\000\000\000\000\000\000\000\020\360\302g\257\177\000\000x+\317d\257\177\000\000\000\000\000\000\000\000\000\000M\307\300d\257\177\000\000\000\000\000\000\000\000\000\000\020\360\302g\257\177\000\000p\310:\342\375\177\000\000\034\000\000\000\000\000\000\000\200\310:\342\375\177\000\000x+\317d\257\177\000\000\250\377\377\377\377\377\377\377\316\361\275d\257\177\000\000y+\317d\257\177\000\000\001", '\000' <repeats 55 times>, "`\307:\342\375\177\000\000\000\000\000\000\000\000\000\000r+\317d\257\177", '\000' <repeats 26 times>"\314, \307:\342\375\177\000\000\350\307:\342\375\177\000\000\000\000\000\000\000\000\000\000\b\310:\342\375\177", '\000' <repeats 58 times>...
        newsigfp = 0x0
        newlogfp = 0x0
        lineRec = 0x0
        stlen = 0
        ssread = <value optimized out>
        writeMode = "w"
        iLineNumbers = 0
        paiLineNumbers = 0x0
        r = 0
        j = 0
        iReturn = 1
        bs = 0x0
        bh = 0x0
        tlvbhrec = {tlvtype = 0, tlvlen = 0, hdr = "\000\000\000", lenHdr = 0 '\000', data = '\000' <repeats 65535 times>}
        ksi = <value optimized out>
        bHasRecHashes = <value optimized out>
        bHasIntermedHashes = <value optimized out>
        bInBlock = <value optimized out>
        bInitDone = 0
        hashchain = 0x0
        ksiRootHash = 0x0
        sigfilerewindPos = 0
        ectx = {fp = 0x0, filename = 0x0, verbose = 0 '\000', recNumInFile = 0, recNum = 0, blkNum = 0, treeLevel = 0 '\000',
          computedHash = 0x0, lefthash = 0x0, righthash = 0x0, fileHash = 0x0, ksistate = 0, errRec = 0x0, frstRecInBlk = 0x0}
        iIndex = <value optimized out>
        iLineSearch = <value optimized out>
        iLineMax = <value optimized out>
        iLineCurrent = <value optimized out>
        bLogLineFound = <value optimized out>
        bBlockSigWritten = <value optimized out>
#1  0x00007faf66009b34 in extract (name=0x7ffde23b17e3 "messagesTest6") at rsgtutil.c:1555
        iSuccess = 1
        sigfname = "messagesTest6.ksisig\000\000\000\000|\377\336e\257\177\000\000\000\000\000\000\000\000\000\000V\266\"a\257\177\000\000\070\333\376e\257\177\000\000\202\222\336e\257\177", '\000' <repeats 42 times>"\306, \004\363d\257\177\000\000/\000\000\000\001\000\000\000\265\300\336e", '\000' <repeats 12 times>"\250, \337\376e\257\177\000\000\025\000\000\000\000\000\000\000\001", '\000' <repeats 15 times>"\232, \224\337e\257\177\000\000`\320:\342\375\177\000\000\371\274\336e\257\177\000\000`\320:\342\375\177\000\000\070\333\376e\257\177\000\000`\320:\342\375\177\000\000\373\211\336e\257\177", '\000' <repeats 58 times>, "|\377\336e\257\177\000\000\000\000\000\000\000\000\000\000W\034Ca\257\177\000\000\070\325\376e\257\177\000\000\202\222\336e\257\177\000\000\000\000\000\000\000\000\000\000\360\316:\342\375\177\000\000\000\000\000\000\000\000\000\000 \333\376e\257\177\000\000"...
        logfp = 0x7faf67c2f010
        sigfp = <value optimized out>
#2  processFile (name=0x7ffde23b17e3 "messagesTest6") at rsgtutil.c:1636
        errbuf = "messagesTest6.gtsig: No such file or directory\n\000hj\377e\257\177\000\000\000\000\240\333u\304\373\377\000\000\326\344\275\313^\377\r\000\000\000\000\000\000\000\220\356:\342\375\177\000\000\340\361:\342\375\177\000\000\000\000\000\000\000\000\000\000\340\374:\342\375\177\000\000P\375:\342\375\177\000\000\000\000\000\000\000\000\000\000\360\357:\342\375\177\000\000\374\f\273d\257\177\000\000\310d\377e\257\177\000\000\242\323\336e\257\177\000\000\000\000\000\000\000\000\000\000\206\362\336e\257\177\000\000\330\037\000f\257\177\000\000\b\375:\342\375\177\000\000\020\375:\342\375\177\000\000\037\375:\342\375\177\000\000p\323\336e\257\177\000\000\360\254\271d\257\177\000\000P\375:\342\375\177\000\000n\333\336e\257\177\000\000\310d\377e\257\177", '\000' <repeats 12 times>"\240, \372u\304\373\377\000\000\000\000\000\000\000\000\360\357:\342\375\177\000\000\374\f\273d\257\177"...
#3  0x00007faf6600a169 in main (argc=6, argv=<value optimized out>) at rsgtutil.c:1817
        i = 5
        opt = <value optimized out>

**Comment by alorbach** [comment]
Fixed with https://github.com/rsyslog/rsyslog/pull/800
