### ISSUE TITLE
rsgtutil returns segmentation fault with -P parameter

### ISSUE THREAD

**Issue by friedl** [rsyslog/rsyslog#803]
*Version:* rsgtutil 8.16.0
*Command:* rsgtutil --extract 2 messagesTest6 -P http://verify.guardtime.com/ksi-publications.bin

*Note:* Works correctly with --publications-server parameter

*From core dump:*
#0  0x00007f403f8689a1 in extract (name=0x7fff71cec7f6 "messagesTest6") at rsgtutil.c:1550
        iSuccess = 1
        sigfname = "messagesTest6.ksisig\000\000\000\000|\357d?@\177\000\000\000\000\000\000\000\000\000\000V\246\250:@\177\000\000\070˄?@\177\000\000\202\202d?@\177", '\000' <repeats 42 times>"\306, \364x>@\177\000\000/\000\000\000\001\000\000\000\265\260d?", '\000' <repeats 12 times>"\250, τ?@\177\000\000\025\000\000\000\000\000\000\000\001", '\000' <repeats 15 times>"\232, \204e?@\177\000\000p\221\316q\377\177\000\000\371\254d?@\177\000\000p\221\316q\377\177\000\000\070˄?@\177\000\000p\221\316q\377\177\000\000\373yd?@\177", '\000' <repeats 58 times>, "|\357d?@\177\000\000\000\000\000\000\000\000\000\000W\f\311:@\177\000\000\070ń?@\177\000\000\202\202d?@\177", '\000' <repeats 11 times>"\220"...
        logfp = 0x7f404007d010
        sigfp = 0x7f404007d250
#1  processFile (name=0x7fff71cec7f6 "messagesTest6") at rsgtutil.c:1636
        errbuf = "messagesTest6.gtsig: No such file or directory\n\000hZ\205?@\177\000\000\000\000\300]\235\343\376\377\000\000\326\304\311~\200\376\r\000\000\000\000\000\000\000\240\257\316q\377\177\000\000\360\262\316q\377\177\000\000\000\000\000\000\000\000\000\000\360\275\316q\377\177\000\000`\276\316q\377\177", '\000' <repeats 11 times>"\261, \316q\377\177\000\000\374\374@>@\177\000\000\310T\205?@\177\000\000\242\303d?@\177\000\000\000\000\000\000\000\000\000\000\206\342d?@\177\000\000\330\017\206?@\177\000\000\030\276\316q\377\177\000\000 \276\316q\377\177\000\000/\276\316q\377\177\000\000p\303d?@\177\000\000\360\234?>@\177\000\000`\276\316q\377\177\000\000n\313d?@\177\000\000\310T\205?@\177", '\000' <repeats 12 times>"\300, |\235\343\376\377\000\000\000\000\000\000\000\000\000\261"...
#2  0x00007f403f869169 in main (argc=6, argv=<value optimized out>) at rsgtutil.c:1817
        i = 4
        opt = <value optimized out>

**Comment by alorbach** [comment]
Fixed with https://github.com/rsyslog/rsyslog/pull/800
