### ISSUE TITLE
Memory leak with rsgtutil —extract

### ISSUE THREAD

**Issue by friedl** [rsyslog/rsyslog#804]
Version: rsgtutil 8.16.0

[root@localhost repo]# valgrind --tool=memcheck --leak-check=full *rsgtutil --extract 1,2 /var/log/messagesTest6 --publications-server http://verify.guardtime.com/ksi-publications.bin*
==2608== Memcheck, a memory error detector
==2608== Copyright (C) 2002-2012, and GNU GPL'd, by Julian Seward et al.
==2608== Using Valgrind-3.8.1 and LibVEX; rerun with -h for copyright info
==2608== Command: rsgtutil --extract 1,2 /var/log/messagesTest6 --publications-server http://verify.guardtime.com/ksi-publications.bin
==2608==
==2608==
==2608== HEAP SUMMARY:
==2608==     in use at exit: 1,253,522 bytes in 26,192 blocks
==2608==   total heap usage: 93,232 allocs, 67,040 frees, 9,282,996 bytes allocated
==2608==
==2608== 32 bytes in 1 blocks are definitely lost in loss record 217 of 488
==2608==    at 0x4C27A2E: malloc (vg_replace_malloc.c:270)
==2608==    by 0x114DEA: rsksiIntoImprintFromKSI_DataHash (librsksi.c:109)
==2608==    by 0x11A8D3: rsksi_vrfy_nextRecExtract (librsksi_read.c:1588)
==2608==    by 0x10D03F: extractKSI (rsgtutil.c:1287)
==2608==    by 0x10EB33: processFile (rsgtutil.c:1555)
==2608==    by 0x10F168: main (rsgtutil.c:1817)
==2608==
==2608== 56 (24 direct, 32 indirect) bytes in 1 blocks are definitely lost in loss record 250 of 488
==2608==    at 0x4C267BB: calloc (vg_replace_malloc.c:593)
==2608==    by 0x114E77: rsksiImprintFromKSI_DataHash (librsksi.c:125)
==2608==    by 0x11A4EA: rsksi_vrfy_nextRecExtract (librsksi_read.c:1582)
==2608==    by 0x10D03F: extractKSI (rsgtutil.c:1287)
==2608==    by 0x10EB33: processFile (rsgtutil.c:1555)
==2608==    by 0x10F168: main (rsgtutil.c:1817)
==2608==
==2608== 64 (32 direct, 32 indirect) bytes in 1 blocks are definitely lost in loss record 270 of 488
==2608==    at 0x4C267BB: calloc (vg_replace_malloc.c:593)
==2608==    by 0x119337: rsksiHashstepFromKSI_DataHash (librsksi_read.c:1117)
==2608==    by 0x11A8F7: rsksi_vrfy_nextRecExtract (librsksi_read.c:1591)
==2608==    by 0x10D03F: extractKSI (rsgtutil.c:1287)
==2608==    by 0x10EB33: processFile (rsgtutil.c:1555)
==2608==    by 0x10F168: main (rsgtutil.c:1817)
==2608==
==2608== 64 (32 direct, 32 indirect) bytes in 1 blocks are definitely lost in loss record 271 of 488
==2608==    at 0x4C267BB: calloc (vg_replace_malloc.c:593)
==2608==    by 0x119337: rsksiHashstepFromKSI_DataHash (librsksi_read.c:1117)
==2608==    by 0x119476: verifySigblkFinishChain (librsksi_read.c:1851)
==2608==    by 0x10D2BD: extractKSI (rsgtutil.c:1307)
==2608==    by 0x10EB33: processFile (rsgtutil.c:1555)
==2608==    by 0x10F168: main (rsgtutil.c:1817)
==2608==
==2608== 96 bytes in 1 blocks are definitely lost in loss record 289 of 488
==2608==    at 0x4C27A2E: malloc (vg_replace_malloc.c:270)
==2608==    by 0x5268236: KSI_DataHasher_close (hash.c:549)
==2608==    by 0x52683B4: KSI_DataHash_create (hash.c:291)
==2608==    by 0x114FE1: hash_node_ksi (librsksi.c:769)
==2608==    by 0x11A5CE: rsksi_vrfy_nextRecExtract (librsksi_read.c:1654)
==2608==    by 0x10D03F: extractKSI (rsgtutil.c:1287)
==2608==    by 0x10EB33: processFile (rsgtutil.c:1555)
==2608==    by 0x10F168: main (rsgtutil.c:1817)
==2608==
==2608== 104 (40 direct, 64 indirect) bytes in 1 blocks are definitely lost in loss record 291 of 488
==2608==    at 0x4C267BB: calloc (vg_replace_malloc.c:593)
==2608==    by 0x117CF5: rsksi_tlvRecDecode (librsksi_read.c:741)
==2608==    by 0x117FBA: rsksi_tlvrd (librsksi_read.c:942)
==2608==    by 0x11917D: rsksi_getBlockParams (librsksi_read.c:1185)
==2608==    by 0x10CF87: extractKSI (rsgtutil.c:1252)
==2608==    by 0x10EB33: processFile (rsgtutil.c:1555)
==2608==    by 0x10F168: main (rsgtutil.c:1817)
==2608==
==2608== 128 (64 direct, 64 indirect) bytes in 2 blocks are definitely lost in loss record 303 of 488
==2608==    at 0x4C267BB: calloc (vg_replace_malloc.c:593)
==2608==    by 0x119337: rsksiHashstepFromKSI_DataHash (librsksi_read.c:1117)
==2608==    by 0x11A54D: rsksi_vrfy_nextRecExtract (librsksi_read.c:1631)
==2608==    by 0x10D03F: extractKSI (rsgtutil.c:1287)
==2608==    by 0x10EB33: processFile (rsgtutil.c:1555)
==2608==    by 0x10F168: main (rsgtutil.c:1817)
==2608==
==2608== 622 bytes in 10 blocks are definitely lost in loss record 383 of 488
==2608==    at 0x4C27A2E: malloc (vg_replace_malloc.c:270)
==2608==    by 0x5D61EC1: strdup (strdup.c:43)
==2608==    by 0x11ACFB: rsksi_errctxSetErrRec (librsksi_read.c:133)
==2608==    by 0x10D202: extractKSI (rsgtutil.c:1242)
==2608==    by 0x10EB33: processFile (rsgtutil.c:1555)
==2608==    by 0x10F168: main (rsgtutil.c:1817)
==2608==
==2608== 840 (552 direct, 288 indirect) bytes in 1 blocks are definitely lost in loss record 393 of 488
==2608==    at 0x4C267BB: calloc (vg_replace_malloc.c:593)
==2608==    by 0x10CDAE: extractKSI (rsgtutil.c:1171)
==2608==    by 0x10EB33: processFile (rsgtutil.c:1555)
==2608==    by 0x10F168: main (rsgtutil.c:1817)
==2608==
==2608== 2,445 (32 direct, 2,413 indirect) bytes in 1 blocks are definitely lost in loss record 430 of 488
==2608==    at 0x4C267BB: calloc (vg_replace_malloc.c:593)
==2608==    by 0x117D65: rsksi_tlvRecDecode (librsksi_read.c:801)
==2608==    by 0x117FBA: rsksi_tlvrd (librsksi_read.c:942)
==2608==    by 0x11917D: rsksi_getBlockParams (librsksi_read.c:1185)
==2608==    by 0x10CF87: extractKSI (rsgtutil.c:1252)
==2608==    by 0x10EB33: processFile (rsgtutil.c:1555)
==2608==    by 0x10F168: main (rsgtutil.c:1817)
==2608==
==2608== 1,237,431 (4,768 direct, 1,232,663 indirect) bytes in 1 blocks are definitely lost in loss record 488 of 488
==2608==    at 0x4C267BB: calloc (vg_replace_malloc.c:593)
==2608==    by 0x118C36: rsksi_vrfyConstruct_gf (librsksi_read.c:1349)
==2608==    by 0x10CBC9: extractKSI (rsgtutil.c:1106)
==2608==    by 0x10EB33: processFile (rsgtutil.c:1555)
==2608==    by 0x10F168: main (rsgtutil.c:1817)
==2608==
==2608== LEAK SUMMARY:
==2608==    definitely lost: 6,294 bytes in 21 blocks
==2608==    indirectly lost: 1,235,588 bytes in 25,973 blocks
==2608==      possibly lost: 0 bytes in 0 blocks
==2608==    still reachable: 11,640 bytes in 198 blocks
==2608==         suppressed: 0 bytes in 0 blocks
==2608== Reachable blocks (those to which a pointer was found) are not shown.
==2608== To see them, rerun with: --leak-check=full --show-reachable=yes
==2608==
==2608== For counts of detected and suppressed errors, rerun with: -v
==2608== ERROR SUMMARY: 11 errors from 11 contexts (suppressed: 8 from 6)

**Comment by rgerhards** [comment]
I strongly think this is is a purley cosmetic issue because this memory is freed upon program termination. It doesn't look like there is a real leak inside e.g. a loop, so that memory consumption really grows. The potential fix, I guess, will just release the memory a ms before the whole thing is released by the OS. For QA testing purposes, I still think it is worth getting this straight.
