### ISSUE TITLE
Extracting records from a signed log file creates a malformed record integrity proof

### ISSUE THREAD

**Issue by friedl** [rsyslog/rsyslog#805]
*Version:* rsgtutil 8.16.0

*Command:* rsgtutil <signedLogFile> --extract <linenumber(s)> --output <extractedLogFile> --publications-server <pubURL>

*Analyzing "extractedLogFile.ksisig" with gttlvdump:*
TLV[0905]:
  TLV[0800]:
    TLV[0801]:020456c57cd103010e03020375030203df03020f6f030103052101109a6323831efb6d186fd13ba88667efe0d2040961e6b3bfc9d1a157937841d606010107250423010a616e6f6e206874747000020a616e6f6e3a687474700003000407052c06ebd2f3f5
    TLV[0801]:020456c57cd103010e03020375030203df03020f6f052101540bf9dbd93116e0271db9e434389e5c4fd17634ba1641236a93c6609d029ce8060101072201010e031d03000c72656c6561736520746573740000000000000000000000000000072601010102210100000000000000000000000000000000000000000000000000000000000000000723022101000000000000000000000000000000000000000000000000000000000000000007230221010000000000000000000000000000000000000000000000000000000000000000082302210100000000000000000000000000000000000000000000000000000000000000000723022101bd241877dfa33d43b234418b340890591bcbed2d88109b39df94f3f5f9ad31b50723022101358824e2f8d5afe759f117799e1795a270c682f3d18dfcc7a8c3fc3dfac98f010823022101a2168d9f112517fb5e9b0fb28c58d94c9efa7c43a66959ae1d8ba884942f91e80723022101db8850b7a3c9e0127d02de7676da7978fd823c647e57ac2e79bd76217da37ded07230221010e0af9e1147da4f91fa8a47e236ac22b99c9334eca89e1258e398a136556efc40722010103031d0300024754000000000000000000000000000000000000000000000000
    TLV[0801]:020456c57cd103010e03020375030203df052101f93938cbfcfa207a77fa366858d37f0909e825fa2bddd27abfb2a87777485ca406010107260101070221010000000000000000000000000000000000000000000000000000000000000000072302210100000000000000000000000000000000000000000000000000000000000000000723022101f10a8a0ba2a471ac0d2af4a085c04bdc7a3fc748acce24deb58d580c2d13a08707230221014b7934ee92c5714379189bcdff523819afa5d4a273c201019776fc2cf61e1b090723022101000000000000000000000000000000000000000000000000000000000000000008230221010000000000000000000000000000000000000000000000000000000000000000072302210100000000000000000000000000000000000000000000000000000000000000000723022101ceaf3b94af753270f870348efe6460ac0866926abaec3676f3634bc432a3b75b0722010105031d0300024754000000000000000000000000000000000000000000000000
    TLV[0801]:020456c57cd103010e030203750521011c0ffc6ee1401749993bdafaac74071a0904955577e42cd5c766055ebf5d3b85060101072601010702210100000000000000000000000000000000000000000000000000000000000000000823022101794856849bd14006c8778565b5c35a17abf4e554e370a023af2440085c6d1cb707230221010000000000000000000000000000000000000000000000000000000000000000082302210138f72845339fc6862ce305515bc1b442bbf2448af25e9a529d67810e43a58fa307230221011f7709f0c55197125b3c560a0d3bc80072eb4e557cf38a1a418adba5f3cff39107230221010000000000000000000000000000000000000000000000000000000000000000072302210184fbef643d336db42b395a2af84b6d987030eb840e316e8f42495f6cf4ec126d0823022101d8c4a7df30463fbe8ef47e0b5c34f3e306c7661f276d4a4314570c790596c4da07230221014820590f32e7ae2f4a7e6148c5e1690e3bbacbbdb6fc0e1b1aac2ab591b5bb9b
    TLV[0801]:020456c57cd103010e0521017fd56913ac900df595816fb6d336f06e4ff1715e1476cca10b306dfc3f964148060101082601010d0221016ddfc15827097bd8f9c0374ef383c4f899406118180190f6586b68ecac063d1a072601012e022101975bf6ae991dfab6d0b536d6e5c593bbf0480ee482f2a939f9dfc4aba5ab0f700723022101441c1e90a684f3571727462d3181782e3a6c756243f1b0f6ace7024c3227cc20
    TLV[0802]:010456c57cd1020456c57cd10521019357c328da56562f8fe710fef474b3ec723a032c355f70f721c861980bba65fd08210137ecf5ce324c8701325f41dd4cbb5349a0a7e97377ccb003d883e114ff3c382c08210160bf6f4bd104f3523f13b890b7a81a2688b2a7a5f76439dfce1ac975ecc4604d082101f319a7e0fa6d8cdf60e71a58c2c1888aac253b444a5cdecd49c33209eee3ea9008210175fcbd0b37b5561e3bd4b83fa9445d2b7323944f4a10a1ab4402da06397fb70a082101deed4599b62d733d01fe2b0c1e3365465e2005e3ffb78e1d8bfbe5fa9acdcf3908210149a9bea01e22c5011d61be9530487c8bcd58964676a04d0e476b32e0d53b46f9082101a237744f5ecff9a81defe589b00657083e1e66304a250966dca25bba9ea3601008210131c5b0981918b776819a6519a95896fbfc48d210c3776595a6abce4442b95315082101251a8538382c5a3d0f21d85bab6f0c31f86cb560d9fa2ae108a1f5f6f41f33420821018543838b2df0adf2c74f0edd66e24e58a846ff6cf0f059700c51394c7870ccb5082101eb7eaeae6bb0b44fcf520fd5ad14866288bbfdcf69ff3fadca4e1be44e09a57608210136e2e89e8f3928f80a6d89ad666354e145473b2c6ff683f0796daa68f2004545082101e44f0a3ea272c03defc1825d3148f0dc4060cf6baf04f3acd0b9afa9ee52cad5082101a0698e6b45edeeaf9037e49f668114617ca60124f0fc416d017d06d78ca4295a082101a6f082b82280f3a6afb14c8e39b7f57860b857b70ca57afd35f40395eeb32458082101496fc0120d854e7534b992ab32ec3045b20d4bee1bfbe4564fd092ceafa08b72082101bb44fd36a5f3cdee7b5c6df3a6098a09e353335b6029f1477502588a7e37be00
    TLV[0805]:3029020456c57cd1042101f2c5cc6c114b453567d6bd30a875f489b0fb7372e1c84dc7bd26b903df597110800b01220116312e322e3834302e3131333534392e312e312e31310080020100033fa9531c697d6d999348531e1ecca6270a771ad2fb81916463b8291150df420c24d72b91ffea7edab34694440cc929a4d9c8dcfab89de07e867f8b454be28bedcd6c5d041de263e201277cf57d57b250d5a514cc34b45a4fb5782104ee1cdd5b450def7bdbeaf00e162ae48f27439771c35a9adbe740bc86b072027022ec9e84065820e99e94f23dd864c3c073f05cedc5da25f67cde08d66bca8249752177eecdaf48e058dfaa2324c1ea463cd62ecfe8aef6f987d80287e6f562efde18ea9b44238a2af268013d95dfe80ae0b66db3bb047e59248009f11fc210a71d3a1188217fa61afbba803a0ecedd0120f980eea0fdd0992eb36d1bf2eec2d236c0ce0304ceda4885
TLV[0907]: <-- NOT A COMPOSITE VALUE --> 01210172ca30af9f74e0496081e7d35ce3cac4f6d9b0dcfcc8cc093b5843dfe85b304f0326010100022101356b5ef76614433cefd2132b7138d3647f761e0a1d34a3166048e9741888a6f5022601010002210140746d37e11ed3a6c6aa7375d51dfaafe871f043be6c93bbc66147b7d26e75670226010100022101cc33b668a14b53b19c9f786d5cf83db655883a7405fd228a9553d4b9617820210226010101022101b702f597d817d07cea28c3b21afb81e2b2e6fcacba1ebbf3cbddcca0

**Comment by rgerhards** [comment]
closed via https://github.com/rsyslog/rsyslog/pull/821
