### ISSUE TITLE
not able to established connection with central server.

### ISSUE THREAD

**Issue by AS2015** [rsyslog/rsyslog#822]
Here i have two server: 1) centos based 2) ubuntu based.
I am trying to send logs from centos to ubuntu server using rsyslog. But between these two servers i am not seeing any connection. In message i am getting this type of error:  

'action 'action 7' suspended, next retry is Thu Feb 25 07:27:25 2016 [v8.16.0 try http://www.rsyslog.com/e/2007 ]'

**Comment by rgerhards** [comment]
This is most probably a configuration issue, not a code issue. Pleast take this to the rsyslog mailing list. Thanks.
