### ISSUE TITLE
rsgtutil: error in dump modus due to "unexpected tlv record"

### ISSUE THREAD

**Issue by rgerhards** [rsyslog/rsyslog#844]
I remember that one tlv record type was changed. Most probaly, rsgutil's dump modus was not updated in this regard.

**Comment by alorbach** [comment]
There is no automatic detection of KSI or GT signature files right now. So when dumping KSI signature files, rsgtutil uses GT api by default which results into dump failure. Using --api KSI parameter fixes the problem. But automatic detection by file ending would be a good solution to not run into problems like this again.

**Comment by rgerhards** [comment]
+1 for some kind of automatic detection
