### ISSUE TITLE
pid-file is written to /etc

### ISSUE THREAD

**Issue by mbiebl** [rsyslog/rsyslog#86]
Version: 8.2.2

I've compiled rsyslog 8.2.2 with the same settings as 7.6 and now suddenly rsyslog creates the pid file as /etc/rsyslog.pid

**Comment by theinric** [comment]
@mbiebl This actually introduces a regression.
You've fixed the path, but scrapped the reference to the SYSLOGD_PIDNAME macro, which at least the Fedora package was using to define the file name.

**Comment by mbiebl** [comment]
@theinric why would you want to change the pidfile name?

**Comment by mbiebl** [comment]
@theinric and if you want to change it, you can use _PATH_LOGPID.
I don't see a good reason to make this unnecessarily complex. So the simplification was intentional.

**Comment by theinric** [comment]
> why would you want to change the pidfile name?

Backwards compatibility.

> and if you want to change it, you can use _PATH_LOGPID.

Redefining something beginning with an underscore wouldn't immediately strike me as the right approach.

> I don't see a good reason to make this unnecessarily complex. So the simplification was intentional.

I wouldn't assume it's a regression if it was mentioned in the commit message.
Insignificant as it may be, this removed a piece of functionality without mentioning it anywhere.

**Comment by mbiebl** [comment]
2015-06-11 19:50 GMT+02:00 theinric <notifications@github.com>:

> and if you want to change it, you can use _PATH_LOGPID.
>
> Redefining something beginning with an underscore wouldn't immediately
> strike me as the right approach
>

Well, I didn't pick that name. It's historical baggage from sysklogd if I'm
not mistaken.

As said, I think a configure switch would probably be the cleanest
solution.
