### ISSUE TITLE
rsyslog stops reading journal data after journal file rotation

### ISSUE THREAD

**Issue by marknelson** [rsyslog/rsyslog#862]
On a CentOS 7.2 installation we have a repeatable problem in which rsyslogd 7.4.7 stops reading and processing journal data after the journal file is rotated. An application-specific log file that being maintained by rsyslog just stops with the last entry having a timestamp identical to the last timestamp before journald rotated its files.

In this particular implementation, the journal is writing to system.journal and user-1000.journal. When the journal rotates and creates new files, an `lsof` shows that rsyslog has system.journal open, but not user-1000.journal.

Sending a `systemctl restart` to rsyslogd does not fix the problem. Stopping the process and restarting it does fix the problem.

It seems like this could a problem in the journald API, but it's hard for me to verify that. The fact that the user-1000.journal file is not followed is the underlying cause, but I can't say why.

Interestingly, setting `SplitFiles=none` in journald.conf seems to be a good workaround - rsyslog doesn't have any problem following the changes in system.journal, just the user-specific one.

I couldn't find an existing or closed bug report on this. Any additional knowledge about it?
- Mark

**Comment by portante** [comment]
Can you post your full /etc/systemd/journal.conf and your /var/log/journal
or /run/log/journal directory listing?  Thanks,

-peter

**Comment by marknelson** [comment]
Yes, at the point where the problem has been recreated I have:

journald.conf:
```
[Journal]
Storage=persistent
SystemMaxUse=50M
```

```
ls -lrH /var/log/journal
/var/log/journal:
total 8.0K
drwxr-sr-x+ 2 root systemd-journal 4.0K Mar  9 07:36 911cb3ebce004b87ae8f8402f4000e5f/

/var/log/journal/911cb3ebce004b87ae8f8402f4000e5f:
total 26M
-rw-r-----+ 1 root systemd-journal 6.3M Mar  9 07:36 system@711faeeb9ca243a1a7107148cb384c5e-000000000130f252-00052d9cd582fc23.journal
-rw-r-----+ 1 root systemd-journal 6.3M Mar  9 07:38 system.journal
-rw-r-x---+ 1 root systemd-journal 6.3M Mar  9 07:36 user-1000@003d3a4fd3754ae5a0b4e59f3f6819c5-000000000130c0a2-00052d9cb8646cd7.journal*
-rw-r-x---+ 1 root systemd-journal 6.3M Mar  9 07:38 user-1000.journal*
```
At this point the last entry in my app-specfic log file being updated by rsyslog, (which journald should currently be writing to user-1000.journal), has  timestamp of 7:36:29, which is the timestamp on the rotated copy of user-1000.journal. lsof shows that rsyslog does NOT have an open file descriptor tu user-1000.journal, only to the rotated file.

If I stop and start rsyslog, it picks up in the right spot - adding all the entries from 7:38 forward to my app-specific log file.

- Mark

**Comment by portante** [comment]
And your rsyslog.conf contents, just to be complete?

**Comment by marknelson** [comment]
rsyslog.conf:
```
$ModLoad imuxsock # provides support for local system logging (e.g. via logger command)
$ModLoad imjournal # provides access to the systemd journal
$imjournalRatelimitInterval 0
$WorkDirectory /var/lib/rsyslog
$ActionFileDefaultTemplate RSYSLOG_TraditionalFileFormat
$IncludeConfig /etc/rsyslog.d/*.conf
$OmitLocalLogging on
$IMJournalStateFile imjournal.state

#### RULES ####

*.info;mail.none;authpriv.none;cron.none                /var/log/messages
authpriv.*                                              /var/log/secure
mail.*                                                  -/var/log/maillog
cron.*                                                  /var/log/cron
*.emerg                                                 :omusrmsg:*
uucp,news.crit                                          /var/log/spooler
local7.*                                                /var/log/boot.log
```
This conf file is included for our app-specific data. I had to obfuscate it slightly to avoid problems with my employer:
```
$EscapeControlCharactersOnReceive off
$umask 0000

############################################################
# Default Template for formatting the log output
############################################################
template(name="OldFormat" type="string" string="%$NOW%-%syslogseverity%,%syslogtag%%msg%\n")
template(name="TestFormat" type="string" string="%$day%-%timegenerated:1:3:date-rfc3164%-%$year% %timegenerated:12:23:date-rfc3339%,%syslogseverity%,%syslogtag%%msg%\n")

template(name="DevelopmentFormat" type="list") {
        property(name="timestamp" dateFormat="rfc3339")
        constant(value=":")
        property(name="syslogseverity")
        constant(value=":")
        property(name="hostname")
        constant(value=":")
        property(name="syslogtag")
        property(name="msg")
        constant(value="\n")
}

template(name="AlarmFormat" type="list") {
        property(name="timestamp" dateFormat="rfc3339")
        constant(value=":")
        property(name="syslogseverity")
        constant(value=":")
        property(name="hostname")
        constant(value=":")
        property(name="syslogtag")
        constant(value="[ALARM] --- ")
        property(name="msg")
        constant(value="\n")
}

############################################################
# Forward alarm messages to our custom handler
############################################################
Module(load="omprog")
if $programname == 'foo' and $syslogserverity <= '1' then
        action(type="omprog"
                binary="/opt/foo/alarms.py"
                template="DevelopmentFormat")

Module(load="bultin:omfile")
if $programname == 'foo' and $syslogseverity == '1' then
  action(type="omfile"
      dirCreateMode="0700"
      fileCreateMode="0644"
      file="/var/log/foo.log"
      template="AlarmFormat")

if $programname == 'foo' and $syslogseverity >= '2' and $syslogseverity <= '7' then
  action(type="omfile"
      dirCreateMode="0700"
      fileCreateMode="0644"
      file="/var/log/foo.log"
      template="DevelopmentFormat")

if $programname == 'foo' and $syslogseverity <= '7' then ~

```

**Comment by marknelson** [comment]
I have to retract my initial comment about the positive effect of `SplitFiles=non`. After more runtime, I see that this only delayed the break. 

One kind of strange thing to see when using lsof to debug the process. Check out the file descriptor number here - one of the input modules is on fd 653!
```
rsyslogd 16659 root    3w      REG  253,0   609468  77392959 /var/log/messages
rsyslogd 16659 root    4w      REG  253,0    27060  77392939 /var/log/cron
rsyslogd 16659 root    5r      REG  253,0  4194304  69020664 /var/log/journal/911cb3ebce004b87ae8f8402f4000e5f/system@711faeeb9ca243a1a7107148cb384c5e-0000000001331586-00052d9def0b0358.journal
rsyslogd 16659 root    8r      REG  253,0  6553600  72161706 /var/log/journal/911cb3ebce004b87ae8f8402f4000e5f/user-1000.journal
rsyslogd 16659 root    9r      REG  253,0  4194304  69729684 /var/log/journal/911cb3ebce004b87ae8f8402f4000e5f/system@711faeeb9ca243a1a7107148cb384c5e-0000000001332858-00052d9df7e64bf0.journal
rsyslogd 16659 root   11w      REG  253,0   771621  69020663 /var/log/foo.log
rsyslogd 16659 root  141r      REG  253,0  4194304  68214407 /var/log/journal/911cb3ebce004b87ae8f8402f4000e5f/system@711faeeb9ca243a1a7107148cb384c5e-0000000001333b36-00052d9e02d96c44.journal
rsyslogd 16659 root  653r      REG  253,0  4194304  69161520 /var/log/journal/911cb3ebce004b87ae8f8402f4000e5f/system@711faeeb9ca243a1a7107148cb384c5e-0000000001334e0a-00052d9e14b924ce.journal
```

**Comment by portante** [comment]
I am not sure about what rsyslog is doing with the journal interfaces.  It
seems okay on the surface, but it might need an update for this, as it does
not match what `sd_journal_wait()` does exactly.

**Comment by portante** [comment]
Sorry to vacillate, upon reading both journalctl, sd_journal_wait(), and
what imjournal does, it would seem this will happen journalctl in follow
mode as well, as i dont' see much of a difference between them.

Have you tried using journalctl -f to watch the journal directly?

-peter

**Comment by portante** [comment]
Hi Mark,

On my Fedora 21 box I was not able to reproduce this behavior.  I have
rsyslog 7.4.10-5.fc21.

First, I applied your journal.conf settings, and your rsyslog.conf settings.

I then create a simple python program to generate 2K random strings:

#!/usr/bin/python
import random, string
print ''.join(random.SystemRandom().choice(string.ascii_uppercase +
string.digits) for _ in range(2048))


Then I used systemd-cat to send it so that I would receive a per-user
journal file (only 1,000 at a time since the default journal rate is 1,000
messages in 30 seconds):

for i in {0..999} ; do ./random_str.py | systemd-cat ; done


Then in one window I ran, tail -f /var/log/messages, and in another,
journalctl --follow.

I caused three file rotations of the user journal file, and all logs were
processed.

We might need another variable from your environment.

-peter

**Comment by marknelson** [comment]
Well if journalctl and rsyslog are using identical code, we are in a mess, because they aren't exhibiting the same behavior.

I actually do just that for my test. I have `journalctl -f -t foo` running side by side with `tail -F /var/log/foo.log` in the other. Never a hiccup with journalctl, but foo.log, being created by rsyslogd, will stop dead in its tracks after some, but not all, rotation of journal files.

Of additional interest, foo.log will start growing again after being stalled on a subsequent rotation. (I'm hammering the log with thousands of messages per second, so I am rotating frequently.)

If I run rsyslog from the command line in with -dn, when things are working properly its spewing data out to the screen - without knowing much about internals it doesn't really mean much. When the rotation occurs and things break, it completely stops putting anything out to the screen, except it wakes up once every 30 seconds, burps out a few messages, and then goes back to sleep.

- Mark

**Comment by rgerhards** [comment]
I am not a journal expert, but it looks like there is a problem with event notifications inside the journal. Have a look at this man page:

https://www.freedesktop.org/software/systemd/man/sd_journal_get_fd.html

A quicky check reveals that rsyslog's imjournal uses poll event notification via ```sd_journal_get_fd()``` and ```sd_journal_get_events()``` whereas journalctl uses a ```sd_journal_wait()```. I guess the difference is rooted here.

I further guess that we could change imjournal to used ```sd_journal_wait()``` as well, but IMHO the problem is rooted in journal and so it is questionable if that work-around will be lasting. I especially think this as you say rsyslog gets awaken at the next file rotation.

For the sake of simplicity, we could probably replace pollJournal with sd_journal_wait, but I am not sure if that would cause any backwards compatibility issues.

**Comment by marknelson** [comment]
Thanks Rainer for looking - it sounds as though this is not something with an easy workaround. 

I will modify our configuration to use imuxcocket and instruct journal to forward to syslog. I think that will bypass the problem, and the negatives are minimal I hope.

- Mark

**Comment by rgerhards** [comment]
@marknelson would you be willing to test imjournal if I make any changes?

**Comment by marknelson** [comment]
Yes, absolutely - I am pretty confident that the problem is reproducible on demand. 

As long as it can be installed on Centos 7.2.

**Comment by marknelson** [comment]
I have just one additional observation on this, and it probably points to a problem in journald. It might be useful for anyone trying to reproduce the problem.

This problem only occurs when journal's rate limiting is turned on. When it is turned off by setting RateLimitInterval to 0, the problem doesn't seem to ever occur.

Further, the problem doesn't occur unless you are actually triggering rate limiting. In my test I'm sending tons of messages, so that journald is going into rate limiting constantly, and journal file rotation is happening every couple of minutes (usually with a maximum size value of 25M or 50M).

- Mark

**Comment by portante** [comment]
@rgerhards, I am not sure I see the same thing.  `sd_journal_wait()` also uses poll() and does the same thing.  At least with the version I am looking at.

I am not seeing a difference in the behavior yet.

@marknelson, what version of systemd to you have on that box?

**Comment by portante** [comment]
@marknelson, journal's default rate limiting is 1,000 messages in 30s, at least looking at my box.

What do you have for rate limiting with rsyslog.conf for imjournal?  I believe by default, imjournal's ratelimiting is 20,000 messages in a 600 second period.

**Comment by marknelson** [comment]
>What do you have for rate limiting with rsyslog.conf for imjournal? 
>I believe by default, imjournal's ratelimiting is 20,000 messages in a 600 second period.

For the purposes of reproducing the problem, I have it set to 0. If we get past this problem and use imjournal in our production systems I expect we will probably keep it at 0.

It really doesn't make much sense to me to have rate control in two places for the same stream. So I have rate control turned on in journal at the default, and turned off for imjournal.

**Comment by marknelson** [comment]
>what version of systemd to you have on that box?

systemd.x86_64                             219-19.el7_2.4             @updates

**Comment by portante** [comment]
@marknelson, I'd like to see a debug trace when it fails, as I just can't reproduce that failure in my environment, though I don't have a centos 7.2 to try an exact match at the moment.

**Comment by rgerhards** [comment]
2016-03-10 16:56 GMT+01:00 Mark Nelson <notifications@github.com>:

> What do you have for rate limiting with rsyslog.conf for imjournal?
> I believe by default, imjournal's ratelimiting is 20,000 messages in a 600
> second period.
>
> For the purposes of reproducing the problem, I have it set to 0. If we get
> past this problem and use imjournal in our production systems I expect we
> will probably keep it at 0.
>
> It really doesn't make much sense to me to have rate control in two places
> for the same stream. So I have rate control turned on in journal at the
> default, and turned off for imjournal.
>
>
>
Just as a side-note, we added the ratelimit to imjournal because we had
other occasions of journal errors that hammered the machine until death
with repeating messages. Made even big news at that time. Just so that you
know.

Rainer

**Comment by marknelson** [comment]
> I'd like to see a debug trace when it fails, as I just can't reproduce that failure 
>in my environment, though I don't have a centos 7.2 to try an exact match at 
>the moment.

@portante can you tell me how you want to set up and collect the trace? Are you talking about running rsyslog -dn and collecting that?

**Comment by marknelson** [comment]
> Made even big news at that time. Just so that you

@rgerhards - yes that makes sense. I guess the smart thing to do is rate limit imjournal somewhere above the rate limit in journal.conf - that way it only kicks in if there is a failure in journal that spews.

**Comment by portante** [comment]
@marknelson, if you can do `rsyslog -d1` and capture it to the point of the stop, that would be great.  I am going to try to get a CentOS 7.2 environment setup here.  BTW, is this a VM or baremetal?

**Comment by marknelson** [comment]
>BTW, is this a VM or baremetal?

It's a bare metal Cisco UCS server.

Working on the capture right now.

**Comment by marknelson** [comment]
The attached log is from `rsyslog -dn` (-d1 is not a legal command line in this version.

The last line that was copied to the application-specific log by rsyslogd was at 10:49:15:
```
2016-03-10T10:49:15.769705-05:00:5:s9500dev-3:abr-nge[67214]:THRIFT:Received Stop, uuid 12345
```
journal rotated the file at 10:49.

The last line appears on the rsyslogd output here:
```
4955.778813859:7f780fea1700: omfile: start of data: '2016-03-10T10:49:15.769705-05:00:5:s9500dev-3:abr-nge[67214]:THRIFT:Received Stop, uuid 12345
'
```
There are just a few more bits of output from rsyslogd after that, then it stopped. After five minutes, not another bit of log data.

Unfortunately, I did not catch the log when it came back to life on the next rotation. 

[rsyslogd.txt](https://github.com/rsyslog/rsyslog/files/167810/rsyslogd.txt)

**Comment by portante** [comment]
@marknelson, you apparently have a typ-o in your rsyslog.conf, look for "syslogserverity", should be "syslogseverity".

**Comment by portante** [comment]
@marknelson, we need to instrument imjournal better with debug statements to see what it is doing.  Right now we just have debug statements on the error paths, and at least in this snippet we don't have any errors.

**Comment by marknelson** [comment]
>you apparently have a typ-o in your rsyslog.conf, look for "syslogserverity", should be "syslogseverity".

@portante, thanks that has been sitting in that config file for some time without anyone noticing :-)

**Comment by davidelang** [comment]
hmm, I wonder if this is related to this bug reported to redhat (where imjournal stops reading data if the time is moved into the past)
https://bugzilla.redhat.com/show_bug.cgi?id=1088021

**Comment by lhorace** [comment]
Hi,

I will also be subsribing to this bug as well as rsyslog has stop logging here on a Oracle Linux 7.2 baremetal box. I suspect it stop logging when I noticed an incorrect timezone set and I updated the timezone via timedatectl. 

P.S. It would be diffult to debug this issue on a production box alto I could quickly setup an Linux Container of Oracle Linux 7.2. Or atleast an Qemu machine at the very least.

Regards,
Horace

**Comment by lhorace** [comment]
Hmm, interestly enough, in my case. This may not be a imjournal related bug, upon investigating dmesg on another unrelated matter, I stumbled onto this:

```
[3836786.946893] systemd-journald[8442]: Failed to write entry (10 items, 351 bytes), ignoring: Cannot assign requested address
[3836786.947075] systemd-journald[8442]: Failed to write entry (10 items, 465 bytes), ignoring: Cannot assign requested address
[3836786.947238] systemd-journald[8442]: Failed to write entry (10 items, 465 bytes), ignoring: Cannot assign requested address
[3836786.947393] systemd-journald[8442]: Failed to write entry (10 items, 474 bytes), ignoring: Cannot assign requested address
[3836786.947548] systemd-journald[8442]: Failed to write entry (10 items, 474 bytes), ignoring: Cannot assign requested address
[3836786.947791] systemd-journald[8442]: Failed to write entry (10 items, 305 bytes), ignoring: Cannot assign requested address
[3836786.947979] systemd-journald[8442]: Failed to write entry (10 items, 323 bytes), ignoring: Cannot assign requested address
[3836786.948170] systemd-journald[8442]: Failed to write entry (10 items, 287 bytes), ignoring: Cannot assign requested address
[3836786.948399] systemd-journald[8442]: Failed to write entry (10 items, 307 bytes), ignoring: Cannot assign requested address
[3836786.948554] systemd-journald[8442]: Failed to write entry (10 items, 326 bytes), ignoring: Cannot assign requested address

[3836786.948745] systemd-journald[8442]: Failed to write entry (10 items, 289 bytes), ignoring: Cannot assign requested address
```

This particular issue seems to be related to this bug https://bugzilla.redhat.com/show_bug.cgi?id=1292447. Where aparently fixes have been backported to systemd and currently in testing. However, in the mean time, I've already switched over to imuxsocket and configured journald to send messages to syslog.

Regards,
Horace

**Comment by rgerhards** [comment]
looks like this was fixed externally in journal - if not, please reopen/repost
