### ISSUE TITLE
 cryptic error message on disk queue corruption

### ISSUE THREAD

**Issue by livelace** [rsyslog/rsyslog#868]
Hello.

My config:

ruleset(name="linux") {
  action(type="omelasticsearch"
    server="elastic.livelace.ru"
    serverport="9200"
    template="system"
    searchIndex="linux"
    searchType="events"
    queue.type="disk"
    queue.size="10000000"
    queue.filename="linux"
    queue.maxdiskspace="5g"
    queue.saveonshutdown="on"
    action.resumeretrycount="-1"
  )
}

ruleset(name="dns") {
  action(type="omelasticsearch"
    server="elastic.livelace.ru"
    serverport="9200"
    template="passivedns"
    searchIndex="dns"
    searchType="queries"
    queue.type="disk"
    queue.size="10000000"
    queue.filename="dns"
    queue.maxdiskspace="5g"
    queue.saveonshutdown="on"
    action.resumeretrycount="-1"
  )
  #action(type="omfile"
  #  template="passivedns"
  #  file="/tmp/dns.log"
  #)
} 

[root@bb ~]# ls -l /var/lib/rsyslog/*.qi            
-rw------- 1 root root 485 Feb 18 00:23 /var/lib/rsyslog/dns.qi
-rw------- 1 root root 500 Feb 18 00:23 /var/lib/rsyslog/linux.qi

If Rsyslog can't deliver data to Elastic then after some count of day, I see:

Mar 10 16:11:49 bb rsyslogd-2040: fatal error on disk queue 'action 1 queue', emergency switch to direct mode [try http://www.rsyslog.com/e/2040 ]
Mar 10 16:11:49 bb rsyslogd-2040: fatal error on disk queue 'action 2 queue', emergency switch to direct mode [try http://www.rsyslog.com/e/2040 ]

I found many mentions about this problem, like this  http://kb.monitorware.com/viewtopic.php?p=26298#p26298

**Comment by rgerhards** [comment]
I agree that the error message is a bit cryptic, I will see that I fix this within the next days. Other than that, everything works as expected in cases where the queue files are corrupt.

**Comment by livelace** [comment]
Note that the messages were not transferred as well. This is not only a message about the problem, but also a problem. Queue files were not damaged. Server has enough space.

**Comment by rgerhards** [comment]
Well, they are damaged. Else you would not get that error. If you think I
am wrong, please provide a debug log

Sent from phone, thus brief.
Am 10.03.2016 15:24 schrieb "Oleg Popov" <notifications@github.com>:

**Comment by livelace** [comment]
What causes of damage of queue files ? Not enough space, terminated main process, kit of plugins ?

**Comment by livelace** [comment]
Maybe, I should give these *.qi files for inspection ?

**Comment by rgerhards** [comment]
damage to queue files can be caused by a myriad of reasons, including those that you mention (where it is "[abnormally] terminated main process". The .qi files alone do not help, if we need to do a lab, we need the full content. Please note that I am currently short on time for labs as higher priority things are in the queue. So for a quick look, the debug log would be better -- or you wait until I have fixed the error message to be a bit more descriptive. I think that should be doable until early next week at latest.

**Comment by livelace** [comment]
Ok, I will try get more verbose details and logs.

**Comment by rgerhards** [comment]
Just in case you haven't seen it. This shows how to obtain a debug log:

http://www.rsyslog.com/doc/v8-stable/troubleshooting/

**Comment by livelace** [comment]
Ok, I turned on debug logging (it is very fast grow) and I will be watching during several days. I want mention, that it is lxc container, data does not transfer to server with Elastic service, we just accumulate data in disk queue.

**Comment by livelace** [comment]
Ok, with debug mode all work fine so far. I tried stop service, stop container, begin data transfer to server, and all good. But, I don't lose hope for error appearing :)

**Comment by livelace** [comment]
Ok, caught it.

Mar 18 16:39:30 bb rsyslogd-2040: fatal error on disk queue 'action 1 queue', emergency switch to direct mode [try http://www.rsyslog.com/e/2040 ]


[root@bb ~]# grep 'fatal error on disk queue' ~/rsyslog.debug -B 20 -A 20
8370.459205110:7fe783971700: DeleteProcessedBatch: we deleted 128 objects and enqueued 0 objects
8370.459234268:7fe783971700: doDeleteBatch: delete batch from store, new sizes: log 20, phys 101
8370.459408746:7fe783971700: strm 0x7fe78b989120: file 12 read 4096 bytes
8370.459554183:7fe783971700: strm 0x7fe78b989120: file 12 read 2459 bytes
8370.459645303:7fe783971700: strm 0x7fe78b989120: file 12 read 0 bytes
8370.459670242:7fe783971700: strm 0x7fe78b989120: file 12 EOF
8370.459691357:7fe783971700: strm 0x7fe78b989120: file 12(linux) closing
8370.459780704:7fe783971700: file '/var/lib/rsyslog/linux.00000405' opened as #-1 with mode 384
8370.459833403:7fe783971700: strm 0x7fe78b989120: open error 2, file '/var/lib/rsyslog/linux.00000405': No such file or directory
8370.459861542:7fe783971700: objDeserialize error -2040 during header processing - trying to recover
8370.459892934:7fe783971700: file '/var/lib/rsyslog/linux.00000405' opened as #-1 with mode 384
8370.459917392:7fe783971700: strm 0x7fe78b989120: open error 2, file '/var/lib/rsyslog/linux.00000405': No such file or directory
8370.459939003:7fe783971700: deserializer has possibly been able to re-sync and recover, state -2040
8370.459960886:7fe783971700: action 1 queue: error -2040 dequeueing element - ignoring, but strange things may happen
8370.459979458:7fe783971700: action 1 queue: got 'file not found' error -2040, queue defunct
8370.459995704:7fe783971700: strm 0x7fe78b986b00: file 10(linux) closing
8370.460011616:7fe783971700: strm 0x7fe78b986b00: file 10(linux) flush, buflen 0 (no need to flush)
8370.460032668:7fe783971700: strm 0x7fe78b989120: file -1(linux) closing
8370.460048316:7fe783971700: strm 0x7fe78b987e60: file 11(linux) closing
8370.460151681:7fe783971700: strmCloseFile: deleting '/var/lib/rsyslog/linux.00000404'
8370.460277238:7fe783971700: Called LogMsg, msg: fatal error on disk queue 'action 1 queue', emergency switch to direct mode
8370.460478175:7fe783971700: main Q: qqueueAdd: entry added, size now log 1, phys 1 entries
8370.460508710:7fe783971700: main Q: EnqueueMsg advised worker start
8370.460525457:7fe783971700: regular consumer finished, iret=-2183, szlog 0 sz phys 0
8370.460544557:7fe783971700: action 1 queue:Reg: Worker thread 7fe78b956160, terminated, num workers now 0
8370.460569645:7fe78096b700: wti 0x7fe78b98ef80: worker awoke from idle processing
8370.460613946:7fe78096b700: DeleteProcessedBatch: we deleted 0 objects and enqueued 0 objects
8370.460635159:7fe78096b700: doDeleteBatch: delete batch from store, new sizes: log 1, phys 1
8370.460654695:7fe78096b700: processBatch: batch of 1 elements must be processed
8370.460680460:7fe78096b700: scriptExec: batch of 1 elements, active (nil), active[0]:1
8370.460695909:7fe78096b700:     IF
8370.460738902:7fe78096b700:           var 'programname'
8370.460822838:7fe78096b700:         ==
8370.460887930:7fe78096b700:           string 'passivedns'
8370.461009367:7fe78096b700:       AND
8370.461084448:7fe78096b700:           var 'msg'
8370.461194599:7fe78096b700:         CONTAINS
8370.461286178:7fe78096b700:           string 'IN'
8370.461440346:7fe78096b700: eval expr 0x7fe78b9553c0, type 'AND'
8370.461461300:7fe78096b700: eval expr 0x7fe78b96cc50, type 'CMP_EQ'
8370.461482926:7fe78096b700: eval expr 0x7fe78b96cd70, type 'V[86]'
--
8370.467836308:7fe78096b700: omelasticsearch: pData replyLen = '140'
8370.467873766:7fe78096b700: omelasticsearch: pData reply: '{"_index":"linux","_type":"events","_id":"AVOJ89Agj1bbM9Fr9sUg","_version":1,"_shards":{"total":1,"successful":1,"failed":0},"created":true}'
8370.467907740:7fe78096b700: omelasticsearch: no local error logger defined - ignoring ES error information
8370.467931324:7fe78096b700: omelasticsearch: result doAction: 0 (bulkmode 0)
8370.467961188:7fe78096b700: Action 0x7fe78b96dec0 transitioned to state: rdy
8370.467983168:7fe78096b700: action 0x7fe78b96dec0 call returned 0
8370.468005997:7fe78096b700: scriptExec: batch of 1 elements, active (nil), active[0]:1
8370.468026471:7fe78096b700:     PRIFILT '*.info;mail.none;authpriv.none;cron.none'
8370.468082952:7fe78096b700:     pmask: 7F 7F  X 7F 7F 7F 7F 7F 7F  X  X 7F 7F 7F 7F 7F 7F 7F 7F 7F 7F 7F 7F 7F 7F 7F
8370.468688719:7fe78096b700: batch: item 0 PRIFILT 1
8370.468709386:7fe78096b700: scriptExec: batch of 1 elements, active 0x7fe76c0008e0, active[0]:1
8370.468729101:7fe78096b700:     ACTION 0x7fe78b980220 [builtin:omfile:/var/log/messages]
8370.468786773:7fe78096b700: RRRR: execAct [builtin:omfile]: batch of 1 elements, active 0x7fe76c0008e0
8370.468808232:7fe78096b700: Called action(NotAllMark), processing batch[0] via 'builtin:omfile'
8370.468828558:7fe78096b700: Called action(Batch), logging to builtin:omfile
8370.468852075:7fe78096b700: submitBatch: enter, nElem 1
8370.468872862:7fe78096b700: tryDoAction 0x7fe78b980220, pnElem 1, nElem 1
8370.468893579:7fe78096b700: Action 0x7fe78b980220 transitioned to state: itx
8370.468913327:7fe78096b700: entering actionCalldoAction(), state: itx
8370.468934242:7fe78096b700: file to log to: /var/log/messages
8370.468954665:7fe78096b700: omfile: start of data: 'Mar 18 16:39:30 bb rsyslogd-2040: fatal error on disk queue 'action 1 queue', emergency switch to direct mode [try http://www.rs'
8370.468975927:7fe78096b700: write to stream, pData->pStrm 0x7fe76c000a60, lenBuf 147
8370.468997733:7fe78096b700: action 0x7fe78b980220 call returned -2121
8370.469019549:7fe78096b700: strm 0x7fe76c000a60: file 1(messages) flush, buflen 147
8370.469040818:7fe78096b700: strmPhysWrite, stream 0x7fe76c000a60, len 147
8370.469108706:7fe78096b700: strm 0x7fe76c000a60: file 1 write wrote 147 bytes
8370.469132206:7fe78096b700: Action 0x7fe78b980220 transitioned to state: rdy
8370.469154153:7fe78096b700: scriptExec: batch of 1 elements, active (nil), active[0]:1
8370.469174940:7fe78096b700:     PRIFILT 'authpriv.*'
8370.469231262:7fe78096b700:     pmask:  X  X  X  X  X  X  X  X  X  X FF  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X
8370.469819071:7fe78096b700: batch: item 0 PRIFILT 0
8370.469839574:7fe78096b700: scriptExec: batch of 1 elements, active 0x7fe76c0008e0, active[0]:0
8370.469859209:7fe78096b700:     ACTION 0x7fe78b980b30 [builtin:omfile:/var/log/secure]
8370.469916106:7fe78096b700: RRRR: execAct [builtin:omfile]: batch of 1 elements, active 0x7fe76c0008e0
8370.469936819:7fe78096b700: Called action(Batch), logging to builtin:omfile
8370.469957560:7fe78096b700: submitBatch: enter, nElem 1
8370.469977953:7fe78096b700: tryDoAction 0x7fe78b980b30, pnElem 1, nElem 1
8370.469999255:7fe78096b700: scriptExec: batch of 1 elements, active (nil), active[0]:1
8370.470019467:7fe78096b700:     PRIFILT 'mail.*'
8370.470074904:7fe78096b700:     pmask:  X  X FF  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X
8370.470631869:7fe78096b700: batch: item 0 PRIFILT 0

**Comment by livelace** [comment]
[root@bb ~]# pidof rsyslogd
14666
[root@bb ~]# ps -p 14666 -o etime=
 3-01:53:20
[root@bb ~]#

**Comment by rgerhards** [comment]
mmhhh.. that is bad. If you look at the debug log, a queue file is missing:
```open error 2, file '/var/lib/rsyslog/linux.00000405': No such file or directory```
At that stage, we have indeed lost because we cannot continue processing the queue. Maybe we can find some more insight when you search for that file name inside the debug log and we check what happened when it was created. If your debug log is less than 8..10GB of data, you can also send me a copy and I'll dig though it.

**Comment by livelace** [comment]
I sent you email with link.

**Comment by rgerhards** [comment]
mhhh, I don't find the mail. Can you tell me what account you sent it from or some other information (like part of the subject or link) that helps me search for it. Thx.

**Comment by livelace** [comment]
Hello. Email from your profile. Subject was "cryptic error message on disk queue corruption #868"

**Comment by livelace** [comment]
Any news ?

**Comment by rgerhards** [comment]
I have now checked the debug log, and it looks somehwat mysterious. Everything works fine, old files are read and new ones created, unless file 404 is being created. Then, a bit later, the reader tries to switch to 405, which is not yet present. The question now is why the reader thinks it should switch files. One idea is that the .qi file is corrupt and stating a too-large number of messages in the queue than there are actually. Unfortunately, the debug instrumentation is insufficient to tell me if that is the case.

So in order to go forward, I would need to add more debug instrumentation. Could you build a special branch from source and use it?

**Comment by livelace** [comment]
Yes, I can do this. If you can send command line arguments which necessary for compiling - it will be perfect.

**Comment by livelace** [comment]
*arguments for full debugging

**Comment by rgerhards** [comment]
Excellent. But I need to create the instrumentation first. Actually, I got the idea that I can also test with a deliberatly malformed .qi file, see how it works, and also see that I can emit proper error messages in those cases. I guess that would be the best thing to work on.

Note that rsyslog has some dependencies. This link might be helpful: http://www.rsyslog.com/doc/master/installation/install_from_source.html

I'll keep you posted, but it may take a short while.

**Comment by rgerhards** [comment]
@livelace I can reproduce the failure if I deliberately corrupt the queue size inside the .qi file, so the test that I added (commit ref above). So the root cause is a corrupt .qi file. I'll now see that I at least get a better error message out of the system. The good news is that I do not need your help while trying to implement this.

**Comment by livelace** [comment]
This is just in time. Ok, I wait the fix. Thanks for your work.

**Comment by rgerhards** [comment]
I just posted the path. Early tests look good. If you give it a try, please report back.

**Comment by davidelang** [comment]
Is there documentation of what the contents of the .qi file mean? it's text, but there's not much explanation of what the different numbers mean (are they byte counts, message counts, etc). If it's documented in the code, it would probably be useful to add a pointer to the file it's in to the troubleshooting page.

**Comment by erpadmin** [comment]
I am getting this error showing up in systemctl status on RHEL7
"rsyslogd[11593]: fatal error on disk queue 'action 0 queue[DA]', emergency switch to direct mod...2040 ]"

ours started occuring after maintenance of a large amount of boxes, not sure if the influx of activity had a hand in this or just the updates themselves on the syslog server

is there a workaround to rid of the message?

**Comment by davidelang** [comment]
move the corrupted queue files somewhere else so they aren't in place when 
rsyslog starts.

you can recreate the missing .qi files and then rsyslog can read them again.
