### ISSUE TITLE
configure: mmgrok requires grok.h

### ISSUE THREAD

**Issue by Whissi** [rsyslog/rsyslog#871]
When `--enable-mmgrok` is set, configure only checks for [glibc](https://github.com/rsyslog/rsyslog/blob/master/configure.ac#L971-L987) but we need to check for _grok.h_, too:

```
Making all in contrib/mmgrok
make[2]: Entering directory '/var/tmp/portage/app-admin/rsyslog-8.17.0/work/rsyslog-8.17.0/contrib/mmgrok'
/bin/sh ../../libtool  --tag=CC   --mode=compile x86_64-pc-linux-gnu-gcc -DHAVE_CONFIG_H -I. -I../..  -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I../../runtime -I../.. -I../../grammar  -I/usr/include/libfastjson -W -Wall -Wformat-security -Wshadow -Wcast-align -Wpointer-arith -Wmissing-format-attribute -Werror=implicit-function-declaration -pthread   -O2 -pipe -march=ivybridge -mtune=ivybridge -mno-xsaveopt -c -o mmgrok_la-mmgrok.lo `test -f 'mmgrok.c' || echo './'`mmgrok.c
libtool: compile:  x86_64-pc-linux-gnu-gcc -DHAVE_CONFIG_H -I. -I../.. -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I../../runtime -I../.. -I../../grammar -I/usr/include/libfastjson -W -Wall -Wformat-security -Wshadow -Wcast-align -Wpointer-arith -Wmissing-format-attribute -Werror=implicit-function-declaration -pthread -O2 -pipe -march=ivybridge -mtune=ivybridge -mno-xsaveopt -c mmgrok.c  -fPIC -DPIC -o .libs/mmgrok_la-mmgrok.o
mmgrok.c:16:18: fatal error: grok.h: No such file or directory
compilation terminated.
Makefile:520: recipe for target 'mmgrok_la-mmgrok.lo' failed
make[2]: *** [mmgrok_la-mmgrok.lo] Error 1
```

**Comment by mostolog** [comment]
I can confirm this with 8.22. perhaps I'm missing a grok-dev package or something like that? Maybe grok.h path isn't properly set on includes.

**Comment by mostolog** [comment]
On Ubuntu 16.04 installing libgrok-dev results in 
> /usr/include/grok.h:7:18: fatal error: pcre.h: No such file or directory

Installing libpcre3-dev
> /usr/include/grok.h:8:20: fatal error: tcutil.h: No such file or directory

After installing libtokyocabinet-dev
> mmgrok.c:17:18: fatal error: glib.h: No such file or directory

After libglib2.0-dev
> make[2]: Entering directory '/rsyslog/grammar'
>   YACC     grammar.c
> ../ylwrap: line 176: yacc: command not found

...https://www.youtube.com/watch?v=geVYIHOat5o ...

So, after reading http://stackoverflow.com/questions/15287765/error-compiling-grok, I ended installing these:
> libgrok-dev libglib2.0-dev bison ctags flex gperf libevent-dev libpcre3-dev libtokyocabinet-dev libgrok1

And that, at least, made make work.

**Comment by Whissi** [comment]
Please tell us where you got rsyslog from (git clone, GitHub release, rsyslog.com...).

**Comment by mostolog** [comment]
From http://www.rsyslog.com/files/download/rsyslog/rsyslog-8.22.0.tar.gz

**Comment by Whissi** [comment]
That's interesting. You shouldn't need flex (YACC) when building from official release tarball. Only required when building from git*.
