### ISSUE TITLE
omczmq: Requires >zeromq-3.2.3

### ISSUE THREAD

**Issue by Whissi** [rsyslog/rsyslog#872]
I'll get the following error when I build rsyslog with `--enable-omczmq`:

```
Making all in contrib/omczmq
make[2]: Entering directory '/var/tmp/portage/app-admin/rsyslog-8.17.0/work/rsyslog-8.17.0/contrib/omczmq'
/bin/sh ../../libtool  --tag=CC   --mode=compile i686-pc-linux-gnu-gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I../..  -I../../runtime -I../.. -I../../grammar  -I/usr/include/libfastjson  -W -Wall -Wformat-security -Wshadow -Wcast-align -Wpointer-arith -Wmissing-format-attribute -Werror=implicit-function-declaration -pthread    -O2 -march=i686 -pipe -c -o omczmq_la-omczmq.lo `test -f 'omczmq.c' || echo './'`omczmq.c
libtool: compile:  i686-pc-linux-gnu-gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I../.. -I../../runtime -I../.. -I../../grammar -I/usr/include/libfastjson -W -Wall -Wformat-security -Wshadow -Wcast-align -Wpointer-arith -Wmissing-format-attribute -Werror=implicit-function-declaration -pthread -O2 -march=i686 -pipe -c omczmq.c  -fPIC -DPIC -o .libs/omczmq_la-omczmq.o
omczmq.c: In function ‘initCZMQ’:
omczmq.c:209:4: error: implicit declaration of function ‘zsock_set_zap_domain’ [-Werror=implicit-function-declaration]
    zsock_set_zap_domain(pData->sock, "global");
    ^
omczmq.c:210:4: error: implicit declaration of function ‘zsock_set_curve_server’ [-Werror=implicit-function-declaration]
    zsock_set_curve_server(pData->sock, 1);
    ^
omczmq.c:254:4: error: implicit declaration of function ‘zsock_set_curve_serverkey’ [-Werror=implicit-function-declaration]
    zsock_set_curve_serverkey (pData->sock, server_key);
    ^
cc1: some warnings being treated as errors
Makefile:520: recipe for target 'omczmq_la-omczmq.lo' failed
make[2]: *** [omczmq_la-omczmq.lo] Error 1
```

I was using _net-libs/zeromq-3.2.3_. After I upgraded to _zeromq-4.1.1_ the error was gone.

So it looks like we need to enforce _>zeromq-3.2.3_ in _configure_ (currently we only check for _czmq_ version).

**Comment by taotetek** [comment]
So - the encryption support definitely requires zeromq 4. I could modify the plugins so that they still build against zeromq 3 but disable the option for CURVE authentication / encryption.

**Comment by Whissi** [comment]
If you ask me I would only adjust the configure check and enforce >=zeromq-4...

Not sure if you still need to support zeromq-3. Can you disable CURVE only for people using zeromq-3?

**Comment by rgerhards** [comment]
@taotetek do we have a plan no how to tackle this? For now, I will just remove the milestone.

**Comment by taotetek** [comment]
@rgerhards I can see if I can get to it today!  Time got away from me.  @Whissi it would be my preference to just support zeromq stable as well - zeromq 3 is quite old at this point.

**Comment by rgerhards** [comment]
@taotetek If you can make it, I'll see that I merge it. I am also struggeling with a lib issue, so I cannot craft the candidate tarball today in any case.

**Comment by taotetek** [comment]
@rgerhards ok - we can bump it to next release if I can't get to it, crazy week already - good news is I should have more time to devote to dev on these plugins again "soon"

**Comment by rgerhards** [comment]
no problem with bumpnig forward :-)

2016-07-11 19:13 GMT+02:00 taotetek <notifications@github.com>:

**Comment by rgerhards** [comment]
@Whissi I have change the requirement to 4, but I now see failures on a buildbot slave where we only provide 3.0.2, with which omczmq built fine. This is in contrast to your (old!) initial posting. If you don't object, I'll update to 3.0.2, as I would assume "something" has changed in the mean time which makes this work.
