### ISSUE TITLE
action 'action 19' resumed (module 'builtin:omfwd') bug

### ISSUE THREAD

**Issue by merteminoglu** [rsyslog/rsyslog#879]
Hi,

I am trying to install rsyslog to 3 Debian 8.2 stable server and they supposed communicate via SSL. So i can send logs without SSL but when i trying to send via SSL, i see problem in my logs. Logs;

Mar  8 10:19:56 debian rsyslogd0: action 'action 19' resumed (module 'builtin:omfwd') [try http://www.rsyslog.com/e/0 ]
Mar  8 10:19:56 debian rsyslogd-2359: action 'action 19' resumed (module 'builtin:omfwd') [try http://www.rsyslog.com/e/2359 ]

I listened related port and there is no problem in SSL connection. 3 way handshake performed and log was send to related server. Test log  can not reach. I saw error log instead of message.

**Comment by davidelang** [comment]
try starting rsyslog in debug mode to see if there are any errors from the SSL handshake (you won't be able to tell from sniffing the connection unless you are decoding the SSL)

**Comment by rgerhards** [comment]
error messages by now are much better
