### ISSUE TITLE
Shutdown issue in input plugins

### ISSUE THREAD

**Issue by theinric** [rsyslog/rsyslog#882]
There's a race condition affecting input plugins that can prevent them from shutting down cleanly.
Specifically, the code in threads.c doesn't call the afterRun() API if the module's thread terminates (thrdStarter() finishes) before the main thread tries to terminate the module explicitly (via thrdTerminate()).
This was brought up by  Jan Stancek in https://bugzilla.redhat.com/show_bug.cgi?id=1216957#c14

Issues caused by this bug were observed in imjournal but, in theory, this could cause issues for other input modules. imfile persists file metadata in afterRun(), imtcp does cleanup there as well.

I'm not sure whether this is a bug in implementation or in the API. It's not clear how afterRun() should be used.
Comment from module-template.h regarding afterRun():
> This function is called after an input module has been run and its thread has been terminated. It shall do any necessary cleanup.

What stage of initialization the module has to reach to be considered "having been run"? imfile allocates data in willRun() which are then freed in afterRun(), which seems inconsistent. Which stages of initialization afterRun() corresponds to? Some modules seem to assume it is always executed.

**Comment by rgerhards** [comment]
Just some quick feedback, would need to dig deeper for more: I think we did not envision that an input module might terminate before being told to do so. I think this can happen in some other modules as well if they run into error conditions. And is it looks, this can happen due to a race on the bTerminate flag. Need to think what the actual problem is, but I would say cleanup should also work in the condition you describe. I hope this quick and incomplete feedback is a bit useful.

**Comment by theinric** [comment]
> And is it looks, this can happen due to a race on the bTerminate flag.

If I understand correctly, this doesn't seem to be so. The call chain is this:

main()
  deinitAll()
    glbl.SetGlobalInputTermination()
      [bTerminateInputs = 1]
    thrdTerminateAll()
      ...
        thrdTerminate()

And it makes sense as some of the threads need to finish processing before terminating, thus setting the flag first looks correct. OTOH this can also lead to terminating "too early".

**Comment by rgerhards** [comment]
I think I agree, except that it may be a desired effect (albeit not correctly handled) to terminate early. When we enter shutdown, we try to shut down inputs as quickly as possible, as otherwise they may hang during enqueuing and other operations.

**Comment by theinric** [comment]
> I think I agree, except that it may be a desired effect (albeit not correctly handled) to terminate early.

Right.
