### ISSUE TITLE
Omrelp still loses messages (even in 8.17.0)

### ISSUE THREAD

**Issue by ondrap** [rsyslog/rsyslog#884]
I cannot reopen an issue, so creating a new one - just tested with 8.17.0 (RPM for rhel7) and the issue #841 still persists. Omrelp loses 1 message every time it tries to connect and deliver.

**Comment by davidelang** [comment]
There is an e-mail thread on this

[rsyslog] retry if output module returns RS_RET_SUSPENDED

from a message from Kane Kim on Mar 28

I'm seeing the same behavior with omrelp module. I've configured omrelp to
non-routable ip address:
module(load="omrelp")
local0.* action(type="omrelp"
    target="10.0.0.1"
    port="2514"
    name="debug_relp"
    queue.filename="relp_queue"
    queue.maxdiskspace="1G"
    queue.saveonshutdown="on"
    queue.spoolDirectory="/var/spool/rsyslog"
    queue.type="Disk"
)
Then I try to log a line:
[root@314959ac8cb0 prism]# logger -p local0.info test
[root@314959ac8cb0 prism]# ls /var/spool/rsyslog/
relp_queue.00000001
# I shutdown rsyslog at this point
[root@314959ac8cb0 prism]# ls /var/spool/rsyslog/
# after shutdown queue is deleted and message is lost
[root@314959ac8cb0 prism]#

http://lists.adiscon.net/pipermail/rsyslog/2016-March/042379.html

**Comment by rgerhards** [comment]
What David said is now being tracked in https://github.com/rsyslog/rsyslog/issues/974

**Comment by rgerhards** [comment]
Should be fixed in 8.37
