### ISSUE TITLE
omelasticsearch : usehttps with self-signed certificate

### ISSUE THREAD

**Issue by Xat59** [rsyslog/rsyslog#89]
Hi team,

related to my comments in this closed issue : https://github.com/rsyslog/rsyslog/pull/44 , I have to use the omelasticsearch with usehttps="on" with a self-signed certificate.

I'm able to push datas in command line using curl with --insecure option.

Would it be possible to add this feature in omelasticsearch please ?

Thanks a lot !
Regards.

**Comment by rgerhards** [comment]
Better (very) late than never... I finally added the ```allowUnsignedCerts="true"``` option. If there is still interest, please test and let me know the outcome. Otherwise, I'll merge as experimental and wait for others to report. Thanks!

**Comment by Xat59** [comment]
Thank a lot team . I will use it really soon :)

**Comment by rgerhards** [comment]
I merge the PR because of the new release (and as I have not heard anything bad so far).

@Xat59 if you get results (either good or bad), please still post them! :-)
