### ISSUE TITLE
EscapeControlCharactersOnReceive and Escape8BitCharactersOnReceive turned off but still seeing escaping in logs

### ISSUE THREAD

**Issue by dbendelman** [rsyslog/rsyslog#902]
B"H

I'm receiving logs on a Unix socket, sending them to a file and also forwarding them to a remote syslog. Despite turning off `EscapeControlCharactersOnReceive` and `Escape8BitCharactersOnReceive`, I'm still seeing escaped characters in both the output file and on the forwarding host.

I'm using the built-in `FileFormat` and `ForwardFormat` templates, which as far as I can tell from [the docs](http://www.rsyslog.com/doc/v8-stable/configuration/templates.html#standard-template-for-writing-to-files) don't include the `escape-cc` property option.

Running v8.16.0 from the `ppa:adiscon/v8-stable` Ubuntu PPA on Ubuntu 14.04. My config follows:

_/etc/rsyslog.conf_

```
$EscapeControlCharactersOnReceive off
$Escape8BitCharactersOnReceive off
$Umask 0022
$WorkDirectory /var/spool/rsyslog

$IncludeConfig /etc/rsyslog.d/*.conf
```

_/etc/rsyslog.d/main.conf_

```
module(load="imuxsock")
input(type="imuxsock" Socket="/var/run/syslog/syslog.sock")

action(
    type="omfile"
    template="RSYSLOG_FileFormat"
    file="/var/log/syslog-main.log"
)
```

_/etc/rsyslog.d/forwarding.conf_

```
action(
    type="omfwd"
    template="RSYSLOG_ForwardFormat"
    target="syslog.mydomain.com"
    port="10514"
    protocol="tcp"
    queue.filename="forwarding"
    queue.size="1000000"
    queue.type="LinkedList"
    queue.saveonshutdown="on"
    queue.maxdiskspace="5g"
    queue.dequeueslowdown="1000"
    action.resumeretrycount="-1"
)
```

**Comment by davidelang** [comment]
do you have any parsers defined? some parsers force escaping of control characters. I know that when I did the first cisco and aix fixup parsers, I took the easy way out and set the flag to require escaping rather than writing the code to deal with both escaped and non-escaped versions of things.

**Comment by rgerhards** [comment]
I think a sample of the messages would be good.
Am 20.04.2016 19:11 schrieb "davidelang" <notifications@github.com>:

**Comment by dbendelman** [comment]
@davidelang no parsers are defined. The config I posted above is all the config I'm setting up rsyslog with.

@rgerhards here's a sample "bad" log (sensitive bits redacted) that got sent to Logstash escaped:

```
<142>2016-05-03T20:16:44.990175+00:00 app5 MyApplicationName: 172.34.53.100 - - [03/May/2016:20:16:44 +0000] \"GET /file.js?param=1 HTTP/1.1\" 200 8079 \"https://github.com/rsyslog/rsyslog\" \"Mozilla/5.0 (iPhone; CPU iPhone OS 9_3_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Mobile/13E238 [FBAN/FBIOS;FBAV/54.0.0.42.135;FBBV/28674375;FBRV/0;FBDV/iPhone6,2;FBMD/iPhone;FBSN/iPhone OS;FBSV/9.3.1;FBSS/2;FBCR/OrangeEspa\xF1a;FBID/phone;FBLC/en_GB;FBOP/5]\"
```

As you can see, the accent on the `n` in `OrangeEspana` was escaped.

Here's another sample "good" log that flowed through the same app->rsyslog->logstash pipeline a few minutes later. This time, there's no escaping:

```
<142>2016-05-03T20:26:30.486121+00:00 app4 MyApplicationName: 172.34.53.110 - - [03/May/2016:20:26:30 +0000] "GET /file.js?param=1 HTTP/1.1" 200 8065 "https://github.com/rsyslog/rsyslog" "Mozilla/5.0 (iPhone; CPU iPhone OS 9_3_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Mobile/13E238 [FBAN/FBIOS;FBAV/54.0.0.42.135;FBBV/28674375;FBRV/0;FBDV/iPhone7,2;FBMD/iPhone;FBSN/iPhone OS;FBSV/9.3.1;FBSS/2;FBCR/Verizon;FBID/phone;FBLC/en_US;FBOP/5]"
```

**Comment by davidelang** [comment]
Please log with the format RSYSLOG_DebufFormat so we can see exactly what was received and what is in each variable.

At this point it's not clear if escaping is happening as the message is being received, or as it is being sent

When rsyslog escapes a message as it's being received, it does so as #nnn (octal value of byte), and so I would expect the multibyte unicode character \xF1a to become #017#032

You may also want to look at the same log on the local file and on the remote side, it could be that logstash is doing the escaping as it receives it.

**Comment by rgerhards** [comment]
Sorry, I don't see the 8 bit char in the second sample. Which is it?

Sent from phone, thus brief.
Am 03.05.2016 22:40 schrieb "dbendelman" <notifications@github.com>:
