### ISSUE TITLE
rsyslogd writing to shared storage file fails after almost concurrent reboot of storage servers

### ISSUE THREAD

**Issue by sakellar** [rsyslog/rsyslog#908]
Hi,
 
1)      I have a setup where rsyslogd writes to shared storage file ( shared storage file which is provided by glusterfs with 2 servers ).
2)      I reboot glusterfs server 1 and then in less than a minute I reboot glusterfs server 2.
3)      Rsyslogd gets stack in the state below while 2 glusterfs servers seem to recover after their almost concurrent reboot.
 
Receive the following error from strace command of rsyslogd
strace -f -ewrite -f -p <rsyslog pid>
Process 17463 attached with 8 threads
[pid 4711] write(10, "Mar 8 15:27:05.592037 warning L"..., 92) = 92
[pid 4711] write(10, "Mar 8 15:27:05.633467 warning L"..., 92) = 92
[pid 4711] write(10, "Mar 8 15:27:05.669069 warning L"..., 92) = 92
[pid 4711] write(7, "Mar 8 15:27:11.077982 err LEI-0"..., 103) = 103
[pid 4711] write(10, "Mar 8 15:27:11.077982 err LEI-0"..., 103) = 103
[pid 4711] write(7, "Mar 8 15:27:11.078299 err LEI-0"..., 103) = -1 ENOTCONN (Transport endpoint is not connected)
[pid 4711] write(10, "Mar 8 15:27:11.078299 err LEI-0"..., 103) = -1 ENOTCONN (Transport endpoint is not connected)
 
Do you have any idea why this issue might happen ?
 
System versions in use :
glusterfs 3.6.9
rsyslogd 8.15.0

**Comment by panath** [comment]
Perhaps there is an issue in runtime/stream.c, in doWriteCall function, 
It does not have handling for error codes (ABORT_FINALIZE(RS_RET_IO_ERROR) does not do anything). 
At least it does not reopen the files, only in tty case it will close/open file.

**Comment by davidelang** [comment]
if you think about the 'normal' case where you are writing to local files, there aren't that many errors that are recoverable at this point. As you move to remote storage, things get more complicated, so I've tagged this as an enhancement request to add additional error handling for these cases.

The fun thing here is going to be testing it. Can you think of any way to simulate the problem in a test?

As always, patches welcome. It's probably going to be far easier for someone who can duplicate the problem to develop/test patches to fix it than someone who can't duplicate it and is just trying to 'go by the book' and cover all possible cases.

**Comment by hese10** [comment]
Here is patch attempt.
[rsyslog.diff.txt](https://github.com/rsyslog/rsyslog/files/452183/rsyslog.diff.txt)
