### ISSUE TITLE
Keepalive parameter handling broken in omfwd

### ISSUE THREAD

**Issue by quixoten** [rsyslog/rsyslog#916]
rsyslog is ignoring keepalive parameters: interval, probes, and time.

I believe this is due to inconsistent naming in the following places:

- https://github.com/rsyslog/rsyslog/blob/07a074dd88afb1224e62eee4e000c66ce4b9ac12/tools/omfwd.c#L166-L169
- https://github.com/rsyslog/rsyslog/blob/07a074dd88afb1224e62eee4e000c66ce4b9ac12/tools/omfwd.c#L1024-L1030
- https://github.com/rsyslog/rsyslog/blob/07a074dd88afb1224e62eee4e000c66ce4b9ac12/tools/omfwd.c#L1376-L1379

**Comment by rgerhards** [comment]
Thanks for reporting. The second one is in error:

https://github.com/rsyslog/rsyslog/blob/07a074dd88afb1224e62eee4e000c66ce4b9ac12/tools/omfwd.c#L1024-L1030

The third one is legacy variables, they have different names. A work-around is to use legacy syntax, which works (but is clumsy).
