### ISSUE TITLE
Failing test git master: privdropuser.sh

### ISSUE THREAD

**Issue by Whissi** [rsyslog/rsyslog#927]
```
rsyslogd: ID for user '' could not be found or error [v8.18.0.master try http://www.rsyslog.com/e/3003 ]
rsyslogd started with pid  80255
imdiag[13500]: mainqueue empty
message indicating drop to gid 250 is missing:
 [origin software="rsyslogd" swVersion="8.18.0.master" x-pid="80255" x-info="http://www.rsyslog.com"] start
ID for user '' could not be found or error [v8.18.0.master try http://www.rsyslog.com/e/3003 ]
 [origin software="rsyslogd" swVersion="8.18.0.master" x-pid="80255" x-info="http://www.rsyslog.com"] exiting on signal 15.
FAIL privdropuser.sh (exit status: 1)
```
```
# id 250
uid=250(portage) gid=250(portage) groups=250(portage)
```

**Comment by rgerhards** [comment]
Could you have a look at the shell script if there is something non-portable for your platform?

**Comment by Whissi** [comment]
Interesting, thought it could be a permission problem, because the user running the test suite was already limited. But when running as root, all 4 privdrop tests are failing. Yes, I'll look into it.

**Comment by rgerhards** [comment]
Its"dropping " to the same user to avoid permission issues.

Sent from phone, thus brief.
Am 30.03.2016 19:03 schrieb "Thomas D." <notifications@github.com>:

**Comment by Whissi** [comment]
OK. The problem is that the checks are relying on `$USER` variable which isn't guaranteed to exist.
We should use `$UID` instead or maybe even better `$EUID`.

But because of the problems with the other tests (when running tests as root these tests cannot work) I want to prepare the following changes:

- Create *privs.common.sh* like I did for the timestamp tests
This script will check/validate ID

- The user should have the possibility to specify a user to use in this test.

- To keep it running without user interaction I am thinking about the following logic:
  1. If the user has set an ID we should use the user's value (after validation)
  2. If the user didn't specify an ID, try to use "rsyslog" first, "syslog" second, "daemon" third and finally current `$EUID`

- If we don't end with a valid UID we can work with, skip the tests


What do you think? Should I prepare a PR?

**Comment by Whissi** [comment]
Mh, we can only try to use different users when running as *root*. Normal users don't have the privileges to run as different user. So if running as non root, we can only use `$EUID`... however does it make sense to test in that case because we are not really dropping privs...

**Comment by rgerhards** [comment]
yeah it makes sense, as the process as such is tested. These test caught sone real errors. It s not the whole thing, of course, but far better than nothing.
