### ISSUE TITLE
Regarding multi-line messages with imfile - what happens to lines before the first matching regex?

### ISSUE THREAD

**Issue by portante** [rsyslog/rsyslog#960]
Hi folks, I have been reviewing the `stream.c` module as used by `imfile` and ran across a condition in `strmReadMultiline`.  Please forgive me if I have missed something simple here.

At [line 874 of stream.c](https://github.com/rsyslog/rsyslog/blob/1348225727812e713587ea47ac4a09bbaee7d20c/runtime/stream.c#L874), where we have found that the current line just read from the file does not match the regular expression, there is a check for an existing previous message segment (`prevMsgSegment`).  If there is one, the current line is added to it.

Is it possible that the beginning of a file has `N` lines which do not match the regular expression?  If that happens, then it appears that all that data is dropped on the floor.  Is that expected?

**Comment by hakman** [comment]
I think I made this change some time ago and considered this acceptable.
The message will fail anyway later in mmnormalize.
https://github.com/rsyslog/rsyslog/commit/c651a351434e6dee8faad185309c9b38df0d2b73

**Comment by davidelang** [comment]
conceptually, you may have a partial message at the beginning of what rsyslog reads in. that data should still be read and a message created, even if it's corrupt.

**Comment by rgerhards** [comment]
We now (8.31 at least) have a timeout feature, this will deliver "incomplete" messages after the timeout. Guess that solves the question.
