### ISSUE TITLE
something wrong in rsyslog_8.18 decode!!

### ISSUE THREAD

**Issue by yubingzhe727** [rsyslog/rsyslog#989]
when we used rsyslog8.18 parse the log ,the result look like this: 

...
Code=-1001 \u00E7�\u0091\u00E7�\u009c\u00E4�\u008d\u00E7�\u0099\u00E5\u008a\u009b\u00Ef�\u008c\u00E7�\u008d\u00E5\u0090\u008e\u00E5\u0086\u008d\u00E8�\u0095\u00E8�\u0095\u00E5\u0090� UserInfo
 ...

but when we used rsyslog8.11 parse the log,the result look like this:

....
"error":"\u4f60\u5411\u964c\u751f\u4eba\u53d1\u9001\u4e86\u592a\u591a\u6d88\u606f\uff0c\u660e\u5929\u518d\u8bd5\u5427
...

I think something wrong in unicode decode...

**Comment by davidelang** [comment]
On Mon, 25 Apr 2016, yubingzhe727 wrote:

> when we used rsyslog8.18 parse the log ,the result look like this:
>
> ...
> Code=-1001 \u00E7???\u0091\u00E7???\u009c\u00E4???\u008d\u00E7???\u0099\u00E5\u008a\u009b\u00Ef???\u008c\u00E7???\u008d\u00E5\u0090\u008e\u00E5\u0086\u008d\u00E8???\u0095\u00E8???\u0095\u00E5\u0090??? UserInfo
> ...
>
> but when we used rsyslog8.11 parse the log,the result look like this:
>
> ....
> "error":"\u4f60\u5411\u964c\u751f\u4eba\u53d1\u9001\u4e86\u592a\u591a\u6d88\u606f\uff0c\u660e\u5929\u518d\u8bd5\u5427
> ...
>
> I think something wrong in unicode decode...

it can happen, but it would help to know what the original log looked like and 
what the config you are using to parse the log is.

David Lang
